### ISSUE TITLE
thread_cattr_accessor behaves different from cattr_access for subclasses, even when not using threads.

### ISSUE THREAD

**Issue by mshiltonj** [rails/rails#43228] opened 2021-09-16 15:15 UTC
### Steps to reproduce
thread_cattr_accessor behaves differently from cattr_access for subclasses, even when not using threads.

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "active_support/core_ext/module"
require "minitest/autorun"


class Foo
  cattr_accessor :foo #=> CATTR
  self.foo = "bar"
end

class Bar < Foo
end

class TFoo
  thread_cattr_accessor :foo #=> THREAD_CATTR
  self.foo = "bar"
end

class TBar < TFoo
end

class BugTest < Minitest::Test
  def test_stuff
    assert_equal Foo.foo, 'bar'
    assert_equal Bar.foo, 'bar'
    assert_equal TFoo.foo, 'bar'
    assert_equal TBar.foo, 'bar'
  end
end
```

### Expected behavior
Without using threads (or within a single thread) I expect thread_attr_accessor to work the same at cattr_accessor.

### Actual behavior
When using subclasses, the subclass does not receive the value defined in the superclass for the class attribute

### System configuration
**Rails version**: Tested on 5.2. 6.1 and 7.0

**Ruby version**: 2.7.3

**Comment by ghiculescu** [comment] 2021-09-16 16:54
Hmmm, this seems to be expected: https://github.com/rails/rails/blob/f58f8e175e8674224c33a4f37544dae719f3aaf1/activesupport/test/core_ext/module/attribute_accessor_per_thread_test.rb#L136

See also https://github.com/rails/rails/pull/25681, and the docs https://api.rubyonrails.org/classes/Module.html#method-i-thread_mattr_accessor

**Comment by ghiculescu** [comment] 2021-09-16 16:56
As to them being inconsistent, that's a reasonable point worth discussing. We try to use https://discuss.rubyonrails.org/c/rubyonrails-core/5 for feature / API discussion. Would you like to make a thread there?

I'm going to close this as it appears to be behaving as intended.

**Closed by ghiculescu** 2021-09-16 16:56 UTC

**Comment by mshiltonj** [comment] 2021-09-16 17:33
I think #25681 the the opposite condition. My case is the subclass does *not* have a set value, but also does *not* use the value of the superclass.  

That line in the test sets a baseline of divergent behavior from cattr_accessor, so thread_cattr_access is not truly a thread-safe replacement for cattr_accessor.  With cattr_accessor, the the subclass gets the superclass value (as a default value in my case) until the subclass sets it's own value for the field.

**Comment by mshiltonj** [comment] 2021-09-16 17:34
I will create a topic over on that discourse. Thanks.
