### ISSUE TITLE
PostgreSQL, Serial and/or primary key with trigger does not get populated in model on insert, Active Record 7.1

### ISSUE THREAD

**Issue by JesseChavez** [rails/rails#52485] opened 2024-08-01 20:49 UTC
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  # gem "rails", "~> 6.1.7"
  # gem "rails", "~> 7.0.8"
  gem "rails", "~> 7.1.3"
  # gem "rails", "7.2.0.beta3"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  host: "localhost",
  database: "rails_test",
  username: "dev",
  password: "password"
)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :trigger_gen_serials, force: true, id: false do |t|
    t.integer :sid
    t.string  :value
  end

  execute(
    <<-SQL
    CREATE OR REPLACE FUNCTION populate_column()
    RETURNS TRIGGER AS $$
    DECLARE
    max_value INTEGER;
    BEGIN
    SELECT MAX(sid) INTO max_value FROM trigger_gen_serials;
    NEW.sid = COALESCE(max_value, 0) + 1;
    RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER before_insert_trigger_gen
    BEFORE INSERT ON trigger_gen_serials
    FOR EACH ROW
    EXECUTE FUNCTION populate_column();
    SQL
  )

  create_table :trigger_pop_serials, force: true, id: false do |t|
    t.integer :id, null: false
    t.string  :value
  end

  execute(
    <<-SQL
    CREATE OR REPLACE FUNCTION populate_id_column()
    RETURNS TRIGGER AS $$
    DECLARE
    max_value INTEGER;
    BEGIN
    SELECT MAX(id) INTO max_value FROM trigger_pop_serials;
    NEW.id = COALESCE(max_value, 0) + 1;
    RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER before_insert_trigger_pop
    BEFORE INSERT ON trigger_pop_serials
    FOR EACH ROW
    EXECUTE FUNCTION populate_id_column();
    SQL
  )

end

class TriggerGenSerial < ActiveRecord::Base
  self.primary_key = :sid
end

class TriggerPopSerial < ActiveRecord::Base
  self.primary_key = :id
end

class BugTest < Minitest::Test
  def test_serial_sid_present
    sn = TriggerGenSerial.create!(value: '111')

    # Fails primary key and/or id is not present
    refute_nil sn.sid
  end

  def test_serial_sid_reload
    sn = TriggerGenSerial.create!(value: '222')

    # Fails since primary key is not present
    assert sn.reload
  end

  def test_serial_id_present
    sn = TriggerPopSerial.create!(value: '11')

    # Fails primary key and/or id is not present
    refute_nil sn.id
  end

  def test_serial_id_reload
    sn = TriggerPopSerial.create!(value: '22')

    # Fails since primary key is not present
    assert sn.reload
  end
end
```

### Expected behavior
The primary key should be populated whether is `id` or a custom name such as `sid`

There is a test for this scenario however it's not catching this issue.

### System configuration
**Rails version**:
Rails 7.1

**Ruby version**:
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]

**Postgres version**:
PostgreSQL 11.22 on x86_64-pc-linux-gnu

**Comment by JesseChavez** [comment] 2024-08-01 21:02
Here is a snippet  of the test results

```
# Running:

D, [2024-08-02T06:41:02.015920 #621347] DEBUG -- :   TRANSACTION (0.4ms)  BEGIN
D, [2024-08-02T06:41:02.016561 #621347] DEBUG -- :   TriggerPopSerial Create (1.0ms)  INSERT INTO "trigger_pop_serials" ("value") VALUES ($1)  [["value", "11"]]
D, [2024-08-02T06:41:02.017315 #621347] DEBUG -- :   TRANSACTION (0.6ms)  COMMIT
F

Failure:
BugTest#test_serial_id_present [serial_with_trigger.rb:108]:
Expected nil to not be nil.


bin/rails test serial_with_trigger.rb:104

D, [2024-08-02T06:41:02.018160 #621347] DEBUG -- :   TRANSACTION (0.3ms)  BEGIN
D, [2024-08-02T06:41:02.018438 #621347] DEBUG -- :   TriggerPopSerial Create (0.6ms)  INSERT INTO "trigger_pop_serials" ("value") VALUES ($1)  [["value", "22"]]
D, [2024-08-02T06:41:02.019063 #621347] DEBUG -- :   TRANSACTION (0.6ms)  COMMIT
D, [2024-08-02T06:41:02.022326 #621347] DEBUG -- :   TriggerPopSerial Load (0.1ms)  SELECT "trigger_pop_serials".* FROM "trigger_pop_serials" WHERE "trigger_pop_serials"."id" IS NULL LIMIT $1  [["LIMIT", 1]]
E

Error:
BugTest#test_serial_id_reload:
ActiveRecord::RecordNotFound: Couldn't find TriggerPopSerial with [WHERE "trigger_pop_serials"."id" IS NULL]
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation/finder_methods.rb:413:in `raise_record_not_found_exception!'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation/finder_methods.rb:127:in `take!'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation/finder_methods.rb:110:in `find_by!'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1160:in `_find_record'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1075:in `block in reload'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation.rb:929:in `_scoping'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation.rb:467:in `scoping'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/scoping/default.rb:51:in `unscoped'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1075:in `reload'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/attribute_methods/dirty.rb:64:in `reload'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/autosave_association.rb:237:in `reload'
    serial_with_trigger.rb:115:in `test_serial_id_reload'


bin/rails test serial_with_trigger.rb:111

D, [2024-08-02T06:41:02.024569 #621347] DEBUG -- :   TRANSACTION (0.2ms)  BEGIN
D, [2024-08-02T06:41:02.024991 #621347] DEBUG -- :   TriggerGenSerial Create (0.6ms)  INSERT INTO "trigger_gen_serials" ("value") VALUES ($1)  [["value", "222"]]
D, [2024-08-02T06:41:02.025502 #621347] DEBUG -- :   TRANSACTION (0.5ms)  COMMIT
D, [2024-08-02T06:41:02.026346 #621347] DEBUG -- :   TriggerGenSerial Load (0.2ms)  SELECT "trigger_gen_serials".* FROM "trigger_gen_serials" WHERE "trigger_gen_serials"."sid" IS NULL LIMIT $1  [["LIMIT", 1]]
E

Error:
BugTest#test_serial_sid_reload:
ActiveRecord::RecordNotFound: Couldn't find TriggerGenSerial with [WHERE "trigger_gen_serials"."sid" IS NULL]
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation/finder_methods.rb:413:in `raise_record_not_found_exception!'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation/finder_methods.rb:127:in `take!'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation/finder_methods.rb:110:in `find_by!'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1160:in `_find_record'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1075:in `block in reload'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation.rb:929:in `_scoping'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/relation.rb:467:in `scoping'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/scoping/default.rb:51:in `unscoped'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1075:in `reload'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/attribute_methods/dirty.rb:64:in `reload'
    /home/jessec/.gem/ruby/3.1.4/gems/activerecord-7.1.3.4/lib/active_record/autosave_association.rb:237:in `reload'
    serial_with_trigger.rb:101:in `test_serial_sid_reload'


bin/rails test serial_with_trigger.rb:97

D, [2024-08-02T06:41:02.026859 #621347] DEBUG -- :   TRANSACTION (0.2ms)  BEGIN
D, [2024-08-02T06:41:02.027042 #621347] DEBUG -- :   TriggerGenSerial Create (0.3ms)  INSERT INTO "trigger_gen_serials" ("value") VALUES ($1)  [["value", "111"]]
D, [2024-08-02T06:41:02.027483 #621347] DEBUG -- :   TRANSACTION (0.4ms)  COMMIT
F

Failure:
BugTest#test_serial_sid_present [serial_with_trigger.rb:94]:
Expected nil to not be nil.


```

**Comment by JesseChavez** [comment] 2024-08-02 01:14
This issue was found when fixing some for the JRuby adapter

https://github.com/jruby/activerecord-jdbc-adapter/issues/1154

**Comment by ruyrocha** [comment] 2024-08-10 02:50
@JesseChavez I cannot reproduce the error using the `7-1-stable` branch, e.g;

```ruby
gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails", branch: "7-1-stable"
  gem "pg"
end
```

And output:

```rspec
D, [2024-08-09T23:48:46.733366 #360651] DEBUG -- :   TRANSACTION (0.1ms)  BEGIN
D, [2024-08-09T23:48:46.733669 #360651] DEBUG -- :   TriggerPopSerial Create (0.4ms)  INSERT INTO "trigger_pop_serials" ("value") VALUES ($1) RETURNING "id"  [["value", "22"]]
D, [2024-08-09T23:48:46.733982 #360651] DEBUG -- :   TRANSACTION (0.2ms)  COMMIT
D, [2024-08-09T23:48:46.737773 #360651] DEBUG -- :   TriggerPopSerial Load (0.1ms)  SELECT "trigger_pop_serials".* FROM "trigger_pop_serials" WHERE "trigger_pop_serials"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
.D, [2024-08-09T23:48:46.739174 #360651] DEBUG -- :   TRANSACTION (0.0ms)  BEGIN
D, [2024-08-09T23:48:46.739470 #360651] DEBUG -- :   TriggerGenSerial Create (0.4ms)  INSERT INTO "trigger_gen_serials" ("value") VALUES ($1) RETURNING "sid"  [["value", "111"]]
D, [2024-08-09T23:48:46.739731 #360651] DEBUG -- :   TRANSACTION (0.2ms)  COMMIT
.D, [2024-08-09T23:48:46.739949 #360651] DEBUG -- :   TRANSACTION (0.0ms)  BEGIN
D, [2024-08-09T23:48:46.740039 #360651] DEBUG -- :   TriggerPopSerial Create (0.1ms)  INSERT INTO "trigger_pop_serials" ("value") VALUES ($1) RETURNING "id"  [["value", "11"]]
D, [2024-08-09T23:48:46.740201 #360651] DEBUG -- :   TRANSACTION (0.1ms)  COMMIT
.D, [2024-08-09T23:48:46.740355 #360651] DEBUG -- :   TRANSACTION (0.0ms)  BEGIN
D, [2024-08-09T23:48:46.740436 #360651] DEBUG -- :   TriggerGenSerial Create (0.1ms)  INSERT INTO "trigger_gen_serials" ("value") VALUES ($1) RETURNING "sid"  [["value", "222"]]
D, [2024-08-09T23:48:46.740598 #360651] DEBUG -- :   TRANSACTION (0.1ms)  COMMIT
D, [2024-08-09T23:48:46.740917 #360651] DEBUG -- :   TriggerGenSerial Load (0.0ms)  SELECT "trigger_gen_serials".* FROM "trigger_gen_serials" WHERE "trigger_gen_serials"."sid" = $1 LIMIT $2  [["sid", 2], ["LIMIT", 1]]
.

Finished in 0.011703s, 341.7831 runs/s, 341.7831 assertions/s.
4 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by JesseChavez** [comment] 2024-08-10 04:27
Hi @ruyrocha 

Yes, when using 

```
gem "rails", github: "rails/rails", branch: "7-1-stable"
```

works fine however using the gem it does not work

```
gem "rails", "~> 7.1.3"
```

it's a bit tricky

**Comment by ruyrocha** [comment] 2024-08-10 06:42
@JesseChavez give it a try:

```ruby
gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "~> 7.1"
  # gem "rails", "7.1.3.4"
  # gem "rails", path: "~/GitHub/rails/"
  # gem "rails", github: "rails/rails", branch: "7-1-stable"
  gem "pg"
end
```

It will work and it doesn't make any sense. 

I ran the debugging script inside a fresh container just to be sure.

**Comment by baarde** [comment] 2024-10-24 09:46
I think this has been solved by #50783 / version 7.1.4.

**Comment by skipkayhil** [comment] 2024-10-30 05:08
Confirmed that the script passes on 7.1.4+, so I'm going to close this

**Closed by skipkayhil** 2024-10-30 05:08 UTC

**Comment by JesseChavez** [comment] 2024-11-12 20:58
yes, the issue was fixed by that change

Thanks @baarde
