### ISSUE TITLE
append_before_action is run before before_action

### ISSUE THREAD

**Issue by collimarco** [rails/rails#31259] opened 2017-11-28 15:39 UTC
### Example code to reproduce the issue

```
class ApplicationController < ActionController::Base
  append_before_action :set_time_zone

  private

  def set_time_zone
    # current_user is always nil here...
    Time.zone = current_user.time_zone if current_user
  end
end
```

```
class ExampleController < ApplicationController
  before_action :authenticate!
end
```

### Expected behavior

In the above code I would expect `set_time_zone` to be executed after `authenticate!`.

### Actual behavior

`set_time_zone` is executed before `authenticate!`.

### System configuration

Rails 4.2.10
Ruby 2.2.2

**Comment by pixeltrix** [comment] 2017-11-28 16:25
@collimarco `append_before_action` and `before_action` are the same method so it's no different to:

``` ruby
class ApplicationController < ActionController::Base
  before_action :set_time_zone

  private

  def set_time_zone
    # current_user is always nil here...
    Time.zone = current_user.time_zone if current_user
  end
end 

class ExampleController < ApplicationController
  before_action :authenticate!
end
```

Obviously the `ApplicationController` class is evaluated before defining `ExampleController` so `authenticate!` is executed after `set_time_zone`. Perhaps you can use `prepend_before_action :authenticate!` in your controller subclass?

Closing since this is how Rails has behaved for a _long_ time

**Closed by pixeltrix** 2017-11-28 16:25 UTC

**Comment by bananatron** [comment] 2019-08-08 10:14
Maybe I'm missing something, but having a method named `append_before_action` sets the expectation that it would behave in a way which is consisted with `prepend_before_action`.

In the case where you put `prepend_before_action` in your subclass, it will run before the `before_action` on the parent class (implying that ALL actions in that cycle are resolved before the next cycle begins), and yet the reverse seems not to be true?

If it's true that it's a duplicate of `before_action`, it seems strange that it [exists at all](https://github.com/rails/rails/blob/511d1abc8ad523aa3592e30b4ecf4dac92a2a352/actionpack/lib/abstract_controller/callbacks.rb#L9-L20).

**Comment by bishosilwal** [comment] 2023-07-04 18:32
If anyone has the same issue I got a workaround like this:

`app/application_controller.rb`

```ruby
class ApplicationController < ActionController::Base
  def initialize
    super
    self.class_eval do
      append_before_action :foo

      def foo
        # code
      end
    end
  end
end
```

Now with this, the foo callback is added at last in the child's callback chain and it seems working for me.
