### ISSUE TITLE
Performance regression in activerecord scoping

### ISSUE THREAD

**Issue by klgilbert** [rails/rails#20418] opened 2015-06-02 19:09 UTC
The Rails releases range from 3.20 to 4.2.1 and there's a decrease in performance seen throughout.

There's a regression from 4.1.10 to 4.2.0. There's an increase in total allocated objects per iteration that also occurs. At 4.2.0 iterations per second is at 27K. For allocated objects per iteration, it's 150 for 4.2.0.

The graphs seen below can be located at [rubybench.org](http://rubybench.org/rails/rails/releases?result_type=activerecord/postgres_scope "Rubybench.org").

![activerecord_scope](https://cloud.githubusercontent.com/assets/1337012/7922652/aeab96c2-087b-11e5-8aa2-416e128e967b.png)

![activerecord_scope_allocated_objects](https://cloud.githubusercontent.com/assets/1337012/7922828/c198a4f4-087c-11e5-844b-f3816074e169.png)

**Comment by sgrif** [comment] 2015-09-21 21:53
@klgilbert Do you have the code that demonstrates this regression? I do not see anything on RubyBench that shows this regression, and the current benchmarks for scopes do not have the same performance. http://rubybench.org/rails/rails/releases?result_type=activerecord/postgres_scope_where

**Comment by sgrif** [comment] 2015-09-21 21:54
Never mind, I see the difference. The benchmarks now are loading the records, whereas before they were not. I'm going to go ahead and close this, since as the difference between those graphs show, this is a microbenchmark that is trivialized, even in another micro benchmark.

**Closed by sgrif** 2015-09-21 21:54 UTC
Labels: activerecord
