### ISSUE TITLE
AR does not infer primary key in association for composite primary keys.

### ISSUE THREAD

**Issue by jarl-dk** [rails/rails#49622] opened 2023-10-13 13:25 UTC
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true, primary_key: %i[number] do |t|
    t.integer :number
    t.string :title
  end

  create_table :chapters, force: true, primary_key: %i[book_number number] do |t|
    t.integer :book_number
    t.integer :number
    t.string :title
  end

  create_table :sections, force: true, primary_key: %i[book_number chapter_number number] do |t|
    t.integer :book_number
    t.integer :chapter_number
    t.integer :number
    t.string :title
  end
end

class Book < ActiveRecord::Base
  has_many :chapters, foreign_key: :book_number, inverse_of: :book
  has_many :sections, foreign_key: %i[book_number chapter_number], inverse_of: :book
end

class Chapter < ActiveRecord::Base
  self.primary_key = %i[book_number number]

  belongs_to :book, foreign_key: :book_number, inverse_of: :chapters

  has_many :sections, foreign_key: %i[book_number chapter_number], inverse_of: :chapter
  # has_many :sections, primary_key: %i[book_number chapter_number], foreign_key: %i[book_number chapter_number], inverse_of: :chapter
  # has_many :sections, query_constraints: %i[book_number chapter_number], inverse_of: :chapter
end

class Section < ActiveRecord::Base
  self.primary_key = %i[book_number chapter_number number]
  belongs_to :book, foreign_key: :book_number, inverse_of: :sections

  belongs_to :chapter, foreign_key: %i[book_number chapter_number], inverse_of: :sections
  # belongs_to :chapter, primary_key: %i[book_number chapter_number], foreign_key: %i[book_number chapter_number], inverse_of: :sections
  # belongs_to :chapter, query_constraints: %i[book_number chapter_number], inverse_of: :sections
end

class BugTest < Minitest::Test
  def test_association_stuff
    book = Book.create!(number: 1, title: "First book")
    book.chapters << Chapter.create!(number: 1, title: "Chapter one") << Chapter.create!(book:, number: 2, title: "Chapter two")
    book.chapters.first.sections << Section.create!(number: 1, title: "Section one") << Section.create!(number: 2, title: "Section two")

    assert_equal 2, book.chapters.count
    assert_equal 2, Chapter.count
    assert_equal 2, book.chapters.first.sections.count
    assert_equal 2, Section.count
  end
end
```

### Expected behavior
I expected AR to automatically infer primary key from the `Chapter.primary_key` for the Chapter#sections association and the test to run green.

### Actual behavior
An error saying:
```shell
ActiveRecord::CompositePrimaryKeyMismatchError: Association Chapter#sections primary key ["book_number", "number"] doesn't match with foreign key [:book_number, :chapter_number]. Please specify query_constraints, or primary_key and foreign_key values.
```

### System configuration
**Rails version**: edge

**Ruby version**: 3.2.2

**Comment by rafaelfranca** [comment] 2023-10-13 13:38
Duplicate of #49135

**Closed by rafaelfranca** 2023-10-13 13:38 UTC

**Comment by nvasilevski** [comment] 2023-10-13 13:42
>Duplicate of https://github.com/rails/rails/issues/49135

It is but it's phrased a bit differently with a focus on the `primary_key` while the actual problem is in how `foreign_key:` being specified in the example. So perhaps Rails could be more explicit about not supporting `foreign_key` as an array, at least at the moment.

>I expected AR to automatically infer primary key from the Chapter.primary_key for the Chapter#sections association

It is capable of inferring it from `Chapter`, the issue here is that passing `foreign_key:` as an array is not supported and `query_constraints:` must be used instead. Understandably that it may not be the optimal API for some setups but this is an expected API

**Comment by rafaelfranca** [comment] 2023-10-13 13:53
> So perhaps Rails could be more explicit about not supporting `foreign_key` as an array, at least at the moment.

Yes. Let's do that.

**Comment by jarl-dk** [comment] 2023-10-13 14:09
Hm...
The following program
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true, primary_key: %i[number] do |t|
    t.integer :number
    t.string :title
  end

  create_table :chapters, force: true, primary_key: %i[book_number number] do |t|
    t.integer :book_number
    t.integer :number
    t.string :title
  end

  create_table :sections, force: true, primary_key: %i[book_number chapter_number number] do |t|
    t.integer :book_number
    t.integer :chapter_number
    t.integer :number
    t.string :title
  end
end

class Book < ActiveRecord::Base
  has_many :chapters, foreign_key: :book_number, inverse_of: :book
  has_many :sections, foreign_key: %i[book_number chapter_number], inverse_of: :book
end

class Chapter < ActiveRecord::Base
  self.primary_key = %i[book_number number]

  belongs_to :book, foreign_key: :book_number, inverse_of: :chapters

  # has_many :sections, foreign_key: %i[book_number chapter_number], inverse_of: :chapter
  has_many :sections, primary_key: %i[book_number chapter_number], foreign_key: %i[book_number chapter_number], inverse_of: :chapter
  # has_many :sections, query_constraints: %i[book_number chapter_number], inverse_of: :chapter
end

class Section < ActiveRecord::Base
  self.primary_key = %i[book_number chapter_number number]
  belongs_to :book, foreign_key: :book_number, inverse_of: :sections

  # belongs_to :chapter, foreign_key: %i[book_number chapter_number], inverse_of: :sections
  belongs_to :chapter, primary_key: %i[book_number chapter_number], foreign_key: %i[book_number chapter_number], inverse_of: :sections
  # belongs_to :chapter, query_constraints: %i[book_number chapter_number], inverse_of: :sections
end

class BugTest < Minitest::Test
  def test_association_stuff
    book = Book.create!(number: 1, title: "First book")
    book.chapters << Chapter.create!(number: 1, title: "Chapter one") << Chapter.create!(book:, number: 2, title: "Chapter two")
    book.chapters.first.sections << Section.create!(number: 1, title: "Section one") << Section.create!(number: 2, title: "Section two")

    assert_equal 2, book.chapters.count
    assert_equal 2, Chapter.count
    assert_equal 2, book.chapters.first.sections.count
    assert_equal 2, Section.count
  end
end
```

Gives me an error saying:
```shell
ActiveRecord::CompositePrimaryKeyMismatchError: Association Chapter#sections primary key ["book_number", "chapter_number"] doesn't match with foreign key [:book_number, :chapter_number]. Please specify query_constraints, or primary_key and foreign_key values.
```

i.e. **Please specify query_constraints, or primary_key and foreign_key values**. 

So do you mean that this error message is misleading? And should only be "Please specify query_constraints,"?

**Comment by nvasilevski** [comment] 2023-10-13 14:22
>So do you mean that this error message is misleading?

It is. There should be a different error message raised earlier that disallows setting `foreign_key:` to an array at least as long as it is not supported. 

>And should only be "Please specify query_constraints,"?

Yeah, something like "Passing `foreign_key:` as an array is not supported, please use `query_constraints:` 

The message you are currently seeing was supposed to serve a different purpose and it happened to be misleading because currently rails calls `to_s` on whatever is passed as the `foreign_key:` so now your association is configured to use a `[:book_number, :chapter_number].to_s` as a foreign key which is being treated as a single-column fk


I'll work on providing better error message for this situation

**Comment by jarl-dk** [comment] 2023-10-16 05:40
OK.

May I suggest (for future rails):
  1. For rails 7.x seres:  Support arrays of `primary_keys` and `foreign_keys`, i.e. extending API.
  1. For rails 7.x seres: Deprecate and discourage use of `query_constraints` because standard DB terminology is primary keys and foreign keys. and it is awkward to use difference names just because the primary/foreign key is composed f more than one field.
  1. For rails 8.0: remove support for `query_constraints`

That way the API will be a natural extension of the existing (Rails 7.0) API and align very well with the very popular [`composite_primary_keys`](https://github.com/composite-primary-keys/composite_primary_keys) gem.

**Comment by nvasilevski** [comment] 2023-10-17 13:48
>Support arrays of primary_keys and foreign_keys, i.e. extending API.

This is something I do see being done in the next Rails versions with the feature becoming more mature. However
>Deprecate and discourage use of query_constraints because standard DB terminology is primary keys and foreign keys.

Support of `foreign_key: ` param being an array should not necessarily go with deprecation of `query_constraints:`. "Query constraints" is a generic concept which allows you to specify more than one column to use when it comes to performing association-related queries. The reason to use more than one column can be anything - you could either be using composite foreign keys or for example you just want to include `tenant_key` into the queries for sharding purposes. `tenant_key` has nothing to do with association's foreign key and this is why `query_constraints: [:tenant_key, :actual_foreign_key]` makes more sense semantically compared to `foreign_key: [:tenant_key, :actual_foreign_key]` since schema-wise the associated model can easily be referenced using `actual_foreign_key` without the `tenant_key` 

But I guess we will see what `query_constraints` and `foreign_key:` options will grow into.
