### ISSUE TITLE
 The `primary_replica` database is not configured for the `development` environment.

### ISSUE THREAD

**Issue by lpelorosso** [rails/rails#38680] opened 2020-03-09 03:40 UTC
### Expected behavior
Read database configuration from database.yml.

### Actual behavior
Seems to be ignoring the config when specifying a replica database, inside a rake task.
Note that there are no database configurations listed on the error. However, if I remove the `connects_to` from the `Doctors` class, it correctly connects to the `primary` database.

### System configuration
**Rails version**: Rails 6.0.2.1

**Ruby version**: ruby 2.6.3p62

**Rake version**: version 13.0.1

### Error:

ActiveRecord::AdapterNotSpecified: The `primary_replica` database is not configured for the `development` environment.

Available databases configurations are:

/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/connection_specification.rb:252:in `resolve_symbol_connection'
/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/connection_specification.rb:219:in `resolve_connection'
/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/connection_specification.rb:140:in `resolve'
/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:187:in `resolve_config_for_connection'
/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:50:in `establish_connection'
/home/vertexar/Projects/Nusive/patologia.api/lib/tasks/migrate_data.rake:20:in `<class:Doctor>'
/home/vertexar/Projects/Nusive/patologia.api/lib/tasks/migrate_data.rake:18:in `block in <main>'
/home/vertexar/Projects/Nusive/patologia.api/lib/tasks/migrate_data.rake:4:in `<main>'

...

### database.yml

```
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ***
  password: ***
  host: localhost

development:
  primary:
    <<: *default
    database: ****
  primary_replica:
    <<: *default
    adapter: mysql2
    database: ****
    replica: true
```
### Rake Task

Inside rake task I define:

```
  class Doctor < ActiveRecord::Base
    connects_to database: { writing: :primary_replica, reading: :primary_replica }
  end
```

**Comment by wtn** [comment] 2020-03-09 07:59
The parent class of `Doctor` should be `ApplicationRecord`.

The "replica" functionality is strictly for read-only use, maybe you are looking for "sharding" functionality.

**Comment by eileencodes** [comment] 2020-03-09 12:20
@wtn is correct, your models should look like this:

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: { writing: :primary, reading: :primary_replica }
end

class Doctor < ApplicationRecord
end
```

> Seems to be ignoring the config when specifying a replica database, inside a rake task.

Which rake task?

It would be best to provide a demo application that reproduces the problem as right now I don't have enough information to help you.

**Comment by lpelorosso** [comment] 2020-03-09 15:31
Thank you so much for the suggestions. I actually tried that before submitting the issue. The rake task at the moment only tries to retrieve doctors from the replica database. This is the rake task:

```
namespace :migrate do
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    connects_to database: { writing: :primary, reading: :primary_replica }
    end

  class Doctor < ApplicationRecord
  end

  namespace :data do
    desc 'Migrate Data'
    task doctors: :environment do
      puts '[] Migrate Data Task'
      p migrate:Doctor.all
    end
  end
end
```

**Comment by eileencodes** [comment] 2020-03-09 15:42
But Rails provides the migration tasks for you, why are you creating a new one?

**Comment by lpelorosso** [comment] 2020-03-09 15:45
Well, that is correct. Maybe the name wasn't the best one. Still, replacing the name does not fix the issue. The objective of this rake task is getting data from a database, and migrate it into another one, which has different tables.

**Comment by eileencodes** [comment] 2020-03-09 15:50
Please provide a demo application that reproduces the issue. I don't have enough information here to help further.

**Comment by eileencodes** [comment] 2020-03-09 18:18
Oh I see the problem. The way you're writing this rake task can't work. You can't create models inside the task and try to connect them to the databases. The configuration won't be available to be assigned yet. The configuration is only available after `load_config` is called. Also I'm not sure what `migrate:Doctors.all` should do...that's not going to migrate the database. If you move the models to behave correctly and update the task to call the models in the Rails application I think things will work better for you.

I'm going to close this because this isn't a bug in the Rails configurations or multiple database setup.

**Comment by lpelorosso** [comment] 2020-03-09 20:08
Thank you Eileen! The task was just a sample. I understand what you say, it is helpful, thank you!

**Closed** 2020-03-09 20:08 UTC
