### ISSUE TITLE
`has_many through:, dependent: :restrict_with_exception` doesn't work if `through` association is `dependent: :destroy` 

### ISSUE THREAD

**Issue by ojab** [rails/rails#34730] opened 2018-12-17 17:10 UTC
See the test case, works fine in rails-5.0 and fails on rails >= 5.1. Also `user.feedback.reload` before destroying fixes the issue.
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :roles, force: true do |t|
    t.integer :user_id
  end

  create_table :feedbacks, force: true do |t|
    t.integer :role_id
  end
end

class User < ActiveRecord::Base
  has_many :roles, dependent: :destroy
  has_many :feedbacks, through: :roles,
                       dependent: :restrict_with_exception
end

class Role < ActiveRecord::Base
  belongs_to :user
  has_many :feedbacks
end

class Feedback < ActiveRecord::Base
  belongs_to :role
  has_one :user, through: :role
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create!
    role = Role.create!(user: user)
    feedback = Feedback.create!(role: role)

    assert_raises ActiveRecord::DeleteRestrictionError do
      # `user.feedbacks.reload` call fixes the issue
      user.destroy!
    end
  end
end

```

### Expected behavior
`ActiveRecord::DeleteRestrictionError` is raised

### Actual behavior
`user` record is destroyed 

### System configuration
**Rails version**: master

**Ruby version**: 2.5

**Comment by gmcgibbon** [comment] 2019-01-08 20:43
This is happening because of order of dependent callbacks. When you define
```
class User < ActiveRecord::Base
  has_many :roles, dependent: :destroy
  has_many :feedbacks, through: :roles,
                       dependent: :restrict_with_exception
end
```
the first callback destroys the join, and the second one queries for its existence. If you load the association early with `user.feedbacks.reload` it fixes itself, but not in an ideal way. Here's [the line](https://github.com/rails/rails/blob/48375319da490b421e994f22480a43c0f9983ab1/activerecord/lib/active_record/associations/builder/association.rb#L137) the callback gets defined. Changing callback order would break legacy behaviour, so I think I think documenting this gotcha and removing `dependent: :destroy` from your code is the best course of action.

**Comment by ojab** [comment] 2019-01-08 21:17
Well, legacy behavior is already broken since rails-5.1, isn't it? And inconsistent behavior depending on the state of association (loaded/not loaded) is indeed a bug.
In my case removing of `dependent: :destroy` breaks business logic, so it's not an option.

**Comment by gmcgibbon** [comment] 2019-01-08 23:20
> Well, legacy behavior is already broken since rails-5.1, isn't it?

Fair point. I'll inspect the code on 5.0 and see why it works there and get back to you.

**Comment by gmcgibbon** [comment] 2019-01-09 19:38
I can't get the test case to pass with `gem "rails", "5.0"`. It appears to fail for the same callback ordering reason. What am I missing?

**Comment by ojab** [comment] 2019-01-09 20:55
Whoops, looks like I've messed up testing and it's a regression since `rails-5.0`, testcase works with `gem "rails", "~> 4.2.0"`.

**Comment by gmcgibbon** [comment] 2019-01-10 19:09
If its been broken in every version of Rails 5, I think its safe to assume that this is new behaviour, and we should not change it going forward. You can try removing the `dependent` options to your associations and setting the callbacks manually to sidestep the issue. In terms of code changes, there's not much we can do without breaking expected behaviour, so I'm going to close this.

Thank you for your report.

**Closed by gmcgibbon** 2019-01-10 19:09 UTC
Labels: activerecord
