### ISSUE TITLE
Counter cache does not work well with optimistic locking

### ISSUE THREAD

**Issue by skanev** [rails/rails#16449] opened 2014-08-09 21:07 UTC
Counter cache and optimistic locking don't play well together. The example below illustrated the problem:

``` ruby
require 'active_record'
require 'minitest/autorun'
require 'sqlite3'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection 'sqlite3::memory:'

ActiveRecord::Schema.define do
  create_table :people do |t|
    t.string :name
    t.integer :lock_version, null: false, default: 0
    t.integer :vehicles_count, null: false, default: 0
    t.integer :jobs_count, null: false, default: 0
    t.timestamps
  end

  create_table :jobs do |t|
    t.belongs_to :person
  end

  create_table :vehicles do |t|
    t.belongs_to :owner, polymorphic: true
  end
end

class Person < ActiveRecord::Base
  has_many :jobs,                 dependent: :destroy, counter_cache: true
  has_many :vehicles, as: :owner, dependent: :destroy, counter_cache: true
end

class Job < ActiveRecord::Base
  belongs_to :person, counter_cache: true
end

class Vehicle < ActiveRecord::Base
  belongs_to :owner, polymorphic: true, counter_cache: true
end

class BugTest < Minitest::Test
  def test_locking_simple_non_polymorphic
    person = Person.create!
    person.jobs << Job.create!

    # Fails on the next expression. jobs#<< updates the lock_version in the
    # database, but not in the loaded object. Raises StaleObjectError.

    person.destroy
  end

  def test_locking_simple_polymorphic
    person = Person.create!
    person.vehicles << Vehicle.create!

    # Should fail on the next expression if counter_cache worked for
    # polymorphic relationships. It doesn't at the time of writing so the
    # test passes. Fails on top of #16445

    person.destroy
  end
end
```

Note that one of the tests passes, because counter cache does not work on polymorphic associations. If that is fixed (#16445), both tests will fail.

As far as I can tell, the expected behaviour is for counter cache to bump the `lock_version`. It does so in the database, but in some situations it fails to update it in the loaded object. I've created a [gist with test cases](https://gist.github.com/skanev/f442394e81463588e9d6) that tests this behaviour in detail. All of the tests currently fail.

One way to get the tests in the gist to pass is to add `touch: true` to both `belongs_to` relationships (after applying #16445 and #16448, which fix some bugs). `touch: true` seems to do a good job of updating `lock_version` in the loaded model when necessary.

I see three possible ways to resolve this issue:
1. **Don't bump `lock_version` for `counter_cache`**. This makes some sense to me – the version is not bumped if there is no `counter_cache` and I don't see why adding a cache should change this. The user can always intentionally get it by passing `touch: true`.
2. **Have the counter cache do what `touch: true` does**. I gave this a shot, but couldn't get it to work in all cases. It might introduce some duplication between `counter_cache` and `touch`. It makes the `counter_cache` code very aware of (and non-orthogonal to) the optimistic locking code.
3. **Always set `touch: true` in the association when there is a counter cache**. It's a cheap solution :smile: . Not sure how it can be implemented, but it's seems to be the simplest thing that will (1) preserve the behaviour and (2) fix the issue. Also – no duplication.

There might be other possibilities that I haven't thought of.

My personal favourite is the first one. It gives the user the most options and it doesn't require changing the `counter_cache` too much. Not changing the `lock_version` behaviour also makes sense to me. However, I understand it might not be the desired solution.

Thoughts?

/cc @senny

P.S.: Whichever of the three (or more) options makes the most sense, I'd love to try implementing it :smile:

**Comment by beno** [comment] 2015-02-03 14:07
Just ran in to this, on 4.2. Is there a workaround?

**Comment by beno** [comment] 2015-02-03 14:16
Just ran in to this, on 4.2. ~~Is there a workaround?~~

Simple workaround:

```ruby
    #active_record/persistence.rb:168

    def destroy
      raise ReadOnlyRecord, "#{self.class} is marked as readonly" if readonly?
      destroy_associations
      reload #reload record
      destroy_row if persisted?
      @destroyed = true
      freeze
    end
```

**Comment by tdgs** [comment] 2015-09-10 14:57
I don't get why updating the counter_cache should update the lock_version actually. The counter_cache is readonly attribute. It should not be versioned we the other attributes.

Consider the following scenario: You have an application with posts and comments. The posts table has a counter_cache to store the number of comments, and it also has a lock_version to prevent multiple_edits. With the current behaviour, if you open a  post for editing and in the meantime somebody comments, then you cannot save your post.

IMHO posting a comment should not mess with your post edit.

What do you think?

**Comment by toao** [comment] 2015-09-10 15:59
@tdgs good point! The counter cache isn't directly connected to the record where it is stored, but to the related association. So updating the counter shouldn't interfere with the lock version.

That raises the question why it was explicitly added here: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/locking/optimistic.rb#L165

If you take the [intention of optimistic locking](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/locking/optimistic.rb#L5) into account (preventing simultaneous updates to overwrite each other), it's not clear why updated counter caches should ever change the lock version.

**Comment by gucki** [comment] 2015-09-22 13:26
@tdgs @toao If you wouldn't update the counter cache the result could be incosistent because it's *not* uing using atomic database operations like `UPDATE posts SET comments_count = comments_count + 1 WHERE id = 1`.

@tdgs Imo in the usecase you describe it's up to you to catch the exception and properly handle it. For example you could check what columns changed and retry your update (reload the record and update again) if nothing conflicting changed.

**Comment by uberllama** [comment] 2015-12-01 16:00
I just ran into this the other day. Counter cache should definitely *not* be updating lock version. Counter caches are denormalizations, and should not be considered relevant to optimistic locking.

**Comment by gucki** [comment] 2015-12-01 16:06
@uberllama If you don't apply locking and are not using atomic databasse operations (rails doesn't use   atomic databasse operations) your counter cache gets out of sync sooner or later.

**Comment by jmuheim** [comment] 2015-12-14 12:40
When creating a child object through the association of the parent object, the counter cache of the parent is updated in the DB, but not in the ruby object:

    it 'destroys associated boilerplate copies' do
      project = create :project, :with_boilerplate_copy

      expect {
        project.destroy
      }.to change { BoilerplateCopy.count }.by -1
    end

Fails:

    Failure/Error: project.destroy
    ActiveRecord::StaleObjectError:
      Attempted to destroy a stale object: Project

When adding a `project.reload` before deleting the project, it passes.

I stumbled over this issue while doing some research for this StackOverflow topic: http://stackoverflow.com/questions/34267129/rails-and-optimistic-locking-creating-an-object-through-an-association-changes

**Comment by BintLopez** [comment] 2017-08-11 16:47
Can confirm this is still occurring. Just encountered the same issue when creating a object through its association. Our project is using **4.2.7**. Example below is obvi contrived but representative of the issue we're experiencing.
```ruby
class Cat < ActiveRecord::Base
  has_many :treats, inverse_of: :cat
end

class Treats < ActiveRecord::Base
  belongs_to :cat, inverse_of: :treats
end

cat1 = Cat.find 1
cat2 = Cat.find 2

# Creating the cat updates the lock
cat1.treats.create!

# Throws a stale object error unless do cat2.reload
cat2.update!(name: 'Fluffy')
```

**Comment by rvirani1** [comment] 2017-11-14 03:00
Still having in Rails 5

**Comment by yan-hoose** [comment] 2019-08-14 11:55
Still running into this on Rails 5.2.3

```
class Post < ActiveRecord::Base
  has_many :comments, inverse_of: :post
end

class Comment < ActiveRecord::Base
  belongs_to :post, inverse_of: :comments, counter_cache: true
end

post = Post.find 1

# updates the lock_version in the DB but not on the Ruby object
post.comments.create!

# Throws an ActiveRecord::StaleObjectError
post.update!(title: 'Updated title')
```

**Comment by hashwin** [comment] 2019-10-01 18:38
@yan-hoose Yup still facing the same issue on 5.2.3.
Did you manage to find any workaround for this?

**Comment by toao** [comment] 2019-10-01 19:00
@hashwin the issue was not tackled, it's still present, even in 6.0.0

our quick'n'dirty fix is to patch the [problematic method](https://github.com/rails/rails/blob/v6.0.0/activerecord/lib/active_record/locking/optimistic.rb#L153-L156) like this:

```
module ActiveRecord
  module Locking
    module Optimistic
      module ClassMethods
        def update_counters(id, counters)
          super
        end
      end
    end
  end
end
```

**Comment by yan-hoose** [comment] 2019-10-01 20:05
@hashwin My workaround was to reload the parent model everywhere in our code where this issue manifests.

Using the example above, I did a `post.reload` after `post.comments.create!`

**Comment by hashwin** [comment] 2019-10-02 03:30
@yan-hoose I considered that, but it won't work in situations where you need to keep track of the changes on the model because reloading clears everything.

@toao Seems like an alright solution.
I wonder why that code was explicitly introduced in the first place? (13 years ago!  https://github.com/rails/rails/commit/83752373b9c83bf585b5fe44836c65612b680cf9#diff-e8099d3205c1cc5136a5441174a6078bR120)

I feel like all it has to do is update the ruby object itself, not just the db, and it would work even with updating the lock version.

**Comment by jonathanhefner** [comment] 2020-05-08 19:03
I've created a new minimal reproduction script based on @yan-hoose's comment https://github.com/rails/rails/issues/16449#issuecomment-521215501.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.integer :lock_version, default: 0
    t.integer :comments_count, default: 0
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: true
end

class BugTest < Minitest::Test
  def test_the_bug
    post = Post.create!

    # Updates the lock_version in the DB but not on the Ruby object
    post.comments.create!

    # Raises an ActiveRecord::StaleObjectError
    post.update!(title: "foo")

    assert_equal "foo", post.title
  end
end
```

**Comment by tbcooney** [comment] 2020-05-08 19:13
Thanks for re-opening @jonathanhefner 🙏 As you saw on my issue #39115, my workaround was to reload the parent model. Should I just roll with this until the issue is addressed in a release?

**Comment by jonathanhefner** [comment] 2020-05-08 19:23
@tbcooney I don't think there's any *official* workaround at the moment, so do whatever works for you. :+1: 

Another option, if it's possible in your app, might be to re-order the operations.  For example, change from: 

```ruby
post.comments.create!
post.update!(title: "foo")  # raises ActiveRecord::StaleObjectError
```

To:
```ruby
post.update!(title: "foo")
post.comments.create!  # nothing raised
```

**Comment by alipman88** [comment] 2020-05-16 15:22
Unless I'm missing something, at first glance I believe there's a straightforward solution: Bump up an ActiveRecord instance's lock version after incrementing/decrementing a cache_counter column, such that the ActiveRecord instance's lock version remains in parity with the DB.

I'm going to think about this a little more before submitting a PR, but intend to submit a patch within the next week or so.

First draft: https://github.com/alipman88/rails/commit/ddc981739f213e7313e6bec601b736071bc8624a

**Closed** 2020-05-20 01:12 UTC
Labels: With reproduction steps, activerecord
