### ISSUE TITLE
config/environments/development.rb:53:in `block in <top (required)>': uninitialized constant ActiveSupport::EventedFileUpdateChecker (NameErro

### ISSUE THREAD

**Issue by rezapci** [rails/rails#27462] opened 2016-12-27 03:03 UTC
``` sh
 [reza@1610:~/Demo/railsgirls$ bin/rails generate controller Say hello goodbye

/home/reza/Demo/railsgirls/config/environments/development.rb:53:in `block in <top (required)>': uninitialized constant ActiveSupport::EventedFileUpdateChecker (NameError)
	from /usr/lib/ruby/vendor_ruby/rails/railtie.rb:210:in `instance_eval'
	from /usr/lib/ruby/vendor_ruby/rails/railtie.rb:210:in `configure'
	from /home/reza/Demo/railsgirls/config/environments/development.rb:1:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:597:in `each'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:597:in `block in <class:Engine>'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `each'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
	from /usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
	from /home/reza/Demo/railsgirls/config/environment.rb:5:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:92:in `require'
	from /var/lib/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:92:in `preload'
	from /var/lib/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /var/lib/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /var/lib/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /var/lib/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /var/lib/gems/2.3.0/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

```

i created a rails new app, after the installation I add bundle exec rails about, then when I add bin/rails generate controller Say hello goodbye.  that shows the error.  

### System configuration
**Rails version**:
rails version
Rails 5.0.1
**Ruby version**:
rvm install ruby-2.3.1
rvm install ruby-2.3
rvm install 2.3.1
rvm install 2.3

how could i fix this?
<a href="https://gyazo.com/b25e8282c50f79488087c71e3d12e095"><img src="https://i.gyazo.com/b25e8282c50f79488087c71e3d12e095.png" alt="https://gyazo.com/b25e8282c50f79488087c71e3d12e095" width="1139"/></a> #

**Comment by prathamesh-sonpatki** [comment] 2016-12-27 06:38
Could not reproduce on the brand new app setup from scratch:

``` sh
$ rails -v
Rails 5.0.1
$ rails new rails_demo_app
$ cd rails_demo_app/
$ bin/rails generate controller Say hello goodbye
/Users/prathamesh/.rbenv/versions/ruby-dev/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/Users/prathamesh/.rbenv/versions/ruby-dev/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/Users/prathamesh/.rbenv/versions/ruby-dev/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
Running via Spring preloader in process 21156
Expected string default value for '--jbuilder'; got true (boolean)
Expected string default value for '--helper'; got true (boolean)
Expected string default value for '--assets'; got true (boolean)
      create  app/controllers/say_controller.rb
       route  get 'say/goodbye'
       route  get 'say/hello'
      invoke  erb
      create    app/views/say
      create    app/views/say/hello.html.erb
      create    app/views/say/goodbye.html.erb
      invoke  test_unit
      create    test/controllers/say_controller_test.rb
      invoke  helper
      create    app/helpers/say_helper.rb
      invoke    test_unit
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/say.coffee
      invoke    scss
      create      app/assets/stylesheets/say.scss
```

Was there anything else that you had done before running the generate command?

**Comment by rezapci** [comment] 2016-12-27 07:24
nothing i just follow the instruction on my book..!!!

**Comment by matthewd** [comment] 2016-12-27 08:08
> `/usr/lib/ruby/vendor_ruby/rails`

That sounds like it's been installed with an OS package, not a gem.

Most likely this is a version mismatch between the loaded components and the generated application; if Active Support 5.0 was loaded, that class would be defined.

**Comment by marceloboeira** [comment] 2016-12-30 10:14
Same problem here with Rails 5.0.1 and Ruby 2.4.0.

**Comment by CliffordBernard** [comment] 2016-12-30 21:10
I get this when I run rake commands.  Everything seems to work fine.

```
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
```

**Comment by kaspth** [comment] 2016-12-30 21:20
@marceloboeira @CliffordBernard those will go away in 5.0.2 when https://github.com/rails/rails/pull/27458 goes out 😉

**Comment by marceloboeira** [comment] 2016-12-30 23:36
@kaspth thanks!

**Comment by mjmaix** [comment] 2016-12-31 07:10
I'm also getting the same error messages and also exits the app right away, blocking dev.. 

```
Michael-MBP:poseidon mick$ rails server
/Users/mick/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/Users/mick/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/Users/mick/.rvm/gems/ruby-2.4.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:13: warning: constant ::Fixnum is deprecated
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
/Users/mick/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
Exiting
```

**Comment by pixeltrix** [comment] 2017-01-10 17:28
Closing since this is fixed in 5-0-stable

**Closed by pixeltrix** 2017-01-10 17:28 UTC
Labels: needs work, railties
