### ISSUE TITLE
Default initializer files promote a configuration anti-pattern

### ISSUE THREAD

**Issue by dan-jensen** [rails/rails#36650] opened 2019-07-10 16:54 UTC
### Steps to reproduce
1. `rails new test_app`
1. `grep Rails.application.config test_app/config/initializers/*`
1. Count 9 results, spanning 4 of 9 files
1. Form expectation that using `Rails.application.config` in initializer files is safe
1. Use `Rails.application.config` in initializer files and encounter problems like #10908, #19801 and #24748

### Expected behavior
It is safe to use `Rails.application.config` in initializer files, because it is used in default initializer files (and suggested in documentation).

### Actual behavior
It is **not** safe to use `Rails.application.config` in initializer files.  Such usage can cause loading order problems that are unpredictable and difficult to troubleshoot.  It is an acknowledged anti-pattern:

- @fxn commented in Issue #24748 (2016): "In general, configuration specific to the application object needs to go either in config/application.rb or in config/environments/#{Rails.env}.rb, you can't just assign to an arbitrary config point in config/initializers and expect it to work."
- @rafaelfranca commented in Issue #19801 (2015): "These loading order problems are the worst" and [confirmed](https://github.com/rails/rails/issues/19801#issuecomment-95258268) that the comments in [ActiveJob::QueueAdapters::SidekiqAdapter](https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb) should be changed so they stop suggesting the use of initializers.
- @arunagw commented in Issue #10908 (2013): "configurations can't be set on initializers".

### System configuration
**Rails version**: Multiple, including latest

**Ruby version**: Multiple, including latest

### Proposed solution
Change the **expected behavior** by eliminating all use of `Rails.application.config` in [default initializer templates](https://github.com/rails/rails/tree/master/railties/lib/rails/generators/rails/app/templates/config/initializers).  That is most easily (although not necessarily best) accomplished by moving those configuration lines into application.rb.  This solution seems much easier than changing the **actual behavior** by somehow making it safe to use `Rails.application.config` in initializers.

After that, update the documentation to eliminate all suggestions to use `Rails.application.config` in initializers (e.g. [ActiveJob::QueueAdapters::SidekiqAdapter](https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb) per Issue #19801).  After that, perhaps introduce an exception if configuration with `Rails.application.config` is attempted after primary initialization is complete, to eliminate these loading order problems forever.

**Comment by ivanovv** [comment] 2019-07-15 10:00
One of the reasons we are using initializers is keeping code DRY (eg, same setting can be used for redis cache store and sidekiq redis config), so suggesting a way to reuse code would also be very useful, imo.

**Comment by rafaelfranca** [comment] 2019-07-16 01:50
`Rails.application.config` is not an anti-pattern. Indeed there are a few problems when gems are forcing Rails components to be initialized earlier. Those problems are things that need to be fixed on those gems, not a anti-pattern.

Thank you for the ussye.

**Closed by rafaelfranca** 2019-07-16 01:50 UTC

**Comment by fxn** [comment] 2019-07-16 03:17
The problem is not `Rails.application.config` per se, it is our tendency to push application configuration to initializers in newly generated applications, and this comment generated in `config/application.rb`:

```ruby
# Settings in config/environments/* take precedence over those specified here.
# Application configuration can go into files in config/initializers
# -- all .rb files in that directory are automatically loaded after loading
# the framework and any gems in your application.
```

The boot process generally speaking is:

1. Users configure via `config`.
2. Railties and engines translate that config into their API using their own initializers.
3. The initializers of railties and engines generally run before application initializers.

So, by the time application initializers run, it is generally speaking too late _by design_.

Our init & config story is not enterely round in my view.

**Comment by dan-jensen** [comment] 2019-08-13 19:48
> too late by design

In apparent support of that perspective, @jeremy commented in https://github.com/rails/rails/pull/34985/files#r260500138: "Having boot and initialization phases share config space is the problem".

**Comment by asmrtfm** [comment] 2025-05-27 11:50
@fxn  makes sense.  I can see now that my issue isn't really related to the topic discussed here, lol
