### ISSUE TITLE
Make Rails' Minitest reporters loading configurable

### ISSUE THREAD

**Issue by fnando** [rails/rails#24179] opened 2016-03-13 12:16 UTC
### Steps to reproduce

I'll use minitest-reporters. First, add it to the Gemfile:

```ruby
gem "minitest-reporters"
```

Then load it at `test/test_helper.rb`:

```ruby
require "minitest/reporters"
Minitest::Reporters.use! Minitest::Reporters::DefaultReporter.new(color: true)
```

Now run tests. You should see results from both Rails reporters and minitest-reporters.

![](https://dl.dropboxusercontent.com/s/zbfmhsn46d99hd3/2016-03-13%20at%209.15%20AM.png)

### Expected behavior

After disabling Rails custom reporters, only the output of the custom reporter should be seen.

### Actual behavior

Adding a custom reporter will always output test results several times. Rails should include a configuration (e.g. environment variable or something as `config.minitest.enable_reporters`) to disable injecting Rails default reporters.

This is the expected output after [commenting out these lines](https://github.com/rails/rails/blob/v5.0.0.beta3/railties/lib/rails/test_unit/minitest_plugin.rb#L87-L89) of [railties/lib/rails/test_unit/minitest_plugin.rb](https://github.com/rails/rails/blob/v5.0.0.beta3/railties/lib/rails/test_unit/minitest_plugin.rb):

![](https://dl.dropboxusercontent.com/s/t0y7dtw3k1mf807/2016-03-13%20at%209.26%20AM.png)

### System configuration

- **Rails version**: 5.0.0.beta3
- **Ruby version**: 2.3.0

**Comment by maclover7** [comment] 2016-03-13 13:50
cc @kaspth

**Comment by zenspider** [comment] 2016-03-14 21:51
This suggests that rails is still not using minitest correctly. The reporter setup is totally malleable.

**Comment by kaspth** [comment] 2016-03-14 22:08
@zenspider agreed. I'm having trouble seeing how our reporters can co-exist with others, though. Currently we just zap Minitests existing ones, https://github.com/rails/rails/blob/4232f7ee427a510eb07e420f5883611bcb0abfae/railties/lib/rails/test_unit/minitest_plugin.rb#L87-L89, which causes these problems.

I've noticed Minitests pride plugin replaces the io passed to the reporter is that generally a better way? Thanks!

**Comment by zenspider** [comment] 2016-03-14 23:37
@kaspth actually that looks fine to me. So the problem is more along the lines of minitest-reporters either not fully zapping everything else and taking over or at least not selectively adding reporters?

**Comment by fnando** [comment] 2016-03-14 23:41
@zenspider can the loading plugin order affect this?

**Comment by zenspider** [comment] 2016-03-15 00:23
@fnando shouldn't. I mean... it'll affect which one is printing first, right? But the problem here is that there are too many cooks in the kitchen.

**Comment by kaspth** [comment] 2016-03-21 21:15
Per @zenspider, I'm going to close this as minitest-reporters issue:

> the problem is more along the lines of minitest-reporters either not fully zapping everything else and taking over

@fnando can you open an issue on minitest-reporters? Thanks everyone! :heart:

**Comment by fnando** [comment] 2016-03-21 21:19
@kaspth This isn't a problem specific to minitest-reporters. I have a gem that uses a custom reporter that is also failing with this problem.

**Comment by kaspth** [comment] 2016-03-21 21:22
That could just be it has the problem as minitest-reporters. E.g. not clearing out other reporters sufficiently to take over. Can you link to that code?

**Comment by fnando** [comment] 2016-03-21 21:30
@kaspth this is the minitest plugin initializer: https://github.com/fnando/minitest-utils/blob/master/lib/minitest/utils_plugin.rb

```ruby
require "minitest/utils"

module Minitest
  def self.plugin_utils_init(options)
    reporters = Minitest.reporter.reporters
    reporters.clear
    reporters << Minitest::Utils::Reporter.new(options[:io], options)
    reporters << Minitest::Utils::TestNotifierReporter.new(options[:io], options) if defined?(TestNotifier)
  end
end
```

**Comment by kaspth** [comment] 2016-03-21 21:36
Oh my, can these reporters turn into a game of whack-a-mole. It might be better for Rails to not support any other reporters and just clear them completely. But then we require a config option as you say.

Thanks, I'll look into it :heart:

**Comment by fnando** [comment] 2016-03-21 21:39
@kaspth maybe Rails should load the reporter when running `require "rails/all"`, but making possible to opt-out when wanted.

**Comment by kaspth** [comment] 2016-03-22 20:40
Should be fixed in https://github.com/rails/rails/commit/b9465e8755509cc79ad7492914a26c8ac3884de0, take a look 😁

(Don't know why GitHub didn't close this automatically, thought I had the syntax right.)

**Closed by kaspth** 2016-03-22 20:40 UTC
Labels: railties

**Comment by fnando** [comment] 2016-03-22 20:55
@kaspth AWESOME! It's working now. Thanks! :)

**Comment by kaspth** [comment] 2016-03-22 20:56
Fuckin' A, that's great to hear! 😄
