### ISSUE TITLE
Broken table alias referencing in Rails 7.0.5.1

### ISSUE THREAD

**Issue by kaoru** [rails/rails#48592] opened 2023-06-27 13:42 UTC
### Steps to reproduce

We're using a combination of "where missing" and "or + scope" to find events which have not ended, meaning that they don't have a schedule at all _or_ they do have a schedule and it doesn't have a date _or_ they do have a schedule and it has a date and that date is today or in the future.

The behaviour has changed in Rails 7.0.5.1 to throw an `ActiveRecord::StatementInvalid` error, because on 7.0.4.3 the left joined table was not given an alias but on 7.0.5.1 it is given an alias and that alias is then not consistently used in the where clauses produced.

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', '~> 7.0', '= 7.0.5.1'
  # gem 'rails', '~> 7.0', '= 7.0.4.3'
  # gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
#ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :events, force: true do |t|
  end

  create_table :event_schedules, force: true do |t|
    t.integer :event_id
    t.date :date
  end
end

class Event < ActiveRecord::Base
  has_one :schedule, class_name: 'EventSchedule', dependent: :destroy

  scope :not_ended, -> { where.missing(:schedule).or(EventSchedule.not_ended) }
end

class EventSchedule < ActiveRecord::Base
  belongs_to :event

  scope :date_not_set, -> { where(date: nil) }
  scope :not_ended, -> { where('date >= ?', Date.today).or(date_not_set) }
end

class BugTest < Minitest::Test
  def setup
    Event.create
    Event.create.then { |e| e.create_schedule(date: Date.yesterday) }
    Event.create.then { |e| e.create_schedule(date: Date.today) }
    Event.create.then { |e| e.create_schedule(date: Date.tomorrow) }
  end

  # This works on Rails 7.0.4.3 and gives an ActiveRecord::StatementInvalid on
  # Rails 7.0.5.1 because the table alias behaviour has changed.
  def test_events_not_ended
    puts
    puts Event.not_ended.to_sql
    puts

    assert_equal 3, Event.not_ended.uniq.count
  end
end
```

### Expected behavior

On Rails 7.0.4.3 (and on the main branch of `rails/rails`) the SQL produced is:

```sql
SELECT "events".* FROM "events" LEFT OUTER JOIN "event_schedules" ON "event_schedules"."event_id" = "events"."id" WHERE ("event_schedules"."id" IS NULL OR date >= '2023-06-27' OR "event_schedules"."date" IS NULL)
```

Which works because there is no table alias.

### Actual behavior

The SQL produced is:

```sql
SELECT "events".* FROM "events" LEFT OUTER JOIN "event_schedules" "schedule" ON "schedule"."event_id" = "events"."id" WHERE ("schedule"."id" IS NULL OR date >= '2023-06-27' OR "event_schedules"."date" IS NULL)
```

Which throws an error:

```
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: event_schedules.date
```

Because the table is alias to "schedule" but then referred to as "events_schedule" in the merged or scope.

### System configuration
**Rails version**: 7.0.5.1

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment] 2023-06-27 14:27
Duplicate of https://github.com/rails/rails/issues/48334

**Closed by fatkodima** 2023-06-27 14:27 UTC
