### ISSUE TITLE
[Regression 4.1.10] where(polymorphic: nil) or where(polymorphic: [])

### ISSUE THREAD

**Issue by niedfelj** [rails/rails#19510] opened 2015-03-25 15:21 UTC
In 4.1.9, a query on a polymorphic relationship like this would just return nil:

```
2.2.1 :001 > Spree::Adjustment.where(adjustable: nil).tax.first
  Spree::Adjustment Load (3.9ms)  SELECT  "spree_adjustments".* FROM "spree_adjustments"  WHERE "spree_adjustments"."adjustable_id" IS NULL AND "spree_adjustments"."source_type" = 'Spree::TaxRate'  ORDER BY "spree_adjustments"."id" ASC LIMIT 1
 => nil 
2.2.1 :002 > Spree::Adjustment.where(adjustable: nil).first
  Spree::Adjustment Load (0.7ms)  SELECT  "spree_adjustments".* FROM "spree_adjustments"  WHERE "spree_adjustments"."adjustable_id" IS NULL  ORDER BY "spree_adjustments"."id" ASC LIMIT 1
 => nil 
2.2.1 :003 > exit

2.2.1 :001 > Spree::Adjustment.where(adjustable: []).first
  Spree::Adjustment Load (1.2ms)  SELECT  "spree_adjustments".* FROM "spree_adjustments"  WHERE 1=0  ORDER BY "spree_adjustments"."id" ASC LIMIT 1
 => nil 
2.2.1 :002 > Spree::Adjustment.where(adjustable: []).tax.first
  Spree::Adjustment Load (0.6ms)  SELECT  "spree_adjustments".* FROM "spree_adjustments"  WHERE 1=0 AND "spree_adjustments"."source_type" = 'Spree::TaxRate'  ORDER BY "spree_adjustments"."id" ASC LIMIT 1
 => nil 
```

In 4.1.10, due to changes in the 
```
ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:64:in `expand'
```
those same queries are now raising exceptions

```
2.2.1 :001 > Spree::Adjustment.where(adjustable: nil).tax.first
NameError: uninitialized constant Spree::Adjustment::Adjustable
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/inheritance.rb:133:in `compute_type'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/reflection.rb:221:in `klass'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/reflection.rb:272:in `association_primary_key'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:64:in `expand'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:43:in `block in build_from_hash'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `each'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:954:in `build_where'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:572:in `where!'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:559:in `where'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/querying.rb:10:in `where'
	from (irb):1
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/console.rb:90:in `start'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/console.rb:9:in `start'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from Spree::Adjustment.where(adjustable: nil).first
NameError: uninitialized constant Spree::Adjustment::Adjustable
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/inheritance.rb:133:in `compute_type'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/reflection.rb:221:in `klass'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/reflection.rb:272:in `association_primary_key'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:64:in `expand'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:43:in `block in build_from_hash'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `each'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:954:in `build_where'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:572:in `where!'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:559:in `where'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/querying.rb:10:in `where'
	from (irb):2
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/console.rb:90:in `start'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/console.rb:9:in `start'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from Spree::Adjustment.where(adjustable: []).tax.first
NameError: uninitialized constant Spree::Adjustment::Adjustable
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/inheritance.rb:133:in `compute_type'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/reflection.rb:221:in `klass'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/reflection.rb:272:in `association_primary_key'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:64:in `expand'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:43:in `block in build_from_hash'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `each'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:954:in `build_where'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:572:in `where!'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:559:in `where'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/querying.rb:10:in `where'
	from (irb):3
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/console.rb:90:in `start'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/console.rb:9:in `start'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from Spree::Adjustment.where(adjustable: []).first
NameError: uninitialized constant Spree::Adjustment::Adjustable
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/inheritance.rb:133:in `compute_type'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/reflection.rb:221:in `klass'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/reflection.rb:272:in `association_primary_key'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:64:in `expand'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:43:in `block in build_from_hash'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `each'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:954:in `build_where'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:572:in `where!'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/relation/query_methods.rb:559:in `where'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.10/lib/active_record/querying.rb:10:in `where'
	from (irb):4
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/console.rb:90:in `start'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/console.rb:9:in `start'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/joel/.rvm/gems/ruby-2.2.1/gems/railties-4.1.10/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'2.2.1 :005 > 
```

**Comment by JDutil** [comment] 2015-03-25 15:56
This is a duplicate of https://github.com/rails/rails/pull/19479 and can be closed.

**Closed** 2015-03-25 16:20 UTC
