### ISSUE TITLE
Unable to parse `filter_parameters` in development environment leads to unclear error message

### ISSUE THREAD

**Issue by xtina-starr** [rails/rails#29947] opened 2017-07-25 21:15 UTC
When malformed query parameters are passed, a controller fails to parse the query parameters (which is expected). In production, this is ok because the `PublicExceptions` middleware catches it and shows the corresponding error page. In development on the other hand, the `DebugExceptions` middleware attempts to render the [request and response template](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb#L9) but is unable to parse `filtered_parameters` and doesn't display the correct error message. 

Here is the test that replicates the bug:

```diff
diff --git a/railties/test/application/middleware/exceptions_test.rb b/railties/test/application/middleware/exceptions_test.rb
index fe07ad3cbe..8ad218beb8 100644
--- a/railties/test/application/middleware/exceptions_test.rb
+++ b/railties/test/application/middleware/exceptions_test.rb
@@ -134,5 +134,21 @@ def index
       assert_match(/boooom/, last_response.body)
       assert_match(/測試テスト시험/, last_response.body)
     end
+
+    test "displays diagnostics message when malformed query parameters are provided" do
+      controller :foo, <<-RUBY
+        class FooController < ActionController::Base
+          def index
+          end
+        end
+      RUBY
+
+      app.config.action_dispatch.show_exceptions = true
+      app.config.consider_all_requests_local = true
+
+      get "/foo?x[y]=1&x[y][][w]=2"
+      assert_equal 400, last_response.status
+      assert_match "Rack::QueryParser::ParameterTypeError", last_response.body
+    end
   end
 end
```

If you run the test above, it'll fail with the message below:

```
$ rails -v
Rails 5.2.0.alpha
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
$ ruby -I"lib:test" test/application/middleware/exceptions_test.rb
Run options: --seed 20823

# Running:

......F

Failure:
ApplicationTests::MiddlewareExceptionsTest#test_displays_diagnostics_message_when_malformed_query_parameters_are_provided [test/application/middleware/exceptions_test.rb:151]:
Expected /Rack::QueryParser::ParameterTypeError/ to match "".
```

**Comment by yuki24** [comment] 2017-10-24 12:46
just wanted to let everyone know that this bug still exists and shows unhelpful messages.

**Comment by yuki24** [comment] 2018-06-29 17:15
I got bitten by this bug again due to a typo in a `name` attribute in an `<input>` tag. This really needs to be fixed in both `master` and `5-2-stable`. The pull request I sent earlier needs rebasing, but I'll update the branch as soon as possible. I'll also prepare an example app that replicates the issue to demonstrate how easy it is to run into this issue and how odd this could look.

**Comment by st0012** [comment] 2019-04-28 16:34
I can confirm that this still happens on latest master. Although the message is now slightly changed into

```
Failure:
ApplicationTests::MiddlewareExceptionsTest#test_displays_diagnostics_message_when_malformed_query_parameters_are_provided [test/application/middleware/exceptions_test.rb:153]:
Expected /Rack::QueryParser::ParameterTypeError/ to match # encoding: US-ASCII
"".
```

@yuki24 would you mind update your branch? It has some conflicts.

**Closed** 2019-05-08 00:46 UTC
Labels: With reproduction steps, actionpack, attached PR
