### ISSUE TITLE
Activestorage duplicating blobs when .attach is called

### ISSUE THREAD

**Issue by muyiwaoyeniyi** [rails/rails#40827] opened 2020-12-13 18:40 UTC
### Steps to reproduce
1. Initialize an activerecord object that has say `has_many_attached :files` relationship. Ensure to set the files attribute with a ActionDispatch::Http::UploadedFile object.
2. Then call `.attach` on `files` with an activestorage blob object.

### Expected behavior
I should have two blobs waiting to be attached/persisted. One from each step.

### Actual behavior
I have 3 blobs waiting to be attached. 

From looking at the code, it seems `.attach` appends any existing blobs to the new attachables and then it calls the `files` setter method which itself appends any existing blobs to the "new attachables" from `.attach` . See code references below.

https://github.com/rails/rails/blob/95d4c50eb5d35c036a1a52fc66c81d11a84ddd37/activestorage/lib/active_storage/attached/many.rb#L35
https://github.com/rails/rails/blob/95d4c50eb5d35c036a1a52fc66c81d11a84ddd37/activestorage/lib/active_storage/attached/model.rb#L149

As a side note, if you use the setter method directly on step 2 to set the activestorage blob, then you get 2 blobs waiting to be attached. The issue only occurs when `.attach` is used. You could also just replace step 1 with a .attach call. You get the same results.

### System configuration
**Rails version**: 6.1.0.rc2

**Ruby version**: 2.7.1

Thanks for the hard work by the Rails team!

**Comment by lucasfp-br** [comment] 2021-03-08 19:13
@muyiwaoyeniyi I had this problem too.

After spent some hours debugging, I'd realize that use "files" in has_many_attached association could be the critical point leading to this. And it was!

I've changed the association to `has_many_attached :attachments` and fixed all controller references and it's working fine now. I'm still encouraged to investigating what is causing this problem in the lib and maybe submit a PR...

**Comment by elliotjd1** [comment] 2021-06-11 09:27
I had the same issue (Rails 6.1.3.2). I tried lucasfp13's suggestions but was still facing the same problem.

What worked for me was to call `.save` on the model after each call to `.attach`, then I would end up with the correct number of attachments.

**Comment by zzak** [comment] 2021-06-11 13:25
@santib Wasn't this already an issue you were dealing with? 🤔

**Comment by santib** [comment] 2021-06-11 16:02
> @santib Wasn't this already an issue you were dealing with? 🤔

@zzak Not sure if it's related. Maybe if someone can provide a reproduction script or a test it would be better. What I understand from the reproduction steps

>1. Initialize an activerecord object that has say has_many_attached :files relationship. Ensure to set the files attribute with a ActionDispatch::Http::UploadedFile object.
>2. Then call .attach on files with an activestorage blob object.

Is a test like this:
```ruby
  test "attaches two files" do
    user = User.new(name: 'Tina', highlights: [fixture_file_upload("image.gif")])
    user.highlights.attach fixture_file_upload("racecar.jpg")

    assert_equal 2, user.highlights.size
    assert_equal "image.gif", user.highlights.first.filename.to_s
    assert_equal "racecar.jpg", user.highlights.second.filename.to_s
  end
```

(except that we use `highlights` instead of `files` but shouldn't change anything)

And that test passes on `main` 🤔 thoughts?

**Comment by santib** [comment] 2021-06-11 16:10
>@santib Wasn't this already an issue you were dealing with? 🤔

@zzak Not sure if it's related. Maybe if someone can provide a reproduction script or a test it would be better. What I understand from the reproduction steps

>1. Initialize an activerecord object that has say has_many_attached :files relationship. Ensure to set the files attribute with a ActionDispatch::Http::UploadedFile object.
>2. Then call .attach on files with an activestorage blob object.

Is a test like this:
```ruby
  test "attaches two files" do
    user = User.new(name: 'Tina', files: [fixture_file_upload("image.gif")])
    user.files.attach create_blob(filename: "racecar.jpg")

    assert_equal 2, user.files.size
    assert_equal "image.gif", user.files.first.filename.to_s
    assert_equal "racecar.jpg", user.files.second.filename.to_s
  end
```

And that test passes on main 🤔 thoughts?

**Comment by muyiwaoyeniyi** [comment] 2021-06-11 16:46
@abhaynikam in my code, `replace_on_assign_to_many` is set to false.

@santib are you saying the steps I provided didn't highlight the problem?

**Comment by abhaynikam** [comment] 2021-06-11 17:10
@muyiwaoyeniyi Sorry. My bad. The PR description needs to be `replace_on_assign_to_many = false` when set to false. @santib In the test cases on main, `replace_on_assign_to_many` is true due to which they passed for you. Toggling the flag reproduces the issue. 😊

**Comment by muyiwaoyeniyi** [comment] 2021-06-11 17:18
@abhaynikam Thanks for clarifying and I appreciate the Rails team!

**Comment by zzak** [comment] 2023-07-28 23:44
So I looked into this and I think that this is intended behavior.

The following test cases pass, and are correct to me:

```ruby
  test "attaches two files" do
    user = User.new(name: "Tina", highlights: [fixture_file_upload("image.gif")])
    user.highlights.attach create_blob(filename: "racecar.jpg")

    assert_equal 2, user.highlights.size
    assert_equal "image.gif", user.highlights.first.filename.to_s
    assert_equal "racecar.jpg", user.highlights.second.filename.to_s
  end

  test "should attach two files with association setter and attach helper method" do
    user = User.new(name: "Tina", highlights: [fixture_file_upload("image.gif")])
    user.highlights.attach fixture_file_upload("racecar.jpg")
    user.save

    user.reload
    assert_equal 2, user.highlights.count
    assert_equal "image.gif", user.highlights.first.filename.to_s
    assert_equal "racecar.jpg", user.highlights.second.filename.to_s
    assert ActiveStorage::Blob.service.exist?(user.highlights.first.key)
    assert ActiveStorage::Blob.service.exist?(user.highlights.second.key)
  end
```

From: [this comment](https://github.com/rails/rails/issues/40827#issuecomment-859687927) and abhaynikam/rails/@dad69c5ea3 (without `append_on_assign`).

The thing that I didn't expect, but kinda makes sense, is that assign (`association=`) will replace the existing attachments, with this test:

```ruby
  test "should attach three files with association setter method" do
    user = User.new(name: "Tina", highlights: [fixture_file_upload("image.gif")])
    user.highlights = [fixture_file_upload("racecar.jpg")]
    user.highlights = [fixture_file_upload("report.pdf")]

    user.save

    user.reload
    assert_equal 3, user.highlights.count
    assert_equal "image.gif", user.highlights.first.filename.to_s
    assert_equal "racecar.jpg", user.highlights.second.filename.to_s
    assert_equal "report.pdf", user.highlights.third.filename.to_s
    assert ActiveStorage::Blob.service.exist?(user.highlights.first.key)
    assert ActiveStorage::Blob.service.exist?(user.highlights.second.key)
    assert ActiveStorage::Blob.service.exist?(user.highlights.third.key)
  end

# Failure:
# ActiveStorage::ManyAttachedTest#test_should_attach_three_files_with_association_setter_method 
# Expected: 3
#   Actual: 1
```

Maybe this is also intentional, but I'm concerned that this leaves dangling blobs that should be deleted?

The next step is to probably verify that and make sure there is test coverage.

For example, I would expect this test to fail without the `only: ActiveStorage::PurgeJob`, but it doesn't:

```ruby
  test "successfully updating an existing record to replace existing, independent attachments" do
    @user.vlogs.attach create_blob(filename: "funky.mp4"), create_blob(filename: "town.mp4")

    assert_no_enqueued_jobs do #only: ActiveStorage::PurgeJob do
      @user.update! vlogs: [ create_blob(filename: "whenever.mp4"), create_blob(filename: "wherever.mp4") ]
    end

    assert_equal "whenever.mp4", @user.vlogs.first.filename.to_s
    assert_equal "wherever.mp4", @user.vlogs.second.filename.to_s
  end
```

/cc @santib

**Comment by santib** [comment] 2023-07-29 15:11
@zzak Let's see if I understand this correctly:

1. the original bug report can be ignored since it requires the `replace_on_assign_to_many` config to be `false` and that was already deprecated and removed from Rails 7.1

2. When you said
> The thing that I didn't expect, but kinda makes sense, is that assign (association=) will replace the existing attachments, with this test:
> [code]
> Maybe this is also intentional, but I'm concerned that this leaves dangling blobs that should be deleted?

Why didn't you expect that behavior? I think it works similar to `ActiveRecord's has_many` that if you do `user.friends = [friend1]` it will replace the  association with the newly passed array, right?

Regarding the dangling blobs: That's a good point 👍 we can work on a fix that removes any orphan blob, just keep in mind that there are some border cases where one blob can be attached to multiple objects.

**Comment by zzak** [comment] 2023-07-29 21:51
1) For sure, thanks for checking! I will close this issue, sorry for hijacking!

2) Yeah, I wanted to make sure my assumptions were correct, now the next thing is to make sure that behavior is covered by tests.

3) Dangling blobs: Just checking that it's a known issue, and doesn't surprise anyone. Do you know of any other issues or PRs attempting to address it? We can move our discussion there or on discord. :pray:

Thanks!

**Closed by zzak** 2023-07-29 21:51 UTC
Labels: attached PR, activestorage
