### ISSUE TITLE
In request spec, default_url_options are processed only after first request

### ISSUE THREAD

**Issue by philipmw** [rails/rails#18505] opened 2015-01-14 07:41 UTC
I created a minimal Rails app that demonstrates the problem with Rails 4.2.0: https://github.com/philipmw/rails-default-url-options-bug

```
% rspec spec/controllers/catalog_controller_spec.rb
BEFORE GET
book_index_path=/book
book_index_path({})=/book
book_index_path(b: 'c')=/book?b=c
AFTER GET
default_url_options invoked
book_index_path=/book
book_index_path({})=/book?defarg=defval
book_index_path(b: 'c')=/book?b=c&defarg=defval
```

The difference between BEFORE and AFTER is:

```
get catalog_index_path
```

The effect is that the behavior of Rails URL helpers depends on the state of an integration test. Before a request, URL helpers behave one way; after a request, another way. This is unexpected and makes it more difficult to write tests.

**Comment by vipulnsward** [comment] 2015-01-14 08:16
@philipmw  can you try reproducing this using https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb ?

**Comment by rafaelfranca** [comment] 2015-01-14 13:41
Does it work fine at 4.1?

**Comment by philipmw** [comment] 2015-01-14 15:42
@rafaelfranca, 4.1 has the same test output as 4.2.

vipulnsward, nice template. I will adapt my code to that template in a few hours and post an update.

**Comment by philipmw** [comment] 2015-01-14 17:53
@vipulnsward, I rewrote the test case using your template and pushed to the same repo.

The problem appears to be specific to Rspec. With minitest, I had to `include Rails.application.routes.url_helpers` into the test case to get URL helpers, at which point the helpers worked consistently before and after a request. With rspec, however, I do not need to `include` that module.

When I do `include` that module into an rspec test case, it again works consistently before and after.

**Comment by pixeltrix** [comment] 2015-01-28 15:24
@philipmw maybe something is mutating the default_url_options hash in RSpec?

**Comment by jonathanhefner** [comment] 2020-05-25 20:04
I tried to reproduce this with both RSpec and Minitest, using this updated script:

<details>
  <summary>Updated script</summary>

  ```ruby
  # frozen_string_literal: true

  require "bundler/inline"

  gemfile(true) do
    source "https://rubygems.org"

    git_source(:github) { |repo| "https://github.com/#{repo}.git" }

    # Activate the gem you are reporting the issue against.
    gem "rails", "6.0.3"

    gem "rspec"
    gem "rspec-rails"
  end

  require "rack/test"
  require "action_controller/railtie"

  class TestApp < Rails::Application
    config.root = __dir__
    # config.hosts << "example.org"
    config.hosts.clear
    config.session_store :cookie_store, key: "cookie_store_key"
    secrets.secret_key_base = "secret_key_base"

    config.logger = Logger.new($stdout)
    Rails.logger  = config.logger

    routes.draw do
      resources :catalogs
      resources :books
    end
  end

  class CatalogsController < ActionController::Base
    include Rails.application.routes.url_helpers

    def default_url_options
      STDERR.puts "default_url_options invoked"
      {'defarg' => 'defval'}
    end

    def index
      render inline: books_path
    end
  end


  ##### RSpec

  require "rspec/rails"

  RSpec.describe CatalogsController, type: :request do
    # Commenting out this line doesn't seem to make a difference:
    include Rails.application.routes.url_helpers

    it 'generates URLs correctly' do
      puts "BEFORE GET (RSpec)"
      puts "catalogs_path=#{catalogs_path}"
      puts "catalogs_path({})=#{catalogs_path({})}"
      puts "catalogs_path(b: 'c')=#{catalogs_path(b: 'c')}"

      get catalogs_path
      expect(response.body).to eq '/books?defarg=defval'

      puts "AFTER GET (RSpec)"
      puts "catalogs_path=#{catalogs_path}"
      puts "catalogs_path({})=#{catalogs_path({})}"
      puts "catalogs_path(b: 'c')=#{catalogs_path(b: 'c')}"
    end
  end


  ##### Minitest

  require "minitest/autorun"

  class BugTest < Minitest::Test
    include Rack::Test::Methods
    include Rails.application.routes.url_helpers

    def test_generates_urls_correctly
      puts "BEFORE GET (Minitest)"
      puts "catalogs_path=#{catalogs_path}"
      puts "catalogs_path({})=#{catalogs_path({})}"
      puts "catalogs_path(b: 'c')=#{catalogs_path(b: 'c')}"

      get catalogs_path
      assert_equal '/books?defarg=defval', last_response.body

      puts "AFTER GET (Minitest)"
      puts "catalogs_path=#{catalogs_path}"
      puts "catalogs_path({})=#{catalogs_path({})}"
      puts "catalogs_path(b: 'c')=#{catalogs_path(b: 'c')}"
    end

    private
      def app
        Rails.application
      end
  end
  ```
</details>

Here is the output I got:

```
BEFORE GET (RSpec)
catalogs_path=/catalogs
catalogs_path({})=/catalogs
catalogs_path(b: 'c')=/catalogs?b=c
I, [2020-05-25T14:49:40.183776 #29825]  INFO -- : Started GET "/catalogs" for 127.0.0.1 at 2020-05-25 14:49:40 -0500
default_url_options invoked
default_url_options invoked
AFTER GET (RSpec)
catalogs_path=/catalogs
catalogs_path({})=/catalogs?defarg=defval
catalogs_path(b: 'c')=/catalogs?b=c&defarg=defval
.

Finished in 0.0835 seconds (files took 6.78 seconds to load)
1 example, 0 failures

Run options: --seed 41373

# Running:

BEFORE GET (Minitest)
catalogs_path=/catalogs
catalogs_path({})=/catalogs
catalogs_path(b: 'c')=/catalogs?b=c
I, [2020-05-25T14:49:40.278036 #29825]  INFO -- : Started GET "/catalogs" for 127.0.0.1 at 2020-05-25 14:49:40 -0500
default_url_options invoked
default_url_options invoked
AFTER GET (Minitest)
catalogs_path=/catalogs
catalogs_path({})=/catalogs
catalogs_path(b: 'c')=/catalogs?b=c
.

Finished in 0.038369s, 26.0628 runs/s, 26.0628 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

Note that both tests ran in the same process, and Minitest ran after RSpec.  So it looks this is an RSpec issue.  Also, the presence of `include Rails.application.routes.url_helpers` in the spec doesn't seem to change anything anymore.

I'm going to close this for now, but feel free to add more information if it turns out Rails is at fault!

**Closed by jonathanhefner** 2020-05-25 20:04 UTC
Labels: With reproduction steps, actionpack
