### ISSUE TITLE
Rails 4.2 and sqlite3, inconsistent results when matching a text column with a ASCII-8BIT string

### ISSUE THREAD

**Issue by jplang** [rails/rails#18585] opened 2015-01-18 20:31 UTC
With sqlite3, when doing a query with a condition that matches a text column with an ASCII-8BIT encoded string, we get inconsistent results:
* when using a dynamic finder, no results are returned
* when using `#where` with hash condition, no results are returned
* when using `#where` with an array condition, expect results are returned

Here is a quick example where path is the text column:

```ruby
Loading test environment (Rails 4.2.0)
irb(main):001:0> p = "/test/some/path/in/the/repo"
=> "/test/some/path/in/the/repo"
irb(main):002:0> Change.where(:path => p).count
   (0.0ms)  SELECT COUNT(*) FROM "changes" WHERE "changes"."path" = ?  [["path", "/test/some/path/in/the/repo"]]
=> 2
# fine, now we encode the string to ASCII-8BIT
irb(main):003:0> p.encode! "ASCII-8BIT"
=> "/test/some/path/in/the/repo"
irb(main):004:0> Change.where(:path => p).count
   (0.0ms)  SELECT COUNT(*) FROM "changes" WHERE "changes"."path" = ?  [["path", "/test/some/path/in/the/repo"]]
=> 0
irb(main):005:0> Change.where("path = ?", p).count
   (1.0ms)  SELECT COUNT(*) FROM "changes" WHERE (path = '/test/some/path/in/the/repo')
=> 2
irb(main):006:0> Change.find_by_path(p)
  Change Load (0.0ms)  SELECT  "changes".* FROM "changes" WHERE "changes"."path" = ? LIMIT 1  [["path", "/test/some/path/in/the/repo"]]
=> nil
```

**Comment by sgrif** [comment] 2015-01-19 23:02
I'm pretty sure this is a duplicate of #18582, but I will double check.

**Comment by sgrif** [comment] 2015-01-19 23:33
I was unable to replicate the issue. Can you please provide a reproduction script using this as a template? https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

**Comment by jplang** [comment] 2015-01-28 21:44
Sure, here it is: https://gist.github.com/jplang/16ca110cd4a2d03f79ed
The 2 last assertions won't pass. Only seems to happen if the column is a text column.

```
  1) Failure:
BugTest#test_find_with_ascii_8bit_encoded_string [test.rb:54]:
Expected: 1
  Actual: 0
```

**Comment by sgrif** [comment] 2015-01-28 21:48
This is the expected behavior. In the last case we know to try and convert the encoding, since the column is a string. When using a string query, you're basically doing safe string interpolation, and we have no way to know if the value is going to a string or binary column.

**Comment by jplang** [comment] 2015-01-28 21:57
Then the expected behaviour changed from Rails 4.1.8 to Rails 4.2 (the whole test passes with Rails 4.1.8). This test also passes with Rails 4.2 and the other database adapters (mysql and postgresql).

**Comment by sgrif** [comment] 2015-01-28 22:08
Let me look a little bit deeper, since `"anystring"` shouldn't be changing values regardless of encoding.

**Comment by sgrif** [comment] 2015-01-28 22:08
> This test also passes with Rails 4.2 and the other database adapters (mysql and postgresql).

The conversion of string encodings is SQLite3 specific

**Comment by sgrif** [comment] 2015-01-28 22:10
Ah, I see the problem. We are only modifying the encoding for string columns, but not for text columns.

**Closed** 2015-01-28 22:20 UTC
Labels: activerecord, needs feedback
