### ISSUE TITLE
ActiveRecord joins interchanging the arguments?

### ISSUE THREAD

**Issue by pramodtech** [rails/rails#30604] opened 2017-09-14 23:14 UTC
### Steps to reproduce

**Setup**

```ruby
# rate_paln.rb
#  district_id 
#  base         
class RatePlan < ApplicationRecord
  has_many :rate_plan_details
end

# rate_plan_detail.rb
#  property_type 
#  term 
class RatePlanDetail < ApplicationRecord
  belongs_to :rate_plan
end
```
**Query**
```ruby
rate_plan_details = RatePlanDetail.joins(:rate_plan).where(rate_plan: { 
  district_id: 277, base: true })

rate_plan_details.where(term: 20, property_type: 'Residential' ).exists?
```

### Expected behavior
```sql
SELECT `rate_plan_details`.* FROM `rate_plan_details` 
INNER JOIN `rate_plans` ON `rate_plans`.`id` = `rate_plan_details`.`rate_plan_id` 
WHERE (`rate_plans`.`district_id` = 277 AND `rate_plans`.`base` = 1)

SELECT  1 AS one FROM `rate_plan_details` 
INNER JOIN `rate_plans` ON `rate_plans`.`id` = `rate_plan_details`.`rate_plan_id` 
WHERE `rate_plan_details`.`term` = 20 AND `rate_plan_details`.`property_type` = 'Residential' 
AND (`rate_plans`.`district_id` = 277 AND `rate_plans`.`base` = 1) LIMIT 1
```

### Actual behavior
```sql
SELECT `rate_plan_details`.* FROM `rate_plan_details` 
INNER JOIN `rate_plans` ON `rate_plans`.`id` = `rate_plan_details`.`rate_plan_id` 
WHERE (`rate_plans`.`district_id` = 277 AND `rate_plans`.`base` = 1)

SELECT  1 AS one FROM `rate_plan_details` 
INNER JOIN `rate_plans` ON `rate_plans`.`id` = `rate_plan_details`.`rate_plan_id` 
WHERE `rate_plan_details`.`term` = 277 AND `rate_plan_details`.`property_type` = 1 
AND (`rate_plans`.`district_id` = 20 AND `rate_plans`.`base` = 'Residential') LIMIT 1
```

### System configuration
**Rails 4.2.9**

**ruby 2.3.3p222**

**Comment by redtachyons** [comment] 2017-09-15 02:35
could not reproduce, https://gist.github.com/redtachyons/e827b6520085c3dd967ce83d3e156f43

**Comment by pramodtech** [comment] 2017-09-15 19:49
@redtachyons That is strange, though I can't reproduce with above test case but on my machine I can still reproduce it. Attached screenshot of my console. What can possibly be wrong with my local setup as everything else works just fine?
![console](https://user-images.githubusercontent.com/1197039/30500677-41ba3bb8-9a14-11e7-84a8-3f90ff4172fc.png)

**Comment by redtachyons** [comment] 2017-09-16 03:48
@pramod-sharma which database adapter you are using, also are you using any extra gems which monkey patch active record ?

**Comment by pramodtech** [comment] 2017-09-18 17:53
Yeah, I am using squeel gem and it appears that it is causing this issue. Thanks for help @redtachyons

**Comment by redtachyons** [comment] 2017-09-18 18:28
@pramodtech Welcome, Now you can close this issue 👍

**Closed** 2017-09-18 18:32 UTC
