### ISSUE TITLE
Rails 4.2 attributes setters overriding

### ISSUE THREAD

**Issue by andrey-skat** [rails/rails#18986] opened 2015-02-18 11:16 UTC
Attribute methods override fails in some cases
For example, we have model `User` with `email` attribute and we want to override setter 
```ruby
class User < ActiveRecord::Base
  def email=(value)
    super
  end
end    
```
When we do `first_or_create`
```ruby
User.where(email: 'email@email.com').first_or_create
```
we've got
```
NoMethodError: super: no superclass method `email=' for #<User id: nil, email: nil, created_at: nil, updated_at: nil>
```
After
```ruby
User.new
```
`first_or_create` works well.

**Comment by senny** [comment] 2015-02-18 15:07
@andrey-skat thank you for your report. Could you please attach an executable test-case to reproduce the issue? You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point.

**Comment by andrey-skat** [comment] 2015-02-18 16:40
gist for test case
https://gist.github.com/andrey-skat/84d3b2f0203391f45f3b

with activerecord 4.1.9 this test passes
if add `User.new` in the beginning of test this test passes

**Comment by sbhatore** [comment] 2015-02-19 04:07
Failed to reproduce the error mentioned. It successfully creates a new record of the given email in users table, if it doesn't exist.

**Comment by WizardOfOgz** [comment] 2015-02-19 22:26
Seeing this, too. I will try to get some solid examples for you.

**Comment by CraigCottingham** [comment] 2015-02-19 22:33
I'm having the exact same problem, and @andrey-skat's suggestion to add `User.new` gets me past it.

To clarify for anyone who comes in behind me, the fix looks like this:

```User.new
user = User.where(email: "email@example.com").first_or_create```

**Comment by sgrif** [comment] 2015-02-20 16:18
Duplicate of https://github.com/rails/rails/issues/18339

**Closed by sgrif** 2015-02-20 16:18 UTC
Labels: activerecord
