### ISSUE TITLE
Define custom URL helpers doesn't list route in /rails/info/routes

### ISSUE THREAD

**Issue by thomasvanholder** [rails/rails#52210] opened 2024-06-24 18:06 UTC
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "debug"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger

  routes.draw do
    get "/" => "test#index", :as => :root

    direct :homepage do
      "https://rubyonrails.org"
    end
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_root_path
    assert_includes routes.pluck(:alias), "root"
  end

  def test_returns_homepage_path
    assert_includes routes.pluck(:alias), "homepage"
  end

  private

  def app
    Rails.application
  end

  def routes
    Rails.application.routes.routes.map { |r| {alias: r.name, path: r.path.spec.to_s, controller: r.defaults[:controller], action: r.defaults[:action]} }
  end
end
```

### Expected behavior
When adding a custom URL helper by using the `direct` method, the route should be listed when viewing the existing routes on `/rails/info/routes` or through the rails routes command `rails routes | grep homepage`

### Actual behavior
The newly created path is accessible by the helper `hompeage_url`, yet it isn't listed when viewing the routes `/rails/info/routes` file.

### System configuration
**Rails version**: 7.1.1.3

**Ruby version**: 3.3.0

**Comment by rafaelfranca** [comment] 2024-06-26 20:01
Duplicate of #48866

**Closed by rafaelfranca** 2024-06-26 20:01 UTC
