### ISSUE TITLE
rescue_from ActiveRecord::DeleteRestrictionError - uninitialized constant when in production

### ISSUE THREAD

**Issue by athix** [rails/rails#43666] opened 2021-11-17 18:15 UTC
### Steps to reproduce

```terminal
$ rails new --api --database=postgresql
```

Modify application controller as follows:

```ruby
class ApplicationController < ActionController::API
  rescue_from ActiveRecord::DeleteRestrictionError, with: :not_processable

  # 422
  def not_processable(err)
    render json: { error: err.message }, status: :unprocessable_entity
  end
end
```

```terminal
$ RAILS_ENV=production rails c
/private/tmp/example/app/controllers/application_controller.rb:2:in `<class:ApplicationController>': uninitialized constant ActiveRecord::DeleteRestrictionError (NameError)
[truncated for brevity]
```

Thanks to @schneems for assistance with this.

You can apparently use the following require at the top of the file to properly load the constant:

```ruby
require 'active_record/associations'
```

We suspect that it's an issue with how zeitwerk is loading the constant. There are no issues loading the constant if you manually rescue from it in another controller inline (as opposed to using the rescue_from):

```ruby
begin
   # ...
rescue ActiveRecord::DeleteRestrictionError => e
  puts e
end

# Alternatively, this also works without issue:

def some_method
  # ...
rescue ActiveRecord::DeleteRestrictionError => e
  not_processable(e)
end
```

### Expected behavior

`rescue_from ActiveRecord::DeleteRestrictionError` works as intended within `app/controllers/application_controller.rb`

### Actual behavior

In production only, it fails to load the constant `ActiveRecord::DeleteRestrictionError`.

### System configuration

**Rails version**: `6.x`

**Ruby version**: `3.x`

**Comment by schneems** [comment] 2021-11-17 20:44
I was able to reproduce the problem from the given steps. I've not done any additional debugging. I'm not sure what existing tools/configuration we have for hinting to zeitwork where these constants live.

**Comment by aishbuilds** [comment] 2021-11-24 22:26
Hi @athix @schneems - It looks like this issue has been fixed. I tried replicating in latest `main` and `ActiveRecord::DeleteRestrictionError` auto loads well. 

Here's a quick walkthrough:

https://user-images.githubusercontent.com/4476196/143320312-80d6569d-e997-44fc-828a-6e6d35ececc9.mov

**Comment by athix** [comment] 2021-11-24 22:34
Thanks @aishbuilds, would you mind letting me know when that goes live in the next gem release?

**Comment by schneems** [comment] 2021-11-25 00:45
Thanks for the check @aishbuilds!

We can’t notify every issue when a version is released, that would be a bit tedious. You can use IFTTT along with github’s RSS feed of releases to trigger a notification. (like an email or text). I have that set up to notify me about jruby releases.

I’m going to close this since the issue is fixed on main. You might want to try on the 6.x branch and make sure it’s fixed there too otherwise we should open an issue (or re open this one) to ask for a backport.

**Closed by schneems** 2021-11-25 00:45 UTC
Labels: activerecord, With reproduction steps, autoloading

**Comment by skipkayhil** [comment] 2023-02-02 22:33
> This occurred for me with Rails `7.0.4.2`. I was previously using `7.0.4` without any issue.

If you have reproduction steps, please open a new issue. People are unlikely to see comments on 2 year old closed issues.
