### ISSUE TITLE
change_table alters default precision for datetime columns

### ISSUE THREAD

**Issue by jamesarosen** [rails/rails#46889] opened 2023-01-04 21:06 UTC
### Steps to reproduce
Create one or more migrations that use (A) `create_table` or `add_column` and (B) `change_table` to add `datetime` columns:

```rb
class TestPrecision < ActiveRecord::Migration[7.0]
  def change
    create_table :precision_tests do |t|
      t.string :name, null: false, index: { unique: true }
      t.datetime :dt_via_create_table
      t.timestamps
    end

    add_column :precision_tests, :dt_via_add_column, :datetime

    change_table :precision_tests, bulk: true do |t|
      t.column :dt_via_change_table, :datetime
    end
  end
end
```

Possibly related to #44358

### Expected behavior
Rails should generate the same (default) precision for all three columns.

### Actual behavior
Rails generates default precision for `dt_via_create_table` and `dt_via_add_column`, but `precision: nil` for `dt_via_change_table`. This difference appears in the `schema.rb`:

```rb
create_table "precision_tests", force: :cascade do |t|
  t.string "name", null: false
  t.datetime "dt_via_create_table"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
  t.datetime "dt_via_add_column"
  t.datetime "dt_via_change_table", precision: nil
  t.index ["name"], name: "index_precision_tests_on_name", unique: true
end
```

and in the database:
```
# \d precision_tests
                                              Table "public.precision_tests"
       Column        |              Type              | Collation | Nullable |                   Default
---------------------+--------------------------------+-----------+----------+---------------------------------------------
 id                  | bigint                         |           | not null | nextval('precision_tests_id_seq'::regclass)
 name                | character varying              |           | not null |
 dt_via_create_table | timestamp(6) without time zone |           |          |
 created_at          | timestamp(6) without time zone |           | not null |
 updated_at          | timestamp(6) without time zone |           | not null |
 dt_via_add_column   | timestamp(6) without time zone |           |          |
 dt_via_change_table | timestamp without time zone    |           |          |
Indexes:
    "precision_tests_pkey" PRIMARY KEY, btree (id)
    "index_precision_tests_on_name" UNIQUE, btree (name)
```

### System configuration
**Rails version**: 7.0.2

**Ruby version**: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [aarch64-linux-musl]

**PostgreSQL version**: PostgreSQL 14.4 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bi

**Comment by ghiculescu** [comment] 2023-01-06 04:17
Hmm. This isn't failing:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define {}

class Post < ActiveRecord::Base
end

class TestPrecisionMigration < ActiveRecord::Migration[7.0]
  def change
    create_table :posts do |t|
      t.string :name, null: false, index: { unique: true }
      t.datetime :dt_via_create_table
      t.timestamps
    end

    add_column :posts, :dt_via_add_column, :datetime

    change_table :posts, bulk: true do |t|
      t.column :dt_via_change_table, :datetime
    end
  end
end

class BugTest < Minitest::Test
  def test_migration_up
    TestPrecisionMigration.migrate(:up)
    Post.reset_column_information

    assert_equal 6, Post.columns_hash["dt_via_create_table"].sql_type_metadata.precision
    assert_equal 6, Post.columns_hash["dt_via_add_column"].sql_type_metadata.precision
    assert_equal 6, Post.columns_hash["dt_via_change_table"].sql_type_metadata.precision
  end
end
```

But maybe the issue is specific to schema.rb. Can you share a simple app to replicate the issue in?

**Comment by jamesarosen** [comment] 2023-01-06 20:38
Try it with postgresql instead of sqlite3. [Here's](https://github.com/jamesarosen/rails-46889-demo) an example app.

**Comment by fatkodima** [comment] 2023-01-07 16:32
I was able to reproduce the issue using the linked sample app. 
The bug was fixed in https://github.com/rails/rails/pull/46110, which was also backported to `7-0-stable` branch, but was not yet released.

**Closed** 2023-01-07 16:50 UTC
Labels: activerecord
