### ISSUE TITLE
sqlite3_adapter has conflict with new version of sqlite3 gem

### ISSUE THREAD

**Issue by jasnow** [rails/rails#35153] opened 2019-02-04 19:11 UTC
Line 12 of activerecord-6.0.0.beta1/lib/active_record/connection_adapters/sqlite3_adapter.rb
is 
```
gem "sqlite3", "~> 1.3.6"
```
and it conflicts with the new sqlite 1.4.0 gem release.

Getting these two messages:
```
LoadError: Error loading the 'sqlite3' Active Record adapter.
Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6),
already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.
```
and
```
Gem::LoadError: can't activate sqlite3 (~> 1.3.6), already activated
sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.
```

**Comment by sponomarev** [comment] 2019-02-04 23:30
@jasnow You can specify `gem "sqlite3", "~> 1.3.6"` in your Gemfile explicitly OR wait the new rails version to be released OR use master directly.

The original issue was fixed in #35154

**Closed** 2019-02-04 23:35 UTC
Labels: activerecord

**Comment by no-reply** [comment] 2019-02-04 23:37
@sponomarev any thoughts on what the work-around is for folks trying to test engines against existing rails versions?

My CI process generates rails apps for a supported Ruby/Rails build matrix to run the engine's suite against. I've thought about adding a generator to adjust the `Gemfile`, but [engine install breaks before any generator can run](https://gist.github.com/no-reply/d07c751074510ba4643484f1d19ddabc).

**Comment by sponomarev** [comment] 2019-02-05 02:59
@no-reply It looks that you're running some database-related code in `engine_cart:generate`. I guess the only solution here is to specify `sqlite3` version in your newly generated Gemfile.

**Comment by femotizo** [comment] 2019-02-09 12:24
> @jasnow You can specify `gem "sqlite3", "~> 1.3.6"` in your Gemfile explicitly OR wait the new rails version to be released OR use master directly.
> 
> The original issue was fixed in #35154

@jasnow  @sponomarev 
This solution worked for me 
https://stackoverflow.com/a/54606137/1960924

**Comment by jasnow** [comment] 2019-02-09 12:50
@femotizo  -  Thank you for confirming that this is real rails issue.

**Comment by WilliamBarela** [comment] 2019-02-15 08:48
It seems that this [pull request](https://github.com/rails/rails/commit/d9601fd622a08b8ef5346c10f00fb13328d34d76#diff-1b086e9c0c1a6b852fda7b3542d6957b) was trying to fix this issue.

However, trying this on both Ruby 2.3.3 and Ruby 2.5.3 with the latest version of Rails the Gemfile generated on a new Rails app still does not populate with the new sqlite3 dependency as mentioned [here](https://stackoverflow.com/questions/54529739/replace-gem-error-loading-the-sqlite3-active-record-adapter-while-creating)

**Comment by sponomarev** [comment] 2019-02-15 14:32
@WilliamBarela new versions with the patch has not been released yet

**Comment by jasnow** [comment] 2019-02-15 15:09
@sponomarev - Is it in master?

**Comment by sponomarev** [comment] 2019-02-15 15:49
@jasnow yup. And ported to all version branches

**Comment by jasnow** [comment] 2019-02-15 16:19
Check for 6.0 and 3.2 and both fixed the above error so I'm looking forward to the gem's release. I had to pin 36 "canary" repos that I maintain.

**Comment by zhenxingdev** [comment] 2019-03-01 01:56
Encounter the same problem, ask for help! ! There is no corresponding solution in the official, there are many ways to deal with google search.

@jasnow

**Comment by puntodamar** [comment] 2019-03-15 13:16
manually update `sqlite3_adapter.rb` works for me.
Is this safe?
source : https://stackoverflow.com/questions/54527277/cant-activate-sqlite3-1-3-6-already-activated-sqlite3-1-4-0/54606137

**Comment by sikachu** [comment] 2019-03-15 15:23
@puntodamar probably not, since you'll have to do that on every platform you deploy to.

I'd suggest either pin sqlite to 1.3, or point Rails to `5-2-stable` branch for the time being while the core team is preparing for the release.

**Comment by sikachu** [comment] 2019-03-22 05:48
Just want to drop by a note that Rails Core team has released 5.2.3.rc1: https://weblog.rubyonrails.org/2019/3/22/Rails-5-2-3-rc1-has-been-released/ It should contain the relax dependency requirement of sqlite, fixing the issue you are seeing.

5.2.3 should be out by next week if there is no regression found.

**Comment by jasnow** [comment] 2019-03-22 13:44
@sikachu - Are you going to "relax dependency requirement of sqlite" for Rails 6.0.0 too?
PS. I have only 1 repo with 5.2.2.x. I have verified that the new version removes the sqlite3 workaround (THANKS).

**Comment by sikachu** [comment] 2019-03-22 13:46
(I was not the one who fixed it, I just relay the news)

But yes, the same fix in in `master`, so you should have no problem with this since 6.0.0.beta3 until the final 6.0.0 release.

**Comment by jasnow** [comment] 2019-03-22 18:46
@sikachu - Are they going to backport this "relax dependency requirement of sqlite" for pre-6.0.0 versions of Rails?

**Comment by sponomarev** [comment] 2019-03-22 19:11
@jasnow Yep. The fix will be present in the next manor releases.

**Comment by sikachu** [comment] 2019-03-23 05:26
@jasnow it should be in both 5.2.x and 6.0.0.beta3 and after. Those are the only two versions we provide bug fixes according to [our maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html).

**Comment by fffx** [comment] 2019-12-31 17:27
Today, when I use `git biset ` to find another bug in rails encountered this issue happens in v5.0.0.rc1, which confused me a lot, should we fix this in old versions too?
