### ISSUE TITLE
Where query with `>` or `<` does not use binds

### ISSUE THREAD

**Issue by schneems** [rails/rails#31219] opened 2017-11-24 20:53 UTC
### Steps to reproduce

```ruby
Issue.where("id < ?", 33).first
```

Produces

```sql
Issue Load (0.7ms)  SELECT  "issues".* FROM "issues" WHERE (id < 33) ORDER BY "issues"."id" ASC LIMIT $1  [["LIMIT", 1]]
```

Note that the id value `33` is not using a bind parameter but is instead hard coded into the query.

**Rails version**: 5.1.4

**Ruby version**: 2.5.0.preview1

**Comment by fatkodima** [comment] 2017-12-10 12:44
It looks like **every** (not just with `<` or `>`) `where` query with string expression not uses binds. This query `Issue.where("id = ?", 33).first` does not work with binds also.
Internally, for future query assembling it is simply converted into string here https://github.com/rails/rails/blob/cf0fcbe7f6fd52b3455af99b61ef2c40e6a0062e/activerecord/lib/active_record/relation/where_clause_factory.rb#L14 without any tries to use provided binds.

**Comment by eugeneius** [comment] 2017-12-21 00:35
https://github.com/rails/rails/commit/cbcdecd2c55fca9613722779231de2d8dd67ad02

> It was noted that we can probably eventually change `where("foo = ?", 1)` to use a bind param

**Comment by composerinteralia** [comment] 2018-01-26 21:20
I have a branch that uses bind params for `"foo = ?"`, `"foo < ?"`, `"foo <= ?"`, `"foo > ?"`, and `"foo >= ?"`. I should be able to make a PR early next week, but I am curious if there is a standard app we use for benchmarking.

**Comment by sgrif** [comment] 2018-01-26 23:37
I'm going to close this, as it's not a bug. I do eventually want to change this to start using bind params (it's a deeper structural change that is not going to be easy to make), but this is currently the expected behavior.

**Closed by sgrif** 2018-01-26 23:37 UTC
Labels: activerecord, pinned
