### ISSUE TITLE
Many uses of deprecated "Using last argument as keyword parameters" in actionpack, active*

### ISSUE THREAD

**Issue by J-Vaughan** [rails/rails#39161] opened 2020-05-06 04:40 UTC
### Steps to reproduce
**Environment**

- rails 6.0.2.2
- basically everything 6.0.2.2

I installed rails for the first time on this machine today, created a new project, using the newest (stable) versions of all dependencies.

**On** macOS 10.15.4

### Expected behaviour
No unnecessary warnings from core modules/gems, I assume.

### Actual behaviour
As far as I've seen, most of the commands function as normal, but when running essentially any `rails xxxx` command, warnings are spat out to the effect of:

```
% rails db:create
/usr/local/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
/usr/local/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
/usr/local/lib/ruby/gems/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
/usr/local/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/postgresql/oid/specialized_string.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
Created database 'xxxxxx_development'
Created database 'xxxxxx_test'
```

### System configuration
**Rails version**: Rails 6.0.2.2

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

**Comment by midhun-at-vineti** [comment] 2020-05-06 06:10
Tested this on:

### Environment A:
- Rails 6.0.2.2
- Ruby v2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]

#### Result:
Unable to reproduce. 

## Environment B:
- Rails 6.0.2.2
- Ruby v2.7.0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

#### Result: 
Able to reproduce this issue. 

```
bundle exec rails db:create
/Users/midhun/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/midhun/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
```

```
bundle exec rails db:migrate
/Users/midhun/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/midhun/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
/Users/midhun/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:212: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/midhun/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:274: warning: The called method `transaction' is defined here
/Users/midhun/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb:503: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/midhun/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/timestamp.rb:127: warning: The called method `create_or_update' is defined here
```

**Comment by kamipo** [comment] 2020-05-06 06:18
Can you try to check Rails 6.0.3.rc1?

**Comment by midhunkrishna** [comment] 2020-05-06 12:06
@kamipo I just tested this on Rails: 6.0.3rc1, ruby: 2.7.0p0, and it looks like the warnings are not present there. 

```bash
$ bundle show rails
[DEPRECATED] use `bundle info rails` instead of `bundle show rails`
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
/Users/romeo/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rails-6.0.3.rc1

$ rbenv local
2.7.0

$ bundle exec rake db:create
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'

$ bundle exec rake db:migrate
$
```

cc: @J-Vaughan

**Comment by eileencodes** [comment] 2020-05-06 12:58
These are fixed in master and 6.03 so I'm going to close this. 6.0.3 final will be released soon.

**Closed by eileencodes** 2020-05-06 12:58 UTC

**Comment by J-Vaughan** [comment] 2020-05-06 14:24
Thank you for investigating the issue!

**Comment by candim** [comment] 2020-05-06 14:37
Why do I keep getting all these emails I don't understand what this is and
I have never signed up for u all pls quit sending me emails

**Comment by J-Vaughan** [comment] 2020-05-06 16:33
Hey @candim!

I assume since you forked rails, you were automatically signed up to "watch" it. You can turn this off by:
- Scrolling to the top of the page, where you'll see "Used By xxx | Watch xxx | Star xxx | Fork xxx"
- Clicking on Watch
- Selecting "Not Watching"

I hope this helps you :)
