### ISSUE TITLE
neither change_column_default nor change_column will remove a default value

### ISSUE THREAD

**Issue by pmeno** [rails/rails#18784] opened 2015-02-02 17:31 UTC
I tried to remove a default value from a text field and and had to generate three different migrations to finally get it working. `change_column_default` and `change_column ....,default: nil` don't behave as expected and do nothing. `change_column_null ...,true` was the only schema action that worked for me. Any particular reason for this?

https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb

**Comment by rafaelfranca** [comment] 2015-02-02 17:32
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by pmeno** [comment] 2015-02-02 17:33
I'm not seeing how this isn't an issue? Two functions that do the exact same thing don't do the exact same thing.

**Comment by rafaelfranca** [comment] 2015-02-02 17:34
It should work since it is a documented and even tested behavior. If you believe it is not working could you try to reproduce using this script? Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by senny** [comment] 2015-03-05 10:37
@pmeno could you please provide a way to reproduce? This will go a long way in solving the issue.

**Comment by imanel** [comment] 2015-03-24 18:15
Ok - this one is strange. Test:

**Comment by imanel** [comment] 2015-03-24 18:18
Ok - this one is strange. Test:
``` ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.1'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :ccs, force: true do |t|
    t.integer :value, default: 1
  end

  create_table :ccds, force: true do |t|
    t.integer :value, default: 1
  end

  create_table :ccns, force: true do |t|
    t.integer :value, default: 1
  end

  change_column :ccs, :value, :integer, default: nil
  change_column_default :ccds, :value, nil
  change_column_null :ccns, :value, true
end

class CC < ActiveRecord::Base; end
class CCD < ActiveRecord::Base; end
class CCN < ActiveRecord::Base; end

class BugTest < Minitest::Test
  def test_change_column
    cc = CC.create
    assert_equal nil, cc.value
  end

  def test_change_column_default
    ccd = CCD.create
    assert_equal nil, ccd.value
  end

  def test_change_column_null
    ccn = CCN.create
    assert_equal nil, ccn.value
  end
end
```

Result:
```
  1) Failure:
BugTest#test_change_column_null [test.rb:49]:
Expected: nil
  Actual: 1

3 runs, 3 assertions, 1 failures, 0 errors, 0 skips
```

What is bothering me are how migrations are done:
```
-- create_table(:ccs, {:force=>true})
D, [2015-03-24T19:09:37.149250 #71333] DEBUG -- :    (0.4ms)  CREATE TABLE "ccs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" integer DEFAULT 1) 
   -> 0.0058s
-- create_table(:ccds, {:force=>true})
D, [2015-03-24T19:09:37.150625 #71333] DEBUG -- :    (0.3ms)  CREATE TABLE "ccds" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" integer DEFAULT 1) 
   -> 0.0013s
-- create_table(:ccns, {:force=>true})
D, [2015-03-24T19:09:37.151437 #71333] DEBUG -- :    (0.2ms)  CREATE TABLE "ccns" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" integer DEFAULT 1) 
   -> 0.0007s
-- change_column(:ccs, :value, :integer, {:default=>nil})
D, [2015-03-24T19:09:37.151781 #71333] DEBUG -- :    (0.1ms)  begin transaction
D, [2015-03-24T19:09:37.154681 #71333] DEBUG -- :    (0.5ms)  CREATE TEMPORARY TABLE "accs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" integer DEFAULT 1) 
D, [2015-03-24T19:09:37.155234 #71333] DEBUG -- :    (0.1ms)  SELECT * FROM "ccs"
D, [2015-03-24T19:09:37.155535 #71333] DEBUG -- :    (0.2ms)  DROP TABLE "ccs"
D, [2015-03-24T19:09:37.156096 #71333] DEBUG -- :    (0.1ms)  CREATE TABLE "ccs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" integer) 
D, [2015-03-24T19:09:37.156606 #71333] DEBUG -- :    (0.0ms)  SELECT * FROM "accs"
D, [2015-03-24T19:09:37.157106 #71333] DEBUG -- :    (0.4ms)  DROP TABLE "accs"
D, [2015-03-24T19:09:37.157521 #71333] DEBUG -- :    (0.3ms)  commit transaction
   -> 0.0060s
-- change_column_default(:ccds, :value, nil)
D, [2015-03-24T19:09:37.157987 #71333] DEBUG -- :    (0.1ms)  begin transaction
D, [2015-03-24T19:09:37.158646 #71333] DEBUG -- :    (0.2ms)  CREATE TEMPORARY TABLE "accds" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" integer DEFAULT 1) 
D, [2015-03-24T19:09:37.159175 #71333] DEBUG -- :    (0.1ms)  SELECT * FROM "ccds"
D, [2015-03-24T19:09:37.159417 #71333] DEBUG -- :    (0.2ms)  DROP TABLE "ccds"
D, [2015-03-24T19:09:37.160007 #71333] DEBUG -- :    (0.1ms)  CREATE TABLE "ccds" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" integer) 
D, [2015-03-24T19:09:37.160442 #71333] DEBUG -- :    (0.0ms)  SELECT * FROM "accds"
D, [2015-03-24T19:09:37.160732 #71333] DEBUG -- :    (0.2ms)  DROP TABLE "accds"
D, [2015-03-24T19:09:37.160978 #71333] DEBUG -- :    (0.2ms)  commit transaction
   -> 0.0033s
-- change_column_null(:ccns, :value, true)
D, [2015-03-24T19:09:37.161292 #71333] DEBUG -- :    (0.0ms)  begin transaction
D, [2015-03-24T19:09:37.161943 #71333] DEBUG -- :    (0.2ms)  CREATE TEMPORARY TABLE "accns" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" integer DEFAULT 1) 
D, [2015-03-24T19:09:37.162396 #71333] DEBUG -- :    (0.1ms)  SELECT * FROM "ccns"
D, [2015-03-24T19:09:37.162657 #71333] DEBUG -- :    (0.1ms)  DROP TABLE "ccns"
D, [2015-03-24T19:09:37.163232 #71333] DEBUG -- :    (0.1ms)  CREATE TABLE "ccns" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" integer DEFAULT 1) 
D, [2015-03-24T19:09:37.163700 #71333] DEBUG -- :    (0.0ms)  SELECT * FROM "accns"
D, [2015-03-24T19:09:37.163956 #71333] DEBUG -- :    (0.2ms)  DROP TABLE "accns"
D, [2015-03-24T19:09:37.164124 #71333] DEBUG -- :    (0.1ms)  commit transaction
   -> 0.0031s
```
It looks like despite providing valid argument to [change_column_null](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L461) it's not modifying table... Any idea what could be wrong here? I'm also little confused about how different are calls from mentioned code and in logger - I might be missing something.

**Comment by senny** [comment] 2015-06-22 14:25
@imanel I'm not sure I understand your script. `change_column_null` doesn't set the columns default but wether a column can be null or not. Since `null: true` is the default the call in your example doesn't modify the table. If you change it to `change_column_null false` you'll see that it appends a NOT NULL constraint.

@pmeno I'm going to close this issue. If you still experience the problem please provide a [sample script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) to reproduce the issue and I'll gladly reopen.

**Closed by senny** 2015-06-22 14:25 UTC
Labels: activerecord, needs feedback
