### ISSUE TITLE
Undefined method `start' for #<Thread:0x007fc17f821ca0>

### ISSUE THREAD

**Issue by colinramsay** [rails/rails#24999] opened 2016-05-12 15:53 UTC
### Steps to reproduce
I started working on a new Rails 5 RC1 project with the --api flag. I see this problem when I run `bin/rails routes`.

### Expected behavior
Routes should be shown

### Actual behavior
An error is thrown:

```
rails aborted!
NoMethodError: undefined method `start' for #<Thread:0x007fc17f821ca0>
Did you mean?  status
ruby-2.3.1@xxxxx/gems/activesupport-5.0.0.rc1/lib/active_support/evented_file_update_checker.rb:31:in `initialize'
```

### System configuration
**Rails version**: 5.0.0.rc1
**Ruby version**: ruby-2.3.1
**Gemfile.lock**: http://pastebin.com/raw/cFgHp6Qu

I have tried this with listen v3.0.7 and v3.1.4. I've added a number of gems to the project (see Gemfile.lock) so it could be an interaction between them. Some evidence for this is that `bin/rails routes RAILS_ENV=test` works as expected.

**Comment by rafaelfranca** [comment] 2016-05-12 16:07
Can you please provide a sample application that reproduces the error?

**Comment by colinramsay** [comment] 2016-05-12 16:15
https://github.com/colinramsay/rails-24999

I use rvm so it's set up to create a new gemset and use ruby 2.3.1 via the config files. If you do that then you should be able to run `bundle install` then `bin/rails routes` to see the problem.

FWIW I am on OSX 10.11.3 (15D21).

**Comment by sblackstone** [comment] 2016-05-12 16:43
```
(byebug) t = Listen.to(dtw, &method(:changed))

#<Thread:0x007fd7c5ad2470@/Users/sblackstone/.rvm/gems/ruby-2.3.1@rails-24999/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapter.rb:299 run>



```

**Comment by vipulnsward** [comment] 2016-05-12 18:21
Strangely this is loading listen version: 1.3.1 for me, on this App, that is causing the issue. Gemfile has 3+ version.

**Comment by colinramsay** [comment] 2016-05-13 13:51
@sblackstone if I remove brakeman, it works.

**Comment by KudosX** [comment] 2016-05-13 18:59
that's weird.  I had the same error with 5.0.0.rc1 and removing brakeman also solved the problem.  Not sure how you figured out brakeman was causing the issue but, thanks a bunch!  I ripped out RVM and started using chruby so, thought my error had to do with that fiasco.

**Comment by rafaelfranca** [comment] 2016-05-13 19:26
Closing since this is a issue with brakeman.

**Closed by rafaelfranca** 2016-05-13 19:26 UTC
Labels: activesupport

**Comment by presidentbeef** [comment] 2016-05-17 22:16
* Brakeman should be added to Gemfiles with `require: false` since you don't want it running with the application
* There is apparently a conflict between the version of `listen` vendored by Sass (vendored by Brakeman) and the one explicitly added as a dependency.
* Next version of Brakeman won't load vendored dependencies immediately which may mostly avoid the Gemfile issue
