### ISSUE TITLE
Error during failsafe response: undefined method `valid_encoding?' when passing :controller param

### ISSUE THREAD

**Issue by Linuus** [rails/rails#37252] opened 2019-09-20 09:23 UTC
### Steps to reproduce
I wasn't able to get this to fail in the minimal test apps so here's instructions:

1. Generate a new Rails app: `rails new foobar`
2. Run `rails s`
3. Make a call to a non existing route passing a `:controller` param:

```sh
curl -XPOST http://localhost:3000/foobar -d '{ "controller": { "foo": "bar" } }' -H 'Content-Type: application/json'
```

### Expected behavior
It should return a 404/routing error.

### Actual behavior
The server crashes with:

```
Started POST "/foobar" for ::1 at 2019-09-20 11:21:22 +0200

ActionController::RoutingError (No route matches [POST] "/foobar"):

actionpack (6.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
webpacker (4.0.7) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.0) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Error during failsafe response: undefined method `valid_encoding?' for {"foo"=>"bar"}:ActiveSupport::HashWithIndifferentAccess
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/http/parameters.rb:90:in `set_binary_encoding'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/http/parameters.rb:60:in `parameters'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/http/mime_negotiation.rb:66:in `block in formats'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/request.rb:59:in `fetch'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/request.rb:59:in `fetch_header'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/http/mime_negotiation.rb:64:in `formats'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/public_exceptions.rb:25:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/rack/logger.rb:38:in `call_app'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `block in call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/static.rb:126:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/webpacker-4.0.7/lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/engine.rb:526:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
  /Users/linus/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

It only happens if I pass the `controller` param and the content type above.

### System configuration
**Rails version**: 6.0.0 (and 5.x)

**Ruby version**: 2.5.5

**Comment by latortuga** [comment] 2019-09-20 16:19
Looks like this was introduced by 92209356c31 @eileencodes @tenderlove @ttanimichi you all three are tagged. Problem is that if controller is present, it assumes it's a string which is valid in the normal course of events, but not I guess should not be assumed.

I'm thinking we bail out on the early return if controller is not a String, or perhaps add a `.to_s` in there.

**Comment by ce07c3** [comment] 2019-09-21 19:00
`controller` is a user supplied dictionary in the above case. Would it be possible to separate more strictly between parsing route parameters and mapping these to controller and action, and post data?

**Comment by latortuga** [comment] 2019-09-23 15:25
> `controller` is a user supplied dictionary in the above case. Would it be possible to separate more strictly between parsing route parameters and mapping these to controller and action, and post data?

I don't think that passing a `controller` param as a dictionary is a valid way of interacting with the Rails router. However, I agree that it probably shouldn't have gotten to this point without some more strict checking so I therefore agree with the idea of separating. The router *does* support routing by controller param though.

The reason I proposed modifying the early return or checking for a string is because the only valid value of a `controller` param to the router is a String. Perhaps it's more of a band aid fix though.

**Comment by ce07c3** [comment] 2019-09-23 15:30
> > `controller` is a user supplied dictionary in the above case. Would it be possible to separate more strictly between parsing route parameters and mapping these to controller and action, and post data?
> 
> I don't think that passing a `controller` param as a dictionary is a valid way of interacting with the Rails router. However, I agree that it probably shouldn't have gotten to this point without some more strict checking so I therefore agree with the idea of separating. The router _does_ support routing by controller param though.
> 
> The reason I proposed modifying the early return or checking for a string is because the only valid value of a `controller` param to the router is a String. Perhaps it's more of a band aid fix though.

But this is not the issue, right? The Rails router should not work user supplied POST data, but on the path.

**Comment by latortuga** [comment] 2019-09-23 16:26
Good call! I just tried this out myself on a Rails 5 app I have sitting around and I got these deprecation warnings:

```
DEPRECATION WARNING: Using a dynamic :controller segment in a route is deprecated and will be removed in Rails 6.0.
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0.
```

So, yes you're right, user-supplied `controller` should not be used in this situation at all. Sorry for the diversion!

**Comment by ce07c3** [comment] 2019-12-22 17:13
I don't think this has been addressed.

**Comment by Linuus** [comment] 2020-03-21 18:44
The original report was on 6.0. I can see if I can test master as well when I get some time.

**Comment by Linuus** [comment] 2020-06-22 06:18
Did a quick test this morning on edge rails and it fails. It's really easy to reproduce locally, but it doesn't fail when using tests in the minimal bug template.

How to reproduce:
```sh
❯ rails new foobar --edge
❯ cd foobar
❯ rails s
```

Make a request to a non-existing route and supply a param called `controller`:

```sh
❯ curl -XPOST http://localhost:3000/foobar -d '{ "controller": { "foo": "bar" } }' -H 'Content-Type: application/json'
500 Internal Server Error
```

Error:
```sh
=> Booting Puma
=> Rails 6.0.3.2 application starting in development 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 3.12.6 (ruby 2.6.5-p114), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
Started POST "/foobar" for ::1 at 2020-06-22 08:12:47 +0200
   (2.3ms)  SELECT sqlite_version(*)
  
ActionController::RoutingError (No route matches [POST] "/foobar"):
  
rails (cd1f219eb935) actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (b18a195183f8) lib/web_console/middleware.rb:132:in `call_app'
web-console (b18a195183f8) lib/web_console/middleware.rb:28:in `block in call'
web-console (b18a195183f8) lib/web_console/middleware.rb:17:in `catch'
web-console (b18a195183f8) lib/web_console/middleware.rb:17:in `call'
rails (cd1f219eb935) actionpack/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
rails (cd1f219eb935) railties/lib/rails/rack/logger.rb:37:in `call_app'
rails (cd1f219eb935) railties/lib/rails/rack/logger.rb:26:in `block in call'
rails (cd1f219eb935) activesupport/lib/active_support/tagged_logging.rb:80:in `block in tagged'
rails (cd1f219eb935) activesupport/lib/active_support/tagged_logging.rb:28:in `tagged'
rails (cd1f219eb935) activesupport/lib/active_support/tagged_logging.rb:80:in `tagged'
rails (cd1f219eb935) railties/lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
rails (cd1f219eb935) actionpack/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
rails (cd1f219eb935) actionpack/lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
rails (cd1f219eb935) activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
rails (cd1f219eb935) actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'
rails (cd1f219eb935) actionpack/lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
rails (cd1f219eb935) actionpack/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (d099e066931b) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
rails (cd1f219eb935) railties/lib/rails/engine.rb:527:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Error during failsafe response: undefined method `valid_encoding?' for {"foo"=>"bar"}:ActiveSupport::HashWithIndifferentAccess
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/ht
tp/parameters.rb:89:in `set_binary_encoding'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/ht
tp/parameters.rb:60:in `parameters'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/ht
tp/mime_negotiation.rb:66:in `block in formats'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:69:in `fetch'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:69:in `fetch_header'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/ht
tp/mime_negotiation.rb:64:in `formats'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/public_exceptions.rb:25:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/show_exceptions.rb:50:in `render_exception'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/show_exceptions.rb:36:in `rescue in call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/show_exceptions.rb:31:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/railties/lib/rails/rack/logger.rb
:37:in `call_app'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/railties/lib/rails/rack/logger.rb
:26:in `block in call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/activesupport/lib/active_support/
tagged_logging.rb:80:in `block in tagged'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/activesupport/lib/active_support/
tagged_logging.rb:28:in `tagged'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/activesupport/lib/active_support/
tagged_logging.rb:80:in `tagged'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/railties/lib/rails/rack/logger.rb
:26:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13
:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/remote_ip.rb:81:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/request_id.rb:27:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/activesupport/lib/active_support/
cache/strategy/local_cache_middleware.rb:29:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/executor.rb:14:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/static.rb:126:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/host_authorization.rb:82:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/webpacker-d099e066931b/lib/webpacker/dev_server_prox
y.rb:25:in `perform_request'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/railties/lib/rails/engine.rb:527:
in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_t
hread'
```

**Comment by Linuus** [comment] 2020-06-22 06:21
I guess the stacktrace is a bit cleaner in production env

```
❯ RAILS_ENV=production rails s
=> Booting Puma
=> Rails 6.0.3.2 application starting in production 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 3.12.6 (ruby 2.6.5-p114), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Error during failsafe response: undefined method `valid_encoding?' for {"foo"=>"bar"}:ActiveSupport::HashWithIndifferentAccess
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/ht
tp/parameters.rb:89:in `set_binary_encoding'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/ht
tp/parameters.rb:60:in `parameters'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/ht
tp/mime_negotiation.rb:66:in `block in formats'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:69:in `fetch'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:69:in `fetch_header'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/ht
tp/mime_negotiation.rb:64:in `formats'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/public_exceptions.rb:25:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/show_exceptions.rb:50:in `render_exception'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/show_exceptions.rb:36:in `rescue in call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/show_exceptions.rb:31:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/railties/lib/rails/rack/logger.rb
:37:in `call_app'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/railties/lib/rails/rack/logger.rb
:26:in `block in call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/activesupport/lib/active_support/
tagged_logging.rb:80:in `block in tagged'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/activesupport/lib/active_support/
tagged_logging.rb:28:in `tagged'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/activesupport/lib/active_support/
tagged_logging.rb:80:in `tagged'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/railties/lib/rails/rack/logger.rb
:26:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/remote_ip.rb:81:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/request_id.rb:27:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/activesupport/lib/active_support/
cache/strategy/local_cache_middleware.rb:29:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/executor.rb:14:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/actionpack/lib/action_dispatch/mi
ddleware/host_authorization.rb:76:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-cd1f219eb935/railties/lib/rails/engine.rb:527:
in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
  /Users/linus/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_t
hread'
```

**Comment by Linuus** [comment] 2020-09-21 07:16
Still an issue on edge.

**Comment by eileencodes** [comment] 2020-09-21 19:46
I wrote a test locally and was able to reproduce. This was fixed by https://github.com/rails/rails/pull/40124 earlier today.

**Closed by eileencodes** 2020-09-21 19:46 UTC
Labels: actionpack

**Comment by Linuus** [comment] 2020-09-22 07:27
Awesome! Thanks.
