### ISSUE TITLE
Ruby injection comment at end of a view with no spaces after results in a blank page. 

### ISSUE THREAD

**Issue by cmendla** [rails/rails#25557] opened 2016-06-28 13:11 UTC
### Steps to reproduce

add a ruby injection with a todo comment at the very end of a view with no spaces after. 

i.e.  <% # TODO fix dropdown %> 

the view page is then blank except for the content of the application.html.erb. 

The page will function as normal after putting a space after the injection. 
### Expected behavior

Putting a comment with ruby injection should not cause a blank page. 
### Actual behavior

Putting a comment such as <% # TODO fix dropdown %> at the very end of a view with no spaces after causes a blank page. (running Puma in development mode). Content from layouts\application.html.erb is shown but nothing from the page. 

Adding a space after the injected comment will cause the page to appear as expected. 

This seems to be repeatable for my configuration
### System configuration

**Rails version**: rails (4.2.5.1, 4.2.5, 4.2.4)

**Ruby version**:  ruby 2.0.0p647 (2015-08-18) [i386-mingw32]

**Comment by rafaelfranca** [comment] 2016-06-28 14:06
Could you provide a sample application which reproduce the issue?

**Comment by cmendla-cct** [comment] 2016-06-30 17:17
[untitled1.zip](https://github.com/rails/rails/files/341966/untitled1.zip)

If you run this project and go to http://localhost:3000/examples, you will see a blank page. However, if you delete line 26  in untitled1\app\views\examples\index.html.erb which is <% # TODO testing %> with no spaces or other characters after the %> you will then see 

Listing Examples
New Example

This shows that an injected remark with no spaces will cause a blank page to display.

**Comment by Edouard-chin** [comment] 2016-07-01 04:16
You can resolve your issue by modifying so:
```erb
<% # TODO testing %> # Wrong
<%# TODO testing %> # Good
```
But IMHO it's a small bug that could be fixed:

`<% %>` Tells ERB to execute ruby, which in your case is a ruby comment. What happens is when the templates gets [compiled](https://github.com/rails/rails/blob/master/actionview/lib/action_view/template.rb#L283), the resulting value of the variable `code` is something looking like this:

```
"@output_buffer = output_buffer || ActionView::OutputBuffer.new;@output_buffer.safe_append='<h1>No Comment</h1>\n'.freeze; names.each do |name| \n@output_buffer.safe_append='  <li> '.freeze;@output_buffer.append=( name );@output_buffer.safe_append=' </li>\n'.freeze; end \n #LOL ;@output_buffer.to_s"
```

The important part is that when this will get evaluated, `@output_buffer` needs to be returned. In our case, ruby interpret the last line `#LOL ;@output_buffer.to_s"` as a full comment. The returning value of `code` is not `@output_buffer.to_s` anymore.

When you added the the new line at EOF, `#LOL\n ;@output_buffer.to_s"` doesn't get interpreted the same way

**Comment by rafaelfranca** [comment] 2016-07-01 04:31
@Edouard-chin nice investigation! Do you see any way to fix this behavior?

**Comment by Edouard-chin** [comment] 2016-07-01 04:49
Thanks! ❤️ 
Sure, I'll open a PR, I believe it will be easier for you to comment on it.

**Comment by Edouard-chin** [comment] 2017-10-05 17:34
This issue was fixed by https://github.com/rails/rails/commit/7da8d76206271bdf200ea201f7e5a49afb9bc9e7

**Comment by Edouard-chin** [comment] 2020-03-10 13:41
Closing this since the issue no longer appears when we switched to `Erubi`

**Closed by Edouard-chin** 2020-03-10 13:41 UTC
Labels: With reproduction steps, actionview, attached PR
