### ISSUE TITLE
counter_cache does not update the parent updated_at column when the count decrease

### ISSUE THREAD

**Issue by yzhanginwa** [rails/rails#20867] opened 2015-07-13 19:08 UTC
I have 2 models: Book and Chapter. Table books has column chapters_count.

class Book < ActiveRecord::Base
  has_many :chapters
end

class Chapter < ActiveRecord::Base
   belongs_to :book, counter_cache: true, touch: true
end

If I do this:

  chapter = @book.chapters.first
  chapter.book_id = nil
  chapter.save

The @book.chapters_count will decrease by 1, but the @book.updated_at does not change.

If I do this:

  chapter = Chapter.create
  chapter.book_id = @book.id
  chapter.save

The @book.chapter_count will increase by 1 , AND the @book.updated_at get updated.

This does not reasonable for me. I'm wondering if this is a but in my rails version 4.2.1.

Thanks,
Yi Zhang

**Comment by ccallebs** [comment] 2015-07-22 04:18
@yzhanginwa I was not able to duplicate your issue using the bug report template. Everything looks to be functioning as you expect.

https://gist.github.com/ccallebs/ea0802dbbcedb09984ea

**Comment by myrridin** [comment] 2015-08-13 23:50
I was also unable to reproduce this issue, even after modifying the script to point at rails 4.2.1.

https://gist.github.com/myrridin/d47b697bbd5c8673a7bc

Are you still experiencing this issue? What database are you using?

**Comment by rafaelfranca** [comment] 2015-08-13 23:53
@ccallebs @myrridin Thank you for creating the script.

@yzhanginwa looks like we can't reproduce you problem, so I'm closing this issue. Let us know if you can give us more information. Thanks

**Closed by rafaelfranca** 2015-08-13 23:53 UTC
