### ISSUE TITLE
ActiveStorage::Blob#purge_later with queue_adapter 'inline' raises NotImplementedError

### ISSUE THREAD

**Issue by SampsonCrowley** [rails/rails#32985] opened 2018-05-25 04:43 UTC
### Steps to reproduce

call `some_attachment.purge_later` in test environment when queue adapter is set to `:inline`

### Expected behavior
it should run the purge immediately

### Actual behavior
raises `NotImplementedError`

### System configuration
**Rails version**: 5.2.0

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**Comment by SampsonCrowley** [comment] 2018-05-25 04:44
```

**Comment by y-yagi** [comment] 2018-05-25 23:37
This looks like the expected behavior. 
As in error message, inline adapter does not support `purge_later`. Also, I do not think there is a need to change the behavior of `purge_later` by adapter. 
Is this not resolved by using async or test adapter in the test?

**Comment by y-yagi** [comment] 2018-05-28 22:46
As mentioned above, this is intentional behavior. So I will close. If you have any problems with using other adapters, please reopen them freely.

**Closed by y-yagi** 2018-05-28 22:46 UTC
