### ISSUE TITLE
An error with sqlite3, i just made the skeleton and this error appeared

### ISSUE THREAD

**Issue by Doyddin** [rails/rails#44687] opened 2022-03-14 18:39 UTC
### Steps to reproduce

```ruby
# Your reproduction script goes here
```bundle install

### Expected behavior
<!-- Tell us what should happen -->
the bundle installed and the app running
### Actual behavior
<!-- Tell us what happens instead -->
appears a error for every gem that uses activerecord which is ->
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/ext/bootsnap
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r
./siteconf20220314-9264-an0w4o.rb extconf.rb
creating Makefile

current directory:
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/ext/bootsnap
make DESTDIR\= clean

current directory:
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/ext/bootsnap
make DESTDIR\=
generating bootsnap-x64-mingw-ucrt.def
compiling bootsnap.c
make: gcc: No such file or directory
make: *** [Makefile:246: bootsnap.o] Erro 127

make failed, exit code 2
```
and when i try "gem pristine sqlite3 --version 1.4.2 this appears -> 
```
Restoring gems to pristine condition...
Temporarily enhancing PATH for MSYS/MINGW...
Using msys2 packages: mingw-w64-x86_64-sqlite3
Building native extensions. This could take a while...
ERROR:  While executing gem ... (Gem::Ext::BuildError)
    ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sqlite3-1.4.2/ext/sqlite3
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r ./siteconf20220314-16176-wojw9e.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby31-x64/bin/$(RUBY_BASE_NAME)
        --with-sqlcipher
        --without-sqlcipher
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib
        --with-sqlite3-config
        --without-sqlite3-config
        --with-pkg-config
        --without-pkg-config
C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:591:in `try_link0'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:609:in `try_link'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:711:in `try_ldflags'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:1895:in `pkg_config'
        from extconf.rb:35:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/sqlite3-1.4.2/mkmf.log

extconf failed, exit code 1
```
### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 3.1.1p18

**Comment by SkipKayhil** [comment] 2022-03-14 19:15
Seems to be a duplicate of #44158, there are some suggestion for fixes in the comments

**Comment by Edouard-chin** [comment] 2022-03-15 00:58
Thank you @SkipKayhil . I'll close this as it's a duplicate of #44158 and not related to Rails. Feel free to reopen it if you are still having issue after trying the suggested solutions @Doyddin

**Closed by Edouard-chin** 2022-03-15 00:58 UTC
