### ISSUE TITLE
ActiveRecord pluck id returns sporadic 'f' value: undefined method `to_i' for false:FalseClass

### ISSUE THREAD

**Issue by sgringwe** [rails/rails#18964] opened 2015-02-17 06:02 UTC
I am getting sporadic issues in production (roughly up to 10 times a week) where a pluck function call of ids returns a false boolean as one of the ids. It then errors when calling to_i on the false value in the type caster.

Error 1 (most common):
```
@school.user_ids
```
```
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/type/integer.rb:19:in `type_cast_from_database': undefined method `to_i' for false:FalseClass (ActionView::Template::Error)
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/result.rb:84:in `block (2 levels) in cast_values'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/result.rb:84:in `map'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/result.rb:84:in `block in cast_values'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/result.rb:83:in `map'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/result.rb:83:in `cast_values'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:181:in `pluck'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:58:in `ids_reader'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/associations/builder/collection_association.rb:66:in `user_ids'
	from app/presenters/analytics/index_presenter.rb:30:in `applications'
```

Error 2 (IN query shortened for brevity, but any more values in reality):
```
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec': PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "f"
LINE 1: ... 43051, 43052, 43053, 43054, 43055, 43056, 43057, 'f', 43059...
                                                             ^
: SELECT "career_fairs"."id" FROM "career_fairs" WHERE "career_fairs"."public" = 't' AND "career_fairs"."location_id" IN (43057, 'f', 43059, 43060, 'f', 43062, 43063, 43064, 43065, 43066, 43067, 43068, 43069, 43070, 43071) AND (end_date > '2015-02-17 01:11:27.100724') AND (1=1) (ActiveRecord::StatementInvalid)
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
  from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:336:in `select'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
  from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb:180:in `pluck'
  from app/controllers/career_fairs_controller.rb:42:in `block (2 levels) in index'
```

How does a false value leak into these calls? Running pluck again (in console for example) does not return false for any locations in database. It is a normal primary key id using normal rails schema.

**Comment by sgrif** [comment] 2015-02-17 15:43
Can you give any more details about the issue? Does it seem to only happen with a specific model? Without a script we can use to reproduce the issue (preferably using our template [here](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)), it's hard for us to do much about this. With regards to your specific question:

> How does a false value leak into these calls?

It shouldn't, especially since the integer type explicitly handles booleans. Hence why more info is needed.

**Comment by sgringwe** [comment] 2015-02-18 18:30
@sgrif unfortunately I don't have much more info other than it happens sporadically. I recently got a newish error that seems related:
```
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:94:in `type_cast': undefined method `type_cast_from_database' for nil:NilClass (ActionView::Template::Error)
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:42:in `original_value'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:37:in `value'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_set.rb:31:in `fetch_value'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/read.rb:93:in `_read_attribute'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods.rb:50:in `__temp__9646'
	from app/views/application/_topbar.html.haml:36:in `block in _app_views_application__topbar_html_haml__1372241991419791063_70181657051360'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
	from vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
	from app/views/application/_topbar.html.haml:35:in `_app_views_application__topbar_html_haml__1372241991419791063_70181657051360'
```
Sorry for the lack of info, I will continue trying to find out more.

**Comment by raouldevil** [comment] 2015-02-24 17:50
One of your problems may not be the `id`, but the arguments you are passing in for `"career_fairs"."location_id"`.

For example, if I do the following query: `User.where(id: [1,2])` generates the following SQL: ``users`.* FROM `users`  WHERE `users`.`id` IN (1, 2)`

This corresponds to this part of your query: `"career_fairs"."location_id" IN (43057, 'f', 43059, 43060, 'f', 43062, 43063, 43064, 43065, 43066, 43067, 43068, 43069, 43070, 43071)`

So at least one of your errors may be related to something strange going on in your stored database values.

**Comment by rafaelfranca** [comment] 2015-02-24 17:58
Right. Closing since we can't reproduce it. Thank you for reporting.

**Closed by rafaelfranca** 2015-02-24 17:58 UTC
Labels: activerecord, needs feedback

**Comment by sgrif** [comment] 2015-02-24 22:17
We should still never be generating `'f'` for an integer column, regardless of the values passed. Still, agreed we shouldn't leave this open since we don't have the information required to reproduce.

**Comment by sgringwe** [comment] 2015-02-25 00:59
Will update with information when I get it

**Comment by raouldevil** [comment] 2015-02-25 08:02
@sgringwe Do the query parameters for `"career_fairs"."location_id"` originate in your code somewhere or do they come directly from your database?

**Comment by sgringwe** [comment] 2015-02-25 23:00
@raouldevil They come directly from the database:
```
location_ids = Location.where(state: state).pluck(:id) # if the state is nil, we won't find anything
@state_public_career_fairs = CareerFair.where(public: true, location_id: location_ids).where('end_date > ?', Time.zone.now).where.not(id: @career_fairs.pluck(:id))
```

**Comment by cristianbica** [comment] 2015-02-26 08:56
@sgringwe what could help identifying the problem is (if you can):
- provide the schema.rb definition and the sql definition for those 2 tables (only the fields involved in the query)
- add some "debug"-ish code into your environment where you see this issue. Something like:
```ruby
begin
  locations = Location.where(state: state)
  @state_public_career_fairs = CareerFair.where(public: true, location_id: locations.pluck(:id)).where('end_date > ?', Time.zone.now).where.not(id: @career_fairs.pluck(:id))
rescue => e
  Rails.logger.info locations.to_sql
  Rails.logger.info locations.count
  Rails.logger.info locations.pluck(:id).inspect
  # and any info you might find usefull
 raise e #to don't alter your current flow
end
```

**Comment by sgringwe** [comment] 2015-02-26 18:03
I will give that a go, thanks @cristianbica

**Comment by sgringwe** [comment] 2015-07-09 16:14
Alright - I have some more information. At this point I am now on 4.2.1. Ruby 2.2.0. This is on a new method:

```
class StudentScreen < ActiveRecord::Base
  has_and_belongs_to_many :majors
  has_and_belongs_to_many :major_groups

  def combined_major_ids
    major_group_major_ids = major_groups.joins(school_majors: [:major])
    (major_ids.to_a + major_group_major_ids.pluck('majors.id')).flatten.compact.uniq
  rescue => e
    if major_group_major_ids
      Rails.logger.info "major_group_major_ids.to_sql:"
      Rails.logger.info major_group_major_ids.to_sql

      Rails.logger.info "major_group_major_ids.pluck('majors.id').inspect:"
      Rails.logger.info major_group_major_ids.pluck('majors.id').inspect
    end

    raise e
  end
end
```

The output is

```
Jul 09 08:04:07 handshake-production app/web.8:  Processing by JobsController#show as HTML 
Jul 09 08:04:07 handshake-production app/web.8:    Parameters: {"id"=>"70057"} 
Jul 09 08:04:08 handshake-production app/web.8:  major_group_major_ids.to_sql: 
Jul 09 08:04:07 handshake-production app/web.8:  SELECT "major_groups".* FROM "major_groups" INNER JOIN "major_groups_school_majors" ON "major_groups_school_majors"."major_group_id" = "major_groups"."id" INNER JOIN "school_majors" ON "school_majors"."id" = "major_groups_school_majors"."school_major_id" INNER JOIN "majors" ON "majors"."id" = "school_majors"."major_id" INNER JOIN "major_groups_student_screens" ON "major_groups"."id" = "major_groups_student_screens"."major_group_id" WHERE "major_groups_student_screens"."student_screen_id" = 82221 
Jul 09 08:04:07 handshake-production app/web.8:  major_group_major_ids.pluck('majors.id').inspect: 
Jul 09 08:04:08 handshake-production app/web.8:  ActionView::Template::Error (undefined method `to_i' for false:FalseClass): 
Jul 09 08:04:08 handshake-production app/web.8:      1: = pass_to_js(show_job_pass_to_js) 
Jul 09 08:04:08 handshake-production app/web.8:      2:  
Jul 09 08:04:08 handshake-production app/web.8:      3: = content_for :page_header do 
Jul 09 08:04:08 handshake-production app/web.8:      4:   .container-fluid 
Jul 09 08:04:08 handshake-production app/web.8:    app/models/student_screen.rb:299:in `rescue in combined_major_ids' 
Jul 09 08:04:08 handshake-production app/web.8:    app/models/student_screen.rb:291:in `combined_major_ids' 
Jul 09 08:04:08 handshake-production app/web.8:    app/models/job.rb:416:in `major_ids' 
Jul 09 08:04:08 handshake-production app/web.8:    lib/json_helper.rb:25:in `as_json' 
Jul 09 08:04:08 handshake-production app/web.8:    app/helpers/application_helper.rb:15:in `pass_to_js' 
Jul 09 08:04:08 handshake-production app/web.8:    app/views/jobs/show.html.haml:1:in `_app_views_jobs_show_html_haml__814365339616939366_70210668442420' 
Jul 09 08:04:08 handshake-production app/web.8:    app/controllers/application_controller.rb:522:in `set_stamper' 
Jul 09 08:04:08 handshake-production app/web.8:    app/controllers/application_controller.rb:517:in `user_time_zone' 
Jul 09 08:04:08 handshake-production app/web.8:  Completed 500 Internal Server Error in 257ms (ActiveRecord: 111.5ms) 
```

It looks like nothing is printed for the inspect (assuming it errored again within the rescue). Hope this helps! I am still getting this error sporadically and now multiple times a day (5+).

Potentially of interest is the MajorGroup class relations:
```
class MajorGroup < ActiveRecord::Base
  has_and_belongs_to_many :school_majors, -> { distinct }
  has_many :majors, -> { distinct }, through: :school_majors
end
```

Some other lines that give the same error:
```
survey_responses.where(user_id: user.id).where.not(id: Appointment.all.pluck(:pre_survey_response_id, :post_survey_response_id, :advisor_survey_response_id).flatten.uniq).first
```
```
user.institution.approved_employers.pluck(:id)
```
```
@career_fair.institution.majors.select(:id, :name)
```

All errors lead to https://github.com/rails/rails/blob/master/activerecord/lib/active_record/type/integer.rb which in 4.2.1 appears to be defined as

```
def type_cast_from_database(value)
  return if value.nil?
  value.to_i # this is the line that errors
end
```

but it appears that this has changed since that version in master https://github.com/rails/rails/commits/master/activerecord/lib/active_record/type/integer.rb

**Comment by sgringwe** [comment] 2015-08-18 05:39
@sgrif @raouldevil @cristianbica FYI This ended up being caused by https://github.com/sparklemotion/nokogiri/issues/1332 (libxml conflciting with nokogiri and causing memory consuption). no issue with rails. thanks for your help!
