### ISSUE TITLE
Cookies with names starting in underscore are ignored in the http request

### ISSUE THREAD

**Issue by thiagolcmelo** [rails/rails#31597] opened 2017-12-30 14:18 UTC
### Steps to reproduce

Create a simple app, with a simple controller and view.

$ rails _5.1.4_ new my_app
$ cd my_app/
$ bundle install && bundle update
$ rails generate controller StaticPages index

In the StaticPages controller, change the `index` according to:

```
def index
    if cookies['_ga'].nil?
        random_id = (0...9).map { ('0'..'9').to_a[rand(10)] }.join
        timestamp = (Time.new().to_i*1000).to_s
        cookies['_ga'] = {
            value: "1.2.#{random_id}.#{timestamp}",
            expires: 2.year.from_now,
            domain: "yourdomain.com"
        }
    end
end
```

Also, please set you `routes.rb` according to:

```
Rails.application.routes.draw do
  root to: 'static_pages#index'
  get 'static_pages/index'
end
```

Then just launch the app:

$ rails server -p 8080

### Expected behavior

I expected:

1. the first request to bring back a response with a new cookie with a new value **OK**
2. the second request sends the cookie value **OK**
3. the second request brings back a response with the same cookie already created in the step 1 **NOK**.

### Actual behavior

It is always generating a new cookie for the response, since it is not finding the cookie in the `request.cookies` or in the `cookies`. Actually, they are both `nil` (`request.cookies` and `cookies`)

If I just remove the "_" in the front of the cookie's name, it works as expected.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.0p0

**Comment by y-yagi** [comment] 2017-12-31 00:11
I could not reproduce your issue. I can get cookies that include underscoring in a name. 
Can you please provide a sample application that reproduces the issue?

**Comment by shime** [comment] 2018-01-04 09:26
I also couldn't reproduce it with that configuration. Need more details on how to do so. Failing test would be ideal.

**Comment by thiagolcmelo** [comment] 2018-01-08 01:10
@y-yagi and @shime 

I am really sorry for wasting your time. I tried it again and it worked as it should.
 
I have an app where it does not work, but the issue is probably another thing.

If you guys think it would worth to investigate:
https://github.com/thiagolcmelo/underscore-cookie-error

**Comment by y-yagi** [comment] 2018-01-08 03:53
Thanks for providing sample application. 
As you are aware, your sample application seems work as expected.  
So the issue is not Rails, and I will close this. 
If you will find the cause, and it's issue of Rails, feel free reopen issue. Thanks!

**Closed by y-yagi** 2018-01-08 03:53 UTC
