### ISSUE TITLE
action mailbox amazon subscription confirmation

### ISSUE THREAD

**Issue by michelson** [rails/rails#35813] opened 2019-04-01 03:05 UTC
### Steps to reproduce

Create an Amazon SNS subscription, which points to `/rails/action_mailbox/amazon/inbound_emails`  then send the confirmation subscription from amazon panel.

### Expected behavior
the controller should be able to detect the message type `subscriptionConfirmation` 
from  Message type `request.headers`
```
"HTTP_X_AMZ_SNS_MESSAGE_TYPE"=>"SubscriptionConfirmation",
"HTTP_X_AMZ_SNS_MESSAGE_ID"=>"xxx",
 "HTTP_X_AMZ_SNS_TOPIC_ARN"=>"arn:aws:sns:us-east-xxxx:myapp",
```
 and `open` a new request with the `request.body['SubscribeURL']` confirming the subscription. The action should return 200

### Actual behavior
it throws error trying to process an empty content , the problem is that the controller tries to process an inbound but the message has no `params[:content]`

```
ActionController::ParameterMissing (param is missing or the value is empty: content):
actionpack (6.0.0.beta3) lib/action_controller/metal/strong_parameters.rb:459:in `require'
actionmailbox (6.0.0.beta3) app/controllers/action_mailbox/ingresses/amazon/inbound_emails_controller.rb:46:in `create'
```
### System configuration
**Rails version**:
6.0.0.beta3
**Ruby version**:
2.5.0

my monkeypatch was put this in an initializer:
```ruby
require 'open-uri'
ActionMailbox::Ingresses::Amazon::InboundEmailsController.class_eval do
  private
    def authenticate
      # get amazon message type and topic
      amz_message_type = request.headers['x-amz-sns-message-type']
      amz_sns_topic = request.headers['x-amz-sns-topic-arn']

      request_body = JSON.parse request.body.read
      # if this is the first time confirmation of subscription, then confirm it
      if amz_message_type.to_s.downcase == 'subscriptionconfirmation' #and amz_sns_topic.to_s.downcase == 'arn:aws:sns:us-west-2:xxxxx:myapp'
        open(request_body["SubscribeURL"])
        render plain: "ok" and return
      end

      head :unauthorized unless verifier.authentic?(request_body)
    end
end
```

**Comment by michelson** [comment] 2019-04-01 03:36
invalid report

**Comment by georgeclaghorn** [comment] 2019-04-01 17:02
This is a duplicate of #35704.

**Closed by georgeclaghorn** 2019-04-01 17:02 UTC
