### ISSUE TITLE
Switch/change table name during request dynamically?

### ISSUE THREAD

**Issue by kapso** [rails/rails#20148] opened 2015-05-13 20:57 UTC
Based on my request, I would like to query either `test_users` or `users`. I am doing this using `User.table_name = "test_users"` or `User.table_name = "users"`

This works in development, but not in production (i.e table name in the query does not change), due to - 

```ruby
config.cache_classes = true
config.eager_load = true
```

I am guessing the table names are being cached somewhere and `Model.table_name=` does not update the cache.

Is this a bug? or expected behavior? How can I switch the table name dynamically? I am running `4.2.0` and if it helps postgres (pg gem).

**Comment by kapso** [comment] 2015-05-14 16:25
Hey guys can anyone let me know if this is a bug or expected behavior, this is an urgent production issue for us and would really appreciate any help. Thanks.

**Comment by rafaelfranca** [comment] 2015-05-14 16:31
I can see that it is expected behavior because it was never designed to be changed dynamically in production. I don't know if it is possible to do, but right now it is working as intended. If you want to investigate please go ahead, but since this is more a feature request I'm closing this issue.

Thank you so much for the issue.

**Closed by rafaelfranca** 2015-05-14 16:31 UTC

**Comment by kapso** [comment] 2015-05-14 16:35
Thanks for the quick reply, appreciate it. Any internal rails hack that can allow this behavior? or this is just not possible? @rafaelfranca

**Comment by rafaelfranca** [comment] 2015-05-14 16:41
I think you can you can try to define a anonymous class or just define a `TestUser` class

**Comment by kapso** [comment] 2015-05-14 16:54
Yea I can do that, problem I am using `User.*` calls all over my code (and theres plenty of code). Is there a way to proxy all method call (both class & instance)? that way I can just this proxy method to delegate calls to anonymous or `TestUser` class? @rafaelfranca

**Comment by rafaelfranca** [comment] 2015-05-14 17:17
Not that I know, sorry.

**Comment by kibs** [comment] 2015-10-27 09:19
@kapso Did you find a solution for your issue?

**Comment by kapso** [comment] 2015-10-27 09:27
Nope, I ended up using a different "test" schema and it worked great. Using `apartment` which I highly recommend - https://github.com/influitive/apartment

**Comment by LemonAndroid** [comment] 2018-11-24 10:13
@rafaelfranca Wouldn't it be possible to use `RuntimeRegistry` for this case?
