### ISSUE TITLE
ActionView::MissingTemplate error on first request, second request renders json ok, rails 4.1.8

### ISSUE THREAD

**Issue by tzoro** [rails/rails#17946] opened 2014-12-06 14:28 UTC
Using rails 4.1.8

to reproduce:
1. scaffold dummy item
2. add method in controller
  def myroute
    render :json => true
  end
3. add route
match "testroute" => "controller#action", via: [:get, :post], :defaults => { :format => :json }

behavior:
First request after controller file has been saved app throws "ActionView::MissingTemplate" error, second request renders json.

Not sure am i doing something wrong.

**Comment by rafaelfranca** [comment] 2015-01-02 03:12
Closing this  since we could not reproduce. Let us know if you could get the reproduction steps

**Closed by rafaelfranca** 2015-01-02 03:12 UTC
Labels: actionpack, actionview
