### ISSUE TITLE
Fanout.rb thread variable is sometimes nil

### ISSUE THREAD

**Issue by frobichaud** [rails/rails#21873] opened 2015-10-05 18:24 UTC
Hi,
we're seeing many occurrences of 
"NoMethodError undefined method `pop' for nil:NilClass" on fanout.rb. We don't have reproducible steps, we're running in a multithreaded production environment. The Thread[:_timestack] variable is nil.

See below for the stacktrace.
```
NoMethodError undefined method `pop' for nil:NilClass
gems/activesupport-4.2.2/lib/active_support/notifications/fanout.rb:126 finish
          def finish(name, id, payload)
            timestack = Thread.current[:_timestack]
            started = timestack.pop
            @delegate.call(name, started, Time.now, id, payload)
          end
        end
gems/activesupport-4.2.2/lib/active_support/notifications/fanout.rb:46block in finish
gems/activesupport-4.2.2/lib/active_support/notifications/fanout.rb:46each
gems/activesupport-4.2.2/lib/active_support/notifications/fanout.rb:46finish
gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:36finish
gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:25instrument
gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467log
gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299execute
gems/activerecord-4.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:231execute
gems/activerecord-4.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:235exec_query
gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:347select
gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:32select_all
gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:68block in select_all
gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:83cache_sql
gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:68select_all
gems/activerecord-4.2.2/lib/active_record/relation/calculations.rb:264execute_simple_calculation
gems/activerecord-4.2.2/lib/active_record/relation/calculations.rb:221perform_calculation
gems/activerecord-4.2.2/lib/active_record/relation/calculations.rb:127calculate
gems/activerecord-4.2.2/lib/active_record/relation/calculations.rb:125calculate
gems/activerecord-4.2.2/lib/active_record/relation/calculations.rb:42count
gems/will_paginate-3.0.7/lib/will_paginate/active_record.rb:97count
gems/will_paginate-3.0.7/lib/will_paginate/active_record.rb:95count
gems/will_paginate-3.0.7/lib/will_paginate/active_record.rb:113empty?
```

**Comment by thedarkone** [comment] 2015-10-06 03:24
Which Ruby are you using?

**Comment by jmaitrehenry** [comment] 2015-10-06 03:26
I'm working with @frobichaud, and we use ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

**Comment by thedarkone** [comment] 2015-10-06 03:59
I looked at the code and I think it is correct, I don't know why you are getting the errors.

Make sure you don't have code manually calling `ActiveSupport::Notifications::Instrumenter`'s `start` and `finish`, you can also attempt to detect out-of-order `start` and `finish` calls, with monkey patch like this:

```ruby
ActiveSupport::Notifications::Instrumenter.class_eval do
  undef :start
  undef :finish
  
  def instrument(name, payload={})
    __start name, payload
    begin
      yield payload
    rescue Exception => e
      payload[:exception] = [e.class.name, e.message]
      raise e
    ensure
      __finish name, payload
    end
  end

  # Send a start notification with +name+ and +payload+.
  def __start(name, payload)
    nesting = Thread.current[:_notif_nesting] ||= 0
    Thread.current[:_notif_nesting] += 1
    Rails.logger.info "#{Thread.current} #{'-' * nesting}start (#{name})"
    @notifier.__start name, @id, payload
  end

  # Send a finish notification with +name+ and +payload+.
  def __finish(name, payload)
    nesting = Thread.current[:_notif_nesting] ||= 0
    Thread.current[:_notif_nesting] -= 1 unless Thread.current[:_notif_nesting] == 0
    Rails.logger.info "#{Thread.current} #{'-' * nesting}finish (#{name})"
    @notifier.__finish name, @id, payload
  end
end

ActiveSupport::Notifications::Fanout.class_eval do
  undef :start
  undef :finish
  undef :listeners_for
  
  def __start(name, id, payload)
    __listeners_for(name).each { |s| s.start(name, id, payload) }
  end

  def __finish(name, id, payload)
    __listeners_for(name).each { |s| s.finish(name, id, payload) }
  end
  
  def __listeners_for(name)
    # this is correctly done double-checked locking (ThreadSafe::Cache's lookups have volatile semantics)
    @listeners_for[name] || synchronize do
      # use synchronisation when accessing @subscribers
      @listeners_for[name] ||= @subscribers.select { |s| s.subscribed_to?(name) }
    end
  end

  def listening?(name)
    __listeners_for(name).any?
  end
end
```

Note that I haven't tested the monkey patch, but hopefully the intention is clear and if I missed or messed up some method names or something you can fix it up.

**Comment by sgrif** [comment] 2015-10-06 23:40
I agree with @thedarkone here, there's no reason that this should be failing. Even if this is somehow a bug in Rails, unless a minimal Rails app which we can use to reproduce this issue can be provided, I don't think there's anything we can do. Since the issues tracker is reserved only for bugs in Rails, I'm going to go ahead and close this.

**Closed by sgrif** 2015-10-06 23:40 UTC

**Comment by johnhamelink** [comment] 2015-11-23 15:48
I also have this issue - I'm using rgeo/activerecord-postgis-adapter which pops up in the stacktrace for this error for me. I will attempt to use @thedarkone's monkeypatch to find out where this issue is coming from in my case, and if it's coming from this repo I will report back here.

**Comment by skaestle** [comment] 2015-11-27 14:21
@sgrif hello! would you mind reopening this issue? I have created a small rails (4.2.5) app that showcases the error: https://github.com/skaestle/investigate-rails-notification.

this happens when an error is thrown while subscribed to `process_action.action_controller`: https://github.com/skaestle/investigate-rails-notification/blob/master/app/controllers/posts_controller.rb#L7
