### ISSUE TITLE
HABTM relationship only partially loaded when using includes

### ISSUE THREAD

**Issue by helderasmoreira** [rails/rails#42743] opened 2021-07-09 13:25 UTC
### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '6.1.0'
  gem 'sqlite3'
  gem 'faker'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :categories, force: true do |t|
    t.string :name
  end

  create_table :categories_posts, force: true do |t|
    t.integer :post_id
    t.integer :category_id
  end
end

class Post < ActiveRecord::Base
  has_and_belongs_to_many :categories
end

class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

class BugTest < Minitest::Test
  def test_includes_with_where
    category = Category.create!(name: Faker::Lorem.word)
    other_category = Category.create!(name: Faker::Lorem.word)
    another_category = Category.create!(name: Faker::Lorem.word)

    Post.create!(categories: [category, other_category, another_category])

    relation = Post.includes(:categories).where(categories: { name: other_category.name })

    assert_equal 1, relation.size

    # should be 3 but it's 1 only: the category that we filtered by
    assert_equal 3, relation.first.categories.size
  end
end
```

### Expected behavior
I'm looking for some insight and opinions here rather than feeling quite strongly that this would be the expected behaviour.

When using `includes` of an HABTM relationship along with some type of filtering (`where`), the HABTM relationship in the resulting objects would contain the "entire" relationship results despite having been filtered by it.

The actual behaviour seems like it could lead to some confusing scenarios? 
The object's state does not reflect the DB for the object at the point in time where the object was loaded.

### Actual behavior
When using `includes` of an HABTM relationship along with some type of filtering (`where`), the HABTM relationship in the resulting objects will only be partially loaded — with the relationship objects that match the filtering.

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.6.6

**Comment by ghiculescu** [comment] 2021-07-19 21:10
Can you confirm if the behavior is the same if using `preload` and `eager_load`, instead of `includes`?

I think I agree that this is a bug, it would be good to confirm if it is consistent across all those methods.

**Comment by heldersantosmoreira** [comment] 2021-07-20 08:38
I can confirm the same behaviour happens with `eager_load`.

As for `preload`, to my knowledge we cannot really filter by the relation directly while using it?
So to use it, and still filter, one would do something like:
```ruby
Post.joins(:categories).where(categories: { name: other_category.name }).preload(:categories)
```
which I would say is kind of the workaround for this behaviour without needing to reset the relationship or something similar.
Since `preload` always triggers a separate query it is not bounded by the initial `joins` (and filter) and therefore works well.

**Comment by intrip** [comment] 2021-07-29 10:59
@heldersantosmoreira thanks for the report! Il'd work on a patch to fix this, unless you're interested into doing it.

**Comment by intrip** [comment] 2021-07-29 13:11
@heldersantosmoreira I took a look and agree that this behaviour looks counter intuitive on the first sight but on the other hand I don't think is a bug: the exact purpose of `eager_load` is to store the loaded records (with whatever `where` condition was set) and allow to retrieve such value without doing any further queries.

If when calling `.size` we should load the records again (ignoring the previous `where` condition set) the whole purpose of `eager_loading` fades away...

You can still fetch the records without the `where` condition by  using relation.first.categories.unscope(:where).size

@ghiculescu am I overlooking at something?

**Comment by intrip** [comment] 2021-07-29 13:17
@heldersantosmoreira I took a look and whilst on a first sight looks counter-intuitive this is the correct behaviour from my POV: the purpose of `eager_load` is in fact to load the `categories` filtered with the given where condition hence the categories for the posts would be only the ones which matches the previous where query.

If you want to retrive all the categories ignoring the previous filter you can either:
- use relation.first.categories.rewhere.size
- use `left_joins`  instead of `eager_load`

@ghiculescu  am I overlooking at something?

**Comment by ghiculescu** [comment] 2021-07-29 15:15
Hmmm. I looked for examples of this pattern in our app, I found a few, mostly of this style:

```ruby
# a user can be in many teams, and a team can have many users. HABTM on both sides.
teams = Team.includes(:users).where(user: { id: users_the_current_user_can_see })
accessible_teams = teams.pluck(:id, "users.id").to_h
```

Currently this returns a hash of team IDs to a list of user IDs, the list of user IDs is always a subset of `users_the_current_user_can_see`. With the proposed change, this would potentially return user IDs that aren't in `users_the_current_user_can_see`.

So at least in this case, the current behaviour is exactly what we want.

I searched through https://github.com/rails/rails/blob/main/activerecord/test/cases/associations/eager_test.rb but I can't find any tests that cover this specific case. https://github.com/rails/rails/blob/c166b3b64a375df22cc26714b4a9ad0507fb0673/activerecord/test/cases/associations/eager_test.rb#L202 is probably the closest. Maybe it's a good idea to add one?

**Comment by ghiculescu** [comment] 2021-07-29 15:16
> Since `preload` always triggers a separate query it is not bounded by the initial joins (and filter) and therefore works well.

This concerns me though, since replacing `includes` with `preload` is sometimes a good way of speeding queries up (replacing one big slow query with two small fast ones). But in my specific example that would change the output.

**Comment by intrip** [comment] 2021-07-29 19:57
@ghiculescu Thanks!

> I searched through https://github.com/rails/rails/blob/main/activerecord/test/cases/associations/eager_test.rb but I can't find any tests that cover this specific case.

I'll make a PR to add a test

> This concerns me though, since replacing includes with preload is sometimes a good way of speeding queries up (replacing one big slow query with two small fast ones). But in my specific example that would change the output.

The key is that `preload` doesn't consider the conditions on the outer tables which leads to that result. I don't think we can do much in that sense since it's just the way it works.

To summarise do you agree on:

1. I'll open a PR to add the missing test
2. we close this issue since it's expected behaviour

?

**Comment by ghiculescu** [comment] 2021-07-29 20:15
> * I'll open a PR to add the missing test
> * we close this issue since it's expected behaviour

Agree with this, but could you also add some docs on this specific difference between `includes` / `eager_load` / `preload`?

**Comment by intrip** [comment] 2021-07-30 08:17
> > * I'll open a PR to add the missing test
> > * we close this issue since it's expected behaviour
> 
> Agree with this, but could you also add some docs on this specific difference between `includes` / `eager_load` / `preload`?

@ghiculescu 

I think the guides already mention such information:

[preload](https://edgeguides.rubyonrails.org/active_record_querying.html#preload) 

**"The preload method using an array, hash, or a nested hash of array/hash in the same way as the includes method to load any number of associations with a single Model.find call. However, unlike the includes method, it is not possible to specify conditions for eager loaded associations."*

**Comment by heldersantosmoreira** [comment] 2021-07-30 08:29
@intrip first of all, thanks for looking into this 🙌 

As for the issue at hand: like I said initially I "understand" why it happens but I must say I'm not convinced that 1) it is desirable and 2) it is intuitive. 

The docs for [includes](https://api.rubyonrails.org/v6.1.4/classes/ActiveRecord/QueryMethods.html#method-i-includes) for instance detail:

> Specify relationships to be included in the result set.

Furthermore they include an entire section on "conditions" where there's no mention of how this affects the result set or the loaded relationships.

All in all, maybe it is more about documentation but it bothers me a bit that a given object is loaded and presented for use without representing correctly the database at the time it was loaded. But I can see this being more me than a real 🐛😃

**Comment by intrip** [comment] 2021-08-02 15:11
@heldersantosmoreira I understand that this looks counter-intuitive but I think this is the expected behaviour.

Agree that we can make the existing docs clearer about this specific scenario: are you interested in writing a PR for that? We should also add a test for this specific scenario.

**Comment by heldersantosmoreira** [comment] 2021-08-03 07:46
> @heldersantosmoreira I understand that this looks counter-intuitive but to me this looks to be the expected behaviour.
> 
> Agree that we can make the existing docs clearer about this specific scenario: are you interested in writing a PR for that? We should also add a test for this specific scenario.
> 
> /cc @kamipo since maybe he disagrees with the above statement and we should consider this as a bug.

@intrip I'm a little stressed for time this week but I can try to put something together in the coming weeks. 

If you feel like you can tackle it before that, please do go ahead 🙂

**Comment by intrip** [comment] 2021-08-03 08:32
@heldersantosmoreira all yours, tnx!

**Closed** 2021-12-29 18:59 UTC
Labels: activerecord, With reproduction steps
