### ISSUE TITLE
Can't create foreign_keys with create_join_table in migration

### ISSUE THREAD

**Issue by openscript** [rails/rails#26005] opened 2016-07-31 09:40 UTC
### Steps to reproduce
1. Generate a new migration `rails generate migration CreateJoinTableUsersOffers users offers`
2. This generates the following migration:
   
   create_join_table :users, :offers do |t|
     # t.index [:"users,_id", :offer_id]
     # t.index [:offer_id, :"users,_id"]
   end
3. Using the `column_options` to add foreign keys
   
   create_join_table :users, :offers, column_options: {foreign_key: true} do |t|
     # t.index [:"user_id", :offer_id]
     # t.index [:offer_id, :"user_id"]
   end
### Expected behavior

This migration should generate foreign key constraints like this does:

```
add_foreign_key :offers_users, :offers
add_foreign_key :offers_users, :users
```
### Actual behavior

It doesn't create any foreign_keys. It works with indexes though.
### System configuration

**Rails version**: 5.0.0
**Ruby version**: 2.3.1p112

**Comment by prakashmurthy** [comment] 2016-07-31 17:52
Running the following migration
```ruby
create_join_table :users, :offers do |t|
# t.index [:"users,_id", :offer_id]
# t.index [:offer_id, :"users,_id"]
end
```

results in the `users_offers` table being created with `user_id` and `offer_id` fields as follows (on mysql) : 
```ruby
 create_table "offers_users", id: false, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.integer "user_id",  null: false
    t.integer "offer_id", null: false
 end
```

No need to add the `user_id` and `offer_id` fields as foreign keys separately. 

Passing `foreign_key: true` as one of the `column_options` does not have any impact, and that is the correct behavior.

**Comment by openscript** [comment] 2016-07-31 20:13
Why is this the correct behaviour? It doesn't create the foreign key constraints that way, but with `add_foreign_key` they are created.

**Comment by ShomesTech** [comment] 2016-08-17 05:44
@openscript 
The migration method create_join_table creates an HABTM (has and belongs to many) join table for many to many mapping. Creating foreign_key on HABTM join table is not logical from the the relational database HABTM join table concept and hence adding that to create_join_table has no additional impact.
@prakashmurthy would you be able to confirm the same ?

**Comment by openscript** [comment] 2016-08-17 07:01
@ShomesTech Why shouldn't we want foreign key constraints on a many to many relation? The foreign key constraints are there to maintain referential integrity; ensuring that you can't insert values that don't exist in the related table.

**Comment by matthewlmcclure** [comment] 2016-12-27 16:47
It seems this issue is a duplicate of #22960.

**Comment by betesh** [comment] 2017-02-28 01:23
I agree with @matthewlmcclure that this asks the same question as #22960.  However, I'm not sure why the PR there didn't address this in a far simpler way.  Instead of the [current code](https://github.com/rails/rails/blob/v5.0.1/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L340), which is:

      type = column_options.delete(:type) || :integer
      create_table(join_table_name, options.merge!(id: false)) do |td|
        td.send type, t1_column, column_options
        td.send type, t2_column, column_options
      end

wouldn't this be better?

      create_table(join_table_name, options.merge!(id: false)) do |td|
        td.references t1_column, column_options # column_options would include the type key
        td.references t2_column, column_options
      end

This would allow the following:

    create_join_table :table1, :table2, column_options: { foreign_key: true } # ...

**Comment by kamipo** [comment] 2017-03-04 10:30
Now `create_join_table` allows references options in #28217. Closing.

**Closed by kamipo** 2017-03-04 10:30 UTC
Labels: activerecord
