### ISSUE TITLE
Hosts permitting: only one level of domains supported

### ISSUE THREAD

**Issue by cmrd-senya** [rails/rails#44921] opened 2022-04-19 10:49 UTC
### Steps to reproduce

1. Use the special "starting dot" syntax
2. Try opening subdomain of the second level, e.g "level2.level1.product.com

This is from the Rails docs: 
```ruby
# Allow requests from subdomains like `www.product.com` and
# `beta1.product.com`.
Rails.application.config.hosts << ".product.com"
```

Respective code entry point: https://github.com/rails/rails/blob/8ace32c4ccdc760d17548de777b08c13bc9e07bd/actionpack/lib/action_dispatch/middleware/host_authorization.rb#L72-L73

### Expected behavior
The request is served, the validation is passing

### Actual behavior
Host getting blocked. Only "level 1" hosts is supported with the "dot syntax". This is controversial with the statement from the documentation that this is "A special case is supported that allows you to permit all sub-domains" 

### System configuration
**Rails version**: 6.1.4.6

**Ruby version**: 2.7.2

**Comment by SkipKayhil** [comment] 2022-04-19 21:15
Hey @cmrd-senya, thanks for the report. It looks like this is a duplicate of #43953 so I'm going to close this, but feel free to comment on the other issue

**Closed by SkipKayhil** 2022-04-19 21:15 UTC
