### ISSUE TITLE
redirect_to concatenates "redirect path" without leading slash

### ISSUE THREAD

**Issue by jablan** [rails/rails#33905] opened 2018-09-17 11:50 UTC
### Steps to reproduce

```ruby
redirect_to 'the.evil.site'
```

### Expected behavior

I am redirected to `http://my.site/the.evil.site`

### Actual behavior

I am redirected to `http://my.sitethe.evil.site`

### System configuration
**Rails version**:
Every
**Ruby version**:
Every

**Comment by jablan** [comment] 2018-09-17 11:59
In https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/redirecting.rb#L105-L106 there is:

```ruby
      when String
        request.protocol + request.host_with_port + options
```

while I would expect something like `URI::join(request.protocol, request.host_with_port, options)`

(although I am aware that's not such a trivial change)

**Comment by y-yagi** [comment] 2018-09-19 23:27
Thanks for your issue. 
However, linking as a string is the intended behavior as documented. 
https://edgeapi.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_to 
Using `URI::join` here will be incompatible. 　 

If the beginning is not `/`, it might be a good to take some care. But it is feature request.  
We don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feedback.

**Closed by y-yagi** 2018-09-19 23:27 UTC
