### ISSUE TITLE
Rails loads url_helper from engine module vs application module (if they have the same name)

### ISSUE THREAD

**Issue by vronin** [rails/rails#33732] opened 2018-08-27 21:23 UTC
### Steps to reproduce

I have an application  which has the same module "Api" both in application and in the engine

**controllers/api/v1/foos_controller.rb**
```
module Api
  module V1
    class FoosController < ActionController::API

      def foo
          render plain: "Foo" 
      end

    end
  end
end
```

**engines/api/app/controllers/api/v2/bars_controller.rb**
```
module Api
  module V2
    class BarsController < ActionController::API

      def bar
          render plain: "Bar" 
      end

    end
  end
end

```
**config/routes.rb**
```
Rails.application.routes.draw do
  mount Api::Engine, at: '/api'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1 do
      get 'foos/foo', to: 'foos#foo'
    end
  end
  
end
```
It will throw if I try to access application url_helpers. As an example, if I will add `puts api_foos_foo_path` into `FoosController::foo`.

It will work it I will try to access engine url_helpers. As an example if I will add `puts v2_bars_bar_path` into `FoosController::foo`.

I checked and apparently, it imported (automagically) url helper from engine (vs application) for some reason.

In the case if I will add `include Rails.application.routes.url_helpers` to FooController then application url handlers will start working again.

### Expected behavior
I expected Rails application to import url helper for Rails app and engine import url helpers for engine

### Actual behavior
Rails application imports url helper for engine.

### System configuration
**Rails version**: Rails 5.2.1

**Ruby version**: ruby 2.5.1p57

**Comment by vronin** [comment] 2018-08-28 00:12
[test.zip](https://github.com/rails/rails/files/2326005/test.zip)

Steps:
1) Run app
2) Open http://localhost:3000/api/foos/foo
3) Uncomment `puts api_foos_foo_path` in controllers/api/v1/foos_controller.rb
4) Open http://localhost:3000/api/foos/foo (it will throw) which will show the issue
5) Uncomment `include Rails.application.routes.url_helpers`  in controllers/api/v1/foos_controller.rb
6) Open http://localhost:3000/api/foos/fo (it will start working again)

**Comment by lewispb** [comment] 2018-08-31 19:11
I have reproduced using the steps described above and your example application.

However, [as per this guide](https://guides.rubyonrails.org/engines.html#routes), on step 3 I do not get an error if I use `puts main_app.api_foos_foo_path`.

Therefore, as the guide does warn:

> Calls to normal routing methods such as articles_path may end up going to undesired locations if both the application and the engine have such a helper defined.

I'm not sure if this is a bug.

**Comment by lewispb** [comment] 2018-08-31 19:35
Thanks for that. For my own benefit I did some research and found [this blog post](https://crypt.codemancers.com/posts/2013-09-22-isolate-namespace-in-rails-engines/
), which I _think_ describes the issue:

> This inherited method will be called in the context of your controllers. Again if your controller is under Blorgh `(or Api)` module, it magically includes only the routes defined by gem, otherwise it includes the application route helpers. 

I'm not sure of the fix yet, but this seems to be related:

https://github.com/rails/rails/blame/master/actionpack/lib/abstract_controller/railties/routes_helpers.rb

**Comment by vronin** [comment] 2018-09-04 00:50
@lewispb I agree with Rafael. There is no disambiguate here. The code is in the main app and it's calling main app helper.  

I tried to read the article and it went over my head (I am not that familiar with Rails under the hood). The only note which I would have is that the article is for Rails 4.0 (vs Rails 5.2). My guess that there were substantial amount of changes from that moment (when engines were just introduced) up to now.

**Comment by darren987469** [comment] 2018-09-08 07:05
You call `isolate_namespace Api` in your engine. So it treats `Api::V1::FoosController` as part of the engine. And it includes url_helpers from engine, not from application.

```ruby
# test/engines/api/lib/api/engine.rb
module Api
  class Engine < ::Rails::Engine
    isolate_namespace Api
  end
end
```

If you change `Api::V1::FoosController` to other namespace, for example: `ApplicationApi::V1::FoosController`, then it would include url_helpers from application and you can call `api_foos_foo_path ` as normal.

```ruby
# test/app/controllers/application_api/v1/foos_controller.rb
module ApplicationApi
  module V1
    class FoosController < ActionController::API
      def foo
        render plain: api_foos_foo_path
      end
    end
  end
end

# test/config/routes.rb
Rails.application.routes.draw do
  mount Api::Engine, at: '/api'

  get 'api/foos/foo', to: 'application_api/v1/foos#foo'
end
```

I think it make sense for `Api::V1::FoosController` to include url_helpers from engine, not from application. Since `Api` namespace is isolated by engine. What do you think? @vronin

**Comment by rafaelfranca** [comment] 2018-09-12 21:44
Good investigation @darren987469. Yes, that makes sense. Because you isolated the entire Api namespace it does treat anything inside it as part of the Engine. Closing since this is not an issue.

**Closed by rafaelfranca** 2018-09-12 21:44 UTC
Labels: With reproduction steps, actionpack, engines
