### ISSUE TITLE
Rails 5's flash messages are incompatible with Rails 4's

### ISSUE THREAD

**Issue by marcelokanzaki** [rails/rails#24726] opened 2016-04-25 13:38 UTC
### Steps to reproduce

Rails 5 app:
```ruby
class SomeController < ApplicationController
  def some_action
    redirect_to '/rails4app', flash: {success: 'Some message.'}
  end
end
```

Rails 4 app:
```html
<% flash.map do |msg_type, message| %>
  <%= message %>
<% end %>
```

### Expected behavior
To see the flash message.

### Actual behavior
```ruby
NoMethodError
undefined method `map' for nil:NilClass
Did you mean?  tap
```
First line of the Framework Trace:
```ruby
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:249:in `stringify_array'
```

### System configuration
**Rails version**: 5.0.0.beta3 (1st app), 4.2.3 (2nd app)

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by vipulnsward** [comment] 2016-04-25 18:18
Hmm, I can't seem to reproduce this, @marcelokanzaki can you check if this works for you?
https://gist.github.com/vipulnsward/ff4276309460ca8e7f1d5adfa935d1c3

**Comment by marcelokanzaki** [comment] 2016-04-25 19:10
@vipulnsward thanks for the response. It seems to me that both actions are on the same app.

The issue happens when you set a flash message in a Rails 5 app e try to read it in a Rails 4 app.

**Comment by rafaelfranca** [comment] 2016-04-25 19:50
Which cookie format the Rails 4 application is using? Marshal or JSON? In Rails 4 the default is Marshal and in the Rails 5 the default is JSON so you need to configure both to be the same if you want to both application being able to read.

**Comment by marcelokanzaki** [comment] 2016-04-25 19:53
Both json.

**Comment by marcelokanzaki** [comment] 2016-04-25 19:55
complete framework trace:

```ruby
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:249:in `stringify_array'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:104:in `initialize'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:87:in `new'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:87:in `from_session_value'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:9:in `flash'
devise (4.0.0) lib/devise/failure_app.rb:17:in `flash'
devise (4.0.0) lib/devise/failure_app.rb:81:in `redirect'
devise (4.0.0) lib/devise/failure_app.rb:41:in `respond'
actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
devise (4.0.0) lib/devise/failure_app.rb:21:in `call'
devise (4.0.0) lib/devise/delegator.rb:5:in `call'
warden (1.2.6) lib/warden/manager.rb:142:in `call_failure_app'
warden (1.2.6) lib/warden/manager.rb:128:in `process_unauthenticated'
warden (1.2.6) lib/warden/manager.rb:43:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.3) lib/rails/engine.rb:518:in `call'
railties (4.2.3) lib/rails/application.rb:165:in `call'
/usr/local/Cellar/passenger/5.0.24/libexec/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/local/Cellar/passenger/5.0.24/libexec/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/local/Cellar/passenger/5.0.24/libexec/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/local/Cellar/passenger/5.0.24/libexec/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/local/Cellar/passenger/5.0.24/libexec/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by marcelokanzaki** [comment] 2016-04-25 20:03
![captura de tela 2016-04-25 as 17 02 18](https://cloud.githubusercontent.com/assets/843048/14797162/8fbb6406-0b07-11e6-9786-9c330073a2c1.png)

**Comment by vipulnsward** [comment] 2016-04-25 21:30
This trace is from 4.2? So its an issue there?

**Comment by marcelokanzaki** [comment] 2016-04-25 21:37
@vipulnsward the issue is that 4.2 can't read a flash message set by a 5.0.

**Comment by jeremy** [comment] 2016-04-26 02:02
This is desirable, but not a release blocker. Fine to improve in 5.0.x.

@marcelokanzaki Have you `git bisect` to find the commit responsible for the behavior change?

**Comment by rafaelfranca** [comment] 2016-04-26 04:05
Almost 100% sure it is https://github.com/rails/rails/pull/18721

**Comment by rafaelfranca** [comment] 2016-04-26 04:26
A possible solution is to always return `'discard'` as an empty array and remove that key in Rails 5.1. If that seems reasonable I can work on that. I prefer to have it fixed in Rails 5.0.0 since I'll need to run both Rails versions in my application for a while.

**Comment by jeremy** [comment] 2016-04-26 04:43
Sounds good @rafaelfranca.

**Comment by marcelokanzaki** [comment] 2016-04-26 05:38
@jeremy I haven't but I seems @rafaelfranca found it. Thanks guys for investigating.

**Closed** 2016-05-06 20:14 UTC
Labels: actionpack
