### ISSUE TITLE
[ActiveRecord] eager_load not loading all objects

### ISSUE THREAD

**Issue by Dorian** [rails/rails#29701] opened 2017-07-06 19:34 UTC
### Steps to reproduce

Active Record with Postgres reproduction script: https://gist.github.com/Dorian/be645733b7d388e8539e05db67f71a6f

### Expected behavior

It should print the same number of both loaded dependencies (e.g. 1 credit and 1 debit transaction)

### Actual behavior

It prints 1 credit and 0 debit transaction when eager loaded

### System configuration

SQL Query (formated):

```sql
SELECT "users"."id" AS t0_r0,
       "transactions"."id" AS t1_r0,
       "transactions"."source_id" AS t1_r1,
       "transactions"."destination_id" AS t1_r2,
       "debit_transactions_users"."id" AS t2_r0,
       "debit_transactions_users"."source_id" AS t2_r1,
       "debit_transactions_users"."destination_id" AS t2_r2
FROM "users"
LEFT OUTER JOIN "transactions" ON "transactions"."destination_id" = "users"."id"
LEFT OUTER JOIN "transactions" "debit_transactions_users" ON "debit_transactions_users"."source_id" = "users"."id"
```

SQL Output (from Postico):

<img width="300" alt="screen shot 2017-07-06 at 10 09 40 pm" src="https://user-images.githubusercontent.com/129149/27930703-e4697f54-6297-11e7-8e69-8861941a251f.png">

Explain:

```
                                           QUERY PLAN
-------------------------------------------------------------------------------------------------
 Hash Right Join  (cost=136.39..183.67 rows=2260 width=56)
   Hash Cond: (credit_transactions_users.destination_id = users.id)
   ->  Seq Scan on transactions credit_transactions_users  (cost=0.00..25.70 rows=1570 width=24)
   ->  Hash  (cost=108.14..108.14 rows=2260 width=32)
         ->  Hash Right Join  (cost=60.85..108.14 rows=2260 width=32)
               Hash Cond: (transactions.source_id = users.id)
               ->  Seq Scan on transactions  (cost=0.00..25.70 rows=1570 width=24)
               ->  Hash  (cost=32.60..32.60 rows=2260 width=8)
                     ->  Seq Scan on users  (cost=0.00..32.60 rows=2260 width=8)
(9 rows)
```

**ActiveRecord version**: 5.0 and 5.1 tested
**Ruby version**: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]`

**Comment by Dorian** [comment] 2017-07-06 20:33
Seems like something is going wrong with the mapping of attributes, e.g. https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/finder_methods.rb#L357-L383

**Comment by eugeneius** [comment] 2017-07-07 01:08
This is a duplicate of https://github.com/rails/rails/issues/26805, and would be fixed by https://github.com/rails/rails/pull/27737.

**Comment by sgrif** [comment] 2017-07-17 18:03
Confirmed duplicate

**Closed by sgrif** 2017-07-17 18:03 UTC
