### ISSUE TITLE
ActionRecord callback not being called when another callback makes an update

### ISSUE THREAD

**Issue by jcarloslopez** [rails/rails#48546] opened 2023-06-21 14:22 UTC
Looks like it has to do with the update being called because if you change the update for another print both will be called

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :value
  end
end

class Post < ActiveRecord::Base
  after_create_commit :this_will_never_be_called
  after_create_commit :this_will_be_called

  private

  def this_will_never_be_called
    p "This will never be called"
  end

  def this_will_be_called
    update(value: 3)
  end
end

class BugTest < Minitest::Test
  def test_output_produces_output
    assert_output(/This will never be called/) { Post.create }
  end
end
```

### Expected behavior
The first callback should be called and print the output prior to the update in the second callback.

### Actual behavior
The first callback is not being called but the second one is.

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.0.2p107

**Comment by abaldwin88** [comment] 2023-06-23 01:39
Confirming reproduction of the issue from the script. Removing the `update` call or swapping the declaration order of `after_create_commit` will cause the test case to start passing.

**Comment by abaldwin88** [comment] 2023-06-24 11:31
Looks like a duplicate of #46155 ?

**Comment by skipkayhil** [comment] 2023-06-27 02:20
Yeah, I'm going to close for the same reason I closed the other one. This appears to be expected based on the note in the guide.

**Closed by skipkayhil** 2023-06-27 02:20 UTC
