### ISSUE TITLE
[ActiveRecord] Rails datetime type column changed? method behavior not correct.

### ISSUE THREAD

**Issue by zw963** [rails/rails#32266] opened 2018-03-16 03:34 UTC
### Steps to reproduce

```rb
pusher = Pusher.create(scheduled_at: '2017-12-12 12:12:12')
old_time = pusher.scheduled_at

# here same date with previous date
pusher.assign_attributes(scheduled_at: '2017-12-12 12:12:12')
new_time = pusher.pusher.scheduled_at

p old_time == new_time        # => true
pusher.scheduled_at_changed?  # => true
```

### Expected behavior

``pusher.scheduled_at_changed?`` should be false, because two time value same.

### Actual behavior
``pusher.scheduled_at_changed?`` is true.

### System configuration
**Rails version**:
Rails 4.1.16

**Ruby version**:
Ruby 2.3.4

**Comment by rafaelfranca** [comment] 2018-03-16 04:58
Are you able to reproduce this with Rails 5.1?

**Comment by composerinteralia** [comment] 2018-03-16 12:19
I am not able to reproduce this on any version. @zw963 am I missing something here?

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "5.2.0rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :scheduled_at
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(scheduled_at: '2017-12-12 12:12:12')
    old_time = post.scheduled_at

    post.assign_attributes(scheduled_at: '2017-12-12 12:12:12')
    new_time = post.scheduled_at

    assert old_time == new_time
    assert !post.scheduled_at_changed?
  end
end
```

**Comment by zw963** [comment] 2018-03-17 05:26
@composerinteralia , hi, I change your's config to my exact project rails version, but could not reproduce too.

```rb
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "4.1.16"
  gem "mysql2", '0.3.20'
end

require "active_record"
require 'active_support/testing/time_helpers'
require "minitest/autorun"
require "logger"

# Need create test_time_database with mysql console:
# CREATE DATABASE test_time_database DEFAULT CHARACTER SET utf8;

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  database: "ikcrm_cms_test",
  host: '127.0.0.1',
  port: '3306',
  username: 'root',
  password: '123456'
)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "promotion_pushers", force: true do |t|
    t.integer  "promotion_id"
    t.integer  "user_id"
    t.integer  "expected_corp_count",           default: 0
    t.integer  "expected_user_count",           default: 0
    t.integer  "product_type",                  default: 0
    t.integer  "range_type",                    default: 0
    t.integer  "role_type",                     default: 0
    t.integer  "pusher_type",                   default: 0
    t.integer  "button_link_type",              default: 0
    t.boolean  "delayed",                       default: false
    t.datetime "scheduled_at"
    t.datetime "executed_at"
    t.string   "title"
    t.string   "description"
    t.string   "image_file_name"
    t.string   "image_content_type"
    t.integer  "image_file_size"
    t.datetime "image_updated_at"
    t.string   "image_up"
    t.string   "button_link"
    t.string   "button_text"
    t.boolean  "disabled",                      default: true
    t.integer  "labelid"
    t.datetime "notification_update_pusher_at"
    t.string   "crm_api_host",                                  null: false
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "user_not_active_days"
    t.integer  "user_no_activity_days"
  end
end

class PromotionPusher < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_changed
    @pp = PromotionPusher.create(scheduled_at: '2017-12-12 13:12:12', crm_api_host: 'http://www.example.org')
    assert_equal true, @pp.persisted?
    assert_equal '2017-12-12 13:12:12', @pp.scheduled_at.strftime('%F %T')

    @pp.assign_attributes(scheduled_at: '2017-12-12 13:12:12')
    assert_equal false, @pp.scheduled_at_changed?
  end
end
```

**Comment by zw963** [comment] 2018-03-17 05:30
But, for my corp old project with SAME database(`ikcrm_cms_test`) and almost remove all model methods, still not working ...

```rb
# model/promotion_pusher.rb

# == Schema Information
#
# Table name: promotion_pushers
#
#  id                            :integer          not null, primary key
#  promotion_id                  :integer
#  user_id                       :integer
#  expected_corp_count           :integer          default(0)
#  expected_user_count           :integer          default(0)
#  product_type                  :integer          default(0)
#  range_type                    :integer          default(0)
#  role_type                     :integer          default(0)
#  pusher_type                   :integer          default(0)
#  button_link_type              :integer          default(0)
#  delayed                       :boolean          default(FALSE)
#  scheduled_at                  :datetime
#  title                         :string(255)
#  description                   :string(255)
#  image_file_name               :string(255)
#  image_content_type            :string(255)
#  image_file_size               :integer
#  image_updated_at              :datetime
#  image_up                      :string(255)
#  button_link                   :string(255)
#  button_text                   :string(255)
#  disabled                      :boolean          default(TRUE)
#  labelid                       :integer
#  notification_update_pusher_at :datetime
#  crm_api_host                  :string(255)      not null
#  created_at                    :datetime
#  updated_at                    :datetime
#

class PromotionPusher < ActiveRecord::Base
  belongs_to :promotion
  belongs_to :user
end
```

```rb
# spec/models/promotion_pusher_spec.rb

require "minitest/autorun"

ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../../config/environment", __FILE__)

class BugTest < Minitest::Test
  def test_changed
    @pp = PromotionPusher.create(scheduled_at: '2017-12-12 13:12:12', crm_api_host: 'http://www.example.org')
    assert_equal true, @pp.persisted?
    assert_equal '2017-12-12 13:12:12', @pp.scheduled_at.strftime('%F %T')
    @pp.assign_attributes(scheduled_at: '2017-12-12 13:12:12')
    assert_equal true, @pp.scheduled_at_changed?
  end
end
```

I think some very weird things is happen for this project which caused by some gem?

**Comment by zw963** [comment] 2018-03-17 13:45
I try to remove most ActiveRecord relative gems, it still happen in this old project ...

**Comment by zw963** [comment] 2018-03-17 13:47
BTW: in  my test, i try another string column too, but, that behavior work as expect.
when assign same string with exist value, `string_column_changed?` method return false

**Comment by y-yagi** [comment] 2018-03-18 01:10
Can not reproduce with the executable test case, so I think that this is probably an application specific issue.  
Therefore, I close this. But if you can reproduce with the executable test case, please feel free to reopen. Thanks.

**Closed by y-yagi** 2018-03-18 01:10 UTC
Labels: needs work

**Comment by izhilenkov** [comment] 2019-07-10 18:39
Have the same issue, totally the same versions of rails, mysql and ruby. Only for datetime.
