### ISSUE TITLE
ActiveRecord coerces String values to nil for jsonb fields

### ISSUE THREAD

**Issue by DarkArc** [rails/rails#27236] opened 2016-11-30 22:33 UTC
### Steps to reproduce
Using PostgreSQL, create a table with a jsonb field, and a corresponding ActiveRecord model, for this example the field will be called `foo` and the model `Bar`.

Then using the rails console:
```
b = Bar.new
b.foo = "test string"
b.foo
```

### Expected behavior
`b.foo` returns `"test string"`

### Actual behavior
`b.foo` returns `nil`

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.2.5

### Additional notes

I believe this is happening because of this line, which only encodes Hashes and Arrays: https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/postgresql/oid/json.rb#L21

It also seems this behavior was changed in Rails 5, and is likely no longer an issue there:
https://github.com/rails/rails/blob/5-0-1/activerecord/lib/active_record/type/internal/abstract_json.rb

**Comment by maclover7** [comment] 2016-11-30 22:54
@DarkArc Can you please confirm whether or not this is a bug for you on Rails master?

**Comment by utilum** [comment] 2016-11-30 23:18
[Executable test case](https://gist.github.com/utilum/a0a96132f3342e04209d66046996009b) fails in 4.2.7, passes in >=5.0.0

**Comment by maclover7** [comment] 2016-12-01 00:02
Since the issue is fixed in Rails 5, going to close out this issue. Thanks for the reproduction script, @utilum!

**Comment by DarkArc** [comment] 2016-12-01 00:54
@maclover7 so is there any hope of getting a fix for rails 4, or is 4 effectively EOL for non-critical fixes?

**Comment by maclover7** [comment] 2016-12-01 01:02
@DarkArc If you can find the commit that fixed this and can open up a backport PR to `4-2-stable` then it'll probably be merged, but otherwise I'd just suggest moving to Rails 5 😬

**Comment by sgrif** [comment] 2016-12-01 19:56
We should bisect and see how much work it would be to backport

**Comment by sgrif** [comment] 2016-12-01 19:57
Oh never mind, I see what you're trying to do. Assigning anything other than hashes or arrays to json fields was unsupported prior to Rails 5. Supporting other primitives results in major changes in behavior, and absolutely would not be backported.

**Closed by sgrif** 2016-12-01 19:57 UTC
Labels: activerecord, PostgreSQL
