### ISSUE TITLE
STI and view path

### ISSUE THREAD

**Issue by kalsan** [rails/rails#42587] opened 2021-06-24 09:14 UTC
This is a question/discussion about the behavior of templates/partials with regard to STI.

### Steps to reproduce

Rails 6.1

Assuming STI model Tree with two implementations `CherryTree` and `AppleTree` inheriting from `Tree`.

We have three controllers, `TreesController`, `CherryTreesController` and `AppleTreesController`; the two latter ones inherit from the first.

We have three view directories in the default location: `views/trees/_form.haml`, `views/cherry_trees/_form.haml` and `views/apple_trees/_form.haml`.

In `AppleTreesController < TreesController`:

```
def edit
  # ...
  render partial: 'form'
end
```

### Actual behavior

The behavior appears to be:

- If `views/trees/_form.haml` exists, it is rendered.
- Otherwise, `views/apple_trees/_form.haml` is rendered.

### Expected behavior

Given common inheritance behavior, I'd have expected that instead, the more specific view is preferred:

- If `views/apple_trees/_form.haml` exists, it is rendered.
- Otherwise, the generic fallback `views/trees/_form.haml` is rendered.

### Conclusion

Why is the more generic partial preferred?

Best,
Kalsan

**Comment by ghiculescu** [comment] 2021-06-24 15:23
I would expect that behavior too. To help with debugging are you able to share an app that replicates the issue?

**Comment by hahmed** [comment] 2021-06-25 23:32
@kalsan I was not able to replicate this behaviour, seems to be working for me... 🤔 

Here is the output from the logs (I used ERB instead of haml views):

```
Started GET "/cherry_trees/2/edit" for ::1 at 2021-06-26 00:28:56 +0100
Processing by CherryTreesController#edit as HTML
  Parameters: {"id"=>"2"}
  Tree Load (0.1ms)  SELECT "trees".* FROM "trees" WHERE "trees"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/trees_controller.rb:62:in `set_tree'
  Rendered cherry_trees/_form.erb (Duration: 1.4ms | Allocations: 815)
Completed 200 OK in 3ms (Views: 1.7ms | ActiveRecord: 0.1ms | Allocations: 1530)
```

**Comment by pixeltrix** [comment] 2021-06-26 07:41
@hahmed I wonder if this is a Haml bug? Can you reproduce in a new app using Haml templates?

**Comment by hahmed** [comment] 2021-06-26 14:25
Not able to repro with haml templates either

```
Started GET "/cherry_trees/2/edit" for ::1 at 2021-06-26 15:15:34 +0100
Processing by CherryTreesController#edit as HTML
  Parameters: {"id"=>"2"}
  Tree Load (0.1ms)  SELECT "trees".* FROM "trees" WHERE "trees"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/trees_controller.rb:63:in `set_tree'
  Rendered cherry_trees/_form.haml (Duration: 2.7ms | Allocations: 868)
Completed 200 OK in 5ms (Views: 3.1ms | ActiveRecord: 0.1ms | Allocations: 1583)
```

Controller:

```
# app/controllers/cherry_trees_controller.rb
# app/views/cherry_trees/_form.haml -- view location
# app/views/trees/_form.haml -- not rendered from the edit action

  def index
    @trees = CherryAppleTree.all
  end

  def show; end

  def edit
    render partial: 'form'
  end
end
```

**Comment by kalsan** [comment] 2021-06-27 09:56
Thank you all for your efforts! It must have to do with a gem or patch then. It's a large application, I will investigate further for the cause of the problem.

**Comment by hahmed** [comment] 2021-06-28 08:11
I'm going to go ahead and close this for now, but let us know when you find something. This issue can be re-opened 😀

**Closed by hahmed** 2021-06-28 08:11 UTC
Labels: actionview
