### ISSUE TITLE
ruby fails to load active_support/core_ext/array/conversions: undefined method `deprecator' for module ActiveSupport

### ISSUE THREAD

**Issue by x-yuri** [rails/rails#52273] opened 2024-07-04 23:09 UTC
### Steps to reproduce

`a.sh`:

```sh
docker run --rm -it ruby:3.3.3-alpine sh -euxc '
    if [ "${1-}" ]; then
        gem install activesupport -v "$1"
    fi
    gem install click_house
    ruby -rclick_house -e ""
' - "${1-}"
```

```sh
$ sh a.sh
...
+ ruby -rclick_house -e 
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for module ActiveSupport (NoMethodError)

  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
	from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/duration.rb:3:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /usr/local/bundle/gems/click_house-2.1.2/lib/click_house.rb:11:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `rescue in require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:135:in `require'
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- click_house (LoadError)
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'

$ sh a.sh '~> 6'
...
+ ruby -rclick_house -e 
```

### Expected behavior

It doesn't fail with ActiveSupport 7.

### Actual behavior

It fails.

### System configuration
**Rails version**: -

**Ruby version**: `3.3.3`

**Comment by fatkodima** [comment] 2024-07-04 23:12
Duplicate of #50726.

**Closed by fatkodima** 2024-07-04 23:12 UTC
