### ISSUE TITLE
rescue in _decrypt: ActiveSupport::MessageEncryptor::InvalidMessage running 2 different ruby projects locally

### ISSUE THREAD

**Issue by niightly** [rails/rails#32656] opened 2018-04-20 01:31 UTC
### Steps to reproduce
1. Create a project A and encrypt `rails secrets:setup` the secrets.yml
2. Raise the server on project A folder using the key you set on the first encryption
3. Create the project B and encrypt `rails secrets:setup` the secrets.yml
4. Stop the project A server, start the server on project B folder (don't forget to change the RAILS_MASTER_KEY).

### Expected behavior
I should be able to work with 2 Ruby projects simultaneously.

### Actual behavior
When I change between folders even changing the `RAILS_MASTER_KEY` and stop the sprint and run `rails server` or `rails console` it returns this error:
```shellscript
/Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/message_encryptor.rb:133:in `rescue in _decrypt': ActiveSupport::MessageEncryptor::InvalidMessage (ActiveSupport::MessageEncryptor::InvalidMessage)
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/message_encryptor.rb:112:in `_decrypt'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/message_encryptor.rb:84:in `decrypt_and_verify'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/secrets.rb:55:in `decrypt'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/secrets.rb:96:in `preprocess'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/secrets.rb:27:in `block in parse'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/secrets.rb:24:in `each'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/secrets.rb:24:in `each_with_object'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/secrets.rb:24:in `parse'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/application.rb:391:in `secrets'
	from (erb):4:in `<main>'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/mongoid-6.1.1/lib/mongoid/config/environment.rb:40:in `load_yaml'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/mongoid-6.1.1/lib/mongoid/config.rb:86:in `load!'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/mongoid-6.1.1/lib/mongoid.rb:104:in `load!'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/mongoid-6.1.1/lib/mongoid/railtie.rb:59:in `block in <class:Railtie>'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
	from /Users/thiagogs/github/places-at-ibm/config/environment.rb:5:in `<top (required)>'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:102:in `require'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/thiagogs/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

### System configuration
**Rails version**: Rails 5.1.6

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]

**Comment by y-yagi** [comment] 2018-04-20 07:58
Hmm, I could not reproduce the issue with reproduce steps. 
In the state generated by rails new, encrypted secrets should not be read in the development environment, have you changed any config? 
If so, can you provide the sample application?

**Comment by y-yagi** [comment] 2018-04-21 13:25
I tried again with your config, but couldn't reproduce. 
Is there anything else you have changed?  Is it also possible to reproduce with newly application?

**Comment by y-yagi** [comment] 2018-04-23 22:51
You need to provide the correct reproducing procedure or reproduced application. If it were not, we can not do anything. Therefore, I close this. 
But if you can provide reproduced application, feel free to reopen. Thanks!

**Closed by y-yagi** 2018-04-23 22:51 UTC
Labels: railties

**Comment by trostli** [comment] 2018-07-20 05:21
This happened to me when I generated master.key locally. To fix i just deleted it from my config folder.

**Comment by sagarpatidar** [comment] 2018-12-18 06:19
`credentials.yml.enc` file and `master.key` work together. `master.key` contains string to decrypt `credentials.yml.enc`, so they go hand-in-hand. So either delete both and recreate using `EDITOR=vim rails credentials:edit` or get the pairs right.

**Comment by headius** [comment] 2019-03-16 15:46
I ran into this as well. Can someone clarify if it's valid to have just the encoded credentials.yml.enc file in a Rails repo? That was the case here; no master.key but a credentials file. Because of missing master.key, it reported that I had not set up `secret_key_base` so I proceeded to `credentials:edit`. It was happy to create a master.key file and then blew up with this error because the existing credentials could not be decrypted (I assume).

Perhaps the error could be improved to indicate that these files appear to be mismatched, rather than this completely opaque error?

**Comment by monroemann** [comment] 2021-05-03 20:39
> This happened to me when I generated master.key locally. To fix i just deleted it from my config folder.

You deleted the master.key from _which_ config folder?  On development, on master, on heroku?

**Comment by monroemann** [comment] 2021-05-03 20:43
> `credentials.yml.enc` file and `master.key` work together. `master.key` contains string to decrypt `credentials.yml.enc`, so they go hand-in-hand. So either delete both and recreate using `EDITOR=vim rails credentials:edit` or get the pairs right.

We tried this, and pushed everything again to heroku, and we're getting the same error every time we add the master key to heroku.

This is the primary error we are getting:

```
         1: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.3.1/lib/active_support/message_encryptor.rb:180:in `_decrypt' /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.3.1/lib/active_support/message_encryptor.rb:203:in `rescue in _decrypt': ActiveSupport::MessageEncryptor::InvalidMessage (ActiveSupport::MessageEncryptor::InvalidMessage)
monroemann@DESKTOP-6VLHQ8A bdcommunity (master) $
```

Does that error provide any clues?  SES works fine on development, but when we try to push to Heroku, it crashes immediately.
