### ISSUE TITLE
HashWithIndifferentAccess#dig does not behave in Rails 5.0.0.beta2 as it did in beta1

### ISSUE THREAD

**Issue by claudiob** [rails/rails#23411] opened 2016-02-01 23:54 UTC
Here's the snippet of code to replicate: https://gist.github.com/claudiob/f2096db9d47e35d19ad2

In short, given a hash with indifferent access like

```ruby
data = {"this" => {"views" => 1234}}.with_indifferent_access
```

Then calling `data.dig(:this, :views)` was correctly returning 1234 under beta1 but returns `nil` under beta2.

Even calling `data.dig(:this)` returns `nil` under beta2.

**Comment by sgrif** [comment] 2016-02-02 00:32
I've not done a bisect to confirm, but this is likely caused by #18909

**Comment by maclover7** [comment] 2016-02-02 01:53
Bisected, and as though by Sean, this is the bad commit: https://github.com/rails/rails/commit/38a990237a0f99d99b885ea6570cae3752138a29. Working on a fix for this.

**Comment by maclover7** [comment] 2016-02-02 02:21
Opened PR #23414 to try and solve this.

**Closed** 2016-02-02 03:21 UTC
Labels: activesupport, attached PR, regression, With reproduction steps
