### ISSUE TITLE
Rails console fails to start due to LoadError on trying to require irb

### ISSUE THREAD

**Issue by Caeleron** [rails/rails#42373] opened 2021-06-03 14:24 UTC
### Steps to reproduce

Create a new rails project and run `rails console` or `bin/rails console` in the project.

### Expected behavior

The rails console starts successfully. 

### Actual behavior

Rails immediately crashes with the following:
```
/usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- irb (LoadError)
Did you mean?  erb
               drb
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/commands/console/console_command.rb:3:in `<main>'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
	from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/command/behavior.rb:40:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/command/behavior.rb:40:in `block in lookup'
	from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/command/behavior.rb:39:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/command/behavior.rb:39:in `lookup'
	from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/command.rb:76:in `find_by_namespace'
	from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/command.rb:48:in `invoke'
	from /usr/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/commands.rb:18:in `<main>'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /home/cameron/OtherProjects/mykanban/bin/rails:5:in `<main>'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /usr/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/fork_tracker.rb:10:in `block in fork'
	from /usr/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/fork_tracker.rb:10:in `block in fork'
	from /usr/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/fork_tracker.rb:8:in `fork'
	from /usr/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/fork_tracker.rb:8:in `fork'
	from /usr/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/fork_tracker.rb:26:in `fork'
	from /usr/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/fork_tracker.rb:8:in `fork'
	from /usr/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/fork_tracker.rb:26:in `fork'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```
### System configuration
Any x86-64 Arch Linux install with ruby and ruby-irb installed through pacman, and rails installed globally through gem.
Note, it is possible to require irb normally outside of rails. 
**Rails version**: Rails 6.1.3.2
**Ruby version**: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

**Comment by SkipKayhil** [comment] 2021-06-03 17:25
I was able to reproduce this:
```bash
docker run -it archlinux:base-devel bash
```
in the container:
```bash
pacman -Syu ruby
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"
gem install rails
rails new irb_test --skip-webpack-install # webpack will fail because no node.js
cd irb_test
bin/rails c
```

I also tried making a plain ruby script that requires irb to make sure irb existed and that worked fine:
```ruby
require 'irb'
p 'irb required'
# => "irb required"
```

**Comment by lfalcao** [comment] 2021-06-04 00:38
@SkipKayhil thanks for the script! If someone gets this error:

```bash
docker run -it archlinux:base-devel bash
[root@f423c21762bf /]# pacman -Syu ruby
error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)
```

Run docker as privileged: `docker run -it archlinux:base-devel bash --privileged=true`

**Comment by zzak** [comment] 2021-06-04 01:17
Here to ask the dumb questions, but is this a bug in bootsnap? 🤔

**Comment by SkipKayhil** [comment] 2021-06-04 01:24
> Here to ask the dumb questions, but is this a bug in bootsnap? 🤔

I don't think its bootsnap, possibly bundler?

```ruby
require 'bundler/inline'

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
end

require 'irb'

p 'irb required'
```

this also causes `require 'irb'` to throw an error:
```bash
/root/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- irb (LoadError)
Did you mean?  erb
               drb
        from /root/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
        from /root/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /root/.local/share/gem/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
        from irb_test.rb:11:in `<main>'
```

**Comment by lfalcao** [comment] 2021-06-04 01:32
> Here to ask the dumb questions, but is this a bug in bootsnap? thinking

Nop. Running `DISABLE_BOOTSNAP=1 DISABLE_SPRING=1 bin/rails c` also crashes.

**Comment by lfalcao** [comment] 2021-06-04 01:39
> (or how ruby is packaged on arch?)

Probably this. Just tried with rvm and worked. The ruby installed by pacman, does not includes 'irb'... 

pacman install:
```
[root@1921843291cc irb_test]# ls /root/.local/share/gem/ruby/3.0.0/bin
bootsnap  bundle  bundler  byebug  listen  nokogiri  puma  pumactl  racc  rackup  rails  rake  spring  sprockets  thor	tilt
```

rvm install:
```
[root@1921843291cc irb_test]# ls /usr/local/rvm/rubies/ruby-3.0.0/bin/
bundle	bundler  erb  executable-hooks-uninstaller  gem  **irb**  racc  rake  rbs  rdoc  ri  ruby  ruby_executable_hooks  typeprof
```

**Comment by zzak** [comment] 2021-06-04 02:08
Oh ok, good find @lfalcao it seems that this was change in [arch](https://lists.archlinux.org/pipermail/arch-general/2019-January/045954.html) so we can probably close this issue.

**Comment by HParker** [comment] 2021-06-04 02:10
Looks like irb is installed at `/usr/lib/ruby/gems/3.0.0`

**Comment by HParker** [comment] 2021-06-04 02:27
hmm, very confusing. I haven't found a combination of `GEM_HOME` and `GEM_PATH` that finds the irb pacman installs. 

Is it safe to say the best advice for this situation is to use a ruby manager like `rbenv`, `rvm` or `chruby`?

**Comment by lfalcao** [comment] 2021-06-04 02:34
@HParker yep, I think its the best solution at this moment. 

ping @anatolik

**Comment by pixeltrix** [comment] 2021-06-04 05:26
Adding `gem 'irb'` to your Gemfile also fixes the problem - for some reason on Arch the gem isn't in the default set of gems, e.g:

```
% gem list | grep irb
irb (default: 1.3.5)
```

vs.

```
# gem list | grep irb
irb (1.3.5)
```

I suspect this is a packaging thing in Arch but we should probably make sure before closing otherwise we may need to add `irb` to `railties.gemspec` if it's not going to be included in the default gems in future.

**Comment by zzak** [comment] 2021-06-04 11:50
@pixeltrix That is indeed the case:

https://lists.archlinux.org/pipermail/arch-general/2019-January/045954.html

**Comment by pixeltrix** [comment] 2021-06-04 15:25
> @pixeltrix That is indeed the case:
> 
> https://lists.archlinux.org/pipermail/arch-general/2019-January/045954.html

I saw that, but it's in reference to Ruby 2.6 - isn't this new bug?

**Comment by Caeleron** [comment] 2021-06-04 15:29
As a followup, I found an AUR package that provides Rails and pulls it into the system through the package manager:

https://aur.archlinux.org/packages/ruby-rails/

However, there is no change in behavior and the same bug occurs.

**Comment by pixeltrix** [comment] 2021-06-04 15:44
@zzak looks like that is the cause - here's the line where irb is removed:
https://github.com/archlinux/svntogit-packages/blob/packages/ruby/trunk/PKGBUILD#L75

Then in ruby-irb it's just a regular `gem install`:
https://github.com/archlinux/svntogit-community/blob/packages/ruby-irb/trunk/PKGBUILD#L22

Not sure of a way to install a gem and place it in the default set? If there isn't then Arch need to fix the ruby PKGBUILD script to not remove irb. Either way it seems this isn't a Rails bug?

**Comment by Caeleron** [comment] 2021-06-04 16:04
> Adding `gem 'irb'` to your Gemfile also fixes the problem

Can confirm that does indeed solve the problem and irb loads correctly after adding it.

**Comment by anatol** [comment] 2021-06-04 16:13
The rationale behind splitting `irb` from `ruby` distribution is that irb development moved to [a separate repository](https://github.com/ruby/irb). And ruby distribution is in a weird state right now. From one side they ship `irb` as a part of default gemset. From other side if a CEV happens then ruby developers suggest to update `irb` as a standalone gem using `rubygems`.

default gemset and stanalone gems use different locations. Arch packaging manager does not handle such either/or conditions. So we've moved to using `irb` (and some other components) as standalone gems exclusively.

My suggestion is to add `gem irb'` to your Gemfile. It is a future-proof solution in case if ruby community decides to de-couple `irb` completely.

**Comment by pixeltrix** [comment] 2021-06-04 16:29
@anatol my understanding of gemifying the standard library is to allow updates outside of Ruby release cycles but there would be gems like irb that remained 'standard', (i.e. could be required directly) and others would be 'bundled' where you'd need to include them in your Gemfile. Sometimes gems go from standard to bundled, like rexml has recently.

There's more information available here: https://stdgems.org

**Comment by guilleiguaran** [comment] 2021-06-27 09:11
Closing this since it isn't caused by Rails.

**Closed by guilleiguaran** 2021-06-27 09:11 UTC
Labels: railties

**Comment by q9f** [comment] 2021-08-31 10:30
> Closing this since it isn't caused by Rails.

Hi, I'm learning Rails and ended up here due to getting stuck in the tutorial. While the issue might not be _caused_ by rails, you could do new users a favor though: The Gemfile generated by `rails new` should come with `irb` dev dependency.

```
  gem 'irb', require: false
```

What do you think?

**Comment by viktorianer** [comment] 2021-11-01 10:01
In my case I could start `rails console` in docker `development` environment (Alpine Linux), but not in `test` environment.

```bash
docker-compose run --rm test bundle exec rails console
...
Running via Spring preloader in process 14
Loading test environment (Rails 6.1.4.1)
/usr/local/bundle/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require': cannot load such file -- irb/color_printer (LoadError)
```

After I deleted the volume `rails_cache_data`, which in my case is holding `/app/tmp/cache` folder, I could start the `rails console` again.

```bash
docker-compose run --rm test bundle exec rails console
Creating volume "..._rails_cache_data" with default driver
...
Running via Spring preloader in process 14
Loading test environment (Rails 6.1.4.1)
irb(main):001:0>
```

No need to include gem `irb` for me.
