### ISSUE TITLE
[Regression 4.2.1.rc2] undefined method  primary_key

### ISSUE THREAD

**Issue by JDutil** [rails/rails#19087] opened 2015-02-26 03:42 UTC
Receiving all kinds of `undfined method primary_key` errors on the Spree projects spec suite from testing 4.2.1.rc2:
https://circleci.com/gh/JDutil/spree/877

Can anyone point me to the change causing these errors?

**Comment by arthurnn** [comment] 2015-02-26 03:46
probably https://github.com/rails/rails/commit/e43d96c12a3de240d70ef730942cc1bc73238481 . cc @sgrif

**Comment by sgrif** [comment] 2015-02-26 04:06
Can you isolate the problem and give me a script I can use to reproduce the issue, using https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb as a template?

**Comment by JDutil** [comment] 2015-02-26 17:23
Yea will try to write a regression test for this, but think I know why it's happening.  It looks like passing an empty array to a polymorphic association lookup is what caused the error.  I'm able to fix the Spree specs having made this change:
https://github.com/JDutil/spree/commit/064401f30ff40d59775704bc62d2b42b1a50defc

**Comment by sgrif** [comment] 2015-02-26 18:20
Cool, that should be enough for me to fix it.

**Comment by JDutil** [comment] 2015-02-26 18:24
I haven't been able to work up a regression spec yet, but another possible scenario I'm thinking it could be because the association is defined within a concern.  So primary_key is trying to be called on the concern module rather than the model including the concern...  Tried putting this together to reproduce the scenario but it's working fine in the script:
https://gist.github.com/JDutil/1710c49b6a39bb81dada

**Comment by sgrif** [comment] 2015-02-26 18:27
Fixed in https://github.com/rails/rails/commit/5cfe01e61b7eb5f280d246af714272d857c18c46

**Closed by sgrif** 2015-02-26 18:27 UTC
Labels: activerecord

**Comment by sgrif** [comment] 2015-02-26 18:30
Confirmed this issue is not present on master.

**Comment by sgrif** [comment] 2015-02-26 18:31
@JDutil Just in case you were curious, it was trying to call it on the module because that module matches the association name. The association defaulted to that behavior because we passed it `nil` for `base_class`

**Comment by JDutil** [comment] 2015-02-26 18:35
Thanks.  Looks like the only other issues I'm seeing now are related to rspec mocks, and not specifically rails related.

**Comment by stormsilver** [comment] 2015-03-02 21:09
For posterity, this also fixes this: https://gist.github.com/stormsilver/cd413ed30c6ec5328e6f
