### ISSUE TITLE
Possible to use enums and load a model more than once?

### ISSUE THREAD

**Issue by seanknox** [rails/rails#20643] opened 2015-06-20 08:37 UTC
Using Rails 4.1.10. I have an app with models that manually require other models so we can load the minimum dependencies for fast tests: ActiveRecord and model being tested, not all of Rails. All is good except with an enum defined on a model class. I get an enum conflict if the model is loaded a second time. E.g.:

```ruby
## Comment loads Conversation and Author
require './app/models/conversation'
require './app/models/author'
 
class Comment < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :author
end
```
```ruby
## Conversation loads Comment and Author
require './app/models/comment'
require './app/models/author'

class Conversation < ActiveRecord::Base
  belongs_to :author
  has_many :comments
end
```
```ruby
## Simple Author model using an enum
class Author < ActiveRecord::Base
  enum role: [:poet, :novelist]
end
```

If I try to use instantiate a `Comment` (for example), `Author` is loaded twice and an enum conflict is detected.

```ruby
4.1.10@2.1.2> Comment.new
ArgumentError: You tried to define an enum named "role" on the model "Author", but this will generate a instance method "role=", which is already defined by another enum.
from /Users/seanknox/src/fun_with_enums_app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.10/lib/active_record/enum.rb:189:in `detect_enum_conflict!'
```

I admit I haven't looked much at the enum source to determine why ActiveRecord can't deal with an enum being defined by the same class again. Any suggestions?

**Comment by pascalbetz** [comment] 2015-06-20 12:20
the code for __enum__ checks if the methods that are being created for the enum would not overwrite existing methods.
I guess you are loading the class multiple times thus you are reopening the class definition and try to add a method that is already present.

Besides that i don't think it's a wise idea to require files manually from within each other (let rails deal with the autoloading, sprinkle your own require statements throughout your code is asking for problems): you could add 
```ruby
unless defined? Comment
```
to only require the file once

**Comment by seanknox** [comment] 2015-06-20 15:57
They're just Ruby models; there's no dark magic involved with code requiring its dependencies.

**Comment by pascalbetz** [comment] 2015-06-21 00:48
Apparently you are adding the same enum multiple times (see _detect_enum_conflict_ calls around here https://github.com/rails/rails/blob/master/activerecord/lib/active_record/enum.rb#L152) which leads me to think you are loading the same file twice which will try to add the enum twice. No dark magic but as you mentioned just how ruby works. 
Class definition is re-opened, not overwritten. If you manage to require the same file multiple times.

**Comment by seanknox** [comment] 2015-06-21 05:00
Yes, I'm very aware of what I'm trying to do. I'll await a different answer. Thanks for your help.

**Comment by senny** [comment] 2015-06-22 08:18
Ruby `>= 1.9` should not require a file which has been previously required. If `author.rb` is loaded twice, the error is expected. Active Record enum tries to not overwrite existing methods on your model. Adding the same enum twice will overwrite previously generated methods.

Also if you want those `require` statements to play nicely with Rails' autoloading in development you should use [`require_dependency`](http://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#require-dependency) instead.

**Comment by al2o3cr** [comment] 2015-06-22 19:07
@seanknox You shouldn't need the explicit paths on the `require` lines - `$LOAD_PATH` generally has `app/models` on it. I remember this used to cause very strange behavior on old Rubies, as the same file would wind up in `$LOADED_FEATURES` under several pathnames (`/usr/foo/bar.rb` vs `/usr/../usr/foo/bar.rb`, for example).

I'm not 100% sure when that behavior vanished - I believe it was with the fast-require refactor [in ruby-core #7158](https://bugs.ruby-lang.org/issues/7158) but I don't have a system with Ruby <1.9.3 at hand right now to test against.

JRuby has two issues ([#1941](https://github.com/jruby/jruby/issues/1941) and [#2477](https://github.com/jruby/jruby/issues/2477)) that appear to involve similar reloading-already-required-files problems.

**Comment by chancancode** [comment] 2015-06-23 06:52
To answer your original question: the fact that enum is not working here is the correct behaviour and not a bug.

Like others have pointed out, the problem here is that the same file is being loaded (evalulated) twice. We consider this a user-error and we definitely don't intend to "support" this "use case" (it really is a bug, things that is a lot stranger than this error is probably happening behind the scene).

Happy to help you figure out *why* the file is being loaded twice, but we will need more information about your set up since it sounds pretty unconventional.

Closing for now since the original symptom being reported is not a bug.

**Closed by chancancode** 2015-06-23 06:52 UTC
Labels: activerecord, needs feedback

**Comment by seanknox** [comment] 2015-06-24 06:57
Thanks @senny @al2o3cr (Hi Jones!) @chancancode!

**Comment by chancancode** [comment] 2015-06-24 17:47
No problem! If you have more info, feel free to add it here or open a new issue

**Comment by MattDHill** [comment] 2016-06-26 14:50
I'm getting the same error. I have two different enums on the same model, each containing the same values:

```
class Group < ApplicationRecord

enum who_can_post: [:everyone, :managers, :only_me]
enum who_can_add: [:everyone, :managers, :only_me]

end
```

When I attempt to create a new Group, I get the following error:

"You tried to define an enum named "who_can_add" on the model "Group", but this will generate a instance method "everyone?", which is already defined by another enum."

**Comment by gilcierweb** [comment] 2017-03-26 00:26
I solved my problem by leaving **config / environments / production.rb** as default and everything returned to normal without errors

**Comment by Feuda** [comment] 2018-07-20 07:14
@MattDHill You can use the :_prefix or :_suffix options when you need to define multiple enums with same values. http://api.rubyonrails.org/classes/ActiveRecord/Enum.html
