### ISSUE TITLE
ActionView::Helpers::AssetUrlHelper.asset_path() is inconsistent with blank and nil source

### ISSUE THREAD

**Issue by Kevinrob** [rails/rails#30673] opened 2017-09-21 09:27 UTC
### Steps to reproduce

It's not really a bug but more like inconsistency about how argument `source` is handled.

If `source.nil?`, an error is raised. If `source.blank?`, an empty string is returned.  
Is it really a good thing to raise an error for `nil` source?

### Expected behavior
`asset_path("")` return `""`
`asset_path(nil)` return `""`

### Actual behavior
`asset_path("")` return `""`
`asset_path(nil)` raise `ArgumentError`

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.3.1

**Comment by y-yagi** [comment] 2017-09-22 06:20
This is expected behavior. Please see #20669 for details.

**Comment by ckornaros** [comment] 2017-09-22 13:48
@y-yagi if asset_path can handle an empty string it makes more sense that it can also handle a nil argument. Don't understand why ArgumentError exception is raised...

**Comment by pixeltrix** [comment] 2017-11-09 14:58
@ckornaros if you read the issue referenced by @y-yagi the reasoning is that it's probably due to something going wrong like `find` not returning a record so it'd be better to raise rather than blindly casting `nil` to an empty string.

Closing since this is the expected behaviour.

**Closed by pixeltrix** 2017-11-09 14:58 UTC
