### ISSUE TITLE
Getting_started.md Basic Auth required twice

### ISSUE THREAD

**Issue by puneet97** [rails/rails#29421] opened 2017-06-11 20:02 UTC
### Steps to reproduce
After following the [guide to create a basic rails app](https://github.com/rails/rails/blob/master/guides/source/getting_started.md#basic-authentication), the authentication has to be provided twice when creating a new article or editing article.

Basic Authentication has following code in ArticlesController:
```ruby
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  # snippet for brevity
```
The `except:` part should have `:create` too like:
```ruby
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show, :create]

  def index
    @articles = Article.all
  end

  # snippet for brevity
```

### Expected behavior
The user is asked to enter name/password when creating, editing, deleting article only once during the process.

### Actual behavior
The user has to authenticate twice, first when clicking new/edit article (method `new`/`create` is called) and a second time after clicking create in the `articles/new` or `articles/edit` (method `create` is called).

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.3.1

**Comment by adamshen** [comment] 2017-06-14 04:34
Use Chrome Developer Tools to see if the header of request has a field called 'Authorization' after you logged. If not, probably it's not a issue of server side.

**Comment by puneet97** [comment] 2017-06-15 06:11
I checked again and it works correctly when using it for the first time on opening browser, ie, only asks for authorization once but after using this [fix](https://stackoverflow.com/questions/5957822/how-to-clear-basic-authentication-details-in-chrome/6224994#6224994) for clearing basic authentication details, it starts asking for the authentication twice (new then create & edit then update) and yes it has the Authorization header after giving login details for the first time during 'new' or 'edit'.
If `:create` and `:update` are added to `except:` then it doesn't ask twice.

**Comment by OrthoDex** [comment] 2017-06-24 17:49
Hi!
I was trying to replicate this issue and I implemented the fix mentioned by @puneet97. It does ask the auth info twice, however the console also throws this warning message:

`[Deprecation] Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked. See https://www.chromestatus.com/feature/5669008342777856 for more details.`

The [change](https://www.chromestatus.com/feature/5669008342777856) is effective on Opera browsers as well.

That being said, just to be sure I checked on Firefox as well, and it works fine. It asks auth info only once.

**Comment by al2o3cr** [comment] 2017-09-23 15:44
@puneet97 Sounds like you're experiencing the issue described in one of the [comments](https://stackoverflow.com/questions/5957822/how-to-clear-basic-authentication-details-in-chrome#comment16379705_6224994) to that StackOverflow question. Chrome retains the `user@` part of the URL but doesn't show it. :(

BTW - HTTP auth is stateless, so skipping it for `create` means that (barring other security measures not mentioned in your question) anyone who can make a `POST` request to the application can create records. *Probably* not what you're intending.

**Comment by skflowne** [comment] 2017-10-20 00:14
I've been trying to reproduce this on 5.1.4 and Chrome 61.
I was asked for credentials only once, even after restarting the browser to clear the auth.
Typing the address in the form `dhh:secret@localhost:3000/articles/new` also doesn't ask again on `create`.
Not sure I understand what the 'fix' is though.

**Comment by rafaelfranca** [comment] 2017-10-20 18:18
Closing since we can't reproduce

**Closed by rafaelfranca** 2017-10-20 18:18 UTC
Labels: docs
