### ISSUE TITLE
Rails instalation problem!

### ISSUE THREAD

**Issue by uste11** [rails/rails#43627] opened 2021-11-10 19:27 UTC
Hi guys! I'm new here and I recently wanted to start programming in ruby. I have a mac whit os Sierra 10.12.6 on it. I installed ruby but i can't install rails. Everytime i try to install it and hit enter it just doesn't do anything. I will add a pic so you can see(btw i have all the plugins i need installed, i got the gorails.com installation guide and done everything they said there).![image](https://user-images.githubusercontent.com/94073939/141180027-2267f6b5-54f5-440b-9c4d-e41680ca9019.jpeg)
And it just stays like this

**Comment by Meowcenary** [comment] 2021-11-11 00:19
Please run `gem install -V rails -v 6.1.4.1 > output.txt` and then put the contents of output.txt here. The `-V` flag is for verbose (detailed) output.

**Comment by uste11** [comment] 2021-11-11 06:19
> Please run `gem install -V rails -v 6.1.4.1 > output.txt` and then put the contents of output.txt here. The `-V` flag is for verbose (detailed) output. 

Thanks man, i will try that!

**Comment by ceritium** [comment] 2021-11-11 11:19
**offtopic**

@uste11, a tip for take screenshots on mac: 
- [`shift+cmd+4`] partial screen
- [`shift+cmd+5`] full screen

**Comment by uste11** [comment] 2021-11-11 18:19
> Please run `gem install -V rails -v 6.1.4.1 > output.txt` and then put the contents of output.txt here. The `-V` flag is for verbose (detailed) output.

tried that rn and actually it does the same thing, just stays like that and is not executing anythin
![Screen Shot 2021-11-11 at 20 18 34](https://user-images.githubusercontent.com/94073939/141349134-50e11d16-9c08-4b08-a4e8-33e24562158e.png)
g.

**Comment by Meowcenary** [comment] 2021-11-12 15:51
> > Please run `gem install -V rails -v 6.1.4.1 > output.txt` and then put the contents of output.txt here. The `-V` flag is for verbose (detailed) output.
> 
> tried that rn and actually it does the same thing, just stays like that and is not executing anythin ![Screen Shot 2021-11-11 at 20 18 34](https://user-images.githubusercontent.com/94073939/141349134-50e11d16-9c08-4b08-a4e8-33e24562158e.png) g.

The command _is_ running , but the output is being redirected to the file `output.txt`. If you want to see the output in your terminal directly you can instead run `gem install -V rails -v 6.1.4.1`, but since I wanted to see the output I thought it would be nice to have it in the file. Why don't you try running `gem install -V rails -v 6.1.4.1` and posting a screenshot? 

I get the impression there is something small going wrong that we are not seeing.

**Comment by uste11** [comment] 2021-11-12 18:45
> > > Please run `gem install -V rails -v 6.1.4.1 > output.txt` and then put the contents of output.txt here. The `-V` flag is for verbose (detailed) output.
> 
> > 
> 
> > tried that rn and actually it does the same thing, just stays like that and is not executing anythin ![Screen Shot 2021-11-11 at 20 18 34](https://user-images.githubusercontent.com/94073939/141349134-50e11d16-9c08-4b08-a4e8-33e24562158e.png) g.
> 
> 
> 
> The command _is_ running , but the output is being redirected to the file `output.txt`. If you want to see the output in your terminal directly you can instead run `gem install -V rails -v 6.1.4.1`, but since I wanted to see the output I thought it would be nice to have it in the file. Why don't you try running `gem install -V rails -v 6.1.4.1` and posting a screenshot? 
> 
> 
> 
> I get the impression there is something small going wrong that we are not seeing.

Thank you so much for implication man!! I will try that a lil later and post it up here.

**Comment by uste11** [comment] 2021-11-14 16:53
> > > Please run `gem install -V rails -v 6.1.4.1 > output.txt` and then put the contents of output.txt here. The `-V` flag is for verbose (detailed) output.
> 
> > 
> 
> > tried that rn and actually it does the same thing, just stays like that and is not executing anythin ![Screen Shot 2021-11-11 at 20 18 34](https://user-images.githubusercontent.com/94073939/141349134-50e11d16-9c08-4b08-a4e8-33e24562158e.png) g.
> 
> 
> 
> The command _is_ running , but the output is being redirected to the file `output.txt`. If you want to see the output in your terminal directly you can instead run `gem install -V rails -v 6.1.4.1`, but since I wanted to see the output I thought it would be nice to have it in the file. Why don't you try running `gem install -V rails -v 6.1.4.1` and posting a screenshot? 
> 
> 
> 
> I get the impression there is something small going wrong that we are not seeing.

Hello man! Tried it again and didnt do nothing gor a few hrs. So idk

**Comment by Meowcenary** [comment] 2021-11-15 04:33
The output file is completely empty? That seems odd. Well, if it is empty I'd trying running the command **without** `> output.txt` and if nothing shows up in terminal still then I'm not sure.

**Comment by eileencodes** [comment] 2021-11-15 20:50
I'm sorry you're having trouble but I don't think this is a Rails issue. The `gem` command is what's hanging, not the `rails` command. My recommendation is to try installing other gems and if that also hangs check that your network or a proxy/firewall isn't blocking rubygems.org. I'm going to close this since it's not a bug with the framework.

**Closed by eileencodes** 2021-11-15 20:50 UTC
