### ISSUE TITLE
Cannot find/load capybara/dsl file sometimes with latest Rails version

### ISSUE THREAD

**Issue by jasnow** [rails/rails#28094] opened 2017-02-21 15:32 UTC
### Steps to reproduce

 1. Example: Clone https://github.com/jasnow/Practice-Git-with-Rails5edge repo.

 2. Run "rake" to see no errors.

 3. Then run "bundle update" to get new edge version of Rails.
   * Revision: 5716c4ddf4e03c75bd50df901a515ac445167a99

 4. Run "rake" and you get this error message:
   * LoadError: cannot load such file -- capybara/dsl

(Guidelines for creating a bug report are [available here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior

Before upgrading to latest Rails version, "rake" ran cleanly (no errors).

### Actual behavior

After upgrading to latest Rails version, "rake" gets this error message:
   * LoadError: cannot load such file -- capybara/dsl

### System configuration
**Rails version**: Edge Rails (gem 'rails', git: 'https://github.com/rails/rails')

**Ruby version**: 2.4.0 [ x86_64 ]

**Machine/OS: Mid-2014 MacBook Pro running 10.12.3.

**Comment by eileencodes** [comment] 2017-02-21 16:18
Sorry about that @jasnow. This should be fixed on master

**Closed** 2017-02-21 16:17 UTC
Labels: actionpack

**Comment by jasnow** [comment] 2017-02-21 19:15
Verified fixes.Thanks.

**Comment by fernandes** [comment] 2017-02-28 15:37
hi...

first, thank you for your great work on system tests @eileencodes 🙇 

I created a new rails app with the following command:

```bash
rails new --javascript=jquery --webpack=react --no-skip-yarn --no-skip-gemfile --no-skip-spring --skip-coffee --no-skip-javascript --no-skip-system-test app
```

And rails is complaining about `capybara/dsl`

I had to add `capybara` and `selenium-webdriver` to Gemfile... wouldn't it supposed to be added automatically once I passed `--no-skip-system-test` option?

ps: Sorry about posting on your closed issue @jasnow but searching on GH issues I got here, so I believe other ppl can come here too! 👍

**Comment by eileencodes** [comment] 2017-02-28 15:53
@fernandes I tested my rails copy and capybara and selenium were automatically added to the Gemfile when using the flags you posted. If you can reproduce reliably please open a new issue. If you don't want system tests then 5.1.beta1 is technically broken because the change that fixed this hasn't been released yet.

**Comment by fernandes** [comment] 2017-02-28 15:59
@eileencodes sure, thank you for your quick reply :)

**Comment by lucke84** [comment] 2017-10-18 11:29
@eileencodes I believe there's a typo in the [fix you mentioned above](https://github.com/rails/rails/commit/1d8466c38804a555df58ebe214c9aa0e240ad856): https://github.com/rails/rails/blob/1d8466c38804a555df58ebe214c9aa0e240ad856/railties/lib/rails/test_help.rb#L14
