### ISSUE TITLE
Shortcuts for `request.params[key]` and `request.params[key] = value` removed without deprecation.

### ISSUE THREAD

**Issue by tgxworld** [rails/rails#24555] opened 2016-04-15 06:22 UTC
When `ActionDispatch::Request` stopped inheriting from `Rack::Request`, the [methods](https://github.com/rack/rack/blob/241db7a81eb18860a0a7293675614472593c165a/lib/rack/request.rb#L19-L29) `[]` shortcut for  `request.params['some-key']` and `[]=` shortcut for `request.params['some-key'] = 'something'` were removed. I was wondering if there should at least be a deprecation warning to make upgrading easier. Otherwise, it is hard to upgrade to Rails 5 when multiple gems are still accessing the params using those methods.

### System configuration
**Rails version**: Rails 5.0.0.beta3

**Ruby version**: ruby 2.3.0p0

**Comment by maclover7** [comment] 2016-04-15 14:25
Hmm, if we want to remove these and go through a proper deprecation cycle, we will have to:
- ship a deprecation warning in 5.0.0 (and remove internal usage, if any)
- actually remove the methods in 5.1.0

I will take a look at this later today -- r? @maclover7

**Comment by maclover7** [comment] 2016-04-15 14:28
cc @tenderlove

**Comment by maclover7** [comment] 2016-04-16 00:35
PR incoming...

**Comment by maclover7** [comment] 2016-04-16 00:36
Opened PR #24572

**Comment by maclover7** [comment] 2016-04-16 01:05
Marking as a regression since there was no deprecation warning :grimacing:

**Comment by jeremy** [comment] 2016-04-16 20:54
We must keep compat, so we have some choices:

1. Revert the change.
2. A PR to add the same [Rack::Request convenience methods](https://github.com/rack/rack/blob/45acf49/lib/rack/request.rb#L19-L49) to AD::Request.
3. A Rack PR to move [Rack::Request convenience methods](https://github.com/rack/rack/blob/45acf49/lib/rack/request.rb#L19-L49) to Rack::Request::Helpers then a Rails PR to bump our Rack dep.
4. A Rack PR to move [Rack::Request convenience methods](https://github.com/rack/rack/blob/45acf49/lib/rack/request.rb#L19-L49) to a new Rack::Request::LikeItsAHashForReal and a Rails PR to bump our Rack dep and include the new module in AD::Request.

**Comment by maclover7** [comment] 2016-04-16 21:07
IMHO option 2 is the best route (since most of the methods are helpers, after all...?), but I think this might be a Rack Core Team question 😬

**Comment by jeremy** [comment] 2016-04-16 22:58
@maclover7 Have you reviewed the methods that were lost? What do you think we should do?

**Comment by maclover7** [comment] 2016-04-17 00:38
Ahh whoops -- I meant to say option 3 😲  (reorganize the convenience methods within Rack)

This is Rack's public API (and should stay within Rack), but I think other objects should be able to selectively include that behavior via a Module.

**Comment by vipulnsward** [comment] 2016-04-17 16:20
As of now, these are delegated ones- https://github.com/rack/rack/blob/45acf493f153bac95fa486bc5a8633baaa9e49e4/test/spec_request.rb#L1370-L1392

**Comment by jeremy** [comment] 2016-04-17 20:02
Downside with 3 is that it means all request-alike objects must also commit to a hash-y interface that they may wish to claim for other purposes. @tenderlove?

**Comment by maclover7** [comment] 2016-04-17 20:07
passing on the rails-bot love to @tenderlove :)

r? @tenderlove

**Comment by tenderlove** [comment] 2016-04-20 19:08
I think we should go with option 2.  I'm not sure we should be treating the request as a hash like object (though I'll entertain contrary arguments).

**Comment by tenderlove** [comment] 2016-04-20 20:43
After speaking with @jeremy on this, I think we should move the methods in to the module in Rack and then deprecate them.

**Comment by maclover7** [comment] 2016-04-20 20:49
👍 should I open up a PR on Rack for this?

**Comment by tenderlove** [comment] 2016-04-20 21:22
@maclover7 yes please

**Comment by jeremy** [comment] 2016-04-24 21:23
This needn't block 5.0.0 release candidate, though we would like to address it for final release. Removing milestone.

**Comment by tenderlove** [comment] 2016-05-08 00:30
These should be in rack at rack/rack@93b28997fd37920e2c8d34a48ec236a947434ab3 and rack/rack@7c3d700c00d13e0dead8f110a95606fd1332c5a2

**Closed by tenderlove** 2016-05-08 00:30 UTC
Labels: actionpack, attached PR, regression
