### ISSUE TITLE
ActiveRecord 5.x arel queries use NULL instead of record id

### ISSUE THREAD

**Issue by griffithchaffee** [rails/rails#29430] opened 2017-06-12 17:01 UTC
ActiveRecord 5.x queries built using arel and a record no longer pull the `id` of the record, instead `NULL` is used.

Looks like this may be similar to #29133 but I think this bugtest is a little more clear on the issue.

### Steps to reproduce

[bugtest](https://gist.github.com/griffithchaffee/9286304ce525e9ec2c18f3ee8820f3a1)

``` ruby
post = Post.find(1)
Post.arel_table[:id].eq(post).to_sql

# 4.x result: "posts"."id" = 1
# 5.x result: "posts"."id" = NULL
```

### Expected behavior
`to_param` should be called on passed record

### Actual behavior
`NULL` is used

### System configuration
**Rails version**: 5.x (5.1 and 5.0 break)

**Ruby version**: 2.4

**Comment by vipulnsward** [comment] 2017-06-12 18:41
Automatic typecasting has been deprecated and removed in 8.0

https://github.com/vipulnsward/arel/commit/1e24cd4525c7ff58f9f2d1323292c2d67244ec01

We can close this, but if https://github.com/rails/rails/issues/29133 is being caused by it, we will need to investigate it.

cc @rafaelfranca

**Closed by vipulnsward** 2017-06-12 18:41 UTC

**Comment by griffithchaffee** [comment] 2017-06-12 19:38
@vipulnsward thanks for the info!

Just a note to anyone else viewing this issue, this type of query did not output a deprecation warning in `rails v5.0.3` which used `arel v7.1.4`. My bugtest shows that this type of query also failed in `rails 5.0`.

A quick check of vipulnsward/arel@1e24cd4 makes it look like `column` was always `nil`

```ruby
      def quote value, column = nil
        return value if Arel::Nodes::SqlLiteral === value
        if column
          print_type_cast_deprecation
        end
        @connection.quote value, column
      end
```
