### ISSUE TITLE
Rails 7.2 ignores "self.table_name=" in a subclass, at least when using the Audited gem

### ISSUE THREAD

**Issue by pond** [rails/rails#52715] opened 2024-08-26 21:42 UTC
### Steps to reproduce

A minimal Rails application is attached:

[table_name_bug.zip](https://github.com/user-attachments/files/16754026/table_name_bug.zip)

* Once unpacked run `bundle install` as usual
* Run `bundle exec rake db:create db:migrate`

You can now switch between Rails 7.1 vs 7.2 via the Gemfile thus:

```ruby
gem "rails", "= 7.2.1"
# ...or...
gem "rails", "= 7.1.4"
```

* Run `bundle install` to ensure the application is using the configured Rails version
* Run `bundle exec rake test`

### Expected behavior

Rails 7.1.4's result for `bundle exec rake test` is a test pass. The test makes no assertions - it just shouldn't raise an exception.

```
$ bundle exec rake test  
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 22184

# Running:

.

Finished in 0.041376s, 24.1686 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

I expect an identical result in Rails 7.2.

### Actual behavior

Rails 7.2.1's result for `bundle exec rake test` is a test error caused by an unexpected exception.

```
$ bundle exec rake test  
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 21383

# Running:

E

Error:
UserTest#test_auditing:
ActiveRecord::StatementInvalid: Could not find table 'audits'
    test/models/user_test.rb:5:in `block in <class:UserTest>'


bin/rails test test/models/user_test.rb:4



Finished in 0.014166s, 70.5916 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

Note that if I hand-hack the Audited gem via `bundle open audited` so that the `Audited::Audit` class itself declares `self.table_name = 'audit_trails'`, then this test will now pass under Rails 7.2. The issue seems to be that the base class is being consulted for the table name when, instead, the in-use subclass should be.

**No other gem changes** at all are needed to provoke the issue. The *only* change is switching 7.1.4 vs 7.2.1 in the `Gemfile`. The `bundle install` for each reported, respectively:

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using activesupport 7.1.4 (was 7.2.1)
Using activemodel 7.1.4 (was 7.2.1)
Using actionview 7.1.4 (was 7.2.1)
Using activejob 7.1.4 (was 7.2.1)
Using activerecord 7.1.4 (was 7.2.1)
Using actionpack 7.1.4 (was 7.2.1)
Using actioncable 7.1.4 (was 7.2.1)
Using activestorage 7.1.4 (was 7.2.1)
Using actionmailer 7.1.4 (was 7.2.1)
Using railties 7.1.4 (was 7.2.1)
Using actionmailbox 7.1.4 (was 7.2.1)
Using actiontext 7.1.4 (was 7.2.1)
Using rails 7.1.4 (was 7.2.1)
Bundle complete! 9 Gemfile dependencies, 76 gems now installed.
```

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using activesupport 7.2.1 (was 7.1.4)
Using activemodel 7.2.1 (was 7.1.4)
Using actionview 7.2.1 (was 7.1.4)
Using activejob 7.2.1 (was 7.1.4)
Using activerecord 7.2.1 (was 7.1.4)
Using actionpack 7.2.1 (was 7.1.4)
Using actioncable 7.2.1 (was 7.1.4)
Using activestorage 7.2.1 (was 7.1.4)
Using actionmailer 7.2.1 (was 7.1.4)
Using railties 7.2.1 (was 7.1.4)
Using actionmailbox 7.2.1 (was 7.1.4)
Using actiontext 7.2.1 (was 7.1.4)
Using rails 7.2.1 (was 7.1.4)
Bundle complete! 9 Gemfile dependencies, 77 gems now installed.
```

### System configuration

The attached replication code was generated with Ruby 3.3.4 and Rails 7.2.1 via:

```sh                                      
rails new table_name_bug --skip-git --skip-docker --skip-keeps \
  -skip-action-mailer --skip-action-mailbox --skip-action-text \
  --skip-active-job --skip-active-storage --skip-action-cable \
  --skip-asset-pipeline --skip-javascript --skip-hotwire \
  --skip-jbuilder --skip-bootsnap --skip-rubocop \
  --skip-brakeman --skip-ci
```

(I just noticed the single hyphen typo in `skip-action-mailer `, which _is_ the command as-run; Rails didn't seem to care and it makes no difference to the test outcome or replication case. Our "real" application showing this is of course very dramatically larger and more complicated, including most of the components that are skipped above).

* Add Audited gem to bundle

```sh
cd table_name_bug
bundle install
bundle exec rails generate audited:install
```

* Edited migration's table name to "audit_trails" instead of "audits"
* Added a migration for table "users" with just a text column of "name"

```sh
bundle exec rake db:create db:migrate
```

Added models for `AuditTable` and `User` - see `app/models` - specifying the custom table name in the `AuditTable` model and indicating that this class should be used for auditing via `config/initializers/audit.rb`.

This was all done in Rails 7.2.1 to show it wasn't a question of upgrading from Rails 7.1 or earlier that causes issues. That said, we now must change all cases of `[7.2]` to `[7.1]` in migrations and update `application.rb` to load defaults for 7.1, in order to be able to switch back to Rails 7.1.x at all in the `Gemfile`. After that, tests can be run as described above.

**Comment by rafaelfranca** [comment] 2024-08-27 00:19
Caused by a0993f81d0.

The reason why this fail is because you inherited from `Audit` but didn't mark that model as abstract, so Rails will try to define its attributes using the `table_name` defined in `Audit`, which is `audits`.

Of course I don't think this was an intended breakage. It was caused by trying to load the schema when defining the attributes.

Here is the minimal reproduction script:

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "7.2.1"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end

  create_table :audit_trails, force: true do |t|
    t.integer :auditable_id
    t.string :auditable_type
  end
end

class User < ActiveRecord::Base
  has_many :audits, as: :auditable, class_name: "AuditTrail", inverse_of: :auditable

  after_create :audit_create

  def audit_create
    audits.create!
  end
end

class Audit < ActiveRecord::Base
  belongs_to :auditable, polymorphic: true
end

class AuditTrail < Audit
  self.table_name = "audit_trails"
end

class BugTest < Minitest::Test
  def test_association_stuff
    u = User.create!(name: "Test one")
    u.update!(name: "Test two")
  end
end
```

cc @byroot

**Comment by pond** [comment] 2024-08-27 00:42
@rafaelfranca

> ...you inherited from `Audit` but didn't mark that model as abstract...

It would be up to the Audited gem to do so since that's where the `Audit` model is defined, but that model _is not abstract_ anyway. It is the model you would use unless you are subclassing for additional custom behaviour, as per the Gem's documentation. I see nothing about that which would be particularly unusual or surprising in nature; it seems like a sensible, valid approach to me, BICBW.

So - hopefully a fix can be produced within Rails to get things working again `:-)`

**Comment by byroot** [comment] 2024-08-27 07:03
I think it would be preferable to fix that in audited gems.

From Active Record point of view, if a model isn't marked as `abstract`, then its `table_name` must exist.

I think it's very easy to workaround this in your app for now by marking the base class as abstract or assigning the real table table name to it. And then it would be easy for the gem to automatically mark the model as abstract when subclassed, or something like that.

**Comment by ahmar7** [comment] 2024-08-27 07:34
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by byroot** [comment] 2024-08-27 07:36
If anyone received the previous mail. Don't do it, this is a malware. Reporting it to GitHub.

**Comment by rafaelfranca** [comment] 2024-08-27 15:51
Thanks Jean. I agree this should be fixed in the gem. If you subclass a model, its table needs to exist unless you mark it as `abstract_class`. The fact that it worked before was by accident, not by design.

**Closed by rafaelfranca** 2024-08-27 15:51 UTC
Labels: activerecord, With reproduction steps

**Comment by pond** [comment] 2024-08-27 20:43
@byroot That's absolutely not true, the **whole point** of that gem is to provide:

* An out-of-box class which can be used or subclassed for custom behaviour
* An ability to configure and override the table name (which we use)
* In combination, the table name definition in the subclass *must be honoured*

This is a *widely used gem* that's existed almost since the dawn of Rails itself. **Please, please reconsider**.

@rafaelfranca / @byroot If you think it should be fixed in the gem, how exactly would you do that, given the above? I don't see how it's possible and I don't see how breaking something that's worked since (waves hands) kind of forever is helpful to Rails or its community.

This is a minor release, not a major release. Semver dictates no breaking changes.

**Comment by byroot** [comment] 2024-08-27 20:48
> Remember, when subclassed, that base class is never directly instantiated.

Yeah, so the gem can define `inherited` and set `self.abstract_class = true` when it happens. 

> This is a minor release, not a major release. Semver dictates no breaking changes.

https://guides.rubyonrails.org/maintenance_policy.html

**Comment by byroot** [comment] 2024-08-27 20:50
> This is a minor release, not a major release. Semver dictates no breaking changes.

And to clarify. In SemVer only documented behavior can be considered breaking change. The behavior this gem was relying on wasn't documented (it actually contradict the documentation). Every single ActiveRecord::Base subclass must either have its `.table_name` point to an actual table OR have `abstract_class = true`.

**Comment by pond** [comment] 2024-08-27 21:14
@byroot Can you point me at the docs stating that, please? It would help with traction on the corresponding issue with the Audited gem team.

**Comment by byroot** [comment] 2024-08-27 21:18
https://api.rubyonrails.org/classes/ActiveRecord/Inheritance/ClassMethods.html

>  If you are using inheritance with Active Record and don’t want a class to be considered as part of the STI hierarchy, you must set this to true.

**Comment by pond** [comment] 2024-08-27 21:18
@byroot Thanks. I'll continue this over at https://github.com/collectiveidea/audited/issues/725.

**Comment by pond** [comment] 2024-08-28 22:12
@byroot / @rafaelfranca As a closing note:

https://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html

> ...If you don’t have a type column defined in your table, **single-table inheritance won’t be triggered**. In that case, it’ll **work just like normal subclasses with no special magic** for differentiating between them or reloading the right type with find.

(My emphasis).

This directly contradicts the quoted part of https://api.rubyonrails.org/classes/ActiveRecord/Inheritance/ClassMethods.html and so invalidates the reasons herein for leaving the change in Rails as-is. However, perhaps you would prefer to fix the overall documentation because it seems **this change has forced any inheritance, even when not STI, to always have a table present for the base class.**

**Comment by pond** [comment] 2024-08-28 22:34
@rafaelfranca / @byroot

Rounding this off - fixing it in Audited looks impractical, or at least extremely ugly; rationale including solutions attempted and the final answer can be tracked via https://github.com/collectiveidea/audited/pull/726, for sake of interest.

If you encounter other issues that seem to fall into the same domain in future, you might need to make documentation-based recommendations rather than code solutions. Setting something to be an abstract class is the right answer if ActiveRecord STI is actually engaged but, in the case of the Audited gem, it is not.

**Comment by mazib** [comment] 2024-10-17 05:08
Not sure if this adds any value to the discussion here, but usage of the audited gem without a custom table name (e.g.; remaining on the default of `"audits"`) causes `Serialization failed: Tried to dump unspecified class: Class`

The only difference in behavior was an upgrade to Rails 7.2.1.1 from 7.1.
