### ISSUE TITLE
Rails 7 - ActiveSupport Cache raises "Zlib::DataError: incorrect header check"

### ISSUE THREAD

**Issue by shivabhusal** [rails/rails#47601] opened 2023-03-08 06:08 UTC
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate/comment-out the following line to switch between Rails versions.
  gem "activesupport", "~> 7.0.4"
  # gem "activesupport", "~> 6.1.2"

  gem "redis"
end

require "active_support"
require "minitest/autorun"

# This test case is a reproduction of the issue I faced when trying to compress cache entries.
# below, threshold does not matter. No matter how long is the value, it will raise error in Rails 7
class CompressedCacheBugTest < Minitest::Test

  def test_can_use_redis_client_with_compression
    # It requires a redis server running on localhost:<default-port>
    cache = ActiveSupport::Cache.lookup_store(:redis_cache_store, {url: 'redis://localhost'})

    value = 'somevalue'

    cache.fetch('my-cache-key', compressed: true, force: true) do
      value
    end

    assert_equal value, cache.fetch('my-cache-key')
  end

  def test_can_use_memory_store_with_compression
    cache = ActiveSupport::Cache.lookup_store(:memory_store)

    value = 'somevalue'

    cache.fetch('my-cache-key', compressed: true, force: true) do
      value
    end

    assert_equal value, cache.fetch('my-cache-key')
  end
end
```

### Expected & Actual behavior
In Rails 6 it was working just fine. You can switch between versions in the example above.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 2.7.7

**Comment by yahonda** [comment] 2023-03-08 07:19
According to `git bisect`, this behavior changes since https://github.com/rails/rails/commit/a0e4920296e927fc80a8ff362d5516e24636a7de

**Comment by yahonda** [comment] 2023-03-08 09:38
Please feel free to open a pull request.

**Comment by ghiculescu** [comment] 2023-05-07 09:00
The kwarg that should be used is `compress:`, not `compressed:`. [Docs here](https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-write).  If you change the reproduction script to use `compress:` it works fine.

So I'm going to close this, though I think a PR to that warns if the wrong kwarg is provided might not be a bad idea...

**Closed by ghiculescu** 2023-05-07 09:00 UTC
Labels: activesupport, With reproduction steps
