### ISSUE TITLE
ActiveModel::Dirty #{attribute_name}_changed? returning nil instead of false

### ISSUE THREAD

**Issue by batter** [rails/rails#24220] opened 2016-03-16 22:28 UTC
### Steps to reproduce
[Here's a gist using the ActiveRecord bug template demonstrating the issue](https://gist.github.com/batter/6947876631e7d72144c9)

### Expected behavior
I would expect that calling `ModelKlass.new.attribute_name_changed?` to always return `true` or `false`. Specifically in this case it should return `false` if the attribute has yet to changed, since it is a method with a question mark appended to the end of it.

### Actual behavior
It returns `nil` in these cases. This is a departure from the behavior in the rest of the Rails 4.2 releases

### System configuration
**Rails version**:
4.2.6

**Ruby version**:
I saw it happen on 2.2.1 and 2.3.0

**Comment by maclover7** [comment] 2016-03-16 22:55
This was caused by c7802dccba69517083000261477f7e1d410e1cca -- cc @sgrif

**Comment by jeremy** [comment] 2016-03-16 23:05
We generally treat treat `?` methods as truthy, not literally boolean. But I think it's reasonable to be flexible, particularly when it's an otherwise-boolean value changing on a stable release line.

**Comment by sgrif** [comment] 2016-03-16 23:10
`attribute_changed?` doesn't even show up in the documentation, but `changed?` is documented as returning a boolean, so I'm willing to call this one a bug as it implies that `attribute_changed?` would return a boolean as well. http://api.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-changed-3F

**Comment by Sen-Zhang** [comment] 2016-03-17 17:41
Integer type attributes have the same problem too.

**Comment by batter** [comment] 2016-03-18 21:20
@Sen-Zhang as per my understanding, the attribute type does not matter for this

**Comment by Sen-Zhang** [comment] 2016-03-18 21:47
@batter I agree

**Comment by maclover7** [comment] 2016-04-20 19:58
Closed via #24515.

**Closed by maclover7** 2016-04-20 19:58 UTC
Labels: activemodel, attached PR, With reproduction steps
