### ISSUE TITLE
wrong behaviour of Active Record's preloader after 4.1

### ISSUE THREAD

**Issue by kamciokamcio** [rails/rails#20704] opened 2015-06-26 09:39 UTC
When using Rails 4.0 I cas use preloader like this:
>u1 = User.first
ActiveRecord::Associations::Preloader.new(u1, :posts).run

From Rails 4.1 Preloader API changed. Now when I run in rails console: 
>u1 = User.first
ActiveRecord::Associations::Preloader.new.preload(u1, :posts)

I get:
>2.1.5 :007 > u1 = User.first
  User Load (0.3ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
 => #<User id: 1> 
2.1.5 :008 > ActiveRecord::Associations::Preloader.new.preload(u1, :posts)
  Post Load (0.3ms)  SELECT "posts".* FROM "posts" WHERE "posts"."user_id" IN (1)
  Post Load (0.2ms)  SELECT "posts".* FROM "posts"
  Post Load (0.2ms)  SELECT "posts".* FROM "posts"
 => [#<ActiveRecord::Associations::Preloader::HasMany:0xb31d228 @klass=Post(id: integer, user_id: integer), @owners=[#<User id: 1>], @reflection=#<ActiveRecord::Reflection::HasManyReflection:0xbe319d4 @name=:posts, @scope=nil, @options={:inverse_of=>:user}, @active_record=User(id: integer), @klass=Post(id: integer, user_id: integer), @plural_name="posts", @automatic_inverse_of=nil, @type=nil, @foreign_type="posts_type", @constructable=true, @association_scope_cache={true=>#<ActiveRecord::StatementCache:0xb39ce74 @query_builder=#<ActiveRecord::StatementCache::Query:0xb39ce88 @sql="SELECT \"posts\".* FROM \"posts\" WHERE \"posts\".\"user_id\" = ?">, @bind_map=#<ActiveRecord::StatementCache::BindMap:0xb39ed8c @indexes=[0], @bind_values=[[#<ActiveRecord::ConnectionAdapters::Column:0xb7ffdcc @name="user_id", @cast_type=#<ActiveRecord::Type::Integer:0xb80c518 @precision=nil, @scale=nil, @limit=nil, @range=-2147483648...2147483648>, @sql_type="integer", @null=true, @default=nil, @default_function=nil>, #<ActiveRecord::StatementCache::Substitute:0xb39f980>]]>>}, @scope_lock=#<Mutex:0xbe318bc>, @class_name="Post", @inverse_of=#<ActiveRecord::Reflection::BelongsToReflection:0xbd14498 @name=:user, @scope=nil, @options={:inverse_of=>:posts}, @active_record=Post(id: integer, user_id: integer), @klass=User(id: integer), @plural_name="users", @automatic_inverse_of=nil, @type=nil, @foreign_type="user_type", @constructable=true, @association_scope_cache={}, @scope_lock=#<Mutex:0xbd1436c>, @class_name="User", @inverse_of=#<ActiveRecord::Reflection::HasManyReflection:0xbe319d4 ...>, @foreign_key="user_id">, @foreign_key="user_id", @active_record_primary_key="id">, @preload_scope=#<struct values={}, bind_values=[]>, @model=User(id: integer), @scope=#<ActiveRecord::Relation [#<Post id: 1, user_id: 1>, #<Post id: 2, user_id: 1>, #<Post id: 3, user_id: 1>, #<Post id: 4, user_id: 2>]>, @owners_by_key={1=>[#<User id: 1>]}, @preloaded_records=[#<Post id: 1, user_id: 1>, #<Post id: 2, user_id: 1>, #<Post id: 3, user_id: 1>], @reflection_scope=#<ActiveRecord::Relation [#<Post id: 1, user_id: 1>, #<Post id: 2, user_id: 1>, #<Post id: 3, user_id: 1>, #<Post id: 4, user_id: 2>]>>] 

Query for posts is made three times - once with condition for specific user, and twice getting all posts - which is not optimal. 

[Sample application for replication](https://github.com/kamciokamcio/preloader-error)

**Comment by senny** [comment] 2015-06-29 13:02
Hey @kamciokamcio 

The Active Record Preloader API is private and not intended for public use. That's why the API can change without deprecation notices. It's purpose is internal to provide the public facing `Relation#includes` functionality.

I'm closing this as `includes` is working as expected. If you have the same issues using includes please report back and I'll happily reopen.

Also, I was not able to reproduce this problem on `master` or `4-2-stable` using [this script](https://gist.github.com/senny/429b5057776ab96d8ebc)

**Closed by senny** 2015-06-29 13:02 UTC
