### ISSUE TITLE
Relative URL + Engine = path doubling

### ISSUE THREAD

**Issue by eltiare** [rails/rails#21459] opened 2015-09-02 02:57 UTC
In the current version of Rails if I mount an engine in an app and then assign it a relative path (config.relative_url_root), linking from the main app to the engine causes it to double the relative path. For example: the link_to helper generates '/relative/relative/ship' when it should just generate '/relative/ship'. Going from a page in the engine to the main app does not do this. I do not know what will happen with multiple engines mounted, but I am willing to try it.

I have created a barebones application to exemplify this problem here:   https://github.com/eltiare/relative-url-engine-bug

This is a big problem for those who use engines. I'm not sure how I'd go about writing a test case for this, but I will look into it tomorrow.

**Comment by eltiare** [comment] 2015-09-02 17:56
I was made aware of a workaround, which is to add this to the app's configuration: 

```
# In order to fix the problem, the following options must be set.
routes.default_url_options ||= {}
routes.default_url_options[:script_name]= ''
```

I have updated the example application.

**Comment by y-yagi** [comment] 2015-09-03 12:22
I think this issue is related to #20958.

**Comment by merhard** [comment] 2015-09-05 02:15
This seems to be a duplicate of issue #20920 and is a regression introduced in v4.2.3 that is yet to be addressed.

As @y-yagi, said, #20958 is a pull request attempting to fix this.

**Comment by eltiare** [comment] 2015-09-06 04:18
Sorry, I did look for any possible duplicates but didn't find it. Would've thought for sure it would have been merged by now. :)

**Comment by merhard** [comment] 2015-09-24 15:24
Fyi, I added a new pull request with a different solution to this issue. #21743 Hopefully this issue can be resolved soon.

**Closed** 2015-10-07 21:26 UTC
Labels: engines

**Comment by chrisbloom7** [comment] 2016-03-01 03:01
This is not fixed in Rails 4.2.5, I'm still getting doubled subdirectories in my routes. I downgraded to 4.2.2 and it works as expected.

**Comment by pixeltrix** [comment] 2016-03-01 13:00
@chrisbloom7 the commit that fixes it (37864d7) isn't in 4.2.5 - it will be in 4.2.6. The release process for 4.2.5 took quite a while so it was already branched off 4-2-stable at the point I backported it.

**Comment by merhard** [comment] 2016-03-01 22:55
@pixeltrix Are you sure? That commit is listed in the [v4.2.5 Changelog](https://github.com/rails/rails/blob/v4.2.5/actionpack/CHANGELOG.md). The company I work for has been using Rails `>= v4.2.5` in production since it was released and have not seen this issue occur on that version.

@chrisbloom7 Does upgrading to Rails v4.2.6.rc1 solve your issue? If not, please provide a sample application or script that reproduces what you are experiencing so it can be investigated.

**Comment by pixeltrix** [comment] 2016-03-03 09:37
@merhard you're right - I remember that I had to cherry pick it to the 4-2-5 branch manually and that's why the 4-2-stable commit isn't listed as being in 4.2.5. Sorry for misleading you @chrisbloom7 - can you try to reproduce again?

**Comment by chrisbloom7** [comment] 2016-03-06 19:49
@pixeltrix You are correct. After downgrading to 4.2.2 things started working as expected, but then bumping back to 4.2.5 didn't cause the broken behavior to return. I'll chalk it up to a hiccup with Passenger itself.

**Comment by arianf** [comment] 2018-10-25 22:28
@chrisbloom7 I'm hitting this with rails 5.1.6, does that mean this is likely a passenger issue? If so how did you fix it within passenger?
