### ISSUE TITLE
:time doesn't follow the same dst behavior of :datetime

### ISSUE THREAD

**Issue by plentz** [rails/rails#24880] opened 2016-05-06 02:56 UTC
### Steps to reproduce

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '>= 5.0.0.beta4'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
ActiveRecord::Base.time_zone_aware_types << :time
ActiveRecord::Base.time_zone_aware_attributes = true

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.time :time_offset_bug
  end

end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_offset_bug
    Time.zone = 'Brasilia'
    assert_equal "-03:00", Time.current.formatted_offset # this works

    post = Post.create!(time_offset_bug: "14:00")

    # this blows up
    assert_equal "-03:00", post.time_offset_bug.formatted_offset
    assert_equal "2000-01-01 17:00:00 UTC", post.time_offset_bug.utc.to_s
  end
end

```

### Expected behavior
`post.time_offset_bug.utc_offset` should be -3 (and the `time` saved in the database should be saved in UTC)

### Actual behavior
`post.time_offset_bug.utc_offset` is -2 and the time saved in the database isn't saved in UTC.

### System configuration
Rails 5.0.0.beta4(happens at `master` as well)
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by plentz** [comment] 2016-05-06 03:00
maybe related with #15726. cc @sgrif

**Comment by plentz** [comment] 2016-05-06 20:34
PS: I think that fixing this bug isn't going to be that hard. But once fixed, what we should do with users that were already using it and the data in their databases is wrong? 💭

**Comment by sgrif** [comment] 2016-05-06 20:42
I think this is just misunderstanding how Active Record's :UTC vs :local settings work, but I'll take a closer look after Railsconf

**Comment by vipulnsward** [comment] 2016-05-06 20:49
This is due to DST on different values you are using, and not an issue here.
```
puts Time.zone.parse("2000-01-01 17:00:00 UTC").formatted_offset
-02:00
puts Time.zone.now.formatted_offset
-03:00
```

**Comment by sgrif** [comment] 2016-05-06 20:50
:heart: @vipulnsward

**Comment by plentz** [comment] 2016-05-06 21:35
@vipulnsward Thanks for the feedback, but still unclear to me why `post.time_offset_bug.utc` isn't returning `17:00` as (I think) it should(`14:00` + 3 from my timezone to UTC)

**Comment by vipulnsward** [comment] 2016-05-07 23:08
@plentz please note that you are operating over two different object types.
Time vs TimeWithZone. From your example:

```
puts Time.current.dst?
=> false
puts post.time_offset_bug.dst?
=> true
puts post.time_offset_bug.utc.dst?
=> false
puts post.time_offset_bug.utc.in_time_zone.dst?
=> true
```

`post.time_offset_bug.utc` is a `Time` object without this information.

**Comment by plentz** [comment] 2016-05-08 21:08
@vipulnsward @sgrif sorry for being so insistent, but guys, I *really* think that we have something very wrong here. I just created a new test cases that should be more clear:

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '>= 5.0.0.beta4'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
ActiveRecord::Base.time_zone_aware_types << :time
ActiveRecord::Base.time_zone_aware_attributes = true

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :datetime_from_time_current
    t.time :time_from_time_current
  end

end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_dst_bug
    Time.zone = 'Brasilia'

    post = Post.create!(
      datetime_from_time_current: Time.current,
      time_from_time_current: Time.current
    )

    assert_equal false, post.datetime_from_time_current.dst?
    assert_equal false, post.time_from_time_current.dst?
  end
end
```

The problem looks like to be related with DST (and then affecting the `timezone_offset` that I reported initially)

**Comment by sgrif** [comment] 2016-05-08 21:13
I am currently in the process of moving. I will look more closely when I have time

**Comment by bzanchet** [comment] 2016-05-09 14:13
Hey folks, I have a new example that should clarify the root cause of this bug:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '>= 5.0.0.beta4'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
ActiveRecord::Base.time_zone_aware_types << :time
ActiveRecord::Base.time_zone_aware_attributes = true

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.time :the_time
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_dst_bug
    Time.use_zone('Brasilia') do # GMT-3
      post = Post.create!(the_time: "8:00") # 11:00 UTC
      post.reload # it's saved as 10:00 UTC
      assert_equal 8, post.the_time.hour # it's fine because DST conversion in and out "cancels out"
      Time.use_zone('UTC') do # GMT 0
        post.reload
        assert_equal 11, post.the_time.hour # failure
      end
    end
  end
end
```

The problem seems to happen because the string `"8:00"` gets converted into a TimeWithZone at `1/1/2000`, which is DST period for `Brasilia`, and then saved as `"10:00UTC"` instead of `"11:00UTC"`.

The bug ins't instantly visible because the same problem - but the other way around - happens when parsing data from the database: it defaults to `1/1/2000`, which wrongly assumes DST, and then the error "cancels out".

Something similar happens if I use `Time.current`: it keeps the hour/minute part of it but not the date, thus assuming DST when it shouldn't. For instance, right now it's `2016-05-09 11:03:26` but the Post object ends up with a `TimeWithZone "2000-01-01 13:03:26"` (when the correct value is `14:03:26`).

Does that make sense?

**Comment by sgrif** [comment] 2016-05-09 14:39
So this isn't a bug, just a side effect of how we have to handle time zones here. Times in SQL inherently have no date, and aren't affected by DST (other than the time zone name being `PDT` or `PST`). However, we have no equivalent type in Ruby to map to, and ruby `Time` objects *do* have a date. We have to pick one arbitrarily, and the date that we've historically picked is 2000-01-01. When you add time zones into the mix, some time zones will be in DST, others won't. For a single given time zone however, it will be consistent, and converting between them will work properly.

The issue with your bug report is that you're assuming the `Brazilia` time zone is UTC-3. It isn't. On that date it is UTC-2. The time is stored as the appropriate representation. There's no "DST canceling out" as you've described it. For the results of time columns to be consistent, we *have* to pick an arbitrary date and use it consistently.

Even if we assumed that we want to avoid DST entirely here (which I'm not sure we do), I don't think there's any possible action we could take. To ensure that the resulting ruby `Time` object was not in DST, we'd have to change the date depending on the time zone. This would completely break comparisons between multiple time columns.

**Closed by sgrif** 2016-05-09 14:39 UTC
Labels: activesupport

**Comment by bzanchet** [comment] 2016-05-09 14:55
hey @sgrif, thanks for the throughout reply. I agree that there's no equivalent type in ruby to handle a time with no date and this seems to be the root cause of this problem.

Anyway.

I insist it's a bug because time is supposed to be consistent between timezones (right?) and the date is an internal implementation detail that shouldn't matter to the user (again, right?). So, speaking strictly from a user's perspective, 8AM GMT-3 should be 11AM UTC.

Just to be clear, we're dealing with times and timezones only - _dates and DST doesn't even come into question unless we start diving into implementation details_.

It's like I want to display a message to my users starting 5 minutes from now, for 30 minutes, but then my London users won't see it until tomorrow.

**Comment by sgrif** [comment] 2016-05-09 15:07
If you're only storing for display purposes, it's likely best to use UTC
and not have the attribute be tz aware. You can also convert it to the
current date to have the DST semantics applied to the current date.

> DST doesn't even come into question unless we start diving into
implementation details.

DST always comes into play. Times would convert differently depending on
the date they were read, otherwise.

**Comment by bzanchet** [comment] 2016-05-09 16:27
hey @sgrif, thanks again for taking the time to discuss this. Here's what happens if I try to save it as UTC:

```ruby
class BugTest < Minitest::Test
  def test_dst_bug
    Time.use_zone('Brasilia') do # GMT-3
      now = Time.current # 13h30
      post = Post.create!(the_time: now.utc) # 16:30 UTC
      post.reload # it's saved as 16:30 UTC
      assert_equal 13, post.the_time.hour # fail: Expected: 13, Actual: 14
    end
  end
end
```

I wish this workaround worked, but it only highlights the fact that `1/1/2000` doesn't work every time. Is this what you meant by `it's likely best to use UTC`?

**Comment by sgrif** [comment] 2016-05-09 16:30
No. I mean not using time zone aware attributes on fields where it's not
needed -- or setting Time.zone to UTC

**Comment by sgrif** [comment] 2016-05-09 16:31
Also just to clarify one last point before I log off, I would love to
improve this behavior as I agree there is something unintuitive. I just
don't think there is an alternative that would work here.

**Comment by bzanchet** [comment] 2016-05-09 17:26
Awesome. I do believe there's a better way, and I wish I had the time to go in and write a patch myself (I might as well do it next weekend).

So, here's the main argument: the central idea behind the current implementation is to convert the time to UTC and then store it - so we can decide later what to do about conversion (as in: when reading back from the database we have the choice to convert it back to whatever timezone we want or just stay on UTC).

Does that sound right? To me, it sure looks like the best approach.

If we agree to this point, there's one remaining question:

> DST always comes into play. Times would convert differently depending on the date they were read, otherwise.

it depends on whether DST is analogous to jumping one time zone or a special case that should be handled independently (I don't know the answer to that question, and I believe it doesn't matter for fixing this bug - I'm all for *not* changing the current behaviour). Would you agree?

All that said, here's the facts:

**Walking timezones works**

- 8AM stored on UTC should read as 9AM when read on UTC+1, 10AM on UTC+2 etc... [1].
- 8AM stored on UTC should read as 3AM when read on UTC-5 (EST), 2AM on UTC-6 (CST) etc... [2].

**Entering and leaving DST doesn't affect stored time, that also works:**

- 8AM stored _outside DST_ should be read as 8AM when read _during_ DST
- 8AM stored _during DST_ should read as 8AM when read _outside_ DST

(and it doesn't matter if it's EST/EDT or BST/BDT)


This all sounds right and consistent, right? But then we're failing here:

**South America shouldn't be different**.

- 8AM stored on UTC should read as 5AM when read on UTC-3 [3]

Am I missing something here?



[1] 
```ruby
  # all good here
  def test_europe
    Time.use_zone('London') do # GMT 0
      post = Post.create!(the_time: "8:00")
      post.reload
      assert_equal 8, post.the_time.hour
      Time.use_zone('Berlin') do # GMT+1
        post.reload
        assert_equal 9, post.the_time.hour
      end
      Time.use_zone('Helsinki') do # GMT+2
        post.reload
        assert_equal 10, post.the_time.hour
      end
    end
  end
```

[2]
```ruby
  # all good here
  def test_north_america
    Time.use_zone('London') do
      post = Post.create!(the_time: "8:00")
      post.reload
      assert_equal 8, post.the_time.hour
      Time.use_zone('Eastern Time (US & Canada)') do # GMT-5
        post.reload
        assert_equal 3, post.the_time.hour
      end
      Time.use_zone('Central Time (US & Canada)') do # GMT-6
        post.reload
        assert_equal 2, post.the_time.hour
      end
    end
  end
```

[3]
```ruby
  # fails 
  def test_south_america
    Time.use_zone('London') do # GMT 0
      post = Post.create!(the_time: "8:00")
      post.reload
      assert_equal 8, post.the_time.hour
      Time.use_zone('Brasilia') do # GMT-3
        post.reload
        assert_equal 5, post.the_time.hour # fails; Actual: 6
      end
    end
  end
```

**Comment by bzanchet** [comment] 2016-05-09 19:11
Ah, also please notice that both New York (EST) and Dallas (CST) are on DST right now (thus using EDT/CDT, GMT-4 and GMT -5, respectively) but that doesn't seem to affect the time conversion. I think the current behaviour is the right way to do it and America/Sao_Paulo should't be the only exception :)

**Comment by lazaronixon** [comment] 2022-09-28 23:22
@rafaelfranca WTF???

**Comment by lazaronixon** [comment] 2022-09-29 20:03
lib/time_only_type.rb
```ruby
class TimeOnlyType < ActiveModel::Type::DateTime
  TIME_FORMAT = "%H:%M:%S"

  def cast(value)
    super("#{Date.today} #{value}") if value.present?
  end

  def serialize(value)
    super(value).strftime(TIME_FORMAT) if value.present?
  end
end
```

config/initializers/time_only.rb
```ruby
require "time_only_type"
ActiveRecord::Type.register :time_only, TimeOnlyType
ActiveModel::Type.register  :time_only, TimeOnlyType
```

app/models/availability.rb

```ruby
class Availability < ApplicationRecord
  attribute :starts_at, :time_only
  attribute :ends_at,   :time_only
end
```

**Comment by everton** [comment] 2023-06-22 00:39
Rails force the date part of that object to be 2000-01-01 on this line of ActiveModel:

  https://github.com/rails/rails/blob/main/activemodel/lib/active_model/type/time.rb#L73

So, if you need to change this behavior for the entire application, I think you will need to replace/monkey-patch this method, changing the hardcoded string by the `::Date.today` from the previous workaround, OR prepending this class and replacing the returned object date part, something like this:

config/initializers/time_casted_for_today.rb

```
module TimeCastedForToday
  def cast_value(...)
    super&.change(::Date.today.then { { year: _1.year, month: _1.month, day: _1.day }})
  end
end

ActiveModel::Type::Time.prepend TimeCastedForToday
```

**Comment by Paul-Bob** [comment] 2024-10-08 12:30
> Workaround
> 
> config/initializers/time_only.rb
> 
> ```ruby
> class TimeOnlyType < ActiveRecord::Type::DateTime
>   def cast(value)
>     value.is_a?(::String) ? super("#{Date.today} #{value}") : super
>   end
> end
> 
> ActiveRecord::Type.register :time_only, TimeOnlyType
> ```
> 
> app/models/availability.rb
> 
> ```ruby
> class Availability < ApplicationRecord
>   attribute :starts_at, :time_only
>   attribute :ends_at,   :time_only
> end
> ```

Is there a specific reason for this not being set as the default behavior? It would reduce friction with DST during conversions compared to using `2000-01-01`. Are there any benefits on using `2000-01-01`?

**Comment by everton** [comment] 2024-10-08 12:37
@Paul-Bob After some time using the TimeOnly type I found the workaround required more adaptations to handle some cases for comparisons, conversions, and other requirements from places like forms, etc. But I agree with you that the arbitrary date is pretty unexpected and leads to mistakes

**Comment by everton** [comment] 2024-10-08 12:44
The code as I'm using it right now (it has been more than a year since I touched this code the last time, so I don't remember all the details, but if you need I can try to understand it again with you).

> config/initializers/time_only.rb

```ruby
class TimeOnly
  def hour = @hours
  def  min = @minutes
  def  sec = @seconds

  # We replicate Postgres allowed values here, so both '09:00'
  # and '09:00:00' are valid values (but not just 09)
  def initialize(values = [0, 0, 0])
    if values.is_a? Array
      @hours, @minutes, @seconds = values
      @seconds ||= 0
    elsif values.is_a? Numeric
      @hours, @minutes, @seconds = Time.use_zone('UTC') {
        Time.zone.at(values).then { [_1.hour, _1.min, _1.sec] }
      }
    elsif values.is_a? String
      @hours, @minutes, @seconds = parse_string(values)
    elsif values.respond_to? :hour
      @hours, @minutes, @seconds = values.hour, values.min, values.sec
    else
      raise "Don't know how to convert #{values.inspect} into TimeOnly"
    end

    validate_arguments!
  end

  def to_i = (@hours * 3600) + (@minutes * 60) + (@seconds || 0)

  # We need to accept the timezone to allow Setting class to convert
  # the TimeOnly objects using the timezone selected by the freelancer
  def to_time(time_zone = 'UTC')
    # Time.zone.now.change(hour: @hours, min: @minutes, sec: @seconds)
    Time.use_zone(time_zone) { Time.zone.at(to_i) }
  end

  # TODO: reconsider if we must keep unsing Time methods like hour, and strftime
  # I'm not sure if we must keep using Time methods like strftime,
  # I'm afraid this may bring more problems with timezones and dates,
  # but on the other side, we would must be forced to create our own
  # ways to tormat it
  delegate :strftime, :in_time_zone, to: :to_time

  def to_s
    if @seconds.blank? || @seconds == 0
      '%02d:%02d'      % [ @hours, @minutes ]
    else
      '%02d:%02d:%02d' % [ @hours, @minutes, @seconds ]
    end
  end

  def +(secs) = self.class.new(to_i + secs)
  def -(secs) = self.class.new(to_i - secs)

  # By converting to_i we can just delegate the comparison methods
  # We need them for things like stepping through the range of start..end
  # to generate the list of available slots of time
  include Comparable
  def succ   = self.class.new(to_i + 1) # Required to create ranges!
  def <=>(other)
    return unless other # Just replicating what 1 <=> nil do: return nil

    return to_i <=> other.to_i if other.is_a? self.class

    # deal with strings to avoid converting params manually on controllers
    # TimeOnly.new('09:00') > '09:00 AM'
    return self <=> self.class.new(other) if other.is_a? String

    # we need to cast the current object to a Time (or similar) object
    # conserving time-zone, etc, and replacing hour, min, and sec
    cast_in(other.dup) <=> other
  end

  alias_method :before?, :<
  alias_method :after?,  :>

  def cast_in(time_like_object)
    time_like_object.dup.change(hour: hour, min: min, sec: sec)
  end

  private
  def parse_string(values)
    Time.use_zone('UTC') {
      Time.zone.parse(values).then { [_1.hour, _1.min, _1.sec] }
    }
  end

  def validate_arguments!
    # Reuse Ruby Time class to ensure values are inside valid ranges
    Time.new(2000, 1, 1, @hours, @minutes, @seconds)
  rescue ArgumentError => e
    raise e # Re-raise the Time exceptions replacing it's backtrace
  end
end

class TimeOnlyType < ActiveRecord::Type::Value
  def cast(value)
    return if value.blank?

    if value.is_a? Hash # Casting from params
      # When params came as {1=>2023, 2=>7, 3=>3, 4=>9, 5=>0, 6=>0}
      value = value.values_at(4, 5, 6).compact
    end

    TimeOnly.new(value)
  end

  def serialize(value)
    value.to_s
  end

  def changed_in_place?(raw_old_value, new_value)
    raw_old_value != serialize(new_value)
  end
end

ActiveRecord::Type.register :time_only, TimeOnlyType

module TimeOnlyAwareness
  def <=>(other)
    if other.is_a? TimeOnly
      other = self.dup.change(hour: other.hour, min: other.min, sec: other.sec)
    end

    super(other)
  end
end

## At the moment I create this module, both Time and TimeWithzone
## classes convert to DateTime before calling #between? so we don't
## need to monkey patch them directly, but I added tests to grant this
## stil working in the future
#
# Time                       .prepend TimeOnlyAwareness
# ActiveSupport::TimeWithZone.prepend TimeOnlyAwareness
DateTime .prepend TimeOnlyAwareness
```

**Comment by everton** [comment] 2024-10-08 12:47
I also have these tests here to cover some cases:

```ruby
require 'test_helper'

class TimeOnlyCustomTypeTest < ActiveSupport::TestCase
  test 'convertion to_i and other calculations' do
    assert_equal '01:00',    TimeOnly.new( 3600).to_s
    assert_equal '05:00',    TimeOnly.new(18000).to_s
    assert_equal '05:00:30', TimeOnly.new(18030).to_s
    assert_equal '05:01',    TimeOnly.new(18060).to_s

    assert_equal '01:15',   (TimeOnly.new( 3600) + 15.minutes).to_s
    assert_equal '00:45',   (TimeOnly.new( 3600) - 15.minutes).to_s

    assert TimeOnly.new('09:01').between? \
      TimeOnly.new('09:00:59'), TimeOnly.new('09:01:01')
  end

  test 'comparisons' do
    assert TimeOnly.new('09:00:01') > '09:00 AM'
    assert TimeOnly.new('09:00:01') > TimeOnly.new('09:00')
    assert TimeOnly.new('09:00:01') > Time       .new(2000, 1, 1, 9, 0, 0, 'UTC')
    assert TimeOnly.new('09:00:01') > DateTime   .new(2000, 1, 1, 9, 0, 0, 'UTC')
    assert TimeOnly.new('09:00:01') > Time.zone.local(2000, 1, 1, 9, 0, 0)
    assert TimeOnly.new('09:00:01') > DateTime   .new(2000, 1, 1, 9, 0, 0, 'American Samoa')
  end

  # Keep this test covering all the 3 types, bacause at the moment I create
  # the code to deal with TimeOnly, both Time and TimeWithzone classes convert
  # to DateTime before calling #between? so we don't need to monkey patch them
  # directly, but we need tests to grant this stil working in the future
  test 'comparison using monkey_patched time formats (reverse comparison)' do
    #  Sat, 01 Jan 2000 09:30:00 +0000

    assert    DateTime.new(2000, 1, 1, 9, 30, 0, 'UTC').between? \
      TimeOnly.new('09:00'), TimeOnly.new('10:00')

    assert        Time.new(2000, 1, 1, 9, 30, 0, 'UTC').between? \
      TimeOnly.new('09:00'), TimeOnly.new('10:00')

    # This test was passing because we were always using UTC as the TimeZone
    # but with test mutations I detected that our TimeOnly objects were not
    # handling TimeWithZones properly.
    #
    # In the bottom of config/initializers/time_only.rb file we are prepending
    # the module TimeOnlyAwareness in the DateTime class but not in the
    # ActiveSupport::TimeWithZone; This class convert its objects into Time
    # objects to handle methos like #between?, and these Time objects are not
    # aware of the zone, so '10:00' became '14:00' in America/New_York.
    #
    # Obs.: just prepending the module to the Time class will not work, we will
    #   need to add methods like the #between? there, since it converts to UTC
    #   in the #between? (and other similar methods) instead of calling <=>
    #
    # Obs. 2: curiously, the (prepended) DateTime#<=> is actually called, so
    #   apparently the Time is also converting again into DateTime or something
    #   similar happens and this must be investigated before removing the skip.
    skip 'TimeOnly is not working with TimeWithZone objects'

    Time.use_zone('America/New_York') do
      # Time.zone.* return ActiveSupport::TimeWithZone object
      assert Time.zone.local(2000, 1, 1, 9, 30, 0).between? \
        TimeOnly.new('09:00'), TimeOnly.new('10:00')
    end

    # Now let's deal with other timezones... The TimeOnly object is casted
    # as a Time (with zone) object using the same class of the compared object.
    # It sets the hour+min+sec directly in that object, so it doesn't matter
    # what timezone it is,the TimeOnlyn must always work for comparison
    #
    # American Samoa is UTC -11:00; The westernmost time zone know by Rails
    assert    DateTime.new(2000, 1, 1, 9, 30, 0, 'American Samoa').between? \
      TimeOnly.new('09:00'), TimeOnly.new('10:00')

    #           Samoa is UTC +13:0; The easternmost time zone know by Rails
    assert    DateTime.new(2000, 1, 1, 9, 30, 0, 'Samoa'        ).between? \
      TimeOnly.new('09:00'), TimeOnly.new('10:00')
  end
end
```

**Comment by everton** [comment] 2024-10-08 12:48
> I also have these tests here to cover some cases:
> 
> ```ruby
> require 'test_helper'
> 
> class TimeOnlyCustomTypeTest < ActiveSupport::TestCase
>   test 'convertion to_i and other calculations' do
>     assert_equal '01:00',    TimeOnly.new( 3600).to_s
>     assert_equal '05:00',    TimeOnly.new(18000).to_s
>     assert_equal '05:00:30', TimeOnly.new(18030).to_s
>     assert_equal '05:01',    TimeOnly.new(18060).to_s
> 
>     assert_equal '01:15',   (TimeOnly.new( 3600) + 15.minutes).to_s
>     assert_equal '00:45',   (TimeOnly.new( 3600) - 15.minutes).to_s
> 
>     assert TimeOnly.new('09:01').between? \
>       TimeOnly.new('09:00:59'), TimeOnly.new('09:01:01')
>   end
> 
>   test 'comparisons' do
>     assert TimeOnly.new('09:00:01') > '09:00 AM'
>     assert TimeOnly.new('09:00:01') > TimeOnly.new('09:00')
>     assert TimeOnly.new('09:00:01') > Time       .new(2000, 1, 1, 9, 0, 0, 'UTC')
>     assert TimeOnly.new('09:00:01') > DateTime   .new(2000, 1, 1, 9, 0, 0, 'UTC')
>     assert TimeOnly.new('09:00:01') > Time.zone.local(2000, 1, 1, 9, 0, 0)
>     assert TimeOnly.new('09:00:01') > DateTime   .new(2000, 1, 1, 9, 0, 0, 'American Samoa')
>   end
> 
>   # Keep this test covering all the 3 types, bacause at the moment I create
>   # the code to deal with TimeOnly, both Time and TimeWithzone classes convert
>   # to DateTime before calling #between? so we don't need to monkey patch them
>   # directly, but we need tests to grant this stil working in the future
>   test 'comparison using monkey_patched time formats (reverse comparison)' do
>     #  Sat, 01 Jan 2000 09:30:00 +0000
> 
>     assert    DateTime.new(2000, 1, 1, 9, 30, 0, 'UTC').between? \
>       TimeOnly.new('09:00'), TimeOnly.new('10:00')
> 
>     assert        Time.new(2000, 1, 1, 9, 30, 0, 'UTC').between? \
>       TimeOnly.new('09:00'), TimeOnly.new('10:00')
> 
>     # This test was passing because we were always using UTC as the TimeZone
>     # but with test mutations I detected that our TimeOnly objects were not
>     # handling TimeWithZones properly.
>     #
>     # In the bottom of config/initializers/time_only.rb file we are prepending
>     # the module TimeOnlyAwareness in the DateTime class but not in the
>     # ActiveSupport::TimeWithZone; This class convert its objects into Time
>     # objects to handle methos like #between?, and these Time objects are not
>     # aware of the zone, so '10:00' became '14:00' in America/New_York.
>     #
>     # Obs.: just prepending the module to the Time class will not work, we will
>     #   need to add methods like the #between? there, since it converts to UTC
>     #   in the #between? (and other similar methods) instead of calling <=>
>     #
>     # Obs. 2: curiously, the (prepended) DateTime#<=> is actually called, so
>     #   apparently the Time is also converting again into DateTime or something
>     #   similar happens and this must be investigated before removing the skip.
>     skip 'TimeOnly is not working with TimeWithZone objects'
> 
>     Time.use_zone('America/New_York') do
>       # Time.zone.* return ActiveSupport::TimeWithZone object
>       assert Time.zone.local(2000, 1, 1, 9, 30, 0).between? \
>         TimeOnly.new('09:00'), TimeOnly.new('10:00')
>     end
> 
>     # Now let's deal with other timezones... The TimeOnly object is casted
>     # as a Time (with zone) object using the same class of the compared object.
>     # It sets the hour+min+sec directly in that object, so it doesn't matter
>     # what timezone it is,the TimeOnlyn must always work for comparison
>     #
>     # American Samoa is UTC -11:00; The westernmost time zone know by Rails
>     assert    DateTime.new(2000, 1, 1, 9, 30, 0, 'American Samoa').between? \
>       TimeOnly.new('09:00'), TimeOnly.new('10:00')
> 
>     #           Samoa is UTC +13:0; The easternmost time zone know by Rails
>     assert    DateTime.new(2000, 1, 1, 9, 30, 0, 'Samoa'        ).between? \
>       TimeOnly.new('09:00'), TimeOnly.new('10:00')
>   end
> end
> ```

As you can see, I was not able to investigate all cases, there is an skip on this test, but for our use case it was not something relevant at the time

**Comment by Paul-Bob** [comment] 2024-10-08 12:52
Wow, it's more complex than expected, great work there, thanks for sharing! 

Have you thought about releasing a gem with this?

**Comment by everton** [comment] 2024-10-08 12:55
@Paul-Bob I thought the use case was so specific that I never considered it

**Comment by Paul-Bob** [comment] 2024-10-08 13:19
> @Paul-Bob I thought the use case was so specific that I never considered it

I'm not sure yet which parts would be relevant to my use case, but I find it helpful to store the current date instead of `2000-01-01`.

Currently, I'm in the `Europe/Bucharest` timezone, where DST is active. I'm storing the user's input as UTC. However, when converting back to the `Europe/Bucharest` timezone, the conversion assumes that DST is not in effect due to the use of `2000-01-01` and there is a discrepancy of 1 hour on what the user introduced and what is being displayed. When I use the current date instead, it behaves as expected.

```ruby
# Non-DST
Time.new("2000-01-01 10:45:00.000000000 +0000").in_time_zone('Europe/Bucharest')
# 2000-01-01 12:45:00.000000000 EET +02:00

# DST active
Time.new("2024-10-08 10:45:00.000000000 +0000").in_time_zone('Europe/Bucharest')
# 2024-10-08 13:45:00.000000000 EEST +03:00
```
