### ISSUE TITLE
TypeError PG::TypeMap undefined method `key?' for nil if !type_map.key?(oid)

### ISSUE THREAD

**Issue by navidemad** [rails/rails#52595] opened 2024-08-13 16:50 UTC
https://github.com/rails/rails/issues/51780

### System configuration
OS: Heroku Ubuntu 22
**Rails version**: 7.1.3.4
**Ruby version**: 3.3.4
**gem pg version**: 1.5.7

## Backtrace
```ruby
TypeError · wrong argument type nil (expected PG::TypeMap) Unhandled error
NoMethodError: undefined method `key?' for nil if !type_map.key?(oid)
```

## Explanation
Hello, we are facing some weird issues happening randomly.
On line that are doing a basic find on the database, which is working 99.99% of the time.
```ruby
parking = Parking.find_by(id: params[:parking_id])
```

Does it ring any bell in the code source ?
I created an issue on the ruby-pg gem, but it seems to be related to activerecord postgresql adapter instead:
https://github.com/ged/ruby-pg/issues/582#issuecomment-2286653775

@larskanis :
> The text `if !type_map.key?(oid)` if here in ActiveRecord:
> 
> https://github.com/rails/rails/blob/ac1d7681d05906b2b050eced76c6a2165f420821/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L830
> 
> And the TypeError comes probably from here:
> 
> https://github.com/rails/rails/blob/ac1d7681d05906b2b050eced76c6a2165f420821/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L16
> 
> That's all I can say for now. No idea why the type map should be `nil` in either case.

**Comment by rafaelfranca** [comment] 2024-08-22 14:59
Duplicate of #51780

**Closed by rafaelfranca** 2024-08-22 14:59 UTC
