### ISSUE TITLE
Rails 4.2.5.2: ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT)

### ISSUE THREAD

**Issue by jarkelen** [rails/rails#23978] opened 2016-03-01 07:47 UTC
### Steps to reproduce
* Update Rails from `4.2.5.1` to `4.2.5.2` and do a `bundle update rails`
* Deploy Rails app to Heroku
* Some pages (which are views with Haml) give a `ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT)`
* A rollback to previous release on Heroku and the page is working again

### Expected behavior
Page should work as normal

### Actual behavior
error `ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT)` occurs

### System configuration
**Rails version**:
4.2.5.2

**Ruby version**:
2.2.2

**Comment by anujaware** [comment] 2016-03-01 08:01
@jarkelen Can you please print the trace here?

**Comment by jarkelen** [comment] 2016-03-01 08:05
* It also happens on development environment, not only on Heroku
* It seems to be happening on bootstrap tags only

Trace:
````
 CACHE (0.0ms)  SELECT  "answers".* FROM "answers" WHERE "answers"."question_id" = $1 AND "answers"."usersurvey_id" = $2  ORDER BY "answers"."id" ASC LIMIT 1  [["question_id", 220], ["usersurvey_id", 87]]
  Rendered answers/_question.html.haml (2.0ms)
  Rendered answers/_question.html.haml (2.5ms)
  Rendered answers/index.html.haml within layouts/application (36.5ms)
Completed 500 Internal Server Error in 166ms (ActiveRecord: 100.1ms)
[Rollbar] Reporting exception: incompatible character encodings: UTF-8 and ASCII-8BIT
[Rollbar] Exception not reported because Rollbar is disabled

ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    3:     .question_title= question.intro
    4:   .col-xs-12.col-md-2.question_element
    5:     - unless question.remark.blank?
    6:       %button.btn.btn-default{"data-target" => "#remarkModal", "data-toggle" => "modal", :type => "button"}
    7:         = I18n.t(".activerecord.attributes.question.remark")
    8: 
    9:       / Modal
  app/views/answers/_question.html.haml:6:in `_app_views_answers__question_html_haml___1257051608129488434_51322260'
  app/views/answers/index.html.haml:45:in `block in _app_views_answers_index_html_haml___878025953428997124_70096195565980'
  app/views/answers/index.html.haml:44:in `_app_views_answers_index_html_haml___878025953428997124_70096195565980'
````

**Comment by chashmeetsingh** [comment] 2016-03-01 08:31
@jarkelen  can you upload a sample app for reviewing it ?

**Comment by pixeltrix** [comment] 2016-03-01 12:12
It seem unlikely that 4.2.5.1 -> 4.2.5.2 is the cause after reviewing this changes here:
https://github.com/rails/rails/compare/v4.2.5.1...v4.2.5.2

Did any dependent gems get updated at the same time? For example when I ran `bundle update rails` last night for one of my apps it updated sprockets and sprockets-rails as well.

**Comment by rafaelfranca** [comment] 2016-03-01 15:18
Agree with @pixeltrix. All the 4.2.5.2 patches made was to check by `permitted?` flag in parameters, it could not break any view with an encoding error.

I'll close this issue but please keep us posted with your findings so we can reopen if needed.

**Closed by rafaelfranca** 2016-03-01 15:18 UTC

**Comment by erikse** [comment] 2016-03-01 19:11
We noticed updating Rails 4.2.5.1 to 4.2.5.2 with `bundle update rails` pushed the version of sprockets from 2.x to 3.x in our app, so that was quite an unexpected step! 

alphagov/smart-answers#2320

The 4.2.5 to 4.2.5.1 update on the 26 Jan, with the same command, seemed okay leaving sprockets at 2.x 

alphagov/smart-answers#2253

**Comment by manfe** [comment] 2016-04-19 21:01
Hey guys, this error is happening to me with Rails 4.2.5.1 and Ruby 2.1.5p273.

the error: 
```
I, [2016-04-19T17:37:17.317035 #3090]  INFO -- : Started GET "/" for 200.17.85.253 at 2016-04-19 17:37:17 -0300
I, [2016-04-19T17:37:17.318022 #3090]  INFO -- : Processing by HomeController#index as HTML
I, [2016-04-19T17:37:17.319217 #3090]  INFO -- :   Rendered home/index.html.erb within layouts/application (0.1ms)
I, [2016-04-19T17:37:17.320545 #3090]  INFO -- : Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)
F, [2016-04-19T17:37:17.321531 #3090] FATAL -- : 
ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8):
    21:             </a>
    22:           </div>
    23:           <div class="col-lg-2 col-md-3 col-sm-3" id="second-logo">
    24:             <%= image_tag('mid-logo.png') %>
    25:           </div>
    26:           <div class="col-lg-6 col-md-5 col-sm 4">
    27:             <h1>SCP - Sistema de Controle de Projetos</h1>
  app/views/layouts/application.html.erb:24:in `_app_views_layouts_application_html_erb__3492403733937390265_26400640'
```
I start debug it and removed the line 24, the error changed another line. I continue removing until I removed the line: `<title><%= ENV['TITULO_DO_SITE'] %></title>`

So I inspect the ENV VAR and inside of it I noticed that there was a tilde accent.
`export TITULO_DO_SITE="SCP - Controle de Projetos de Pesquisa do Campus Sertão"`

So I removed the `ã` and it start to work again.

The interesting thing is: There are another ENV VARs with accents and when I executed a Mailer method that use these other ENV VARS with accents, the e-mail was rendered (html.erb) and sent normally.

I am on it like 3 or 4 hours and couldn't find a way to fix it.

**Comment by gingerlime** [comment] 2016-06-01 13:37
I'm having a similar issue to @manfe. The odd thing is that the error depends on the request itself.

We have a template with a few UTF-8 characters, e.g. `ä`. It renders just fine most of the time, but some times fails, depending on the request params.

i.e.

```bash
curl 'http://my.dev.box:3000/en/search?x=✓'  # raises this error
curl 'http://dev.kenhub.com:3000/en/search?x=1'  # works fine
```

removing the UTF-8 characters from the template renders fine in both cases.

Tried various changes like adding `# encoding: UTF-8` on the template, using `force_encoding('UTF-8') on the string and various other hacks, but nothing seems to resolve this.

**Comment by michaeloboyle** [comment] 2016-07-06 20:25
I get a potentially related error after upgrade from 4.2.5.1 to 4.2.5.2

```
     Failure/Error: expect(mail.attachments.last['Content-Type'].to_s).to eq("application/pdf; charset=UTF-8; filename=\"Agreement for #{enrollment.user.name}.pdf\"")
       
       expected: "application/pdf; **charset=UTF-8;** filename=\"Agreement for Test First Test Last.pdf\""
            got: "application/pdf; filename=\"Agreement for Test First Test Last.pdf\""
```

**Comment by gingerlime** [comment] 2017-03-29 09:00
We're still getting those errors from time to time, and couldn't figure out a solution... :-/

**Comment by pixeltrix** [comment] 2017-03-29 09:19
@gingerlime we occasionally got them on petition.parliament.uk until I spent some time tracking them down. Turns out some browsers aren't great at encoding things properly and Rack would leave the url as ASCII-8BIT. When rendering a template that had UTF-8 characters in it we'd get exceptions when trying to use that url in the output. Once I forced the encoding on the request url to be UTF-8 before using it in rendering then all the exceptions went away.

**Comment by gingerlime** [comment] 2017-03-29 09:22
Thanks @pixeltrix! Could you elaborate a little about how to force the encoding on the request exactly?

**Comment by pixeltrix** [comment] 2017-03-29 09:46
It'll depend on how you're using it (and if it's the cause of your error - the ASCII-8BIT data may be from something else) but you can see what I did in these commits:

https://github.com/alphagov/e-petitions/commit/1f63d9e179ea95bde1922d6b14ea9405547a2418
https://github.com/alphagov/e-petitions/commit/dd5c6ca1e0b1ac829272f1529d481a4604c3d0fa

It'll mean you'll get weird characters sometimes but that's better than the page blowing up.

**Comment by gingerlime** [comment] 2017-03-29 09:53
Thanks @pixeltrix. Correct me if I'm wrong, but you actually use the original url somewhere back in the view? I don't think we use the `original_url` anywhere in our views, so I'm not sure where exactly to force this.

I found https://github.com/whitequark/rack-utf8_sanitizer but not sure what potential (negative) side-effects it might have...

**Comment by pixeltrix** [comment] 2017-03-29 10:01
@gingerlime it might be implicit in some manner - e.g. being used in a cache key for a `cache :foo { }` template block - if you can get a full trace inside Rails in where it blows up then it's possible we may be able to guard against it.

**Comment by gingerlime** [comment] 2017-03-29 10:18
@pixeltrix it's been a while since I [looked at it](https://github.com/rails/rails/issues/23978#issuecomment-222994468), but I wasn't able to pinpoint to where exactly... Tried wrapping any input I could think of with `.force_encoding('UTF-8')` to no avail... I was able to work out that removing (hard-coded) UTF-8 characters from the views resolved it (but I'm guessing that it simply matched the request and response formats to ASCII-8BIT, not sure). That's the closest I got...

Maybe this rack middleware is a reasonable workaround, although I try to avoid (potentially opaque) layers of middleware unless absolutely necessary.

**Comment by gingerlime** [comment] 2017-03-29 13:00
Thanks @pixeltrix. Your examples and suggestions helped a lot.

I managed to do more hunting, and eventually discovered somewhere we used `request.url` (some meta tag for facebook, `og:url`...).

Somehow view traces aren't the most specific, which makes tracing those kinds of bugs much harder. But at least I found it! Thanks again.
