### ISSUE TITLE
Constraint Subdomain and Redirect causes double redirect

### ISSUE THREAD

**Issue by Tonkpils** [rails/rails#21582] opened 2015-09-10 18:40 UTC
When setting the following constraints on the routes:

**routes.rb**
```ruby
constraints subdomain: false do
  get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
end
```
It actually performs two redirects for some reason and ends up in `www.www.localhost:3000`.

In the browser I can see it redirected `localhost:3000 => www.localhost:3000 => www.www.localhost:3000`

Writing a test case for this seems to pass

**actionpack/test/dispatch/routing_test.rb**
```ruby
  def test_redirect_with_subdomain_constraint
    draw do
      constraints subdomain: false do
        get ":any", to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
      end

      get "/", to: "private#index"
    end

    get "http://example.com"
    verify_redirect "http://www.example.com/"
  end
```

However, creating a sample app with Rails v4.2.4 with the same routes causes the double redirection. 

https://github.com/Tonkpils/double-redirect-rails-issue

![image](https://cloud.githubusercontent.com/assets/1507561/9797921/e7226e1e-57cb-11e5-966d-175ea39ea89a.png)

**Comment by al2o3cr** [comment] 2015-09-10 19:25
Unrelated but first off: if you're really just aiming to canonicalize to the `www` version of your domain, it may be more efficient to do that at the web server level, FWIW.

Can you reproduce this issue on anything other than `localhost`? My guess is that `www.localhost` isn't getting picked up as having a subdomain since it only has one dot.

**Comment by Tonkpils** [comment] 2015-09-10 19:29
> Unrelated but first off: if you're really just aiming to canonicalize to the www version of your domain, it may be more efficient to do that at the web server level, FWIW.

I agree with you but it's not possible AFIK on services like Heroku.

> Can you reproduce this issue on anything other than localhost? My guess is that www.localhost isn't getting picked up as having a subdomain since it only has one dot.

Ah, that's a very good guess. I think the test may be passing because it contains an `.com`. I'll round back with an update

**Comment by pixeltrix** [comment] 2015-09-11 12:57
You can set the number of top-level domains as an argument to subdomain, e.g:

``` irb
>> app.get('http://www.localhost')
>> app.request.subdomain
=> "" 
>> app.request.subdomain(0)
=> "www" 
```

This can also be set in an environment file as well:

``` ruby
# config/environments/development.rb
config.action_dispatch.tld_length = 0
```

Closing as this is expected behavior.

**Closed by pixeltrix** 2015-09-11 12:57 UTC
