### ISSUE TITLE
ActiveStorage named variants `deep_symbolize_keys` undefined

### ISSUE THREAD

**Issue by brennongs** [rails/rails#42269] opened 2021-05-21 22:06 UTC
### Steps to reproduce
We're migrating from Paperclip to ActiveStorage (🎉 ), and everything was going super smoothly until we got to porting over our named variants.

model:
```ruby
class User < ApplicationRecord
  include PublicActivity::Model

  # ...

  has_one_attached :avatar do |attachable|
    attachable.variant :large, resize: '600x600'
    attachable.variant :medium, resize: '300x300'
    attachable.variant :thumb, resize: '100x100'
  end

  #...
end
```

In our graphql logic we have:
```ruby
def thumb_url
  object.variant(:thumb).processed.url
end

def medium_url
  object.variant(:medium).processed.url
end

def large_url
  object.variant(:large).processed.url
end
```

We are using [graphql gem](https://graphql-ruby.org)
### Expected behavior
I would expect that calling our graphql controller at `thumb_url` would return the url for the preprocessed `:thumb`-sized image.

### Actual behavior
`NoMethodError: undefined method 'deep_symbolize_keys' for :thumb:Symbol`

My team and I have _scoured_ the internet trying to find anything that would resolve this. I found a single article that pointed me in the direction of [`encrypted_configuration.rb`](https://github.com/rails/rails/blob/a6a9fed1719a3cfe47eb1566ae4d6034374fd809/activesupport/lib/active_support/encrypted_configuration.rb) saying it might be our yaml files being bad but I double checked all our yaml files and they seem fine. We are totally stuck.

### System configuration
**Rails version**:
`~> 6.1.2`
**Ruby version**:
`2.7.2`

**Comment by zzak** [comment] 2021-05-22 00:30
@brennongs Could you provide a reproducible example?

**Comment by brennongs** [comment] 2021-05-24 11:00
What information is missing that would make this reproducible? I guess I don't know what a reproducible example is.

**Comment by abhaynikam** [comment] 2021-05-24 16:09
@brennongs You are getting above error because the feature to add `pre-defined named variants` is not yet released in Rails 6.1. This would be released in Rails 7.0 or would be available in Rails Edge. This feature was added in PR: https://github.com/rails/rails/pull/39135

I can see the confusion is because Active Storage guides mention pre-defined variants feature here: https://edgeguides.rubyonrails.org/active_storage_overview.html#has-one-attached

This is because the guides are point to `Rails Edge`. See the top-right corner in the following screenshot.
![image](https://user-images.githubusercontent.com/7736232/119374938-d9066e80-bcd7-11eb-8f74-90bfd3657e87.png)



**Workaround**: You could use `object.avatar.variant(resize: "100x100").processed.url` in the GraphQL field resolver for now. Hope this helps 😊

**Comment by brennongs** [comment] 2021-05-24 17:19
@abhaynikam Thank you! so would I do the model like
```ruby
has_one_attached :avatar
```
just like normal? and then in the graphql controller do the code you suggested?

**Comment by zzak** [comment] 2021-05-25 02:00
@brennongs It sounds like we might have an answer, but for future reference: we provide a few [templates](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) for creating an executable test case. Such as ActiveStorage using [released gem](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_storage_gem.rb) or using [current main branch verison](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_storage_main.rb).

**Comment by abhaynikam** [comment] 2021-05-25 05:03
> just like normal? and then in the graphql controller do the code you suggested?

Yep. That would resolve this issue.

**Comment by zzak** [comment] 2021-05-25 05:44
Since it seems like this issue is resolved, I'm going to close this ticket. Please feel free to re-open if you have concerns, or open a new ticket if you've found a bug. [Discuss](https://discuss.rubyonrails.org/) is also a great place to discuss these types of issues. Thanks!

**Closed by zzak** 2021-05-25 05:44 UTC
Labels: activestorage
