### ISSUE TITLE
Strong parameters converts nested arrays of numbers into flat array of strings

### ISSUE THREAD

**Issue by slhck** [rails/rails#38698] opened 2020-03-11 13:17 UTC
### Steps to reproduce

Please see the following test case:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.0.2.1"
  gem "byebug"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    post "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    data = params.require(:client_report).permit(
      :client_time,
      data: {}
    )
    render json: data
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    data = {
      client_report: {
        client_time: Time.now.asctime,
        data: {
          "I11": {
            "segments": [
              {
                "bitrate": 331.46,
                "codec": "aac",
                "duration": 5.48,
                "start": 0
              },
              {
                "bitrate": 333.02,
                "codec": "aac",
                "duration": 5.0,
                "start": 5.48
              }
            ],
            "streamId": 42
          },
          "I23": {
            "stalling": [[0, 2], [5, 3]],
            "streamId": 42
          },
          "IGen": {
            "device": "pc",
            "displaySize": "1920x1080",
            "viewingDistance": "150cm"
          }
        }
      }
    }
    post "/", data
    json_response = JSON.parse(last_response.body)
    puts "Received: " + last_response.body
    assert json_response == data[:client_report].as_json
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

I am expecting `params.permit(..., data: {})` to permit the data hash and return it as-is.

### Actual behavior

Instead, the data gets mangled. The `["I23"]["stalling"]` value turns from:

    [[0, 2], [5, 3]]

into:

    ["0","2","5","3"]

This is clearly a bug, as Rails should not modify the data structure. Also looking at the documentation of strong parameters, where the following example is given (emphasis mine):

> Imagine a scenario where you have parameters representing a product name and a hash of **arbitrary data** associated with that product, and you want to permit the product name attribute and also the **whole data** hash:
>
>     def product_params
>       params.require(:product).permit(:name, data: {})
>     end

If indeed the data could be arbitrary, and the whole data would be permitted, the above example would not fail.

### System configuration

**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5

**Comment by tannakartikey** [comment] 2020-03-12 20:44
Seems the duplicate of https://github.com/rails/rails/issues/23640

**Comment by slhck** [comment] 2020-03-12 21:53
Indeed, that's quite similar. It's a bit baffling that this has been open for 4 years!

**Closed** 2023-05-08 05:42 UTC

**Comment by slhck** [comment] 2023-05-08 05:50
That was a surprisingly simple fix, thanks @tindron!
