### ISSUE TITLE
Images saved using ActiveStorage different in production and development environments

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#45519] opened 2022-07-04 17:47 UTC
### Expected behavior
In both environments same behavior

### Actual behavior
In development environment saved (attach) image in content-page within `gem ckeditor` using `ActiveStorage` with `mini_magick` - then in production environment image are not showed, and vice versa - saved in production, then are not showed in development. I use **same database** (mysql) in development and production environments.

### System configuration
- **Ruby version**: 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
- **Rails version**: 7.0.3
- gem [ckeditor](https://github.com/galetahub/ckeditor) 5.1.1

```
# storage.yml
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
```

In production environment I use config: 
```ruby
config.assets.compile = true
config.active_storage.service = :local
config.active_storage.variant_processor = :mini_magick
```
in development:
```ruby
config.active_storage.service = :local
config.active_storage.variant_processor = :mini_magick
```

saved image in source code of page show like this:
```
<img alt="" src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68a08d9de8f843ecd8b5c5be61d33859a3333bb7/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--2ccbd7d12a252e03eb26bb2401505e4efaeff669/7d85fe9c160bb2f3b559a45303cc8ce4.jpg" style="width: 700px; height: 475px;" />
```

### The problem, most likely, is in the ActiveStorage, because the `gem ckeditor` works correctly with other configurations

@rafaelfranca
#### It is not `sprockets-rails` issue but ActiveStorage

**Comment by nvasilevski** [comment] 2022-07-04 19:27
Correct me if I'm wrong, but it seems like you are saving images on disk, which means locally uploaded files are stored on your personal machine and production-uploaded files are stored on a remote server. So even though you connect to the same database doesn't mean that the files are stored at the same disk storage. In other words, it's unclear how production environment is supposed to access your local disk and vice-versa  

**Presumably** if you were to store these images in a cloud storage, then you would be able to access them in both development & production environments, but I'm not experienced enough with Active Storage to say for sure

**Comment by Sega100500** [comment] 2022-07-04 20:13
@nvasilevski 
Please read more carefully issue.
In both development and production environment files are sored on local disk.

**Comment by hahmed** [comment] 2022-07-04 20:43
@Sega100500 had a look at this and I could not replicate.

I used sqlite and did not add the gem ckeditor -- could you repro this issue on a rails app and link it to here? (maybe try without ckeditor?)

Here is what I did;

- Upload a file in development
- run RAILS_ENV=production RAILS_LOG_TO_STDOUT=1 rails s 
- I could see the same image in dev/production 

```
# model
class Post < ApplicationRecord
  has_one_attached :avatar
end

# storage.yml
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# development.rb
config.active_storage.service = :local

# production.rb
config.active_storage.service = :local
```

**Comment by hahmed** [comment] 2022-07-04 20:48
Could you confirm, is the url exactly the same for both development and production for the active storage attachment?

**Comment by Sega100500** [comment] 2022-07-04 22:10
@hahmed 

Yes, in both environments image tag is same:
```
development:
/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68a08d9de8f843ecd8b5c5be61d33859a3333bb7/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--2ccbd7d12a252e03eb26bb2401505e4efaeff669/7d85fe9c160bb2f3b559a45303cc8ce4.jpg

production:
/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68a08d9de8f843ecd8b5c5be61d33859a3333bb7/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--2ccbd7d12a252e03eb26bb2401505e4efaeff669/7d85fe9c160bb2f3b559a45303cc8ce4.jpg
```

No issue https://github.com/rails/rails/issues/45510 is confirmed and https://github.com/rails/sprockets/commit/e36620745d7150fc33eccffeaf79e741a774499c

**Comment by nvasilevski** [comment] 2022-07-05 02:27
@hahmed I think you can't reproduce because you are running both environments on the same local machine
but @Sega100500 seems to be running production env on a remote server, at least judging by a different `http://site_name/ ` url
So I don't get why there is an expectation to be able to read files locally by a relative path while these files are stored somewhere on a remote server storage. The only thing that is shared is the database, so the records of those attachments are the same, however files have different physical location

**Comment by Sega100500** [comment] 2022-07-05 03:13
@nvasilevski 
I repeat once again. Everything is **on the same computer**, in local storage. I have a separate dedicated server where I run both development and production environments. Enough of the stupid talk about different computers and cloud storage! Please don't treat me like an idiot

**Comment by Sega100500** [comment] 2022-07-05 06:21
log for access to images:
```
Started GET "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68a08d9de8f843ecd8b5c5be61d33859a3333bb7/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--2ccbd7d12a252e03eb26bb2401505e4efaeff669/7d85fe9c160bb2f3b559a45303cc8ce4.jpg" for 127.0.0.1 at 2022-07-05 10:51:51 +0000
Started GET "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b39a79abe1fc9d54c86ce75bcc62c1784a0d0c2e/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--87434b5b17ecf664e5afa5d13fb437d352c75836/8a1dfb3d38902f327f72ab68fab72a8e.jpg" for 127.0.0.1 at 2022-07-05 10:51:51 +0000
Processing by ActiveStorage::Representations::RedirectController#show as JPEG
Processing by ActiveStorage::Representations::RedirectController#show as JPEG
  Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68a08d9de8f843ecd8b5c5be61d33859a3333bb7", "variation_key"=>"[FILTERED]", "filename"=>"7d85fe9c160bb2f3b559a45303cc8ce4"}
  Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b39a79abe1fc9d54c86ce75bcc62c1784a0d0c2e", "variation_key"=>"[FILTERED]", "filename"=>"8a1dfb3d38902f327f72ab68fab72a8e"}
Filter chain halted as :set_blob rendered or redirected
Completed 404 Not Found in 13ms (ActiveRecord: 0.0ms | Allocations: 6204)

  ActiveStorage::Blob Load (0.1ms)  SELECT `active_storage_blobs`.* FROM `active_storage_blobs` WHERE `active_storage_blobs`.`id` = 7 LIMIT 1
  ActiveStorage::VariantRecord Load (0.1ms)  SELECT `active_storage_variant_records`.* FROM `active_storage_variant_records` WHERE `active_storage_variant_records`.`blob_id` = 7 AND `active_storage_variant_records`.`variation_digest` = 'M/VzNGhS9AFWVcqpUDZZlVkiVQs=' LIMIT 1
  ActiveStorage::Attachment Load (0.1ms)  SELECT `active_storage_attachments`.* FROM `active_storage_attachments` WHERE `active_storage_attachments`.`record_id` = 5 AND `active_storage_attachments`.`record_type` = 'ActiveStorage::VariantRecord' AND `active_storage_attachments`.`name` = 'image' LIMIT 1
  ActiveStorage::Blob Load (0.1ms)  SELECT `active_storage_blobs`.* FROM `active_storage_blobs` WHERE `active_storage_blobs`.`id` = 8 LIMIT 1
  Disk Storage (13.4ms) Generated URL for file at key: ms8cvksaxwm75ehtqrduh5czj0uq (http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhiWE00WTNacmMyRjRkMjAzTldWb2RIRnlaSFZvTldONmFqQjFjUVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpYzJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SWpoaE1XUm1Zak5rTXpnNU1ESm1NekkzWmpjeVlXSTJPR1poWWpjeVlUaGxMbXB3WnlJN0lHWnBiR1Z1WVcxbEtqMVZWRVl0T0Njbk9HRXhaR1ppTTJRek9Ea3dNbVl6TWpkbU56SmhZalk0Wm1GaU56SmhPR1V1YW5CbkJqc0dWRG9SWTI5dWRHVnVkRjkwZVhCbFNTSVBhVzFoWjJVdmFuQmxad1k3QmxRNkVYTmxjblpwWTJWZmJtRnRaVG9LYkc5allXdz0iLCJleHAiOiIyMDIyLTA3LTA1VDA1OjU2OjUxLjY4MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--9d155852c1d591734c5723d6be2d3dad801d2189/8a1dfb3d38902f327f72ab68fab72a8e.jpg)
Redirected to http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhiWE00WTNacmMyRjRkMjAzTldWb2RIRnlaSFZvTldONmFqQjFjUVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpYzJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SWpoaE1XUm1Zak5rTXpnNU1ESm1NekkzWmpjeVlXSTJPR1poWWpjeVlUaGxMbXB3WnlJN0lHWnBiR1Z1WVcxbEtqMVZWRVl0T0Njbk9HRXhaR1ppTTJRek9Ea3dNbVl6TWpkbU56SmhZalk0Wm1GaU56SmhPR1V1YW5CbkJqc0dWRG9SWTI5dWRHVnVkRjkwZVhCbFNTSVBhVzFoWjJVdmFuQmxad1k3QmxRNkVYTmxjblpwWTJWZmJtRnRaVG9LYkc5allXdz0iLCJleHAiOiIyMDIyLTA3LTA1VDA1OjU2OjUxLjY4MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--9d155852c1d591734c5723d6be2d3dad801d2189/8a1dfb3d38902f327f72ab68fab72a8e.jpg
Completed 302 Found in 71ms (ActiveRecord: 3.5ms | Allocations: 35789)

Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhiWE00WTNacmMyRjRkMjAzTldWb2RIRnlaSFZvTldONmFqQjFjUVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpYzJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SWpoaE1XUm1Zak5rTXpnNU1ESm1NekkzWmpjeVlXSTJPR1poWWpjeVlUaGxMbXB3WnlJN0lHWnBiR1Z1WVcxbEtqMVZWRVl0T0Njbk9HRXhaR1ppTTJRek9Ea3dNbVl6TWpkbU56SmhZalk0Wm1GaU56SmhPR1V1YW5CbkJqc0dWRG9SWTI5dWRHVnVkRjkwZVhCbFNTSVBhVzFoWjJVdmFuQmxad1k3QmxRNkVYTmxjblpwWTJWZmJtRnRaVG9LYkc5allXdz0iLCJleHAiOiIyMDIyLTA3LTA1VDA1OjU2OjUxLjY4MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--9d155852c1d591734c5723d6be2d3dad801d2189/8a1dfb3d38902f327f72ab68fab72a8e.jpg" for 127.0.0.1 at 2022-07-05 10:51:51 +0000
Processing by ActiveStorage::DiskController#show as JPEG
  Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"8a1dfb3d38902f327f72ab68fab72a8e"}
Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Allocations: 294)
```

**Comment by nvasilevski** [comment] 2022-07-05 12:55
What is the `Rails.root` for both envs?
Could you get local path for both files and see if these files are actually there?
For example in a dev env
```ruby
bundle exec rails c
blobs = ActiveStorage::Blob.last(2) # assuming that the last 2 are problematic, but feel free to load them trough an association or whatever is available in the app
blobs.all? { |b| File.exists?(ActiveStorage::Blob.service.path_for(b.key)) } 
```
you could even check it for `ActiveStorage::Blob.all` if the app is not too big

**Comment by eileencodes** [comment] 2022-07-05 13:11
@Sega100500 - I understand that you are frustrated but please be respectful of the people volunteering their time to help you.

**Comment by Sega100500** [comment] 2022-07-06 10:28
@skipkayhil 
Yes, they (`secret_key_base`) are really different for different environments, and I had an assumption that something is being encrypted at some level. I'm still trying to figure out at what level this happens.
At what I noticed that the thumbs of these images are displayed in both environments.

**Comment by Sega100500** [comment] 2022-07-06 13:35
Another little experiment. It's not about image thumbnails, they behave exactly like images. You can see the page code:

```html
<h3>Thumbs</h3>

<p>In development:</p>

<p><img src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b96d92b49a3952361b003307b59c219cbd5329f8/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERFeE9IZ3hNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--0deccec5ffc002b1ecd33b70cbe3d821c100bc52/Picture-1.jpg" title="Picture-1.jpg" /></p>

<p><img src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e5514a135e2163abb2f728f020525ef5ce099b1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERFeE9IZ3hNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--0deccec5ffc002b1ecd33b70cbe3d821c100bc52/Picture-2.jpg" title="Picture-2.jpg" /></p>

<p>In production:</p>

<p><img src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5f5e27b4233d2cd14d82ddb5f37646ea24fe93c0/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERFeE9IZ3hNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--2eb576d2cecb774c401d342aa0ecfe6fefd61e98/Picture-1.jpg" title="Picture-1.jpg" /></p>

<p><img src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b9bb3610f993d5135f8b17ff718883d2ac06d3ae/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERFeE9IZ3hNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--2eb576d2cecb774c401d342aa0ecfe6fefd61e98/Picture-2.jpg" title="Picture-2.jpg" /></p>

<h3>In development</h3>

<p><img alt="" src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b96d92b49a3952361b003307b59c219cbd5329f8/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--87434b5b17ecf664e5afa5d13fb437d352c75836/Picture-1.jpg" style="width: 700px; height: 475px;" /></p>

<p><img alt="" src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e5514a135e2163abb2f728f020525ef5ce099b1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--87434b5b17ecf664e5afa5d13fb437d352c75836/Picture-2.jpg" style="width: 700px; height: 488px;" /></p>

<h3>In production</h3>

<p><img alt="" src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5f5e27b4233d2cd14d82ddb5f37646ea24fe93c0/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--2ccbd7d12a252e03eb26bb2401505e4efaeff669/Picture-1.jpg" style="width: 700px; height: 475px;" /></p>

<p><img alt="" src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b9bb3610f993d5135f8b17ff718883d2ac06d3ae/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--2ccbd7d12a252e03eb26bb2401505e4efaeff669/Picture-2.jpg" style="width: 700px; height: 488px;" /></p>
```

But the fact is that thumbs images are formed dynamically in the `ckeditor` browser of the images using **`image_path(asset.url_content)`** (for use as path to image on content-page) and **`image_tag(asset.url_thumb, title: asset.filename)`**, their values are then written into the content page.

In code of `ckeditor`:
```ruby
def url_content
  rails_representation_url(storage_data.variant(resize: '800>').processed, only_path: true)
end

def url_thumb
  rails_representation_url(storage_data.variant(resize: '118x100').processed, only_path: true)
end
```

---

### Conclusion

ActiveStorage generates different paths for image in different environments.

**Comment by eileencodes** [comment] 2022-07-06 15:49
> Please fix it

It doesn't look like anyone has been able to reproduce this so far which means we can't determine the cause or fix. Can you provide an application that reproduces the bug? This will help us determine if it's coming from ckeditor or in Rails. Other users haven't reported similar issues so it's hard to say what's wrong without a repro.

**Comment by nvasilevski** [comment] 2022-07-06 16:44
There must be something else apart from just different `secret_key_base`
As far as I understand, `signed_id` (which is used in the image url) are being generated "on the fly"
Which means that as long as the same environment generates (renders) and verifies signed ids we should be fine.
In other words, it is kind of expected for different environments to generate different URLs based on different `secret_key_base`, but it shouldn't be braking anything

Here is a reproduction script that intended to show that as long as we generate and read signed ids (urls) in the same env, it should just work. 

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  gem "sqlite3"
  gem "debug"
end

require "active_record/railtie"
require "active_storage/engine"
require "action_mailer/railtie"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_upload_and_download
    user = User.create!(
      profile: {
        content_type: "text/plain",
        filename: "dummy.txt",
        io: ::StringIO.new("dummy"),
      }
    )

    assert_equal "dummy", user.profile.download
    old_signed_id = user.profile.signed_id
    blob = ActiveStorage::Blob.find_signed!(old_signed_id, purpose: :blob_id)
    assert_equal(blob.id, user.profile.id)
    # Signed id stays the same as long as we use the same verifier and secret
    assert_equal(ActiveStorage::Blob.find(blob.id).signed_id, ActiveStorage::Blob.find(blob.id).signed_id)

    # Changing env
    TestApp.config.secret_key_base = "new_secret"
    # resetting verifier to a new one with the new secret
    ActiveStorage::Blob.signed_id_verifier = TestApp.message_verifier("new_activestorage_verifier")
    new_signed_id =  user.profile.signed_id
    refute_equal(old_signed_id, new_signed_id) # definitely different

    blob = ActiveStorage::Blob.find_signed!(new_signed_id, purpose: :blob_id)
    assert_equal(blob.id, user.profile.id)
  end
end
```

**Comment by Sega100500** [comment] 2022-07-06 18:27
@nvasilevski

Many Thanks for this! Many Thanks for this! If it really depends on the `secret_key_base` and will display different results in development and production environments.

**Comment by nvasilevski** [comment] 2022-07-06 18:45
If the goal is to have same URLs (signed_ids) generated for both envs, I think the most targeted solution would be to configure `ActiveStorage.verifier` to use message verifier with the same secret, like:
```ruby
ActiveStorage.verifier = ActiveSupport::MessageVerifier.new("same_active_storage_secret_for_both_development_and_production")
```
Not sure if that sounds solid security-wise though
But in my opinion at least it would be better than sharing the same `secret_key_base` as `secret_key_base` is used in different places while `ActiveStorage.verifier` is scoped to Active Storage uploads

**Comment by eileencodes** [comment] 2022-07-06 20:11
I chatted with @nvasilevski and re-read the issue and now have a better understanding of what the problem is. I asked for a reproduction app because it was clear that none of us fully understood the problem. Reproductions drastically reduce time to solution, that's why we ask for it in the issue template.

Unfortunately the behavior you're trying to use (a signed upload in one env working in another) is not supported. Signed URLs are a security feature, which means that the signature for one environment should not work in another environment. Uploads should only be done on the environment in which they are intended to be used. Changing this would lower the security of the Rails framework and we are unwilling to do that.

I'm going to close this issue because it's not a bug in the framework and any workaround we could suggest would harm the security of your application. Hope the explanation of why this is an issue is helpful for you to find another solution in your application.

**Closed by eileencodes** 2022-07-06 20:11 UTC
Labels: activestorage

**Comment by Sega100500** [comment] 2022-07-06 21:07
@nvasilevski 

Brilliant idea, amazing!
Everything worked as it should! I understood your idea, corrected where necessary.

Thank you very much! You would know how much you helped me!

I had to fix the ActiveStorage initializer a little, but this is the lesser of evils, what is the work of ActiveStorage in different environments.

**Comment by Sega100500** [comment] 2022-07-06 21:17
@eileencodes

> Signed URLs prevent a malicious actor from iterating over your uploads and downloading them (increasing your server costs) among other nefarious activities.

Using the **same key** for encryption `Signed URLs` in both environments will not weaken the security of the application in the least!

>The documentation for ASt is here https://edgeguides.rubyonrails.org/active_storage_overview.html and includes some info about public access. It might solve your problem but I'm not sure since I don't have an app to test against and your use-case is non-standard.

I've read it all over and over! There is nothing like that, I have already tried all sorts of configurations.

The bug is present in the system and it consists approximately in the following scheme (as I already gave an example earlier):
```ruby
def get_num(num)
   if Rails.env == 'development`
     num + 1
   else
     num
   end
end
```

It turns out that in the development environment the system is less secure just because the encryption key is used differently? Not even an algorithm, but only a key.

**Comment by eileencodes** [comment] 2022-07-06 21:33
> I've read it all over and over! There is nothing like that, I have already tried all sorts of configurations.

There is an entire section on public access here https://edgeguides.rubyonrails.org/active_storage_overview.html#public-access

I'm not going to argue about this anymore. This issue is closed.

**Comment by Sega100500** [comment] 2022-07-07 01:44
@eileencodes 

@eileencodes , firstly, I want to immediately apologize for the fact that if suddenly my words offend you ...
You understand little about information security, so I recommend that you talk less about this topic in the future. And you need to be more attentive to solving people's issues, and not proceed from the fact that everything works fine for you. No, not everything!

### And now, in fact, the solution of the issue

Yes, Rails is a good, reliable and secure system - honor and praise to developers! But pranoia has never brought anything good to anyone. Everything is closed and hidden in safe safes, as if... But what is the use of all these locks, if they prevent only the owner of the safe from reaching the goal?... after all, the key always hangs on the door of the safe...

I got to the bottom of the truth! Indeed, the key for all encryptions is **`secret_key_base`**. And it seems to be stored in a safe place - it is encrypted in the `credentials.yml.enc` file, but the decryption key is right there next to it - the `master.key` file, and the algorithm is known `rails credentials:edit`. What was the meaning of all this undertaking, I did not understand.
The entire defense of Rails is to prevent a potential hacker from accessing the rails file system. But in Rails this mechanism is very well implemented. Why it was necessary to do redundant encryption is completely incomprehensible to me...

I assure you, I have already looked at all those links on the ActiveStorage configuration repeatedly and tried many configurations! Again, this is your incompetence in the matter.

All the salt lies precisely in the **`secret_key_base`**! And this is not even an ActiveStorage problem, this is a Rails problem - everything really is - for test and development environments, a separate generated **`secret_key_base`** is used, which is stored in `tmp/development_secret.txt`.

The right direction was pointed to me by @nvasilevski, for which many thanks to him! At first, I wanted to somehow substitute something secret and permanent for all environments into the configuration, `secret_key_base` is just right for this role. But everything turned out to be very simple:

1. `rails credentials:edit` - see the secret_key_base value, copy them
2. paste that value in `tmp/development_secret.txt`
3. And voila - **everything works as it should**!

Of course, after launching into production, you need to remove this secret key from the file.

But if I had immediately communicated with a specialist who is well versed in Rails, I would not have spent so much time solving this issue. But everything that is done - everything is for the best - I have studied many details and mechanisms in Rails.

Perhaps someone will find the information useful, I hope so. That's why I wrote this comment.

Thanks to all !

**Comment by matthewd** [comment] 2022-07-07 15:13
@Sega100500 you've been repeatedly out of line in this thread, and your last comment was entirely not okay. In recognition of the fact you've apparently thought better of it and edited that comment, I'm only going to give you a short cooling-off period of one week.

I invite you to consider how you'd like to be treated as a volunteer contributor on a public project, and choose to act accordingly in future.

Further conversation in this style is not welcome, and will not be tolerated.
