### ISSUE TITLE
Possible AR Polymorphic Association Regression (5.2.0.beta2)?

### ISSUE THREAD

**Issue by afair** [rails/rails#31328] opened 2017-12-04 23:05 UTC
### Steps to reproduce
I have reduced the models in my application to the essential association. Post (parent) has a Tracker (polymorphic child association. Given a child, I need to get it's parent record.

    class Post < ActiveRecord::Base
      # Note that Post uses an UUID id.
      has_one    :tracker, as: :track
    end

    class Tracker < ActiveRecord::Base
      # attributes include track_type (varchar) and track_id (uuid)
      belongs_to :track, polymorphic:true
    end

In the context of the Bug Report Template [My Template Source](https://gist.github.com/afair/b4cc7904a24476b5bba9fc3d133978e1),
the association works as expected for the simplified case (not full application).
I have been trying to identify a failing case for it unsuccessfully.

### Expected behavior

In Rails 5.1.4, this works (finding a parent from a polymorphic child):

    >  Tracker.find(31).track
    => #<Post:0x00007ffbf38531c0
         id: "a85c5f88-6fca-473a-bdc0-205002907972", ... >

### Actual behavior
After upgrading to Rails 5.0.2.beta2 (as well as on edge), I now get an exception:

    >  t=Tracker.find(31)
    => #<Tracker:0x00007fd2eaca8360
         id: 31,
         track_type: "Post",
         track_id: "a85c5f88-6fca-473a-bdc0-205002907972", ... >

    >  Tracker.find(31).track
    ActiveRecord::InverseOfAssociationNotFoundError: Could not find the inverse association for track (nil in Post)
    from /Users/allen/.rvm/gems/ruby-2.4.2/bundler/gems/rails-c383c4142a1c/activerecord/lib/active_record/reflection.rb:527:in `polymorphic_inverse_of'

Though I can get the association starting from the final point: Parent -> Child -> Parent

    >  Post.find(t.track_id)
    => #<Post:0x00007fd2ebaa3668
        id: "a85c5f88-6fca-473a-bdc0-205002907972", ... >
    >  Post.find(t.track_id).tracker
    => #<Tracker:0x00007fd2eb99b3d8
         id: 31,
         track_type: "Post",
         track_id: "a85c5f88-6fca-473a-bdc0-205002907972", ... >
    >  Post.find(t.track_id).tracker.track
    => #<Post:0x00007fd2ec22a328
         id: "a85c5f88-6fca-473a-bdc0-205002907972", ... >
Digging into active_record/reflection.rb for 5.1.4, I see `has_inverse?` returns false, because
`can_find_invserse_of_automatically?` returns false.

    def polymorphic_inverse_of(associated_class)
      #           can_find_inverse_of_automatically?(self) #=> false
      if has_inverse? #=> false
        #...
      end
    end
While in 5.2.0.beta2, `has_inverse?` now returns `:tracker` and tries to get the inverse_relationship.
Since `inverse_of` "Does not work in combination with the :polymorphic options." (api docs) this fails,
and raises the Exception.  It seems `can_find_inverse_of_automatically?` now returns true which it shouldn't. The documentation block says "Third, we must not have options such as <tt>:polymorphic</tt> ..." which this is.

    def polymorphic_inverse_of(associated_class)
      #                can_find_inverse_of_automatically?(self) #=> true
      if has_inverse?  #=> :tracker
        #              associated_class #=> Post()
        #              options          #=> {:polymorphic=>true}
        if inverse_relationship = associated_class._reflect_on_association(options[:inverse_of]) #=> nil
          inverse_relationship
        else
          raise InverseOfAssociationNotFoundError.new(self, associated_class)
        end
      end
    end

### System configuration
**Rails version**: Rails 5.2.0.beta2 (and edge)

**Ruby version**: Ruby MRI 2.4.2

Thank you for your time! I appreciate all you do for the project!

**Comment by tradeli** [comment] 2017-12-05 15:00
Maybe related #31338

**Comment by fatkodima** [comment] 2017-12-27 16:42
Can't reproduce on `5.2.0.beta2` (and edge). All is working as expected.
My (assembled from yours pieces) test:

```
  def test_association_stuff
    post = Post.create
    Tracker.create(track:post)
    tracker = Tracker.first
    p tracker
    post = tracker.track
    p post

    assert_equal tracker.track_id, post.id

    t = Tracker.find(1)
    p Tracker.find(1).track
    p Post.find(t.track_id)
    p Post.find(t.track_id).tracker
    p Post.find(t.track_id).tracker.track
  end
```

**Comment by tradeli** [comment] 2017-12-31 08:56
So maybe Kamipo fixed it but forgot to close this hahaha
I think it was here: [commit](https://github.com/rails/rails/commit/6a8ce7416d6615a13ee5c4b9f6bcd91cc5adef4d)

**Comment by kamipo** [comment] 2018-01-06 18:34
Closing this since can't reproduce on `5.2.0.beta2` (and edge, and all stable branches).

**Closed by kamipo** 2018-01-06 18:34 UTC

**Comment by koenpunt** [comment] 2018-01-08 20:48
I actually am experiencing this issue with Rails 5.2.0.beta2..

**Comment by koenpunt** [comment] 2018-01-08 21:08
Explicitly adding `inverse_of: ...` to my `belongs_to ..., polymorphic: true`, makes it work again tho..
