### ISSUE TITLE
ActiveStorage::FileNotFoundError due to ActiveStorage says a files is attached but it's not uploaded yet

### ISSUE THREAD

**Issue by palexvs** [rails/rails#49449] opened 2023-10-02 04:46 UTC
### Steps to reproduce
It's easy to reproduce:

The first console that fetches a file:
```
loop do
  if (image = some_model.find(1).image).attached?
    key = image.attachment.blob.key
    exist = image.attachment.blob.service.exist?(key)
    puts "exist?(#{key}) => #{exist}"
    break if exist
  else
    sleep(0.01)
  end
end
```

The second console that uploads the file:
```
class ActiveStorage::Blob < ActiveStorage::Record
  def upload_without_unfurling(io)
    sleep(1) # Imitate big file upload or some delay on a storage system side
    service.upload key, io, checksum: checksum, **service_metadata
  end
end

some_model.find(1).image.attach(io: StringIO.new(file), filename: filename, content_type: "image/jpg")
```

output in the first console 
```
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => true
```

Most probably, the issue happens due to the upload taking place in `after_commit` callback https://github.com/rails/rails/blob/7-1-stable/activestorage/lib/active_storage/attached/model.rb#L127 that is after a Blob marked as attached and ready to be used

### Expected behavior
`.attached?` returns `true` only when a file is fully uploaded

### Actual behavior
`.attached?` returns `true`, but a file could still be uploading. That leads to many `ActiveStorage::FileNotFoundError` exceptions in our project 

### System configuration
**Rails version**: 7.0.8

**Ruby version**:  3.2.2

**Comment by phil-6** [comment] 2023-10-02 09:15
I think we're experiencing the same issue. After creating an object with an attached image, we're seeing `ActionView::Template::Error: Cannot get a signed_id for a new record.` when using `url_for(chat.picture)`

`chat.picture.url` works fine. However, we want to use `url_for` so a relative url is returned.

Our Chat model has `has_one_attached :picture, service: :chat_pictures` and we attach the picture with `@chat.picture.attach(params[:chat][:picture])`

**Comment by rafaelfranca** [comment] 2023-10-02 10:47
Duplicate of #47047

**Closed by rafaelfranca** 2023-10-02 10:47 UTC
