### ISSUE TITLE
Adding connects_to in ApplicationRecord and subclass mixes up connections during seeds

### ISSUE THREAD

**Issue by ScottRobbins** [rails/rails#36928] opened 2019-08-13 23:06 UTC
### Steps to reproduce
I created an example app that shows this issue https://github.com/ScottRobbins/RailsMultipleDatabaseIssue

You will need to set up the necessary credentials for your local database.

Run the seeds `bundle exec rails db:seed`

### Expected behavior
These seeds should run fine 

### Actual behavior
Error:
```
rails aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'development_secondary.artists' doesn't exist
/Users/scottrobbins/TestProjects/RailsMultipleDatabaseIssue/db/seeds.rb:9:in `<main>'
bin/rails:4:in `<main>'

Caused by:
Mysql2::Error: Table 'development_secondary.artists' doesn't exist
/Users/scottrobbins/TestProjects/RailsMultipleDatabaseIssue/db/seeds.rb:9:in `<main>'
bin/rails:4:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

### System configuration
**Rails version**: 6.0.0.rc2

**Ruby version**: 2.6.3

**MySQL version**: 5.6 & 5.7

### Other notes

We made this setup based on the [documentation](https://github.com/rails/rails/blob/master/guides/source/active_record_multiple_databases.md) and a recommendation on an [unrelated issue](https://github.com/rails/rails/issues/36894#issuecomment-519672987)

To get around this error, we are removing the `connects_to` call from the `ApplicationRecord` and making a subclass of that for both the primary and secondary database. You can see that fix [in this pr](https://github.com/ScottRobbins/RailsMultipleDatabaseIssue/pull/2) on the example project

**Comment by prathamesh-sonpatki** [comment] 2019-08-14 03:52
@ScottRobbins This issue does not exist on 6-0-stable branch.  I verified your app against it and it is working correctly.

**Comment by rafaelfranca** [comment] 2019-08-14 05:05
Closing since the issue is already fixed. Let us know if you still have it.

**Closed by rafaelfranca** 2019-08-14 05:05 UTC
