### ISSUE TITLE
default_scope overrides default model values

### ISSUE THREAD

**Issue by exocode** [rails/rails#45039] opened 2022-05-07 23:56 UTC
### Steps to reproduce

SCHEMA:
```ruby
create_table "user", force: :cascade do |t|
    t.string "name"
    t.boolean "active", default: false
end
```

Model
```ruby
class User < ApplicationRecord
  default_scope { where(active: true) }
end

u = User.create!(name: "test")
u.active? # returns true (should be false)
```

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do

  create_table :users, force: true do |t|
    t.string :name
    t.boolean :active, default: false # <<<< default false
    
  end
end

class User < ActiveRecord::Base
  
end


class UserWithDefaultScope < User
  default_scope { where(active: true) }
end

class BugTest < Minitest::Test
  # WORKS
    def test_built_user
    new_user = User.new(name: "test")

    assert_equal false, new_user.active?
  end

  def test_created_user
    saved_user = User.create!(name: "test2")   

    assert_equal false, saved_user.active?
  end 

  # FAILS
  def test_with_default_scope_built_user
    new_user = UserWithDefaultScope.new(name: "test")

    assert_equal false, new_user.active?
  end

  def test_with_default_scope_created_user
    saved_user = UserWithDefaultScope.create!(name: "test2")   

    assert_equal false, saved_user.active?
  end

end


```

### Expected behavior
user.active should be false

### Actual behavior
user.active is false

### System configuration
**Rails version**:
rails 6.1.4.1

**Ruby version**:
ruby '2.7.2'

**Comment by SkipKayhil** [comment] 2022-05-08 00:43
Copying my comment from https://github.com/rails/rails/issues/44741#issuecomment-1075343828:

> Actually this is specifically documented so I think this behavior is intended: https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Default/ClassMethods.html#method-i-default_scope
> 
> > The default_scope is also applied while creating/building a record. It is not applied while updating or deleting a record.
> 
> ```ruby
> Article.new.published    # => true
> Article.create.published # => true
> ```

so I believe this is working as intended. This is a slightly different case (the schema having a default value set) so I'm going to leave the issue open for now to give others a chance to chime in, but based on the discussion in the other linked issue I don't think this will be changed.

**Comment by exocode** [comment] 2022-05-08 10:29
My understanding is, that `default_scope` is used to "pre-filter" regular database queries, like "ordering" or "where" clauses, to not accidentally show results.

So a default query (like in the one in the link you posted) `Article.all` returns Articles which are published and ordered by date, by default.

A common use case:
- when I create an Article they must be reviewed before by a Moderator/Editor
- So each creation of an Artcle must be initially unpublished or in a review state
- This is where `default:` in DB schemes comes into place. Each `Article` MUST be `published: false` after creation
- Only editors are able to publish them after reviewing

How would you solve that, if `default_scope` overrides the **in the DB defined scheme**:
`t.boolean, :published, default: false` ??

I don't think that it intentionally to create all Articles with `Article.unscoped.create`. What about fixtures and fabricators?

For what reason exists a default: option in the migration, when it get's overridden by a default_scope (which is used to return filtered queries). 

How do you create for example `Users` which must not be `active` by default, after they sign up and you have a `default_scope` in the `User` model

I don't get the point, please enlighten me :-)

**Comment by eileencodes** [comment] 2022-05-09 15:41
> What is the purpose of default migration values, when they get overridden in the model? Has someone a use case please for the current behaviour?

Having a default set on your schema and using default scopes, is a case of using 2 competing features. If you're using both together, it's not surprising to me that `default_scope` wins. By setting that in your model you're essentially saying "everything should have this default scope regardless of what else is going on, unless I call `unscoped`". .

> For what reason exists a default:-option in the migration/schemes, when they get overridden by a default_scope (which is a query and return filtered queries).

These features have different use cases, that's why they both exist. The `default` option is for cases when an application always wants a default value set on creation, but does not want to change select queries to include that in the query. `default_scope` however, is meant to change the query by always adding a default scope. Basically `default` can only set a default _value_ whereas `default_scope` changes the underlying query. In your case you're using the same column, but default_scope could be use for much more than querying a single column with a default value.

> I suggest default_scope should not override in DB scheme predefined/default values. If this is the intention of the user there could be a default_attributes or an application wide configuration

Changing this could have a lot consequences on applications currently using `default_scope` with other columns/attributes. We could deprecate the behavior but I don't agree the current behavior is incorrect. I get this is frustrating, but changing this is non-trivial and the behavior is documented, so I'm going to close this issue.

**Closed by eileencodes** 2022-05-09 15:41 UTC
Labels: activerecord
