### ISSUE TITLE
ActiveRecord::CollectionProxy#delete_all and ActiveRecord::Relation#delete_all do not follow the principle of least surprise

### ISSUE THREAD

**Issue by zealoushacker** [rails/rails#19085] opened 2015-02-26 02:22 UTC
Though it seems like the two methods above ought to behave identically, and follow the principle of least surprise, they actually behave *very surprisingly* and differently:

`ActiveRecord::CollectionProxy#delete_all` and its counterpart `ActiveRecord::CollectionProxy#destroy_all` take as its argument a `dependent` parameter, whose default value is `nil`. This is very different from how `ActiveRecord::Relation#delete_all` and `ActiveRecord::Relation#destroy_all` work, which take a set of conditions, such as those that may be passed to  `ActiveRecord::Base#where`.

This doesn't seem to make any sense, and caused me to figure out the answer by reading the docs, rather than following the obvious assumption that both should work in the same fundamental way. 

While the answer to this issue may be: "RTFM" - I did, and this seems like an incorrect design decision that may be in need of refactoring, leading to a lot of head scratching.

/cc: @eschoppik, with whom I had discovered this issue.

**Comment by prathamesh-sonpatki** [comment] 2015-02-26 03:38
@zealoushacker The usecases of these 2 methods are different. `CollectionProxy#delete_all/destroy_all` are used internally to delete associated records when parent record gets deleted based on the `dependent` option. `Relation#delete_all/destroy_all` methods will delete the records which match the conditions given in arguments. I think we should not call the `CollectionProxy#delete_all/destroy_all` methods ourselves as Rails will internally handles it through the associations DSL. May be the `CollectionProxy` class should be marked as `nodoc`? //@arthurnn

**Comment by sgrif** [comment] 2015-02-26 04:09
> While the answer to this issue may be: "RTFM"

Yeah, pretty much. The issue tracker is reserved for bugs only (e.g. this used to work on 4.1, but is broken on 4.2). Discussions like this are better suited for the mailing list.

**Closed by sgrif** 2015-02-26 04:09 UTC

**Comment by prathamesh-sonpatki** [comment] 2015-02-26 04:27
@sgrif User should not call the `CollectionProxy#delete_all/destroy_all` right? Should those methods be nodoc'ed?

**Comment by sgrif** [comment] 2015-02-26 04:35
No those methods are part of the public api.

**Comment by zealoushacker** [comment] 2015-02-26 04:39
+1 on the nodoc. However, it feels like it's just too easy to make that mistake, because the method makes sense in the context it's called on a CollectionProxy, but then surprises you with the thrown error when invokes. 

Make it private so it may not be called directly on the collection, or rename it. Yes?

**Comment by sgrif** [comment] 2015-02-26 04:41
The methods will not be nodoced. It is part of the public API on Relation, so it is part of the public API of Relation subclasses.

**Comment by zealoushacker** [comment] 2015-02-26 04:59
Then how is surprising users a good thing?

Should I issue a pr creating a method with a different name accomplishing the functionality of the CollectionProxy version of these methods, renaming all occurrences in the code base that depend on them, and then recreating #delete_all/#destroy_all to do what they do for ActiveRecord::Relation, so they don't surprise users?

**Comment by sgrif** [comment] 2015-02-26 05:00
As I've already said, the issues tracker is not the right place to discuss this, as it is not a bug.
