### ISSUE TITLE
ActiveRecord calling after_update before calling after_create

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#23390] opened 2016-02-01 03:42 UTC
I have some code which when calling save, seems to invoke callbacks incorrectly. Some how, after calling `_create_record`, it ends up calling `after_update`, but soon after `after_create` is invoked.

Here is a stack trace of the first call to `after_update`

```
   #0  trigger_update <GeoZone::Poi#trigger_update(action=?)>
   #1 [block]   block in <class:Poi> 
   #2 [block]   block in make_lambda <ActiveSupport::Callbacks::Callback#make_lambda(filter)>
   #3 [block]   block in halting_and_conditional <ActiveSupport::Callbacks::Filters::After.halting_and_conditional(callback_sequence, user_callback, user_conditions)>
   #4 [block]   block in call <ActiveSupport::Callbacks::CallbackSequence#call(*args)>
   #5 [method]  call <ActiveSupport::Callbacks::CallbackSequence#call(*args)>
   #6 [method]  __run_callbacks__ <ActiveSupport::Callbacks#__run_callbacks__(callbacks, &block)>
   #7 [method]  _run_update_callbacks <ActiveRecord::Base#_run_update_callbacks(&block)>
   #8 [method]  _update_record <ActiveRecord::Callbacks#_update_record(*arg1)>
   #9 [method]  _update_record <ActiveRecord::Timestamp#_update_record(*args)>
   #10 [method]  create_or_update <ActiveRecord::Persistence#create_or_update()>
   #11 [block]   block in create_or_update <ActiveRecord::Callbacks#create_or_update()>
   #12 [method]  call <ActiveSupport::Callbacks::Filters::End#call(env)>
   #13 [block]   block (2 levels) in compile <ActiveSupport::Callbacks::CallbackChain#compile()>
   #14 [method]  call <ActiveSupport::Callbacks::CallbackSequence#call(*args)>
   #15 [method]  __run_callbacks__ <ActiveSupport::Callbacks#__run_callbacks__(callbacks, &block)>
   #16 [method]  _run_save_callbacks <ActiveRecord::Base#_run_save_callbacks(&block)>
   #17 [method]  create_or_update <ActiveRecord::Callbacks#create_or_update()>
   #18 [method]  save <ActiveRecord::Persistence#save(*arg1)>
   #19 [method]  save <ActiveRecord::Validations#save(options=?)>
   #20 [method]  save <ActiveRecord::AttributeMethods::Dirty#save(*arg1)>
   #21 [block]   block (2 levels) in save <ActiveRecord::Transactions#save(*arg1)>
   #22 [block]   block in with_transaction_returning_status <ActiveRecord::Transactions#with_transaction_returning_status()>
   #23 [method]  transaction <ActiveRecord::ConnectionAdapters::DatabaseStatements#transaction(options=?)>
   #24 [method]  transaction <ActiveRecord::Transactions::ClassMethods#transaction(options=?, &block)>
   #25 [method]  with_transaction_returning_status <ActiveRecord::Transactions#with_transaction_returning_status()>
   #26 [block]   block in save <ActiveRecord::Transactions#save(*arg1)>
   #27 [method]  rollback_active_record_state! <ActiveRecord::Transactions#rollback_active_record_state!()>
   #28 [method]  save <ActiveRecord::Transactions#save(*arg1)>
   #29 [method]  save_belongs_to_association <ActiveRecord::AutosaveAssociation#save_belongs_to_association(reflection)>
   #30 [block]   block in add_autosave_association_callbacks <self.add_autosave_association_callbacks(UNKNOWN) (undefined method)>
   #31 [block]   block in define_non_cyclic_method <GeoZone::PoiCategory#autosave_associated_records_for_poi(*args)>
   #32 [block]   block in make_lambda <ActiveSupport::Callbacks::Callback#make_lambda(filter)>
   #33 [block]   block in halting <ActiveSupport::Callbacks::Filters::Before.halting(callback_sequence, user_callback, halted_lambda, filter)>
   #34 [block]   block in call <ActiveSupport::Callbacks::CallbackSequence#call(*args)>
   #35 [method]  call <ActiveSupport::Callbacks::CallbackSequence#call(*args)>
   #36 [method]  __run_callbacks__ <ActiveSupport::Callbacks#__run_callbacks__(callbacks, &block)>
   #37 [method]  _run_save_callbacks <ActiveRecord::Base#_run_save_callbacks(&block)>
   #38 [method]  create_or_update <ActiveRecord::Callbacks#create_or_update()>
   #39 [method]  save <ActiveRecord::Persistence#save(*arg1)>
   #40 [method]  save <ActiveRecord::Validations#save(options=?)>
   #41 [method]  save <ActiveRecord::AttributeMethods::Dirty#save(*arg1)>
   #42 [block]   block (2 levels) in save <ActiveRecord::Transactions#save(*arg1)>
   #43 [block]   block in with_transaction_returning_status <ActiveRecord::Transactions#with_transaction_returning_status()>
   #44 [method]  transaction <ActiveRecord::ConnectionAdapters::DatabaseStatements#transaction(options=?)>
   #45 [method]  transaction <ActiveRecord::Transactions::ClassMethods#transaction(options=?, &block)>
   #46 [method]  with_transaction_returning_status <ActiveRecord::Transactions#with_transaction_returning_status()>
   #47 [block]   block in save <ActiveRecord::Transactions#save(*arg1)>
   #48 [method]  rollback_active_record_state! <ActiveRecord::Transactions#rollback_active_record_state!()>
   #49 [method]  save <ActiveRecord::Transactions#save(*arg1)>
   #50 [method]  insert_record <ActiveRecord::Associations::HasManyAssociation#insert_record(record, validate=?, raise=?)>
   #51 [block]   block in save_collection_association <ActiveRecord::AutosaveAssociation#save_collection_association(reflection)>
   #52 [method]  save_collection_association <ActiveRecord::AutosaveAssociation#save_collection_association(reflection)>
   #53 [block]   block in add_autosave_association_callbacks <self.add_autosave_association_callbacks(UNKNOWN) (undefined method)>
   #54 [block]   block in define_non_cyclic_method <self.autosave_associated_records_for_poi(UNKNOWN) (undefined method)>
   #55 [block]   block in make_lambda <ActiveSupport::Callbacks::Callback#make_lambda(filter)>
=> #56 [block]   block in halting_and_conditional <ActiveSupport::Callbacks::Filters::After.halting_and_conditional(callback_sequence, user_callback, user_conditions)>
   #57 [block]   block in call <ActiveSupport::Callbacks::CallbackSequence#call(*args)>
   #58 [method]  call <ActiveSupport::Callbacks::CallbackSequence#call(*args)>
   #59 [method]  __run_callbacks__ <ActiveSupport::Callbacks#__run_callbacks__(callbacks, &block)>
   #60 [method]  _run_create_callbacks <ActiveRecord::Base#_run_create_callbacks(&block)>
   #61 [method]  _create_record <ActiveRecord::Callbacks#_create_record()>
   #62 [method]  _create_record <ActiveRecord::Timestamp#_create_record()>
   #63 [method]  create_or_update <ActiveRecord::Persistence#create_or_update()>
```

Here is the stack trace calling `after_create`

```
Showing all accessible frames in stack (84 in total):
--
=> #0  trigger_update <GeoZone::Poi#trigger_update(action=?)>
   #1 [block]   block in <class:Poi> 
   #2 [block]   block in make_lambda <ActiveSupport::Callbacks::Callback#make_lambda(filter)>
   #3 [block]   block in halting_and_conditional <ActiveSupport::Callbacks::Filters::After.halting_and_conditional(callback_sequence, user_callback, user_conditions)>
   #4 [block]   block in call <ActiveSupport::Callbacks::CallbackSequence#call(*args)>
   #5 [method]  call <ActiveSupport::Callbacks::CallbackSequence#call(*args)>
   #6 [method]  __run_callbacks__ <ActiveSupport::Callbacks#__run_callbacks__(callbacks, &block)>
   #7 [method]  _run_create_callbacks <ActiveRecord::Base#_run_create_callbacks(&block)>
   #8 [method]  _create_record <ActiveRecord::Callbacks#_create_record()>
   #9 [method]  _create_record <ActiveRecord::Timestamp#_create_record()>
   #10 [method]  create_or_update <ActiveRecord::Persistence#create_or_update()>
```

It seems like the issue is the order of invocation of `self.autosave_associated_records_for_poi`. But, I'm not sure what other information would be useful to debug this issue.

**Comment by rafaelfranca** [comment] 2016-02-01 03:43
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by ioquatix** [comment] 2016-02-01 03:45
Yes I can try.

**Comment by ioquatix** [comment] 2016-02-01 05:46
Okay, here it is.

The output:

```
-- create_table("category", {:force=>:cascade})
D, [2016-02-01T18:45:31.632130 #42828] DEBUG -- :    (0.2ms)  CREATE TABLE "category" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL) 
   -> 0.0144s
-- create_table("poi_category", {:force=>:cascade})
D, [2016-02-01T18:45:31.632643 #42828] DEBUG -- :    (0.1ms)  CREATE TABLE "poi_category" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "poi_id" integer(4) NOT NULL, "category_id" integer(4) NOT NULL) 
   -> 0.0004s
-- create_table("poi", {:force=>:cascade})
D, [2016-02-01T18:45:31.632945 #42828] DEBUG -- :    (0.1ms)  CREATE TABLE "poi" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL) 
   -> 0.0003s
D, [2016-02-01T18:45:31.642948 #42828] DEBUG -- :    (0.3ms)  CREATE TABLE "active_record_internal_metadatas" ("key" varchar PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL) 
D, [2016-02-01T18:45:31.651491 #42828] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.1ms)  SELECT  "active_record_internal_metadatas".* FROM "active_record_internal_metadatas" ORDER BY "active_record_internal_metadatas"."key" ASC LIMIT ?  [["LIMIT", 1]]
D, [2016-02-01T18:45:31.665609 #42828] DEBUG -- :    (0.0ms)  begin transaction
D, [2016-02-01T18:45:31.666607 #42828] DEBUG -- :   SQL (0.1ms)  INSERT INTO "active_record_internal_metadatas" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "development"], ["created_at", 2016-02-01 05:45:31 UTC], ["updated_at", 2016-02-01 05:45:31 UTC]]
D, [2016-02-01T18:45:31.666772 #42828] DEBUG -- :    (0.0ms)  commit transaction
Run options: --seed 54156

# Running:

D, [2016-02-01T18:45:31.686636 #42828] DEBUG -- :    (0.0ms)  begin transaction
D, [2016-02-01T18:45:31.687210 #42828] DEBUG -- :   SQL (0.0ms)  INSERT INTO "category" DEFAULT VALUES
D, [2016-02-01T18:45:31.687375 #42828] DEBUG -- :    (0.0ms)  commit transaction
D, [2016-02-01T18:45:31.703327 #42828] DEBUG -- :    (0.1ms)  begin transaction
D, [2016-02-01T18:45:31.704276 #42828] DEBUG -- :   SQL (0.1ms)  INSERT INTO "poi" DEFAULT VALUES
D, [2016-02-01T18:45:31.705585 #42828] DEBUG -- :   SQL (0.1ms)  UPDATE "poi" SET "id" = ? WHERE "poi"."id" = ?  [["id", 1], ["id", 1]]
D, [2016-02-01T18:45:31.706034 #42828] DEBUG -- :   SQL (0.1ms)  INSERT INTO "poi_category" ("poi_id", "category_id") VALUES (?, ?)  [["poi_id", 1], ["category_id", 1]]
D, [2016-02-01T18:45:31.706257 #42828] DEBUG -- :    (0.0ms)  commit transaction
F

Finished in 0.043374s, 23.0551 runs/s, 23.0551 assertions/s.

  1) Failure:
BugTest#test_association_stuff [./bug.rb:80]:
--- expected
+++ actual
@@ -1 +1 @@
-[:after_update, :after_save, :after_create, :after_save]
+[:after_create, :after_save]


1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

Here is the test case: https://gist.github.com/ioquatix/f7559ce10e25ee0df8b6

**Comment by ioquatix** [comment] 2016-02-01 05:54
So, just FYI, if you comment out the line

```
		#poi.categories << category 
```

Everything works as expected. This is kind of what I assumed - if you look into the backtrace you see it's saving the association first which is trigging some strange behaviour.

**Comment by ioquatix** [comment] 2016-02-01 05:58
The reason why this is a problem is because we have a state synchronisation system which depends on another table, and we add entries when these callbacks are triggered. Mobile clients, in effect, read this change list and do as instructed (e.g. create, update or delete). Fortunately this edge case isn't completely problematic but it isn't ideal. I caught it because our unit test explicitly checks the order these entries are created. I'm pretty sure about 3-6 months ago this was working correctly. Perhaps someone more knowledgeable about this repo can bisect?

**Comment by prathamesh-sonpatki** [comment] 2016-02-01 06:06
Thanks for the script @ioquatix!

Verified that this script fails on 4.2.5, master but passes on 4.0.9

Here are results on 4.0.9
```
D, [2016-02-01T11:35:11.131408 #56088] DEBUG -- :    (0.0ms)  begin transaction
D, [2016-02-01T11:35:11.134029 #56088] DEBUG -- :   SQL (0.0ms)  INSERT INTO "category" DEFAULT VALUES
D, [2016-02-01T11:35:11.134219 #56088] DEBUG -- :    (0.0ms)  commit transaction
D, [2016-02-01T11:35:11.146741 #56088] DEBUG -- :    (0.0ms)  begin transaction
D, [2016-02-01T11:35:11.148434 #56088] DEBUG -- :   SQL (0.1ms)  INSERT INTO "poi" DEFAULT VALUES
D, [2016-02-01T11:35:11.150870 #56088] DEBUG -- :   SQL (1.6ms)  INSERT INTO "poi_category" ("category_id", "poi_id") VALUES (?, ?)  [["category_id", 1], ["poi_id", 1]]
D, [2016-02-01T11:35:11.151421 #56088] DEBUG -- :    (0.0ms)  commit transaction
.

Finished tests in 0.023449s, 42.6457 tests/s, 42.6457 assertions/s.

1 tests, 1 assertions, 0 failures, 0 errors, 0 skips
```

Notice that there is no update query to update id of `poi`.

```
D, [2016-02-01T18:45:31.705585 #42828] DEBUG -- :   SQL (0.1ms)  UPDATE "poi" SET "id" = ? WHERE "poi"."id" = ?  [["id", 1], ["id", 1]]`
```

is not present with 4.0.9.

**Comment by ioquatix** [comment] 2016-02-01 06:09
I didn't even realise that UPDATE id = 1 WHERE id = 1... wow, that's some next level full retard.

**Comment by prathamesh-sonpatki** [comment] 2016-02-01 06:11
@ioquatix Will it possible for you to use git bisect and figure out which commit caused this? Thanks for the help so far!

**Comment by ioquatix** [comment] 2016-02-01 06:12
I don't know anything about using git bisect on this massive repo sorry, is it explained somewhere how to do it?

**Comment by prathamesh-sonpatki** [comment] 2016-02-01 06:15
ok, no issues :) We will need to add this test that you have added in activerecord tests, and run git bisect against it.

**Comment by ioquatix** [comment] 2016-02-05 01:01
Just wondering if there is an ETA for a fix? This is a pretty major bug.

**Comment by maclover7** [comment] 2016-02-05 01:59
Will take a look at this. r? @maclover7

**Comment by ioquatix** [comment] 2016-02-05 02:01
Some notes:

Failed with arel 5.0.1 and rails 4.1.14
Failed with arel 5.0.1 and rails 4.1.0
Success with arel 4.0.2 rails 4.0.13

Bisecting now..

**Comment by ioquatix** [comment] 2016-02-05 02:02
26d19b4661f3d89a075b5f05d926c578ff0c730f is the first bad commit
commit 26d19b4661f3d89a075b5f05d926c578ff0c730f
Author: wangjohn <wangjohn@mit.edu>
Date:   Fri Mar 1 16:49:33 2013 -0500

    Created a method to automatically find inverse associations and cache
    the results. Added tests to check to make sure that inverse associations are
    automatically found when has_many, has_one, or belongs_to associations
    are defined.

:040000 040000 1121f1a2ed2ccbd0003404fe971e17a28d7e9804 6c63be2f96fdd536b557dd986a827ef9238e00d6 M	activerecord

**Comment by ioquatix** [comment] 2016-02-05 02:03
Okay, so the problem is due to the inverse relationship.. So, i'm going to add the inverse relationship manually and bisect again. Hold on.

**Comment by ioquatix** [comment] 2016-02-05 02:05
Okay, now it is failing with 4.0.13

**Comment by ioquatix** [comment] 2016-02-05 02:07
```ruby
lass Category < ActiveRecord::Base
	self.table_name = "category"

	has_many :poi_categories, inverse_of: :category
	has_many :pois, :through => :poi_categories
end

class PoiCategory < ActiveRecord::Base
	self.table_name = "poi_category"
	
	belongs_to :category, inverse_of: :poi_categories
	belongs_to :poi, autosave: true, inverse_of: :poi_categories
end

class Poi < ActiveRecord::Base
	self.table_name = "poi"

	has_many :poi_categories, autosave: true, :dependent => :destroy, inverse_of: :poi
	has_many :categories, through: :poi_categories
	
	attr_accessor :sequence
	
	after_create {|record| sequence << :after_create }
	after_update {|record| sequence << :after_update }
	after_save {|record| sequence << :after_save }
end
```

The only change was to add `inverse_of: poi`. This should be fine though right?

**Comment by ioquatix** [comment] 2016-02-05 02:08
Broken in 4.0.0.

**Comment by ioquatix** [comment] 2016-02-05 02:09
Working in rails 3.2.22

**Comment by ioquatix** [comment] 2016-02-05 02:15
Okay, so I don't think there is a specific commit I can identify but it does seem to be broken even in v3.x.x - however there are other bugs that start cropping up which make it hard to identify.

I believe the next step would be to actually take a look at the callback sequence. It looks like the callback sequence is somehow being triggered incorrectly because when Poi is being saved, it saves it's relationships, but then somehow that comes back to Poi and triggers the update callback before the create callback is done.

**Comment by maclover7** [comment] 2016-02-05 03:02
After some debugging with your reproduction script, I was able to determine that the autosave functionality you have enabled is the issue you are seeing. By enabling autosave on two of the models (note test cases [here][jon]), this causes the `after_update` and `after_save` callbacks to be pulled into the stack -- this is on purpose, and I believe is the intended behavior of `autosave`. I don't think this is a bug here. You can view my [full reproduction script here][jon] -- please let me know if you do not agree with my conclusion. :)

[jon]: https://gist.github.com/maclover7/5d3b9506c1a511890b83

**Comment by ioquatix** [comment] 2016-02-05 06:00
Well, it fixes our problem, so I won't argue. However, superficially, it does appear to be a bug. Especially I don't get why:

```
D, [2016-02-01T18:45:31.705585 #42828] DEBUG -- :   SQL (0.1ms)  UPDATE "poi" SET "id" = ? WHERE "poi"."id" = ?  [["id", 1], ["id", 1]]`
```

is a good idea in any situation. And, the order of callbacks should be somewhat invariant? Anyway, thanks for your input and time, it was very helpful.

**Comment by maclover7** [comment] 2016-02-05 15:16
No problem! Closing issue.

**Closed by maclover7** 2016-02-05 15:16 UTC
Labels: activerecord, With reproduction steps
