### ISSUE TITLE
"Cannot expire connection, it is owned by a different thread" in Rails 7.2 tests

### ISSUE THREAD

**Issue by jdelStrother** [rails/rails#52973] opened 2024-09-19 13:29 UTC
### Steps to reproduce

After upgrading 7.1.4 -> 7.2.1, we've started seeing some sporadic failures in our test suite. I've narrowed it down to happening when a Capybara system test is followed by a unit test that sets `use_transactional_tests = false`, followed by another Capybara system test. Capybara then fails to load pages, with errors along the lines of:

```
  ActiveRecord::ActiveRecordError:
  Cannot expire connection, it is owned by a different thread: #<Thread:0x000000010051b0e8 sleep>. Current thread: #<Thread:0x0000000110dc03c8 /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:113 run>.

# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:316:in `expire'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:555:in `block (3 levels) in checkin'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:110:in `run_callbacks'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:913:in `_run_checkin_callbacks'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:554:in `block (2 levels) in checkin'
# /nix/store/cvwv2rkas498bv81lrd2wxdr50kfkqhv-ruby-3.2.4/lib/ruby/3.2.0/monitor.rb:202:in `synchronize'
# /nix/store/cvwv2rkas498bv81lrd2wxdr50kfkqhv-ruby-3.2.4/lib/ruby/3.2.0/monitor.rb:202:in `mon_synchronize'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:551:in `block in checkin'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:550:in `checkin'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:367:in `release_connection'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/query_cache.rb:48:in `block in complete'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_handler.rb:108:in `block (2 levels) in each_connection_pool'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/pool_manager.rb:31:in `each_value'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/pool_manager.rb:31:in `block in each_pool_config'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/pool_manager.rb:30:in `each_value'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/pool_manager.rb:30:in `each_pool_config'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_handler.rb:107:in `block in each_connection_pool'
# ./vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:265:in `block in each_value'
# ./vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:101:in `block in each_pair'
# ./vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:100:in `each_pair'
# ./vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:100:in `each_pair'
# ./vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:276:in `each_pair'
# ./vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:265:in `each_value'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_handler.rb:106:in `each_connection_pool'
# ./vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.1/lib/active_record/query_cache.rb:47:in `complete'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/execution_wrapper.rb:36:in `before'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:385:in `block in make_lambda'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:179:in `block in call'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:668:in `block (2 levels) in default_terminator'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:667:in `catch'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:667:in `block in default_terminator'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:180:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `block in invoke_before'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `each'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `invoke_before'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:109:in `run_callbacks'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/execution_wrapper.rb:142:in `complete'
# ./vendor/bundle/ruby/3.2.0/gems/activesupport-7.2.1/lib/active_support/execution_wrapper.rb:136:in `complete!'
# ./vendor/bundle/ruby/3.2.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/executor.rb:28:in `ensure in call'
# ./vendor/bundle/ruby/3.2.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/executor.rb:28:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/static.rb:27:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/rack-3.1.7/lib/rack/sendfile.rb:114:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/rack-cors-2.0.2/lib/rack/cors.rb:102:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/rack-mini-profiler-3.3.1/lib/mini_profiler.rb:191:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/railties-7.2.1/lib/rails/engine.rb:535:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/rack-3.1.7/lib/rack/urlmap.rb:76:in `block in call'
# ./vendor/bundle/ruby/3.2.0/gems/rack-3.1.7/lib/rack/urlmap.rb:60:in `each'
# ./vendor/bundle/ruby/3.2.0/gems/rack-3.1.7/lib/rack/urlmap.rb:60:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/rack-3.1.7/lib/rack/builder.rb:277:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/capybara-3.40.0/lib/capybara/server/middleware.rb:60:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
# ./vendor/bundle/ruby/3.2.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
# ./vendor/bundle/ruby/3.2.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
# ./vendor/bundle/ruby/3.2.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
# ./vendor/bundle/ruby/3.2.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
# ./vendor/bundle/ruby/3.2.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
# ./vendor/bundle/ruby/3.2.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

The puma thread seems to be trying to expire a connection owned by the main thread.

I've also occasionally seen the error reported being "Cannot expire connection, it is not currently leased".

I've bisected the Rails issue down to starting at https://github.com/rails/rails/pull/51725 - prior to that commit, I don't see any of these errors.

The transactionless test could be as simple as:

```ruby
RSpec.describe User, type: :model do
  self.use_transactional_tests = false
  it "can handle simultaneous transactions" do
    Array.new(5) {
      Thread.new { User.first }
    }.map(&:join)
  end
end
```

I'm still working on a reproduction script, but having tried to narrow it down for several hours without any luck I thought I'd post this in the hope that someone might immediately recognise the problem. 

@casperisfine I don't suppose this rings any bells for you? Sorry, I appreciate it's a vague question - I'll carry on trying to come up with a demo app if not.

### System configuration
**Rails version**: 7.1.4

**Ruby version**: 3.2.4

**Comment by casperisfine** [comment] 2024-09-19 13:46
> I don't suppose this rings any bells for you?

It doesn't ring a particular bell, but yes there is a number of things that could be going wrong, but not easy to investigate without a repro.

But yes, it sounds like a synchronisation issue between the various threads. I suspect the Puma thread is sometimes leasing a connection while transactional fixtures are still active. With transactional fixtures the same connection is handed to all threads, so if you don't check it back in in the right order, you might end up with this sort of errors.

**Comment by jdelStrother** [comment] 2024-09-20 14:14
I believe I've come up with a small-ish reproduction here:

https://github.com/jdelStrother/rails-transaction-error

Check it out, run `bundle && ruby test/system/posts_test.rb -v`, and you should hit an unexpected test failure that worked fine under Rails 7.1 .  It doesn't happen 100% of the time, please re-run a couple of times if you don't see it immediately.


There's a few layers to the problem...

The test suite at https://github.com/jdelStrother/rails-transaction-error/blob/90b02d59442a503a0f4995a1ee8c0f2e11cff07a/test/system/posts_test.rb#L18-L48 has 3 tests:

1) fetching posts#show via puma
2) a test with `use_transactional_tests = false` that uses a connection in a thread
3) again, fetching posts#show via puma


The last test fails - it seems like the controller (in a puma thread) is re-using a connection that doesn't have the same view of the database as the test does, and so fails to find the newly-created Post.

The problem only surfaces if the request from the first test uses `ActiveRecord::Base.connection`, like [PostsController is doing here](https://github.com/jdelStrother/rails-transaction-error/blob/90b02d59442a503a0f4995a1ee8c0f2e11cff07a/app/controllers/posts_controller.rb#L4)


So the first bug is that in the third test, the main thread's connection has created a Post that the puma thread's connection can't see. (Unless it's a user-error and there's something wrong with my direct use of `ActiveRecord::Base.connection` or those `Thread.new { Post.first }` calls?)

If the controller throws an exception (eg ActiveRecord::RecordNotFound) because its connection is in a weird state, _then_ you'll see the `Cannot expire connection, it is not currently leased` errors. I'm not sure if that's a second bug, or just a symptom of the first, but you can see that by uncommenting this line: https://github.com/jdelStrother/rails-transaction-error/blob/90b02d59442a503a0f4995a1ee8c0f2e11cff07a/app/controllers/posts_controller.rb#L7

**Comment by casperisfine** [comment] 2024-09-23 13:21
Thanks a lot for the repro. I unfortunately won't have time to look at it this week, but hoping to dig into it sometimes next week (sorry).

**Comment by jdelStrother** [comment] 2024-09-23 13:26
No problem, let me know if I can help clarify anything.

**Comment by woto** [comment] 2024-09-28 11:52
Just came here by googling same problem. Didn't get this error before. I'm on Rails 8 beta 1. Can't localize problem yet. Strange thing. I have 3 tests. When I run all of them. Then 1 test failed and other passes. But if I run tests 1 by one separately, then all tests are failed.

**Comment by fwolfst** [comment] 2024-09-30 08:28
We have private reproducible code where running a single (Capybara/feature, rspec) spec fails. Unfortunately I cannot share the code and extracting/recreating a repository where it is reproducible might be a lot of work, but tell me if that is needed (afaiu we already have code to reproduce from @jdelStrother ).

**Comment by casperisfine** [comment] 2024-09-30 14:02
> so fails to find the newly-created Post.

Ah, so that's the "not found" I'm seeing. OK I'll try to dig a bit deeper.

**Comment by casperisfine** [comment] 2024-09-30 14:08
Ok, I get the repro now. Sorry, Monday morning is hard.

**Comment by jdelStrother** [comment] 2024-09-30 14:35
Oh good 😅. 

I was struggling to figure out why you might not be seeing it in the reproduction, & started putting together a docker image to see if I could make it any more reproducible. It does seem to occur far less frequently in a dockerized version compared to running natively on my M1 MacBook - maybe failing 20% of the time rather than 80%.

In theory, the reproduction test (`ruby test/system/posts_test.rb`) should have zero test failures (like it does in Rails 7.1). If it raises RecordNotFound or ActiveRecordError, that means you've reproduced the bug.

**Comment by casperisfine** [comment] 2024-09-30 14:39
So what I'm seeing by adding some debug logs:

- `PostsTest1#test_1)_initial_visit`
  - Main thread checkout and pin the connection (because transactional on)
  - Puma thread checkout -> checking -> checkout again
  - Main thread checkin the connection
- `PostsTest2#test_2)_threaded_transactions` 
  - Just the main thread using connections, no activity from Puma.
- `PostsTest3#test_3)_visiting_with_a_bad_transaction`
  - Puma thread checkin the connection it was holding onto, and that create an error.

Still unclear why this timeline is like this, I need to figure out why Puma is checking out a connection at the end of `test_1` and holding onto it.

**Comment by casperisfine** [comment] 2024-09-30 15:07
Alright, I think I got a smoking gun.

The connection is supposed to be released at the end of the request by the executor, the code is essentially:

```
      ActiveRecord::Base.connection_handler.each_connection_pool do |pool|
        pool.release_connection if pool.active_connection? && !pool.lease_connection.transaction_open?
      end
```

But it's not happening, because:

```
(ruby) pool.lease_connection.transaction_open?
true
```

I think this code is just not accounting for transactional fixtures.

**Comment by fwolfst** [comment] 2024-09-30 15:31
> @jdelStrother can you try this branch: #53118 ? I fixes your repro script.

Adding
```
+gem 'activerecord', git: 'https://github.com/Shopify/rails', branch: 'release-transactional-fixtures-connections'
```
should do the trick, right? In my case it is still giving `ActiveRecord::ActiveRecordError: Cannot expire connection, it is owned by a different thread: #<Thread:0x000000012fbb4b00@puma srv tp 001 /....../puma-6.4.3/lib/puma/thread_pool.rb:113 sleep>. Current thread: #<Thread:0x0000000102ccb0e8 run>`. :(

**Comment by casperisfine** [comment] 2024-09-30 15:33
> should do the trick, right?

Yes.

>  it is still giving ActiveRecord::ActiveRecordError: Cannot expire connection

😢 

That said, https://github.com/rails/rails/pull/53118 definitely fixes a bug, so I'll add some test, merge it and backport it.

But there might be another bug hiding behind... so we'll have to keep investigating. Unfortunately I can't make your repro fail once this is applied, so I might need a new repro. Unless you mean it's still happening in the repro you shared? Or is this error from your real application?

**Comment by fwolfst** [comment] 2024-09-30 15:38
@casperisfine Also, I am not jdelStrother :D , thus its not my repo, you are mixing us. "My" error is from a real application, betterplace.org with git history all the way back to 2006. I _can_ try to extract the minimal failing scenario, but we have a bit of special cruft here and there (but hey, we are on Rails 7.1 and kicking !).

**Comment by casperisfine** [comment] 2024-09-30 15:42
> Also, I am not jdelStrother :D

Arf sorry.

One thing I need to check, is why transactional fixtures are even enabled for system test. IIRC historically they were automatically disabled in that case. With the new connection pinning code it's now possible to make system tests use transactional fixtures, but I don't remember explicitly allowing it.

**Comment by jdelStrother** [comment] 2024-09-30 17:06
> @jdelStrother can you try this branch: #53118 ? I fixes your repro script.

I've monkeypatched it into our rails 7.2 branch, looks good! I no longer see any failures in either the repro script or our real app.

Seems weird that @fwolfst is still seeing issues - I'll leave our testsuite re-running itself overnight to see if I can catch any flakey cases.

**Comment by fwolfst** [comment] 2024-09-30 18:04
Will try to find a minimal, shareable and reproducible issue tomorrow, but cannot guarantee that we'll throw enough time at it.

**Comment by casperisfine** [comment] 2024-09-30 19:12
Thanks @fwolfst , in the meantime disabling transactional fixtures for system tests is definitely the way to go, and probably what I'm gonna make the default once I can confirm was it used to be.

**Comment by byroot** [comment] 2024-09-30 21:14
>  I'll open a separate issue if I do.

Thank you. I'll close this one then.

**Closed by byroot** 2024-09-30 21:14 UTC

**Comment by fwolfst** [comment] 2024-10-01 08:39
@byroot I observe something inverse to other threads in here.
Iff I run a specific test (with line number) like in 
`rspec spec/features/donation/to_ngo_spec.rb:60` the error will be thrown 🔴 .
If I run the whole file like in
`rspec spec/features/donation/to_ngo_spec.rb:60` it works 🟢 (4 test cases in the file).

In both cases, a `puts self.use_transactional_tests` shows me a `true`. I can "fix" the spec run with a single test if I set `use_transactional_tests` to `false` in that test case.

Another way to "fix" this is to not set the `js: true` metadata for the example group (https://github.com/teamcapybara/capybara/blob/0480f90168a40780d1398c75031a255c1819dce8/README.md?plain=1#L178). Not sure if that is reproducible with a vanilla rails+capybara setup, might try later.

**Comment by fwolfst** [comment] 2024-10-02 08:06
@byroot A couple of hundred deleted files later, I managed to pin our issue down to a specific setting in #53147 .
