### ISSUE TITLE
Controller spec failed with 6.0.0.beta2

### ISSUE THREAD

**Issue by kaluznyo** [rails/rails#35417] opened 2019-02-26 09:25 UTC
When I launch my controller spec on my Rails 6.beta2 app we get an error with every spec like this: 

```
    get :mailings
    expect(response.status).to eq(200)
```
We got this error :
 ```
ArgumentError:
     #   wrong number of arguments (given 2, expected 1)
     #   /Users/okaluzny/.rvm/gems/ruby-2.6.1@app/gems/actionview-6.0.0.beta2/lib/action_view/template.rb:325:in `compile'
````

(full backtrace : https://gist.github.com/kaluznyo/0be1125afab16fa615d00ed9446362ae)

In my real app, with server, no error when I go to this page

Don't know if it's related but we also get warning :

DEPRECATION WARNING: formats is deprecated and will be removed from Rails 6.1 (called from block (2 levels) in <top (required)> at /Users/okaluzny/Sites/my_app/spec/controllers/account_controller_spec.rb:172)

But I don't send 'formats' in my request.

### System configuration
**Rails version**:
6.0.0.beta2
**Ruby version**:
2.6.1

**Comment by rafaelfranca** [comment] 2019-02-26 23:22
Can you provide an example application that reproduce the issue?

**Comment by jamesjefferies** [comment] 2019-02-27 11:26
This may be an issue with rspec-rails: https://github.com/rspec/rspec-rails/issues/2086 which references this commit https://github.com/rails/rails/commit/28f88e0074f473f58c2d3fd54cb3daff81027c12#diff-562906215bf781788ec5aaf37e958cb8

**Comment by rafaelfranca** [comment] 2019-02-27 17:25
Thanks. Closing since it is a rspec issue.

**Closed by rafaelfranca** 2019-02-27 17:25 UTC
Labels: more-information-needed

**Comment by jasnow** [comment] 2019-03-22 18:06
Here is the workaround to build Rails 6.0.0.beta3 until rspec-rails gets upgraded.
Replace:
```
gem 'rspec-rails'
```
with
```
  gem 'rspec-rails', git: 'https://github.com/rspec/rspec-rails', branch: '4-0-dev'
  gem 'rspec-core', git: 'https://github.com/rspec/rspec-core'
  gem 'rspec-mocks', git: 'https://github.com/rspec/rspec-mocks'
  gem 'rspec-support', git: 'https://github.com/rspec/rspec-support'
  gem 'rspec-expectations', git: 'https://github.com/rspec/rspec-expectations'
```

**Comment by Arpanbhalla** [comment] 2019-07-17 04:34
@jasnow Thanks I jchecked issue gets fixed with this version `gem 'rspec-rails', '~> 4.0.0.beta2'`

**Comment by NatassiaTavares** [comment] 2019-07-25 11:38
Thanks @Arpanbhalla , saved me many hours

**Comment by rietta** [comment] 2019-08-18 23:12
Thanks @jasnow. This is still an issue with Rails 6.0.0 released on the 15th. Updating my notes accordingly with your workaround.

**Comment by luizpicolo** [comment] 2019-08-22 02:22
Thansk @jasnow
