### ISSUE TITLE
Rails 5.2.3 db:seed doesn't work with `wait_until` job

### ISSUE THREAD

**Issue by vitalinfo** [rails/rails#35862] opened 2019-04-04 20:53 UTC
### Related to theses changes
https://github.com/rails/rails/pull/34953

### Steps to reproduce
- add to any model after create callback where run some job with `wait_until` parameter, like `SomeJob.set(wait_until: Time.utc.end_of_day).perform_later`
- create object of this model in the seed file
- run `rails db:seed`

### Expected behavior
Seed works fine

### Actual behavior
Crash with `NotImplementedError: Use a queueing backend to enqueue jobs in the future.`

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6+

**Comment by rafaelfranca** [comment] 2019-04-04 20:58
Duplicate of #35812

**Closed by rafaelfranca** 2019-04-04 20:58 UTC
