### ISSUE TITLE
Initializing a memcache store with a Dalli client using a namespace behaves differently

### ISSUE THREAD

**Issue by aledustet** [rails/rails#47323] opened 2023-02-08 22:12 UTC
### Steps to reproduce

When a new memcache store is initialized, one of the [options](https://github.com/rails/rails/blob/fad9050d80cb4d2d7c482311832724558bbfbbc2/activesupport/lib/active_support/cache/mem_cache_store.rb#L119) allowed is an already operational client. 
When only the address of the memcache server is provided, a new client is initialized and most options are [prevented](https://github.com/rails/rails/blob/fad9050d80cb4d2d7c482311832724558bbfbbc2/activesupport/lib/active_support/cache/mem_cache_store.rb#L128) from making it's way to the new client.
This is because there are custom [transformations](https://github.com/rails/rails/blob/fad9050d80cb4d2d7c482311832724558bbfbbc2/activesupport/lib/active_support/cache/mem_cache_store.rb#L321) that would be redundant otherwise.
When doing so, we prevent(among other things) the key manager from [truncating](https://github.com/petergoldstein/dalli/blob/1666b93de72d72b52a64b7349cbbb66a1a2af4b5/lib/dalli/key_manager.rb#L50) keys that are longer than the allowed length.
The problem is that when a client is provided, this safeguard is not in place and some surprising behavior can occur, particularly when [reading multiple keys](https://github.com/rails/rails/blob/fad9050d80cb4d2d7c482311832724558bbfbbc2/activesupport/lib/active_support/cache/mem_cache_store.rb#L288).

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activesupport", "~> 7.0.0"
  gem "dalli"
end

require "active_support"
require "minitest/autorun"
require "dalli"

# This test case is a reproduction of the one present on
# rails/activesupport/test/cache/behaviors/cache_store_behavior.rb#708
# It requires a memcached server running on localhost:11211
class MemCacheStoreBugTest < Minitest::Test
  def test_can_use_dalli_client_with_custom_options
    namespace = "custom_namespace"
    dalli_client = Dalli::Client.new("localhost:11211", { namespace: })
    # To reproduce this on a config file it should be initialized as:
    # namespace = "custom_namespace"
    # config.cache_store = :mem_cache_store, [Dalli::Client.new("localhost:11211", { namespace: })], { namespace:, pool: false, socket_timeout: 60 })
    cache = ActiveSupport::Cache.lookup_store(:mem_cache_store, [dalli_client], { namespace:, pool: false, socket_timeout: 60 })
    long_key = SecureRandom.alphanumeric * 2048
    value = "bar"

    assert cache.write(long_key, value)
    # The lookup will succeed, since we write using the same mechanism.
    # it is [documented](https://guides.rubyonrails.org/caching_with_rails.html#cache-keys) that
    # a dalli client should not be used to read directly any keys written by rails
    assert_equal value, cache.fetch(long_key)
    # The issue occurs because the key length is precisely 250 characters
    # on activesupport's side, when Dalli attempts to add the namespace
    # it was initialized with, the key length exceeds 250 characters, kicking
    # of a [truncation](https://github.com/petergoldstein/dalli/blob/1666b93de72d72b52a64b7349cbbb66a1a2af4b5/lib/dalli/key_manager.rb#L54)
    # process on Dalli that will prevent the matching on the `read_multi`
    # method to map the normalized key with the response.
    assert_equal({ long_key => value }, cache.read_multi(long_key))
  end

  def test_can_use_dalli_client_without_custom_options
    namespace = "custom_namespace"
    dalli_client = Dalli::Client.new("localhost:11211")
    cache = ActiveSupport::Cache.lookup_store(:mem_cache_store, [dalli_client], { namespace:, pool: false, socket_timeout: 60 })
    long_key = SecureRandom.alphanumeric * 2048
    value = "bar"

    assert cache.write(long_key, value)
    assert_equal value, cache.fetch(long_key)
    assert_equal({ long_key => value }, cache.read_multi(long_key))
  end
end
```

### Expected behavior

Lookups for an existing key that are a cache hit when using `fetch`/`read` should be returned in the same `key => value` pair when using `read_multi`

Too fix it we can reverse the lookup of the key when `read_multi` is invoked. I have an [example](https://github.com/aledustet/rails/pull/1/files) on how it could look. Refrained from opening a PR because I would like to make sure this is a worthwhile effort. 

Depending on how critical this feature is, I feel we could explore a couple of solutions. FWIW the behavior seems to have been around for quite a while and I couldn't find any issues mentioning specifically.

1. Deprecate the feature of initializing with a Dalli client. I'm not sure what use-case is serving the ability of providing an instance of a client. It is not documented on the guides that it can/should be done, but there is a [reference](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-memcachestore) to the Dalli client documentation that mentions that the namespace can be overriden.

2. Add a warning whenever a Dalli client is added, mentioning that keys longer than the max character limit will not be returned when reading multiple entries.

3. Have a [workaround](https://github.com/aledustet/rails/pull/1/files) on the `read_multi` invocation when the dalli client includes a namespace. For that example there is some surprising behavior when looking up multiple keys, the namespace is [dropped](https://github.com/petergoldstein/dalli/blob/88614e8c9ed63c92bff18da94830fd1e30782099/lib/dalli/pipelined_getter.rb#L139) 🤔  

4. This is a very very niche bug and documenting it here is enough 😄 

Delegating namespace management to the Dalli client should not be considered, given that there are custom transformations for encoding, types of the keys that can be used and others that are present on the rails implementation and not on Dalli's, also the usage of the client should remain an [implementation detail](https://github.com/rails/rails/issues/21595#issuecomment-139815433).

### Actual behavior

Lookups for an existing key that are a cache hit when using `fetch`/`read` are returned in a hash where every key is nil when using `read_multi`, and the key is over 250 characters long when the `Dalli` client has a custom namespace.

### System configuration
**Rails version**:

rails 7.0.4 
But can be reproduced on main and at least down to v6.0

**Ruby version**:

ruby 3.2.0

**Comment by jamiemccarthy** [comment] 2023-02-09 04:44
Pinging @petergoldstein on this interesting PR. I'm not familiar enough (yet) with how Dalli's process_server works to have an informed opinion, but in particular the claim in point 3 above may be worth looking into.

**Comment by aledustet** [comment] 2023-02-09 14:16
Thanks @jamiemccarthy I think dalli might be a better place to add a fix, after noodling a bit more I think a good strategy would be to patch `Dalli::PipelinedGetter` to use a similar [mechanism](https://github.com/rails/rails/blob/fad9050d80cb4d2d7c482311832724558bbfbbc2/activesupport/lib/active_support/cache/mem_cache_store.rb#L291) than active support does when remapping the keys to offer a response `echoing` the same keys regardless of size limits.

**Comment by petergoldstein** [comment] 2023-02-09 14:37
Hi, I'm the primary `dalli` maintainer.

From my perspective it's unclear why the MemCacheStore provides the option of passing in a `Dalli::Client`.  It enables a number of potential errors - threading issues, external access to cache key/values, etc. - that would otherwise be impossible. So I'd definitely recommend deprecate passing in a client instance, regardless of this issue.

Re: 3, this seems to be a misunderstanding of the code.  The referenced line refers to the keys and values that have already been retrieved from `memcached`.  In a pipelined getter they key value is retrieved from the memcached response, memcached only knows about the key that includes the namespace, and there's a need to do a reverse mapping to the original user-provided key.

So yes, the namespace (which is added to the user provided key by the Dalli client) is being stripped here, but only to give the originally provided key - it is intended behavior.

This is known to work badly with truncation, for the obvious reasons.  If memcached only knows about the truncated key, then it's not possible to generate the original (untruncated) user key, and you get a truncated value in the return map.  The original, untruncated key is "missing" from the return map.  It's probably worth documenting that on the wiki.

It would probably be possible to do something like the `ActiveSupport` mechanism, but it has a number of downsides for the  typical `Dalli` case.  A typical use case for the `get_multi` and `get_multi_cas` is at least tens of thousands, and more commonly hundreds of thousands or millions of keys.  There is a premium on efficiency, and I'm not sure what the performance impact would be.  If you'd like to submit a PR to `Dalli` I'll take a look.

**Comment by aledustet** [comment] 2023-02-09 14:45
@petergoldstein Thank you so much for your thorough response 🙏 
I am more inclined to the deprecation route and to your point about `It enables a number of potential errors - threading issues, external access to cache key/values, etc.` another example is compression, `activesupport` would be duplicating compression on a client with the `compress` flag enabled.

> Re: 3, this seems to be a misunderstanding of the code. 
💯

> is at least tens of thousands, and more commonly hundreds of thousands or millions of keys.
Amazing context! I'll attempt to add this functionality but not without at least some benchmarking tests. Will probably be best to add a clarification on the wiki to start, noting the behavior on larger keys and `get_multi{_cas}` behavior.

Very energizing to read your response I'm really pumped to see this through now 🎉 🎉 🎉

**Comment by aledustet** [comment] 2023-02-10 22:21
Updated the [wiki](https://github.com/petergoldstein/dalli/wiki/Using-Dalli-with-Rails) 👍

**Comment by ghiculescu** [comment] 2023-05-26 03:27
Fixed in https://github.com/rails/rails/pull/47340

**Closed by ghiculescu** 2023-05-26 03:27 UTC
Labels: activesupport, attached PR
