### ISSUE TITLE
Rails 5.0.0.beta4 - Cannot customize scaffold templates

### ISSUE THREAD

**Issue by Joshfindit** [rails/rails#24774] opened 2016-04-28 16:33 UTC
### Steps to reproduce

Either: 
* create templates at `lib/templates/erb/scaffold/` (this location is suggested elsewhere and works pre-5)
* modify or replace the templates at `<GEM LOCATION>/gems/railties-5.0.0.beta4/lib/rails/generators/erb/scaffold/templates`

Then run `rails generate scaffold Class name:string`

### Expected behaviour
Rails generates the Models, Views, Controllers, etc based on the modified templates

### Actual behaviour
Rails completely ignores the modified templates, and generates bare-bones

### System configuration
**Rails version**: `Rails 5.0.0.beta4`

**Ruby version**: `ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]`

**Comment by vipulnsward** [comment] 2016-04-28 19:24
Can you create a sample App demonstrating this behaviour?

**Comment by Joshfindit** [comment] 2016-04-28 20:39
Alright; I have a feeling that this was a reasonable request designed to uncover the root of the problem.

I spun up a fresh machine, installed rails, copied the templates to `lib/templates/erb/scaffold/`, and ran `rails generate scaffold Class name:string`, and it worked; changes were carried through to the generated view.


What troubleshooting steps are suggested to track this down on the machine with the issue?
On that machine, Rails 5 was installed as an RVM gemset (loosely following http://railsapps.github.io/updating-rails.html )

**Comment by rafaelfranca** [comment] 2016-04-28 20:52
If you are using spring try to stop spring after the template is added.

Closing since it can't be reproduced in a new application.

**Closed by rafaelfranca** 2016-04-28 20:52 UTC
Labels: railties

**Comment by Joshfindit** [comment] 2016-04-29 01:07
Disabled spring, restarted, and it now works as expected.

Cheers

**Comment by grantzau** [comment] 2017-03-08 14:43
Same here. `bin/spring stop` and run the `rails generate ...` command again.

**Comment by Tashows** [comment] 2018-03-22 17:18
That happened to me as well in a Rails 4.2 app. Stoping spring solved the issue for the views part, however the controller is still being ignored.
