### ISSUE TITLE
form_for documentation needs to be updated.

### ISSUE THREAD

**Issue by jpstokes** [rails/rails#26671] opened 2016-09-30 15:07 UTC
### Steps to reproduce
Using form_for does not automatically enable multipart as suggested by documentation when form object isn't being used to implement file_field and file_field_tag - i.e. not using f.file_field.

```
<%= form_for @person do |f| %>
  <%= file_field :picture %>
<% end %>

<%= form_for @person do |f| %>
  <%= file_field_tag :picture %>
<% end %>
```

### Expected behavior
Expected form_for to automatically set multipart => true.

### Actual behavior
multipart => true was not set and had to set manually contrary to  the documentation

http://guides.rubyonrails.org/form_helpers.html (Section 5 Uploading Files)

### System configuration
Rails 4.1.5

Ruby 2.2.4

**Comment by mechanicles** [comment] 2016-10-01 14:13
@jpstokes Not sure how you are actually implementing it.

Automation of multipart will work only with `form_for` and using its `file_field` helper. i.e. `f.file_field`
```
<%= form_for @person do |f| %>
  <%= f.file_field :picture %>
<% end %>
```
Above code should add/set multipart in the form.

But in your example of `form_for`, you haven't used form builder object for `file_field` helper. Please change it `file_field :picture` to `f.file_field :picture` and let us know.

It looks like that you are not using helpers properly. `filed_field`  & `file_field_tag` both are different. Please check Rails guide to know more about their usages.

**Comment by maclover7** [comment] 2016-10-06 22:20
Hi @jpstokes! Agree with @mechanicles -- in order for certain features to be activated within forms, you need to call the tag helper methods on the `f` variable. Closing out this issue as expected behavior.

**Closed by maclover7** 2016-10-06 22:20 UTC
