### ISSUE TITLE
undefined method 'clear' for nil:NilClass in actionpack-4.2.0/lib/action_controller/test_case.rb

### ISSUE THREAD

**Issue by nPn-** [rails/rails#18285] opened 2015-01-01 15:07 UTC
In some rspec before(:all) blocks it seems like the setup_subscriptions method in this file is not being called, resulting in the a nil instance_variable when reset_template_assertion is called.

more info can be found in this stackoverflow question

http://stackoverflow.com/questions/27727786/rails-4-2-update-method-fails-only-when-called-from-beforeall-block

    def reset_template_assertion
      RENDER_TEMPLATE_INSTANCE_VARIABLES.each do |instance_variable|
        instance_variable_get("@_#{instance_variable}").clear
      end
    end

for now I just added a check to make sure the variable is not nil before calling clear on it, but I am not sure if the problem is that the setup_subsriptions __should__ have been call and was not.

    def reset_template_assertion
      RENDER_TEMPLATE_INSTANCE_VARIABLES.each do |instance_variable|
        variable_name = "@_#{instance_variable}"
        variable = instance_variable_get(variable_name)
        variable.clear if variable
      end
    end

**Comment by al2o3cr** [comment] 2015-01-01 16:34
The methods in question appear to have been added to fix #16119. `setup_subscriptions` is registered as as a setup method [here](https://github.com/rails/rails/blob/2910956fc9006d3c26f56992dab630fa97b7f7bc/actionpack/lib/action_controller/test_case.rb#L14), but I believe `before(:all)` is going to run prior to that code executing.

Out of curiosity, how was this working before? I would have thought the user created by the call in `before(:all)` would be lost when the database was reset between specs...

**Comment by sgrif** [comment] 2015-01-01 17:06
@al2o3cr It would have worked if it was using transactional fixtures.

**Comment by nPn-** [comment] 2015-01-01 17:12
Yes that must be why it was working,  at some point I started using database_cleaner and needed to set 
config.use_transactional_fixtures = true

maybe I should move away from that?

**Comment by sgrif** [comment] 2015-01-01 17:13
If you're using database cleaner, you would need to turn transactional fixtures off. You'd also want to move data created in `before(:all)` to `before(:each)`.

**Comment by sgrif** [comment] 2015-01-01 17:14
@nPn- Is your app using `active_model_serializers`?

**Comment by nPn-** [comment] 2015-01-01 17:17
@sgrif   I don't think so, I just checked for that string in my project folder and it was not found, do you know which file it would be in?

**Comment by sgrif** [comment] 2015-01-01 17:17
It'd be in your Gemfile. My hunch is that this is actually https://github.com/rails-api/active_model_serializers/issues/766, not an issue in Rails.

**Comment by sgrif** [comment] 2015-01-01 17:22
If you add `p method(:process).source_location` above this line: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L64, it should tell you which gem is causing the problem for you.

**Comment by nPn-** [comment] 2015-01-01 17:39
It now looks like this:  but I did not get a "here" or anything from the p .  not sure why

**Comment by sgrif** [comment] 2015-01-01 17:40
Ping @brandonhilkert can you help us track down which gem this is coming from?

**Comment by brandonhilkert** [comment] 2015-01-01 18:24
@nPn- if it blows up prior to getting the output, it's because the `process` method in another gem is being hit prior to the one in Rails (`super`) throwing the exception. Can you post your `Gemfile`?

**Comment by nPn-** [comment] 2015-01-01 19:35
Sorry for the delay ...

Here is my current Gemfile : 
source 'https://rubygems.org'
ruby '2.0.0'
#ruby-gemset=railstutorial_rails_4_0

# gem 'rails', '~>4.1.0'
gem 'rails', '~>4.2.0'
gem 'bootstrap-sass', '2.3.2.0'
gem 'bcrypt-ruby', '3.1.2'
gem 'faker', '1.1.2'
gem 'will_paginate', '3.0.4'
gem 'bootstrap-will_paginate', '0.0.9'
gem 'sprockets', '2.11.0'
gem 'pg', '0.15.1'
gem 'responders', '~> 2.0'

## added for google maps
gem 'jquery-turbolinks'
# gem 'gmaps4rails'
gem 'gmapsjs-rails'
##

gem 'rest_client'   

gem "puma"
gem "gcm"
gem "geocoder"

gem "figaro"

# gem "pg_search"

group :development, :test do
  
  #gem 'sqlite3', '1.3.8'
   gem 'guard', '= 2.7.3'
   # gem 'rspec-rails', '~>2.14.0'
   gem 'rspec-rails', '~>3.1.0'
  # The following optional lines are part of the advanced setup.
   gem 'guard-rspec' #, '2.5.0'
   gem 'spork-rails', '4.0.0'
   gem 'guard-spork', '1.5.0'
   gem 'childprocess', '0.3.6'
   gem "teaspoon"
 #  gem "phantomjs-binaries"
 #  gem "phantomjs.rb"
end

group :test do
  gem 'selenium-webdriver', '2.35.1'
  gem 'capybara' #, '2.1.0'
  gem 'factory_girl_rails', '4.2.0'
  gem 'cucumber-rails', '1.3.0', :require => false
  gem 'database_cleaner', github: 'bmabey/database_cleaner'

  # Uncomment this line on OS X.
  #gem 'growl', '1.0.3'

  # Uncomment these lines on Linux.
  gem 'libnotify', '0.8.0'

  #Uncomment these lines on Windows.
  #gem 'rb-notifu', '0.0.4'
  #gem 'win32console', '1.3.2'
  #gem 'wdm', '0.1.0'
end

gem 'sass-rails', '4.0.1'
gem 'uglifier', '2.1.1'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.0.4'
gem 'jquery-ui-rails', '4.2.1'
gem 'turbolinks', '~> 2.3.0'
# gem 'turbolinks', '1.1.1'
gem 'jbuilder', '1.0.2'

group :doc do
  gem 'sdoc', '0.3.20', require: false
end

group :production do
  gem 'unicorn'
  #gem 'pg', '0.15.1'
  gem 'rails_12factor', '0.0.2'
end

**Comment by brandonhilkert** [comment] 2015-01-01 19:57
@nPn- I looked at a few I wasn't as familiar with and nothing sticks out to me. Unfortunately, the next step would be to comment each out, bundle, and then start the app to see if it works. 

On a side note, you have quite a few in the `developer` and `test` group. Do you know if you get the error when running the app in `production`. Might be a good first step to see if the offending gem is in that group. At least it'll point you in the right direction.

**Comment by sgrif** [comment] 2015-01-01 19:58
Thanks @brandonhilkert. I'm going to close the issue, since it's almost certainly not a Rails bug. If you are able to reproduce with a new Rails app, please do reopen.

**Comment by nPn-** [comment] 2015-01-01 19:59
thanks for the help!  and happy new year!

**Comment by al2o3cr** [comment] 2015-01-01 22:18
This is trivially reproducible in a blank application. [For instance](https://github.com/al2o3cr/request_spec_demo). Performing a `get` inside a `before(:all)` block works on 4.1.8, fails on 4.2.0.

Does anybody know why `clear` is preferable here to just resetting the instance variables to a known value? Something like:
```ruby
    def reset_template_assertion
      RENDER_TEMPLATE_INSTANCE_VARIABLES.each do |instance_variable|
        instance_variable_set("@_#{instance_variable}", Hash.new(0))
      end
    end
```

The new `reset_template_assertion` could also be reused and replace the code [here](https://github.com/rails/rails/blob/2910956fc9006d3c26f56992dab630fa97b7f7bc/actionpack/lib/action_controller/test_case.rb#L21) that initially sets the variables.

**Comment by brainopia** [comment] 2015-01-02 12:45
@al2o3cr I've used a different fix to the one you've asked about. There is no need to setup template variables if we can't control their time-to-live with teardown callback. Especially if we take into account that relevant ActiveSupport::Notifications also need to be setup and teardown.

Since you won't use rspec expectations outside of an actual test, the methods like `#get`, `#post` are needed there only to setup a context (cookies, session) and we can simply ignore template stuff until there is something to clear.

**Closed** 2015-01-02 13:59 UTC
Labels: actionpack
