### ISSUE TITLE
Actionview Test failing: DateHelperSelectTagsI18nTests#test_select_month_with_frozen_month_names

### ISSUE THREAD

**Issue by pvalena** [rails/rails#46130] opened 2022-09-26 13:56 UTC
### Steps to reproduce

While running tests for Fedora, during a package build, we've encountered a test error.

Tests is executed like so:

```
ruby -Itest -- 'test/template/date_helper_i18n_test.rb'
```

### Actual behavior

* Test file: test/template/date_helper_i18n_test.rb

```
Running 13 tests in a single process (parallelization threshold is 50)
Run options: --seed 35591

# Running:

......E

Error:
DateHelperSelectTagsI18nTests#test_select_month_with_frozen_month_names:
ArgumentError: mocked method :call expects 2 arguments, got [:"date.month_names"]
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:907:in `translated_month_names'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:890:in `month_names'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:962:in `month_name'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:830:in `block in select_month'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:827:in `upto'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:827:in `select_month'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:639:in `select_month'
    test/template/date_helper_i18n_test.rb:121:in `block in test_select_month_with_frozen_month_names'
    /usr/share/gems/gems/activesupport-7.0.4/lib/active_support/testing/method_call_assertions.rb:24:in `assert_called_with'
    test/template/date_helper_i18n_test.rb:120:in `test_select_month_with_frozen_month_names'

rails test test/template/date_helper_i18n_test.rb:117
```

### System configuration
**Rails version**:
7.0.4

**Ruby version**:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by yahonda** [comment] 2022-09-26 15:03
This failure can be addressed by running tests using bundler.

```
bundle install
bundle exec ruby -Itest -- 'test/template/date_helper_i18n_test.rb'
```

**Comment by ghiculescu** [comment] 2022-10-20 16:21
Closing as it seems like it's not an issue ^
Happy to reopen if there are any other issues here.

**Closed by ghiculescu** 2022-10-20 16:21 UTC

**Comment by thesamesam** [comment] 2023-04-05 07:46
@pvalena I'm pretty sure the issue is that the minitest patches you've backported need to be adapted a bit for a test which was committed upstream _after_ the minitest patches, which means the version of the test that got committed to master is different to the one on release-7-0.

Try:
```diff
Commit on master adding test_select_month_with_frozen_month_names: https://github.com/rails/rails/commit/60ca482cf0da9a628655532ffaa8a5598c351a80
Commit on release-7-0 adding test_select_month_with_frozen_month_names: https://github.com/rails/rails/commit/b3e79be9c6f13b2b2908d1022d24b2188ff7ece3

The release-7-0 version drops the minitest bits which upstream haven't backported, but we are (as are Fedora).

https://github.com/rails/rails/issues/46130
--- a/test/template/date_helper_i18n_test.rb
+++ b/test/template/date_helper_i18n_test.rb
@@ -115,11 +115,15 @@ def test_select_month_given_use_short_month_option_translates_abbr_monthnames
   end
 
   def test_select_month_with_frozen_month_names
-    month_names = Date::MONTHNAMES.dup.drop(1).freeze
+    month_names = Date::MONTHNAMES.dup.drop(1)
+    mock = Minitest::Mock.new
+    expect_called_with(mock, [:'date.month_names'], locale: "en", returns: month_names.freeze)
 
-    assert_called_with(I18n, :translate, [:'date.month_names', locale: "en"], returns: month_names) do
+    I18n.stub(:translate, mock) do
       select_month(8, locale: "en")
     end
+
+    assert_mock(mock)
   end
 
   # date_or_time_select
```
