### ISSUE TITLE
Order of "manual" joins messed up when using .merge

### ISSUE THREAD

**Issue by tbreier** [rails/rails#24281] opened 2016-03-22 21:48 UTC
When using a JOIN like `.joins('INNER JOIN posts ON users.id = posts.user_id')` instead of `.joins(:posts)`, and then using `.merge` with a relation with another JOIN defined on (in this case) `posts`, the JOIN with that other table gets put in the front, which is not something that MySQL is happy about.

This description is probably a bit confusing, but I hope the gist makes clear what I mean (see below).
### Steps to reproduce

See https://gist.github.com/tbreier/e388c3f4727f985126a1
### Expected behavior

.merge works when the scope to be merged with a) is joined manually (not via symbol describing association) and b) contains a join with another table
### Actual behavior

The gist above crashes.

```
# Running:

SELECT `users`.* FROM `users` INNER JOIN `posts` ON `posts`.`user_id` = `users`.`id` LEFT OUTER JOIN `comments` ON `comments`.`post_id` = `posts`.`id`
SELECT `users`.* FROM `users` LEFT OUTER JOIN `comments` ON `comments`.`post_id` = `posts`.`id` INNER JOIN posts ON users.id = posts.user_id
D, [2016-03-22T14:38:34.101618 #5326] DEBUG -- :   User Load (0.6ms)  SELECT `users`.* FROM `users` INNER JOIN `posts` ON `posts`.`user_id` = `users`.`id` LEFT OUTER JOIN `comments` ON `comments`.`post_id` = `posts`.`id`
D, [2016-03-22T14:38:34.108212 #5326] DEBUG -- :   User Load (0.6ms)  SELECT `users`.* FROM `users` LEFT OUTER JOIN `comments` ON `comments`.`post_id` = `posts`.`id` INNER JOIN posts ON users.id = posts.user_id
E

Finished in 0.025738s, 38.8537 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'posts.id' in 'on clause': SELECT `users`.* FROM `users` LEFT OUTER JOIN `comments` ON `comments`.`post_id` = `posts`.`id` INNER JOIN posts ON users.id = posts.user_id
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mysql2-0.4.3/lib/mysql2/client.rb:107:in `_query'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mysql2-0.4.3/lib/mysql2/client.rb:107:in `block in query'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mysql2-0.4.3/lib/mysql2/client.rb:106:in `handle_interrupt'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mysql2-0.4.3/lib/mysql2/client.rb:106:in `query'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `exec_query'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/querying.rb:39:in `find_by_sql'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation.rb:639:in `exec_queries'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation.rb:515:in `load'
    /Users/tms/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation.rb:243:in `to_a'
    merge_join.rb:63:in `test_association_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```
### System configuration

ActiveRecord 4.2.6, mysql2 0.4.3, MySQL 5.6.27, Ruby 2.1.2

By the way, I am curious behind the rationale of converting joins contained in the scope to be merged to a  `LEFT OUTER JOIN`. This appears to be intended, as described in #16140.

**Comment by sevaorlov** [comment] 2016-05-07 17:04
Not sure what is the reason, but it seems by design Rails converts inner joins to outer joins when merging.
https://github.com/rails/rails/blob/fix/joins-in-association-conditions/activerecord/lib/active_record/relation/merger.rb#L122

then these joins are called 'stashed' here https://github.com/rails/rails/blob/fix/joins-in-association-conditions/activerecord/lib/active_record/relation/query_methods.rb#L1044 and passed as outer joins here https://github.com/rails/rails/blob/fix/joins-in-association-conditions/activerecord/lib/active_record/relation/query_methods.rb#L1071
https://github.com/rails/rails/blob/fix/joins-in-association-conditions/activerecord/lib/active_record/associations/join_dependency.rb#L106

Can someone from Rails team give feedback about this?

**Comment by sevaorlov** [comment] 2016-05-07 17:07
Not sure what is the reason, but it seems by design Rails converts inner joins to outer joins when merging.
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/merger.rb#L122

then these joins are called 'stashed' here https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L1050 and passed as outer joins here https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L1077
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/join_dependency.rb#L106

Can someone from Rails team give feedback about this?

**Comment by maclover7** [comment] 2016-05-07 17:11
cc @sgrif, assigning to you so it doesn't get lost while you are 🚗  to Canda -- r? @sgrif

**Comment by thedarkone** [comment] 2016-05-20 14:10
I have #15461 that attempts to fix this. The PR is a bit stale now, but I'll try to look into it really soon.

**Comment by oyeanuj** [comment] 2016-07-10 21:55
@sgrif @thedarkone Any updates here?

**Comment by thedarkone** [comment] 2016-07-10 22:30
I will not be able to work on my PR until after 22nd.

**Comment by MaxLap** [comment] 2016-08-14 21:54
I think the "left_outer_joins" method also needs to be taken into consideration. 

Right now, it is treated as a distinct list of values from the joins_values, so it's impossible to keep the order. The merge of associations also doesn't treat the left_joins the same as the regular joins.

**Comment by tibbon** [comment] 2018-07-23 18:21
Any updates on this one?

**Comment by MaxLap** [comment] 2018-07-23 19:34
Shameless plug: I made a gem to do conditions on associations without using `JOIN`. It uses `EXISTS`, which avoids lots issues from `JOIN`, including this issue here. (unless you are using `JOIN` for some other use than filtering)

You can read about all of the issues with the alternatives here: [activerecord_where_assoc - ALTERNATIVES_PROBLEMS](https://github.com/MaxLap/activerecord_where_assoc/blob/master/ALTERNATIVES_PROBLEMS.md)

This is the gem: [activerecord_where_assoc](https://github.com/MaxLap/activerecord_where_assoc)

**Comment by chumakoff** [comment] 2018-08-24 11:02
For those who has the same problem there is a workaround:
 
```
    users_with_posts = User.joins('INNER JOIN posts ON users.id = posts.user_id')
    posts_with_comments = Post.joins(:comments)

    User.joins(users_with_posts.join_sources).joins(posts_with_comments.join_sources)
```

**Closed** 2019-07-30 03:39 UTC
Labels: With reproduction steps, activerecord
