### ISSUE TITLE
Rails autoloader/zeitwerk not loading files correctly on application boot

### ISSUE THREAD

**Issue by christopherdbull** [rails/rails#44881] opened 2022-04-12 17:27 UTC
### Steps to reproduce
Since upgrading from 6.0 to ~7.0 my rails application won't boot due to constant autoloading failure.

The Constant in question is a file defined below, living at `app/adapters/content_api/http_client.rb`
```ruby
module ContentApi
  class HttpClient
  end
end
```

### Expected behavior
The file should be autoloaded correctly such that when referenced in environment configuration doesn't crash 
`config.x.adapters.content_api = ContentApi::HttpClient`. This was the behaviour under 6.0
### Actual behavior
System crashes as the constant hasn't been correctly loaded

```
rails aborted!
NameError: uninitialized constant ContentApi
```

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 2.7.3

**Comment by SkipKayhil** [comment] 2022-04-13 03:59
Hey @christopherdbull, do you have a public repo where you could reproduce this issue? Without seeing the whole context it's hard to know for sure what is going wrong. My best guess is that you don't have a `app/adapters/content_api.rb` file defining the `ContentApi` module, which would be required for Zeitwerk.

**Comment by eugeneius** [comment] 2022-04-13 10:19
Note that Zeitwerk will "autovivify" the `ContentApi` module, there's no need to define it explicitly:

https://github.com/fxn/zeitwerk#implicit-namespaces

But yes, we can't do much here without a sample application demonstrating the problem.

**Comment by SkipKayhil** [comment] 2022-04-13 15:56
> Note that Zeitwerk will "autovivify" the `ContentApi` module, there's no need to define it explicitly:
> 
> https://github.com/fxn/zeitwerk#implicit-namespaces

Thank you for the correction and the link, I tried to find that in the Rails guides but couldn't.

> Sorry, have put together an example here: https://github.com/christopherdbull/zeit-test
> 
> This is a barebones install with one new 'adapter' added, and then referenced in the `development` environment config. If you try and run anything it will crash on init.

I believe it is intended that you can't autoload in `config/environments/*.rb`, and you should have seen warnings about this in 6.0 (with `zeitwerk` enabled): https://github.com/rails/rails/issues/40904#issuecomment-752230159

There are some good suggestions for handling different ways of loading in the [guides here](https://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots). I'm going to close this for now, but feel free to reopen if things still aren't working

**Closed by SkipKayhil** 2022-04-13 15:56 UTC
Labels: autoloading

**Comment by christopherdbull** [comment] 2022-04-13 16:02
Thanks, I'll try this. We didn't enable zeitwerk in 6.0 as didn't see the benefit to our project.
