### ISSUE TITLE
Unexpected behavior with empty VERSION parameter

### ISSUE THREAD

**Issue by quantumlicht** [rails/rails#28359] opened 2017-03-09 16:42 UTC
### Steps to reproduce
With pending migration files,
run `RAILS_ENV=production bundle exec rake db:migrate VERSION= `
This was the result of mistakenly copy pasting an empty line that contained a whitespace. (It may also have contained a newline  character). 
### Expected behavior
The migration should not be executed or should report a malformed version.

### Actual behavior
Migration was rollbacked and then executed as expected by looking at this code:
https://github.com/rails/rails/blob/f47b4236e089b07cb683ee9b7ff8b06111a0ec10/activerecord/lib/active_record/railties/databases.rake#L63

### System configuration
**Rails version**:
4.2.3

**Ruby version**:
2.1.5

### Possible explanations.
I am by no means a rake expert, but it seems like the check at this line: 
https://github.com/rails/rails/blob/f47b4236e089b07cb683ee9b7ff8b06111a0ec10/activerecord/lib/active_record/railties/databases.rake#L86 fails when we pass in an empty string. Namely,
`" ".to_i == 0 `

**Comment by musicmage4114** [comment] 2017-03-17 17:06
This is actually the expected behavior. The only values in Ruby that return "false" are `false` and `nil`; all other values, including an empty string `""` and `0`, are "truthy" and return "true".

So the line you linked reads "if `"" == true` (it does), then convert that string to an integer (which ends up being `0`) and assign it to `version`.

So on the next line, `version == 0`, or more importantly, `version != false`, and an exception is not raised.

All that being said, I'm not sure if this is the _intended_ behavior or not.

**Comment by maclover7** [comment] 2017-03-19 01:47
@quantumlicht Can you submit a PR to change this to check for `empty?` for similar on `ENV['VERSION']`? I believe this behavior also affects other Rake tasks -- would be great if those could be fixed as well.

**Comment by quantumlicht** [comment] 2017-03-19 21:58
Sure I will give it a go!

**Comment by quantumlicht** [comment] 2017-03-19 22:16
Yes, it will be my pleasure to submit a PR. Can you point me to which file I should write the test in? It's my first submission, so still unfamiliar with the codebase.

**Comment by maclover7** [comment] 2017-03-19 22:21
@quantumlicht I'd say probably in [this file](https://github.com/rails/rails/blob/master/activerecord/test/cases/tasks/database_tasks_test.rb)

**Comment by quantumlicht** [comment] 2017-03-20 18:36
I think I found what I was looking for in railties/test/application/rake/migrations_test.rb
I will fix/add to those tests to make sure my PR is passing all tests

**Closed** 2017-03-27 21:07 UTC
Labels: activerecord, attached PR
