### ISSUE TITLE
TypeError: can't quote Hash when a column name has a table name

### ISSUE THREAD

**Issue by parrish** [rails/rails#29700] opened 2017-07-06 19:21 UTC
### Steps to reproduce

A model has an association with a non-inferred class name that is also the name of an attribute.  A join query tries to query the column rather than the table.

``` ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "5.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :people, force: true do |t|
    t.string :tags, array: true
  end
  create_table :tags do |t|
    t.belongs_to :person
  end
end

class Person < ActiveRecord::Base
  has_many :nicknames, class_name: "Tag"
end

class Tag < ActiveRecord::Base
  belongs_to :person
end

class BugTest < Minitest::Test
  def test_column_join_names
    Person.joins(:nicknames).where(tags: { id: 1 }).to_sql
  end
end
```

### Expected behavior
A valid query should be produced, in this case: `SELECT "people".* FROM "people" INNER JOIN "tags" ON "tags"."person_id" = "people"."id" WHERE "tags"."id" = 1`

### Actual behavior
An error is raised: `TypeError: can't quote Hash`

### System configuration
**Rails version**:
Any >= 5.1.0

**Ruby version**:
Any >= 2.2.3

**Comment by matthewd** [comment] 2017-07-08 17:44
Thanks for the report! While your test schema looks slightly different, I'm pretty sure this is a duplicate of https://github.com/rails/rails/issues/29045, so I'll close it for now.

**Closed by matthewd** 2017-07-08 17:44 UTC
