### ISSUE TITLE
bin/dev fails when attempting to run with bun

### ISSUE THREAD

**Issue by TheAssailant** [rails/rails#50575] opened 2024-01-04 07:04 UTC
### Steps to reproduce
1. Run `rails new new-test-app --javascript bun --css bootstrap`
2. Attempt to run `bin/dev`
3. The CSS thread will exit with an error: `[nodemon] failed to start process, ""bun" exec not found`

Confirmed on both macOS Sonoma and Win11 under WSL2.

### Expected behavior
`bin/dev` should run the server with CSS and JS watchers

### Actual behavior
Server fails to start up. Editing the `watch:css` line in `package.json` to use single quotes instead of escaped double quotes fixes this issue.

```
    "watch:css": "nodemon --watch ./app/assets/stylesheets/ --ext scss --exec 'bun run build:css'"
```

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**Comment by bparanj** [comment] 2024-01-04 14:09
Seems like bun is either not installed on your machine or is not setup properly. Check the version:

```
bun --version
```

Please see: https://stackoverflow.com/questions/72902668/bun-not-found-after-running-installation-script for troubleshooting your issue.

**Comment by TheAssailant** [comment] 2024-01-04 20:11
Bun is installed and set up correctly. Swapping command for whoami also produces an error.

```
    "watch:css": "nodemon --watch ./app/assets/stylesheets/ --ext scss --exec \\\"whoami && exit 0\\\""
```

```
15:05:12 css.1  | [nodemon] starting `"whoami`
15:05:12 css.1  | sh: -c: line 0: unexpected EOF while looking for matching `"'
15:05:12 css.1  | sh: -c: line 1: syntax error: unexpected end of file
15:05:12 css.1  | [nodemon] process failed, unhandled exit code (2)
15:05:12 css.1  | [nodemon] 
15:05:12 css.1  | [nodemon] Either the command has a syntax error,
15:05:12 css.1  | [nodemon] or it is exiting with reserved code 2.
15:05:12 css.1  | [nodemon] 
15:05:12 css.1  | [nodemon] To keep nodemon running even after a code 2,
15:05:12 css.1  | [nodemon] add this to the end of your command: || exit 1
15:05:12 css.1  | [nodemon] 
15:05:12 css.1  | [nodemon] Read more here: https://git.io/fNOAG
15:05:12 css.1  | [nodemon] 
15:05:12 css.1  | [nodemon] nodemon will stop now so that you can fix the command.
```

The issue seems to be the `\\\"` escape sequence. Replacing with either `'` or `\"` works.
```
    "watch:css": "nodemon --watch ./app/assets/stylesheets/ --ext scss --exec \"bun run build:css\""
```

**Comment by skipkayhil** [comment] 2024-01-04 20:32
I'm going to close as a duplicate of rails/cssbundling-rails#137. Let's move the discussion over there (and PRs to cssbundling-rails are welcome of course)

**Closed by skipkayhil** 2024-01-04 20:32 UTC
