### ISSUE TITLE
non-rails project now throws "uninitialized constant #<Class:ActiveSupport::Delegation>::Inflector"

### ISSUE THREAD

**Issue by patrick99e99** [rails/rails#52811] opened 2024-09-05 22:06 UTC
### Steps to reproduce
* create a gem
* add `s.add_development_dependency 'factory_bot'` to gemspec (version 6.4.6 is installed for me)
* add spec_helper file with `require 'factory_bot'

### Expected behavior
it should work

### Actual behavior
```
An error occurred while loading ./spec/lib/my_gem/my_spec.rb.
Failure/Error: require 'factory_bot'

NameError:
  uninitialized constant #<Class:ActiveSupport::Delegation>::Inflector
# ./spec/spec_helper.rb:5:in `<top (required)>'
```

### System configuration
**Ruby version**:
3.3.0

**Comment by Earlopain** [comment] 2024-09-06 08:51
Duplicate of https://github.com/rails/rails/issues/52582

`factory_bot` needs to make a new release. https://github.com/thoughtbot/factory_bot/issues/1685

**Closed** 2024-09-06 12:43 UTC
