### ISSUE TITLE
ActiveRecord parameterized query on a JSON column always uses String

### ISSUE THREAD

**Issue by januszm** [rails/rails#52508] opened 2024-08-05 16:00 UTC
### Steps to reproduce
Assuming we have a model that stores some raw data in a JSON column (e.g. coming from another application), in the format below:

```ruby
House.last.data
# =>
{"city"=>"Troutman",
"state"=>"NC",
"zipcode"=>"28166",
"yearBuilt"=>2014 }
```
notice: 2014 is stored as an Integer.

When trying to query SQL using a JSON column, activerecord incorrectly converts the received numeric value to a string.

```ruby
House.where("data->'$.yearBuilt' > ?", 2000)
# =>
# "SELECT `houses`.* FROM `houses` WHERE (data->'$.yearBuilt' > '2000')"
# => []
```

### Expected behavior
There should be a way to tell Activerecord what do we want the `?` to be transformed to, e.g. that the value is expected to be a Number

```ruby
House.where("data->'$.yearBuilt' > ?", 2000)
# "SELECT `houses`.* FROM `houses` WHERE (data->'$.yearBuilt' > 2000)"
```

### Actual behavior
Value passed to the ? placeholder is converted to string
```ruby
(data->'$.yearBuilt' > '2000')
```

### System configuration
Rails 7.0.8.4
Ruby 3.2.4

**Comment by Jay0921** [comment] 2024-08-06 11:41
@januszm I can't replicate the issue without more details. Could you update the test below to demonstrate the issue?

```ruby
# frozen_string_literal: true

require "bundler/inline"
require "debug"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "7.0.8.4"
  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :houses, force: true do |t|
    t.json :data
  end
end

class House < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def setup
    data = {
      "city" => "Troutman",
      "state" => "NC",
      "zipcode" => "28166",
      "yearBuilt" => 2014
    }

    @house = House.create(data:)
  end

  def test_json_query
    result = House.where("data->'$.yearBuilt' > ?", 2000)

    assert_includes result, @house
  end
end
```

**Comment by januszm** [comment] 2024-08-06 19:52
@Jay0921  here's the updated script, database adapter is `mysql2`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "7.0.8.4"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "mysql2", username: "root", database: "myapp_development")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :houses, force: true do |t|
    t.json :data
  end
end

class House < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def setup
    data = {
      "city" => "Troutman",
      "state" => "NC",
      "zipcode" => "28166",
      "yearBuilt" => 2014
    }

    @house = House.create(data:)
  end

  def test_json_query
    result = House.where("data->'$.yearBuilt' > ?", 2000)

    assert_includes result, @house
  end
end
```

```
❯ bundle exec ruby parameterized_query_json.rb
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
-- create_table(:houses, {:force=>true})
D, [2024-08-06T21:51:09.159880 #55742] DEBUG -- :    (11.7ms)  DROP TABLE IF EXISTS `houses`
D, [2024-08-06T21:51:09.181695 #55742] DEBUG -- :    (21.7ms)  CREATE TABLE `houses` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `data` json)
   -> 0.0624s
D, [2024-08-06T21:51:09.306468 #55742] DEBUG -- :   ActiveRecord::InternalMetadata Load (2.0ms)  SELECT `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1
Run options: --seed 10588

# Running:

D, [2024-08-06T21:51:09.397371 #55742] DEBUG -- :   TRANSACTION (0.2ms)  BEGIN
D, [2024-08-06T21:51:09.400736 #55742] DEBUG -- :   House Create (3.3ms)  INSERT INTO `houses` (`data`) VALUES ('{\"city\":\"Troutman\",\"state\":\"NC\",\"zipcode\":\"28166\",\"yearBuilt\":2014}')
D, [2024-08-06T21:51:09.401838 #55742] DEBUG -- :   TRANSACTION (1.0ms)  COMMIT
D, [2024-08-06T21:51:09.403335 #55742] DEBUG -- :   House Exists? (0.9ms)  SELECT 1 AS one FROM `houses` WHERE (data->'$.yearBuilt' > '2000') AND `houses`.`id` = 1 LIMIT 1
D, [2024-08-06T21:51:09.403708 #55742] DEBUG -- :   House Load (0.2ms)  SELECT `houses`.* FROM `houses` WHERE (data->'$.yearBuilt' > '2000') /* loading for inspect */ LIMIT 11
F

Failure:
BugTest#test_json_query [parameterized_query_json.rb:45]:
Expected #<ActiveRecord::Relation []> to include #<House id: 1, data: {"city"=>"Troutman", "state"=>"NC", "zipcode"=>"28166", "yearBuilt"=>2014}>.
```

**Comment by skipkayhil** [comment] 2024-08-07 02:49
I believe this is not unique to JSON, and is actually a duplicate of https://github.com/rails/rails/issues/44312. The behavior is intentional due to some MySQL behavior as described in the comments in that issue.

I'm going to close, but feel free to reply here (or there if you agree this is a duplicate) if the suggested workarounds don't work for you!

**Closed by skipkayhil** 2024-08-07 02:49 UTC

**Comment by januszm** [comment] 2024-08-07 12:45
@skipkayhil  you're right, looks like a duplicate, I'll look at that linked issue. I hope it's resolved at some point.
