### ISSUE TITLE
Rails 6 multiple DB test Issue - PG::ConnectionBad: connection is closed error

### ISSUE THREAD

**Issue by navied** [rails/rails#36743] opened 2019-07-24 04:41 UTC
### Steps to reproduce

Git clone test repro: https://github.com/navied/pgtestbug
```
rails db:create
rails db:migrate
rails test
```

Edit: 

Another way for the error to pop up is to directly try and load the fixtures:

```
rails db:fixtures:load
```

### Expected behavior
Tests should pass

### Actual behavior

The first test that gets ran (order does not matter) always fails with a PG::ConnectionBad error.

![image](https://user-images.githubusercontent.com/1896993/61765325-9c4f5080-adaa-11e9-9440-89ac18789365.png)

I have honed in the issue being primary on a specific fixture, if you delete the account_concepts.yml fixture the tests will pass.  But I have not been able to find the specific reason as to why that fixture or db schema is causing it fail. This issue is also not present when you are not using a dual db setup.

### System configuration
**Rails version**: 6.0.0 RC2

**Ruby version**: 2.5.5p157

**Postgres Version**: 11.3

**Comment by eileencodes** [comment] 2019-07-24 14:55
I know what the problem is, but not sure how to fix it. The debug steps I took are:

* Turning on parallel testing did not reproduce the bug
* Deleting `fixtures :all` did not reproduce the bug
* Turning on eager_load in test did not reproduce the bug

I think by establishing a connection on ApplicationRecord to an existing database connection is killing it somehow. Technically you don't need to connect to the primary since it should already be connected. But that doesn't explain why it only breaks in PosrgreSQL since I've done this same code in a MySQL app. It should just re-establish the connection but seems like it's just dropping it instead. I'm not that familiar with postgres or our adapter here. I'm hoping someone with a bit more knowledge on postgres (@matthewd maybe?) knows what's might be happening here.

P.S. I'm going to push a PR to your demo app because there is one thing that's not done correctly.

**Comment by navied** [comment] 2019-07-24 14:58
@eileencodes go for it, also I was about to comment that I was able to repro it on sqlite3 as well.  Comes up with a similar error:

![image](https://user-images.githubusercontent.com/1896993/61804438-eca5cd00-ae01-11e9-9602-ac3edbfd8e6b.png)

**Comment by eileencodes** [comment] 2019-07-26 02:07
Hey @navied do you have a SQLIte3 app that reproduces this bug? I've not been able to reproduce it with what I believe are the minimal requirements and am thinking this is a different bug from the PostgreSQL one.

**Comment by navied** [comment] 2019-07-26 02:50
@eileencodes Just made a branch with it here that should show the error: https://github.com/navied/pgtestbug/tree/sqlite3

**Comment by eileencodes** [comment] 2019-07-26 15:23
I've narrowed this down and it's caused by my change in SchemaMigration so that it can work with multiple databases in https://github.com/rails/rails/pull/36439. Figuring out a fix.

**Comment by eileencodes** [comment] 2019-07-31 15:08
We have tracked this down and know what's causing it. Fixtures is holding onto a connection that it shouldn't be. We have a tentative fix but it needs work to get ActiveRecord tests passing.

In the meantime if you're blocked on your project you can remove the call to `establish_connection` in ApplicationRecord since it will already be established.

**Comment by eileencodes** [comment] 2019-08-02 18:26
This should be fixed by https://github.com/rails/rails/pull/36845

**Comment by navied** [comment] 2019-08-03 02:58
Ran the patch on my application and it works perfectly, thank you @eileencodes !

**Closed** 2019-08-04 19:25 UTC
