### ISSUE TITLE
Child validations with accepts_nested_attributes_for

### ISSUE THREAD

**Issue by rbarrera87** [rails/rails#18520] opened 2015-01-14 19:39 UTC
`valid?` method is validating the child association when I used `accepts_nested_attributes_for:` only when the association is loaded, even if I'm not modifying anything in the associated model, imagine the follow scenario:

```ruby
class User < ActiveRecord::Base  
  has_one :participant, dependent: :destroy
  validates_presence_of :username

  accepts_nested_attributes_for :participant
end

class Participant < ActiveRecord::Base  
  belongs_to :user
  validates_presence_of :phone_number
end

user = User.first
user.valid?
#=> true

#You must have a broken validation in the associated model to replicate this

user.participant
user.valid?
#=> false
user.errors.full_messages
#=> ["Participant phone number can't be blank"]
```

Is this a bug or there is any way to skip the associated validations and validate it only if I'm modifying some attributes in the associated model?

**Comment by sgrif** [comment] 2015-01-14 20:16
I believe this is the expected behavior of `accepts_nested_attributes_for`, as it sets the association to autosave. You should not have an invalid record in your database, unless you explicitly circumvented Rails' validations, which you should do at your own risk.

**Comment by rbarrera87** [comment] 2015-01-14 22:12
It might be the expected behavior but what I want to point here is that `valid?` method is not showing the same result, even when I'm not modifying anything in my instance variable. If `valid?` method were consistent, then it should validate both models always (therefore, it should return false always) but it's not.
I think the correct behavior should be as follow:
```ruby
user = User.first
user.valid?
#=> true

#loading association (for any reason)
participant = user.participant
...
# while I'm not modifying the  participant_attributes, valid? method should be true
user.valid?
#=> true

#Assign values in the setter
user.participant_attributes= [{ phone_number: "" }]
#at this time valid? method should validate the associated model since I'm modifying it
user.valid?
#=> false
user.errors.full_messages
#=> ["Participant phone number can't be blank"]
```

**Comment by sgrif** [comment] 2015-01-14 22:16
That's true of any association which is set to be autosaved, as the alternative is to eagerly load all associations whenever you save one of them, which would be bad. Again, this follows the assumption that a record *shouldn't* exist in the database, in which case the result wouldn't change here. If you explicitly bypass validations, you are doing so at your own risk, and behaviors like this can arise.

**Comment by senny** [comment] 2015-06-22 14:31
Closing for the reasons presented by @sgrif 

@rbarrera87 thank you for reporting.

**Closed by senny** 2015-06-22 14:31 UTC
Labels: activerecord

**Comment by gkop** [comment] 2017-07-15 01:16
@sgrif it's not just explicitly bypassing validations that can get you in trouble. It's also if you use [the `on:` option](http://guides.rubyonrails.org/active_record_validations.html#on) or [Conditional Validations](http://guides.rubyonrails.org/active_record_validations.html#conditional-validation).

I think there may be a good explanation for mine and the @rbarrera87's problem but I haven't found it yet. How come autosave still validates the children even if they haven't changed?

**Comment by villu164** [comment] 2020-11-25 05:54
For anyone that stumbles on rspec specs  breaking after adding `accepts_nested_attributes_for`,

```ruby
class User < ApplicationRecord
  has_one :profile
  accepts_nested_attributes_for :profile
end
```

then you might be missing simply a `inverse_of: :user`

```ruby
class User < ApplicationRecord
  has_one :profile, inverse_of: :user
  accepts_nested_attributes_for :profile
end
```
