### ISSUE TITLE
CustomSerializer.load is always called with nil argument (AR 4.2)

### ISSUE THREAD

**Issue by apeiros** [rails/rails#18825] opened 2015-02-06 10:09 UTC
With a custom serializer, ActiveRecord seems to always call .load with nil as argument, no matter what .dump returned.
Demo (tested against rails 4.2 gem with sqlite3): https://gist.github.com/apeiros/395f161ca002b0abe666

**Comment by apeiros** [comment] 2015-02-06 10:16
Inspecting the database, it doesn't seem to store the result of dump in the first place.

**Comment by sgrif** [comment] 2015-02-06 13:50
Duplicate of https://github.com/rails/rails/issues/18169

**Comment by sgrif** [comment] 2015-02-06 13:51
Sorry, this is not a duplicate of that issue, but this is the expected behavior. We save `nil` to the database if the result of `dump` is the same as `dump(nil)`, as it's defined as the "default" value.

**Closed by sgrif** 2015-02-06 13:51 UTC
Labels: activerecord

**Comment by apeiros** [comment] 2015-02-06 14:03
Ah, I see, this makes sense. The puzzle pieces start to fall together.
I think I'll do a documentation patch as at least to me, this was not clear from the existing docs.
I'll update the dummy serializer in the specs I'm working on accordingly.

**Comment by sgrif** [comment] 2015-02-06 14:51
Feel free to open a PR to clarify
