### ISSUE TITLE
Warning: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by cerenaracli** [rails/rails#39080] opened 2020-04-29 12:42 UTC
### Steps to reproduce
We have a model called Brochure and 'audited' gem. We upgraded our rails version from 4.2.10 to 5.0.7. We encountered a problem after upgrading the version.Gem(audited-activerecord) we used before is not used with rails 5.0.7 but 'audited' is used so we changed it.

When we start our app, we are seeing the following console warning:
ArgumentError - wrong number of arguments (given 2, expected 1):
  app/controllers/application_controller.rb:50:in `set_audit_user'

```
def set_audit_user
      @search = Brochure.with_active_company.is_published.live.newest.select('brochures.id,brochures.company_id').search(params[:q])
      @city = (params[:city_f].present? and City.pluck(:slug).include?(params[:city_f])) ? City.friendly.find(params[:city_f]) : City.friendly.find('istanbul')
      @cities = City.all.order('name ASC')
      catgories = Category.all
      @header_categories  = catgories.first(6)
      @categories_all  = catgories.last(catgories.count-6) if catgories.count > 6
      # Set audit current user
      Audited.current_user_method = :current_company if company_signed_in?
      @current_company = company_signed_in? ? current_company : nil
 end
```
we got the error on the line with _@search_. when we tested it, we saw that the problem is in 'Brochure.with_active_company'. In here, 'with_active_company' is scope.
  `scope :with_active_company, -> { joins(:company).where('companies.is_active = ?', true).with_company }`
  `scope :is_published, -> { where(status: Brochure.statuses[:published]) }`

What are your thoughts on this warning?

Thank you very much!!!

### System configuration
**Rails version**:5.0.7

**Ruby version**: 2.4.0

**Comment by eileencodes** [comment] 2020-04-29 13:01
Hey @cerenaracli thanks for the report. There's not enough information here for us to determine whether this is a bug in Rails. Please use our bug scripts here https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb to reproduce the issue. If you can't reproduce the issue without the audited gem then it's likely the cause and you need to open an issue on that gems repo.

**Comment by zhengpd** [comment] 2020-05-13 02:21
Hi @cerenaracli I saw that you also reported the issue at `audited` repo https://github.com/collectiveidea/audited/issues/531 . If it's confirmed causing by `audited` gem or resolved, you could close the issue here at Rails so that it would be less distraction in open issues of Rails.

If the cause is not known yet, you might try:
1. Run `Brochure.with_active_company` in `rails console` to see if the error comes out
2. Or remove audited-related code from `Brochure` model and try step 1.

**Closed** 2020-05-13 13:17 UTC
Labels: more-information-needed
