### ISSUE TITLE
Creating a record with create! with a missing required belongs_to relationship doesn't raise an error

### ISSUE THREAD

**Issue by adamcooke** [rails/rails#23854] opened 2016-02-24 14:54 UTC
I've noticed that on Rails 5.0.0.beta2 that creating a new record using `Model.create!` doesn't raise any errors and creates an invalid record when there is a missing `belongs_to` relationship. 

This assume that `belongs_to_required_by_default` is `true` and the `belongs_to` relationship doesn't specify any options for `optional` or `required` implying that it is required.

Is this desired behaviour? I'd have thought this should raise a normal `ActiveRecord::RecordInvalid` exception.

**Comment by rafaelfranca** [comment] 2016-02-24 15:44
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by adamcooke** [comment] 2016-02-24 16:02
Having written a test using the template, I can't reproduce. This led me to investigate further, I have now discovered that it seems to be happening on when using `db:seed`. 

I've created a basic rails app which demonstrate the behaviour at https://github.com/adamcooke/rails-seeds-belongs-to-test. If you run `db:reset` you'll find that a `Contact` is created with a null `account_id`. When running `Contact.create!` in a console, an appropriate error is raised.

I'm not too familiar with what's different between the console & seed environments to cause this.

**Comment by chashmeetsingh** [comment] 2016-02-24 16:45
try adding validations in the models you will get error both ways

**Comment by Shwetakale** [comment] 2016-02-24 17:02
+1 for this. It seems to be on reset association validations are not executed. After using

    rake db:reset

It created on contact with nil account_id

    #<ActiveRecord::Relation [#<Contact id: 1, account_id: nil, name: nil, created_at: "2016-02-24 17:01:50", updated_at: "2016-02-24 17:01:50">]>

**Comment by chashmeetsingh** [comment] 2016-02-24 17:05
Validations are not executed because there aren't any validations

**Comment by rafaelfranca** [comment] 2016-02-24 17:09
Yes. There is. `belongs_to :foo, required: true` create a validation.

**Comment by Shwetakale** [comment] 2016-02-24 17:12
@chancancode In rails 5 belongs_to are default required. we need to add ```optional: true``` if we don't want it to be mandatory.

**Comment by waits** [comment] 2016-04-03 20:56
I reproduced this on 5.0.0.beta3 as well: https://github.com/waits/rails-reset-belongs-to-test

Note that it fails when running `db:reset` or `db:setup`. `db:seed` behaves correctly.

**Comment by waits** [comment] 2016-04-03 23:05
It also works fine when running `bin/rake` instead of `bin/rails`...

**Comment by waits** [comment] 2016-04-04 01:04
I started working on this issue in #24409.

**Comment by kamipo** [comment] 2018-02-03 16:54
This should be fixed by #31135.

**Closed by kamipo** 2018-02-03 16:54 UTC
Labels: activerecord, attached PR
