### ISSUE TITLE
index.html.erb changes not reflect on browser

### ISSUE THREAD

**Issue by qslcna** [rails/rails#42624] opened 2021-06-28 08:04 UTC
### Steps to reproduce

run
```ruby
 rails s
```
on development environment
edit app/views/home/index.html.erb 
e.g. add `<p>hi</p>`
refresh the browser

### Expected behavior

browser should display the view updated ( `hi`  ) without restart server
### Actual behavior

browser still display the  old one, while I restart server and refresh the browser updates ( `hi`) appears.
### System configuration
**Rails version**:
6.1
**Ruby version**:
2.7

**Comment by qslcna** [comment] 2021-06-28 08:11
routes.rb
```ruby
Rails.application.routes.draw do
  
  get 'home/index'

  resources :sale_orders, :customers

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
```

home_controller.rb
```ruby
class HomeController < ApplicationController
  def index
  end
end

```

application.html.erb
```html
<!DOCTYPE html>
<html>
  <head>
    <title>PocketWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'main', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'main' %> 
  </head>

  <body class="hold-transition skin-blue sidebar-mini" >
     <%= yield %>
  </body>
</html>

```

home/index.html.erb
```html
<div class='.wrapper' id='app'>
   
</div>
```

home/index.html.erb (edited)
```html
<div class='.wrapper' id='app'>
   <p>hi</p>
</div>
```

**Comment by qslcna** [comment] 2021-06-28 08:12
BTW, I make all config as default

**Comment by zzak** [comment] 2021-06-28 10:26
@qslcna In this case, I wonder if a public repo that demonstrates the issue would be helpful 🤔 I'm not seeing anything that would change this behavior in the code you pasted.

**Comment by qslcna** [comment] 2021-06-28 13:20
@zzak  https://github.com/qslcna/pocket_web.git

**Comment by alexcameron89** [comment] 2021-06-28 14:31
Hey @qslcna, I checked out the repo that you provided, and was able to see view changes without restarting the server so I am not able to reproduce the issue. I see that the app is using Vue libraries and I wonder if you're having conflicts elsewhere outside of Rails.

I have a couple of recommendations:
1. **See if something outside of Rails is conflicting** - Have you checked to see what the HTML response is from the app? There is a chance that the HTML is correct, but Vue is conflicting with it.
2. **See if you can reproduce the issue in a brand new minimal Rails app** - If you're still having an issue, I recommend creating a brand new rails app, skipping any non-Rails gem or JS package additions outside of what `rails new` provides and using only the code parts that [you mentioned above](https://github.com/rails/rails/issues/42624#issuecomment-869471411) to see if you can reproduce the issue. If so, you can provide us with that repo, and I'll take another look at it to see if I can reproduce the issue.

I'm going to close this in the meantime since it does not seem to be an issue with Rails, but if you're able to reproduce it in a minimal Rails app, mention me and I'll take another look.

**Closed by alexcameron89** 2021-06-28 14:31 UTC

**Comment by qslcna** [comment] 2021-07-04 14:17
@alexcameron89  I think that it's because of wsl2 (https://github.com/microsoft/WSL/issues/4417)
