### ISSUE TITLE
It is impossible to create pages in rails 7

### ISSUE THREAD

**Issue by vasilevskykv** [rails/rails#48113] opened 2023-05-02 18:58 UTC
### Steps to reproduce

**config/routers.rb:**
```ruby
Rails.application.routes.draw do
   root "pages#index"
 end
```
**app/controllers/pages_controller.rb:**
```ruby
class PagesController < ApplicationController 
    def index
    end
end
```
**app/views/pages/index.html.erb:**
```ruby
<h1>Welcome to AskIt!</h1>

&copy; @vaskonst <%= Time.now.year %>
```

### Expected behavior

Normal opening of the web page "index.html"
### Actual behavior

Showing I:/Install/RubyRails/AskIt/app/views/layouts/application.html.erb where line # raised:

Permission denied @ rb_file_s_rename - (I:/Install/RubyRails/AskIt/tmp/cache/assets/sprockets/v4.0.0/ws/wsX7cXuUe10xkdDaQwCc1cC-WQSQ8EbnJH395GSTKAI.cache.68480.20436.623370, I:/Install/RubyRails/AskIt/tmp/cache/assets/sprockets/v4.0.0/ws/wsX7cXuUe10xkdDaQwCc1cC-WQSQ8EbnJH395GSTKAI.cache)
### System configuration
**Operation System**
Windows 10
**Rails version**:
Rails 7.0.4.3
**Ruby version**:
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]

**Comment by nvasilevski** [comment] 2023-05-03 17:18
>The problem is solved 

Glad you found a solution! The issue seem to be caused by the environment setup and not Rails itself so I'll close the issue

**Closed by nvasilevski** 2023-05-03 17:18 UTC
