### ISSUE TITLE
Engine dummy app under 5.2.2.1 on travis fatal errors on fail to create tmp/development_secret.txt

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#35611] opened 2019-03-14 15:59 UTC
This is somehow related to the [5.2.2.1 patch for secret_key_base](https://groups.google.com/forum/#!topic/rubyonrails-security/IsQKvDqZdKw)

I have some Rails engines that get tested on travis. I didn't update either of the Rails-engine-skeleton generated "dummy" apps for 5.2.2.1 -- as I generally don't when new Rails versions come out, usually don't need to (and sometimes do things to try and test under multiple Rails versions with same dummy app, which has worked fine since Rails 5.0). 

However, my gemfiles/gemspecs allowed 5.2.2.1, so next time a travis test ran, it picked up the recently released 5.2.2.1. 

And it failed in a weird way on travis, that I have not managed to reproduce locally. 

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/travis/build/sciencehistory/kithe/spec/dummy/tmp/development_secret.txt
/home/travis/build/sciencehistory/kithe/gemfiles/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2.1/lib/rails/application.rb:597:in `binwrite'
```

If we look at [5.2.2.1 application.rb:597](https://github.com/rails/rails/blob/v5.2.2.1/railties/lib/rails/application.rb#L597), we see it only _gets_ to to that codepath if the file did not exist. And then uses `File.binwrite(key_file, random_key)` to try to create it. 

`File.binwrite` doens't normally fail on a file that doesn't exist yet, it's perfectly happy to create a new file. The parent directory `spec/dummy/tmp` *does* exist. 

I don't understand why it's failing here, and am not able to reproduce not-on-travis. It could be some kind of bug or weird environment on travis I guess. 

I think the workaround is probably just making sure my test environment defines a `secret_key_base` so that codepath is never executed. 

Filing this here in part so other people can find it; I think it's possible a lot of people testing Rails engines (or apps? Not sure) on travis are going to start seeing this failure with Rails 5.2.2.1.

**Comment by eileencodes** [comment] 2019-03-14 16:02
Hey @jrochkind thanks for the report. 

Are you sure the tmp dir exists on travis? If you delete it locally I bet this will fail locally. We had that issue with Rails tests in Travis. Maybe we need to create the tmp dir if it doesn't exist. Will discuss with the team and get back to you.

**Comment by jrochkind** [comment] 2019-03-14 16:09
Thanks for quick response @eileencodes!

I am pretty sure it exists on travis.... ah wait, it probably does not. I _thought_ it was checked into my repo (so would exist), but it turns out it was not, because I have no files in it, so does not actually exist in the repo. 

So that does seem likely. (I get a _slightly different_ error when testing locally without the `tmp`, bu that's probably MacOS local vs linux travis). 

I _could_ add a `tmp/.keep` so it exists in the repo. 

Here's another thing which also fixed it fine, adding to my `spec/dummy/config/environments/test.rb`: `config.secret_key_base = SecureRandom.hex(64)` -- so that the new 5.2.2.1 code trying to create a `tmp/development_secret.txt` does not get called. Which seems fine to do. 

So both of those are fine workarounds. 

But I _think_ every other part of Rails that is going to use `Rails.root.join("tmp")` will create it first if it does not exist. If this is true, perhaps this code path should be doing that rather than failing on non-existent `tmp` too?

**Comment by jrochkind** [comment] 2019-03-14 16:16
So, I just tested it out, if you create a brand new "engine" with `rails plugin new foo`, it has a `.gitignore` that includes `test/dummy/tmp/`. So you're probably never going to get `tmp` in your repo. And then when you do some CI somewhere... it seems highly likely to run into this problem. So.

**Comment by andrehjr** [comment] 2019-03-14 16:23
Isn't this fixed by https://github.com/rails/rails/pull/35607 ?

**Comment by eileencodes** [comment] 2019-03-14 16:25
Didn't see that, awesome, thanks @andrehjr!

**Closed by eileencodes** 2019-03-14 16:25 UTC
Labels: railties, regression

**Comment by jrochkind** [comment] 2019-03-14 16:30
Looks like that exactly fixes this, @andrehjr, yes! 

Of course, nobody running 5.2.2.1 has that fix.  :(

I'd note that the description of why the fix is needed can be expanded though:

> The tmp directory is added to version control in the newly created application. 

True, f06ce4c12 generates a `.keep` file in tmp when you do `rails new appname`, since Rails 5.0. 

But when you are generating an _engine_ with `rails plugin new`, even the `test/dummy/tmp` app does _not_ have a `tmp` dir in it at all (nor a .keep file in the non-existing dir), and additionally has a generated `.gitignore` that would keep `tmp/.keep` out of the repo anyway. 

So this problem will bite people testing _engines_, even if they generated in rails 5.0-5.2.2.1.  It may get a lot of people until/unless a 5.2.x release is made that fixes it?

**Comment by eileencodes** [comment] 2019-03-14 16:34
5.2.3 is going to be released very soon and since this only affects running builds on CI and is not a bug in the implementation that makes it less secure it doesn't make sense to release Rails 5.2.2.2 to fix it.

**Comment by jrochkind** [comment] 2019-03-14 16:36
Reasonable, especially if 5.2.3 is indeed very soon. Hopefully anyone having the problem will find this ticket and see how to fix their builds. (Not _totally_ sure it only effects CI, but the fix is the same either way) 

Would be good to make sure #35607 is back-ported to 5.2.3 though!

**Comment by eileencodes** [comment] 2019-03-14 16:38
It was in https://github.com/rails/rails/commit/b4079b17ede84bf48dcd7fae74595952e32ec119

**Comment by scones** [comment] 2019-03-24 19:32
broken in 6.0.0.beta3

**Comment by scones** [comment] 2019-03-24 19:39
adding the following lines to the testing container invocation script before starting the actual tests solved my problem:

```
              mkdir -p tmp
              echo -n '12345678901234567890123456789012' > tmp/development_secret.txt

```

**Comment by jrochkind** [comment] 2019-03-25 21:38
@scones I think just the `mkdir -p tmp` might be sufficient?

I guess we do need a workaround of some kind at least until 5.2.3 and another 6.0.0beta is released. 

That could be one of em. Another could be making sure your internal dummy/test app (by default at `./test/dummy` although it might be in other places if you are using rspec etc) has a `tmp` checked into the repo.
