### ISSUE TITLE
Wrong documented - path to images when using image_tag, image_path helper

### ISSUE THREAD

**Issue by Javix** [rails/rails#23683] opened 2016-02-15 09:51 UTC
It is [indicated](https://github.com/rails/rails/blob/d330d86b2c218d9653ebdbbd6ec9f4a8ec55a6e8/actionview/lib/action_view/helpers/asset_tag_helper.rb#L208) in the doc that when using `image_path` helper the generated HTML will be as follows:
```
image_path("icons/edit.png")                               # => "/assets/icons/edit.png"
```
The `image_path` is used internally by `image_tag` helper. 
But it is not really the case, - the generated HTML code contains `images`prefix and will be as follows:
```
= image_tag('icons/multiple-devices.svg') => #/images/icons/multiple-devices.svg
```
I put `multiple-devices.vg` file into `assets/icons`.
What's wrong with that?

**Comment by xw19** [comment] 2016-02-15 10:09
@Javix Which version of rails are you using ?

**Comment by Javix** [comment] 2016-02-15 10:11
4.2.5

**Comment by Javix** [comment] 2016-02-15 10:33
Sure, if I put my image inside `assets/images/icons` folder it works. Because in `compute_asset_extname` method we check `ASSET_EXTENSIONS[options[:type]`where the passed in type will be `image`, that's where images prefix comes from.

**Comment by xw19** [comment] 2016-02-15 10:35
Can you point to the app that shows this inconsistency ?

**Comment by Javix** [comment] 2016-02-15 10:43
I can't for the moment it is in a private repo. 
It will work if you put that whenever you want in a view (I'm using `slim`, but I think to have the same behaviour with era templates):
```
= image_tag('icons/awesome_image.svg')
```
and you put your `awesome_image.svg` inside `assets/images/icons`.
If you put your `awesome_image.svg` just inside assets folder, it fails to load it. Because Rails will try to load it from `assets/images/icons`.

**Comment by xw19** [comment] 2016-02-15 11:39
You are expected to put that image into assets/image directory

**Comment by Javix** [comment] 2016-02-15 11:42
@xw19 sure, I've figured out of that. The point I'd like to take your attention to is that the documentation does not talk about it, no where :(.

**Comment by xw19** [comment] 2016-02-15 11:45
Can you create a PR ?

**Comment by Javix** [comment] 2016-02-15 13:35
Rails 5beta already has it updated. Not sure if it is needed.

**Comment by maclover7** [comment] 2016-02-15 14:53
cc @schneems

**Comment by schneems** [comment] 2016-02-15 15:50
Was this previously working and if so what version of rails was it working on? Can you try this using Rails master?

Can you give me an example app that reproduces the behavior? When the asset pipeline cannot find an asset, it fill fall back on the string you supplied. I think something like that is happening here.

**Comment by Javix** [comment] 2016-02-15 19:21
@schneems I pushed an example app at git@github.com:Javix/image_tag_app.git.

**Comment by ashrestha91** [comment] 2016-04-19 08:26
Odd, I'm seeing a similar issue, but it sounds like it's reversed:

I have an image "photo.png" in `app/assets/images/photo.png`.  The helpers give me the following:
```
>> image_tag 'photo.png'
=> "<img alt=\"Photo\" src=\"/assets/photo.png\" />"

>> image_url 'photo.png'
=> "127.0.0.1/images/photo.png"

>> image_path 'photo.png'
=> "/images/photo.png"
```

**Comment by schneems** [comment] 2016-04-20 14:22
Here's the deal. You've got that asset under `app/assets/app_icons` which isn't in Sprocket's search path.

Then you're looking for

```
<%= image_path('app_icons/evolution.svg')%>
```

Sprockets would expect this file in

```
app/assets/app_icons/app_icons
```

Since it starts looking at the root of each of your paths.

The solution is to add that folder to your paths:

```ruby
    # config/application.rb
    config.assets.paths << Rails.root.join("app/assets/app_icons")
    config.assets.precompile << "app_icons/evolution.svg"
```



Then in your view use

```
<%= image_path('evolution.svg')%>
```

## Takewaway

You're using the API incorrectly, however this seems like something we could warn you about or raise an error. Maybe in development we check to see if we could find an asset by that name "evolution.svg" and tell you that while we didn't find it where we were looking we did find it in `<path>`. Though that would have made things more confusing in this case. I'll need to think a bit more on it. I'm going to close this issue and open a new one in sprockets.

**Closed by schneems** 2016-04-20 14:22 UTC
Labels: asset pipeline

**Comment by schneems** [comment] 2016-04-20 14:37
I opened rails/sprockets#281. I think there's definitely something we could do to improve this experience. I'm not 100% sure on the best course. Please follow that issue for updates.

**Comment by sagg155** [comment] 2018-11-14 11:22
@schneems , i'm also getting same error using this image_tag.

I have put my image-icon in app/assets/images/icons/my-icon folder.
I have used the image_ tag like this ;->
                    <%= image_tag 'icons/my-icon/question_circle.svg',
                            class: 'c-navbar__logo_img',
                            alt: 'Help-icon' %>      


But this is giving me error on console that image on that path doesn't exist.
After hours of debugging and trying every possible permutation for this path still not able to solve my problem of rendering the image on my web page.


Ruby  Version ->  ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]

Please look into this issue. Very very urgent!!!!
Thanks in advance. Any help will be appreciated!!!
