### ISSUE TITLE
[Rails 6.0.4][Ruby 2.7.2] Deprecation warning "Use Rails::SourceAnnotationExtractor instead."

### ISSUE THREAD

**Issue by VTRyo** [rails/rails#42569] opened 2021-06-23 02:42 UTC
### Steps to reproduce

- `bundle exec rspec` or `rails c`

### Expected behavior

Completion should work without any warning

### Actual behavior

Although there is no direct use of "SourceAnnotationExtractor", the following warning message is printed

```ruby
DEPRECATION WARNING: SourceAnnotationExtractor is deprecated! Use Rails::SourceAnnotationExtractor instead. (called from <top (required)> at /app/config/application.rb:7)
```

### System configuration
**Rails version**: 6.0.4 

**Ruby version**: 2.7.2

### About the others

I've been running the Update based on the following conversation, but there was no change in the output of the warning message.

- https://github.com/rails/rails/pull/37776
- https://github.com/rails/rails/issues/37775
- https://github.com/rails/rails/pull/37468

**Comment by yahonda** [comment] 2021-06-23 06:57
Would you push a git repository and/or provide [an executable test case ](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html) which reproduces this issue?

**Comment by casperisfine** [comment] 2021-06-23 14:21
`called from <top (required)> at /app/config/application.rb:7`

So it's in the app config. The message also make it clear how to fix it. I think we can close.

**Comment by casperisfine** [comment] 2021-06-23 15:32
I don't think so, but even if it is, it would require non-rails code, so really this seems like 3rd party to me.

**Comment by rafaelfranca** [comment] 2021-06-23 22:08
Closing since Rails doesn't reference this constant anywhere in this code. Let you know if you find the reason for the deprecation. Thank you

**Comment by VTRyo** [comment] 2021-06-24 05:35
Thank you all.
I'm sorry I haven't been able to reply to your questions.

I'll raise another issue when I find the reason for deprecation.

**Closed** 2021-06-24 05:36 UTC
