### ISSUE TITLE
config.allow_concurrency = false, in a test environment, removes the session in an IntegrationTest

### ISSUE THREAD

**Issue by kensentor** [rails/rails#29608] opened 2017-06-28 15:09 UTC
### Steps to reproduce

https://github.com/kensentor/rails_concurrency_bug_demo - this app declares a barebones controller endpoint in `application_controller.rb`, and a test that hits that endpoint and then asserts that the `session` variable is a `ActionDispatch::Request::Session`. This will fail while `config.allow_concurrency = false` is in `config/environments/test.rb`.

### Expected behavior
An IntegrationTest's `session` variable should contain an `ActionDispatch::Request::Session` after the test makes a request.

### Actual behavior
It seems that once a request is made, the integration test's `session` is replaced with an empty hash. Flash messages set in the controller will also not be present in the 'flash' variable in the test.

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.3.1

My understanding is that `config.allow_concurrency = false` is an old setting, and one that my workplace likely carried forward from Rails 2, but the setting breaks tests in a very sneaky, hard to detect way in Rails 5 (Rails 4 worked fine). If the setting is too old to be fixed, maybe it should show a warning of some sort when used.

**Comment by rafaelfranca** [comment] 2017-06-28 15:34
The only thing `allow_concurrency` as `false` does is to add `Rack::Lock` to the middleware stack and configure the code executor differently. @matthewd do you know what could affect the `IntegrationTest` logic?

**Comment by rafaelfranca** [comment] 2017-06-28 15:50
It seems to be `Rack::Lock` when I remove it from the stack it works as expected. Not sure why though.

**Comment by lugray** [comment] 2017-07-07 23:21
As outlined in Rack/rack#1189, this is caused by `Rack::Lock` replacing the `env`, invalidating the copy held by `ActionDispatch::Request` which assumes that `env` is mutated but not replaced throughout the middleware stack.

**Comment by lugray** [comment] 2017-07-11 18:37
This has been fixed in rack and back-ported to [2-0-stable](https://github.com/rack/rack/tree/2-0-stable).  It will be fixed in rails on the next rack release.

**Closed** 2017-07-11 18:45 UTC
Labels: actionpack
