### ISSUE TITLE
Bug with AR::Base#count when passing params to count

### ISSUE THREAD

**Issue by devonestes** [rails/rails#25636] opened 2016-07-01 20:37 UTC
### Steps to reproduce

Here's a gist with the reproduction script: https://gist.github.com/devonestes/369857bc5459f0771fcd5b0e63bb863d

### Expected behavior
I expect models that inherit from ActiveRecord::Base to be able to accept a hash of options when calling `.count`.

### Actual behavior
I get a malformed SQL string: `SELECT COUNT({:author_type=>"Dude", :author_id=>1}) FROM "posts"`

### System configuration
**Rails version**:
5.0.0
**Ruby version**:
2.3.1

**Comment by matthewd** [comment] 2016-07-01 20:38
That hasn't been true since Rails 2.3.

**Comment by devonestes** [comment] 2016-07-01 20:40
@matthewd I would tend to agree with you, but my upgrade today - and the reproduction script I attached - seem to be showing different results.

**Comment by matthewd** [comment] 2016-07-01 20:43
@devonestes you have a reproduction script, on some 3.x or 4.x version, that supports this? :confused:

The "That" I was referring to was your expectation, not the described behaviour (which is what I expect).

**Comment by rafaelfranca** [comment] 2016-07-01 20:46
This working differently in Rails 4 is probably because of activerecord-deprecated_finders that provided the similar feature.

**Comment by devonestes** [comment] 2016-07-01 20:51
@matthewd I've updated the reproduction script to show that it does indeed work in 4.2.3: https://gist.github.com/devonestes/369857bc5459f0771fcd5b0e63bb863d

**Comment by devonestes** [comment] 2016-07-01 20:53
Sounds like this is expected behavior, but we didn't really get a deprecation warning (or at least I didn't see any in 4.2.3). Maybe the upgrade path can be a little more explicit for users? I have to admit, this one was a head scratcher for me this morning!

**Comment by rafaelfranca** [comment] 2016-07-01 20:55
Does it work or just it ignores the arguments? Have you tried 4.2.6 to see if the deprecation happens?

**Comment by devonestes** [comment] 2016-07-01 21:02
Looks like it does just ignore the arguments... I see the following SQL logging when I run the script:

```
# Running:

D, [2016-07-01T13:56:20.844515 #29114] DEBUG -- :    (0.2ms)  BEGIN
D, [2016-07-01T13:56:20.850880 #29114] DEBUG -- :   SQL (0.5ms)  INSERT INTO "posts" ("author_type", "author_id") VALUES ($1, $2) RETURNING "id"  [["author_type", "Dude"], ["author_id", 1]]
D, [2016-07-01T13:56:20.851796 #29114] DEBUG -- :    (0.4ms)  COMMIT
D, [2016-07-01T13:56:20.852956 #29114] DEBUG -- :    (0.4ms)  SELECT COUNT(*) FROM "posts"
.
```

I also tried in 4.2.6 and saw nothing about deprecation of that feature... Here's the total output:

```
 ☢  ~/esh/IRT   upgrading-to-rails-5±  ruby bug_script.rb
Resolving dependencies...
Using rake 11.2.2
Using json 1.8.3 (was 2.0.1)
Using i18n 0.7.0
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 1.6.4 (was 2.0.1)
Using mime-types-data 3.2016.0521
Using arel 6.0.3 (was 7.0.0)
Using bundler 1.12.5
Using concurrent-ruby 1.0.2
Using pg 0.18.4
Using thor 0.19.1
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using mime-types 3.1
Using sprockets 3.6.3
Using activesupport 4.2.6 (was 5.0.0)
Using loofah 2.0.3
Using mail 2.6.4
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.6 (was 5.0.0)
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7 (was 2.0.1)
Using activejob 4.2.6 (was 5.0.0)
Using activerecord 4.2.6 (was 5.0.0)
Using actionview 4.2.6 (was 5.0.0)
Using actionpack 4.2.6 (was 5.0.0)
Using actionmailer 4.2.6 (was 5.0.0)
Using railties 4.2.6 (was 5.0.0)
Using sprockets-rails 3.1.1
Using rails 4.2.6 (was 5.0.0)
-- create_table(:posts, {:force=>true})
D, [2016-07-01T14:01:37.649887 #29532] DEBUG -- :    (5.5ms)  DROP TABLE "posts"
D, [2016-07-01T14:01:37.655466 #29532] DEBUG -- :    (4.8ms)  CREATE TABLE "posts" ("id" serial primary key, "author_type" character varying, "author_id" integer)
   -> 0.0325s
-- create_table(:authors, {:force=>true})
D, [2016-07-01T14:01:37.658622 #29532] DEBUG -- :    (1.7ms)  DROP TABLE "authors"
D, [2016-07-01T14:01:37.663264 #29532] DEBUG -- :    (4.3ms)  CREATE TABLE "authors" ("id" serial primary key, "name" character varying)
   -> 0.0077s
Run options: --seed 59502

# Running:

D, [2016-07-01T14:01:37.728117 #29532] DEBUG -- :    (0.2ms)  BEGIN
D, [2016-07-01T14:01:37.734919 #29532] DEBUG -- :   SQL (0.5ms)  INSERT INTO "posts" ("author_type", "author_id") VALUES ($1, $2) RETURNING "id"  [["author_type", "Dude"], ["author_id", 1]]
D, [2016-07-01T14:01:37.735784 #29532] DEBUG -- :    (0.4ms)  COMMIT
D, [2016-07-01T14:01:37.737890 #29532] DEBUG -- :    (0.4ms)  SELECT COUNT(*) FROM "posts"
.

Finished in 0.020032s, 49.9198 runs/s, 49.9198 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by rafaelfranca** [comment] 2016-07-01 21:08
Yes, you should be able to see a deprecation.

**Comment by matthewd** [comment] 2016-07-01 21:12
@RF to be clear, per the milestone, we're saying there's a deprecation missing from **4.2**, right? And it's fine for 5.0 to stick with the straight failure?

**Comment by rafaelfranca** [comment] 2016-07-01 21:22
Yeah, 5.0 should with the failure and 4.2 should show the deprecation. We are not adding a new deprecation we are only fixing a bug that make it not being printed.

**Comment by devonestes** [comment] 2016-07-01 21:22
That makes sense - hopefully other's won't be as confused as I was. Thanks for helping!

**Comment by connorshea** [comment] 2016-07-10 17:40
What's the status on adding this deprecation?

**Comment by rafaelfranca** [comment] 2016-07-12 02:32
It was fixed by https://github.com/rails/rails/pull/20450 and already in 4.2.7.rc1

**Closed by rafaelfranca** 2016-07-12 02:32 UTC
Labels: activerecord
