### ISSUE TITLE
Rails 4.2.6 boot fails under Ruby 2.4.0preview1

### ISSUE THREAD

**Issue by deepj** [rails/rails#25466] opened 2016-06-21 22:47 UTC
### Steps to reproduce

1. `rails new test_app`
2. `cd test_app`
3. `rails s`

### Expected behavior
Run Rails server

### Actual behavior
It fails on this

```console
$ rails s
=> Booting WEBrick
=> Rails 4.2.6 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/deepj/.gem/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
	from /Users/deepj/.gem/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/deepj/.gem/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/deepj/.gem/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/deepj/.gem/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/deepj/.gem/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/deepj/.gem/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/deepj/.gem/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/deepj/.gem/ruby/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	 ... 5660 levels...
	from /Users/deepj/.rubies/ruby-2.4.0-preview1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/deepj/dev/bugs/rails-4.2.6-ruby-2.4.0/test_app/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

### System configuration
**Rails version**: 4.2.6 (included 4-2-stable branch)

**Ruby version**: 2.4.0preview1

**Comment by jonathanhefner** [comment] 2016-06-22 01:18
Duplicate of #25125, I think.

**Comment by maclover7** [comment] 2016-06-22 01:19
thanks @jonathanhefner, closing as a dup of #25125.

**Closed by maclover7** 2016-06-22 01:19 UTC
