### ISSUE TITLE
after_commit on: :update callbacks are triggered even when none of the object's attributes are updated.

### ISSUE THREAD

**Issue by manojmj92** [rails/rails#44500] opened 2022-02-21 12:28 UTC
Hi everyone,

I came across this behaviour of `after_commit on: :update` callback and wanted to make sure if this is a bug or not.

Such callbacks are being fired even on empty saves where none of the object's attributes (including `updated_at`) changes. In short, there wasn't any update per se to the record, but the `update` callbacks are being triggered anyway, which is confusing.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org/"

  git_source(:github) { |repo| "[https://github.com/#{repo}.git](https://github.com/#%7Brepo%7D.git)" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  after_commit :some_callback, on: :update

  private

  def some_callback
    raise 'triggered'
  end
end


class BugTest < Minitest::Test
  def test_callback
    Post.create!
    post = Post.last

    post.save! # raises error from the callback, but ideally it shouldn't because no attribute of `post` was changed.
  end
end
```

### Expected behavior

`update` callbacks should not be triggered because there are no updates to any of the attributes of the object.

### Actual behavior

`update` callbacks are being triggered even though there are no updates to any of the attributes of the object.

### System configuration
**Rails version**:

`7.0.0`

**Ruby version**:

`ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`

**Comment by mansakondo** [comment] 2022-02-21 15:58
Hi @manojmj92. From my understanding, it seems that this behaviour is intentional:
https://github.com/rails/rails/blob/7b1f65e8f56738aaa8dd15f19d3ac5f4385ff229/activerecord/lib/active_record/persistence.rb#L1097-L1103

**Comment by nvasilevski** [comment] 2022-02-21 18:42
It seems to behave according to the code but I must admit that from some point of view `after_commit` implies existence of a transaction `commit` performed at the database layer and in this particular test case we don't have any commit performed. So I can see why it can be considered inconsistent.
I can't seem to to find a doc that explicitly states that `after_commit` callback is strongly coupled with a transaction commit but some docs seem to imply this. For example:
https://github.com/rails/rails/blob/18707ab17fa492eb25ad2e8f9818a320dc20b823/activerecord/lib/active_record/transactions.rb#L175-L179

Also this test for example again kind of implies having some transaction to be committed but we don't really have any:
https://github.com/rails/rails/blob/b4cab6a8547dbb12211efc0b086a80712df3278d/activerecord/test/cases/transaction_callbacks_test.rb#L113-L119

To confirm we could modify the test as following:
```ruby
  def test_call_after_commit_after_transaction_commits
    @first.after_commit_block { |r| r.history << :after_commit }
    @first.after_rollback_block { |r| r.history << :after_rollback }

    sql = capture_sql do
      @first.save!
    end
    assert_empty sql # passes
    assert_equal [:after_commit], @first.history
  end
```
Perhaps `transaction` refers to a Rails concept of a transaction and strongly coupled to an actual database transaction. But anyway feels like there is some space for discussion/clarification. Maybe at least it could result in a tiny update for documentation

**Comment by mansakondo** [comment] 2022-02-21 19:19
> It seems to behave according to the code but I must admit that from some point of view `after_commit` implies existence of a transaction `commit` performed at the database layer and in this particular test case we don't have any commit performed. So I can see why it can be considered inconsistent.

I also believe that this behaviour is confusing.

**Comment by mansakondo** [comment] 2022-02-21 19:55
I'm not sure, but this behaviour may be caused by this code:
https://github.com/rails/rails/blob/2459c20afb508c987347f52148210d874a9af4fa/activerecord/lib/active_record/transactions.rb#L313-L325

**Comment by vipulnsward** [comment] 2022-02-21 20:05
Yes these are due to empty transactions which the save is enclosed in. We can add documentation if helpful but changing this behavior will break lots of apps.

**Closed** 2022-02-21 20:05 UTC
