### ISSUE TITLE
has_one through triggering autosave by default

### ISSUE THREAD

**Issue by TiagoCardoso1983** [rails/rails#9336] opened 2013-02-20 10:14 UTC
I found the strangest issue by activerecord (3.2.12, not sure how that works in 4). Basically I have the following set this way:

``` ruby
class Bing < ActiveRecord::Base
  belongs_to :bang
  has_one :bong, :through => :bang
end
```

All is well, until I persist an instance of Bing. If I keep updating it, the bong association is also saved, or autosaved. Only after I explicitly set a flag :autosave => false on the association it stopped. So, the has_one through association is autosavable by default(!), which looks like a bug to me. 

I went so far as debugging it all the way to a method in autosave_association called save_has_one_association, where the option[:autosave] is nil. And nil != false (line 390). I don't know if that is the reason and autosave should be false by default instead of nil. Maybe you can tell me.

I didn't test it with has_many through relations.

**Comment by rogercampos** [comment] 2015-01-09 18:16
I can confirm also this issue, setting `autosave: false` explicitly fixed it. Only happens on `has_one` associations, not `has_many`. The bug showed up after upgrading from 4.0.12 to 4.1.8.

```
[39] pry(main)> a = Cart.bound.last.user
  Cart Load (3.0ms)  SELECT  "carts".* FROM "carts"  WHERE "carts"."deleted_at" IS NULL AND "carts"."petrified" = 'f' AND ("carts"."user_id" IS NOT NULL)  ORDER BY "carts"."id" DESC LIMIT 1
  User Load (0.9ms)  SELECT  "users".* FROM "users"  WHERE "users"."deleted_at" IS NULL AND "users"."id" = $1 LIMIT 1  [["id", 63154]]
=> #<User id: 63154>
[40] pry(main)> a.cart.update_attributes(user: nil)
   (0.3ms)  BEGIN
  SQL (0.4ms)  UPDATE "carts" SET "updated_at" = $1, "user_id" = $2 WHERE "carts"."id" = 39192200  [["updated_at", "2015-01-09 17:48:53.443101"], ["user_id", nil]]
   (0.6ms)  COMMIT
=> true
[41] pry(main)> a.save
   (0.3ms)  BEGIN
  User Exists (0.5ms)  SELECT  1 AS one FROM "users"  WHERE ("users"."authentication_token" = 'xxx' AND "users"."id" != 63154) LIMIT 1
  User Exists (0.4ms)  SELECT  1 AS one FROM "users"  WHERE ("users"."previous_identity" = 'xxx' AND "users"."id" != 63154) LIMIT 1
  SQL (0.4ms)  UPDATE "carts" SET "updated_at" = $1, "user_id" = $2 WHERE "carts"."id" = 39192200  [["updated_at", "2015-01-09 17:48:55.124911"], ["user_id", 63154]]
   (0.5ms)  COMMIT
=> true
```

**Comment by jjasonclark** [comment] 2015-11-30 23:28
I've been hitting this issue as well. Although I was not able to fix the issue by setting `autosave: false` on the `belongs_to` and `has_one` associations because I'm also using `accepts_nested_attributes_for` which sets the autosave value automatically.

**Amazingly I found a solution that works.** I added the `foreign_key` value the `belongs_to` side of the association. Now I can save the model with the `has_one` in it without triggering a double save after autosaving the model with the `belongs_to` in it.

In the end, just for good measure, I added the `foreign_key` setting to both sides of the association.

**Comment by samphilipd** [comment] 2016-01-22 00:33
Digging into this today I realized that the only reason this works is because setting foreign_key disables autosave, which is what causes the double save issue.

See issue #23171

**Comment by chewi** [comment] 2016-10-10 11:10
Still seeing this in 4.2.7.1. It's happening because of this check across `save_has_one_association` and `record_changed?`.

```ruby
record[reflection.foreign_key] != id
```

This checks whether the associated record is currently pointing at a record other than self. This doesn't make sense for a through association.

**Comment by maclover7** [comment] 2016-11-02 00:20
Closing since https://github.com/rails/rails/pull/23197 / https://github.com/rails/rails/commit/c7adc610f0233b9afd51a6d68aa9061cdb250fad were merged to master.

**Closed by maclover7** 2016-11-02 00:20 UTC
Labels: activerecord, attached PR
