### ISSUE TITLE
Missing require on active_support/isolated_execution_state ?

### ISSUE THREAD

**Issue by pmustel** [rails/rails#45505] opened 2022-07-01 11:37 UTC
### Steps to reproduce

I have a small piece of  ruby code, running in bundle with gems 'ruby-kafka' and 'activesupport' Ruby-kafka uses the notifications to tell a message is produced. But it crashes. It seems to be missing a 'require' somewhere. 

It works when I add: 
require 'active_support/iloacted_execution_state'

# Your reproduction script goes here

require 'active_support/notifications'
require 'kafka'

Thread.new do
  ActiveSupport::Notifications.subscribe('produce_message.producer.kafka') do
    puts 'Hello'
  end
end

sleep 1

kafka = Kafka.new(seed_brokers: 'localhost:9092', client_id: 'maia_agent')
producer = kafka.producer
producer.produce('text', topic: 'TOPIC')

### Expected behavior

prints 'hello'

### Actual behavior

activesupport-7.0.3/lib/active_support/notifications.rb:272:in `registry': uninitialized constant ActiveSupport::IsolatedExecutionState (NameError)
	from /opt/t2data.com/develop/maia_test_suite/packages/maia_agent/local_repository/.bundle.dep/ruby/3.0.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:267:in `instrumenter'

### System configuration
activesupport-7.0.3

ruby-3.0.3

**Comment by Edouard-chin** [comment] 2022-07-01 12:31
Hello @pmustel ! The `IsolatedExecutionState` constant is autoloaded as you can see here https://github.com/rails/rails/blob/c704da66de59262f4e88824589ae4eddefb6ed4a/activesupport/lib/active_support.rb#L51 , there is no need to require it.

This same `active_support.rb` file is loaded automatically by bundler thanks to this line https://github.com/rails/rails/blob/c704da66de59262f4e88824589ae4eddefb6ed4a/railties/lib/rails/generators/rails/app/templates/config/application.rb.tt#L23. 

You should be adding a similar line to your script `Bundler.require(:default)`

**Comment by pmustel** [comment] 2022-07-01 12:39
Aha. So it works if i require whole activesupport. But I just want the notifications part... Worked OK in version 6.1.5

Works: 

require 'activesupport'
Bundle.require(:default)

Does not work: 

require 'activesupport/notifications'
Bundle.require(:default)

**Comment by Edouard-chin** [comment] 2022-07-01 12:54
> Works:
require 'activesupport'
Bundle.require(:default)

Ah yeah you are right, the second can only work work if your gemfile look like this. Ultimatelly both are the same, choose what you prefer 

```
gem "activesupport", require: "active_support"
```

**Comment by Edouard-chin** [comment] 2022-07-01 13:02
> Aha. So it works if i require whole activesupport

Just to clarify, requiring "activesupport" doesn't load the whole library, it just loads a single file (activesupport.rb). Your boot time won't be affected whatsoever. Hope this helps!

**Comment by ghiculescu** [comment] 2022-07-05 17:14
> Aha. So it works if i require whole activesupport. But I just want the notifications part... Worked OK in version 6.1.5
> 
> Works:
> 
> require 'activesupport' Bundle.require(:default)
> 
> Does not work:
> 
> require 'activesupport/notifications' Bundle.require(:default)

This used to work, but it was never intended to. https://guides.rubyonrails.org/active_support_core_extensions.html#how-to-load-core-extensions discusses how you should require Active Support. You should always have the top level require.

I'm going to close this as it's behaving as intended, but if there are any additional issues happen to re-open!

**Closed by ghiculescu** 2022-07-05 17:14 UTC
Labels: activesupport
