### ISSUE TITLE
$ rails new command fails with ruby 2.6.5p114 and rails 6.0.2.1

### ISSUE THREAD

**Issue by marvindanig** [rails/rails#38110] opened 2019-12-27 22:10 UTC
### Steps to reproduce

```
$ rails -v
Rails 6.0.2.1
$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
$ rails new tailwindapp --db=postgres

```

### Expected behavior
The rails new command fails at `$ bundle install` step. 

### Actual behavior
```
$ rails new tailwindapp --db=postgres
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/sa/Projects/ror/tailwindapp/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_0.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_6_0.rb
         run  bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.1
Using concurrent-ruby 1.1.5
Using minitest 5.13.0
Using thread_safe 0.3.6
Using zeitwerk 2.2.2
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using crass 1.0.5
Using rack 2.0.8
Using nio4r 2.5.2
Using websocket-extensions 0.1.4
Using bundler 2.1.2
Using mini_mime 1.0.2
Using public_suffix 4.0.2
Using byebug 11.0.1
Using regexp_parser 1.6.0
Using childprocess 3.0.0
Using ffi 1.11.3
Using rb-fsevent 0.10.3
Using ruby_dep 1.5.0
Using method_source 0.9.2
Using thor 1.0.1
Using rubyzip 2.0.0
Using tilt 2.0.10
Using spring 2.1.0
Using turbolinks-source 5.2.0
Using i18n 1.7.0
Using tzinfo 1.2.6
Using nokogiri 1.10.7
Using rack-test 1.1.0
Using puma 4.3.1
Using sprockets 4.0.0
Using msgpack 1.3.1
Using websocket-driver 0.7.1
Using loofah 2.4.0
Fetching sqlite3 1.4.2
Using bindex 0.8.1
Using addressable 2.7.0
Using mimemagic 0.3.3
Using rb-inotify 0.10.1
Using rack-proxy 0.6.5
Using selenium-webdriver 3.142.7
Using xpath 3.2.0
Using bootsnap 1.4.5
Using sassc 2.2.1
Using rails-html-sanitizer 1.3.0
Using marcel 0.3.3
Using listen 3.1.5
Using capybara 3.30.0
Using turbolinks 5.2.1
Using activesupport 6.0.2.1
Fetching webdrivers 4.2.0
Using mail 2.7.1
Using rails-dom-testing 2.0.3
Using globalid 0.4.2
Using activemodel 6.0.2.1
Using jbuilder 2.9.1
Using spring-watcher-listen 2.0.1
Using actionview 6.0.2.1
Using activejob 6.0.2.1
Using activerecord 6.0.2.1
Using actionpack 6.0.2.1
Using actioncable 6.0.2.1
Using activestorage 6.0.2.1
Using actionmailer 6.0.2.1
Using railties 6.0.2.1
Using sprockets-rails 3.2.1
Using actionmailbox 6.0.2.1
Using actiontext 6.0.2.1
Using sassc-rails 2.1.2
Using web-console 4.0.1
Using webpacker 4.2.2
Using rails 6.0.2.1
Using sass-rails 6.0.0
Installing webdrivers 4.2.0
Installing sqlite3 1.4.2 with native extensions
Bundle complete! 17 Gemfile dependencies, 75 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
         run  bundle exec spring binstub --all
* bin/rake: Spring inserted
* bin/rails: Spring inserted
       rails  webpacker:install
rails aborted!
LoadError: Could not open library '/Users/sa/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext/libsass.bundle': dlopen(/Users/sa/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext/libsass.bundle, 5): no suitable image found.  Did find:
	/Users/sa/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext/libsass.bundle: load commands not in a segment
	/Users/sa/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext/libsass.bundle: stat() failed with errno=25
/Users/sa/Projects/ror/tailwindapp/config/application.rb:7:in `<main>'
/Users/sa/Projects/ror/tailwindapp/Rakefile:4:in `<main>'
/Users/sa/Projects/ror/tailwindapp/bin/rails:9:in `<top (required)>'
/Users/sa/Projects/ror/tailwindapp/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
LoadError: Could not open library '/Users/sa/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/lib/sassc/libsass.bundle': dlopen(/Users/sa/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/lib/sassc/libsass.bundle, 5): no suitable image found.  Did find:
	/Users/sa/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/lib/sassc/libsass.bundle: load commands not in a segment
	/Users/sa/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/lib/sassc/libsass.bundle: stat() failed with errno=25
/Users/sa/Projects/ror/tailwindapp/config/application.rb:7:in `<main>'
/Users/sa/Projects/ror/tailwindapp/Rakefile:4:in `<main>'
/Users/sa/Projects/ror/tailwindapp/bin/rails:9:in `<top (required)>'
/Users/sa/Projects/ror/tailwindapp/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)


```

### System configuration
**Rails version**:
6.0.2.1

**Ruby version**:
2.6.5

**Comment by rafaelfranca** [comment] 2019-12-28 14:54
Thank you for the issue. The problem is in the version of sassc that is being installed. It seems to not work well with you operation system. Closing since it is not a Rails issue.

**Closed by rafaelfranca** 2019-12-28 14:54 UTC
