### ISSUE TITLE
ActionController::Live introduces a race condition when using caches_action

### ISSUE THREAD

**Issue by bschmeck** [rails/rails#37333] opened 2019-10-01 14:18 UTC
### Steps to reproduce

1. Clone [this barebones repo](https://github.com/bschmeck/live_caching_demo)
1. Run `bundle install`
2. Launch via `rails s`
3. Visit `localhost:3000/demo` in a browser and reload a few times
4. Observe `ActionDispatch::IllegalStateError` written to the terminal

To make the problem occur consistently, modify the `actionpack-action_caching` gem to sleep for a second before setting the Content-Type header here: https://github.com/rails/actionpack-action_caching/blob/6c48c98d0b59d4868ac71817bf46cbdee26467ff/lib/action_controller/caching/actions.rb#L171

### Expected behavior

The method should render without errors.

### Actual behavior

An `ActionDispatch::IllegalStateError` is raised, because the caching gem attempts to set the `Content-Type` header after the body has been written.

The docs for `ActionController::Live` very clearly state that you are not allowed to write headers after the response has been committed, but it was not apparent that the restriction applies to *all* actions in the controller, even those that don't explicitly interact with `response.stream`.

### System configuration
**Rails version**: 5.0.7

**Ruby version**: 2.5.6

**Comment by brunocalmels** [comment] 2021-06-04 12:17
I'm still experiencing this issue on `rails@6.0.0` and `actionpack-action_caching@1.2.1` on many projects. Weird there's not many more people coming across this.

**Comment by zzak** [comment] 2021-06-04 23:22
@brunocalmels Would you be able to help test if this is still an issue on the [main branch](https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller_main.rb)?

**Comment by brunocalmels** [comment] 2021-06-05 15:25
I forked @bschmeck's [repo](https://github.com/bschmeck/live_caching_demo) and updated Rails source to use [main branch](https://github.com/rails/rails). You can check it out [here](https://github.com/brunocalmels/live_caching_demo).

I confirmed the issue is not occurring any more.

**Comment by zzak** [comment] 2021-06-07 06:14
@brunocalmels Glad to hear and thanks for giving it a shot. I'm going to close this but please feel free to open a new bug report if you can reproduce it.

**Closed by zzak** 2021-06-07 06:14 UTC
