### ISSUE TITLE
Loading Interlock conflicts with explicit thread use

### ISSUE THREAD

**Issue by matthewd** [rails/rails#24028] opened 2016-03-03 14:48 UTC
Existing code that spawns a new thread and then waits on its result, where that thread triggers an autoload, can cause a deadlock in the Interlock.

We have no programmatic evidence that such a pattern is safe. The fact it's survived in the real world, however, suggests the cases we care about are in fact safe-in-practice. Generally, they're safe because the original thread is waiting for the entire time the second thread is running -- so the "only one thread can autoload" rule is still actually enforced.

---

There are two variants of this situation.

The first is where the spawned thread is just doing arbitrary work. We can detect this when it tries to autoload and notices it doesn't hold the share lock. As it's detectable, we can raise a descriptive error, and/or offer a `:trust_me` concurrency mode which allows it (again, on the basis that while we can't prove it's safe, if the code already existed [pre-interlock, it was just as unsafe.. we just weren't noticing] and was not causing weird bugs, there's a reasonable chance it's okay).

The second is where the spawned thread enters the executor. Specifically, this can come up if the spawned thread is processing requests through the application's rack middleware stack -- Capybara does this. In this case, because the callee is properly using the new APIs, I can see no way to detect that something's amiss.

---

In both cases, it's really the calling thread that's at fault: an autoload-capable thread cannot wait on another autoload-capable thread without yielding the lock. The capability to do so is new, but the problem was already there.

**Comment by thedarkone** [comment] 2016-03-04 19:27
I think we discussed that this is going to be an issue :(.

Re problem n. 2, there would be a similar complication if a thread uses external thread pools to do something (futures etc.), right?

If you have a thread in the interlock (with a sharing ticket) and want to block/sleep, the correct course of action is it to yield shares. Maybe threads attempting to gain an exclusive lock should use timed sleeps waking every 50/100ms, going over a `Thread.list` and keeping track of sharing threads that are sleeping (`thread.status == 'sleep'`), sleeping should be a no-no for a thread in an interlock, so e.g. after 2s if we notice that a thread with a share ticket is continuously sleeping - issue a descriptive warning, telling user to use `yield_shares`? Or even give up with a timeout error: "timeout on attempting to grab an interlock..."

**Comment by matthewd** [comment] 2016-03-04 19:45
Yeah, I'd anticipated "user thread operation doesn't acquire interlock -> unsafe", and that if a thread *has* acquired the interlock, it's going to have to behave (e.g., yield shares).

The one that's caught me by surprise on Capybara (& friends -- there's a `select` in poltergeist that's biting us too) is that the second thread may end up "accidentally" acquiring the lock, thus promising to conform to a contract of which it's unaware.

We're currently not as strict in yielding internally as we theoretically could be (though it'd be messier), so it's not that unreasonable to sleep while holding the lock: while waiting on an SQL query, for example.

We could, at least, go with a "no threads have moved in 20s" message if someone is waiting to acquire the exclusive lock. It wouldn't *necessarily* mean something was wrong, but properly phrased (and disableable) it might be enough to improve over the extended silent nothingness you get at the moment.

**Comment by thedarkone** [comment] 2016-03-04 19:57
> it's not that unreasonable to sleep while holding the lock: while waiting on an SQL query, for example.

Yeah, that's why I was suggesting an interrupted sleep and taking notes on shared threads. We could even check the sharing-sleeping thread's backtrace...

**Comment by sgrif** [comment] 2016-03-11 22:40
@matthewd Any updates on this? Let me know if you need some additional support to work on it.

**Comment by TikiTDO** [comment] 2016-04-09 10:30
I'd like to help to help out, but I'm having trouble figuring out how to reproduce the issue. Any chance anyone might have an example app that reproduces the problem?

**Comment by TikiTDO** [comment] 2016-04-09 12:05
Does [this](https://github.com/TikiTDO/rails_issue_24028) accurately reproduce the error in this issue?

**Comment by TikiTDO** [comment] 2016-04-09 13:52
A possible way to fix this would be to hack something like [this](https://gist.github.com/TikiTDO/cbb94b554b5b94c35f99d904b8a66124) into the Thread class. Then it's possible to do a check in the interlock on whether a parent thread owns the share lock, and let one ancestor thread through at a time.

The only concern I would have with that is whether it's fair game to write to Thread variables. I could throw a basic example together if that's the case.

**Comment by jeremy** [comment] 2016-04-26 02:28
Re. accidental lock acquisition: if we tracked thread parents (with… [hacks](https://github.com/mje113/thread-parent/blob/master/lib/thread_parent.rb#L22-L33)), we could relinquish a sleeping parent's share lock while a child acquires an exclusive lock.

**Comment by sgrif** [comment] 2016-04-26 02:32
Please no

**Comment by TikiTDO** [comment] 2016-04-28 19:24
@jeremy I actually played with that idea when I was investigating the issue, but as per my comment above that would not resolve the problem. This deadlock can happen between sibling threads, as per my example [here](https://github.com/TikiTDO/rails_issue_24028). 

Worse, this sort of use case with sibling threads can be at the mercy of the thread scheduler, leading to inconsistent behavior based on which thread happened to run first in a given run.

**Comment by jeremy** [comment] 2016-04-30 00:02
Nice exhibit, @TikiTDO. Thanks for writing that up!

**Comment by avatsaev** [comment] 2016-05-04 12:16
Is there a potential fix? It's the last blocker, would be nice to go RC already

**Comment by TikiTDO** [comment] 2016-05-04 15:27
I submitted a pull request with a potential fix above, but there has been no action or comments on it.

**Comment by sgrif** [comment] 2016-05-04 15:29
It's on our radar. Everybody on the team is quite busy and there's a back log. Thank you for your patience

**Comment by sgrif** [comment] 2016-05-06 17:11
@matthewd Is there any other action we need to take on this that should block the RC? I do want to do a better job of detecting some of the common mistakes here, but I don't think it needs to block the release, we can do it in 5.0.1

**Comment by avatsaev** [comment] 2016-05-06 17:18
@sgrif i totally agree with this, this is an edge case scenario, been open for 2 months, this shouldn't block the release, let's move this thing to RC

**Comment by eacaps** [comment] 2016-05-06 17:21
I'm all for getting a release candidate but this bug does have some people who have run into it in the wild #24741

**Comment by thedarkone** [comment] 2016-05-06 18:50
> but I don't think it needs to block the release, we can do it in 5.0.1

@sgrif btw this is a development mode issue (unless somebody is running class auto-reloading in production), so IMHO this shouldn't be a blocker.

@eacaps, your issue is a dev mode problem, right?

**Comment by sgrif** [comment] 2016-05-06 18:53
Yes. I was going to do a write up soon. We've discussed it and we think that we would still like to improve the situation, but it's not a blocker for 5.0.0.

**Comment by avatsaev** [comment] 2016-05-06 18:54
So are we moving forward now? What did you decide?

**Comment by avatsaev** [comment] 2016-05-06 19:01
finally, thank you.

**Comment by eacaps** [comment] 2016-05-09 15:28
Everything seems to work fine when I deployed my application on our heroku staging environment, so pushing to 5.0.1 will be fine. @thedarkone, any chance you could explain why this is only an issue in development mode? I'm not familiar enough with Ruby to understand the intricacies of this type of class loading.

**Comment by sgrif** [comment] 2016-05-09 15:33
Autoloading doesn't occur in production

**Comment by eacaps** [comment] 2016-05-09 15:42
So the call to

`config.channel_paths.each { |channel_path| require channel_path }`

would already have the CommentsChannel class loaded in memory and thus not run into the load_interlock issues correct?

**Comment by thedarkone** [comment] 2016-05-09 15:53
@eacaps yes. Althought It is a bit more complicated than that (e.g. a `require` call in your example will also not involve autloading even in dev mode), "autloading" is what happens when you reference a constant without first having to `require 'user'`.

There is a guide for that: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html.

**Comment by machty** [comment] 2016-06-10 14:07
I was bit by this earlier today; I'm using the ActiveAdmin gem and noticed that if I made a change to my ruby code and reloaded the page, there was about a 50% chance that some JS/CSS would take some multiple of 20s to load. I took a stacktrace of the deadlock [here](https://gist.github.com/machty/bc40406167f11b73763dff77e995aa54). It definitely seems to be an issue with interlock deadlock.

Like everyone else is saying, this doesn't cause issues on prod, and I'd also add that (somewhat obviously) if I configure puma to have a max of 1 thread to handle requests, the problem goes away on dev.

**Comment by kwasimensah** [comment] 2016-09-21 07:21
I just ran into this too a lost of couple of hours. I'd rather have const_missing throw an exception when run on not the main thread to make it clear that this usage is problematic

**Comment by grosser** [comment] 2016-09-22 18:27
FYI can be 'solved' by disabling locking ... https://github.com/zendesk/samson/pull/1301

**Comment by matthewd** [comment] 2016-09-22 18:57
@grosser if you're going to "just go back to the way rails 4 handled it which worked fine for many years", you probably want to actually do that, and not just monkey-patch a single method away.

The right way to do that:

```ruby
# if allow_concurrency was previously (under 4.2) explicitly set to true:
config.allow_concurrency = :unsafe

# if allow_concurrency was previously (under 4.2) set to nil / not set:
config.allow_concurrency = !!(config.cache_classes && config.eager_load)

# (if it was explicitly false, that's still the thing you want)
```

Rails 5 "thinks" it needs the lock because it relies on that lock to permit greater concurrency outside of production mode. If you turn off the concurrency, the lock goes away. If you neuter the lock and keep the additional concurrency, you're going to have problems.

---

@rails/issue anyone want to try to slide some of the above into the upgrading guide?

**Comment by grosser** [comment] 2016-09-22 19:03
❤️ thx for the details, will try that instead :)

**Comment by grosser** [comment] 2016-09-22 19:07
... did not work ... had `true` before, set to `:unsafe` ... still hangs :(

**Comment by grosser** [comment] 2016-09-22 19:09
since I had true neutering the lock is ok ? ... any idea what kind of trouble I should be looking for / how better to hack this ?

... or any other solution except "do not do any autoload in threads" :D

**Comment by matthewd** [comment] 2016-09-22 19:34
With `:unsafe`, we don't lock during execution: https://github.com/rails/rails/blob/5-0-stable/railties/lib/rails/application/finisher.rb#L99-L111

Do you have *overlapping* cross-thread autoloads that depend on each other? :confused: The load itself still locks under `:unsafe`, but that's really because it didn't seem like it'd matter -- all the conflicts I've seen have been due to code getting stuck holding the shared `running` lock (and thereby blocking a load).

TBH, I'd at least start by checking https://github.com/rails/rails/pull/25344 -- I understand moving on if it doesn't leap out, but so far the output I've seen from that has been pretty clear. If nothing else, you might identify some 3rd party whose lock we're not cooperating with, and you can make it their problem to find a better long-term fix.

Otherwise, yeah, I guess you're no worse off with the monkey-patch than you were/are with old-`true` / new-`:unsafe` anyway. 

The failure mode is an incompletely loaded class: thread A accesses User, triggering autoload; while User is being loaded in A, thread B accesses User, which resolves to a class, and continues. Then B raises, because the class it's holding is still missing half its methods.

**Comment by maclover7** [comment] 2016-09-22 20:19
Will open up a PR to add some upgrading docs to warn about this, and try and give some possible solutions

**Comment by grosser** [comment] 2016-09-23 02:52
tried the middleware by copy-pasting it into application.rb ...

A sleep  Waiting in start_exclusive No lock -- `5.0.0.1/lib/active_support/dependencies.rb:203:in `const_missing'` (blocks B and C)
B: sleep Sharing  blocking: A -- Queue.pop
C: sleep Sharing blocking: a -- `lib/action_controller/metal/live.rb:209` buffer.pop

I don't understand why these threads would block each other ... they are not doing the same things :(

**Comment by mohitgpt24** [comment] 2020-03-26 00:29
> Will open up a PR to add some upgrading docs to warn about this, and try and give some possible solutions

@maclover7 any updates on this?

**Comment by byroot** [comment] 2021-05-06 22:21
I'm pretty sure this is among the problems solved by Zeitwerk. Closing.

**Closed by byroot** 2021-05-06 22:21 UTC
Labels: activesupport, pinned
