### ISSUE TITLE
ActiveRecord no longer supports older PostgreSQL versions, but need to connect to those still exists

### ISSUE THREAD

**Issue by stevecj** [rails/rails#26256] opened 2016-08-23 03:19 UTC
### Steps to reproduce
Attempt to connect to a PostgreSQL 8.x database from ActiveRecord 5.x

### Expected behavior
Should work, albeit, perhaps with limited functionality. It would be fine if we had to specify a different adapter name, e.g. "postgresql-legacy"

There are many situations in which an application may need to connect to interact with databases besides its primary database. Discontinuing support for older versions of database servers that are still in common use leaves developers unable to update ActiveRecord and maintain the ability to interact with those database servers unless they give up on using ActiveRecord to do so.

### Actual behavior
RuntimeError: Your version of PostgreSQL (80316) is too old. Active Record supports PostgreSQL >= 9.1.

### System configuration
5.0.0

**Ruby version**:
2.2.5

**Comment by rafaelfranca** [comment] 2016-08-23 03:27
It is by design and we don't plan to support old database versions, sorry. 9.1 was released in 2011, so it is already 5 years since its release.

**Closed by rafaelfranca** 2016-08-23 03:27 UTC

**Comment by stevecj** [comment] 2016-08-23 03:31
I accept that the issue is closed, but to fulfill my need to grumble… In the real world, the need to connect to databases older than that still exists. ActiveRecord has many database drivers, so why not have one of them be for legacy PostgreSQL? It wouldn't even need to support migrations.

**Comment by rafaelfranca** [comment] 2016-08-23 03:34
Because someone would need to maintain that adapter and we have no interest of maintaining it.

**Comment by adiakritos** [comment] 2018-01-22 22:04
@rafaelfranca How might we go about supporting older versions of postgres? 

@stevecj Have you figured out a solution for this? Would love to hear about it! Anyone else who comes across this thread would also appreciate it as well I'm sure.

**Comment by rafaelfranca** [comment] 2018-01-22 22:18
> @rafaelfranca How might we go about supporting older versions of postgres?

I don't know. The Rails team have no interest on this.

**Comment by adiakritos** [comment] 2018-01-23 00:26
thanks

**Comment by nbaki** [comment] 2018-01-25 16:47
@rafaelfranca Could you at least point us in a useful direction or provide some tips? Your responses aren't the least bit helpful.

**Comment by rafaelfranca** [comment] 2018-01-25 17:00
Sorry, I don't know what is required for add support to old PostgreSQL version, and like I said I have no interest on investigate it because Rails will not support it.

If you really need to connect to an old version you can use Rails 4.2, upgrade your PostgreSQL version and later upgrade to Rails 5.0. Or you can for Rails and change the PostgreSQL adapter to support your version of the database.
