### ISSUE TITLE
active_model.rb

### ISSUE THREAD

**Issue by overtube** [rails/rails#50028] opened 2023-11-12 19:11 UTC
### Steps to reproduce
`gem install rails`

```
Couldn't find file to include 'activemodel/README.rdoc' from lib/active_model.rb
```

### Actual behavior
**running command** 
`gem install rails` 

### System configuration
**Rails version**:
`Rails 7.1.2`

**Ruby version**:
`ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]`

**Gem version**:
`3.4.22`

**Comment by skipkayhil** [comment] 2023-11-12 19:22
Duplicate of #49524

**Closed by skipkayhil** 2023-11-12 19:22 UTC
