### ISSUE TITLE
Undefined method `to_sql' for class `ActiveRecord::ConnectionAdapters::TableDefinition' (NameError)

### ISSUE THREAD

**Issue by piyushawasthi** [rails/rails#18750] opened 2015-01-31 13:31 UTC
I have got this bug while upgrading my app rails version '4.2.0',

/gems/activesupport-4.2.0/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `to_sql' for class `ActiveRecord::ConnectionAdapters::TableDefinition' (NameError)

**Comment by sgrif** [comment] 2015-01-31 14:30
Please provide a script that we can use to reproduce the issue, or at least a full stack trace.

**Comment by piyushawasthi** [comment] 2015-04-16 15:09
I have re-install rails but getting same error again. Will you please help me out what the reason behind that.

/gems/activesupport-4.2.1/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `to_sql' for class `ActiveRecord::ConnectionAdapters::TableDefinition' (NameError)
/gems/activesupport-4.2.1/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
/gems/redhillonrails_core-1.2.0/lib/redhillonrails_core/active_record/connection_adapters/table_definition.rb:9:in `block in included'
/gems/redhillonrails_core-1.2.0/lib/redhillonrails_core/active_record/connection_adapters/table_definition.rb:6:in `class_eval'
/gems/redhillonrails_core-1.2.0/lib/redhillonrails_core/active_record/connection_adapters/table_definition.rb:6:in `included'
from /home/user/.rvm/gems/ruby-2.1.2@thrive_final/gems/redhillonrails_core-1.2.0/lib/redhillonrails_core.rb:32:in `include'
from /home/user/.rvm/gems/ruby-2.1.2@thrive_final/gems/redhillonrails_core-1.2.0/lib/redhillonrails_core.rb:32:in `<top (required)>'
from /home/user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
from /home/user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
from /home/user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `each'
from /home/user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `block in require'
from /home/user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
from /home/user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
from /home/user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
from /home/user/.rvm/gems/ruby-2.1.2@thrive_final/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `require'
from /home/user/.rvm/gems/ruby-2.1.2@thrive_final/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
from /home/user/.rvm/gems/ruby-2.1.2@thrive_final/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
from /home/user/.rvm/gems/ruby-2.1.2@thrive_final/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
from /home/user/.rvm/gems/ruby-2.1.2@thrive_final/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
from /home/user/.rvm/gems/ruby-2.1.2@thrive_final/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'

**Comment by senny** [comment] 2015-04-24 13:33
@piyushawasthi to help you, we need to understand what's going on. Could you modify [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) to reproduce the error you are getting?

**Comment by pan** [comment] 2015-05-26 06:08
The error "`ActiveRecord::ConnectionAdapters::TableDefinition' (NameError)" looks like an issue coming from the deprecated gem redhillonrails_core which seems not working with rails 4+.  You probably want to use its successor https://github.com/lomba/schema_plus instead. I would suggest removing the activerecord label for this issue.

**Comment by senny** [comment] 2015-06-22 14:13
It's been a month without feedback. To help debug the issue we need some way to reproduce the problem in a blank rails application. As @pan pointed out this could very well be the usage of a gem that's causing issues. For the time being I'm going to close this issue. If you still experience problems, please report back with further information. Thank you :yellow_heart:

**Closed by senny** 2015-06-22 14:13 UTC
Labels: activerecord, needs feedback
