### ISSUE TITLE
Rails 6.1: Unknown key: :foreign_type in has_one association

### ISSUE THREAD

**Issue by DanielHeath** [rails/rails#40830] opened 2020-12-14 07:34 UTC
### Steps to reproduce

Use a polymorphic `has_one` relationship with a custom name for the association type.

### Expected behavior

Per rails 6 & below (and per documentation for 6.1) the foreign_type setting should be respected when looking up associations

### Actual behavior

The whole app fails to boot.

```
/home/daniel/.gem/ruby/2.6.3/gems/activesupport-6.1.0/lib/active_support/core_ext/hash/keys.rb:52:in `block in assert_valid_keys': Unknown key: :foreign_type. Valid keys are: :class_name, :anonymous_class, :primary_key, :foreign_key, :dependent, :validate, :inverse_of, :strict_loading, :autosave, :required, :touch (ArgumentError)
	from /home/daniel/.gem/ruby/2.6.3/gems/activesupport-6.1.0/lib/active_support/core_ext/hash/keys.rb:50:in `each_key'
	from /home/daniel/.gem/ruby/2.6.3/gems/activesupport-6.1.0/lib/active_support/core_ext/hash/keys.rb:50:in `assert_valid_keys'
	from /home/daniel/.gem/ruby/2.6.3/gems/activerecord-6.1.0/lib/active_record/associations/builder/association.rb:69:in `validate_options'
	from /home/daniel/.gem/ruby/2.6.3/gems/activerecord-6.1.0/lib/active_record/associations/builder/association.rb:42:in `create_reflection'
	from /home/daniel/.gem/ruby/2.6.3/gems/activerecord-6.1.0/lib/active_record/associations/builder/association.rb:32:in `build'
	from /home/daniel/.gem/ruby/2.6.3/gems/activerecord-6.1.0/lib/active_record/associations.rb:1604:in `has_one'
	from /home/daniel/projects/Radiopaedia/app/models/study.rb:23:in `<class:Study>'

```

### System configuration
**Rails version**:
6.1.0
**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by calaveraDeluxe** [comment] 2020-12-14 08:56
This line changed to only allow `:foreign_type` when `:as` is also passed:

https://github.com/rails/rails/blob/5cfd58bbfb8425ab1931c618d98b649bab059ce6/activerecord/lib/active_record/associations/builder/has_one.rb#L11

It seems `:foreign_type` was allowed without `:as` before that change:

https://github.com/rails/rails/blob/1286ab6c4951095ba1c4950f44aff6108f04d572/activerecord/lib/active_record/associations/builder/singular_association.rb#L5-L8

I'm never sure with polymorphic associations: what does `:foreign_type` even do without a polymorphic association?

**Comment by DanielHeath** [comment] 2020-12-14 09:24
Honestly I'm not clear. I have:
```
  has_one :case_component, inverse_of: :itemable, foreign_key: 'itemable_id', foreign_type: 'itemable_type'
```

The documentation for `:as` says `Specifies a polymorphic interface (See #belongs_to).`
There's no mention of `as` in the `belongs_to` documentation, so I'm not really clear on why it would be set.

**Comment by ghiculescu** [comment] 2020-12-14 23:18
@kamipo changed this in https://github.com/rails/rails/commit/2c008d9f6311d92b3660193285230505e74a114f

the comments [here](https://github.com/rails/rails/blob/5cfd58bbfb8425ab1931c618d98b649bab059ce6/activerecord/lib/active_record/associations.rb#L1541..L1546) imply that this isn't dependent on the `:as` option (but will be guessed if `:as` is provided and this isn't), which makes me think this is probably a bug.

**Comment by rafaelfranca** [comment] 2020-12-16 23:33
@kamipo can you take a look?

**Comment by kamipo** [comment] 2020-12-18 07:19
>Honestly I'm not clear. I have:
>```
>  has_one :case_component, inverse_of: :itemable, foreign_key: 'itemable_id', foreign_type: 'itemable_type'
>```

In Rails 6.0, `foreign_type: 'itemable_type'` is silently ignored unless `as: :itemable` is specified.
If you intend `foreign_type: 'itemable_type'` is used, it hadn't work as expected originally.

Looking at the above code, `inverse_of: :itemable` is a mistake for `as: :itemable`.
Use `as: :itemable` instead.

>The documentation for `:as` says `Specifies a polymorphic interface (See #belongs_to).`
There's no mention of `as` in the `belongs_to` documentation, so I'm not really clear on why it would be set separately to `inverse_of`.

`Specifies a polymorphic interface (See #belongs_to).` means that "See #belongs_to for what is a polymorphic interface, i.e. Specifies like `as: :itemable`, `:itemable` should be the name of polymorphic belongs_to (`belongs_to :imageable, ..., polymorphic: true`).

(We probably can improve the documentation though...)

**Comment by rafaelfranca** [comment] 2020-12-18 21:07
Closing since this is not a bug in the rails code it is actually found a bug in the application code. Feel free to open a PR to update the documentation.

**Closed by rafaelfranca** 2020-12-18 21:07 UTC
