### ISSUE TITLE
Trying to save a column with a type mismatch raises "Stacklevel too deep" error instead of failing gracefully.

### ISSUE THREAD

**Issue by georgemillo** [rails/rails#23241] opened 2016-01-25 19:51 UTC
This occurs on master (as of 6dfab475ca23) but doesn't seem to be occurring in 5.0.0.beta1.

Simple demo (assuming a model called `Model` with normal timestamps).

In 5.0.0.beta1:

```
m = Model.new
m.created_at = []
m.save
# => TypeError: can't cast Array
```

So far, so expected. But on 6dfab475ca23:

```
m.created_at = []
m.save
# => SystemStackError: stack level too deep
```

Note that this isn't caused by the `save` method *per se*, rather it's coming from whatever is being used to read/display created_at. E.g. I get the same error if I try `m.created_at`, `m.to_s`, or simply just typing `m` in the console (because that triggers `#inspect` which then attempts to display the `created_at` timestamp.)

Tested this with SQLite and Postgres. Note that I'm not sure if this issue is specific to date/datetime columns because I couldn't think of any other cases which would normally raise a `TypeError` (i.e. ActiveRecord can't cast the type).

**Comment by maclover7** [comment] 2016-01-25 20:06
Not able to reproduce with [this test script](https://gist.github.com/maclover7/5438c39e9ae4eed1fdee). Could you make a test script using one of the templates [here]() which reproduces the error you are seeing?

**Comment by maclover7** [comment] 2016-01-25 20:06
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)?

**Comment by georgemillo** [comment] 2016-01-25 20:40
Strangely, I can't replicate it with a test script either, but [here's a basic app](https://github.com/georgemillo/rails-issue-23241-demo) that replicates the error.

Pull it, open up the console and try `m = Model.new(created_at: [Time.now])`.

Just to confirm, I'm getting this error with Ruby MRI 2.3.0 on a Mac, and that app is loading Rails at commit `6dfab475ca23`.

**Comment by maclover7** [comment] 2016-01-25 20:46
Confirm error is occurring. Looking into right now.

**Comment by matthewd** [comment] 2016-01-25 20:47
@sgrif I haven't actually looked at this yet, so forgive me if I'm jumping the gun, but.. arrays + datetimes = https://github.com/rails/rails/commit/302e92359cc88258ae15a82454c58408a4b8157e, maybe?

**Comment by maclover7** [comment] 2016-01-25 20:51
^ +1 to @matthewd, when I use Rails at commit c1a1595740b243bed02f5e59090cc58dac77bbf3 (commit right before https://github.com/rails/rails/commit/302e92359cc88258ae15a82454c58408a4b8157e), everything's fine, but then https://github.com/rails/rails/commit/302e92359cc88258ae15a82454c58408a4b8157e causes the error. This is not caused by the sec work that landed today.

**Closed** 2016-02-02 16:19 UTC
Labels: activerecord
