### ISSUE TITLE
Rails 7.0.4 fails with rails new blog

### ISSUE THREAD

**Issue by vladsf** [rails/rails#47363] opened 2023-02-11 08:23 UTC
### Steps to reproduce
Following official [Getting Started with Rails](https://guides.rubyonrails.org/getting_started.html) run `rails new blog` and
get various errors:

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies.....
Using rake 13.0.6
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/3.0.0
Using concurrent-ruby 1.2.0
Using websocket-extensions 0.1.5
...
Fetching msgpack 1.6.0
Fetching matrix 0.4.2


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle config set --local path 'vendor/bundle'
      bundle install

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 

sudo: a password is required

```
It ends up with a broken installation of the blog example. CSS, JS files seems to be missed. Some calls work, some do not.
`bundle config set --local path 'vendor/bundle'` does not help. The generated app is still broken.

Is there way to get `rails new blog` working without `sudo`?

### System configuration
**Rails version**:
Rails 7.0.4.2
**Ruby version**:
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

**Comment by hahmed** [comment] 2023-02-11 16:43
Hey @vladsf it's very likely that you are using the system installed ruby version, which will show errors similar to the one you are seeing. 

Could you give https://www.ruby-lang.org/en/documentation/installation/ or https://gorails.com/setup/macos/13-ventura a try and see how that works?

Generally installing ruby via managers like chruby/asdf/rbenv is the way you want to go.

If this issue still persists, please do report back, I will close this as the issue is mostly about how you installed ruby (not related to rails), once that's setup properly I'm hopeful the rails install and the rest of the guide will run smoothly 🙂

**Closed by hahmed** 2023-02-11 16:43 UTC

**Comment by vladsf** [comment] 2023-02-11 17:54
> Could you give https://www.ruby-lang.org/en/documentation/installation/ or https://gorails.com/setup/macos/13-ventura a try and see how that works?

I did followed the official documentation you mentioned and used ` $ sudo apt-get install ruby-full` like the one suggests.

If Rails require the special way of installing ruby the why it is not part of **Getting Started** guide?

Why do you close it??

**Comment by zzak** [comment] 2023-02-13 02:21
I'm not familiar with debian/ubuntu these days, but I remember if you use `sudo` to install ruby then you also need `sudo` to install gems.

I would recommend using one of the installation managers mentioned here:
https://www.ruby-lang.org/en/documentation/installation/#installers
