### ISSUE TITLE
Error in Rails Guides? (Asset Pipeline: Preprocessing) 

### ISSUE THREAD

**Issue by rlue** [rails/rails#31649] opened 2018-01-08 07:49 UTC
[Section 2.5 of the Guides on the Asset Pipeline](http://guides.rubyonrails.org/asset_pipeline.html#preprocessing) state:

> In development mode, or **if the asset pipeline is disabled**, when these files are requested they are processed... and then sent back to the browser as JavaScript and CSS respectively.

But if you “disable the asset pipeline” [according to the guide’s instructions](http://guides.rubyonrails.org/asset_pipeline.html#what-is-the-asset-pipeline-questionmark),

```
$ rails new foo --skip-sprockets
```

then out-of-the-box, accessing any page that uses `layouts/application.html.erb` raises the following error in console (in development):

    ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):

or returns 404 (in production).

Am I misunderstanding the terminology used here? What is this quote intended to mean?

**Comment by IamDBiswal** [comment] 2018-01-10 10:49
@rule I attempted to reproduce your issue in development mode with Rails Version 4.2.6. The above issue can be fixed by uncommenting  require "sprockets/railtie" in application.rb.

Your application.rb should have:

require "sprockets/railtie"

**Comment by rlue** [comment] 2018-01-10 11:09
Doesn't un-commenting that line simply re-enable the asset pipeline?

> You will have to remove the comment operator on that line to later enable the asset pipeline:
>
> ```bash
> # require "sprockets/railtie"
> ```

I'm not just trying to make it work; I'm trying to understand what the guides mean when they say 

>

**Comment by rlue** [comment] 2018-01-10 11:10
Ugh fat fingers.

**Comment by composerinteralia** [comment] 2018-01-29 04:04
This does seem like a bug.

### Steps to reproduce

```
rails new foo --skip-sprockets --database=sqlite3
cd foo/
bin/setup
bin/rails generate scaffold posts
bin/rails db:migrate
bin/rails server
```

Visit `http://localhost:3000/posts` 

### Expected behavior
Page should load without errors

### Actual behavior
404s for`javascripts/application.js` and `stylesheets.css`
Also, the generated destroy button doesn't work, since the relevant javascript is not on the page.

### System configuration
**Rails version**: 5.1.4 and 5.0.6

**Ruby version**: 2.31

**Comment by matthewd** [comment] 2018-01-29 04:34
The paragraph in section 2.5 sounds like it's just wrong; "if the asset pipeline is disabled", then "when these files are requested", "they are processed by" absolutely nothing: it's the asset pipeline that arranges said processing -- whether it's at runtime, or during a precompile.

To @composerinteralia's point, I think it's fair to say that the scaffolds depend on the default javascript, and if you opt out of the asset pipeline, you're obliged to make your own arrangements to get it in there. Concretely, I don't think it would be valuable for us to specifically handle that combination of options by generating `public/javascripts/application.js` etc.

**Comment by composerinteralia** [comment] 2018-01-29 04:39
@matthewd even without scaffolds, the default layout still has `stylesheet_link_tag` and `javascript_link_tag`

**Comment by matthewd** [comment] 2018-01-29 06:28
Hmm.. I'm not sure. I guess my main point is that while a few years ago, someone using `--skip-sprockets` might reasonably have meant "keep off my lawn; I'm using hand-crafted `.js` files", today I think it's far more likely someone using that option is avoiding sprockets in favour of the new hotness -- whether that be webpack(er) or otherwise. Given that, I think I'm pretty happy to generate an application with the requested hole in the middle of it, instead of making any effort to route around; there's something to be said for leaving the edges of said hole rough/obvious.

**Comment by rlue** [comment] 2018-01-29 07:52
Thanks for looking into this, @composerinteralia and @matthewd. Before we get too far down this rabbit hole, though, I'd like to get some finality on the original question — what should the guides say?

> "if the asset pipeline is disabled", then "when these files are requested", "they are processed by" absolutely nothing: it's the asset pipeline that arranges said processing

Thank you! The sentence we're quoting begins, “In development mode, or if the asset pipeline is disabled,” when it appears it should just say, “In development mode.” In any case, the section it comes from is really about **preprocessing** (_i.e.,_ transpilation from, say, CoffeeScript to JS before concatenation/minification — not to be confused with **precompilation**), but then it takes a detour into how things behave in this case or that, and appears to be describing precompilation instead.

I'm going to work on a PR to rewrite this section (and possibly rename it, to avoid confusion with "precompilation"), unless anyone has any objections.

---

> there's something to be said for leaving the edges of said hole rough/obvious.

I think that if a built-in option for `rails new` results in a broken app, there should at least be a mention or warning of it in the generator output.

**Comment by schneems** [comment] 2018-04-16 12:34
Feel free to send a PR if you can clarify some of the language.

Regarding transpiling versus precompiling, the asset pipeline used “precompile” to refer to anything that happens between a source file on disk and an asset being served.

**Comment by schneems** [comment] 2018-04-16 12:34
Feel free to send a PR if you can clarify some of the language.

Regarding transpiling versus precompiling, the asset pipeline used “precompile” to refer to anything that happens between a source file on disk and an asset being served.

**Closed by schneems** 2018-04-16 12:34 UTC
