### ISSUE TITLE
ActiveRecord::Associations::Preloader does not eager load with conditions

### ISSUE THREAD

**Issue by jzzcoder** [rails/rails#38557] opened 2020-02-23 03:26 UTC
```ruby
# active_record_master.rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.boolean :active
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def setup
    Comment.destroy_all
    Post.destroy_all
    post1 = Post.create!
    post1.comments << Comment.create!(active: true)
    post2 = Post.create!
    post2.comments << Comment.create!(active: true)
    @posts = Post.all
    @sql_calls = []
  end

  def collect_sql
    ActiveSupport::Notifications.subscribe("sql.active_record") do |name, started, finished, unique_id, payload|
      @sql_calls.push(payload[:sql])
    end
  end

  def test_eager_loading
    ActiveRecord::Associations::Preloader.new.preload(@posts, :comments)
    collect_sql
    comments = @posts.map { |a| a.comments.to_a }.flatten
    assert_equal 2, comments.count
    assert_equal [], @sql_calls
  end

  def test_eager_loading_with_conditions
    ActiveRecord::Associations::Preloader.new.preload(@posts, :comments, Comment.where(active: true))
    collect_sql
    comments = @posts.map { |post| post.comments.where(active: true).to_a }.flatten
    assert_equal 2, comments.count
    assert_equal [], @sql_calls
  end
end
```

**Comment by eileencodes** [comment] 2020-02-24 20:49
Closing as duplicate of #38395

**Closed by eileencodes** 2020-02-24 20:49 UTC
