### ISSUE TITLE
ActiveRecord::Base.collection_cache_versioning is false once upgraded and flipped Rails.application.config.active_record.cache_versioning 

### ISSUE THREAD

**Issue by BelenRemedi** [rails/rails#39855] opened 2020-07-15 23:00 UTC
### Steps to reproduce
- Upgrade from Rails 5.2 to Rails 6.0 
- Run the update task
- Uncomment `Rails.application.config.active_record.collection_cache_versioning` in `config/initializers/new_framework_defaults_6_0.rb`

```
Loading development environment (Rails 6.0.2.2)
[1] pry(main)> ActiveRecord::Base.collection_cache_versioning
=> false
[2] pry(main)> User.limit(3).cache_version
=> nil
[3] pry(main)> Rails.application.config.active_record.collection_cache_versioning
=> true
```
### Expected behavior
ActiveRecord::Base.collection_cache_versioning configuration should be enabled.

### Actual behavior
ActiveRecord::Base.collection_cache_versioning configuration seems to be disabled and the `cache_version` for any ActiveRecord::Relation object is empty.

Note: Adding `config.active_record.collection_cache_versioning = true` to the application.rb makes it work (ActiveRecord::Base.collection_cache_versioning is true and User.limit(3).cache_version returns the `cache_version` correctly)

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**:  2.5.8

**Comment by victorperez** [comment] 2020-07-16 02:41
@BelenRemedi What is the value for `config.load_defaults` setting in `application.rb`? Since you have recently updated from `5.2` you probably have it set as `config.load_defaults 5.2`, if you want to use the rails 6 defaults then it should set as `config.load_defaults 6.0`

**Comment by victorperez** [comment] 2020-07-16 03:20
@BelenRemedi since you have recently upgraded from rails 5.2, can this be caused because you have the load defaults as `config.load_defaults 5.2` in `application.rb`? What happen if you change it to `config.load_defaults 6.0`? Does it return `true` then?

**Comment by BelenRemedi** [comment] 2020-07-16 13:19
I didn't want to change the value for `config.load_defaults` (that's 5.2) because the file `config/initializers/new_framework_defaults.rb` that is created by the upgrade task allow us to flip new defaults one by one.

**Comment by victorperez** [comment] 2020-07-16 14:34
Sorry but this is not replicable so just trying to get all the information that I can.

I created a new `5.2.0` and changed the Gemfile to use `6.0.2.2` then run `rails app:update` to  generate the `new_framework_defaults.rb` file and uncomment the `Rails.application.config.active_record.collection_cache_versioning = true` in the initializer, after that this is the output of the rails console:

```
Loading development environment (Rails 6.0.2.2)
2.7.1 :005 > ActiveRecord::Base.collection_cache_versioning
 => true
2.7.1 :006 > User.limit(3).cache_version
 => "0"
2.7.1 :007 > Rails.application.config.active_record.collection_cache_versioning
 => true
```

Here is the demo app in case you want to review it: https://github.com/victorperez/rails-collection-cache-versioning

**Comment by BelenRemedi** [comment] 2020-07-16 15:44
You're right, it's not replicable in a new app. I tried the same as you and couldn't reproduce it 😕 So it seems to be something specific to our existing app. 
Sorry and thank you!!

**Comment by victorperez** [comment] 2020-07-16 18:24
This could be caused by some gem that your application is using.

I did some testing installing some gems in the demo app (which was working correctly) and after install `stringex` gem (https://github.com/rsl/stringex) I can experience the same behaviour you are describing in this issue.

So I would recommend to review if any gem is using cause this behaviour in your app. If your app is also using the `stringex` gem then have a winner!

**Comment by eugeneius** [comment] 2020-07-16 21:00
Some previous reports of the same problem: https://github.com/rails/rails/issues/23589, https://github.com/rails/rails/issues/27844, https://github.com/rails/rails/issues/33283, https://github.com/rails/rails/issues/36322, https://github.com/rails/rails/issues/37030.

The cause is often a misbehaving gem, but it's also possible that the application itself is loading the framework prematurely. https://github.com/rails/rails/pull/38024 proposes to print a warning when this happens, although it seems to be stalled a bit.

For now, there's a useful tip here: https://github.com/rails/rails/issues/37030#issuecomment-524511912

If you add `ActiveSupport.on_load(:active_job) { puts caller }` to `config/application.rb`, after `require 'rails/all'` but before `Bundler.require`, you'll get a stacktrace that should identify the code that's loading the framework too early.

I'm going to close this since it's not a bug in Rails, although I'm eager to see https://github.com/rails/rails/pull/38024 or something like it introduced.

**Closed by eugeneius** 2020-07-16 21:00 UTC

**Comment by BelenRemedi** [comment] 2020-07-17 13:56
That's interesting. I'll try identifying the code that's loading the framework too early.
Thank you @eugeneius for clarifying this and the tips!
