### ISSUE TITLE
PostgreSQL view regression in Rails 7.1 in RETURNING logic

### ISSUE THREAD

**Issue by edwinv** [rails/rails#50474] opened 2023-12-28 15:48 UTC
### Steps to reproduce

While upgrading our Rails app to 7.1 we noticed a behavior change in PostgreSQL views. This is caused by the changes in https://github.com/rails/rails/pull/48241 by @nvasilevski @eileencodes The issue hasn't been noticed because the tests are not complete. To make the tests cover the situation better, change `activerecord/test/cases/view_test.rb:189` to assert also the presence of the `id` field after insert:

```ruby
      def test_insert_record
        new_record = PrintedBook.create! name: "Rails in Action", status: 0, format: "paperback"
        assert new_record.id

        new_book = PrintedBook.last
        assert_equal "Rails in Action", new_book.name
      end
```

Fetching the last record will always succeed, because the `id` field on the initial record is not used. Before commit 3421e892afa532a254e54379ac2ce9bef138cf3f this test passed, after the commit the test fails:

```console
$ git checkout 3421e892afa532a254e54379ac2ce9bef138cf3f^
$ ARCONN=postgresql bundle exec ruby -Itest test/cases/view_test.rb -n test_insert_record
1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
$ git checkout 3421e892afa532a254e54379ac2ce9bef138cf3f
$ ARCONN=postgresql bundle exec ruby -Itest test/cases/view_test.rb -n test_insert_record
Failure:
UpdateableViewTest#test_insert_record [test/cases/view_test.rb:191]:
Expected nil to be truthy.


bin/rails test test/cases/view_test.rb:189
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

### Expected behavior

[A simple VIEW in PostgreSQL is automatically updatable.](https://www.postgresql.org/docs/current/sql-createview.html) Insert statements on the view are perfectly fine. The resulting record should have the `id` attribute filled, like any other PostgreSQL table.

### Actual behavior

The `id` field is empty. The record states that it is persisted, but no `id` is present, causing issues with using the record after saving it.

### System configuration
**Rails version**: tested on the `main` branch against the specific commit

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment] 2023-12-28 15:52
Can you verify that https://github.com/rails/rails/pull/49955 fixes this issue?

**Comment by edwinv** [comment] 2023-12-28 15:56
Yes, it does! Great to see this situation being added as a test case in the PR.

**Comment by fatkodima** [comment] 2023-12-28 16:38
Duplicate of https://github.com/rails/rails/issues/49950

**Closed by fatkodima** 2023-12-28 16:38 UTC
