### ISSUE TITLE
Params wrapper should come before instrumentation [...]

### ISSUE THREAD

**Issue by mvastola** [rails/rails#22898] opened 2016-01-03 00:36 UTC
As of the most recent change to the file (8e489db9dee1f4cfb0c3a259bd59626d86eacb07), lines 239-246 of [actionpack/lib/action_controller/base.rb](https://github.com/rails/rails/blob/8e489db9dee1f4cfb0c3a259bd59626d86eacb07/actionpack/lib/action_controller/base.rb#L239)  constitute the end of the list of the modules included (in order) into `ActionController::Base`.

The contents of these lines are as follows:
```
  # Add instrumentations hooks at the bottom, to ensure they instrument
  # all the methods properly.
  Instrumentation,
  # Params wrapper should come before instrumentation so they are
  # properly showed in logs
  ParamsWrapper
]
```

I am not certain if this is a situation wherein the code was changed and the commenting just needs to be updated, or if the code itself is incorrect, (the later obviously makes this a higher priority) but either way, a fix should probably be made.

**NOTE: The same exact code (and thus the same exact error) is present in [actionpack/lib/action_controller/api.rb](https://github.com/rails/rails/blob/8e489db9dee1f4cfb0c3a259bd59626d86eacb07/actionpack/lib/action_controller/api.rb).**

**Comment by mvastola** [comment] 2016-01-03 00:39
`Blame` points to @josevalim and @jstorimer as modifying the lines of code in question in `base.rb` and @jmbejar as doing so in `api.rb`, so I am tagging them all in case any of them can offer insight into the best way to address this issue for the code they contributed/worked on.

**Comment by jmbejar** [comment] 2016-01-05 17:09
@mvastola I was not directly involved on changes related with the modules `Instrumentation` and `ParamsWrapper` (since I've just copied part of what we have in `actionpack/lib/action_controller/base.rb` to `actionpack/lib/action_controller/api.rb`, but I did some reseach.

I tested changing the order of those modules, so I confirmed we need to execute first the code to wrap parameters, which makes sense for JSON requests. Otherwise, the parameters that you would see in the logs are the values before wrapping them.

It seems that `ParamsWrapper` was deliberated put right after `Instrumentation` in the code for this reason. Although time spent on wrapping params is not being count by `Instrumentation`, it's probably not so important compared with render time, db time and so.

Regarding the comment in the code, I suppose `Params wrapper should come before instrumentation` means that params wrapper should come before instrumentation in _execution time_ rather than in the source file (which are opposite concepts).
Is this your point of concern regarding the comment text? (Disclaimer: I'm not English native speaker, so it's just my humble guess in the meaning of the sentence).

In any case, I would close the issue.

**Comment by mvastola** [comment] 2016-01-05 17:36
> Is this your point of concern regarding the comment text? 

Yes. I don't think your explanation makes sense though because the comment before is:
```
  # Add instrumentations hooks at the bottom, to ensure they instrument
  # all the methods properly.
```

**Comment by jmbejar** [comment] 2016-01-05 17:53
Ok I didn't read the other comment lines. At least, we can confirm that the code is correct and behaving as expected. The issue is only related with the comments.

**Comment by mvastola** [comment] 2016-01-05 18:53
True. That's a plus. So this is a comment error and thus low priority. Now that I know, I'll make a PR.

**Comment by rafaelfranca** [comment] 2016-01-06 00:45
Feel free to send the pull request. I'm closing this since it is not an issue.

**Closed by rafaelfranca** 2016-01-06 00:45 UTC
