### ISSUE TITLE
Callbacks called twice when child accepts_nested_attributes_for parent

### ISSUE THREAD

**Issue by jakemiller13** [rails/rails#48688] opened 2023-07-07 16:25 UTC
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :name
  end
end

class Post < ActiveRecord::Base
  has_one :comment

  before_validation :before_validation_callback_post
  after_validation :after_validation_callback_post

  before_save :before_save_callback_post
  after_save :after_save_callback_post

  before_create :before_create_callback_post
  after_create :after_create_callback_post

  def before_validation_callback_post
    puts 'Post: before_validation_callback'
  end

  def after_validation_callback_post
    puts 'Post: after_validation_callback'
  end

  def before_save_callback_post
    puts 'Post: before_save_callback'
  end

  def after_save_callback_post
    puts 'Post: after_save_callback'
  end

  def before_create_callback_post
    puts 'Post: before_create_callback'
  end

  def after_create_callback_post
    puts 'Post: after_create_callback'
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post

  accepts_nested_attributes_for :post

  before_validation :before_validation_callback_comment
  after_validation :after_validation_callback_comment

  before_save :before_save_callback_comment
  after_save :after_save_callback_comment

  before_create :before_create_callback_comment
  after_create :after_create_callback_comment

  def before_validation_callback_comment
    puts 'Comment: before_validation_callback'
  end

  def after_validation_callback_comment
    puts 'Comment: after_validation_callback'
  end

  def before_save_callback_comment
    puts 'Comment: before_save_callback'
  end

  def after_save_callback_comment
    puts 'Comment: after_save_callback'
  end

  def before_create_callback_comment
    puts 'Comment: before_create_callback'
  end

  def after_create_callback_comment
    puts 'Comment: after_create_callback'
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    Comment.create!(name: 'foo', post_attributes: {name: 'bar'})
  end
end

```

### Expected behavior
`before_validation`, `after_validation`, `before_save`, `after_save` callbacks should only be called once when saving a parent record that accepts nested attributes for a child record. Note that `before_create`, `after_create` callbacks **are** only called once, so this inconsistency is especially confusing.

### Actual behavior
`before_validation`, `after_validation`, `before_save`, `after_save` are all called twice on parent record.

```
(base) m-apd-jmiller:models jmiller$ ruby active_record_main.rb 
Fetching https://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Using rake 13.0.6
Using connection_pool 2.4.1
Using minitest 5.18.1
Using webrick 1.8.1
Using erubi 1.12.0
Using rack 3.0.8
Using websocket-extensions 0.1.5
Using marcel 1.0.2
Using rack-test 2.1.0
Using bundler 2.4.7
Using websocket-driver 0.7.5
Using nio4r 2.5.9
Using zeitwerk 2.6.8
Using date 3.3.3
Using timeout 0.4.0
Using builder 3.2.4
Using io-console 0.6.0
Using racc 1.7.1
Using crass 1.0.6
Using thor 1.2.2
Using sqlite3 1.6.3 (x86_64-darwin)
Using rack-session 2.0.0
Using mini_mime 1.1.2
Using rackup 2.1.0
Using concurrent-ruby 1.2.2
Using net-protocol 0.2.1
Using reline 0.3.5
Using i18n 1.14.1
Using net-imap 0.3.6
Using nokogiri 1.15.3 (x86_64-darwin)
Using net-pop 0.1.2
Using net-smtp 0.3.3
Using loofah 2.21.3
Using irb 1.7.1
Using rails-html-sanitizer 1.6.0
Using tzinfo 2.0.6
Using mail 2.8.1
Using activesupport 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using activemodel 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using rails-dom-testing 2.1.1
Using activerecord 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using actionview 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using globalid 1.1.0
Using actionpack 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using activejob 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using actioncable 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using activestorage 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using actionmailer 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using actionmailbox 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using actiontext 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using railties 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
Using rails 7.1.0.alpha from https://github.com/rails/rails.git (at main@a5fc471)
-- create_table(:posts, {:force=>true})
D, [2023-07-07T12:17:20.483607 #2897] DEBUG -- :    (0.1ms)  DROP TABLE IF EXISTS "posts"
D, [2023-07-07T12:17:20.485077 #2897] DEBUG -- :    (1.1ms)  CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar)
   -> 0.0286s
-- create_table(:comments, {:force=>true})
D, [2023-07-07T12:17:20.485698 #2897] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "comments"
D, [2023-07-07T12:17:20.486042 #2897] DEBUG -- :    (0.1ms)  CREATE TABLE "comments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "post_id" integer, "name" varchar)
   -> 0.0009s
D, [2023-07-07T12:17:20.488263 #2897] DEBUG -- :    (0.1ms)  CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY)
D, [2023-07-07T12:17:20.490839 #2897] DEBUG -- :    (0.1ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2023-07-07T12:17:20.532633 #2897] DEBUG -- :   ActiveRecord::InternalMetadata Load (2.7ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
D, [2023-07-07T12:17:20.533215 #2897] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ('environment', 'development', '2023-07-07 16:17:20.532735', '2023-07-07 16:17:20.532743')
Run options: --seed 61519

# Running:

Comment: before_validation_callback
Post: before_validation_callback
Post: after_validation_callback
Comment: after_validation_callback
Post: before_save_callback
Post: before_create_callback
D, [2023-07-07T12:17:20.661392 #2897] DEBUG -- :   TRANSACTION (0.1ms)  begin transaction
D, [2023-07-07T12:17:20.661656 #2897] DEBUG -- :   Post Create (0.4ms)  INSERT INTO "posts" ("name") VALUES (?)  [["name", "bar"]]
Comment: before_validation_callback
Comment: after_validation_callback
Comment: before_save_callback
Comment: before_create_callback
D, [2023-07-07T12:17:20.662908 #2897] DEBUG -- :   Comment Create (0.1ms)  INSERT INTO "comments" ("post_id", "name") VALUES (?, ?)  [["post_id", 1], ["name", "foo"]]
Comment: after_create_callback
Comment: after_save_callback
Post: after_create_callback
Post: after_save_callback
Comment: before_save_callback
Comment: after_save_callback
D, [2023-07-07T12:17:20.663528 #2897] DEBUG -- :   TRANSACTION (0.1ms)  commit transaction
```

### System configuration
**Rails version**: 5.2.8.1, 7.0.6 (tested both)

**Ruby version**: 2.7.6, 3.2.1 (tested both)

**Comment by RobertChang0722** [comment] 2023-07-18 19:16
This only happens when the model itself `belongs_to` a model and use `accepts_nested_attributes_for the belongs_to model`

So if you use Post `accepts_nested_attributes_for :comment` this bug will not occur.

I haven't had time to organize the tests yet, but this is the result of the manual tests so far.

**Comment by joshuay03** [comment] 2023-10-19 22:53
> @joshuay03 happy to update the title but I'm not sure I understand what change you are suggesting.

@jakemiller13 Your title says "parent accepts_nested_attributes_for child", which is the usual case, but in your reproduction script it's the child that accepts_nested_attributes_for for the parent.

**Comment by jakemiller13** [comment] 2023-10-20 14:14
🤦🏼‍♂️ 

Thanks @joshuay03

**Comment by joshuay03** [comment] 2023-10-23 10:58
So I had a quick look into this today and the issue is that the [autosave logic for `has_one`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/autosave_association.rb#L434-L472) simply doesn't account for records that were previously new records, which covers this issue scneario where the child is saved, then the parent is saved via autosaved (because of nested attributes), and then the child is saved again because it's a 'new' associated record'.

You can also replicate it without passing in the nested attributes directly:
```ruby
Comment.create!(name: "foo", post: Post.new(name: "bar"))
```

This issue is exactly the same as `https://github.com/rails/rails/pull/39771` but for `has_one` (changing the association from `has_one :comment` to `has_many :comments` results in no duplicates). I think it can be fixed in a similar way by accounting for records that were previously new records therefore skipping the save logic (including callbacks).

I'll get a PR up as soon as I can. I've got rid of the duplicates for now, just figuring out some unrelated test failures.

**Closed** 2024-07-08 17:00 UTC
Labels: activerecord, attached PR
