### ISSUE TITLE
Calling escape_javascript is slow

### ISSUE THREAD

**Issue by benubois** [rails/rails#38071] opened 2019-12-22 19:47 UTC
<img width="1157" alt="Screen Shot 2019-12-22 at 8 33 14 PM" src="https://user-images.githubusercontent.com/133809/71326473-91385200-24fb-11ea-8fd9-a53d57004573.png">

The large performance penalty seems to be a side effect of calling `escape_javascript`. Performance seems fine when calling `escape_javascript` by itself.

### Steps to reproduce

I'm not able to reproduce this with the single-script templates. This script will setup a rails app that demonstrates the issue.

```bash
#!/bin/bash

gem install rails

rails new blog        \
--skip-action-mailer  \
--skip-action-mailbox \
--skip-action-text    \
--skip-active-record  \
--skip-active-storage \
--skip-action-cable   \
--skip-sprockets      \
--skip-spring         \
--skip-listen         \
--skip-javascript     \
--skip-turbolinks     \
--skip-test

mkdir -p blog/app/views/users

cat > blog/app/views/layouts/application.html.erb <<- EOF
<!DOCTYPE html>
<html>
  <body>
    <%= yield %>
  </body>
</html>
EOF

cat > blog/config/routes.rb <<- EOF
Rails.application.routes.draw do
  resources :users do
    collection do
      get :escape_javascript
      get :no_escape_javascript
    end
  end
end
EOF

cat > blog/app/controllers/users_controller.rb <<- EOF
class UsersController < ApplicationController
  def escape_javascript
    @collection = (1..100).to_a
  end

  def no_escape_javascript
    @collection = (1..100).to_a
  end
end
EOF

cat > blog/app/views/users/escape_javascript.html.erb <<- EOF
<%= escape_javascript render partial: "user", collection: @collection, as: :user %>
EOF

cat > blog/app/views/users/no_escape_javascript.html.erb <<- EOF
<%= render partial: "user", collection: @collection, as: :user %>
EOF

cat > blog/app/views/users/_user.html.erb <<- EOF
<li>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
</li>
EOF

blog/bin/rails server
```

Then visit the following URLs and observe the response time in the log.

1. [http://localhost:3000/users/escape_javascript](http://localhost:3000/users/escape_javascript)
2. [http://localhost:3000/users/no_escape_javascript](http://localhost:3000/users/no_escape_javascript)

### Expected behavior

Calling `escape_javascript` should be slightly slower than not calling it.

### Actual behavior

Performance is many times slower.

### System configuration
**Rails version**:

6.0.2.1

**Ruby version**:

2.6.5

**Comment by kaspth** [comment] 2019-12-22 20:35
Thanks, you're welcome to try a PR, it'd need an isolated benchmark too. I'll close this as it's not a bug, it's just the current performance of `escape_javascript`.

**Closed by kaspth** 2019-12-22 20:35 UTC

**Comment by benubois** [comment] 2019-12-22 20:43
Hi @kaspth,

Ok, I'll try looking into it more. However, I don't think it is just the current performance of `escape_javascript`. Calling `escape_javascript` by itself has fine performance.

Thanks!

**Comment by benubois** [comment] 2019-12-22 20:45
Oh, also, I think it is a regression. I first encountered it when upgrading from 5.1.7 to 6.0.2.

**Comment by kaspth** [comment] 2019-12-22 21:12
Even better case for a `benchmark-ips` benchmark, yeah 😄

Seems like it could be contingent on string length too, considering the passing a whole bunch of rendered partials.
