### ISSUE TITLE
Errors reported when ActionMailer emails are sent via ActiveJob do not filter mailer params, potentially leak sensitive data

### ISSUE THREAD

**Issue by tekin** [rails/rails#52965] opened 2024-09-18 11:25 UTC
When ActiveJob fails trying to send an ActionMailer email it does not filter mailer params, potentially leaking sensitive data.

### Steps to reproduce

For example:

```ruby

Rails.application.config.filter_parameters = ["email_address"]

class ExampleMailer < ActionMailer::Base
  default to: -> { params.fetch(:email_address) }

  def hello
    @message = "Hello, world"

    mail from: "test@example.com"
    raise "hell"
  end
end

ExampleMailer.with(email_address: 'recipient@example.com').hello.deliver_later
```

The reported error will include the params from the email unfiltered in the serialised params, even with `"email_address"` configured in `Rails.application.config.filter_parameters`.

### Expected behavior

The same parameter filtering applied to web requests should also be applied to serialised mailer params.

### Actual behavior

The params from the mailer are included unfiltered in the reported parameters from the job:

```ruby
[
  "ExampleMailer",
  "hello",
  "deliver_now",
  {
    "_aj_ruby2_keywords": [
      "params",
      "args"
    ],
    "args": [],
    "params": {
      "_aj_symbol_keys": [
        "email_address",
      ],
      "email_address": "recipient@example.com"
    }
  }
]
```

**Comment by fatkodima** [comment] 2024-09-18 12:55
> The params from the mailer are included unfiltered in the reported parameters from the job:

Do you mean in the logs? Or in some other place too?

**Comment by fatkodima** [comment] 2024-09-18 13:42
Which error reporting service and gem for it do you use?

**Comment by tekin** [comment] 2024-09-18 13:45
> Which error reporting service and gem for it do you use?

We're using [appsignal](https://github.com/appsignal/appsignal-ruby), with Sidekiq as our background job processor.

**Comment by tekin** [comment] 2024-09-18 14:20
> Looks like this is an issue with that gem. They need to filter data before sending it to their services. https://github.com/appsignal/appsignal-ruby/blob/17319445904db986551ce49b93405f459d56388c/lib/appsignal/integrations/railtie.rb#L69-L75
> 
> When the job is running, it contains `{job: <instance of a job>}` as its context
> 
> https://github.com/rails/rails/blob/c0807dc6c2f83b9e65bfdc45d52d8d36ddf5e897/activejob/lib/active_job/execution.rb#L66
> 
> which is then used as part of the `:context` for `Rails.error.report`.
> Would you mind opening an issue report there too?

Is that definitely the case? Rails already does automatic filtering of `params` as part of requests such that they are filtered from exceptions before they bubble up to any subscribing services.

**Comment by bdewater** [comment] 2024-09-18 14:24
This seems like a duplicate of earlier PRs attempting to add controller-style param filtering for jobs, here's a write up on the current state: https://github.com/rails/rails/pull/34438#issuecomment-2336749226

**Comment by fatkodima** [comment] 2024-09-18 14:33
Yeah, so that is for logging which should be solved on the rails side. But I still think this is a problem with appsignal gem. It does not filter what we have in the `:context` when sending data to their services.

**Comment by tekin** [comment] 2024-09-18 15:25
Thanks @bdewater that's useful to see, I'll be sure to configure our sensitive jobs to not log parameters.

Thanks also @fatkodima, I'll speak with the folks at AppSignal to see if automatic filtering of job params based on the configured filters makes sense or not. It's definitely possible to configure filtered params directly for AppSignal, but feels like it should filter out anything in `Rails.application.config.filter_parameters` by default.

**Closed** 2024-09-18 15:25 UTC
Labels: activejob
