### ISSUE TITLE
Cannot pass options to cache_store memory_store 

### ISSUE THREAD

**Issue by kritik** [rails/rails#38532] opened 2020-02-20 16:08 UTC
### Steps to reproduce
1.In Gemile `gem 'rails', git: 'https://github.com/rails/rails.git', branch: '6-0-stable'`
2. in development.rb `config.cache_store = :memory_store, { size: 64.megabytes }` as proposed in [guides](https://guides.rubyonrails.org/caching_with_rails.html#configuration). 
3. rails s

Seems that [this commit](https://github.com/rails/rails/commit/9845cd6338e44d9fff39ea1cd64851af085133ac) sends several params to cache store. But MemoryStore is not updated to receive more params https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache/memory_store.rb#L21

### Expected behavior
Rails should be started

### Actual behavior
/memory_store.rb:21:in `initialize': wrong number of arguments (given 2, expected 0..1) (ArgumentError)

### System configuration
**Rails version**: 6.0.2.1 eef309eb6dda64fe39e51daa408c91f793cd17e7

**Ruby version**:
ruby -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]

### Last lines
```
	 6: from /Users/Vladimir/.rvm/gems/ruby-2.6.0@shoperb/bundler/gems/rails-eef309eb6dda/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	 5: from /Users/Vladimir/.rvm/gems/ruby-2.6.0@shoperb/bundler/gems/rails-eef309eb6dda/railties/lib/rails/initializable.rb:32:in `run'
	 4: from /Users/Vladimir/.rvm/gems/ruby-2.6.0@shoperb/bundler/gems/rails-eef309eb6dda/railties/lib/rails/initializable.rb:32:in `instance_exec'
	 3: from /Users/Vladimir/.rvm/gems/ruby-2.6.0@shoperb/bundler/gems/rails-eef309eb6dda/railties/lib/rails/application/bootstrap.rb:59:in `block in <module:Bootstrap>'
	 2: from /Users/Vladimir/.rvm/gems/ruby-2.6.0@shoperb/bundler/gems/rails-eef309eb6dda/activesupport/lib/active_support/cache.rb:60:in `lookup_store'
	 1: from /Users/Vladimir/.rvm/gems/ruby-2.6.0@shoperb/bundler/gems/rails-eef309eb6dda/activesupport/lib/active_support/cache.rb:60:in `new'
/Users/Vladimir/.rvm/gems/ruby-2.6.0@shoperb/bundler/gems/rails-eef309eb6dda/activesupport/lib/active_support/cache/memory_store.rb:21:in `initialize': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
```

**Comment by hahmed** [comment] 2020-02-21 10:28
@kritik mind posting an app that reproduces this error please?

**Comment by kritik** [comment] 2020-02-22 14:08
@hahmed do you want zip file or repo?

**Comment by hahmed** [comment] 2020-02-22 15:36
@kritik if you can post a link to a Github repo that would be nice, once the issue is replicated, I can have a look into the issue 👍🏼

**Comment by kritik** [comment] 2020-02-23 07:50
@hahmed, will do but @eugeneius patch seems to be working

**Comment by kritik** [comment] 2020-02-23 07:56
@hahmed Here's repo https://github.com/kritik/rails_cache_example

**Comment by hahmed** [comment] 2020-02-24 10:45
@kritik thanks for repo the issue, can you check your repo against master please? I believe the issue has been fixed in `https://github.com/rails/rails/commit/fa986ae0cac423bf1ebcb5caeccbecf00c990094`

**Comment by kritik** [comment] 2020-02-24 10:54
@hahmed Yes, you're right. It works! So, stable is not so stable? :) Seems this ticket and pull request are unnecessary anymore, however I would put that commit to stable branch as well.

**Comment by hahmed** [comment] 2020-02-24 11:18
Glad we could get to the bottom of the issue!

> however I would put that commit to stable branch as well.

@eugeneius I'm assuming that commit does not need to go into the branch `branch: '6-0-stable'`?

**Comment by kamipo** [comment] 2020-02-24 17:37
Backported fa986ae0cac423bf1ebcb5caeccbecf00c990094  to 6-0-stable 5813aac648c86068c38f1c146ed15c261b41985b.

**Closed by kamipo** 2020-02-24 17:37 UTC
Labels: activesupport, regression
