### ISSUE TITLE
rescue_from rescues from unexpected classes

### ISSUE THREAD

**Issue by natematykiewicz** [rails/rails#35930] opened 2019-04-10 22:25 UTC
### Steps to reproduce
Raise an `ActiveRecord::RecordNotFound` error. Rescue that error and raise your own custom class. Add `rescue_from ActiveRecord::RecordNotFound, with: -> { head(:not_found) }` to your controller.

### Expected behavior
Trigger your series of errors, and see that the custom error class is raised, resulting in the action erroring.

### Actual behavior
See the `rescue_from` you added is catching your custom error and rendering a 404, even though the error class is different. It turns out, the reason this is happening, is because the `cause` of the error is an `ActiveRecord::RecordNotFound` error, and the `cause` matches my `rescue_from`.

I guess I don't understand why anyone would ever want to match the cause of the error. That's the whole point of rescuing specific error classes and raising your own custom error classes. It would be nice to be able to at least configure away this behavior as it's very counterintuitive to me as it's not how `rescue` works. I was under the impression that `rescue_from` was essentially a global `rescue` handler, and today I learned that it's quite different.

Admittedly I never knew that `exception.cause` existed until I dug through the source code. Today I wrote the following on my custom error class, to work around this behavior:

```ruby
def cause
  nil
end
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.0

**Comment by rafaelfranca** [comment] 2019-04-11 20:09
Thank you for the issue.

That is the behavior since Rails 5.1 https://github.com/rails/rails/commit/e35b98e6f5c54330245645f2ed40d56c74538902#diff-4be3c90df95ede75a8d48016f370c0d9R1.

But I agree we should have a way to disable it. Can you open a PR?

Closing since this is not an issue, but a feature request.

**Closed by rafaelfranca** 2019-04-11 20:09 UTC

**Comment by natematykiewicz** [comment] 2019-04-11 20:46
@rafaelfranca That's not the commit that did it. That one removes custom ActionContoller logic in favor of the `ActiveSupport::Rescuable` logic, while also adding `rescue_from` to ActionMailer.

The true culprit is https://github.com/rails/rails/commit/266455cf25aba942b8717ceb0269d66f719b5696#diff-81f758fb88f738604ba750f9dde1f6bb
(This PR: https://github.com/rails/rails/pull/18774)

This commit changed from using `original_exception` (something that Rails errors explicitly opted in to when an exception for sure should be unwrapped) and replaced it with `cause` (something that **_ALL_** errors have). I know it was over 3 years, ago, but the switch from `original_exception` to `cause` seems very short-sighted to me. The PR even points out the difference. I'm just shocked that such a major regression would be introduced, without making you opt in explicitly.

Even this comment agrees that it feels problematic: https://github.com/rails/rails/pull/18774#issuecomment-188544516

It feels like the Rails core team decided to do this to simplify internal code, without thinking about the public API at all. 😢

**Comment by Webovani** [comment] 2021-01-20 18:25
Just spent two hours trying to find out what's wrong and which development gem may be causing such nonsense. And I am pretty surprised it's actually Rails! 

My usage:

ApplicationController:
```ruby
  rescue_from ActiveRecord::RecordNotFound do |exception|
    redirect_to root_path, { alert: "Object not found." }
  end
```
Setting (model):
```ruby
class SettingMissing < RuntimeError; end

def self.[](name)
  find_by_name!(name).converted_value
rescue ActiveRecord::RecordNotFound
  raise SettingMissing, "Missing setting '#{name}'"
end
```
I expect the app to crash when a Setting is missing (it's a developer error). That's why I am raising a custom error. RecordNotFound error is handled. I just handled it by raising something else. But rescue_from will rather match the cause of the exception instead of exception that is actually thrown. It doesn't make any sense to me.

```ruby
def self.[](name)
  ...
rescue ActiveRecord::RecordNotFound
  i_cant_even_tyep / 0
end
```

Whatever error happens in the rescue clause is masked by the RecordNotFound exception, so even if you know about the behavior and like it, it will cost you dearly some time, when anything unexpected happens while handling exception and you will never find it.

And there is no mention of this behavior in `rescue_from` documentation and you have to dig around to find out why.

I think documentation update is needed to avoid confusion. 
And until there is a possibility to turn off the cause-following behavior or detect that the handled exception is not the thrown one, I need to find out some alternative solution.

**Comment by natematykiewicz** [comment] 2021-01-20 18:40
I still think it's actually a regression, though we're only noticing it a few years later.
