### ISSUE TITLE
ENV['RAILS_RELATIVE_URL_ROOT'] and url_for

### ISSUE THREAD

**Issue by julian7** [rails/rails#5122] opened 2012-02-21 21:32 UTC
I wanted to deploy a rails app into a subdirectory, and setting RAILS_RELATIVE_URL_ROOT env var works pretty well... except, it is not used in any REST-like route generation.

```shell
horadrim:~/Code>>% rails new relative_url_root_test
Using -T --skip-bundle from /Users/js/.railsrc
...
horadrim:~/Code>>% cd relative_url_root_test
horadrim:~/Code/relative_url_root_test>>% bundle --path vendor --binstubs
Fetching gem metadata from https://rubygems.org/.........
...
horadrim:~/Code/relative_url_root_test>>% script/rails g scaffold page title:string body:text
...
horadrim:~/Code/relative_url_root_test>>% bin/rake db:migrate
...
horadrim:~/Code/relative_url_root_test>>% RAILS_RELATIVE_URL_ROOT=/subdir script/rails c
Loading development environment (Rails 3.2.1)
irb(main):001:0> app.url_for Page
=> "http://www.example.com/pages"
```

Shouldn't it be http://www.example.com/subdir/pages ?

**Comment by coldnebo** [comment] 2015-01-02 20:56
I don't have time to write up tests, etc, but as I recall from previous times I researched this: Passenger/Apache handles suburi paths (e.g. http://www.example.com/myrailsapp) by:

1. using the [PassengerRoot config](https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerRoot) to set baseURI.
2. [setting SCRIPT_NAME to baseURI](https://github.com/phusion/passenger/blob/f9ce58d141316932f53c595ad7beed833172a6bc/ext/apache2/Hooks.cpp#L878) before dispatching to Rack.
3. [Rack uses SCRIPT_NAME](https://github.com/rack/rack/blob/ab172af1b63f0d8e91ce579dd2907c43b96cf82a/lib/rack/request.rb#L329) so links and assets get generated correctly to the suburi.

Note: config.relative_url_root doesn't need to be set in this case because script_name is supported in many places in Rails independent of relative_url_root.  This may be because script_name is lower level (i.e. in Rack), hence handles suburi semantics for both certain Rails cases and other Ruby frameworks.  TL;DR: there may be some duplication of intent wrt relative_url_root.

Note: Webrick doesn't respect these semantics at all and needs to be config.ru mapped (as pointed out above) to work correctly with suburi.  Both config.relative_url_root and SCRIPT_NAME have to be set in my experience to use assets and link helpers correctly too.

Other servers (Thin, Unicorn, nginx) have some reverse proxy settings that can work, but assets need to have SCRIPT_NAME in order to correctly resolve.  I'm a bit hazy on the specifics here because I primarily use webrick/pry and Passenger/Apache for my debugging and deployed environments.  I've been playing with nginx, but in my experience, it's been difficult to get a single Rails app able to reliably work with suburi in all environments without hacks.  I've been working on a gem to normalize behavior so that (for example) a Rails dev could simply set "config.relavtive_url_root" and have everything else 'just work' no matter whether they were in webrick, Apache/Passenger, nginx, etc.

You'd see things like:

* http://localhost:3000/myrailsapp (local webrick)
* http://mymac/myrailsapp (local nginx)
* http://www.example.com/myrailsapp (deployed Apache/Passenger)

work seemlessly without separate configs everywhere. :)

**Comment by rafaelfranca** [comment] 2015-01-02 22:08
@coldnebo thank you

**Comment by rafaelfranca** [comment] 2015-03-03 20:24
Fixed by #18775

**Closed by rafaelfranca** 2015-03-03 20:24 UTC
Labels: actionpack, With reproduction steps

**Comment by arianf** [comment] 2015-08-26 17:24
This still doesn't 100% work.

**Comment by joealba** [comment] 2015-08-26 17:32
The implementation introduced a regression as well -- https://github.com/rails/rails/issues/20920

A test app to show the regression and a pull request for a new fix are included in that issue.

**Comment by poc7667** [comment] 2015-10-26 15:09
not working on 4.2.4, why the apparent bug still existing ?

**Comment by llimllib** [comment] 2015-11-10 02:41
Is this bug fixed in any release? Here I am trying to test it on 4.2.5:

```shell
$ RAILS_RELATIVE_URL_ROOT=/subdir rails c
Loading development environment (Rails 4.2.5.rc2)
irb(main):001:0> app.skills_translator_suggest_path
=> "/skills-translator/suggest"

$ cat config/routes.rb
Rails.application.routes.draw do
  get 'skills-translator/suggest' => 'skills#index', as: :skills_translator_suggest
end
```

and here's another way it's manifested itself:

```shell
$ grep "http.post.*suggest" app/assets/javascripts/skill_translator.js.erb
    $http.post('<%= url_helper.skills_translator_suggest_path %>', $scope.formData).then(function (res) {

$ RAILS_RELATIVE_ROOT_URL=/veterans-employment-center rake assets:precompile \
>   && grep 'http.post.*suggest' public/assets/application-*.js
    $http.post('/skills-translator/suggest', $scope.formData).then(function (res) {
```

**Comment by llimllib** [comment] 2015-11-10 03:13
Looks like to get it to work, you can pass the `script_name` parameter to the `_path` helper:

```
$http.post('<%= url_helper.skills_translator_suggest_path(script_name: ENV['RAILS_RELATIVE_URL_ROOT']) %>', $scope.formData).then(function (res) {
```

^^^ works, though it's ugly and I'd argue that this bug should be open!

**Comment by creativereason** [comment] 2016-09-29 18:08
Is there a workaround for this? Running into this issue deploying a site to a subdirectory using 4.2. Routes, links and helpers don't work, but the scripts do when setting `[:script_name]` and `config.relavtive_url_root`.
