### ISSUE TITLE
rails5 generate scaffold with no fields generates a broken controller test

### ISSUE THREAD

**Issue by rubys** [rails/rails#23314] opened 2016-01-28 18:21 UTC
Reproduction scenario:

    rails new throwaway 
    cd throwaway
    rails generate scaffold Cart
    rails db:migrate
    rails test

Test results: [throwaway.txt](https://github.com/rails/rails/files/108646/throwaway.txt)

[this is with rails master]

**Comment by diego-silva** [comment] 2016-01-28 20:48
I took a quick-look on this and it seem related to brynary/rack-test#122

**Comment by vipulnsward** [comment] 2016-01-29 08:00
Able to reproduce on master. Issue with https://github.com/vipulnsward/rails/blob/703f1052ae2e5da3d5ef18a759c03ba5692f1e24/railties/lib/rails/generators/test_unit/scaffold/templates/functional_test.rb#L41-L44

**Comment by vipulnsward** [comment] 2016-01-29 08:11
btw, I also see- 

```ruby 

E

RuntimeError: Invalid option key: per_form_csrf_tokens=
    app/controllers/application_controller.rb:1:in `<top (required)>'
    app/controllers/carts_controller.rb:1:in `<top (required)>'
    test/controllers/carts_controller_test.rb:37:in `block in <class:CartsControllerTest>'

```

**Comment by mohitnatoo** [comment] 2016-01-29 18:35
I've started looking into this one.

**Comment by rubys** [comment] 2016-01-31 17:39
Possibly related: https://github.com/rails/rails/issues/23384

**Comment by rubys** [comment] 2016-02-07 03:36
Root problem is here: https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/scaffold_controller/templates/controller.rb#L61

The else clause returns a hash.  The then clause returns nil instead of an empty hash.

There are a number of ways to fix this.  My suggestion is to emit, as a comment, what the else clause would return so that developers can expand upon it.  And then follow that comment with an empty hash: `{}`.

**Comment by diego-silva** [comment] 2016-02-08 17:04
The problem is actually on JBuilder scaffold_controller, if you disable the JBuilder gem on the Gemfile it generates a working set of controller/tests.

I've created a PR on rails/jbuilder and once its merged it should fix this issue. After that it might be good to change the minimum required version for JBuilder on the generated Gemfile for `rails new`.

**Comment by diego-silva** [comment] 2016-02-09 23:23
The PR for Jbuilder was merged and I am not able to reproduce this issue with the new version `(2.4.1)` anymore.

Not sure if we should enforce the generated Gemfile for `rails new` to use at least version `2.4.1` or just keep it as it is (`~> 2.0`).

**Comment by rubys** [comment] 2016-02-10 00:44
> The PR for Jbuilder was merged and I am not able to reproduce this issue with the new version (2.4.1) anymore.

Agreed.  Thanks!

Before: http://intertwingly.net/projects/AWDwR4/checkdepot-223/section-9.2.html#cmd8
After: http://intertwingly.net/projects/AWDwR4/checkdepot/section-9.2.html#cmd8

> Not sure if we should enforce the generated Gemfile for rails new to use at least version 2.4.1 or just keep it as it is (~> 2.0).

Probably should enforce the new version; but in practice it likely won't be an issue.

**Closed** 2016-02-10 16:24 UTC
Labels: actionpack
