### ISSUE TITLE
"undefined method `accessor'" after attempting to reverse an PG db with hstore

### ISSUE THREAD

**Issue by IamNaN** [rails/rails#16971] opened 2014-09-19 02:31 UTC
Pretty simple repro on Rails 4.1.5 and PostgreSQL:

1. Add hstore to an app being sure to enable the hstore extension* and change the schema format to sql in application.rb
2. Create a model and table that use hstore with store_accessor (i.e. `store_accessor :specs, :color, :material, :shape` 
3. Migrate your db

(At this point everything works.)

4. Rollback your db migrations (i.e. `rake db:migrate VERSION=0`)
5. Migrate forward again

At this point anything that uses one of the `specs` causes and "undefined method `accessor'" exception in activerecord lib/active_record/connection_adapters/postgresql_adapter.rb.

If between steps 3 and 4 you drop and recreate the database, everything works again.

It's possible I had this problem in Rails 4.1.2 but I just didn't encounter it.

* I have a migration that runs first, it enables the hstore extension on up and disables it on down.

**Comment by herophuong** [comment] 2015-02-12 09:16
In my case, first I used ActiveRecord::Store to serialize some attributes into one column of type `text` with this (1):

```ruby
class Player < ActiveRecord::Base
  store :avatar, accessors: %i(small_avatar medium_avatar large_avatar), coder: JSON
end
```

And then I tried to migrate this column into `json` using this code (2):

```ruby
class ConvertToJsonInPlayers < ActiveRecord::Migration
  def up
    avatars = Player.all.map do |player|
      [player.id, player.avatar]
    end
    remove_column :players, :avatar
    add_column :players, :avatar, :json
    avatars.each do |avatar|
      Player.find(avatar[0]).update_attributes({avatar: avatar[1]})
    end
  end
end
```

Then changed the way my model accesses the attributes (3):

```ruby
class Player < ActiveRecord::Base
  store_accessor :avatar, :small_avatar, :medium_avatar, :large_avatar
end
```

In development, running (2) before (3) has no problem. But when I deployed this code to Heroku, because (3) was already there while the column `avatar` was still in `text` type, this error occured:

```
NoMethodError: undefined method `accessor' for #<ActiveRecord::Type::Text:0x007f0bfb6856d8>
```

Destroying the database all at once is a no-no, definitely.

**Comment by senny** [comment] 2015-02-12 09:22
@herophuong this is not something we can solve. That's the reason why you should not use your applications models in migrations. It's better to define a throw-away model inside your migration class and make sure that one has the right configuration:

```ruby
class ConvertToJsonInPlayers < ActiveRecord::Migration
  class MyModel < ActiveRecord::Base
    self.table_name = "the_table"
    store :avatar, accessors: %i(small_avatar medium_avatar large_avatar), coder: JSON
  end

  def up
    # ...
  end
end

```

**Comment by senny** [comment] 2015-03-05 09:31
It's been a while without feedback. I'm going to close this issue. If there is still something left to discuss please report back.

**Closed by senny** 2015-03-05 09:31 UTC
Labels: activerecord, needs feedback, PostgreSQL

**Comment by victorhazbun87** [comment] 2015-10-23 15:58
It is happening to me too 
NoMethodError: undefined method `accessor' for #<ActiveRecord::Type::Value:0x007faa80a348f0>


        store_accessor :data,
        :company_access,
        :locations_access,
        :staff_members_access,
        :customers,
        :online_scheduling

**Comment by Almaron** [comment] 2016-09-13 07:34
Same thing here on Rails 4.2.7, a `jsonb` field called `additional`, and `store_accessor :additional, :distance, :walking_time, :driving_time` causes an error:
`NoMethodError: undefined method `accessor' for #<ActiveRecord::Type::Value:0x0000000afa9e48>
from /home/malk/.rvm/gems/ruby-2.2.3@domus/gems/activerecord-4.2.7.1/lib/active_record/store.rb:132:in `store_accessor_for'
`

**Comment by senny** [comment] 2016-10-20 18:48
@victorhazbun87 @Almaron do you have a way to reproduce this using a [bug report template](https://github.com/rails/rails/tree/master/guides/bug_report_templates) or in a sample application? If we have something to look into this I'll happily reopen the issue.

**Comment by kvokka** [comment] 2017-02-06 04:42
Hello, I've got this issue yet with Rails 5.0.1, easiest way to reproduce, is this chunk

```
  module Foo
    extend ActiveSupport::Concern

    included do
      scope :last_updated_at, -> { order(updated_at: :desc).limit(1).last&.updated_at }
      self.last_updated_at
    end
  end
 
class Bar < ActiveRecord::Base
  include Foo
  store_accessor :settings, :s1, :s2
end
Bar.first.s1 # => NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Text
```

**Comment by vinagrito** [comment] 2017-07-25 18:53
Well I have the same issue...the difference is that on my local it actually works fine, but when I deploy to Heroku I'm getting 
`NoMethodError (undefined method 'accessor' for #<ActiveModel::Type::Value:.....>)`

running Rails 5.0.2

**Comment by jcgasche** [comment] 2018-06-11 08:51
This just happened to me, I haven't found any solution that makes the store work. Hasn't anyone found a way to solve this?

**Comment by msdundar** [comment] 2018-08-14 12:35
Same here with Rails 5.2.1!

**Comment by jcgasche** [comment] 2018-08-14 13:40
So I found an answer to this. I will write a better answer here soon and I'm writing a small blogpost about this to make sure it is covered somewhere.

## What happened
In the meantime, here is what happened to me, the chronology is important:

* I successfully created the hstore needed in the db, and migrated.
*  I added the rails line allowing this hstore to store "JSON attributes"
i.e.: `<store :hstore_column_name, accessors: [  :attribute_one_name, ...]>`

* I then reverted the migration as I needed to change something.
* I made my modifications in the migration, then tried to re-run migrate.
* This is when the "bug" (which is not one) appeared.

What is happening is that the line declaring the hstore is still in the model at this point. When Rails tries to run the migration, the model is called, and this line throws an error, as this DB column is supposed to be used for hstore, but does not exist.

## Quick Fix
My quick fix was to remove the hstore declaration in the model and to migrate, then re-add it.

## Better solution
A better solution to make hstore migrations fully reversible, allowing for model evolutions (if this hstore disappears a year from now and a newcomer needs to migrate their DB to the latest), and allowing for data population at the same time requires 3 migrations, where the hstore declaration is declared for the model inside the migration file.
I'm working on a clean explanation, and will gladly take feedback from people in this thread, I don't have the pretension to say I will come up with the best way by myself.

I hope this helps, but let me know if this is not what is happening.

**Comment by msdundar** [comment] 2018-08-14 13:49
@jcgasche exactly! I noticed this issue when I take a look to `schema.rb`. It seems like `revert migration` is not working as expected for hstore!

I will explain my situation for further investigation:

- Created a migration adding two columns as hstore:

```
class AddProfileFieldsToUser < ActiveRecord::Migration[5.2]
  def change
    add_column :users, :profile, :jsonb
    add_column :users, :preferences, :jsonb
  end
end
```

Then I decided to do this with a single column and reverted the migration:

```
rake db:rollback STEP=1
```

Edited the migration as follows:

```
class AddProfileFieldsToUser < ActiveRecord::Migration[5.2]
  def change
    add_column :users, :profile_preferences, :jsonb
  end
end
```

Migrated again with `rake db:migrate`. But when I take a look to `schema.rb` it was still standing like this:

```
  t.jsonb "profile"
  t.jsonb "preferences"
```

Then I completely deleted the `schema.rb` and run the `rake db:migrate` again and nothing happened in schema.rb, it was still the same:

```
  t.jsonb "profile"
  t.jsonb "preferences"
```

**Comment by jcgasche** [comment] 2018-08-14 14:06
I would say this is an issue more with the migration than with the hstore. Also I personally use :text for my hstores, but I cannot tell the benifits/disavantages of either.

Just as a sanity check, have you taken all the steps to make sure your changes to the migration file were correctly taken into account by your source control?
Could it be only possible that you changed the migration file before running the rollback? (even if I took understand you migrated later again from scratch, it could be a combination of both points up here)

Last but not least, can you reproduce this phenomenon where you create 2 hstores, rollback, but these hstores are still here?

**Comment by edgr** [comment] 2019-12-29 09:30
@msdundar it seems I have bumped into the exact same issue (changing my mind about the jsonb column and rolling back then migrating again) except I only have 1 column in my schema. Consequently, my user/edit page is not accessible anymore in production. Did you find the way to fix this issue?

**Comment by yshmarov** [comment] 2021-01-16 10:58
Exactly the same issue here. @edgr , did you find a solution?

> 
> 
> @msdundar it seems I have bumped into the exact same issue (changing my mind about the jsonb column and rolling back then migrating again) except I only have 1 column in my schema. Consequently, my user/edit page is not accessible anymore in production. Did you find the way to fix this issue?

**Comment by yshmarov** [comment] 2021-01-16 12:10
Typing `heroku restart` or `git push heroku main -f` fixed the issue for me. As well initially I had the code in a `concern`. When I moved it to the model & pushed to production it also started working.
