### ISSUE TITLE
Regression in URL generation in Rails 7.1

### ISSUE THREAD

**Issue by adrianthedev** [rails/rails#51910] opened 2024-05-24 19:52 UTC
Hi,

I think I found a regression/bug in Rails 7.1

#### Context

We, at [Avo](http://github.com/avo-hq/avo) use one main engine but also have a few smaller ones alongside it to bring new features.

The issue consists in the fact that URLs that are generated and displayed in the initial, parent engine (`avo`), for the second engine do not contain the mount path of the first one.

What happens is:

 - `avo` engine gets mounted on `/avo`
 - `pro` engine gets mounted in the `avo` engine on `/pro`
 - the expectation is that any route we call on the `pro` engine should be generated with the `/avo` prefix

*That is the way it worked on 7.0

### Steps to reproduce

https://gist.github.com/adrianthedev/ab57557950a05804532377b69185d866

The script should be executed with the `RAILS_VERSON` env variable like so:

```bash
# run with rails 7.0.8.3 (last 7.0 version) and see the tests pass
RAILS_VERSION=7.0.8.3 ruby repro.rb

# run with rails 7.1 and see the tests fail
RAILS_VERSION=7.1.0 ruby repro.rb
```

### Expected behavior

The generated URL should contain the `/avo` prefix in both 7.0 and 7.1.

### Actual behavior

The generated URL does not contain the `/avo` prefix in Rails 7.1.

### System configuration
**Rails version**: 7.0 and 7.1

**Ruby version**: 3.3.1

**Comment by rafaelfranca** [comment] 2024-05-24 19:55
I didn't investigate yet but I'm almost sure this was by design. Now that you have a reproduction script, can you use it to bisect and find which commit changed the behavior?

**Comment by adrianthedev** [comment] 2024-05-25 10:35
I think I found the commit, it's https://github.com/rails/rails/commit/a393e0de09

But I can't see how this broke the previous behavior.

**Comment by adrianthedev** [comment] 2024-05-25 11:27
Correction. It's https://github.com/rails/rails/commit/95fa021465. I'm not sure why it didn't trigger the bug earlier when I was going through the commit list.

**Comment by rafaelfranca** [comment] 2024-05-27 19:27
@bensheldon any idea why that would break the behavior on this issue?

**Comment by bensheldon** [comment] 2024-05-27 19:59
That's weird and unexpected that nested engines would do that! I'm also tagging @jonathanhefner who helped me with my change. 

I want to ask, on the gist, what happens if you remove the `include Rails.application.routes.url_helpers` from the [controller](https://gist.github.com/adrianthedev/ab57557950a05804532377b69185d866#file-url_regression_in_7_1-rb-L83)? Including route helpers in a controller or view should not be necessary. As a potential bug, we should isolate which set of route helpers (controller/views, or the ones hanging off Rails) is affected (could be both too, but they're different because the former has access to Rack Env and the latter does not).

**Comment by adrianthedev** [comment] 2024-05-28 07:25
Thanks for chiming in @bensheldon. I feel a bit lost because I don't know anything so deep about routing in Rails.

When I remove the `include Rails.application.routes.url_helpers` from the controller with Rails 7.1.0.alpha I get this error `ActionView::Template::Error (undefined local variable or method `avo_pro' for an instance of #<Class:0x000000017dc700a0>)`

I left it there because it was ther ein the first place in the [reproduction script](https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller.rb). I don't know if removing that from the script behaves the same as in a regular app.

**Comment by zzak** [comment] 2024-05-28 11:58
#51933 gets the repro script to pass, but it's not ready to be merged

**Comment by adrianthedev** [comment] 2024-05-28 13:42
@zzak I can confirm that it fixes the issues in our repo as well.
Please let me know what I can do to help you to get that PR merged.

**Comment by zzak** [comment] 2024-05-29 12:42
Thanks for trying the branch and confirm the fix. I was making sure to add a regression test and CI passed. :pray:

**Closed** 2024-05-31 09:12 UTC
Labels: actionpack, railties, attached PR
