### ISSUE TITLE
Rails 6.0.2.1 and ruby 2.7.0 many warnings

### ISSUE THREAD

**Issue by mayeco** [rails/rails#38454] opened 2020-02-14 03:48 UTC
### Steps to reproduce
rails c

```
gems/ruby-2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
gems/ruby-2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
gems/ruby-2.7.0/gems/activerecord-6.0.2.1/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
gems/ruby-2.7.0/gems/activerecord-6.0.2.1/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
gems/ruby-2.7.0/gems/activemodel-6.0.2.1/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
gems/ruby-2.7.0/gems/activemodel-6.0.2.1/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
gems/ruby-2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql/oid/specialized_string.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
gems/ruby-2.7.0/gems/activemodel-6.0.2.1/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
Loading development environment (Rails 6.0.2.1)
```

### Expected behavior
No warnings

### Actual behavior
To many warnings

### System configuration
**Rails version**:
6.0.2.1

**Ruby version**:
2.7.0

**Comment by kamipo** [comment] 2020-02-14 03:53
Duplicate of #38245, this is already fixed in the 6-0-stable branch.

**Closed by kamipo** 2020-02-14 03:53 UTC
