### ISSUE TITLE
Asset folder is not created

### ISSUE THREAD

**Issue by josephmo** [rails/rails#45799] opened 2022-08-09 16:38 UTC
### Steps to reproduce

Up until this morning, I have been using the following build script to start my Production server:

    sudo rm -Rf /home/deploy/current/
    git clone -b xxxx git@xxxxxxx.git /home/deploy/current
    cd /home/deploy/current/
    bundle update
    bundle install
    rake db:migrate
    rake db:seed
    rails tailwindcss:build
    bundle exec rake assets:precompile
    bundle binstubs puma
    sudo systemctl stop puma
    sudo systemctl start puma
    sudo service nginx restart

and things were working fine. This morning, when I did this, I discovered that the public/assets folder was not created. So, obviously the application is not working.

I rebooted the server, and re-tried this multiple times. No error are generated in the log file. I tried precompiling with the --trace switch, and no errors.

```ruby
# Your reproduction script goes here
```

### Expected behavior

I was expecting a  public/assets folder to be created and the assets precompiled there.

### System configuration
**Rails version**:

7.0.3.1

**Ruby version**:

3.1.0

**Comment by skipkayhil** [comment] 2022-08-10 02:20
Hey @josephmo, thanks for opening an issue! Do you have a repo you could share that demonstrates the issue? Without this it will be very difficult to figure out what may be going wrong

**Comment by josephmo** [comment] 2022-08-10 13:08
The application is proprietary, so I can' share the repo publicly.

**Comment by eileencodes** [comment] 2022-08-10 13:46
> The application is proprietary, so I can' share the repo publicly.

No worries, we were asking you to make a new one that reproduces the issue you're seeing.

**Comment by flavorjones** [comment] 2022-08-10 18:23
Is it possible that this was caused by https://github.com/rails/tailwindcss-rails/pull/189, in which case an update to https://github.com/rails/tailwindcss-rails/releases/tag/v2.0.12 should fix it?

**Comment by josephmo** [comment] 2022-08-10 19:09
> Is it possible that this was caused by [rails/tailwindcss-rails#189](https://github.com/rails/tailwindcss-rails/pull/189), in which case an update to https://github.com/rails/tailwindcss-rails/releases/tag/v2.0.12 should fix it?

Changing the of tailwind gem back to 2.0.10 from 2.0.11 seems to have solved the problem.

**Comment by flavorjones** [comment] 2022-08-10 19:18
@josephmo If you can confirm that upgrading to 2.0.12 also fixes it, please feel free to close this!

**Closed** 2022-08-10 20:45 UTC
Labels: asset pipeline
