### ISSUE TITLE
Rename column migration does not preserve MySQL constraints

### ISSUE THREAD

**Issue by wlnirvana** [rails/rails#39251] opened 2020-05-12 14:55 UTC
MySQL columns created with `NULL` constraint loses this constraint, leading to `Invalid default value` error during `rename_column`.

### Steps to reproduce

Run `ruby bug.rb` with `bug.rb` containing the following script:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  gem "rails", '=5.2.4.2'
  gem 'mysql2', '~>0.4.10'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
    :adapter  => "mysql2",
    :host     => "127.0.0.1",
    :username => "tmp",
    :password => "tmp",
    :database => "tmpdb"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true do |t|
    t.string :name
    t.timestamp :brought_date
  end
end

class Book < ActiveRecord::Base
end

class RenameColumn < ActiveRecord::Migration[5.2]
  def change
    reversible do |dir|
      dir.up do
        rename_column :books, :brought_date, :bought_date
      end

      dir.down do
        rename_column :books, :bought_date, :brought_date
      end
    end
  end
end

class BugTest < Minitest::Test
  def test_migration_up
    RenameColumn.migrate(:up)
  end

  def test_migration_down
    RenameColumn.migrate(:down)
  end
end
```

### Expected behavior

Migration succeeds, or the following SQL statements:

```sql
CREATE TABLE `books` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `brought_date` timestamp NULL);
ALTER TABLE `books` CHANGE `brought_date` `bought_date` timestamp NULL;
```

### Actual behavior

```ActiveRecord::StatementInvalid: Mysql2::Error: Invalid default value for 'bought_date': ALTER TABLE `books` CHANGE `brought_date` `bought_date` timestamp DEFAULT NULL```

caused by the following generated SQL statement:

```sql
CREATE TABLE `books` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `brought_date` timestamp NULL);
ALTER TABLE `books` CHANGE `brought_date` `bought_date` timestamp DEFAULT NULL;
```

### System configuration

**Rails version**: Rails 5.2.4.2

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]

**Comment by gmcgibbon** [comment] 2020-05-12 22:58
There is no difference between `timestamp NULL` and `timestamp DEFAULT NULL` AFAICT, they both infer a nullable column in mysql. If you add a constraint in your test case like `t.timestamp :brought_date, null: false` the constraint is carried over renames correctly. Closing, but please let me know if I missed something. Thanks!

**Closed by gmcgibbon** 2020-05-12 22:58 UTC
Labels: activerecord

**Comment by wlnirvana** [comment] 2020-05-13 00:23
@gmcgibbon `timestamp NULL` and `timestamp DEFAULT NULL` actually behave differently, at least in my environment:

```bash
$ mysql --protocol=tcp -u tmp -p tmpdb
Enter password:
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 139
Server version: 5.7.29 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> DROP TABLE IF EXISTS `books`;
Query OK, 0 rows affected (0.02 sec)

mysql> CREATE TABLE `books` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `brought_date` timestamp NULL);
Query OK, 0 rows affected (0.02 sec)

mysql> ALTER TABLE `books` CHANGE `brought_date` `bought_date` timestamp NULL;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql>
mysql>
mysql>
mysql>
mysql> DROP TABLE IF EXISTS `books`;
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE `books` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `brought_date` timestamp NULL);
Query OK, 0 rows affected (0.02 sec)

mysql> ALTER TABLE `books` CHANGE `brought_date` `bought_date` timestamp DEFAULT NULL;
ERROR 1067 (42000): Invalid default value for 'bought_date'
mysql>
```

I'm not very familiar with SQL, but I suspect `NOT NULL` and `NULL` are **constraints** about if a column can be null. On the other hand `DEFAULT NULL` just specifies the default value, which is quite different semantic.

**Comment by kamipo** [comment] 2020-05-13 02:26
Related #31804, #37421.

That nonstandard behavior is caused by `explicit_defaults_for_timestamp=off`.
That behavior is already deprecated in 5.6.6 and will be removed in the future version of MySQL.
Use new default `explicit_defaults_for_timestamp=on`.
