### ISSUE TITLE
SECRET_KEY_BASE in Environment Specific Credentials not found

### ISSUE THREAD

**Issue by causztic** [rails/rails#38906] opened 2020-04-09 10:35 UTC
I would like to have my secret_key_base in my environment specific credentials, but it looks like it cannot be found if I'm using the environment variable `RAILS_#{RAILS_ENV.upcase}_KEY`. I tried `RAILS_MASTER_KEY` as well to no avail.

### Steps to reproduce
1. Start a new Rails 6 application
2. `EDITOR=vi rails credentials:edit --environment production` and add in `secret_key_base`, using `rails secret` to generate

Doing `RAILS_ENV=production rails c` works at this point. Now,

3. Rename `config/credentials/production.key` to something else (`config/credentials/production.keya` for example)
4. Run `RAILS_PRODUCTION_KEY=your_key_here RAILS_ENV=production rails c`
5. An error is raised, saying:
```
application.rb:580:in `validate_secret_key_base': Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit` (ArgumentError)
```

### Expected behavior
The `secret_key_base` should be read correctly 

### Actual behavior
The `secret_key_base` is not found

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.5

**Comment by jonathanhefner** [comment] 2020-04-10 19:42
Although `RAILS_#{options[:environment].upcase}_KEY` was originally used in #33521, it was removed in #33928.

> I tried RAILS_MASTER_KEY as well to no avail.

I could not reproduce the error when using `RAILS_MASTER_KEY`.

**Comment by causztic** [comment] 2020-04-11 00:01
I retried my steps and i got the same error with `RAILS_MASTER_KEY`, here are more detailed steps I took again:

1. `rails new app`
2. `rails secret`
3. `EDITOR=vi rails credentials:edit --environment production`
4. copy results from 2 to 3 as `secret_key_base: secret_here`, and then `wq!`
5. `mv config/credentials/production.key config/credentials/production.keya`
6. `RAILS_MASTER_KEY=production_key_from_file_above RAILS_ENV=production rails c` 
7. Error: ```/Users/yaojie/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.2/lib/rails/application.rb:580:in `validate_secret_key_base': Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit` (ArgumentError)```

**Comment by jonathanhefner** [comment] 2020-04-11 01:57
I managed to reproduce the error!  The problem is actually caused by rails/spring#305 (aka rails/spring#490).  The `RAILS_MASTER_KEY` environment variable is not being picked up by Spring after its initial load.  You can verify this by inserting `STDERR.puts ENV["RAILS_MASTER_KEY"].inspect` before the [raise](https://github.com/rails/rails/blob/v6.0.2.2/railties/lib/rails/application.rb#L580).

If you run `spring stop` before `rails c`, the error should not occur.

**Comment by rafaelfranca** [comment] 2020-04-13 20:16
Closing this issue in favor or the spring issue.

**Closed by rafaelfranca** 2020-04-13 20:16 UTC
