### ISSUE TITLE
Possible breaking change on version `8.0.1` for `class_attribute`

### ISSUE THREAD

**Issue by Paul-Bob** [rails/rails#53992] opened 2024-12-18 11:46 UTC
### Steps to reproduce

1. Execute the test case using `gem "rails", "8.0.0"` 
2. Execute the same test case using `gem "rails", "8.0.1"`
3. Observe that with `gem "rails", "8.0.1"`, the behavior deviates, introducing a breaking change.

Below is the executable test case, constructed according to the guidelines outlined [here](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case):

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Works as expected
  gem "rails", "8.0.0"

  # Breaks
  # gem "rails", "8.0.1"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class ExampleBase
  class_attribute :the_attribute

  def self.the_attribute
    @the_attribute || "default_attribute_for_#{to_s.underscore}"
  end
end

class ExampleInherit < ExampleBase
  self.the_attribute = "custom_attribute"
end

class BugTest < ActiveSupport::TestCase
  def test_stuff
    assert_equal "custom_attribute", ExampleInherit.the_attribute
  end
end

```

### Expected behavior

The `ExampleInherit.the_attribute` method should return `"custom_attribute"` when using `gem "rails", "8.0.1"`, consistent with the behavior in version `8.0.0`.

### Actual behavior

- With `gem "rails", "8.0.0"`, the method `ExampleInherit.the_attribute` returns `"custom_attribute"` as expected.
- However, with `gem "rails", "8.0.1"`, it returns `"default_attribute_for_example_inherit"`.

### System configuration
**Rails version**:

- `8.0.0` (working as expected)
- `8.0.1` (breaking change)

**Ruby version**:

Tested with `ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]`

**Comment by nvasilevski** [comment] 2024-12-18 19:45
https://github.com/rails/rails/pull/53640 is the only change in `8.0.1` around class attributes so this PR must be relevant

One thing I wrongly assumed is that the issue is caused by value not being set to `@the_attribute` variable when in reality the issue is caused by `ExampleInherit` having it's own reader for the class attribute so we never call the parent's. So now I'm not so sure whether the change is purely internal or can be considered as a behavior change and needs to be treated as a bug 😕 

But while it could be a bug I still want to gently push towards doing a refactoring primarily to eliminate unnecessary recalculation of `"default_attribute_for_#{subclass.to_s.underscore}"` string

**Comment by Paul-Bob** [comment] 2024-12-18 19:59
> #53640 is the only change in `8.0.1` around class attributes so this PR must be relevant

Thanks for pointing that out. This PR was already mentioned in the [original issue](https://github.com/avo-hq/avo/issues/3538), which led me to discover it, and I have already taken a look.

> One thing I wrongly assumed is that the issue is caused by value not being set to `@the_attribute` variable when in reality the issue is caused by `ExampleInherit` having it's own reader for the class attribute so we never call the parent's. 

Inheritance should fallback to parent's methods unless explicitly overridden right?

>So now I'm not so sure whether the change is purely internal or can be considered as a behavior change and needs to be treated as a bug 😕

I'm having the exact same question, let me know if I can help with anything.

> But while it could be a bug I still want to gently push towards doing a refactoring primarily to eliminate unnecessary recalculation of `"default_attribute_for_#{subclass.to_s.underscore}"` string

Thank you for the recommendations!

**Comment by byroot** [comment] 2024-12-29 10:09
That's indeed a result of https://github.com/rails/rails/pull/53640, before that assigning a `class_attribute` would always redefine the method, so it would override or replace your `def self.the_attribute`.

As Nikita said, it was an implementation details, was pretty bad for performance, and prevented decorating the accessor.

So I'm afraid I have to close this as wontfix.

**Closed by byroot** 2024-12-29 10:09 UTC
Labels: activesupport

**Comment by Paul-Bob** [comment] 2024-12-31 11:42
Thanks for the details @nvasilevski & @byroot, nice performance improvement there!

I end up with a clean implementation on my side that works as expected without overriding the reader method:

```ruby
class ExampleBase
  class_attribute :the_attribute, default: "default_attribute_for_#{to_s.underscore}"
end

class ExampleInherit < ExampleBase
  self.the_attribute = "custom_attribute"
end
```
