### ISSUE TITLE
ActiveStorage's `attach` not saving/uploading the attachment until `.save` is called

### ISSUE THREAD

**Issue by luizkowalski** [rails/rails#43663] opened 2021-11-17 12:25 UTC
I have the following code that I use on my seed file to attach a file to a record:

```ruby
organization.id_document.attach(
  io: File.open(Rails.root.join('test/fixtures/files/id.pdf')),
  content_type: 'application/pdf',
  identify: false,
  filename: "scan_id_2#{organization.id}"
)
```
It worked fine until some time ago (I don't really remember exactly when) but now, its behavior is weird...this is the output of the command above:

```ruby
=> #<ActiveStorage::Attached::Changes::CreateOne:0x00007fb849a58fa8
 @attachable=
  {:io=>#<File:/Users/luizkowalski/rails_dev/de-abi-prototype/test/fixtures/files/id.pdf>,
   :content_type=>"application/pdf",
   :identify=>false,
   :filename=>"scan_id_2c968db2e-dd5a-4016-bf3d-d6037aff4d7b"},
 @blob=
  #<ActiveStorage::Blob:0x00007fb846e7f8f0
   id: nil,
   key: nil,
   filename: "scan_id_2c968db2e-dd5a-4016-bf3d-d6037aff4d7b",
   content_type: "application/pdf",
   metadata: {"identified"=>true},
   service_name: "local",
   byte_size: 83186,
   checksum: "4emOsAkvy+n/uSlvSz5dvg==",
   created_at: nil>,
 @name="id_document",
 @record=
  #<Organization:0x00007fb84ae92690
   id: "c968db2e-dd5a-4016-bf3d-d6037aff4d7b",
....
```
as you can see, the blob is not saved, id and key are `nil` but the output of `attached?` is `true`

```ruby
[6] pry(main)> organization.id_document.attached?
=> true
```

but if close and reopen the console, then it changes to `false`

```ruby
[1] pry(main)> Organization.last.id_document.attached?
  Organization Load (0.8ms)  SELECT "organizations".* FROM "organizations" ORDER BY "organizations"."created_at" DESC, "organizations"."id" DESC LIMIT $1  [["LIMIT", 1]]
  ActiveStorage::Attachment Load (0.6ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", "c968db2e-dd5a-4016-bf3d-d6037aff4d7b"], ["record_type", "Organization"], ["name", "id_document"], ["LIMIT", 1]]
=> false
```

I notice that I append `.save` to the `attach`, then it works:

```ruby
[3] pry(main)> organization.id_document.attach(
  io: File.open(Rails.root.join('test/fixtures/files/id.pdf')),
  content_type: 'application/pdf',
  identify: false,
  filename: "scan_id_2#{organization.id}"
).save

  ActiveStorage::Blob Load (0.8ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" INNER JOIN "active_storage_attachments" ON "active_storage_blobs"."id" = "active_storage_attachments"."blob_id" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", "c968db2e-dd5a-4016-bf3d-d6037aff4d7b"], ["record_type", "Organization"], ["name", "id_document"], ["LIMIT", 1]]
  ActiveStorage::Attachment Load (0.8ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", "c968db2e-dd5a-4016-bf3d-d6037aff4d7b"], ["record_type", "Organization"], ["name", "id_document"], ["LIMIT", 1]]
  TRANSACTION (0.1ms)  BEGIN
  ActiveStorage::Blob Create (0.5ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "service_name", "byte_size", "checksum", "created_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["key", "7gbye511cm3b390xwf23y3af621z"], ["filename", "scan_id_2c968db2e-dd5a-4016-bf3d-d6037aff4d7b"], ["content_type", "application/pdf"], ["metadata", "{\"identified\":true}"], ["service_name", "local"], ["byte_size", 83186], ["checksum", "4emOsAkvy+n/uSlvSz5dvg=="], ["created_at", "2021-11-17 12:18:26.999163"]]
  ActiveStorage::Attachment Create (0.6ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "id_document"], ["record_type", "Organization"], ["record_id", "c968db2e-dd5a-4016-bf3d-d6037aff4d7b"], ["blob_id", 3], ["created_at", "2021-11-17 12:18:27.001233"]]
  Organization Update (1.4ms)  UPDATE "organizations" SET "updated_at" = $1 WHERE "organizations"."id" = $2  [["updated_at", "2021-11-17 12:18:27.002596"], ["id", "c968db2e-dd5a-4016-bf3d-d6037aff4d7b"]]
  TRANSACTION (1.0ms)  COMMIT
  TRANSACTION (0.1ms)  BEGIN
  ActiveStorage::Blob Update (0.4ms)  UPDATE "active_storage_blobs" SET "metadata" = $1 WHERE "active_storage_blobs"."id" = $2  [["metadata", "{\"identified\":true,\"analyzed\":true}"], ["id", 3]]
  TRANSACTION (0.5ms)  COMMIT
  Disk Storage (1.0ms) Uploaded file to key: 7gbye511cm3b390xwf23y3af621z (checksum: 4emOsAkvy+n/uSlvSz5dvg==)
=> #<ActiveStorage::Blob:0x00007fe9c1f68080
 id: 3,
 key: "7gbye511cm3b390xwf23y3af621z",
 filename: "scan_id_2c968db2e-dd5a-4016-bf3d-d6037aff4d7b",
 content_type: "application/pdf",
 metadata: {"identified"=>true, "analyzed"=>true},
 service_name: "local",
 byte_size: 83186,
...
```

I found nothing on the documentation about calling `.save`, seems like the API has changed at some point? Here is some more information:

**storage.yml**

```yaml
local:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['AWS_BUCKET'] %>
  region: <%= ENV['AWS_REGION'] %>
```

**organization.rb**

```ruby
class Organization < ApplicationRecord
  include PgSearch::Model
  include Locatable
  ...
  has_one_attached :id_document
  validates :id_document, blob: { content_type: %w[application/pdf image/png image/jpg image/jpeg] }
  ....
```

### Expected behavior
`.attach` should upload/save the attachment without having to call `.save`

### Actual behavior
`.attach` seems like to only instantiate the `Attached::One` instance, without actually saving/uploading it

### System configuration
**Rails version**: 6.1.4.1 (also reproduced on 6.1.4)

**Ruby version**: 3..0.2

**Comment by ghiculescu** [comment] 2021-11-17 15:35
Hey, thanks for the report. This is expected behavior as of Rails 6. See https://github.com/rails/rails/pull/33303

I'm going to close this as working as intended, but please reopen if I've missed something :)

**Comment by luizkowalski** [comment] 2021-11-17 15:37
hey @ghiculescu, thanks for clarifying...maybe the documentation needs to be updated then? because there no mentions of the `.save` requirement: https://guides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects

**Comment by ghiculescu** [comment] 2021-11-17 15:39
Ahhh, yes, that's a great callout. Would you be interested in making a PR? Otherwise I can, and either way, thank you for reoprting.

**Comment by luizkowalski** [comment] 2021-11-17 15:40
yeah, I can do it...just need to know if you want me to explain something about this behavior or just add `.save` to the examples would be fine

**Comment by ghiculescu** [comment] 2021-11-17 15:44
I think just add `.save` and mention it (once you've attached something to the record, you need to save it).

**Closed** 2021-11-21 15:47 UTC
Labels: docs, activestorage

**Comment by Sollace** [comment] 2025-05-11 17:21
Just a quick reminder that the `.save` requirement is still not documented [here](https://guides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects). I was wondering why my attachments weren't being saved and was led here by my search.
