### ISSUE TITLE
Unexpected count value with Rspec + Worker +.deliveries.count

### ISSUE THREAD

**Issue by isuPatches** [rails/rails#29008] opened 2017-05-07 16:52 UTC
Not really sure if this is due to something with Rspec or ActionMailer itself...please note that I didn't include the views for the mailers, but included everything else relevant.

### Steps to reproduce

1. Have a worker that triggers two mailers

```
class MailerWorker
  include Sidekiq::Worker

  def perform
    PrimaryMailer.email.deliver_later
    SecondaryMailer.email.deliver_later
    puts "Primary mailer delivery count: #{PrimaryMailer.deliveries.count}"
    puts "Secondary mailer delivery count: #{SecondaryMailer.deliveries.count}"
  end
end
```
2. Have the appropriate mailers

Primary:

```
class PrimaryMailer < ApplicationMailer
  def email
    mail(to: 'isuPatches@yahoo.com', subject: 'Primary Email')
  end
end
```

Secondary:

```
class SecondaryMailer < ApplicationMailer
  def email
    mail(to: 'isuPatches@yahoo.com', subject: 'Secondary Email')
  end
end
```

3. Run a set of specs

```
require 'spec_helper'

describe MailerWorker do
  it 'has the appropriate count for PrimaryMailer' do
    expect {
      perform_enqueued_jobs do
        subject.perform
      end
    }.to change{ PrimaryMailer.deliveries.count }.by(1)
  end

  it 'has the appropriate count for SecondaryMailer' do
    expect {
      perform_enqueued_jobs do
        subject.perform
      end
    }.to change{ SecondaryMailer.deliveries.count }.by(1)
  end
end
```

4. Note the count for both PrimaryMailer and SecondaryMailer is 2 instead of 1

```
Primary mailer delivery count: 2
Secondary mailer delivery count: 2
F

Failures:

  1) MailerWorker has the appropriate count for SecondaryMailer
     Failure/Error:
       expect {
         perform_enqueued_jobs do
           subject.perform
         end
       }.to change{ SecondaryMailer.deliveries.count }.by(1)
     
       expected `SecondaryMailer.deliveries.count` to have changed by 1, but was changed by 2
     # ./spec/workers/mailer_worker_spec.rb:13:in `block (2 levels) in <top (required)>'
```

### Expected behavior
PrimaryMailer.deliveries is 1
SecondaryMailer.deliveries is 1

### Actual behavior
PrimaryMailer.deliveries is 2
SecondaryMailer.deliveries is 2

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.4.1

**Rspec version**: 3.6.0

**Comment by isuPatches** [comment] 2017-05-07 17:07
I've also tried manually clearing the value:

```
 before(:each) do
    ActionMailer::Base.deliveries.clear
  end
```

but in some cases, the count still seems weird to me, but I could totally be doing something wrong.

**Comment by shivabhusal** [comment] 2017-05-21 11:11
Have you considered this example: 

Performs all enqueued jobs in the duration of the block.
```ruby
def test_perform_enqueued_jobs
  perform_enqueued_jobs do
    MyJob.perform_later(1, 2, 3)
  end
  assert_performed_jobs 1
end
```
This method also supports filtering. If the :only option is specified, then only the listed job(s) will be performed.
```ruby
def test_perform_enqueued_jobs_with_only
  perform_enqueued_jobs(only: MyJob) do
    MyJob.perform_later(1, 2, 3) # will be performed
    HelloJob.perform_later(1, 2, 3) # will not be performed
  end
  assert_performed_jobs 1
end
```
**point is**: Since there are two `deliver_later`s and you did not specify which particular Job to skip/perform, it performs both of the jobs. Hence you are seeing the count `2`. I might be wrong though, just trying to help.

**Comment by shivabhusal** [comment] 2017-05-21 11:24
[As per this line ](https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/delivery_methods.rb#L47) it seems that no matter what `MailerClass` you are sending message, it will untimately wind up to [Mail::TestMailer](https://github.com/mikel/mail/blob/cfff6c866bda6485210d304f72293c29f6045e81/lib/mail/network/delivery_methods/test_mailer.rb) of `gem 'mail'`. Therefore the counts you are seeing is `global` not `Mailer` specific.

**Comment by isuPatches** [comment] 2017-05-21 19:52
Ahhh...okay...I was expecting it to be specific to the other mailer classes.  If this is intended/expected due the nature of tests, disregard...it just threw me off when I stumbled across this.

**Comment by kylestengline** [comment] 2017-08-10 06:40
I've also run into this. 
I realize this is probably painfully obvious, but for some clarification; the intended/expected behavior is that the test should return 2 and not 1, correct? This is due to the global count and not the mailer specific count?

**Comment by rafaelfranca** [comment] 2017-08-11 19:05
Correct. Closing since this is not an issue.

**Closed by rafaelfranca** 2017-08-11 19:05 UTC
