### ISSUE TITLE
where(enum_attribute: :value) working incorrect

### ISSUE THREAD

**Issue by woto** [rails/rails#21972] opened 2015-10-16 15:22 UTC
Hi, i found that problem were fixed in master branch, but it exists in 4.2.4

4.2.4

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.4'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :conversations, force: true  do |t|
    t.integer :status
  end
end

class Conversation < ActiveRecord::Base
  enum status: [ :active, :archived ]
end

class BugTest < Minitest::Test
  def test_association_stuff
    conv = Conversation.create!(status: :archived)
    assert_equal Conversation.archived, Conversation.where(status: :archived)
  end
end
```

master

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :conversations, force: true  do |t|
    t.integer :status
  end
end

class Conversation < ActiveRecord::Base
  enum status: [ :active, :archived ]
end

class BugTest < Minitest::Test
  def test_association_stuff
    conv = Conversation.create!(status: :archived)
    assert_equal Conversation.archived, Conversation.where(status: :archived)
  end
end
```

**Comment by davidcelis** [comment] 2015-10-16 23:37
If the problem is fixed on master, there isn't really anything to do here. You'll need to wait for the Rails team to release a new version of 4.2 (and potentially previous minor versions if they plan a backport).

**Comment by woto** [comment] 2015-10-17 01:38
Rail master branch is v5, isn't it?
https://github.com/rails/rails/blob/master/RAILS_VERSION

Commenting from cell phone, unable to view in console while running test.

**Comment by davidcelis** [comment] 2015-10-17 07:11
Do you know what commit fixed your issue? Is it not also present in 4-2 stable or any other branch?

**Comment by woto** [comment] 2015-10-17 09:54
@davidcelis Don't know

**Comment by rafaelfranca** [comment] 2015-10-17 18:55
It was not a commit but a serie of refactorings and changes in the implementation that made it possible. It is not easy to backport so it will be not made.

**Closed by rafaelfranca** 2015-10-17 18:55 UTC
