### ISSUE TITLE
Rails 5: NoMethodError: undefined method `default_scope_override'

### ISSUE THREAD

**Issue by bdmac** [rails/rails#25838] opened 2016-07-14 22:23 UTC
### Steps to reproduce

Unable to provide steps to reproduce as this exception was logged in staging environment after upgrading to Rails 5. Has been logged 6 times.
### Expected behavior

Exception should not happen... 😄 
### Actual behavior

Received the following exception:

```
NoMethodError: undefined method `default_scope_override' for #<Class:0x007fdd05ebe7b0> Did you mean? default_scope_override=
```

Here is a public link to the exception in Honeybadger showing the full backtrace: https://app.honeybadger.io/fault/45385/81558167c102a4255d65a56a00d53244

Thinking it may have been a gem issue I grepped our entire gemset folder for references to this method and found nothing besides activerecord:

```
bdmac@brian-mbpro:~/code/bishop(chore/rails-5)$ grep -ri default_scope_override ~/.gem/ruby/2.3.0/gems/
/Users/bdmac/.gem/ruby/2.3.0/gems//activerecord-5.0.0/lib/active_record/scoping/default.rb:        class_attribute :default_scope_override, instance_writer: false, instance_predicate: false
/Users/bdmac/.gem/ruby/2.3.0/gems//activerecord-5.0.0/lib/active_record/scoping/default.rb:        self.default_scope_override = nil
/Users/bdmac/.gem/ruby/2.3.0/gems//activerecord-5.0.0/lib/active_record/scoping/default.rb:          if self.default_scope_override.nil?
/Users/bdmac/.gem/ruby/2.3.0/gems//activerecord-5.0.0/lib/active_record/scoping/default.rb:            self.default_scope_override = !Base.is_a?(method(:default_scope).owner)
/Users/bdmac/.gem/ruby/2.3.0/gems//activerecord-5.0.0/lib/active_record/scoping/default.rb:          if self.default_scope_override
```
### System configuration

**Rails version**: Rails 5.0.0

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]

**Comment by maclover7** [comment] 2016-07-15 00:20
Thank you for providing a public Honeybadger link, but to be able to get to the root of this, 
can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? However, as you mentioned, this error could be caused by a gem included in your project doing something funky.

**Comment by prathamesh-sonpatki** [comment] 2016-07-16 13:30
This looks like an issue where some gem or 3rd party code is using namespace `ActiveRecord::Scoping` or `ActiveRecord::Scoping::Default`. The reproduction script can help.

**Comment by nasa42** [comment] 2017-03-29 09:02
I believe this issue can be closed in favour of https://github.com/rails/rails/issues/27418.

**Closed** 2017-03-29 17:05 UTC
Labels: activerecord

**Comment by shepmaster** [comment] 2018-08-20 21:23
See also #33209 which addresses a similar issue about lazily autoloading namespaced classes concurrently.
