### ISSUE TITLE
Different result .group(enum).count with PostgreSQL adapter

### ISSUE THREAD

**Issue by AlejandroJL** [rails/rails#27511] opened 2016-12-30 18:07 UTC
### Steps to reproduce
```
class App < ApplicationRecord
   has_many :experiments, dependent: :destroy
end
```

```
class Experiment < ApplicationRecord
   enum state: { inactive: 'Inactive', active: 'Active' }, _suffix: true
end

```
In rails console with _development_ environment

```
App.first.experiments.group(:state).count
=> {"Running"=>1, "Finished"=>1, "Draft"=>1}
```

In _production_ environment:
```
App.first.experiments.group(:state).count
=> {"running"=>1, "finished"=>1, "draft"=>1}
```

### Expected behavior
Same result 

### Actual behavior
Different result

### System configuration
Rails 5.0.1, 5.0.0.1, 5.0.0
Ruby 2.3.3
PostgreSQL 9.6

Thanks!

**Comment by matthewd** [comment] 2016-12-30 18:58
Duplicate of #27438

**Closed by matthewd** 2016-12-30 18:58 UTC
