### ISSUE TITLE
AR: define_attribute_methods is not fired when record is loaded from marshal

### ISSUE THREAD

**Issue by printercu** [rails/rails#18659] opened 2015-01-23 16:01 UTC
When loading marshaled record `define_attribute_methods` is not fired. So if there was no calls to `.new` before, the record wont have attribute methods. I don't even know if this can be fixed in rails, or this is ruby's issue (cause there is no callbacks after load in marshal).

There is `marshal_load` method, which can be defined in model, but the problem that there is no superclass method for it.

For now I've workaround: firing `define_attribute_methods` manually right before `Marshal.load`.

Any ideas? Thanks in advance!

cc @tenderlove

**Comment by sgrif** [comment] 2015-01-23 21:57
Duplicate of https://github.com/rails/rails/issues/18339

**Closed by sgrif** 2015-01-23 21:57 UTC

**Comment by printercu** [comment] 2015-01-24 03:50
@sgrif it doesn't. `initialize` isn't called when Marshal loads resource. reopen?

**Comment by sgrif** [comment] 2015-01-24 03:56
Sorry, I referenced the wrong issue (I just quickly searched for one involving attribute method definition, I had forgotten that there's been more than one)...

This issue has definitely already been resolved, though. Feel free to test for yourself on 4-2-stable, or master. If you think there's still a bug which hasn't been resolved, please provide a script that can be used to reproduce the issue, using this template: https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

**Comment by printercu** [comment] 2015-01-25 17:10
@sgrif I've checked my app with rails 4-2-stable, there is still the issue.

I've made testcase for `activerecord/test/cases/attribute_methods_test.rb`

```ruby
  def test_generated_attr_methods_are_defined_after_marshal_load_overwritten
    dump = Marshal.dump(Computer.new)
    assert_not_equal [], Computer.generated_attribute_methods.instance_methods
    Computer.undefine_attribute_methods
    assert_equal [], Computer.generated_attribute_methods.instance_methods
    Marshal.load(dump)
    assert_not_equal [], Computer.generated_attribute_methods.instance_methods
  end
```

It fails on last assertion in master.

**Comment by onyxraven** [comment] 2016-09-16 17:29
I know this is an old issue but I think this is the same issue I'm seeing here.

https://gist.github.com/onyxraven/24c7bcb8a85c42688a694c05c0a8db50

What I think is going on is that `class.define_attribute_methods` is being called within initialize.  So for a class we haven't seen before, that hasn't yet been run.  Marshal.load bypasses initialize.

**Comment by printercu** [comment] 2016-09-18 13:02
@sgrif was it supposed to be reopened?

**Comment by kamaljoshi** [comment] 2016-12-13 17:39
@sgrif This error came because of this change: https://github.com/rails/rails/commit/84cf156e2428551069d6fba5547fc41bc42182b2#diff-dfe09551f2188457e7e1891d86047c57

Before this change, the missing method was being defined and appropriately called.

Can we reopen this?

**Comment by rafaelfranca** [comment] 2016-12-13 19:10
Please open an new issue with all information you have and link to this issue. We prefer to not reopen old issues.

**Comment by kamaljoshi** [comment] 2016-12-13 19:41
@rafaelfranca Sure, I will create a new issue.
