### ISSUE TITLE
Getting started - 7.5 deleting an article -  add reference to turbo_include_tags

### ISSUE THREAD

**Issue by lind25** [rails/rails#44879] opened 2022-04-12 15:22 UTC
### Steps to reproduce
Following the getting started guide on step 7.5 deleting an article - click on the "Destroy" link.

### Expected behavior
A pop up should appear saying "Are you sure?"

### Actual behavior
Nothing.

Expected behaviour can be produced by adding
<%= turbo_include_tags %>

### System configuration
**Rails version**:
7.0.2.3
**Ruby version**:
3.1.1p18 2022-02-18

**Comment by ghiculescu** [comment] 2022-04-18 22:16
Hmm, the Turbo include tags should get added automatically when the app is created. Did that not happen in your case?

**Comment by lind25** [comment] 2022-04-19 19:10
> Hmm, the Turbo include tags should get added automatically when the app's layout is created. Did that not happen in your case?

It did not.
Below is the app/views/layouts/application.html.erb that was automatically generated.

`<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>`

**Comment by zahnow** [comment] 2022-04-26 20:19
Ran into this as well.

**Comment by OscarPay** [comment] 2022-05-25 15:05
same happened to me

**Comment by skipkayhil** [comment] 2022-05-27 16:22
Can one of the people who has run into this issue share the `rails new` command used and the full logs of it running? It's hard to know what went wrong without reproduction (if you can reproduce with a dockerfile that would be even better)

**Comment by lind25** [comment] 2022-05-29 18:50
> Can one of the people who has run into this issue share the `rails new` command used and the full logs of it running? It's hard to know what went wrong without reproduction (if you can reproduce with a dockerfile that would be even better)

There is an error related to turbo when running new (line 250 in the attached).  I'm not sure if this is causing the issue or the fact rails is aborted (line 241).  [rails new blog2 log.txt](https://github.com/rails/rails/files/8794043/rails.new.blog2.log.txt)

I am running Windows 11 and per https://github.com/rubygems/rubygems/issues/5269 the tzinfo-data issue is expected (I have run 'bundle install' and 'rails importmap:install' after updating the Gemfile but I still need to add <%= turbo_include_tags %> manually.

**Comment by skipkayhil** [comment] 2022-05-29 19:39
> > Can one of the people who has run into this issue share the `rails new` command used and the full logs of it running? It's hard to know what went wrong without reproduction (if you can reproduce with a dockerfile that would be even better)
> 
> 
> 
> There is an error related to turbo when running new (line 250 in the attached).  I'm not sure if this is causing the issue or the fact rails is aborted (line 241).  [rails new blog2 log.txt](https://github.com/rails/rails/files/8794043/rails.new.blog2.log.txt)
> 
> 
> 
> I am running Windows 11 and per https://github.com/rubygems/rubygems/issues/5269 the tzinfo-data issue is expected (I have run 'bundle install' and 'rails importmap:install' after updating the Gemfile but I still need to add <%= turbo_include_tags %> manually.
> 
> 

Perfect, this log helps a lot. It looks like the issue is a cascade of errors: `importmap:install` fails because of the rubygems issue and this leads to `turbo-install` failing because it doesn't find the importmap file or a `package.json`.

You can see what should be running if both installs succeeded here: https://github.com/hotwired/turbo-rails/blob/main/lib/install/turbo_with_importmap.rb

I'll also add that when I looked at `turbo-rails`, I saw using `turbo_include_tags` is deprecated: https://github.com/hotwired/turbo-rails/blob/3355f2fae0a2bd3653ccccc62d9395b677c4ee1f/app/helpers/turbo/includes_helper.rb#L2 so I would recommend using one of the techniques `turbo:install` uses to add the library and not use the helper.

**Comment by lind25** [comment] 2022-05-29 20:51
Thank you.
Running the below seems to work for me:

rails new blog
* manually amend gemfile for tzinfo-data bug *
bundle install
bundle add importmap-rails
rails importmap:install
rails turbo:install

**Comment by skipkayhil** [comment] 2022-06-29 14:15
Closing this now because a fix for the latest Ruby on Windows has been released in Bundler 2.3.17.

Updating with `gem install bundler` should prevent the `tzdata-info` issue seen above when running `rails new`.

**Closed by skipkayhil** 2022-06-29 14:15 UTC
Labels: docs
