### ISSUE TITLE
Rails 7.2 fails to start on MacOS

### ISSUE THREAD

**Issue by n-rodriguez** [rails/rails#52561] opened 2024-08-11 03:13 UTC
### Steps to reproduce

Run Rails 7.2 on macOS (Sonoma 14.6.1).

### Expected behavior

Rails should start

### Actual behavior

```sh
[2024-08-11T05:10:47.738937 #28356 #]  INFO ["07c7256b-0e43-485b-850a-e02576be893b"] - concerto.puma: Started GET "/" for 127.0.0.1 at 2024-08-11 05:10:47 +0200
objc[28356]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[28356]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

### System configuration

**Rails version**: 7.2.0

**Ruby version**: 3.3.4

Thank you!

**Comment by roharon** [comment] 2024-08-11 03:52
I got similar problem when run with puma, spring.


Did you try this?

```bash
export DISABLE_SPRING=true
```

this page would be helpful.

https://stackoverflow.com/questions/52671926/rails-may-have-been-in-progress-in-another-thread-when-fork-was-called

**Comment by n-rodriguez** [comment] 2024-08-11 04:20
Hi @roharon! 

I don't use `spring` so 

```sh
export DISABLE_SPRING=true
```

doesn't work but your link was very helpful because 

```sh
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

does work 👍 

Thank you!

**Comment by byroot** [comment] 2024-08-11 07:52
Closing as duplicate of https://github.com/rails/rails/issues/38560

**Closed by byroot** 2024-08-11 07:52 UTC
