### ISSUE TITLE
where.not doesn't work for polymorphic associations

### ISSUE THREAD

**Issue by DonGiulio** [rails/rails#26269] opened 2016-08-24 13:48 UTC
### Steps to reproduce

prepare the project, find the files here: 
https://gist.github.com/DonGiulio/b2c6296061124acc4028bbbe971fc5b7
```
$ rails new polymorphic
$ cp comment.rb polymorphic/app/models
$ cp hat.rb polymorphic/app/models
$ cp tshirt.rb polymorphic/app/models
$ cp migration.rb polymorphic/db/migrate
$ rake db:create db:migrate
$ rails console
```

in the console: 
```
ts = Tshirt.create(name: 'ts1')                    # => #<Tshirt id: 3, name: "ts1", created_at: "2016-08-24 13:27:38", updated_at: "2016-08-24 13:27:38">
ts.comments.create(comment: 'comment 1 on ts1')    # => #<Comment id: 9, commentable_type: "Tshirt", commentable_id: 3, comment: "comment 1 on ts1", created_at: "2016-08-24 13:27:38", updated_at: "2016-08-24 13:27:38">
ts.comments.create(comment: 'comment 2 on ts1')    # => #<Comment id: 10, commentable_type: "Tshirt", commentable_id: 3, comment: "comment 2 on ts1", created_at: "2016-08-24 13:27:38", updated_at: "2016-08-24 13:27:38">
hat = Hat.create(name: 'hat1')                     # => #<Hat id: 3, name: "hat1", created_at: "2016-08-24 13:27:38", updated_at: "2016-08-24 13:27:38">
hat.comments.create(comment: 'comment 1 on hat 1') # => #<Comment id: 11, commentable_type: "Hat", commentable_id: 3, comment: "comment 1 on hat 1", created_at: "2016-08-24 13:27:38", updated_at: "2016-08-24 13:27:38">
hat.comments.create(comment: 'comment 2 on hat 1') # => #<Comment id: 12, commentable_type: "Hat", commentable_id: 3, comment: "comment 2 on hat 1", created_at: "2016-08-24 13:27:38", updated_at: "2016-08-24 13:27:38">

Comment.where(commentable: hat).pluck(:id, :commentable_type, :commentable_id) #  => [[11, "Hat", 3], [12, "Hat", 3]]
Comment.where.not(commentable: hat).pluck(:id, :commentable_type, :commentable_id) # => []

# error, the previous result should contain comments 9 and 10. 
```

### Expected behavior
where.not should find the comments that do not belong to 'hat' 
(it should find the comment 9 and 10) 

### Actual behavior
where.not returns an empty list.

### Analysis
The where.not just negates every clause specified: 

positive version: 
```
Comment.where(commentable: hat).to_sql

"SELECT \"comments\".* 
    FROM \"comments\" 
    WHERE \"comments\".\"commentable_type\" = 'Hat' 
       AND \"comments\".\"commentable_id\" = 3"
```

negation: the `=` have just turned to `!=`
```
Comment.where.not(commentable: hat).to_sql

"SELECT \"comments\".*
   FROM \"comments\" 
   WHERE (\"comments\".\"commentable_type\" != 'Hat') 
       AND (\"comments\".\"commentable_id\" != 3)"
```
this is incorrect, the query should negate both clauses at the same time, rather than both indipendently. 

The correct query would be: 
```
"SELECT \"comments\".*
   FROM \"comments\" 
   WHERE (\"comments\".\"commentable_type\" != 'Hat') 
       OR (\"comments\".\"commentable_id\" != 3)"
```
this returns the correct results. 

using logic this explains why it needs to be an OR 
```
c = a AND b
!c = !(a AND b)
!c = !a OR !b

```
what we have now is: 
`!c = !a AND !b `
which is WRONG

### System configuration
Rails 4.1.14
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-darwin15.0]

still present in 
Rails 5.0.0.1
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by georgeclaghorn** [comment] 2016-08-24 13:52
This is a duplicate of #16983.

**Comment by DonGiulio** [comment] 2016-08-24 14:16
workaround: 
```

type = 'Hat'
id = 3
sql = <<-SQL
SELECT \"comments\".* FROM \"comments\" WHERE (\"comments\".\"commentable_type\" != '#{type}') OR (\"comments\".\"commentable_id\" != #{id})
SQL
ActiveRecord::Base.connection.execute(sql)
```

**Closed** 2016-08-24 15:46 UTC
