### ISSUE TITLE
Why does upsert_all disallow unique_by primary key?

### ISSUE THREAD

**Issue by kapso** [rails/rails#40059] opened 2020-08-16 20:58 UTC
I am looking to batch `UPDATE...` on my database, and found `upsert_all`. But it seems you cannot upsert using the primary key, so something like this... 

`Product.upsert_all([{id: 1, order_count: 23}, {id: 93, order_count: 67}], unique_by: :id)`

...results in the following error - `ArgumentError (No unique index found for id)`

Curious why does `upsert_all` disallows updates by primary key.  BTW, I did try `unique_by: :products_pkey` as well but that did not work either.

### System configuration
**Rails version**: `6.0.3.2`

**Ruby version**: `2.7.1`

**Comment by simi** [comment] 2020-08-16 21:06
Can you try to skip `unique_by` at all since you're using primary key and that's default option?

**Comment by kapso** [comment] 2020-08-16 22:29
Yea skipping the unique_by option is the first thing I had tried, but that doesn't work either.

**Comment by simi** [comment] 2020-08-16 22:37
Is your primary key present here?

```
ActiveRecord::Base.connection.schema_cache.primary_keys(Product.table_name)
```

**Comment by kapso** [comment] 2020-08-17 02:56
@simi yes this is the response for the above `"id"`

**Comment by simi** [comment] 2020-08-17 08:00
I can't reproduce your problem. Can you share script to reproduce this? You can use prepared template for that - https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb.

**Comment by KapilSachdev** [comment] 2020-08-17 08:48
Duplicate of #36528


```ruby
# frozen_string_literal: true

begin
  require 'bundler/inline'
rescue LoadError => e
  warn 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', '~>6.0.3'
  gem 'sqlite3'
  gem 'byebug'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :products, force: true do |t|
    t.bigint :order_count
  end
end

class Product < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    Product.upsert_all([{ id: 1, order_count: 23 }, { id: 93, order_count: 67 }], unique_by: :id)
  end
end
```
Failing on 6-0-stable.
Passing on master due to 
https://github.com/rails/rails/blob/9078abc0b8ce1739cdd5a410c084038312e55126/activerecord/lib/active_record/insert_all.rb#L77-L78

This is in master for a year now, so unsure whether its being targeted for 6.1 or wasn't able to get into 6.0.x somehow, but i think it should be backported.

cc @kaspth

**Comment by KapilSachdev** [comment] 2020-09-09 13:10
@jonathanhefner can you provide some information if this should be backported or not?
We can close this if we are not interested in backporting this.

**Comment by SampsonCrowley** [comment] 2020-09-24 21:07
this really feels like it should be backported. was extremely surprised that PK index doesn't count as a unique index to use when specifying PK value to skip needing to check all indexes for known unique values

**Comment by kapso** [comment] 2020-10-11 04:50
Curious, if there's a fix coming out for this anytime soon? since `6.0.3.4` did not have it.

Thanks.

**Comment by kapso** [comment] 2020-11-14 04:50
Just noticed that `6.1.0.rc1` is out, has the above issue been fixed in 6.1?

**Comment by KapilSachdev** [comment] 2020-11-14 12:43
It will be shipped with `6.1.0` and is available in `6.1.0.rc1`(8389f99).

https://github.com/rails/rails/blob/8389f9902c3f0e984df17a77386493f856d7a1bb/activerecord/lib/active_record/insert_all.rb#L77-L78

**Comment by kapso** [comment] 2020-12-13 07:53
Updated to 6.1, still finding issues...

**1.** When combining `new record insertion` + `update existing records` in `upsert_all`, I see the following

```
ArgumentError (All objects being inserted must have the same keys)
```

**2.** When only doing `update existing records`, I see the following error 

```
ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR:  null value in column "name" violates not-null constraint)
```

for this `Product.upsert_all([{id: 85, count: 899929}, {id: 86, count: 9223232}])`

**Comment by SampsonCrowley** [comment] 2020-12-13 18:09
@kapso that's not related to this issue. Upsert is an "either update or insert" function. You have to provide the info necessary to insert records if they don't exist, and all records must have the same keys in the objects provided

**Comment by kapso** [comment] 2020-12-14 09:33
@SampsonCrowley what about issue `#2`? 

`product_name` column is already populated for model `Product` and I am just trying to bulk update the `count` column for the 2 rows.

**Comment by SampsonCrowley** [comment] 2020-12-14 09:38
@kapso idk what issue #2 is, but again the code you have provided is not how upsert works *or* what it's for, and your issue is not related to the issue in this thread

**Comment by kapso** [comment] 2020-12-14 09:57
@SampsonCrowley lemme ask you this way...

Is the following use of `upsert` incorrect, given I am trying to bulk update only the `count` column in the `Product` model?

`Product.upsert_all([{id: 85, count: 899929}, {id: 86, count: 9223232}])`

**Comment by SampsonCrowley** [comment] 2020-12-14 09:59
If the rows didn't exist yet, would those be valid records?

**Comment by kapso** [comment] 2020-12-14 10:55
@SampsonCrowley no they wont, coz `product_name` in `Product` model is `NOT NULL` in Postgres

**Comment by bobcats** [comment] 2021-03-03 20:21
@kapso I think what you're trying to achieve isn't possible currently because, as far as I can tell, the set of columns that are updated on conflict are the same as set of columns attempted to be inserted into. If you could control which columns are updated on conflict, I think then you could do what you're describing.

**Comment by SampsonCrowley** [comment] 2021-03-03 20:48
@bobcats @kapso what he is trying to do is perfectly possible, what you are looking for is the `updateMany` function to only *update* *many* records.

Once again, *upsert* is for *inserting* any non-existent records AND *updating* any that already exist in one action. You are using the wrong function for your purposes and your issue has *nothing* to do with the one the rest of us are trying to solve here in this issue

**Comment by arsduo** [comment] 2021-03-11 15:50
(I know this is off-topic, but I want to document it for anyone else ends up here after trying to use `upsert_all` as an `update_many`:)

I was trying to do the same thing as @kapso and running into the same issue -- I got it to work by providing all the attributes for the records to be updated:

```ruby
Product.upsert_all(
  products_to_update.map {|product| 
    product.attributes.symbolize_keys.merge(count: new_count_for_product(product))
  }
)
```

**Comment by arcreative** [comment] 2021-06-23 00:38
This is a huge problem for me, but I'm not sure why it's happening.  I have two models that I'm upserting in my `seeds.rb` file that work fine, but a third, nearly-identical model won't for whatever reason.  I have gone as far as to add another unique index on the `id` column, as well as specify it in the `unique_by` option, and nothing wants to work.

**Comment by arcreative** [comment] 2021-06-23 00:43
Figured it out--my migration for the model I was trying to upsert had a singularized name instead of a pluralized one.  This is definitely not the error message I expected in this situation, but upserts seem to be working as expected on primary keys.

**Comment by byroot** [comment] 2021-07-28 13:20
From my understanding this issue was resolved. Closing.

**Closed by byroot** 2021-07-28 13:20 UTC
Labels: activerecord
