### ISSUE TITLE
Rails 5.1.4: Empty request param parsed to array with empty string

### ISSUE THREAD

**Issue by vitalinfo** [rails/rails#30740] opened 2017-09-28 08:21 UTC
### Steps to reproduce
f.e. on `patch` request send `entity[title][]`, params will have `title: [""]`

### Expected behavior
expect get empty array

### System configuration
**Rails version**:
5.1.4

**Ruby version**:
2.4.1

**Comment by al2o3cr** [comment] 2017-09-29 12:28
AFAIK this is expected behavior. Here's some relevant specs (for `Rack::Utils.parse_nested_query`)

https://github.com/rack/rack/blob/6b942ff543416e0c82196f0790d4915c7eead4cb/test/spec_utils.rb#L159-L162

Depending on the exact format you send (with/without the `=`) you'll get either `nil` or `""`.

**Comment by pixeltrix** [comment] 2017-11-09 14:22
Closing because this is the expected behaviour and is Rack's responsibility anyway.

**Closed by pixeltrix** 2017-11-09 14:22 UTC

**Comment by sweetleon** [comment] 2017-11-27 19:31
Was this happening on previous version of Rails? I'm upgrading a client's codebase from 4.x and this is causing test failures, so it definitely didn't behave this way in 4.x.

**Comment by piotrimbierowicz** [comment] 2018-01-24 23:12
@vitalinfo Have you tried to fix this? I have the same issue after migration from rails 5.0.2 to 5.1.4

**Comment by vitalinfo** [comment] 2018-01-25 06:54
@piotrimbierowicz, not I don't
as said @pixeltrix this's expected behaviour, that's why I did some workaround in my project

**Comment by piotrimbierowicz** [comment] 2018-01-25 07:52
If it's an expected behaviour so how can I send an empty array in POST or PATCH request?

when my params are:
```
  campaign: {
    prospect_lists: []
  }
```

in the controller I get:

```
{"campaign"=>{"prospect_lists"=>[""]}
```

which is a big problem when you use Grape API, because it starts failing during params validation:

```
params do
  requires :campaign, type: Hash do
    optional :prospect_lists, type: Array do
      requires :id, type: Integer
      requires :add_new_prospects_automatically, type: Boolean
    end
    [...]
  end
end

patch '/:id' do
  [...]
end
```

Maybe I could find a workaround here, but what about an example, when you send an array of strings (for example tags for blog post), and instead of no tags you create empty tag because `[]` is converted to `[""]` each time.

@pixeltrix Do you know which version introduced that behaviour?

cc: @vitalinfo

**Comment by rafaelfranca** [comment] 2018-01-25 19:45
> how can I send an empty array in POST or PATCH request?

send the parameters as JSON or something that is not www-encoded.

**Comment by piotrimbierowicz** [comment] 2018-01-26 16:01
Thanks for your help! I didn't know that my specs don't do that. Problem solved ✅

**Comment by pokonski** [comment] 2018-04-11 08:26
https://github.com/rails/rails/issues/30740#issuecomment-360578558

what about GET requests?

**Comment by SUMAR7** [comment] 2020-06-03 12:52
> Thanks for your help! I didn't know that my specs don't do that. Problem solved

Can you please tell me how did you fix this issue for grape API? I'm having the same issue.

**Comment by ericproulx** [comment] 2020-06-08 17:12
> > Thanks for your help! I didn't know that my specs don't do that. Problem solved
> 
> Can you please tell me how did you fix this issue for grape API? I'm having the same issue.

We had the same issue in our test suite. We solved it by adding `as: :json` when calling the Grape api
```ruby
 post your_url, params: your_parameters, as: :json
```
