### ISSUE TITLE
Actioncable latency/client side ping feature.  

### ISSUE THREAD

**Issue by wadestuart** [rails/rails#24908] opened 2016-05-07 20:32 UTC
I have been looking at the actioncable stuff and it appears that the connection monitor relies on ping which is server -> client.   I am wondering if any thought has been made to have a client ping variation which is generated on the client periodically and hits the ac service with a immediate rebroadcast to that client.  It seems like this could not only provide an active check on the client side as to connection status but also if the ping payload is made to be time data would allow for a round trip latency estimation (current timestamp - returned ping timestamp).   

I am building this functionality for a new app and it seems like this could make sense to be generalized on the client/server.  I can imagine that many if not most apps built on actioncable would either want to display connection status / latency or at least take actions on it.  I don;t want to spend the time to generalize this if it is not wanted or already being planned somewhere.

**Comment by maclover7** [comment] 2016-05-07 21:22
Hmm, I don't think the current ping implementation is meant to work the way you are proposing. However, you could definitely create a `PingRebroadcastChannel` or the like in your own application, and implement this on your own (maybe even release it as a gem for others to use! 😄).

For any future feature requests, please send a message to the [rubyonrails-core mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core). Thanks!

**Comment by jeremy** [comment] 2016-05-07 21:26
We've considered it and have come across the need ourselves. Particularly, on client suspend/resume and visibility changes when you'd like to immediately check connection liveness rather than waiting ~seconds to be notified.

In fact, client-initiated pings (with server pongs) may be a better route overall. Please do pursue it.

(We also do round-trip latency gauging using our own app monitoring channels, including pubsub.)

**Comment by wadestuart** [comment] 2016-05-07 23:36
@maclover7 Sorry for the improper placement I will bring this to the mailing list -- I apologize for not being informed about the proper route. 

@jeremy Yeah,  from what I am seeing it makes a lot of sense to bring such a rebound up the stack slightly to allow for a short circuit (fast path) for the response instead of creating pub sub channels and logic to segment the data between clients.  Basically the service understanding that (if configured of course) to echo back to the client on a virtual pub/sub with very little overhead. 


As soon as I complete my current project I will work to generalize it in a pr and bring a post to the mailing list.    Thanks!

**Comment by NullVoxPopuli** [comment] 2016-05-08 00:37
Is there anyway to tell if a web socket is open / stale / disconnected? like, If the server for whatever reason stops responding to me? how do try re-connecting?
Been trying to solve this for my action_cable_client gem https://github.com/NullVoxPopuli/action_cable_client

From my research, it seems regular web-socket implementations do ping/pong messages, but it feels messy. Shouldn't the connection itself somehow know of its own state?

**Comment by jeremy** [comment] 2016-05-08 00:46
@NullVoxPopuli It does know its own state, but only to the extent that TCP exposes it. You can have a keepalive connection that had been severed and neither party may be aware.

The WebSockets protocol does have ping/pong frames, but they're meant for protocol-level keepalive, not heartbeating, and are server→client only.

More on this: https://www.w3.org/Bugs/Public/show_bug.cgi?id=13104

**Comment by wadestuart** [comment] 2016-05-08 01:21
From what I see the current ping(heartbeat) in AC is meant to touch the connection periodically to try to sense down states and is application level not ws protocol.   I will say the choice of label is unfortunate as there are two different beasts here,  protocol and application level with overlapping names.  

The current rails client side and server side,  from my reading of the code, will have the server periodically (every 3 seconds by default) send a message of type ping to the client.  The client js will take note of receiving the ping and if a certain amount of the pings are missed (by default 2 or 6 seconds) it will take action to reconnect.   For my needs I not only want the client to take a more active role in this timeout but also tend to always need some sort of latency detection (latency is one of the core reasons for my want to use websockets). 

I am thinking that instead of (or even in addition to) the current server->client ping,  that by creating a client side periodic (and callable function) that pings the server with a data payload consisting of Date.getTime() and perhaps a increment,  the server having a short curcut for that message type may simply echo back on that connection.  This creates a round trip that ensures from the client (where you would want to display such things most of the time) there is an active way to test the validity of the connection status and if the client simply does a current Date.getTime() - the echoed Date.getTime() it can drop the tested round trip latency into an getter.  

The net is instead of just kind of waiting for 6 seconds of failure to receive pings from the server to mark the page or take action on the client,  the client can both have an active periodic test,  a runable test to guard specific actions that want to ensure an active and working connection,  and receive "free" latency information for display or taking action on (such as degrading down to a high latency behavior).  Given a increment/id in addition to time payload there could also be a "free" indicator for lost messages/percentage.

**Comment by jeremy** [comment] 2016-05-08 01:39
> I will say the choice of label is unfortunate as there are two different beasts here, protocol and application level with overlapping names.

Confirm. Keepalive pings vs heartbeat… beats.

> [if] pings are missed (by default 2 or 6 seconds) it will take action to reconnect

Confirm.

> I not only want the client to take a more active role in this timeout but also tend to always need some sort of latency detection

Perfect case for client→server heartbeating.

> The net is instead of just kind of waiting for 6 seconds of failure to receive pings from the server to mark the page or take action on the client, the client can both have an active periodic test, a runable test to guard specific actions that want to ensure an active and working connection, and receive "free" latency information

Note this can largely be done with server→client pings as well. The difference is that client-initiated heartbeats mean they can control liveness checks and that they can inform the server of current state (e.g. sequence number, last message received, etc.)

Arguably we can & should switch to client-initiated heartbeats wholesale. The server is in the dark about client state now.

**Comment by wadestuart** [comment] 2016-05-19 22:59
just giving a status on this,  I am in the middle of a site launch and will not be able to factor this for a few weeks.  If anyone else wants to take a shot please feel free else I will get a PR up as soon as I am able (work > pr =).   If this is too long for this to sit feel free to close and I can reopen after I get the PR ready.

**Comment by danielrhodes** [comment] 2016-05-21 17:30
@wadestuart I've played around this stuff quite a bit, so familiar with the issues concerning what you're talking about.

For clarification: What you are proposing is to change the ping from being initiated server side to being initiated client side, correct?

And is this because the timeout you are observing on the client is taking too long? (e.g. you want to be notified faster of a disconnect). Or do you not trust that when the monitor says it is connected that it is really connected? (this might be because you are sending a high rate of messages, and can't afford to lose any).

Here's how I would weigh in on this:
- I think this could be a good idea. Then clients can change their ping frequency to their liking on the client.
- The server still needs to do a ping to know that a client is still connected. The way I would propose changing this is to send a websocket ping frame, which all browsers support. Unfortunately we can't do the websocket ping frame from the client side because it isn't in the JS client.

**Comment by wadestuart** [comment] 2016-05-21 19:20
> For clarification: What you are proposing is to change the ping from being initiated server side to being initiated client side, correct?

Kind of,   I think the server side ping is useful,  so I do not know that we would want to remove the functionality.  If we did I would think the server side would need to be rewritten to passively listen for the client initiated pings to retain the server side disconnect.  I think it may be easier to leave the server side like it is (given it just sends out 1 message every 3 seconds and is low overhead).

I think the client should:

- Once connected to WS,  trigger a ping (mind you we are not talking protocol ping frames here just app level pings) on a configurable period (defaulting at 3 seconds).  
- The payload on the ping should be a counter and timestamp.   
- The server should be modified to expect these pings from the client and just do a echo of the payload unchanged back to the client (without overhead of setting up a pub/sub).  
- The client, when receiving the ping should set a getter that takes the current client time and subtracts the timestamp in the return ping which represents round trip latency.  
- The client when noticing the counter has skipped an expected response should set a getter with some sort of indication that there has been lost messages.
- The client disconnect/reconnect code path should be reworked to timeout window on the client initiated ping return instead of its current behavior of a window based on when it last received a ping from the server.  
- I think the message type should be unique between the server side ping and the client ping.


> And is this because the timeout you are observing on the client is taking too long? (e.g. you want to be notified faster of a disconnect). Or do you not trust that when the monitor says it is connected that it is really connected? (this might be because you are sending a high rate of messages, and can't afford to lose any).

It is taking too long,  not configurable on the client side,  it is a passive check,  it is initiated by the side that normally does not need to handle most of the scenarios of a disconnect/reconnect and given certain disconnect types the client would not know it has been disconnected until the system's tcp timeout occurred (which is also why I don't think we can just get rid of the server side ping). 

>The server still needs to do a ping to know that a client is still connected. The way I would propose changing this is to send a websocket ping frame, which all browsers support responding to (Faye supports this as well). Unfortunately we can't do the websocket ping frame from the client side because it isn't in the JS client, but that doesn't matter.

This is not a protocol level ping --  just a plain jane app level message of type "ping" (maybe we should relabel this in the code to heartbeat or some such to stop the name overlap).

**Comment by Undo1** [comment] 2016-06-10 22:40
Throwing my two cents in on this: It'd really be nice to have the *ability* to reconfigure this (or turn it off completely!). I'm running a single always-on service in Python (using the `websocket` lib) that is talking to my Rails app. They should have a very stable connection anyway, and I know this ahead of time.

**Comment by Preen** [comment] 2016-11-15 07:13
Any news on this?

**Comment by Undo1** [comment] 2016-11-16 18:18
@Preen There is a way to do it, I've confirmed that http://stackoverflow.com/a/40125618/1849664 works.

**Comment by wadestuart** [comment] 2016-11-16 19:46
I have 2 different versions of code to do most of this right now but I ended up having to fork out and they are commingled with other changes for one of my projects that I can't release.   I will need to spend some time extracting it out to the rails head for a pr and add in a little functionality for the disable/configure portions.  I will try to make some time to do this as soon as I can but I am stuck on a product launch of Dec 15th so its a roulette spin at this point on the timing.

**Comment by vincentwoo** [comment] 2016-12-26 03:58
Has there been any movement on this? Now that actioncable is being pushed as a canonical happy path for rails, I think having more robust connection status should be a big priority!

**Comment by Undo1** [comment] 2017-03-27 19:04
... this is a feature request, not a bug.

**Comment by rafaelfranca** [comment] 2017-03-27 19:13
Thanks for commenting. Since we don't accept feature requests in the issue tracker I'm closing it.

**Closed by rafaelfranca** 2017-03-27 19:13 UTC
Labels: actioncable
