### ISSUE TITLE
In controller rescued error is shown if `rescue` clause raises

### ISSUE THREAD

**Issue by SzNagyMisu** [rails/rails#33414] opened 2018-07-22 08:42 UTC
### Steps to reproduce

[repro](https://github.com/SzNagyMisu/rails-controller-error) (see branches `rails-5.1.6` and `rails-5.2.0`)

If I rescue an exception in a controller action (let's say, an `ActiveRecord::RecordInvalid` after a `.create!` or an `#update!`) and then in the `rescue` clause I raise another exception (by making a typo, for example), I get the **original (rescued) exception** in the response. So if I have

    class BooksController < ApplicationController
      def create
        Book.create!(book_params)
      rescue ActiveRecord::RecordInvalid
        redirect_to new_book # sometimes I just forget the `_path` suffix
      end
    end

in case the `book_params` contain insufficient or erroneous data, and an `ActiveRecord::RecordInvalid` exception is raised, the response contains the error message `ActiveRecord::RecordInvalid in BooksController#create`, and it points to the line `Book.create!(book_params)`.

Then, a couple of hours of investigation show me, that I just forgot about the `_path` suffix of `#new_book_path` and it raises a `NameError`, which caused the action to collapse, only with the wrong error message.

In the **repro** I tried it against rails 5.1.6 and 5.2.0 (ruby 2.4.1). I tried to write tests for the expected behavior, but in _test environment_ this is exactly what I get: `NameError: undefined local variable or method ...`, so tests became meaningless.

I tried it out in the rails console too, and found out that the problem exists in _development_ and _production_ mode but not in _test_.

### Expected behavior
The action should show the **last exception** in the response, **not the rescued** one.

### Actual behavior
In _development_ and _production_ mode, if the `rescue` clause raises, the **original (rescued) exception** is shown

### System configuration
**Rails version**: 5.x

**Ruby version**: I don't think, it matters, but I'm using 2.4.1

**Comment by azbshiri** [comment] 2018-07-22 10:02
```
require "action_controller/railtie"
require "active_record/railtie"
require "test/unit"

class Book
  def self.create!(params)
    raise ActiveRecord::RecordInvalid
  end
end

class ApplicationController < ActionController::Base
end

class BooksController < ApplicationController
  def create
    Book.create!(book_params)
  rescue ActiveRecord::RecordInvali
    redirect_to new_book
  end

  def book_params
  end
end

class ApplicationControllerTest < Test::Unit::TestCase
  def test_that_it_returns_last_exception
    assert_raise(NameError) do
      BooksController.new.create
    end
  end
end

```

**Comment by SzNagyMisu** [comment] 2018-07-22 11:29
It does pass, like all my tests. As I mentioned, the problem exists only in _develompent_ and _production_ mode.

**Comment by azbshiri** [comment] 2018-07-22 11:45
Would you create a sample app for test purposes?

**Comment by SzNagyMisu** [comment] 2018-07-22 14:53
See link in first line of issue.

**Comment by azbshiri** [comment] 2018-07-22 16:29
this line reraises `ActiveRecord::RecordInvalid`cause of  `NameError` which is the exception https://github.com/rails/rails/blob/97321956e6c2d2bae1bf6f76fce5bfb909ab58b0/actionpack/lib/action_controller/metal/rescue.rb#L25

when i change `rescue_with_handler(exception) || raise` to `rescue_with_handler(exception) || raise (exception.class, exception.message(` it works properly. but `ActionView::MissingTemplate`

**Comment by azbshiri** [comment] 2018-07-22 16:30
@rafaelfranca how is that?

**Comment by azbshiri** [comment] 2018-07-22 16:54
```ruby
      def process_action(*args)
        super
      rescue Exception => exception
        request.env["action_dispatch.show_detailed_exceptions"] ||= show_detailed_exceptions?
        unless exception.nil? || exception.cause.nil?
          rescue_with_handler(exception) || raise(exception.class, exception.message)
        end
        rescue_with_handler(exception) || raise
      end
```

This fixes the problem but only one test fails
https://github.com/rails/rails/blob/97321956e6c2d2bae1bf6f76fce5bfb909ab58b0/actionpack/test/controller/new_base/render_template_test.rb#L145

**Comment by azbshiri** [comment] 2018-07-23 06:02
@schneems  what's your opinion?

**Comment by SzNagyMisu** [comment] 2018-08-06 14:09
Any progress? Is it decided that this issue is considered as a bug or not?

**Comment by rafaelfranca** [comment] 2018-08-07 18:32
The exception cause must be handled by the rescue handler and in this case the cause is the `ActiveRecord::RecordInvalid`. This mean that the default exception handler will handle it as a `ActiveRecord::RecordInvalid` not letting the original exception to be raised.

In this case we can't re-raise the `NameError` without letting the framework handle it and its cause. The behavior is correct, but the error page is wrong. I believe https://github.com/rails/rails/pull/32410 would fix this issue. Can you check the error page in the master branch?

**Comment by yuki24** [comment] 2018-10-02 15:56
This may be specific to the exception classes registered to `ActionDispatch::ExceptionWrapper.rescue_responses`. I've been thinking to make that consistent but hadn't had time for investigation.

@SzNagyMisu would you mind posting a screenshot of the debug view? That will give me a rough idea of what's going on only in development or production.

**Comment by yuki24** [comment] 2018-10-02 17:06
It does seem like we no longer need this check now that we show all the nested exceptions: https://github.com/rails/rails/blob/cf608ee34dd833b0357ef4eefa692db33242d2aa/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L38

**Comment by SzNagyMisu** [comment] 2018-10-04 10:36
This is what I see (using `rails 6.0.0.alpha from https://github.com/rails/rails (at master@3000c14)`)
![rails-controller-error-6](https://user-images.githubusercontent.com/25562614/46468594-235a1a80-c7d1-11e8-8d5a-8e4daefc815a.png)
If I click on the red bar, it shows the same box again with `line#7` highlighted.

The server log tells the same thing:

    Completed 500 Internal Server Error in 183ms (ActiveRecord: 0.0ms)

    ActiveRecord::RecordInvalid (Record invalid):
    app/controllers/main_controller.rb:7:in `create'


Was it that you asked, @yuki24?

**Comment by yuki24** [comment] 2019-01-02 11:20
I believe this issue still exists. I should be able to re-visit this later this month.

**Comment by yuki24** [comment] 2019-01-24 21:14
Ok, I have a fix for this, but it's sort of blocked by https://github.com/rails/rails/pull/35047. @rafaelfranca would you mind taking a look at #35047?

**Closed** 2019-01-25 19:44 UTC
