### ISSUE TITLE
Rails path helpers generate paths with %2F instead of slashes

### ISSUE THREAD

**Issue by ChannyAzar** [rails/rails#28249] opened 2017-03-02 10:14 UTC
### Steps to reproduce

I have in my routes file:

```
resources :projects, constraints: { id: /[a-...../ }, path: "/" do
    member do
      get :check_delete
    end
```

In my code: `check_delete_project_path(project)`

### Expected behavior
It should return the path seperated by slash.

### Actual behavior
The path is generated with %2F. Then the action fails with 404.

### System configuration
**Rails version**: 4.1.16

**Ruby version**: 2.1.9

### Note:
In Rails 4,1.1 it works fine. So it seems like a bug in one of the dependencies of Rails 4.1.16.

**Comment by pixeltrix** [comment] 2017-03-06 14:07
This is a duplicate of #16058 - there's extensive discussion on that ticket of workaround but essentially `to_param` which is what gets called by `check_delete_project_path(project)` is working correctly.

**Closed by pixeltrix** 2017-03-06 14:07 UTC
