### ISSUE TITLE
Rails 4.2.3 postgresql_adapter.rb problem for has_one through has_one scopes

### ISSUE THREAD

**Issue by mleszcz** [rails/rails#20718] opened 2015-06-27 14:36 UTC
user.rb:
has_one :subscription, -> { where(package_id: Package.permanent, current: true) }
has_one :package, through: :subscription

user.subscription call works, but it breaks on user.package call:

ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR: bind message supplies 4 parameters, but prepared statement "a6" requires 3

: SELECT "packages".* FROM "packages" INNER JOIN "subscriptions" ON "packages"."id" = "subscriptions"."package_id" WHERE "subscriptions"."user_id" = $1 AND "subscriptions"."current" = $2 AND "subscriptions"."package_id" IN (SELECT "packages"."id" FROM "packages" WHERE "packages"."category" = $3) LIMIT 1

from (..)/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:606:in `exec_prepared'

**Comment by rafaelfranca** [comment] 2015-06-27 16:33
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_recordg_gem.rb?

**Comment by mleszcz** [comment] 2015-06-27 19:27
Sure, here you go:
https://gist.github.com/mleszcz/6df56f688dc9daae04b4

The above test works fine on 4.2.2 but fails on 4.2.3.

**Comment by meinac** [comment] 2015-06-28 00:36
I've found the breaking point. [This](https://github.com/rails/rails/commit/c99bea1df015eeff4764e2d886de90620ab9fb67) commit causes the problem. I'll dive into deep for fixing this.

**Comment by meinac** [comment] 2015-06-29 19:34
The solution is simple but I don't know why this causes the problem. Changing [this line](https://github.com/rails/rails/commit/c99bea1df015eeff4764e2d886de90620ab9fb67#diff-4e9083413ec4b38982bb9e737f7454e8L21) solves the problem. There are some new issues because of this change.

**Comment by sgrif** [comment] 2015-06-30 20:11
This was fixed by https://github.com/rails/rails/commit/449241cc30545783419bd8f3cbc7b81137316001

**Closed by sgrif** 2015-06-30 20:11 UTC
Labels: activerecord, needs feedback
