### ISSUE TITLE
Confusing error message for before-* filters

### ISSUE THREAD

**Issue by gonchs** [rails/rails#22713] opened 2015-12-20 23:22 UTC
When the callback chain is terminated as a result of returning ```false``` in the ```before-*``` filter, the error returned looks like this:

```
(0.2ms)  BEGIN
Article Exists (0.6ms)  SELECT  1 AS one FROM "articles" WHERE "articles"."url" = 'http://www.example.com' LIMIT 1
(0.3ms)  ROLLBACK
```

This is consufing as it implies that the record was not saved due to a duplicate record which is not the case.

More info: https://stackoverflow.com/questions/34386602/record-exists-when-it-doesnt#34386875

**Comment by eileencodes** [comment] 2015-12-21 13:11
Hi @gonchs thanks for the report. What version of Rails are you using? Can you create a script that reproduces that issue using these templates https://github.com/rails/rails/tree/master/guides/bug_report_templates

**Comment by gwincr11** [comment] 2015-12-23 17:56
I believe this is related to this pull request https://github.com/rails/rails/pull/21218 which deprecates the above behavior in Rails 5.0

DEPRECATION WARNING: Returning `false` in Active Record and Active Model callbacks will not implicitly halt a callback chain in the next release of Rails. To explicitly halt the callback chain, please use `throw :abort` instead.

**Comment by rafaelfranca** [comment] 2015-12-23 17:59
Yes, it is. Closing since it is already fixed in master.

**Closed by rafaelfranca** 2015-12-23 17:59 UTC
