### ISSUE TITLE
Nested params are parsed incorrectly (unexpectedly) in controllers

### ISSUE THREAD

**Issue by simsalabim** [rails/rails#23997] opened 2016-03-02 04:39 UTC
Hi all, I ran into some inconsistency with controller parsing nested params.
### Steps to reproduce

``` ruby
post '/', params: {
  "items" => [
    { "brand" => { "name" => "Apple" }, "id" =>1, "color" => "pink" },
    { "brand" => { "name" => "Samsung" }, "id" => 2, "color" => "gold" },
  ]
}

# what appears in controller
{"items"=>[{"brand"=>{"name"=>"Samsung"}, "id"=>"1", "color"=>"pink"}, {"id"=>"2", "color"=>"gold"}]}
```

https://gist.github.com/simsalabim/6785d3c85bdd20f2e7c5
### System configuration

**Rails version**: 5.0.0.beta3 (current master)
**Ruby version**: 2.3.0

Oddly enough, the gist fails on earlier versions of Rails too (4-2-stable, 4-1-stable), while our production app works fine on 4.2.5.

Could anyone please tell me what I'm missing and where is the best place to start looking for params being processed in a controller action? Thanks.

**Comment by vipulnsward** [comment] 2016-03-02 06:37
I can confirm this on master.

**Comment by rthbound** [comment] 2016-03-02 14:36
@simsalabim  Does this behave the same in dev/production mode as it does in your test environment?

It reminds me of this: https://github.com/rack/rack/issues/951 and #23624.

**Comment by simsalabim** [comment] 2016-03-02 16:30
@rthbound `RAILS_ENV=production/test/development ruby bug_report.rb` return unexpected results consistently. I debugged Rack a little last night but had no clue where to start from. Thanks for the link!

**Comment by simsalabim** [comment] 2016-03-03 01:43
It looks exactly like rack/rack#951. I can confirm that with the following the test will pass:
```ruby
{
  "items" => [
    { "q" => "s", "brand" => { "name" => "Apple" }, "color" => "pink" },
    { "q" => "s", "brand" => { "name" => "Samsung" }, "color" => "gold" },
  ]
}
```
The bug turns dramatic if a hash is the only element of array: 
```ruby
# the following will always fail
{
  "items" => [
    { "brand" => { "name" => "Apple" } },
    { "brand" => { "name" => "Samsung" } },
  ]
}
```

**Comment by sikachu** [comment] 2016-03-04 20:52
Looks like this is Rack issue and it will be fixed soon. Going to keep this open in the mean time.

**Comment by dhh** [comment] 2016-03-11 14:42
@sikachu Any update?

**Comment by sikachu** [comment] 2016-03-11 14:45
@dhh I think we're waiting for rack/rack#1029 to be merged, then we can test against Rack master possibly.

**Comment by dhh** [comment] 2016-03-11 14:50
Maybe @tenderlove can help us getting that committed?

On Fri, Mar 11, 2016 at 3:46 PM, Prem Sichanugrist <notifications@github.com

**Comment by rthbound** [comment] 2016-03-12 00:07
Looks like https://github.com/rack/rack/pull/1029 is now merged. Time to retest?

**Comment by rthbound** [comment] 2016-03-12 00:12
The tests in the [reproduction script](https://gist.githubusercontent.com/simsalabim/6785d3c85bdd20f2e7c5/raw/61c119aac66adeaba298977bdede4de4a0d3f79c/rails_controller_params_bug_report.rb) now pass against master.

**Comment by vipulnsward** [comment] 2016-03-13 07:30
Thanks, this is now pending a rack release.

**Comment by dhh** [comment] 2016-03-21 15:29
@tenderlove Can you push out a new rack release to close this out?

**Comment by jrabramson** [comment] 2016-04-21 21:09
Using the newest rack seems to make the hash munging even worse, any update on this?

**Comment by vipulnsward** [comment] 2016-04-21 21:13
@jrabramson do you mean you see this on latest rack master?

**Comment by jrabramson** [comment] 2016-04-21 21:16
yes, it parses hashes inside of arrays even worse than the beta3 rack

**Comment by haggen** [comment] 2016-04-27 14:42
I'm getting something similar in `4.2.5`:

This:

```ruby
{
  thing: [
    { stuff: [1, 2] },
    { stuff: [3, 4] }
  ]
}
```

Ends up like this:
```ruby
{
  thing: [
    { stuff: [1, 2, 3, 4] },
    { }
  ]
}
```

**Comment by jrabramson** [comment] 2016-04-27 17:55
if you want to make it work the way you'd expect for now, you can change 'first_key` to `child_key` in /lib/rack/query_parser.rb line 100

**Comment by haggen** [comment] 2016-04-27 18:01
@jrabramson That's odd. The file you mentioned only exist in the branch master (version `2.0.0-beta`) in rack repository. But Rails `< 5` uses `1.6-stable`. Thought it was worth mentioning. 

I could locate the code you're talking about in file the `utils.rb`. I'm trying your suggestion right now.

Thanks!

**Comment by jrabramson** [comment] 2016-04-27 18:07
Ahh yea, in that version it hadn't seen seperated out yet.

**Comment by haggen** [comment] 2016-04-27 18:17
@jrabramson I'm afraid it didn't work.

Here's what I did: I took (this patch](https://github.com/rack/rack/pull/1029/files) and applied to the file `utils.rb` in the branch `1.6-stable`. It kinda fixed one problem, but created another, now instead of this:

```
{
  thing: [
    { stuff: [1, 2, 3, 4] },
    { }
  ]
}
```

I got this:

```
{
  thing: [
    { stuff: [1] },
    { stuff: [2] },
    { stuff: [3] },
    { stuff: [4] },
  ]
}
```

See how it respected the first `[]` in the field name, creating new objects instead o merging into the first. But now it splits the array inside the object into multiple parent objects.

My field's name is `...[thing][][stuff][]`.

Then I tried changing back `first_child` to `child_key` as you mentioned (but kept the other changes described in the patch I linked above) and it got back to the previous problem.

I'm sad. 😢

**Comment by jrabramson** [comment] 2016-04-27 18:20
Looking at the structure of what you want, I think it's impossible with the way rack currently parses nested hashes

**Comment by haggen** [comment] 2016-04-27 18:27
@jrabramson Well, that sucks. Thanks a lot for the heads up!

**Comment by jrabramson** [comment] 2016-04-27 18:40
@haggen can you pass the data as a json body instead of params?

**Comment by haggen** [comment] 2016-04-27 18:54
@jrabramson Guess I have to now. 😝  It's actually a `jsonb` column but I was using `fields_for` otherwise I'd have to use JS to generate the JSON before submitting it in hidden field or something. Thanks a lot for all the help much appreciated!

**Comment by Vivid** [comment] 2016-04-28 15:38
Hi all! I've stumbled upon a similar problem - not sure if I have to report it as a separate issue. 

In short: when submitting multipart form data with hash that has an element with blank value (i.e. blank text field of a form), it doesn't appear in params (the key is missing). When submitting the same form not as a multipart form data, the field presents in the hash (which is a correct behavior). [Attached is a test script demonstrating both scenarios](https://github.com/rails/rails/files/240862/test.rb.txt).

**Comment by Vivid** [comment] 2016-04-28 15:48
Update: after switching to use rack version from the master test passes, so pls ignore it :)

**Comment by tenderlove** [comment] 2016-05-06 02:01
Sorry if this is a bad question, but this test:

```
post '/', params: {
  "items" => [
    { "brand" => { "name" => "Apple" }, "id" =>1, "color" => "pink" },
    { "brand" => { "name" => "Samsung" }, "id" => 2, "color" => "gold" },
  ]
}
```

How does your app actually post data like that in production?  I'm having a hard time thinking of a way to make a form that posts an array of nested hashes.

**Comment by haggen** [comment] 2016-05-06 02:10
@tenderlove If I remember correctly this does the trick: `fields_for :items, [], index: nil do ... end`

**Comment by tenderlove** [comment] 2016-05-06 02:16
OK.  I think the parameter parser in Rack has the same ambiguity (with regard to this query) as it did in previous versions.  The change I made was that `params` would get encoded in the controller test and then decoded again so it's more similar to production behavior.  So, I think the correct fix is to make this type of controller test post the same data that the form would post in production.  Is there any way you can show me a sample form and a sample POST request?  I can probably do it, but if you happen to have that it would be a bit faster.  Thank you!!

**Comment by tenderlove** [comment] 2016-05-06 04:52
@haggen does Rails process the request correctly for that form?  I'm trying to figure out a situation where it would be possible for Rails to generate and post the data structure that @simsalabim is showing.

**Comment by simsalabim** [comment] 2016-05-06 15:23
> How does your app actually post data like that in production? I'm having a hard time thinking of a way to make a form that posts an array of nested hashes.

@tenderlove this is a good question. It's an API call, hence no form.

**Comment by sgrif** [comment] 2016-05-06 19:26
> It's an API call, hence no form

Could you not just use JSON then and eliminate the ambiguities?

**Comment by tenderlove** [comment] 2016-05-06 20:50
> @tenderlove this is a good question. It's an API call, hence no form.

Thanks.  Are you posting JSON, or are you encoding to the query params?  The reason I'm asking is because the Rails parameter + Rack query parameter parser has never supported a structure like this.  For example:

```ruby
require 'active_support/all'
require 'rack/utils'
require 'rack'

p Rack.release

x = {
  "items" => [
    { "brand" => { "name" => "Apple" }, "id" =>1, "color" => "pink" },
    { "brand" => { "name" => "Samsung" }, "id" => 2, "color" => "gold" },
  ]
}.to_query
generated = CGI.unescape(x)

p generated

p Rack::Utils.parse_nested_query generated
```

If you run this against older versions of Rack, it won't successfully round trip.  The thing that changed in Rails is that we encode the parameters in the controller test, then decode them in order to make the test similar to what actually happens in production.  If this doesn't round trip in your test, I suspect that the test isn't correct.  That is why I asked if there is a form or something that is able to produce this data structure.  If you're using an API endpoint, I would like to know how you are actually encoding the parameters (whether that is via JSON or query parameters).

Thank you!

**Comment by bmedenwald** [comment] 2016-06-07 20:12
I suspect this is related, but here's a different payload that exhibits the problem better.  I've boiled this down a ways, but it comes from a subset of Stripe's web hooks, which are sent as query parameters and not as a JSON body.

```ruby
require 'active_support/all'
require 'rack/utils'
require 'rack'

p Rack.release

x = {
 "data" => [
  { "id" => "sub_7fIggpcyHh1", "period" => { "start" => 1452012860, "end" => 1455900860 }, "plan" => { "id" => "Plan-A", "object" => "plan" } },
  { "id" => "sub_7fIggpcyHh1", "period" => { "start" => 1452012860, "end" => 1455900860 }, "plan" => { "id" => "Plan-B", "object" => "plan" } },
 ]
}.to_query
generated = CGI.unescape(x)

p generated

p Rack::Utils.parse_nested_query generated
```

If I run the above utilizing Rails 4.2.6 and Rack 1.6.4, it ultimately comes out correct.  It's an array with 2 objects, each with a key/value and 2 objects.

```ruby
{"data"=> [
  {"id"=>"sub_7fIggpcyHh1",
    "period"=>{"end"=>"1455900860", "start"=>"1452012860"},
    "plan"=>{"id"=>"Plan-A", "object"=>"plan"}},
  {"id"=>"sub_7fIggpcyHh1DfD",
    "period"=>{"end"=>"1455900860", "start"=>"1452012860"},
    "plan"=>{"id"=>"Plan-B", "object"=>"plan"}}
]}
```

but in Rails 5.0.0.rc1 and Rack 2.0.0.rc1 this is what I'll receive in the last step.  It's now an array of 5 objects, all the objects are different.  It changes the meaning pretty extensively.

```ruby
{"data"=> [
  {"id"=>"sub_7fIggpcyHh1", "period"=>{"end"=>"1455900860"}},
  {"period"=>{"start"=>"1452012860"}, "plan"=>{"id"=>"Plan-A"}},
  {"plan"=>{"object"=>"plan"},
    "id"=>"sub_7fIggpcyHh1DfD",
    "period"=>{"end"=>"1455900860"}},
  {"period"=>{"start"=>"1452012860"}, "plan"=>{"id"=>"Plan-B"}},
  {"plan"=>{"object"=>"plan"}}
]}
```

**Comment by bmedenwald** [comment] 2016-06-08 20:41
@tenderlove Here is another example, this time from a nested form with models using `accepts_nested_attributes_for` 2 levels deep.  The models look like this:

```ruby
class Company < ActiveRecord::Base
  accepts_nested_attributes_for :groups, allow_destroy: true
end

class Group < ActiveRecord::Base
  accepts_nested_attributes_for :memberships, allow_destroy: true
end

class Membership < ActiveRecord::Base
end
```

The payload from a single form that allowed both CRUD of Groups and Memberships to those Groups generates a payload like this:

```ruby
x = {
  "company" => {
    "groups_attributes" => [
      { "id" => 1, "memberships_attributes" => [ { "id" => 1, "_destroy" => true } ] },
    ]
  }
}.to_query
```

Using the same script above, this works with Rails 4.2.6/Rack 1.6.4, providing a single object in the `groups_attributes` array:

```ruby
{ "company" => { "groups_attributes" => [ { "id" => "1", "memberships_attributes" => [ { "_destroy" => "true", "id" => "1" } ] } ] } }
```

But doesn't in Rails 5.0.0.rc1/Rack 2.0.0.rc1, splitting them up into 2 items in the `groups_attributes`:
```ruby
{ "company" => { "groups_attributes" => [ { "id" => "1", "memberships_attributes" => [ { "_destroy" => "true" } ] }, { "memberships_attributes" => [ { "id" => "1" } ] } ] } }
```

It feels like this issue belongs back in the 5.0.0 milestone.  A data structure like this may not be common, but for those that do it's a big regression.

**Comment by tenderlove** [comment] 2016-06-08 21:01
@bmedenwald not sure if this *is* the same issue that OP reported, but I have been able to reproduce the case you've given.  We were able to roundtrip the query you provided with Rack 1.4.6, but not on 2.0.0.  I tracked down the problem to rack/rack@7f00781a7b9c75ddb86d0ab52132885ee88d5bac .  Unfortunately reverting that commit breaks other tests.  I'm tempted to revert rack/rack#1029, but that will cause rails/rails#23624 to be unfixed.

Fixing one bug causes another, but I'd rather *not* break existing apps than fix something already known to be broken.

@matthewd @jeremy any opinions?

**Comment by tenderlove** [comment] 2016-06-08 21:01
@bmedenwald also thank you very much for providing a test case that would break in one version and not another.  I really appreciate it!

**Comment by tenderlove** [comment] 2016-06-08 21:03
```ruby
require 'rack/utils'
require 'rack'
require 'minitest/autorun'
require 'cgi'

p Rack.release

class MyTest < Minitest::Test
  def query
    "data[][id]=sub_7fIggpcyHh1&data[][period][end]=1455900860&data[][period][start]=1452012860&data[][plan][id]=Plan-A&data[][plan][object]=plan&data[][id]=sub_7fIggpcyHh1&data[][period][end]=1455900860&data[][period][start]=1452012860&data[][plan][id]=Plan-B&data[][plan][object]=plan"
  end

  def test_round_trip
    x = {
      "data" => [
        { "id" => "sub_7fIggpcyHh1", "period" => { "start" => '1452012860', "end" => '1455900860' }, "plan" => { "id" => "Plan-A", "object" => "plan" } },
        { "id" => "sub_7fIggpcyHh1", "period" => { "start" => '1452012860', "end" => '1455900860' }, "plan" => { "id" => "Plan-B", "object" => "plan" } },
      ]
    }

    generated = CGI.unescape(query)

    assert_equal x, Rack::Utils.parse_nested_query(generated)
  end
end
```

The output of `to_query` on `x` in this test case didn't change between Rails releases, but parsing did.

**Comment by tak1n** [comment] 2016-08-04 10:33
I'm not sure if this issue already handles this case but I currently was in process of upgrading one of our apps to rails 5. The problem is nested attributes are broken on rails 5.

I made a public available reproduction app: https://github.com/tak1n/nested_attributes_reproduction

I have a integration test which hits an update action:
https://github.com/tak1n/nested_attributes_reproduction/blob/master/test/integration/book_test.rb

In this update action I have a binding.pry where I get following params:

```
./bin/rake test TEST="test/integration/book_test.rb" TESTOPTS="--name='/BookTest#test_something$/'"
Run options: "--name=/BookTest#test_something$/" --seed 62421

# Running:


From: /home/benny/dev/onlim/testapp/app/controllers/books_controller.rb @ line 3 BooksController#update:

    2: def update
 => 3:   binding.pry
    4: end

[1] pry(#<BooksController>)> params
=> <ActionController::Parameters {"book"=>{"title"=>"Cool", "pages_params"=>[{"id"=>"1", "content"=>"another content"}, {"id"=>"2", "_destroy"=>"1", "content"=>"another new page"}]}, "format"=>"json", "controller"=>"books", "action"=>"update", "id"=>"1"} permitted: false>
```

It should be 3 page_params hashes but instead it merged the hash for deleting and the hash for creating a new page into one.

This `{"id"=>"2", "_destroy"=>"1", "content"=>"another new page"}` should be:
```
{"id"=>"2", "_destroy"=>"1"},
{"content"=>"another new page"}
```

**Comment by javierjulio** [comment] 2016-08-16 15:54
@tak1n I checked your test file https://github.com/tak1n/nested_attributes_reproduction/blob/master/test/integration/book_test.rb but I believe there is an issue because this definitely does work for me (same case) in Rails 5 integration tests but you need to specify `as: :json` there, the format option is for controller tests. Change the code to what you see below and see if it passes:

```ruby
  test "something" do
    params = {
      book: {
        title: 'Cool',
        pages_params: [
          { id: @page.id, content: 'another content' },
          { id: @delete_page.id, _destroy: 1 },
          { content: 'another new page' }
        ]
      }
    }

    put book_url(@book.id), params: params, as: :json
  end
```

Note that the `as: :json` is a separate hash from params entirely. Has to be separate based on docs. Also while the URL does have `.json` at the end I don't believe that is sufficient as when I first started doing this I looked at what happens under the hood and the test seems to really do certain things based on the `as:` option being set. Give it a try and let me know if that works.

**Comment by cvoege** [comment] 2017-05-12 16:10
Is there any progress on fixing the actual parsing here?

Currently, if you try to post a FormData object via AJAX, it will randomly break the entire structure because of this issue. This means that if you try to post a form with any sort of nested structure it will completely break the structure. Normally I just AJAX JSON, which doesn't suffer from this issue, but any time I upload a file I need to use FormData and that means I have to use the broken and unpredictable parser. What's the recommended solution to this?

**Comment by repinel** [comment] 2017-05-16 03:41
This only seems to happen on the `test` environment. Git bisect pointed my to c546a2b. Here is one more test case:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  secrets.secret_token    = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    patch "/" => "test#update"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def update
    render plain: test_params.to_h.inspect
  end

  def test_params
    params.require(:test).permit(children_attributes: [:id, :name, :description, :_destroy])
  end
end

require "rails/test_help"
require "minitest/autorun"

class TestControllerTest < ActionController::TestCase
  test "accessing cookies directly" do
    patch :update, id: 999, test: {
      children_attributes: [{ name: "New Hello", description: "foo" },
                            { id: 1, name: "Hi", description: "goo" },
                            { id: 2, _destroy: true }]
    }
    assert response.ok?
    assert_equal '{"children_attributes"=>[{"name"=>"New Hello", "description"=>"foo"}, {"id"=>"1", "name"=>"Hi", "description"=>"goo"}, {"id"=>"2", "_destroy"=>true}]}', response.body
  end
end
```

**Rails version:** 5.0.3, 5.1.1, master
**Ruby version:** 2.4.1
**rack version:** 2.0.3
**rack-test version:** 0.6.3

**Comment by repinel** [comment] 2017-05-16 15:48
Actually, the reason it was only failing in the tests for me is because the they were really not matching production.

Here is the corrected test:
```ruby
patch :update, id: 999, test: {
  children_attributes: {
    "0" => { name: "New Hello", description: "foo" },
    "1" => { id: 1, name: "Hi", description: "goo" },
    "2" => { id: 2, _destroy: true }
  }
}
```

Sorry about the confusion.

**Comment by arg** [comment] 2017-05-30 15:33
> Currently, if you try to post a FormData object via AJAX, it will randomly break the entire structure because of this issue. This means that if you try to post a form with any sort of nested structure it will completely break the structure. Normally I just AJAX JSON, which doesn't suffer from this issue, but any time I upload a file I need to use FormData and that means I have to use the broken and unpredictable parser. What's the recommended solution to this?

I can confirm the issue is reproducible on Rails 5.1.1. My similar scenario:

```ruby
class Item < ApplicationRecord
  has_many :images
  accepts_nested_attributes_for :images
  # some attributes: name, description, etc.
end

class Image < ApplicationRecord
  # includes attachments logic powered by Shrine gem (not related to the issue)
  # attachment data is stored in "asset_data" attribute
  # also has some authorship information fields (owner, copyright, etc.)
end
```

Form data:
```ruby
item[name] = 'name'
item[description] = 'description'
item[images_attributes][][asset] = File1,File2 # upload with <input type='file' name='item[images_attributes][][asset]' multiple>
item[images_attributes][][owner] = 'owner name 1'
item[images_attributes][][copyright] = 'copyright info 1'
item[images_attributes][][owner] = 'owner name 2'
item[images_attributes][][copyright] = 'copyright info 2'
```

Expected result:
```ruby
item: {
  name: 'name',
  description: 'description'
  images_attributes: [
    {
      asset: File1
      owner: 'owner name 1'
      copyright: 'copyright info 1'
    },
    {
      asset: File2
      owner: 'owner name 1'
      copyright: 'copyright info 2'
    }
  ]
}
```

Actual result:
```ruby
item: {
  name: 'name',
  description: 'description'
  images_attributes: [
    {
      asset: File1
    },
    {
      asset: File2
      owner: 'owner name 2'
      copyright: 'copyright info 1'
    },
    {
      copyright: 'copyright info 2'
    }
  ]
}
```

The actual result is corrupted. Notice the missing `owner name 1`, incorrect copyright info disposition, additional element with only `copyright info 2`.

**Comment by jsantos** [comment] 2017-07-07 04:15
Not sure if this is related, but here's my current issue:

I have the following route, `intervals#bulk_update`:

```ruby
resources :intervals, only: [:index, :update, :destroy] do
    collection do
      put :bulk_update
  end
end
```

And the following payload is sent over JSON (test contents below):
```ruby
put :bulk_update, params: {
  intervals: [
    {
      id: @stop.id,
      interval_type: 'stop',
      stop: {
        id: @stop.intervalable.id,
      },
      start_time: @stop.start_time,
      end_time: @stop.end_time
    },
    {
      id: @trip.id,
      interval_type: 'trip',
      trip: {
        id: @trip.intervalable.id,
        mode_id: modes(:foot).id,
        mode_source: "algorithm_generated_mode"
      },
      confirmed: true,
      start_time: @trip.start_time,
      end_time: @trip.end_time
    }
  ]
}, format: :json
```

That `confirmed` field is a bit spontaneous, so it doesn't show up on every request. Here's what I get on the controller params:

```json
{
  "intervals": [
    {
      "end_time": "2017-02-10 06:06:14 UTC",
      "id": "428",
      "interval_type": "stop",
      "start_time": "2017-02-10 04:06:15 UTC",
      "stop": {
        "id": "186"
      },
      "confirmed": "true"
    },
    {
      "end_time": "2017-02-10 06:26:14 UTC",
      "id": "429",
      "interval_type": "trip",
      "start_time": "2017-02-10 06:06:14 UTC",
      "trip": {
        "id": "180",
        "mode_id": "4",
        "mode_source": "algorithm_generated_mode"
      }
    }
  ],
  "format": "json",
  "controller": "api/v2/intervals",
  "action": "bulk_update"
}
```

It's hard to notice, but the `confirmed` field jumped from the second array element to the first one...

However, if I switch `format: :json` to `as: :json`, the following goes on `params`:

```json
{
  "intervals": [
    {
      "id": 433,
      "interval_type": "stop",
      "stop": {
        "id": 189
      },
      "start_time": "2017-02-10T04:06:15.000Z",
      "end_time": "2017-02-10T06:06:14.000Z"
    },
    {
      "id": 434,
      "interval_type": "trip",
      "trip": {
        "id": 181,
        "mode_id": 4,
        "mode_source": "algorithm_generated_mode"
      },
      "confirmed": true,
      "start_time": "2017-02-10T06:06:14.000Z",
      "end_time": "2017-02-10T06:26:14.000Z"
    }
  ],
  "format": "json",
  "controller": "api/v2/intervals",
  "action": "bulk_update",
  "interval": {
  }
}
```

This time the `confirmed` field ended up in the right place, but I got an extra `"inteval": {}` on the `params` hash. Is this expected?

Another curious thing (that I verified while writing this): If I keep `format: :json` and just name the parameter something else, results vary; so far what I noticed if that if I name it in a way that goes alphabetically after `end_time`, like `verified`, the param goes on the right place...

**Comment by mockdeep** [comment] 2017-09-09 00:24
I'm not sure if it's the same issue, but we're seeing something similar when upgrading to Rails 5.0. We have a test that looks like:

```ruby
put(:update, params: valid_params)
```

in the test, `valid_params` is:

```ruby
{
  :id=>"update_recipients",
  :routing_wizard=>{
    :steps=>[
      {
        :recipients_attributes=>[{:name=>"Homer Simpson", :email=>"h@s.com"}],
        :type=>"RecipientStep",
        :seq=>2
      },
      {
        :recipients_attributes=>[{:name=>"Marge Simpson", :email=>"m@s.com"}],
        :type=>"RecipientStep",
        :seq=>3,
        :skippable=>true,
        :label=>"blah!"
      }
    ]
  }
}
```

and on the server they come out as:

```ruby
{
  "routing_wizard"=>{
    "steps"=>[
      {
        "recipients_attributes"=>[
          {"email"=>"h@s.com", "name"=>"Homer Simpson"},
          {"email"=>"m@s.com", "name"=>"Marge Simpson"}
        ], 
        "seq"=>"2", "type"=>"RecipientStep", "label"=>"blah!"
      },
      {"seq"=>"3", "skippable"=>"true", "type"=>"RecipientStep"}
    ]
  },
  "id"=>"update_recipients",
  "controller"=>"routing_wizard",
  "action"=>"update"
}
```

Notice that somehow the `recipients_attributes` from both `steps` got lumped together under the first `step` on the server. We're not using `json`, as this is a normal form post. It works fine when I walk through this flow on our app directly.

**Comment by mockdeep** [comment] 2017-09-09 19:16
Okay, after doing quite a bit of digging, I've learned that this issue is related to the fact that the the `ActiveSupport` `Hash#to_query` extension [sorts the query parameters before joining them](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/to_query.rb#L82). When I try removing the `sort!` the results show up on the server as expected. It looks like `Rack::Utils.parse_nested_query` handles things differently depending on the order of the params. I came across [this other issue](https://github.com/rails/rails/issues/10529) which looks like the same thing but was closed a couple of years ago.

**Comment by lunaru** [comment] 2018-03-07 21:49
Is there an update on the status of this? It's still reproducible under Rails 5.1.5 and breaks even if the tests use `format: :json`

**Comment by tenderlove** [comment] 2018-09-25 20:01
I think we can close this because it was fixed here: https://github.com/rails/rails/pull/33093

If not, lets reopen or make a new ticket.  Thanks!

**Closed by tenderlove** 2018-09-25 20:01 UTC
Labels: With reproduction steps, actionpack, third party issue

**Comment by amex-doug** [comment] 2020-01-26 09:54
Is there a way to address this issue for Rails 4? I tried the `as` solution, but it doesn't seem to respect my headers.

post path, params: params, headers: valid_header, as: :json
