### ISSUE TITLE
After Commit Callbacks Are Called When RELEASE SAVEPOINT

### ISSUE THREAD

**Issue by omarodeh95** [rails/rails#52641] opened 2024-08-17 19:48 UTC
### Description
In a rolled back transaction, after commit callbacks are called. This issue (if verified) is represented in **only the first test case**.

### Steps to reproduce

```ruby
# frozen_string_literal: true
require "bundler/inline"
require "active_record"
require "minitest/autorun"
require "logger"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "sqlite3", "~> 1.4"

  ###
  # This is a fork that Block running callbacks for Savepoint Transactions
  # The fork does pass this file tests, BUT DOES NOT PASS ALL OTHER TESTS
  # gem 'rails', git: 'https://github.com/omarodeh95/rails-savepoint-after-commit-issue.git', branch: 'main'
  # gem "sqlite3", "~> 2.0"
  ###
end

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.boolean "is_called", default: false
  end
end

class Post < ActiveRecord::Base
  after_create_commit :queue_some_job

  attr_accessor :is_called

  private
  def queue_some_job
    self.is_called = true
  end
end

class BugTest < Minitest::Test

  # FIXME Failing test case
  def test_after_commit_with_failing_outer_unjoinable_transaction
    Post.destroy_all

    first_post = Post.new(is_called: false)
    second_post = Post.new(is_called: false)

    ActiveRecord::Base.transaction joinable: false do
      first_post.save!

      ActiveRecord::Base.transaction do
        second_post.save!
      end

      raise ActiveRecord::Rollback
    end

    assert_equal 0, Post.count

    assert_equal false, first_post.is_called
    assert_equal false, second_post.is_called
  end

  # Passing case
  def test_after_commit_after_successful_transaction
    Post.destroy_all

    first_post = Post.new(is_called: false)
    second_post = Post.new(is_called: false)

    ActiveRecord::Base.transaction do
      first_post.save!

      ActiveRecord::Base.transaction requires_new: true do
        second_post.save!
      end
    end

    assert_equal 2, Post.count

    assert_equal true, first_post.is_called
    assert_equal true, second_post.is_called
  end

  # Passing case
  def test_after_commit_with_failing_inner_unjoinable_transaction
    Post.destroy_all

    first_post = Post.new(is_called: false)
    second_post = Post.new(is_called: false)

    ActiveRecord::Base.transaction joinable: false do
      first_post.save!

      ActiveRecord::Base.transaction do
        second_post.save!

        raise ActiveRecord::Rollback
      end
    end

    assert_equal 1, Post.count

    assert_equal true, first_post.is_called
    assert_equal false, second_post.is_called
  end

  # Passing case
  def test_after_commit_with_failing_inner_transaction
    Post.destroy_all

    first_post = Post.new(is_called: false)
    second_post = Post.new(is_called: false)

    ActiveRecord::Base.transaction do
      first_post.save!

      ActiveRecord::Base.transaction requires_new: true do
        second_post.save!

        raise ActiveRecord::Rollback
      end
    end

    assert_equal 1, Post.count

    assert_equal true, first_post.is_called
    assert_equal false, second_post.is_called
  end

  # Passing case
  def test_after_commit_with_failing_outer_transaction
    Post.destroy_all

    first_post = Post.new(is_called: false)
    second_post = Post.new(is_called: false)

    ActiveRecord::Base.transaction do
      first_post.save!

      ActiveRecord::Base.transaction requires_new: true do
        second_post.save!
      end

      raise ActiveRecord::Rollback
    end

    assert_equal 0, Post.count

    assert_equal false, first_post.is_called
    assert_equal false, second_post.is_called
  end
end
```
### Expected behavior
If a transaction is rolled back, and no record is saved, I expect no after commit callbacks to be called.

### Actual behavior
After commit callbacks are called when releasing a savepoint in a rolled back transaction

### Note
- ActiveRecord::Rollback is intentionally raised to represent a possible raised exception
- This issue has be raised and closed before, you can check [here](https://github.com/rails/rails/issues/39912)
- I have created a [fork](https://github.com/omarodeh95/rails-savepoint-after-commit-issue.git) that force blocking callbacks for Savepoints Transactions, but a lot of active record tests are **FAILING**. You can uncomment this fork in this test file for all tests to pass

### System configuration
**Rails version**:
Rails 7.2.0
**Ruby version**:
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]

**Comment by casperisfine** [comment] 2024-08-19 13:24
> ` # FIXME Failing test case`

So you use `ActiveRecord::Base.transaction joinable: false do`. `joinable: false` is a private API used by Rails itself fro transactional fixtures, it tells Active Record to open a transaction, but behave like there isn't one.

So this is working as designed as far as I can tell. Is there a reason why you are using `joinable: false`?

**Comment by byroot** [comment] 2024-08-19 14:30
Closing for now, will reopen if it turns out there is a reason why `joinable: false` should delay after commit callbacks.

**Closed by byroot** 2024-08-19 14:30 UTC

**Comment by omarodeh95** [comment] 2024-08-19 23:53
## Reply
The confusion here is that the `after_commit` is called even though no records were saved. and I would not say this is an expected or wanted behavior.

@casperisfine 
> it tells Active Record to open a transaction, but behave like there isn't one

 I think it still behaves as if there is a transaction. Yes it does open a nested transaction (savepoint), but it runs `after_commit` callbacks for  when releasing that savepoint. The problem is that releasing the savepoint does not guarantee that there is no **Roll Back**.

@casperisfine 
> Is there a reason why you are using joinable: false?

There is not a specific case at my end, I was just tinkering around with `ActiveRecord::Transaction` to get a better understanding, especially with the **rails 7.2.0 and Queued Jobs Enhancement**. But I would use `joinable: false` if I want to make sure the outer transaction is not affected by the inner transaction. As an example I have this following example

```ruby
# Model
class User < ApplicationRecord
  after_create_commit :queue_a_job

  private

  def queue_a_job
    WelcomeJob.perform_later(self.id)
    sleep 1
  end
end

# ActiveJob (I am using Sidekiq adaptor)
class WelcomeJob < ApplicationJob
  def perform(user_id)
    puts User.find(user_id)
  end
end

```
and in console (rails c)
I am running this code

```ruby
ActiveRecord::Base.transaction joinable: false do # Set joinable to false and make sure it is not affected by any inner transaction
  User.create(name: '1')
  ActiveRecord::Base.transaction requires_new: false do # It can be true or false, the outer transaction does not really care if it fails or not. I will make it pass anyway
    User.create(name: '2')
  rescue => e
    puts "Handle inner transaction error and roll it back"
    raise ActiveRecord::Rollback 
  end
  
  THE_PROBLEM # just raising an error
rescue => e
  puts "Handle the error and rollback the whole thing including the inner transaction"
  raise ActiveRecord::Rollback
end
```
Result is no records are saved because of the rollback. and **2 jobs are queued**
```
  TRANSACTION (0.2ms)  begin transaction
  TRANSACTION (0.0ms)  SAVEPOINT active_record_1
  User Create (1.9ms)  INSERT INTO "users" ("name", "age", "created_at", "updated_at") VALUES (?, ?, ?, ?) RETURNING "id"  [["name", "1"], ["age", nil], ["created_at", "2024-08-19 23:19:41.583146"], ["updated_at", "2024-08-19 23:19:41.583146"]]
  TRANSACTION (0.0ms)  RELEASE SAVEPOINT active_record_1
Enqueued WelcomeJob (Job ID: c6714484-20ed-46a4-9bca-580a7cbf80a2) to Sidekiq(default) with arguments: 78
  TRANSACTION (0.1ms)  SAVEPOINT active_record_1
  User Create (0.7ms)  INSERT INTO "users" ("name", "age", "created_at", "updated_at") VALUES (?, ?, ?, ?) RETURNING "id"  [["name", "2"], ["age", nil], ["created_at", "2024-08-19 23:19:42.595100"], ["updated_at", "2024-08-19 23:19:42.595100"]]
  TRANSACTION (0.0ms)  RELEASE SAVEPOINT active_record_1
Enqueued WelcomeJob (Job ID: d1f80e19-ca08-49ab-a4e8-f13a525e731e) to Sidekiq(default) with arguments: 79
Handle the error and rollback the whole thing including the inner transaction
  TRANSACTION (0.2ms)  rollback transaction
=> nil
```
Check number of saved users
```ruby
User.count
```
```
User Count (1.6ms)  SELECT COUNT(*) FROM "users"
=> 0
```

Sidekiq log is filled with errors, `ActiveRecord::RecordNotFound` in this case.
```
2024-08-19T23:28:16.460Z pid=84204 tid=1gi8 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","wrapped":"WelcomeJob","args":[{"job_class":"WelcomeJob","job_id":"c6714484-20ed-46a4-9bca-580a7cbf80a2","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[78],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2024-08-19T23:19:41.587041000Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"51f24bb8748b9dfc28c6428b","created_at":1724109581.587187,"enqueued_at":1724110096.449314,"error_message":"Couldn't find User with 'id'=78","error_class":"ActiveRecord::RecordNotFound","failed_at":1724109581.6016,"retry_count":4,"retried_at":1724109804.514378}}
2024-08-19T23:28:16.460Z pid=84204 tid=1gi8 WARN: ActiveRecord::RecordNotFound: Couldn't find User with 'id'=78
2024-08-19T23:28:16.461Z pid=84204 tid=1gi8 WARN: app/jobs/welcome_job.rb:4:in `perform'
```
