### ISSUE TITLE
TaggedLogging breaks JSON formatters

### ISSUE THREAD

**Issue by HoneyryderChuck** [rails/rails#49151] opened 2023-09-05 11:49 UTC
### Expected behavior

The activesupport TaggedLogging component breaks loggers which support hash inputs, because it [appends and injects the message into a string](https://github.com/rails/rails/blob/v7.0.3.1/activesupport/lib/active_support/tagged_logging.rb#L33). This may break other types of inputs such as exceptions, that the default logger formatter supports by default, such as [the ones defined in msg2str](https://github.com/ruby/logger/blob/master/lib/logger/formatter.rb#L25C10-L25C10).

In the particular case of the formatter we maintain at our company, which accepts calls such as `logger.info({msg: "bla})`, this results in JSON logger messages being wrongly formatted, i.e. `"{\"time\":\"2023-09-05T10:57:42.409825\",\"level\":\"INFO\",\"pid\":152,\"name\":\"bla\",\"msg\":\"{:msg=>\\\"bang\\\"}\"}\n"`, because we rely on defining our own `Logger::Formatter#call`, but this gets overriden in rails by activesupport, which [extends the defined formatter](https://github.com/rails/rails/blob/v7.0.3.1/activesupport/lib/active_support/tagged_logging.rb#L92) and overrides our changes.

### Actual behavior

I'd expect the call mentioned above to produced the following message: `"{\"time\":\"2023-09-05T10:57:42.409825\",\"level\":\"INFO\",\"pid\":152,\"name\":\"bla\",\"msg\":\"bla\"}"`. I believe this could be done if the formatter override used `.prepend` instead of `extend`. 

I've looked at at least one ruby json formatter in the OS wild, and [they resort to sniffing the string for json content, parsing and enriching payload, then dumping again](https://github.com/chadlwm/log_formatter/blob/master/lib/log_formatter/common_json.rb#L49), which is definitely the type of silly workaround I'd like to avoid.

### System configuration
**Rails version**: if 7.0.7.2 (latest)
**Ruby version**: irrelevant (in my case, 3.2)

**Comment by paulreece** [comment] 2023-09-05 14:25
I'm game to make a PR to address this.  Could you provide a reproduction script so I can test this locally?

**Comment by HoneyryderChuck** [comment] 2023-09-05 14:55
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rails', '~> 7.0'
end

require 'action_controller/railtie'
require 'logger'
require 'json'


class MyFormatter < Logger::Formatter
  def call(severity, time, progname, msg)
    puts "formatter received: #{msg} (msg: #{msg.class})"
    if msg.is_a?(Hash)
      msg = JSON.dump(msg) << "\n"
    end

    super
  end
end

class App < ::Rails::Application
  routes.append do
    root to: 'root#index'
  end

  config.log_formatter = MyFormatter.new
  logger = ActiveSupport::Logger.new($stdout)
  logger.formatter = config.log_formatter
  config.logger = ActiveSupport::TaggedLogging.new(logger)
end

class RootController < ActionController::Base
  def index
    render plain: Rails.version
  end
end

App.initialize!

Rails.logger.info msg: "bang"

**Comment by skipkayhil** [comment] 2023-09-06 21:50
> Still, not sure if there is usage in the wild for tagged logging with json-encoded log payload (the linked OSS library above and the parse-then-redump flow leads me to believe there is).

I agree there is an appetite for more structured logging, but I think `TaggedLogging` is designed pretty explicitly for only logging simple strings. Making it more complex when Rails doesn't ship a structured logger doesn't seem right either.

Since this feels more like a feature request than a bug (and there's a trivial solution anyways), I'm going to close this. Feel free to reply if you have other questions.

**Closed by skipkayhil** 2023-09-06 21:50 UTC
