### ISSUE TITLE
ActiveRecord::Base.connection_pool.with_connection is not thread safe

### ISSUE THREAD

**Issue by DimitriosLisenko** [rails/rails#37477] opened 2019-10-15 11:09 UTC
### Steps to reproduce
I'm doing the following to reproduce this issue:
1) Create a brand new rails application with`rails new blog -d mysql`
2) Create an article model with
```
rails generate model Article title:string text:text
```
3) Create a comment model with
```
rails generate model Comment commenter:string body:text article:references
```
4) Run `bundle exec rails db:create` and `bundle exec rails db:migrate`.
5) Use the following definition for app/models/article.rb. Note that I added the sleep to `after_initialize` to simulate work happening as part of initializing the model.
```
class Article < ApplicationRecord

  has_many :comments
  after_initialize :do_after_initialize

  private

  def do_after_initialize
    sleep(rand(0.001..0.03))
  end

end
```
6) Use the following definition for app/models/comment.rb.
```
class Comment < ApplicationRecord

  belongs_to :article
  after_initialize :do_after_initialize

  private

  def do_after_initialize
    sleep(rand(0.001..0.03))
  end

end
```
7) Create the following initial objects in the rails console:
```
article = Article.new(title: "Hello, world!", text: "Lorem Ipsum")
article.save!
article.comments.create!(commenter: "bloodninja", body: "boring and derivative")
article.comments.create!(commenter: "me", body: "did you forget to change the default text?")
```
8) Run this loop (for about a minute), and eventually it will raise - the map will return either 0 or 1 IDs.
```
while true
  article = Article.first
  threads = []
  10.times do
    threads << Thread.new do
      Rails.application.executor.wrap do # NOTE: this is required to replicate... without it, it's fine...
      # ActiveRecord::Base.connection_pool.with_connection do # NOTE: this also replicates the issue...
        ids = article.comments.map(&:id)
        puts ids.inspect
        raise "Oh noes!" if ids.size != 2
      end
    end
  end
  threads.map(&:join)
end
```

### Expected behavior
The loop should run forever, until the heat death of the universe. Or at least until I switch my laptop off :)

### Actual behavior
Eventually, "Oh noes!" is raised, with the offending `ids` array having 0 or 1 elements.
Interestingly enough, changing this line:
```
ids = article.comments.map(&:id)
```
to
```
ids = article.comments.to_a.map(&:id)
```
seems to resolve the issue. EDIT: correction - using to_a inside `ActiveRecord::Base.connection_pool.with_connection` still raises, but using it inside `Rails.application.executor.wrap` seems to be fine, although this could just be timing related at this point.

Note that using `select` instead of `map` also has the same issue.

As a result of this, whenever `select` or `map` is run against an ActiveRecord collection in a multithreading context, you sometimes unexpectedly get missing elements.

### System configuration
**Rails version**: replicated in both 5.2.3 and 6.0.0
**Ruby version**: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]

**Comment by pascalbetz** [comment] 2019-10-17 10:20
Error occurs for me when using `ActiveRecord::Base.connection_pool.with_connection do`:
`RuntimeError (Oh noes!)`

Rails: 6.0
Ruby: 2.6.0
Probably took a bit more than a minute.

**Comment by p8** [comment] 2019-10-17 11:57
Problem here is that you are sharing `article` between threads without using a mutex. So each thread can change the state of `article` while other threads are doing the same.

**Comment by pascalbetz** [comment] 2019-10-17 12:23
@p8 yes, this seems to be the reason. could not reproduce this with the mutex.
I missed that, even though its only reading data, obviously the internal state of the association is mutated.

**Comment by matthewd** [comment] 2019-10-17 12:26
> Problem here is that you are sharing `article` between threads without using a mutex.

Indeed.

The Active Record constants and globals (including the connection pool) are designed to be threadsafe, but individual AR instances (both models and relations) are not; you'll need your own locking to share them.

Off the top of my head, I'm not sure why the version without the executor / `with_connection` block would behave differently -- maybe just timing? 

If you can reproduce threads affecting each others allocated connections without them sharing a model, that would be (more surprising and) very concerning, but I'm going to close this for now.


Thanks for reporting, though!

**Closed by matthewd** 2019-10-17 12:26 UTC
