### ISSUE TITLE
before_action callbacks and controller inheritance

### ISSUE THREAD

**Issue by prrrnd** [rails/rails#24846] opened 2016-05-04 06:21 UTC
### Steps to reproduce

I have the two controllers as shown below; 
```ruby
# app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  # ...
  def set_account
    @account = Account.find(params[:account_id])
  end
  # ...
end

# app/controllers/admin/members_controller.rb
class Admin::MembersController < Admin::BaseController
  before_action :set_account, only: :show
  # ...

  def show
  end
end
```

### Expected behavior
@account to be set before Admin::MembersController#show

### Actual behavior
undefined method `set_account' for #<Admin::MembersController:0x007f984420f3d0>

### Full trace
```
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:145:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `block in call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `each'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:137:in `process'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal.rb:196:in `dispatch'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal.rb:237:in `block in action'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:30:in `each'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:30:in `serve'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:815:in `call'
vendor/bundle/ruby/2.2.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
vendor/bundle/ruby/2.2.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
vendor/bundle/ruby/2.2.0/gems/apipie-rails-0.3.5/lib/apipie/static_dispatcher.rb:65:in `call'
vendor/bundle/ruby/2.2.0/gems/bullet-4.14.10/lib/bullet/rack.rb:12:in `call'
vendor/bundle/ruby/2.2.0/gems/apipie-rails-0.3.5/lib/apipie/extractor/recorder.rb:132:in `call'
vendor/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'
vendor/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'
vendor/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/query_cache.rb:36:in `call'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:377:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/reloader.rb:73:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/rack/logger.rb:22:in `call'
vendor/bundle/ruby/2.2.0/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/static.rb:116:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/engine.rb:518:in `call'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:165:in `call'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
vendor/bundle/ruby/2.2.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
vendor/bundle/ruby/2.2.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
vendor/bundle/ruby/2.2.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
vendor/bundle/ruby/2.2.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
vendor/bundle/ruby/2.2.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
vendor/bundle/ruby/2.2.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
vendor/bundle/ruby/2.2.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/server.rb:80:in `start'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:75:in `server'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```
### System configuration
**Rails version**: 4.2.5.1

**Ruby version**: 2.2.3

**Comment by sevenseacat** [comment] 2016-05-04 06:23
seeing the entire code of that `Admin::BaseController` would be a great help here, because that should work fine

**Comment by prrrnd** [comment] 2016-05-04 06:32
@sevenseacat I cannot share the entire code here, but the code below still throws the same exception.

```ruby
# app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin!

  layout 'backend'
  helper :admin

  def set_account
    @account = Account.find(params[:account_id])
  end
end
```

`:authenticate_admin!` from devise works fine though.

**Comment by Erol** [comment] 2016-05-04 11:26
I can confirm this is happening on master with the following code:

```ruby
class Admin::BaseController < ApplicationController
  def set_account
  end
end

class Admin::MembersController < ApplicationController
  before_action :set_account, only: :show

  def show
  end
end

Rails.application.routes.draw do
  namespace :admin do
    resources :members
  end
end
```

**Comment by vipulnsward** [comment] 2016-05-04 15:03
I am not able to reproduce this on master- https://gist.github.com/vipulnsward/5488d33b4395cbfa3c729ce67b2692a8

@prrrnd can you check above script to see, if I have missed something that's different from your case?

**Comment by prrrnd** [comment] 2016-05-04 18:05
@vipulnsward Thanks for looking into it.
From the script above, I see two notable differences. One is the namespace, `Admin::`, the other is the parent controller inheritance. My `Admin::BaseController` inherits from an `ApplicationController`, which inherits from  `ActionController::Base`
Not sure how these two could affect this, but it's probably worth pointing out.
I'll try on a new rails app when I get some time.

**Comment by Erol** [comment] 2016-05-05 06:15
The code below works for me on Rails 4.2.5.1:

```
class Admin::BaseController < ApplicationController
  def set_account
  end
end

class Admin::MembersController < Admin::BaseController
  before_action :set_account, only: :show

  def show
    render text: ''
  end
end
```

Is this similar to yours @prrrnd?

**Comment by rafaelfranca** [comment] 2016-05-05 17:00
As we could not reproduce I'm closing this issue but please let us know if you find anything new or if you can isolate the root cause in an example application so we can take a look.

Thanks

**Closed by rafaelfranca** 2016-05-05 17:00 UTC
Labels: actionpack

**Comment by burennto** [comment] 2019-04-04 05:40
Not sure if related, but ran into the same issue on Rails 5.2.1, and found that `protect_from_forgery with: :null_session` in the parent controller needs to be AFTER all `before_action` declarations in that controller.

```
class V1::BaseController < ActionController::Base
  before_action :authenticate

  # needs to be AFTER all the `before_action` declarations
  protect_from_forgery with: :null_session

  def authenticate
    ...
  end

  def find_user
    ...
  end
end

class V1::VisitsController < V1::BaseController
  before_action :find_user

  def create
    ...
  end
end
```
