### ISSUE TITLE
Development Environment Lockup when Eager Loading Files Rails 5.1

### ISSUE THREAD

**Issue by stratigos** [rails/rails#30578] opened 2017-09-12 00:00 UTC
### Steps to reproduce

1. Use Rails 5.1.2
2. Turn ` config.eager_load=true` on in the development config.
3. Start server, load any page / make a request.
4. Change any model or controller file.
5. Make another request to the server, a long hang will happen, and the following exception will be thrown:

`ArgumentError (unknown firstpos: NilClass):`

### Expected behavior
I can change files without the server locking up due to eager loading them. As stated by @dan-jensen in a comment below, Id also like to be able to catch any eager loading issues in development before shipping code.

### Actual behavior
If I change anything besides an ERB template, whole server locks up on next request, and exception thrown. Killing server and restarting it restores access, but this has to be done for every single file change.

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.1

Other users have [reported experiencing this](https://stackoverflow.com/questions/44465118/rails-5-1-unknown-firstpos-nilclass-issue-reloading-application).  It appears to be a bug with eager loading.

**Comment by alastairbAtEF** [comment] 2017-09-12 00:06
12:04 #

**Comment by ccasabona** [comment] 2017-09-12 12:11
If you revert the change to the code (step 4 above) back to what it was when the server was started, then a new request (meaning not a page reload) will work without restarting the server.

**Comment by dan-jensen** [comment] 2017-10-26 22:26
Reproducible in Rails 5.1.4 as well.

This bug is more serious than it might appear.  Setting `config.eager_load = true` in development seems to be the best way to expose eager loading problems before an app is deployed to a production environment.  But to avoid this bug you must leave the default of `config.eager_load = false` in development.  For most apps, that means eager loading is not used - not tested in any way - until the app reaches a production environment.  That's a recipe for a production outage for apps with even a slightly customized file structure.

**Comment by PikachuEXE** [comment] 2017-10-27 03:51
Really annoying bug for 5.1
I plan to stay on 5.0.x until this bug is fixed

**Comment by rafaelfranca** [comment] 2017-10-31 06:00
Now I'm puzzled, I wonder how this worked in Rails 5.0. I'll take a look.

**Comment by rafaelfranca** [comment] 2017-10-31 06:02
BTW, other way to test eager loading without testing in production is to use the test environment. It is more suited to be eager loaded since it doesn't keep a long running process that needs to reload classes if something change. And the result is the same since the eager load mechanism is the same no matter the environment.

**Comment by lime** [comment] 2017-11-30 14:06
> BTW, other way to test eager loading without testing in production is to use the test environment. It is more suited to be eager loaded since it doesn't keep a long running process that needs to reload classes if something change.

However, if we use Spring in the test environment then there _is_ a long running process that needs to reload classes.

See https://github.com/rails/spring/issues/519 for an example of that combination breaking (on Rails 5.0).

**Comment by lime** [comment] 2017-12-01 07:48
I thought I'd cross-post one potential solution here too:

From the [Rails guides](http://guides.rubyonrails.org/configuring.html#rails-general-configuration):

> `config.enable_dependency_loading`: when true, enables autoloading, even if the application is eager loaded

Seems to help for the test environment in Rails 5.0, haven't tried with 5.1 yet.

**Comment by PikachuEXE** [comment] 2017-12-01 07:56
@lime
Let's read the whole paragraph

> `config.enable_dependency_loading`: when true, enables autoloading, even if the application is eager loaded and config.cache_classes is set as true. Defaults to false.

My `cache_classes` is `false` in `development`

**Comment by lime** [comment] 2017-12-01 08:07
Yeah sorry, I goofed up when copying the text.

**Comment by PikachuEXE** [comment] 2017-12-15 01:19
Will anything be done for this issue?

**Comment by PikachuEXE** [comment] 2018-01-05 01:35
Any progress on fixing this?

**Comment by PikachuEXE** [comment] 2018-01-19 09:08
I checked the stacktrace myself
And it seems the `#ast` method in
https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_dispatch/journey/routes.rb#L49
Can return `nil` when `anchored_routes` is empty

not sure how to fix it (what node to pass in when `anchored_routes` empty)

**Comment by PikachuEXE** [comment] 2018-01-19 09:41
Created minimal sample app:
https://github.com/PikachuEXE/rails_issue_30578

I think it's mainly [sass-mediaqueries-rails](https://github.com/paranoida/sass-mediaqueries-rails)
calling `isolate_namespace` at https://github.com/paranoida/sass-mediaqueries-rails/blob/master/lib/sass-mediaqueries-rails/engine.rb
Which causes an empty `RouteSet`

**Comment by TheStu** [comment] 2018-01-24 18:20
I started getting this error while in the process of migrating an existing Rails 5.1.3 app to an API. I've narrowed it down to the [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) gem. Just bundle installing the gem causes the error, and no amount of configuring the gem seems to help.

**Comment by PikachuEXE** [comment] 2018-01-25 01:12
I guess it's also due to [a call to `isolate_namespace`](https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/engine.rb#L5)

**Comment by PikachuEXE** [comment] 2018-03-05 01:56
I "fixed" my app by removing the related gem
But I think this still should be fixed

**Comment by dan-jensen** [comment] 2018-06-08 16:44
Reproducible in Rails 5.2.0.

**Comment by dan-jensen** [comment] 2018-06-11 20:18
Just submitted PR #33118 to fix this.  Thanks @PikachuEXE and @TheStu for your work on narrowing this down.  You were both right.

**Comment by y-yagi** [comment] 2018-06-11 23:16
Fixed by #33118.

**Closed by y-yagi** 2018-06-11 23:16 UTC
