### ISSUE TITLE
Model.unscoped block not removing default scope for joins

### ISSUE THREAD

**Issue by aprescott** [rails/rails#13775] opened 2014-01-20 21:27 UTC
Summary:

Suppose Model has a default scope.

```ruby
Model.unscoped { Foo.joins(:model) }
```

acts as if `Model.unscoped { ... }` were not specified. That is, it constructs `Foo.joins(:model)` as if it weren't inside `Model.unscoped`, so that `Model.default_scope` is mistakenly continuing to apply to the `joins`, even though `unscoped` should have removed it.

----

Consider a `User` with a `default_scope` that specifies `status = 1`:

```ruby
>> User.all.to_sql
#=> "SELECT `users`.* FROM `users`  WHERE `users`.`status` = 1"
```

If an `Item` belongs to `User`, trying to join the two with `Item.joins(:user)` seems to always respect `User.default_scope`, no matter how you try to remove the default scope. So the `joins` SQL

```ruby
>> Item.joins(:user).to_sql # includes User.default_scope, CORRECTLY.
#=> "SELECT `items`.* FROM `items` INNER JOIN `users` ON `users`.`id` = `items`.`user_id` AND `users`.`status` = 1
```

correctly includes

```
`users`.`status` = 1
```

as it should, but if you try to remove it with `User.unscoped { ... }`, the `status = 1` default scope on `User` is still applying, which I believe is a bug:

```ruby
User.unscoped do
  Item.joins(:user) # User is incorrectly still scoped to status == 1 here
end
```

As a total aside, it would be nice to have something like `joins_unscoped(:user)` as an alternative.

**Comment by aprescott** [comment] 2015-03-16 15:30
After some confusion from #18109, I have amended the description to better explain that `User.unscoped { Item.joins(:user) }` is ignoring `User.unscoped` as if it weren't present. My previous wording could have also suggested that `Item.joins(:user)` should always act as if it were called inside a `User.unscoped { ... }` block so that all `joins` calls ignored default scopes, which is not the aim of this issue and is something I'd consider broken.

**Comment by sidot3291** [comment] 2015-07-18 01:27
I've been working on a new feature to potentially resolve this problem, as well as the other issues highlighted in #10643.

I accomplished it by introducing a new "inline scope," and also standardizing the order in which scopes are prioritized: 1) default, 2) association scope, 3) inline scope.

Say you have a `has_many :comments` association that applies a scope that hides soft-deletes via a :deleted_at attribute.  You can undo the association scope with an inline scope like this:

        Post.includes(:comments => ->{ unscope(where: :deleted_at) })

Nested joins are possible within inline scopes.  For the sake of clarity, these two lines are equivalent:

        Comment.joins(:author => :address)
        Comment.joins(:author => -> { joins(:address) })

Code here, still needs to be prepped for a PR but wanted to share first:

https://github.com/sidot3291/rails/commit/1735537aec94b149544bd3d2419d0cd0e395ab9d

**Comment by sgrif** [comment] 2015-07-18 12:56
I'm not a fan of the lambda form. This shouldn't require new behavior or functionality. The issue is the lazy computation of the join path that we follow. Due to time constraints, this probably won't happen until Rails 5.1, but the goal is ultimately to require `joins` to be explicit (e.g. you must do `User.joins(posts: :comments)`, not `User.joins(:posts, :comments)`, which will allow the tree to be built eagerly instead fixing this issue.

**Comment by sidot3291** [comment] 2015-07-18 17:15
Hi @sgrif 

I'm not sure I understand your point about the tree being built eagerly.  I think joins are already required to be explicit?  In rails 4.1, `User.joins(:posts, :comments)` fails unless there is a `:comments` association on User.  If a `:comments` association exists on both User and Post, the two examples here still produce different SQL.

Ultimately, what I want to see provided is granular control over scopes.  I think default_scope has rightly received a lot of negative attention because it's so hard to alter once it's there.  Rails 4.1 fixed some of those issues by allowing named scopes to override default scopes, but as this thread and #10643 highlight, we don't have an effective way to alter the scope when pulling in models by association.

I think we'll run into two issues with the strategy proposed in this thread, if it's the only solution we build:

1. The solution applies scope to the Model, not to the association.  And so, we are forced to assume that a scope is relevant to an association simply because the class matches.  This may not be the desired effect when a user brings in multiple associations with the same class.
2. Nesting quickly gets dirty.  It's unclear to me how you could apply different scopes to `:a`, `:b`, `:c` in each of these cases: `.joins(:a => {:b=>:c})`, `.joins(:a => [:b, :c])`, `.joins([:a, :b, :c])`

**Comment by aprescott** [comment] 2015-07-18 17:31
Even with the lambda functionality you described, I wouldn't consider that as fixing this issue. An `unscoped` acting as if it isn't there at all is still broken, lambda or no lambda.

**Comment by sidot3291** [comment] 2015-07-18 18:10
Hmm, what is setting the expectation that the association should be unscoped in your example?

    User.unscoped do
      Item.joins(:user) # User is incorrectly still scoped to status == 1 here
    end

The association definition is:

    class Item
      belongs_to :user, class_name: "User" #default class_name
    end

So are you arguing that within the `User.unscoped` block, all references to `User` should return `User.unscoped` instead?  If not, what is mechanism for the association working off of `User.unscoped` instead of just `User`?

**Comment by aprescott** [comment] 2015-07-18 18:32
The definition of `unscoped`'s block form tells you one thing, and `User.unscoped { Item.joins(:user) }` doesn't adhere to it, because it doesn't remove the default scope. This is already considered a legitimate bug (https://github.com/rails/rails/issues/13775#issuecomment-34577250 + others), and I think all the preceding discussion in this PR and other linked PRs expand on it a fair bit, so I won't rehash all that.

**Comment by sidot3291** [comment] 2015-07-19 01:10
Turns out this was a bug for all scoping blocks, not just unscoped: http://apidock.com/rails/ActiveRecord/Relation/scoping

Just issued a PR: https://github.com/rails/rails/pull/20937

I still think we need more granular control over the scope of joins, and would be interested in some more conversation around the inline lambda idea.  Does anyone have alternative ideas for altering scope at the association level?

**Comment by andyrue** [comment] 2015-10-20 14:53
Is there a suggested work around for this issue, or do I need to remove default_scope from my associated tables?

**Comment by masterchef** [comment] 2015-11-12 23:37
This is probably the worst bug in active record. It basically makes default scope completely unusable if you have any sort of complexity in your business logic. I wish default_scope came with a warning about this issue.

**Comment by sidot3291** [comment] 2015-11-13 01:55
Against my better judgement, I've been using a monkey patch that builds in my lambda-scope functionality for rails 4.1

https://gist.github.com/sidot3291/77b999ffeaa5d1d290b2

YMMV - solved my problems.

**Comment by mockdeep** [comment] 2016-01-21 19:41
Running into this one, too. We've got some workarounds in places, but it's all pretty kludgey. Would be great to get it fixed in rails proper.

**Comment by tawan** [comment] 2016-01-30 17:10
Hi, CodeTriage assigned this issue to me.

I read all comments carefully and came to the conclusion that PR #18109 solves exactly the problem that the author of the issue reported.

I try to summarise where the current behaviour deviates from the expected behaviour promised by the API:
Partial documentation of [ActiveRecord::Base.unscoped](https://github.com/rails/rails/blob/c4d85dfbc71043e2a746acd310e32f4f04db801a/activerecord/lib/active_record/scoping/default.rb#L16-L33)

        # Returns a scope for the model without the previously set scopes.
        #   class Post < ActiveRecord::Base
        #     def self.default_scope
        #       where(published: true)
        #     end
        #   end
        # ...
        # This method also accepts a block. All queries inside the block will
        # not use the previously set scopes.
        #
        #   Post.unscoped {
        #     Post.limit(10) # Fires "SELECT * FROM posts LIMIT 10"
        #   }

It says that **all queries** inside the block will not use the previously set scopes. Here I agree with the author of the issue and I would expect that this also includes queries composed of joins with the AR model in question. All previously set scopes, **including a default scope**, should have no effect at all within the given block.

This method is realised by invoking `ActiveRecord::Relation#scoping` on a new plain vanilla relation object of the AR model (which does not include a default scope).

Documentation of [ActiveRecord::Relation#scoping](https://github.com/rails/rails/blob/c4d85dfbc71043e2a746acd310e32f4f04db801a/activerecord/lib/active_record/relation.rb#L332-L341)

    # Scope all queries to the current scope.
    #
    #   Comment.where(post_id: 1).scoping do
    #     Comment.first
    #   end
    #   # => SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = 1 ORDER BY "comments"."id" ASC LIMIT 1
    #
    # Please check unscoped if you want to remove all previous scopes (including
    # the default_scope) during the execution of a block.
   
Here the documentation says again that  **all queries** within the given block are scoped to the current scope (in our case it's a clear new scope). The method achieves that by registering itself as the current scope for the AR model in question. It does this via [ActiveRecord::Scoping::ScopeRegistry.set_value_for](https://github.com/rails/rails/blob/c4d85dfbc71043e2a746acd310e32f4f04db801a/activerecord/lib/active_record/scoping.rb#L90).

The API is currently not honoured when the join constraints are constructed [without checking](https://github.com/rails/rails/blob/c4d85dfbc71043e2a746acd310e32f4f04db801a/activerecord/lib/active_record/associations/join_dependency/join_association.rb#L62) the `ScopeRegistry` for a potential `:current_scope` of the AR model.
```ruby
klass.send(:build_default_scope, relation)
```
PR #18109  fixes this as expected, IMO.

I hope this summary helps in understanding the issue and the solution.

**Closed** 2016-02-11 18:34 UTC
Labels: activerecord, attached PR, With reproduction steps

**Comment by pooja-mane** [comment] 2019-05-27 15:19
@miguelgraz 
I am also facing the same problem while doing join default scope also gets called.

Do you have any solution for this?

**Comment by arielscherman** [comment] 2019-06-04 22:39
@miguelgraz I've been facing the same issue, and if you don't write a raw join (which in some cases can be pretty painful), you could go for this which works.

Based on the models:

```ruby
class User
  default_scope { <some scope> }
end

class Item
  belongs_to :user
end
```

In order to be able to do a `joins` on `Item` to `User` without being impacted with the default scope, you could do this:

```ruby
class UnscopedUser < User
  self.default_scopes = []
end

class Item
  belongs_to :user

  # add this association
  belongs_to :unscoped_user, foreign_key: :user_id
end
```

Then in order to skip the default scope when doing the join you just do:

```ruby
Item.joins(:unscoped_user)
```

**Comment by IlkhamGaysin** [comment] 2022-08-02 14:13
+1 having this with `includes`

**Comment by simi** [comment] 2022-08-02 15:15
@IlkhamGaysin would you mind to open new issue with reproducer (https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb) on rails main?

**Comment by wdiechmann** [comment] 2022-12-04 20:17
FWIW - if "Google dragged you" here whilst fighting `unscoped` in the `delegated_type` context here's what works for me. Instead of trying to do `Employee.all.joins....` I learned from [ThoughtBot](https://thoughtbot.com/upcase/videos/advanced-querying-custom-joins) to make a custom JOINS like the one below handing me the  `pin_codes_across_all_accounts`

thx for sharing ThoughtBout!!

```
class AbstractResource  < ApplicationRecord
  self.abstract_class = true
  def self.default_scope
    Sidekiq.server? ? where(deleted_at: nil) : where(deleted_at: nil, account: Current.account)
  end
end

class Asset < AbstractResource
  delegated_type :assetable, types: %w[ Employee Facility Stock  ], dependent: :destroy
end

class Employee < AbstractResource
  include Assetable
  delegate :asset_work_transactions, :asset_workday_sums, :teams, to: :asset

  # this custom JOINS generates this SQL:
  # SELECT assets.*, employees.* FROM "assets" 
  # LEFT JOIN employees on employees.id = assets.assetable_id and assets.deleted_at is null 
  # WHERE "assets"."assetable_type" = $1  [["assetable_type", "Employee"]]
  def pin_codes_across_all_accounts
    Asset.unscoped.employees.joins(<<-SQL).
         LEFT JOIN employees on employees.id = assets.assetable_id and assets.deleted_at is null
         SQL
         select("assets.*","employees.*").map &:pin_code
  end

module Assetable
  extend ActiveSupport::Concern
  included do
    has_one :asset, as: :assetable, touch: true, dependent: :destroy
    delegate :name, :calendar, :account, :state, :tasks, :work_schedules, :deleted_at, to: :asset   
  end
end
```

**Comment by KirtashW17** [comment] 2023-05-23 09:59
I think this issue should be re-opened. Preloading is not always an option, and with a manual join you lose some interesting ORM features.
