### ISSUE TITLE
ActionText installation fails

### ISSUE THREAD

**Issue by El-Potato-Slayer** [rails/rails#41345] opened 2021-02-05 15:11 UTC
### Steps to reproduce
Run `rails action_text:install`

### Expected behavior
action_text should install successfully

### Actual behavior
Installation fails, and the following error is produced
```
rails  app:binstub:yarn
Installing JavaScript dependencies
         run  bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.1 from "."
rails aborted!
Errno::ENOEXEC: Exec format error - bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.1
```

### System configuration
**Rails version**: Rails 6.1.1

**Ruby version**: ruby 2.7.2p137

**Comment by jonathanhefner** [comment] 2021-02-05 15:30
Thank you for opening an issue!  This is a duplicate of #41123, and is fixed by #41200.

**Closed by jonathanhefner** 2021-02-05 15:30 UTC
