### ISSUE TITLE
Cannot validate presence of ids on multi-multi associations

### ISSUE THREAD

**Issue by jonswar** [rails/rails#17667] opened 2014-11-18 19:00 UTC
When a multi-multi association is created indirectly through one of its parent objects, ActiveRecord will try to validate it while it is in an invalid state (its foreign ids are nil). The code below works in Rails 3.2.18 but fails in Rails 4.1.7. (I tried to test this against rails.git master but I was getting an unrelated problem with bad generated sqlite3 sql, even for a much simpler test).

```
#!/usr/bin/env ruby
unless File.exists?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', '4.1.7'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books do |t|
  end

  create_table :authors do |t|
  end

  create_table :book_authors do |t|
    t.integer :book_id
    t.integer :author_id
  end
end

class Book < ActiveRecord::Base
  has_many :book_authors
  has_many :authors, :through => :book_authors
end

class Author < ActiveRecord::Base
  has_many :book_authors
  has_many :books, :through => :book_authors
end

class BookAuthor < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
  validates_presence_of :book_id, :author_id
end

class BugTest < MiniTest::Unit::TestCase

  # Fails with 'ActiveRecord::RecordInvalid: Validation failed: Book authors is invalid'
  # Specifically, the book_id and author_id are nil.
  def test_create_book_author_relationship
    author = Author.create!
    book = Book.create!(:author_ids => author.id)  # or :authors => author
    assert(true)
  end

  # Without the validates_presence_of or similar, this test will fail
  def test_create_blank_book_author
    assert_raises(ActiveRecord::RecordInvalid) { BookAuthor.create! }
  end
end
```

**Comment by jonswar** [comment] 2015-01-06 17:35
Never heard back on this. I don't understand why this should be broken...we just want to validate the presence of an id, not the whole associated object. Is it possible to fix?

**Comment by brainopia** [comment] 2015-01-06 19:16
@jonswar Hello,

I've checked the behavior on 3.2.18. The test does not fail, but with a more meaningful assertion it could be seen that only `book` and `author` records are created without `book_authors` record.

On rails 4.x you'll get an exception. But without doubt it's more beneficial than to silently loose a record as was in previous version.

When associated records are created, they are validated together before any sql executes. By default it's done only on new records (to ensure integrity) but can be enabled on updates to existing records as well (autosave: true). Since in your example `book_author` is a new record, it will be validated by it's parent `book` on save.

Ability to disable validations on a new associated record (as was previously possible with autosave: false) won't help you in this case. Since you'd like your validations be ran, but only after book is created.

It's hard to provide general mechanism to specify when associated records should be validated, since they could be arbitrarily complex. Fortunately it's easy to do manually. The book and author should be created first and then relationship between them. To ensure integrity you'd wrap them in transaction:

```ruby
ActiveRecord::Base.transaction do
  author = Author.create!
  book = Book.create!
  BookAuthor.create! author_id: author.id, book_id: book.id
end
```

And if you have associated record ids and don't wont to load them to create `book_author` it sill would work fine as you requested.

**Comment by jonswar** [comment] 2015-02-06 17:46
> only book and author records are created without book_authors record

@brainopia I don't understand. I changed the test to confirm that the book_authors record is created, and it still passes for me on 3.2.18.

    def test_create_book_author_relationship
      assert(BookAuthor.count == 0)
      author = Author.create!
      book = Book.create!(:author_ids => author.id)  # or :authors => author
      assert(BookAuthor.count == 1)
      book_author = BookAuthor.first
      assert(book_author.author_id == author.id)
      assert(book_author.book_id == book.id)
    end

**Comment by p8** [comment] 2021-07-12 06:43
I'm closing this as it seems no longer reproducible on main:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books do |t|
  end

  create_table :authors do |t|
  end

  create_table :book_authors do |t|
    t.integer :book_id
    t.integer :author_id
  end
end

class Book < ActiveRecord::Base
  has_many :book_authors
  has_many :authors, :through => :book_authors
end

class Author < ActiveRecord::Base
  has_many :book_authors
  has_many :books, :through => :book_authors
end

class BookAuthor < ActiveRecord::Base

  belongs_to :book
  belongs_to :author
  validates_presence_of :book, :author
end

class BugTest < MiniTest::Unit::TestCase

  # Fails with 'ActiveRecord::RecordInvalid: Validation failed: Book authors is invalid'
  # Specifically, the book_id and author_id are nil.
  def test_create_book_author_relationship
    author = Author.create!
    assert Book.new(authors: [author]).valid?
  end

  # Without the validates_presence_of or similar, this test will fail
  def test_create_blank_book_author
    assert_raises(ActiveRecord::RecordInvalid) { BookAuthor.create! }
  end
end
```

**Closed by p8** 2021-07-12 06:43 UTC
Labels: With reproduction steps, activerecord
