### ISSUE TITLE
ActionView template finder can become really slow due to disk IO

### ISSUE THREAD

**Issue by elia** [rails/rails#20752] opened 2015-07-01 22:13 UTC
As the number of view paths, template handlers and formats increases.

Caching `ActionView::PathResolver#find_template_paths` as follows sped the rendering of an API call (rabl/json) **from 2500ms to 30ms** once the cache was warmed up:

``` ruby
ActionView::PathResolver.class_eval do
  def find_template_paths(query)
    Rails.cache.fetch([:action_view_path_resolver_cache, query]) do
      Dir[query].reject { |filename|
        File.directory?(filename) ||
          # deals with case-insensitive file systems.
          !File.fnmatch(query, filename, File::FNM_EXTGLOB)
      }
    end
  end
end
```
### Details

The app is Rails v4.1.11 / Ruby 2.2.1 / Spree 2-4-stable. I also noticed really slow performance for partial lookups relying on controller inheritance (e.g. `render 'header'` where `_header.html` is in `app/views/application`), I think it might be for the same reason.

I got this results on a Spree 2.4 app with Rails 4.1.11 calling [this API endpoint](https://github.com/spree/spree/blob/2-4-stable/api/app/controllers/spree/api/states_controller.rb#L8-L20) during which `#find_template_paths` [is called 137 times](https://gist.github.com/elia/e3e624e2235f12946ea4) with queries as long as:

```
/Users/elia/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/kaminari-0.16.3/app/views/layouts/action_controller/base{.en,}{.json,}{.v10,.v9,.v8,.v7,.v6,.v5,.v4,.v3,.v2,.v1,}{}{.erb,.builder,.raw,.ruby,.prawn,.coffee,.opal,.haml,.rabl,.jbuilder,}
```

From what I saw not much has changed on rails@master wrt the path lookup, but I could be wrong. I agree that this can be regarded as a Spree issue but I believe that similar problems arise in many Rails apps.

_just for completeness the logs of the two requests follow_

Without the patch:

```
Started GET "/api/states.json?country_id=155" for 127.0.0.1 at 2015-07-01 23:49:58 +0200
Processing by Spree::Api::StatesController#index as JSON
  Parameters: {"country_id"=>"155"}
  Spree::User Load (0.5ms)  SELECT  "spree_users".* FROM "spree_users"  WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."spree_api_key" = '' LIMIT 1
  Spree::Country Load (0.3ms)  SELECT  "spree_countries".* FROM "spree_countries"  WHERE "spree_countries"."id" = $1 LIMIT 1  [["id", 155]]
  Spree::State Load (0.2ms)  SELECT  "spree_states".* FROM "spree_states"  WHERE "spree_states"."country_id" = $1  ORDER BY name DESC LIMIT 1  [["country_id", 155]]
  Spree::State Load (0.4ms)  SELECT "spree_states".* FROM "spree_states"  WHERE "spree_states"."country_id" = $1  ORDER BY name ASC  [["country_id", 155]]
  Rendered /Users/elia/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bundler/gems/spree-aa554d622f47/api/app/views/spree/api/states/index.v1.rabl (1.7ms)
Completed 200 OK in 2848ms (Views: 2829.6ms | ActiveRecord: 1.9ms)
```

With the patch:

```
Started GET "/api/states.json?country_id=155" for 127.0.0.1 at 2015-07-01 23:49:05 +0200
Processing by Spree::Api::StatesController#index as JSON
  Parameters: {"country_id"=>"155"}
  Spree::User Load (0.7ms)  SELECT  "spree_users".* FROM "spree_users"  WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."spree_api_key" = '' LIMIT 1
  Spree::Country Load (0.3ms)  SELECT  "spree_countries".* FROM "spree_countries"  WHERE "spree_countries"."id" = $1 LIMIT 1  [["id", 155]]
  Spree::State Load (0.2ms)  SELECT  "spree_states".* FROM "spree_states"  WHERE "spree_states"."country_id" = $1  ORDER BY name DESC LIMIT 1  [["country_id", 155]]
  Spree::State Load (0.4ms)  SELECT "spree_states".* FROM "spree_states"  WHERE "spree_states"."country_id" = $1  ORDER BY name ASC  [["country_id", 155]]
  Rendered /Users/elia/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bundler/gems/spree-aa554d622f47/api/app/views/spree/api/states/index.v1.rabl (1.8ms)
Completed 200 OK in 31ms (Views: 7.7ms | ActiveRecord: 2.0ms)
```
### Solution (?)

The above patch of course is not good (even in concept) for development where views are added and modified regularly. A possible solution could be to keep the lookup dynamic just inside the app root and cache the paths coming from gems. That in turn could be an issue for people relying on the fact that views are reloaded even for gems in development (e.g. pleople using engines) but to me seems a good trade off anyway.

cc @tenderlove @masterkain

**Comment by elia** [comment] 2015-07-02 08:24
**UPDATE**

The following should work fine in development, with this I'm getting a response in 140ms (instead of 30ms).

```ruby
ActionView::PathResolver.class_eval do
  def find_template_paths(query)
    search = lambda do |query|
      Dir[query].reject { |filename|
        File.directory?(filename) ||
          # deals with case-insensitive file systems.
          !File.fnmatch(query, filename, File::FNM_EXTGLOB)
      }
    end
    
    return search[query] if query.start_with? Rails.root.to_s
    Rails.cache.fetch([:action_view_path_resolver_cache, query]) { search[query] }
  end
end
```

**Comment by rafaelfranca** [comment] 2016-03-11 15:17
@tenderlove thoughts?

**Comment by fxgallego** [comment] 2016-03-17 01:13
Hi, got here by ActionView::PathResolver#find_template_paths. In the RubyProf it  report takes 94% time rendering a template in app/views/application. Performance gets better when moving the template to the same folder in which is called. My app is not so big but a  I noticed this problem running on windows.
This is Rails 4.2.4 Ruby 2.2.4 (W10)

**Comment by fxgallego** [comment] 2016-03-17 16:06
Tested on JRuby on windows and the same problem. Same app on linux works ok and changing the template locations makes no difference. Clearly it's a problem related with the number of system calls and how fast is the call depending on the OS / filesystem.

**Comment by tenderlove** [comment] 2016-03-17 17:50
Template paths should be cached in production.  Just to be clear, this is an issue in *development*, right?  I *think* we have some code to watch the FS now (/cc @matthewd), and if we can watch the FS we should know when to expire caches.  If we can get the cache to expire correctly, then I don't see a problem caching in dev.

**Comment by fxgallego** [comment] 2016-03-17 17:58
@tenderlove yes, for me it's development only.

**Comment by elia** [comment] 2016-05-12 21:20
@tenderlove can confirm it's development only. Would it be ok to just add some API to the `AV::PathResolver` for expiring the paths cache and then use it from the FS watcher? 

I've gained another 1.2s (on another page) doing pretty much the same with Sprockets paths (see below), would that approach be ok for Sprockets too?

Alternatively the FS calls could be delegated to some kind of FS wrapper. The should be swappable with one that caches the results and expires them when the watcher says so.

cc @schneems 

---

_Saving me 1.2s more caching `Sprockets::Environment#find_asset` for assets outside of the project._

```ruby
CACHED_RAILS_ROOT_PATH = Rails.root.to_s
CACHED_RAILS_VENDOR_PATH = Rails.root.to_s

# See https://github.com/rails/rails/issues/20752
module ActionViewPathResolverCache
  # Will cache the result for anything outside the current app.
  # 
  # Benchmark on: /api/states.json?country_id=155
  # 
  #   Before: Completed 200 OK in 2525ms (Views: 2508.5ms | ActiveRecord: 5.1ms)
  #   After:  Completed 200 OK in 28ms (Views: 11.8ms | ActiveRecord: 4.5ms)
  # 
  def find_template_paths(query)
    action_view_path_resolver_cache = (Thread.current[:action_view_path_resolver_cache] ||= {})

    action_view_path_resolver_cache[query] or begin
      result = super

      # Don't cache app template paths in development, as they can be modified
      if query.start_with?(::CACHED_RAILS_VENDOR_PATH) || !query.start_with?(::CACHED_RAILS_ROOT_PATH)
        action_view_path_resolver_cache[query] = result
      end

      result
    end
  end

  ActionView::PathResolver.prepend self if ENV['CACHE_TEMPLATE_LOOKUP']
end

module TurboSprocketsEnvironment
  # Will cache the result for anything outside the current app.
  #
  # BEWARE: Won't recognize newly created files that override stuff already
  #         present withing the other sprockets paths (e.g. overriding jquery).
  #
  # Benchmark on: /it/IT/women
  #
  #   Before: Completed 200 OK in 2278ms (Views: 2172.8ms | ActiveRecord: 29.1ms)
  #   After:  Completed 200 OK in 967ms (Views: 876.8ms | ActiveRecord: 27.6ms)
  #
  def find_asset(*args)
    turbo_sprockets_cache = (Thread.current[:"turbo_sprockets_cache_#{object_id}"] ||= {})
    
    turbo_sprockets_cache[args] or begin
      asset = super or return
      path  = asset.filename

      # Don't cache app template paths in development, as they can be modified
      if path.start_with?(::CACHED_RAILS_VENDOR_PATH) || !path.start_with?(::CACHED_RAILS_ROOT_PATH)
        turbo_sprockets_cache[args] = asset
      end

      asset
    end
  end

  Sprockets::Environment.prepend self if ENV['CACHE_TEMPLATE_LOOKUP']
end
```

**Comment by elia** [comment] 2016-05-12 21:40
uuugh, I'm dumb, I accidentally tested caching everything in sprockets (this is not vendor `CACHED_RAILS_VENDOR_PATH = Rails.root.to_s`), so the gain above is what _could_ be gained if sprockets was to use the FS watcher instead of constantly checking the mtime of all the dependent assets. After fixing the two constants the Sprockets hack isn't yielding any significant gain 😞.

```ruby
CACHED_RAILS_ROOT_PATH = File.expand_path("#{__dir__}/..")
CACHED_RAILS_VENDOR_PATH = File.expand_path("#{__dir__}/../vendor")
```

**Comment by fxgallego** [comment] 2016-07-07 13:42
I've made the following test:
In action_view\template\resolver.rb override initialize in OptimizedFileSystemResolver as
```ruby
  # An Optimized resolver for Rails' most common case.
  class OptimizedFileSystemResolver < FileSystemResolver #:nodoc:
    def initialize(path, pattern=nil)
      super(path, pattern=nil)
      reloader = ActiveSupport::FileUpdateChecker.new([], {@path => ['*']}) do
        clear_cache
      end
      Rails.application.reloaders << reloader
      ActionDispatch::Reloader.to_prepare do
        reloader.execute_if_updated
      end
    end
```
And in order to force template resolver cache in development without change another file I've added the following code after the caching class accessor definition:
```ruby
    cattr_accessor :caching
    self.caching = true
    # For test only
    def self.caching=(boolean)
      @caching = true
    end
```

I've done some simple tests like modify views, add and remove new partials and the FileSystemUpdater always clears the cache.
The development performance is huge, specially in windows.

I'm not a rails internals expert so I'm not aware of what other things could go wrong.

**Comment by fxgallego** [comment] 2016-08-04 11:30
I'd to restart rails after adding a new view file so this is not exactly the solution. It is a shame the Ruby file api performance under windows :(

**Comment by DangerDawson** [comment] 2016-09-01 08:45
Just to add my 2 cents worth:

We have experienced exactly the problem you describe, and found that upgrading from ruby 2.1.* to 2.2.* or 2.3.* amplified the slow down by a factor of 3-4x ( mac os x ).

@layonferreira did some benchmarking around what we see as a performance regression in ruby

[issue 10015](https://bugs.ruby-lang.org/issues/10015)

I also discovered this gem which looks to solve the issue we are seeing in Rails by caching the filenames and doing the search in memory 

[more_optimized_resolver](https://github.com/amatsuda/more_optimized_resolver)
[presentation](http://sssslide.com/speakerdeck.com/a_matsuda/3x-rails)

Although it does not support case-insensitive files systems.

I would love to see the problem described fixed in rails, as it would make a huge difference to productivity and developer happiness when working with rails in development mode.

**Comment by fxgallego** [comment] 2017-09-26 17:52
This is probably related to this https://bugs.ruby-lang.org/issues/13167

**Comment by fernandomm** [comment] 2017-11-08 13:56
I don't if this is directly related to this issue since I didn't had the chance to dig into the ActionView code yet.

After upgrading a Rails 3.2 application to 4.2 and then 5.1 I noticed a huge performance drop in development environment when running Rails 4.2 or 5.1. It doesn't happen in production.

This application makes use of several partials to render pages and rails log clearly show that actionview is taking 3s+ to load in some pages.

After verifying the differences between production and development environment, I found that the setting config.action_view.cache_template_loading is what causes the problem.

Enabling it in development drops the load time from 3000ms to less than 500ms. But having cache_template_loading enabled it not ok in development since I would have to restart the server whenever a template is changed.

It looks like Rails < 4 cached partials/templates **within the same request** but the newer versions doesn't.

I added the following code in ApplicationController:

```
  prepend_before_action {
    ActionView::Resolver.caching = true
  }
  after_action {
    ActionView::Resolver.caching = false
  }

```

Then disabled config.action_view.cache_template_loading and restarted the server. I'm now getting the response times below 500ms while I still can make changes to views and test them without restarting the server.

This was tested on OS X 10.12.5 as well as in a docker container running phusion/passenger-ruby24:0.9.26 image.

**Comment by bencrouse** [comment] 2017-12-19 17:28
I'm experiencing this in the test environment as well for system tests. A simple `Rails.application.config.action_view.cache_template_loading = true` fixes.

@tenderlove @rafaelfranca any reason this shouldn't be true for the test environment? Seems like a no-brainer PR I could open...

**Comment by inopinatus** [comment] 2018-06-01 09:12
I had renders with nested layouts taking over 1500ms in dev, of which 95% was Dir::glob. I've got this back down to 30ms by caching the results of Dir.glob (with cache eviction when `listen` says the path has changed).

**Comment by jrochkind** [comment] 2018-07-13 00:38
> Template paths should be cached in production.

I'm not totally sure this is true, I got here because I feel like I'm seeing touching the disk to find and load templates on every call, even in production. But I'm not totally sure what I'm seeing. 

Could anyone give me a hint as to _what_ code where is supposed to be caching template lookup in production, and what config variables we're talking about here for "in production" (`config.cache_classes == true`?)   That would be super helpful to me in figuring out what's going on. I'm not seeing anything obvious in `LookupContext` or the things that call it, that would even suggest anything is trying to cache lookup.

**Comment by wheeyls** [comment] 2018-08-18 21:46
I ran into this this week. On Mac OS X I found that this is slow:

    Dir['app/views/template/name{.{en},}{.html,}{+{},}{.{raw,erb,html,builder,ruby,markerb,coffee,slim,jbuilder},}']

But that this actually performs just fine:

    Dir['app/views/template/name*']

`File.fnmatch` seems to be taking care of the rest of the resolution, so this monkey patch seems to resolve the issue altogether:


    def find_template_paths(query)
      prefilter = query.split('{')[0]

      # use file system to narrow down results
      Dir[prefilter + '*'].reject do |filename|
        File.directory?(filename) ||
          # query run without filesystem to verify result
          !File.fnmatch(query, filename, File::FNM_EXTGLOB)
      end
    end

**Comment by bencrouse** [comment] 2018-08-20 13:12
@wheeyls was there a bug or something in your first monkey patch? I tried it and saw clear improvement, so I made a note to come back to it this morning so I could potentially add the monkey patch in my app.

**Comment by wheeyls** [comment] 2018-08-20 13:57
@bencrouse yes there was a bug in the first monkey patch. It didn't support `variants` properly so I didn't want to leave it out there.

This is version is better, but might still have subtle issues. On the plus side, it is something like 10x faster.

```
if Rails.env.development?
  module ActionView
    class PathResolver
      def find_template_paths(query)
        prefilter(query).reject do |filename|
          File.directory?(filename) ||
            !File.fnmatch(query, filename, File::FNM_EXTGLOB)
        end
      end

      def prefilter(query)
        path = query.split('{')[0]
        # sort by + sign to make sure that variant matches get priority
        Dir[path + '*'].uniq.sort_by { |i| i =~ /\+/ ? 0 : 1 }
      end
    end
  end
end
```

**Comment by jrochkind** [comment] 2018-08-20 15:58
This has been a pretty big problem in development for me for a couple years now. (I don't totally understand why it _became_ a bigger problem than it used to be; an app that previously was fine in dev with the number of partial tempaltes it loaded now is almost unusable in dev). 

(I'm actually surprised this problem isn't widespread. Maybe most people don't try to use lots of partials?)

@wheeyls  any chance of making an actual PR, which hopefully can be approved, to fix this for everyone?

**Comment by inopinatus** [comment] 2018-08-26 02:38
@jrochkind I actually think this probably is widespread, and people are either being deterred from Rails development "because it's so slow", sucking it up because they've overheard the false mantra that "Rails is slow", suffering in silence, or just fixing it themselves with an ad-hoc, poorly specified monkey-patched cache that works for them.

**Comment by jrochkind** [comment] 2018-08-26 13:32
Going through past comments, this seems to be a performance regression in Dir.glob in ruby stdlib itself? Very weird. And somewhat distressing that ruby core isn't fixing it. https://bugs.ruby-lang.org/issues/13167

@DangerDawson posted a link to this gem that provides it's own monkey-patch to Rails to try and work around: https://github.com/amatsuda/more_optimized_resolver

Not sure if that's still working with present Rails, or if it has any edge case bugs. But people trying monkey patches might want to start from there, rather than re-invent the wheel?

I think perhaps the error only occurs when you are using Rails template lookup paths to find templates that are not in the local app immediate controller-named views directory. And probably gets worse the more template lookup paths you have (the more controller superclasses in combination with Rails engines).  This may explain why/how it may not be effecting everyone, and not obviously a priority to fix -- it may actually just make the Rails template lookup paths feature unusable, but not be so no noticeable if you aren't using it. 

This is still really unfortunate. I wish there was a way to get someone who understood what was going on better to prioritize it. :(

**Comment by wheeyls** [comment] 2018-08-26 15:57
@jrochkind The actionview test suite is pretty complete. The monkeypatch I’m using doesn’t resolve all the issues, but I was going to take some time and write a version that satisifies those specs without hitting the IO issues that DIR.glob raises.

It is strange to fix it at this level though. Who knows how many other uses of glob are out there that are surprisingly slow?

This appears to be really painful for us when we run our code inside a docker container, and much less acute when running on mac os. So I assume the impact of this issue varies greatly based on OS, which may explain why ruby core hasn’t prioritized this yet.

**Comment by jrochkind** [comment] 2018-08-26 17:20
@wheeyls Yeah, it ought to be fixed at the ruby level, which requires C expertise as well as differnet politics over in ruby-core. 

I think the way Rails template lookup works _especially_ triggers the performance regression, it winds up using Dir multiple times in a particularly performance-problematic -- it seems -- to do template lookup in all the lookup paths. And does it multiple times every request in development mode, the more partials you have the more. 

So I think probably few other software is impacted as much as Rails, and it's not unreasonable to have a Rails patch for it in the meantime. 

I would be so thrilled if you had one!

If you had a Rails patch, you could mention in the ruby core ticket on the Dir.glob regression, that you had to do these crazy things to work around the regression, which perhaps would help share some urgency there

**Closed** 2018-09-13 01:53 UTC
Labels: actionview, pinned

**Comment by jrochkind** [comment] 2018-12-18 22:20
@ahorek on #30502 asked me to test ruby 2.6.0.rc1 for this. My actual issue is more related to this ticket than #30502, so I moved it here. 

The good news is, ruby 2.6.0 does help a lot. 

I made a test rails 5.2.2 app that simply loads the same partial 1000 times in a view that does nothing else. Note this is all rails 5.2.2, so does _not_ have the improvement in #33860 yet, this is is purely comparing ruby versions. 

both tested with no bootsnap, no spring. (They didn't actually make too much of a difference). 

### ruby 2.5.3

First load: 5747ms, 1649ms attributed to rendering, but I don't believe that, since nothing else is happening

subsequent loads: 1510-1560ms

### ruby 2.6.0, bootsnap with cold cache, no spring

First load: 4513ms, 630.3ms attributed to view rendering, but I don't believe that
Subsequent loads: 660-720ms

## So, yes, ruby 2.6 helps enormously

Almost 3x faster on non-first loads. 

## Still suggests  _no_ caching in development

Even 630ms for 1000 renders of the _same_ partial suggests to me that Rails is hitting the disk on _every_ render call. 

I would have expected that Rails could treat this like _class_ caching/reloading too. During the same request, once you look up `render "whatever_partial"`, subsequent renders of the _same_ partial during the _same request_ should ideally not have to hit disk again. It should only have to be looked up on disk again in a future request, triggered the same was as class caching/reloading (ie, maybe not at all if nothing has changed on disk?). 

It does not seem like this is happening however? Perhaps it is more complex to implement than it might seem?

If #33860 makes each "lookup of paths on disk to find template" even faster, that on top of ruby 2.6 should help further.  But it's still going to be slower than it could be if it's still hitting disk on every single `render` call, even for the same string in the same place in the same request. 

You might ask, why not use `:collection` rendering?  Of course I do, but imagine `render partial: "widget", collection: @widgets`, where the `widget.html.erb` _itself_ does a `render "widget_description"` or something. There's no getting around that one. In a complex app, this can be such a serious slowdown in development that I am forced to refactor lots of things into helpers that were more readable as partials, just to make the app usable in development. 

But 2.6 will definitely help.

**Comment by ahorek** [comment] 2018-12-19 00:04
you can enable caching in development
```
Rails.application.configure do
  config.action_controller.perform_caching = true
end
```
but then you'll loose ability to change partials without restart.

In development rails have to touch the disk because templates could be changed, added, removed or even replaced with a different one with the same name and higher priority. That's why you can't cache their locations so easily without breaking stuff.

Caching partials during the same request could work I think...

In overall the IO is slower on windows or another example https://bugs.ruby-lang.org/issues/14378
It could be more efficient if ruby is optimized specifically for windows, but it's not simple to support many platforms and windows is way too different from others.
How many ruby production servers runs on windows? That's why ruby and also other languages like python aren't as fast on windows. Not because windows are bad or slow, but generally it isn't worth to optimize for it if you still want to support many platforms like ruby do.

there's one more way to avoid this problem. Try https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux
ruby & rails are surprisingly much faster then the native windows binary.

**Comment by jrochkind** [comment] 2018-12-19 00:10
@ahorek sorry, I think I wasn't clear. 

With caching turned off, as standard for development Rails will reload _classes_ at most _once per request_. 

But, I believe, Rails will check the disk to locate a a view template, on every single call to `render`, possibly multiple times per request for the exact same template. 

I have spent some time trying to understand the template loading code, and not quite figured it out, it's complicated and spread across a number of different classes. But I think it making an expensive check to disk on every render -- even repeated renders with the same arguments from the same call site -- is the only explanation for observed behavior. 

If this could be improved to match _class_ caching -- such that the lookup is cached for the duration of the request, as with classes -- this would probably have enormous benefit. However, the complexity of the code makes it hard to figure out how to do this, and possibly makes it hard or infeasible to do it, not sure. I haven't been able to figure out where it all happens, or I would try a PR.

**Comment by jrochkind** [comment] 2018-12-25 15:37
Thanks for the feedback @ahorek. 

I want to clarify, this is _not_ windows-only, my profiling above was on MacOS, which showed significant speedup in loading of many partials in dev-mode. 

Thanks for the MRI patch, it def helps!

**Comment by ahorek** [comment] 2018-12-25 23:14
I would like to mention I'm not the author of the patch, h.shirosaki is https://bugs.ruby-lang.org/users/2931
Thanks to him and many others who helped to include this patch to ruby 2.6!
