### ISSUE TITLE
System testing crashes with RunTimeError – Queue not empty

### ISSUE THREAD

**Issue by lcskoerner** [rails/rails#39982] opened 2020-08-04 23:38 UTC
### Steps to reproduce
Using the versions described below run:
rails new project

test/application_system_test_case.rb

```ruby
require "test_helper"
​
class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  Capybara.register_driver(:headless_chrome) do |app|
    capabilities = Selenium::WebDriver::Remote::Capabilities.chrome \
      chromeOptions: { args: %w[headless disable-gpu window-size=1280x760] }
    Capybara::Selenium::Driver.new app,
      browser: :chrome, desired_capabilities: capabilities
  end
​
  def setup
    super
    Capybara.configure do |config|
      config.run_server = false
      config.app_host = 'https://www.google.com'
    end
  end
​
  driven_by :selenium, using: :headless_chrome
end
```

test/system/projects_test.rb

```ruby
require "application_system_test_case"
​
class ProjectsTest < ApplicationSystemTestCase
  test "visits google" do
    visit "/"
​
    assert_equal "https://www.google.com", Capybara.app_host
    page.assert_text "About"
  end
end
```

rails test:system
the system will crash with the following error:

```
Run options: --seed 46930

# Running:

/Users/lucaskoerner/code/lcskoerner/project/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/lucaskoerner/code/lcskoerner/project/config/application.rb to limit the frameworks that will be loaded.
/Users/lucaskoerner/code/lcskoerner/project/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/lucaskoerner/code/lcskoerner/project/config/application.rb to limit the frameworks that will be loaded.
Traceback (most recent call last):
	2: from /Users/lucaskoerner/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/minitest-5.14.1/lib/minitest.rb:68:in `block in autorun'
	1: from /Users/lucaskoerner/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/minitest-5.14.1/lib/minitest.rb:145:in `run'
/Users/lucaskoerner/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:124:in `shutdown': Queue not empty, but all workers have finished. This probably means that a worker crashed and 3 tests were missed. (RuntimeError)
```

The test works if you update test/test_helper.rb line 7 to:

`parallelize(workers: 1)`

It may be related to https://github.com/lcskoerner/rails-task-manager/blob/master/test/test_helper.rb

### Expected behavior

The test should run successfully

### Actual behavior
The test is crashing

### System configuration
**Rails version**: Rails 6.0.3.2

**Ruby version**: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin18]

Mac OS version: 10.14.6

Chrome version: 84.0.4147.105 (Official Build) (64-bit)

**Comment by eileencodes** [comment] 2020-08-05 14:10
I edited your issue to make the code more readable.

**Comment by eileencodes** [comment] 2020-08-05 15:17
Do your other tests run fine? Or is it just the system tests that don't work with parallel testing?

**Comment by lcskoerner** [comment] 2020-08-05 15:30
Thank you for the edit @eileencodes 🙏🏻

Other tests seem to run just fine. I believe the issue is related to Selenium/Headless Chrome.

**Comment by KapilSachdev** [comment] 2020-08-09 07:45
Tested with the example provided and same system configuration except the OS.
Working fine in `Ubuntu 20.04.1`.

_Just to verify, can you point rails to master in your Gemfile (`gem 'rails', github: 'rails/rails'`) and see if its still reproducible._

**Comment by lcskoerner** [comment] 2020-08-12 02:53
Hi @KapilSachdev, I made the update and the issue does not occur. 

The original gem info was:
`gem 'rails', '~> 6.0.3', '>= 6.0.3.2'`

🙂

**Comment by KapilSachdev** [comment] 2020-08-12 10:15
That could mean that it is resolved in `master`.
However, I'm unable to reproduce the issue in my machine, so created a script, so can you confirm if the following script raises the error for you.

```ruby
# frozen_string_literal: true

require 'bundler/inline'
gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
  gem 'byebug', require: true
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

require 'rails/test_help'

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  parallelize(workers: :number_of_processors)
  Capybara.register_driver(:headless_chrome) do |app|
    capabilities = Selenium::WebDriver::Remote::Capabilities.chrome \
      chromeOptions: { args: %w[headless disable-gpu window-size=1280x760] }
    Capybara::Selenium::Driver.new app,
                                   browser: :chrome, desired_capabilities: capabilities
  end

  def setup
    super
    Capybara.configure do |config|
      config.run_server = false
      config.app_host = 'https://www.google.com'
    end
  end

  driven_by :selenium, using: :headless_chrome
end

class ProjectsTest < ApplicationSystemTestCase
  test 'visits google' do
    visit '/'

    assert_equal 'https://www.google.com', Capybara.app_host
    page.assert_text 'About'
  end
end
```

**Comment by lcskoerner** [comment] 2020-08-17 02:53
Hi @KapilSachdev, it has raised the following error. Can you help me solve this ruby version dependency issue?

`Gem::LoadError: You have already activated concurrent-ruby 1.1.6, but your Gemfile requires concurrent-ruby 1.1.7. Prepending `bundle exec` to your command may solve this.
/Users/lucaskoerner/code/lcskoerner/project/test/system/projects_test.rb:4:in `<main>'
/Users/lucaskoerner/code/lcskoerner/project/bin/rails:9:in `<top (required)>'
/Users/lucaskoerner/code/lcskoerner/project/bin/spring:15:in `require'
/Users/lucaskoerner/code/lcskoerner/project/bin/spring:15:in `<top (required)>'`

**Comment by KapilSachdev** [comment] 2020-08-17 04:00
Create a new file `<filename>.rb` and paste the contents of the above script in that.
Run `ruby <filename>.rb`.

That should work without ny issues.

**Comment by lcskoerner** [comment] 2020-08-17 04:01
It worked fine @KapilSachdev. It failed when I ran it using rails test:system

**Comment by KapilSachdev** [comment] 2020-08-17 04:09
For that you should append `bundle exec` as suggested by the error.
`bundle exec rails test:system`

If the script ran successfully with `gem 'rails', '~> 6.0.3', '>= 6.0.3.2'` but with `rails:test system` still causes `RuntimeError` then i think this script does not reproduces your issue.

Can you review the script and try updating to reproduce the issue.

**Comment by lcskoerner** [comment] 2020-08-17 05:23
I executed exactly as suggested and got the same issue:

```
bundle exec rails test:system
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.1
Fetching concurrent-ruby 1.1.7 (was 1.1.6)
Installing concurrent-ruby 1.1.7 (was 1.1.6)
Using i18n 1.8.5
Using minitest 5.14.1
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.7 (was 2.0.2)
Installing tzinfo 1.2.7 (was 2.0.2)
Using zeitwerk 2.4.0
Fetching activesupport 6.0.3.2 (was 6.1.0.alpha)
Installing activesupport 6.0.3.2 (was 6.1.0.alpha)
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.10
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.6.0
Using rails-html-sanitizer 1.3.0
Fetching actionview 6.0.3.2 (was 6.1.0.alpha)
Installing actionview 6.0.3.2 (was 6.1.0.alpha)
Using rack 2.2.3
Using rack-test 1.1.0
Fetching actionpack 6.0.3.2 (was 6.1.0.alpha)
Installing actionpack 6.0.3.2 (was 6.1.0.alpha)
Using nio4r 2.5.2
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.3
Fetching actioncable 6.0.3.2 (was 6.1.0.alpha)
Installing actioncable 6.0.3.2 (was 6.1.0.alpha)
Using globalid 0.4.2
Fetching activejob 6.0.3.2 (was 6.1.0.alpha)
Installing activejob 6.0.3.2 (was 6.1.0.alpha)
Fetching activemodel 6.0.3.2 (was 6.1.0.alpha)
Installing activemodel 6.0.3.2 (was 6.1.0.alpha)
Fetching activerecord 6.0.3.2 (was 6.1.0.alpha)
Installing activerecord 6.0.3.2 (was 6.1.0.alpha)
Using mimemagic 0.3.5
Using marcel 0.3.3
Fetching activestorage 6.0.3.2 (was 6.1.0.alpha)
Installing activestorage 6.0.3.2 (was 6.1.0.alpha)
Using mini_mime 1.0.2
Using mail 2.7.1
Fetching actionmailbox 6.0.3.2 (was 6.1.0.alpha)
Installing actionmailbox 6.0.3.2 (was 6.1.0.alpha)
Fetching actionmailer 6.0.3.2 (was 6.1.0.alpha)
Installing actionmailer 6.0.3.2 (was 6.1.0.alpha)
Fetching actiontext 6.0.3.2 (was 6.1.0.alpha)
Installing actiontext 6.0.3.2 (was 6.1.0.alpha)
Using public_suffix 4.0.5
Using addressable 2.7.0
Using bundler 2.1.4
Using byebug 11.1.3
Using regexp_parser 1.7.1
Using xpath 3.2.0
Using capybara 3.33.0
Using childprocess 3.0.0
Using method_source 1.0.0
Using thor 1.0.1
Fetching railties 6.0.3.2 (was 6.1.0.alpha)
Installing railties 6.0.3.2 (was 6.1.0.alpha)
Using sprockets 4.0.2
Using sprockets-rails 3.2.1
Fetching rails 6.0.3.2 (was 6.1.0.alpha)
Installing rails 6.0.3.2 (was 6.1.0.alpha)
Using rubyzip 2.3.0
Using selenium-webdriver 3.142.7
Using webdrivers 4.4.1
rails aborted!
Gem::LoadError: You have already activated concurrent-ruby 1.1.6, but your Gemfile requires concurrent-ruby 1.1.7. Prepending `bundle exec` to your command may solve this.
/Users/lucaskoerner/code/lcskoerner/project/test/system/projects_test.rb:4:in `<main>'
/Users/lucaskoerner/code/lcskoerner/project/bin/rails:9:in `<top (required)>'
/Users/lucaskoerner/code/lcskoerner/project/bin/spring:15:in `require'
/Users/lucaskoerner/code/lcskoerner/project/bin/spring:15:in `<top (required)>'
Tasks: TOP => test:system
(See full trace by running task with --trace)
```

**Comment by KapilSachdev** [comment] 2020-08-17 05:35
Does `projects_test.rb` contains the script? 

If that's the case it won't work.
The script can not be used with rails command.

_The script was meant to be ran with `ruby` command. It was created to have a minimal code for reproduction, narrow down to a specific area of the problem and reduce the variables that are introduced with a full fledged rails app._

**Comment by lcskoerner** [comment] 2020-08-20 22:16
@KapilSachdev current status is:

rails test:system is running fine now.
your script (using ruby) is running fine as well.

🙂

**Comment by jonathanhefner** [comment] 2020-08-21 02:14
It sounds like this can be closed, yes?  Thank you for your help @KapilSachdev!

**Closed by jonathanhefner** 2020-08-21 02:14 UTC
