### ISSUE TITLE
Test failed after upgrading from Rails 5 rc1 to rc2

### ISSUE THREAD

**Issue by rosenfeld** [rails/rails#25497] opened 2016-06-23 20:58 UTC
Any ideas on what change could be causing this test to fail?

Output from RSpec:

```
1) MainController returns http success
     Failure/Error: process 'index', method: :get
     
     ActionDispatch::IllegalStateError:
       header already sent
```

Test:

```ruby
RSpec.describe MainController, type: :controller do
  it "returns http success" do
    process 'index', method: :get
    expect(response).to redirect_to new_user_session_path
  end
end
```

The action indeed works when testing manually and I get the redirected response but after upgrading from rc1 to rc2 this test failed. All other tests passed. The error happens in the line beginning with "process". Any ideas?

**Comment by maclover7** [comment] 2016-06-23 21:08
Thank you for reporting! Closing as a duplicate of #25269.

**Closed by maclover7** 2016-06-23 21:08 UTC

**Comment by rosenfeld** [comment] 2016-06-23 21:42
Thanks, by the way I'm also using Devise.
