### ISSUE TITLE
Unable to Preview audio/vnd.wave in Chrome

### ISSUE THREAD

**Issue by Raj-Kumar-P** [rails/rails#41880] opened 2021-04-08 13:29 UTC
I am using **active storage(5.2.5)**

On **.wav** file uploading it shows content type as **'audio/wav'** in direct upload. After **active_storage_attachments** create, **mimemagic gem** updates the content type as **audio/x-wav**. And the same file previewing in **chrome**.

But after changing to **marcel** it saves the content type as '**audio/vnd.wave**'. While debugging, **active_storage / blob / identifiable** updates the content types. And '**audio/vnd.wave**' not previewed in **chrome**, but **safari** allows previewing.

So, tried to comment the lines to update on **active_storage/blob/identifiable**. It updates the content type as **audio/x-wav** and allows it to preview in Chrome.

Tried to add configuration in **application.rb**

> config.active_storage.content_types_allowed_inline += %w[audio/wave audio/vnd.wave audio/wav audio/x-wav audio/x-pn-wav]

But unable to preview the **audio/vnd.wave** extension files in **chrome**.

Do I need to update any configurations to preview the **.wav** extension file in Chrome?

Hope understand my issue. Please help me to identify the issue.

**Comment by gmcgibbon** [comment] 2021-04-09 21:18
I can verify WAV audio uploaded with Active Storage has a content type of `audio/vnd.wave`. When uploading to a service like GCS, it is `audio/wav`. Audio element [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) seem to also suggest `audio/wav` is what browsers expect, however using an audio tag with `audio/vnd.wave` audio works in Chrome, Safari, and Firefox. @georgeclaghorn should [this line](https://github.com/rails/marcel/blob/949e9d6890d0ed52b75962280634670d102aa8dd/lib/marcel/tables.rb#L1111) be changed?

**Comment by georgeclaghorn** [comment] 2021-04-09 21:24
What does "preview" mean here? Can you provide a minimal sample app that demonstrates the issue?

**Comment by Raj-Kumar-P** [comment] 2021-04-12 12:46
I just tried to play the uploaded audio file in inline.

**Comment by gmcgibbon** [comment] 2021-04-21 21:21
I think this covers it: https://github.com/gmcgibbon/rails-issues/tree/wav_preview

If you change the content type header in the controller `audio/x-wav` and stream the audio, chrome is able to play the audio stream. Other browsers (firefox, safari) don't seem to be able to do this for either `audio/x-wav` or `audio/vnd.wave`. Only mp3 streams seem to work across browsers.

Regardless of browser behaviour, if the content type for wav files is different now that we're using marcel/mini_mime, it might be considered a regression.

**Comment by gmcgibbon** [comment] 2021-05-11 20:39
There's already an issue on marcel for this over on marcel, and I feel that it is a better place to track this issue since this is not actually an issue in Rails. Closing this in favour of https://github.com/rails/marcel/issues/41.

**Closed by gmcgibbon** 2021-05-11 20:39 UTC
Labels: activestorage
