### ISSUE TITLE
ParamsWrapper, nested ressource, parent id never included

### ISSUE THREAD

**Issue by elbarto132** [rails/rails#16194] opened 2014-07-16 19:53 UTC
Assume we have a nested ressource, resulting in a route like this:
/api/quotes/:quote_id/comments/:id(.:format)
If it gets called, ParamsWrapper never includes :quote_id
It should be included by default because it appears in attribute_names, but even if you set wrap_parameters :comment, include: [:id, :quote_id] it will not be included
Workaround: params[:comment][:quote_id] = params[:quote_id]

**Comment by elbarto132** [comment] 2015-08-25 18:47
ruby: 2.2.2
rails: 4.2.4
the problem still exists

**Comment by mgodwin** [comment] 2018-02-25 22:14
Hey @elbarto132, is this still an issue?  Did you discover any workarounds?

**Comment by chumakoff** [comment] 2018-09-12 11:15
@elbarto132 It is not an issue. It is how things work. I don't see any problem or bug here.

The parameter is present on the root level because it is explicitly specified in the path generated by `message_comments_url` method in your example:

```
= simple_form_for @comment, url: message_comments_url(params[:message_id]) do |f|
  = f.input :content
  = f.button :submit
```

The parameter is not present in the `comment` attributes group because in is not included in the form. It should be:

```
= simple_form_for @comment, url: message_comments_url(params[:message_id]) do |f|
  = f.input :message_id, as: :hidden
  = f.input :content
  = f.button :submit
```
Also, you should assign the attribute in the controller for it to be available in the form

```
class CommentsController < ApplicationController
  def new
    @comment = Comment.new(message_id: params[:message_id])
  end
```

But, you don't need this parameter in the form since you already have it in the url on the root level. Anyway, choose only one place to keep the parameter (url or form).

If you leave it at that, your `create` action should look like this:

```
class CommentsController < ApplicationController
  def create
     comment = Comment.new(params[:comment])
     comment.message_id = params[:message_id]
     comment.save
  end
```

What I am trying to say is that what you are expecting looks like Rails should be able to read your mind, but it is not so powerful yet )  There is no issue. Please, close it.

**Comment by vonnenaut** [comment] 2020-03-31 09:28
There's been no discussion in quite some time on this and it looks like it can be closed as not being an issue but rather a difference of expected behavior.  Can it be closed now?

**Comment by jonathanhefner** [comment] 2020-05-09 23:33
@elbarto132 Thank you for the issue, but I believe @chumakoff is correct.

Thank you @chumakoff for the thorough explanation!

**Closed by jonathanhefner** 2020-05-09 23:33 UTC
Labels: With reproduction steps, actionpack
