### ISSUE TITLE
Double require of clusivity.rb in ActiveModel reinitializes ERROR_MESSAGE

### ISSUE THREAD

**Issue by ewrenn8** [rails/rails#34264] opened 2018-10-19 19:51 UTC
### Steps to reproduce
We are running a Rails app which we recently updated our Rails gems for from 4->5.2.1 This app uses Sequel as the ORM and uses the individual Rails gems ActiveModel, ActionPack, ActionView, and Railties (instead of the comprehensive Rails gem).

 After this recent upgrade, customers have begun reporting seeing the following error in their logs:
```
/vendor/bundle/ruby/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/clusivity.rb:8: warning: already initialized constant ActiveModel::Validations::Clusivity::ERROR_MESSAGE
[2018-10-13 04:32:58+0000] 
/vendor/bundle/ruby/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/clusivity.rb:8: warning: previous definition of ERROR_MESSAGE was here
```
We have tracked this issue down to the loading of the `active_model/validtaions/clusivity.rb` file. This file is explicitly loaded in the `active_model/validtaions.rb` file [here][v.rb]. The same line is also responsible for loading the `active_model/validtaions/inclusion.rb` and `active_model/validtaions/exclusion.rb` files which both indirectly load the `clusivity.rb` file by a different path, shown [here][i.rb] and [here][e.rb]. 

Because the paths are different, `require` is attempting to load the `clusivity.rb` file twice, in turn attempting to redefine the ERROR_MESSAGE constant. We have verified this by seeing the the require of `clusivity.rb` returns true in both `validtaions.rb` as well as `exclusion.rb`. We also verified by removing the inclusion from both `exclusion.rb` and `inclusion.rb` and seeing there was no error printed.

### Expected behavior
Clusivity.rb only gets loaded once

### Actual behavior
Ruby attempts to load clusivity.rb twice which results in the attempt to redefine the constant ERROR_MESSAGE, resulting in an error

### System configuration
**Rails version**:
ActionPack 5.2.1
ActionView 5.2.1
ActiveModel  5.2.1
Railties 5.2.0
**Ruby version**:
Ruby 2.4

[v.rb]: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations.rb#L439
[i.rb]: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/inclusion.rb#L3
[e.rb]: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/exclusion.rb#L3

**Comment by y-yagi** [comment] 2018-10-19 23:14
Since require is an absolute path to manage the path, I usually guess that loading of the same file will not occur.
Can you please provide a sample application that reproduces the issue?

**Comment by ewrenn8** [comment] 2018-10-31 20:41
Hi @y-yagi ,

Although ruby does track already loaded files, a system set up which includes a symlink to the application and its gems will cause a double require.

When there is a symlink, the `__dir__` method of requiring, used [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations.rb#L439), expands the symlink to the absolute path to the file, allowing it to bypass searching the `$LOAD_PATH` for the file and require it directly. This fully expanded path then gets added to $LOADED_FEATURES.

This conflicts with the requires done in `inclusion.rb` and `exclusion.rb` done [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/inclusion.rb#L3) and [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/exclusion.rb#L3). This is because those requires do not provide an absolute path to a file so ruby must first search the `$LOAD_PATH` for a path containing `active_model/validations/clusivity`. The resulting path to `clusivity.rb` does not contain the expanded symlink because the symlink is not expanded when the gem's lib path is added to `$LOAD_PATH`. 

The difference between these required paths will cause ruby to require both even though they are the same file. This causes ERROR_MESSAGE to be initialized twice, resulting in the error we are seeing.

Because the error is so system dependent, it's difficult to provide an application which reproduces the issue but after inspecting the $LOAD_PATH and $LOADED_FEATURES it is clear this is where the issue lies.

**Comment by y-yagi** [comment] 2018-10-31 22:44
Hi, thanks for you details explanation. 
By changing `validations.rb` to an explicit `require`, that issue may be solved.  
But if this happens only with symlink, I am worried about the different problem. 
  
Problems related to symlink + require combinations are fixed in Ruby 2.5. 
Ref: [Bug \#10222: require\_relative and require should be compatible with each other when symlinks are used](https://bugs.ruby-lang.org/issues/10222) 
Can you confirm your issue with Ruby 2.5?

**Closed** 2018-11-22 22:55 UTC
Labels: more-information-needed

**Comment by vspar** [comment] 2019-04-12 15:39
Had the same issue on a Windows 10 dev system.

c:/ruby25-x64/lib/ruby/gems/2.5.0/gems/activemodel-5.2.3/lib/active_model/validations/clusivity.rb:8: warning: already initialized constant ActiveModel::Validations::Clusivity::ERROR_MESSAGE

c:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activemodel-5.2.3/lib/active_model/validations/clusivity.rb:8: warning: previous definition of ERROR_MESSAGE was here

Note the difference in "c:/ruby" and "c:/Ruby". These would be treated as different folders on *nix systems but in Windows they are the same.

I got round the problem by updating the path in the relevant files:

C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\activemodel-5.2.3\lib\active_model\validations\inclusion.rb
```
#require "active_model/validations/clusivity"
require __dir__ + "/clusivity"
```

C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\activemodel-5.2.3\lib\active_model\validations\exclusion.rb
```
#require "active_model/validations/clusivity"
require __dir__ + "/clusivity"
```

**Comment by vspar** [comment] 2019-04-12 16:35
I found reinstalling Ruby with a lowercase install path also solved the problem.

This is an old consideration with Windows systems of course but it's been a while since I used Windows for development (normally I work on Linux)!

But perhaps this is the same issue?

**Comment by y-yagi** [comment] 2019-04-12 22:18
Thanks for your information! 

> I found reinstalling Ruby with a lowercase install path also solved the problem.

I think this seems to be a Ruby's issue. Can you reproduce this issue with Ruby 2.6?

**Comment by vspar** [comment] 2019-04-15 11:28
Hi @y-yagi 

Yes, I think you're right.

Trying but as yet unable to recreate this using Ruby 2.6.

**Comment by y-yagi** [comment] 2019-04-15 22:36
Hi @vspar 
Thanks for your confirmation! 
If you can reproduce this issue with Ruby 2.6, please feel free to create a new issue. Thanks.
