### ISSUE TITLE
[Rails 6.0.3] Unexpected Behavior of Queries When a Boolean is Returned in an Active Record Model's Scope Block

### ISSUE THREAD

**Issue by junnnyyy** [rails/rails#52425] opened 2024-07-26 08:09 UTC
Hello,

This is Chloe Lee from South Korea. I am a software engineer currently developing with Ruby on Rails. While working with Active Record models, I encountered an issue where using methods like exists? inside a scope block, which returns a boolean, unexpectedly triggers a full table query. I am writing to discuss this issue as it seems to result in unexpected behavior.

Thank you for your attention to this matter.

### Steps to reproduce

(https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) below: -->
```ruby
# Define a simple Active Record model
class User < ApplicationRecord
  scope :false_scope, -> { false }
end

# Trying to chain scope which should not work but does not raise any error and falls back to 'all'
User.false_scope
```

### Expected behavior
When using a scope that inadvertently returns a boolean value, Rails should either handle this gracefully by ignoring the scope or raising an error, to prevent unexpected behavior. The use of such scopes should be clearly documented as incorrect or unsupported, guiding developers towards correct practices.

### Actual behavior
Currently, when a scope block returns a boolean value, it appears to fall back to the default all scope, leading to the entire table being queried without any filters. This can lead to significant performance issues and unexpected results in large datasets.

### System configuration
**Rails version**: Rails 6.0.3.7

**Ruby version**: ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]

I would appreciate any guidance or feedback on this matter, as ensuring the reliability and correctness of such features is crucial for maintaining the integrity of applications built with Rails.

Thank you very much for considering this issue. I look forward to your insights and any potential resolutions.

**Comment by Earlopain** [comment] 2024-07-26 08:37
Hi there, Rails 6.0 is not supported for bug fixes anymore. Disregarding that, this is documented behaviour: 

https://api.rubyonrails.org/v7.1.3.4/classes/ActiveRecord/Scoping/Named/ClassMethods.html#method-i-scope
> Adds a class method for retrieving and querying objects. The method is intended to return an [ActiveRecord::Relation](https://api.rubyonrails.org/v7.1.3.4/classes/ActiveRecord/Relation.html) object, which is composable with other scopes. **If it returns nil or false, an [all](https://api.rubyonrails.org/v7.1.3.4/classes/ActiveRecord/Scoping/Named/ClassMethods.html#method-i-all) scope is returned instead.**

I'm not quite sure about the usefulness of that, requiring an explicit `all` seems better and raising for non-relations like you said but this is where it's at right now.

**Comment by skipkayhil** [comment] 2024-07-26 15:13
Closing since this is behaving as documented. I've previously read a comment on an issue from Rafael explaining why this is by design, but having trouble finding it at the moment 🙁

**Closed by skipkayhil** 2024-07-26 15:13 UTC

**Comment by junnnyyy** [comment] 2024-07-29 02:59
@Earlopain @skipkayhil 
Thank you for your kind response! If I come across any additional information, I will be sure to share it. Have a great day!
