### ISSUE TITLE
Calling model.valid? will unexpectedly freeze strings as a side-effect

### ISSUE THREAD

**Issue by aprescott** [rails/rails#25353] opened 2016-06-10 16:49 UTC
In Rails 5.0.0.rc1 (and earlier, although I don't know how far back it goes), assigning a string as the value of an attribute can lead to that string being indirectly frozen after calling `valid?`.

This can cause unexpected behavior. I'll give a specific example of how it causes a bug with shoulda-matchers and Rails' own Postgres adapter's handling of `:money` types, but there are no doubt similar cases.

### Steps to reproduce

Take a `Product` model with a `sku` string attribute. Calling `product.valid?` will freeze strings used as part of assignments, which is a side-effect that can break other code:

```ruby
create_table :products, id: :uuid do |t|
  t.string :sku, null: false
end
```

```ruby
product = Product.new
str = "a string"
product.sku = str
str.frozen? #=> false
product.valid? #=> false
str.frozen? #=> true
```

### Expected behavior

Calling `model.valid?` should not cause a side-effect of freezing a string it doesn't control.

### Actual behavior

`model.valid?` freezes the string.

### System configuration

**Rails version**: 5.0.0.rc1.

**Ruby version**: 2.3.1.

### More explanation

The string is frozen after `product.valid?`, because [`ImmutableString` calls `freeze`](https://github.com/rails/rails/blob/v5.0.0.rc1/activemodel/lib/active_model/type/immutable_string.rb#L25), and `ImmutableString` is used as part of the mutable [`ActiveModel::Type::String` casting](https://github.com/rails/rails/blob/v5.0.0.rc1/activemodel/lib/active_model/type/string.rb#L15).

I'd like to give an example of how this freezing behavior can quite quickly break code, using shoulda-matchers.

Suppose the `Product` model above also has a `price` money attribute:

```ruby
create_table :products, id: :uuid do |t|
  t.integer :product_type, null: false
  t.string :sku, null: false
  t.money :price, null: false
end
```

Depending on the `product_type`, both `price` and `sku` are required to be `nil`:

```ruby
# `premium_product?` is based on `product_type`
validates :sku, inclusion: { in: [nil] }, unless: :premium_product?
validates :price, inclusion: { in: [nil] }, unless: :premium_product?
```

A unit test looks something like this:

```ruby
before { allow(subject).to receive(:premium_product?).and_return(false) }

# 1
it { should validate_inclusion_of(:sku).in_array([nil]) }
# 2
it { should validate_inclusion_of(:price).in_array([nil]) }
```

This simple setup has an order-dependent test failure. If expectation 1 runs before expectation 2, then expectation 2 fails.

The reason is that `validate_inclusion_of`, at least in 3.1.1, will [reuse the same string object](https://github.com/thoughtbot/shoulda-matchers/blob/v3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb#L497) for both tests. Call that string object `shoulda_test_string` for clarity.

When expectation 1 runs, it does something like:

```ruby
product.sku = shoulda_test_string
product.valid?
# ...
```

Since `product.valid?` will eventually call `shoulda_test_string.freeze`, the string used by shoulda-matchers is now froze.

Now expectation 2 runs and does something similar, only this time `product.price` is a money type. This time, [`ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Money` will try to do its own value casting using `sub!`](https://github.com/rails/rails/blob/v5.0.0.rc1/activerecord/lib/active_record/connection_adapters/postgresql/oid/money.rb#L25). Except the receiver of `sub!` is the frozen string, so the test errors when trying to read the assigned value:

```
Failure/Error: should validate_inclusion_of(:price).in_array([nil])

RuntimeError:
  can't modify frozen String
# /Users/adam/.gem/ruby/2.3.1/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb:136:in `public_send'
```

**Comment by aprescott** [comment] 2016-06-10 17:12
My original description included a misleading link to a commit that appears to actually be unrelated. I've removed it.

**Comment by zlobz** [comment] 2016-06-10 19:28
#24185

**Comment by maclover7** [comment] 2016-06-10 19:33
Closing as a duplicate of #24185.

**Closed by maclover7** 2016-06-10 19:33 UTC

**Comment by aprescott** [comment] 2016-06-10 19:37
@maclover7 since this is being closed, are you suggesting that the responsibility for fixing my broken use case rests with the shoulda-matchers maintainers? More generally, is it part of the contract of Active{Record,Model} that strings are frozen after calling `valid?`, and that to reliably work around this sort of case, you must, say, copy strings given as model attributes?

**Comment by zlobz** [comment] 2016-06-10 19:52
@aprescott you can use my patch (#24185)

**Comment by aprescott** [comment] 2016-06-10 20:03
@zlobz if something's going to be patched, I think it'd be better to patch shoulda-matchers in this case, to duplicate the string. Unfortunately, thoughtbot/shoulda-matchers appears to be currently without a maintainer, so actually getting that fix included in a release might take a long time. That's assuming they'd accept the change.

I strongly disagree that this isn't a bug, though.

**Comment by zlobz** [comment] 2016-06-10 20:20
@aprescott +1
It's unsafe to use the same string object in multiple tests, because an application or Rails can modify the string object.
