### ISSUE TITLE
[Rails 7.1.3] async_find_by_sql needs promise.value.value ?!

### ISSUE THREAD

**Issue by OskarEichler** [rails/rails#50980] opened 2024-02-06 03:06 UTC
### Steps to reproduce
When calling async_find_by_sql since upgrading from Rails 7.1.2 to Rails 7.1.3 the promise no longer returns it's result when calling .value, but instead we need to call .value twice, in order to actually get the values.

### Expected behavior
promise.value should return the result.

### Actual behavior
Since Rails 7.1.3 need to call promise.value.value instead.

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.2.1

**Comment by skipkayhil** [comment] 2024-02-06 04:24
Duplicate of #50776, fixed in #50778

**Closed by skipkayhil** 2024-02-06 04:24 UTC
