### ISSUE TITLE
Scopes behaviour change?

### ISSUE THREAD

**Issue by caiammm** [rails/rails#29445] opened 2017-06-13 21:29 UTC
### Steps to reproduce

download this project https://github.com/caiammm/test_rails_5_scopes
you can see the nested scopes in https://github.com/caiammm/test_rails_5_scopes/blob/master/app/models/course.rb

It doesn't work anymore in rails 5.0.3

you can run in rails console 
`Course.scope_multiple_things`

### Expected behavior

It should work like in rails 4.1.14.1, returning the relation
`SELECT "courses".* FROM "courses" INNER JOIN "universities" ON "universities"."id" = "courses"."university_id" WHERE ("courses"."id" BETWEEN 1 AND 300) AND "courses"."enabled" = 't' AND "universities"."enabled" = 't'`

### Actual behavior
It doesn't work
`SELECT "courses".* FROM "courses" INNER JOIN "universities" ON "universities"."id" = "courses"."university_id" WHERE ("courses"."id" BETWEEN 1 AND 300) AND "courses"."enabled" = 't' AND "universities"."enabled" = `

The last parameter for `universities.enabled` in the end of string is missing

### System configuration
**Rails version**:
the new one 5.0.3
the old one 4.1.14.1

**Ruby version**:
ruby 2.2.3p173

**Comment by che-burashco** [comment] 2017-06-23 00:37
I was able to reproduce the bug. Looking at the exact point where it was introduced in the code. I know for sure that 4-2-stable definitely has it as well

**Comment by che-burashco** [comment] 2017-06-23 14:48
I've tracked the problem down and I think I have a solution ready, just need to cover it with tests. Looks like the 'non_conflicting_binds(other)' method in ActiveRecord::Relation::WhereClause is rejecting all the bind clauses with the same name, disregarding the table they were supposed to be bound to. Hence, if you have two tables with the same attribute and you try to merge the where clauses applied to both of them in the same scope it leads to an incorrect query, since there will be only one bind left at the end, instead of two

**Comment by savroff** [comment] 2017-06-27 22:37
@che-burashco any success?

**Comment by che-burashco** [comment] 2017-06-28 15:13
@savroff I have a fix ready. Just need to run all the tests. Should be able to wrap it up in a pull request tonight.

**Comment by che-burashco** [comment] 2017-06-29 14:39
Hm, interesting, one of the test cases for the pull request on the CI has failed. I think it's the order of the test execution, because the same test fails on master if I use the right seed even for 2.4.1. I will look at it a bit later.

**Comment by caiammm** [comment] 2017-07-06 14:04
@che-burashco Thank you so much for taking this bug seriously.

**Comment by che-burashco** [comment] 2017-07-06 14:13
@caiammm no worries. It was a part that was missed at a certain point when the 5.0 was coded. The failing tests are not related directly to the change that I made, since they happen for particular seeds even when no changes are applied. And it's related to the fact that the postgres adapter runs this piece of code in schema_statements.rb:
`def schema_search_path
  @schema_search_path ||= select_value("SHOW search_path", "SCHEMA")
end`

It stores an additional statement in the QueryCache if the schema_search_path variable is null, which leads to the test failure.

Unfortunately, I think the PR is not going to be code reviewed until all the tests are passing, and I didn't have much time over the weekend to look at it. So I will need a bit of more time to figure out which particular sequence of tests leads to a failure

**Comment by eugeneius** [comment] 2017-07-06 15:56
The flaky query cache tests were fixed in https://github.com/rails/rails/pull/29634 - if you rebase your branch they should pass.

**Comment by che-burashco** [comment] 2017-07-06 17:10
@eugeneius oh, amazing. Thanks. Will do it later on today

**Comment by kamipo** [comment] 2017-09-04 16:10
Fixed by 213796f.

**Closed by kamipo** 2017-09-04 16:10 UTC
Labels: activerecord
