### ISSUE TITLE
Actioncable disconnects every time a file change in development

### ISSUE THREAD

**Issue by jbescoyez** [rails/rails#39975] opened 2020-08-03 09:29 UTC
### Steps to reproduce
* `git clone git@github.com:jbescoyez/cable-test.git` (a minimal actioncable implementation)
* `rails s`

* Go to: `http://localhost:3000/chats/new` and open the console
* `touch app/controllers/application_controller.rb ` (or any other file)
* Go back to: `http://localhost:3000/chats/new` and "Create a chat"

### Expected behavior
The new "chat" would appear in the list above the input.

### Actual behavior
Nothing appears and we can see that the WebSocket is disconnected in the console (it would reconnect a few seconds later).

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.7.0p0

**Comment by composerinteralia** [comment] 2020-08-15 07:24
Thank you for the issue! The behavior you are describing is expected in development.

Whenever a file gets changed [Rails reloads your application](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#introduction) to pick up those changes. One of the things it needs to do as it reloads the application is [restart the Action Cable server](https://github.com/rails/rails/blob/40b7d93c5bf04974cfd0201a8e391c499c046f0b/actioncable/lib/action_cable/engine.rb#L73-L75) so it is running with the new version of the code. This does take a few seconds, but it is hopefully still faster than manually restarting the server.

It is possible to opt out of reloading by setting `config.cache_classes = true`. If you do that then you will need to manually restart the server to pick up any code changes you make.

Since this is the expected behavior, I am going to close this issue.

**Closed by composerinteralia** 2020-08-15 07:24 UTC
