### ISSUE TITLE
AR any? behaves erratically in conjunction with polymorphic associations

### ISSUE THREAD

**Issue by fosterfarrell9** [rails/rails#33625] opened 2018-08-15 18:07 UTC
It appears that the `any?` method of ActiveRecord behaves erratically in some some situations where polymorphic associations are involved. 

### Steps to reproduce

Set up the following minimal working example.
https://github.com/fosterfarrell9/anytrouble

I am very sorry that I was not able to find a smaller example. 

### Explanation of the example
It basically consists of a model  `Medium` which is in a polymorphic association to `Teachable`, which is one of `Course`, `Lecture`, `Lesson`. Among these three, there are one-to-many-relations: a lesson belongs to a lecture, a lecture belongs to a course. There is a `course` method on any of these that that returns the corresponding course. The database is sparsely poulated: There is one entry for `Course`, one entry for `Lecture` (which belongs to the single course) and one entry for `Medium`; its teachable is the single lecture.
The problem occurs if you use the `any?` method on `Medium` if you want to find out if there is a Medium whose course is the single course.

### Expected behavior

```
Medium.any? { |m| m.teachable.course == Course.first }
```
should be `true`.

### Actual behavior

If you start a fresh rails console and execute the above request, it returns 
`nil`. If you execute it again, it always return the correct value `true`.

```
2.5.1 :001 > Medium.any? { |m| m.teachable.course == Course.first }
  Medium Load (0.3ms)  SELECT "media".* FROM "media"
  Lecture Load (0.1ms)  SELECT  "lectures".* FROM "lectures" WHERE "lectures"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Course Load (0.1ms)  SELECT  "courses".* FROM "courses" WHERE "courses"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Course Load (0.1ms)  SELECT  "courses".* FROM "courses" ORDER BY "courses"."id" ASC LIMIT ?  [["LIMIT", 1]]
 => nil
2.5.1 :002 > Medium.any? { |m| m.teachable.course == Course.first }
  Medium Load (0.3ms)  SELECT "media".* FROM "media"
  Lecture Load (0.3ms)  SELECT  "lectures".* FROM "lectures" WHERE "lectures"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Course Load (0.3ms)  SELECT  "courses".* FROM "courses" WHERE "courses"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Course Load (0.2ms)  SELECT  "courses".* FROM "courses" ORDER BY "courses"."id" ASC LIMIT ?  [["LIMIT", 1]]
 => true
```

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Database adapter**: sqlite3 (version 3.24.0)

### Remark
If you use `Medium.all.to_a.any?` instead of `Medium.any?` the problem disappears.

**Comment by georgeclaghorn** [comment] 2018-08-15 18:51
One of our programmers has seen this in Basecamp on Rails master. Strangely, it only happens to him. Others can’t reproduce it.

Further details:
* It affects all Enumerable methods: `select`, `detect`, `any?`, etc.
* It happens exactly 20% of the time.
* We ruled out Spring.
* We ruled out a modified or corrupted checkout of Rails.
* We use MySQL.

**Comment by blechereyal** [comment] 2018-09-03 16:37
Stumbled upon this too on rails: `5.1.6`, ruby: `2.5.1p57` without any polymorphic association

* Details

- happens only when associated record is not preloaded/eager loaded or joined with
  ```
  # Wrong
  Client.some_scope.any? { |client| a.associated_model; true } => nil
  # Ok
  Client.some_scope.any? { |client| true } => true
  Client.some_scope.includes(:associated_model).any? { |a| a.associated_model; true } => true
  ```
- The query for the associated model is run even for the first line of code

**Comment by kaungst** [comment] 2018-09-05 01:25
Same issue as @georgeclaghorn only we're using PostgreSQL, rails: `5.2`, ruby: `2.5.1p57`

**Comment by gwincr11** [comment] 2018-09-07 17:31
This appears to be an issue with Enumerable in Ruby 2.5.1. I have a forked version at https://github.com/gwincr11/anytrouble using Rails 2.4.2 and the issue goes away.

**Comment by gwincr11** [comment] 2018-09-07 19:07
Yeah, I just dug through the active record code. The [any?](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L266) method passes blocks to super, after checking in pry it is going to `Enumerable#any?`. This was [introduced three years ago](https://github.com/rails/rails/commit/b644964b2b555798fc4b94d384b98438db863b3f) and has been stable.

<img width="642" alt="screen shot 2018-09-07 at 3 01 10 pm" src="https://user-images.githubusercontent.com/289882/45238136-d016aa00-b2ae-11e8-9bd9-8de50cbd5564.png">

The any? method in Ruby was updated with 2.5.0, I think this maybe the pr that causes the issue? https://github.com/ruby/ruby/commit/a9770bac6375c9d4ff8ba8bb1842841aec7c59e3

**Comment by tenderlove** [comment] 2018-09-10 22:29
I've been able to reproduce the error consistently:

```ruby
def raises_thing
  raise Exception
rescue Exception
end

def test
  all = Medium.all
  all.any? { |m|
    raises_thing
    true
  }
end

p test # => nil
p test # => nil
```

The first time we call this it has to resolve the constant.  Rails calls `safe_constantize` with the string `"Lecture::Course"` which raises an exception.  The second time we don't need to do that anymore, so we don't get a `nil`.  Seems like something about raising an exception ruins the optimization introduced in the commit above.

**Comment by tenderlove** [comment] 2018-09-10 23:10
I [reduced the app surface area](https://github.com/tenderlove/anytrouble), but strangely I can't reproduce this outside of the app yet.

**Comment by tenderlove** [comment] 2018-09-10 23:32
I was able to reproduce this outside of the application.  It looks like something to do with the bindex gem.

```ruby
require "active_record"
require "securerandom"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ':memory:'
ActiveRecord::Migration.verbose = false

ActiveRecord::Schema.define do
  create_table :media, force: true do |t|
    t.timestamps null: false
  end
end

class Medium < ActiveRecord::Base; end

Medium.create!

def raise_thing
  raise Exception
rescue Exception
end

if ENV['BINDEX']
  require "bindex"
end

x = Medium.all
p Medium.all.any? { raise_thing; true }
```

When I run this:

```
[aaron@TC-183 rails (master)]$ be ruby -I../bindex/lib benchmark.rb 
true
[aaron@TC-183 rails (master)]$ BINDEX=1 be ruby -I../bindex/lib benchmark.rb 
nil
```

**Comment by tenderlove** [comment] 2018-09-10 23:59
Just going to summarize what I've found so far (I want to stop working on this today).  Changing [this delegate method `:each`](https://github.com/rails/rails/blob/3000c1490565b3a21376d6444cb6fe24dfe4e383/activerecord/lib/active_record/relation/delegation.rb#L41) to `def each; records.each { |x| yield x }; end` will fix it, but `def each(&block); records.each(&block); end` will continue to exhibit the behavior.  This is further proof for me that the lazy proc optimization is to blame (the first one won't be lazy but the second will).

Removing [these callback internals in bindex](https://github.com/gsamokovarov/bindex/blob/e910a2efae7be47afac952b19685c09ce672674a/ext/bindex/cruby.c#L10-L22) don't impact the program, but eliminating [this call](https://github.com/gsamokovarov/bindex/blob/e910a2efae7be47afac952b19685c09ce672674a/ext/bindex/cruby.c#L28) does.  Seems like there's a problem with `rb_debug_inspector_open` in combination with the lazy proc optimization.

**Comment by tenderlove** [comment] 2018-09-11 18:40
@gwincr11 and I were able to reduce this to use Ruby without Rails or bindex:

```ruby
require "fiddle"

def raise_thing
  raise Exception
rescue Exception
end

class MyRelation
  include Enumerable

  def each(&block)
    records.each(&block)
  end

  def records
    [1]
  end
end

callback = Class.new(Fiddle::Closure) {
  def call x, y
    Fiddle.dlwrap(Object.new)
  end
}.new(Fiddle::TYPE_VOIDP, [Fiddle::TYPE_VOIDP, Fiddle::TYPE_VOIDP])

function_address = Fiddle::Handle::DEFAULT["rb_debug_inspector_open"]
func = Fiddle::Function.new(function_address,
                            [Fiddle::TYPE_VOIDP, Fiddle::TYPE_VOIDP],
                            Fiddle::TYPE_VOIDP)

tp = TracePoint.new(:raise) { |_| func.call(callback, callback) }

tp.enable

y = MyRelation.new
p y.any? { raise_thing; true }
```

It's definitely something to do with the Ruby debug API.  I'll look in to it more.  I guess the good news is this isn't a bug in Rails!

As a work around, removing `web-console` will fix the app.  Also I guess this means that it's probably not broken in production. 😄

**Comment by tenderlove** [comment] 2018-09-11 21:57
I filed a ticket with a smaller repro [here](https://bugs.ruby-lang.org/issues/15105).  I'll try to work on it later, but I think we can close this for now (as it's a Ruby bug and not a Rails bug).

**Closed by tenderlove** 2018-09-11 21:57 UTC
