### ISSUE TITLE
Rails db migrations fails with multiple databases when an activerecord object is called.

### ISSUE THREAD

**Issue by freibuis** [rails/rails#46733] opened 2022-12-15 02:03 UTC
### Steps to reproduce

when setting the multiple database connections from the model for users like such
```ruby
class User < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: {
    writing: :primary,
    reading: :primary
  }
end
```
 any migration that calls the ActiveRecord model closes the DB connection when it is called from within a migration
 
 this is a terrible example  create col, display column_names, remove col
  ```ruby
  def up
    add_column :users, :fielda, :string

    puts User.column_names   # fails when `User` model class is used 

    remove_column :uses, :fieldb
  end
  ```
  at the point when the `User` class is ever used the connection closes and any further calls to the database are closed and `ActiveRecord::ConnectionNotEstablished: connection is closed` message is returned on further migrations
  
  if you comment the `connects_to database: ` from the model, the migrations work when using a single database connection correctly.

### Expected behavior
`connects_to database: ` method on ActiveRecord model  should not drop connections to the database in migrations when using the ActiveRecord model in the migration

### System configuration
tested on 7.0.3 / 7.0.4

**Ruby version**:
3.1.2

**Comment by eileencodes** [comment] 2022-12-15 14:00
I am pretty sure this was fixed by https://github.com/rails/rails/pull/45450. I can't reproduce on main with my demo app. If it's not fixed on 7-0-stable I will you need you provide a reproduction.

As a note connecting to the same database twice does not make sense, it just wastes max possible connection to mysql. Either the reading connection should be it's own replica database or it should be removed from the `connects_to` call.

**Comment by eileencodes** [comment] 2022-12-15 15:23
I also just realized your connection class and model is set up wrong. The class that establishes the connection cannot be a model you are running migrations against. Each separate connection should have an abstract class that the models belonging to that database inherit from. The default `ApplicationRecord` should contain the connection for your main, primary database if it exists. Otherwise you are overwriting the default connection established by `ActiveRecord::Base`. This is all in the multi-db [guides](https://guides.rubyonrails.org/active_record_multiple_databases.html). 

So your application set up should be like this.

```ruby
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  connects_to database: { writing: :primary, reading: :primary_replica }
end

class User < ApplicationRecord
end

class OtherRecord < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :other_record, reading: :other_record_replica }
end

class SomethingInOtherRecord < OtherRecord
end
```

I'm going to close this because I am confident the database setup being incorrect is the issue. The reason you don't see this without `connects_to` is because in that case you are not overwriting the existing `ActiveRecord::Base` connection that's established on boot by the Railtie

**Closed by eileencodes** 2022-12-15 15:23 UTC
