### ISSUE TITLE
Test fixtures don't raise ReadonlyError when using replica connection

### ISSUE THREAD

**Issue by 8398a7** [rails/rails#37765] opened 2019-11-21 13:01 UTC
### Steps to reproduce

I created a repository to check the behavior because it was difficult to move with the prepared template.
https://github.com/8398a7/multidb_sample

I have confirmed that the problem can be reproduced with the current master(7dbee78c386e0833b5f6691776e395f7286ce38e).

The essence of the problem is that the replica information is overwritten in the test environment and `ActiveRecord :: ReadOnlyError` does not occur.
https://github.com/rails/rails/blob/7dbee78c386e0833b5f6691776e395f7286ce38e/activerecord/lib/active_record/test_fixtures.rb#L189-L203

When use_transactional_tests is true, you can see that the actual database destination cannot be a replica.
However, I want `ActiveRecord :: ReadOnlyError` to be raised correctly.

```ruby
require_relative 'boot'

require 'rails/all'

Bundler.require(*Rails.groups)

module MultidbSample
  class Application < Rails::Application
    config.load_defaults 6.0

    config.active_record.database_selector = { delay: 0.seconds }
    config.active_record.database_resolver = ActiveRecord::Middleware::DatabaseSelector::Resolver
    config.active_record.database_resolver_context = ActiveRecord::Middleware::DatabaseSelector::Resolver::Session
  end
end

Rails.application.routes.draw do
  resources :counters, only: [] do
    collection do
      get :get_counter
      post :post_counter
    end
  end
end

class CountersController < ApplicationController
  def get_counter
    @counter = Counter.first
    @counter.update!(count: @counter.count + 1)
  end

  def post_counter
    @counter = Counter.first
    @counter.update!(count: @counter.count + 1)
  end
end
```

If there is code like the above, accessing get_counters will raise `ActiveRecord :: ReadOnlyError`.
However, when you write a test like this, the exception is not detected.

```ruby
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'

require File.expand_path('../config/environment', __dir__)

abort('The Rails environment is running in production mode!') if Rails.env.production?
require 'rspec/rails'
begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end
RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true
  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!
end

require 'rails_helper'

RSpec.describe CountersController, type: :request do
  let(:counter) { Counter.create! }
  context 'post' do
    it 'post request' do
      counter
      post '/counters/post_counter'
    end
  end
  context 'get' do
    it 'get request' do
      counter
      get '/counters/get_counter'
    end
  end
end
```

I'm sorry for the rspec example because I'm not familiar with minitest, but I want an exception to occur in the get request case.
This also has the same problem when the connection destination is changed with `connected_to`.

```ruby
ActiveRecord::Base.connected_to(role: :reading) do 
  Hoge.create!
end
```

Such mistakes are usually noticed in reviews, but can be overlooked if they are deep.
And I want to avoid disabling `use_transactional_tests` from the point of test execution time to notice this problem.
I would be very happy if you could consider it!

### Expected behavior

```ruby
require 'rails_helper'

RSpec.describe CountersController, type: :request do
  let(:counter) { Counter.create! }
  context 'post' do
    it 'post request' do
      counter
      post '/counters/post_counter'
    end
  end
  context 'get' do
    it 'get request' do
      counter
      expect { get '/counters/get_counter' } .to raise_error ActiveRecord::ReadOnly
    end
  end
end
```

### Actual behavior

There is no exception.

### System configuration
**Rails version**: master(7dbee78c386e0833b5f6691776e395f7286ce38e)

**Ruby version**: 2.6.5

**Comment by eileencodes** [comment] 2019-11-21 20:13
Hey @8398a7 I am looking at this bug but you didn't include any instructions about how to reproduce with the app you provided or the error you're seeing. 

When I run your app's tests locally I get `NoMethodError: undefined method `count' for nil:NilClass` but I don't think that's the error you're reporting here.

Thanks!

**Comment by 8398a7** [comment] 2019-11-21 23:18
I'm sorry. I didn't list the steps to reproduce.
You can reproduce it by running `bundle exec rspec`.

**Comment by Edouard-chin** [comment] 2019-11-22 02:41
Easiest solution to unblock you is to add `config.active_record.database_selector = { delay: -1.seconds }` inside the `environments/test.rb` file so that Rails will read from the primary connection all the time (that's what it does anyway since we share connection between master and replica as you saw) and it will prevents writes.


Not sure how we can fix this in the framework, we'd have to stop sharing connection between master ->replica. Maybe we can modify the transaction isolation level https://github.com/rails/rails/blob/3f1473379ce3eafc6f8a9912a7c4fb410745cac6/activerecord/lib/active_record/test_fixtures.rb#L126 🤔

**Comment by eileencodes** [comment] 2019-11-22 14:35
> You can reproduce it by running bundle exec rspec.

I tried this and all the tests pass.

**Comment by 8398a7** [comment] 2019-11-22 15:08
The `get request` executed by this rspec is a test that writes at the time of get, so it should not be passed, but it is a problem.

**Comment by 8398a7** [comment] 2019-11-23 09:52
I sent PR to your repository to reproduce the problem.
https://github.com/eileencodes/recipes_app/pull/5

When accessing in the development environment, ActiveRecord :: ReadOnly error occurs.
![cap](https://user-images.githubusercontent.com/8043276/69476836-4c4ccd00-0e22-11ea-9bfb-811c9060a3e4.gif)
However, the test cannot detect this problem.
https://github.com/eileencodes/recipes_app/blob/master/test/controllers/cakes_controller_test.rb#L26-L29

**Comment by eileencodes** [comment] 2019-11-25 15:45
Ok I see the problem now. You need to tell the app to use the writing role. Since this is a get request and the connection switching middleware is installed, Rails will (correctly) assume that you want to only read.

If you always want to update while reading you'll need to add a `connected_to` block inside the show method.

```ruby
def show
  ActiveRecord::Base.connected_to(role: :writing)
    @cake.update!(cake_type: @cake.cake_type + 1)
  end
end
```

Since this is behaving correctly and isn't a bug I'm going to close this PR. Let me know if you hit other issues.

**Comment by 8398a7** [comment] 2019-11-25 23:12
@eileencodes 
No, I don't want to write in get method. The content of PR is an example for a simple understanding of the nature of the problem.

What I feel bugs through the example is that ActiveRecord::ReadOnlyError does not occur if it is a test environment.
The point that I want to solve is that there is a risk of exception problems that cannot be reproduced in a test environment and that occur in production environment.

**Comment by eileencodes** [comment] 2019-11-26 01:10
@8398a7 please make an example, with clear steps, how to reproduce the problem you are seeing.

**Comment by 8398a7** [comment] 2019-11-26 01:16
@eileencodes 
https://github.com/eileencodes/recipes_app/pull/5

Although the procedure described above is updated in the GET method, no exception occurs in test.
Is this an example of how to reproduce the problem?

I think this is because the `config[:replica]` attribute disappears when doing `pool_manager.set_pool_config (: default, writing_pool_config)` in setup_shared_connection_pool.

**Comment by kamipo** [comment] 2019-11-26 01:35
I think one possible way to test query to replica is suppressing the effect of `enlist_fixture_connections` (or  `setup_shared_connection_pool`) in the `TestCase` class.

See also https://github.com/rails/rails/pull/34773#discussion_r252124180.

**Comment by 8398a7** [comment] 2019-11-26 01:46
I understand that `use_transactional_tests` must be false for tests that actually connect to replicas.
Currently, `config[:replica]` is lost because it is overwritten including meta information in `setup_shared_connection_pool`.

Is it possible to handle `ActiveRecord::ReadOnlyError` on the rails side by leaving the information of `config[:replica]` before overwriting?
It uses a writer transaction but `config[:replica] = true` so `ActiveRecord::ReadOnlyError` was expecting behavior to occur.
If you can't handle on the rails side, it will be difficult to solve the problem.

**Comment by kamipo** [comment] 2019-11-26 02:51
I suppose there is no official way to test query to replica for now, probably we need to fix to only do the overwrite when when transactional fixtures are enabled. https://github.com/rails/rails/pull/34773#discussion_r252130411

**Comment by kamipo** [comment] 2019-11-26 02:58
oh does `self.use_transactional_tests = false` works now? If so is it not enough to use that?

**Comment by 8398a7** [comment] 2019-11-26 03:10
The reason I want to raise `ActiveRecord::ReadOnlyError` in the test environment is mainly because I want to notice human mistakes with the integration test.
A simple example is as follows:

```ruby
class UsersController < ApplicationController
  def show
    @user_json = User.find(params[:id]).some_json
  end
end

class User < ApplicationRecord
  def some_json
    update!(reference_count: reference_count + 1)
    {...}
  end
end
```

This is a really terrible example, but real-world apps can have side-effect problems with more complex backgrounds.
I think that there are cases where side effects occur only under specific conditions and are detected only during production, not at the time of development.

To deal with this human mistake, the review should be perfect or all tests should have `self.use_transactional_tests = false`.
I understand that you can use `self.use_transactional_tests = false` in a test that you want to connect to a replica, but I wanted to avoid using `self.use_transactional_tests = false` in every test to prevent human error.

**Comment by eileencodes** [comment] 2019-11-26 15:00
Ok @8398a7In the future please add an assertion that fails (an `assert_raises ActiveRecord::ReadOnlyError ` would have been sufficient to reproduce). That would have avoided the back and forth because the problem you're seeing would have been clear to me.

I will think about how to fix this problem now that I understand what the bug is. I'm also going to update the title so others who experience this can find the report more easily.

**Comment by eileencodes** [comment] 2019-11-26 23:36
I don't see an easy way to fix this. I thought about merging `replica: true` into the writing config for that pool but this works because the pool is the same, we can't access the config, make a new pool, and get the effect we need.

The underlying problem is how transactions work in tests. They don't commit records so we have to share a connection between writing and reading, otherwise you won't be able to write and read on different connection roles. I'm not sure there's a straightforward way to fix this yet.

**Comment by 8398a7** [comment] 2019-11-27 09:28
I am sorry that the method of reproduction is bad...

https://github.com/Edouard-chin/rails/commit/bb9e83e1b462f89ff8a1517a2721e7a8e5ff78b8
I think the above commit is an effective way to solve the problems I reported.
But changing the transaction isolation level is a major change.
Changing this may break existing tests.
However, the problem that data does not flow when connected to an actual replica is also solved.

I thought it would be nice to be able to easily change the isolation level and stop sharing connections as well.

**Closed** 2020-01-10 16:15 UTC
Labels: activerecord
