### ISSUE TITLE
Rails 5.0.0beta2: Weird behaviour of config belongs_to_required_by_default

### ISSUE THREAD

**Issue by nflorentin** [rails/rails#23589] opened 2016-02-10 09:00 UTC
I'm facing a weird issue with the new config **belongs_to_required_by_default**

## In first app

created with rails 5.0.0beta1 and updated to 5.0.0beta2, I have in initializers/active_record_belongs_to_required_by_default.rb:
`Rails.application.config.active_record.belongs_to_required_by_default = true`

In rails console:
```
> Rails.application.config.active_record.belongs_to_required_by_default
=> true
> ActiveRecord::Base.belongs_to_required_by_default
=> nil
> User.belongs_to_required_by_default
=> nil
```

If I replace `Rails.application.config.active_record.belongs_to_required_by_default = true` with `ActiveRecord::Base.belongs_to_required_by_default = true`, **all work as expected** and I get my associations validated.

After the replacement, I get in console:
```
> Rails.application.config.active_record.belongs_to_required_by_default
=> nil
> ActiveRecord::Base.belongs_to_required_by_default
=> true
> User.belongs_to_required_by_default
=> true
```

## In second app

freshly created with rails 5.0.0beta2, with `Rails.application.config.active_record.belongs_to_required_by_default = true`.

In rails console:
```
> Rails.application.config.active_record.belongs_to_required_by_default
=> true
> ActiveRecord::Base.belongs_to_required_by_default
=> true
> User.belongs_to_required_by_default
=> true
```

**Comment by nflorentin** [comment] 2016-02-10 09:46
Just find that installing **friendly_id**, only adding it in gemfile, was the reason of this issue.
I think I can close this one.
I open an [issue](https://github.com/norman/friendly_id/issues/730) on friendly_id repo.

**Comment by sandfoxme** [comment] 2016-05-23 16:45
Rails 5.0.0.rc1, same issue, no friendly_id

**Comment by jeremy** [comment] 2016-05-23 17:18
This is due to initialization order. Any plugin that loads AR will cause it to pull config to AR::Base so subsequent initializers will be too late in the game to take effect.

Try setting this in config/application.rb instead or setting `ActiveRecord::Base.belongs_to_required_by_default = true` instead of `Rails.application.config.active_record.belongs_to_required_by_default`.

**Comment by sandfoxme** [comment] 2016-05-23 20:48
@jeremy thanks! But default rails initializer should be changed accordingly then so it won't confuse people in this situation

**Comment by jeremy** [comment] 2016-05-23 20:59
Agree @sandfoxme. Up for submitting a PR?

**Comment by sandfoxme** [comment] 2016-05-23 22:45
@jeremy ok, maybe tomorrow

**Comment by sandfoxme** [comment] 2016-05-25 22:02
Actually I'm confused on how to fix this. Just changing initializer to `ActiveRecord::Base.belongs_to_required_by_default = true` seems not good enough

p.s. and the issue should be reopened

**Comment by lleger** [comment] 2016-06-23 21:39
This issue bit me today after upgrading to RC2. Setting `ActiveRecord::Base.belongs_to_required_by_default` solved the issue for me. When I upgraded, I removed `config/initializers/active_record_belongs_to_required_by_default.rb` in favor of `config/initializers/new_framework_defaults.rb`. Adding that file back and simply setting `Rails.application.config.active_record.belongs_to_required_by_default` also solved the issue. In my mind that supports the "initialization order" issue. Happy to work on a PR to help this if anyone has thoughts on where to start.

**Comment by lleger** [comment] 2016-06-23 21:44
In my case, specifically, it seems like the Devise initializer caused the issue. Moving it to the bottom of the order (`z_devise.rb`) alleviated the issue.

**Comment by rafaelfranca** [comment] 2016-06-23 22:40
While I agree that we can fix this issue it is more a plugin/gem not playing nice with the rails hooks. I'll take care of fixing it in devise and if you can try to find which gem/plugin is doing it please open an issue.

**Comment by lukeredpath** [comment] 2016-06-24 14:39
Also ran into this issue (I think its this issue) when installing the `paranoia` gem:
https://github.com/rubysherpas/paranoia/issues/335

Narrowed it down to the fact that it is re-opening ActiveRecord::Base.

I suppose the question is where should this issue be fixed? Should gems not being re-opening ActiveRecord::Base? Should this be fixed in Rails?

**Comment by lukeredpath** [comment] 2016-06-24 14:51
My current preferred workaround for this issue, if caused by a gem, is to disable auto-require in your Gemfile:

```ruby
gem 'paranoia', require: false
```

Create a new initialiser in which you require any libraries that re-open ActiveRecord

```ruby
# z_paranoia.rb
require 'paranoia'
```

This ensures that it gets loaded after the configuration is set.

**Comment by rafaelfranca** [comment] 2016-06-29 03:32
> I suppose the question is where should this issue be fixed? Should gems not being re-opening ActiveRecord::Base? Should this be fixed in Rails?

This should be fixed in the gems.

There is no problem in re-opening `ActiveRecord::Base` but they need to do in the right way.

See https://github.com/plataformatec/devise/commit/c2c74b0a39238e7d997486814a1c8f75fdaf276f on how they should be doing this.

**Comment by sandfoxme** [comment] 2016-06-29 12:44
Many gems re-open ActiveRecord::Base so I think there should be at least bad behavior detection with a warning, otherwise we have incorrect state without any clear sign of it

**Comment by wlipa** [comment] 2016-08-12 21:38
Should we not refer to model classes in initializers (to reference constants, e.g.)?  Doing so in an early initializer seems to break active_record_belongs_to_required_by_default as well.

**Comment by rafaelfranca** [comment] 2016-08-12 23:39
> Should we not refer to model classes in initializers (to reference constants, e.g.)?

It is not recommended, no. This not just breaking the hooks but also can connect to database when you should not be connecting.

**Comment by rafaelfranca** [comment] 2016-08-12 23:41
> I think there should be at least bad behavior detection with a warning, otherwise we have incorrect state without any clear sign of it

:+1:. This is something that we should have. If you want please submit a pull request.

I'm closing since this is no much we can do here.

**Closed by rafaelfranca** 2016-08-12 23:41 UTC
Labels: activerecord, railties

**Comment by jeromedalbert** [comment] 2016-08-26 11:21
At the time of writing I have 3 gem dependencies that cause this problem in my current project (`ahoy`, `cancancan` and `delayed_job_active_record`).

After reporting the issues, I found that in the meantime the simplest way to hack around this problem is to include the line
```ruby
config.active_record.belongs_to_required_by_default = true
```
directly in `application.rb`. Not ideal at all of course, but just FYI in case someone has the same problem and needs to get going.

**Comment by roberts1000** [comment] 2016-10-26 23:22
Great info.  I just hit this tonight on an app that was migrated to Rails 5.  I agree that it's not necessarily a Rails issue, but it's a little concerning that gems can corrupt Rails 5 apps so easily.   I'll likely end up explicitly adding `required: true` or `optional: true` with every `belongs_to` call to guard against some gem reverting Rails to Rails 4 behavior (and leaving some data unprotected).  I like this approach a little better than moving the config line to application.rb since it's currently not the recommended location.   Explicitly using `required: true` or `optional: true` has the added benefit of making intention clear to other developers.

**Comment by ivanovaleksey** [comment] 2017-06-01 15:50
In my case this is happening with [ransack](https://github.com/activerecord-hackery/ransack/issues) gem.

**Comment by jeromedalbert** [comment] 2017-06-01 17:06
For anyone still having a problem with this, Rails 5.1 has removed the clunky `new_framework_defaults.rb`, and has now the following `application.rb` code:

```ruby
module BananaApp
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.1

    ...
```

The `config.load_defaults 5.1` line is the equivalent of the old `new_framework_defaults` content, which among other things does `Rails.application.config.active_record.belongs_to_required_by_default = true`. Since this config is now done in `application.rb`, it solves any problem in the current issue.

So if you want to keep "the Rails way" and solve this problem, just upgrade to 5.1 and have `config.load_defaults 5.1` in your application.rb.

I am happy that this problem was solved on the Rails side, this was the right way to solve all of this.

**Comment by ivanovaleksey** [comment] 2017-06-01 20:08
@jeromedalbert thank you for the reply. Right now I can update application only to 5.0.3. 
What is the best solution in this case? Manually move `active_record.belongs_to_required_by_default = true` to `application.rb`?

**Comment by jeromedalbert** [comment] 2017-06-01 20:19
That would be an equivalent solution yeah

**Comment by p8** [comment] 2019-07-08 16:47
To find out which gem is calling ActiveRecord add the following line to config/application.rb before `Bundler.require(*Rails.groups)`:
```
  ::ActiveRecord = 1
```

**Comment by akostadinov** [comment] 2021-08-20 10:55
To figure out where issue comes from, better follow advice in https://github.com/rails/rails/issues/39855#issuecomment-659670294 and similar for ActiveJob https://github.com/rails/rails/issues/37030#issuecomment-524487416

Basically `ActiveSupport.on_load(:active_job) { puts caller }` and possibly some `puts` calls to see at which point some particular initializer is being executed.
