### ISSUE TITLE
undefined method `alias_method_chain' for ActionController::Base:Class

### ISSUE THREAD

**Issue by arshekas** [rails/rails#46705] opened 2022-12-12 19:56 UTC
Hi,

We have updated our rails app from rails 4.2.6 to rails 5.2.5 and ruby version from 2.3.0 to 2.6.6, we have changed the code according to here [https://gist.github.com/anklos/eb0088e26223c92a034cd1ea36fcee2c](https://gist.github.com/anklos/eb0088e26223c92a034cd1ea36fcee2c). However, when we run the application we are getting this error somewhere from application.rb 

code from application.rb where erroring out

```
require File.expand_path('../boot', __FILE__)

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups). **THIS LINE GIVING ERROR**
```

Error
```
`block in <module:ControllerHelper>': undefined method `alias_method_chain' for ActionController::Base:Class (NoMethodError)
Did you mean?  alias_method
```

Any help would be appreciated!

Thanks

**Comment by nvasilevski** [comment] 2022-12-12 20:26
Is there a stacktrace available for the exception? As Eileen pointed out in a different in another issue, it is unlikely caused by Rails and most likely called from one of the gems. Similar to https://github.com/rails/rails/issues/46660#issuecomment-1341003874

You can look through the source for Rails 5.2.5 https://github.dev/rails/rails/tree/cb0a558f42fc6957fac4d2daa16771b72ff7da6e and see that nothing in Rails 5.2.5 is calling `alias_method_chain`
<img width="332" alt="image" src="https://user-images.githubusercontent.com/5512772/207147273-ac1b7376-07dd-4426-a93f-1dcaa8d35364.png">

Based on a very similar issue, usually stacktrace should point to the code that is still using removed `alias_method_chain` method

**Comment by eileencodes** [comment] 2022-12-13 14:33
Closing because this isn't a bug in Rails, 5.2 removed all calls to alias_method_chain so it's the app or another gem.

**Closed by eileencodes** 2022-12-13 14:33 UTC
