### ISSUE TITLE
ActiveStorage DiskService directory sharding

### ISSUE THREAD

**Issue by dmke** [rails/rails#39405] opened 2020-05-23 19:29 UTC
### Steps to reproduce

1. Setup ActiveStorage with "disk service" as described here: https://guides.rubyonrails.org/active_storage_overview.html#disk-service
2. Create an attachment. Observe the path to the blob (`RAILS_ROOT/storage/ab/cd/abcdef...`).
3. Create a variant. Observe the path to the variant (`RAIL_ROOT/storage/va/ri/variants/abcdef...`)

### Expected behavior

I'd expected variants to be directory-sharded properly as well; the should reside in `RAILS_ROOT/storage/variants/ab/cd/abcdef...` (or similar).

### Actual behavior

(All) variants reside directly in `RAILS_ROOT/storage/va/ri/variants/`, defeating the directory-sharding.

### System configuration

- **Rails version**: all versions since Rails 5.2
- **Ruby version**: independent of Ruby

I've identified `ActiveStorage::Service::DiskService#folder_for` ([5-2-stable, (`eb3f1e2`)](https://github.com/rails/rails/blob/eb3f1e2/activestorage/lib/active_storage/service/disk_service.rb#L135-L137), [6-0-stable (`779029d`)](https://github.com/rails/rails/blob/779029d/activestorage/lib/active_storage/service/disk_service.rb#L143-L145), [master (`2e15092`)](https://github.com/rails/rails/blob/2e15092/activestorage/lib/active_storage/service/disk_service.rb#L148-L150)) to be the culprit, which independent of the shape of the `key` parameter, returns the first two 2-character-pairs:

```ruby
folder_for("variants/abcdef...") #=> "va/ri"
```

A simple (?) fix ought to change behavior of `#folder_for` to leave the `variants/` prefix alone:

```ruby
folder_for("abcdef...") #=> "ab/cd"
folder_for("variants/abcdef...") #=> "variants/ab/cd"
```

with a naïve implementation being:

```diff
 def folder_for(key)
+  if key.start_with? "variants/"
+    [ "variants", key[9..10], key[11..12] ].join("/")
+  else
     [ key[0..1], key[2..3] ].join("/")
+  end
 end
```

(I've not tested this yet, so I don't know if this breaks something else).

### Other Notes

I've posted this [last year to rubyonrails-talk](https://groups.google.com/d/msg/rubyonrails-talk/L-dJHtWL-Jo/pOcqoymeBgAJ) (the [import to Discourse](https://discuss.rubyonrails.org/t/q-activestorage-diskservice-directory-sharding/73662) butchered the formatting a bit), forgot about this, found the "May Of WTFs" and thought, I'd revive this properly.

I haven't noticed any performance problems with this setup yet, but the largest project using this only contains 6500 attachments with 7500 variants in total.

Also, as mentioned in the post: changing this would not solve the issue for existing setups, as they'd still have potentially thousands of variants still residing in `RAILS_ROOT/storage/va/ri/variants/`. This might or might not be a problem: I've considered the variants directory to be ephemeral, so deleting and regenerating should only cost CPU time (and potentially a few users waiting for their images to appear). Depending on the access rates though, this could mean a *prohibitive* amount of CPU usage...

**Comment by georgeclaghorn** [comment] 2020-05-24 01:49
Duplicate of #38985, where the conclusion was that variant tracking (#37901) indirectly fixes this by making variants blobs in their own right.

On review, that’s maybe not the most satisfying conclusion, since it implies you need to either manually migrating existing variants or blow them away and let them be recreated…but I agree that variants should be treated as ephemeral and safe to throw away and recreate, as you said.

**Closed by georgeclaghorn** 2020-05-24 01:49 UTC

**Comment by dmke** [comment] 2020-05-25 07:16
Cool, thank you.

If I'm reading the changelog correctly, this is scheduled for inclusion in 6.1, right? Also, for prosperity's sake, how would a safe migration path look like?

Would this work?

1. Upgrade to Rails 6.1, leave `config.active_storage.track_variants = false`.
2. Create `active_storage_variant_records` table.
3. Iterate over `Blob`s and their known variants (i.e. extract a list of variant parameters from the views or wherever variants are referenced):
  - compute the variant's digest,
  - if `RAILS_ROOT/storage/va/ri/variants/$digest` exist:
    - copy/hard-link `RAILS_ROOT/storage/va/ri/variants/$digest` to `RAILS_ROOT/storage/$digest[0,2]/$digest[2,2]/$digest`,
    - create a variant record
4. Set `config.active_storage.track_variants = true`.
5. Nuke `RAILS_ROOT/storage/va/ri/variants/`.

My open questions for now:
- How do I access the transformation digest, given a `Blob` instance and a transformation hash?
- Does `VariantWithRecord.find_or_create_by!(blob_id: $blob_id, digest: $digest)` suffice for "creating a variant record"?
