### ISSUE TITLE
update_all no longer uses ActiveRecord model ID 

### ISSUE THREAD

**Issue by leejarvis** [rails/rails#25875] opened 2016-07-18 13:31 UTC
### Steps to reproduce

Create a new rails project with Search `has_many` User. Try to `update_all(user_id: User.last)`. On v4.2 the attribute will be updated as expected, on v5.0 it will not. Using the ID directly works as expected.

Rails 4.2

```
[3] pry(main)>
[3] pry(main)> Rails.version
=> "4.2.5.2"
[4] pry(main)> Search.last.user
  Search Load (1.0ms)  SELECT  "searches".* FROM "searches"  ORDER BY "searches"."id" DESC LIMIT 1
=> nil
[5] pry(main)> Search.update_all(user_id: User.last)
  User Load (0.7ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
  SQL (9.2ms)  UPDATE "searches" SET "user_id" = 3
=> 183
```

```
>> Rails.version
=> "5.0.0"
>> Search.last.user
  Search Load (6.9ms)  SELECT  "searches".* FROM "searches" ORDER BY "searches"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> nil
>> Search.update_all(user_id: User.last)
  User Load (1.0ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
  SQL (16.8ms)  UPDATE "searches" SET "user_id" = NULL
=> 183
>> Search.update_all(user_id: User.last.id)
  User Load (1.3ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
  SQL (16.2ms)  UPDATE "searches" SET "user_id" = 3
=> 183
```

### Expected behaviour

`update_all(x_id: x)` should infer the `id` attribute from an ActiveRecord model instance (`x`) as it does in version 4.2.

### Actual behavior

The SQL generated from `update_all` will simply do `SET "x_id" = NULL` unless you explicitly return the `id` attribute `update_all(x_id: x.id)`

### System configuration
**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by sgrif** [comment] 2016-07-18 13:34
See also: https://twitter.com/lee_jarvis/status/755027870649647104

I'm not sure that this is actually expected to work, but from a cursory glance at the code it looks like it should be working, so I'm going to take a brief look into it

**Comment by sgrif** [comment] 2016-07-18 13:36
Also for future reference, providing a reproduction script using [our standard bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) is extremely helpful.

**Comment by leejarvis** [comment] 2016-07-18 13:42
Oh sorry I hadn't seen that. Just for completeness, here it is:

```ruby
#!/usr/bin/env ruby

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_update_all
    comment = Comment.create!
    post    = Post.create!

    Comment.update_all(post_id: post)

    assert_equal post, comment.reload.post
  end
end
```

**Comment by sgrif** [comment] 2016-07-18 13:45
So it looks like this was the result of a change that was made to increase consistency. You'll note that if you were to do `Comment.new(post_id: Post.last)`, it would also assign to `nil`. However, there is code that more or less is meant to make this work (granted, it has `# TODO: deprecate this` above it), so I'll restore this behavior for 5.0.1 (deprecated to be removed in 5.1)

**Comment by sgrif** [comment] 2016-07-18 13:59
Fixed by #25876 (I'm closing this manually instead of through the PR, as that commit won't end up in master so Github won't close the issue)

**Closed by sgrif** 2016-07-18 13:59 UTC
Labels: activerecord

**Comment by leejarvis** [comment] 2016-07-18 14:06
Thanks! ✨

**Comment by stadniklksndr** [comment] 2018-03-30 08:27
Test script above passed successfully only for 5-0-stable.
If it's possible to backport [commit](https://github.com/rails/rails/pull/25876/commits/7c106aefd687b02a941a20400156b7d5f2841948) to 5-2-0 too

**Comment by Zyphrax** [comment] 2018-03-30 11:38
@stadniklksndr I see that @sgrif wrote that this functionality was going to be deprecated in Rails 5.1, because it was never officially supported. The functions like `update_all` are meant for raw database changes with minimal Rails interference. It would probably be best to change the calls to `update_all`. Would be great though if the method could pass some kind of warning or error when a complex object is passed, but that might negatively impact performance.
