### ISSUE TITLE
A bug around ActiveSupport.to_time_preserves_timezone

### ISSUE THREAD

**Issue by kirs** [rails/rails#26644] opened 2016-09-27 20:37 UTC
### Steps to reproduce

I swear that I tried to create a single file script to reproduce the issue, but I couldn't.
Here is the instruction [as well as a repo with complete app with a failing test](https://github.com/kirs/rails_to_time_preserves_timezone_bug).

1. `bundle exec railties/exe/rails new ../events_blog_five --dev --skip-turbolinks --skip-action-cable --skip-sprockets`
2. `rails g model event happened_at:datetime `
3. Apply the diff:

```diff
diff --git a/config/application.rb b/config/application.rb
index 8ce1279..f67478a 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -21,5 +21,6 @@ module EventsBlogFive
     # Settings in config/environments/* take precedence over those specified here.
     # Application configuration should go into files in config/initializers
     # -- all .rb files in that directory are automatically loaded.
+    config.time_zone = "Eastern Time (US & Canada)"
   end
 end
diff --git a/config/initializers/new_framework_defaults.rb b/config/initializers/new_framework_defaults.rb
index 0b910f7..a2a9f60 100644
--- a/config/initializers/new_framework_defaults.rb
+++ b/config/initializers/new_framework_defaults.rb
@@ -12,7 +12,8 @@ Rails.application.config.action_controller.forgery_protection_origin_check = tru
 
 # Make Ruby 2.4 preserve the timezone of the receiver when calling `to_time`.
 # Previous versions had false.
-ActiveSupport.to_time_preserves_timezone = true
+# Disable for reproducing purposes
+# ActiveSupport.to_time_preserves_timezone = true
 
 # Require `belongs_to` associations by default. Previous versions had false.
 Rails.application.config.active_record.belongs_to_required_by_default = true
diff --git a/test/fixtures/events.yml b/test/fixtures/events.yml
new file mode 100644
index 0000000..5b96641
--- /dev/null
+++ b/test/fixtures/events.yml
@@ -0,0 +1,4 @@
+one:
+  happened_at: 2016-05-02 11:00:00
+two:
+  happened_at: 2016-05-02 11:00:00
diff --git a/test/models/event_test.rb b/test/models/event_test.rb
new file mode 100644
index 0000000..457a410
--- /dev/null
+++ b/test/models/event_test.rb
@@ -0,0 +1,8 @@
+require 'test_helper'
+
+class EventTest < ActiveSupport::TestCase
+  test "tz" do
+    times = Event.all.map(&:happened_at).sort.map { |n| n.to_s(:long) }
+    assert_equal ["May 02, 2016 07:00", "May 02, 2016 07:00"], times
+  end
+end
```

4. Run the test with `TZ=UTC rails test test/models/event_test.rb`. Output:

```ruby
Failure:
EventTest#test_tz [/Users/kir/Projects/opensource/events_blog_five/test/models/event_test.rb:6]:
--- expected
+++ actual
@@ -1 +1 @@
-["May 02, 2016 07:00", "May 02, 2016 07:00"]
+["May 02, 2016 07:00", "May 02, 2016 11:00"]
```

### Expected behavior

That the `happened_at` values will be equal, as described in fixtures.

### Actual behavior

Second value is mutated: `["May 02, 2016 07:00", "May 02, 2016 11:00"]`

### System configuration
**Rails version**: today's master (`21ecf42730de2004a95d913038c1f417c24496be`)

**Ruby version**: `ruby 2.3.1p112`

this is probably related to https://github.com/rails/rails/commit/c9c5788a527b70d7f983e2b4b47e3afd863d9f48
cc @pixeltrix

**Comment by sgrif** [comment] 2016-09-27 20:44
Important to note that removing the `.sort` causes the issue to go away, which is what landed us on the `.to_time` change as relevant.

**Comment by pixeltrix** [comment] 2016-09-28 07:00
@sgrif removing the `sort` gives `["May 02, 2016 07:00", "May 02, 2016 07:00"]` ? That implies the `sort` is mutating the time values somehow - weird. I'll have a look today.

**Comment by pixeltrix** [comment] 2016-09-28 07:20
Hmm, can't reproduce with Rails 5.0.0.1 which suggest that c9c5788 isn't the direct cause - will see what's changed in master that might be relevant.

**Comment by pixeltrix** [comment] 2016-09-28 07:28
Looks like the cause is actually 3132fa6 - don't know why yet.

**Comment by pixeltrix** [comment] 2016-09-28 08:49
God I'm stupid - we can't cache `getlocal` because you can call it with different utc_offsets. I assume that sort must be calling `getlocal` via `<=>` somehow (with utc_offset = nil or 0). Then `AS::TWZ#strfitime` calls `getlocal` with the utc_offset of -14400 (EDT) and 💥 .

Options are:

1. Remove the cache (pros: easy, cons: slow)
2. Use a hash to cache getlocal by utc_offset (pros: fast, cons: threading issues?)
3. Make `strftime` use `utc.getlocal` (pros: easy, cons: doesn't fix underlying problem)

Obvious 3 is a non-starter, so the choice is between 1 and 2. Do we need use a threadsafe Concurrent::Hash for the implementation if we go with 2?

**Comment by rafaelfranca** [comment] 2016-09-28 17:07
We only need a threadsafe cache if the cache is at the class level. But 2 seems good to me

**Comment by tbalthazar** [comment] 2016-10-01 09:16
I've created a simple script that reproduces the `sort` bug and narrows it down to the `localtime` method, as explained by @pixeltrix.
I'm gonna fix the issue by using a hash to cache `getlocal` (as suggested by @pixeltrix) and add some tests.

``` ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem 'activesupport', :git => 'git://github.com/rails/rails.git', :ref => '21ecf42730de2004a95d913038c1f417c24496be'
end

require "active_support"
require "active_support/time"
require "minitest/autorun"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  def test_localtime_caching
    tz = ActiveSupport::TimeZone["Eastern Time (US & Canada)"]
    twz = ActiveSupport::TimeWithZone.new(nil, tz, Time.utc(2016,5,2,11))

    assert_equal "2016-05-02 11:00:00 -0400", twz.to_s
    assert_equal "2016-05-02 13:00:00 -0200", twz.localtime(-7200).to_s
    assert_equal "2016-05-02 14:00:00 -0100", twz.localtime(-3600).to_s
  end

  def test_sort_time_with_zone
    times = []
    tz = ActiveSupport::TimeZone["Eastern Time (US & Canada)"]
    twz = ActiveSupport::TimeWithZone.new(nil, tz, Time.utc(2016,5,2,11))
    times << twz
    times << twz

    times = times.sort.map { |t| t.to_s(:long) }
    expected = ["May 02, 2016 11:00", "May 02, 2016 11:00"]

    assert_equal expected, times
  end
end
```

**Closed** 2016-10-01 20:30 UTC
Labels: activesupport, attached PR
