### ISSUE TITLE
Can't set HABTM association: Validation failed: Left side must exist

### ISSUE THREAD

**Issue by masciugo** [rails/rails#21041] opened 2015-07-27 18:00 UTC
I am using rails 5, cloned today from master. It seems I cannot update habtm association in very basic examples. I have 2 models:

    class User < ActiveRecord::Base
      has_and_belongs_to_many :projects
    end

    class Project < ActiveRecord::Base
      has_and_belongs_to_many :users
    end

I always got `ActiveRecord::RecordInvalid: Validation failed: Left side must exist` whenever I try to update the association. [Here](https://github.com/masciugo/test_habtm) is a sample application with some failing tests:

**/test/models/user_test.rb**

    require 'test_helper'

    class UserTest < ActiveSupport::TestCase
      test "assign habtm by objects" do
        john = User.find_by(name: 'john')
        john.projects = Project.all
        assert_equal 2, john.projects.count
      end
      test "assign habtm by ids" do
        john = User.find_by(name: 'john')
        john.project_ids = Project.ids
        assert_equal 2, john.projects.count
      end
      test "assign habtm by inserting" do
        john = User.find_by(name: 'john')
        john.projects << Project.first
        assert_equal 1, john.projects.count
      end
      test "assign habtm by creating" do
        john = User.find_by(name: 'john')
        proj = john.projects.build(title: 'yo')
        proj.save
        assert_equal 1, john.projects.count
      end
    end

and this is the output:

    masciugo@macbookpro ~/dev/test_habtm $ bin/rake test
    Run options: --seed 60643

    # Running:

    EEFE

    Finished in 0.153089s, 26.1287 runs/s, 6.5322 assertions/s.

      1) Error:
    UserTest#test_assign_habtm_by_objects:
    ActiveRecord::RecordInvalid: Validation failed: Left side must exist
        test/models/user_test.rb:6:in `block in <class:UserTest>'

      2) Error:
    UserTest#test_assign_habtm_by_ids:
    ActiveRecord::RecordInvalid: Validation failed: Left side must exist
        test/models/user_test.rb:11:in `block in <class:UserTest>'

      3) Failure:
    UserTest#test_assign_habtm_by_creating [/Users/masciugo/dev/test_habtm/test/models/user_test.rb:23]:
    Expected: 1
      Actual: 0

      4) Error:
    UserTest#test_assign_habtm_by_inserting:
    ActiveRecord::RecordInvalid: Validation failed: Left side must exist
        test/models/user_test.rb:16:in `block in <class:UserTest>'

    4 runs, 1 assertions, 1 failures, 3 errors, 0 skips

    Failed tests:

    bin/rails test test/models/user_test.rb:4
    bin/rails test test/models/user_test.rb:9
    bin/rails test test/models/user_test.rb:19
    bin/rails test test/models/user_test.rb:14

**Comment by masciugo** [comment] 2015-07-27 18:29
Creating a purchase with some player ids gives me instead a different error but I guess correlated. It seem as it wrongly infers the join table name which exists as `player_purchases` and it works (i.e. I can retrieve purchase with associated players) when manually populated:

    irb(main):013:0> Player.all
      Player Load (0.3ms)  SELECT `players`.* FROM `players`
    => #<ActiveRecord::Relation [#<Player id: 13, name: "cor", ledger_id: 8, created_at: "2015-07-27 16:59:03", updated_at: "2015-07-27 16:59:03">, #<Player id: 14, name: "ste", ledger_id: 8, created_at: "2015-07-27 16:59:03", updated_at: "2015-07-27 16:59:03">]>
    irb(main):014:0> l.purchases.create(name: 'benz', amount: 60, payer_id: 13, player_ids: [13,14])
       (0.3ms)  BEGIN
      Player Load (0.4ms)  SELECT `players`.* FROM `players` WHERE `players`.`id` IN (13, 14)
       (0.2ms)  ROLLBACK
    NoMethodError: undefined method `purchases_players' for #<Purchase:0x007f9a991ca7b0>
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activemodel/lib/active_model/attribute_methods.rb:433:in `method_missing'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activemodel/lib/active_model/errors.rb:464:in `generate_message'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activemodel/lib/active_model/errors.rb:480:in `normalize_message'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activemodel/lib/active_model/errors.rb:312:in `add'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activerecord/lib/active_record/autosave_association.rb:339:in `association_valid?'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activerecord/lib/active_record/autosave_association.rb:319:in `block in validate_collection_association'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activerecord/lib/active_record/autosave_association.rb:319:in `each'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activerecord/lib/active_record/autosave_association.rb:319:in `validate_collection_association'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activerecord/lib/active_record/autosave_association.rb:218:in `block in define_autosave_validation_callbacks'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activerecord/lib/active_record/autosave_association.rb:157:in `instance_eval'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activerecord/lib/active_record/autosave_association.rb:157:in `block in define_non_cyclic_method'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/callbacks.rb:430:in `block in make_lambda'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/callbacks.rb:166:in `call'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/callbacks.rb:166:in `block (2 levels) in halting'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/callbacks.rb:601:in `call'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
    ... 50 levels...
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/railties/lib/rails/commands/console_helper.rb:9:in `start'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/railties/lib/rails/commands/commands_tasks.rb:69:in `console'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/railties/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/railties/lib/rails/commands.rb:18:in `<top (required)>'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/dependencies.rb:302:in `require'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/dependencies.rb:302:in `require'
      from /Users/masciugo/dev/quenta-api/bin/rails:8:in `<top (required)>'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/dependencies.rb:296:in `load'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/dependencies.rb:296:in `block in load'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-40ce686b5732/activesupport/lib/active_support/dependencies.rb:296:in `load'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      from /Users/masciugo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      from -e:1:in `<main>'irb(main):015:0>

**Comment by masciugo** [comment] 2015-07-28 08:47
I added another test which shows something interesting: 

    test "assign habtm by params" do
      paul = User.new(name: 'paul', project_ids: Project.ids)
      paul.save
      assert_equal 2, john.projects.count
    end

and the output:

      5) Error:
    UserTest#test_assign_habtm_by_params:
    NoMethodError: undefined method `users_projects' for #<User id: nil, name: "paul", created_at: nil, updated_at: nil>
        test/models/user_test.rb:27:in `block in <class:UserTest>'

It looks for `users_projects`. Shouldn't it be `projects_users` like the default join table name?

**Comment by pixeltrix** [comment] 2015-07-28 09:36
I've created a single file test that seems to pass on master:

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new('/dev/null')

ActiveRecord::Schema.define do
  create_table :projects  do |t|
    t.string :name
  end

  create_table :users  do |t|
    t.string :name
  end

  create_join_table :projects, :users
end

class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
end

class User < ActiveRecord::Base
  has_and_belongs_to_many :projects
end

class Issue21041Test < Minitest::Test
  def setup
    @user = User.create! name: 'John'
    @project_foo = Project.create! name: 'Project Foo'
    @project_bar = Project.create! name: 'Project Bar'
    @projects = [@project_foo, @project_bar]
  end

  def teardown
    User.delete_all
    Project.delete_all
  end

  def test_assign_habtm_by_objects
    @user.projects = Project.all
    assert_equal 2, @user.projects.count
  end

  def test_assign_habtm_by_ids
    @user.project_ids = Project.ids
    assert_equal 2, @user.projects.count
  end

  def test_assign_habtm_by_inserting
    @user.projects << Project.first
    assert_equal 1, @user.projects.count
  end

  def test_assign_habtm_by_creating
    @user.projects.create(name: 'Project Baz')
    assert_equal 1, @user.projects.count
  end

  def test_assign_habtm_by_attributes
    @user.update! project_ids: Project.ids
    assert_equal 2, @user.projects.count
  end
end
```

can you see what's the difference in your application that's causing yours to fail?

**Comment by masciugo** [comment] 2015-07-28 14:19
@pixeltrix  your script works for me too, but my very basic [example app](https://github.com/masciugo/test_habtm) still fails. The only difference I see is that it was created with the --api switch, so I also tried without it but same errors. I did very very few steps to build it from scratch so I don't really know where I got wrong. Sorry If I can't provide more than a dummy test app.

**Comment by lsgpimentel** [comment] 2015-07-28 17:55
I'm still receiving the same error, as describe in this SO topic: http://stackoverflow.com/questions/31279978/activerecordrecordinvalid-validation-failed-left-side-must-exist

**Comment by pixeltrix** [comment] 2015-07-28 18:56
Okay, I've worked out why there's a difference - it's because of the option `belongs_to_required_by_default`. Changing this from true to false makes the tests work, however I'm not sure why the `require: true` option on the `belongs_to` associations for the join model are failing because both models do exist. I'll keep digging.

**Comment by pixeltrix** [comment] 2015-07-28 20:01
Hmm, looks like the one of the `belongs_to` associations on the constructed join model isn't pointing to the right column so is seen as nil. Previously this wasn't a problem but since we require `belongs_to` associations by default now it blows up. The easy fix is just to put `optional: true` on the `:left_side` association when it's constructed but I think we can do better than that :smile:

**Comment by masciugo** [comment] 2015-07-29 07:47
👍

**Comment by denniss** [comment] 2015-08-12 16:55
I was able to reproduce the error by starting a new rails app.... but I just tried creating a failing test for it under rails and it's passing...... 

https://github.com/denniss/rails/commit/df5f6bc6fc1c51ed17ae2a8077470dc1b782d87d

**Comment by smeade** [comment] 2015-09-09 08:11
@pixeltrix - Verifying that as you noted, the errors occur when `belongs_to_required_by_default` is true.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'
  gem 'byebug'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new('/dev/null')
ActiveRecord::Base.belongs_to_required_by_default = true

ActiveRecord::Schema.define do
  create_table :projects  do |t|
    t.string :name
  end

  create_table :users  do |t|
    t.string :name
  end

  create_join_table :projects, :users
end

class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
end

class User < ActiveRecord::Base
  has_and_belongs_to_many :projects
end

class Issue21041Test < Minitest::Test
  def setup
    @user = User.create! name: 'John'
    @project_foo = Project.create! name: 'Project Foo'
    @project_bar = Project.create! name: 'Project Bar'
    @projects = [@project_foo, @project_bar]
  end

  def teardown
    User.delete_all
    Project.delete_all
  end

  def test_assign_habtm_by_objects
    @user.projects = Project.all
    assert_equal 2, @user.projects.count
  end

  def test_assign_habtm_by_ids
    @user.project_ids = Project.ids
    assert_equal 2, @user.projects.count
  end

  def test_assign_habtm_by_inserting
    @user.projects << Project.first
    assert_equal 1, @user.projects.count
  end

  def test_assign_habtm_by_creating
    @user.projects.create(name: 'Project Baz')
    assert_equal 1, @user.projects.count
  end

  def test_assign_habtm_by_attributes
    @user.update! project_ids: Project.ids
    assert_equal 2, @user.projects.count
  end
end
```

results in:
`5 runs, 0 assertions, 0 failures, 5 errors, 0 skips`
https://gist.github.com/smeade/41a910e0b7a2f5ac0c1e

**Comment by sgrif** [comment] 2015-10-29 22:54
Gah forgot to mention in the commit message. Fixed by https://github.com/rails/rails/commit/21a386bb0726cce4f4a5d64d55fbb55d8a2b9837

**Closed by sgrif** 2015-10-29 22:54 UTC
Labels: activerecord, Important
