### ISSUE TITLE
Why bin/test command not working?

### ISSUE THREAD

**Issue by daitranthanhhoa** [rails/rails#32942] opened 2018-05-21 04:46 UTC
### Steps to reproduce
Run bin/test command
'bin' is not recognized as an internal or external command, operable program or batch file.

http://guides.rubyonrails.org/plugins.html

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**: 5.2

**Ruby version**:2.5

**Comment by utilum** [comment] 2018-05-21 09:34
I can't reproduce this locally.

Did you complete step 1, `cd` into the 'yaffle' directroy, successfully run `bundle install` and failed trying `bin/test` in [step 2](http://guides.rubyonrails.org/plugins.html#testing-your-newly-generated-plugin)?

What OS are you using?

**Comment by daitranthanhhoa** [comment] 2018-05-21 09:57
Yes, i using win 7, 32bit

**Comment by daitranthanhhoa** [comment] 2018-05-21 11:26
thank you. it can't run by cmd, but it can run from terminal of aptana is ok.

**Comment by utilum** [comment] 2018-05-21 11:32
If the issue is resolved, would you like to close it?

**Closed** 2018-05-21 11:36 UTC
