### ISSUE TITLE
dependent: :restrict_with_error not working properly

### ISSUE THREAD

**Issue by stephanngamedev** [rails/rails#24526] opened 2016-04-12 18:37 UTC
### Steps to reproduce
```ruby
class Blog < ActiveRecord::Base
	has_many :users, dependent: :destroy
end

class User < ActiveRecord::Base
	has_many :posts, dependent: :restrict_with_error
end

class Post < ActiveRecord::Base
	belongs_to :user
end

class BugTest < Minitest::Test
	def test_dependent_destroy
		blog = Blog.create!

		user = blog.users.create!

		post = user.posts.create!

		user.destroy
		assert_equal true, user.errors[:base].any? #ok

		blog.destroy #throw a exception here =(
		assert_equal true, blog.errors[:base].any?
	end
end
```
File for testing: https://gist.github.com/stephanngamedev/1944e2c78895ecac577af1f43c74543f

### Expected behavior
`blog.destroy` should add an error on blog object, 

### Actual behavior
But it is throwing an exception

### System configuration
**Rails version**: 4.2.5.1

**Ruby version**: 2.3.0

**Comment by vipulnsward** [comment] 2016-04-12 18:59
Its setting the error on `blog.users.first.errors`

**Comment by stephanngamedev** [comment] 2016-04-12 19:11
but it's throwing an expection. The line `assert_equal true, blog.errors[:base].any?` was not executed. The same occurs on my controller

**Comment by vipulnsward** [comment] 2016-04-12 19:18
Looks like this was fixed on master- https://gist.github.com/vipulnsward/c6bb0b7b740b6a8d85c9f55d6dc42c34

I can see it raise on 4.2

**Comment by vipulnsward** [comment] 2016-04-12 19:18
@stephanngamedev can you see if this works for you on master?

**Comment by stephanngamedev** [comment] 2016-04-12 19:51
Tomorrow I show the results on master, I'm going home

**Comment by vipulnsward** [comment] 2016-04-19 21:15
Going to give this a close, since its fixed on master. @stephanngamedev please reopen if you see this even with https://gist.github.com/vipulnsward/c6bb0b7b740b6a8d85c9f55d6dc42c34 on master.

**Closed by vipulnsward** 2016-04-19 21:15 UTC
Labels: activerecord

**Comment by kkarski82** [comment] 2017-07-24 09:01
I've had similar issue in Rails 5.0.3 (it's not throwing an exception but it isn't adding an error to the object either). I've found out that it is caused by the order of relations listed in the object (you should put restricts before other cascades that might fail on children).
