### ISSUE TITLE
includes with string columns break - undefined method 'first' for nil:NilClass - ActiveRecord

### ISSUE THREAD

**Issue by mujtaba-saboor** [rails/rails#42669] opened 2021-07-01 15:36 UTC
### Steps to reproduce
`Arel.includes(:association_name)` gives an error if the joining columns of both the tables are String, and one of the columns has the same string but empty spaces in it. 

In my case I had two models `user.rb` and `assets.rb`. In `asset.rb` I had an association:
```ruby
has_one  :last_detected_user, foreign_key: :email, primary_key: :candidate_email, class_name: 'User'
```
and when I call
```ruby
assets.includes(:last_detected_user)
```
It gives `NoMethodError: undefined method 'first' for nil:NilClass`. 
The reason behind this is that I had a row in assets where for example 
`asset.candidate_email => "mutjaba@github.com  "`(note the empty space at the end)
and it's corresponding user:
`user.email => "mujtaba@github.com"`

### Expected behavior
It was expected that if Rails joined `asset.candidate_email => "mutjaba@github.com        "`(with spaces at the end) to `user.email => "mujtaba@github.com"`, it should also let `includes` work.

### Actual behavior
But even though Rails joined `"mujtaba@github.com   "` to `"mujtaba@github.com"` the logic in file `activerecord-6.0.3.2/lib/active_record/associations/preloader/association.rb`
```ruby
owner = owners_by_key[convert_key(record[association_key_name])].first
```
breaks and causes an error `NoMethodError: undefined method 'first' for nil:NilClass`

### System configuration
**Rails version**:
Rails 6.0.3.2
**Ruby version**:
ruby 2.7.1p83

### My suggestion
This is the original code in `activerecord-6.0.3.2/lib/active_record/associations/preloader/association.rb`
```ruby
def owners_by_key
  @owners_by_key ||= owners.each_with_object({}) do |owner, result|
    key = convert_key(owner[owner_key_name])
    (result[key] ||= []) << owner if key
  end
end
```

changing it to this would fix the problem
```ruby
def owners_by_key
  @owners_by_key ||= owners.each_with_object({}) do |owner, result|
    key = convert_key(owner[owner_key_name])
    key = key.strip if key.instance_of?(String)
    (result[key] ||= []) << owner if key
  end
end
```

**Comment by alexcameron89** [comment] 2021-07-01 16:58
Hey @mujtaba-saboor, I'm not sure that we'd expect the behavior of stripping spaces from a string for association queries in the first place. I created a reproducible test script just to verify, and I don't see that the `:last_detected_user` would return the record either, which is the behavior I'd expect.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :email
  end

  create_table :assets, force: true do |t|
    t.string :candidate_email
  end
end

class Asset < ActiveRecord::Base
  has_one  :last_detected_user, foreign_key: :email, primary_key: :candidate_email, class_name: 'User'
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    asset = Asset.create!(candidate_email: "mutjaba@github.com ")
    user = User.create!(email: "mujtaba@github.com")

    assert Asset.all.includes(:last_detected_user)
    assert_equal user, asset.last_detected_user
  end
end
```

I may be misunderstanding the issue that you're seeing, so can you either verify that the script I provided accurately represents your issue or provide a similar script so that we can run it and understand the issue you're having?

**Comment by mujtaba-saboor** [comment] 2021-07-02 12:13
Hey @alexcameron89 I'm using MySQL as my database, in my case empty space is saved to the database, for example 
```ruby
asset = Asset.create!(candidate_email: "mutjaba@github.com   ")
```
would assign email with empty space, but in your case, it is changed to `"mutjaba@github.com" and then saved.


My question is why does Rails join `candidate_email =>  'mutjaba@github.com     '` with `email => 'mutjaba@github.com'`. The two strings are separate in length. I agree I should've saved `candidate_email` without trailing spaces and that's something I've fixed in my workflow by calling `candidate_email.strip` before saving, but, nonetheless it is an issue at Rails end.

**Comment by mujtaba-saboor** [comment] 2021-07-02 12:57
I've debugged it further, I've found that MySQL collation `utf8mb4_0900_ai_ci` removes trailing spaces before saving string type columns, whereas, I have collation `utf8_unicode_ci`. Can you retry your script with column collation set to `utf8_unicode_ci`? It will allow you to save strings with trailing whitespace and that is when the issue arises.

**Comment by alexcameron89** [comment] 2021-07-02 16:14
Thank you for the additional information, that was very helpful. It looks like the same issue came up in the past twice: 
- 2014 - https://github.com/rails/rails/issues/15539
- 2020 - https://github.com/rails/rails/issues/39672

It also looks like the error itself has been fixed in `main` from https://github.com/rails/rails/pull/41385, although it is not a part of any versions yet. Now the `first for nil::NilClass` error won't raise, but the preloading still won't return the record. As you showed in the original issue description, the issue arises from the comparisons happening in Ruby vs. the DB. 

Given that not all DB's treat padding the same way (nor do the many Collations provided by MySQL), I don't think dealing with it in the code seems like an ideal solution, following similar feedback from the members on the past two tickets. Pixeltrix did mention adding a warning for cases of using foreign keys with case-insensitive collations:
>  PRs for better warnings that can be given without affecting runtime performance are always welcome. 👍

Since the error itself has been fixed on `main`, and since he has addressed the issue on a ticket with the same issue (https://github.com/rails/rails/issues/39672), I'm going to close this as a duplicate of that ticket. If you'd like to discuss adding a warning for these case, feel free to mention it on that ticket and I'll re-open it or open a PR to have that discussion.

**Closed by alexcameron89** 2021-07-02 16:14 UTC
