### ISSUE TITLE
Dependency on mimemagic 0.3.x no longer valid

### ISSUE THREAD

**Issue by pedantic-git** [rails/rails#41750] opened 2021-03-24 12:02 UTC
The gem mimemagic (see https://github.com/minad/mimemagic/issues/97 & https://github.com/minad/mimemagic/issues/98 ) has resolved a licensing issue today by yanking all builds prior to 0.4.0, but Rails itself (activestorage) has a dependency on `mimemagic (~> 0.3.2)`.

Would it be possible to release new patches of 6.1 (and others?) that relax this dependency to include 0.4.x?

### Steps to reproduce

Attempt to install any version of Rails!

### Expected behavior

Gem will install

### Actual behavior

> Your bundle is locked to mimemagic (0.3.5), but that version could not be found
> in any of the sources listed in your Gemfile. If you haven't changed sources,
> that means the author of mimemagic (0.3.5) has removed it. You'll need to update
> your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
> in order to install.

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 3.0.0

**Comment by pedantic-git** [comment] 2021-03-24 12:05
This is no longer a breaking issue because the maintainer of mimemagic has released a compatible version called 0.3.6, but the dependency probably still should be updated! https://github.com/minad/mimemagic/issues/98

**Comment by morgoth** [comment] 2021-03-24 12:06
Also, please note that the mimemagic gem is now on GPL2 license https://github.com/minad/mimemagic/commit/c0f7b6b21a192629839db87612794d08f9ff7e88

**Comment by minad** [comment] 2021-03-24 12:10
See my comment here: https://github.com/minad/mimemagic/issues/98#issuecomment-805768643

> Note that the GPL-2.0 license may not be desirable under all circumstances. If there is interest in the alternative approach proposed in #97 (reading the freedesktop.xml file at startup) and someone prepares a PR a new version could be released under the MIT license again.

**Comment by minad** [comment] 2021-03-24 13:05
For now I decided to archive the project. The last released versions are 0.3.6 and 0.4.0 released under the GPL-2.0.

**Comment by pedrofurtado** [comment] 2021-03-24 13:06
I did not understand the root cause of yanked versions, but what is the solution for this scenario? Force everyone in the world to upgrade to 0.3.6? I will ask this in mimemagic repo, but the repo was archived (that I also not understand why was archived). Crazy day! 😆

**Comment by coding-bunny** [comment] 2021-03-24 13:06
How will this affect projects running older Rails versions?
E.g Commercial legacy projects etc?

**Comment by gberdugo** [comment] 2021-03-24 13:09
> I did not understand the root cause of yanked versions, but what is the solution for this scenario? Force everyone in the world to upgrade to 0.3.6? I will ask this in mimemagic repo, but the repo was archived (that I also not understand why was archived). Crazy day!

I think so

> How will this affect projects running older Rails versions?
> E.g Commercial legacy projects etc?

I'm not a lawyer, but in my understanding, the mimemagic change to GPL licence forces rails to be distributed in GPL also, which forces all projects that are using Rails to be open-sourced

**Comment by jellybob** [comment] 2021-03-24 13:09
Updating to 0.4.x would be a substantial issue for many people, as it will result in a GPL2 dependency being pulled in, which a large proportion of companies have policies against using.

**Comment by coding-bunny** [comment] 2021-03-24 13:10
yeah GPL definitely is not an option for us.

**Comment by minad** [comment] 2021-03-24 13:16
The best way forward is probably to create a version of the gem which is licensed under the MIT license and loads the mime database at startup. This is the approach proposed by the maintainer of shared-mime-info, see https://github.com/minad/mimemagic/issues/97.

**Comment by nicholalexander** [comment] 2021-03-24 13:22
does someone want to take on or self nominate setting up some official fork and license change that rails can use?  i would volunteer but not sure what the rails team might want to do with this...

**Comment by minad** [comment] 2021-03-24 13:24
@nicholalexander If the rails teams nominates an official maintainer, please notify me. Then we can also arrange the takeover process for the gem at rubygems.org

**Comment by jk779** [comment] 2021-03-24 13:28
I don't want to party poop but because [0.3.6](https://rubygems.org/gems/mimemagic/versions/0.3.6) is already GPL-2 which brings everybody in a sticky situation right now i guess...

**Comment by coding-bunny** [comment] 2021-03-24 13:29
I'm willing to help out/contribute, but will need some good explanation on what the possibilities are that can be done to remedy this problem correctly. Although I'd rather see the solution in the hands of the Rails team

**Comment by olafura** [comment] 2021-03-24 13:30
Another solutions is to use: https://pagure.io/mailcap/blob/master/f/mime.types like https://github.com/elixir-plug/mime

Seems to be under Public Domain from Redhat, derives from http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by erran** [comment] 2021-03-24 13:31
> I don't want to party poop but because 0.3.6 is already GPL-2 which brings everybody using rails in a sticky situation right now i guess...

👍🏽 Since @minad is a fan of yanking gems maybe they’ll yank the GPL-2 license as a non-breaking gem version since it poisons the license for anyone using rails too as far as I can tell.

**Comment by minad** [comment] 2021-03-24 13:32
@olafura This is a good solution too.

**Comment by jellybob** [comment] 2021-03-24 13:34
I'm not convinced @olafura's solution is a great one. Freedesktop.org's mime types file is much more exhaustive than Red Hat's, particularly around identifying a file type via matching byte patterns within a file. Red Hat's version is solely based on file extensions.

**Comment by minad** [comment] 2021-03-24 13:36
@erran This is not a good proposal. Do you prefer to have no 0.3.x version available at all? The fastest way to sort this out is:

1. Generate tables.rb from https://pagure.io/mailcap/blob/master/f/mime.types and distribute that as 0.3.7 and 0.4.1. But @jellybob's objection is true.
2. Load the freedesktop.org.xml at startup and don't distribute tables.rb as part of the mimemagic gem. Then we can also create a 0.3.7 and 0.4.1 version under the MIT license.

**Comment by coding-bunny** [comment] 2021-03-24 13:36
I'm going to try and make a PR to replace the gem. Even if it's not ideal, it's a good starting point for me and can be rejected/updated by others

**Comment by jellybob** [comment] 2021-03-24 13:38
As I see it there are two options, both with drawbacks, so as others have said some input from the Rails team is probably needed:

Option 1: Download the freedesktop.org mime type descriptions at runtime. This probably results in a minimum of changes to mimemagic, and doesn't impact how that gem behaves. However, this then means potential issues for people deploying in tightly regulated environments as additional communication with third party servers will need to be approved - in some cases there's potential for pulling in dependencies from third parties at run time simply not being approved at all.

Option 2: Move to using Red Hat's public domain licensed mime type descriptions. Doesn't have issues with pulling in resources at run time, but it will mean a reduction in accuracy during mime type sniffing.

**Comment by georgeclaghorn** [comment] 2021-03-24 13:39
Using a database that doesn’t contain magic signatures isn’t a viable path. We (via Marcel) use MimeMagic specifically for this feature; if we don’t need that, we already have multiple other MIME type DBs available in Rails with varying completeness (but we do need it).

**Comment by minad** [comment] 2021-03-24 13:40
@coding-bunny Please notify me when you have something ready.
@jellybob Yes, that's right. Pulling/Loading at runtime is not without impact. I think it needs a bit of effort to get this right. I think it is best to require the file being present at startup by requiring manual installation of the file.

**Comment by matthewford** [comment] 2021-03-24 13:40
> As I see it there are two options, both with drawbacks, so as others have said some input from the Rails team is probably needed:
> 
> Option 1: Download the freedesktop.org mime type descriptions at runtime. This probably results in a minimum of changes to mimemagic, and doesn't impact how that gem behaves. However, this then means potential issues for people deploying in tightly regulated environments as additional communication with third party servers will need to be approved - in some cases there's potential for pulling in dependencies from third parties at run time simply not being approved at all.
> 
> Option 2: Move to using Red Hat's public domain licensed mime type descriptions. Doesn't have issues with pulling in resources at run time, but it will mean a reduction in accuracy during mime type sniffing.

You could take a similar approach to faraday, where there is a common interface but two implementations

**Comment by sergey-alekseev** [comment] 2021-03-24 13:41
Not only Rails depends on mimemagic. The gem is [used by](https://github.com/minad/mimemagic/network/dependents?package_id=UGFja2FnZS0xMDYyMDY%3D) 576,971 Repositories and 172 Packages on Github ATM. It would be more correct for @minad to unarchive https://github.com/minad/mimemagic and move this conversation there IMO.

**Comment by minad** [comment] 2021-03-24 13:44
@sergey-alekseev I disagree. The Rails dependency is certainly the most impactful one. It is best if we find a solution which works for Rails and which is sanctioned by the Rails team.

**Comment by coding-bunny** [comment] 2021-03-24 13:46
I've started here : https://github.com/rails/rails/pull/41751

**Comment by YorickPeterse** [comment] 2021-03-24 13:57
@minad The problem with yanking the older versions unannounced means every existing project that (indirectly) depends on mimemagic can no longer be installed, _unless_ they bump the version. The new license in turn may prevent may projects from doing so for legal reasons. 

Of course the Gem should already have been using the GPL license, but it would have been much better if this was at least announced ahead of time in some way. 

As an example: we are running into this issue in GitLab, effectively making it impossible to deploy new versions until we find a workaround. Bumping the version may not work either, as we disallow GPL dependencies (as these conflict with our enterprise edition).

**Comment by jellybob** [comment] 2021-03-24 13:57
I've forked mimemagic, and intend to make changes as described in the issue opened on my fork at https://github.com/jellybob/mimemagic/issues/1

**Comment by pauldub** [comment] 2021-03-24 14:08
The database at https://www.nationalarchives.gov.uk/PRONOM/Default.aspx includes magic numbers signatures and was mentionned by https://github.com/zRedShift/mimemagic/issues/4#issuecomment-805774658 as an alternative to freedesktop's database.

**Comment by coding-bunny** [comment] 2021-03-24 14:13
We most likely need the solution from @jellybob because marcel, another rails dependency also needs a solution to this problem.
So a MIT compatible gem as new release would resolve it for everything at once, as the dependency can just be upgraded then.

**Comment by pixeltrix** [comment] 2021-03-24 14:20
@pauldub The acknowledgements for PRONOM include Adobe, Borland, Corel and Microsoft amongst others - we'd need clarification that this isn't tainted in some way as well.

**Comment by Deradon** [comment] 2021-03-24 14:24
WDYT about this: https://github.com/Deradon/mimemagic/commit/7f4ed120a8626d4b7cce052edb04c621c998f2d5 ?

**Comment by jellybob** [comment] 2021-03-24 14:26
@Deradon the distributed gem will still be GPL licensed, because you're distributing a GPL licensed source file as part of it. All that change really does is remove the dependency from Github, however the Github repo isn't what's being distributed to end users.

**Comment by YorickPeterse** [comment] 2021-03-24 14:29
From my understanding there are two GPL files at play: an XML file used to generate a Ruby file, and the Ruby file itself.

Would it be an option to include the XML file in the Git repository, use that to generate a somewhat different Ruby file at `gem build` time, then _only_ include that derived file in the Gem? Or would the derived file still be GPL due to being based on a GPL XML file?

**Comment by minad** [comment] 2021-03-24 14:30
@YorickPeterse 

> Or would the derived file still be GPL due to being based on a GPL XML file?

You basically answered your own question here. The file is then GPL since it is derived.

**Comment by Deradon** [comment] 2021-03-24 14:30
@jellybob Is it considered `distributing a GPL licensed source file` if we fetch it once during build time and reformat it to ruby code, and discard the original source afterwards?

**Comment by jellybob** [comment] 2021-03-24 14:31
@Deradon by a strict reading of the GPL license, yes. I'm attempting to get in touch with the maintainer of the source file to discuss what the options are.

**Comment by Pierstoval** [comment] 2021-03-24 14:33
To anyone forking  this repo, remember that you can fork it only starting at the [f46e0d38](https://github.com/minad/mimemagic/commit/f46e0d387a635241f952d54b68f18fa94d291513), because it is the last one with MIT license.

**Comment by regismesquita** [comment] 2021-03-24 14:35
@Pierstoval don't you mean https://github.com/minad/mimemagic/commit/c0f7b6b21a192629839db87612794d08f9ff7e88 ?

**Comment by minad** [comment] 2021-03-24 14:37
@Pierstoval While you are technically correct, I am willing to change the license of the mimemagic.rb files back to MIT. The only files which cannot be licensed and distributed under MIT are freedesktop.org.xml and the derived tables.rb. Note that the "loading at runtime approach" has been proposed by @hadess themselves in minad/mimemagic#97. It would be best to get confirmation by @hadess as to what is considered a compliant solution, as @jellybob is attempting. I suggest you follow https://github.com/jellybob/mimemagic/issues/1.

**Comment by coding-bunny** [comment] 2021-03-24 14:54
So I managed to get my PR to be green for Rails.
Not sure if this solves the problem given the `marcel` dependency, but point for effort I guess xD

**Comment by hadess** [comment] 2021-03-24 14:54
> @Pierstoval While you are technically correct, I am willing to change the license of the mimemagic.rb files back to MIT. The only files which cannot be licensed and distributed under MIT are freedesktop.org.xml and the derived tables.rb. Note that the "loading at runtime approach" has been proposed by @hadess themselves in [minad/mimemagic#97](https://github.com/minad/mimemagic/issues/97). It would be best to get confirmation by @hadess as to what is considered a compliant solution, as @jellybob is attempting. I suggest you follow [jellybob/mimemagic#1](https://github.com/jellybob/mimemagic/issues/1).

I don't know whether that'd be "compliant", because that would require a law degree and rubber stamps which I don't have, but that would solve the problem as I saw it.

What I wouldn't agree to is shipping the freedesktop.org.xml (and derived) files in an MIT-licensed project. None of the (past) versions of mimemagic labelled as "MIT" are actually "MIT" licensed, as they use a GNU GPL source, essentially making them all GPL. The changed license is a correction, not a relicense.

**Comment by nirvdrum** [comment] 2021-03-24 14:54
@Pierstoval You'll need to roll back to a commit before the GPL dependency (freedesktop.org.xml) was added to _mimemagic_. The [issue](https://github.com/minad/mimemagic/issues/97) precipitating all of this is that the old MIT license was invalid for the project. It's not as simple as going back to when the license file changed, unless you think the original license violation claim was invalid.

**Comment by bopm** [comment] 2021-03-24 14:58
@nirvdrum so technically speaking before mimemagic [was created](https://github.com/minad/mimemagic/commit/749a7e59de480b7c0373acc4f8ceb4444352ba46#diff-2ea7e2364883967953ab518a8316b639e612b8a6f20eadb7b97939d91c8e2612).

**Comment by regismesquita** [comment] 2021-03-24 15:00
@nirvdrum but it shows that the gem code is itself MIT and the author's intent, so if you fork at that point and then remove all of the GPL dependencies isn't that ok to release it as MIT?

**Comment by mvz** [comment] 2021-03-24 15:00
@nirvdrum that would mean a license violation can never be fixed and I don't think that's how it's supposed to work.

**Comment by jellybob** [comment] 2021-03-24 15:02
@hadess can you either comment on the ticket at https://github.com/jellybob/mimemagic/issues/1, or get in touch with me in some other way? I'm attempting to find a solution to this problem, and your input as the maintainer of the source data would be very much appreciated.

**Comment by callumacrae** [comment] 2021-03-24 15:03
> It would be best to get confirmation by @hadess as to what is considered a compliant solution,

Note that it isn't just up to @hadess, it's also up to any other contributors (past and future) to the file in question, unless they've signed a CLA giving @hadess authorisation to make these decisions.

**Comment by CrazyPython** [comment] 2021-03-24 15:14
> , the mimemagic change to GPL licence forces rails to be distributed in GPL also, which forces all projects that are using Rails to be open-sourced

Sort of. You are allowed to dual-license dependent software under GPL and MIT. The GPL merely requires a license at least as permissive as it.

**Comment by nirvdrum** [comment] 2021-03-24 15:14
@regismesquita @mvz There's a few different things going on. I may very well have misread what the OP was saying. All I was pointing out is that the issue isn't that the license file changed. Whatever your ultimate solution is, it needs to address the notion that the project was never properly MIT in the first place.

**Comment by madejejej** [comment] 2021-03-24 15:17
I just wanted to drop a small hint here.

`mimemagic` is only a dependency to `activestorage` and `actionmailbox`.

If your Rails app doesn't use `activestorage` nor `actionmailbox `, you could cherry-pick the other rails subgems for now:

```ruby
gem 'activesupport'
gem 'actionpack'
gem 'actionview'
gem 'activemodel'
gem 'activerecord'
gem 'actionmailer'
gem 'railties'
gem 'sprockets-rails'

# if you use cucumber-rails, the latest version depends on Rails
# however, cucumber-rails on master branch only depends on railties
gem 'cucumber-rails', require: false, github: 'cucumber/cucumber-rails'
```

**Comment by regismesquita** [comment] 2021-03-24 15:18
@nirvdrum I see your point but still, the project was MIT, it just had files violating that license, sure we can't just use an older version, but I don't think that it makes us unable to fork a previous version and fix it.

**Comment by mvz** [comment] 2021-03-24 15:20
> @regismesquita @mvz There's a few different things going on. I may very well have misread what the OP was saying. All I was pointing out is that the issue isn't that the license file changed. Whatever your ultimate solution is, it needs to address the notion that the project was never properly MIT in the first place.

Oh, it definitely needs to address the license violation, but AIUI you can fork from a commit that was MIT licensed, and then do the fix. But, I'm not a lawyer of course.

**Comment by jellybob** [comment] 2021-03-24 15:20
@regismesquita the previous version had a license file saying it was MIT, but due to including a file taken from a GPL licensed project, the entire thing is actually GPL licensed because that's a requirement of using GPL licensed libraries. This works in a similar way to it not being sufficient for me to just slap a sticker on something saying "Property of Jon" for ownership to be transferred to me.

**Comment by jasongerard** [comment] 2021-03-24 15:21
> @nirvdrum I see your point but still, the project was MIT, it just had files violating that license, sure we can't just use an older version, but I don't think that it makes us unable to fork a previous version and fix it.

There is no previous version that didn't have this file in it though.

**Comment by mvz** [comment] 2021-03-24 15:22
> the entire thing is actually GPL licensed

I'm not sure that's true. At this point, we need laywers :shrug:.

**Comment by regismesquita** [comment] 2021-03-24 15:22
@jellybob wouldn't that make your fork GPL'ed then?

**Comment by jellybob** [comment] 2021-03-24 15:23
@regismesquita potentially - I'm attempting to get in touch with maintainers at freedesktop.org to clarify that.

**Comment by Pierstoval** [comment] 2021-03-24 15:26
> > the entire thing is actually GPL licensed
> 
> I'm not sure that's true. At this point, we need laywers 🤷.

That's true according to how GPL works, hence the licence fix to GPL-v2.

Removing the GPL-related file(s) from the repository and changing the licence to MIT is still possible, even though the files will have to be fetched at some point (hence the proposal to fetch the files at runtime).

That's what [FOSCKEditorBundle](https://github.com/FriendsOfSymfony/FOSCKEditorBundle) did: since the bundle is MIT, and CKEditor is GPL, it cannot be bundled with the code, so you have a command to download it at runtime.

**Comment by mvz** [comment] 2021-03-24 15:30
@Pierstoval there's a difference between 'should be licensed under GPL-2 or else it's a license violation' and 'is automatically licensed under GPL-2'.

**Comment by luke-hill** [comment] 2021-03-24 15:32
@madejejej I'm a maintainer for cucumber rails (As is @mvz), we can try expedite something here if required. I'll catch up on this thread tomorrow.

**Comment by wwahammy** [comment] 2021-03-24 15:33
Quite honestly, I think the original claim that this was a GPL violation is wrong. I think the database could be included under fair use. You'd need a lawyer to verify but I think this could have been kept under the MIT license.

**Comment by jellybob** [comment] 2021-03-24 15:38
My perspective on this (and as far as I can tell I'm the only one actively trying to resolve this issue) is that I don't want to reach a conclusion which while technically compliant with the license goes against the spirit of that license, and the author's intention when they released the database under that license. I'm talking to the maintainers about potential options, and will update once there's something to say.

**Comment by enebo** [comment] 2021-03-24 15:39
This may be a stupid question but has anyone asked the original copyright holder if they will allow that single file to be MIT licensed.  I know they reported the problem originally but they may see the bind people are in and allow just that data to be MIT licensable.

**Comment by tinco** [comment] 2021-03-24 15:41
@Pierstoval IANAL, but that's not how it works. It just means you are in violation of the GPLv2. The way that situation is resolved is by a lawsuit. Again, IANAL but no judge would ever say you should give all your businesses proprietary code away just because you inadvertently pulled in a GPL source file.

If you do it knowingly though,  that's a whole different story, and companies have in the past been forced to release their full source code just to make them comply.

I don't like the release of 0.3.6, I think it was better to break people's deployments, so that they are made aware of their violation, and they could upgrade to 0.4 to make a decision. Now people are unknowingly pulling in the new license, and their legal position is slightly diminished. Either way it was definitely the most ethical move by Daniel to pull the gems.

**Comment by tachyons** [comment] 2021-03-24 15:42
Terming something as fair use or illegal at this scale can't be done using random opinion from internet, I think community need to consult organisation like EFF or FSF for practical way forward. I think decision to yank gem was bit to early, But I empathize with the gem owner as it is difficult to take a decision when internet is storming about it

**Comment by wwahammy** [comment] 2021-03-24 15:44
I really encourage a qualified lawyer be consulted as well as folks at GNOME as this is part of GNOME.

**Comment by jk779** [comment] 2021-03-24 15:45
Background info: 
@enebo @wwahammy etc.: it seems @hadess is technically right. have a look here for example: https://gitlab.freedesktop.org/xdg/shared-mime-info/-/issues/154 https://github.com/zRedShift/mimemagic/issues/4#issuecomment-805712232

**Comment by ebassi** [comment] 2021-03-24 15:47
> as the file is part of GNOME.

The shared MIME database is not "part of GNOME"; as you might have noticed, the source repository is on freedesktop.org. GNOME, KDE, and other projects are consumers of the shared MIME database.

The recommendation to ask a lawyer for licensing issues, though, is a good recommendation.

**Comment by syedanabimam** [comment] 2021-03-24 15:50
This could have been handled better :confused: honestly!

**Comment by krisleech** [comment] 2021-03-24 15:51
If you have a SasS product maybe this applies?

```
As long as you don't distribute your binaries, there is no problem with using GPL libraries (or other code) in an otherwise closed-source project. 

As far as the regular GPL and LGPL are concerned, providing access to use your software over a network (like in SaaS) is not considered distribution. This means that there is no problem with using (L)GPL libraries in a closed-source SaaS project.
```

ref: https://softwareengineering.stackexchange.com/questions/220742/using-full-gpl-libraries-in-software-as-a-service-saas-models/220743

**Comment by wwahammy** [comment] 2021-03-24 15:52
> My perspective on this (and as far as I can tell I'm the only one actively trying to resolve this issue) is that I don't want to reach a conclusion which while technically compliant with the license goes against the spirit of that license, and the author's intention when they released the database under that license. I'm talking to the maintainers about potential options, and will update once there's something to say.

I generally agree and negotiation and a mutual agreement is the best solution. But look at what the file in question actually is: It describes the "magic numbers" of file types. Claiming that there's a copyright on that is a little like saying there's a copyright on an API. It's not a straightforward.

And I'm not suggesting "lawyering" up. I'm suggesting that we're not qualified to know what the options are. I strongly, strongly, strongly recommend talking to a lawyer before doing too much more.

**Comment by ZanderBrown** [comment] 2021-03-24 15:52
> @Pierstoval there's a difference between 'should be licensed under GPL-2 or else it's a license violation' and 'is automatically licensed under GPL-2'.

There may be a difference but not a particularly useful one, functionally it's the same really: You avoid the license violation by being GPL so really it is automatically GPL. In fact you could argue that's the whole point of GPL.

**Comment by wwahammy** [comment] 2021-03-24 15:54
> The shared MIME database is not "part of GNOME"; as you might have noticed, the source repository is on freedesktop.org. GNOME, KDE, and other projects are consumers of the shared MIME database.

My misunderstanding @ebassi, thanks for correcting me. I saw freedesktop.org and assumed GNOME.

**Comment by YorickPeterse** [comment] 2021-03-24 15:54
@wwahammy There's a bit more to it than just a bunch of bits: https://github.com/zRedShift/mimemagic/issues/4#issuecomment-805801107

**Comment by Haegin** [comment] 2021-03-24 15:54
> If you have a SasS product maybe this applies?
> 
> ```
> As long as you don't distribute your binaries, there is no problem with using GPL libraries (or other code) in an otherwise closed-source project. 
> 
> As far as the regular GPL and LGPL are concerned, providing access to use your software over a network (like in SaaS) is not considered distribution. This means that there is no problem with using (L)GPL libraries in a closed-source SaaS project.
> ```
> 
> ref: https://softwareengineering.stackexchange.com/questions/220742/using-full-gpl-libraries-in-software-as-a-service-saas-models/220743

There's more information about how GPL applies to SaaS products (that are accessed over a network, but not distributed) in an article at https://resources.whitesourcesoftware.com/blog-whitesource/the-saas-loophole-in-gpl-open-source-licenses

From the looks of it, hosting a Rails app that uses GPL code doesn't require the source code to be made available to all users.

**Comment by amingilani** [comment] 2021-03-24 15:55
> This may be a stupid question but has anyone asked the original copyright holder if they will allow that single file to be MIT licensed. I know they reported the problem originally but they may see the bind people are in and allow just that data to be MIT licensable.

@enebo Not a stupid question, but there are about [120 contributors](https://github.com/freedesktop/xdg-shared-mime-info/graphs/contributors).

**Comment by enebo** [comment] 2021-03-24 15:55
@jk779 yeah I figured they were within their rights but I was hoping dual licensing that file would just cause less heartache.  Your links makes it look like they felt they were being ignored in their original requests.  So the 'stupid' part of my comment is I could have dug a little bit before asking my question :)

**Comment by mlooney** [comment] 2021-03-24 15:57
@enebo seems like the original file is a derivative of other gplv2 sources anyway, so It doesn't seem like an "original author" (could one be identified) would have a choice in the matter in any event.

**Comment by mvz** [comment] 2021-03-24 15:57
@ZanderBrown the point of the exchange you're replying to is whether the violation could be fixed by removing the GPL bits instead of just changing the license to GPL for everything. For that purpose, the difference is relevant.

**Comment by ZanderBrown** [comment] 2021-03-24 16:00
@mvz whilst the GPL derived code exists the whole "gem" is GPL, but yes I don't see why the "un (directly) tainted" code couldn't be considered MIT (assuming author consent) if the GPL components are completely removed - of course the resultant package would (at least initially) be quite useless

**Comment by olafura** [comment] 2021-03-24 16:17
There is also https://github.com/hanklords/shared-mime-info which uses the query protocol that shared-mime-info has
https://www.freedesktop.org/wiki/Specifications/shared-mime-info-spec/

So it should be possible to use the data with having problems with the GPL licence.

**Comment by jellybob** [comment] 2021-03-24 16:18
I've spoken to the freedesktop.org contributor who raised the original complaint, and they are happy with the approach being taken in my fork of the gem. I'm going to push ahead with implementing that now.

**Comment by wwahammy** [comment] 2021-03-24 16:29
> I've spoken to the freedesktop.org contributor who raised the original complaint, and they are happy with the approach being taken in my fork of the gem. I'm going to push ahead with implementing that now. See [jellybob/mimemagic#1](https://github.com/jellybob/mimemagic/issues/1) for more details (but please pay heed of the comment right at the top about license lawyering).

I mentioned there but also my only minor request would be that those of us can use GPL2+ code have a way to use the original mimemagic. In short, let's not break it for people who don't need it broken :)

**Comment by pedantic-git** [comment] 2021-03-24 16:32
I haven't seen it discussed anywhere yet but is anyone looking into a new solution based on an _extant_ magic numbers database that isn't licensed as GPL? For example, [the one that is bundled with Apache httpd](https://github.com/apache/httpd/blob/c900f76b3214046164ceb687bb6856bfb539cc62/docs/conf/magic) (Apache License), which contains the magic numbers for many of the most popular file types (GIF, PNG, PDF, etc.)

**Comment by jellybob** [comment] 2021-03-24 16:36
@pedantic-git I certainly haven't, as my personal objective here is to unblock deployments of services I'm responsible for with the minimum of friction while retaining mimemagic's runtime functionality unchanged, but it sounds like it could be a good solution longer term.

**Comment by georgeclaghorn** [comment] 2021-03-24 16:36
We (the Rails core team and friends) are currently investigating the possibility of using the 2-clause BSD–licensed [libmagic](https://man7.org/linux/man-pages/man3/libmagic.3.html), the basis of the standard [`file`](https://en.wikipedia.org/wiki/File_(command)) tool, or Ruby translation of its magic DBs.

**Comment by pedantic-git** [comment] 2021-03-24 16:38
@georgeclaghorn I wish I could hit the :heart: button multiple times

**Comment by pcreux** [comment] 2021-03-24 16:50
"Someday ~ImageMagick~ mimemagic will finally break for good and we'll have a long period of scrambling as we try to reassemble civilization from the rubble."

<img width=300 src="https://user-images.githubusercontent.com/45299/112349467-fd1ce380-8c85-11eb-9f4a-278e0db4400a.png">

https://xkcd.com/2347/

**Comment by fidalgo** [comment] 2021-03-24 17:24
I do not have full context here, but can't we make `shared-mime-info` a system dependecy? In unix systems, it could be the equivalent of having sqlite installed. I'm running Fedora Linux and this is my file list for the package:
`rpm -ql shared-mime-info`

```
/usr/bin/update-mime-database
/usr/lib/.build-id
/usr/lib/.build-id/33
/usr/lib/.build-id/33/04cee19eb6db922ba834294b7c093a1f07fd2f
/usr/share/applications/gnome-mimeapps.list
/usr/share/applications/mimeapps.list
/usr/share/doc/shared-mime-info
/usr/share/doc/shared-mime-info/HACKING.md
/usr/share/doc/shared-mime-info/NEWS
/usr/share/doc/shared-mime-info/README.md
/usr/share/doc/shared-mime-info/shared-mime-info-spec.xml
/usr/share/gettext/its/shared-mime-info.its
/usr/share/gettext/its/shared-mime-info.loc
/usr/share/licenses/shared-mime-info
/usr/share/licenses/shared-mime-info/COPYING
/usr/share/man/man1/update-mime-database.1.gz
/usr/share/mime
/usr/share/mime/packages
/usr/share/mime/packages/freedesktop.org.xml
/usr/share/pkgconfig
/usr/share/pkgconfig/shared-mime-info.pc
```

can't we inquiry the location of the `freedesktop.org.xml` file in the filesystem and use it? We would need to raise an error if the package is not installed... and I have no idea how to do it on windows.

just my $.02

**Comment by ewascent** [comment] 2021-03-24 17:26
Thanks IBM! You are making the world a harder place to get work done.

**Comment by jellybob** [comment] 2021-03-24 17:27
@fidalgo see https://github.com/jellybob/mimemagic/pull/3 where I'm doing just that.

**Comment by hadess** [comment] 2021-03-24 17:33
> Thanks IBM! You are making the world a harder place to get work done.

What does IBM have to do with licensing terms not being followed?

**Comment by lamont-granquist** [comment] 2021-03-24 17:35
Note that by yanking all prior versions the author has broken every Gemfile.lock which is currently being used which references, which will require a forced upgrade and release on everyone (breaking e.g. autoscaling of existing tested services).

If this is just a licensing issue, it might be useful for the author to work with rubygems directly to replace the old versions with ones that just have the license fixed.

**Comment by wwahammy** [comment] 2021-03-24 17:36
I don't want to yell this but I feel like I need to: there has been literally tens of thousands of dollars of developer time spent hereon this issue and yet, to my knowledge, NO ONE has spent a few hundred bucks on FOSS lawyer to actually tell us what to do, if anything.

**Comment by georgeclaghorn** [comment] 2021-03-24 17:37
I’m locking this issue because the continued discussion is not terribly productive. We’ll follow up here when we have updates as they pertain specifically to Rails.

**Comment by georgeclaghorn** [comment] 2021-03-26 19:12
[Rails 5.2.5, 6.0.3.6, and 6.1.3.1 have been released](https://weblog.rubyonrails.org), removing the mimemagic dependency.

**Closed by georgeclaghorn** 2021-03-26 19:12 UTC

**Comment by rmacklin** [comment] 2021-03-26 20:13
Thank you @georgeclaghorn!

I've put together a patch for `ruby-advisory-db` to include rails 5.2.5 in some of the `patched_versions` lists for some prior rails CVEs: https://github.com/rubysec/ruby-advisory-db/pull/464. Can you confirm this looks correct?

**Comment by georgeclaghorn** [comment] 2021-03-26 21:17
Looks good, @rmacklin. :+1:

**Comment by bengalamx** [comment] 2021-03-27 22:45
Could not find gem 'mimemagic (= 0.3.6)' in any of the gem sources listed in your Gemfile

**Comment by pboling** [comment] 2021-03-27 23:58
All the GPL versions (<= 0.3.6 and = 0.4.0) were yanked.

The latest release is 0.3.10 if you would like to give it a try.

You can always check https://rubygems.org/gems/mimemagic

**Comment by bengalamx** [comment] 2021-03-28 22:48
Hey @georgeclaghorn, rails 5.2.5 still uses MimeMagic 😔

<img width="1227" alt="Captura de Pantalla 2021-03-28 a la(s) 16 47 38" src="https://user-images.githubusercontent.com/3253845/112770732-5027cb00-8fe5-11eb-8845-f81372af2d92.png">

**Comment by georgeclaghorn** [comment] 2021-03-28 22:51
Your screenshot shows the installed version of `carrierwave` depending on it. You can check `Gemfile.lock` for other gems that may depend on it.

**Comment by bruno** [comment] 2021-03-28 23:57
:rocket: :arrow_up: Deployed as part of **[production 2021-03-28 23:57:06](https://github.com/waysact/waysact/releases/tag/release/production/2021.03.28_23.57.06)**.

**Comment by vandreychuk-blackbird** [comment] 2021-03-29 13:20
> Hey @georgeclaghorn, rails 5.2.5 still uses MimeMagic 😔
> 
> <img alt="Captura de Pantalla 2021-03-28 a la(s) 16 47 38" width="1227" src="https://user-images.githubusercontent.com/3253845/112770732-5027cb00-8fe5-11eb-8845-f81372af2d92.png">

have u solved the issued? I have the same issue even after install shared-mime-info package.
macos big sur 11.2.3, apple m1

**Comment by lekansogunle** [comment] 2021-03-29 13:23
> > Hey @georgeclaghorn, rails 5.2.5 still uses MimeMagic 😔
> > <img alt="Captura de Pantalla 2021-03-28 a la(s) 16 47 38" width="1227" src="https://user-images.githubusercontent.com/3253845/112770732-5027cb00-8fe5-11eb-8845-f81372af2d92.png">
> 
> have u solved the issue? I have the same issue even after install shared-mime-info package.
> macos big sur 11.2.3, apple m1

Have you tried to update mimemagic with `bundle update mimemagic`

**Comment by reedstonefood** [comment] 2021-03-29 13:25
@vandreychuk-blackbird - george has [already answered your question](https://github.com/rails/rails/issues/41750#issuecomment-808972692)

> Your screenshot shows the installed version of carrierwave depending on it. You can check Gemfile.lock for other gems that may depend on it.

Rails depended on mimemagic, it no longer does, but other gem still rely on it. `carrierwave` is one such gem; that is the cause of your error message.

It looks like they have [removed the dependency](https://github.com/carrierwaveuploader/carrierwave/commit/3f809672dd2d18ee4398a7bba9d8f9effa05023e) but have [yet to release a new version of the gem](https://github.com/carrierwaveuploader/carrierwave/issues/2553). Once they have you can use it & you won't have this problem anymore.

**Comment by vandreychuk-blackbird** [comment] 2021-03-29 13:34
@reedstonefood @lekansogunle thank u, I've tried to reinstall brew and shared-mime-info package and eventually it works...

**Comment by EstebanAO** [comment] 2021-03-29 17:12
What about projects with rails 4 (specifically I have 4.2.5)? Is there going to be an upgrade for that version?

**Comment by georgeclaghorn** [comment] 2021-03-29 17:16
Active Storage was introduced in Rails 5.2. Rails < 5.2 doesn’t transitively depend on `mimemagic`.

**Comment by orlando** [comment] 2021-03-30 21:25
In case someone is looking for a solution, you need to upgrade the Rails version, in my case to `6.1.3.1` https://weblog.rubyonrails.org/2021/3/26/marcel-upgrade-releases/

**Comment by radinreth** [comment] 2021-03-31 06:30
Today, I am trying to docker image of my rails app 6.0.3.5

Then got a nasty error below:

![image](https://user-images.githubusercontent.com/5484758/113097494-2c50c900-9221-11eb-8c95-90febb453f1e.png)

I got it works by:

`bundle update --conservative mimemagic `

More detail: [user1678123 - stackoverflow](https://stackoverflow.com/questions/66844316/bundlergemnotfound-could-not-find-mimemagic-0-3-5-in-any-of-the-sources-on-ra#answer-66847191)

**Comment by samcdavid** [comment] 2021-04-12 14:46
For anyone else that runs into this error when trying to build their project, I updated my Rails 5 project to 5.2.5 and this resolved the issue and `mimemagic` is no longer in the Gemfile.lock.

**I personally have not tried this for Rails 6**, but I suspect that if you are on Rails 6 and upgrade to 6.1.3.1 that this will also resolve your build issues and remove `mimemagic` from your lock file.

**Comment by redconfetti** [comment] 2021-04-13 20:01
I just updated Rails from v6.1.3 to v6.1.3.1, this replaced the dependency in activestorage with mini_mime (~> 1.0.2).

**Comment by flutterq** [comment] 2021-04-27 02:00
[[Solved] Bundler::GemNotFound: Could not find mimemagic-0.3.5 in any of the sources on Rails project with Docker
](https://exerror.com/bundlergemnotfound-could-not-find-mimemagic-0-3-5-in-any-of-the-sources-on-ra/)
