### ISSUE TITLE
HABTM :association_foreign_key not work in AR 5.1

### ISSUE THREAD

**Issue by kvokka** [rails/rails#29102] opened 2017-05-16 05:27 UTC
Code 
```
class Foo
  has_and_belongs_to_many :properties,
    :join_table => :property_buildmaterial,
    :foreign_key => :materialid_fk,
    :association_foreign_key => :propertyid_fk
end
```
returns
```
ArgumentError: Unknown key: :association_foreign_key. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type, :index_errors
```
It works with Rails 5.0.3, and return error with Rails 5.1, Ruby version 2.3.3

**Comment by alexcameron89** [comment] 2017-05-16 12:19
Hey @kvokka, I am not able to reproduce the issue you are having. could you create a reproducible bug script [using one of the templates here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)? That will make it easier for us to reproduce the issue. [Here](https://gist.github.com/364ada8f1f2b533d6bc6e0db0571ed0f) is the script that I used to try to recreate your issue, if you want to work off of that.

**Comment by libc** [comment] 2017-07-19 15:01
Could be caused by 3rd party gem. For example in our application [the exact same error is caused by `ar-octopus`.](https://github.com/thiagopradi/octopus/issues/444)

Roughly like this:
```ruby
module TotallyRails
  def has_and_belongs_to_many(name, scope = nil, **options)
    p scope: scope, options: options
  end
end

module Octopus
  def has_and_belongs_to_many(name, scope = nil, options = {})
    super
  end
end

class RailsWithOctopus
  include TotallyRails
  include Octopus
end

class RailsWithoutOctopus
  include TotallyRails
end

# prints {:scope=>{:key=>:value}, :options=>{}}
RailsWithOctopus.new.has_and_belongs_to_many(:hello, key: :value)
# prints {:scope=>nil, :options=>{:key=>:value}}
RailsWithoutOctopus.new.has_and_belongs_to_many(:hello, key: :value)
```

**Comment by alexcameron89** [comment] 2017-07-19 20:00
I'm going to close this since there hasn't been activity in a few months. If you are able to reproduce this issue with a clean Rails application, I'll gladly reopen it.

**Closed by alexcameron89** 2017-07-19 20:00 UTC
Labels: activerecord, needs work
