### ISSUE TITLE
Active Record GROUP_BY/COUNT calculation returns correct query but incorrect result? 

### ISSUE THREAD

**Issue by ajh-sr** [rails/rails#41073] opened 2021-01-11 04:40 UTC
In the process of upgrading to 6.1.0, tests of ours that relied on the `groupdate` gem started failing, but I'm also seeing strange behaviour using plain `group`. In 6.0.3.4, we see the expected behaviour. 

### Steps to reproduce
I tried to create a minimal test case from the template [here](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) but it seems not to exhibit the issue below. I'm not sure if this is because it's using sqlite rather than postgres or if the issue is resolved in master or...  😞 

https://gist.github.com/ajh-sr/ea1db6d11ff39e51edd1267bff86a2fc

### Expected behavior
In 6.0.3.4, 
```
irb(main):005:0> Client.group(:agency_id).count(:all)
   (0.3ms)  SELECT COUNT(*) AS "count_all", "clients"."agency_id" AS "clients_agency_id" FROM "clients" GROUP BY "clients"."agency_id"
=> {nil=>5, "ad9601cd-5130-4325-bb2a-5f651fa57443"=>1, "7dbef763-272f-4d12-b6c3-1838bf402196"=>1, "0eb5a6ec-b29b-444e-ba93-d4c0a833d3d8"=>1, "c3cf771f-0aba-403c-ad7f-3d9f53576abc"=>1}
```
The only difference between the generated queries returned on the console between version 6.0.3.4 and version 6.1.0 seems to be the alias `AS "count_all"`

### Actual behavior
In a Rails 6.1 console we see:
```
irb(main):001:0> Client.count(:all)
   (1.0ms)  SELECT COUNT(*) FROM "clients"
=> 9

irb(main):009:0> Client.pluck :agency_id
   (0.7ms)  SELECT "clients"."agency_id" FROM "clients"
=> [nil, nil, nil, "c3cf771f-0aba-403c-ad7f-3d9f53576abc", "7dbef763-272f-4d12-b6c3-1838bf402196", "0eb5a6ec-b29b-444e-ba93-d4c0a833d3d8", "ad9601cd-5130-4325-bb2a-5f651fa57443", nil, nil]

irb(main):002:0> Client.group(:agency_id).count(:all)
   (0.7ms)  SELECT COUNT(*), "clients"."agency_id" AS "clients_agency_id" FROM "clients" GROUP BY "clients"."agency_id"
=> {nil=>0, "ad9601cd-5130-4325-bb2a-5f651fa57443"=>0, "7dbef763-272f-4d12-b6c3-1838bf402196"=>0, "0eb5a6ec-b29b-444e-ba93-d4c0a833d3d8"=>0, "c3cf771f-0aba-403c-ad7f-3d9f53576abc"=>0}
```

If I copy and paste the query returned against the postgresql DB, I see the expected results:
![image](https://user-images.githubusercontent.com/71472057/104145598-7e592e00-542c-11eb-9055-7be32d6b0e81.png)

And if I run the query at the rails console using `exec_query`, the results are returned as expected:

```
irb(main):011:0> ActiveRecord::Base.connection.exec_query('SELECT COUNT(*), "clients"."agency_id" AS "clients_agency_id" FROM "clients" GROUP BY "clients"."agency_id"')
  SQL (0.6ms)  SELECT COUNT(*), "clients"."agency_id" AS "clients_agency_id" FROM "clients" GROUP BY "clients"."agency_id"
=> #<ActiveRecord::Result:0x00007f81218f9d60 @columns=["count", "clients_agency_id"], @rows=[[5, nil], [1, "ad9601cd-5130-4325-bb2a-5f651fa57443"], [1, "7dbef763-272f-4d12-b6c3-1838bf402196"], [1, "0eb5a6ec-b29b-444e-ba93-d4c0a833d3d8"], [1, "c3cf771f-0aba-403c-ad7f-3d9f53576abc"]], @hash_rows=nil, @column_types={"clients_agency_id"=>#<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Uuid:0x00007f812200d390 @precision=nil, @scale=nil, @limit=nil>}>
```

Is there something I'm missing? 

### System configuration
**Rails version**: 6.1.0

**Ruby version**: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin18

**Comment by intrip** [comment] 2021-03-26 15:08
I've tweaked your script [to use `pg`](https://gist.github.com/intrip/c5ca39e0f4d49e1f91cb76f3c78f2dca) but couldn't reproduce the issue. Most likely the issue is in the `groupdate` gem and you'd better open an issue in their repository.

**Comment by ghiculescu** [comment] 2021-06-21 19:20
I'm going to close this for now @ajh-sr but please reopen if you can replicate it. If it helps, see if adding the `groupdate` gem to your replication script helps replicate the issue, then you could work backward from there.

**Closed by ghiculescu** 2021-06-21 19:20 UTC
Labels: activerecord
