### ISSUE TITLE
Date#to_time doesn't respect Time#use_zone

### ISSUE THREAD

**Issue by Dbz** [rails/rails#25428] opened 2016-06-18 01:06 UTC
### Steps to reproduce
```Ruby
# System clock should be in PDT
Time.use_zone('Eastern Time (US & Canada)') do
  d = Date.parse('friday')
  puts d.to_time
  puts d.to_time.zone

  t = Time.zone.parse('friday')
  puts t
  puts t.zone
end
```

### Expected behavior
> 2016-06-17 00:00:00 -0400
> EDT
> 2016-06-17 00:00:00 -0400
> EDT

### Actual behavior
> 2016-06-17 00:00:00 -0700
> PDT
> 2016-06-17 00:00:00 -0400
> EDT

### System configuration
**Rails version**: Rails 4.2.3

**Ruby version**: ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin14.1.0]

### Code Fix
In: [date conversions](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/date/conversions.rb#L73-L85)
```Ruby
def to_time(form = :local)
  raise ArgumentError, "Expected :local or :utc, got #{form.inspect}." unless [:local, :utc].include?(form)
  ::Time.zone.send(form, year, month, day) # Time.zone.send instead of Time.zone
end
```

**Comment by Dbz** [comment] 2016-06-18 01:08
This could theoretically be a breaking API change when people are using `Date#to_time` in a `Time#use_zone` block (or if they have a config value for the application time zone), and they are expecting to get the local machine time. It seems unlikely, but it is possible.


I'd love to contribute to Rails and make a pull request.

**Comment by maclover7** [comment] 2016-06-18 01:18
Hmm, I'm not able to reproduce on the latest on `4-2-stable` or Rails `master` using [this reproduction script](https://gist.github.com/maclover7/4863204fd291e62a6025fb8c62a6d703). I'd advise that you upgrade your application to the latest version in the 4.2.x series, or a more recent version 😬

**Comment by Dbz** [comment] 2016-06-18 01:36
I ran an 'rspec' version of that script on mine and it failed. I'll try creating a rails `4.2.3` app and testing it.

**Comment by Dbz** [comment] 2016-06-18 01:44
Okay I ran this script:

```Ruby
require 'active_support'
require 'rails_helper'
include ApplicationHelper

describe 'date in a time zone' do
  specify 'date and time are equal' do
    puts "Testing on Rails #{Rails::VERSION::STRING}..."

    d = Date.new
    t = Time.new
    Time.use_zone('Eastern Time (US & Canada)') do
      d = Date.parse('friday')
      t = Time.zone.parse('friday')
    end

    expect(d.to_time).to eq(t)
    expect(d.to_time.zone).to eq(t.zone)
  end
end
```

In the console: `$ be rspec spec/time_test.rb`

Output:

```
Testing on Rails 4.2.3...
F

Failures:

  1) date in a time zone date and time are equal
     Failure/Error: expect(d.to_time).to eq(t)

       expected: 2016-06-17 00:00:00.000000000 -0400
            got: 2016-06-17 00:00:00.000000000 -0700

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -Fri, 17 Jun 2016 00:00:00 EDT -04:00
       +2016-06-17 00:00:00 -0700

     # ./spec/time_test.rb:16:in `block (2 levels) in <top (required)>'

Finished in 0.02766 seconds (files took 2.56 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/time_test.rb:6 # date in a time zone date and time are equal
```

Gemfile additions:

```Ruby
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-rails'
```

Rails version: `Rails 4.2.3`
Ruby version: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]`

**Comment by maclover7** [comment] 2016-06-18 01:54
The reason why that is failing is because you need to run your `expect`s / `assert`s within the `Time.use_zone` block -- not outside. `Time.zone` is only changed within the block that is provided -- this can be seen in the [source](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/time/zones.rb#L60-L68) for this method, as there is an `ensure` catcher that makes sure that the original time zone is restored after the execution of the block 😬

**Comment by Dbz** [comment] 2016-06-18 01:57
I moved them inside the block and they are still failing.

**Comment by Dbz** [comment] 2016-06-18 01:59
That was actually my suspicion at first when I was investigating the issue. However, I believe that the ensure is actually handling everything correctly: it is converting the time properly when changing the time zone. In the code example, the time and time zone are not being converted correctly.

**Comment by Nowaker** [comment] 2016-06-18 06:54
> Rails version: Rails 4.2.3

4.2.6 is the latest version.

**Comment by Dbz** [comment] 2016-06-18 14:30
I have updated to Rails 4.2.6 (which is important because there are changes to the relevant files!)

I modified the `.parse('friday')`s to `.parse('2016-6-17')` because it was an incorrect parse statement.

[Here are the relevant files](https://gist.github.com/Dbz/6804ac5923b162a9aac7707006ed6210)

Even in the latest version of rails, the issue is still persisting.

**Comment by maclover7** [comment] 2016-06-18 14:51
I just want to point out again that you need to place the `assert`s/`expect`s inside of the `Time.use_zone` block -- this is the *only supported behavior* here. Many of the tests you posted in your reproduction script do not do this...

Going to give this issue a close, since this appears to be working correctly / is the expected behavior. If you can create a reproduction script which shows that `Date#to_time` does not work properly within `Time.use_zone`'s block, I'd be happy to reopen the issue 😬

**Comment by Dbz** [comment] 2016-06-18 16:26
I apologize; you already made it clear to me that I needed to put the `expect`s/`assert`s in the `Time.use_zone` block. I have modified the code to put all of the `expect`s inside of the time block, and the results are the same. [You can see the code here.](https://gist.github.com/Dbz/6804ac5923b162a9aac7707006ed6210)

The reason why I bring this bug up is because we have code in production that is supposed to run at a certain time in Pacific Standard Time, but our servers are in UTC, and the code runs at the 'correct time', but in UTC.

Here is a more complex and code example:

```Ruby
specify 'Everything is consistent in a Time#use_zone block' do
  Time.use_zone('UTC') do
    two_pm_friday = Date.parse('2016-6-17').to_time +
      Time.zone.parse('2pm').seconds_since_midnight.seconds
    expect(Time.zone.name).to eq('UTC')
    expect(two_pm_friday.zone).to eq('UTC')
  end
end
```

This test fails because `two_pm_friday.zone` equals `PDT`

```
Failures:

  1) date in a time zone Everything is consistent in a Time#use_zone block
     Failure/Error: expect(two_pm_friday.zone).to eq('UTC')

       expected: "UTC"
            got: "PDT"

       (compared using ==)
     # ./spec/time_test.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/time_test.rb:8:in `block (2 levels) in <top (required)>'
```

**Comment by Dbz** [comment] 2016-06-20 22:05
@maclover7 I also realized the reason your initial test script may have failed was because if you are in NYC, the eastern timezone is also your computer's local timezone. Will you try running this slightly modified one instead? It uses the Pacific Time zone.

```Ruby
require 'active_support'
require 'minitest/autorun'

class BugTest < Minitest::Test
  def test_stuff
    puts "Testing on Rails #{Rails::VERSION::STRING}..."

    Time.use_zone('Pacific Time (US & Canada)') do
      d = Date.parse('2016-6-17')
      t = Time.zone.parse('2016-6-17')
      
      assert_equal d.to_time, t
      assert_equal d.to_time.zone, t.zone
    end
  end
end
```

**Comment by maclover7** [comment] 2016-06-21 02:12
👍 Sorry I closed this, reopening.

**Comment by maclover7** [comment] 2016-06-21 02:15
Updated reproduction script here --> https://gist.github.com/maclover7/4863204fd291e62a6025fb8c62a6d703.

Traced the issue to `#to_time` not taking into account the `Time.zone`. Working on a fix, but it's breaking a bunch of tests :(

**Comment by Dbz** [comment] 2016-06-21 02:16
If it's okay. I'd love to write the pull request and fix the tests. Can you give me just the slightest bit of guidance? Which branch should I make a pull request to?

**Comment by maclover7** [comment] 2016-06-21 15:53
Sure, that's fine with me. I'm happy to help review the PR once it's ready to go. :)

**Comment by pixeltrix** [comment] 2016-07-01 08:54
@Dbz you're not really comparing the right things here - you're converting the date to an instance of `Time` which only really has UTC and local time, whereas `Time.zone.parse` is an `ActiveSupport::TimeWithZone` instance which supports arbitrary timezones. The `Time.use_zone` method only affects the setting for the latter and not the system timezone. There's a method called `in_time_zone` on `Date` that will convert it to an instance of `ActiveSupport::TimeWithZone` in the way that you would expect, e.g:

``` irb
>> Time.use_zone("Hawaii") { Time.zone.parse('friday') }
=> Thu, 30 Jun 2016 00:00:00 HST -10:00 
>> Time.use_zone("Hawaii") { Date.parse('friday').in_time_zone }
=> Fri, 01 Jul 2016 00:00:00 HST -10:00 
```

Note that the timezone is the same but the time is actually different. This is because the `Date.parse` method is unaware of the Rails timezone support. You can use `String#in_time_zone` instead, e.g.

``` irb
>> Time.use_zone("Hawaii") { 'friday'.in_time_zone }
=> Thu, 30 Jun 2016 00:00:00 HST -10:00 
```

As you can see this has the same time as `Time.zone.parse`.

With the upcoming Ruby 2.4 release things start get complicated as it changes the behavior of `to_time` to preserve the offset when calling, e.g:

``` irb
# Ruby 2.3
>> Time.parse('00:00 PDT')
=> "2016-07-01T00:00:00.000-07:00" 
>> Time.parse('00:00 PDT').to_time
=> "2016-07-01T08:00:00.000+01:00" 

# Ruby 2.4
>> Time.parse('00:00 PDT')
=> 2016-07-01 00:00:00 -0700 
>> Time.parse('00:00 PDT').to_time
=> 2016-07-01 00:00:00 -0700 
```

Note that this is just UTC offset though - it doesn't handle DST transitions like Rails timezone handling, e.g.

```
# Ruby 'timezone' support
>> Time.parse('2016-10-01 00:00:00 BST')
=> 2016-10-01 00:00:00 +0100 
>> Time.parse('2016-10-01 00:00:00 BST') + 31
=> 2016-10-01 00:00:31 +0100 

# Rails timezone support
>> Time.zone.parse('2016-10-01 00:00:00 PDT')
=> Sat, 01 Oct 2016 08:00:00 BST +01:00 
>> Time.zone.parse('2016-10-01 00:00:00 PDT') + 31.days
=> Tue, 01 Nov 2016 08:00:00 GMT +00:00 
```

Note the timezone change from BST to GMT in the latter.

So, I'm sorry if you've wasted your time trying to write a PR but I don't think this is a bug - we'd be changing the behavior of built-in Ruby methods which we don't want to do.

**Closed by pixeltrix** 2016-07-01 08:54 UTC
Labels: activesupport, With reproduction steps

**Comment by Dbz** [comment] 2016-07-01 18:38
@pixeltrix No problem! I'm just trying to help. Thank you for the plethora of examples. I hope that I can contribute to Rails in the future.

**Comment by Dbz** [comment] 2016-07-01 22:59
@maclover7 Thank you as well for your time in reviewing this and going over it!

**Comment by jchatel** [comment] 2017-03-21 10:00
You mean in latest Rails/Ruby, this crazy behaviour didn't change?

Time.zone.name => UTC

Time.use_zone("Samoa") do
    t = Time.new(2017,1,1, 10,30,00)
    p t.to_time
end

=> 2017-01-01 10:30:00 +0100

t.zone
"W. Europe Standard Time"

Time.use_zone is not very useful here and I ended up having to pass time_zone to my function doing a Date.to_time

**Comment by jchatel** [comment] 2017-03-21 10:03
Apparently, this was fixed in Ruby 2.4 ... going to migrate.

**Comment by Dbz** [comment] 2017-03-27 00:59
Hey jchatel, as an FYI that is a dead link

**Comment by jchatel** [comment] 2017-03-27 08:30
bummer, try this: http://126kr.com/article/9eyowneyyqe

"This is considered a bug fix, since early Ruby versions did not preserve the time zone of the receiver object when invoking the to_time method."
