### ISSUE TITLE
On has_many_inversing object_id has different values after create

### ISSUE THREAD

**Issue by dmitry** [rails/rails#38313] opened 2020-01-25 19:11 UTC
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile do
  source 'https://rubygems.org'

  ruby '2.6.1'

  gem 'activerecord', path: '../'
  gem 'sqlite3'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Base.has_many_inversing = true

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :phone_numbers, force: true do |t|
    t.references :user, null: false
  end
end

class User < ActiveRecord::Base
  has_many :phone_numbers, inverse_of: :user
end

class PhoneNumber < ActiveRecord::Base
  belongs_to :user, inverse_of: :phone_numbers
end

class BugTest < Minitest::Test
  def test_accessing_parent_association_before_creation_inverses_one_record
    pn = PhoneNumber.new
    pn.build_user
    pn.save!
    assert_equal 1, pn.user.phone_numbers.size
    assert_equal pn.object_id, pn.user.phone_numbers.first.object_id
  end
end

```

### Expected behavior

`ActiveRecord::Base.has_many_inversing = true`

After creating the parent model with has_many inversible association it should inverse with the same record.

### Actual behavior

It returns other `object_id` on inversible assocation after the create. Means object was reinitialized after the transaction.

### System configuration
**Rails version**: 6.1.0.pre
**Ruby version**: 2.6.1

**Comment by fabriziobertoglio1987** [comment] 2020-02-07 18:16
I think it has something to do with the ActiveRecord::Associations::CollectionAssociation [private methods][1], but I am still reviewing the sourcecode

[1]: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/collection_association.rb#L316-L512

**Comment by fabriziobertoglio1987** [comment] 2020-02-10 10:12
I am currently working on a pull request for this issue. Hopefully I'll be able to publish the changes soon.

**Comment by fabriziobertoglio1987** [comment] 2020-02-10 11:17
My latest update, from [`inverse_associations_test.rb`][1]

```ruby
  def test_inversed_instance_should_not_be_reloaded_after_stale_state_changed_with_validation
    face = Face.new man: Man.new

    old_inversed_man = face.man
    face.save!
    new_inversed_man = face.man

    assert_equal old_inversed_man.object_id, new_inversed_man.object_id
  end
```
where 

```ruby
class Face < ActiveRecord::Base
  belongs_to :man, inverse_of: :face
end
```

I am still working on this task. Thanks


[1]: https://github.com/rails/rails/blob/master/activerecord/test/cases/associations/inverse_associations_test.rb#L712-L720

**Comment by fabriziobertoglio1987** [comment] 2020-02-10 17:19
The following edited [test cases] passes green 
```ruby
def test_with_has_many_inversing_should_try_to_set_inverse_instances_when_the_inverse_is_a_has_many
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  with_has_many_inversing do
    i = interests(:llama_wrangling)
    m = i.polymorphic_man
    assert_not_nil m.polymorphic_interests
    iz = m.polymorphic_interests.detect { |_iz| _iz.id == i.id }
    assert_not_nil iz
    assert_equal i.topic, iz.topic, "Interest topics should be the same before changes to child"
    i.topic = "Eating cheese with a spoon"
    assert_equal i.topic, iz.topic, "Interest topics should be the same after changes to child"
    iz.topic = "Cow tipping"
    assert_equal i.topic, iz.topic, "Interest topics should be the same after changes to parent-owned instance"
    m.save
    old_id = m.object_id
    assert_equal old_id, m.interests.first.man.object_id
  end
end
```
The below test cases (pasted in the same test file) fails

```ruby
  ActiveRecord::Schema.define do
    create_table :users, force: true do |t|
    end

    create_table :phones, force: true do |t|
      t.references :user, null: false
    end
  end

  class User < ActiveRecord::Base
    has_many :phones, inverse_of: :user
  end

  class Phone < ActiveRecord::Base
    belongs_to :user, inverse_of: :phones
  end

  def test_accessing_parent_association_before_creation_inverses_one_record
    phone = Phone.new
    phone.build_user
    phone.save!
    assert_equal 1, Phone.all.size
    assert_equal 1, User.all.size
    assert_equal 1, phone.user.phones.size
    assert_equal phone.object_id, phone.user.phones.first.object_id
  end
```

in both cases `stale_target?` returns `false`, so the issue may be somewhere else.

```ruby
class CollectionAssociation < Association #:nodoc:
  # Implements the reader method, e.g. foo.items for Foo.has_many :items
  def reader
    if stale_target?
      reload
    end

    @proxy ||= CollectionProxy.create(klass, self)
    @proxy.reset_scope
  end
end
```

[1]: https://github.com/rails/rails/blob/master/activerecord/test/cases/associations/inverse_associations_test.rb#L712-L720

**Comment by fabriziobertoglio1987** [comment] 2020-02-11 17:43
This post is written in the effort to organize my thoughts and understand ActiveRecord Associations.

`BelongsToAssociation` inherits from `SingularAssociation`.

```ruby
module ActiveRecord
  module Associations
    class SingularAssociation < Association #:nodoc:
      # Implements the reader method, e.g. foo.bar for Foo.has_one :bar
      def reader
        if !loaded? || stale_target?
          reload
        end

        target
      end
    end
  end
end
```

`HasManyAssociation` inherits from `CollectionAssociation` . It does not cache the association

```ruby
module ActiveRecord
  module Associations
    class CollectionAssociation < Association #:nodoc:
      # Implements the reader method, e.g. foo.bars for Foo.has_many :bars
      def reader
        if stale_target?
          reload
        end

        @proxy ||= CollectionProxy.create(klass, self)
        @proxy.reset_scope
      end
    end
  end
end
```

Using the `rails console` to retrieve `user.posts` CollectionProxy

```ruby
user = Post.last.user
collection_association = ActiveRecord::Associations::CollectionAssociation.new(user, User.reflections()["posts"])
=> #<ActiveRecord::Associations::CollectionAssociation:0x00007fae0cc72268>
collection_proxy = ActiveRecord::Associations::CollectionProxy.new(Post, collection_association)
=> [#<Post:0x00007fae0b787600>, #<Post: ...>]
collection_association.reader
=> [#<Post:0x00007fae0b787600>, #<Post: ...>]
```

Upon `Association` instanciation, `@loaded` and `@target` are set to `false` and `nil`.

```ruby
class Association #:nodoc:
  attr_reader :owner, :target, :reflection

  delegate :options, to: :reflection

  def initialize(owner, reflection)
    reflection.check_validity!

    @owner, @reflection = owner, reflection
    @_scope = nil

    reset
    reset_scope
  end
end
```

>Associations in Active Record are middlemen between the object that holds the association, known as the <tt>owner</tt>, and the associated result set, known as the <tt>target</tt>.

The class responsible for creating the above instance is `ActiveRecord::Associations::ClassMethods`, but it is still not clear to me the connection between `ActiveRecord::Base` and `ActiveRecord::Association`.


[1]: https://github.com/fabriziobertoglio1987/surf-rails
[2]: https://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html

**Comment by fabriziobertoglio1987** [comment] 2020-02-12 16:07
```ruby 
module ActiveRecord
  module Core
    extend ActiveSupport::Concern
      # Overwrite the default class equality method to provide support for decorated models.
      def ===(object) # :nodoc:
        object.is_a?(self)
      end
    end
  end
end
```

and
  
```ruby
phone === phone.user.phones.first
=> true
phone.send(:'===', phone.user.phones.first)
=> true
```

I would really appreciate some feedback.
Thanks a lot

**Comment by fabriziobertoglio1987** [comment] 2020-02-12 16:53
I would need some help on this issue. I just noticed:

```ruby
phone === phone.user.phones.first
```

there must been some override of `===` method, so maybe that is the solution to this issue.

**Comment by fabriziobertoglio1987** [comment] 2020-02-12 20:02
This post is written in an effort to organize my thoughts. 

`ActiveRecord::Base` includes `ActiveRecord::Associations`. 

The `ActiveRecord::Associations` class methods `has_many`, `belongs_to`, `has_and_belongs_to_many` will add the corresponding `Reflection`

```ruby
def has_many(name, scope = nil, **options, &extension)
  reflection = Builder::HasMany.build(self, name, scope, options, &extension)
  Reflection.add_reflection self, name, reflection
end
```

the method `association(name)` will return the association (`has_many` or `belongs_to`) target.

```ruby
def association(name) #:nodoc:
  association = association_instance_get(name)

  if association.nil?
    unless reflection = self.class._reflect_on_association(name)
      raise AssociationNotFoundError.new(self, name)
    end
    association = reflection.association_class.new(self, reflection)
    association_instance_set(name, association)
  end

  association
end
```

The association is stored and retrieved from cache.
```ruby
# Returns the specified association instance if it exists, +nil+ otherwise.
def association_instance_get(name)
  @association_cache[name]
end

# Set the specified association instance.
def association_instance_set(name, association)
  @association_cache[name] = association
end
```

tomorrow I will investigate the role of the cache in triggering new sql queries, instead of using the existing cache (`clear_association_cache`)

```ruby
phone = Phone.new
phone.build_user
phone.save!
phone.association_cached(:user)
phone.send(:association_instance_get, :user).target
=> #<User:0x00007fa8b7308fb0 id: 1>
phone.user.association_cached?(:phones)
=> true
phone.user.send(:association_instance_get, :phones).target
=> [#<Phone:0x00007fa8b72029b8 id: 1, user_id: 1>, #<Phone:0x00007fa8b72029b8 id: 1, user_id: 1>]
phone.user.phones
=> [#<Phone:0x00007fa8b72029b8 id: 1, user_id: 1>]
```

**Comment by fabriziobertoglio1987** [comment] 2020-02-13 11:30
`.reload` clears the association cache. It is triggered if `stale_target?` is `true`.

`stale_target?` checks that the association is:
1. not an `inversed` association
2. it is `loaded?`
3. the `@stale_state` is not equal to `stale_state` implemented in the child association

```ruby
class ActiveRecord::Associations:Association
  # The target is stale if the target no longer points to the record(s) that the
  # relevant foreign_key(s) refers to. If stale, the association accessor method
  # on the owner will reload the target. It's up to subclasses to implement the
  # stale_state method if relevant.
  #
  # Note that if the target has not been loaded, it is not considered stale.
  def stale_target?
    !@inversed && loaded? && @stale_state != stale_state
  end
end
```

`stale_state` is implemented in the `BelongsToAssociaton` and `HasManyAssociation`.

```ruby
class BelongsToAssociation < Association
  def stale_state
    result = owner._read_attribute(reflection.foreign_key) { |n| owner.send(:missing_attribute, n, caller) }
    result && result.to_s
  end
end
```

`stale_state` is related to the reflection `foreign_key` value.

```ruby
pry> belongs_to = ActiveRecord::Associations::BelongsToAssociation.new(phone, Phone.reflections()["user"])
=> #<ActiveRecord::Associations::BelongsToAssociation:0x00007fc082f99e68/>
pry> belongs_to.send(:stale_state)
=> '1'
pry> phone.user_id
=> 1
```

`stale_state` is not implemented in `HasManyAssociation`, but `CollectionAssociation` still uses `stale_target?` to `reload`.

```ruby
pry> has_many = ActiveRecord::Associations::HasManyAssociation.new(user, User.reflections()['phones'])
=> #<ActiveRecord::Associations::HasManyAssociation:0x00007fc0859da218 
      # @loaded=false
      # @inversed=false 
      # @stale_state=nil>
pry> has_many.send(:stale_state)
=> nil
```

`@inversed` is set in `Association.inversed_from`

```ruby
def inversed_from(record)
  self.target = record
  @inversed = !!record
end
```

If `owner` is `nil`, then `@inversed` is `false`, `load_target` will set `@target`.
The `Association` class has two attribute writers to set the `inverse`.

```ruby
class Associations::Associations
  # Set the inverse association, if possible
  def set_inverse_instance(record)
    if inverse = inverse_association_for(record)
      inverse.inversed_from(owner)
    end
    record
  end

  def set_inverse_instance_from_queries(record)
    if inverse = inverse_association_for(record)
      inverse.inversed_from_queries(owner)
    end
    record
  end
end
```

The `@inverse` attribute is set with `Association.build_record(attributes)` through `initialize_attributes`

```ruby
class Associations::Association
  def build_record(attributes)
    reflection.build_association(attributes) do |record|
      initialize_attributes(record, attributes)
      yield(record) if block_given?
    end
  end
end
```

`SingularAssociation.build` calls `build_record`

```ruby
class SingularAssociation < Association
  def build(attributes = nil, &block)
    record = build_record(attributes, &block)
    set_new_record(record)
    record
  end
end
```

calling `belongs_to.build()` will update the `target` and `loaded` flags, somehow to make us notice an ActiveRecord object has been created and yet not persisted to the database.

```ruby
class CollectionProxy
  def build(attributes = {}, &block)
    @association.build(attributes, &block)
  end
  alias_method :new, :build
end
user.phones.build
=> #<Phone:0x00007fc082a6b8b0 id: nil, user_id: 1>
user.phones
=> [#<Phone:0x00007fc083139098 id: 1, user_id: 1>, #<Phone:0x00007fc081f53d60 id: nil, user_id: 1>]
belongs_to.build()
=> #<User:0x00007fc082fab050 id: nil>
belongs_to
=> #<ActiveRecord::Associations::BelongsToAssociation:0x00007fc083bb3c30 
      # @loaded=true 
      # @inversed=false
      # @target=#<User:0x00007fc082fab050 id: nil>,>
```

**Comment by fabriziobertoglio1987** [comment] 2020-02-13 15:59
using `loaded!` does not fix the issue

```ruby
pry> has_many = ActiveRecord::Associations::HasManyAssociation.new(phone.user, User.reflections()['phones'])
pry> has_many.loaded!
```

while using `phone.user.phones.load()` fixes the issue. The solution must be related to the `Relation` class and it's role in performing the queries.

```ruby
class Relation
  # Causes the records to be loaded from the database if they have not
  # been loaded already. You can use this if for some reason you need
  # to explicitly load some records before actually using them. The
  # return value is the relation itself, not the records.
  #
  #   Post.where(published: true).load # => #<ActiveRecord::Relation>
  def load(&block)
    unless loaded?
      @records = exec_queries(&block)
      @loaded = true
    end

    self
  end
end
```

The following test case passes as green

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile do
  source 'https://rubygems.org'

  ruby '2.6.1'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem 'activerecord'
  gem 'sqlite3'
  gem 'byebug'
end

require "active_record"
require "minitest/autorun"
require "logger"
require 'byebug'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Base.has_many_inversing = true

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :phones, force: true do |t|
    t.references :user, null: false
  end
end

class User < ActiveRecord::Base
  has_many :phones, inverse_of: :user
end

class Phone < ActiveRecord::Base
  belongs_to :user, inverse_of: :phones
end

class BugTest < Minitest::Test
  def test_accessing_parent_association_before_creation_inverses_one_record
    phone = Phone.new
    phone.build_user
    phone.user.phones.load()
    phone.save!
    assert_equal phone.object_id, phone.user.phones.first.object_id
  end
end
```

I'll keep working on this and prepare a pull request soon.

**Comment by fabriziobertoglio1987** [comment] 2020-02-14 11:22
`CollectionAssociation` has a `reader` method to retrieve the associations from the database.
```ruby
class CollectionAssociation < Association #:nodoc:
  # Implements the reader method, e.g. foo.items for Foo.has_many :items
  def reader
    if stale_target?
      reload
    end

    @proxy ||= CollectionProxy.create(klass, self)
    @proxy.reset_scope
  end
end
```

`CollectionProxy` initializer is called with 

1. `klass` is the model (for ex. `Post`)
2. `association`

The `initializer` methods does the following:

1. call the parent `initializer` method and passes `Post`. The parent sets `@loaded=false`
2. add the extensions (for has_many they are `[]`)

```ruby
class CollectionProxy < Relation
  def initialize(klass, association, **) #:nodoc:
    @association = association
    super klass

    extensions = association.extensions
    extend(*extensions) if extensions.any?
  end
end
```

but the main functionalities are included in `CollectionAssociation` which delegates to `CollectionProxy`.
If `ActiveRecord::Base.has_many_inversing`, then ...

```ruby
class CollectionAssociation < Association
  def target=(record)
    return super unless ActiveRecord::Base.has_many_inversing

    case record
    when Array
      super
    else
      add_to_target(record, true)
    end
  end

  def add_to_target(record, skip_callbacks = false, &block)
    if association_scope.distinct_value
      index = @target.index(record)
    end
    replace_on_target(record, index, skip_callbacks, &block)
  end
end
```

`add_to_target` will call `set_inverse_instance` and tries to skip the query

```ruby
class Association
  # Set the inverse association, if possible
  def set_inverse_instance(record)
    if inverse = inverse_association_for(record)
      inverse.inversed_from(owner)
    end
    record
  end
end
```

`target=` is called on `reload`
The `reload` inside `CollectionAssociation.reader` is triggering the method  

```ruby
class CollectionAssociation < Association #:nodoc:
  # Implements the reader method, e.g. foo.items for Foo.has_many :items
  def reader
    if stale_target?
      reload
    end
  end
end

class Association
  # Reloads the \target and returns +self+ on success.
  # The QueryCache is cleared if +force+ is true.
  def reload(force = false)
    klass.connection.clear_query_cache if force && klass
    reset
    reset_scope
    load_target
    self unless target.nil?
  end

  def load_target
    @target = find_target if (@stale_state && stale_target?) || find_target?

    loaded! unless loaded?
    target
  rescue ActiveRecord::RecordNotFound
    reset
  end
  private
    def find_target
      scope = self.scope
      return scope.to_a if skip_statement_cache?(scope)

      conn = klass.connection
      sc = reflection.association_scope_cache(conn, owner) do |params|
        as = AssociationScope.create { params.bind }
        target_scope.merge!(as.scope(self))
      end

      binds = AssociationScope.get_bind_values(owner, reflection.chain)
      sc.execute(binds, conn) { |record| set_inverse_instance(record) } || []
    end
end
```

**Comment by fabriziobertoglio1987** [comment] 2020-02-14 18:32
The issue is caused from `ActiveRecord::Base.save`, the test does not fail without saving.

```ruby
module ActiveRecord
  module Persistence
    module ClassMethods
      def save(*args, **options, &block)
        create_or_update(*args, **options, &block)
      rescue ActiveRecord::RecordInvalid
        false
      end
    end
  end

  # Creates a record with values matching those of the instance attributes
  # and returns its id.
  def _create_record(attribute_names = self.attribute_names)
    attribute_names = attributes_for_create(attribute_names)

    new_id = self.class._insert_record(
      attributes_with_values(attribute_names)
    )

    self.id ||= new_id if @primary_key

    @new_record = false

    yield(self) if block_given?

    id
  end
end
```

after `save` the foreign key changes and `stale_target?` returns true. The record is reloaded

```ruby
class SingularAssociation < Association #:nodoc:
  # Implements the reader method, e.g. foo.bar for Foo.has_one :bar
  def reader
    if !loaded? || stale_target?
      reload
    end

    target
  end
end
```

**Comment by dmitry** [comment] 2020-02-14 23:14
@gmcgibbon can you please help with this issue?

**Comment by fabriziobertoglio1987** [comment] 2020-02-15 18:22
The following test cases passes as green

```ruby
class BugTest < Minitest::Test
  def test_accessing_parent_association_before_creation_inverses_one_record
    phone = Phone.new
    user = User.create
    phone.user = user
    has_many = phone.user.phones.instance_variable_get(:@association)
    has_many.instance_variable_set(:@loaded, true)
    phone.save
    assert_equal phone.object_id, phone.user.phones.first.object_id
  end
end
```

The issue is caused from the method `find_nth_with_limit` when `loaded?` is false.

```ruby
def find_nth_with_limit(index, limit)
  if loaded?
    # no new object_id
    records[index, limit] || []
  else
    # returns new objects
    relation = ordered_relation

    if limit_value
      limit = [limit_value - index, limit].min
    end

    if limit > 0
      relation = relation.offset(offset_index + index) unless index.zero?
      relation.limit(limit).to_a
    else
      []
    end
  end
end
```
I am still investingating the issue connected to `find_nth_with_limit` and the reason `has_many.loaded?` returns false.
I will prepare a pull request this week. Thanks

**Comment by fabriziobertoglio1987** [comment] 2020-02-16 11:51
`phone.user.phones` does not trigger `loaded!`. 
The change was introduced with [34533][2]

>To not [load the association][1]. When setting the inverse on has_many we don't want the collection to be fully loaded because there's probably other records that we don't have in memory yet.

The `ActiveRecord::Associations::Association` class method `target=`

```ruby
def target=(target)
  @target = target
  loaded!
end
```

is re-defined in child class `ActiveRecord::Associations::CollectionAssociation` (the parent for `HasManyAssociation`).
The re-refined method does not invoke `loaded!`.

```ruby
def target=(records)
  @target = records
end

def inversed_from(record)
  self.target = [record]
  @inversed = !!record
end
alias :inversed_from_queries :inversed_from
```

other methods rely on `@association.loaded?`. 
The bug in this issue is connected to the usage of `loaded?` inside `ActiveRecord::Relation` (module `FinderMethods`) method `find_nth_with_limit`. The method is called from `.first()` to return the first entry of `CollectionProxy`.

as `loaded?` returns false, the method does not use the cached result in `records`, performs n+1 query and returns it as a new object.

```ruby
def find_nth_with_limit(index, limit)
  if loaded?
    # no new object_id
    records[index, limit] || []
  else
    # other logic..
  end
end
```

The below test cases uses `phone.user.phones.records.first.object_id` instead of `phone.user.phones.first` and returns identical `object_id`

```ruby
class BugTest < Minitest::Test
  def test_accessing_parent_association_before_creation_inverses_one_record
    phone = Phone.new
    phone.build_user
    phone.save
    assert_equal phone.object_id, phone.user.phones.records.first.object_id
  end
end
```

I am working on a pull request for this issue, trying to triggering `loaded!` with the correct conditions  (as said by gmcgibbon)

>When setting the inverse on has_many we don't want the collection to be fully loaded because there's probably other records that we don't have in memory yet.

[1]: https://github.com/rails/rails/blob/b9c7305dbe57931a153a540d49ae5d469af61a14/activerecord/lib/active_record/associations/association.rb#L77
[2]: https://github.com/rails/rails/pull/34533/files#r236719211

**Comment by fabriziobertoglio1987** [comment] 2020-02-17 11:29
`CollectionAssociation` method `target=` 

```ruby
def target=(record)
  return super unless ActiveRecord::Base.has_many_inversing

  case record
  when Array
    super
  else
    add_to_target(record, true)
  end
end
```

`replace_on_target` [37643][1]

```ruby
def replace_on_target(record, index, skip_callbacks)
  catch(:abort) do
    callback(:before_add, record)
  end || return unless skip_callbacks

  set_inverse_instance(record)

  @_was_loaded = true

  yield(record) if block_given?

  if index
    target[index] = record
  elsif @_was_loaded || !loaded?
    @association_ids = nil
    target << record
  end

  callback(:after_add, record) unless skip_callbacks

  record
ensure
  @_was_loaded = nil
end
```

> You need to be careful with assumptions regarding the target: The proxy
> does not fetch records from the database until it needs them, but new
> ones created with +build+ are added to the target. So, the target may be
> non-empty and still lack children waiting to be read from the database.
> If you look directly to the database you cannot assume that's the entire
> collection because new records may have been added to the target, etc.
>
> If you need to work on all current children, new and existing records,
> +load_target+ and the +loaded+ flag are your friends.

[1]: https://github.com/rails/rails/pull/37643/files

##### FIRST OPTION - trigger loaded! from [target=][2]
Working on a solution

[2]: https://github.com/gmcgibbon/rails/blob/db60199354bed0202d3dac873752703c1bff199a/activerecord/lib/active_record/associations/collection_association.rb#L449-L472

##### SECOND OPTION - redefine [find_nth_with_limit][3] in [CollectionProxy][4]

```ruby
module ActiveRecord
  module FinderMethods
    def find_nth_with_limit(index, limit)
      if loaded?
        records[index, limit] || []
      else
        relation = ordered_relation

        if limit_value
          limit = [limit_value - index, limit].min
        end

        if limit > 0
          relation = relation.offset(offset_index + index) unless index.zero?
          relation.limit(limit).to_a
        else
          []
        end
      end
    end
  end
end
```

```ruby
class CollectionProxy 
  def find_nth_with_limit(index, limit)
    # use existing methods or a new one to check that the collection was loaded
    if @association.alternative_check_example?
      records[index, limit] || []
    else
      super(index, limit)
    end
  end
end
```

[3]: https://github.com/gmcgibbon/rails/blob/master/activerecord/lib/active_record/relation/finder_methods.rb#L524-L541
[4]: https://github.com/gmcgibbon/rails/blob/master/activerecord/lib/active_record/associations/collection_proxy.rb

**Comment by fabriziobertoglio1987** [comment] 2020-02-20 08:17
@gmcgibbon thanks. I am working on a pull request for this issue.

**Comment by fabriziobertoglio1987** [comment] 2020-02-20 08:23
Hello @gmcgibbon ,

can I write a pull request for this issue?
I have been working on it for 1 week and I have clear idea of the issue.

Thanks
Fabrizio

**Comment by dmitry** [comment] 2020-02-20 09:36
@fabriziobertoglio1987 we definitely need to pair with you to do learning together from the activerecord source.

**Comment by fabriziobertoglio1987** [comment] 2020-02-20 11:43
Thanks 

I give up. 
Feel free to do the pull request

**Comment by gmcgibbon** [comment] 2020-02-20 19:01
👋 Sorry I'm late on this issue.

> I also notices the following, loaded! is not called when .first is called.

I think this sums up the discrepancy of expectations here. Here's a PR I made awhile ago to try and change this behaviour: https://github.com/rails/rails/pull/34469.

As I understand it, we want to selectively load association targets to:

A) Avoid the fact that we cannot guarantee the collection is fully loaded when the `has_many` owner is persisted.
> When setting the inverse on has_many we don't want the collection to be fully loaded because there's probably other records that we don't have in memory yet.

B) Avoid performance concerns with loading the entire collection at once to query one record.
> The current implementation will limit the number of rows returned, but if I'm reading this correctly it will load all rows from the database, then get the n'th row from the in-memory collection.

The expectation then becomes executing a query (and _not_ marking the target as loaded) in the majority of cases where a persisted record invokes its `has_many` association. As such, I think the `object_id` changing when found through an unloaded association is expected, so I'm going to close this issue.

@dmitry the other problem where the inverse gets set twice via `build_user` (https://github.com/rails/rails/issues/38312) is indeed a bug. I see there's a PR open for it already so this should be fixed soon. 

@fabriziobertoglio1987 thank you for documenting your findings. Unfortunately, I think any fix to amend this behaviour would introduce performance problems or behavioural changes to Active Record that would break legacy apps.

**Closed by gmcgibbon** 2020-02-20 19:01 UTC
Labels: activerecord

**Comment by fabriziobertoglio1987** [comment] 2020-02-20 19:40
Thanks a lot @gmcgibbon for the amazing explanation. I am really thankful for this message, as It helps me to understand how `ActiveRecords` works and to connect the missing dots.

I dislike solving issues alone, for this reason I posted all the messages here....

Thanks for the explanation. I am really happy the issue is closed and we can move on to the next one.  I wish you a good evening. Fabrizio

**Comment by dmitry** [comment] 2020-02-20 20:45
@gmcgibbon 

> As I understand it, we want to selectively load association targets to

When we just created an object in the database, I think there are no reason to `load!` it right away from the database, as it is not staled.

> we cannot guarantee the collection is fully loaded

It's fully loaded when it was just created. We are not mutating it anywhere else, it should be stored in memory as it is, without initializing a new object from scratch with the loaded data from the database. We can use mechanism similar to the `reload` - it just loads new data to the object without reinitializing it.

Please let me know if I got something wrong, but in the use-case I've written in the topic it makes sense not to reinitialize object, but to reuse it with the data from the database or even from the memory, especially when the parent (belongs_to record) and child objects (in `target` of has_many association) are just created.

**Comment by gmcgibbon** [comment] 2020-02-21 01:46
@dmitry 

> It's fully loaded when it was just created. We are not mutating it anywhere else, it should be stored in memory as it is, without initializing a new object from scratch with the loaded data from the database. We can use mechanism similar to the reload - it just loads new data to the object without reinitializing it.

This is why I mentioned #34469 specifically. If we assume that finder methods (`first`, `last`, `find`, etc.) are always supposed to hit the database, we will always be querying the data over again. If we also assume that new data from the database will always allocate new record objects for `target`, this is intended behaviour.

I'm open to a change that assigns data fetched from the DB to existing records instead of initializing and replacing, but I'm a little skeptical of the payoff. We will need to prove it is worth doing with benchmarks, and not overly complicate collection association code. Feel free to re-open the issue if you want to give this a shot.
