### ISSUE TITLE
ActiveSupport::Deprecation does not fallback to configured disallowed_behavior

### ISSUE THREAD

**Issue by grncdr** [rails/rails#44553] opened 2022-02-25 16:43 UTC
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", "~> 7.0.0"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    warnings = []

    ActiveSupport::Deprecation.disallowed_warnings << /my_gem soon/
    ActiveSupport::Deprecation.disallowed_behavior = ->(msg, callstack, horizon, gem_name) {
      warnings << msg
    }

    deprecator = ActiveSupport::Deprecation.new('soon', 'my_gem')
    deprecator.deprecation_warning(:some_method)

    refute warnings.empty?
  end
end
```

### Expected behavior

I expect the custom `disallowed_behavior` to be called by `#deprecation_warning`.

### Actual behavior

The gem-default behaviour (`:raise`) is called instead.

### System configuration

**Rails version**:

6.1.4.4 (but this problem affects all versions of Rails from 6.1 onwards)

**Ruby version**:

Ruby 3.1 (but this problem also occurs in earlier Ruby versions).

### More information

I _think_ this could be fixed by prepending a fallback to `ActiveSupport::Deprecation.disallowed_behavior` here: https://github.com/rails/rails/blob/87d4d0f4126f64d991d40a1827de50935ddfdbff/activesupport/lib/active_support/deprecation/behaviors.rb#L71-L73

However, because this class is using a singleton and [InstanceDelegator](https://github.com/rails/rails/blob/87d4d0f4126f64d991d40a1827de50935ddfdbff/activesupport/lib/active_support/deprecation/instance_delegator.rb) the method might need two definitions, one on the class-level (that falls back to DEFAULT_BEHAVIORS) and one on the instance level (that falls back to the class-level behavior).

**Comment by grncdr** [comment] 2022-02-25 16:48
As a work-around, I am doing this in an initializer.
```rb
ActiveSupport::Deprecations[:raise] = ->(...) { ... }
```

**Comment by rafaelfranca** [comment] 2022-02-25 17:45
`ActiveSupport::Deprecation.disallowed_behavior ` you are only changing the behavior of the default deprecator. If you create a new instance you need to configure it instead of the default.

**Comment by rafaelfranca** [comment] 2022-02-25 17:47
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", "~> 7.0.0"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    warnings = []

    deprecator = ActiveSupport::Deprecation.new('soon', 'my_gem')
    deprecator.disallowed_behavior = ->(msg, callstack, horizon, gem_name) {
      warnings << msg
    }
    deprecator.disallowed_warnings << /my_gem soon/
    deprecator.deprecation_warning(:some_method)

    refute warnings.empty?
  end
end
```

**Comment by grncdr** [comment] 2022-02-25 18:09
@rafaelfranca I understand the mechanics of why it didn't work as I expected, but I feel like either this behavior is a bug, or the documentation could be improved.

If the behavior is not open to discussion, the documentation for [#deprecate_methods](https://api.rubyonrails.org/classes/ActiveSupport/Deprecation/MethodWrapper.html#method-i-deprecate_methods) could be improved. This is where I got the idea to pass a custom deprecator, and it doesn't mention that this deprecator will *not* pick up any config from [config.active_support.disallowed_deprecation](https://guides.rubyonrails.org/configuring.html#config-active-support-disallowed-deprecation).

I'd still prefer to call this a bug, but if not: would a PR for that documentation change be more likely to be accepted?

**Comment by rafaelfranca** [comment] 2022-02-25 18:32
This is not a code bug, but it is a documentation bug. A PR to update the documentation makes sense.

**Comment by grncdr** [comment] 2022-02-26 14:43
Ok, I tried updating the documentation, and that clarified what is surprising-enough-to-be-a-bug-IMO about this behavior: the global configuration of `ActiveSupport::Deprecation.disallowed_warnings` _does_ affect the custom deprecator, while `ActiveSupport::Deprecation.disallowed_behavior` _doesn't_.

So one can't simply write something like this:

> Note that custom deprecators are not affected by the global `config.active_support.deprecation_*` settings.

but instead must clarify which global settings will affect the custom deprecator, and which won't.  Consider this (accurate) documentation:

> Note that custom deprecators are not affected by the global [config.active_support.deprecation](https://guides.rubyonrails.org/configuring.html#config-active-support-deprecation) or [config.active_support.disallowed_deprecation](https://guides.rubyonrails.org/configuring.html#config-active-support-disallowed-deprecation) settings, but **are** affected by the global [config.active_support.disallowed_deprecation_warnings](https://guides.rubyonrails.org/configuring.html#config-active-support-disallowed-deprecation-warnings) setting.
>
> This means that deprecations created using a custom deprecator (without it's own `disallowed_behavior`) **will raise exceptions** if they match the globally configured `disallowed_deprecation_warnings` setting.

It might not be a _bug_, but it sure feels wrong to require such complex explanations to avoid shooting yourself in the foot.

Or maybe it's better to say that a custom deprecator using the global `disallowed_exceptions` matcher list is a bug, and fix that?

**Comment by grncdr** [comment] 2022-03-03 13:54
@rafaelfranca any chance this could be re-opened in light of the above? (It's been a few days and I'm not sure if you've seen my last comment).

**Comment by ghiculescu** [comment] 2022-03-03 15:52
I agree that's pretty surprising. Do you think the issue is the use of [`attr_writer`](https://github.com/rails/rails/blob/a2217aede9009de5f7c1cd2d02bc2d0039bab8bf/activesupport/lib/active_support/deprecation/disallowed.rb#L17) vs setting [`disallowed_behaviour=`](https://github.com/rails/rails/blob/a2217aede9009de5f7c1cd2d02bc2d0039bab8bf/activesupport/lib/active_support/deprecation/behaviors.rb#L107) directly?

**Comment by grncdr** [comment] 2022-03-04 12:02
I think the first issue is deciding what the intended behavior here is, custom deprecators should either use or not use shared global config in a consistent way and right now they don't. @cpruitt seems to be the original author of this feature from https://github.com/rails/rails/pull/37940, maybe he can shed some light on how it should work?

---

If custom deprecators are intended to be isolated and not use global config, then line 27 here is the culprit: https://github.com/rails/rails/blob/a2217aede9009de5f7c1cd2d02bc2d0039bab8bf/activesupport/lib/active_support/deprecation/disallowed.rb#L26-L38

Just changing that to use `self.disallowed_warnings` would fix the inconsistency by ensuring that custom deprecators are isolated from the global config... but that use of the shared global `disallowed_warnings` looks *very* intentional to me.

---

If custom deprecators _should_ use the global config, then I'd say this lazy reader needs to be modified: https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/activesupport/lib/active_support/deprecation/behaviors.rb#L71-L73

If an `ActiveSupport::Deprecation` instance doesn't have it's own disallowed behaviour it should fall back to the global one. However, the "global" methods are implemented by delegating to a singleton instance, so you'd need an `if self == ActiveSupport::Deprecation.instance` check to avoid infinite recursion. This would be somewhat more complicated than isolated instances, but it would (IMO) provide a better experience for users of the framework.

---

Personally I prefer the latter, since it was the behaviour I expected in the first place :wink: but I'm happy to contribute either solution.

**Comment by ghiculescu** [comment] 2022-03-04 15:13
The latter seems correct to me also (but I'm not on core so don't take my word on it).
@rafaelfranca what do you think?

**Comment by skipkayhil** [comment] 2022-10-22 22:11
Going to close this as well per https://github.com/rails/rails/pull/44772#issuecomment-1282715196

**Closed by skipkayhil** 2022-10-22 22:11 UTC
Labels: activesupport, attached PR
