### ISSUE TITLE
ActionCable can deplete AR's connection pool

### ISSUE THREAD

**Issue by AndreasWurm** [rails/rails#23778] opened 2016-02-19 14:39 UTC
Normally ActionCable::ServerWorker::ActiveRecordConnectionManagement takes care to ensure connections are checked back into the pool. This is not ensured when using ActiveRecord from within a ActionCable::Channel::Streams stream_form/stream_for callback.

Observed this behaviour in rails 5.0.0.beta2.

Example:
```
class MyChannel < ApplicationCable::Channel
  def subscribed
    queue = "my_channels_queue"
    stream_from queue, -> (message) do
      # open a db connection, this will not be returned to the pool
      ActiveRecord::Base.connection
      transmit ActiveSupport::JSON.decode(message), via: queue
    end
  end
end
```

**Comment by maclover7** [comment] 2016-02-19 15:09
If a user is manually calling `ActiveRecord::Connection`, shouldn't they have to return it to Active Record when they are done using the connection? Not sure it is Action Cable's responsibility to cleanup here...

**Comment by AndreasWurm** [comment] 2016-02-19 15:56
well its just an example.. if i do MyModel.find(1) or any AR call instead the same thing happens, and my expectation was it just works and its taken care of.

The Readme states 
> You have access to your full domain model written with Active Record or your ORM of choice.

and has examples using active record without managing connections manually, and it works everywere else since ActionCable::ServerWorker::ActiveRecordConnectionManagement takes care of things, just not in the provided example. Personally I consider this a bug since I dont think anyone would expect that for this method its their responsibility to manage the pool, were everywere else its taken care of.

**Comment by zhu1230** [comment] 2016-02-20 08:15
+1

**Comment by benoitongit** [comment] 2016-02-21 01:23
Same issue, I get the following error after using ActiveRecord from an ApplicationCable::Channel class:
"ActiveRecord::ConnectionTimeoutError - could not obtain a connection from the pool within 5.000."
Tested with last commit: 22c318d6cfe39933b2f5adb383cb6f0153f505d3

**Comment by dhh** [comment] 2016-02-24 11:11
@jeremy Same issue as we were seeing, it appears.

**Comment by doits** [comment] 2016-02-25 12:12
After updating to `5.0.0.beta3`, I get a lot of `ActiveRecord::ConnectionTimeoutError` when running a large test suite of my rails app (including a lot of feature specs). With `5.0.0.beta2` it does not happen. Only mysterious thing: I don't use `ActionCable` at all. So either I hit a different bug or it is the same but the source doesn't lie in `ActionCable` but goes deeper.

**Comment by dhh** [comment] 2016-02-25 12:43
@jeremy ^

**Comment by chashmeetsingh** [comment] 2016-02-25 19:59
I tried many configurations for the gem file bouncing between beta2 and 3 and found that the issue is caused by the active job gem
Hope this helps!

**Comment by jeremy** [comment] 2016-02-25 20:30
The issue we're seeing is that the AJ async adapter creates enormous executor pools for each queue, quickly exhausting the db conn pool.

Quick hack in `config/environments/development.rb`:
```ruby
ActiveJob::AsyncJob.const_set :DEFAULT_EXECUTOR_OPTIONS, ActiveJob::AsyncJob::DEFAULT_EXECUTOR_OPTIONS.merge(min_threads: 0, max_threads: 2, idletime: 10)
```

The defaults now are min = cpu count, max = 10 * cpu count, idle time = 1 minute.

If you have 4 CPUs and 10 different AJ queue names, that means up to 400 db connections per process.

Large pools are OK, really, but they need to release connections back to the pool after performing each job. And, ideally, they'd use a separate db connection pool that doesn't compete for the same resources as serving web requests.

**Comment by chashmeetsingh** [comment] 2016-02-25 20:42
@jeremy You mean something like this?
https://github.com/chashmeetsingh/rails/blob/master/activejob/lib/active_job/async_job.rb

**Comment by matthewd** [comment] 2016-02-25 20:43
I expect to be able to address this via #23807.

**Comment by chashmeetsingh** [comment] 2016-02-25 20:47
ok great :)

**Comment by jeremy** [comment] 2016-02-25 21:17
@matthewd That is… awesome! 🤘 Tames many beasts.

Another less-hacky workaround. Explicitly release connections after performing jobs in dev/test:
```ruby
  # Dev and test use the async adapter which sets up large
  # worker pools per queue, easily exhausting available db conns.
  # That's only a problem because we don't release connections
  # back to the pool by default.
  if queue_adapter.is_a? ActiveJob::QueueAdapters::AsyncAdapter
    after_perform do
      ActiveRecord::Base.clear_active_connections!
    end
  end
```

**Comment by doits** [comment] 2016-02-25 21:55
>     if queue_adapter.is_a? ActiveJob::QueueAdapters::AsyncAdapter

Ah, that is exactly the problem I have. With the latest change of ActiveJob, from the [changelog](https://github.com/rails/rails/blob/master/activejob/CHANGELOG.md) ...

> Change the default adapter from inline to async. [...]

... my tests (including a lot of mail specs) began using the as `AsyncAdapter` and therefore the problem manifested itself. Nice the puzzle fits together for me now ;-)

**Comment by jeremy** [comment] 2016-03-01 20:27
@AndreasWurm Could you check with master now that #23807 merged?

**Comment by AndreasWurm** [comment] 2016-03-02 01:06
@jeremy 
changed to rails master but either I get this error from javascript "Uncaught Error: Existing connection must be closed before opening" and I cant send through the channel since its undefined or puma just stops responding at all. So cant really test the scenario. Also just from looking at the patch I suspect it doesnt fix my original issue since it basically just does the same as before: callbacks on work, subscribe and unsubscribe.

In my original post i missed to report Im using the redis adapter.

**Comment by AndreasWurm** [comment] 2016-03-07 17:07
with the current master and only one channel it works again. the error still exists and connections are not checked back into the pool when used from inside a stream_from callback.

**Comment by jeremy** [comment] 2016-03-07 18:46
@AndreasWurm Confirm. Manual connection management is still required in stream blocks, but shouldn't be. Working on it.

**Closed** 2016-04-14 17:25 UTC
Labels: actioncable, activerecord
