### ISSUE TITLE
has_many :through with `include Comparable`

### ISSUE THREAD

**Issue by jnimety** [rails/rails#27595] opened 2017-01-06 18:57 UTC
I'm not sure this is a bug but this has worked in previous versions of rails and stopped working in rails 5.0.1. It was a huge pain to track down so if nothing else maybe someone will find this if they're running into a similar issue.

If a has_many :through join model includes Comparable then creating join records through the association does not set the foreign key for all but the first record. For example, in the test below, `Event.create(user_ids: [user1.id, user2.id])` will create two Invite join records but only the first one is assigned an event_id.
 
### Steps to reproduce

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "5.0.1"
  #gem "activerecord", "5.0.0.1"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection adapter: "postgresql"
ActiveRecord::Base.connection.drop_database "test_has_many_through_with_comparable"
ActiveRecord::Base.connection.create_database "test_has_many_through_with_comparable"
ActiveRecord::Base.establish_connection adapter: "postgresql", database: "test_has_many_through_with_comparable"
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :events, force: true do |t|
  end

  create_table :invites, force: true do |t|
    t.integer :event_id
    t.integer :user_id
  end

  create_table :users, force: true do |t|
  end
end

class Event < ActiveRecord::Base
  has_many :invites

  has_many :users, :through => :invites
end

class Invite < ActiveRecord::Base
  include Comparable

  belongs_to :event
  belongs_to :user
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_has_many_through_with_comparable
    user1 = User.create
    user2 = User.create

    event = Event.create(user_ids: [user1.id, user2.id]) # Invite#event_id does not get set for user2

    assert_equal event.invites.count, 2
  end
end
```

### Expected behavior

Correctly create joins records with foreign_keys correctly populated

### Actual behavior

foreign_keys are nil

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

**Comment by utilum** [comment] 2017-01-06 19:54
Can reproduce.

**Comment by jtrost** [comment] 2017-01-06 19:54
One thing that stands out about your code is that the Invite class does not define the `<=>` operator. The [Comparable documentation](https://ruby-doc.org/core-2.3.3/Comparable.html) says:
>The class must define the <=> operator, which compares the receiver against another object, returning -1, 0, or +1 depending on whether the receiver is less than, equal to, or greater than the other object.

It's not clear what the Invite class is comparing, however if you add this method to the class then the test will pass.
````ruby
def <=>(other)
  1
end
````

**Comment by jnimety** [comment] 2017-01-06 20:02
It still fails if I add a `score` column and use

```
def <=>(other)
  other.score <=> self.score
end
```

**Comment by alexcameron89** [comment] 2017-01-06 20:25
This looks to be fixed on master by @sgrif with 15ddd5179c746a2201b9805edf0764f515da8d7a.

**Comment by jnimety** [comment] 2017-01-06 20:48
fantastic, thanks for looking into this.

**Comment by sgrif** [comment] 2017-01-06 20:53
Hm... That was committed to 5-0-stable several months before 5.0.1 was released though. I'm curious why it wasn't included.

**Comment by sgrif** [comment] 2017-01-06 20:55
I'm being thick. That commit was in 5.0.1. I don't think that commit fixed this issue.

**Comment by jnimety** [comment] 2017-01-06 21:09
here's an updated test, it fails as long as the compare method returns equality (0).

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "5.0.1"
  #gem "activerecord", "5.0.0.1"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection adapter: "postgresql"
ActiveRecord::Base.connection.drop_database "test_has_many_through_with_comparable"
ActiveRecord::Base.connection.create_database "test_has_many_through_with_comparable"
ActiveRecord::Base.establish_connection adapter: "postgresql", database: "test_has_many_through_with_comparable"
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :events, force: true do |t|
  end

  create_table :invites, force: true do |t|
    t.integer :event_id
    t.integer :user_id
  end

  create_table :users, force: true do |t|
  end
end

class Event < ActiveRecord::Base
  has_many :invites

  has_many :users, :through => :invites
end

class Invite < ActiveRecord::Base
  include Comparable

  belongs_to :event
  belongs_to :user

  def <=>(other)
    0
  end
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_has_many_through_with_comparable
    user1 = User.create
    user2 = User.create

    event = Event.create(user_ids: [user1.id, user2.id]) # Invite#event_id does not get set for user2

    assert_equal event.invites.count, 2
  end
end
```

**Comment by maclover7** [comment] 2017-01-06 22:54
Marking as a regression since the tests pass on `4-2-stable`, but are failing on v5.0.1. Investigating...

**Comment by kamipo** [comment] 2017-01-07 12:25
Fixed in #27442 on master.

**Comment by maclover7** [comment] 2017-01-07 13:31
👍 Added `needs backport` label on that PR, so hopefully will be backported to `5-0-stable` soon by the core team.

**Comment by maclover7** [comment] 2017-01-08 19:25
Going to close out this issue since the PR that fixes this bug has been backported to `5-0-stable` via 70f13384270e9609de200b0b29e82ce515487d24.

**Closed by maclover7** 2017-01-08 19:25 UTC
Labels: activerecord, attached PR, regression, With reproduction steps
