### ISSUE TITLE
ActiveSupport::SafeBuffer losts $1 in block of String#gsub

### ISSUE THREAD

**Issue by tdtds** [rails/rails#18985] opened 2015-02-18 09:04 UTC
ActiveSupport::SafeBuffer#html_safe injected into String instances, it losts captured string ($1...) in the block of String#gsub. see:

```ruby
require 'active_support/core_ext/string/output_safety'
'abc'.html_safe.gsub(/(b)/){p $1} # => nil
'abc'.gsub(/(b)/){p $1} # => "b"
```

**Comment by matthewd** [comment] 2015-02-18 11:40
Duplicate of #1555 (see also #12672)

**Closed by matthewd** 2015-02-18 11:40 UTC
