### ISSUE TITLE
Database default value is not set when property is not a permitted param.

### ISSUE THREAD

**Issue by martndemus** [rails/rails#19047] opened 2015-02-23 16:52 UTC
I have a `User` model with a `role` property (see below). When I do `User.create!(email: 'me@example.org')`, in the console, the user gets created as you would expect, the email will de the one I gave and the `role` is set to the default (`'owner'`). When I call `POST /users` with `{ "user": { "email": "me@example.org", "role": "member" } }` then the validation fails, of which I expect it shouldn't. Does Rails do something special when creating a model with a params object? (did try casting the params to hash, did not work).

```ruby
class User < ActiveRecord::Base 
  validates :email, presence: true
  validates :role, inclusion: { in: %w{member owner} }
end
```
```ruby
class UsersController < ApplicationController
  def create
    @user = User.create!(user_params)
  end

  def user_params
     params.require(:user).permit(:email)
  end
end
```
```
                                        Table "public.users"
     Column      |            Type             |                     Modifiers                      
-----------------+-----------------------------+----------------------------------------------------
 id              | integer                     | not null default nextval('users_id_seq'::regclass)
 email           | character varying           | not null
 role            | character varying(16)       | not null default 'member'::character varying
```

**Comment by rafaelfranca** [comment] 2015-02-23 17:19
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by cristianbica** [comment] 2015-02-23 21:03
I've created a test https://gist.github.com/cristianbica/4e615aa1bfe87b288a38 and I cannot reproduce. @martndemus what rails version are you using?

**Comment by martndemus** [comment] 2015-02-24 07:36
I am using Rails 4.2.
I will give it a go to reproduce it using the template.

**Comment by cristianbica** [comment] 2015-02-24 08:38
cannot reproduce with 4.2.0 also https://gist.github.com/cristianbica/4a5a5e8cdeabaa189662

**Comment by martndemus** [comment] 2015-02-24 08:52
Cannot reproduce it myself too.
Did a `rake db:reset`, this (I think) fixed it for me. Perhaps a glitch in migrations?

**Comment by cristianbica** [comment] 2015-02-24 09:05
Perhaps. Anyway I'm closing this as we cannot reproduce. Thanks

**Closed by cristianbica** 2015-02-24 09:05 UTC
Labels: activerecord, needs feedback
