### ISSUE TITLE
`request.url` does not take `relative_url_root` into account

### ISSUE THREAD

**Issue by gioele** [rails/rails#24393] opened 2016-04-01 16:34 UTC
The URL returned by `request.url` ignores the value of `Rails.config.action_controller.relative_url_root`.

The [documentation of `ActionDisplay::HTTP:URL#url`](https://github.com/rails/rails/blob/8a8325766a870df0abcf4662fb71660173737253/actionpack/lib/action_dispatch/http/url.rb#L193-L200) says that it "Returns the complete URL used for this request". This is not true for projects that are not mounted under `/`.

This means that projects that use `request.url` cannot work unmodified when mounted under other directories with `RAILS_RELATIVE_URL_ROOT`.
### Steps to reproduce
1. Create a minimal Rails application with the model "Foo".
2. In `app/view/foo/index.html.erb` write
   
   ```
   request.url = <%= request.url %>
   relative_url = <%= controller.relative_url_root %>
   ```
3. Setup Apache
   
   ```
   RewriteRule      ^/bar(.*)$  http://localhost:4000/$1  [P,L]
   ProxyPassReverse  /bar       http://localhost:4000/
   ```
4. Launch the Rails application
   
   ```
   RAILS_RELATIVE_URL_ROOT=/bar bundle exec bin/rails -p 4000
   ```
5. Visit `http://localhost/bar/foo`
### Expected behavior

The page should display

```
request.url = http://localhost/bar/foo
relative_url = /bar
```
### Actual behavior

The page displays

```
request.url = http://localhost/foo
relative_url = /bar
```

Please note the missing **`/bar`** in `request.url`.
### System configuration

**Rails version**: 4.2.5

**Ruby version**: 2.2.3

**Comment by maclover7** [comment] 2016-04-01 16:48
Hmm, I think this is more a case of Action Dispatch not knowing about `relative_url_root` -- it seems like it is only available within Action Controller and Railties. Looking into how this context might be integrated into Action Dispatch...

**Comment by maclover7** [comment] 2016-04-01 21:41
Opened up PR #24396 to try and tackle this.

**Comment by pixeltrix** [comment] 2016-04-03 12:32
The path for `#url` actually comes from the Rack method `#fullpath` which is `SCRIPT_NAME` and `PATH_INFO` concatenated. This should be correct - the `SCRIPT_NAME` should be `/bar` and the `PATH_INFO` should be `/foo`. Looking at the example code your `RewriteRule` looks odd - that would rewrite the request path to `/foo` before it hits the Rails app so it never sees the `/bar`. I haven't set up an Apache/Rails sub-directory config in years so I'll have to double check the docs on this.

**Comment by gioele** [comment] 2016-04-04 09:26
@pixeltrix: for `SCRIPT_NAME` to be `/bar` inside the Rails app, the Apache configuration should be modified to

```
RewriteRule      ^/bar(.*)$  http://localhost:4000/bar$1  [P,L]
ProxyPassReverse  /bar       http://localhost:4000/bar
```

But then, a Rails server started with

```
RAILS_RELATIVE_URL_ROOT=/bar bundle exec bin/rails -p 4000
```

will complain that

> No route matches [GET] "/bar"

when `http://localhost/bar` is accessed.

**Comment by gioele** [comment] 2016-04-04 12:53
A change that could solve this problem (while being less intrusive than #24396) is to

1. Generate a default `config.ru` that takes `relative_url_root` into account (PR #24412):

    ```patch
    -run Rails.application
    +map Rails.application.config.relative_url_root || '/' do
    +  run Rails.application
    +end
    ```

2. Document that the `RAILS_RELATIVE_URL_ROOT` variable must be set to the same value of `SCRIPT_NAME` (and maybe complain if the two differ).

**Comment by pixeltrix** [comment] 2016-04-04 21:01
@gioele unfortunately that `map` won't work in situation where your forwarding to a different port because of [this check in Rack::URLMap][1]:

``` ruby
  unless casecmp?(hHost, host) \
      || casecmp?(sName, host) \
      || (!host && (casecmp?(hHost, sName) ||
                    casecmp?(hHost, sName+':'+sPort)))
    next
  end
```

The `host` variable is `nil` so it all comes down to the last check and the ports don't match. You also have the issue of `public/assets` being in a subdirectory which adds complications.

[1]: https://github.com/rack/rack/blob/1.6.4/lib/rack/urlmap.rb#L51-L56

**Comment by maclover7** [comment] 2017-03-28 22:47
Previously reported at #22074

**Comment by wnewbery** [comment] 2017-05-31 10:35
Is the URL helpers (at least as in #22074) actually related? Been trying to locate the relevant Rails source code, but did not find anything yet (especially when the helpers are used outside a request, so no request URI at all).

Also in direct regards to this bug, I just tested my application and with 5.1.1 running behind Apache Passenger, `request.url` in my controller does return the correct URL in a controller from a fresh app.

Extract from my Apache config:
```
Alias /sub-app /home/ubuntu/rails/sub_app/public
<Directory /home/ubuntu/rails/sub_app/public>
    Allow from all
    Options -Multiviews
    Require all granted
    PassengerEnabled on
    PassengerAppEnv development
    PassengerBaseURI /sub-app
    PassengerAppRoot /home/ubuntu/rails/sub_app
</Directory>
```
`routes.rb`
```ruby
Rails.application.routes.draw do
  get "/", to: "home#show", as: :home
end
```
In my controller, outputting values:
```
> ENV["SCRIPT_NAME"]
nil
> ENV["RAILS_RELATIVE_URL_ROOT"]
"/sub-app"
> request.url
"https://example.com/sub-app/"
> home_path
"/sub-app/"
> ActionController::Base.helpers.javascript_path "application"
"/sub-app/assets/application-bca9270d8fe15fafc50c40002915a778c51a654b1f2a3ecc78c39e380845d2b2.js"
```
The default `config.ru` for reference is just:
```ruby
require_relative 'config/environment'
run Rails.application
```

Running `RAILS_RELATIVE_URL_ROOT=/sub-app rails console`
```
> ENV["RAILS_RELATIVE_URL_ROOT"]
"/sub-app"
> helpers.javascript_path "application"
"/sub-app/assets/application-bca9270d8fe15fafc50c40002915a778c51a654b1f2a3ecc78c39e380845d2b2.js"
> app.home_path
"/"
```

Making `request.url` right under Passenger at least, asset helpers always right, but url helpers wrong outside a controller/view/request (ignored RAILS_RELATIVE_URL_ROOT).

**Comment by jsmartt** [comment] 2018-08-08 15:45
This is still an issue in Rails 5.1.6. Any plans to tackle it?

**Comment by remofritzsche** [comment] 2019-08-29 11:57
This is still an issue in Rails 6 as well. It would be very nice if this could get fixed.

**Comment by nicolrx** [comment] 2020-08-03 16:22
Why is this issue closed?

**Comment by PWKad** [comment] 2020-08-03 20:05
@nicolrx it is not closed.

Is there a workaround that can help with patching this?

**Comment by kikonen** [comment] 2021-05-08 18:57
Was just hit with this issue, and was hopigng to find some solution

**Comment by pixeltrix** [comment] 2021-05-08 19:41
@kikonen does using `request.original_url` work for you?

**Comment by kikonen** [comment] 2021-05-08 20:40
Not strictly, tried to setup rails app to run into docker via separate nginx docker image doing proxy into app, so that app is runing under specfiic path. In production using currently nginx+passenger, which works in "somewhat similar" config, aka. app running in subpath in server. Thus few things to resolve, and and one seems to be related into handling of relative_url_root in path helpers.

**Comment by pixeltrix** [comment] 2021-05-09 06:49
@kikonen the `original_script_name` option is used by engines to ensure that the url generated is correct since they can be mounted under a prefix the engine author doesn't control.

I'm going to close this issue for the following reasons:

1. `request.url` is a Rack method so is out of scope for Rails issues
2. `request.url` reflects the environment passed to a Rack application - e.g. a Rails engine or Sinatra app, and changing the behaviour of the method to include `relative_url_root` will likely break most of them.
3. `request.original_url` provides the full url as passed to the Rails application - a combination of the environment variables SCRIPT_NAME, PATH_INFO and QUERY_STRING. If this isn't correct then it's likely your reverse proxy configuration needs fixing.

@kikonen if you think there's a bug in Rack and/or Rails with how it's interpreting the CGI environment variables please create a new issue in the relevant repo with a detailed description of how to reproduce the problem, including the config for nginx, passenger, etc. so that we can properly diagnose it.

Thanks everyone 👍🏻

**Closed by pixeltrix** 2021-05-09 06:49 UTC
Labels: With reproduction steps, actionpack, attached PR

**Comment by arianf** [comment] 2021-05-17 21:21
This is still broken why was this closed

```
(byebug) MyApp::Application.routes.url_helpers.projects_path
"/projects"
(byebug) MyApp::Application.routes.url_helpers.projects_url
"http://localhost/projects"
(byebug) MyApp::Application.config.relative_url_root
"/sp"
```

**Comment by pixeltrix** [comment] 2021-05-17 23:35
@arianf the reasons I closed it are the ones I gave in my previous comment - your examples are not related to `request.url` and I'll respond on the issue you opened about those.
