### ISSUE TITLE
ActionMailbox passes an empty string for Attachments on submit

### ISSUE THREAD

**Issue by joshzandman** [rails/rails#45088] opened 2022-05-13 16:36 UTC
### Steps to reproduce
When submitting the local form from `/rails/conductor/action_mailbox/inbound_emails` in development, Rails is passing an empty string to the attachments array, resulting in this error `undefined method original_filename' for "":String`.

### Expected behavior
When submitting the form with or without an attachment, there should not be an empty string that gets passed into the array.

### Actual behavior
`"attachments"=>[""]`

### System configuration
**Rails version**: `Rails 7.0.2.4`

**Ruby version**: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`

**Comment by dorianmariefr** [comment] 2022-05-14 05:35
Reproduced it with:

- `rails new action-mailbox-example`
- `bundle`
- `rails s`
- Going to http://localhost:3000/rails/conductor/action_mailbox/inbound_emails
- [New inbound email by form](http://localhost:3000/rails/conductor/action_mailbox/inbound_emails/new)
- Submitting the form

<img width="1087" alt="Screen Shot 2022-05-14 at 07 34 28" src="https://user-images.githubusercontent.com/58794487/168412237-7b141ee0-5529-4ad3-8790-3f3a0162a0da.png">

```
NoMethodError (undefined method `original_filename' for "":String

            mail.add_file(filename: attachment.original_filename, content: attachment.read)
                                              ^^^^^^^^^^^^^^^^^^):
  
actionmailbox (7.0.3) app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb:26:in `block (2 levels) in new_mail'
actionmailbox (7.0.3) app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb:25:in `each'
actionmailbox (7.0.3) app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb:25:in `block in new_mail'
<internal:kernel>:90:in `tap'
actionmailbox (7.0.3) app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb:23:in `new_mail'
actionmailbox (7.0.3) app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb:17:in `create'
actionpack (7.0.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.0.3) lib/abstract_controller/base.rb:215:in `process_action'
actionpack (7.0.3) lib/action_controller/metal/rendering.rb:53:in `process_action'
actionpack (7.0.3) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
activesupport (7.0.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
actiontext (7.0.3) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.3) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.3) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
```

**Comment by dorianmariefr** [comment] 2022-05-14 05:48
The source of the form (I have the Dashlane password manager extension):

```erb
  <div>
    <%= form.label :attachments, "Attachments" %><br>
    <%= form.file_field :attachments, multiple: true %>
  </div>
````

```html
<div>
    <label for="mail_attachments">Attachments</label><br>
    <input name="mail[attachments][]" type="hidden" value="" autocomplete="off"><input multiple="multiple" type="file" name="mail[attachments][]" id="mail_attachments" data-dashlane-rid="f82047ec266059ab" data-form-type="other">
  </div>
```

The hidden input that sends an empty string seems to be on purpose.

See https://stackoverflow.com/questions/8929230/why-is-the-first-element-always-blank-in-my-rails-multi-select-using-an-embedde for solutions 

See https://github.com/rails/rails/blob/a4fb045e0d23c978b3fbb245f4327e200bf22308/actionmailbox/app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb#L25-L27

**Comment by dorianmariefr** [comment] 2022-05-14 05:58
So the patch would be:

```diff
diff --git a/app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb b/app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb
index 62523cf..9220a57 100644
--- a/app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb
+++ b/app/controllers/rails/conductor/action_mailbox/inbound_emails_controller.rb
@@ -22,7 +22,7 @@ module Rails
       def new_mail
         Mail.new(mail_params.except(:attachments).to_h).tap do |mail|
           mail[:bcc]&.include_in_headers = true
-          mail_params[:attachments].to_a.each do |attachment|
+          mail_params[:attachments].to_a.select(&:present?).each do |attachment|
             mail.add_file(filename: attachment.original_filename, content: attachment.read)
           end
         end
```

It also needs a test for a pull request

**Comment by joshzandman** [comment] 2022-05-14 06:01
On it, thanks Dorian!

**Comment by SkipKayhil** [comment] 2022-05-14 13:41
Hey @joshzandman, thanks for the report! (and @dorianmariefr for investigating!). I believe this will be fixed by #44702, can either of you confirm?

**Comment by joshzandman** [comment] 2022-05-14 15:01
Ah yes, I can confirm that is the same issue with a fix and passing test.

It would be helpful though if that test also included a file inside the attachments array so that multiple uploads - one being an empty string - is also tested.

**Comment by SkipKayhil** [comment] 2022-05-14 15:07
> My pleasure! I can confirm that is the same issue with a fix and passing test.
> 
> It would be helpful though if that test also included a file inside the attachments array so that multiple uploads - one being an empty string - is also tested.

Definitely, feel free to leave feedback on the PR

**Closed** 2022-05-15 21:07 UTC
Labels: attached PR, actionmailbox
