### ISSUE TITLE
 rails app:update:bin creates and then removes yarn

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#40868] opened 2020-12-17 12:04 UTC
### Steps to reproduce
Enter into a existing project with bin/yarn
Run

```bash
$ rails app:update:bin
```
This will first create yarn and then remove yarn at the same time.

### Expected behavior
bin/yarn is available 

### Actual behavior
```
$ rails app:update:bin
       exist  bin
    conflict  bin/rails
Overwrite /home/kireto/axles/code/is-layout/test/dummy/bin/rails? (enter "h" for help) [Ynaqdhm] n
        skip  bin/rails
    conflict  bin/rake
Overwrite /home/kireto/axles/code/is-layout/test/dummy/bin/rake? (enter "h" for help) [Ynaqdhm] n
        skip  bin/rake
    conflict  bin/setup
Overwrite /home/kireto/axles/code/is-layout/test/dummy/bin/setup? (enter "h" for help) [Ynaqdhm] n
        skip  bin/setup
      create  bin/spring
      create  bin/yarn
      remove  bin/spring
      remove  bin/yarn
```
### System configuration
**Rails version**: 6.1

**Ruby version**: 2.6.5

### Update 1
I've workaround this by copying a bin/yarn from another project and it works. 

### Update 2

Second project, same thing
```
$ rails app:update:bin
       exist  bin
    conflict  bin/rails
Overwrite /home/kireto/axles/code/is-core/test/dummy/bin/rails? (enter "h" for help) [Ynaqdhm] n
        skip  bin/rails
    conflict  bin/rake
Overwrite /home/kireto/axles/code/is-core/test/dummy/bin/rake? (enter "h" for help) [Ynaqdhm] n
        skip  bin/rake
    conflict  bin/setup
Overwrite /home/kireto/axles/code/is-core/test/dummy/bin/setup? (enter "h" for help) [Ynaqdhm] n
        skip  bin/setup
    conflict  bin/spring
Overwrite /home/kireto/axles/code/is-core/test/dummy/bin/spring? (enter "h" for help) [Ynaqdhm] n
        skip  bin/spring
      create  bin/yarn
      remove  bin/spring
      remove  bin/yarn
```

**Comment by rafaelfranca** [comment] 2020-12-17 18:59
Was `skip-javascript` option passed, or is inside the `.railsrc` file?

**Comment by thebravoman** [comment] 2020-12-17 19:50
There is no .railsrc and the skip-javascript was not passed when the project was created. 

Actually the first commit in this project was 
```
 Date:   Wed Jul 26 18:41:45 2017 +0300
```
and since we are running about 150 of them as they are extensions and as we have a detailed tutorials how to create new extensions and in this tutorials we've never set skip-javascript.

**Comment by rafaelfranca** [comment] 2020-12-17 20:09
I'm assuming you are talking about those application being Rails plugins? If that is the case `skip-javascript` is default to true in Rails plugins and that is why `bin/yarn` is being deleted in those plugins.

https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/generators/app_base.rb#L73

https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/generators/rails/app/app_generator.rb#L98-L100

Removing `bin/yarn` when `skip-javascript` is true and `skip-javascript` being true in a Rails plugin was always the same, even in Rails 6.0.

Do you plugins use JavaScript libraries using yarn?

**Comment by thebravoman** [comment] 2020-12-17 20:55
Yes. They are rails plugins although we use them in a different way, but that is a detail.
I was not aware that rails plugins had skip-javascript by default

As they are plugins we leave it to the plugin developers to decide if they would like to use sprockets or webpacker. So some of the plugins use yarn.

> Removing bin/yarn when skip-javascript is true and skip-javascript being true in a Rails plugin was always the same, even in Rails 6.0.

Probably it was. What happened is that saw that the rake assets:precompile was giving an error that there is no bin/yarn and I went on to try to add yarn to the project with rake app:update:bin.

**Comment by rafaelfranca** [comment] 2020-12-18 21:17
This problem of `rake assets:precompile` giving an error is already fixed on the 6-1-stable branch. Can you check that branch and see if it fix your issue?

**Comment by floehopper** [comment] 2020-12-19 10:20
@rafaelfranca 

> What happened is that I saw rake assets:precompile was giving an error that there is no bin/yarn and I went on to try to add yarn to the project with rake app:update:bin.

I'm seeing what sounds like the same problem in a standard Rails app, i.e. not a plugin, when upgrading to v6.1.0. We are using sprockets for both JS and CSS and so I'm pretty sure we didn't add the `--skip-javascript` option when we created the app.

Like @thebravoman I've worked around the problem by manually creating a `bin/yarn` script from [the template source](https://github.com/rails/rails/blob/v6.1.0/railties/lib/rails/generators/rails/app/templates/bin/yarn.tt).

Assuming Rails still supports using sprockets for both JS and CSS, I've always found it a bit confusing that we see the following message when running `assets:precompile`: "Yarn executable was not detected in the system." When in fact, we don't need yarn to be installed, because we're using sprockets. Do you have any thoughts on this? Is it worth me opening a separate issue or PR?

**Comment by thebravoman** [comment] 2020-12-19 18:46
Thanks rafaelfranca. I did follow the changes for 6-1 stable and I saw the changes you are referring. It was connected with a previous issue I reported.

The changes does fix my issue.

**Comment by rahearn** [comment] 2020-12-20 14:56
> I'm seeing what sounds like the same problem in a standard Rails app

Me too, part of the problem is that `rake app:update:bin` removes `bin/yarn` if it thinks that `--skip-javascript` was passed, but it determines that flag based on whether `bin/yarn` existed when `rake app:update:bin` was called. You can break out of the loop by running `rake app:binstub:yarn` first, but then you have yarn installed when the app doesn't need it.

The fix on 6-1-stable worked for my app, hopefully it's released soon.

**Comment by samstickland** [comment] 2020-12-22 14:09
I also had this problem on an application I am upgrading from Rails 6.0 using webpacker that had no `.railsrc` file.

Doing `rake app:binstub:yarn` first fixed my issue. After doing that and running `rake app:update:bin` it made some further changes to `bin/setup`

![image](https://user-images.githubusercontent.com/9951571/102897034-48dda800-445f-11eb-9ccd-eb7d3c841f33.png)

**Comment by doits** [comment] 2020-12-22 14:23
> part of the problem is that rake app:update:bin removes bin/yarn if it thinks that --skip-javascript was passed, but it determines that flag based on whether bin/yarn existed when rake app:update:bin was called

This confused me too while I worked on that issue. Maybe in the future it should be saved as a flag somewhere (in `config/application.rb`, `Rails.application.config.skip_javascript`?), because the check for `bin/yarn` is not reliable as we noticed.

**Comment by doits** [comment] 2020-12-22 14:26
> Assuming Rails still supports using sprockets for both JS and CSS, I've always found it a bit confusing that we see the following message when running assets:precompile: "Yarn executable was not detected in the system." When in fact, we don't need yarn to be installed, because we're using sprockets. Do you have any thoughts on this? Is it worth me opening a separate issue or PR?

This is fixed in https://github.com/rails/rails/tree/6-1-stable already, no warning (and more importantly breakage) anymore.

**Closed** 2020-12-29 03:18 UTC
