### ISSUE TITLE
Setting the TimeZone in an initializer instead of application.rb has unexpected effect

### ISSUE THREAD

**Issue by zavan** [rails/rails#24748] opened 2016-04-27 01:24 UTC
### Steps to reproduce
Instead of setting `config.time_zone` in `application.rb` (which works properly), create an initializer and set the timezone there with: `Rails.application.config.time_zone = 'Brasilia'`.

This works with other configurations, such as `Rails.application.config.active_job.queue_adapter = :delayed_job`, so it probably should work for setting the timezone too.

### Expected behavior
When running `Rails.application.config.time_zone` the configured timezone is shown, and everything, including `Time.zone`, must be in the configured timezone.

### Actual behavior
When running `Rails.application.config.time_zone` the configured timezone is shown, but everything, including `Time.zone`, is still UTC.

### System configuration
**Rails version**:
master at f03c27cad2d3b4a9751cccdc3834f719f1cfbaa2 (Rails 5.0.0.beta3)

**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by maclover7** [comment] 2016-04-27 01:28
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by zavan** [comment] 2016-04-27 01:43
@maclover7 I'm not sure how to initialize a Rails application so that I'm able to call `Rails.application.config.time_zone =` in the test.

**Comment by zavan** [comment] 2016-04-27 01:57
@maclover7 I'm not sure how to setup this so that I can call `Rails.application.config.time_zone = 'Brasilia'` and assert what `Rails.application.config.time_zone` and `Time.zone` returns.

**Comment by repinel** [comment] 2016-04-27 02:45
This seems to happen because the Railtie initializer in [active_support/railtie.rb](https://github.com/rails/rails/blob/791bdf6fb350b5cb272e4277c1b2b3d04beb7a35/activesupport/lib/active_support/railtie.rb#L18) runs before the initializer files.

Having it as a `after_initialize` could be a fix. In the same file, wouldn't the same apply to `config.beginning_of_week`?

**Comment by vipulnsward** [comment] 2016-04-29 14:59
`Rails.application.config.active_job.queue_adapter` is a class attribute on AJ. Its ok to override it(In fact we have a feature to allow to do so on every class.).

Allowing this for `Time.zone_default` is going to be problematic. Imagine this flow:
- We do/don't set `Time.zone_default` as is right now(before initializers).
- Some user or internal initializer uses some time zone config.
- Some other user initializer sets another time zone config using `Rails.application.config.time_zone`
- We end up with different time zone defaults run for one set of initializers vs the ones that are run after setting `Rails.application.config.time_zone`.


I think we should document this instead, thoughts @fxn ?

**Comment by alfie-max** [comment] 2016-04-30 18:13
@vipulnsward I get your point regarding the flow you described. But isn't that the case with all the other `config` ? I mean whatever is set in `application.rb` gets initialised before the ones specified in other `initializer` files (which there may or may not be more than once) and later on get overridden.

Which i believe happens here too with `Rails.application.config.time_zone`, as @zavan has described its value gets changed. But just the expected behaviour is what's missing. So isn't that an anomaly? that the config value and the expected behaviour are different?

Please do correct me if i'm wrong somewhere.

**Comment by fxn** [comment] 2016-05-02 18:19
In general, configuration specific to the application object needs to go either in _config/application.rb_ or in _config/environments/#{Rails.env}.rb_, you can't just assign to an arbitrary config point in _config/initializers_ and expect it to work.

Setting the time zone was one of the examples in the generated _config/application.rb_, but that was deleted in https://github.com/rails/rails/commit/28dcadc0140dfdebe87d5e691fd709c0a9ae0bae.

This is by design. In general Rails does not know about its components. Rails has configuration settings that components pick in their railties initialization, so they are expected to have their value by the time the initialization of railties run. If you check a standard [list of initializers](https://gist.github.com/fxn/306ac7adaa66019447a768d126c1bdad) you'll see the ones in _config/initializers_ get executed very late in the boot process (`load_config_initializers`).

Unfortunately this is not very well documented right now, but at least you know now you need to move that setting.

**Closed by fxn** 2016-05-02 18:19 UTC
Labels: activesupport

**Comment by neves** [comment] 2016-07-11 04:40
@zavan , I can confirm the problem.
application.rb suggest the follow: _"Application configuration should go into files in config/initializers"_
but `config.time_zone = 'Brasilia'` does not work there, just inside application.rb

**Comment by alfie-max** [comment] 2016-07-11 05:01
@neves, please see to the explanation provided by @fxn

**Comment by frenkel** [comment] 2016-07-20 13:20
@alfie-max what are you pointing at? He didn't provide a solution, right?

**Comment by steventen** [comment] 2016-12-28 03:33
`# Application configuration should go into files in config/initializers ...` in `config/application.rb` is confusing
