### ISSUE TITLE
undefined method `existent' coming from active_support/i18n_railtie.rb

### ISSUE THREAD

**Issue by schneems** [rails/rails#21228] opened 2015-08-13 20:33 UTC
On Rails master, i18n version 0.7.0

```
/Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:45:in `map': undefined method `existent' for #<String:0x007fd489ea2968> (NoMethodError)
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:45:in `block in initialize_i18n'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:41:in `each'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:41:in `initialize_i18n'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:15:in `block in <class:Railtie>'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `call'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/lazy_load_hooks.rb:44:in `each'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/initializable.rb:30:in `run'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /Users/richardschneeman/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
  from /Users/richardschneeman/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  from /Users/richardschneeman/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
  from /Users/richardschneeman/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
  from /Users/richardschneeman/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
  from /Users/richardschneeman/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
  from /Users/richardschneeman/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
  from /Users/richardschneeman/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
  from /Users/richardschneeman/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/initializable.rb:54:in `run_initializers'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/application.rb:352:in `initialize!'
  from /Users/richardschneeman/Documents/projects/codetriage/config/environment.rb:5:in `<top (required)>'
  from /Users/richardschneeman/.gem/ruby/2.2.2/gems/skylight-0.6.1/lib/skylight/probes.rb:81:in `require'
  from /Users/richardschneeman/.gem/ruby/2.2.2/gems/skylight-0.6.1/lib/skylight/probes.rb:81:in `require'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
  from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/dependencies.rb:302:in `require'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/application.rb:328:in `require_environment!'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/commands/commands_tasks.rb:147:in `require_application_and_environment!'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  from /Users/richardschneeman/Documents/projects/rails/railties/lib/rails/commands.rb:18:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

**Comment by kaspth** [comment] 2015-08-13 20:39
Thanks, @schneems :grin:

@kirs can you look into this? Here's the line: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/i18n_railtie.rb#L45

**Comment by kirs** [comment] 2015-08-14 10:02
Sure, @schneems how to reproduce it?
I tried:
* running `tasks/console`
* running rails console in generated app
* running rails rails in generated app

**Comment by schneems** [comment] 2015-08-14 21:40
Try using http://github.com/codetriage/codetriage. Setup directions on the readme should be correct, you won't need the github keys if you're not trying to log in.

 I pointed to a local copy of rails master and arel to grab from github:

```
gem 'rails', path: "../rails" # master
gem 'arel', github: 'rails/arel'
```

Then anything I run causes the error. 

```
2.2.2  ~/documents/projects/codetriage (master)
$ rails console
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <class:RouteSet> at /Users/richardschneeman/.gem/ruby/2.2.2/gems/devise-3.5.1/lib/devise/rails/routes.rb:27)
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:2: warning: already initialized constant GitHubBub::Request::USER_AGENT
/Users/richardschneeman/.gem/ruby/2.2.2/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:7: warning: previous definition of USER_AGENT was here
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:3: warning: already initialized constant GitHubBub::Request::RETRIES
/Users/richardschneeman/.gem/ruby/2.2.2/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:12: warning: previous definition of RETRIES was here
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:4: warning: already initialized constant GitHubBub::Request::GITHUB_VERSION
/Users/richardschneeman/.gem/ruby/2.2.2/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:8: warning: previous definition of GITHUB_VERSION was here
/Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:45:in `map': undefined method `existent' for #<String:0x007fe3e3e9ee58> (NoMethodError)
	from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:45:in `block in initialize_i18n'
	from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:41:in `each'
	from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:41:in `initialize_i18n'
	from /Users/richardschneeman/Documents/projects/rails/activesupport/lib/active_support/i18n_railtie.rb:15:in `block in <class:Railtie>'
```

**Comment by kirs** [comment] 2015-08-15 09:38
Thanks!
The exceptions happens because `railties_load_path` is supposed to have only `Rails::Paths::Path` instances, but in the codetriage app `railties_load_path` has one `String`:
```
config.i18n.railties_load_path.map(&:class)
=> [String, Rails::Paths::Path, Rails::Paths::Path, Rails::Paths::Path, Rails::Paths::Path, Rails::Paths::Path, Rails::Paths::Path, Rails::Paths::Path]
config.i18n.railties_load_path.first
=> "/Users/kir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/will_paginate-3.0.4/lib/will_paginate/locale/en.yml"
```

I suppose that the Railtie is somehow pushing this locale to `railties_load_path`, but I didn't find the source yet. Will continue later today :star:

**Comment by kirs** [comment] 2015-08-15 17:42
Here is the line from the will_paginate gem that adds new String path to `railties_load_path`: https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/railtie.rb#L35

Before my PR was merged, `railties_load_path` stored strings, and then to support locale reloading I changed it to store Rails::Path: https://github.com/rails/rails/pull/21124/files#diff-1073ed8063cdf047e123bfdefa114422L592

I'm not sure that we have to support both ways (with String and with Rails::Path), probably the best solution would be to update the will_paginate gem.

**Comment by kirs** [comment] 2015-08-15 17:52
@schneems could you try my fork of will_paginate? https://github.com/mislav/will_paginate/compare/master...kirs:fix/i18n-path

**Comment by schneems** [comment] 2015-08-15 19:35
:+1: works for me

```
Using will_paginate 3.0.4 from git://github.com/kirs/will_paginate.git (at fix/i18n-path)
Using tzinfo 1.2.2
Using nokogiri 1.6.6.2
Using rack-test 0.6.3
Using warden 1.2.3
Using omniauth 1.2.2 from git://github.com/schneems/omniauth.git (at schneems/hashie-breakup)
Using puma 2.11.0
Using rack-protection 1.5.0
Using vegas 0.1.11
Using fission 0.5.0
Using mail 2.6.3
Using launchy 2.3.0
Using binding_of_caller 0.7.2
Using coffee-script 2.2.0
Using crack 0.4.1
Using derailed_benchmarks 1.0.1 from source at ../derailed_benchmarks
Using dotenv-rails 0.10.0
Using foreman 0.63.0
Using faraday 0.9.0
Using net-scp 1.2.1
Using jwt 0.1.11
Using uglifier 2.1.2
Using git_hub_bub 0.0.6
Using httparty 0.11.0
Using mail_view 1.0.3
Using sprockets 2.12.4
Using mocha 1.0.0
Using rails_12factor 0.0.2
Using unicorn 4.6.3
Using redis-namespace 1.3.0
Using simplecov 0.7.1
Using slim 3.0.6
Using activesupport 5.0.0.alpha from source at ../rails
Using loofah 2.0.2
Using xpath 2.0.0
Using puma_auto_tune 0.0.2 from git://github.com/schneems/puma_auto_tune.git (at master)
Using puma_worker_killer 0.0.3 from source at ../puma_worker_killer
Using sinatra 1.4.3
Using webmock 1.20.4
Using fog-core 1.30.0
Using oauth2 0.9.3
Using rails-html-sanitizer 1.0.2
Using capybara 2.3.0
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.5
Using activemodel 5.0.0.alpha from source at ../rails
Using skylight 0.6.1
Using resque 1.24.1
Using fog-xml 0.1.2
Using fog-json 1.0.1
Using fog-local 0.2.1
Using fog-vmfusion 0.1.0
Using omniauth-oauth2 1.1.2
Using poltergeist 1.5.0
Using rails-dom-testing 1.0.6
Using activejob 5.0.0.alpha from source at ../rails
Using activerecord 5.0.0.alpha from source at ../rails
Using valid_email 0.0.10
Using resque_def 0.0.3
Using fog-atmos 0.1.0
Using fog-ecloud 0.1.1
Using fog-profitbricks 0.0.2
Using fog-terremark 0.1.0
Using fog-voxel 0.1.0
Using fog-aws 0.1.2
Using fog-brightbox 0.7.1
Using fog-powerdns 0.1.1
Using fog-radosgw 0.0.4
Using fog-riakcs 0.1.0
Using fog-sakuracloud 1.0.1
Using fog-serverlove 0.1.2
Using fog-softlayer 0.4.5
Using fog-storm_on_demand 0.1.1
Using omniauth-github 1.1.2
Using phantomjs 1.8.1.1
Using actionview 5.0.0.alpha from source at ../rails
Using fog 1.29.0
Using actionpack 5.0.0.alpha from source at ../rails
Using actionmailer 5.0.0.alpha from source at ../rails
Using railties 5.0.0.alpha from source at ../rails
Using sprockets-rails 2.3.2
Using coffee-rails 4.0.1
Using responders 2.1.0
Using jquery-rails 3.0.4
Using rails 5.0.0.alpha from source at ../rails
Using quiet_assets 1.0.2
Using sass-rails 4.0.5
Using slim-rails 3.0.1
Using teaspoon 0.7.4
Using web-console 2.2.1
Using devise 3.5.1
Using maildown 1.0.2
Using rails_autolink 1.1.5
Using wicked 1.0.0
Bundle complete! 49 Gemfile dependencies, 152 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
2.2.2  ~/documents/projects/codetriage (master)
$ rails c
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <class:RouteSet> at /Users/richardschneeman/.gem/ruby/2.2.2/gems/devise-3.5.1/lib/devise/rails/routes.rb:27)
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:2: warning: already initialized constant GitHubBub::Request::USER_AGENT
/Users/richardschneeman/.gem/ruby/2.2.2/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:7: warning: previous definition of USER_AGENT was here
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:3: warning: already initialized constant GitHubBub::Request::RETRIES
/Users/richardschneeman/.gem/ruby/2.2.2/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:12: warning: previous definition of RETRIES was here
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:4: warning: already initialized constant GitHubBub::Request::GITHUB_VERSION
/Users/richardschneeman/.gem/ruby/2.2.2/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:8: warning: previous definition of GITHUB_VERSION was here
Loading development environment (Rails 5.0.0.alpha)
irb(main):001:0>
```

**Comment by kirs** [comment] 2015-08-16 12:04
Awesome! Do you think we can close the issue?

**Comment by jonatack** [comment] 2015-08-17 12:04
Thanks! This issue bit me as well. Not sure will_paginate is being maintained though, no reaction on submitted PRs this year so far.

**Comment by kaspth** [comment] 2015-08-17 14:31
@kirs as far as I can tell `railties_load_path` is [public](https://github.com/rails/rails/blob/7985908beac7a625f545097dba9460c4355d70e4/activesupport/lib/active_support/i18n_railtie.rb#L8), so it not being able to handle strings sounds like a regression to me.

Can't we convert strings to paths?

**Comment by kirs** [comment] 2015-08-18 07:18
Your point makes sense, I'll see how we can solve it.

**Comment by kaspth** [comment] 2015-08-24 20:39
On second thought `I18n.load_path` is how other libraries should extend the load path. So modifying `will_paginate` is the way to go.

**Closed by kaspth** 2015-08-24 20:39 UTC
Labels: activesupport

**Comment by schneems** [comment] 2015-08-24 20:43
Mislav still maintains it but "no more big releases" https://twitter.com/mislav/status/633847149936013313
