### ISSUE TITLE
[BUG since 2016] cookies.delete does not remove cookies for subsequent requests (ActionController::TestCase)

### ISSUE THREAD

**Issue by alexsmartens** [rails/rails#52302] opened 2024-07-10 18:46 UTC
### Steps to reproduce

```ruby
# app/controllers/cookie_cutter_controller.rb
class CookieCutterController < ApplicationController
  def update_cookies
    cookies.delete(:test_value)
  end
end
```

```ruby
# config/routes.rb
Rails.application.routes.draw do
  post "update_cookies", to: "cookie_cutter#update_cookies"
end
```

```ruby
# spec/controllers/cookie_cutter_controller_spec.rb
require "rails_helper"

describe CookieCutterController do
  describe "#update_cookies" do
    before do
      cookies[:test_value] = "candy"
      post :update_cookies
    end

    it "deletes test_value" do
      expect(cookies[:test_value]).to be_nil # fails
    end

    context "with temp fix" do
      before do
        cookies.update(response.cookies)
      end

      it "deletes test_value" do
        expect(cookies[:test_value]).to be_nil # succeeds
      end
    end
  end
end

```
### Expected behavior
`cookies[:test_value]` should be deleted.

### Actual behavior
`cookies[:test_value]` is still present.

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: 3.3.1

**RSpec version**: 3.13

The same problem as raised in https://github.com/rails/rails/issues/37653 and https://github.com/rspec/rspec-rails/issues/1574#issuecomment-373345096.

**Comment by ghiculescu** [comment] 2024-07-15 06:18
`ActionController::TestCase` is deprecated (I know it's not mentioned in this issue, but is in your linked ones). Other than that, is this issue specific to rspec? Or could you create an [action pack test case](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) to demonstrate it?

**Comment by skipkayhil** [comment] 2024-07-17 04:20
Appears to be a duplicate of #27584, I've opened a PR to reapply the attempted fix since the reported regression was fixed in another PR.

**Closed** 2024-09-26 03:57 UTC
Labels: actionpack, attached PR
