### ISSUE TITLE
ActiveRecord::HasManyThroughOrderError

### ISSUE THREAD

**Issue by cjmblue05** [rails/rails#29123] opened 2017-05-17 09:52 UTC
I have a has_one association between 3 models, but it have an error that says "ActionView::Template::Error (Cannot have a has_many :through association 'Policy#intermediary' which goes through 'Policy#invoice' before the through association is defined.)"

```
class Policy < ApplicationRecord

    self.table_name = "gipi_polbasic"
    self.primary_key = "policy_id"

    has_one :invoice
    has_one :intermediary, through: :invoice, foreign_key: :intrmdry_intm_no
```
```
class Intermediary < ApplicationRecord
    self.table_name = "giis_intermediary"
    self.primary_key = "intm_no"

    has_one :invoice, foreign_key: :intrmdry_intm_no
    belongs_to :policy, foreign_key: :policy_id
```
```
class Invoice < ApplicationRecord
    self.table_name = "gipi_comm_invoice"
    self.primary_key = "intrmdry_intm_no"

    belongs_to :policy, foreign_key: :policy_id
    belongs_to :intermediary, foreign_key: :intrmdry_intm_no
```

**Comment by j-dexx** [comment] 2017-05-17 10:56
Shouldn't invoice have `has_one :policy, through: :intermidiary` rather than `belongs_to`?

**Comment by cjmblue05** [comment] 2017-05-18 01:02
its working on rails 5.0.3 but when i updated to rails 5.1.1 this error appeared

**Comment by nplusp** [comment] 2017-05-18 11:59
@cjmblue05 Make sure you don't have another redundant `has_one :intermediary` in your `Policy` model. Got the same error after update.

**Comment by maclover7** [comment] 2017-05-18 22:37
Can you take your example models from above and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by wakatara** [comment] 2017-05-28 18:29
I am having the same problem in 5.1.1 but not 5.0.3. Additionally, I believe it is causing erroneous Cannot Cast Type to Hash errors on the associated model (bizarrely). 

@program.species returns the Cast error, but this is a simple belongs_to model association though I have the has_many through associations on that same model.

Note: I am having this problem in padrino 0.14.0.2 using activerecord as the orm gem (not rails - but think it is AR problem.).

```
class Program < ActiveRecord::Base
  belongs_to :species
  belongs_to :org
  has_many   :trackings
  belongs_to :program_primary_contact, :class_name => 'Account', :foreign_key => :primary_contact_id, :inverse_of => :program_primary_contacts
  has_many   :photos
...
```

```
class Species < ActiveRecord::Base
  has_many :programs
  has_many :orgs, :through => :programs
  #accepts_nested_attributes_for :programs, :allow_destroy => true
  has_many :assessments
  has_many :orgs, :through => :assessments

  # Validations
  validates_presence_of   :family, :order, :genus, :species
  validates_uniqueness_of :name

  before_validation :derive_species_name
...
```

Weird associations behaviour in 5.1.1 
```
irb(main):051:0> @species.programs                                                                                                                             
  DEBUG -  Program Load (1.5ms)  SELECT  "programs".* FROM "programs" WHERE "programs"."species_id" = $1 LIMIT $2  [["species_id", 2010], ["LIMIT", 11]]       
=> #<ActiveRecord::Associations::CollectionProxy [#<Program id: 1, start_year: "2005-01-01", in_range: "No", species_id: 2010, org_id: 14, created_at: "2013-09
-17 23:00:00", updated_at: "2014-01-03 10:56:31", category: "Ex situ research", terminated_at: nil, terminated_reason: "", hidden: false, primary_contact_id: 1
0>]>                                                                                                                                                           
irb(main):052:0> @species.orgs                                                                                                                                 
ActiveRecord::HasManyThroughOrderError: Cannot have a has_many :through association 'Species#orgs' which goes through 'Species#assessments' before the through 
association is defined.                                                                                                                                        
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/reflection.rb:963:in `check_validity!'                                   
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:25:in `initialize'                           
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations/has_many_through_association.rb:8:in `initialize'           
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations.rb:265:in `new'                                             
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations.rb:265:in `association'                                     
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations/builder/association.rb:111:in `orgs'                        
        from (irb):52                                                            
```

And the weird thing where a simple ask on the @program.species throws a cast error.

```
irb(main):050:0> @program.species                                                                                                                              
TypeError: can't cast Hash                                                                                                                                     
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:45:in `rescue in type_cast'      
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:32:in `type_cast'                
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `block in type_casted_bind
s'                                                                                                                                                             
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `map'                     
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:166:in `type_casted_binds'       
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:627:in `exec_cache'            
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `execute_and_clear'     
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:365:in `select_prepar
ed'                                                                                                                                                            
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:40:in `select_all'   
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'           
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/querying.rb:39:in `find_by_sql'                                          
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/statement_cache.rb:107:in `execute'                                      
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations/singular_association.rb:50:in `find_target'                 
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:147:in `load_target'                         
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:53:in `reload'                               
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations/singular_association.rb:7:in `reader'                       
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/associations/builder/association.rb:111:in `species'                     
        from (irb):50                  
```

Note: I resolved all these issues by downgrading to 5.0.3 ActiveRecord.

**Comment by aoozdemir** [comment] 2017-06-14 11:55
Apparently, it meant literally order. I was having this problem, If you define a class like this, it will give you `HasManyThroughOrderError`.
```ruby
class User < ApplicationRecord
  has_many :groups, -> { distinct }, through: :memberships
  has_many :memberships, dependent: :destroy
end
```

```ruby
class User < ApplicationRecord
  has_many :memberships, dependent: :destroy
end
```

**Comment by aoozdemir** [comment] 2017-06-14 11:57
Apparently, it meant literally order. I was having this problem, and I'm not sure if everyone having this error with the same reason, but if you define a class like this, it will give you `HasManyThroughOrderError`.

```ruby
class User < ApplicationRecord
  has_many :groups, -> { distinct }, through: :memberships
  has_many :memberships, dependent: :destroy
end
```

Defining like this, solved my problem.
```ruby
class User < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :groups, -> { distinct }, through: :memberships
end
```

**Comment by Blaked84** [comment] 2017-06-14 12:27
I've got the same issue and as @aoozdemir, I solved it by setting the _has_many_ of the join table before the _has_many trough_

**Comment by wakatara** [comment] 2017-06-14 17:30
@aoozdemir @Blaked84 Thanks guys, doing the following:

```
class Species < ActiveRecord::Base
  has_many :programs
  has_many :assessments
  
  has_many :orgs, :through => :programs
  has_many :orgs, :through => :assessments
```

does eliminate the one error (though why it should work in 5.0.3 and not 5.1.1 is beyond me. 

Sadly though, I am still getting the `TypeError: can't cast Hash` on `@program.species` in irb  which makes me think there is some boog in the associations with 5.1.1 (as mentioned, downgrading to 5.0.3 has everything working as expected.). It does seem subtle and insidious though... especially if it somehow causes an order error on having *all* the has_manys defined before the has_many => throughs  (as you'll note in my original code, I was defining the has_many for each through association before the actual has_many through, so it's a bit weird it threw the errors.

thanks for the assistance though! If there is anything you guys think I can do to help provide more info to run this thing down, please let me know.

**Comment by wakatara** [comment] 2017-06-14 17:59
@aoozdemir @Blaked84 Yeah, I upgraded to 5.1.1 again and tried the following but still seeing the same error on the simple inverse of the species relation with program.

```
🚀  aark_resurrection  (master *) padrino console                                                                                                              
=> Loading development console (Padrino v.0.14.1.1)                                                                                                           
=> Loading Application AarkResurrection::Admin                                                                                                                
=> Loading Application AarkResurrection::App                                                                                                                  
irb(main):001:0> @program = Program.find(1)                                                                                                                   
  DEBUG -  Program Load (0.7ms)  SELECT  "programs".* FROM "programs" WHERE "programs"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]                          
=> #<Program id: 1, start_year: "2005-01-01", in_range: "No", species_id: 2010, org_id: 14, created_at: "2013-09-17 23:00:00", updated_at: "2014-01-03 10:56:3
1", category: "Ex situ research", terminated_at: nil, terminated_reason: "", hidden: false, primary_contact_id: 10>                                           
irb(main):002:0> @program.org                                                                                                                                 
  DEBUG -  Org Load (0.8ms)  SELECT  "orgs".* FROM "orgs" WHERE "orgs"."id" = $1 LIMIT $2  [["id", 14], ["LIMIT", 1]]                                         
=> #<Org id: 14, name: "Chester Zoo", is_zoo: true, created_at: "2013-09-15 23:23:53", updated_at: "2013-09-16 14:30:16", primary_contact_id: 6, country_id: 2
35>                                                                                                                                                           
irb(main):003:0> @species = Species.find(2010)                                                                                                                
  DEBUG -  Species Load (1.0ms)  SELECT  "species".* FROM "species" WHERE "species"."id" = $1 LIMIT $2  [["id", 2010], ["LIMIT", 1]]                          
=> #<Species id: 2010, name: "Agalychnis moreletii", analog: "", has_phylogenetic_study: "Underway", created_at: "2013-09-15 23:23:27", updated_at: "2013-09-1
5 23:23:27", common_name: "Morelet's Treefrog", ex_situ_research_needs_notes: nil, order: "Anura", family: "Hylidae", genus: "Agalychnis", species: "moreletii
">                                                                                                                                                            
irb(main):004:0> @species.programs     
  DEBUG -  Program Load (0.6ms)  SELECT  "programs".* FROM "programs" WHERE "programs"."species_id" = $1 LIMIT $2  [["species_id", 2010], ["LIMIT", 11]]      
=> #<ActiveRecord::Associations::CollectionProxy [#<Program id: 1, start_year: "2005-01-01", in_range: "No", species_id: 2010, org_id: 14, created_at: "2013-$9-17 23:00:00", updated_at: "2014-01-03 10:56:31", category: "Ex situ research", terminated_at: nil, terminated_reason: "", hidden: false, primary_contact_id$ 10>]>                                 
irb(main):005:0> @program.species      
TypeError: can't cast Hash             
        from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb:45:in `rescue in type_cast'  
```

**Comment by aoozdemir** [comment] 2017-06-14 19:08
@wakatara I'm still assuming this is a bug, as it's working on the versions lower than 5.1.1. Or it's a behaviour none of us noticed before. I'm not sure what is causing the `TypeError` though.

**Comment by tuzz** [comment] 2017-06-23 15:32
I've tried to fix part of this issue, first raised by @nplusp. That error should no longer be thrown when overriding a previously defined association. I'm not sure if that fix will address all the code examples presented in this issue, though.

**Comment by pzgz** [comment] 2017-06-28 06:42
I think this should be consider as a bug, it works fine in previous fine. We have to modify all our model codes in project, to make sure the association used in :though got defined before the one using them 😭

**Comment by memoht** [comment] 2017-06-28 13:14
I also stumbled across this issue when upgrading from 5.0.4 to 5.1.1 and it threw me for a loop. I am using Concerns and have one module named `Accountable` which declares a `has many through`.
Under 5.0.4 there is no issue, but 5.1.1 complains about this. The fix so far has been to move the offending `belongs_to` to the line before including the concern in this model.

```
  belongs_to :company
  include Accountable
```
This was very confusing until I ran across this thread and realized order of declaration was important. I try to follow the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide#classes--modules) so I always put includes and extend statements before associations.

**Comment by rafaelfranca** [comment] 2017-06-28 16:29
This is not a bug. Redefined an association is not supported and not recommended at all.

**Comment by pzgz** [comment] 2017-06-28 18:22
@rafaelfranca What does `redefined an association` meant here? Thought the "has_many :through association" is pretty common and also mentioned in [ruby on rails guide](http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association). The guide hasn't mentioned that the association used in `:through` has to be defined first.

**Comment by rafaelfranca** [comment] 2017-06-28 18:30
There are two different issues here.

One is defining the same association twice, this is raising `HasManyThroughOrderError` but it should not, this is a bug since it should raise a different exception.

The other is defining the `:though` association before the source association, this should raise `HasManyThroughOrderError` since there are implications in the behavior when defining the `:through` association before the source association. This is not a bug.
The guide doesn't mention order of associations because the exception exists exactly to avoid people to define them in the wrong order.

**Comment by pzgz** [comment] 2017-06-28 18:51
I see, thanks anyway. This behavior is only be introduced in this version, so it brought confusions.

**Comment by wakatara** [comment] 2017-06-29 03:43
@rafaelfranca Can you explain why this suddenly changed? It violates Rails' "least surprise" principle suddenly having this break in 5.1 when it has worked all the way up to 5.0x. It's definitely a huge behaviour change and counter to many examples in many books and guides. 

As for defining the same association twice (if you're talking about :orgs has_many programs and :orgs has_many :through associations) this is a very common pattern that works in many applications, so am unsure why you'd consider this a bug (maybe it's "un-5.1's-y"?). 

Is there a new, canonical way under 5.1 this should be done where you have an organizations that could have both programs and assessments that would work?

As I think I previously pointed out, this works great in 5.0x so it suddenly breaking in 5.1 seems more a big in 5.1 than an issue with modelling or design. 

/ @pzgz

**Comment by rafaelfranca** [comment] 2017-06-29 12:39
Here is the reason for the change https://github.com/rails/rails/pull/27485. Like you can see it is by design. We want 5.1 raise for a thing that was "fine" in 5.0. It was never fine, the fact that it worked in 5.0 for some case doesn't means that defining the through association before the source association worked fine for all the cases. Because of that it is safer to always define the source association before the through association so now we are enforcing this order to make explicit to the users that there are consequences when defining in a different order. 

> As for defining the same association twice (if you're talking about :orgs has_many programs and :orgs has_many :through associations) this is a very common pattern that works in many applications, so am unsure why you'd consider this a bug (maybe it's "un-5.1's-y"?).

I don't know how that works. If you have two different association with the same name which one you think it is going to be used when you do `species.orgs`, the first or the second?

**Comment by wakatara** [comment] 2017-06-29 13:41
@rafaelfranca 
Ah, I see what you mean now (and thanks v much for explaining the reason for the change, since I imagine it is throwing quite a few people since it did not work that way previously.). 

For the "defining association twice", I think you're confusing the syntax with the intention (or I am). And apologies, I realize it's difficult to understand these things in abstract when I'm referring to a binch of model associations you may not have seen before. 

The traversal path would be species => programs => orgs  and species => assessments => orgs since they represent two different associations. Species.orgs does not represent anything, though I'd expect species.programs.orgs to give me something.

Does that make sense, or am I somehow misunderstanding the how has_many :through is supposed to work (for however long I've been using it.). Should I use another association construct. Additionally, this works in 5.0.x.

The issue is that species.programs throws an error here, which seems to be an issue with the association and a boog. Again, this only happens in 5.1. 

So, I still *think* this is a  bug unless I've misunderstood something here (which is easily possible. I am not so good at teh computering... =] ).. 

Lemme know if I'm not explaining myself well here or I can make this clearer by way of explanation of what I'd done in the 5.0x AR. I'm still sitting AR and a bunch of other gems in padrino at 5.0.x as 5.1 breaks the app in a bunch of different places due to this. 

/ @pzgz

**Comment by wakatara** [comment] 2017-06-29 13:53
@rafaelfranca
Or is the simplest solution to this just to create alternative names for the associations like "program_orgs" and "assessment_orgs" via the class name while still using the table model Orgs? (much like you do with say, an accounts and Organizations table where the Org has many accounts, but has one primary account as contact point.)
ie. 

``` ruby
class Org < ActiveRecord::Base
  has_many :accounts
  belongs_to  :org_primary_contact, :class_name => 'Account', :foreign_key => :primary_contact_id
```

Like I said, the confusion for me stems from the fact this is working fine from AR 3.something up to 5.0.x but not 5.1.x

**Comment by rafaelfranca** [comment] 2017-06-29 15:36
If `Species.orgs` so you don't need to declare `has_many :orgs` twice in `Species`. Can you create an executable script for those associations that are failing?

**Comment by rafaelfranca** [comment] 2017-06-29 15:37
Here is the template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb.

**Comment by BM5k** [comment] 2017-06-30 00:01
FYI The backtrace for `ActiveRecord::HasManyThroughOrderError` is pointing to the controller responsible for the view being rendered _not_ the model that has the improperly ordered associations. That's making the fix more work (open controller to figure out which model is being referenced, then open the model to fix the associations).

**Comment by rafaelfranca** [comment] 2017-06-30 17:20
Can you paste the full backtrace?

**Comment by BM5k** [comment] 2017-06-30 19:48
@rafaelfranca https://gist.github.com/BM5k/0c4f3ef07a0fd6253cfb4e52d43e8522

**Comment by memoht** [comment] 2017-07-03 01:22
My problem seems to have been different after all. I added `optional: true` to the offending belongs_to declaration and the error disappears regardless of the order I tried above. Go figure.

**Comment by ismailakbudak** [comment] 2017-08-21 14:24
I have same problem when upgrading rails 4.2 to 5.1. If you change the order of relations, there is no problem.

**Comment by abepetrillo** [comment] 2017-09-23 18:41
Would be nice if these errors came up on booting rails. Relying on your test coverage to trigger the correct scopes has me a little nervous about the upgrade. Is there any way of loading all the Models and making sure the order is correct?

**Comment by kamipo** [comment] 2017-11-06 00:04
The TypeError was fixed in #29058.

**Comment by eashward** [comment] 2017-11-17 16:38
@rafaelfranca is the issue [here](https://github.com/hzamani/active_record-acts_as/issues/92) related to the order of associations mentioned in model ?

**Comment by kamipo** [comment] 2018-01-06 17:56
This is a same issue with #31068.
I think that redefining association in a STI subclass is a reasonable usage.
I've fixed it in 652258e41a882acccdb9a3ce211dbf356e738b28.

**Closed by kamipo** 2018-01-06 17:56 UTC
Labels: activerecord

**Comment by ericproulx** [comment] 2020-05-27 22:18
Old issue but still relevant for some people. Here's a `rspec` that will reveal all your current `ActiveRecord::HasManyThroughOrderError`

```ruby
# frozen_string_literal: true

describe 'ActiveRecord::HasManyThroughOrderError' do
  describe '#HasManyThroughOrderError' do
    has_many_through_associations = ApplicationRecord.descendants.reject(&:abstract_class).each_with_object({}) do |ar_class, result|
      has_many_through_associations = ar_class.reflect_on_all_associations(:has_many).select do |association|
        association.options.key? :through
      end
      result[ar_class] = has_many_through_associations.map(&:name) if has_many_through_associations.any?
    end
    has_many_through_associations.each do |ar_class, association_names|
      test_class = ar_class.new
      association_names.each do |association_name|
        context "loading #{ar_class}. #{association_name} should not raise an HasManyThroughOrderError" do
          it 'should be a success' do
            expect { test_class.send(association_name.to_sym).first }.not_to raise_error
          end
        end
      end
    end
  end
end
```

**Comment by niquepa** [comment] 2023-04-14 03:27
While migrating a rails app from 5.2 to 6 I faced this error but in my case the relationships order was correct:

```
has_many :users_roles
has_many :roles,      :through => :users_roles
```

`[ActiveRecord::HasManyThroughOrderError: Cannot have a has_many :through association](https://stackoverflow.com/questions/49450963/activerecordhasmanythroughordererror-cannot-have-a-has-many-through-associat)`

The app uses `rolify` and it was at the top of the class:


I had to change the order:
```
has_many :users_roles
----------
rolify
----------
has_many :roles,      :through => :users_roles
```
