### ISSUE TITLE
Rails 7.1 Error when reading active record model from redis cache

### ISSUE THREAD

**Issue by nile1985** [rails/rails#52295] opened 2024-07-09 13:41 UTC
### Steps to reproduce
We have a problem during upgrade Rails from 7.0.8 to 7.1.3.2 with reading AR models from Redis cache.

We have several places where we cache AR models with Redis:

```ruby
Rails.cache.fetch("key_name") { Ar_Model[some_key] }
```

After Rails upgrade we can't read all params (except _id_) from the model. Example:

Run two same consoles. In one of them:

```ruby
model = Rails.cache.fetch("key_name") { Ar_Model[some_key] }
model.class => Ar_Model(id: integer, name: string)
model.name => "some_name"
```

But in the second console:

```ruby
model = Rails.cache.fetch("key_name")
model.class => Ar_Model(id: integer, name: string)
model.id => some_id
model.name => Error! Unknown method 'name' for Ar_Model()
```

Interestingly, after run, for example, _Ar_Model.first_ in the second console, we can read all params from the model without any reloading.

```ruby
model = Rails.cache.fetch("key_name")
model.class => Ar_Model(id: integer, name: string)
model.id => some_id
model.name => Error! Unknown method 'name' for Ar_Model()
Ar_Model.first
model.name => "some_name"
```

### Expected behavior
In the second console:
```ruby
model = Rails.cache.fetch("key_name")
model.class => Ar_Model(id: integer, name: string)
model.id => some_id
model.name => "some_name"
```

### Actual behavior
In the second console:

```ruby
model = Rails.cache.fetch("key_name")
model.class => Ar_Model(id: integer, name: string)
model.id => some_id
model.name => Error! Unknown method 'name' for Ar_Model()
```

### System configuration
**Rails version**: 7.0.8 => 7.1.3.2

**Ruby version**: ruby 3.2.3

**Comment by federicoaldunate** [comment] 2024-07-09 20:06
Does this happens between two different 'rails consoles'?
Can you submit a bug report like this?
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "sqlite3"
  gem "pg"
  gem 'redis'
  gem 'redis-rails'
end

require "active_record"
require "minitest/autorun"
require "active_support/all"
require "active_support"
require "active_support/cache"
require "redis"
require "redis-rails"

# Configure cache store to use Redis
ActiveSupport::Cache::Store.logger = Logger.new(STDOUT)
Rails.cache = ActiveSupport::Cache::RedisStore.new(
  { host: "localhost", port: 6379, db: 0, namespace: "cache" }
)

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end
end

class User < ActiveRecord::Base
  def self.cached_find(id)
    cache_key = "user_#{id}"

    Rails.cache.fetch(cache_key, expires_in: 12.hours) do
      find(id)
    end
  end
end

class BugTest < Minitest::Test
  def setup
    @user = User.create!(name: 'Fede')
  end

  def test_cache
    # Fetching the user from the cache
    cached_user = User.cached_find(@user.id)
    assert_equal @user, cached_user

    # Simulating retrieval from cache by directly writing to cache
    cache_key = "user_#{@user.id}"
    cached_user = Rails.cache.fetch(cache_key)
    assert_equal @user.id, cached_user.id
    assert_equal @user.name, cached_user.name
  end
end
```
I cannot reproduce your bug.

**Comment by nile1985** [comment] 2024-07-10 06:44
Yes, it happens between two different consoles. Ok, I'll try to make a bug report

**Comment by fatkodima** [comment] 2024-07-10 15:06
You really should not store full active record instances in the cache. There was a similar report some time ago (can't find it quickly by the search).

I remember @byroot was involved in that discussion.

**Comment by byroot** [comment] 2024-07-10 16:24
Looks a lot like https://github.com/rails/rails/pull/50594 indeed. Unclear to me why the fix doesn't work in your case.

**Comment by skipkayhil** [comment] 2024-07-10 16:39
@byroot does #50705 need to be merged?

**Comment by byroot** [comment] 2024-07-10 16:54
🤦

**Closed** 2024-07-15 17:24 UTC
