### ISSUE TITLE
ArgumentError for Attribute of Type decimal for Invalid Input with Ruby 2.4

### ISSUE THREAD

**Issue by ushi-as** [rails/rails#27634] opened 2017-01-10 16:01 UTC
The behavior of ```BigDecimal()``` changed in Ruby 2.4. Invalid input like ```"abcd"``` leads to an ```ArgumentError``` now. In Ruby 2.3 it returned ```0.0```.

This leads to an error when assigning invalid input for attributes of type decimal.

```ruby
class Rope < ActiveRecord::Base
  validates :length, numericality: {greater_than: 0}
end

# Ruby 2.3
Rope.new(length: "abcd").valid?
#=> false

# Ruby 2.4
Rope.new(length: "abcd").valid?
# ArgumentError: invalid value for BigDecimal(): "abcd"
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/type/decimal.rb:23:in `BigDecimal'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/type/decimal.rb:23:in `cast_value'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/type/value.rb:36:in `cast'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/type/helpers/numeric.rb:12:in `cast'
#	from /home/app/bundle/gems/activerecord-5.0.1/lib/active_record/attribute.rb:150:in `type_cast'
#	from /home/app/bundle/gems/activerecord-5.0.1/lib/active_record/attribute.rb:38:in `value'
#	from /home/app/bundle/gems/activerecord-5.0.1/lib/active_record/attribute_set.rb:44:in `fetch_value'
#	from /home/app/bundle/gems/activerecord-5.0.1/lib/active_record/attribute_methods/read.rb:66:in `_read_attribute'
#	from /home/app/bundle/gems/activerecord-5.0.1/lib/active_record/attribute_methods/read.rb:36:in `__temp__c6f6e6769647574656'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/validator.rb:149:in `block in validate'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/validator.rb:148:in `each'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/validator.rb:148:in `validate'
#	from /home/app/bundle/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:405:in `public_send'
#	from /home/app/bundle/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:405:in `block in make_lambda'
#	from /home/app/bundle/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
#	from /home/app/bundle/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
#... 7 levels...
#	from /home/app/bundle/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_validate_callbacks'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/validations.rb:408:in `run_validations!'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
#	from /home/app/bundle/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
#	from /home/app/bundle/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_validation_callbacks'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
#	from /home/app/bundle/gems/activemodel-5.0.1/lib/active_model/validations.rb:338:in `valid?'
#	from /home/app/bundle/gems/activerecord-5.0.1/lib/active_record/validations.rb:65:in `valid?
```

**Comment by pixeltrix** [comment] 2017-01-10 17:23
Duplicate of #27429

**Closed by pixeltrix** 2017-01-10 17:23 UTC
