### ISSUE TITLE
Excessive records are created when adding record to HMT association & invese is `has_one` 

### ISSUE THREAD

**Issue by ojab** [rails/rails#40534] opened 2020-11-04 09:04 UTC
### Steps to reproduce
Basically I want to have some PRs which are ignored for 3 weeks into 6.1 and maybe creating of the issue will move it forward.  
See https://github.com/rails/rails/pull/40385 & https://github.com/rails/rails/pull/40390

### Expected behavior
Testcases pass

### Actual behavior
Testcases fail

### System configuration
**Rails version**: 2.6

**Ruby version**: master

**Comment by composerinteralia** [comment] 2020-11-12 17:24
Thanks you for opening those PRs. I appreciate it.

Getting a review from a core member or committer does sometimes take a bit of time (there are 200+ PRs to consider, and limited time to spend on them). I understand that waiting can be frustrating, but if these PRs don't make it into 6.1, they can still be considered for a future release.

The [contribution docs](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#get-some-feedback) suggest nudging things along on the mailing list, or leaving additional comments on the PR. Quickly glancing at your PRs, I think providing more detail in the description about what problem is being solved (is there a bug in the existing behavior, how would one reproduce that bug, what was the result before and after, etc.) might make these PRs easier to prioritize and review.

I am going to close this issue, since it doesn't provide any additional context. The mailing list or further comments on the PRs themselves are a better way to try and move things along.

Thanks!

**Closed by composerinteralia** 2020-11-12 17:24 UTC
