### ISSUE TITLE
MemCacheStore#increment bug

### ISSUE THREAD

**Issue by AlexParamonov** [rails/rails#19803] opened 2015-04-17 22:09 UTC
Right now MemCacheStore does not increment values:
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache/mem_cache_store.rb#L89

it should have default option to equal zero:
Instead of 

```
@data.incr(escape_key(namespaced_key(name, options)), amount)
```
Should be 

```
@data.incr(escape_key(namespaced_key(name, options)), amount, nil, 0)
```

**Comment by rafaelfranca** [comment] 2015-04-19 20:27
Could you explain better why it is not incrementing values?

**Comment by AlexParamonov** [comment] 2015-04-20 00:14
Have no idea why, but it does not in memcached version 1.4.15 on Amazon Elastic Beanstalk.
It does work only when set the default value to 0.

**Comment by meinac** [comment] 2015-04-20 12:00
because in dalli client it says for incr method that
```
If default is nil, the counter must already exist or the operation
will fail and will return nil.  Otherwise this method will return
the new value for the counter.
```
as you showed in the description default value should be setted as zero.

**Comment by meinac** [comment] 2015-04-20 13:07
I believe this is expected behaviour because MemoryStore behaves same with this. You can try it;
```
store = ActiveSupport::Cache::MemoryStore.new
store.increment(:foo) #returns nil
```
Also the documentation about the method says that ```
 This method uses the memcached incr atomic operator and can only be used on values written with the :raw option. ``` So if you want to use this method you have to write the value first with ```raw: true``` option.
In the same documentation it says ```Calling it on a value not stored with :raw will initialize that value to zero.``` but it does not.

**Comment by AlexParamonov** [comment] 2015-04-20 13:12
It would be fine if it actually set any value. I tried with and without raw: the counter is not written to the memcached. No error reported. It just silently returns nil.

If the value was there already, it does not increment as well (with and without raw option).

**Comment by AlexParamonov** [comment] 2015-04-20 13:13
If you had it worked, can you provide an example how to make it write and increment the value in memcached?

**Comment by meinac** [comment] 2015-04-20 14:34
You can try it in rails console here is the complete steps;
```ruby
store = ActiveSupport::Cache::MemCacheStore.new
store.write(:foo, 0, raw: true)
store.increment(:foo) #returns 1
store.read(:foo) #returns 1

store.increment(:bar) #returns nil
```
Can you try and tell me the result?

**Comment by AlexParamonov** [comment] 2015-04-20 15:14
yes, I will try. But only tomorrow if you don't mind

**Comment by AlexParamonov** [comment] 2015-04-26 20:02
```
irb(main):009:0> Rails.cache.write :foo, 0, raw: true
=> 6417066519049535488
irb(main):010:0> Rails.cache.read :foo
=> "0"
irb(main):011:0> Rails.cache.increment :foo
=> 1
irb(main):012:0> Rails.cache.read :foo
=> "1"
```

That worked. But I will keep the local patch since the way Rails forces it to work is confusing. But you have to maintain backward compatibility, I understand.

**Comment by meinac** [comment] 2015-04-26 21:00
@AlexParamonov so feel free to close this.

**Closed** 2015-04-26 21:03 UTC
Labels: needs feedback
