### ISSUE TITLE
Basic Rails 7 project with Bootstrap fails

### ISSUE THREAD

**Issue by LukevanTricht** [rails/rails#44182] opened 2022-01-16 12:05 UTC
### Steps to reproduce
```
rails new testapp -d postgresql -c bootstrap
cd testapp
bin/dev
```

### Expected behavior
App should launch and automatically include the bootstrap/hotwired/stimulus javascript packages

### Actual behavior
the yarn build stage reports these errors:
```
22:01:44 js.1   | ✘ [ERROR] Could not resolve "@hotwired/turbo-rails"
22:01:44 js.1   |
22:01:44 js.1   |     app/javascript/application.js:2:7:
22:01:44 js.1   |       2 │ import "@hotwired/turbo-rails"
22:01:44 js.1   |         ╵        ~~~~~~~~~~~~~~~~~~~~~~~
22:01:44 js.1   |
22:01:44 js.1   |   You can mark the path "@hotwired/turbo-rails" as external to exclude it from the bundle, which will remove this error.
22:01:44 js.1   |
22:01:44 js.1   | ✘ [ERROR] Could not resolve "bootstrap"
22:01:44 js.1   |
22:01:44 js.1   |     app/javascript/application.js:4:27:
22:01:44 js.1   |       4 │ import * as bootstrap from "bootstrap"
22:01:44 js.1   |         ╵                            ~~~~~~~~~~~
22:01:44 js.1   |
22:01:44 js.1   |   You can mark the path "bootstrap" as external to exclude it from the bundle, which will remove this error.
22:01:44 js.1   |
22:01:44 js.1   | ✘ [ERROR] Could not resolve "@hotwired/stimulus"
22:01:44 js.1   |
22:01:44 js.1   |     app/javascript/controllers/hello_controller.js:1:27:
22:01:44 js.1   |       1 │ import { Controller } from "@hotwired/stimulus"
22:01:44 js.1   |         ╵                            ~~~~~~~~~~~~~~~~~~~~
22:01:44 js.1   |
22:01:44 js.1   |   You can mark the path "@hotwired/stimulus" as external to exclude it from the bundle, which will remove this error.
22:01:44 js.1   |
22:01:44 js.1   | ✘ [ERROR] Could not resolve "@hotwired/stimulus"
22:01:44 js.1   |
22:01:44 js.1   |     app/javascript/controllers/application.js:1:28:
22:01:44 js.1   |       1 │ import { Application } from "@hotwired/stimulus"
22:01:44 js.1   |         ╵                             ~~~~~~~~~~~~~~~~~~~~
22:01:44 js.1   |
22:01:44 js.1   |   You can mark the path "@hotwired/stimulus" as external to exclude it from the bundle, which will remove this error.
22:01:44 js.1   |
22:01:44 js.1   | 4 errors
22:01:44 js.1   | [watch] build finished, watching for **changes...**
```

and the yarn build-css stage reports this error:
```
22:01:45 css.1  | Error: Can't find stylesheet to import.
22:01:45 css.1  |   ╷
22:01:45 css.1  | 1 │ @import 'bootstrap/scss/bootstrap';
22:01:45 css.1  |   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
22:01:45 css.1  |   ╵
22:01:45 css.1  |   app/assets/stylesheets/application.bootstrap.scss 1:9  root stylesheet
22:01:45 css.1  |
22:01:45 css.1  | Sass is watching for changes. Press Ctrl-C to stop.
```

### System configuration
```
testapp$ rails -v
Rails 7.0.1
```
```
testapp$ ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
```
```
testapp$ node -v
v17.3.1
```
```
testapp$ yarn -v
3.1.1
```

**Comment by SkipKayhil** [comment] 2022-01-19 20:14
Did you see any errors during the `rails new` command? I tried your reproduction steps and am not seeing any issues.

**Comment by billabel** [comment] 2022-01-20 03:45
I could not reproduce your errors using the same configuration, except for yarn, and the `x86_64-darwin19` version of ruby. 

The latest version of yarn is `1.22.17`

**Comment by yahonda** [comment] 2022-01-20 08:43
It also does not reproduce in my environment on Ubuntu 21.10 box.
I'm also wondering the `yarn` version differences. I assume `yarn` `3.1.1` is that of Apache Hadoop like https://github.com/yarnpkg/yarn/issues/2337


* Environment
```
$ bundle exec rails -v
Rails 7.0.1
$ ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
$ node -v
v17.3.1
$ yarn -v
1.22.5
```

* Steps to reproduce
```
git clone https://github.com/yahonda/sample44182
cd sample44182
bundle install
bin/dev
```

* Actual result
```
$ bin/dev
17:27:17 web.1  | started with pid 464734
17:27:17 js.1   | started with pid 464735
17:27:17 css.1  | started with pid 464736
17:27:17 css.1  | yarn run v1.22.5
17:27:17 js.1   | yarn run v1.22.5
17:27:17 css.1  | $ sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules --watch
17:27:17 js.1   | $ esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --watch
17:27:17 js.1   | [watch] build finished, watching for changes...
17:27:17 web.1  | => Booting Puma
17:27:17 web.1  | => Rails 7.0.1 application starting in development
17:27:17 web.1  | => Run `bin/rails server --help` for more startup options
17:27:17 web.1  | Puma starting in single mode...
17:27:17 web.1  | * Puma version: 5.5.2 (ruby 3.1.0-p0) ("Zawgyi")
17:27:17 web.1  | *  Min threads: 5
17:27:17 web.1  | *  Max threads: 5
17:27:17 web.1  | *  Environment: development
17:27:17 web.1  | *          PID: 464734
17:27:17 web.1  | * Listening on http://127.0.0.1:3000
17:27:17 web.1  | * Listening on http://[::1]:3000
17:27:17 web.1  | Use Ctrl-C to stop
17:27:17 css.1  | Sass is watching for changes. Press Ctrl-C to stop.
17:27:17 css.1  |
^C17:27:25 system | SIGINT received, starting shutdown
17:27:25 web.1  | - Gracefully stopping, waiting for requests to finish
17:27:25 web.1  | === puma shutdown: 2022-01-20 17:27:25 +0900 ===
17:27:25 web.1  | - Goodbye!
17:27:25 web.1  | Exiting
17:27:25 system | sending SIGTERM to all processes
17:27:25 web.1  | exited with code 0
17:27:25 js.1   | terminated by SIGINT
17:27:25 css.1  | terminated by SIGINT

**Comment by yahonda** [comment] 2022-01-20 09:14
My assumption may be wrong. The latest version of yarn is 3.1.1 https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.1.1 . It may be "too new", how about using the classic one https://classic.yarnpkg.com/lang/en/ ?

**Comment by yahonda** [comment] 2022-01-20 13:36
Upgrade yarn version from 1.22.15 to 3.1.1 by following https://yarnpkg.com/getting-started/install but not able to reproduce it.

```ruby
$ bundle exec ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
$ bundle exec rails -v
Rails 7.0.1
$ node -v
v17.3.1
$ corepack enable
$ yarn -v
1.22.15
$ yarn set version stable
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.1.1/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.1.1.cjs
➤ YN0000: Done in 0s 490ms
$ yarn -v
3.1.1
$ bin/dev
22:31:43 web.1  | started with pid 490084
22:31:43 js.1   | started with pid 490085
22:31:43 css.1  | started with pid 490086
22:31:44 css.1  | Internal Error: app@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
22:31:44 js.1   | Internal Error: app@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
22:31:44 css.1  |     at AF.getCandidates (/home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:437:4421)
22:31:44 js.1   |     at AF.getCandidates (/home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:437:4421)
22:31:44 css.1  |     at pd.getCandidates (/home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:432:5275)
22:31:44 js.1   |     at pd.getCandidates (/home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:432:5275)
22:31:44 css.1  |     at /home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:441:7674
22:31:44 js.1   |     at /home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:441:7674
22:31:44 css.1  |     at du (/home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:382:4003)
22:31:44 js.1   |     at du (/home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:382:4003)
22:31:44 css.1  |     at R (/home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:441:7654)
22:31:44 js.1   |     at R (/home/yahonda/.node/corepack/yarn/3.1.1/yarn.js:441:7654)
22:31:44 web.1  | => Booting Puma
22:31:44 web.1  | => Rails 7.0.1 application starting in development
22:31:44 web.1  | => Run `bin/rails server --help` for more startup options
22:31:44 web.1  | Puma starting in single mode...
22:31:44 web.1  | * Puma version: 5.5.2 (ruby 3.1.0-p0) ("Zawgyi")
22:31:44 web.1  | *  Min threads: 5
22:31:44 web.1  | *  Max threads: 5
22:31:44 web.1  | *  Environment: development
22:31:44 web.1  | *          PID: 490084
22:31:44 web.1  | * Listening on http://127.0.0.1:3000
22:31:44 web.1  | * Listening on http://[::1]:3000
22:31:44 web.1  | Use Ctrl-C to stop
22:31:44 js.1   | exited with code 1
22:31:44 system | sending SIGTERM to all processes
22:31:44 css.1  | exited with code 1
22:31:44 web.1  | - Gracefully stopping, waiting for requests to finish
22:31:44 web.1  | Exiting
22:31:45 web.1  | terminated by SIGTERM
$ yarn install
➤ YN0070: Migrating from Yarn 1; automatically enabling the compatibility node-modules linker 👍

➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0000: └ Completed in 3s 88ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ util-deprecate@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ which@npm:2.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wide-align@npm:1.1.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wrappy@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 4s 15ms
➤ YN0000: ┌ Link step
➤ YN0076: │ esbuild-android-arm64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-darwin-64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-darwin-arm64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-freebsd-64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-freebsd-arm64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-32@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-arm64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-arm@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-mips64le@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-ppc64le@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-s390x@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-netbsd-64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-openbsd-64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-sunos-64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-32@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-arm64@npm:0.14.11 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0007: │ esbuild@npm:0.14.11 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 0s 510ms
➤ YN0000: Done with warnings in 7s 644ms
yahonda@myryzen:~/src/github.com/yahonda/sample44182$ bin/dev
22:32:08 web.1  | started with pid 490277
22:32:08 js.1   | started with pid 490278
22:32:08 css.1  | started with pid 490279
22:32:08 js.1   | [watch] build finished, watching for changes...
22:32:09 web.1  | => Booting Puma
22:32:09 web.1  | => Rails 7.0.1 application starting in development
22:32:09 web.1  | => Run `bin/rails server --help` for more startup options
22:32:09 web.1  | Puma starting in single mode...
22:32:09 web.1  | * Puma version: 5.5.2 (ruby 3.1.0-p0) ("Zawgyi")
22:32:09 web.1  | *  Min threads: 5
22:32:09 web.1  | *  Max threads: 5
22:32:09 web.1  | *  Environment: development
22:32:09 web.1  | *          PID: 490277
22:32:09 web.1  | * Listening on http://127.0.0.1:3000
22:32:09 web.1  | * Listening on http://[::1]:3000
22:32:09 web.1  | Use Ctrl-C to stop
22:32:10 css.1  | Compiled app/assets/stylesheets/application.bootstrap.scss to app/assets/builds/application.css.
22:32:10 css.1  | Sass is watching for changes. Press Ctrl-C to stop.
22:32:10 css.1  |
^C22:32:20 system | SIGINT received, starting shutdown
22:32:20 web.1  | - Gracefully stopping, waiting for requests to finish
22:32:20 web.1  | === puma shutdown: 2022-01-20 22:32:20 +0900 ===
22:32:20 web.1  | - Goodbye!
22:32:20 web.1  | Exiting
22:32:20 system | sending SIGTERM to all processes
22:32:20 web.1  | exited with code 0
22:32:20 js.1   | exited with code 129
22:32:20 css.1  | exited with code 129
```

**Comment by przbadu** [comment] 2022-02-08 09:38
I get the same issue:

**simply generated rails new project by setting --css bootstrap flat**

```
rails new demo -d postgresql --css bootstrap
```

**system info:**

```
> rails -v
Rails 7.0.1

> ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
```

**NOTE:**

It did generated rails 7 project without any issue, bootstrap configuration in `application.css`, `application.js`, `package.json` seems correct.

If I run `rails s` I can see bootstrap is also working, but If I run

```
./bin/dev
```


Then above error occurs.

**Comment by przbadu** [comment] 2022-02-08 09:45
This is the generated JSON file with above command 

> RE: `rails new demo -d postgresql --css bootstrap`

and if you check this file `hotwired/stimulus` is missing in the package file

```json
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/turbo-rails": "^7.1.1",
    "@popperjs/core": "^2.11.2",
    "bootstrap": "^5.1.3",
    "esbuild": "^0.14.20",
    "sass": "^1.49.7"
  },
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules"
  }
}
```

**SOLUTION:**

Manually adding `@hotwired/stimulus` fixed the problem

```
yarn add @hotwired/stimulus
```

Now if you run 

```
./bin/dev
```

Everything works.

**Comment by LukevanTricht** [comment] 2022-02-08 21:21
My apologies @yahonda , Github did not notify me that I had replies to my ticket :(

The issue arises due to how Yarn 3.1.1 handles `node_modules`, so if you install packages using Yarn 1.22.7, and then upgrade to Yarn 3.1.1, you won't notice an issue(because `node_modules` already exists).

If you start a fresh Rails project with Yarn 3.1.1, it fails because Yarn 3 doesn't download NPM packages to `node_modules`, and instead downloads them to `~/.yarn`.

**Comment by yahonda** [comment] 2022-02-09 13:43
Thanks for the info and glad you have found how to address it.

**Comment by an280420** [comment] 2022-02-20 14:47
I got the same problem when I reinstalled the operating system. I recently installed Ubuntu 21.10 from scratch. Then I install `nvm`, `node` and `yarn`
my  system config:
```
nvm -v  ---> 0.39.1
node -v ----> v16.14.0
yarn-v  -----> 3.1.1
Rails 7.0.2.2
ruby 3.1.0p0
```
Then i create rails app with bootstrap
```
rails new blog -c bootstrap
cd blog
./bin/dev
```
it`s not working
To resolve the issue I did the following 
```
cd blog
npm remove yarn
yarn install
```
Now `./bin/dev' command working and start application.

**Comment by an280420** [comment] 2022-02-20 19:56
Another way that was mentioned above here and it helped me.
1. Deinstall nvm 
2. Install nvm
3. Install node
4. Install yarn with command `npm install --global yarn`
5. check yarn -v  ----> yarn 1.22.17
With yarn 1.22.17 command `./bin/dev` working

**Comment by viktorianer** [comment] 2022-05-18 20:30
I had the same problem just now. And on my new MacBook Pro, I did not install `yarn` at all. 

Using `rails new` is running without problems, but in step `Install esbuild` there are no errors. This step just not installing `dependencies` and the file `package.json` looks like this:

```json
{
  "name": "app",
  "private": "true",
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules"
  }
}
```

Notice missing `dependencies` in the JSON.

So, it is not a Rails bug. But I am very sure, in the past we got an error, if `yarn` was not found?

**Comment by skipkayhil** [comment] 2022-07-19 01:05
It sounds like a number of solutions have been found, including for the original issue, so I'm going to close this.

**Closed by skipkayhil** 2022-07-19 01:05 UTC

**Comment by bradleygauthier** [comment] 2022-07-27 23:51
After many hours, this somehow fixed it for me:

```
npm remove yarn
yarn install
```

I am not sure this should be a closed issue. Or it should be documented in the getting started process.

**Comment by LukevanTricht** [comment] 2022-07-28 07:06
It would probably be a good idea to document that yarn > 1.x is not supported, to ensure things out outlined correctly. Simply following the [instructions](https://yarnpkg.com/getting-started/install) provided by Yarn for how to install `yarn`, will lead to you getting an unsupported version, and is where the ticket originated from.

**Comment by fertobar** [comment] 2023-06-22 00:28
```
yarn add @hotwired/turbo-rails 
./bin/dev  
```
worked for me

**Comment by fguillen** [comment] 2024-03-30 16:22
This is still failing for me:

- nvm 0.37.2
- node v21.6.0
- yarn 1.22.22
- rails 7.1.3.2
- ruby 3.1.1p18

**Comment by Kamkara007** [comment] 2024-05-09 14:12
to resolve this error,
run this command to remove files on your project:

`rm -rf ~/.yarnrc.yml && rm -rf ~/.pnp.cjs`

after, regenerate yarn files in your app
`yarn install`
and run to install forman et enable bin config

`./bin/setup`

**Comment by Fredericktax-exempt** [comment] 2025-02-09 01:11
@fguillen https://github.com/angular/angular.js
