### ISSUE TITLE
(erb):2:in `concat': can't modify frozen String (RuntimeError) when using Scaffold Generator

### ISSUE THREAD

**Issue by Schwad** [rails/rails#32726] opened 2018-04-25 18:55 UTC
### Steps to reproduce

Not sure what this is coming from, but experiencing this error running a scaffold on a greenfield up-to-date Rails application. Thanks all for your thoughts!

[Fork this application](https://github.com/Schwad/public_spending_gateway)

Run `rails generate scaffold MyTestScaffold body:text number:integer test_two:string`

Receive the following output of the break: 

### Backtrace (unedited)

```
(erb):2:in `concat': can't modify frozen String (RuntimeError)
	from (erb):2:in `template'
	from /Users/nickschwaderer/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /Users/nickschwaderer/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `open'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `block in invoke!'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions.rb:95:in `action'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators/named_base.rb:25:in `block in template'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators/named_base.rb:49:in `inside_template'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators/named_base.rb:24:in `template'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators/erb/scaffold/scaffold_generator.rb:21:in `block (2 levels) in copy_view_files'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators/erb/scaffold/scaffold_generator.rb:19:in `each'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators/erb/scaffold/scaffold_generator.rb:19:in `block in copy_view_files'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators/erb/scaffold/scaffold_generator.rb:18:in `each'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators/erb/scaffold/scaffold_generator.rb:18:in `copy_view_files'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators/rails/scaffold_controller/scaffold_controller_generator.rb:26:in `block in <class:ScaffoldControllerGenerator>'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:274:in `instance_exec'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:274:in `block in _invoke_for_class_method'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/shell.rb:68:in `with_padding'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:133:in `_invoke_from_option_template_engine'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/shell.rb:68:in `with_padding'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:133:in `_invoke_from_option_scaffold_controller'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/generators.rb:276:in `invoke'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	from /Users/nickschwaderer/Documents/webapps/public_spending_gateway/bin/rails:9:in `<main>'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/nickschwaderer/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	from /Users/nickschwaderer/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/nickschwaderer/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

### System configuration
**Rails version**:
5.2.0
**Ruby version**:
2.4.4

**Comment by y-yagi** [comment] 2018-04-25 22:19
Thank you for the issue. 
There seems to be no `Gemfile` in the sample application you uploaded. Could you add that?

**Comment by Schwad** [comment] 2018-04-26 10:59
Thanks for catching that. I will update the gitignore and push the gemfile later today.

**Comment by Schwad** [comment] 2018-04-26 16:01
Pushed gemfile :) thank you.

**Comment by victorhazbun** [comment] 2018-04-26 18:50
👀

**Comment by guilleiguaran** [comment] 2018-04-26 19:08
The problem seems to be caused by Thor 0.19, remove foreman from your Gemfile/gems.rb and run `bundle update thor` and it should be fixed.

There is a PR already open to update foreman (https://github.com/ddollar/foreman/pull/701) but meanwhile you can use foreman locally without declaring it in your Gemfile (just install it at system level)

**Closed by guilleiguaran** 2018-04-26 19:08 UTC
Labels: needs work

**Comment by Schwad** [comment] 2018-04-26 19:18
Okay, thanks for the heads up, I appreciate it.
