### ISSUE TITLE
ActiveRecord preload association queries

### ISSUE THREAD

**Issue by OuYangJinTing** [rails/rails#41637] opened 2021-03-08 10:35 UTC
### Steps to reproduce
```ruby
ActiveRecord::Base.connection.create_table(:users, force: :true) do |t|
  t.string  :name
end
class User < ApplicationRecord
  has_one :account
  has_one :identity
end

ActiveRecord::Base.connection.create_table(:identities, force: :true) do |t|
  t.integer :user_id
end
class Identity < ApplicationRecord
  belongs_to :user
end

ActiveRecord::Base.connection.create_table(:accounts, force: :true) do |t|
  t.integer :user_id
end
class Account < ApplicationRecord
  belongs_to :user
  has_one :identity, through: :user
end

user = User.create(name: :foobar)
user.create_account
user.crreate_identity
```

### Expected behavior
```ruby
Account.includes(:identity).load
# ActiveRecord executed queries:
#   Account Load  SELECT "accounts".* FROM "accounts"
#   Identity Load  SELECT "identities".* FROM "identities" INNER JOIN "users" ON "identities"."user_id" = "users"."id" WHERE "users"."id" = ?
```

### Actual behavior
```ruby
Account.includes(:identity).load
# ActiveRecord executed queries:
#   Account Load  SELECT "accounts".* FROM "accounts"
#   User Load   SELECT "users".* FROM "users" WHERE "users"."id" = ?
#   Identity Load  SELECT "identities".* FROM "identities" WHERE "identities"."user_id" = ?
```

### System configuration
**Rails version**: 4.0+

### Question
Why it need to load the middle model and it isn't polymorphic association?
Can you help me answer?
Thank you!

**Comment by kamipo** [comment] 2021-03-08 20:57
Duplicate of #41377, use `eager_load` instead.

**Closed by kamipo** 2021-03-08 20:57 UTC
