### ISSUE TITLE
Active Record shard resolver's return value is not respected in Action Cable channel functions (websocket communication)

### ISSUE THREAD

**Issue by pospieszynski** [rails/rails#49052] opened 2023-08-27 22:55 UTC
### Steps to reproduce
1. Create a sample app with multiple db shards, let's say "A" & "B".
2. Implement abstract class X that connects to shards A & B.
3. In `application.rb` implement shard_resolver (`config.active_record.shard_resolver`) to always return "B".
4. Implement simple Action Cable channel.

### Expected behavior
The `X.current_shard` invoked in the Action Cable channel function i.e `subscribed` returns the value returned by the `shard_resolver` block  which is "B".

### Actual behavior
The `X.current_shard` returns "default" effectively ignoring the shard_resolver outcome.

### System configuration
**Rails version**:  7.0.7.2

**Ruby version**: 3.0.2

**Comment by Eshwar066** [comment] 2023-08-28 05:33
Hello

**Comment by eileencodes** [comment] 2023-08-28 14:48
Hi @pospieszynski can you please provide a demo application that reproduces the behavior you're seeing? Thanks!

**Comment by smoburgower** [comment] 2023-08-28 16:18
HelloSent from my iPhoneOn Aug 27, 2023, at 23:35, Eshwar Sai ***@***.***> wrote:﻿
Hello

**Comment by pospieszynski** [comment] 2023-08-28 18:48
Hi @eileencodes thanks for the reply, 

Sure here is the [sample app](https://github.com/pospieszynski/testapp) with the cats & dogs shards. I added a simple `NotificationsChannel` channel and a test (`notifications_channel_test.rb`) just to trigger the ActionCable logic. When triggered, it prints the current_shard in Connection class which is ":default"

I don't think the `shard_resolver` is even invoked in specs but when it is used with a frontend that uses websockets connection it is called although its return value is apparently not used.

**Comment by eileencodes** [comment] 2023-08-29 13:03
> I don't think the shard_resolver is even invoked in specs but when it is used with a frontend that uses websockets connection it is called although its return value is apparently not used.

It should be if you're using an integration test and the resolver is defined in application.rb or environments/test.rb. That will include the middleware because it's a full request.

**Comment by pospieszynski** [comment] 2023-08-29 17:50
I see @eileencodes, were you able to verify it's a bug?

**Comment by eileencodes** [comment] 2023-08-29 19:02
No, I haven't had time to look at this yet.

**Comment by eileencodes** [comment] 2023-09-01 20:04
I took a look at this and am kind of confused. I don't see websockets being used at all in a request. And since the test isn't running a request I don't think the middleware is installed. So this doesn't seem like it's reproducing the issue as described.

Additionally, the connections aren't quite set up correctly. ActiveRecord base must have a default connection, so it's going to use `cats`. If ActiveRecord::Base should have a different schema than the AnimalsRecord then there should be an additional connection defined first and connected in `ApplicationRecord`. Once you do that the shards need their own migration directory since ApplicaitonRecord will use db/migrate.

**Comment by pospieszynski** [comment] 2023-09-01 20:25
Hello @eileencodes , thanks for the reply

> And since the test isn't running a request I don't think the middleware is installed

Can you suggest me some resources showing how to properly test the `ActionCable` channel so that It runs the whole ws request? I was looking into [Rails guides](https://guides.rubyonrails.org/testing.html#testing-action-cable) and the way they describe tests does not seem to run the whole request stack, just the channel functions so it was difficult to reproduce in specs. The way I came across that was when I was using AC with my frontend app so it was more of a real life scenario.

> If ActiveRecord::Base should have a different schema than the AnimalsRecord then there should be an additional connection defined first and connected in ApplicationRecord.

I'm not sure I understood this part. This setup was expected to have the same schemas for cats and dogs, just use separate db as shards when connecting via `AnimalsRecord`.

**Comment by eileencodes** [comment] 2023-09-05 13:42
> Can you suggest me some resources showing how to properly test the ActionCable channel so that It runs the whole ws request?

I honestly have no idea, I've never actually used Action Cable. I don't need a test though, if it works in the rails server I can debug from there too. I just don't see any logs for Action Cable with the server started either.

> I'm not sure I understood this part. This setup was expected to have the same schemas for cats and dogs, just use separate db as shards when connecting via AnimalsRecord.

`ActiveRecord::Base` is required to have a connection and since there isn't a `connects_to` in `ApplicationRecord`, it will use cats because it takes the first config. The connection will be established here: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railtie.rb#L304. So if `cats` and `dogs` are shards, there needs to be another connection that's defined for `ActiveRecord::Base`. This is usually the connection used to route to shards.

**Comment by pospieszynski** [comment] 2023-10-08 21:16
Hi @eileencodes 
I've just found a related problem where the value of `shard_resolver` is not respected, this time related to `.current_shard` being used for tagged logs ( reported here: https://github.com/rails/rails/issues/49545 ). Thought I'd ping you here in case that bug helps to inform where the problem comes from. The same app as in this thread can be used to see the problem.

**Comment by zzak** [comment] 2023-10-09 00:15
@pospieszynski I'm going to close this since it seems you've identified the bug and is being worked on. Feel free to re-open if there is something else actionable here.

**Closed by zzak** 2023-10-09 00:15 UTC

**Comment by pospieszynski** [comment] 2023-12-03 14:46
Hi @eileencodes, @zzak I wanted to kindly ask if there are any updates when it comes to this issue and related (#49545)?
It seems as db sharding feature still has some bottlenecks and probably not a lot of resources are there to work on it. 

If that would make sense for you, I can try to help with that - do you mind sharing some docs/notes related to db sharding or maybe we can jump on a call and try to tackle it together? Cheers!;)

**Comment by pospieszynski** [comment] 2024-02-27 16:10
Hey @eileencodes , @zzak sorry to bother you, do you know if there are any plans to fix that?
