### ISSUE TITLE
How to properly keep the module name in `app/` under Rails 7?

### ISSUE THREAD

**Issue by kalsan** [rails/rails#47024] opened 2023-01-16 17:05 UTC
Hi! 

My goal is to define the class `Foo::Bar` in `app/foo/bar.rb` using Rails 7 and Zeitwerk. I've read a few issues and I'm confused as to what the recommended approach to achieve this would be for a modern Rails+Zeitwerk application.

A starting point is https://github.com/rails/rails/issues/40126#issuecomment-816275285 where `ActiveSupport::Dependencies.autoload_paths` is used among others.

Since https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#config-autoload-paths states that `ActiveSupport::Dependencies.autoload_paths` should be avoided, I looked for possible alternatives and found https://github.com/rails/rails/issues/38725 which is also authored by @fxn .

To bypass the frozen Array from within a Gem initializer, I found inspiration from https://github.com/rails/rails/commit/43863bfc5716d8bd2f5be59920239aee1470465a and compiled this to:

```ruby
# lib/mygem/railtie.rb
class Mygem
  class Railtie < Rails::Railtie
    initializer "mygem.configure_eager_load_paths", before: :load_environment_hook, group: :all do
      Rails.application.config.eager_load_paths.delete("#{Rails.root}/app/foo")
      Rails.application.config.eager_load_paths.unshift("#{Rails.root}/app")

      # Prevent *.rb files in assets and views directories to be loaded (optional)
      Rails.autoloaders.main.ignore("#{Rails.root}/app/assets")
      Rails.autoloaders.main.ignore("#{Rails.root}/app/views")
    end
  end
end
```

Since I've only recently started to get into loading in Rails and/or Zeitwerk, I am unsure whether that would be a good idea. In a quick experiment, this method manages to achieve a situation where `app/foo/bar.rb` can define `Foo::Bar` instead of just `Bar`. However, is this the way to go? Are there disadvantages compared to the `ActiveSupport::Dependencies.autoload_paths` approach?

I hope this issue makes sense. Any clarification would be much appreciated.

Cheers,
Kalsan

**Comment by fxn** [comment] 2023-01-16 17:17
Nowadays, the easiest way to do that is to define a namespace for that directory configuring the loader directly (this is OK, the loader is public interface).

Would be something like this (untested):

```ruby
initializer "my_gem.autoload_paths", after: :bootstrap_hook do
  ActiveSupport::Dependencies.autoload_paths.delete("#{Rails.root}/app/foo")
  Rails.autoloaders.main.push_dir("#{Rails.root}/app/foo", namespace: Foo)
end
```

The first line in the block won't be needed in Rails 7.1, but it won't hurt either if you need to support multiple Rails versions.

Could you give it a try?

**Comment by kalsan** [comment] 2023-01-17 07:22
Using Rails 7.0.4 here. These are my findings:

`namespace ::Foo` is required to prevent the constant to become `MyGem::Foo`

Also, the following is no longer working compared to the approach proposed above:

```ruby
class Foo::Bar::Baz
end
```
-> Missing constant `Foo`

Instead, the following is required in at least one file (or create a dummy file defining `Foo` and another one defining `Foo::Bar`:

```ruby
module Foo
  module Bar
    class Baz
    end
  end
end
```

Best,
Kalsan

**Comment by fxn** [comment] 2023-01-17 07:37
@kalsan Awesome.

If there is one file that needs that, it is not because of Rails. The autoloader resolves constants the way Ruby does.

It could be the case that the code in that file needs that particular variant because it relies on that particular nesting. This is normal Ruby programming.

Closing then.

**Closed** 2023-01-17 07:38 UTC

**Comment by fxn** [comment] 2023-01-17 07:44
Ah, let me also add that `Foo` has to be already in memory when the initializer runs.

That is implicit because the call has it. And `Foo` cannot be an autoloadable constant, which in Rails 7 is not possible by design, but in Rails 6 it still is with a warning.

So, that initializer has to either define the namespace, or have it `require`d from a file outside the autoload paths that defines it.

**Comment by kalsan** [comment] 2023-01-17 08:20
Awesome, thanks a lot for your time and your answers! Very helpful.
