### ISSUE TITLE
Code is not reloaded in dev with Docker on OS X

### ISSUE THREAD

**Issue by jeromedalbert** [rails/rails#25186] opened 2016-05-28 19:33 UTC
### Steps to reproduce

0. Install the Docker toolbox on OS X. Here are my [instructions to install it with brew](https://gist.github.com/jeromedalbert/7476f445b7538b488c6ec34b5c4f3da4).
0. Clone https://github.com/jeromedalbert/rails_5_rc1_docker. I have created this dummy application specifically for this issue.
0. Follow the short instructions to set up the project and have a server running.
0. Open the application in your browser.
0. While the server is running, edit `app/controllers/static_controller.rb` and change `'hello world!'` to `'coconut'`.
0. Reload the page in your browser.

### Expected behavior
The page should display "coconut".

### Actual behavior
The page displays the old "hello world!" text.

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1

### Workaround

To make code reloading work for now, in `config/environments/development.rb` replace

    config.file_watcher = ActiveSupport::EventedFileUpdateChecker

with

    config.file_watcher = ActiveSupport::FileUpdateChecker

Restart everything, and code reloading should work.

### Additional comments

I have a feeling that for the `ActiveSupport::EventedFileUpdateChecker` file watcher, the change event does not occur for docker-machine shared files. So it may be more about docker-machine than Rails. But since I am not versed enough in the `EventedFileUpdateChecker` internals, I cannot say for sure. 

Even if it is docker-machine's fault, since I cannot pinpoint the exact problem, I would not know how to articulate it if I were to open an issue on their github repo. We might also find a workaround in Rails or add a warning the Rails documentation. That's why I am opening this issue here. Any insight would be appreciated.

**Comment by gsamokovarov** [comment] 2016-05-28 19:49
The docker on OSX runs on a thin Linux virtual machine. The virtual machine provisioners share code between the VM and the host on a file system that doesn't support notification events, so we cannot use the new listener backend on those.

**Comment by fxn** [comment] 2016-05-28 20:24
What @gsamokovarov said.

Some setups do not work because fs events are not triggered. The generator has [some simple code](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/app_base.rb#L392) to comment out that configuration line.

Do you think the application generator can detect this particular setup somehow?

**Comment by jeremy** [comment] 2016-05-28 23:26
Note this will(/should) work with the [forthcoming Docker for Mac/Windows](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) that are now in beta. OS X FSEvents are bridged to inotify.

**Comment by lnikell** [comment] 2016-05-29 06:42
I had the same issue with my HyperV Ubuntu 16.04, any changes at controllers, models not affected until restart server. Only css and changes in views work properly

**Comment by fxn** [comment] 2016-05-29 07:16
This is something Rails cannot do anything about unless support for detecting this at runtime and hot-switching the monitors is implemented.

Also, you could generate the conservative option always (it was this way when the feature was first implemented). But it was decided to generate the config for the evented monitor by default (mod those simple exceptions linked above) because it is believed that most setups can benefit from it. If the setup does not support it, then you need to opt-out.

I think we can close this one on the basis of not having a bug here, but if you believe Rails could explain this better somewhere please feel free to make a proposal.

**Closed by fxn** 2016-05-29 07:16 UTC
Labels: activesupport, With reproduction steps

**Comment by mrkongo** [comment] 2016-08-21 16:21
@fxn:

> Also, you could generate the conservative option always 

How to?

**Comment by fxn** [comment] 2016-08-23 06:20
@mrkongo Go to *config/environments/development.rb* and comment

    config.file_watcher = ActiveSupport::EventedFileUpdateChecker

out. If not needed for anything else, you may also want to remove the `listen` gem dependency in *Gemfile*.

**Comment by krainboltgreene** [comment] 2017-02-14 00:20
For anyone looking at this, Docker For Mac has other file issues that prevent EventedFile from working. Use File and stick to Docker Toolbox.

**Comment by f1nnix** [comment] 2017-06-22 08:47
`FileUpdateChecker` fix doesn't work properly on:

* docker-machine version 0.11.0, build 5b27455
* Docker version 17.05.0-ce, build 89658be

After change, code is reloaded with ~5 min lag, which makes code reload featured practically useless. Is there any workaround for this?

Thank you.

**Comment by krainboltgreene** [comment] 2017-06-22 15:12
@f1nnix Frankly there never will. You're writing to a file on a computer, that then has to tell some extra file system (Likely vbfs or nfs) of the event, that then has to propagate to the guest machine's filesystem, that then has to report to docker that the file event happened.

Basically, avoid dealing with superhost machine file events.

**Comment by Glutexo** [comment] 2018-02-20 09:12
For me the `EventedFileUpdateChecker` does not work even on bare macOS without Docker. Switching to `FileUpdateChecker` solved the issue.

**Comment by krainboltgreene** [comment] 2018-02-20 17:24
That's sort of a "known issue" with Mac's file watcher. Some things (say, dropbox) can just take complete control, apparently?

**Comment by SeanNieuwoudt** [comment] 2019-09-11 08:21
Just to add to this issue. If you are running your Rails app within a VirtualBox VM, then you are highly likely to experience this too. It doesn't always happen though so it's very tricky to diagnose properly.

To fix the issue: 

In **environments/development.rb**, comment out: 
`config.file_watcher = ActiveSupport::EventedFileUpdateChecker` 

Add:
`config.file_watcher = ActiveSupport::FileUpdateChecker`

Current version of what I'm running (for context):
- Rails 6.0.0
- Vagrant 2.2.4
- VirtualBox 6.0

**Comment by nitsujri** [comment] 2020-10-01 15:32
It's probably just my system, but I recently upgraded to Docker Desktop Community 2.4.0.0 for Mac and lost file updates in Docker.

It works fine if I'm running on my host machine (OSX) or if I switch the `file_watcher` to `FileUpdateChecker`.

Doesn't feel right to do that.

**Comment by nitsujri** [comment] 2020-10-02 02:30
Opened an issue w/ Docker as well https://github.com/docker/for-mac/issues/4962.

Here's a repo for reproduction w/ instructions: https://github.com/jenfi-eng/docker-rails-reload-issue
