### ISSUE TITLE
Unchanged activerecord object has changed? = true with rails5 + postgres json[] column + special characters

### ISSUE THREAD

**Issue by nbrustein** [rails/rails#26991] opened 2016-11-07 21:01 UTC
If an active record object has a json[] property that includes a special character, then `changed?` will be true even when nothing has changed.

### Steps to reproduce

 * Create an active record class that has a column of type `json[]`
 * Store a value in that array that includes a special character like `Ѭ`
 * Load the row in active record
 * call `attributes` on the active record instance
 * `changed?` will be true, even before you make any changes

Here is a test showing this behavior

````
it "should not be changed once it is loaded up" do
    instance = MyModel.new
    instance.assign_attributes({
        "my_json_array" => [{"description"=>"Ѭ"}]
    })
    instance.save!
    reloaded = MyModel.find(instance.id)

    expect(reloaded.changed?).to be(false) # this will pass
    reloaded.attributes
    expect(reloaded.changed?).to be(false) # this will fail
end
````

Here is a test showing that this behavior is coming from `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array`

````
it "should not change in serialization in rails 5" do
    instance = ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array.new(ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Json.new)
    str = "{\"{\\\"description\\\":\\\"Ѭ\\\"}\"}"
    deserialized = instance.deserialize(str)
    expect(instance.serialize(deserialized)).to eq(str) # this fails
end
````

And here is a test showing what I think is the analogous code from rails 4, which passes
````
it "should not have a broken array class in rails 4" do
    instance = ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array.new(ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Json.new)
    str = "{\"{\\\"description\\\":\\\"Ѭ\\\"}\"}"
    deserialized = instance.type_cast_from_database(str)
    expect(instance.type_cast_for_database(deserialized)).to eq(str) # this passes
end
````

### Expected behavior
When I load an instance from the database with a special character inside of a column of the `json[]` type, `changed?` should be false when I haven't made any changes

### Actual behavior
When I load an instance from the database with a special character inside of a column of the `json[]` type, `changed?` is true once I have called `attributes`

### System configuration
**Rails version**:
Rails 5.0.0.1

**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by nbrustein** [comment] 2016-11-07 21:06
@sgrif I saw that you have a lot of activity in `connection_adapters/postgresql/oid/array.rb`, so I thought this issue might be interesting to you, and you might have some suggestions.  I hope it's not rude to point it out to you.  I don't mean to suggest that I expect you to fix it ;)

**Comment by nbrustein** [comment] 2016-11-07 21:27
Update: it appears that `text[]` columns do not have this issue.  Only, as far as I know, `json[]` columns.

**Comment by maclover7** [comment] 2016-11-07 21:58
Since this passed for you on Rails 4.2.x, can you do a `git bisect` to determine which commit introduced a possible regression? Thanks!

**Comment by palkan** [comment] 2016-11-09 11:26
Btw, this one looks like a solution, but haven't been merged yet https://github.com/maclover7/rails/commit/efd8c0186886fac6cf7982d662bb11cc7cf6c9f1#diff-71a38fd3eeeff55fbd47a03809ded3bd .

**Comment by maclover7** [comment] 2016-11-09 22:14
Looks like this is closely related to #22730, a previously reported issue, which claims to be fixed via https://github.com/rails/rails/commit/7ba3a48df5bfdc5e98506bb829f937e03b55a5b3.

@palkan that commit is part of now closed PR #23619

@sgrif any thoughts? 😬

**Comment by sgrif** [comment] 2016-11-10 01:59
It's likely an encoding issue. I will look/fix when I'm back in the country next week

**Comment by maclover7** [comment] 2016-11-17 03:07
ref #27076

**Closed** 2016-11-17 20:02 UTC
Labels: activerecord, attached PR, needs feedback, PostgreSQL

**Comment by nbrustein** [comment] 2016-11-17 22:27
thx

**Comment by nbrustein** [comment] 2016-11-28 16:19
@maclover7, @sgrif: I pulled in rails `5-0-stable`, which includes this PR, and the test above (`it "should not be changed once it is loaded up" do`) is still failing. (also tried with `master`)

**Comment by booleanbetrayal** [comment] 2016-11-28 16:19
Can verify @nbrustein 's experience above ^

**Comment by booleanbetrayal** [comment] 2016-12-21 17:58
@rafaelfranca - we are definitely still experiencing this issue in the just-released 5.0.1 stable. Can you please re-open this issue?

**Comment by booleanbetrayal** [comment] 2016-12-21 18:02
FWIW - we're seeing #27201 as definitely fixed ... just not this specific encoding-related issue.

**Comment by rafaelfranca** [comment] 2016-12-21 18:03
@booleanbetrayal could you open an new issue with a reproducible script like this https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by obie** [comment] 2017-01-12 20:22
I'm seeing this (or a very similar) issue in my 5.0.1 app, with no special characters needed. @rafaelfranca should I make a new Issue or can we reopen this one?

**Comment by obie** [comment] 2017-01-12 20:28
BTW I'm having trouble reproducing the issue in a test, but working on it. Will post update as available.

**Comment by obie** [comment] 2017-01-12 20:29
@nbrustein @booleanbetrayal Did you guys find some sort of solution or workaround? This is killing me at the moment.

**Comment by maclover7** [comment] 2017-01-12 20:53
@obie If seeing a variant of this issue, can you please open up a new issue with a reproduction script? Best to handle it there :)

**Comment by nbrustein** [comment] 2017-01-12 22:25
Our workaround is the following code.  We do this in the one model with the json[] property.

We only care about the `changed?` method, but you might want to implement this in `changes` or somewhere else.  It's ugly, but it does the job.

````
def changed?
        return false unless super
        if changes.size == 1 &&
            changes.keys[0] == 'my_json_array' &&
            changes['stream_entries'][0] == changes['my_json_array'][1]
            return false
        end
        true
end
````

**Comment by maclover7** [comment] 2017-01-12 22:36
@nbrustein if there is a bug with rails, can you please open up a new issue for it with a reproduction script? thanks!

**Comment by obie** [comment] 2017-01-21 16:14
@nbrustein thanks for the workaround code, I will give it a try!

@maclover7 I will try to prepare a reproduction script as soon as I have time again. My first attempt was unsuccessful.
