### ISSUE TITLE
Non-dirty serialized column on child marked as changed when serialize class_name is specified

### ISSUE THREAD

**Issue by steakchaser** [rails/rails#18351] opened 2015-01-05 21:46 UTC
Rails 4.2.0

In a parent -> child relationship where the child has a `serialize` field with the `class_name` option set, the child serialize field is being marked as having changed when in fact it has not.  This then results in the child record being saved every time the parent is saved; even though nothing on the child has actually changed.

I believe this is related to #8328 

Test to reproduce (based on AR test template):
```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', '4.2.0'
    gem 'arel', '6.0.0'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.string :title
  end

  create_table :comments do |t|
    t.integer :post_id
    t.text :array
  end
end

class Post < ActiveRecord::Base
  has_many :comments, dependent: :delete_all

  accepts_nested_attributes_for :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post

  serialize :array, Array
end

class BugTest < Minitest::Test

  # def test_association_stuff
  #   post = Post.create!
  #   post.comments << Comment.create!
  #
  #   assert_equal 1, post.comments.count
  #   assert_equal 1, Comment.count
  #   assert_equal post.id, Comment.first.post.id
  # end

  def test_dirty_tracking_for_serialized_columns
    post = Post.create!
    post.comments << Comment.create!

    # Causes comment to be saved even though nothing has changed
    post.save!
    # Fails when class_name is specified for Comment serialize attribute
    assert_empty post.comments.first.changed_attributes
  end
end
```

**Comment by sgrif** [comment] 2015-01-05 21:53
Duplicate of https://github.com/rails/rails/issues/18169, this has already been fixed on master and 4-2-stable.

**Closed by sgrif** 2015-01-05 21:53 UTC
