### ISSUE TITLE
Generated schema.rb ignores "id: false"

### ISSUE THREAD

**Issue by kapso** [rails/rails#20859] opened 2015-07-13 06:58 UTC
This is on Rails `4.2.3` (Ruby 2.2.2) - `pg` gem (0.18.2)

Table migration:
```ruby
create_table :my_table, id: false do |t|
  t.string :id, primary_key: true
  t.datetime :created_at, null: false
end
```

But in `schema.rb`, `id: false` is lost
```ruby
create_table "my_table", force: :cascade do |t|
  t.datetime "created_at", null: false
end
```

I am using Postgres 9.4.x

**Comment by sgrif** [comment] 2015-07-18 13:24
Duplicate of https://github.com/rails/rails/issues/20749

**Closed by sgrif** 2015-07-18 13:24 UTC
