### ISSUE TITLE
strict_loading error in Association#find_target

### ISSUE THREAD

**Issue by michael-ujet** [rails/rails#48617] opened 2023-06-30 16:53 UTC
### Steps to reproduce
I'm not sure what a minimal representation would be.  We've been running a large application on rails 7.0.5 for a while, but a recent change caused the following error:

```
The :mode option must be one of [:all, :n_plus_one_only].
ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-7.0.5/lib/active_record/core.rb:663:in `strict_loading!'
ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-7.0.5/lib/active_record/associations/association.rb:237:in `block in find_target'
ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-7.0.5/lib/active_record/core.rb:504:in `init_with_attributes'
ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-7.0.5/lib/active_record/persistence.rb:537:in `instantiate_instance_of'
ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-7.0.5/lib/active_record/querying.rb:76:in `block (2 levels) in _load_from_sql'
ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-7.0.5/lib/active_record/result.rb:69:in `each'
```

we're not using strict loading anywhere in our code.  It _seems_ this is due to the following in `Association#find_target`:

```ruby
if owner.strict_loading_n_plus_one_only? && reflection.macro == :has_many
  record.strict_loading!
else
  record.strict_loading!(false, mode: owner.strict_loading_mode)
end
```

which should maybe be:
```ruby
  record.strict_loading!(false)
```

### Expected behavior
No ArgumentError

### Actual behavior
ArgumentError raised

### System configuration
**Rails version**: 7.0.5

**Ruby version**: 3.1.4

**Comment by abhisheksarka** [comment] 2023-07-02 14:39
@michael-ujet Can you share the association setup of the models and for the specific call for which this error is being raised? I was not able to reproduce this in 7.0.5

**Comment by michael-ujet** [comment] 2023-07-05 14:02
i was able to get past the error by making the change above, but then when i went back to pristine gems, i could not reproduce the error either.  i don't know if that had something to do with class loading order or some particular state of my data when i tried to bring up rails. sorry.

**Comment by adrianna-chang-shopify** [comment] 2023-07-05 19:48
👋 I'm going to close this, but if it comes up again please open another issue with repro steps. Thanks!

**Closed by adrianna-chang-shopify** 2023-07-05 19:48 UTC

**Comment by arenclissold** [comment] 2023-08-10 05:16
@adrianna-chang-shopify 
I'm not sure I can add reproduction steps but I'm receiving the same error consistently. We have a large app and this error is occurring in production only. It occurs when attempting to access a user's avatar( has_one :avatar, dependent: :destroy) but only in 3 specific points in our app, all within views.

I'm going to downgrade to a different rails 7 version in the meantime, if I find out more I'll post here or open a more detailed issue

**Comment by adrianna-chang-shopify** [comment] 2023-08-10 18:42
Hi @arenclissold -- thanks for reporting! Yes, definitely feel free to follow up here if you glean any new information.

**Comment by moliver-hemasystems** [comment] 2023-08-18 17:02
I'm currently running into the issue @michael-ujet described while upgrading an application to Rails 7.  I tried downgrading to an earlier version of Rails 7, but either I wasn't going early enough, or it didn't really matter.  The code that threw the error was a record that was trying to reference a belongs_to association.

I added some debugging statements to the `find_target` method to see that `owner` was the instance of the record trying to reference its belongs_to association, and `owner.strict_loading_mode` was nil.

Since we're not using strict loading, to resolve the issue, I just added the following method to our ApplicationRecord base model:

```ruby
def strict_loading_mode
  :all
end
```

What's interesting about this is that I upgraded another app to Rails 7 as well, but didn't run into this issue.  I'll probably add the same method though, just in case.

**Comment by yknx4** [comment] 2023-11-21 01:48
I just had the same issue too

```
Error message:
The :mode option must be one of [:all, :n_plus_one_only].
…ndor/bundle/ruby/3.2.0/gems/activerecord-7.0.7.2/lib/active_record/core.rb:663:in `strict_loading!'
….0/gems/activerecord-7.0.7.2/lib/active_record/associations/association.rb:237:in `block in find_target'
```

```
has_many :program_requirements, inverse_of: :program, dependent: :delete_all
```

```
belongs_to :program, touch: true
```

This is how we have the relation set up.

**Comment by yknx4** [comment] 2023-11-21 07:01
For the record, I also did find that `owner.strict_loading_mode` was nil but wasn't able to reproduce. 

I used this monkeypatch to bypassit

```ruby
module ActiveRecordBaseMonkeyPatch
  def strict_loading_mode
    original_strict_loading_mode = super
    if [:all, :n_plus_one_only].include?(original_strict_loading_mode)
      original_strict_loading_mode
    else
      # In case you want to report to your error handler (we use NewRelic)
      # exception = StandardError.new("strict_loading_mode must be one of [:all, :n_plus_one_only]. Got: #{original_strict_loading_mode.inspect}")
      # exception.set_backtrace(caller)
      # NewRelic::Agent.notice_error(e, { expected: true, custom_params: { original_strict_loading_mode: } })
      :all
    end
  end
end

ActiveSupport.on_load(:active_record) { prepend ActiveRecordBaseMonkeyPatch }
```

**Comment by volleio** [comment] 2023-12-01 15:31
Just ran into this issue upgrading from 6.1.7.2 to 7.0.4.3, despite also not using strict loading anyhere.
We identified that ActiveRecord was loading association information from the cache (Memcached in our case) when this intermittent issue was raised, so we cleared the whole cache with `Rails.cache.clear` and the problem seems to be resolved.

**Comment by sergiogomez** [comment] 2024-07-03 12:16
We have this same issue upgrading a rails application from 6.1 to 7.0, and we think we understand it:

We're caching AR objects in Rails 6.1, and these cached objects [don't have](https://github.com/rails/rails/blob/6-1-stable/activerecord/lib/active_record/core.rb#L780-L791) the new instance variable `@strict_loading_mode` ([added in Rails 7](https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/core.rb#L752-L767)).

Once we're using the upgraded application with Rails 7.0, and we are still loading these cached objects from Rails 6.1 without that variable, [this getter](https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/core.rb#L671) returns `nil`, and [it fails](https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/associations/association.rb#L237).

So [this monkey patch](https://github.com/rails/rails/issues/48617#issuecomment-1820344574) is a valid workaround 😉

**Comment by xjunior** [comment] 2024-09-15 19:06
> We have this same issue upgrading a rails application from 6.1 to 7.0, and we think we understand it:
> 
> We're caching AR objects in Rails 6.1, and these cached objects [don't have](https://github.com/rails/rails/blob/6-1-stable/activerecord/lib/active_record/core.rb#L780-L791) the new instance variable `@strict_loading_mode` ([added in Rails 7](https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/core.rb#L752-L767)).
> 
> Once we're using the upgraded application with Rails 7.0, and we are still loading these cached objects from Rails 6.1 without that variable, [this getter](https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/core.rb#L671) returns `nil`, and [it fails](https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/associations/association.rb#L237).
> 
> So [this monkey patch](https://github.com/rails/rails/issues/48617#issuecomment-1820344574) is a valid workaround 😉, or maybe something like this:
> 
> ```ruby
> module ActiveRecordBaseMonkeyPatch
>   def strict_loading_mode
>     @strict_loading_mode || :all
>   end
> end
> 
> ActiveSupport.on_load(:active_record) { prepend ActiveRecordBaseMonkeyPatch }
> ```

Thank you for your patch, this saved our rails upgrade maintenance window.
