### ISSUE TITLE
Avoid printing screenshots to terminals that don't support them

### ISSUE THREAD

**Issue by gravitystorm** [rails/rails#31159] opened 2017-11-15 17:05 UTC
### Steps to reproduce

The system tests include the [ability to output screenshots of tests](https://github.com/renchap/rails/blob/79435c0e645b807243edf662b2462234494aacd9/actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb), and this happens by default for failing tests. These are sent to the terminal, but some terminals don't support inline images, and instead print out [the base64-encoded copy of the image](https://github.com/renchap/rails/blob/79435c0e645b807243edf662b2462234494aacd9/actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb#L71-L75). I've encountered this using the default "Terminal" in Ubuntu 16.04. 

To reproduce, change any system test so that it fails, and run this on Ubuntu 16.04. 

It is hinted that this might be an expected problem in #28185 (final paragraph). Some terminals will swallow the image data, but when images do get printed to the terminal it fills the scrollback with gobs and gobs of data.

![screenshot from 2017-11-15 17-00-43](https://user-images.githubusercontent.com/360803/32849399-eb26998e-ca26-11e7-8793-44174867784b.png)

### Expected behavior

The base64-encoded image data should not be shown on terminals that don't support inline images. The output should be "simple" rather than "inline" for these terminals. Perhaps "simple" should be the default and "inline" only for terminals that are known to support it.

### Actual behavior

The scrollback is completely filled with base64-encoded image data.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4

**Comment by rafaelfranca** [comment] 2017-11-15 19:08
Is not setting `CAPYBARA_INLINE_SCREENSHOT` sufficient?

**Comment by gravitystorm** [comment] 2017-11-16 15:01
Running something like `RAILS_SYSTEM_TESTING_SCREENSHOT=simple bundle exec rails test:system` does suppress the base64 output. However, I think this counts as a workaround rather than a proper fix.

**Comment by rafaelfranca** [comment] 2017-11-16 19:50
You can export this environment variable in your shell. I don't think Rails should detect if a terminal support embedded images or not. You know which terminal you are using so you can set the config you want.

**Comment by gravitystorm** [comment] 2017-11-16 20:15
OK, if terminal detection is ruled out, then the default should be changed to "simple".

 I don't believe that this non-standard escape sequence (iTerm2 even describes it as  "a set of proprietary escape sequences" in their docs) should be used as default, given the lack of widespread support in other common terminals. It would provide fewer headaches if the iTerm2 users were instead asked to *enable* it using environment variables, rather than the output being "broken by default" for many users.

**Comment by rafaelfranca** [comment] 2017-11-16 20:24
That is a valid point. @eileencodes what do you think?

**Comment by eileencodes** [comment] 2017-11-16 20:47
1) I think changing the default to simple is fine

2) I'm confused why I've not seen this bug. I use Terminal.app and the screenshot is output as a list item.

**Comment by eileencodes** [comment] 2017-11-16 20:48
This is a duplicate of #30957 as well.

**Comment by matthewd** [comment] 2017-11-16 23:48
> The base64-encoded image data should not be shown on terminals that don't support inline images

Indeed. But I thought that was what extensible escape codes were for -- so that a terminal which doesn't recognise the code can properly ignore it, and only show the part of the text that should be visible. :confused:

If a browser was displaying unknown HTML tags as literal text, we'd call that a bug in the browser, not the page content.

I guess I'm unclear where this sits on that spectrum.

**Closed** 2017-11-29 16:02 UTC

**Comment by eileencodes** [comment] 2017-11-29 16:07
I've changed the default to simple so hopefully that will behave better for you. Thanks for the report!
