### ISSUE TITLE
link_to from mailer templates does not go to :put action 

### ISSUE THREAD

**Issue by barsukov** [rails/rails#19929] opened 2015-04-28 07:17 UTC
Probably I put my problem here. I have ``link_to "lala",url, method: put`` from my mail template every time try to call ``show`` (GET) method from controller not a ``update``(PUT). Url is correct I try every methods with url_for and direct try to set ``:action``. I foud the similiar problem here http://stackoverflow.com/questions/12812166/call-update-action-via-link-in-email-with-rails

**Comment by senny** [comment] 2015-04-28 08:13
@barsukov can you provide a minimal sample application to reproduce the problem? You can create a blank rails app and only add in the functionality to replicate the issue. Then upload it to GitHub.

**Comment by barsukov** [comment] 2015-04-28 08:16
You mean I need to create simple rails app with this problem and provide the link to this?

**Comment by senny** [comment] 2015-04-28 08:17
@barsukov yes, that would go a long way to debug your problem and provide help.

**Comment by barsukov** [comment] 2015-04-28 08:22
OK I will

**Comment by prathamesh-sonpatki** [comment] 2015-04-28 08:59
I don't think we can create PUT, POST, DELETE links for mailer templates, because when user clicks on it, Rails UJS is not available to convert them to PUT or POST etc. 

I think what you can do is ->

Include a GET link in the email.
When user clicks on it, show a form to user on your app.
And then when user submits the form, it will be a PUT request.

**Comment by senny** [comment] 2015-04-28 09:02
@prathamesh-sonpatki is right. I somehow managed to miss the part that we are talking about a mailer template :pensive:. Going to close this issue.

@barsukov thank you for reporting.

**Closed by senny** 2015-04-28 09:02 UTC
Labels: actionview, needs feedback

**Comment by prathamesh-sonpatki** [comment] 2015-04-28 09:12
@senny Should I add a note about this in action mailer guide?

**Comment by senny** [comment] 2015-04-28 09:18
@prathamesh-sonpatki sure, I wouldn't go into too much depth though. A simple note that non-get links don't work should be fine.

**Comment by barsukov** [comment] 2015-04-28 11:40
But what happened in standard I think behaviour, I mean I want to confirm or decline some suggesstion for example (and when I go to the links I want to do this action) Of course I have already implement this problem I create to addtional GET action which call my Update action for exampel
```
def accept
  update
end
def decline
  update
end
```
But I think that is not a solution ...

**Comment by prathamesh-sonpatki** [comment] 2015-04-28 12:02
@barsukov We just added a note about it in guides - take.ms/Ot1C2

**Comment by barsukov** [comment] 2015-04-28 12:12
@prathamesh-sonpatki Thanks :)
