### ISSUE TITLE
active_support/json doesn't handle RSpec::Core::Example properly

### ISSUE THREAD

**Issue by kyrylo** [rails/rails#28996] opened 2017-05-05 16:04 UTC
### Steps to reproduce

Setup a simple test and run `RSpec.current_example.to_json` inside it (when `active_support/json` is required)

```ruby
> require 'json'
=> true
> RSpec.current_example.to_json
=> "\"#<RSpec::Core::Example \\\"doesn't set the default project_id\\\">\""
> require 'active_support/json'
=> true
> RSpec.current_example.to_json
SystemStackError: stack level too deep
from /Users/kyrylo/.gem/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
```

### Expected behavior

`to_json` shouldn't fail.

### Actual behavior

`SystemStackError` is being raised.

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.4.0

**Comment by robin850** [comment] 2017-05-08 15:05
Thanks for reporting @kyrylo ! Not sure if it's easily fixable but commenting just to give more context if someone tries to tackle this:

Actually, [`#encode`](https://github.com/rails/rails/blob/1edecda26efb1c8c0a6953c7dff41ad25ae3de0e/activesupport/lib/active_support/json/encoding.rb#L33) calls `#as_json` on the `RSpec::Core::Example` instance. The latter doesn't respond to `to_hash` so [`#as_json`](https://github.com/rails/rails/blob/1edecda26efb1c8c0a6953c7dff41ad25ae3de0e/activesupport/lib/active_support/core_ext/object/json.rb#L54) will call `#instance_values` which returns a `Hash` with the instance variables' name and value.

The problem is that instances of `RSpec::Core::Example` have a `@reporter` instance variable that has a `@configuration` one that has a `@world` one that has a `@filtered_examples` one that is a hash referencing the original instance so it's infinitely looping ([tiny example script here](https://gist.github.com/robin850/26c45dbda3ec778f8f0d4e25defbffac)).

**Comment by maclover7** [comment] 2017-05-08 22:08
cc @samphippen

**Comment by samphippen** [comment] 2017-05-09 13:57
@kyrylo what is the use case for calling `to_json` on `current_example`?

**Comment by kyrylo** [comment] 2017-05-09 14:29
> @samphippen 
> what is the use case for calling to_json on current_example?

It is called indirectly. I stumbled upon this bug while working on airbrake-ruby (https://github.com/airbrake/airbrake-ruby/issues/208). Airbrake tries to report fiber local variables and RSpec uses [`Thread.current[:__rspec]`](https://github.com/rspec/rspec-support/blob/e96cc73d0a7d46d9b1948d165c52f0aff78e9457/lib/rspec/support.rb#L77-L79) to store its metadata.

When I run tests related to that functionality, airbrake-ruby fetches what RSpec stored and calls `.to_json` on it. Apparently, among other things, RSpec stores an instance of `RSpec::Core::Example` there.

**Comment by samphippen** [comment] 2017-05-09 15:26
OK cool. My view on this is that calling `to_json` on an example is of little value and that I don't see a huge need to fix this. @myronmarston @jonrowe any further thoughts?

**Comment by myronmarston** [comment] 2017-05-09 15:34
If I'm reading this thread right, it sounds like we could define `RSpec::Core::Example#to_hash` and it would fix this problem.  Since `to_hash` is a general purpose conversion protocol and useful in its own right (and shouldn't be much effort to define), I think it makes sense for us to add it.

**Comment by matthewd** [comment] 2017-05-09 16:00
As @robin850 noted, without more specific guidance, our `to_json` implementation will attempt to encode the instance variables instead of just using `to_s`. Short of changing that approach entirely, I don't see any way we can support recursive references: at best, we could offer a more descriptive exception.

On that basis, I'm going to close this, and recommend that if airbrake-ruby is going to `to_json` arbitrary unknown objects (from the thread variables, in this case), its best option would be to call each of them directly, with a rescue. Even a perfect blacklist of "keys that are known to sometimes be used by libraries to store recursive data structures" wouldn't protect against a local application doing so.

**Closed by matthewd** 2017-05-09 16:00 UTC
Labels: activesupport
