### ISSUE TITLE
Non-dirty belongs_to validations aren't triggered in validation cycle

### ISSUE THREAD

**Issue by ramkumar-welab** [rails/rails#39695] opened 2020-06-22 11:50 UTC
### Steps to reproduce
post upgrading to Rails 5.2.4.3 from 5.2.3 found that the non-dirty associations aren't getting validated anymore. but our application has been working so far with the expectation that associations get validated irrespective of the changes in the association object. Seems this has been introduced with this change https://github.com/rails/rails/commit/6ea80b6103de9ef76dca9d51149dd94bec846642

1. create a rails project
 `rails new assoc_validaiton_bug -d mysql`
2. create Cutomer model
 `rails g scaffold customer name:string email:string`
3. Create a Alert model
`rails g scaffold alert title:string description:string customer_id: integer`
4. prepare db
 `rails db:create db:migrate`
5. add validation in Customer model
```
class Customer < ApplicationRecord
  validates_presence_of :email
end
```
6. create a belongs_to relationship in Alert model
```
class Alert < ApplicationRecord
  belongs_to :customer
  accepts_nested_attributes_for :customer
end
```

### Expected behaviour
association gets validates irrespective of the changes in the associated object. this is the behaviour as of Rails 5.2.3
```
alert = Alert.new(title: "connection issue", customer_attributes: {name: "hulk"})   
alert.save(validate: false)
alert.valid? # returns false
alert.errors.messages # returns {:"customer.email"=>["can't be blank"]}
```

### Actual behaviour
association isn't validated. this is the behaviour as of Rails 5.2.4.3 
```
alert = Alert.new(title: "connection issue", customer_attributes: {name: "hulk"})   
alert.save(validate: false)
alert.valid? # returns true
alert.errors.messages # returns {}
```

### System configuration
**Rails version**: 5.2.4.3

**Ruby version**: 2.5.7

**Comment by kamipo** [comment] 2020-06-26 00:06
Duplicate of #38045 which is caused by #36671.

**Closed by kamipo** 2020-06-26 00:06 UTC
