### ISSUE TITLE
ActiveSupport::SafeBuffer breaks Regexp.last_match

### ISSUE THREAD

**Issue by Thibaut** [rails/rails#33395] opened 2018-07-19 14:11 UTC
### Steps to reproduce

```ruby
> ActiveSupport::SafeBuffer.new("test").sub(/\w/) { pp Regexp.last_match };
nil

> "test".sub(/\w/) { pp Regexp.last_match };
#<MatchData "t">
```

### Expected behavior

`Regexp.last_match` should be set inside the `sub` / `gsub` block.

### Actual behavior

`Regexp.last_match` is `nil` (or the previous value) inside the `sub` / `gsub` block.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.4.4

**Comment by matthewd** [comment] 2018-07-19 14:18
This is a duplicate of #1555; there isn't a [(practical)](https://github.com/rails/rails/issues/12672#issuecomment-41995575) way it can be made to work, because the regexp "globals" are lexically scoped.

**Closed by matthewd** 2018-07-19 14:18 UTC
