### ISSUE TITLE
Getting Started with Rails: rails server fails when Yarn is not installed

### ISSUE THREAD

**Issue by yhoiseth** [rails/rails#38589] opened 2020-02-27 21:13 UTC
### Steps to reproduce

Following the [Getting Started with Rails guide](https://guides.rubyonrails.org/getting_started.html):

1. Install Rails
2. `rails new blog`
3. `cd blog`
4. `rails server`

### Expected behavior

The server starts without problems or with a friendly error message.

### Actual behavior

```
=> Booting Puma
=> Rails 6.0.2.1 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	77: from bin/rails:3:in `<main>'
	76: from bin/rails:3:in `load'
…
	 2: from /Users/yngve/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:88:in `data'
	 1: from /Users/yngve/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:91:in `load'
/Users/yngve/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:95:in `rescue in load': Webpacker configuration file not found /Users/yngve/Repositories/ruby/blog3/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /Users/yngve/Repositories/ruby/blog3/config/webpacker.yml (RuntimeError)
```

When running `rails webpacker:install`, I get:

```
Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
```

(Note that the same warning appears in the output of `rails new blog`.)

After installing Yarn, `rails webpacker:install` succeeds and `rails server` works.

### Discussion

I consider this a small issue. I was able to figure it out very easily. But the experience was not ideal, and it could throw some beginners off.

I'll try to suggest some improvements to the guide.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

**Comment by yhoiseth** [comment] 2020-02-27 21:15
I just discovered that this was [fixed a week ago](https://github.com/rails/rails/commit/cdef8b4dadb6fba9ac12689d2651ed0a980bb26c). Maybe there's some hickup preventing the fix from being visible on https://guides.rubyonrails.org/getting_started.html?

**Comment by rafaelfranca** [comment] 2020-02-27 22:02
Changes in the guides are only released when a new version of Rails are released. Because of that, that change will be reflected in the website when Rails 6.0.3 is released.

Thank you for the issue.

Duplicate of ##38322.

**Closed by rafaelfranca** 2020-02-27 22:02 UTC
