### ISSUE TITLE
Guides Issue: Anchor links miss their target in Safari

### ISSUE THREAD

**Issue by maxim** [rails/rails#38882] opened 2020-04-06 14:19 UTC
### Steps to reproduce

1. Open Safari 13.1 (might be an issue with others too) on a Mac.
2. Follow this url: https://edgeguides.rubyonrails.org/active_support_core_extensions.html.
3. Search-in-page (cmd+f) for: "inquiry" (no quotes) to find the link in the right-hand menu.
    <img width="169" alt="Screen Shot 2020-04-06 at 10 16 09" src="https://user-images.githubusercontent.com/7758/78568142-ad80a600-77ef-11ea-9fdd-18fadf23b606.png">
4. Click the "inquiry" link.

_Note: This bug cannot be reproduced if you were to go [directly to anchor](https://edgeguides.rubyonrails.org/active_support_core_extensions.html#inquiry)._

### Expected behavior

Page jumps to "Inquiry" section.

### Actual behavior

Page jumps to a place far from the anchor. Here's my result:

<img width="1072" alt="Screen Shot 2020-04-06 at 10 09 19" src="https://user-images.githubusercontent.com/7758/78567461-bae96080-77ee-11ea-8c49-dd9d96447748.png">

**Comment by jonathanhefner** [comment] 2020-04-09 00:09
I don't have a Mac to test with, but I cannot reproduce this behavior in Firefox nor Chromium (on Linux).

I notice the docs use Turbolinks, which has some [unresolved issues](https://github.com/turbolinks/turbolinks/issues/75) with same-page anchor links.  @maxim can you try disabling JavaScript and seeing if the problem persists?

**Comment by maxim** [comment] 2020-04-09 00:29
@jonathanhefner Confirmed, works every time with js disabled, broken every time when enabled.  And yes, this is only on Safari, I tried Chrome and Firefox too, no issues.

**Comment by jonathanhefner** [comment] 2020-04-09 01:32
@maxim Interesting, thank you for testing!  I know there are some big improvements coming to Turbolinks soon, likely including a fix for the same-page anchor issue.  If Turbolinks is indeed the cause, it might be best to wait until its next release before digging deeper.

**Comment by vipulnsward** [comment] 2020-04-11 17:26
Closing in favour of https://github.com/turbolinks/turbolinks/issues/75 for now.
The workarounds mentioned in the issue like https://github.com/turbolinks/turbolinks/issues/75#issuecomment-245894496 / https://github.com/turbolinks/turbolinks/issues/75#issuecomment-520415496 seem too much custom code for guides.

**Closed by vipulnsward** 2020-04-11 17:26 UTC

**Comment by scottmacpherson** [comment] 2020-05-13 02:14
There's something about the interaction between Turbolinks and SyntaxHighligher that's causing this, as disabling either one resolves this issue for me.

**Comment by p8** [comment] 2020-07-16 09:02
Replacing the javascript highlighter with Rouge (#39777) seems to have fixed this problem.
