### ISSUE TITLE
[BUG] numericality: { in: ... } is not validating as expected

### ISSUE THREAD

**Issue by marvoosh** [rails/rails#48732] opened 2023-07-13 11:11 UTC
### Steps to reproduce
Create a new model with an integer column.
On the model add a numericality validation {in:..} and give it a range.

```ruby
column :quantaty, :integer

class dogs
    validates :quantity, numericality: { in: 0..4 }
end
```

### Expected behavior

I expected this test to pass:
```ruby
it 'should validate the numericality of quantity' do
    expect(dogs).to validate_numericality_of(:quantity).is_in(0..4)
end
```
### Actual behavior

The test fails with this error:
> Expected Dogs to validate that :quantity looks like a number
from ‹0› to ‹4›, but this could not be proved.
After setting :quantity to ‹5›, the matcher expected the Dogs
to be invalid, but it was valid instead.

### System configuration
**Rails version**:
Rails 6.1.7.2

**Ruby version**:
ruby 3.2.0

**Comment by fatkodima** [comment] 2023-07-13 11:21
Can you verify the issue still happening on the rails' `main` branch and, if so, create a reproducible test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb ?

**Comment by stufro** [comment] 2023-07-15 15:38
This issue is not happening on `main` branch. However I can reproduce it when using rails 6.1.7.2.

This issue seems to be resolved in v7.0.0 and above.

## Script used to reproduce issue</summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  # gem "rails", github: "rails/rails", tag: "v6.1.7.2" # this version will fail
  gem "sqlite3"
  gem "rspec"
  gem 'shoulda-matchers', '~> 5.0'
end

require "active_record"
require "action_controller"
require "action_view"
require "logger"

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :contributors
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments

  validates :contributors, numericality: { in: 0..4 }
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

describe "rails/rails #48732 bug test" do
  include Shoulda::Matchers::ActiveModel

  it "should validate the numericality of contributors" do
    post = Post.create!(contributors: 2)

    expect(post).to validate_numericality_of(:contributors).is_in(0..4)
  end
end
```

**Comment by fatkodima** [comment] 2023-07-15 16:21
I think, you should open this bug report in the `shoulda-matchers` repo, as this is most likely a bug in it. Or provide us a bug report without external gems, that demonstrates that the validation does not work as expected.

**Comment by stufro** [comment] 2023-07-16 15:33
I have tweaked my script to remove other gems and this does appear to be a bug in rails v6.1.7.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", github: "rails/rails", branch: "main"
  gem "rails", github: "rails/rails", tag: "v6.1.7.2" # this version will fail
  gem "sqlite3"
end

require "active_record"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :contributors
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments

  validates :contributors, numericality: { in: 0..4 }
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

post = Post.create!(contributors: 5)
puts post.valid? # => true
puts post.errors.messages # => {}
```

**Comment by fatkodima** [comment] 2023-07-16 15:48
That was fixed in rails 7 (https://github.com/rails/rails/pull/41022). Since that PR was actually not a bug fix (but a feature implementation) and rails 6 is not supported for bug fixes (see https://guides.rubyonrails.org/maintenance_policy.html), you need to upgrade to newer rails.

**Closed by fatkodima** 2023-07-16 15:48 UTC
Labels: more-information-needed
