### ISSUE TITLE
`rails db:drop:all db:create:all db:migrate` isn't creating tables after adding InternalMetadata/EnvironmentMismatchError

### ISSUE THREAD

**Issue by ojab** [rails/rails#23279] opened 2016-01-27 14:24 UTC
Right now `rails db:drop:all db:create:all db:migrate` leaves DB without any tables, before adding internal metadata this command resulted in migrated DB.
Unfortunately I can't bisect the issue because in many commits dropping/creating/migration in a single run is broken, but AFAICS the issue emerged after adding InternalMetadata/EnvironmentMismatchError.

The first bad commit could be any of:
d70c68d76abcbc24ef0e56b7a7b580d0013255dd
f6628adc11e2e57db75030fca9bae035be5cd95b
c1a1595740b243bed02f5e59090cc58dac77bbf3
de2cb20117af68cef4126d8998cc63e178c58187
302e92359cc88258ae15a82454c58408a4b8157e
a76c4233a9ee9ffbf413c4b8353e73e8ffbeb3a5
350ae6cdc1ea83e21c23abd10e7e99c9a0bbdbd2
ab40d71ff88f99ee4219747fcc8774514ec50ef8
7b065f623f2a56d74eca88ed27970c71a76f0a17
921997675258147fdc2bbbca0da4fb0c771c218d
30391e9ddba745d6bdc0b23f526ecf432dfe6adf
900bfd94a9c3c45484d88aa69071b7a52c5b04b4
34ac8a1e98e85b28fe3ee02a83c85cdaa4b77714
We cannot bisect more!

cc @schneems

**Comment by prathamesh-sonpatki** [comment] 2016-01-27 14:46
May be we can run `bin/rails db:environment:set` before `rails db:migration` is run? 

r? @schneems

**Comment by prathamesh-sonpatki** [comment] 2016-01-27 14:46
Confirmed this issue on master.

**Comment by schneems** [comment] 2016-01-27 15:10
Are you getting any errors or output? Can you run with `--trace`?

**Comment by prathamesh-sonpatki** [comment] 2016-01-27 15:17
Getting this output 

```
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

	bin/rails db:environment:set RAILS_ENV=development

bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

**Comment by schneems** [comment] 2016-01-27 15:24
This is what I get

```
2.3.0  /tmp/blerg
$ rails db:drop:all db:create:all db:migrate --trace
** Invoke db:drop:all (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config
** Execute db:check_protected_environments
** Execute db:drop:all
** Invoke db:create:all (first_time)
** Invoke db:load_config
** Execute db:create:all
** Invoke db:migrate (first_time)
** Invoke environment
** Invoke db:load_config
** Execute db:migrate
== 20160127151202 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0016s
== 20160127151202 CreateUsers: migrated (0.0016s) =============================

** Invoke db:_dump (first_time)
** Execute db:_dump
** Invoke db:schema:dump (first_time)
** Invoke environment
** Invoke db:load_config
** Execute db:schema:dump
```

Though it still doesn't have tables

```
$ rails dbconsole
.tabglSQLite version 3.8.5 2014-08-15 22:37:57
Enter ".help" for usage hints.
sqlite> .tables
sqlite>
```

**Comment by schneems** [comment] 2016-01-27 15:25
Weird that running only the `db:migrate` works

```
$ rake db:migrate
== 20160127151202 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0012s
== 20160127151202 CreateUsers: migrated (0.0013s) =============================

2.3.0  /tmp/blerg
$ rails dbconsole
SQLite version 3.8.5 2014-08-15 22:37:57
Enter ".help" for usage hints.
sqlite> .tables
active_record_internal_metadatas  users
schema_migrations
```

**Comment by ojab** [comment] 2016-01-27 15:26
Getting the same as @schneems here, but saw `bin/rails db:environment:set RAILS_ENV=development` error during bisecting.

**Comment by schneems** [comment] 2016-01-27 15:36
You'll get that error if you're trying to run that command on a non-empty database that was upgraded from Rails 4.2. To resolve it follow directions, run that command. That error is expected, there's no way around it, running it is part of the upgrade process.

I'm running off of a `rails new` app with Rails 5 pointing at master in the Gemfile.

This command also works:

```
$ rails db:drop db:create db:migrate --trace
```

I'm thinking there's some strange interaction with the `:all` invocations.

**Comment by prathamesh-sonpatki** [comment] 2016-01-27 15:37
I am also getting same output now, in my case the database did not had anything in `active_record_internal_metadatas` so the error related to missing data was thrown for the first time.

But now I am getting same issue from https://github.com/rails/rails/issues/23279#issuecomment-175687541 :smile:

**Comment by schneems** [comment] 2016-01-27 20:16
It works if you don't do `all` on `db:create`

```
$ env VERBOSE=true rails db:drop:all db:create db:migrate --trace
```

**Comment by schneems** [comment] 2016-01-27 20:18
BTW I figured out a one liner to test (if you're using a SQLite3 database

```
$ env VERBOSE=true rails db:drop:all db:create:all db:migrate --trace && echo ".tables" | rails dbconsole
```

**Comment by schneems** [comment] 2016-01-27 20:46
I figured out what is going on. I added some logging to see what database we are connected to


```
$ env VERBOSE=true rails db:drop:all db:create:all db:migrate --trace && echo ".tables" | rails dbconsole
** Invoke db:drop:all (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke environment (first_time)
** Execute environment
== Connecting to database: nil
** Invoke db:load_config
** Execute db:check_protected_environments
** Execute db:drop:all
** Invoke db:create:all (first_time)
** Invoke db:load_config
** Execute db:create:all
== Connecting to database: {"adapter"=>"sqlite3", "pool"=>5, "timeout"=>5000, "database"=>"db/development.sqlite3"}
== Connecting to database: {"adapter"=>"sqlite3", "pool"=>5, "timeout"=>5000, "database"=>"db/test.sqlite3"}
== Connecting to database: {"adapter"=>"sqlite3", "pool"=>5, "timeout"=>5000, "database"=>"db/production.sqlite3"}
** Invoke db:migrate (first_time)
** Invoke environment
** Invoke db:load_config
** Execute db:migrate
========
"development"
== 20160127151202 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0012s
"development"
== 20160127151202 CreateUsers: migrated (0.0013s) =============================

** Invoke db:_dump (first_time)
** Execute db:_dump
** Invoke db:schema:dump (first_time)
** Invoke environment
** Invoke db:load_config
** Execute db:schema:dump
```

Notice that the last database to connect is production, so let's check production

```
$ echo ".tables" | RAILS_ENV=production rails dbconsole
active_record_internal_metadatas  users
schema_migrations
```

Bingo. Now there's the question of what changed to cause this behavior? The reason that `db:create:all` doesn't work but `db:create` does is that it creates and establishes the `development` connection https://github.com/rails/rails/blob/cadb8af32dbb8877b096e7f69c401c34260dc902/activerecord/lib/active_record/tasks/database_tasks.rb#L126 so then `db:migrate` will use that connection.

We can fix this by explicitly connecting to the "current" database at the end of `create_all` method in the database tasks, but since we didn't need it before i'm hesitant to use it now.

Here's my guess: i'm thinking that previously AR wasn't "connected" to any database. The "create" action  used in the rake task doesn't use `ActiveRecord::Base.establish_connection` instead it uses https://github.com/rails/rails/blob/cadb8af32dbb8877b096e7f69c401c34260dc902/activerecord/lib/active_record/tasks/database_tasks.rb#L107-L116. So when `db:migrate` gets called it sees that it isn't connected to a DB, tries to connect, succeeds and then migrates the database.

My patch changed the behavior because now we have to `ActiveRecord::Base.establish_connection` to check for protected environments. Now when rake gets around to running `db:migrate` it sees a connection is alive so it uses that instead of creating a new one, it just so happens the last one it established to was "production" so that gets used instead of the one we currently want.

If i'm right about the cause, then it was basically working by accident before.

Any ideas @sgrif ?

**Comment by schneems** [comment] 2016-02-02 01:55
I've been thinking we should maybe explicitly do an `establish_connection` before the migration task.

**Comment by bquorning** [comment] 2016-02-11 21:39
Any progress on this issue? It’s blocking us from making a few (private) gems ready for Rails 5.

**Comment by schneems** [comment] 2016-02-16 20:50
ping @sgrif you assigned this to yourself, do you have an idea on a fix?

**Closed** 2016-02-23 16:15 UTC
Labels: activerecord

**Comment by Schwad** [comment] 2016-09-01 14:40
Our company is running into this same issue on our`gitlab-ci`, is the current fix part of Rails core for 5.0.0.1?

**Comment by ojab** [comment] 2016-09-01 14:47
This issue is fixed in 5.0.0 and doesn't affect any release version of rails.

**Comment by estiens** [comment] 2016-10-05 19:55
I get this behavior (or similar) with Rails 5.0.0.1

```
$ bin/rails db:environment:set RAILS_ENV=development
(works fine)
$ bin/rails db:drop
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

	bin/rails db:environment:set RAILS_ENV=development
```

**Comment by alexjspears** [comment] 2016-10-05 22:26
@estiens Same here popped up today

**Comment by itsterry** [comment] 2016-10-06 16:24
I had this problem on our CI setup, and fixed it with

> rake db:schema:dump

**Comment by schneems** [comment] 2016-10-06 16:29
Anyone have an example app with steps to repro the problem? I'm not exactly sure the underlying failure mode. That first command should populate the internal metadata table, and that should be all we need. I'm wondering if it's trying to drop a different database somehow.

**Comment by vgonda** [comment] 2016-10-18 16:49
I was able to reproduce the error:

- Created a new migration
- `rake db:migrate`
- `bin/rails db:environment:set RAILS_ENV=test`
- 👍
- `rake db:rollback`
- Changed migration
- `rake db:migrate`
- `bin/rails db:environment:set RAILS_ENV=test`
- 😞 Unable to update the testing environment with the migration change due to `ActiveRecord::NoEnvironmentInSchemaError`

This is with 5.0.0

**Comment by schneems** [comment] 2016-10-18 17:01
![Please provide an example app](https://www.dropbox.com/s/woa4h08jwuobzgp/example-apps.gif?dl=1)

**Comment by Schwad** [comment] 2016-11-02 17:46
@vgonda : do you have an example app of this?

**Comment by vgonda** [comment] 2016-11-02 17:55
I don't 😞  I was able to reproduce it in a private repo, but I haven't been able to reproduce since.

**Comment by Schwad** [comment] 2016-11-03 12:27
Dang, well maybe if we summon the @group we could get someone who has an
example app.... OR if someone is currently facing this issue and they come
here via googling around they should really share an example app! :D

**Comment by mvz** [comment] 2016-11-27 08:38
@Schwad I came here by googling. My problem may not be the same but seems related. And I have a super-simple reproduction:

```
git clone git@github.com:publify/publify_amazon_sidebar.git
cd publify_amazon_sidebar
bundle exec rake
```

I get the following output:

```
/home/matijs/.rbenv/versions/2.3.1/bin/ruby -I/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib:/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
rails aborted!
ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `development` environment.
You are running in `test` environment. If you are sure you want to continue, first set the environment using:

	bin/rails db:environment:set RAILS_ENV=test

bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

[snip rest of successful RSpec run output]
```

**Comment by rquant** [comment] 2016-11-28 18:13
I strangely got this error when checking out a pre Rails 5 commit in our repo, loading schema from that commit and then going back to HEAD commit with Rails 5. 
```
Ryans-MacBook-Pro:matic-home ryanquant$ bin/rails db:reset
I, [2016-11-28T08:55:41.209693 #15269]  INFO -- : Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

        bin/rails db:environment:set RAILS_ENV=development
```

Any db rake/rails command I tried to run would cause the error to be thrown (even if i ran the environment setup command recommended in the error). 

Strangely when I ran `bin/rails db:migrate` the normal behavior resumed and it the errors were no more.

**Comment by Schwad** [comment] 2016-11-29 10:32
Interesting. What do you make of this @schneems ?

**Comment by ojab** [comment] 2016-11-29 10:53
`app:update` task (that should be run after upgrade, according to the [guide](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#the-update-task)) deals with it.
AFAIU it is intended behavior.

**Comment by tfluehmann** [comment] 2016-11-29 15:00
I am having the same issue with a bamboo and an instance of my rails 5.0.0.1 app. I already tried app:update, doesn't work.

**Comment by ojab** [comment] 2016-11-30 09:33
@tfluehmann …and you haven't provided steps to reproduce an issue.

**Comment by tfluehmann** [comment] 2016-11-30 10:21
@ojab sorry for that, I fixed it now by running rails db:environment:set RAILS_ENV=test before each command.
My flow looks now like that: 
rails db:environment:set RAILS_ENV=test
rails db:drop RAILS_ENV=test
rails db:environment:set RAILS_ENV=test
rails db:create RAILS_ENV=test

instead of simply:
rails db:drop RAILS_ENV=test
rails db:create RAILS_ENV=test

cheers

**Comment by mvz** [comment] 2016-12-02 13:42
@Schwad I solved my previous reproduction by removing the pending migrations check from `rails_helper.rb`. However, I have another reproduction that cannot be solved this way:

```
git clone git@github.com:publify/publify_core.git
cd publify_core
git checkout raah2
sh foo.sh
```

The file `foo.sh` contains:

```bash
bundle exec rake db:migrate RAILS_ENV=test
RAILS_ENV=test bundle exec rake spec # succes
bundle exec rake # succes
RAILS_ENV=test bundle exec rake spec # failure
``

So the result of the above steps is that the specs are 'run' three times. I added a `raise` at the top of `rails_helper.rb` to make the spec abort if it makes it past the actual problem, which manifests itself int the third run, where it outputs:

```
rake aborted!
ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `development` environment.
You are running in `test` environment. If you are sure you want to continue, first set the environment using:

	bin/rails db:environment:set RAILS_ENV=test

/home/matijs/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/matijs/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => app:db:test:load => app:db:test:purge => app:db:check_protected_environments
(See full trace by running task with --trace)
```

I hope this helps getting to the root of the problem. I'm happy to open a new ticket if you feel this is a different problem.

**Comment by andrewyoo** [comment] 2016-12-14 16:50
I found a solution for myself.  Here we go:

I was encountering ````ActiveRecord::NoEnvironmentInSchemaError```` and started inspecting my databases.

The key difference I found was my ar_internal_metadata had the column ````key```` set as integer on DBs having issues and DBs not having issues ````key```` was set to ````varchar```` and had a value of ````environment````

Also my schema which was loading was doing this:

```ruby
create_table "ar_internal_metadata", primary_key: "key", force: :cascade do |t|
  t.string   "value"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
end
```

The schema should be like:
```ruby
create_table "ar_internal_metadata", primary_key: "key", id: :string, force: :cascade do |t|
  t.string   "value"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
end
```

Now everything works. Hope this helps others.

**Comment by micahlisonbee** [comment] 2017-01-14 14:15
@andrewyoo that schema difference was the cause of my issue as well. I deleted that table manually and re-ran `rails db:migrate` and it resolved itself. Sounds like this issue might need to re-open?

**Comment by ojab** [comment] 2017-01-14 14:34
It will be helpful if someone will write how you've got wrong column type in schema.

**Comment by micahlisonbee** [comment] 2017-01-14 14:42
@ojab Not sure. I had been switching between Rails 4.2 and 5.0 branches as we are upgrading to 5.0...

**Comment by estiens** [comment] 2017-01-24 17:02
@micahlisonbee @ojab I was also regularly switching between Rails 4.2 and Rails 5 branches as I was working on an upgrade when I encountered this issue -- thanks for sleuthing @andrewyoo !

**Comment by JasonBarnabe** [comment] 2017-04-24 19:59
Just to add another potential cause of `ActiveRecord::NoEnvironmentInSchemaError`... I got this running `rake test` which executes rspec and cucumber tests (though running each separately did not show the problem). Upgrading cucumber-rails to 1.4.5 and running `rails generate cucumber:install` fixed it.
