### ISSUE TITLE
ActiveRecord Encryption unable to save with default JSONb column in PostgreSql

### ISSUE THREAD

**Issue by codenamev** [rails/rails#43664] opened 2021-11-17 14:15 UTC
### Steps to reproduce
I wasn't able to get a working test file, so I made [a small Rails app showcasing the underlying issue](https://github.com/codenamev/testy).

```bash
gh clone codenamev/testy
cd testy
bin/rails db:setup
bin/rails db:migrate
bin/rails test test/models/author_test.rb
```

### Expected behavior
I would expect a model with an encrypted JSONb PostgreSQL column that has a default value to save without providing a value.

### Actual behavior
Upon saving the above mentioned JSONb column with a default, a `ActiveRecord::Encryption::Errors::Decryption` error is raised.

### System configuration
**Rails version**: `7.0.0.alpha2`

**Ruby version**: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]`

**Comment by jacobherrington** [comment] 2021-11-20 08:14
Hey Valentino, this is definitely behaving a bit odd.

In fact, `jsonb` columns aren't the only columns that behave unexpectedly.

I'll drop a working reproduction script at the bottom of this comment too!

What I'm seeing is a couple of failures that get swallowed up in the `Encryptor#decrypt` method (see line 57):
https://github.com/rails/rails/blob/f47204802ae2e212a238276492584b7607c513f1/activerecord/lib/active_record/encryption/encryptor.rb#L52-L59

Specifically, your `jsonb` example is actually raising `ActiveRecord::Encryption::Errors::EncryptedContentIntegrity` from `Cipher#decrypt` (line 64):
https://github.com/rails/rails/blob/f47204802ae2e212a238276492584b7607c513f1/activerecord/lib/active_record/encryption/cipher/aes256_gcm.rb#L56-L64

I'm not sure exactly why this is happening, but I think a bit more investigation might make it clear. For some reason, `encrypted_message.headers.auth_tag` evaluates to `nil` in this case.

As for the `text` example I've included in my script, we're actually raising `ActiveRecord::Encryption::Errors::Encoding` from inside `MessageSerializer#load`:
https://github.com/rails/rails/blob/f47204802ae2e212a238276492584b7607c513f1/activerecord/lib/active_record/encryption/message_serializer.rb#L22-L27

That's a little more straightforward (I think). In this case, we end up passing a blank string to `JSON#parse`, which raises a `JSON::ParseError`.

It strikes me that we could choose to skip encryption for both empty hashes and strings, but I'm not sure that's the ideal behavior.

I also think it might be the case that this **is** the intended behavior, I didn't see anything like that documented, but I may have certainly missed it.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"
require "date"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "jsonb_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Encryption.configure \
      primary_key: "nYlllafgBdhQ7Vn37dlWAoqfDbTPl4Fl",
      deterministic_key: "CK7x2oUEeu06bKehhKGiKYAHoytPaOPg",
      key_derivation_salt: "Fol1dR03ZXnL8k4hEUYj7IMr0UlgOMHC"


ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.jsonb :metadata, null: false, default: {}
  end

  create_table :books, force: true do |t|
    t.jsonb :publisher_info, null: false, default: {}
  end

  create_table :fruits, force: true do |t|
    t.text :name, null: false, default: ''
  end

  create_table :cats, force: true do |t|
    t.date :name, null: false, default: Date.new(1965, 8, 3)
  end
end

class Post < ActiveRecord::Base
  encrypts :metadata
end

class Book < ActiveRecord::Base; end

class Fruit < ActiveRecord::Base
  encrypts :name
end

class Cat < ActiveRecord::Base
  encrypts :dob
end

class BugTest < Minitest::Test
  # Unecrypted case -- behaves as expected.
  def test_unencrypted_jsonb_with_default_value
    book = Book.new
    assert book.valid? # Pass
    assert book.save # Pass
    assert_equal({}, book.reload.publisher_info) # Pass
  end

  # Encrypted cases -- these feel more confusing.
  def test_encrypted_jsonb_with_default_value
    post = Post.new
    assert post.valid? # Pass
    assert post.save # Raises ActiveRecord::Encryption::Errors::Decryptions
                     # by way of ActiveRecord::Encryption::Errors::Encoding
    assert_equal({}, post.reload.metadata) # Fails because the record doesn't save
  end

  def test_encrypted_string_with_default_value
    fruit = Fruit.new
    assert fruit.valid? # Pass
    assert fruit.save # Raises ActiveRecord::Encryption::Errors::Decryption
                      # by way of ActiveRecord::Encryption::Errors::EncryptedContentIntegrity
    assert_equal('', fruit.reload.name) # Fails because the record doesn't save
  end

  def test_encrypted_date_with_default_value
    cat = Cat.new
    assert cat.valid? # Pass
    assert cat.save # Pass
    assert_equal(Date.new(1965, 8, 3), cat.reload.name) # Pass
  end
end
```

**Comment by vy0b0x** [comment] 2022-01-05 15:46
set config.active_record.encryption.support_unencrypted_data to true will fix this issue.

**Comment by DalenW** [comment] 2022-01-08 04:09
Had the same issue with a blank default set. Maybe skip encryption if the column value is blank? Probably a bad idea. Why does ActiveRecord attempt to decrypt the column if I'm replacing it with something else?

**Comment by devon** [comment] 2022-01-17 05:27
There is a similar problem: https://github.com/heartcombo/devise/issues/5436

When using [devise](https://github.com/heartcombo/devise) to set up the user table, the default email address is empty, not nil,

It cannot create a user when the setup user email is encrypted:

```
class User < ApplicationRecord
  encrypts :email, deterministic: true, downcase: true
end

User.create(email: 'jack@example.com',  password: 'password', password_confirmation: 'password')
```

The error messages:

```
/Users/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activerecord-7.0.1/lib/active_record/encryption/encryptor.rb:63:in `rescue in decrypt': ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption)
/Users/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activerecord-7.0.1/lib/active_record/encryption/message_serializer.rb:26:in `rescue in load': ActiveRecord::Encryption::Errors::Encoding (ActiveRecord::Encryption::Errors::Encoding)
/Users/jack/.rbenv/versions/3.1.0/lib/ruby/3.1.0/json/common.rb:216:in `parse': 859: unexpected token at '' (JSON::ParserError)
```

In active record 7.0.1, encrypted_attribute_type.rb, the code detect nil? value, not blank? value:

```
def decrypt(value)
  with_context do
    encryptor.decrypt(value, **decryption_options) unless value.nil?
  end
  ...
end
```

**Comment by axelmukwena** [comment] 2022-03-09 19:19
I am experiencing the same as @devon too.  Have you found a workaround?

**Comment by jorgemanrubia** [comment] 2022-05-11 08:11
This should have been fixed in https://github.com/rails/rails/pull/45033.

**Closed by jorgemanrubia** 2022-05-11 08:11 UTC
Labels: activerecord
