### ISSUE TITLE
Rails 5.1: bigint column recognized as integer with limit 4 bytes

### ISSUE THREAD

**Issue by jonhue** [rails/rails#28575] opened 2017-03-26 08:52 UTC
### Expected behavior
Using `rails 5.1.0.rc1` and `mysql2`, migrations *should* use `BIGINT` as primary key integers by default. -> #26266 

### Actual behavior
I cannot set a `BIGINT` as id.

### Steps to reproduce

*db/migrate/20170311112129_create_receipts.rb*

    class CreateReceipts < ActiveRecord::Migration[5.1]
      def change
        create_table :receipts do |t|
    
          t.timestamps null: false
        end
      end
    end

Trying to set a `BIGINT` like `773187872333227144` as `id` ...

```ruby
Receipt.create(id: 773187872333227144)
```

... raises the following exception:

> ActiveModel::RangeError: 773187872333227144 is out of range for ActiveModel::Type::Integer with limit 4 bytes

Still, MySQL recognizes the `BIGINT`:

```
mysql> USE my_app_development
Database changed
mysql> describe receipts;
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| created_at | datetime     | NO   |     | NULL    |                |
| updated_at | datetime     | NO   |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
3 rows in set (0.00 sec)
```

### System configuration
**Rails version**: 5.1.0.rc1

**Ruby version**: 2.3.3

_related to #28386_

**Comment by vipulnsward** [comment] 2017-03-26 14:55
Hi @jonhue what does output from https://gist.github.com/vipulnsward/de107851b4c0db07571a324dee64df3e 
look like for you, when using 5.1.0.rc1 ?

It is still [passing](https://gist.github.com/vipulnsward/de107851b4c0db07571a324dee64df3e#gistcomment-2038032) for me with this new value you have given

**Comment by jonhue** [comment] 2017-03-26 15:20
I answered on the Gist you provided. Weird is that with a new test app, I also cannot reproduce the issue. In my app (originally rails 4.2.8), I encounter this problem with every migration ever created and all new migrations I am creating.

**Comment by rafaelfranca** [comment] 2017-03-27 21:11
I believe you have some gem or monkey patch that changes this behavior. Closing since we can't reproduce in a new application.

**Closed by rafaelfranca** 2017-03-27 21:11 UTC
Labels: activerecord, needs work

**Comment by jonhue** [comment] 2017-03-28 05:17
@rafaelfranca How would you change that behaviour? In the app configuration?

**Comment by kamipo** [comment] 2017-03-28 09:04
We don't know that you have some gem or monkey patch.

If you couldn't find the cause that changes this behavior, you can use `activerecord-suppress_range_error` as a workaround.
https://rubygems.org/gems/activerecord-suppress_range_error

**Comment by jonhue** [comment] 2017-03-28 16:42
Seems like the problem fixed itself somehow.
