### ISSUE TITLE
Chained soped inside OR are not grouped together

### ISSUE THREAD

**Issue by AlexVPopov** [rails/rails#39031] opened 2020-04-24 08:39 UTC
### Steps to reproduce
Given an ActiveRecord model with `start_date`, `end_date` and these scopes:

```ruby
scope :started, -> { where('start_date < :date', date: Time.zone.today) }
scope :without_end_date, -> { where(end_date: nil) }
scope :ended, -> { where('end_date < :date', date: Time.zone.today) }
```

### Expected behavior
I expect `Model.ended.or(started.without_end_date)` to produce:

```ruby
WHERE ((end_date < '2020-04-24') OR (end_date IS NULL AND start_date < '2020-04-24'))
```

### Actual behavior
Instead, the above expression produces:

```ruby
WHERE ((end_date < '2020-04-24') OR (start_date < '2020-04-24') AND "community_events"."end_date" IS NULL)
```

Is this an expected behavior or bug? 

This works:
```ruby
ended.or(where('end_date IS NULL AND start_date < :date', date: Time.zone.today))
```
but I'd like to reuse the already existing scopes.

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.5

**Comment by kamipo** [comment] 2020-04-24 09:03
Can you provide a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by yoelblum** [comment] 2020-04-24 11:52
`# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.date :start_date
    t.date :end_date
  end

end

class Post < ActiveRecord::Base
  scope :started, -> { where('start_date < :date', date: Date.today) }
  scope :without_end_date, -> { where(end_date: nil) }
  scope :ended, -> { where('end_date < :date', date: Date.today) }
end


class BugTest < Minitest::Test
  def test_association_stuff
    only_end_date = Post.create!(end_date: 2.days.ago)
    started_without_end = Post.create!(start_date: 2.days.ago, end_date: nil)
    posts = Post.ended.or(Post.started.without_end_date) 
    assert posts.count == 2
  end
end`

**Comment by yoelblum** [comment] 2020-04-24 11:53
`# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.date :start_date
    t.date :end_date
  end

end

class Post < ActiveRecord::Base
  scope :started, -> { where('start_date < :date', date: Date.today) }
  scope :without_end_date, -> { where(end_date: nil) }
  scope :ended, -> { where('end_date < :date', date: Date.today) }
end


class BugTest < Minitest::Test
  def test_association_stuff
    only_end_date = Post.create!(end_date: 2.days.ago)
    started_without_end = Post.create!(start_date: 2.days.ago, end_date: nil)
    posts = Post.ended.or(Post.started.without_end_date) 
    assert posts.count == 2
  end
end`

**Comment by yoelblum** [comment] 2020-04-24 11:56
https://gist.github.com/yoelblum/33cc97dafc4ef42c7199249ef67b5a98 . This is the SQL that was being output to log:
 `SELECT COUNT(*) FROM "posts" WHERE ((end_date < '2020-04-24') OR (start_date < '2020-04-24') AND "posts"."end_date" IS NULL)`
My observation is that it does return the correct records, although the paranthesis should maybe cover the entire OR expression?

**Comment by kamipo** [comment] 2020-04-24 12:18
Yes, the paranthesis should cover the entire OR expression.

```ruby
relation = Model.cond_a.or(Model.cond_b)
# (A OR B)

relation = relation.cond_c
# (A OR B) AND C
```

I'm closing this since this is not an issue.

**Closed by kamipo** 2020-04-24 12:18 UTC
