### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 1

### ISSUE THREAD

**Issue by dnasseri** [rails/rails#25995] opened 2016-07-30 04:34 UTC
On the latest version of master, I noticed that using `ActiveRecord::Base.connection.exec_query` throws the `ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 1` when prepared statements are disabled. I actually noticed this issue when trying to upgrade from rails 3.2.22 to version 4.2, but AFAIK the bug still exists on master.

### Steps to reproduce

Here is a test which reproduces the issue: 

```
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', github: 'rails/rails'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(
  adapter: 'postgresql',
  port: 5432,
  prepared_statements: false
)

ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Schema.define do
  create_table :people, temporary: true do |t|
    t.string :name
  end
end

class Person < ActiveRecord::Base; end

class BugTest < Minitest::Test

  def test_error
    person = Person.new
    person.name = 'FooBar'
    person.save!
    rows = ActiveRecord::Base.connection.exec_query(
      'SELECT name FROM people WHERE id = $1',
      'sql',
      [person.id]
    ).rows
  end

end
```

When running this test I get

```
ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 1
: SELECT name FROM people WHERE id = $1
    /Users/DN/.rvm/gems/ruby-2.2.4/bundler/gems/rails-815b730b1b79/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `async_exec'
    /Users/DN/.rvm/gems/ruby-2.2.4/bundler/gems/rails-815b730b1b79/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `block in exec_no_cache'
    /Users/DN/.rvm/gems/ruby-2.2.4/bundler/gems/rails-815b730b1b79/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
    /Users/DN/.rvm/gems/ruby-2.2.4/bundler/gems/rails-815b730b1b79/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /Users/DN/.rvm/gems/ruby-2.2.4/bundler/gems/rails-815b730b1b79/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
    /Users/DN/.rvm/gems/ruby-2.2.4/bundler/gems/rails-815b730b1b79/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_no_cache'
    /Users/DN/.rvm/gems/ruby-2.2.4/bundler/gems/rails-815b730b1b79/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:588:in `execute_and_clear'
    /Users/DN/.rvm/gems/ruby-2.2.4/bundler/gems/rails-815b730b1b79/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
    test.rb:34:in `test_error'
```

### Expected behavior (3.2.22)

On earlier versions of rails (3.2.22 specifically), the exec_query method generates and executes the correct query. Here is a test case to confirm:

```
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '3.2.22'
  gem 'minitest'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(
  adapter: 'postgresql',
  database: 'postgres',
  prepared_statements: false
)

#ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Schema.define do
  create_table :people, temporary: true do |t|
    t.string :name
  end
end

class Person < ActiveRecord::Base; end

class BugTest < Minitest::Test

  def test_no_error
    person = Person.new
    person.name = 'FooBar'
    person.save!
    rows = ActiveRecord::Base.connection.exec_query(
      'SELECT name FROM people WHERE id = $1',
      'sql',
      [person.id]
    ).rows
  end

end
```

This test does not error.

### Actual behavior (master)

The test fails with `ActiveRecord::StatementInvalid: PG::ProtocolViolation`. 

### System configuration

**Rails version**: master

**Ruby version**: 2.2.4

**Comment by kalrover** [comment] 2016-07-30 07:58
Duplicate of #24893

`binds` was not passed caused error
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L586-L589
```ruby
         if without_prepared_statement?(binds)
            result = exec_no_cache(sql, name, [])
          elsif !prepare
```

**Comment by dnasseri** [comment] 2016-07-30 13:11
@kalrover @sgrif I tried this on 5.0.0rc1 as suggested here: https://github.com/rails/rails/issues/24893.

I believe the issue is still present. The test case still errors:

```
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '5.0.0.rc1'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(
  adapter: 'postgresql',
  port: 5432,
  prepared_statements: false
)

ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Schema.define do
  create_table :people, temporary: true do |t|
    t.string :name
  end
end

class Person < ActiveRecord::Base; end

class BugTest < Minitest::Test

  def test_error
    person = Person.new
    person.name = 'FooBar'
    person.save!
    rows = ActiveRecord::Base.connection.exec_query(
      'SELECT name FROM people WHERE id = $1',
      'sql',
      [person.id]
    )
    assert rows.length = 1
  end

end
```

**Comment by kalrover** [comment] 2016-07-30 18:43
@dnasseri 
To pass the above test on `5.0.0.rc1` you might delete ` prepared_statements: false` or set it to `true`.
when call `exec_query` function, you might consider this code
```ruby
rows = ActiveRecord::Base.connection.exec_query(
      'SELECT name FROM people WHERE id = $1',
      'sql',
      [ActiveRecord::Relation::QueryAttribute.new(nil, person.id, ActiveRecord::Type::Value.new)]
    )
```

**Comment by dnasseri** [comment] 2016-07-30 20:04
@kalrover Thanks so much for getting back to me.

Indeed, I believe enabling prepared statements does solve this issue. However when upgrading our application from 3.2.22 to 4.2 we saw significant memory issues, and had to disable them (see https://github.com/rails/rails/issues/14645). Unfortunately the fix you suggested:
```
rows = ActiveRecord::Base.connection.exec_query(
      'SELECT name FROM people WHERE id = $1',
      'sql',
      [ActiveRecord::Relation::QueryAttribute.new(nil, person.id, ActiveRecord::Type::Value.new)]
    )
```
Does not seem to resolve the issue when prepared statements are disabled.

**Comment by maclover7** [comment] 2016-07-30 21:41
Thank you for opening up this issue! I'm going to close as a duplicate of #24893, so we can keep all of this information in the same place.

**Closed by maclover7** 2016-07-30 21:41 UTC
