### ISSUE TITLE
Polymorphic type is wrong when doing an association creation

### ISSUE THREAD

**Issue by tenderlove** [rails/rails#20893] opened 2015-07-16 00:36 UTC
```ruby
require 'active_record'
require 'minitest/autorun'

ActiveRecord::Base.establish_connection adapter: 'sqlite3', database: ':memory:'

ActiveRecord::Base.connection.instance_eval do
  create_table(:addresses) do |t|
    t.string :name
    t.integer :addressable_id
    t.string :addressable_type
  end

  create_table(:people) do |t|
    t.string :name
    t.string :type
  end
end

class Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
end

class Person < ActiveRecord::Base
  has_many :addresses, as: :addressable
end

class Vendor < Person
end

class MyTest < Minitest::Test
  def test_ugh
    vendor = Vendor.create(name: 'hello')
    address = vendor.addresses.create(name: 'blah')

    assert_equal Vendor.name, address.addressable_type
  end
end
```

Output:

```
[aaron@TC rails (master)]$ bundle exec ruby test.rb 
Run options: --seed 36919

# Running:

F

Finished in 0.075672s, 13.2149 runs/s, 13.2149 assertions/s.

  1) Failure:
MyTest#test_ugh [test.rb:35]:
Expected: "Vendor"
  Actual: "Person"

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by matthewd** [comment] 2015-07-16 00:41
Isn't this expected behaviour? `addressable_type` is responsible for telling us which table to look in (i.e., the root of the STI tree), not the particular class of the record, isn't it?

Otherwise, what if `type` gets changed?

**Comment by tenderlove** [comment] 2015-07-16 00:48
That is a very good point.  I only filed this bug because apparently there is a gem whose sole purpose is to work around this issue. /cc @zenspider

**Comment by sgrif** [comment] 2015-07-18 13:12
Honestly, neither the current nor asserted behavior in this issue make sense to me. We have no reasonable value to assume for `addressable_type` here. I would expect this to raise an `ArgumentError`, not default to the type of the parent class.

**Comment by al2o3cr** [comment] 2015-07-19 22:48
@sgrif - What do you mean by "no reasonable value to assume for `addressable_type`"? Since the object was built off a `Vendor`, it seems reasonable to have a value based on that.

This particular issue seems to pop up once every year or so; I definitely recall discussion about it on the old Lighthouse. @matthewd has already pointed out the primary issue with the suggested behavior (denormalizing `type`).

For reference, if you're REALLY bored, here's a Greatest Hits version of many of the times this has come up before:
On Github:
* https://github.com/rails/rails/issues/16743
* https://github.com/rails/rails/issues/13653
* https://github.com/rails/rails/issues/7674
* https://github.com/rails/rails/issues/5441
* https://github.com/rails/rails/issues/4729
* https://github.com/rails/rails/issues/888

On Lighthouse:
* https://rails.lighthouseapp.com/projects/8994/tickets/5617-patch-sti-join-model-polymorphic-associations-works-now (where the `store_base_sti_class_for_3_0` was announced)
* https://rails.lighthouseapp.com/projects/8994/tickets/547-polymorphic-associations-sti-don-t-record-the-correct-model-type
* https://rails.lighthouseapp.com/projects/8994/tickets/2594-bug-with-polymorphic-has_one-as-pointing-to-sti-record
* https://rails.lighthouseapp.com/projects/8994/tickets/2435-polymorphic-has_one-and-has_many-should-set-proper-polymorphic_type-in-case-of-sti-patch-ported-to-rails-23
* https://rails.lighthouseapp.com/projects/8994/tickets/2601-single-table-inheritance-self-referential-polymorphic-association-bug

**Comment by tedtoer** [comment] 2015-07-21 06:42
I created separate entity (Vendor inheriting from Person) and exactly the self-class name of this entity must be in *_type column of polymorphic table.

Here is PR for this: https://github.com/rails/rails/pull/20963

**Comment by al2o3cr** [comment] 2015-07-24 16:06
FWIW, @tedtoer - that patch is nearly identical to the one from [this ticket in 2008](https://rails.lighthouseapp.com/projects/8994/tickets/547-polymorphic-associations-sti-don-t-record-the-correct-model-type) that was closed as `wontfix`.

**Closed** 2015-10-14 23:35 UTC
Labels: activerecord, With reproduction steps
