### ISSUE TITLE
Raising an ActiveRecord::RecordInvalid inside a callback does not roll back transaction

### ISSUE THREAD

**Issue by djshitcoin** [rails/rails#33924] opened 2018-09-20 02:17 UTC
### Steps to reproduce

```ruby
class Thing < ApplicationRecord
  after_save do
    something.reload.validate! # validation fails!!!
  end
end

class ThingsController < ApplicationController
  def create
    Thing.transaction do
       Thing.create!
    end
  end
end
```

### Expected behavior
Transaction is rolled back. Thing is not saved.

### Actual behavior
Transaction is not rolled back, Thing is saved.

### System configuration
**Rails version**:
5.2

**Ruby version**:
2.5.1

**Comment by y-yagi** [comment] 2018-09-21 00:18
I couldn't reproduce your issue. 

```ruby 
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :things, force: true do |t|
  end
end

class Thing < ActiveRecord::Base
  after_save do
    raise ActiveRecord::RecordInvalid
  end
end

class BugTest < Minitest::Test
  def test_bug
    begin
      Thing.transaction do
        Thing.create!
      end
    rescue ActiveRecord::RecordInvalid
    end

    assert_empty Thing.all
  end
end
``` 

```
$ ruby 33924.rb
.

Finished in 0.004745s, 210.7572 runs/s, 421.5143 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips 
``` 

Can you create a reproduce script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb)

**Comment by djshitcoin** [comment] 2018-09-21 04:18
Hi, thank you so much for looking in to this.

Sorry, I'm confused right now, because I could have sworn I ran into this problem in production, but now it seems to work.

When I substitute the raised exception with `ActiveRecord::Rollback`, the test case fails. According to the documentation [here](https://guides.rubyonrails.org/active_record_callbacks.html#halting-execution), the test case should also fail when raising `ActiveRecord::RecordInvalid` instead of `ActiveRecord::Rollback`. Maybe the documentation is wrong.

In your test case above, I am very confused why ActiveRecord::RecordInvalid is not being rescued by the filter-chain and needs to be handled in the `test_bug` method. 

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :things, force: true do |t|
  end
end

class Thing < ActiveRecord::Base
  after_save do
    raise ActiveRecord::Rollback
  end
end

class BugTest < Minitest::Test
  def test_bug
    Thing.transaction do
      Thing.create!
    end

    assert_empty Thing.all
  end
end
```
```
Finished in 0.004820s, 207.4689 runs/s, 414.9378 assertions/s.

  1) Failure:
BugTest#test_bug [test.rb:43]:
Expected #<ActiveRecord::Relation [#<Thing id: 1>]> to be empty.

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by y-yagi** [comment] 2018-09-21 06:36
Since `save` and `update_attributes` are rescue `ActiveRecord::RecordInvalid`, `ActiveRecord::RecordInvalid::` is never re-raise, so it is such an explanation.
https://github.com/rails/rails/blob/87a36ca66507cfcc68df817b6dbd69c036fa3dc4/activerecord/lib/active_record/persistence.rb#L278-L282 
Related to: https://github.com/rails/rails/pull/23117 

However, it is certainly not easy to understand because behavior varies depending on the method. 
Improvement of doc is welcome :)

Anyway, the original issue does not seem to be reproduced, so I close this. If you can create a reproduction procedure please freely reopen it. Thanks.

**Closed by y-yagi** 2018-09-21 06:36 UTC
