### ISSUE TITLE
Rails 4.2.0 and 4.2.4 break all the routes under subfolder

### ISSUE THREAD

**Issue by poc7667** [rails/rails#22070] opened 2015-10-26 08:49 UTC
I'm using Rails 4.2.4

And deploy the server under subdirectory by nginx by `location /my_rails_root/`

The root url works fine, I can access my Rails site  by `http://sample.com/my_rails_root/`

However, all the generated routes don't have the  `/my_rails_root/` in its prefix, therefore all the route are failed in my rails app.

The expected product url should be `http://sample.com/my_rails_root/product/12` but I get `http://sample.com/product/12`

#ENV

> RAILS_RELATIVE_URL_ROOT='/my_rails_root'

# routes.rb 

        Rails.application.routes.draw do
          browse_draw = Proc.new do
            ~~~~
          end
          if ENV['RAILS_RELATIVE_URL_ROOT']
            scope ENV['RAILS_RELATIVE_URL_ROOT'] do
              browse_draw.call
            end
          else
            browse_draw.call
          end
        end


# application.rb

    config.relative_url_root = ENV['RAILS_RELATIVE_URL_ROOT']


#nginx

       location /my_rails_root/ {
            rewrite ^/my_rails_root/(.*)$ /$1 break;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header   Host $http_host;
            proxy_pass http://127.0.0.1:8591;
        }

**Comment by arunagw** [comment] 2015-10-27 10:20
I think it's also same as https://github.com/rails/rails/issues/22074

**Comment by mikhailov** [comment] 2015-10-28 11:28
To make Rails app accessible via URI Nginx has a trick called trailing slash that works as you expect for:

```
   location /my_rails_root/ {
        rewrite ^/my_rails_root/(.*)$ /$1 break;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   Host $http_host;
        proxy_pass http://127.0.0.1:8591/;
    }
```

One more thing to do is static content needs a prefix now:

```
config.assets.prefix = "/my_rails_root/assets"
```

However you need an Nginx up and running in development as your redirect_to needs to happen against new URI (/my_rails_root/). Do you have any other ideas?

**Comment by maclover7** [comment] 2016-01-10 18:48
Closing, is a duplicate of #22074.

**Closed by maclover7** 2016-01-10 18:48 UTC
Labels: actionpack, routing
