### ISSUE TITLE
Timezone problem persisting time with ActiveRecord

### ISSUE THREAD

**Issue by pierrickrouxel** [rails/rails#18516] opened 2015-01-14 17:05 UTC
Hi,

I think there is a problem with the time persistence in ActiveRecord.

With: 

```ruby
    config.time_zone = 'Paris'
    config.active_record.default_timezone = :local
```

When I try to persist '2000-01-01T00:00:00.000Z' it is stored in database as 00:00:00 but it should be 01:00:00 because my local timezone is GMT +1.

So when I reload my model the time is 23:00:00.

Can you help my to understand if it's normal?

Thanks.

**Comment by rafaelfranca** [comment] 2015-01-14 17:05
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by pierrickrouxel** [comment] 2015-01-14 19:16
I think this is an issue.

**Comment by rafaelfranca** [comment] 2015-01-14 19:20
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by sgrif** [comment] 2015-01-14 20:22
`"Paris"` is not a valid time zone, causing it to default to UTC. Rails uses the `tzinfo` gem to get time zone information. The correct time zone is `"CET"`

```
[master][~/builds/rails/activerecord] TZ="Paris" irb
irb(main):001:0> ENV["TZ"]
=> "Paris"
irb(main):002:0> Time.now.getlocal
=> 2015-01-14 20:19:17 +0000
irb(main):003:0>
[master][~/builds/rails/activerecord] TZ="CET" irb
irb(main):001:0> ENV["TZ"]
=> "CET"
irb(main):002:0> Time.now.getlocal
=> 2015-01-14 21:20:18 +0100
```

**Comment by sgrif** [comment] 2015-01-14 20:47
Whoops, appears we do actually map `"Paris"` to a time zone in AS

**Comment by pierrickrouxel** [comment] 2015-01-15 10:05
You can find the test here:
https://gist.github.com/a2aff5f16998babe843c.git

Timezone is totally ignored.

**Comment by sgrif** [comment] 2015-01-15 14:43
This is a duplicate of #3145, fixed by #15726.

**Closed by sgrif** 2015-01-15 14:43 UTC
Labels: activerecord, needs feedback

**Comment by pierrickrouxel** [comment] 2015-01-15 15:44
I ran my test with your commit the bug is still present.

**Comment by sgrif** [comment] 2015-01-15 15:50
We cannot change the behavior of time columns without a deprecation cycle. As stated in the deprecation warning, you can add `:time` to the time zone aware attribute types manually in your config. In the test, you should do:

```ruby
ActiveRecord::Base.time_zone_aware_attributes = true
ActiveRecord::Base.time_zone_aware_types << :time
```
