### ISSUE TITLE
Get optionals parameters of Rails routing file.

### ISSUE THREAD

**Issue by bartozz** [rails/rails#35877] opened 2019-04-05 14:37 UTC
# I've the following routes in routes.rb
# How get the optional parameters in the EventsController.?
# In Django is the following
# def events(city = None, type_event = None)
# if city and type_event == None:

Rails.application.routes.draw do 
  resources :events do 
    get "/" => "events#index"
    get "/(:city)/(:type_event)" => "events#index"
  end 
end

**Comment by gadikotamohan** [comment] 2019-04-05 19:37
@bartozz  duplicate of https://github.com/rails/rails/issues/35879

**Closed** 2019-04-05 23:04 UTC
