### ISSUE TITLE
Psych not parsing new installion of Rails database.yml correctly

### ISSUE THREAD

**Issue by vinnyFD** [rails/rails#47404] opened 2023-02-15 16:23 UTC
### Steps to reproduce
cd /tmp 
rails new test_project 
rails console 
Psych.load(File.read('/tmp/test_project/config/database.yml'))

Gives:
/Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: default (Psych::BadAlias)

https://github.com/anarcat/pwstore/commit/8597febca89739c0108cadeee56c160d20651e36 and https://github.com/anarcat/pwstore/commit/8597febca89739c0108cadeee56c160d20651e36 seems like related issues

### Expected behavior
For the database.yml file to be parsed by Psych correctly

### Actual behavior
 Unknown alias: default (Psych::BadAlias)

### System configuration
**Rails version**:
Rails 7.0.4.2 

**Ruby version**:
 ruby 3.1.2p20

**Comment by skipkayhil** [comment] 2023-02-15 23:32
Hey @vinnyFD, thanks for opening an issue!

The way Rails loads `config/database.yml` is through [`Rails.configuration.database_configuration`](https://api.rubyonrails.org/classes/Rails/Application/Configuration.html#method-i-database_configuration), which internally uses [`ActiveSupport::ConfigurationFile`](https://api.rubyonrails.org/classes/ActiveSupport/ConfigurationFile.html). In that class, the file is loaded using `Psych.unsafe_load` (because the database file is trusted and not user controlled), which allows the aliases to be processed correctly.

If you want to load the configuration yourself I would recommend using the `database_configuration` method I mention above. 

I think `Psych.load` is behaving as expected here, so I'm going to close this since its not a bug in Rails. Feel free to reply if you believe I missed something!

**Closed by skipkayhil** 2023-02-15 23:32 UTC
