### ISSUE TITLE
Rails 5.0.0.beta1 compile error hiredis 0.5.2 on windows

### ISSUE THREAD

**Issue by marcomd** [rails/rails#22914] opened 2016-01-04 16:58 UTC
Hello,

this is my first issue on rails 5 and I would like to begin by thanking all the contributors :+1: 

my system: windows ruby 2.2.3 x64

Installing rails i had some troubles with hiredis 0.5.2 which can't be compiled on my system. Version 0.6.1 can be compiled so i forced dependencies from:

    actioncable 5.0.0.beta1 > em-hiredis ~> 0.3.0 > hiredis ~> 0.5.0

to:

    actioncable 5.0.0.beta1 > em-hiredis ~> 0.3.0 > hiredis ~> 0.6.0

This works but I wonder if there are downsides

**Comment by jcoyne** [comment] 2016-01-04 19:00
Is this a duplicate of #22725?

**Comment by rafaelfranca** [comment] 2016-01-04 19:05
Yes

**Closed by rafaelfranca** 2016-01-04 19:05 UTC
Labels: actioncable

**Comment by richpeck** [comment] 2016-01-05 16:46
@marcomd How did you force the dependency? Was that a command-line call or you dl'ed the Rails code and altered the dependency yourself?

**Comment by marcomd** [comment] 2016-01-05 16:56
I changed the dependency inside the gem spec, it is required temporarily as long as em-hiredis will use the working version

**Comment by richpeck** [comment] 2016-01-05 17:09
Thanks for the reply! 
So you cloned the repo and changed the Gemspec locally?

**Comment by marcomd** [comment] 2016-01-06 13:53
Simply installing the gem (not cloning the repo) then you can change the spec locally. You know there is a specific folder with all the specs, there you can force the dependency

**Comment by richpeck** [comment] 2016-01-06 16:41
Again, thanks for the reply.

I'm having trouble loading the gemspec. I've found multiple folders with gemspecs of *installed* gems, none have the Rails 5.0.0 beta file inside. Do you have the path or some further instruction?
