### ISSUE TITLE
how to read uncached data?

### ISSUE THREAD

**Issue by anklos** [rails/rails#25457] opened 2016-06-21 13:20 UTC
### Steps to reproduce

I have a model called `Bid`, and there are a few existing bids in my local database.

1. Start rails console
2. `Bid.all` returns all bids
3. Delete all bid data in database directly
4. I have tried three ways to read uncached data: `Bid.uncached  { Bid.all }`, `ActiveRecord::Base.uncached { Bid.all }` and `Bid.all.reload`, they all return full bids data. And in console it always prints `CACHE (0.0ms)  SELECT "bids".* FROM "bids"  ORDER BY "bids"."updated_at" DESC`, which indicates results are cached data.

### Expected behavior
Return empty array

### Actual behavior
Return cached data

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.0

**Comment by maclover7** [comment] 2016-06-21 15:47
Hmm, [this reproduction script](https://gist.github.com/maclover7/65f43cebf7389863f2ecd26a66af8a3e) passes for me on 4-2-stable (cache is bypassed, query is run).

**Comment by anklos** [comment] 2016-06-22 01:36
@maclover7 right..can you reproduce the issue on your rails console?

**Comment by maclover7** [comment] 2016-06-22 01:46
yeah... works fine for me :/

**Comment by rafaelfranca** [comment] 2016-06-22 01:48
Closing since we can't reproduce but feel free to add more information so we can investigate and reopen if necessary.

**Closed by rafaelfranca** 2016-06-22 01:48 UTC
Labels: activerecord

**Comment by anklos** [comment] 2016-06-22 02:03
@maclover7 ah, sorry, it happened in `before_update` in the `BidObserver` class. only there it always read from cache.
