### ISSUE TITLE
Make it easy to render templates outside of controllers

### ISSUE THREAD

**Issue by dhh** [rails/rails#18409] opened 2015-01-08 18:47 UTC
While templates depend on certain aspects from the controller to be rendered properly, you are often in a scenario where you might need to render something outside of a controller. Examples include jobs, auxiliary scripts, web sockets, etc.

For this purpose, I've been using a RenderMan class like follows:

```ruby
# Would have called this ActionView::Renderer, but that name is already taken
class ActionView::RenderMan
  cattr_accessor(:default_host_options) do
    { "HTTP_HOST"   => 'example.com',
      "SCRIPT_NAME" => '',
      "HTTPS"       => Rails.env.development? ? "off" : "on",
      "rack.input"  => '' }
  end

  def self.render(*args)
    new(*args).render
  end

  def initialize(host_options: Hash.new, **rendering_options)
    @host_options, @rendering_options = host_options, rendering_options
  end

  def render
    with_script_name { controller.render_to_string @rendering_options }
  end

  def controller
    ApplicationController.new.tap do |controller|
      controller.request  = ActionDispatch::Request.new default_host_options.merge(@host_options)
      controller.response = ActionDispatch::Response.new

      controller.params = {}
      Array(@rendering_options[:assigns]).each { |k, v| controller.instance_variable_set "@#{k}", v }
    end
  end

  private
    def with_script_name
      if @host_options["SCRIPT_NAME"]
        begin
          original_default_url_options = Rails.application.routes.default_url_options
          Rails.application.routes.default_url_options = { script_name: @host_options["SCRIPT_NAME"] }
          yield
        ensure
          Rails.application.routes.default_url_options = original_default_url_options
        end
      else
        yield
      end
    end
end
```

In our application, we've further specialized this class into an ApplicationRenderer that looks like so:

```ruby
class ApplicationRenderer < ActionView::RenderMan
  self.default_host_options['HTTP_HOST'] = BC3.domain.hostname
  
  def self.render(account:, **params)
    host_options = (params[:host_options].presence || Hash.new).merge({ 'SCRIPT_NAME' => account.slug_path })
    new(params.merge(host_options: host_options)).render
  end
end
```

It's used as such:

```ruby
ApplicationRenderer.render(account: bucket.account, template: 'webhooks/event', assigns: { event: event })
ApplicationRenderer.render(account: account, partial: "chats/lines/#{line_partial}", locals: locals)
```

(This specialization is mostly just to show the justification of the SCRIPT_NAME munging).

I'd like to see RenderMan go into ActionView, or, if there's a simpler way to achieve the same, then that. I'd also like to find a new class name.

**Comment by pseidemann** [comment] 2015-01-08 23:27
this might be related to #11662. I also like to see this built into rails

**Comment by dhh** [comment] 2015-01-09 01:29
Yup, attacking the same issue.

**Comment by kaspth** [comment] 2015-01-10 18:59
@dhh as for the name, what about something like `UnboundRenderer` or `OmniRenderer`?

**Comment by brainopia** [comment] 2015-01-11 09:16
I'll take a look, if the issue is still unassigned.

**Comment by kaspth** [comment] 2015-01-11 13:12
Go for it.

**Comment by dhh** [comment] 2015-01-11 18:54
Hmm, there's something to `UnboundRenderer` but it's too indirect imo. Maybe StringRenderer could do. That's what it does. Returns the string.

Anyway, @brainopia please do take a stab at this!

**Comment by simi** [comment] 2015-01-11 19:21
What about `DirectRenderer`?

**Comment by dhh** [comment] 2015-01-11 19:38
Hmm. “Direct” is a nice word, but I don’t know if it necessarily implies any more clarity. At some point it is what we define it to be, and it doesn’t matter that much what it really is, I suppose.

**Comment by brainopia** [comment] 2015-01-13 20:56
Hello, David. I've been pondering about this feature. In the example above a request environment consists of `default_host_options` and `host_options`. But at least some of gems depend on environment to contain data populated by middleware.

An example of this would be Devise. A call to `current_user` would fail unless `env['warden']` was setup by Warden middleware. It would be tiresome to manually configure `host_options/default_host_options` in such scenario.

What if we'd have a class that could gather and return a request environment for a given URL by passing it through middleware stack but stopping at application routes. 

```ruby
env = ActionDispatch::Middleware::Env.for 'https://basecamp.com/xxx/projects/yyy',
                                           method: 'GET',
                                           headers: { optional_headers }
```

then it could be used as `host_options/default_host_options`.

It would handle correctly setting all environment variables from your example (`HTTPS`, `HOST_NAME`, `rack.input`, `SCRIPT_NAME` (if it's been setup by application middleware) and many others (e.g., `warden`)).

And we can wrap `ActionDispatch::Middleware::Env` + `ActionView::StringRenderer`
in a additional class to get a simple interface to render arbitrary template for arbitrary request if overhead of calling a middleware stack is acceptable. And if it's not then `ActionView::StringRenderer` is available.

Also regarding `ActionView::StringRenderer#with_script_name` is it necessary in rails 4? Judging by https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/url_for.rb#L41 `SCRIPT_NAME` should be accounted directly from environment without this method. I've tested in application and it has worked for me. May be I'm missing something?

**Comment by dhh** [comment] 2015-01-14 16:34
I like the idea of that! Please give that a go in a PR, and let's try it out. Be happy to test it in our Basecamp stuff. Thanks for working on this.

**Comment by rafaelfranca** [comment] 2015-01-22 14:09
Closed by #18546

**Closed by rafaelfranca** 2015-01-22 14:09 UTC
Labels: actionview

**Comment by assimovt** [comment] 2015-12-08 14:21
What's the easiest way to get the similar behavior with Rails 4? I am trying to get [actioncable-examples](https://github.com/rails/actioncable-examples/blob/master/app/jobs/comment_relay_job.rb#L4) working with 4.2.5.

**Comment by brainopia** [comment] 2015-12-08 14:24
@assimovt here you go https://github.com/brainopia/backport_new_renderer

**Comment by assimovt** [comment] 2015-12-08 14:28
@brainopia Was just reading your Medium post ;) Thanks for the link, will try it out!

**Comment by jclusso** [comment] 2016-11-29 21:59
@dhh I've found myself at this issue after reviewing #18546 and some other related links.

http://www.thegreatcodeadventure.com/using-action-controller-renderers-in-rails-5-with-devise/
https://evilmartians.com/chronicles/new-feature-in-rails-5-render-views-outside-of-actions

What I'm not understanding is how this would ever work in a real world application. Your video on [Rails 5 Action Cable](https://www.youtube.com/watch?v=n0WUjGkDFS0) shows off this code, but what you do is not really possible if you're using any authentication or anything that requires middleware like Devise. 

In the use case you've highlighted in your video, you are rendering views from an asynchronous worker. The only way this would be possible is to pass the request environment in which is basically impossible to serialize.

Am I missing something?

**Comment by dhh** [comment] 2016-12-01 10:43
I don't use Devise, so don't know what that looks like. But you're just rendering the views, not the controller actions. You don't need to have all envs available to do that. If you need that, your code is too tangled. You can just pass the ivar/local vars that the specific template/partial needs.

**Comment by amcates** [comment] 2023-01-26 14:44
Is it possible to use this feature with i18n?  All of my attempts have been unsuccessful.  It seems to always default to :en
