### ISSUE TITLE
Problem with merging scopes and eager loading?

### ISSUE THREAD

**Issue by jmcnevin** [rails/rails#18993] opened 2015-02-18 17:51 UTC
I've modified the AR bug report template to reproduce an issue I've seen with merging of scopes:

```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
    t.integer :user_id
    t.boolean :active, default: true
  end

  create_table :comments, force: true  do |t|
    t.integer :post_id
  end

  create_table :users, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  default_scope { includes(:comments) }
  scope :active, -> { where(active: true) }
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class User < ActiveRecord::Base
  has_many :posts
end

class BugTest < Minitest::Test
  def test_merge
    u = User.create!
    p = Post.create!(user: u)
    c = Comment.create!(post: p)

    puts 'This works.'
    User.joins(:posts).merge(Post.unscope(:includes).active).to_a

    puts 'This breaks.'
    User.joins(:posts).merge(Post.active).to_a
  end
end
```

This will throw the following exception:

```
ActiveRecord::AssociationNotFoundError: Association named 'comments' was not found on User; perhaps you misspelled it?
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations.rb:161:in `association'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations/preloader.rb:156:in `block in grouped_records'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations/preloader.rb:154:in `each'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations/preloader.rb:154:in `grouped_records'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations/preloader.rb:143:in `preloaders_for_one'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations/preloader.rb:115:in `preloaders_on'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations/preloader.rb:103:in `block in preload'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations/preloader.rb:102:in `each'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations/preloader.rb:102:in `flat_map'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/associations/preloader.rb:102:in `preload'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/relation.rb:661:in `block in exec_queries'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/relation.rb:660:in `each'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/relation.rb:660:in `exec_queries'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/relation.rb:546:in `load'
    /Users/jeremym/.rvm/gems/ruby-2.1.0@setup/bundler/gems/rails-0ad6d2764305/activerecord/lib/active_record/relation.rb:244:in `to_a'
    setup.rb:67:in `test_merge'
```

I've been able to reproduce this with 4.1.9, 4.2.0, and master.

**Comment by sgrif** [comment] 2015-02-20 20:07
This looks like the expected behavior. The `includes` values were merged in, and it was something which is invalid when querying against `User`.

**Closed by sgrif** 2015-02-20 20:07 UTC
