### ISSUE TITLE
InvalidAuthenticityToken raised when setting Referrer-Policy: no-referrer; header

### ISSUE THREAD

**Issue by phillycheeze** [rails/rails#30658] opened 2017-09-19 20:29 UTC
### Steps to reproduce
1. Set the following in application.rb or an environment file:
```
config.action_dispatch.default_headers.merge!(
  'Referrer-Policy' => 'no-referrer'
)
```
2. From a Chrome browser, make any valid POST request with a valid authenticity token.
3. Notice the following error is raised: `HTTP Origin header (null) didn't match request.base_url`

### Expected behavior
This error should not be raised since the authenticity token is valid

### Actual behavior
Error is raised

### System configuration
**Rails version**:5.1.4

**Ruby version**:2.3.4

### Cause of issue
In `actionpack/lib/action_controller/metal/request_forgery_protection.rb#L407` it checks if the origin is nil. Chrome, when given the Referrer-Policy header with value `no-referrer`, actually manually sets that header to the string "null". This is new behavior that Chrome (and I suspect Firefox) sets, which breaks this line of the forgery protection.

To solve it, we will need an additional check to see if  `request.origin == 'null'`. 

The offending code is here
```
      # Checks if the request originated from the same origin by looking at the
      # Origin header.
      def valid_request_origin? # :doc:
        if forgery_protection_origin_check
          # We accept blank origin headers because some user agents don't send it.
          request.origin.nil? || request.origin == request.base_url
        else
          true
        end
      end
```

And `request.origin == 'null' # returns true` because Chrome now sets it to a string of null. This would be a great issue to fix since we set this header for strict privacy reasons (see here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)

**Comment by wmakley** [comment] 2017-09-22 18:01
I'm experiencing this on one of my apps. Users could no longer login after updating to Chrome 61. Pretty serious issue.

**Comment by phillycheeze** [comment] 2017-09-22 18:23
I'll try to work on a PR this weekend. I am tagging @jonleighton since he made an update to this exception/method back in April. 

The easy fix is to simply check for a string 'null' value, but long-term there may be a better way to handle this.

**Comment by phillycheeze** [comment] 2017-09-22 18:42
@wmakley For a temporary workaround, you can set the Referrer-Policy to `origin` (this obviously adds the domain origin to the Referer header). I think brand new versions of Chrome now support `same-origin` so that could also be an option.

**Comment by wmakley** [comment] 2017-09-22 19:34
Hmm, that doesn't seem to be the issue on mine. I've tried monkey-patching rails, and setting Referrer-Policy to origin (I didn't have it set either way before), but nothing fixes it. My problem is definitely related though, I just wonder if it has to do with the secure headers gem or devise as well.

**Comment by phillycheeze** [comment] 2017-09-22 19:46
Can you replicate the issue in Chrome? If you can, open up developer tools and find the network request that causes the error. It should show the request Origin header. If it says "null" then this is the same issue. If it is missing or set to another domain, then this is a different issue.

**Comment by wmakley** [comment] 2017-09-22 19:50
Yeah it was a different issue, also caused by Chrome 61 though: https://github.com/twitter/secureheaders/issues/355

I had some headers set for months that caused Chrome 61 to break the login. Weird.

**Comment by yaworsk** [comment] 2017-10-02 19:53
Just wanted to confirm the same behaviour. Using the secure_headers gem, when the referrer-policy is set to no-referrer, Chrome sends a null origin header and rails returns a 422 unprocessable entity error. Changing the header to origin-when-cross-origin fixes the 422

**Comment by sgrif** [comment] 2017-10-09 18:29
Duplicate of #28299

**Closed by sgrif** 2017-10-09 18:29 UTC
