### ISSUE TITLE
config.action_controller.include_all_helpers = false is not respected when set in initializer file

### ISSUE THREAD

**Issue by jcrate** [rails/rails#25418] opened 2016-06-16 14:59 UTC
### Steps to reproduce
Move the option
  `config.action_controller.include_all_helpers = false`
from application.rb to an initializer file.

### Expected behavior
All helpers should not be included for each request. http://api.rubyonrails.org/classes/ActionController/Helpers.html just mentions that the option needs to be set, but does not specify that it cannot be set in an initializer. 

### Actual behavior
The configuration option is ignored and all helpers are loaded.

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.2.4

**Comment by rafaelfranca** [comment] 2016-06-16 15:12
This may happen if the Action Controller for same reason in your application is loaded before the initializers. This is a know limitation of defining options in initializers and depends in the application code. In general you should not load `ActionController::Base` before the initializers in applications.

I'm closing this since it is not a bug in Rails, but a limitation in the initialization process.

cc @fxn

**Closed by rafaelfranca** 2016-06-16 15:12 UTC

**Comment by fxn** [comment] 2016-06-18 15:19
👍
