### ISSUE TITLE
7.0.4 `default_scope` regression. Dependent destroy/delete does not fire when the association returns an empty set because of conditions in the default scope.

### ISSUE THREAD

**Issue by terracatta** [rails/rails#46013] opened 2022-09-12 20:14 UTC
### Summary
When upgrading to 7.0.4 I noticed that deletion queries stopped running if the association no longer can return results due to a condition in the default scope.

### Steps to reproduce
I've prepared the following repro script. (Change the rails version back to 7.0.3 to see the script pass)

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", '7.0.4'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :organizations, force: true
  create_table :posts, force: true do |t|
    t.integer :organization_id
  end
  create_table :topics, force: true do |t|
    t.integer :organization_id
    t.integer :post_id
  end

  add_foreign_key "topics", "posts"
end

class Organization < ActiveRecord::Base
  has_many :posts
  has_many :topics
end

class Post < ActiveRecord::Base
  has_many :topics, dependent: :destroy
  belongs_to :organization
  default_scope { where(organization: Current.organization) }
end

class Topic < ActiveRecord::Base
  belongs_to :post
  belongs_to :organization
  default_scope { where(organization: Current.organization) }
end

class Current < ActiveSupport::CurrentAttributes
  attribute :organization
end

class BugTest < Minitest::Test
  def test_association_stuff
    org1 = Organization.create
    org2 = Organization.create

    Current.organization = org1
    org_1_post = Post.create
    org_1_post_topic = org_1_post.topics.create

    Current.organization = org2

    org_1_post.destroy!
    assert_equal 0, Topic.unscoped.count
  end
end
```

### Expected behavior
The script should run successfully (the topics should be deleted before the parent record is deleted)

### Actual behavior
The script throws an exception because a FK constraint is violated as the model no longer believes it needs to run a deletion at all.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: ruby 3.0.4p208

**Comment by terracatta** [comment] 2022-09-12 20:22
My test script is showing the issue, but my issue description about why it's failing isn't quite right. From what I can see, the actual problem is that the model does not even issue the DELETE query at all (maybe because with the default scope it can no longer see them?)

**Comment by yahonda** [comment] 2022-09-13 06:13
According to git bisect, this behavior change has been introduced via https://github.com/rails/rails/commit/700a6b216f0d6f07fc02372b421f3192ce5ded3e

Just FYI, here are steps to find which commit triggers a behavior change.

```
git clone https://github.com/rails/rails
cd rails
Save the script as  `rep46013.rb` file and replace `gem "rails", '7.0.4'
` with `gem "rails", path: "."` Here are the script that I used.

https://gist.github.com/yahonda/c92c24c626e53117bbbd446e23f37d18
https://gist.github.com/yahonda/c92c24c626e53117bbbd446e23f37d18#file-rep46013-rb-L10

git bisect start v7.0.4 v7.0.3 # git bisect start "bad" "good" tag
git bisect run ruby rep46013.rb
```

**Comment by terracatta** [comment] 2022-09-13 15:11
Thanks @yahonda. 

For folks looking at this issue and deciding if it merits fixing, I'll say that while the previous behavior was beneficial (especially in tests), in production this regression likely has very little impact where we are always reasoning about when to set `Current.organization` in the request lifecycle or in a ActiveJob etc.

I can see a justification for both behaviors and in practice will not impact us much to migrate to the new behavior. That said, I wanted to call it out in an issue in case others were experiencing issues.

**Comment by yahonda** [comment] 2022-11-28 11:54
I'm closing this because at least this is expected behavior.  Thanks again for opening this issue with the detailed steps to reproduce.

**Closed by yahonda** 2022-11-28 11:54 UTC
Labels: activerecord
