### ISSUE TITLE
Odd method delegation `allow_nil` behavior with ActiveStorage attachments

### ISSUE THREAD

**Issue by CodingAnarchy** [rails/rails#33016] opened 2018-05-29 19:16 UTC
### Steps to reproduce

```ruby
class Attachment < ApplicationRecord
  has_one_attached :file

  delegate :filename, to: :file, allow_nil: true
end
```
### Expected behavior

When attachment file is an empty blob, `attachment.filename` should return `nil`.

### Actual behavior

`Module::DelegationError: filename delegated to attachment, but attachment is nil`

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

Ideally, I would expect the options on any delegation to an `ActiveStorage::Attached` subclass to be respected.

**Comment by Schwad** [comment] 2018-06-08 11:06
@CodingAnarchy thanks for submitting this issue. I am getting weird similar responses.

**Comment by giovannibenussi** [comment] 2018-06-13 13:49
I'm not pretty familiar with ActiveStorage but in case someone wants some clue on this issue, a simple solution would be to change ActiveStorage::Attached::One:

```ruby
# activestorage/lib/active_storage/attached/one.rb

module ActiveStorage
  # Representation of a single attachment to a model.
  class Attached::One < Attached
    delegate :filename, to: :attachment, allow_nil: true # add this line
    delegate_missing_to :attachment
```

And a simple test for this would be:

```ruby
# activestorage/test/models/attachments_test.rb
test "without a blob it has a nil filename" do
  assert_nil @user.avatar.filename
end
```

However, as I don't have a lot of experience with ActiveStorage I would like to know others thoughts before issue a pull request.

Regards!

**Comment by maxdavidking** [comment] 2018-06-14 15:46
I can confirm I'm having the same issue as @CodingAnarchy

**Comment by pskl** [comment] 2018-07-06 13:23
Bumping into the same issue.

**Comment by hraynaud** [comment] 2018-07-15 18:32
arrgh me too

**Comment by fabriciofreitag** [comment] 2018-07-24 15:56
+1

**Comment by Shivon** [comment] 2018-07-25 15:40
+1

**Comment by Schwad** [comment] 2018-07-25 16:31
I did not come here with the same reproduction, but I did come here with a very similar error message. This is to some of the +1's who may have been in the same boat.

This happened migrating from carrierwave to activestorage.

Carrierwave: errors would not raise if a file was not present, unless you actively tried to download a nonexistent file. 

Activestorage: Raises error like above. What if you pulled down a copy of `production db` without the pertinent files? Or some other reason a file wouldn't be present? Failures everywhere with this error message. 

What I did that fixed the problem is added some code in an initializer that would 'attach' a dummy file to these objects on the fly in development if the error raised. Not elegant, but efficient. 

If my problem sounds similar to any of this, let me know and I can share the code.

**Comment by halo** [comment] 2018-07-25 18:08
@CodingAnarchy

Technically you would write the following to get the filename, as the filename is defined on the Blob:

```ruby
class Recipe < ApplicationRecord
  has_one_attached :image
end

recipe.image.attachment.blob.filename
```

Now, for your convenience, `image` (you called it `file` in your example) will delegate every unknown method call to its attachment. And the attachment in turn, will delegate every unknown method call to its blob:

```ruby
recipe.image.filename

# At this point `image` says:
# "wow, what's filename? Let's ask my attachment."

# So, effectively the shortcut above translates into:
recipe.image.attachment.filename

# At this point `attachment` says:
# "wow, what's filename? Let's ask my blob."

# So, effectively the shortcut above translates into:
recipe.image.attachment.blob.filename
```

It may well be that there is no attachment. In other words, there is no `ActiveStorage::Attachment` row in your database with a `record_id` pointing to your `recipe.id`.

That's when you see the error you described ("filename delegated to attachment, but attachment is nil").

---

So @giovannibenussi was on the right track by suggesting that the whole chain should be cut off and a `nil` should be returned instead of the error being raised.

However, that's not very feasible because that would have to be done for every single method that `ActiveStorage::Attachment` may respond to, such as `#created_at` and `#record`.

And since the attachment only delegates further to its blob, the fix would also have to include every method that `ActiveStorage::Blob` might be answering for. Such as `#filename`, `#checksum`, etc.

The current implementation is "simple" by just passing everything on instead of writing a lot of code to handle all possible method names.

---

@Schwad complained about an exception being raised in the chain:

> Or some other reason a file wouldn't be present? Failures everywhere with this error message.

I believe it's ambiguous to say "a file is not present". It could mean one of the following:

1. There was never an attempt to attach a file to a record. In other words, it's just a recipe without image. There is no `ActiveStorage::Attachment` in the database
2. There is a `ActiveStorage::Attachment` in the database but it is missing a `ActiveStorage::Blob` record 
3. There is both a `ActiveStorage::Attachment` and its `ActiveStorage::Blob`, but the actual file is missing on the storage space.

The **third one**, the actual file is missing, is out of scope for this issue. Because that would not raise this error.

The **first one** is rather natural. You cannot access an attachment that doesn't exist. Period. If you ask the router to create an URL for it via `redirect_to recipe.image`, the router will raise the dreaded exception because it cannot create a route for `nil`. The only correct way to handle this is to ask [this method](https://github.com/rails/rails/blob/ab8847c92092a57df6433f4fc72682074359531f/activestorage/lib/active_storage/attached/one.rb#L38-L47) first, which exists just for this purpose: `if recipe.image.attached?` so that you won't try to access a non-existing attachment.

I'm not sure how the **second one**, a `Blob` record missing, could even occur. To me, this would indicate data corruption (e.g. manually deleting a `Blob`). 

Let's even just say, this would occur during the upload of the file. The proper way to handle this would probably be checking in your code:

```ruby
recipe.attached? && recipe.blob?
```

But again, I'm not sure this scenario can occur at all. Usually just asking `recipe.attached?` should be fine in 99% of the cases.

> What I did that fixed the problem is added some code in an initializer that would 'attach' a dummy file to these objects on the fly in development if the error raised. Not elegant, but efficient.

I cannot tell whether this is a proposed solution for problem number 1, 2, or 3. It sounds like solving number 2. But @Schwad also said:

> What if you pulled down a copy of production db without the pertinent files?

Are you implying that you download the production database but not the tables `active_storage_attachment` and `active_storage_blob`? Because you should definitely be able to download those two as well!

If you simply omit *the actual files* on the storage file system, you will get another error. E.g. a `Errno::EOENT` when downloading the file. 

That would be the **third one** in the list.

---

All that being said, I agree that the error message is confusing and misleading. Especially for people who are new to ActiveStorage. The title "Odd method delegation" just says it all :)

It feels natural to have `recipe.image.filename` return `nil` when there is no attachment.

But it's also important for developers to understand that you cannot ask for **any** information (filename, metadata, checksum, etc) if there is no attachment to ask these questions to.

My goal here was simply clarification, I don't have a good solution. I would probably keep the exception, but explain that "you have to ask `attached?` first to see whether you can query this information" in the message.

The [ActiveStorage Guide](https://edgeguides.rubyonrails.org/active_storage_overview.html) mentions `attached?` but it does not mention how to retrieve the filename and that that can only be done in conjunction with `attached?`. Maybe the documentation should be improved (volunteers?)

---

> This is to some of the +1's who may have been in the same boat.

@Shivon @fabriciofreitag @hraynaud @pskl @maxdavidking
Please do not add "bump comments" containing `+1`. 

Because people, like me, will subscribe to this issue, waiting for solutions, and instead getting 4 emails with more "problems" that don't add any information.

This creates email noise for *all* participants (including the Rails core team) and friction when reading through this issue. See https://github.com/golang/go/wiki/NoPlusOne

Thank you!

**Comment by CodingAnarchy** [comment] 2018-07-25 20:13
@halo

>So @giovannibenussi was on the right track by suggesting that the whole chain should be cut off and a nil should be returned instead of the error being raised.

>However, that's not very feasible because that would have to be done for every single method that ActiveStorage::Attachment may respond to, such as #created_at and #record.

Is this not the purpose of the `delegate_missing_to` method added in Rails 5.1?  Would that not work with the `allow_nil: true` option?  The only problem is that the `allow_nil: true` option is not "respected" because the delegation does not have that option throughout the chain, as there is no capacity for such an option on `delegate_missing_to` (yet).

I don't see any obvious reason why the entire chain could not have this `allow_nil` style delegation for all methods by just changing the options to a few delegation lines and the functionality of `delegate_missing_to` to allow a return of `nil` (just like `delegate [], to:` already can).

>The only correct way to handle this is to ask this method first, which exists just for this purpose: `if recipe.image.attached?` so that you won't try to access a non-existing attachment.

You can see, though, why peppering every call to every method you might call on the file with a check to see if it exists first seems redundant and complicates the code.  Things like `filenames` and `created_at`, etc. seem like a case where just returning `nil` works just fine.

For instance, if I want to get the filename or put a default string, right now I need to write:

```
- if record.file.attached?
   = record.file.filename
- else
  = "Default string"
```

This isn't extremely bad, but intuitively it seems easier to just write `record.file.filename || "default"`, and I won't run into any issues where I forgot to check beforehand here.  

> I'm not sure how the second one, a Blob record missing, could even occur. To me, this would indicate data corruption

This is a common occurrence for me in the Rails 5.2 version of ActiveStorage due to a bug with transaction rollbacks. (See #32449.)  That issue has been fixed, but not in a backwards compatible way as I understand, so it will remain an issue until Rails 6.  I have a clunky monkey-patch in my own code to avoid it, but I can see others running into it and (like myself originally) not knowing what's going on where `attached?` returns true but there is no `ActiveStorage::Blob` to check against.

**Comment by CodingAnarchy** [comment] 2018-07-25 20:17
I would also add that the natural behavior of `allow_nil: true` is precisely to have the delegation return `nil` if (a) the associated record is missing or (b) the method does not exist on the associated record.  So in this case, it is in at least a direct sense, "broken".

**Comment by Schwad** [comment] 2018-07-25 20:44
I feel that it is a touch overzealous to refer to my comment as a “complaint” :)

I just feel that some of the silent “+1’s” may have gotten here googling the error message that we see here. So I added my observation. 

I am sorry if my message came off as ambiguous. Our situation involved using azure storage- so an instance where a pull down of the full prod db without production credentials in development would result in “no file”. 

The solution is a simple monkey patch in development, rescuing the exception and attaching a dummy file (our development is local storage) and rerunning the method. 

I very much appreciate the discussion here and just wanted to document my thoughts for others who came here in the same boat . Good luck! :)

**Comment by Schwad** [comment] 2018-07-26 12:35
@halo thanks for the thoughts/feedback :) 

Undoubtedly your approach cloning the whole thing into the development bucket is much better!

**Comment by msdundar** [comment] 2018-08-11 17:30
Same issue here, on Rails 5.2.1.

**Closed** 2019-05-23 20:33 UTC
Labels: activestorage, pinned
