### ISSUE TITLE
Exceptions raised from templates should show template code not compiled methods

### ISSUE THREAD

**Issue by dhh** [rails/rails#51090] opened 2024-02-14 16:37 UTC
Seems like we've regressed on exceptions raised from within ERB templates. They're showing the backtrace of the compiled method instead of the underlying template. That's not very helpful.

![CleanShot 2024-02-14 at 08 36 52@2x](https://github.com/rails/rails/assets/2741/0064e1df-78c8-466c-a2a0-1f498bfb6471)

**Comment by rafaelfranca** [comment] 2024-02-14 20:50
I just tried on apple silicon and linux the following steps:

```
rails new --dev my_app
cd my_app
bin/rails g scaffold posts title body
bin/rails db:migrate
```

Then I edited `posts/index.html.erb` to add the invalid code, started the server and got the error pointing to the template. I'm also using 3.2.2.

Which steps did you take to reproduce?

**Comment by dhh** [comment] 2024-02-14 22:23
Oh this is a strange one. This triggers the busted exception:

```
<ul>
  <li><%= link_to post.title, post %></li>
</ul>

<%= link_to "New book", new_book_path %>
```

but this does not:

```
<ul>
  <li>
    <%= link_to post.title, post %>
  </li>
</ul>

<%= link_to "New book", new_book_path %>
```

**Comment by rafaelfranca** [comment] 2024-02-14 22:25
aha! I think maybe the compiled template line isn't matching the source line.

**Comment by rafaelfranca** [comment] 2024-02-14 22:31
Just confirmed this also happens on 7.1

**Comment by nikhilbhatt** [comment] 2024-03-12 07:48
Minimum code to regenerate the issue -->

```
<li><%= link_to post.title, post %></li>
```
Even if empty spaces are present after closing braces it will result in showing compiled string.

```
<%= link_to post.title, post %>  <empty_spaces>
```

**Problem**
1. File- `activesupport/lib/active_support/core_ext/erb/util.rb` method - `tokenize`
2. In this `tokenize` method we are not handling end text that is present after the code `%>`
3. Because of this if empty spaces or text is present after code will result in `raise NotImplementedError`
4. And the final output will take the compiled code.

**Solution**
1. Handle the edge case if some text is present in string.
```
  unless source.eos? || source.exist?(/#{start_re}|#{finish_re}/m)
     tokens << [:TEXT, source.rest]
     source.terminate
  end
```

**Closed** 2024-05-20 08:15 UTC
Labels: actionpack, actionview
