### ISSUE TITLE
undefined method cache for nil:NilClass in  `actionview/lib/action_view/template/resolver.rb`

### ISSUE THREAD

**Issue by immae** [rails/rails#23249] opened 2016-01-25 22:42 UTC
In `actionview/lib/action_view/template/resolver.rb`, a private method `cached` is called in `find_all_anywhere`, but this method is a method that requires an instance variable @cache to be defined (which is initialized in another class class), and is not initialized here, thus the error raised.

**Comment by maclover7** [comment] 2016-01-25 22:47
Duplicate of #23248.

**Closed by maclover7** 2016-01-25 22:47 UTC
Labels: actionview

**Comment by immae** [comment] 2016-01-25 22:49
It doesn't look like a duplicate of #23248 to me?

**Comment by pmueller** [comment] 2016-01-25 23:43
I am affected by this as well, on ruby `2.2.3` after upgrading rails from `4.2.5.0` to `4.2.5.1`. I think this may be different from #23248, @maclover7 

```
 NoMethodError:
       undefined method `cache' for nil:NilClass
actionview-4.2.5.1/lib/action_view/template/resolver.rb:151:in `cached'
actionview-4.2.5.1/lib/action_view/template/resolver.rb:121:in `find_all_anywhere'
```

**Comment by maclover7** [comment] 2016-01-25 23:50
If anyone is seeing any RSpec failures, please see this PR for further review: https://github.com/rspec/rspec-rails/pull/1533

**Comment by pmueller** [comment] 2016-01-25 23:51
Thanks!
