### ISSUE TITLE
Joins from a default_scope is not being respected while using association in has_many :through options

### ISSUE THREAD

**Issue by praveenkumarsinha** [rails/rails#27069] opened 2016-11-16 20:05 UTC
### Steps to reproduce

Suppose here are models defined in application (don't go by names, names used are mere representation)

```
class Appointment < ApplicationRecord
  has_one :transaction_charge, inverse_of: :appointment
  has_many :spoons, inverse_of: :appointment
  belongs_to :umbrella, inverse_of: :appointments

  accepts_nested_attributes_for :transaction_charge

  default_scope { joins(:transaction_charge).where(['transaction_charges.status =? ', true]) }
end

```
```
class TransactionCharge < ApplicationRecord
  belongs_to :appointment, inverse_of: :transaction_charge
end
```
```
class Spoon < ApplicationRecord
  belongs_to :appointment, inverse_of: :spoons
end
```
```
class Umbrella < ApplicationRecord
  has_many :appointments, inverse_of: :umbrella
  has_many :spoons, through: :appointments
end
```

and a seed exists like
```
u = Umbrella.create(name: 'Umbrella 01')
a = u.appointments.create(name: 'appointment 01', transaction_charge_attributes: {status: true, name: 'transaction_charge 01'})
a.spoons.create(name: 'Spoon 01')
a.spoons.create(name: 'Spoon 02')
a.spoons.create(name: 'Spoon 03')
a.spoons.create(name: 'Spoon 04')
a.spoons.create(name: 'Spoon 05')
```

### Expected behavior
While querying for 'spoons' from an object of 'umbrella', i expect it to be
```
2.3.0 :001 > u = Umbrella.take
  Umbrella Load (0.5ms)  SELECT  `umbrellas`.* FROM `umbrellas` LIMIT 1
 => #<Umbrella id: 1, name: "Umbrella 01", created_at: "2016-11-16 18:46:34", updated_at: "2016-11-16 18:46:34"> 
2.3.0 :002 > u.spoons
  Spoon Load (0.7ms)  SELECT `spoons`.* FROM `spoons` INNER JOIN `appointments` ON `spoons`.`appointment_id` = `appointments`.`id` INNER JOIN `transaction_charges` ON `transaction_charges`.`appointment_id` = `appointments`.`id` WHERE (transaction_charges.status =1 ) AND `appointments`.`umbrella_id` = 1
 => #<ActiveRecord::Associations::CollectionProxy [#<Spoon id: 1, appointment_id: 1, name: "Spoon 01", created_at: "2016-11-16 18:46:34", updated_at: "2016-11-16 18:46:34">, #<Spoon id: 2, appointment_id: 1, name: "Spoon 02", created_at: "2016-11-16 18:46:34", updated_at: "2016-11-16 18:46:34">, #<Spoon id: 3, appointment_id: 1, name: "Spoon 03", created_at: "2016-11-16 18:46:34", updated_at: "2016-11-16 18:46:34">, #<Spoon id: 4, appointment_id: 1, name: "Spoon 04", created_at: "2016-11-16 18:46:34", updated_at: "2016-11-16 18:46:34">, #<Spoon id: 5, appointment_id: 1, name: "Spoon 05", created_at: "2016-11-16 18:46:35", updated_at: "2016-11-16 18:46:35">]> 
```

**2.3.0 :003 > u.spoons.to_sql
 => "SELECT `spoons`.* FROM `spoons` INNER JOIN `appointments` ON `spoons`.`appointment_id` = `appointments`.`id` INNER JOIN `transaction_charges` ON `transaction_charges`.`appointment_id` = `appointments`.`id` WHERE (transaction_charges.status =1 ) AND `appointments`.`umbrella_id` = 1" ** 

Need attention on the query that should had been formed to fetch the results

### Actual behavior
But in reality, join statement is being ignored from default scope but condition i.e. where clause is respected.
**2.3.0 :003 > u.spoons.to_sql
 => "SELECT `spoons`.* FROM `spoons` INNER JOIN `appointments` ON `spoons`.`appointment_id` = `appointments`.`id` WHERE (transaction_charges.status =1 ) AND `appointments`.`umbrella_id` = 1"** 

and that results in ActiveRecord::StatementInvalid exception

```
2.3.0 :001 > u = Umbrella.take
  Umbrella Load (0.5ms)  SELECT  `umbrellas`.* FROM `umbrellas` LIMIT 1
 => #<Umbrella id: 1, name: "Umbrella 01", created_at: "2016-11-16 18:46:34", updated_at: "2016-11-16 18:46:34"> 
2.3.0 :002 > u.spoons
  Spoon Load (0.9ms)  SELECT `spoons`.* FROM `spoons` INNER JOIN `appointments` ON `spoons`.`appointment_id` = `appointments`.`id` WHERE (transaction_charges.status =1 ) AND `appointments`.`umbrella_id` = 1
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'transaction_charges.status' in 'where clause': SELECT `spoons`.* FROM `spoons` INNER JOIN `appointments` ON `spoons`.`appointment_id` = `appointments`.`id` WHERE (transaction_charges.status =1 ) AND `appointments`.`umbrella_id` = 1
	from /home/praveen/.rvm/gems/ruby-2.3.0@figsr5/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
	from /home/praveen/.rvm/gems/ruby-2.3.0@figsr5/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
	from /home/praveen/.rvm/gems/ruby-2.3.0@figsr5/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
	from /home/praveen/.rvm/gems/ruby-2.3.0@figsr5/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
	from /home/praveen/.rvm/gems/ruby-2.3.0@figsr5/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'

```

so in the mean time am mitigating it with a custom sql join, like this
```
class Umbrella < ApplicationRecord

  has_many :appointments, inverse_of: :umbrella
  has_many :spoons, -> { joins(' INNER JOIN `transaction_charges` ON `transaction_charges`.`appointment_id` = `appointments`.`id` ') }, through: :appointments
  # has_many :spoons, through: :appointments

end
```

### System configuration
**Rails version**: Rails 5.0.0.1

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by utilum** [comment] 2016-11-17 13:45
@praveenkumarsinha : Names help us understand the abstractions we ask the machine to create and manipulate. Trying to imagine real-world relations between your model names is confusing. Additionally, I have the impression that you provide more details than would be necessary to demonstrate the problem.
Could you try to produce a minimal executable using (this template)[https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb] ?

**Comment by praveenkumarsinha** [comment] 2016-11-18 18:42
Okey here you go..

https://gist.github.com/praveenkumarsinha/a0e77684ba12e69f6c02cff2f2197d03

**Comment by utilum** [comment] 2016-11-19 09:02
Good show @praveenkumarsinha. 
Only problem is the test passes, and you want it to fail, because it fails what you expect, right?

**Comment by praveenkumarsinha** [comment] 2016-11-19 11:57
Yes @utilum 
That https://gist.github.com/praveenkumarsinha/a0e77684ba12e69f6c02cff2f2197d03#file-active-record-query-issue-joins-from-a-default_scope-L91 is a negative assertion.. it should have failed there

**Comment by utilum** [comment] 2016-11-19 22:02
@praveenkumarsinha : In general one writes a test that fails, so that once the code is fixed the test will pass. I've tried to trim and prune your test some more, eoes [this gist](https://gist.github.com/utilum/1bed25de699bf778933263aaf4ae22e6) demonstrate what you are up against?

**Comment by utilum** [comment] 2016-11-20 10:01
Is this a duplicate of #19226 ?

**Comment by maclover7** [comment] 2016-11-20 14:11
Agree with @utilum, this seems very similar to #19226; closing as a dup of that issue.

**Closed by maclover7** 2016-11-20 14:11 UTC
Labels: activerecord, needs work
