### ISSUE TITLE
Chrome display issue with api.rubyonrails.org

### ISSUE THREAD

**Issue by creativetags** [rails/rails#39005] opened 2020-04-21 09:18 UTC
I’m seeing a display issue in Chrome on Mac with the sidebar being offset like this:

![PastedGraphic-1](https://user-images.githubusercontent.com/24856/79848703-5830c100-83b9-11ea-9e1b-7e7208580271.png)

It looks fine on Firefox and Safari

Quick fix is remove overflow-x: hidden from .panel

**Comment by eugeneius** [comment] 2020-04-21 09:23
Duplicate of https://github.com/rails/rails/issues/38768, see https://github.com/rails/rails/issues/38768#issuecomment-601393775.

**Closed by eugeneius** 2020-04-21 09:23 UTC

**Comment by simi** [comment] 2020-04-21 09:49
Just to say, this is present for a while (and it is really annoying). Is there any release planned for now? Isn't it possible to just regenerate current docs? Can I help somehow in here?

**Comment by rafaelfranca** [comment] 2020-04-21 16:36
The answers for your questions are.

Maybe, no and no.
