### ISSUE TITLE
Query params are lost on a test with body

### ISSUE THREAD

**Issue by tamarr** [rails/rails#32067] opened 2018-02-20 10:17 UTC
### Steps to reproduce

Write a controller test like so:
`put :my_path, params: {path_param: x, query_param: y}, body: { body_param: z }.to_json, as: :json`

### Expected behavior

query_param should be available on the params on the controller.

(This can be worked around by putting the query param in the `body` or removing the body completely and adding it to `params` but that creates a difference between test and application)

### Actual behavior

`path_param` and `body_param` are available on the strong params object but `query_param` does not exist in that hash.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.1

**Comment by marcio-soares** [comment] 2018-02-20 10:25
this version of ruby ​​is problematic, replace it with 2.4.2

**Comment by pixeltrix** [comment] 2018-02-20 11:13
@tamarr controller tests are deprecated so we're not fixing bugs in them - use ActionDispatch::IntegrationTest instead. Not sure about 5.1 but on master using the body kwarg has no effect on what's in the params hash.

Duplicate of #23779

**Closed by pixeltrix** 2018-02-20 11:13 UTC
