### ISSUE TITLE
Strong_params erroneously calls 'with_indifferent_access' on scalar values

### ISSUE THREAD

**Issue by chriskilding** [rails/rails#17045] opened 2014-09-24 14:55 UTC
This is a repost of a potential bug in strong_params over at https://github.com/rails/strong_parameters/issues/207, as nobody has yet looked at that bug report.

---

It looks like the recursive hash builder inside strong_params is trying to turn bottom-level scalar values into hashes, which would suggest the recursion is not stopping in certain cases when it hits the bottom of the tree. In the example below, this only happens on the scalar values inside the 'some_array_of_hashes_containing_scalars' array of hashes.

The error message does not trace into the strong_params source code, so I can't be more specific about what the problem is. This is the extent of the message:

```
Completed 500 Internal Server Error in 1512ms

NoMethodError (undefined method `with_indifferent_access' for "d":String):
  app/controllers/api/v1/jobs_controller.rb:21:in `create'


  Rendered vendor/bundle/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.0ms)
  Rendered vendor/bundle/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (4.0ms)
  Rendered vendor/bundle/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (468.0ms)
  Rendered vendor/bundle/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (494.0ms)
```

The relevant parts of the controller (I have had to redact parts of the code):

```
def create
  job = Job.new job_params
  respond_with job, location: api_v1_jobs_url(job)
end

...

private

def job_params
  params.require(:job).permit(
    :some_scalar_attribute,
    :some_array_of_scalars  => [],
    :some_array_of_hashes_containing_scalars => [:scalar_one, :scalar_two]
  )
end
```

The sent json (again redacted to some extent):

```
{
  "job": {
    "some_scalar_attribute": "foo",
    "some_array_of_scalars": ["b", "c"],
    "some_array_of_hashes_containing_scalars": [
      {"scalar_one": "d", "scalar_two": "e"},
      {"scalar_one": "f", "scalar_two": "g"}
    ]
  }
}
```

Platform that we saw this bug on:
- rails 4.1.5
- jruby 1.7.13 (and also saw the bug on 1.7.10)
- oracle jdk 7
- os x 10.9.4/5

**Comment by HashNotAdam** [comment] 2018-10-21 18:20
I was unable to reproduce this issue using the script provided and:
- jruby 1.7.13 (1.9.3p392) 2014-06-24 43f133c on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14
- rails (4.1.5)
- rake (10.3.2)
- macOS 10.13.6

**Comment by jonathanhefner** [comment] 2020-05-08 20:06
I am unable to reproduce this using Rails 6.0.3 and @simonykq's script from https://github.com/rails/rails/issues/17045#issuecomment-56962873.  (Note: the script must be run with `RAILS_ENV=test` in order to avoid a false negative due to `ActionDispatch::HostAuthorization`.)

I'm going to close this issue, but if the problem still exists, please do comment and include a minimal reproduction script.

**Closed by jonathanhefner** 2020-05-08 20:06 UTC
Labels: With reproduction steps
