### ISSUE TITLE
Performance Regression using url_router

### ISSUE THREAD

**Issue by Calamari** [rails/rails#23451] opened 2016-02-03 17:10 UTC
After Rails upgrade from 4.2.4 to 4.2.5 we encoutered a performance regression in our views. The now take mostly twice that many times rendering out json views.

The regression was introduced with that commit: https://github.com/rails/rails/commit/07dfd2ea097706ef0240f1dda5236cdc5f2c8843

For confirming that, we created a complete new app using:
```bash
rails new greenfield --database=sqlite3
cd greenfield
bundle
rails g scaffold thing name:string
rails c
```

Where we ran the following simple benchmarking script:
```ruby
require 'benchmark'

Benchmark.bmbm do |x|
  x.report "routes" do
    1000.times do
      Rails.application.routes.url_helpers.new_thing_url(host: 'localhost')
    end
  end
end
```

A bit crude, I know. But the results we get, do look something like this:

```bash
Rehearsal ------------------------------------------
routes
  1.240000   0.010000   1.250000 (  1.255489)
--------------------------------- total: 1.250000sec

             user     system      total        real
routes   1.130000   0.000000   1.130000 (  1.143587)
```

When forking the `4-2-stable` branch and reverting the mentioned commit `07dfd2ea097706ef0240f1dda5236cdc5f2c8843`, we get this:

```bash
Rehearsal ------------------------------------------
routes   0.070000   0.000000   0.070000 (  0.070763)
--------------------------------- total: 0.070000sec

             user     system      total        real
routes   0.050000   0.000000   0.050000 (  0.050603)
```

In #22320 there is a fix mentioned, but that commit does change nothing at this benchmark results (or our view render benchmarks).

**Comment by sgrif** [comment] 2016-02-03 17:40
The benchmark posted is invalid. URL helpers are included in classes via `include Rails.application.routes.url_helpers`. The following benchmark script, which closer approximates how Rails handles this internally is:

```ruby
helpers = Rails.application.routes.url_helpers

Benchmark.ips do |bm|
  bm.report("url generation") { helpers.new_thing_url(host: 'localhost') }
end
```

That benchmark does show a small regression from 07dfd2ea097706ef0240f1dda5236cdc5f2c8843, but it's barely outside of the margin of error, and has been addressed in 5.0.

I'd check your app for abnormal access of url helpers.

**Closed by sgrif** 2016-02-03 17:40 UTC

**Comment by jeffrafter** [comment] 2016-04-14 22:12
I don't think this should be closed. I have run this in 4.1 and 4.2 and the issue is very clear:

Here is the benchmark I ran
```ruby
helpers = Buyer::Engine.instance.routes.url_helpers

Benchmark.bmbm do |x|
  x.report("url helper using cached helpers") {
    500.times do
      helpers.campaign_url("sup")
    end
  }
  x.report("url helper using the instance") {
    500.times do
      Buyer::Engine.instance.routes.url_helpers.campaign_url("sup")
    end
  }
  x.report("url helper using the class") {
    500.times do
      Buyer::Engine.routes.url_helpers.campaign_url("sup")
    end
  }
end
```

## Rails 4.1.x results
```
                                      user     system      total        real
url helper using cached helpers   0.070000   0.000000   0.070000 (  0.070212)
url helper using the instance     0.060000   0.000000   0.060000 (  0.066860)
url helper using the class        0.070000   0.000000   0.070000 (  0.072689)
```


## Rails 4.2.5.2 results
```
                                      user     system      total        real
url helper using cached helpers   2.990000   0.040000   3.030000 (  3.107506)
url helper using the instance     5.910000   0.110000   6.020000 (  6.203739)
url helper using the class        6.150000   0.080000   6.230000 (  6.724021)
```

In Rails 4.2.x using the cached helpers (as suggested) makes a huge difference. But the helpers even at their best are still almost 2 orders of magnitude slower. I think this should be reopened.

**Comment by jeffrafter** [comment] 2016-04-15 00:38
This issue also seems relevant: https://github.com/rails/rails/issues/22320
