### ISSUE TITLE
5.2.1.1 breaks simple_form

### ISSUE THREAD

**Issue by ThomasConnolly** [rails/rails#34575] opened 2018-11-30 14:14 UTC
### Steps to reproduce
Attempt to start server, development env
### Expected behavior
should run server
### Actual behavior
! Unable to load application: NameError: uninitialized constant SimpleForm
09:09:39 web.1  | bundler: failed to load command: puma (/home/tom/.rvm/gems/ruby-2.5.1/bin/puma)
09:09:39 web.1  | NameError: uninitialized constant SimpleForm
09:09:39 web.1  |   /home/tom/paul/config/initializers/ranged_datetime_wrapper.rb:1:in `<top (required)>'

### System configuration
**Rails version**: 5.2.1.1

**Ruby version**:
2.5.1

**Comment by Edouard-chin** [comment] 2018-11-30 14:37
It's hard to see what could cause that with the couple line of log you provided. Can you reproduce the issue using the [bug report template](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report)

**Comment by rafaelfranca** [comment] 2018-11-30 16:06
As simple form maintainer and the person who released 5.2.1.1 I find very unlikely that 5.2.1.1 would break simple form at all, even more with that error.

That error means that the Ruby process could not find the constant SimpleForm. There are two ways for that happen. Either the gem is not present of the gem is not being required. There was no code changes in Rails that changed the way gems are required so I suggest you to check your Gemfile, Gemfile.lock and your initializers to make sure your application is requiring the gems correctly.

**Comment by gmcgibbon** [comment] 2018-12-02 05:11
I'm unable to reproduce this. I would recommend trying to reproduce this on a sample rails app, and making sure `rails` and `bundler` in your `$PATH` are using the same ruby. This seems like an environment issue to me.

**Comment by msdundar** [comment] 2018-12-03 00:01
Seems like fixed in https://github.com/plataformatec/simple_form/issues/1622 and can be closed.

**Closed** 2018-12-03 00:15 UTC
