### ISSUE TITLE
Bug in ActionDispatch::Integration::RequestHelpers

### ISSUE THREAD

**Issue by akozhemiakin** [rails/rails#24864] opened 2016-05-05 17:27 UTC
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb

I believe, this part of code is intended to check if the request args (if any) has only following keys: params, headers, env, xhr. 

```ruby
REQUEST_KWARGS = %i(params headers env xhr)
def kwarg_request?(args)
  args[0].respond_to?(:keys) && args[0].keys.any? { |k| REQUEST_KWARGS.include?(k) }
end

def non_kwarg_request_warning
  ActiveSupport::Deprecation.warn(<<-MSG.strip_heredoc)
    ActionDispatch::IntegrationTest HTTP request methods will accept only
    the following keyword arguments in future Rails versions:
    #{REQUEST_KWARGS.join(', ')}

    Examples:

    get '/profile',
      params: { id: 1 },
      headers: { 'X-Extra-Header' => '123' },
      env: { 'action_dispatch.custom' => 'custom' },
      xhr: true
  MSG
end
```

However, there are two problems with this code.

First one is with the *kwarg_request?* method itself. It returns true even if only one of the arguments is from the allowed list.
```ruby
# Will return false
kwarg_request?({foo: 10})
# Will return true and do not trigger deprecation warning in the request methods (get, post...)
kwarg_request?({headers: {}, foo: 10})
```

I believe 'any?' in its implementation should be replaced with 'all?':
```ruby
def kwarg_request?(args)
  args[0].respond_to?(:keys) && args[0].keys.all? { |k| REQUEST_KWARGS.include?(k) }
end
```

The second possible problem (I'm not sure, maybe it is indented behavior and I misunderstand something) is with the allowed args themselves: what about 'as' arg? Fore example look at the example in the current documentation: 
```ruby
post articles_path, params: { article: { title: 'Ahoy!' } }, as: :json
```
It seems that 'as' should be added to the allowed args list:
```ruby
REQUEST_KWARGS = %i(params headers env xhr as)
```

If I'm right with all this stuff I'm ready to prepare a pull request.

### System configuration
**Rails version**: 5.0.0.beta4

**Comment by maclover7** [comment] 2016-05-05 19:32
+1 for opening up a PR, these changes make sense to me.

@kaspth, if I remember correctly, were you working on some of the `as` stuff, as part of #23597?

**Comment by kaspth** [comment] 2016-05-05 19:57
Think the kw arg'ed version will blow up with an unknown keyword error when passed `foo`, so I don't think `all?` is needed.

We should add `as` to the kw arg list as you mention (and add a regression that a request purely using `as` is not deprecated). Nice catch! ❤️

**Comment by akozhemiakin** [comment] 2016-05-06 12:35
> Think the kw arg'ed version will blow up with an unknown keyword error when passed foo, so I don't think all? is needed.

@kaspth Then I'm not sure that I fully understand the purpose and mechanics behind it. If we have deprecation warning stating that "ActionDispatch::IntegrationTest HTTP request methods will accept only the following keyword arguments in future Rails versions: ..." and some method to check if we need to show this warning, will not it be logical to show this warning for every args hash with one ore more unpermitted parameters?

Also would not you mind to help me and tell where is the test for RequestHelpers located? I searched through ./actionpack/test/dispatch/**/* files but did not succeed :( And if there are no tests for that stuff yet, where do you think should we place them?

**Comment by Envek** [comment] 2016-05-11 11:14
Also I do not understand from this warning how I should rewrite POST with binary data, like this one?

```ruby
post '/some/path/action', raw_request_body
```

**Comment by kaspth** [comment] 2016-05-30 18:06
Just added `as` to the kw args: https://github.com/rails/rails/pull/25164

> will not it be logical to show this warning for every args hash

@akozhemiakin Ah, I see what you're saying, users could have their tests blow up once we remove the deprecation. Yes, let's change that to `all?` 👍 — please submit a pull request!

@Envek we can't cover every case in a deprecation warning. We'd describe the change with more nuance in the release notes. If we haven't, do submit a pull request 😁

Your example would look like:

```ruby
post articles_url, params: raw_request_body
```

**Comment by jeremy** [comment] 2016-05-30 21:27
If we switch to whitelisting exact keyword args then we won't be able to override+super `#process` with our own keyword args. We'd need to override get/post/…/xhr individually.

For example, say we have a common pattern of passing an OAuth2 bearer token for API authorization, so we accept a `user: …` arg to `API::IntegrationTest#process` which sets the Authorization header for us, allowing
```
post foobars_url, user: @user, params: …
```

Now the `user:` arg wouldn't pass muster and the invocation would be treated as a deprecated non-kwarg call, when it clearly is. Any usage of the new keyword args makes it a kwarg-style call.

To address properly enforcing expected keyword args, I'd suggest doing this at the `#process` level instead. We can rely on Ruby's keyword arg handling rather than implementing it ourselves.

**Comment by akozhemiakin** [comment] 2016-05-30 22:24
Look carefully through the current implementation:
```ruby
def kwarg_request?(args)
  args[0].respond_to?(:keys) && args[0].keys.any? { |k| REQUEST_KWARGS.include?(k) }
end
```
Current implementation says: "return true if args is a hash (responds to :keys) and **it has at least one key from the permitted list**". It has no sense. I'm not sure if it is good or bad idea to whitelist args here, but current implementation definitely has no sense either way. I think we should either fix it to actually check that all values are from the permitted list (as it is done in the pull request) or to remove this check at all.

**Comment by jeremy** [comment] 2016-05-30 23:22
The method's purpose is to distinguish new invocation style (using keyword arguments) from the old invocation style (using positional args).

You interpret the current implementation correctly, except for assuming "**permitted** list." This has nothing to do with what's permitted; it's just to detect whether you're using the new method signature or the old one.

Restated with clearer intent:
```ruby
def process_with_kwargs(http_method, path, *args)
  if deprecated_method_signature?(args.first)
    warn_deprecated_process_invocation if args.any?
    process(http_method, path, { params: args[0], headers: args[1] })
  else
    process(http_method, path, *args)
  end
end

NEW_KEYWORD_ARGUMENTS = %i(params headers env xhr as)
def deprecated_method_signature?(first_arg)
  !first_arg.respond_to?(:keys) || first_arg.keys.none? { |k| k.in? NEW_KEYWORD_ARGUMENTS }
end
```

So we're checking for the inverse of what you're expecting: the _presence_ of _any_ of the new-style keyword arguments means we _aren't_ using deprecated positional args.

**Comment by akozhemiakin** [comment] 2016-05-30 23:42
My interpretation is largely based on the deprecation message shown when ```kwarg_request?``` returns false.

```ruby
def process_with_kwargs(http_method, path, *args)
  if kwarg_request?(args)
    process(http_method, path, *args)
  else
    non_kwarg_request_warning if args.any?
    process(http_method, path, { params: args[0], headers: args[1] })
  end
end

...

def non_kwarg_request_warning
  ActiveSupport::Deprecation.warn(<<-MSG.strip_heredoc)
    ActionDispatch::IntegrationTest HTTP request methods will accept only
    the following keyword arguments in future Rails versions:
    #{REQUEST_KWARGS.join(', ')}

   ...
end
```

You see? "**will accept only the following keyword arguments**"

**Comment by jeremy** [comment] 2016-05-31 00:53
Good catch. The deprecation warning is brief to the point of misleading. It's meant to communicate "The `#{http_method}` method now uses keyword arguments. Please switch from `#{http_method}(action, parameters, session, flash)` to `#{http_method}(params: …, session: …, flash: …)`."

**Comment by akozhemiakin** [comment] 2016-05-31 13:05
Also, if expect it to work like you described, the implementation is still wrong

> If we switch to whitelisting exact keyword args then we won't be able to override+super #process with our own keyword args. We'd need to override get/post/…/xhr individually.

And now try to invoke some request method with extra attribute, like this

```ruby
get articles_path, my_cutsom_arg: :foo
```

... and you will get deprecation warning, because of this chunk:

```ruby
... & args[0].keys.any? { |k| REQUEST_KWARGS.include?(k) }
```

**Comment by akozhemiakin** [comment] 2016-05-31 16:24
@jeremy Also I'm leaning towards the idea that you are right and we should allow arbitrary args to be passed to the request functions. Anyway, I see no harm in it.

So I propose the following:

Refactor ```kwarg_request?``` like this
```ruby
def kwarg_request?(args)
  args[0].respond_to?(:keys)
end
```

Refactor ```process_with_kwrags``` like this (a cosmetic change just to make it less cryptic)
```ruby
def process_with_kwargs(http_method, path, *args)
  if kwarg_request?(args)
    process(http_method, path, *args)
  elsif args.any?
    non_kwarg_request_warning
    process(http_method, path, { params: args[0], headers: args[1] })
  else
    process(http_method, path)
  end
end
```

Refactor deprecation message
```ruby
def non_kwarg_request_warning
  ActiveSupport::Deprecation.warn(<<-MSG.strip_heredoc)
    ActionDispatch::IntegrationTest HTTP request methods will accept only
    the keyword arguments in future Rails versions. Look at the following
    examples for better understanding:

    Wrong form:
    get '/profile', { id: 1 }, { 'X-Extra-Header' => '123' }

    Correct form:
    get '/profile', params: { id: 1 }, headers: { 'X-Extra-Header' => '123' }
  MSG
end
```

If everyone are Ok with this solution, I'll prepare the new pull request.

**Comment by jeremy** [comment] 2016-05-31 17:59
Looks good.

Note that `args[0]` will respond to `:keys` for deprecated invocations, too: `get foo_path, bar: 'value'` will have `{ bar: 'value' }` as `args[0]`, yet it isn't using any of the new keyword arguments. That's why we checked whether you're passing at least one of the new args.

Wrong/Correct → Old/New for the deprecation warning :)

**Comment by robmathews** [comment] 2016-06-23 20:49
Not sure if this is the correct place to comment, but google lead me here, so I'll comment here and happily move somewhere else if directed.

Why are we making this change? I understand that it is slightly cleaner, but out here in the real world, where folks like me manage a large application, changes like this add no value and a lot of work to the upgrade process. We've got more than 5000 tests, and we'll have to change every controller test across a dozen branches. And what's the value? "easier to understand"? It's pretty debatable, that one - if someone hasn't memorized the parameter order by now, they need a different career.

As I said, perhaps is the wrong place to comment, please feel free to direct me to the right place.

**Comment by akozhemiakin** [comment] 2016-06-23 20:55
@robmathews 
If I understand you right, the change you are talking about (you are talking about moving from ordered parameters to keyed arguments, right?) has already been made. So yes, this issue is not dedicated to this already applied change.

**Comment by robmathews** [comment] 2016-06-23 21:01
I understand. Where would you suggest I raise the issue instead?

**Comment by akozhemiakin** [comment] 2016-06-23 21:05
@robmathews
I think it would be appropriate to just post your considerations as a separate issue to the current repository :) (so I have not checked if something similar may be already here)

**Comment by robmathews** [comment] 2016-06-23 22:03
@akozhemiakin Thank you, kind sir.

**Comment by kaspth** [comment] 2016-06-26 20:02
@robmathews sorry, but we're far over the debate since the change has been merged in months ago and 5.0.0 has entered the RC phase.

@akozhemiakin there's still time to improve the deprecation in 5.0.1 if you want to open a PR with your proposed version: https://github.com/rails/rails/issues/24864#issuecomment-222742228 😁

**Comment by akozhemiakin** [comment] 2016-06-26 21:14
@kaspth
The problem is we still do not know how to effectively distinguish between old style request and new style request without confusing false positive or false negative deprecation warnings.

@jeremy perfectly described this problem:
> Note that args[0] will respond to :keys for deprecated invocations, too: get foo_path, bar: 'value' will have { bar: 'value' } as args[0], yet it isn't using any of the new keyword arguments. That's why we checked whether you're passing at least one of the new args.

It is all because both new style invocation and old style invocation take hash as a first argument.

**Comment by kaspth** [comment] 2016-06-27 19:08
How about this?

```ruby
def process_with_keywords(http_method, path, *args)
  if keyworded_request?(*args)
    process(http_method, path, *args)
  else
    non_kwarg_request_warning if args.any?
    process(http_method, path, { params: args[0], headers: args[1] })
  end
end

# Use `:none` to determine unpassed keywords. Swallow extra options with double splat.
def keyworded_request?(params: :none, headers: :none, env: :none, xhr: :none, as: :none, **)
  [ params, headers, env, xhr, as ].any? { |arg| arg != :none }
end
```

I think that should also let @jeremy override `process` and merge in the authorization:

```ruby
def process(http_method, path, user:, **options)
  options[:headers] ||= {}
  options[:headers]['Token-Authorization'] = user.token

  super(http_method, path, **options)
end
```

Also curious why we've chosen to have `process_with_kwargs` capture `*args` and not `**options` it doesn't seem like there'd be more positional args after the method and path ¯\_(ツ)_/¯.

**Comment by kaspth** [comment] 2016-08-13 19:08
I've pushed some hopefully clearer deprecation messages: https://github.com/rails/rails/compare/3a4f1e7...8c45e29

I was thinking about moving the deprecation into a prepended module that overrides process... and tried it out. But then our tests using `assert_called_with` for non-deprecated code won't really run process, it will just pass the args on to a mock. So those would have to be changed.

I also tried overriding process manually. It's a pain! You have to subclass `ActionDispatch::Integration::Session` and override the `integration_session` method. So I doubt most people are doing that to add their own keywords. They are probably more likely to override `get` and friends.

**Comment by kaspth** [comment] 2016-08-13 19:10
I'm not sure what else we can do given the false positive and negative nature of this — if anybody has any ideas do tell! 

I'm going to give this a close until then.

**Closed by kaspth** 2016-08-13 19:10 UTC
Labels: actionpack, attached PR, With reproduction steps
