### ISSUE TITLE
Duplicate records returned when using ActiveRecord::Associations::Preloader on preloaded records.

### ISSUE THREAD

**Issue by jeremy-israel** [rails/rails#39035] opened 2020-04-24 13:54 UTC
### Steps to reproduce
Fetch some records with `.preload`. Select a subset of those records and use `ActiveRecord::Associations::Preloader` to preload another association.

Detailed steps + code to reproduce : https://github.com/jeremy-israel/preload-duplicates-rails-6/blob/master/problem_description_and_steps_to_reproduce.md

### Expected behavior
We're expecting has_many association not to retrieve any duplicate records.

### Actual behavior
Duplicate records are returned.

### System configuration
**Rails version**: `6.0.2.2`

**Ruby version**: `ruby 2.6.6p146`

**Comment by jonathanhefner** [comment] 2020-04-24 22:10
I believe this is a duplicate of #35195, which was closed by 5f9e05048d409b9c3fb35a3620fe361fb03dd4e1.  However, the reproduction script from #35195 fails with Rails 6.0.0 (which included 5f9e05048d409b9c3fb35a3620fe361fb03dd4e1), 6.0.2.2, and current master.

@kamipo Considering your comment about private API and guaranteed behavior in 5f9e05048d409b9c3fb35a3620fe361fb03dd4e1, should this be closed or fixed?

**Comment by alipman88** [comment] 2020-04-28 23:25
I believe this issue may be demonstrated through the public API, per possibly-related issue #39073 - I'm observing what appears to be a bug/regression introduced between Rails 5.2.4.2 and the current master.

**Comment by jonathanhefner** [comment] 2020-05-08 03:52
Fixed by #39156.

**Closed by jonathanhefner** 2020-05-08 03:52 UTC
