### ISSUE TITLE
`rails new` reports files that are not actually created

### ISSUE THREAD

**Issue by kazzix14** [rails/rails#45269] opened 2022-06-05 14:46 UTC
### Steps to reproduce

```ruby
rails new . --database=postgresql --no-skip-git --no-skip-keeps --no-skip-action-mailer --skip-mailbox --skip-action-text --no-skip-active-record --skip-active-job --no-skip-active-storage --skip-action-cable --skip-asset-pipeline --skip-javascript --skip-hotwire --skip-jbuilder --skip-test --skip-system-test --no-skip-bootsnap --api --skip-bundle --force --pretend
```

### Expected behavior
it prints only files that are going to be created.

### Actual behavior
It prints files that are not going to be created as I passing `--skip-*` parameters.  
When I remove `--pretend` from my options, it prints the same thing although it does not create those files actually.

```
       force  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
       force  .gitignore
      create  .gitattributes
       force  Gemfile
         run  git init from "."
Reinitialized existing Git repository in /usr/local/app/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/puma.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
       exist  public
   identical  public/404.html
   identical  public/422.html
   identical  public/500.html
   identical  public/apple-touch-icon-precomposed.png
   identical  public/apple-touch-icon.png
   identical  public/favicon.ico
   identical  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
       exist  vendor
   identical  vendor/.keep
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  app/assets
      remove  lib/assets
      remove  tmp/cache/assets
      remove  app/helpers
      remove  test/helpers
      remove  app/views/layouts/application.html.erb
      remove  public/404.html
      remove  public/422.html
      remove  public/500.html
      remove  public/apple-touch-icon-precomposed.png
      remove  public/apple-touch-icon.png
      remove  public/favicon.ico
      remove  config/initializers/assets.rb
      remove  app/assets/config/manifest.js
      remove  app/assets/config
      remove  app/assets/stylesheets/application.css
      remove  app/jobs
      remove  app/javascript/channels
      remove  app/channels
      remove  test/channels
      remove  config/initializers/content_security_policy.rb
      remove  config/initializers/permissions_policy.rb
      remove  config/initializers/new_framework_defaults_7_0.rb
```

### System configuration
**Rails version**:
```
> rails version
Rails 7.0.2.4
```
**Ruby version**:
```
> ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
```

**Comment by skipkayhil** [comment] 2022-06-11 19:34
Hey @kazzix14, thanks for the report. Am I right in thinking that the file output is as you expect and its only the console output that is confusing? I think the output is caused by how the generator is implemented, which is that it copies all the files in https://github.com/rails/rails/tree/471ab2347fc8941ead6d9f95ef32c6686d706924/railties/lib/rails/generators/rails/app/templates before processing options and removing any files that aren't necessary. I'm hesitant to call this a bug but I can understand why it may be a bit confusing

**Comment by thiagofm** [comment] 2022-06-15 13:29
I've reproduced the same issue. It is real.

**Comment by thiagofm** [comment] 2022-06-16 14:46
If there's the interest of such feature(of not creating/removing files straight away). I'd be up to write it, right now we delegate all those calls directly to Thor(which in return use FileUtils). You'd need to accumulate those file additions and removals somewhere and apply all of those operations at once.

Honestly thought, I see it is as bit complex, hence I don't believe it is the right way to go.  @skipkayhil any thoughts?

**Comment by yahonda** [comment] 2022-06-20 02:37
As long as `rails new` with any --skip options finally creates files as expected, I prefer not to make any changes.

**Comment by skipkayhil** [comment] 2022-06-20 04:44
> As long as `rails new` with any --skip options finally creates files as expected, I prefer not to make any changes.

I had the same thought at first, but I've thought some more about it and maybe there's some room for improvement. What would you think about more frameworks having `active_storage:install` type tasks that generate their necessary files? I think that would both help to solve this issue and provide a better experience for users that generate an app without some frameworks and later want to add them.

**Comment by yahonda** [comment] 2022-06-20 07:28
Thanks for the reply. When Rails provides a new features like "Action Something", adding new features for the existing application like `action_something:install`  should be a good idea. On the other hand I prefer not to change how to install existing features.

**Comment by kazzix14** [comment] 2022-06-25 14:41
Sorry for my late response, and thank you for your responses.

> Am I right in thinking that the file output is as you expect and it's only the console output that is confusing?

Yes. I hadn't noticed that there are removed files also in the output until I read this.

> It doesn't only print the files that are created, but also the files and directories that are removed(check the end of the output).
>
> Is there any file that you have seen that is shown as created, isn't shown as deleted and isn't present in the Rails App that you could make an example?

No. I was wrong as I thought these files are what is created or modified. There are no differences between console output and actual files.
After reading thiagofm's explanation, I understood what's happening in `rails new`. 
I think it's reasonable to print files that are created in initialization, even though they are removed later.

**Comment by yahonda** [comment] 2022-06-26 04:15
Thanks for the update. Let me close this issue because the original issue/question has been resolved.

**Closed by yahonda** 2022-06-26 04:15 UTC
Labels: railties
