### ISSUE TITLE
Stop using CoffeeScript in Rails Guides

### ISSUE THREAD

**Issue by lacostenycoder** [rails/rails#38514] opened 2020-02-19 16:57 UTC
In 2020 is anybody still using CoffeeScript??  Jeez. Why can't we at least update the guides to show examples for regular JS or ES6? Wouldn't that make sense since https://github.com/rails/rails/pull/33079 ?

**Comment by eugeneius** [comment] 2020-02-19 17:01
This is a duplicate of https://github.com/rails/rails/issues/37742. Jeez!

**Closed by eugeneius** 2020-02-19 17:01 UTC
