### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished when migration is running with replica

### ISSUE THREAD

**Issue by artursmolin** [rails/rails#49075] opened 2023-08-29 09:53 UTC
### Steps to reproduce

database.yml
```
staging: &staging
  primary: &staging_primary
    <<: *default
    host: <%= Rails.application.credentials.dig(:database, :host) %>
    database: <%= Rails.application.credentials.dig(:database, :dbname) %>
    username: <%= Rails.application.credentials.dig(:database, :username) %>
    password: <%= Rails.application.credentials.dig(:database, :password) %>
    port: <%= Rails.application.credentials.dig(:database, :port) %>
  primary_replica:
    <<: *staging_primary
    host: <%= Rails.application.credentials.dig(:database, :replica_host) %>
    replica: true
```    

application_record.rb
```
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  connects_to database: { writing: :primary,
                          reading: :primary_replica }
end
```
rails db:migrate
```
...

== 20211202122216 AddFieldAttachmentsMapToCards: migrating ====================
-- add_column(:cards, :field_attachments_map, :jsonb, {:default=>{}})
   -> 0.0045s
== 20211202122216 AddFieldAttachmentsMapToCards: migrated (0.0045s) ===========

== 20211206163126 AddLocaleToUsers: migrating =================================
-- add_column(:users, :locale, :string)
   -> 0.0009s
== 20211206163126 AddLocaleToUsers: migrated (0.0010s) ========================

== 20211211164209 AddPositionToDecks: migrating ===============================
-- add_column(:decks, :position, :integer)
   -> 0.0028s
== 20211211164209 AddPositionToDecks: migrated (0.0363s) ======================

rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

connection is closed


Caused by:
ActiveRecord::ConnectionNotEstablished: connection is closed


Caused by:
PG::ConnectionBad: connection is closed


Caused by:
ActiveRecord::ConnectionNotEstablished: connection is closed


Caused by:
PG::ConnectionBad: connection is closed

Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

### Expected behavior

Migration should go smooth even with replica. 
Without replica setup everything is going ok.

### Actual behavior

Migration fails, PG::ConnectionBad: connection is closed.

### System configuration
**Rails version**: 7.0.7.2

**Ruby version**: 3.2.0

**Comment by eileencodes** [comment] 2023-08-29 13:02
Hi @artursmolin please provide an application that reproduces the issue. We are not able to debug issues without a reproduction. However I believe this is fixed in main already via https://github.com/rails/rails/pull/45450, but I'm not able to backport the change to 7.0.x because it's too major.

**Comment by eileencodes** [comment] 2023-08-29 13:17
@paulreece I've seen this report a lot, and I don't think that's the issue. Especially locally, the migrations don't run on the replicas, they share a database. Also if it was a username/password issue the error wouldn't be ConnectionNotEstablished. I'm pretty sure that the last migration is accessing a closed connection, but I would need to see the contents to be 100% sure of that.

**Comment by paulreece** [comment] 2023-08-29 13:22
That makes sense!

**Closed** 2023-09-12 13:34 UTC
Labels: activerecord, more-information-needed
