### ISSUE TITLE
ActionView translate regression since 4.1 when default is missing

### ISSUE THREAD

**Issue by semaperepelitsa** [rails/rails#19967] opened 2015-04-30 21:00 UTC
Here is my test case:

```ruby
case ARGV[0]
when '4.2'
  gem "actionview", "4.2.1"
when '4.1'
  gem "actionview", "4.1.10"
when '4.0'
  gem "actionpack", "4.0.13"
else
  raise KeyError
end

gem "minitest"
require "action_view"
require "active_support/all"
require "i18n"
require "minitest/autorun"

I18n.enforce_available_locales = false
I18n.backend.store_translations(:en, hello: "Hello")

class TranslateTest < Minitest::Unit::TestCase
  include ActionView::Helpers::TranslationHelper

  def test_ok
    assert_equal "Hello", t(:hello)
  end

  def test_missing
    assert_equal "<span class=\"translation_missing\" title=\"translation missing: en.greeting\">Greeting</span>", t(:greeting)
  end

  def test_default
    assert_equal "Hello", t(:greeting, default: :hello)
  end

  def test_default_missing
    assert_equal "<span class=\"translation_missing\" title=\"translation missing: en.welcome\">Welcome</span>", t(:greeting, default: :welcome)
  end
end
```

The last test is failing since version 4.1.

```
> ruby -w test.rb 4.0
Run options: --seed 46515

# Running tests:

....

Finished tests in 0.007289s, 548.7721 tests/s, 548.7721 assertions/s.

4 tests, 4 assertions, 0 failures, 0 errors, 0 skips
```

```
> ruby -w test.rb 4.1
MiniTest::Unit::TestCase is now Minitest::Test. From test.rb:21:in `<main>'
Run options: --seed 473

# Running:

..E.

Finished in 0.019266s, 207.6196 runs/s, 155.7147 assertions/s.

  1) Error:
TranslateTest#test_default_missing:
I18n::MissingTranslationData: translation missing: en.welcome
    /Users/sema/.gem/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:311:in `handle_exception'
    /Users/sema/.gem/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:161:in `translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.1.10/lib/action_view/helpers/translation_helper.rb:68:in `translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.1.10/lib/action_view/helpers/translation_helper.rb:72:in `rescue in translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.1.10/lib/action_view/helpers/translation_helper.rb:38:in `translate'
    test.rb:37:in `test_default_missing'

4 runs, 3 assertions, 0 failures, 1 errors, 0 skips
```

```
> ruby -w test.rb 4.2
MiniTest::Unit::TestCase is now Minitest::Test. From test.rb:22:in `<main>'
Run options: --seed 19624

# Running:

.E..

Finished in 0.024629s, 162.4102 runs/s, 121.8076 assertions/s.

  1) Error:
TranslateTest#test_default_missing:
I18n::MissingTranslationData: translation missing: en.welcome
    /Users/sema/.gem/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:311:in `handle_exception'
    /Users/sema/.gem/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:161:in `translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/translation_helper.rb:69:in `translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/translation_helper.rb:39:in `translate'
    test.rb:38:in `test_default_missing'

4 runs, 3 assertions, 0 failures, 1 errors, 0 skips
```

Is this a feature or a bug?

**Comment by imanel** [comment] 2015-05-03 16:18
Looks like between 4.0 and 4.1 new options [was introduced](https://github.com/rails/rails/commit/c1d5477b63e73dadec9f284fa55ec22d81f3bf36#diff-cda406008ce3935156e8ba173b1e9837R62) that allows enabling or disabling raise in case of missing translation, with false as default.

But then something [went horribly wrong](https://github.com/rails/rails/commit/dc09322a1db72e86d1bf5070b1d8888ef51f66ed#diff-cda406008ce3935156e8ba173b1e9837R51) and it looks like this option is now always set to `true` in case of fallbacks. You can see some discussion about it in #13832.

In theory #17676 was supposed to fix it, but from what I can see it's not doing it in this case. You could fix it by adding `:rescue_format => nil`, but that's all I can see in there... My theory is that correct line should look like this:

```ruby
raise_error = options[:raise] || options[:rescue_format] || ActionView::Base.raise_on_missing_translations
options[:raise] = ActionView::Base.raise_on_missing_translations
```

**Comment by matthewd** [comment] 2015-05-03 16:45
The problem is that (per the comment above that assignment) `options[:raise]` is being set for the underlying call to `I18n.translate` -- we need that to raise, so that we'll end up in [the right place](https://github.com/rails/rails/blob/71669370ae789f547311821ab880b0f19682b405/actionview/lib/action_view/helpers/translation_helper.rb#L84-L92).

However, having mangled `options` for that purpose, we're then reusing it [when we recurse](https://github.com/rails/rails/blob/71669370ae789f547311821ab880b0f19682b405/actionview/lib/action_view/helpers/translation_helper.rb#L86).

Thus, I suspect we want to add `raise: raise_error` to the merged hash on that line.

**Comment by imanel** [comment] 2015-05-03 18:30
#19998 should fix this problem.

**Closed** 2015-05-04 21:23 UTC
