### ISSUE TITLE
Scope loads all results if the result of the scope is nil (5.0.0.alpha)

### ISSUE THREAD

**Issue by tommyblue** [rails/rails#21882] opened 2015-10-06 09:56 UTC
I'm using rails 5.0.0.alpha (c468d7fedd88e2474fd74e804a954a154674c8a0) and I have a problem with a simple scope query.

In the `User` model I created this scope to get a user with an associated token:

```ruby
class User < ActiveRecord::Base
  has_many :auth_tokens
  scope :by_token, -> (token) { joins(:auth_tokens).where(auth_tokens: { token: token }).first }
end
```

If I ask for a user with `@user = User.by_token(token)` I get the correct user if the token is correct, but I get all the users if the token is wrong.

The console shows this weird behaviour.

With **correct** token:

```
CACHE (0.0ms)  SELECT  "users".* FROM "users" INNER JOIN "auth_tokens" ON "auth_tokens"."user_id" = "users"."id" WHERE (auth_tokens.token = 'coorrect_token') ORDER BY "users"."id" ASC LIMIT 1
```

With **wrong** token:

```
CACHE (0.0ms)  SELECT  "users".* FROM "users" INNER JOIN "auth_tokens" ON "auth_tokens"."user_id" = "users"."id" WHERE (auth_tokens.token = 'wrong_token') ORDER BY "users"."id" ASC LIMIT 1

CACHE (0.0ms)  SELECT "users".* FROM "users"
```

If the first query returns `nil`, then the second query is made and all the users are loaded.
Why rails do this? Is it a bug?

If I transform the scope in a class method the behaviour is correct:

```ruby
def self.by_token(token)
  return self.joins(:auth_tokens).where(auth_tokens: { token: token }).first
end
```

**Comment by senny** [comment] 2015-10-06 18:25
In the case of Active Record a `scope` is something that returns a `Relation`. I don't think the `scope` method should return something other than a `ActiveRecord::Relation` object. Otherwise it won't be composable with other scopes.

That aside, I'm not sure why a `SELECT *` is performed. We should investigate at least the cause of this query.

/cc @rafaelfranca @sgrif

**Comment by matthewd** [comment] 2015-10-06 18:29
This sounds like expected behaviour to me. Does 4.2 behave differently?

**Comment by senny** [comment] 2015-10-06 18:40
@matthewd is the behavior of a scope returning `nil` documented somewhere? I didn't find anything in [the api docs](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html#method-i-scope)

**Comment by rafaelfranca** [comment] 2015-10-06 20:18
I don't know if I'd call it expected behavior but it is how it is implemented now. If scope return `nil` we use `all` so the scope is still composable. https://github.com/rails/rails/blob/cfb371e96a2789790359ec1db779df490fd253d6/activerecord/lib/active_record/scoping/named.rb#L158

I think we should not even allow an scope to return `nil`, but I'm not sure it is possible since we only know what an scope return when evaluating it.

**Comment by senny** [comment] 2015-10-06 20:29
@rafaelfranca thanks for the reference.

Guess we can close this up then.

Since this is not immediately obvious behavior we could add a NOTE: to the docs of `scope`. @tommyblue would you mind sending a PR?

**Comment by sgrif** [comment] 2015-10-06 22:24
Is there any reason for `scope` to continue to survive at this point? Does it provide anything that a class method doesn't? This sort of gotcha is surprising and alarming, especially if you consider new developers. Maybe we should consider deprecating `scope`.

**Comment by rafaelfranca** [comment] 2015-10-06 22:34
Yes -> http://blog.plataformatec.com.br/2013/02/active-record-scopes-vs-class-methods/.

I don't see any good reason to deprecate it. Gotcha that are surprising and alarming will also happen even with class methods. We are missing documentation around this behavior (that by the way is in that blog post) and only that.

**Comment by sgrif** [comment] 2015-10-06 23:14
So basically the only difference is this specific behavior? ¯\_(ツ)_/¯ I'd honestly prefer if we made people do `else all`, since it's much more explicit to future readers of the code. But you're right, it'd be too painful to deprecate at this point.

**Comment by rafaelfranca** [comment] 2015-10-06 23:27
To be fair, I always wanted to deprecate it but I know some people like it, and the pain to upgrade is not worth.

**Comment by sgrif** [comment] 2015-10-06 23:35
I'd argue for maybe soft deprecating it at least? (Removing all references to it in the documentation). If nothing else I'll just add this to my list of things that you may see but should probably never use that I give my students.

**Comment by tommyblue** [comment] 2015-10-07 07:55
So the problem in my code is that I use `.first` at the end of the scope, which returns `nil` if the previous query returns an empty result. And `scope` at that point returns `.all`.
I understand the error (I'm not returning an `ActiveRecord::Relation`), but it's all but the expected result to obtain a `.all` from the scope when the result is `nil` :/
Shouldn't it return an empty relation or raise an error if the return value of the scope isn't an `ActiveRecord::Relation`?

@senny I'll add a paragraph about this behaviour in the doc of the `scope` method here: https://github.com/rails/rails/blob/c1deb81cd005d7091b680ec2089b9b8dba41325f/activerecord/lib/active_record/scoping/named.rb#L136
Ok?

**Comment by al2o3cr** [comment] 2015-10-07 21:57
@tommyblue This has come up before. See also https://github.com/rails/rails/issues/19249, https://github.com/rails/rails/issues/14256, and https://github.com/rails/rails/pull/21465.

**Comment by sgrif** [comment] 2015-10-07 22:00
(Again just saying, this is evidence of a flawed API and we should deprecate it. :P)

**Comment by rafaelfranca** [comment] 2015-10-07 22:23
As already was said to me once:

> As a general rule, I don’t find “people might cut themselves with a sharp knife if they wield it wrong” as a good direction for design. Rails should be full of both spoons, forks, and also some sharp knifes.

**Comment by sgrif** [comment] 2015-10-07 22:27
To take the metaphor slightly too far, there's a difference between a sharp knife, and a knife which cleverly disguises the blade as a handle. Anyway I don't feel super strongly about it and will stop now.

**Comment by rafaelfranca** [comment] 2015-10-07 22:31
hahaha, you gave the same response that I the time I got this answer https://github.com/rails/rails/issues/18847#issuecomment-74112286

**Comment by tommyblue** [comment] 2015-10-08 08:39
@senny is the PR ok?

**Comment by senny** [comment] 2015-10-08 08:44
@tommyblue thanks for the PR. I'll leave this one up to @rafaelfranca. Personally I'm leaning towards what @sgrif is saying and deprecate that behavior but it might be to much of a change for the benefit. Let's wait for @rafaelfranca

**Comment by rafaelfranca** [comment] 2015-10-08 17:21
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Closed by rafaelfranca** 2015-10-08 17:21 UTC
Labels: activerecord, docs

**Comment by pooja-mane** [comment] 2016-08-11 09:18
I have a same issue related to scope.this is my code 
scope :current, -> { where.(current: true).try(:first) }
when i run code for model then it gives me correct output, but for particular records which contains current as false value it return all records whichever it has.
I wrote class method instead of scope like this
def self.current
where(current: true).try(:first)
end
then it works correctly.
I have a question scope internally gets converted into class method then why does it happen if write a try(:first) in scope and in class method it works properly.

**Comment by rafaelfranca** [comment] 2016-08-12 23:33
The answer is already in this thread, please read it.
