### ISSUE TITLE
Cache-Control header should be lower-case for static files with Rack 3

### ISSUE THREAD

**Issue by zarqman** [rails/rails#49489] opened 2023-10-04 20:14 UTC
Responses from `ActionDispatch::Static` can return a mixed-case Cache-Control header on Rails 7.1 with Rack 3.

a) If `Cache-Control` is specified as part of `environments/*.rb` (which is the default on `development` and `test`), its casing is passed through as-is. I don't know if generators for `rails new` and `app:update` should be aware of Rack 3 and update this to lower-case or if it should be modified to lower-case during rails initialization or for each static response. 

Alternatively, the default could just be switched to lower-case since Rack 3 is likely to be pulled in for Rails 7.1 apps--not sure if that's safe if an app ends up running Rack 2 (perhaps because some other gem constrains it).

b) Related, `Content-Length` appears to be mixed-case all the time (both static files and normal controller actions).

### Steps to reproduce

Make sure the app is configured to use Rack 3.

Run `rails dev:cache` if not already enabled (to expose `cache-control` when in `development` mode):
```bash
$ rails dev:cache
Development mode is now being cached.
```

### Expected behavior

```bash
$ curl -I http://localhost:3000/robots.txt
HTTP/1.1 200 OK
last-modified: Sun, 18 Dec 2022 07:14:50 GMT
content-type: text/plain
cache-control: public, max-age=172800
content-length: 150
```

And, if (a) should manage the case of `cache-control` directly in `config/environments/{development,production,test}.rb`, `rails app:update` should offer this:

```ruby
  # example for development.rb
  config.public_file_server.headers = {
    "cache-control" => "public, max-age=#{2.days.to_i}"
  }
```

### Actual behavior

Note the case of the final 2 lines.
```bash
$ curl -I http://localhost:3000/robots.txt
HTTP/1.1 200 OK
last-modified: Sun, 18 Dec 2022 07:14:50 GMT
content-type: text/plain
Cache-Control: public, max-age=172800
Content-Length: 150
```

And again, depending on (a):

```ruby
  # example for development.rb
  config.public_file_server.headers = {
    "Cache-Control" => "public, max-age=#{2.days.to_i}"
  }
```

### System configuration
**Rails version**: 7.1.0.rc2

**Ruby version**: 3.2.2

**Rack version**: 3.0.8

**Comment by rafaelfranca** [comment] 2023-10-04 23:52
I'm not sure what is the problem here. Browsers know how to deal with mixed case header names. I know we could keep it consistent, but well, Rack makes that almost impossible without making Rails code a mess.

Does returning mixed case cause any bad behavior?

**Comment by skipkayhil** [comment] 2023-10-05 02:02
This seems like something we should specifically call out in the upgrading guide. For new apps which will get Rack 3 immediately, maybe we should update the `development.rb` template? Since it's only development, maybe we wait until Rack < 3 is dropped to change?

> Related, `Content-Length` appears to be mixed-case all the time (both static files and normal controller actions).

Let me see if I can track this down, I was able to reproduce

**Comment by byroot** [comment] 2023-10-09 16:53
Since it was established this isn't caused by Rails, closing.

**Closed by byroot** 2023-10-09 16:53 UTC
Labels: actionpack

**Comment by zarqman** [comment] 2023-10-09 18:07
While Rails may not be the source of mixed-case for `content-length`, I believe Rails is the cause of mixed-case for `cache-control` as the default environment templates directly specify `{"Cache-Control" => ...}`.

**Comment by byroot** [comment] 2023-10-09 18:35
Then please open a PR for that if it actually cause problems.
