### ISSUE TITLE
some api docs pages have unescaped html in meta tag content attributes

### ISSUE THREAD

**Issue by bughit** [rails/rails#30801] opened 2017-10-04 18:25 UTC
http://api.rubyonrails.org/v4.2/classes/ActiveRecord/Base.html

```html
    <meta name="description" content="<h1 id="class-ActiveRecord::Base-label-Active+Record">Active Record</h1>  Active Record objects don&#39;t specify their attributes directly, but rather infer them from the table definition with which .">
    <meta property="og:description" content="<h1 id="class-ActiveRecord::Base-label-Active+Record">Active Record</h1>  Active Record objects don&#39;t specify their attributes directly, but rather infer them from the table definition with which .">
```

**Comment by akshay-vishnoi** [comment] 2017-10-06 21:16
![screen shot 2017-10-07 at 2 45 09 am](https://user-images.githubusercontent.com/1928523/31298848-a7a2dcd6-ab09-11e7-8e35-d139e3d9e25b.png)
Confirmed. Where can I fix this?

**Comment by matthewd** [comment] 2017-10-06 21:56
Looks like the recent 4.2.10 release generated using the new version of sdoc... I'm not sure whether it intended to do that. (cc @robin850 and/or @fxn)

**Comment by fxn** [comment] 2017-10-06 22:14
On my phone, maybe the Gemfile does not have a constraint, or is too weak? If that was the case, the docs generator has a patching phase and we could regenerate.

**Comment by fxn** [comment] 2017-10-07 07:17
@matthewd looks like it comes from [this commit](https://github.com/rails/rails/commit/2a1c91bc08d04102d788ce8c5e26d4cca02eb83d).

Historically we have changed designs only on edge, without backporting. For example [this is the API of Rails 3](http://api.rubyonrails.org/v3.0/). It is a mix of consistency within the branch theme, and also avoiding the work to backport adaptations, though if someone wants to do the job I gues is fine too.

**Comment by robin850** [comment] 2017-10-07 20:34
Hey there !

That's my bad actually ; [this commit](https://github.com/zzak/sdoc/commit/8b490a7ef92d3ded47ef86a565fbeddb323f9ce7) introduced this bug but it has been fixed with https://github.com/zzak/sdoc/commit/b811ffae3ced3677f436309de6ab9634e8c52365. We didn't release a version with this fix because there we some concerns to address with the font size and the right margin on the "new theme" before releasing a new version. I hope to cut a release very soon, sorry for the inconvenience.

@fxn : Since documentation is not always the main concern in this repository (what I can totally understand), what do you think about maintaining the documentation code for each series in [rails/rails-docs-server](https://github.com/rails/rails-docs-server) ? This would simplify the generation process plus we would have to explicitly change things (well, the main problem is dependencies here) on the `rails-docs-server` side rather than in this repository. We duplicate a bit things but since doc generation doesn't drastically often change, it shouldn't be a burden.

What do you think ?

**Comment by fxn** [comment] 2017-10-09 19:50
I am going to downgrade in 4-2-stable then.

@robin850 not sure I understand the proposal... can you elaborate please?

**Comment by fxn** [comment] 2017-10-09 21:12
Fixed in production. Thanks!

**Comment by fxn** [comment] 2017-10-09 21:13
@robin850 closed the issue because the problem is fixed, but feel free to followup with that idea.

**Closed by fxn** 2017-10-09 21:12 UTC
