### ISSUE TITLE
Rails 6.1.7 ActiveRecord scope with argument breaks in ruby 3.2.0

### ISSUE THREAD

**Issue by rockorequin** [rails/rails#46934] opened 2023-01-09 03:18 UTC
### Steps to reproduce
In irb:

```
gem 'rails', '=6.1.7'
require 'active_record'
class Test < ActiveRecord::Base
   scope :test, ->(arg: nil) {}
end
Test.test(arg: 1)

```

### Expected behavior
The code should not raise an exception. For example, the output using ruby 3.1.3 is:

```
(Object doesn't support #inspect)
 =>
```

### Actual behavior
The code raises an exception using ruby 3.2.0:

```
(irb):3:in `block in <class:Test>': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /home/rocko/.rvm/gems/ruby-3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `instance_exec'
...
```
The error is raised in _exec_scope()  when it tries to execute the code "instance_exec(*args, &block)".

### System configuration
**Rails version**: 6.1.7

**Ruby version**: 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]

**irb version**: 1.6.2

**Comment by nvasilevski** [comment] 2023-01-09 13:58
I can't seem to be able to reproduce it on `main` or `7.0.4` May I ask you to double check that on a more recent version of Rails? I'm afraid Rails 6 only accepts security patches so it wont be fixed unless reproducible on Rails 7

**Comment by rockorequin** [comment] 2023-01-10 02:29
You're right, it works in 7.0.4. Rails 7.0.4 Rails 7.0.4 uses the triple-dot syntax to accept arguments to _exec_scope and pass them to instance_exec, and making this change in 6.1.7 fixes the issue, ie:

```
    def _exec_scope(...) # :nodoc:
      @delegate_to_klass = true
      _scoping(nil) { instance_exec(...) || self }
    ensure
      @delegate_to_klass = false
    end
```

Do you know if there are deliberate changes in ruby 3.2.0 that cause instance_exec(*args, &block) to fail? I haven't found any compatibility notes indicating this yet.

**Comment by brenoperucchi** [comment] 2023-01-11 00:11
I have the same issue after upgrading from ruby 2.7.7 to ruby 3.2.0.

```ruby
[19] pry(#<Trace>)> orders.create_with(store: self.store).find_or_create_by(content_id: ticket)
ArgumentError: wrong number of arguments (given 1, expected 0)
from /.../gemsets/rails61/gems/activerecord-6.1.7/lib/active_record/suppressor.rb:43:in `save'
[20] pry(#<Trace>)>

```

**Comment by daande** [comment] 2023-01-11 00:25
> You're right, it works in 7.0.4. Rails 7.0.4 uses the triple-dot syntax to accept arguments to _exec_scope and pass them to instance_exec, and making this change in 6.1.7 fixes the issue, ie:
> 
> ```
>     def _exec_scope(...) # :nodoc:
>       @delegate_to_klass = true
>       _scoping(nil) { instance_exec(...) || self }
>     ensure
>       @delegate_to_klass = false
>     end
> ```
> 
> Do you know if there are deliberate changes in ruby 3.2.0 that cause instance_exec(*args, &block) to fail? I haven't found any compatibility notes indicating this yet.

I think it’s due to this bug fix  https://bugs.ruby-lang.org/issues/18633

**Comment by rockorequin** [comment] 2023-01-11 02:43
@daande: thanks. I opened an issue at https://bugs.ruby-lang.org/issues/19330 to ask if this is intentional.

@brenoperucchi: your error looks like it is in code that hasn't changed between Rails 6.1.7 and 7.0.4. Are you able to test if you get the same exception in Rails 7.0.4?

**Comment by brenoperucchi** [comment] 2023-01-11 03:22
I have the same error even on Rails 7.0.4 and with ruby-3.2.0

```ruby
[4] pry(#<Trace>)> orders.create_with(store: self.store).find_or_create_by(content_id: ticket)

ArgumentError: wrong number of arguments (given 1, expected 0)
from /~/.rbenv/versions/3.2.0/gemsets/rails704/gems/activerecord-7.0.4/lib/active_record/suppressor.rb:49:in `save'
[5] pry(#<Trace>)> Rails.version
=> "7.0.4"
```

**Comment by brenoperucchi** [comment] 2023-01-11 04:04
Now I  have the same problem with create method. 
Rails 6.17
Ruby 3.1.3


```ruby
#app/models/account.rb
has_many :balances,     dependent: :destroy, autosave: true
has_many :orders,       through: :balances, source: :order,         dependent: :destroy, autosave: true
```


```ruby
[6] pry(#<Trace>)> account.orders.create(trace: self, message: message, content_id: ticket, symbol:instrument, account: account)
ArgumentError: wrong number of arguments (given 1, expected 0)
from /~/.rbenv/versions/3.1.3/gemsets/rails61/gems/activerecord-6.1.7/lib/active_record/suppressor.rb:43:in `save'
[7] pry(#<Trace>)>
```

**Comment by rafaelfranca** [comment] 2023-01-11 23:11
If you are having that error on 6.1 with Ruby 3.1 this isn't a problem in Rails. Make sure you don't have any monkey patch to Rails methods or gems that might have broken this behavior. If you think it is a bug in Rails please 
could you create a reproduction script with this template https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb?

Apart from that, Rails 6.1 might not support Ruby 3.2 right now since it isn't receiving any bug fix releases anymore.

**Closed by rafaelfranca** 2023-01-11 23:11 UTC

**Comment by rockorequin** [comment] 2023-01-13 01:56
Just a note that at https://bugs.ruby-lang.org/issues/19330 they indicated that this *is* intentional and that with ruby 3.2+ for it to not cause an exception you need to specify the args and keywords specifically to avoid the exception (ie "def _exec_scope(*args, **kw, &block) and then call  instance_exec(*args, **kw, &block)") or to specify ruby2_keywords before the def. Or use "..." like Rails 7.0.4 does.
