### ISSUE TITLE
Default behavior of `I18n.t(nil)` is different between development and production

### ISSUE THREAD

**Issue by khiav223577** [rails/rails#40676] opened 2020-11-24 08:54 UTC
### Steps to reproduce

Add `test.rb`
```rb
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", '5.2.4.4'
end

require "minitest/autorun"
require "logger"

I18n.backend.class.include(I18n::Backend::Fallbacks) if Rails.env.production?

class BugTest < Minitest::Test
  def test_i18n_t_with_nil_key
    assert_nil I18n.t(nil)
  end

  def test_i18n_t_with_missing_key
    assert_equal 'translation missing: en.no_this_key', I18n.t('no_this_key')
  end
end
```

### Expected behavior

In our real case, we refactored an API and had it pass all the test cases. But it's broken when being released in production.
It surprised us that the behavior of `I18n.t(nil)` is not consistent between development and production.

We expect `I18n.t(nil)` to return `nil` in production since it return `nil` instead of `"translation missing: en.no key"` in development. Or if `I18n.t(nil)` return `"translation missing: en.no key"` in development, it will make sense that it will also return `"translation missing: en.no key"` in production.

### Actual behavior

In development.
```rb
I18n.t(nil) 
# => nil
```

In production.
```rb
I18n.t(nil) 
# => "translation missing: en.no key" 
```

```
$ RAILS_ENV=production ruby test.rb

# Running:

.F

Failure:
BugTest#test_i18n_t_with_nil_key [test.rb:20]:
Expected "translation missing: en.no key" to be nil.
```

### System configuration
**Rails version**: 
5.2.4.4

**Ruby version**:
2.5.5

**Comment by composerinteralia** [comment] 2020-11-24 20:39
Thanks for the issue. I can reproduce this with [I18n](https://github.com/ruby-i18n/i18n) alone, so I am going to close this issue and suggest opening an issue on that repo instead. The difference is that the I18n [base backend](https://github.com/ruby-i18n/i18n/blob/4709391dceab9096d5988576f93935843023a6ef/lib/i18n/backend/base.rb#L30) returns `nil` for `nil` keys, whereas the [fallbacks backend](https://github.com/ruby-i18n/i18n/blob/4709391dceab9096d5988576f93935843023a6ef/lib/i18n/backend/fallbacks.rb#L60) ends up throwing a `MissingTranslation` exception. The reason this comes up is because, as your reproduction script accurately shows, Rails only uses the fallbacks backend in production by default (I believe this has been true since https://github.com/rails/rails/commit/9a3a4d6aefa7e2ca94340754eb5541bea1783de0).

```rb
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "minitest"
  gem "i18n"
end

require "minitest/autorun"
require "i18n"
require "logger"

I18n.available_locales = [:en]

class BugTest < Minitest::Test
  def test_i18n_t_with_original_backend
    assert_nil I18n.t(nil)
  end

  def test_i18n_t_with_fallback_backend
    original_backend = I18n.backend
    fallback_backend = Class.new(original_backend.class) do
      include I18n::Backend::Fallbacks
    end
    I18n.backend = fallback_backend.new

    assert_nil I18n.t(nil)

  ensure
    I18n.backend = original_backend
  end
end
```

**Closed by composerinteralia** 2020-11-24 20:39 UTC
