### ISSUE TITLE
Undocumented activerecord behavior introduced on 6.1 

### ISSUE THREAD

**Issue by vpereira** [rails/rails#41126] opened 2021-01-15 14:59 UTC
### Steps to reproduce

```
# app/models/project.rb
class Project < ApplicationRecord
  has_many :packages, inverse_of: :project
end
```

```
# app/models/package.rb
class Package < ApplicationRecord
  belongs_to :project, inverse_of: :packages
  validates :name, presence: true, length: { maximum: 200 }
end
```

#### rails 6.0.3.4

```
> project = Project.create(name: 'foo')
> Package.new(project: project)
> project.packages # empty
```

#### rails 6.1.0 or above

```
> project = Project.create(name: 'foo')
> Package.new(project: project)
> project.packages # not empty, the invalid package is assigned to the project
```

### System configuration

**Ruby version**: 2.5 or greater
**Rails version**: 6.10 or greater

I created some automation to test it, the README has some instructions how to run it :)

https://github.com/vpereira/test_in_multiple_rails

**Comment by louim** [comment] 2021-01-15 15:29
Hey @vpereira,

It seems like https://github.com/rails/rails/issues/41091 is reporting the same thing. This is related to `has_many_inversing` config that was introduced in Rails 6.1. See this PR (and the ones mentioned in) for more details: https://github.com/rails/rails/pull/37429. The behavior you're seeing is the right one. The association inverse is set on the object in memory.

@gmcgibbon It seems like there is no note of that change in https://guides.rubyonrails.org/6_1_release_notes.html#active-record. As the original author, do you think an entry there would be appropriate?

**Comment by vpereira** [comment] 2021-01-15 15:36
hi @louim thank you for the feedback, i will take a look in the linked issues!

**Comment by gmcgibbon** [comment] 2021-01-15 20:12
When upgrading your app you need to [opt into this behaviour](https://github.com/rails/rails/blob/f10dfa7f0ed8dcbb03dc65877797d29f6f6aca9e/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_6_1.rb.tt#L10). Looking at a similar Active Record feature `belongs_to_required_by_default`, this was also not documented in release notes, so I don't feel retroactively adding this is necessary. As @louim points out, this is intended behaviour, so I'm going to close this. Thank you for the issue.

**Closed by gmcgibbon** 2021-01-15 20:12 UTC
Labels: activerecord

**Comment by vpereira** [comment] 2021-01-15 20:55
Alright, thank you @gmcgibbon 

> so I don't feel retroactively adding this is necessary

One line above the one that you linked, you have the following note:

```# Read the Guide for Upgrading Ruby on Rails for more info on each option.```

**Comment by joevandyk** [comment] 2024-08-06 05:43
I got bit by this not being in the Rails 6.1 release notes - I had to dig through the Rails source code a bit to understand this.

**Comment by zzak** [comment] 2024-08-31 01:32
@joevandyk It's documented here as well: https://edgeguides.rubyonrails.org/configuring.html#default-values-for-target-version-6-1
This probably should have been added to the changelog, whoops.
