### ISSUE TITLE
How to use migration without rails, using activerecord just as ORM?

### ISSUE THREAD

**Issue by najamelan** [rails/rails#37871] opened 2019-12-03 18:11 UTC
I have an application that I upgraded to activerecord 6.0.1. [This commit](https://github.com/rails/rails/commit/7cc27d749c3563e6b278ad01d233cb92ea3b7935) broke my app. I'm using `MigrationContext` directly, which supposedly is not a public API according to the commit description.

I remember that when I first wrote it I struggled for quite some time to figure out how to use activerecord migration. Looking at the [documentation](https://rdoc.info/gems/activerecord/ActiveRecord/Migration) to try to fix this, I notice that there is indeed no explanation on how to use it without rails.

So what I have is something like:

```ruby
@migration_context = ActiveRecord::MigrationContext.new '../../../conf/db'.relpath.expand_path

# if the database file does not exist, create the db
#
@migration_context.up 20161208000000 # Create Schema

# later after each time I add data to the database I rebuild the indexes
# 
@migration_context.up 20161209000000 # Add Indexes
```
If I remember correctly, I did it this way because initial population of the DB is faster without indexes in place. I didn't comment my code enough to be sure now though...

How would I do something like this with the public API, or can you point me to any documentation that explains how to do something like this?
@eileencodes 

Thanks in advance for any help.

ps: underlying DB is SQLite

**Comment by eileencodes** [comment] 2019-12-03 18:16
Hey @najamelan thanks for the report. This issue is a duplicate of https://github.com/rails/rails/issues/36544

There isn't currently a public API for this as it was always private.

**Closed by eileencodes** 2019-12-03 18:16 UTC

**Comment by najamelan** [comment] 2019-12-03 18:30
Thanks, from the code linked in the other issue I tried adding the `ActiveRecord::SchemaMigration` parameter to the call and that seems to do the trick. I subscribed to it to keep track of any better way to achieve this if a public API comes along.
