### ISSUE TITLE
Could not run my Rails project on a new PC until I removed jbuilder from gem file.

### ISSUE THREAD

**Issue by mayordwells** [rails/rails#31548] opened 2017-12-23 00:28 UTC
### Steps to reproduce
I installed Rails and Ruby on a new system (Mac OS High Sierra), cloned my old project in Rails 5.2.0.beta2, but could not get it to work on the new system. 

Rails is supposed to run normally as before but instead got a strange behavior, started commenting out gems in Gemfile, based on my understanding of the error log.

Here's what the log looks like:
```
conectar (master) $ bundle exec rails server
=> Booting Puma
=> Rails 5.2.0.beta2 application starting in development
=> Run `rails server -h` for more startup options
Exiting
/Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/concern.rb:128:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/actionview-5.2.0.beta2/lib/action_view/view_paths.rb:7:in `<module:ViewPaths>'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/actionview-5.2.0.beta2/lib/action_view/view_paths.rb:4:in `<module:ActionView>'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/actionview-5.2.0.beta2/lib/action_view/view_paths.rb:3:in `<main>'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/actionview-5.2.0.beta2/lib/action_view/rendering.rb:3:in `<main>'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2/gems/jbuilder-2.7.0/lib/jbuilder/railtie.rb:15:in `<module:ApiRendering>'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2/gems/jbuilder-2.7.0/lib/jbuilder/railtie.rb:14:in `<module:ActionController>'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2/gems/jbuilder-2.7.0/lib/jbuilder/railtie.rb:13:in `block in <class:Railtie>'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/initializable.rb:32:in `run'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/application.rb:360:in `initialize!'
	from /Users/Mayor/Workspace/conectar/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:27:in `app'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:51:in `start'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/command/base.rb:65:in `perform'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/command.rb:46:in `invoke'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/railties-5.2.0.beta2/lib/rails/commands.rb:18:in `<main>'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
	from bin/rails:4:in `<main>'
```
The code didn't run until I commented out jbuilder. But even after that, I still get this.
```
conectar (master) $ bundle exec rails server
=> Booting Puma
=> Rails 5.2.0.beta2 application starting in development
=> Run `rails server -h` for more startup options
/Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/actionview-5.2.0.beta2/lib/action_view.rb:33: warning: already initialized constant ActionView::ENCODING_FLAG
/Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/actionview-5.2.0.beta2/lib/action_view.rb:33: warning: previous definition of ENCODING_FLAG was here
/Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/activemodel-5.2.0.beta2/lib/active_model/validations/clusivity.rb:8: warning: already initialized constant ActiveModel::Validations::Clusivity::ERROR_MESSAGE
/Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activemodel-5.2.0.beta2/lib/active_model/validations/clusivity.rb:8: warning: previous definition of ERROR_MESSAGE was here
/Users/Mayor/.rvm/gems/ruby-2.4.2@global/gems/activesupport-5.2.0.beta2/lib/active_support/core_ext/securerandom.rb:6: warning: already initialized constant SecureRandom::BASE58_ALPHABET
/Users/Mayor/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/core_ext/securerandom.rb:6: warning: previous definition of BASE58_ALPHABET was here
Puma starting in single mode...
* Version 3.11.0 (ruby 2.4.2-p198), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```
Any suggestions and help to remove this error log will be appreciated. Thanks.
### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: 2.4.2

**Comment by y-yagi** [comment] 2017-12-24 03:14
Can you please provide a sample application that reproduces the error?

**Comment by mayordwells** [comment] 2017-12-24 05:41
@y-yagi Please find a link for a new rails app here - https://github.com/mayordwells/calculator-math

**Comment by mayordwells** [comment] 2017-12-24 06:18
Hi @y-yagi Thanks for your interest in helping out with the error, but thought you should know. The error disappeared after removing rvm, all gemsets and the ruby version on my system and then started a whole new installation afresh. 
So my belief is that if the installation of rvm and ruby is correct on your system, you might not be able to reproduce the error. 
I got the idea of doing this while I was creating the new app above. I got even a longer error, so I thought there must be something wrong with my installation. So I was right.
And thank God it worked.

**Comment by y-yagi** [comment] 2017-12-24 10:10
Thanks for providing sample application and details explanation. 
I could not reproduce your error with the provided application. I think your guess is correct.  
So I close this. Thanks!

**Closed by y-yagi** 2017-12-24 10:10 UTC
Labels: needs work

**Comment by etcook** [comment] 2018-01-08 19:59
@y-yagi FWIW, I ran into this error as well with a completely fresh project of Rails 5.2 beta 2 and ruby version 2.5. I ended up just creating the project with 5.1.4 with no error.

**Comment by lauer** [comment] 2018-03-09 13:20
I got same problem with Rails 5.2.0.rc1, ruby 2.4.3 - on a new project on OS X 10.13.3 (High Sierra)
