### ISSUE TITLE
rails-ujs permanently disabling the link

### ISSUE THREAD

**Issue by cis-ankity** [rails/rails#33889] opened 2018-09-15 07:58 UTC
### Steps to reproduce
I've created an anchor tag and used the data-confirm with data-disable-with but when I click on the tag it is showing the confirmation pop-up and disabling the button but after completing the request it is not enabling it again.

<a data-confirm="Are you sure you want to remove this scorer?"  data-disable-with="<i class='fa fa-spinner spinner_title'></i>" class="small red remove hover" data-remote="true" rel="nofollow" data-method="delete" href="/events/event_id> Remove </a>

### Expected behavior
It should have to enable the button after completing the request.

### Actual behavior
It is disabling the button but not enabling it after the request completion.

Could you please tell me why it is happening, because previously I've used jquery-ujs  and it was working fine but after using rails-ujs it stops working.
### System configuration
**Rails version**:
Rails 5.2.0
**Ruby version**:
Ruby - 2.5.1

**Comment by y-yagi** [comment] 2018-09-16 00:48
Can you please provide a sample application that reproduces the issue?

**Comment by y-yagi** [comment] 2018-09-17 23:16
Thank you for the demo app. I was able to reproduce it. 
It seems to be using the a tag to send form data, but why is this? This seems a bit odd. Can you use submit?

**Comment by cis-ankity** [comment] 2018-09-18 06:40
you are right but in my application, I'm using two buttons one submitting the form and another one is a tag which is performing some other functionality by calling an Ajax request that's why we have used that a tag and facing the following problem. Also if we use the confirm with data-disable-with facing the same problem.
Could you please help me to resolve this.

**Comment by cis-ankity** [comment] 2018-09-19 14:46
Any hint from where I'll get the solution?

**Comment by ianfleeton** [comment] 2018-09-21 13:50
It appears that the `a` tag is meant to be supported.

I am finding the observed behaviour is because `disableElement` -> `disableLinkElement` is called for two separated events (a MouseEvent followed by a CustomEvent). The first time your `a` is disabled, the "saving as permanent" text is stored for later restoration, and the text is changed to "saving...". The second time it is disabled, the "saving..." text is stored for later restoration, which it is restored to.

I am trying to track down why `disableElement` ->`disableLinkElement` is called twice, when we only want it called once.

**Comment by ianfleeton** [comment] 2018-09-21 16:14
The two event types that trigger the disable are click and then ajax:send.

I've changed the compiled JavaScript as follows to show a workaround, but I don't know enough about rails-ujs to know if or why it's wrong.

I've added a guard to check if ujs:disabled is set in the expando, and if so return early.

```javascript
disableLinkElement = function(element) {
  if (getData(element, 'ujs:disabled')) {
    return;
  }
  var replacement;
  replacement = element.getAttribute('data-disable-with');
  if (replacement != null) {
    setData(element, 'ujs:enable-with', element.innerHTML);
    element.innerHTML = replacement;
  }
  element.addEventListener('click', stopEverything);
  return setData(element, 'ujs:disabled', true);
};
```

**Comment by cis-ankity** [comment] 2018-09-25 07:44
Thank you @ianfleeton, for looking into the issue. you are right that it is triggering two events for a single tag event and we can add a guard to check that button is disabled and will return if it is. But I think it is not the proper solution for it and we need to find the cause of it that why it is triggering two events.

**Comment by carlosramireziii** [comment] 2018-11-27 19:59
@cis-ankity I ran into the same issue when I had a `remote: true` link within a form. The fix/workaround was to move the link outside of the form.

**Comment by javan** [comment] 2018-12-18 15:54
Fixed via https://github.com/rails/rails/pull/34635

**Closed by javan** 2018-12-18 15:54 UTC
Labels: rails-ujs
