### ISSUE TITLE
Rails 7, cannot be loaded  js controllers in production

### ISSUE THREAD

**Issue by sergitejada** [rails/rails#45861] opened 2022-08-19 18:52 UTC
When moving from development to production environment the JS drivers cannot load into the html.

### Error
![image](https://user-images.githubusercontent.com/49126831/185686468-4c725ec0-515b-43d5-ba8a-1ebc3f5a6d67.png)

### My Code
**JS Folder**:
![image](https://user-images.githubusercontent.com/49126831/185686599-af905db8-3078-45f0-8b11-d60c5da040e6.png)
**Main Page**:
![image](https://user-images.githubusercontent.com/49126831/185687016-275b5870-1b30-4c38-a822-2acfc596f96e.png)
**Config File**:
![image](https://user-images.githubusercontent.com/49126831/185687399-26574566-4606-46ba-b46c-e0719a44d9eb.png)
![image](https://user-images.githubusercontent.com/49126831/185687468-16bde524-aa61-46ca-a0cd-f0f080d436b2.png)

**Public folder and Assets folder**:
![image](https://user-images.githubusercontent.com/49126831/185687084-f85afb46-13ef-4bbe-b868-d6d7dcc3447d.png)

My actions to deploy:
`RAILS_ENV=production rails assets:precompile`
`RAILS_ENV=production rails s`

### System configuration
**Rails version**: 7.0.3

**Ruby version**:  2.7.0

**Comment by hahmed** [comment] 2022-08-22 07:35
Could you reproduce this issue in a smaller sample application and post the link here?

**Comment by natematykiewicz** [comment] 2022-08-28 04:34
Your problem is line 35 in the `config/production.rb`. You didn't specify an asset host. Uncomment the line and set it to your domain.

**Comment by eileencodes** [comment] 2022-08-30 14:42
Closing because this isn't a bug in Rails, but rather a bug in the application.

**Closed by eileencodes** 2022-08-30 14:42 UTC
Labels: more-information-needed
