### ISSUE TITLE
`form_for` behavior is changed at Rails 7.0.0

### ISSUE THREAD

**Issue by yujideveloper** [rails/rails#44326] opened 2022-02-03 15:55 UTC
### Steps to reproduce

`form_for` was re-implemented using `form_with` at #43421.
At this change, a response of `to_model` is no longer used to switch between new / edit forms.
Is this intended?

``` ruby
class UserForm
  include ActiveModel::Model

  def initialize(user)
    @user = user
  end

  def to_model
    @user
  end
end
```

``` ruby
def new
  @user_form = UserForm(User.new)
end

def edit
  @user_form = UserForm(User.find(params[:id]))
end
```

``` erb
<%= form_for(@user_form) do %>
  <%= f.submit %>
<% end %>
```

### Expected behavior

if `to_model` returns a new record, it render a new record form.
if `to_model` returns a persisted record, it render a edit record form.

### Actual behavior

It is always rendering a new record form and never rendering a hidden input field for `_method` even if `to_model` returns a persisted record.

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 2.7.2

**Comment by ghiculescu** [comment] 2022-02-03 15:58
Thanks for the report. This doesn't sound intended. To confirm, this worked in Rails 6.1 but doesn't work in Rails 7?

Could you make an executable test case? That will make it easier to bisect to where the issue came up. https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case

**Comment by yujideveloper** [comment] 2022-02-03 16:12
> Thanks for the report. This doesn't sound intended. To confirm, this worked in Rails 6.1 but doesn't work in Rails 7?

Yes, It's work in Rails 6.1.4.4.

> Could you make an executable test case? That will make it easier to bisect to where the issue came up.

Ok , I try it.

**Comment by ghiculescu** [comment] 2022-02-03 16:14
My first thought was https://github.com/rails/rails/pull/42234 might be the cause. I'd be surprised / concerned if it impacted `form_for`.

**Comment by yujideveloper** [comment] 2022-02-03 18:07
I created executable test case. 

``` ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", github: "rails/rails", ref: "v7.0.1"
  gem "rails", github: "rails/rails", ref: "v6.1.4.4"
end

require "action_view"
require "active_model"
require "minitest/autorun"

class User
  include ActiveModel::Model

  attr_reader :id

  def initialize(persisted:)
    @persisted = persisted
    @id = 1 if persisted
  end

  def persisted?
    !!@persisted
  end
end
class UserForm
  include ActiveModel::Model

  def initialize(user)
    @user = user
  end

  def to_model
    @user
  end
end

class BugTest < ActionView::TestCase
  def setup
    routes = ActionDispatch::Routing::RouteSet.new
    routes.draw do
      resources :users
    end
    controller.singleton_class.include routes.url_helpers
    view.singleton_class.include routes.url_helpers
  end

  def test_new_form
    erb = <<~ERB
    <%= form_for(@user_form) do %><% end %>
    ERB

    user_form = UserForm.new(User.new(persisted: false))
    view.assign(user_form: user_form)
    result = render inline: erb
    assert result.include? '<form class="new_user" id="new_user" action="/users" accept-charset="UTF-8" method="post">'
  end

  def test_edit_form
    erb = <<~ERB
    <%= form_for(@user_form) do %><% end %>
    ERB

    user_form = UserForm.new(User.new(persisted: true))
    view.assign(user_form: user_form)
    result = render inline: erb
    assert result.include? '<form class="edit_user" id="edit_user_1" action="/users/1" accept-charset="UTF-8" method="post">'
    assert result.include? '<input type="hidden" name="_method" value="patch"'
  end

  def test_edit_form_with_method_option
    erb = <<~ERB
    <%= form_for(@user_form, method: :patch) do %><% end %>
    ERB

    user_form = UserForm.new(User.new(persisted: true))
    view.assign(user_form: user_form)
    result = render inline: erb
    assert result.include? '<form class="edit_user" id="edit_user_1" action="/users/1" accept-charset="UTF-8" method="post">'
    assert result.include? '<input type="hidden" name="_method" value="patch"'
  end
end
```

**Comment by seanpdoyle** [comment] 2022-02-03 19:23
I've opened https://github.com/rails/rails/pull/44328.

@yujideveloper do those tests faithfully reproduce your issue?

**Comment by yujideveloper** [comment] 2022-02-03 19:51
@seanpdoyle 

I checked #44328 and it solved `form_for` issue.
But in Rails 6.1.14.4, `form_with` was not attempt to call `to_model`.
Is this change ok?

**Comment by seanpdoyle** [comment] 2022-02-03 20:02
That's a good question! Thank you for pointing that out. I'll roll back that portion of the change and limit the fix to `form_for` only.

Adding support to `form_with` would be a good discussion to have separately.

**Comment by yujideveloper** [comment] 2022-02-04 03:11
Thanks!
I checked pr and ran my test cases again, all passed.

**Comment by gmcgibbon** [comment] 2022-02-18 21:34
Fixed by https://github.com/rails/rails/pull/44328

**Closed by gmcgibbon** 2022-02-18 21:34 UTC
Labels: actionview, attached PR
