### ISSUE TITLE
Wrong output for rake routes

### ISSUE THREAD

**Issue by savroff** [rails/rails#31858] opened 2018-02-01 14:26 UTC
### Steps to reproduce

Controller

```ruby
module Admin
  module Categories
    class AdvancedController
      before_action :set_category!

      private

      def set_category!
        @category ||= Category.find(params[:category_id])
      end
    end
  end
end
```

routes

```ruby
namespace :admin do
  resources :categories do
    resource :advanced, controller: '/admin/categories/advanced'
  end
end
```

### Expected behavior
Output from command`rake routes` 

```
advanced_admin_category GET  /admin/categories/:category_id/advanced(.:format)                                    admin/categories#advanced
```

And get in controller `params[:category_id]` 

### Actual behavior
```
advanced_admin_category GET  /admin/categories/:id/advanced(.:format)                                    admin/categories#advanced
```

But in controller still right parameter `params[:category_id]` 

### System configuration
**Rails version**:
Rails 5.1.1
**Ruby version**:
ruby 2.4.1p111

**Comment by y-yagi** [comment] 2018-02-01 23:19
Your example routes does not generate `advanced_admin_category` prefix. It generates `admin_category_advanced` prefix.
 
```ruby 
# config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories do
      resource :advanced, controller: '/admin/categories/advanced'
    end
  end
end
```

```
$ ./bin/rails routes
                      Prefix Verb   URI Pattern                                            Controller#Action
 new_admin_category_advanced GET    /admin/categories/:category_id/advanced/new(.:format)  admin/categories/advanced#new
edit_admin_category_advanced GET    /admin/categories/:category_id/advanced/edit(.:format) admin/categories/advanced#edit
     admin_category_advanced GET    /admin/categories/:category_id/advanced(.:format)      admin/categories/advanced#show
                             PATCH  /admin/categories/:category_id/advanced(.:format)      admin/categories/advanced#update
                             PUT    /admin/categories/:category_id/advanced(.:format)      admin/categories/advanced#update
                             DELETE /admin/categories/:category_id/advanced(.:format)      admin/categories/advanced#destroy
                             POST   /admin/categories/:category_id/advanced(.:format)      admin/categories/advanced#create
            admin_categories GET    /admin/categories(.:format)                            admin/categories#index
                             POST   /admin/categories(.:format)                            admin/categories#create
          new_admin_category GET    /admin/categories/new(.:format)                        admin/categories#new
         edit_admin_category GET    /admin/categories/:id/edit(.:format)                   admin/categories#edit
              admin_category GET    /admin/categories/:id(.:format)                        admin/categories#show
                             PATCH  /admin/categories/:id(.:format)                        admin/categories#update
                             PUT    /admin/categories/:id(.:format)                        admin/categories#update
                             DELETE /admin/categories/:id(.:format)                        admin/categories#destroy 
``` 

Can you please provide a sample application that reproduces the issue?

**Comment by hiimtaylorjones** [comment] 2018-02-16 13:44
Hi @savroff!

So, I'm unable to reproduce your error and am getting the same exact output as @y-yagi is getting. Could you by chance provide some information on your `routes.rb` file and controller structure? I'm curious if you have some kind of  custom rule that's causing your routes to be spit out somewhat weird. 

The closest I was able to reproduce your error was by changing the route and controller to look like the following:

`routes.rb`

```ruby
Rails.application.routes.draw do
  namespace :advanced do
    resources :admin do
      resource :categories, controller: '/admin/categories/admin'
    end
  end
end
```


`some_controller.rb`

```ruby
module Advanced
  module Admin
    class CategoriesController
      before_action :set_category!

      private

      def set_category!
        @category ||= Category.find(params[:category_id])
      end
    end
  end
end
```

Here's the output of `bundle exec rake routes`

```
                        Prefix Verb   URI Pattern                                         Controller#Action
 new_advanced_admin_categories GET    /advanced/admin/:admin_id/categories/new(.:format)  admin/categories/admin#new
edit_advanced_admin_categories GET    /advanced/admin/:admin_id/categories/edit(.:format) admin/categories/admin#edit
     advanced_admin_categories GET    /advanced/admin/:admin_id/categories(.:format)      admin/categories/admin#show
                               PATCH  /advanced/admin/:admin_id/categories(.:format)      admin/categories/admin#update
                               PUT    /advanced/admin/:admin_id/categories(.:format)      admin/categories/admin#update
                               DELETE /advanced/admin/:admin_id/categories(.:format)      admin/categories/admin#destroy
                               POST   /advanced/admin/:admin_id/categories(.:format)      admin/categories/admin#create
          advanced_admin_index GET    /advanced/admin(.:format)                           advanced/admin#index
                               POST   /advanced/admin(.:format)                           advanced/admin#create
            new_advanced_admin GET    /advanced/admin/new(.:format)                       advanced/admin#new
           edit_advanced_admin GET    /advanced/admin/:id/edit(.:format)                  advanced/admin#edit
                advanced_admin GET    /advanced/admin/:id(.:format)                       advanced/admin#show
                               PATCH  /advanced/admin/:id(.:format)                       advanced/admin#update
                               PUT    /advanced/admin/:id(.:format)                       advanced/admin#update
                               DELETE /advanced/admin/:id(.:format)                       advanced/admin#destroy
```

As you can see, I was able to come close to - but not exactly directly reproduce the unexpected route naming in your project. Has your controller structure ever looked like what I just posted? Is it possible that your code base is generating routes based off an old application structure of yours?

Anything helps here!

**Comment by y-yagi** [comment] 2018-02-18 01:59
I close it because the issue can not be reproduced. 
If you can prepare the reproduction procedure, please feel free to reopen.

**Closed by y-yagi** 2018-02-18 01:59 UTC
Labels: needs work
