### ISSUE TITLE
Active Record: validates on: :save does not work for existing records

### ISSUE THREAD

**Issue by ololobus** [rails/rails#42721] opened 2021-07-07 10:36 UTC
### Steps to reproduce

Imaging you have a model `User` with two persistent fields (`name` and `encrypted_password`) and one accessible attribute `password`. First, I want to validate presence of both `name` and `password` on :create. Second, I want to be sure that `password` is also changed altogether with `name`. So I write following model definition:
```ruby
class User < ApplicationRecord
  attr_accessor :password

  validates :name, presence: true, on: :create
  validates :password, presence: true, on: :create
  validates :password, presence: true, on: :save, if: :name_changed?
end
```

First part works perfectly well, I cannot save new record without either `name` or `password` provided. However, second validation does not work when saving existing record.

### Expected behavior
I expect:
```ruby
$ rails c

u = User.last
u.name = 'new_name'
u.valid? :save # => false
u.save # => false, cannot save without new password
```

### Actual behavior
However, this is what I get:
```ruby
$ rails c

u = User.last
u.name = 'new_name'
u.valid? :save # => false, so the validation seems to be working
u.save # => true, but the record itself is still being saved, i.e. validation is ignored
```

I can force validation usage with anonymous callback:
```ruby
  before_save prepend: true do
    throw(:abort) unless valid? :save
  end
```

Yet, this is not what I expect after reading https://guides.rubyonrails.org/active_record_validations.html. It says that all save / update / create trigger validations. Honestly, this is what I expect from `validates` method doing for me. Otherwise it does not make much sense if I still have to run validations manually.

So why it works for new records, but does not when saving existing ones? Is it a bug? Or is it expected behaviour? If so, where is it documented?

### System configuration
**Rails version**: Rails 6.1.3.2

**Ruby version**: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]

**Comment by intrip** [comment] 2021-07-07 14:40
@ololobus have you tried using `  validates :password, presence: true, if: :name_changed?` instead?

By default validation should run already on `save`. If you pass `save` explicitly instead is considered as custom validation context, which implies that the validation doesn't run by default on `save`.

**Comment by ololobus** [comment] 2021-07-07 15:35
@intrip, just tried and it works, thanks. I missed the part that says `save` is default, so it is not necessary here.

> By default validation should run already on save. If you pass save explicitly instead is considered as custom validation context, which implies that the validation doesn't run by default on save.

However, it still looks a bit misleading that `save` is considered as a custom context, but `create` and `update` are not. I mean that it does not look right to punish users for passing some default value explicitly.

**Comment by intrip** [comment] 2021-07-07 15:46
@ololobus doesn't the docs outline this behaviour already? Please check https://guides.rubyonrails.org/active_record_validations.html#on

Which docs have you been checking that wasn't clear?

**Comment by ololobus** [comment] 2021-07-07 15:48
Actually, the problem is wider. It is not clear for me why Active Record Validations are so picky about `on:` arguments. Its fired by default when you pass :create or :update (default actions / methods), but not for :save (here) and :destroy (#32376) (also default actions / methods).

Yet, I created such a concern / module:
```ruby
module Validatable
  extend ActiveSupport::Concern

  included do
    before_create prepend: true do
      # throw(:abort) is required to break callback execution chain
      # See: https://www.bigbinary.com/blog/rails-5-does-not-halt-callback-chain-when-false-is-returned
      throw(:abort) unless valid? :create
    end

    before_save prepend: true do
      throw(:abort) unless valid? :save
    end

    before_update prepend: true do
      throw(:abort) unless valid? :update
    end

    # prepend: true is required so that dependent: :destroy doesn't run before the validations are executed
    before_destroy prepend: true do
      throw(:abort) unless valid? :destroy
    end
  end
end
```

And after mixing it into my models everything works just fine for all :create, :save, :update and :destroy. So why is it not a default behaviour?

From the user perspective it perfectly makes sense and is what expected. Issue #32376 and follow-up comments confirm that point of view.

**Comment by ololobus** [comment] 2021-07-07 15:56
> Which docs have you been checking that wasn't clear enough?

@intrip, my message was not clear enough, sorry. Yeah, I was reading exactly this tutorial and actually **missed** the first paragraph that says `save` is default, so it was my fault :) Yet, I hope that my argument that passing default values should always be tolerated is still valid.

**Comment by intrip** [comment] 2021-07-12 12:59
@ololobus I understand your point, your requests makes sense but requires to consider `:save` as special keyword (as we already do for `:update` and `:create`) and this will introduce a small breaking change.

Honestly I think the current behaviour is fine and well documented so I wouldn't change it.
That said I'm not the decision maker here, I think we need feedback from the committers or the core team.
/cc @p8 @zzak

**Comment by nickhammond** [comment] 2021-07-23 05:23
The [rails guides](https://guides.rubyonrails.org/active_record_validations.html#on) do a good job of explaining all of the options for the `:on` option. `:create` or `:update` are provided by default and then you can always add a custom context, sometimes you'll see this with a context of `:signup` so that you only validate specific fields on signup for instance. 

The [default value](https://api.rubyonrails.org/v5.1.7/classes/ActiveModel/Validations/ClassMethods.html#method-i-validates) for `:on` is actually `nil` so that it'll run in all contexts instead of a specified context, not `:save`. Specifying `:save` is actually creating a new context that you could then validate against.

**Comment by intrip** [comment] 2021-07-27 14:47
@p8 looks like we close this?

**Comment by p8** [comment] 2021-07-31 17:18
@intrip I think @ololobus has a point that it’s not fully consistent. Not sure if it gets merged, but maybe we can reset the passed context if it is :save here:
https://github.com/rails/rails/blob/c3664b0c2b509fc0a47929f42afbd716959c8f4c/activerecord/lib/active_record/validations.rb#L67
and do the same for the validations?

**Comment by intrip** [comment] 2021-08-02 07:42
@p8 just to make sure I understood you: you propose to make `valid?(:save)` behave in the same way as `valid?` ?

I think it's reasonable but it introduces a small breaking change, also the docs also explicitly mention such inconsistency so I don't know if it's worth changing the behaviour.

**Comment by p8** [comment] 2021-08-13 19:43
@intrip I agree with other commenters the current behaviour is clearly documented.

If we do make `valid?(:save)` work as `valid?`, we'd also have to make sure passing `:save` to `on:` works the same as not passing anything. This would require ActiveRecord to override the `on:` handling: https://github.com/rails/rails/blob/c3664b0c2b509fc0a47929f42afbd716959c8f4c/activemodel/lib/active_model/validations.rb#L163-L170
I think this change probably won't get accepted, as the added complexity has a small benefit.

I'm closing this for now as it's not a bug.

**Closed by p8** 2021-08-13 19:43 UTC
Labels: activerecord
