### ISSUE TITLE
`Import { DirectUploadController } from '@rails/activestorage'` not possible

### ISSUE THREAD

**Issue by tchak** [rails/rails#35248] opened 2019-02-13 12:53 UTC
I would like to be able to import `DirectUploadController` from `@rails/activestorage`
I can import from direct path `@rails/activestorage/src/direct_upload_controller`, but in this case javascript code is not transpiled by babel and fails in older browsers. Is there a reason only `DirectUpload` is exported from `index.js`? If I make a PR to export `DirectUploadController` from `index.js` is there any chance for it to be accepted?

### Expected behavior
Be able to import `DirectUploadController` from `@rails/activestorage`

### Actual behavior
Impossible to import `DirectUploadController` from `@rails/activestorage`

### System configuration
Any version of rails

**Comment by javan** [comment] 2019-02-13 20:49
> I would like to be able to import `DirectUploadController` from `@rails/activestorage`

To do what, exactly?

It wasn't really designed for public consumption, and is essentially an implementation detail of Active Storage's unobtrusive JavaScript component: [`ujs.js`](https://github.com/rails/rails/blob/af6ade0cfd09e3d3d9ebd304a2afae4d60a044dc/activestorage/app/javascript/activestorage/ujs.js) → `DirectUploadsController` → `DirectUploadController`. The [events it emits](https://edgeguides.rubyonrails.org/active_storage_overview.html#direct-upload-javascript-events) are what I'd consider the public API.

The [`DirectUpload`](https://github.com/rails/rails/blob/af6ade0cfd09e3d3d9ebd304a2afae4d60a044dc/activestorage/app/javascript/activestorage/direct_upload.js) class, however, was designed for consumption. For example, here's how Action Text uses it: https://github.com/rails/rails/blob/af6ade0cfd09e3d3d9ebd304a2afae4d60a044dc/actiontext/app/javascript/actiontext/attachment_upload.js#L1-L12

**Comment by javan** [comment] 2019-02-15 17:09
Closing since [you appear to have things working](https://github.com/betagouv/tps/pull/3423/files) now.

**Closed by javan** 2019-02-15 17:09 UTC

**Comment by zzak** [comment] 2021-05-21 23:53
@virolea We would prefer to discuss feature requests to happen in [the forum](https://discuss.rubyonrails.org/) where more people are able to follow along.
