### ISSUE TITLE
Rails 5.0.0.1 increment! does not invoke callbacks where 4.2.7.1 does

### ISSUE THREAD

**Issue by rdunlop** [rails/rails#26554] opened 2016-09-20 04:12 UTC
### Steps to reproduce

Reproduction script https://gist.github.com/rdunlop/e02150cc57a71e7dbf7f752cbc1d5a1f
### Expected behavior

When the 'increment!' method is called on an model, the 'after_save' (and other) callbacks should be invoked
### Actual behavior

No callbacks appear to be invoked
### System configuration

**Rails version**: 5.0.0.1 (works correctly on 4.2.7.1)

**Ruby version**: 2.2.3, 2.3.1 (I didn't try others)

I believe that the following commit changed the behavior:
https://github.com/rails/rails/commit/85a1c025081faf8af8a065e39ee764caebf4054b

I am not familiar enough with concurrency concerns to know what patch to propose to resolve the issue.

**Comment by girishso** [comment] 2016-09-20 05:49
Looks like `increment!` uses `update_all` which skips the validations and callbacks, for performance reasons I suppose.  We either need to fix the docs or fix this.

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/counter_cache.rb#L83

**Comment by maclover7** [comment] 2016-09-20 19:28
cc @sgrif

**Comment by ilan-senexx** [comment] 2017-01-31 13:26
this is a serious bug , i worked around it using after_update_commit for example , 

i saw that on branch master you added the `touch` options to increment! method 

not sure why this one works but it does : )

**Comment by rafaelfranca** [comment] 2017-01-31 23:34
This is a change in behavior made by design. I don't see a way to make incrementing counting concurrent safe without doing it directly in the database and skipping callbacks. We need to update the documentation.

**Comment by kamipo** [comment] 2017-03-04 09:32
The doc was fixed in #25427.

**Closed by kamipo** 2017-03-04 09:32 UTC
Labels: activerecord, needs feedback
