### ISSUE TITLE
`create` or `save` calls can cause PG::NotNullViolation

### ISSUE THREAD

**Issue by Esaron** [rails/rails#35614] opened 2019-03-14 20:33 UTC
### Steps to reproduce
Using `create` or `save`, attempt to persist any ActiveRecord model instance with a null attribute for which a not null constraint exists at the database level (PG).

### Expected behavior
The call should fail silently.

### Actual behavior
The call explodes in the exact same way as if one had called `create!` or `save!`.

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**: 2.4.3

This was discovered after working through an upgrade from 4.2 to 5.2.2.1. Calls to `find_or_create_by` which had previously silently failed, started to throw `ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "not_nullable_column" violates not-null constraint`.

I did not find an exact duplicate for this issue searching though past ones, or evidence that this was an intended change in behavior in some version between 4.2 and 5.2.2.1.

**Comment by gmcgibbon** [comment] 2019-03-14 23:38
I'm [not seeing the described behaviour of rails 4.2](https://gist.github.com/gmcgibbon/bab4d3443de1d3279059029b252451ff). Keep in mind `save` is supposed to silently fail on model validations, `PG::NotNullViolation` is happening when the record is being persisted. I would expect this to always raise as it indicates a problem with your table's constraints versus the data you expect to be acceptable.

Rails 4.2 is also no longer supported, so I think in any case this is the intended behaviour. With that in mind, I'm going to close this. If I missed something, please let me know. Thank you for your report!

**Closed by gmcgibbon** 2019-03-14 23:38 UTC
Labels: activerecord

**Comment by Esaron** [comment] 2019-03-15 02:12
After a bit of digging, this doesn't seem to be as simple as I initially thought. It's actually looking like it's due to what might be an intended behavior, but I figured I'd provide an update and some code just in case it's actually a bug. Forgive the mess I made of your script.

`belongs_to` associations, as I understand it, changed such that they default to being required. IE - the new `belongs_to`, sans options, should function the same way as the old `belongs_to` with `required: true`. This does not seem to be the case. If I explicitly pass `optional: false`, then I get the behavior I expect. See https://gist.github.com/Esaron/76cef55c5c94fa5e369efdee97e69103.

`ruby db_error_raise_on_save.rb '4.2.10'` and
`ruby db_error_raise_on_save.rb '5.2.2.1'`

I could simply be mistaken in my understanding of how this is meant to work, so please correct me if I'm wrong.

**Comment by gmcgibbon** [comment] 2019-03-15 06:38
`ActiveRecord::Base.belongs_to_required_by_default = true` is [set by framework defaults](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-record-belongs-to-required-by-default-option) so you don't get that unless you opt into defaults for `5.0` or greater.  In the passing tests you can call `#create` without getting errors because the `required` validation check is failing, and that stops persistence.

**Comment by Esaron** [comment] 2019-03-15 13:09
That's the section I must have glossed over in the guide. Thanks!
