### ISSUE TITLE
Getting started steps don't work on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by dskloet** [rails/rails#42709] opened 2021-07-06 11:04 UTC
### Steps to reproduce

I'm new to both Ruby and Rails so I just wanted to try it out.
I'm following the steps on https://github.com/basecamp/rails#getting-started

First I got
```
$ gem install rails
Fetching: concurrent-ruby-1.1.9.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
```

Since it's a permission issue, I thought maybe I should run as root so I try with sudo

```
$ sudo gem install rails
[sudo] password for dskloet: 
Fetching: concurrent-ruby-1.1.9.gem (100%)
Successfully installed concurrent-ruby-1.1.9
Fetching: i18n-1.8.10.gem (100%)
Successfully installed i18n-1.8.10
Fetching: tzinfo-2.0.4.gem (100%)
Successfully installed tzinfo-2.0.4
Fetching: zeitwerk-2.4.2.gem (100%)
Successfully installed zeitwerk-2.4.2
Fetching: activesupport-6.1.4.gem (100%)
Successfully installed activesupport-6.1.4
Fetching: rack-2.2.3.gem (100%)
Successfully installed rack-2.2.3
Fetching: rack-test-1.1.0.gem (100%)
Successfully installed rack-test-1.1.0
Fetching: racc-1.5.2.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing rails:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/racc-1.5.2/ext/racc/cparse
/usr/bin/ruby2.5 -r ./siteconf20210706-6968-airftl.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/racc-1.5.2 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/racc-1.5.2/gem_make.out
```

Since it still doesn't work, I copy the error message "ERROR: Failed to build gem native extension" into Google and find [this](https://stackoverflow.com/questions/13767725/unable-to-install-gem-failed-to-build-gem-native-extension-cannot-load-such) so I try

```
sudo apt-get install ruby-dev
```

and once again

```
$ gem install rails
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
```

and once again with `sudo`

```
$ sudo gem install rails
Building native extensions. This could take a while...
Successfully installed racc-1.5.2
Fetching: nokogiri-1.11.7-x86_64-linux.gem (100%)
Successfully installed nokogiri-1.11.7-x86_64-linux
Fetching: crass-1.0.6.gem (100%)
Successfully installed crass-1.0.6
Fetching: loofah-2.10.0.gem (100%)
Successfully installed loofah-2.10.0
Fetching: rails-html-sanitizer-1.3.0.gem (100%)
Successfully installed rails-html-sanitizer-1.3.0
Fetching: rails-dom-testing-2.0.3.gem (100%)
Successfully installed rails-dom-testing-2.0.3
Fetching: builder-3.2.4.gem (100%)
Successfully installed builder-3.2.4
Fetching: erubi-1.10.0.gem (100%)
Successfully installed erubi-1.10.0
Fetching: actionview-6.1.4.gem (100%)
Successfully installed actionview-6.1.4
Fetching: actionpack-6.1.4.gem (100%)
Successfully installed actionpack-6.1.4
Fetching: activemodel-6.1.4.gem (100%)
Successfully installed activemodel-6.1.4
Fetching: activerecord-6.1.4.gem (100%)
Successfully installed activerecord-6.1.4
Fetching: globalid-0.4.2.gem (100%)
Successfully installed globalid-0.4.2
Fetching: activejob-6.1.4.gem (100%)
Successfully installed activejob-6.1.4
Fetching: mini_mime-1.1.0.gem (100%)
Successfully installed mini_mime-1.1.0
Fetching: mail-2.7.1.gem (100%)
Successfully installed mail-2.7.1
Fetching: actionmailer-6.1.4.gem (100%)
Successfully installed actionmailer-6.1.4
Fetching: nio4r-2.5.7.gem (100%)
Building native extensions. This could take a while...
Successfully installed nio4r-2.5.7
Fetching: websocket-extensions-0.1.5.gem (100%)
Successfully installed websocket-extensions-0.1.5
Fetching: websocket-driver-0.7.5.gem (100%)
Building native extensions. This could take a while...
Successfully installed websocket-driver-0.7.5
Fetching: actioncable-6.1.4.gem (100%)
Successfully installed actioncable-6.1.4
Fetching: marcel-1.0.1.gem (100%)
Successfully installed marcel-1.0.1
Fetching: activestorage-6.1.4.gem (100%)
Successfully installed activestorage-6.1.4
Fetching: actionmailbox-6.1.4.gem (100%)
Successfully installed actionmailbox-6.1.4
Fetching: actiontext-6.1.4.gem (100%)
Successfully installed actiontext-6.1.4
Fetching: thor-1.1.0.gem (100%)
Successfully installed thor-1.1.0
Fetching: method_source-1.0.0.gem (100%)
Successfully installed method_source-1.0.0
Fetching: railties-6.1.4.gem (100%)
Successfully installed railties-6.1.4
Fetching: bundler-2.2.21.gem (100%)
Successfully installed bundler-2.2.21
Fetching: sprockets-4.0.2.gem (100%)
Successfully installed sprockets-4.0.2
Fetching: sprockets-rails-3.2.2.gem (100%)
Successfully installed sprockets-rails-3.2.2
Fetching: rails-6.1.4.gem (100%)
Successfully installed rails-6.1.4
Parsing documentation for racc-1.5.2
Installing ri documentation for racc-1.5.2
Parsing documentation for nokogiri-1.11.7-x86_64-linux
Installing ri documentation for nokogiri-1.11.7-x86_64-linux
Parsing documentation for crass-1.0.6
Installing ri documentation for crass-1.0.6
Parsing documentation for loofah-2.10.0
Installing ri documentation for loofah-2.10.0
Parsing documentation for rails-html-sanitizer-1.3.0
Installing ri documentation for rails-html-sanitizer-1.3.0
Parsing documentation for rails-dom-testing-2.0.3
Installing ri documentation for rails-dom-testing-2.0.3
Parsing documentation for builder-3.2.4
Installing ri documentation for builder-3.2.4
Parsing documentation for erubi-1.10.0
Installing ri documentation for erubi-1.10.0
Parsing documentation for actionview-6.1.4
Installing ri documentation for actionview-6.1.4
Parsing documentation for actionpack-6.1.4
Installing ri documentation for actionpack-6.1.4
Parsing documentation for activemodel-6.1.4
Installing ri documentation for activemodel-6.1.4
Parsing documentation for activerecord-6.1.4
Installing ri documentation for activerecord-6.1.4
Parsing documentation for globalid-0.4.2
Installing ri documentation for globalid-0.4.2
Parsing documentation for activejob-6.1.4
Installing ri documentation for activejob-6.1.4
Parsing documentation for mini_mime-1.1.0
Installing ri documentation for mini_mime-1.1.0
Parsing documentation for mail-2.7.1
Installing ri documentation for mail-2.7.1
Parsing documentation for actionmailer-6.1.4
Installing ri documentation for actionmailer-6.1.4
Parsing documentation for nio4r-2.5.7
Installing ri documentation for nio4r-2.5.7
Parsing documentation for websocket-extensions-0.1.5
Installing ri documentation for websocket-extensions-0.1.5
Parsing documentation for websocket-driver-0.7.5
Installing ri documentation for websocket-driver-0.7.5
Parsing documentation for actioncable-6.1.4
Installing ri documentation for actioncable-6.1.4
Parsing documentation for marcel-1.0.1
Installing ri documentation for marcel-1.0.1
Parsing documentation for activestorage-6.1.4
Installing ri documentation for activestorage-6.1.4
Parsing documentation for actionmailbox-6.1.4
Installing ri documentation for actionmailbox-6.1.4
Parsing documentation for actiontext-6.1.4
Installing ri documentation for actiontext-6.1.4
Parsing documentation for thor-1.1.0
Installing ri documentation for thor-1.1.0
Parsing documentation for method_source-1.0.0
Installing ri documentation for method_source-1.0.0
Parsing documentation for railties-6.1.4
Installing ri documentation for railties-6.1.4
Parsing documentation for bundler-2.2.21
Installing ri documentation for bundler-2.2.21
Parsing documentation for sprockets-4.0.2
Installing ri documentation for sprockets-4.0.2
Parsing documentation for sprockets-rails-3.2.2
Installing ri documentation for sprockets-rails-3.2.2
Parsing documentation for rails-6.1.4
Installing ri documentation for rails-6.1.4
Done installing documentation for racc, nokogiri, crass, loofah, rails-html-sanitizer, rails-dom-testing, builder, erubi, actionview, actionpack, activemodel, activerecord, globalid, activejob, mini_mime, mail, actionmailer, nio4r, websocket-extensions, websocket-driver, actioncable, marcel, activestorage, actionmailbox, actiontext, thor, method_source, railties, bundler, sprockets, sprockets-rails, rails after 40 seconds
32 gems installed
```

OK, this appears to have done something.
So I continue the guide:

```
$ rails new myapp
-bash: /usr/local/bin/rails: Permission denied
```

So I check the permission:

```
$ ls -l /usr/local/bin/rails
-rwx------ 1 root root 604 Jul  6 12:44 /usr/local/bin/rails
```

OK, that's weird. So I fix the permissions and try again:

```
$ sudo chmod a+rx /usr/local/bin/rails
$ rails new myapp
Traceback (most recent call last):
	2: from /usr/local/bin/rails:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem railties (>= 0.a) with executable rails (Gem::GemNotFoundException)
```

I tried searching for the error message but found [very few results](https://www.google.com/search?q=%22can%27t+find+gem+railties+(%3E%3D+0.a)+with+executable+rails+(Gem%3A%3AGemNotFoundException)%22&oq=%22can%27t+find+gem+railties+(%3E%3D+0.a)+with+executable+rails+(Gem%3A%3AGemNotFoundException)%22&aqs=chrome.0.69i59.1080j0j7&sourceid=chrome&ie=UTF-8).

I'm not sure how to continue.

### System configuration
**Rails version**: 6.1.4

**Ruby version**: 2.5.1p57

**OS**: Ubuntu 18.04 LTS.

**Comment by yahonda** [comment] 2021-07-06 12:28
How about installing bundler as follows?

sudo apt install ruby-bundler

**Comment by dskloet** [comment] 2021-07-06 13:26
After installing ruby-bundler I still get the same error
```
$ rails new myapp
Traceback (most recent call last):
	2: from /usr/local/bin/rails:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem railties (>= 0.a) with executable rails (Gem::GemNotFoundException)
```

**Comment by yahonda** [comment] 2021-07-06 14:35
How about executing rails new with sudo as follows?

```
$ sudo rails new myapp
```

I think this is not a Rails issue then how about moving this question to https://discuss.rubyonrails.org/c/rubyonrails-talk/ if it still reproduces?

**Comment by mdemare** [comment] 2021-07-07 10:13
The getting started instructions in `README.md` are part of the rails repository, and if they assume having ruby installed via RVM or homebrew as opposed to a linux package manager, we might as well spell that out.

**Comment by dskloet** [comment] 2021-07-08 11:33
Yes, that would be helpful.

**Comment by mdemare** [comment] 2021-07-08 13:47
I started up an AWS EC2 instance with Ubuntu 18.04 and this is the smallest amount of steps that I could find to get Rails up and running (On ruby 2.5, the default for Ubuntu 18)

```
sudo apt update
sudo apt -y install software-properties-common zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev ruby-full
echo 'export PATH="$HOME/.gem/ruby/2.5.0/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
gem install --user-install --no-document rails
rails new hello ----minimal --skip-javascript --skip-sprockets
(cd hello; rails s)
```

I've been installing ruby for two decades on various platforms and yet it took me several tries and a bit of googling to get this right.

Linux users are used to package managers, and beginning rails users won't need to have multiple ruby versions installed, so therefore I'd prefer installing with apt over RVM or rbenv. `gem install --user-install` will allow linux users to install gems in their home dir, without using sudo, similar to homebrew users on macos, but the executable gem path needs to be added to `PATH` (and not all users use bash).

Finally, a lot of packages are required to compile all the native gems that rails needs.

This is too much information for the README, but we could link to the rails guide (https://guides.rubyonrails.org/getting_started.html#creating-a-new-rails-project-installing-rails) more prominently, and expand the guide to cover installing both ruby and rails.

Currently the guide delegates to ruby-lang.org, which doesn't explain how to install newer versions of ruby via apt, or which packages to install to be able to build native gems. Nor is that mentioned in the getting started rails guide, (although it is in https://guides.rubyonrails.org/development_dependencies_install.html). The guide also recommends running `gem install rails` which doesn't work if ruby is installed for all users.

In my opinion, this is a place where Rails could be a lot more opinionated than it is now.

**Comment by dskloet** [comment] 2021-07-08 14:43
Thanks for this effort! In my opinion, if a "Getting Started" section assumes you already know what you're doing, it's not very useful for getting started. And I also don't understand the point of all these separate package managers. Somehow whenever any instructions tell me to use npm or pip (and now apparently also gem) I know it's not going to work on my system. Even though I thought Ubuntu is quite popular and standard.

Since I open this issue, I decided to finally take the step to upgrade to Ubuntu 20.04. But I thought your steps might still work for me. But it seems they don't:
```
$ sudo apt -y install software-properties-common zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev ruby-full
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.3-4).
libffi-dev set to manually installed.
libreadline-dev is already the newest version (8.0-4).
libyaml-dev is already the newest version (0.2.2-1).
libsqlite3-dev is already the newest version (3.31.1-4ubuntu0.2).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.4).
software-properties-common is already the newest version (0.98.9.5).
sqlite3 is already the newest version (3.31.1-4ubuntu0.2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1.2).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: gcc (>= 4:9.2) but 4:7.4.0-1ubuntu2.3 is to be installed
                   Depends: g++ (>= 4:9.2) but 4:7.4.0-1ubuntu2.3 is to be installed
E: Unable to correct problems, you have held broken packages.
```
I'm a bit confused by this since I thought the job of the package manager is to make sure that dependencies are met.

**Comment by lfalcao** [comment] 2021-07-09 05:56
@dskloet Well, maybe the docs are not optimal. But I would suggest you to avoid the use of default ruby from so (/usr/bin/ruby). Use a version manager (like rvm, rbenv, asdf...) or even docker to keep your application dependencies/environment isolated and portable.

**Comment by dskloet** [comment] 2021-07-09 06:05
Thanks @lfalcao but I don't have an application to manage. I just want to try out Rails. I thought that's what the "Getting Started" section is for. If you want to recommend advanced version management, maybe there should be another section for that?

Either way, if version management is easy, I have nothing against it. Right now nothing seems to be working either way.

**Comment by mdemare** [comment] 2021-07-09 08:54
> Since I open this issue, I decided to finally take the step to upgrade to Ubuntu 20.04. But I thought your steps might still work for me. But it seems they don't:

I checked and the instructions work on a clean install of Ubuntu 20.04. The upgrade must have left some packages in a broken state. See https://askubuntu.com/q/937254 for somebody with a similar problem.

**Comment by mdemare** [comment] 2021-07-09 09:05
> @dskloet I suggest you to avoid the use of default ruby from so (/usr/bin/ruby). Use a version manager (like rvm, rbenv, asdf...) or even docker to keep your application dependencies/environment isolated and portable.

This is ultimately not about tech support for @dskloet, but about how we recommend that beginning Rails devs install Ruby and Rails on Ubuntu and other linux distros. I believe that instead of linking to ruby-lang.org or saying "there are so many options, apt, yum, from source, rvm, rbenv etc. do whatever works for you", the Rails community should pick one method, explain it in detail, in the Rails guides without delegating to other sites, and then in a footnote mention the other installation methods and why you'd want to use them.

**Comment by dskloet** [comment] 2021-07-09 11:04
I agree. While I certainly appreciate the tech support, the reason for reporting the issue is to get the documentation improved. And hopefully my struggles can help guide the improvements.

Thanks, with the askubuntu.com link I was able to remove a bad Ubuntu 18 package and then successfully apt install.
But after the `gem install` step, the `rails new` step failed.

```
$ gem install --user-install --no-document rails
Fetching rack-2.2.3.gem
Fetching tzinfo-2.0.4.gem
Fetching concurrent-ruby-1.1.9.gem
Fetching sprockets-4.0.2.gem
Fetching i18n-1.8.10.gem
Fetching activesupport-6.1.4.gem
Fetching nokogiri-1.11.7-x86_64-linux.gem
Fetching zeitwerk-2.4.2.gem
Fetching crass-1.0.6.gem
Fetching loofah-2.10.0.gem
Fetching rails-html-sanitizer-1.3.0.gem
Fetching rails-dom-testing-2.0.3.gem
Fetching rack-test-1.1.0.gem
Fetching erubi-1.10.0.gem
Fetching builder-3.2.4.gem
Fetching actionview-6.1.4.gem
Fetching actionpack-6.1.4.gem
Fetching sprockets-rails-3.2.2.gem
Fetching thor-1.1.0.gem
Fetching method_source-1.0.0.gem
Fetching railties-6.1.4.gem
Fetching mini_mime-1.1.0.gem
Fetching marcel-1.0.1.gem
Fetching activemodel-6.1.4.gem
Fetching activerecord-6.1.4.gem
Fetching globalid-0.4.2.gem
Fetching activejob-6.1.4.gem
Fetching activestorage-6.1.4.gem
Fetching actiontext-6.1.4.gem
Fetching mail-2.7.1.gem
Fetching actionmailer-6.1.4.gem
Fetching actionmailbox-6.1.4.gem
Fetching websocket-extensions-0.1.5.gem
Fetching rails-6.1.4.gem
Fetching websocket-driver-0.7.5.gem
Fetching nio4r-2.5.7.gem
Fetching actioncable-6.1.4.gem
WARNING:  You don't have /home/dskloet/.gem/ruby/3.0.0/bin in your PATH,
	  gem executables will not run.
GemWrappers: Can not wrap not executable file: /usr/local/bin/rackup
Successfully installed rack-2.2.3
Successfully installed concurrent-ruby-1.1.9
GemWrappers: Can not wrap not executable file: /usr/local/bin/sprockets
Successfully installed sprockets-4.0.2
Successfully installed zeitwerk-2.4.2
Successfully installed tzinfo-2.0.4
Successfully installed i18n-1.8.10
Successfully installed activesupport-6.1.4
GemWrappers: Can not wrap not executable file: /usr/local/bin/nokogiri
Successfully installed nokogiri-1.11.7-x86_64-linux
Successfully installed crass-1.0.6
Successfully installed loofah-2.10.0
Successfully installed rails-html-sanitizer-1.3.0
Successfully installed rails-dom-testing-2.0.3
Successfully installed rack-test-1.1.0
Successfully installed erubi-1.10.0
Successfully installed builder-3.2.4
Successfully installed actionview-6.1.4
Successfully installed actionpack-6.1.4
Successfully installed sprockets-rails-3.2.2
GemWrappers: Can not wrap not executable file: /usr/local/bin/thor
Successfully installed thor-1.1.0
Successfully installed method_source-1.0.0
Successfully installed railties-6.1.4
Successfully installed mini_mime-1.1.0
Successfully installed marcel-1.0.1
Successfully installed activemodel-6.1.4
Successfully installed activerecord-6.1.4
Successfully installed globalid-0.4.2
Successfully installed activejob-6.1.4
Successfully installed activestorage-6.1.4
Successfully installed actiontext-6.1.4
Successfully installed mail-2.7.1
Successfully installed actionmailer-6.1.4
Successfully installed actionmailbox-6.1.4
Successfully installed websocket-extensions-0.1.5
Building native extensions. This could take a while...
Successfully installed websocket-driver-0.7.5
Building native extensions. This could take a while...
Successfully installed nio4r-2.5.7
Successfully installed actioncable-6.1.4
Successfully installed rails-6.1.4
37 gems installed

$ rails new hello ----minimal --skip-javascript --skip-sprockets
-bash: /usr/local/bin/rails: /usr/bin/ruby2.5: bad interpreter: No such file or directory

$ type rails
rails is hashed (/usr/local/bin/rails)
 head -1 /usr/local/bin/rails
#!/usr/bin/ruby2.5

$ ls -l /usr/bin/ruby*
lrwxrwxrwx 1 root root     7 Apr  3  2020 /usr/bin/ruby -> ruby2.7
-rwxr-xr-x 1 root root 14488 Apr 15 16:38 /usr/bin/ruby2.7
```

There seems to be some kind of version mismatch where it expects me to have version 2.5 where I only have version 2.7?

**Comment by mdemare** [comment] 2021-07-09 11:53
If you install via `gem install --user-install` then the gems will be installed in your home dir, and the gem executable should be in your path. That's why you get `WARNING:  You don't have /home/dskloet/.gem/ruby/3.0.0/bin in your PATH` in your output, although I don't understand why it refers to `ruby/3.0.0`.

Because the gem executable for rails that you just installed is not in your path, `rails new` does not find it and apparently finds an older install at `/usr/local/bin/rails` which was installed with a hardcoded link to `ruby2.5`.

**Comment by dskloet** [comment] 2021-07-09 13:01
Of course that's what the new $PATH was for. But somehow there's no `bin/` in my `$HOME/.gem/ruby/2.5.0/`. Only a directory called `cache`.
I do also have a `$HOME/.gem/ruby/3.0.0/` which does have a `bin/` so I tried putting that in my `$PATH`, but then I get this error.

```
$ type rails
rails is /home/dskloet/.gem/ruby/3.0.0/bin/rails
Fri Jul 09 14:56:26 dskloet@xps: ~/rails
$ rails new hello ----minimal --skip-javascript --skip-sprockets
/home/dskloet/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems.rb:281:in `find_spec_for_exe': can't find gem railties (>= 0.a) with executable rails (Gem::GemNotFoundException)
	from /home/dskloet/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems.rb:300:in `activate_bin_path'
	from /home/dskloet/.gem/ruby/3.0.0/bin/rails:23:in `<main>'
```

**Comment by mdemare** [comment] 2021-07-09 13:19
So you also have installed RVM?

**Comment by dskloet** [comment] 2021-07-09 14:52
I don't know? Is that installed with `apt-get install ruby-dev`?

**Comment by dskloet** [comment] 2021-07-10 09:10
After running `rvm reset` it seems to work.

**Comment by hahmed** [comment] 2021-07-13 21:27
@dskloet did you manage to get rails up and running? If it's not working, could you give this guide a try, hopefully that helps you to get setup: https://gorails.com/setup/ubuntu/21.04

The bigger issue in this discussion sounds like it's related to a frustrating experience getting a new user from installing ruby/ bundler all the way to getting a rails app up and running. 

All we want to do is create a new rails app!

The other questions seem to be;
- What is the system ruby, why is it recommended not to use it?
- Why should I use a ruby manager?
- Why do I need bundler? This command does not work `gem install rails`

At the moment we currently do not cover that setup -- which I can understand is frustrating.

Let's say rails guides adds a section on setup, that does open the floor to a whole load of other setup related questions. As mentioned here https://github.com/rails/rails/issues/42709#issuecomment-874816317 I feel it's easier to move this discussion over into discourse...

**Comment by dskloet** [comment] 2021-07-14 08:10
Yes, after `rvm reset` I was able to run rails and serve the welcome page.
I haven't had time yet to try anything else after that.

**Comment by hahmed** [comment] 2021-07-14 12:39
> This is too much information for the README, but we could link to the rails guide (https://guides.rubyonrails.org/getting_started.html#creating-a-new-rails-project-installing-rails) more prominently, and expand the guide to cover installing both ruby and rails.

@mdemare 

I think maybe the link for "Getting started..." in point 5 is maybe a bit low and could be tied into point 1? That way perhaps a user will less likely try `gem install rails` if they have not setup ruby? Would you be open to creating a PR to address that?

<img width="1673" alt="Screenshot 2021-07-14 at 13 36 05" src="https://user-images.githubusercontent.com/658005/125623002-fdb6178d-ec8b-4dc6-b944-991e259976e2.png">

**Comment by mdemare** [comment] 2021-07-14 14:26
@hahmed Sure!

**Comment by hahmed** [comment] 2021-07-18 21:20
@dskloet seeing as you got this working I'm going to go ahead and close this ticket for now. Feel free to raise any more issues you find with the docs, or a PR to address them if you can 🙂

**Closed by hahmed** 2021-07-18 21:20 UTC
