### ISSUE TITLE
Overwriting minitest option parsing breaks minitest plugins that add options

### ISSUE THREAD

**Issue by grosser** [rails/rails#25046] opened 2016-05-17 04:25 UTC
This is not a big issue for me, just something I noticed and that seems like a bad practice / will make it impossible for other gems to add their own minitest options ...
### Steps to reproduce

```
gem install minitest-line
ruby test/integration/seed_test.rb --line 6
```
### Expected behavior

Allow other minitest plugins to add commandline options.
### Actual behavior

```
vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.rc1/lib/rails/test_unit/minitest_plugin.rb:57:in `plugin_rails_options': invalid option: --line (OptionParser::InvalidOption)
    from vendor/bundle/ruby/2.2.0/gems/minitest-5.8.4/lib/minitest.rb:191:in `block (2 levels) in process_args'
```
### System configuration

**Rails version**: 5.0.0.rc1 / Minitest 5.8.4

**Comment by sikachu** [comment] 2016-05-17 14:24
Thanks for reporting in. I think it's because we are using `OptionParser ` hence restricting the options that we're accepting. I think we can look into making it passing all options to underlying Minitest.

**Comment by kaspth** [comment] 2016-05-17 14:30
Good find! Happens because we've unshifted ourselves to be the first minitest plugin that gets it's options processed: https://github.com/rails/rails/commit/b9465e8755509cc79ad7492914a26c8ac3884de0.

I've worked up a possible solution at #25055.

**Comment by taq** [comment] 2017-01-11 18:40
Guys, I was updating an app to version 5 and just faced the problem referenced on this issue, is there any idea when it will be fixed? Guard running all the tests (when using `spring: true` on the Guardfile) or not running any tests just complicated a little there on my test approach with Guard. Thanks!

**Comment by grosser** [comment] 2017-01-11 19:02
Idea fix: "make minitest better" ... add all these nice enhancements to minitest itself ... see maxitest for more ideas on what to fix ...

**Comment by dreammaker** [comment] 2017-03-16 17:32
I would like to use the `minitest-autotest` gem, and I get an invalid `--server` option.  I think this is going to keep cropping up more and more as people upgrade to Rails 5.

What exactly is holding up the attached PR?

@grosser, what do you mean by "maxitest"?

**Comment by grosser** [comment] 2017-03-17 15:23
https://github.com/grosser/maxitest

**Comment by KjellMorgenstern** [comment] 2017-04-20 11:23
Is there any progress on this? As I understand from this ticket, the rails extension seems to prevent all the other extensions from adding their options.
Simply reversing the extension load order back to like it was in 4.2 is not an option, but maybe the rails plugin could deal with the options more carefully (if that is truly the cause of the issue).

**Comment by mmoll** [comment] 2017-07-05 18:35
#29572 is the recent approach, I guess...

**Closed** 2017-07-10 19:13 UTC
Labels: attached PR, railties, With reproduction steps
