### ISSUE TITLE
ActiveSupport::PerThreadRegistry is pre Fiber and not PerThread.

### ISSUE THREAD

**Issue by arthurnn** [rails/rails#30047] opened 2017-08-02 19:46 UTC
### Steps to reproduce

https://gist.github.com/arthurnn/9dc9a71cbbddac98a9dee2c79dfd7d05
`test_conn_swap_in_fiber` test will fail on that gist.

### Expected behavior
When setting a new `connection_handler` to `ActiveRecord::Base`, new Fibers, running on the same thread, should use that handler.

### Actual behavior
Because `ActiveRecord::RuntimeRegistry` uses `ActiveSupport::PerThreadRegistry`, that means the attributes created there will be per-thread and per-fiber, as `PerThreadRegistry` uses `Thread.current[]` method.

### System configuration
**Rails version**:
Latest

**Ruby version**:
Latest

I wonder if this is a by-design thing. see @fxn [comment](https://github.com/rails/rails/issues/19693#issuecomment-94164135)?
The issue here though is, setting a `connection_handler=` is a valid AR api. And it end-up been by fiber and not per-thread, which is a surprising behavior. 

@rafaelfranca @tenderlove @eileencodes @dhh @jeremy thoughts?

I found that issue when debugging some connection swapping issues at GitHub.
I assume Shopify would not have this problems because they use https://github.com/byroot/monorails/blob/d740c3a54a8da3c8f3a67eb414b65f50040e1f24/lib/monorails/per_thread_registry_40.rb

**Comment by tenderlove** [comment] 2017-08-02 23:26
I'd expect it to be per thread (not per fiber), but I'm not sure of the original intention.  @matthewd might have some thoughts on this.  Per-thread really seems like the right behavior for database connections anyway, so we could introduce an "actually per thread" registry in order to maintain backwards compatibility. 🤷‍♀️

**Comment by matthewd** [comment] 2017-08-03 06:10
I think it's by design for the connection, on the basis that things could get confused if you have multiple fibers entering and exiting transaction blocks (say), independently. https://github.com/rails/rails/pull/22630#r47997074

But I think it'd also be fair to claim this has never been given deep thought, and we've mostly relied on a model of one-fiber-per-thread. Probably need to work through the various possible combinations, and see whether we can find a useful pattern.

i.e., I agree it's unpleasantly surprising that gist doesn't work... but I'm also nervous that the obvious fix would create more surprises elsewhere.

**Comment by arthurnn** [comment] 2017-08-03 14:20
> I think it's by design for the connection, on the basis that things could get confused if you have multiple fibers entering and exiting transaction blocks (say)

So what you are saying is:
```
enum = Enumerator.new do |r|
  ActiveRecord::Base.transaction do 
   # Some db ops here
    r << 1
  end
  r << 2
end

enum.next
enum.next
```

something like that? I think that will change the transaction

**Comment by fxn** [comment] 2017-08-03 14:52
This was the concern I expressed in the discussion of https://github.com/rails/rails/issues/19693. The API says thread-local, and the implementation is fiber-local because `Thread#[]` is.

My proposal was to define an API with the three locality options, something in the line of

```ruby
mattr_accessor :pool, one_per: :process # default
mattr_accessor :pool, one_per: :thread
mattr_accessor :pool, one_per: :fiber
```

but there was a counter-argument of practicality, since few people uses fibers.

In any case, the API and implementation do not square, and has finally leaked in this use case.

**Comment by matthewd** [comment] 2017-08-03 15:38
Right, it probably won't matter for `connection_handler`.. I was thinking of the fact that the actual *connection* (within the pool, within the handler) is per-fiber. And now that I say that out loud, I realize it's actually not, because it doesn't use AS::PTR 😖. 

```ruby
enum = Enumerator.new do |r|
  ActiveRecord::Base.transaction do # A
   # Some db ops here
    r << 1
  end # B
  r << 2
end

ActiveRecord::Base.transaction do # C
  enum.next
end # D
enum.next
```

Without having actually run it full of putses, I believe something like the above would hit "surprise mode" -- the transaction started at A would be closed by D, and C by B. I think.

**Comment by sgrif** [comment] 2017-08-03 15:49
Is `Monitor` re-entrant per-thread or per-fiber? If it's the latter, that code would deadlock.

**Comment by matthewd** [comment] 2017-08-03 15:51
Per-thread I believe, but which monitor is being held across lines there? :confused:

**Comment by sgrif** [comment] 2017-08-03 15:52
`transaction do; end` synchronizes on the connection for the duration of the block

**Comment by matthewd** [comment] 2017-08-03 16:13
Oh, right, the new thing 👍🏻

**Comment by arthurnn** [comment] 2017-08-25 18:29
So I guess, because of the synchronization of transactions('the new thing') the surprising behaviour above is not a concern?
Should we change, at least the connection_handler to be per thread and not per fiber then?

**Comment by ioquatix** [comment] 2018-02-16 12:07
Was there ever an update to this?

**Comment by arthurnn** [comment] 2018-06-07 18:04
@ioquatix nop.
We have a monkey patch for this at GitHub source to go around the issue.

**Comment by eileencodes** [comment] 2018-08-31 20:59
Since I'm working on Rails multiple databases I'm going to reopen this as I think it's something we're definitely going to need to fix.

**Closed** 2018-11-20 22:46 UTC
Labels: activerecord

**Comment by ioquatix** [comment] 2019-08-28 00:06
@eileencodes unfortunately the way you chose to fix this issue breaks rails/activerecord for any web-server which is multi-fiber. But what is the benefit to be per-thread? I'm not clear on that.

**Comment by ioquatix** [comment] 2019-08-28 22:48
Sorry and thanks for feedback. I've identified some things I can improve on. I think what you are doing is fantastic - I see you putting in a huge amount of effort on large surface area and I'm sure many people, myself included, are grateful for your efforts.

This is a tricky issue as shown by all the previous discussion. I don't even know if there is a one-size-fits-all fix.

The reason why the change concerns me is because it silently breaks `falcon` with any `ActiveRecord` application, or any application which uses fibers with ActiveRecord.

- Main fiber. Begin transaction. AR connection checked out on thread.
- Fiber swapped. Some other query executes.
- Fiber swapped. Another transaction started.
- Fiber swapped. Transaction committed.

The interleaving of operations with a shared connection could create a lot of very weird issues.

If you assign to both thread-local and fiber-local, and default to fiber-local, I think you can get the best of both worlds.

```ruby
class Pool
	def self.connection_handler= value
		thread = Thread.current
		
		thread[:connection_handler] = value
		thread.thread_variable_set(:connection_handler, value)
	end
	
	def self.connection_handler
		thread = Thread.current

		return thread[:connection_handler] || thread.thread_variable_get(:connection_handler)
	end
end

Fiber.new do
	Pool.connection_handler = "A"
	
	puts "(1) Pool.connection_handler: #{Pool.connection_handler.inspect}"
	
	Fiber.new do
		puts "(2) Pool.connection_handler: #{Pool.connection_handler.inspect}"
	end.resume
	
	Fiber.new do
		Pool.connection_handler = "B"
		puts "(3) Pool.connection_handler: #{Pool.connection_handler.inspect}"
	end.resume
	
	puts "(4) Pool.connection_handler: #{Pool.connection_handler.inspect}"
end.resume
```

**Comment by ioquatix** [comment] 2019-08-28 23:01
Also, I'll make a PR. It's probably a good point for further discussion, since we can see if it actually works/breaks anything.
