### ISSUE TITLE
Column name not correctly escaped when grouping

### ISSUE THREAD

**Issue by noryus** [rails/rails#24785] opened 2016-04-29 15:12 UTC
### Steps to reproduce
Create a model Customer with an attribute 'from' of type string.
You can't perform Customer.group(:from).count 

### Expected behavior
It should not raise an error (even if from is a reserved SQL word).

### Actual behavior
It raise an error. The reason is  it does not escape correctly the column name:
SELECT COUNT(customers.\`from\`) AS count_customers_from, **from AS from** FROM \`customers\` GROUP BY \`analytics_customers\`.\`from\`
You must write Customer.group("customers.\`from\`").count in order to perform the request

### System configuration
**Rails version**:
activerecord-4.2.3
**Ruby version**:
2.2.0

**Comment by maclover7** [comment] 2016-04-29 19:36
Looks like the problem is fixed on master, but broken on 4-2-stable, via [this reproduction script](https://gist.github.com/maclover7/60e3fc71259174445f875f5dba95c698). Not sure if we want to find the commit that fixes this, and then backport it...

Assigning to @sgrif so he doesn't forget about this while he's moving :)

r? @sgrif

**Comment by jeremy** [comment] 2016-04-29 22:17
@maclover7 Which commit or PR fixed it on master? If it's a non-invasive bugfix, it's a candidate for 4-2-stable backport.

**Comment by maclover7** [comment] 2016-04-29 22:28
Wasn't able to find the commit / PR that fixed the bug -- git kept saying that it couldn't find a merge base :(

**Comment by vipulnsward** [comment] 2016-04-29 22:30
This was fixed in https://github.com/rails/rails/pull/21950
We can backport: https://github.com/vipulnsward/rails/commit/c2d33c4abf01ec25b2d1528a7dae923aef5a30af

**Comment by vipulnsward** [comment] 2016-04-29 22:34
Confirmed that https://gist.github.com/vipulnsward/b0c2bf8aec01512a8691b902e11fa618 fixes it.
@jeremy you would backport? Or a PR would do.

**Comment by jeremy** [comment] 2016-04-29 23:25
Nice @vipulnsward. Backport PR against 4-2-stable sounds good, though we'll need to be careful not to introduce behavior changes beyond the intended fix.

**Comment by vipulnsward** [comment] 2016-05-01 07:09
Closed by https://github.com/rails/rails/pull/24797

**Closed by vipulnsward** 2016-05-01 07:09 UTC
Labels: activerecord, With reproduction steps
