### ISSUE TITLE
Rails server doesn't start Puma on the correct port

### ISSUE THREAD

**Issue by lucaspiller** [rails/rails#28971] opened 2017-05-03 12:08 UTC
After upgrading to Rails 5.1, running `rails server` no longer starts the server on the default port of 3000 on my project. Weirdly it prints that it is starting on port 3000, but Puma is booted up on port 9292. If I pass the port number it works correctly.

I've tried creating a new Rails project, but can't reproduce it, so it must be something strange with my configuration, but I have no idea what it could be (it's a private project so I can't share it).

### Steps to reproduce

Run `bundle exec rails server`

### Expected behavior

Server should be started on port 3000.

### Actual behavior

Server is started on port 9292.

```
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
W, [2017-05-03T14:52:33.021141 #25863]  WARN -- : DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /home/luca/code/paytouch/pt_dashboard/config/initializers/callback_terminator.rb:5)
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
```

### System configuration

**Rails version**: 5.1
**Ruby version**: 2.4.1
**Puma version**: 3.8.2

Diff of Gemfile changes (the only thing that has changed) after upgrading from Rails 5.0.2 to 5.1: https://gist.github.com/lucaspiller/02be631352812417e5d4ffb4ce8e9044

config/puma.rb:

```
port ENV['PORT'] || 3000
environment ENV['RACK_ENV'] || 'development'
```

**Comment by alexcameron89** [comment] 2017-05-03 13:34
Hey @lucaspiller, if you're not able to reproduce the issue with a new Rails project, that usually means that it's a configuration issue. I tried myself and am not able to reproduce the issue.

Start by seeing if you have `PORT` environment variable set somewhere or if one of your Gems is conflicting with your application. I'm going to close this, but if you are able to reproduce the issue and a skeleton Rails app, I'll be happy to open it back up and take a look at it.

**Comment by astrashe** [comment] 2017-05-03 16:17
@alexcameron89 I'm having the same problem, and I can reproduce it.  I'm testing with Fedora Server 25.  I use Vagrant to spin these servers up, so I know I have a consistent, clean starting point.

It only happens to me when I use "-b 0.0.0.0".  If I use both -b and -p, the server starts on the specified port.  If I don't specify the port, Rails gives a message that says the server is starting on port 3000, but Puma's message says that it's listening on port 9292 (which is the actual port it uses).

I ran this example as root, but I've done it as a non-root user as well, and gotten the same results.

```
[root@localhost ~]# ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
[root@localhost ~]# rails -v
Rails 5.1.0
[root@localhost ~]# rails new portbug

[...]

root@localhost portbug]# echo $PORT

root@localhost ~]# cd portbug
[root@localhost portbug]# rails db:create
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
[root@localhost portbug]# rails s -b 0.0.0.0
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
```

**Comment by alexcameron89** [comment] 2017-05-03 17:06
Thank you @astrashe, I am able to reproduce that issue.

**Comment by maclover7** [comment] 2017-05-03 19:19
cc @schneems

**Comment by y-yagi** [comment] 2017-05-04 05:57
This is duplicate of https://github.com/puma/puma/issues/1255, and fixed by  https://github.com/puma/puma/pull/1277.

**Comment by micahbf** [comment] 2017-05-15 21:43
I suspect this is the same issue, but I can't confirm it - `-p` also became whitespace-sensitive in Rails 5.1.

Example:
```
% rails s -p9000
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://localhost:9000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.1-p112), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

Note that without a space, Rails sees the argument but Puma boots on the default 3000.

With a space, everything is peachy:

```
% rails s -p 9000
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://localhost:9000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.1-p112), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:9000
Use Ctrl-C to stop
```

**Comment by schneems** [comment] 2017-05-18 20:17
Works fine for me

```
$ rails server -p9000
/Users/schneems/.gem/ruby/2.4.1/gems/activesupport-5.0.1.rc2/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/Users/schneems/.gem/ruby/2.4.1/gems/activesupport-5.0.1.rc2/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
[tunemygc] not enabled
=> Booting Puma
=> Rails 5.0.1.rc2 application starting in development on http://localhost:9000
=> Run `rails server -h` for more startup options
/Users/schneems/.gem/ruby/2.4.1/gems/activesupport-5.0.1.rc2/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
I, [2017-05-18T15:16:29.471616 #28346]  INFO -- : Loaded Configuration: /Users/schneems/Documents/projects/codetriage/config/scout_apm.yml. Using environment: development
[28346] Puma starting in cluster mode...
[28346] * Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
[28346] * Min threads: 5, max threads: 5
```

**Comment by msyvr** [comment] 2017-05-18 21:16
Like @micahbf, I can replicate the issue. 
@schneems, I seem to not be able to find the
* Listening on tcp://0.0.0.0:9000
detail in your clip. If your port 3000 is already in use, does it still work? For me, that situation (and if the whitespace is omitted after -p) leads to the server automatically exiting.

**Comment by schneems** [comment] 2017-05-18 21:49
Ok I can repro this with rails 5.1.1

```
$ be rails s -p9000
[tunemygc] not enabled
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:9000
=> Run `rails server -h` for more startup options
I, [2017-05-18T16:46:31.136145 #76988]  INFO -- : Loaded Configuration: /Users/schneems/Documents/projects/codetriage/config/scout_apm.yml. Using environment: development
[76988] Puma starting in cluster mode...
[76988] * Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
[76988] * Min threads: 5, max threads: 5
[76988] * Environment: development
[76988] * Process workers: 2
[76988] * Preloading application
[76988] * Listening on tcp://0.0.0.0:3000
[76988] Use Ctrl-C to stop
[76988] - Worker 1 (pid: 76993) booted, phase: 0
[76988] - Worker 0 (pid: 76992) booted, phase: 0
```

Can you open a new issue? You can link back to this thread.

**Comment by micahbf** [comment] 2017-05-18 22:01
Created the issue: #29138 

Thanks!

**Comment by msyvr** [comment] 2017-05-18 22:02
Sorry, I'm new here... This issue was reopened by @alexcameron89. Did you want me to open a new issue anyhow?

**Comment by msyvr** [comment] 2017-05-18 22:02
Ignore that. @micahbf was faster

**Comment by y-yagi** [comment] 2017-06-03 09:49
Since Puma 3.9 was released, updating Puma solves the original issue.

**Comment by schneems** [comment] 2017-06-03 17:54
Thanks!

**Closed by schneems** 2017-06-03 17:54 UTC
Labels: railties, third party issue, With reproduction steps

**Comment by TechCanuck** [comment] 2017-07-06 14:53
Confirmed, upgrading to puma definitely solves this issue.

**Comment by schneems** [comment] 2017-07-06 15:34
Great

**Comment by MassMadankumar** [comment] 2017-12-13 11:08
root@instance-2:/mnt/zapstore.com/shopifyapp/zap# rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.0 (ruby 2.4.2-p198), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop

**Comment by tatyana12** [comment] 2019-04-23 21:49
How to get http instead of tsp as below to see  a page?
Puma starting in cluster mode...
[20539] * Version 3.12.0 (ruby 2.5.1-p57), codename: Llamas in Pajamas
[20539] * Min threads: 5, max threads: 5
[20539] * Environment: development
[20539] * Process workers: 2
[20539] * Preloading application
[20539] * Listening on tcp://localhost:9000
