### ISSUE TITLE
ParameterFilter raises on Hashs with Integer keys

### ISSUE THREAD

**Issue by paul** [rails/rails#39011] opened 2020-04-21 22:37 UTC
### Steps to reproduce

In a Rails console:

```
pry(main)> ActiveSupport::ParameterFilter.new([/password/]).filter(password: "secret", 42 => "secret")
```

### Expected behavior

We use the ParameterFilter in our app in a few places, particularly subscribers to Command objects to avoid logging secrets that get passed in. Sometimes one Command object will pass a hash to another that has integers for keys, rather than strings, the most common example being something the output of something like `User.where(stuff).index_by(&:id)`. 

When ParameterFilter is initialized with a list that includes a regex, this causes an exception to be raised when the filter attempts to run the regex against the integer key.

### Actual behavior

```
ActiveSupport::ParameterFilter.new([/password/]).filter(password: "secret", 42 => "secret")
TypeError: no implicit conversion of Integer into String
from /home/rando/.gem/ruby/2.6.6/gems/activesupport-6.0.2.2/lib/active_support/parameter_filter.rb:106:in `match?'
```

### System configuration
**Rails version**:
6.0.2.2

**Ruby version**:
2.6.6

**Comment by abhaynikam** [comment] 2020-04-22 05:32
@paul This issue was fixed in the commit: https://github.com/rails/rails/commit/e5d692a664c963968e42c2fe385e02392e86ddae 

I think Rails 6.0.2.2 doesn't have the change yet but it would be resolved in future versions. I am not sure when things are backported so maybe some core member could comment on that part.

I tested this on the latest master in Rails console and it works fine for me 🎉 
```
irb(main):001:0> ActiveSupport::ParameterFilter.new([/password/]).filter(password: "secret", 42 => "secret")
=> {:password=>"[FILTERED]", 42=>"secret"}
```

**Comment by eugeneius** [comment] 2020-04-22 06:59
This is a duplicate of https://github.com/rails/rails/issues/37428, and will be fixed in the next non-security release.

**Closed by eugeneius** 2020-04-22 06:59 UTC
Labels: activesupport

**Comment by paul** [comment] 2020-04-22 15:33
Ah, OK. I searched the issues for `ParameterFilter` and didn't find that one. Thanks!
