### ISSUE TITLE
rails new with version specified fails if newer version installed

### ISSUE THREAD

**Issue by vfonic** [rails/rails#29577] opened 2017-06-26 04:33 UTC
### Steps to reproduce

Run:

```sh
gem install rails -v 5.1.1
gem install rails -v 5.0.2
rails _5.0.2_ new new_app
```

### Expected behavior

New app is created.

### Actual behavior

Error is raised. Full stack pasted here:

```
/Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2278:in `check_version_conflict': can't activate activesupport-5.1.1, already activated activesupport-5.0.2 (Gem::LoadError)
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1404:in `activate'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent.rb:15:in `<top (required)>'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/logger_silence.rb:3:in `<top (required)>'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/logger.rb:1:in `<top (required)>'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support.rb:27:in `<top (required)>'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/generators.rb:6:in `<top (required)>'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/application.rb:1:in `<top (required)>'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/cli.rb:14:in `<top (required)>'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/exe/rails:9:in `<top (required)>'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/bin/rails:22:in `load'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/bin/rails:22:in `<main>'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/viktorfonic/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

### System configuration
**Rails version**:
5.0.2 / 5.1.1

**Ruby version**:
2.4.0
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Comment by y-yagi** [comment] 2017-06-26 04:40
Duplicate of #29113.  And this is problem of rubygems.  Ref https://github.com/rubygems/rubygems/issues/1931

**Closed** 2017-06-26 04:49 UTC
