### ISSUE TITLE
HABTM query not using the join table 

### ISSUE THREAD

**Issue by luisobo** [rails/rails#24717] opened 2016-04-24 16:17 UTC
Hi,

I believe I've found a bug with ActiveRecord. I've spent quite a while trying to figure out if there is  a problem with my models but I couldn't find it, in any case, I don't discard that option.
### Steps to reproduce

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do

  create_table "retweets", id: false, force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "tweet_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "retweets", ["tweet_id"], name: "index_retweets_on_tweet_id"
  add_index "retweets", ["user_id"], name: "index_retweets_on_user_id"

  create_table "tweets", force: :cascade do |t|
    t.string   "text"
    t.integer  "author_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "tweets", ["author_id"], name: "index_tweets_on_author_id"

  create_table "users", force: :cascade do |t|
    t.string   "username"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end

class User < ActiveRecord::Base

  has_many :tweets, inverse_of: :author, foreign_key: :author_id

  has_and_belongs_to_many :retweets, class_name: "Tweet", inverse_of: :retweeters, join_table: :retweets
end

class Tweet < ActiveRecord::Base
  belongs_to :author, class_name: "User", inverse_of: :tweets, foreign_key: :author_id

  has_and_belongs_to_many :retweeters, class_name: "User", inverse_of: :retweets, join_table: :retweets
end


class BugTest < Minitest::Test
  def test_association_stuff
    u1 = User.create!
    u2 = User.create!
    u3 = User.create!

    u1.tweets.create!(text: 'setting up my twittr')

    t1 = u1.tweets.first

    u2.retweets << t1

    # This is the problematic query
    retweets_by_u2 = Tweet.where(retweeters: [u2, u3])

    # This is fine
    assert_equal 1, u1.tweets.count
    assert_equal 1, u2.retweets.count
    assert_equal t1.id, u2.retweets.first.id

    # It will crash here, when resolving the retweets_by_u2 query
    result = retweets_by_u2.to_a
    assert_equal t1.id, result.first.id
    assert_equal 1, retweets_by_u2.count
  end
end
```
### Expected behavior

When querying for `Tweet.where(retweeters: list_of_users)` I'd expect to get the list of tweets retweeted by the users in the provided list (u2 and u3) in the example. It should also work with other queries. 
### Actual behavior

It crashes. I think it does not use the join table "retweets" and it tries to query the "tweets" table instead with a column "user_id".

This is the error:

```
Finished in 0.063514s, 15.7446 runs/s, 47.2338 assertions/s.

  1) Error:
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: tweets.user_id: SELECT "tweets".* FROM "tweets" WHERE "tweets"."user_id" IN (2, 3)
    /Users/luis/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
    /Users/luis/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
    /Users/luis/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:193:in `block in exec_query'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:552:in `block in log'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:546:in `log'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:190:in `exec_query'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:376:in `select'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/relation.rb:699:in `exec_queries'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/relation.rb:580:in `load'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/relation.rb:260:in `records'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-8f22006c6923/activerecord/lib/active_record/relation.rb:256:in `to_a'
```

As you can see, the query it tries to execute is `SELECT "tweets".* FROM "tweets" WHERE "tweets"."user_id" IN (2, 3)` but I think it should be `SELECT "tweets".* FROM "tweets" INNER JOIN "retweets" ON "retweets"."tweet_id" = "tweets"."id" WHERE "retweets"."user_id" IN (2, 3)`
### System configuration

**Rails version**:
rails 5.0.0.beta3 from git://github.com/rails/rails.git (at master@8f22006)

**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

**Comment by maclover7** [comment] 2016-04-24 17:46
Hmm, looks like the `join_table `argument is tripping up Active Record. Would you be willing to look into a fix for this? Also, has this worked for you on previous versions of Rails?

**Comment by luisobo** [comment] 2016-04-24 18:20
I only tried it in rails 4.2.3 and it didn't work. Re: fix, I'm afraid I cannot commit the time at the moment -- I wouldn't even know where to start. I'd be happy to provide any additional info necessary.

**Comment by bquorning** [comment] 2016-04-24 21:56
I can’t find any documentation saying you can call `Tweet.where(retweeters: [u2, u3])`. As I read [the guides](http://guides.rubyonrails.org/association_basics.html#methods-added-by-has-and-belongs-to-many-collection-where), you can only call `@tweet.where(user_id: [u2, u3])` on a single instance of `Tweet`.

In your use case, I would opt for using `has_many, through` and have a proper `Retweet` class. It can keep the same columns as it has now, just add an `:id` column. Now, you can search for `Retweet.where(user: [u2, u3])`.

**Comment by vipulnsward** [comment] 2016-04-27 14:04
@luisobo can you confirm if this is an issue with hm:t for you?

**Comment by vipulnsward** [comment] 2016-04-27 17:27
I believe what you are trying to achieve is:
```ruby 
Tweet.joins(:retweeters).where(retweets: {user_id:u2.id})
```
Right now, `retweeters` doesn't resolve in the way you are trying to achieve(It can't incur the join as well as can't find the join table to use, in the context you are executing it, ie. Tweet).

**Comment by luisobo** [comment] 2016-04-27 21:41
@vipulnsward re: hm:t I fails with the same error, see example and error below. 

re: `Tweet.joins(:retweeters).where(retweets: {user_id:u2.id})` yep, that works, with both habtm and hm:t. The downside is that it exposes implementation details of the association at query time, namely, the name of the join table and the name of the fk column. It's sad because rails has all that info :(

The way I see it, there are two alternatives, if the query I was using (without the `joins` was supposed to work in the first place (I don't know), this would be a bug, I guess. 

Alternatively, if rails is behaving as it was intended to, and the current proper way of making that query is with that `joins`, I'd turn this into a feature request, if you will, for the reason I mentioned. It believe it should either work without the `joins` (preferably) or it should give a proper error message and/or be documented. Or else, whatcha think?

Thanks!

Here is the hm:t example and error.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do

  create_table "retweets", id: false, force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "tweet_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "retweets", ["tweet_id"], name: "index_retweets_on_tweet_id"
  add_index "retweets", ["user_id"], name: "index_retweets_on_user_id"

  create_table "tweets", force: :cascade do |t|
    t.string   "text"
    t.integer  "author_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "tweets", ["author_id"], name: "index_tweets_on_author_id"

  create_table "users", force: :cascade do |t|
    t.string   "username"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end

class User < ActiveRecord::Base

  has_many :tweets, inverse_of: :author, foreign_key: :author_id

  # has_and_belongs_to_many :retweets, class_name: "Tweet", inverse_of: :retweeters, join_table: :retweets, foreign_key: :user_id, association_foreign_key: :tweet_id
  has_many :retweets, inverse_of: :user
  has_many :retweeted_tweets, through: :retweets, inverse_of: :retweeters, source: :tweet

  def timeline
    Tweet.where(author: following)
  end



end

class Tweet < ActiveRecord::Base
  belongs_to :author, class_name: "User", inverse_of: :tweets, foreign_key: :author_id

  # has_and_belongs_to_many :retweeters, class_name: "User", inverse_of: :retweets, join_table: :retweets, foreign_key: :tweet_id, association_foreign_key: :user_id
  has_many :retweets, inverse_of: :tweet
  has_many :retweeters, through: :retweets, inverse_of: :retweeted_tweets, source: :user
end

class Retweet < ActiveRecord::Base
  belongs_to :user, inverse_of: :retweets
  belongs_to :tweet, inverse_of: :retweets
end


class BugTest < Minitest::Test
  def test_association_stuff
    u1 = User.create!
    u2 = User.create!
    u3 = User.create!

    u1.tweets.create!(text: 'setting up my twittr')

    t1 = u1.tweets.first

    u2.retweets.create(tweet: t1)

    

    retweets_by_u2 = Tweet.where(retweeters: [u2, u3])

    # This one works tho
    # retweets_by_u2 = Tweet.joins(:retweeters).where(retweets: { user_id: [u2, u3]})

    # This is fine
    assert_equal 1, u1.tweets.count
    assert_equal 1, u2.retweeted_tweets.count
    assert_equal t1.id, u2.retweeted_tweets.first.id

    # It will crash here, when resolving the retweets_by_u2 query
    result = retweets_by_u2.to_a
    assert_equal t1.id, result.first.id
    assert_equal 1, retweets_by_u2.count
  end
end


# Actual query
# SELECT "tweets".* FROM "tweets" WHERE "tweets"."user_id" IN (2, 3)

# Expected query
# SELECT "tweets".* FROM "tweets" INNER JOIN "retweets" ON "retweets"."tweet_id" = "tweets"."id" WHERE "retweets"."user_id" IN (2, 3)
```

```
Finished in 0.054277s, 18.4241 runs/s, 55.2723 assertions/s.

  1) Error:
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: tweets.user_id: SELECT "tweets".* FROM "tweets" WHERE "tweets"."user_id" IN (2, 3)
    /Users/luis/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
    /Users/luis/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
    /Users/luis/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:196:in `block in exec_query'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:548:in `block in log'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:542:in `log'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:193:in `exec_query'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/relation.rb:699:in `exec_queries'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/relation.rb:580:in `load'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/relation.rb:260:in `records'
    /Users/luis/.rvm/gems/ruby-2.2.2/bundler/gems/rails-da2dc68c86d4/activerecord/lib/active_record/relation.rb:256:in `to_a'
    ./bugreport.rb:102:in `test_association_stuff'
```

**Comment by vipulnsward** [comment] 2016-04-28 19:51
Ref: https://github.com/rails/rails/commit/6a6c4c459106e2d9b76dd1233133a2bf30866ab0

**Comment by kamipo** [comment] 2017-10-20 05:51
Requiring `joins` is an expected behavior.
I'm giving this a close because this is a feature request, and we reserve the issue tracker for issues only.

**Closed by kamipo** 2017-10-20 05:51 UTC
Labels: activerecord, With reproduction steps
