### ISSUE TITLE
ActiveRecord inconsistency when assigning invalid existing/new has_many records

### ISSUE THREAD

**Issue by Roko131** [rails/rails#35168] opened 2019-02-05 16:54 UTC
### Short Explanation
Using has_many assignment (collection=(objects) acts differently if an invalid associated object is new or existing.
### Steps to reproduce

```ruby
class User < ApplicationRecord
  has_many :posts, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :posts
end

class Post < ApplicationRecord
  belongs_to :user, inverse_of: :posts
  validates :content, exclusion: { in: %w(bad evil)}
end

# creating a user and a post:
user = User.create(name: 'John')
post = user.posts.create(content: 'post1')

user1 = User.first
user_posts_ar1 = user1.posts.to_a
user_posts_ar1.first.content = 'bad' # editing an existing post- making it invalid
user1 = User.first
user1.posts = user_posts_ar1 # doesn't raise error
user1.save

user2 = User.first
user_posts_ar2 = user2.posts.to_a
user_posts_ar2 << user.posts.new(content: 'bad') # creating a new post - invalid one
user2 = User.first
user2.posts = user_posts_ar2 # raises ActiveRecord::RecordNotSaved (Failed to replace posts because one or more of the new records could not be saved.)
# user2.save
```

### Expected behavior

`user1.posts = user_posts_ar` should act as `user2.posts = user_posts_ar`
Both containing an invalid post. only different is that user2's invalid post is **new**
They should (In my humble opinion) both either raise exception or both not.

### Actual behavior

`user1.posts = user_posts_ar` doesn't raise error unlike
`user2.posts = user_posts_ar` which does raise error

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3

**Comment by gmcgibbon** [comment] 2019-02-06 23:57
[Test case](https://gist.github.com/gmcgibbon/f3626bf950f5bbb416c4490d032e764e)

You'll find in the first example, ActiveRecord won't save replaced records (because they are the same). In the second example, it will try to save the replaced records if the collection is different here: https://github.com/rails/rails/blob/9cc463ed7b7be098602b72a98f72220ea6466ba2/activerecord/lib/active_record/associations/collection_association.rb#L253-L257

This save seems to be intended behaviour (see [tests](https://github.com/rails/rails/blob/master/activerecord/test/cases/associations/has_many_associations_test.rb#L1926)), changing it would break legacy applications. As such, I'm going to close this. If you want to raise an error in the first example, try using `#save!` instead. Thank you for the report.

**Closed by gmcgibbon** 2019-02-06 23:57 UTC
Labels: activerecord
