### ISSUE TITLE
LoadError for ffi when creating a new rails app

### ISSUE THREAD

**Issue by parmort** [rails/rails#36342] opened 2019-05-25 02:29 UTC
### Steps to reproduce
`rails new app_name`

### Expected behavior
Rails creates a new app, sets it up, etc.

### Actual behavior

Here's the exact command output (gotten using `tee`):
```
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /home/nolan/code/app_name/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_0.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_6_0.rb
         run  bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies......
Using rake 12.3.2
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/lib/ruby/gems/2.6.0
  /usr/lib/ruby/gems/2.6.0/build_info
  /usr/lib/ruby/gems/2.6.0/cache
  /usr/lib/ruby/gems/2.6.0/doc
  /usr/lib/ruby/gems/2.6.0/extensions
  /usr/lib/ruby/gems/2.6.0/gems
  /usr/lib/ruby/gems/2.6.0/specifications
Using concurrent-ruby 1.1.5
Using i18n 1.6.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using zeitwerk 2.1.6
Using activesupport 6.0.0.rc1
Using builder 3.2.3
Using erubi 1.8.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.3
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 6.0.0.rc1
Using rack 2.0.7
Using rack-test 1.1.0
Using actionpack 6.0.0.rc1
Using nio4r 2.3.1
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using actioncable 6.0.0.rc1
Using globalid 0.4.2
Using activejob 6.0.0.rc1
Using activemodel 6.0.0.rc1
Using activerecord 6.0.0.rc1
Using mimemagic 0.3.3
Using marcel 0.3.3
Using activestorage 6.0.0.rc1
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailbox 6.0.0.rc1
Using actionmailer 6.0.0.rc1
Using actiontext 6.0.0.rc1
Using public_suffix 3.0.3
Using addressable 2.6.0
Using bindex 0.7.0
Using msgpack 1.2.10
Using bootsnap 1.4.4
Using bundler 2.0.1
Using byebug 11.0.1
Using regexp_parser 1.5.1
Using xpath 3.2.0
Using capybara 3.21.0
Using childprocess 1.0.1
Using ffi 1.11.1
Using jbuilder 2.9.1
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using ruby_dep 1.5.0
Using listen 3.1.5
Using method_source 0.9.2
Using puma 3.12.1
Using rack-proxy 0.6.5
Using thor 0.20.3
Using railties 6.0.0.rc1
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 6.0.0.rc1
Using rubyzip 1.2.3
Using sass-listen 4.0.0
Using sass 3.7.4
Using tilt 2.0.9
Using sass-rails 5.0.7
Using selenium-webdriver 3.142.3
Using spring 2.0.2
Using spring-watcher-listen 2.0.1
Using sqlite3 1.4.1
Using turbolinks-source 5.2.0
Using turbolinks 5.2.0
Using web-console 4.0.0
Using webdrivers 3.9.4
Using webpacker 4.0.2
Bundle complete! 17 Gemfile dependencies, 75 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rails: spring inserted
       rails  webpacker:install
RAILS_ENV=development environment is not defined in config/webpacker.yml, falling back to production environment
rails aborted!
LoadError: cannot load such file -- ffi
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/evented_file_update_checker.rb:110:in `boot!'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/evented_file_update_checker.rb:68:in `initialize'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/i18n_railtie.rb:60:in `new'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/i18n_railtie.rb:60:in `initialize_i18n'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/i18n_railtie.rb:18:in `block in <class:Railtie>'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application/finisher.rb:123:in `block in <module:Finisher>'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:32:in `instance_exec'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:32:in `run'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:60:in `run_initializers'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application.rb:362:in `initialize!'
/home/nolan/code/app_name/config/environment.rb:5:in `<main>'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application.rb:338:in `require_environment!'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application.rb:514:in `block in run_tasks_blocks'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/command.rb:48:in `invoke'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands.rb:18:in `<main>'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/home/nolan/code/app_name/bin/rails:9:in `<top (required)>'
/home/nolan/code/app_name/bin/spring:15:in `require'
/home/nolan/code/app_name/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'

Caused by:
Bootsnap::LoadPathCache::FallbackScan: 

Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
```

### System configuration
**Rails version**: `Rails 6.0.0.rc1`, installed with `gem install rails --pre`

**Ruby version**: `2.6.3p62`

**Comment by edudepetris** [comment] 2019-05-26 01:39
I'm not able to reproduce this behaviour with 
- Rails 6.0.0.rc1  installed with gem install rails --pre
- Ruby 2.6.1
- MacOs Mojave 10.14.5

i got a new rails app, setted up properly.

**Comment by parmort** [comment] 2019-05-27 00:50
After downgrading to `5.2.3`, everything seems to work fine. Could there be some version inconsistency for `ffi`, `bootsnap`, or `webpacker`?

**Comment by prathamesh-sonpatki** [comment] 2019-05-27 15:42
Can you upload a sample application on Github that reproduces the issue? Thanks.

**Comment by parmort** [comment] 2019-05-27 20:14
Here's the repo: https://github.com/parmort/rails-test-app

I'm not sure how helpful this will be, since this happens while rails is creating the directory and the files (I think). Bundler definitely hasn't run yet.

**Comment by parmort** [comment] 2019-05-27 22:21
Update: in rails `5.2.3`, running `rails s` throws the error: 
```
/usr/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- ffi (LoadError)
```

This was run after a standard 5.2.3 `rails new app`. App can be found here: https://github.com/parmort/rails-test-app/tree/rails-523

**Comment by y-yagi** [comment] 2019-05-28 23:27
@parmort  Can you try creating a new app with `skip-bootsnap` option? 

```bash
$ rails new app_name --skip-bootsnap 
```

**Comment by parmort** [comment] 2019-05-31 20:44
Yeah, the generated files are available [here](https://github.com/parmort/rails-test-app/tree/6-no-bootsnap). I still got an error:
```
       exist  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Reinitialized existing Git repository in /home/nolan/code/rails-test-app/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_0.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_6_0.rb
         run  bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies......
Using rake 12.3.2
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/lib/ruby/gems/2.6.0
  /usr/lib/ruby/gems/2.6.0/build_info
  /usr/lib/ruby/gems/2.6.0/cache
  /usr/lib/ruby/gems/2.6.0/doc
  /usr/lib/ruby/gems/2.6.0/extensions
  /usr/lib/ruby/gems/2.6.0/gems
  /usr/lib/ruby/gems/2.6.0/specifications
Using concurrent-ruby 1.1.5
Using i18n 1.6.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using zeitwerk 2.1.6
Using activesupport 6.0.0.rc1
Using builder 3.2.3
Using erubi 1.8.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.3
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 6.0.0.rc1
Using rack 2.0.7
Using rack-test 1.1.0
Using actionpack 6.0.0.rc1
Using nio4r 2.3.1
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using actioncable 6.0.0.rc1
Using globalid 0.4.2
Using activejob 6.0.0.rc1
Using activemodel 6.0.0.rc1
Using activerecord 6.0.0.rc1
Using mimemagic 0.3.3
Using marcel 0.3.3
Using activestorage 6.0.0.rc1
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailbox 6.0.0.rc1
Using actionmailer 6.0.0.rc1
Using actiontext 6.0.0.rc1
Using public_suffix 3.1.0
Using addressable 2.6.0
Using bindex 0.7.0
Using bundler 2.0.1
Using byebug 11.0.1
Using regexp_parser 1.5.1
Using xpath 3.2.0
Using capybara 3.22.0
Using childprocess 1.0.1
Using ffi 1.11.1
Using jbuilder 2.9.1
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using ruby_dep 1.5.0
Using listen 3.1.5
Using method_source 0.9.2
Using puma 3.12.1
Using rack-proxy 0.6.5
Using thor 0.20.3
Using railties 6.0.0.rc1
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 6.0.0.rc1
Using rubyzip 1.2.3
Using sass-listen 4.0.0
Using sass 3.7.4
Using tilt 2.0.9
Using sass-rails 5.0.7
Using selenium-webdriver 3.142.3
Using spring 2.0.2
Using spring-watcher-listen 2.0.1
Using sqlite3 1.4.1
Using turbolinks-source 5.2.0
Using turbolinks 5.2.0
Using web-console 4.0.0
Using webdrivers 4.0.0
Using webpacker 4.0.6
Bundle complete! 16 Gemfile dependencies, 73 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rails: spring inserted
       rails  webpacker:install
RAILS_ENV=development environment is not defined in config/webpacker.yml, falling back to production environment
rails aborted!
LoadError: cannot load such file -- ffi
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/evented_file_update_checker.rb:110:in `boot!'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/evented_file_update_checker.rb:68:in `initialize'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/i18n_railtie.rb:60:in `new'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/i18n_railtie.rb:60:in `initialize_i18n'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/i18n_railtie.rb:18:in `block in <class:Railtie>'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application/finisher.rb:123:in `block in <module:Finisher>'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:32:in `instance_exec'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:32:in `run'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:60:in `run_initializers'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application.rb:362:in `initialize!'
/home/nolan/code/rails-test-app/config/environment.rb:5:in `<top (required)>'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/home/nolan/.gem/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application.rb:338:in `require_environment!'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application.rb:514:in `block in run_tasks_blocks'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/command.rb:48:in `invoke'
/home/nolan/.gem/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
/home/nolan/code/rails-test-app/bin/rails:9:in `require'
/home/nolan/code/rails-test-app/bin/rails:9:in `<top (required)>'
/home/nolan/code/rails-test-app/bin/spring:15:in `require'
/home/nolan/code/rails-test-app/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
```

**Comment by y-yagi** [comment] 2019-05-31 23:59
@parmort Thanks for your help! 
Can you specify `config.autoloader = :classic` to https://github.com/parmort/rails-test-app/tree/6-no-bootsnap? 

```diff 
diff --git a/config/application.rb b/config/application.rb
index a6c63a9..8dfbdb6 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -10,6 +10,7 @@ module App
   class Application < Rails::Application
```

After that, please try to run `bin/rails webpacker:install`.

**Comment by fxn** [comment] 2019-06-01 05:46
I cannot reproduce using the RC and Ruby 2.6.3p62.

Does

```
ruby -rffi -e1
```

err in your system?

**Comment by parmort** [comment] 2019-06-07 19:17
@fxn Yes, it throws a `cannot load such file` error.

**Comment by fxn** [comment] 2019-06-07 19:29
Squares.

So I believe you should try first to get `ffi` to load in that one-liner, seems like something needs to be debugged in your installation. Once you solve that, the Rails command should just work.

I am curious about the source of the error, but if you don't mind I'll close the issue because it does not seem to be a Rails issue.

But if once understood you'd like to write a followup, please do so!

**Closed** 2019-06-07 19:29 UTC

**Comment by parmort** [comment] 2019-06-07 19:51
OK, I got it working. Not quite sure how, but I uninstalled `ffi`, removed the `/usr/lib/ruby/gems/2.6.0` directory, and ran `rails new` with no issues on `6.0.0.rc1`.
