### ISSUE TITLE
`ActionDispatch::IntegrationTest` prefixes `main_app` URL helpers with the `at` of the last call to a `Rails::Engine`-provided controller 

### ISSUE THREAD

**Issue by TastyPi** [rails/rails#46302] opened 2022-10-21 21:49 UTC
### Steps to reproduce

I could not figure out how to reproduce it in a single file, but I have a minimal repo demonstrating the issue at https://github.com/TastyPi/rails-routes-issue. The `main.rb` file has been commented to explain everything I tried.

There are several stars that need to align in order for this bug to appear, but they happened to me in a real app so I guess I'm lucky like that.

Required state:
 1. Tests are run with `RAILS_ENV=test` (removing that from my reproduction makes the test pass somehow)
 1. The app mounts an engine that provides a controller
 1. During an `ActionDispatch::IntegrationTest` call the engine's controller
 1. After the engine controller call, URL helpers for the main application either prefix paths with the engine's mount path if `sprockets-rails` is a dependency, or fail with a `RuntimeError` if it isn't.

### Expected behavior

URL helpers for the main app should behave consistently and not add engine mount path prefixes.

### Actual behavior

After calling an engine's controller `ActionDispatch::IntegrationTest` starts prefixing main app route helpers with the engine's mount path.

Curiously, if the Rails app does not depend on `sprockets-rails` then using the URL helper after the engine controller call results in the following error:

```
RuntimeError: In order to use #url_for, you must include routing helpers explicitly. For instance, `include Rails.application.routes.url_helpers`.
```

I don't know if that's because of something specific to `sprockets-rails` or a weird coincidence. 

Note that the helpers work correctly *before* calling the engine.

### System configuration
**Rails version**: Discovered in 7.0.4, reproduction is using main (commit [7fdcbe7](https://github.com/rails/rails/commit/7fdcbe747f7ab5ef664b894f73c8e0ada04c5c50) as of time of writing)

**Ruby version**: 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by skipkayhil** [comment] 2022-10-22 22:04
Hey @TastyPi, thanks for opening an issue! I believe this is a duplicate of #45500, so I'm going to close this. Feel free to let me know if you think this is different, or chime in over there with any info you have

**Closed by skipkayhil** 2022-10-22 22:04 UTC

**Comment by TastyPi** [comment] 2022-10-22 23:07
@skipkayhil yes that does sound the same as mine, I'll follow along there
