### ISSUE TITLE
System tests ignore active_job.queue_adapter settings 

### ISSUE THREAD

**Issue by thomas07vt** [rails/rails#37537] opened 2019-10-23 15:17 UTC
### Steps to reproduce
1. Set the active job queue adapter to inline for test environments:
```ruby
# config/environments/test.rb
config.active_job.queue_adapter = :inline
```
2. Have some controller deliver an email later:

```ruby
#app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
    mail = ApplicationMailer.test_email.deliver_later
    render json: mail.as_json
  end
end
```
3. Test this controller action using a system test, and assert that the job was processed inline:
```ruby
require "application_system_test_case"

class AdapterTest < ApplicationSystemTestCase
  test "visiting the index" do
    assert(Rails.application.config.active_job.queue_adapter == :inline)
    visit root_url
    assert(ActionMailer::Base.deliveries.length == 1)
  end
end
```

### Expected behavior
I expect the inline queue adapter to be used by active job (this is the case for 5.2 but not for 6.0)

### Actual behavior
ActiveJob used the ActiveJob::QueueAdapters::TestAdapter.

This [PR #33849](https://github.com/rails/rails/pull/33849/files) makes a change to include the  ActiveJob::TestHelper module in integration tests.

This causes System tests to ignore the Rails.application.config.active_job.queue_adapter setting (set for example in config/environments/test.rb file.)

That module defines a before_setup method here: activejob-6.0.0/lib/active_job/test_helper.rb:36 which sets the test adapter:

```ruby
def before_setup # :nodoc:
  test_adapter = queue_adapter_for_test

  queue_adapter_changed_jobs.each do |klass|
    klass.enable_test_adapter(test_adapter) # this method sets @_test_adapter
  end

  clear_enqueued_jobs
  clear_performed_jobs
  super
end
```

It also defines a new #queue_adapter method with this:

```ruby
def queue_adapter
  self._test_adapter.nil? ? super : self._test_adapter
end
```

And since we are setting the @_test_adapter in the `before_setup` method, this will always return ActiveJob::QueueAdapters::TestAdapter regardless of the Rails.application.config.active_job.queue_adapter config settings.

I assume that rails should respect the queue_adapter settings and am happy to PR a fix for this but I wasn't sure if there was a proper hierarchy to to use when setting the queue adapter in tests.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.5

**Comment by gmcgibbon** [comment] 2019-10-23 16:04
Thanks for reporting! This is a duplicate of https://github.com/rails/rails/issues/37270 so I'm going to close this. We're currently working toward a fix.

**Closed by gmcgibbon** 2019-10-23 16:04 UTC
Labels: With reproduction steps, activejob
