### ISSUE TITLE
Controllers still try to render view when using "render json"

### ISSUE THREAD

**Issue by anthonator** [rails/rails#23923] opened 2016-02-27 04:03 UTC
### Steps to reproduce

**Routes**

```ruby
Rails.application.routes.draw do
  resources :providers, only: [:create]
end
```

**Controller**

```ruby
class ProvidersController < ApplicationController
  def create
    render json: { hello: 'world' }
  end
end
```

Make a POST HTTP request to `/providers` or `/providers.json` with `Accept` and `ContentType` headers set to `application/json`.

**EDIT** In order to reproduce this you will need to have `jbuilder` as a dependency.

### Expected behavior
Expecting the following JSON to render:

```js
{
   "hello": "world"
}
```

### Actual behavior
Get the following error:

```
ActionView::MissingTemplate:
       Missing template providers/create, application/create with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
         * "/usr/src/app/app/views"
```

Rails still seems to be attempting to render a view template rather than the value provided to `render json`.

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.3.0

**Comment by chashmeetsingh** [comment] 2016-02-27 07:31
Not able to reproduce

Started POST "/providers" for ::1 at 2016-02-27 13:00:37 +0530
Processing by ProvidersController#create as */*
  Parameters: {"ContentType"=>"application/json"}
Completed 200 OK in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms)

<img width="231" alt="screen shot 2016-02-27 at 12 55 01 pm" src="https://cloud.githubusercontent.com/assets/8962264/13371682/307a7942-dd52-11e5-908c-3f5a1a323caa.png">
@anthonator

**Comment by maclover7** [comment] 2016-02-27 14:35
Unable to reproduce using [this test script](https://gist.github.com/maclover7/babd04216822e1d64646). Would you be able to create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), or a bare-bones Rails application, that would demonstrate the problem you are seeing?

**Comment by anthonator** [comment] 2016-02-27 17:17
This only seems to happen when `jbuilder` is a dependency. I'll have a sample app up in a second.

**Comment by anthonator** [comment] 2016-02-27 17:21
https://github.com/anthonator/rails_23923

If you add and remove `jbuilder` in the Gemfile you'll see it work and not work.

**Comment by chashmeetsingh** [comment] 2016-02-27 18:01
right same error

**Comment by maclover7** [comment] 2016-02-27 18:08
Hmm... this sounds like an error specifically within jbuilder. Can you open up an issue on [https://github.com/rails/jbuilder](https://github.com/rails/jbuilder)?

**Comment by anthonator** [comment] 2016-02-27 18:10
I can but this isn't an issue with the same version of jbuilder in 4.2.

**Comment by anthonator** [comment] 2016-02-27 18:12
Being discussed in jbuilder issues: https://github.com/rails/jbuilder/issues/317

**Comment by anthonator** [comment] 2016-02-27 21:14
A workaround:

```ruby
render plain: { hello: 'world' }.to_json, content_type: 'application/json'
```

**Comment by maclover7** [comment] 2016-02-27 21:41
@anthonator Would you be willing to do a git bisect to try and find where this problem was introduced?

**Comment by akshaymohite** [comment] 2016-02-28 08:45
For everyone to be on the same page: The problem is with `api_only` applications.
This works in 4.2 because we didn't have api only applications back then.

**Comment by mysmallidea** [comment] 2016-03-19 20:20
I'm also having this problem, just like @anthonator described. Json responses are raising ActionView::MissingTemplate instead of rendering inline json. 

The example app above does reproduce it for me.

**Comment by atomkirk** [comment] 2016-04-06 21:05
I am having the exact same problem, same set up.

**Comment by prathamesh-sonpatki** [comment] 2016-04-10 06:48
@rafaelfranca Should this be a blocker for 5.0?

**Comment by sharpone74** [comment] 2016-04-14 05:41
Same issue, rails API only, jbuilder included.

**Comment by jeremy** [comment] 2016-04-15 16:58
Moving to #24178

**Closed by jeremy** 2016-04-15 16:58 UTC
Labels: actionpack, attached PR, With reproduction steps

**Comment by hopewise** [comment] 2020-01-31 06:25
I am not using jbuilder, I still have this issue, I tried everything, kindly check here: https://stackoverflow.com/questions/59962060/why-rails-fails-to-detect-ajax-request-in-production

**Comment by selcuktoklucu** [comment] 2021-11-16 05:39
I'm having the same issue with default devise controllers (for example in `SessionsController < Devise::SessionsController` class) only when I wanna use `ActionView::Layouts` in some parts of the application.

If I remove the `ActionView::Layouts` from `ApplicationController`, rendering with `render json: json_object` totally works but with layouts it throws the error : `ActionView::MissingTemplate`.
