### ISSUE TITLE
`ActiveModel::Errors#added?` does not match custom message symbol

### ISSUE THREAD

**Issue by kmiyake** [rails/rails#36334] opened 2019-05-23 08:46 UTC
### Steps to reproduce

From Rails 5.2.0, `ActiveModel::Errors#added?` does not match custom message symbol. (But when v5.1.7 it is matched custom message symbol.)
I don't know we should respect `:message` option or not.
But I think if it is used `:message` option with symbol, we should respect it.

See below test:

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "active_model"
require "minitest/autorun"

class Person
  include ActiveModel::Model

  attr_accessor :nickname
end

class BugTest < Minitest::Test
  def test_validates_format_of_setting_custom_message_symbol
    Person.validates_format_of(:nickname, with: /\A[a-z]+\z/, message: :blank)

    person = Person.new(nickname: "123")

    assert_predicate person, :invalid?
    assert_equal person.errors.added?(:nickname, :blank), true
  end
end
```

```
# Running:

F

Failure:
BugTest#test_validates_format_of_setting_custom_message_symbol [errors_added.rb:29]:
Expected: false
  Actual: true


rails test errors_added.rb:23



Finished in 0.018101s, 55.2456 runs/s, 110.4911 assertions/s.
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

### Expected behavior
Return `true`

### Actual behavior
Return `false`

### System configuration
**Rails version**:
master

**Ruby version**:
2.6.3

**Comment by rafaelfranca** [comment] 2019-05-23 18:05
Duplicate of #34629

**Closed by rafaelfranca** 2019-05-23 18:05 UTC

**Comment by kmiyake** [comment] 2019-05-23 21:23
I'm sorry. I didn't check as I should have done.
Thank you for your information.
