### ISSUE TITLE
Eager loading on polymorphic association fails

### ISSUE THREAD

**Issue by dimonzozo** [rails/rails#15965] opened 2014-06-29 10:12 UTC
When I'm trying to eager_load two entities through single polymorphic associations - AR fails and generates wrong SQL conditions on second one.

`Hotel.eager_load(:cake_designers, :drink_designers)`

    SELECT "hotels"."id"          AS t0_r0, 
           "cake_designers"."id"  AS t1_r0, 
           "drink_designers"."id" AS t2_r0 
    FROM   "hotels" 
           LEFT OUTER JOIN "departments" 
                        ON "departments"."hotel_id" = "hotels"."id" 
           LEFT OUTER JOIN "chefs" 
                        ON "chefs"."department_id" = "departments"."id" 
                           AND "chefs"."employable_type" = 'CakeDesigner' 
           LEFT OUTER JOIN "cake_designers" 
                        ON "cake_designers"."id" = "chefs"."employable_id" 
           LEFT OUTER JOIN "departments" "departments_hotels_join" 
                        ON "departments_hotels_join"."hotel_id" = "hotels"."id" 
           LEFT OUTER JOIN "chefs" "chefs_hotels_join" 
                        ON "chefs_hotels_join"."department_id" = 
                           "departments_hotels_join"."id" 
                           AND "chefs"."employable_type" = 'DrinkDesigner' 
           LEFT OUTER JOIN "drink_designers" 
                        ON "drink_designers"."id" = 
                           "chefs_hotels_join"."employable_id" 

**"chefs"**."employable_type" = 'DrinkDesigner' should be
**"chefs_hotels_join"**."employable_type" = 'DrinkDesigner'

**Comment by pixeltrix** [comment] 2015-02-01 01:18
This issue is a duplicate of #18168 and was closed by 6ecf6bb.

**Closed by pixeltrix** 2015-02-01 01:18 UTC
Labels: activerecord
