### ISSUE TITLE
json column sometimes saves modified data

### ISSUE THREAD

**Issue by razola** [rails/rails#28236] opened 2017-03-01 12:14 UTC
Hi, 

Ok this is a really weird one. I'm not sure what the most helpful way to describe this is, but here we go.

I have a model with json columns that I update with the same hash object, BUT when I read the data one column inserts colons in some places. See the screenshot below. I've tried a few things to figure out what could be causing this but I genuinely have no clue what could be going on here.

![2017-03-01 at 12 39](https://cloud.githubusercontent.com/assets/700469/23459474/bf9ef332-fe80-11e6-92ad-d55e8951d6c4.png)

Here's the hash I'm saving:

`hash = {"is_claimed"=>true, "rating"=>4.0, "url"=>"https://www.yelp.com/biz/sweetgreen-new-york-4?adjust_creative=rBwuSnKM4CtGEBys0jrGnw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=rBwuSnKM4CtGEBys0jrGnw", "location"=>{"state"=>"NY", "address1"=>"100 Kenmare St", "zip_code"=>"10012", "cross_streets"=>"Mott St & Mulberry St", "display_address"=>["100 Kenmare St", "New York, NY 10012"], "address3"=>"", "country"=>"US", "address2"=>"", "city"=>"New York"}, "review_count"=>164, "phone"=>"+16469645012", "categories"=>[{"alias"=>"salad", "title"=>"Salad"}, {"alias"=>"vegetarian", "title"=>"Vegetarian"}], "image_url"=>"https://s3-media1.fl.yelpcdn.com/bphoto/fF1MdB4b5W3p0yJj54UTmg/o.jpg", "price"=>"$$", "is_closed"=>false, "coordinates"=>{"longitude"=>-73.9972511652099, "latitude"=>40.7210635428336}, "display_phone"=>"(646) 964-5012", "id"=>"sweetgreen-new-york-4", "name"=>"sweetgreen", "hours"=>[{"is_open_now"=>false, "hours_type"=>"REGULAR", "open"=>[{"day"=>0, "is_overnight"=>false, "start"=>"1030", "end"=>"2200"}, {"day"=>1, "is_overnight"=>false, "start"=>"1030", "end"=>"2200"}, {"day"=>2, "is_overnight"=>false, "start"=>"1030", "end"=>"2200"}, {"day"=>3, "is_overnight"=>false, "start"=>"1030", "end"=>"2200"}, {"day"=>4, "is_overnight"=>false, "start"=>"1030", "end"=>"2200"}, {"day"=>5, "is_overnight"=>false, "start"=>"1030", "end"=>"2200"}, {"day"=>6, "is_overnight"=>false, "start"=>"1030", "end"=>"2200"}]}], "transactions"=>[], "photos"=>["https://s3-media2.fl.yelpcdn.com/bphoto/fF1MdB4b5W3p0yJj54UTmg/o.jpg", "https://s3-media1.fl.yelpcdn.com/bphoto/L_s2d9pAfUc2D9xCaYxlWw/o.jpg", "https://s3-media4.fl.yelpcdn.com/bphoto/XCLvs3i6Jg1uUHxzym60rQ/o.jpg"], "reviews"=>[{"time_created"=>"2017-02-23 15:16:03", "text"=>"After having Sweetgreens, I actually ENJOY eating salads! Sg is probably the only salad cafe I would care to go to in NYC and order a salad. This particular...", "user"=>{"name"=>"Tiffany M.", "image_url"=>"https://s3-media2.fl.yelpcdn.com/photo/HezNPEYv6zogbgCM2HzBUg/o.jpg"}, "url"=>"https://www.yelp.com/biz/sweetgreen-new-york-4?hrid=POgTxLHDG7jRqX5sf6b2Rw&adjust_creative=rBwuSnKM4CtGEBys0jrGnw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=rBwuSnKM4CtGEBys0jrGnw", "rating"=>5}, {"time_created"=>"2017-01-24 10:28:54", "text"=>"I've been to a lot of Sweetgreens in my day. I think I've given every single one of them four stars. They've all been solid. They've all been fairly...", "user"=>{"name"=>"Molly T.", "image_url"=>"https://s3-media1.fl.yelpcdn.com/photo/JnV-c8ziIpzIvqczok_tzQ/o.jpg"}, "url"=>"https://www.yelp.com/biz/sweetgreen-new-york-4?hrid=i-W-KQLInsT3pOBsrKb7bQ&adjust_creative=rBwuSnKM4CtGEBys0jrGnw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=rBwuSnKM4CtGEBys0jrGnw", "rating"=>5}, {"time_created"=>"2017-01-21 05:22:21", "text"=>"Wow! The salad was amazing.\nExpect a long line for lunch. 10-15 min wait.\n\nRegulars do order online and pickup. \n\nThe new spicy dressing was awesome", "user"=>{"name"=>"A K.", "image_url"=>"https://s3-media4.fl.yelpcdn.com/photo/B4-4zmahYG2PDPj2KnpIHA/o.jpg"}, "url"=>"https://www.yelp.com/biz/sweetgreen-new-york-4?hrid=WE4EZkN4IOAKni1wt-WZhQ&adjust_creative=rBwuSnKM4CtGEBys0jrGnw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=rBwuSnKM4CtGEBys0jrGnw", "rating"=>5}]}
`

### System configuration
**Rails version**: Rails 5.0.1

**Ruby version**: 2.3.3

**Comment by pixeltrix** [comment] 2017-03-01 14:57
It looks like it's seeing those as times - this may be a bug in Rails but it's hard to tell based on just this. Can you please try to reproduce in a standalone script or failing that a new application pushed up somewhere, thanks.

**Comment by razola** [comment] 2017-03-01 16:08
I've tried to reproduce issue but without success. It seems to somehow be related to this specific db column. I have about 4500 rows in the db and all rows have de extra colons in column a, but not in column b.

**Comment by al2o3cr** [comment] 2017-03-02 02:04
@razola I'd recommend digging around in that model - the behavior looks like the kind of thing that happens when something modifies a hash entry in place with `gsub!` or similar. What do you get if you print out `hash` *after* the call to `update`?

**Comment by pixeltrix** [comment] 2017-03-02 08:07
Closing because it appears to be application related. Thanks for coming back to me @razola

**Closed by pixeltrix** 2017-03-02 08:07 UTC
