### ISSUE TITLE
[Active Support] Time difference producing unexcepted behaviour

### ISSUE THREAD

**Issue by maniSHarma7575** [rails/rails#46096] opened 2022-09-22 06:19 UTC
### Steps to reproduce
Is this a excepted behaviour?

1. Open the rails console.
2. Type the following command: 

```ruby
Time.zone.yesterday - Time.zone.now
```
Output:
```
/Users/manishsharma/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3.1/lib/active_support/core_ext/date/calculations.rb:104:in `-': expected numeric (TypeError)
```
```ruby
Time.zone.now - Time.zone.yesterday
```
Output:
```
3.1.2 :002 > Time.zone.now - Time.zone.yesterday
/Users/manishsharma/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3.1/lib/active_support/core_ext/time/calculations.rb:209:in `ago': undefined method `-@' for Wed, 21 Sep 2022:Date (NoMethodError)

    since(-seconds)
          ^
Did you mean?  -
/Users/manishsharma/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3.1/lib/active_support/core_ext/time/calculations.rb:294:in `-': can't convert Date into an exact number (TypeError)
```

```ruby
Time.zone.now - Time.zone.yesterday
```
Output:
```
/Users/manishsharma/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3.1/lib/active_support/core_ext/date/calculations.rb:104:in `-': expected numeric (TypeError)
```

```ruby
3.1.2 :003 > Time.zone.now - Date.yesterday
```
```
/Users/manishsharma/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3.1/lib/active_support/core_ext/time/calculations.rb:209:in `ago': undefined method `-@' for Wed, 21 Sep 2022:Date (NoMethodError)

    since(-seconds)
          ^
Did you mean?  -
/Users/manishsharma/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3.1/lib/active_support/core_ext/time/calculations.rb:294:in `-': can't convert Date into an exact number (TypeError)
```

### Expected behavior
All these commands should return the no of seconds
```ruby
3.1.2 :004 > Time.zone.now - 3.days.ago
 => 259199.999954
```

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**Comment by clouvet** [comment] 2022-09-22 10:12
@maniSHarma7575, `Time.zone.now` returns an `ActiveSupport::TimeWithZone` object, while `Time.zone.yesterday` returns a `Date` object. It's not possible to do arithmetic between the two different objects, so you get a `TypeError`, which I'd call expected behavior. 

In your last example, `3.days.ago` also returns an `ActiveSupport::TimeWithZone` object, which is why that can be subtracted and return the number of seconds.

**Comment by eileencodes** [comment] 2022-09-22 15:08
Closing since this is not a framework bug.

**Closed by eileencodes** 2022-09-22 15:08 UTC
