### ISSUE TITLE
Getting started guides has several errors

### ISSUE THREAD

**Issue by DouglasAllen** [rails/rails#27332] opened 2016-12-11 21:09 UTC
Many times in the guide it's showing to use bin/rails for rake tasks.
A couple are
http://guides.rubyonrails.org/getting_started.html

# 5.2 section
In this example, the articles_path helper is passed to the :url option. To see what Rails will do with this, we look back at the output of bin/rails routes:

and 

# 5.5 Running a Migration

At this point, you can use a bin/rails command to run the migration:

$ bin/rails db:migrate

I'm sure that there are others too but I'm not that far into it. Come on folks. This is like the old days of things not working for newbs. But you've come a long way so thanks Github, Heroku, and maybe twitter.

**Comment by utilum** [comment] 2016-12-11 21:42
The guide is correct for Rails version 5. Which one are you using? There are links to older versions at the top of the guides' index.

**Comment by maclover7** [comment] 2016-12-11 22:44
Agree with @utilum; beginning in Rails 5, Rake tasks are proxied through the `rails` CLI command. Closing since this is expected behavior.

**Closed by maclover7** 2016-12-11 22:44 UTC

**Comment by DouglasAllen** [comment] 2016-12-11 22:51
K. My bad I loaded the #<Gem::Version "4.2.7.1">
I had no idea of these changes. Why did they do this? All this time it has been Rake's job.

**Comment by MSP-Greg** [comment] 2016-12-12 05:16
@DouglasAllen 

I believe bin/rails is used **after** one has created a Rails app, and it is used from the main app folder/directory.

I believe most (all?) places it is mentioned involve operations that operate on (or require) an app.  For instance, routes have no meaning in Rails itself, but they do have meaning in a Rails application.

If, after re-reading the guides, you still feel this is not clear, please make suggestions.
