### ISSUE TITLE
Rails 5.0.0.beta2 API Exits due to undefined method in logger_silence [activesupport]

### ISSUE THREAD

**Issue by OkySabeni** [rails/rails#23566] opened 2016-02-09 00:37 UTC
This is the error that I get:

It's a new app and it just start failing.

Sample App is zipped. I remove the json file because it contains potentially sensitive information
[Sample.zip](https://github.com/rails/rails/files/122428/Sample.zip)

Command: `rails s`
>
=> Booting Puma
=> Rails 5.0.0.beta2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/logger_silence.rb:23:in `level': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/server.rb:140:in `log_to_stdout'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/server.rb:76:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/command.rb:20:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands.rb:19:in `<top (required)>'
	from /Users/okywingz/Projects/DevServer/bin/rails:9:in `require'
	from /Users/okywingz/Projects/DevServer/bin/rails:9:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/client/rails.rb:28:in `load'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/client/rails.rb:28:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/client/command.rb:7:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/client.rb:28:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-1.6.3/bin/spring:49:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/binstub.rb:11:in `load'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/okywingz/Projects/DevServer/bin/spring:13:in `require'
	from /Users/okywingz/Projects/DevServer/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by maclover7** [comment] 2016-02-09 00:39
Can you provide a sample application to reproduce this error, or the CLI commands you used to generate the app?

**Comment by OkySabeni** [comment] 2016-02-09 00:45
Sure @maclover7 I attached a sample zip and the command I use.

**Comment by maclover7** [comment] 2016-02-09 00:57
I am able to reproduce the error you are seeing using the application you provided... Can you provide the commands you used to generate the application? The line which is causing your error (`lib/active_support/logger_silence.rb:23`) hasn't been edited for months, so I think that the error may be laying hidden somewhere else...

**Comment by OkySabeni** [comment] 2016-02-09 01:05
I'll have to go from my memory.

`rails new DevServer --api`

That's pretty much it. I did switch over to using `postgres`. I also set ruby 2.3.0 and rails_12  factor gem in Gemfile. Someone in SO also have this issue so it's not unique to me.

http://stackoverflow.com/questions/35280048/first-time-using-rails-5-trouble-with-tsort-each

Let me know if you need more info.

**Comment by maclover7** [comment] 2016-02-09 01:14
Generated a new app locally, and coming up with `rails_12factor` as the causer of your error. Closing this as a third party issue.

**Closed by maclover7** 2016-02-09 01:14 UTC

**Comment by AbdullahAlger** [comment] 2016-02-26 11:57
I don't think this is a bug from `rails_12factor`. I have the gem installed and I can ruby Rails 5 just fine.
