### ISSUE TITLE
counter_cache is incremented twice times

### ISSUE THREAD

**Issue by mikes01** [rails/rails#24183] opened 2016-03-14 09:41 UTC
I have two models student and school with one to many relationship:

```
class School < ActiveRecord::Base
  has_many :students, inverse_of: :school

  validates :name, presence: true, uniqueness: true
end

class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :invitable

  include ActiveUser

  attr_accessor :inviting # flag used for conditional validations

  belongs_to :school, counter_cache: true

  delegate :name, to: :school, prefix: 'school', allow_nil: true

  validates :password, password_complexity: true, if: :password_required?

  private

  def password_required?
    inviting ? false : super
  end
end
```

When I try update student (which doesn't belong to any school) with school with below code:

```
student.school = @school
student.save(validate: false)
```

Counter cache student.school_count is incremented twice time.
When I replace above code with:

`@school.students << student`

It works fine.

Rails version: 4.2.5.1
Ruby version: 2.3.0

**Comment by eliasjpr** [comment] 2016-03-15 19:33
@mikes01 can you please create a test gist https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by mikes01** [comment] 2016-03-17 18:23
@eliasjpr here is a test gist: https://gist.github.com/mikes01/934e7248525e87d1a08c

**Comment by maclover7** [comment] 2016-03-17 20:35
Script fails on 4-2-stable for me.

**Comment by mikes01** [comment] 2016-04-01 20:43
@maclover7 Did you mean that there is a bug in the script or the test failed?

**Comment by mrageh** [comment] 2016-04-02 21:24
@mikes01 I think he means the test failed and this is a bug in AR

**Comment by tijwelch** [comment] 2016-04-07 01:54
Confirmed the test fails for me too.

**Comment by tomkadwill** [comment] 2016-04-23 18:32
Seems that this is also broken on master. Is anyone looking at fixing this? If not, I will have a try!

**Comment by vipulnsward** [comment] 2016-04-23 19:33
@tomkadwill your comment made me investigate and find a fix for this. 😁 
Go ahead and make use of https://gist.github.com/vipulnsward/1031bde143ea061be1aa8aa8599f0147
Add a test, and send PR

**Comment by tomkadwill** [comment] 2016-04-23 21:19
Thanks for your help @vipulnsward! I'll write a test and send a PR tomorrow.

**Comment by mrageh** [comment] 2016-04-23 21:35
@tomkadwill here's a test I wrote for this issue a long time ago, but my patch to fix the problem was not great so I did not submit it. 

https://gist.github.com/mrageh/aa1b64ba749a32e1170ea7c858a04df1

**Closed** 2016-05-01 04:50 UTC
Labels: activerecord, With reproduction steps
