### ISSUE TITLE
include not invoke as_json for nested association

### ISSUE THREAD

**Issue by hsul4n** [rails/rails#39212] opened 2020-05-09 23:48 UTC
### Steps to reproduce
When trying to use `Model.as_json(include: foo)` `as_json` is not being invoked on `foo`.

### here is the template that describe the issue:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :todos, force: true do |t|
    t.references :user, foreign_key: true
  end

  create_table :tasks, force: true do |t|
    t.references :todo, foreign_key: true
  end
end

class User < ActiveRecord::Base
  has_many :todos
end

class Todo < ActiveRecord::Base
  belongs_to :user
  has_many :tasks

  def as_json(*)
    super.tap do |hash|
      hash["foo"] = "hello"
    end
  end
end

class Task < ActiveRecord::Base
  belongs_to :todo

  # this is not been called anymore
  def as_json(*)
    super.tap do |hash|
      hash["bar"] = "world"
    end
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create!
    user.todos << Todo.create!
    user.todos.first.tasks << Task.create!
		
    assert_equal user.todos.as_json(), user.as_json(include: :todos)["todos"]
  end
end
```

### System configuration
**Rails: 6.0.0**:

**Ruby: 2.5.3**:

**Comment by kuldeepaggarwal** [comment] 2020-05-10 00:07
Hi @hsul4n, As per the [documentation](https://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html), the right way to include the association in the `as_json` output is:

```rb
user.as_json(include: :todos)
```

I believe this is not a bug anymore.

**Comment by jonathanhefner** [comment] 2020-05-10 00:55
@hsul4n Thank you for the issue, but @kuldeepaggarwal is correct.

Thank you @kuldeepaggarwal for the explanation!

**Comment by hsul4n** [comment] 2020-05-10 01:35
@kuldeepaggarwal, @jonathanhefner sorry for the bad explanation because I was confused, here is a better one.

**Comment by jonathanhefner** [comment] 2020-05-10 01:45
@hsul4n I see.  Would you mind filling out this [reproduction script template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) with your example?  It makes it easier for volunteers to confirm the behavior you are seeing.  Thank you!

**Comment by eugeneius** [comment] 2020-05-10 06:59
You're running into the issue described in this blog post:
https://thoughtbot.com/blog/better-serialization-less-as-json

As mentioned there, you need to override `serializable_hash` on your models, not `as_json`.

https://github.com/rails/rails/pull/2200 was an attempt to make overriding `as_json` work as expected, but it wasn't backwards compatible with `serializable_hash` and broke XML serialisation. Conceivably a new patch that solved both of those issues could be accepted... but that would be a new feature, rather than a bug fix. I'm going to close this as a non-issue, since overriding `as_json` isn't explicitly documented as supported.

**Closed by eugeneius** 2020-05-10 06:59 UTC
