### ISSUE TITLE
Is load_async supposed to work on associations?

### ISSUE THREAD

**Issue by andrejbl** [rails/rails#45408] opened 2022-06-20 12:27 UTC
### Steps to reproduce
I have a model called `App` which has a `has_many` association to a model called `ManualTags`.

```ruby
class App < ApplicationRecord
  ...
  has_many :manual_tags, class_name: "TagService::Private::DataModels::ManualTag"
  ...
end
```

Trying to force the association to load_async doesn't seem to work (notice no ASYNC in the log output):

```ruby
test = app.reload.manual_tags.load_async; sleep 1; test.load;
...
TagService::Private::DataModels::ManualTag Load (0.7ms)  SELECT `manual_tags`.* FROM `manual_tags` WHERE `manual_tags`.`deleted` = FALSE AND `manual_tags`.`app_id` = '<obfuscated>'
```

However, when I explicitly force a dummy relation on the query, it gets executed async without problems: 🤔 

```ruby
test = app.reload.manual_tags.where("1=1").load_async; sleep 1; test.load;
...
ASYNC TagService::Private::DataModels::ManualTag Load (0.0ms) (db time 0.7ms)  SELECT `manual_tags`.* FROM `manual_tags` WHERE `manual_tags`.`deleted` = FALSE AND `manual_tags`.`app_id` = '<obfuscated>' AND (1=1)
...
```

I'm using the reload/load mechanism since this repro is ran on the console and I want to make sure the query doesn't get optimised to run straight away or is already loaded.

In both cases, I can see that the async behaviour on the connection is enabled:

```ruby
[5] Rails(DEV)> app.manual_tags.connection.async_enabled?
=> true
[6] Rails(DEV)> app.manual_tags.where("1=1").connection.async_enabled?
=> true
```

The `async_query_executor` is configured to run in `:multi_thread_pool` mode:

```ruby
config.active_record.async_query_executor = :multi_thread_pool
```

Am I missing something here? Or there is a an issue or load_async is not supposed to work on associations? Thanks for the input!

### Expected behavior
`test = app.reload.manual_tags.load_async; sleep 1; test.load;` runs the query asynchronously

### Actual behavior
`test = app.reload.manual_tags.load_async; sleep 1; test.load;` runs the query synchronously 

### System configuration
**Rails version**:
`Rails 7.0.3`

**Ruby version**:
`ruby 2.7.5`

**Comment by nvasilevski** [comment] 2022-06-20 14:27
I feel like there is a tiny misconception of the `load_async` feature, at least in this particular example.
I believe the feature was supposed to make queries `async` relatively to each other but not the `sleep` in the main thread
To be specific, we could modify the code to be
```ruby
test = app.reload.manual_tags.where("1=1").load_async;
puts "before sleep"
sleep 5;
puts "after sleep"
test.load;
```
And see that the query is going to be executed after `5 seconds` of sleep, even though it is marked as `ASYNC`

So I just wanted to point out that `sleep` seems to be irrelevant for the example and may lead to some confusion.

But the difference between
```diff
-app.reload.manual_tags.load_async
+app.reload.manual_tags.where("1=1").load_async
```
is still interesting though and may need attention

**Comment by casperisfine** [comment] 2022-06-22 15:48
Ok, I managed to reproduce and it's indeed a bug. `CollectionProxy#record` doesn't account for `load_async`, I'll have to modify it.

It's particularly bad because the async query is scheduled and executed, but its result is never used hence why it doesn't appear in logs.

**Closed** 2022-06-23 12:11 UTC
Labels: activerecord

**Comment by mikerobe** [comment] 2023-03-28 01:57
Is this supposed to work on the association itself?

``` ruby
[33] pry(main)> user.notes.load_async; nil
=> nil
[34] pry(main)> user.notes.loaded?
=> false
[35] pry(main)> a = user.notes.load_async; nil
=> nil
[36] pry(main)> a.loaded?
=> true
```

Basically when I assign the result of load_async to a variable (as is done in this ticket), it will load asynchronously and use the async result, but if you call load_async on the association and then later refer to the association, it's as if the async_load was never invoked.

**Comment by skipkayhil** [comment] 2023-03-28 15:25
> This is rails 7.0.4.3.

The [fix that was backported](https://github.com/rails/rails/commit/ee7b4dd51cb9a32887ea9b66feaf118a7cf9c6a8) mentions that the association will not be marked as loaded, but the records can be returned

**Comment by mikerobe** [comment] 2023-03-28 19:39
It'll return records, but from what I can tell it's running the query again, synchronously, when the association is used even if it's previously had `load_async` invoked on it (I don't know if that's what you meant),

``` ruby
[3] pry(main)> user.notes.load_async; nil 
=> nil
[4] pry(main)> user.notes.to_a.first
  Note Load (1.9ms)  SELECT "notes".* FROM "notes" WHERE "notes"."notable_id" = $1 AND "notes"."notable_type" = $2  [["notable_id", 9342], ["notable_type", "User"]]
[5] pry(main)> user = User.find(9342); nil
  User Load (1.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 9342], ["LIMIT", 1]]
=> nil
[6] pry(main)> a = user.notes.load_async;
[7] pry(main)> a.to_a.first
  ASYNC Note Load (0.0ms) (db time 0.7ms)  SELECT "notes".* FROM "notes" WHERE "notes"."notable_id" = $1 AND "notes"."notable_type" = $2  [["notable_id", 9342], ["notable_type", "User"]]
```

It seems to only use the ASYNC result when you assign the `load_async` to something and then use it, but not on the association itself after `load_async` has been run on that association.

**Comment by rafaelfranca** [comment] 2023-03-28 21:04
If you believe there is a bug please open a new issue with a way to reproduce. People usually do even open already closed issues.

**Comment by rafaelfranca** [comment] 2023-03-28 21:05
Does:

```
user.notes.object_id
user.notes.object_id
```

return the same value?

**Comment by byroot** [comment] 2023-03-28 21:06
@rafaelfranca it is definitely a limitation as noted in the commit message: https://github.com/rails/rails/commit/ee7b4dd51cb9a32887ea9b66feaf118a7cf9c6a8

I never really got back to it though. Tracking it would make sense.

**Comment by mikerobe** [comment] 2023-03-29 22:01
Great! I submitted an issue here: https://github.com/rails/rails/issues/47809

@rafaelfranca the `user.notes.object_id` is the same in both cases:

``` ruby
[9] pry(main)> user = User.find(9342); nil
  User Load (1.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 9342], ["LIMIT", 1]]
=> nil
[10] pry(main)> user.notes.object_id
=> 91220
[11] pry(main)> user.notes.load_async; nil
=> nil
[12] pry(main)> user.notes.object_id
=> 91220
[13] pry(main)> user.notes.to_a.count
  Note Load (1.1ms)  SELECT "notes".* FROM "notes" WHERE "notes"."notable_id" = $1 AND "notes"."notable_type" = $2  [["notable_id", 9342], ["notable_type", "User"]]
=> 12
```
