### ISSUE TITLE
Time manipulation inconsistency with ActiveSupport::TimeZone

### ISSUE THREAD

**Issue by airled** [rails/rails#42467] opened 2021-06-13 08:25 UTC
### Steps to reproduce
```ruby
irb(main):001:0> zone = ActiveSupport::TimeZone['Moscow']
irb(main):002:0> zone
=> #<ActiveSupport::TimeZone:0x0000560d29ccf8d0 @name="Moscow", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: Europe/Moscow>>
irb(main):003:0> t1 = Time.new(2021, 5, 29, 0, 0, 0, '+03:00')
irb(main):004:0> t2 = Time.new(2021, 5, 29, 0, 0, 0, zone)
irb(main):005:0> t1
=> 2021-05-29 00:00:00 +0300
irb(main):006:0> t2
=> 2021-05-29 00:00:00 +0300
irb(main):007:0> t1 + 1.days
=> 2021-05-30 00:00:00 +0300
irb(main):008:0> t2 + 1.days
=> 2021-05-30 00:00:00 +0600
```
### Expected behavior
Both times should save time zone after time manipulation

### Actual behavior
Time object created with time zone of Active Support does not save time zone (it uses machine's one) after time manipulation

### System configuration
**Rails version**: 6.0.3.7

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Comment by pixeltrix** [comment] 2021-06-14 19:29
You're creating an instance of `Time` with an `ActiveSupport::TimeZone` instance rather than an instance of `ActiveSupport::TimeWithZone`. The ability to pass a zone object to `Time.new` was only added in Ruby 2.6 so duration calculations assume local or UTC time. Since Rails 7.0 only supports 2.7+ it's something we can look to fix but for now I'd recommend creating standard `ActiveSupport::TimeWithZone` instances, e.g.

```
>> zone = ActiveSupport::TimeZone['Moscow']
>> t1 = Time.new(2021, 5, 29, 0, 0, 0, '+03:00')
=> 2021-05-29 00:00:00 +0300
>> t2 = zone.local(2021, 5, 29, 0, 0, 0)
=> Sat, 29 May 2021 00:00:00.000000000 MSK +03:00
>> t1 + 1.day
=> 2021-05-30 00:00:00 +0300
>> t2 + 1.day
=> Sun, 30 May 2021 00:00:00.000000000 MSK +03:00
```

**Comment by airled** [comment] 2021-06-14 22:57
Well, another workaround for now might be to transform time object to datetime
```ruby
irb(main):001:0> zone = ActiveSupport::TimeZone['Moscow']
irb(main):002:0> t2 = Time.new(2021, 5, 29, 0, 0, 0, zone)
irb(main):003:0> t2
=> 2021-05-29 00:00:00 +0300
irb(main):004:0> td = t2.to_datetime
irb(main):005:0> td
=> Sat, 29 May 2021 00:00:00 +0300
irb(main):006:0> td + 1.days
=> Sun, 30 May 2021 00:00:00 +0300
```

Close it.

**Comment by pixeltrix** [comment] 2021-06-15 09:35
Going to reopen this since it is a bug that needs fixing

**Comment by zzak** [comment] 2021-06-16 11:36
@pixeltrix Could you elaborate on where you think this could be fixed? Perhaps myself or someone could help contribute a patch 🙏

**Comment by pixeltrix** [comment] 2021-06-16 14:50
The problem looks like it's in `advance`:

``` ruby
>> zone = ActiveSupport::TimeZone['Moscow']
=> #<ActiveSupport::TimeZone:0x00007fa58f8a4eb8 @name="Moscow", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: Europe/Moscow>>
>> t1 = Time.new(2021, 5, 29, 0, 0, 0, '+03:00')
=> 2021-05-29 00:00:00 +0300
>> t2 = Time.new(2021, 5, 29, 0, 0, 0, zone)
=> 2021-05-29 00:00:00 +0300
>> t1.advance(seconds: 60)
=> 2021-05-29 00:01:00 +0300
>> t2.advance(seconds: 60)
=> 2021-05-29 00:01:00 +0100
```

However we should add test coverage for all the `Time` core_ext methods when used with an instance with a zone object since there may be other issues.

**Comment by ghiculescu** [comment] 2021-06-23 22:50
i think the issue is actually in `change` and is fixed by https://github.com/rails/rails/pull/42583

**Closed** 2021-06-26 05:59 UTC
Labels: activesupport, attached PR
