### ISSUE TITLE
Nested Attributes validation fails with `required: true` option

### ISSUE THREAD

**Issue by itsNikolay** [rails/rails#27028] opened 2016-11-13 17:43 UTC
### Steps to reproduce
run 
`$ createdb foobar`
`$ ruby blog.rb`
```ruby
# blog.rb
require "active_record"

class Post < ActiveRecord::Base
  establish_connection adapter: "postgresql", database: "foobar"
  connection.create_table table_name, force: true

  has_many :attachments

  accepts_nested_attributes_for :attachments
end

class Attachment < ActiveRecord::Base
  establish_connection adapter: "postgresql", database: "foobar"
  connection.create_table table_name, force: true do |t|
    t.string :filename
    t.references :post
  end

  belongs_to :post, required: true # NOTE: the issue in this line
end

post = Post.new(attachments_attributes: [{ filename: 'some filename' }])
post.validate
p post.errors

#<ActiveModel::Errors:0x007fb581ff2bf0 @base=#<Post id: nil>, 
# @messages={:"attachments.post"=>["must exist"]}, 
# @details={"attachments.post"=>[{:error=>:blank}]}>

```

### Expected behavior
Nested attributes validation should pass with `required: true` option

### Actual behavior
Nested attributes validation does not pass with `required: true` option

### System configuration
**Rails version**:
Rails 5.0.0.1

**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

### P.S.
This example works well without `required: true` options

**Comment by prathamesh-sonpatki** [comment] 2016-11-13 17:56
Thanks, this is duplicate of https://github.com/rails/rails/issues/25198.

**Closed by prathamesh-sonpatki** 2016-11-13 17:56 UTC
