### ISSUE TITLE
Rails.env interpretation by config_for

### ISSUE THREAD

**Issue by qutorial** [rails/rails#31396] opened 2017-12-11 14:01 UTC
### Steps to reproduce

Create a file

config/sample.yml  like this:

development:
  database: dev

test:
  database: foo

In config/application.rb add this line:
  
   config.sample = config_for(:sample)

Run console like this with mistake:

rails console --environment test

mistake is that no = sign is used before the word test, but a space instead

Then in console:
Rails.configuration.sample
 => {"database"=>"dev"}

but

Rails.env
 => "test"

### Expected behavior
Rails.configuration.sample
 => {"database"=>"test"}

or an error message when running console

### Actual behavior
Rails.configuration.sample
 => {"database"=>"dev"}

### System configuration

ruby 2.3.1p112 

rails 5.1.1

**Comment by y-yagi** [comment] 2017-12-11 23:19
It is expected behavior that can use space to specify env. 
Therefore, `Rails.env` is returning the correct value. The reason why the result of `config_for` is not as expected is probably that there is something wrong with the application. Please check the setting of the application. 

Also, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by qutorial** [comment] 2017-12-12 09:24
Hello and thanks for your answer.

This is the only relevant place in the app for this task:

In config/application.rb add this line:

config.sample = config_for(:sample)


It is perfectly matching the rails documentation. I am also not asking for support therefore.

If the command line is designed to use space too, it is a bug then.

**Comment by y-yagi** [comment] 2017-12-12 12:25
OK, But I can not reproduce your problem with my application.
Can you please provide a sample application that reproduces the issue?

**Comment by qutorial** [comment] 2017-12-12 17:17
Here you go:
git clone https://github.com/qutorial/railsenv.git
cd railsenv
bundle install
./reproduce.sh

**Comment by qutorial** [comment] 2017-12-12 17:19
There you see how = and space make rails console behave differently.
The reproduce.sh shall explain everything. Otherwise, please, ping me.

**Comment by qutorial** [comment] 2017-12-12 17:20
This app was created with rails new and then one change to config/application.rb, and one added file config/sample.yml. Like described in the first post.

**Comment by y-yagi** [comment] 2017-12-13 12:27
Thank you for providing sample application. 
Spring seems to be unable to correctly parse the long option. 

```
$ export DISABLE_SPRING=1
$ ./bin/rails r --environment test 'p Rails.env; p Rails.configuration.sample'
"test"
{"database"=>"test"}
$ export DISABLE_SPRING=0
$ ./bin/rails r --environment test 'p Rails.env; p Rails.configuration.sample'
Running via Spring preloader in process 8488
"development"
{"database"=>"dev"} 
```

**Comment by qutorial** [comment] 2017-12-13 12:38
Ok. What are the next steps? 
Can I help in some way?

**Comment by y-yagi** [comment] 2017-12-13 12:45
Please create a issue to [spring](https://github.com/rails/spring).

Also, if you are interested, can you make a PR?  

I think probably need to fix the following lines. 
https://github.com/rails/spring/blob/f0d2d65afd715cb0103af9e31ecfcee7f2d2c825/lib/spring/commands/rails.rb#L21
https://github.com/rails/spring/blob/f0d2d65afd715cb0103af9e31ecfcee7f2d2c825/lib/spring/commands/rails.rb#L69
https://github.com/rails/spring/blob/f0d2d65afd715cb0103af9e31ecfcee7f2d2c825/lib/spring/commands/rails.rb#L91

**Comment by qutorial** [comment] 2017-12-13 12:48
Let me try : )

**Comment by qutorial** [comment] 2017-12-13 13:41
It is not very straightforward to me right now, how do I set up development environment for spring to run tests after I perform changes.
Is there a document about it? (The readme.md of spring did not help)

**Comment by qutorial** [comment] 2017-12-13 14:11
This have to be the fix, but I am not sure how to test it.
https://github.com/qutorial/spring/commit/28fffdbec2cd5b3a36d4555b7c31230cea581cb5

**Comment by y-yagi** [comment] 2017-12-13 22:25
Let's create a PR and discuss with Spring's maintainers.
Also, this is the issue of Spring. So I close this. Thanks!

**Closed by y-yagi** 2017-12-13 22:25 UTC
