### ISSUE TITLE
ROR 4.2.5 updated from 4.2.4: undefined method `attributes' for false:FalseClass

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#22292] opened 2015-11-14 11:12 UTC
Just updated from 4.2.4 to 4.2.5 and run the tests.

Three tests failed on Idea.destroy_all, where Idea is my object (Idea is shown below)

```ruby
Idea.destroy_all
  Idea Load (0.3ms)  SELECT `ideas`.* FROM `ideas` WHERE `ideas`.`deleted_at` IS NULL
   (0.3ms)  BEGIN
  Idea Load (0.5ms)  SELECT  `ideas`.* FROM `ideas` WHERE `ideas`.`id` = 1 LIMIT 1
  SQL (0.6ms)  UPDATE `ideas` SET `deleted_at` = '2015-11-14 11:05:36', `updated_at` = '2015-11-14 11:05:36' WHERE `ideas`.`id` = 1
   (42.6ms)  ROLLBACK
NoMethodError: undefined method `attributes' for false:FalseClass
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.5/lib/active_record/attribute_set.rb:68:in `=='
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activemodel-4.2.5/lib/active_model/callbacks.rb:142:in `!='
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activemodel-4.2.5/lib/active_model/callbacks.rb:142:in `block (2 levels) in _define_after_model_callback'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:107:in `call'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:107:in `call'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:227:in `block (2 levels) in halting_and_conditional'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:227:in `each'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:227:in `all?'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:227:in `block in halting_and_conditional'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `block in call'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `each'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_destroy_callbacks'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
... 18 levels...
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/kireto/robopartans/reduco/fllcasts/bin/rails:10:in `<top (required)>'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/kireto/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/kireto/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

The idea class:
```ruby
class Idea < ActiveRecord::Base
	include Sanitizer

	validates_presence_of :title
	validates_length_of :description, :minimum => 5, :too_short => "The Description must be atleas 5 characters."

	before_save :sanitize

	belongs_to :user

	default_scope { where(:deleted_at => nil) }
end
```

The db/schema:
```ruby
create_table "ideas", force: :cascade do |t|
    t.string   "title",       limit: 255
    t.text     "description", limit: 65535
    t.datetime "created_at",                null: false
    t.datetime "updated_at",                null: false
    t.integer  "user_id",     limit: 4,     null: false
    t.datetime "deleted_at"
  end
```

**Comment by sgrif** [comment] 2015-11-14 16:06
Please provide a script to reproduce the issue using this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

**Comment by al2o3cr** [comment] 2015-11-16 16:56
It appears that [this commit](https://github.com/rails/rails/commit/cfb371e96a2789790359ec1db779df490fd253d6) introduced the behavior that's causing the exception here. Does `==` on `AR::AttributeSet` need a guard like the one on `==` in `AR::AttributeSet::Builder`?

A better question would be what is an `AttributeSet` doing showing up that context at all. That may need more context from @thebravoman - it isn't clear to me where the `after_*` callback that triggers the bug is coming from.

**Comment by sgrif** [comment] 2015-11-16 18:43
Yeah, my guess is that a callback is returning an attribute set for some reason, which should never happen. I will end up adding that guard either way, but it shouldn't matter in supported usage.

**Comment by mrageh** [comment] 2015-11-16 22:20
I tried to write out a bug script for the above issue and it the test it passing, so maybe this is not an issue?

https://gist.github.com/mrageh/d023360501708538cbea

**Comment by al2o3cr** [comment] 2015-11-21 14:08
@mrageh My guess is that there's something else in the original sample that's adding callbacks that we can't see.

**Comment by al2o3cr** [comment] 2015-11-28 21:36
@thebravoman Is your application using `permanent_records`by any chance? #22417 is reporting an identical issue.

**Comment by thebravoman** [comment] 2015-11-30 08:28
@al2o3cr yes it is, actually. 
```ruby
 default_scope { where(:deleted_at => nil) }
```

**Comment by jhaungs** [comment] 2016-04-16 15:22
I've found this situation occurring when there is a destroy callback, and an ActiveRecord class **includes** Comparable and implements the **<=> ** method. 

```
def <=>(other)
   self.name <=> other.name
end
```
During the destroy callback, the **<=>** method, instead of being called with another ActiveRecord object to be compared to **self,** is instead called (from line 141 in callbacks.rb) with **false** as the **other** parameter, due to the override **<=>** being called from **!=.** 

This crashes, sending **name** to **false.**

**Comment by maclover7** [comment] 2016-04-16 16:08
@jhaungs Can you open up a new ticket with a reproduction script that matches your usage?

Closing this issue per https://github.com/rails/rails/issues/22292#issuecomment-160553559, which says that the original issue author is using `permanent_records`, which reaches into Active Record internals.

**Closed by maclover7** 2016-04-16 16:08 UTC
Labels: activerecord

**Comment by jhaungs** [comment] 2016-04-16 17:00
@maclover7 I've never used this script before. I'm happy to make a reproducible case, but how do I do the equivalent of this in the script?  This is cut from my application.rb file.  

How do I get access to the config object to set the observer?

class Application < Rails::Application
  config.active_record.observers = :audit_observer
end

**Comment by sgrif** [comment] 2016-04-16 17:03
You should isolate only the code which interacts with Active Record to demonstrate the problem. If the code requires other gems to be reproduced, you should open an issue on that gem.

**Comment by jhaungs** [comment] 2016-04-16 17:12
Well, that was pedantic. Anyone else willing to answer my question? I can't isolate whether the fault is in Active Model or the observer gem unless I can get the test to run.

**Comment by jhaungs** [comment] 2016-04-16 17:41
@maclover7 

I was able to reproduce the problem using the script and no additional gems. Issue #24584
