### ISSUE TITLE
Destroying has_many records raises error when it probably shouldn't

### ISSUE THREAD

**Issue by dzader** [rails/rails#20991] opened 2015-07-23 03:50 UTC
Calling object.destroy results in destroy! being called on the has_many records which causes a ActiveRecord::RecordNotDestroyed exceptions to be raised if there is an error destroying the has_many record. Would be nice if that destroy call honored whether .destroy or .destroy! was called on the parent.

**Comment by jvanbaarsen** [comment] 2015-07-24 07:21
@dzader Can you provide a testcase in the bug report template? (See: https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb). That would be really helpful! :heart:

**Comment by sgrif** [comment] 2015-07-24 15:19
Forgot to mention it in the commit message. This was fixed in https://github.com/rails/rails/commit/d937a1175f10586b892842348c1d6ecaa47aad2e. I consider this an ergonomic improvement, not a bug, so I will not be backporting this change to 4.x.

**Closed by sgrif** 2015-07-24 15:19 UTC

**Comment by jasonperrone** [comment] 2017-10-12 18:35
Not sure how this is not a bug. If I put dependent: :restrict_with_error on my has_many, that means I do not want an exception raised, and yet it is raised.
