### ISSUE TITLE
rake db clears previously-set ActiveRecord::Base.configurations

### ISSUE THREAD

**Issue by wtn** [rails/rails#38330] opened 2020-01-27 23:25 UTC
I am using the rails 6 "multiple databases" API to run a multi-tenant setup. Each tenant has its own database. Instead of enumerating each tenant in my `database.yml`, that file references a single "template" tenant database. At application launch, an initializer appends a hash config object for each tenant database to the `ActiveRecord::DatabaseConfigurations` object.

The issue is that `rake db` tasks reload database configurations set at rails boot. This happens in `db:load_config` [here](https://github.com/rails/rails/blob/1d1991430dc5174a54abe5c2f6ecb3fd180a829e/activerecord/lib/active_record/railties/databases.rake#L19) which calls into [here](https://github.com/rails/rails/blob/1d1991430dc5174a54abe5c2f6ecb3fd180a829e/activerecord/lib/active_record/railtie.rb#L41) and results in re-reading the application's `database.yml`.

**Configuration:** rails 6.0.2.1

**Steps to reproduce**
1. Modify `ActiveRecord::Base.configurations` from an initializer
2. Run `rake db:drop` or similar

**Expected behavior**
* `ActiveRecord::Base.configurations` is unchanged (same as after step 1)

**Actual behavior**
* `ActiveRecord::Base.configurations` gets reinitialized from `database.yml`

**Comment by eileencodes** [comment] 2020-01-28 15:23
This behavior is intentional. Otherwise how else will we create the rake tasks for multi-db?

What is the issue you're experiencing from this behavior? If you have a specific bug you're hitting please create a sample application that demonstrates the issue.

**Comment by eileencodes** [comment] 2020-01-31 17:26
I'm gonna close this since there hasn't been a response. If there''s a bug caused by reinitializing please let me know and I'll reopen. However, simply re-initializing isn't a bug.

**Comment by wtn** [comment] 2020-01-31 21:11
I've posted an app with [tests](https://github.com/wtn/db_config_injection_app/blob/master/test/db_setup_test.rb) that demonstrate the behavior. If you can please reopen this issue, I would appreciate it.

To clarify, running a rake database task for a rails app from the command line results in the database config file being read at three points:
1. rake calls `ActiveRecord::Tasks::DatabaseTasks.setup_initial_database_yaml` [here](https://github.com/rails/rails/blob/6a6e3f6efe9d621543da77dd3e9f1e875778d4e6/activerecord/lib/active_record/railties/databases.rake#L5)
2. ActiveRecord configures its databases [here](https://github.com/rails/rails/blob/6a6e3f6efe9d621543da77dd3e9f1e875778d4e6/activerecord/lib/active_record/railtie.rb#L210)
3. rake re-configures ActiveRecord [here](https://github.com/rails/rails/blob/6a6e3f6efe9d621543da77dd3e9f1e875778d4e6/activerecord/lib/active_record/railtie.rb#L41) → [here](https://github.com/rails/rails/blob/6a6e3f6efe9d621543da77dd3e9f1e875778d4e6/activerecord/lib/active_record/railties/databases.rake#L19)

My issue is with point 3. Rake does not need to force a change when ActiveRecord is already configured, and reinitializing is the less-expected choice.

> This behavior is intentional. Otherwise how else will we create the rake tasks for multi-db?

Under rails, the rake tasks work as long as ActiveRecord is configured (point 2).

I acknowledge that my approach looks unconventional at first, but is simple and works with the current public API. I hope that you will give some consideration to customized (but valid) database configurations as the API evolves.

Thanks for your work on multiple databases support, and I appreciate your continuing leadership regarding this interface.

**Comment by tgxworld** [comment] 2020-09-04 06:57
@wtn I took a look at this and it turns out the reassignment of `ActiveRecord::Base.configurations` in `db:load_config` is actually not necessary in the context of Rails because loading `ActiveRecord` itself would already have loaded the configurations.

Can you try out https://github.com/rails/rails/pull/40175 to see if that fixes it for you? 

If you want to work around the issue, you can alter `Rails.application.config.database_configuration` in your initializer instead of the `ActiveRecord::Base.configurations`

**Closed** 2020-09-04 13:10 UTC
Labels: activerecord, pinned

**Comment by wtn** [comment] 2020-09-04 16:28
Thank you very much!
