### ISSUE TITLE
[active-record] Disable type casting for a function set in :default option

### ISSUE THREAD

**Issue by sproot** [rails/rails#22055] opened 2015-10-24 01:22 UTC
I'd like to use custom PLPGSQL function to generate value for id column instead of auto_increment.
I've tried to set the function as a default value in different ways but the problem was detected in rails type casting logic.

It is impossible to set function ("next_id()" for example) for integer column types because ```connection_adapters/abstract/quoting.rb#quote``` method tries to cast this value to integer and obviously gets 0 in result.

```ruby
# active_record/connection_adapters/abstract/quoting.rb
def quote(value, column = nil)
...
  if column
    value = column.cast_type.type_cast_for_database(value)
  end
....
end

# active_record/type/integer.rb
def cast_value(value)
  case value
  when true then 1
  when false then 0
  else
    value.to_i rescue nil
  end
end
```

I believe this should be fixed. 
Does anyone know some workaround that allows to set function as a default value?

**Comment by rafaelfranca** [comment] 2015-10-24 01:52
Which version are you using?

**Comment by sproot** [comment] 2015-10-24 08:08
4.2.4

**Comment by sproot** [comment] 2015-10-24 08:17
To be more clear, table definitions such as:
```ruby
create_table :table_name, id: :bigint, default: "next_id('table_name'::text)" do |t|
...
end
```

or

```ruby
create_table :table_name, id: false do |t|
      t.integer :id, limit: 8, default: "next_id('table_name'::text)", primary_key: true
end
```

should generate the following sql:

```sql
CREATE TABLE "table_name" ("id" bigint PRIMARY KEY  DEFAULT next_id('table_name'::text))
```

instead of 

```sql
CREATE TABLE "table_name" ("id" bigint PRIMARY KEY  DEFAULT 0)
```

**Comment by sproot** [comment] 2015-10-24 09:47
However there is an ugly hack:
```ruby
create_table :table_name, id: :bigint, default: Struct.new(:quoted_id).new("next_id('table_name')") do |t|
...
end
```

It's working since quoting is ignored for some reason when ```quoted_id``` method is defined:

```ruby
# active_record/connection_adapters/abstract/quoting.rb
def quote(value, column = nil)
  # records are quoted as their primary key
  return value.quoted_id if value.respond_to?(:quoted_id)
  ...
end
```

**Comment by matthewd** [comment] 2015-10-24 10:17
Duplicate of https://github.com/rails/rails/pull/20005

**Closed by matthewd** 2015-10-24 10:17 UTC
