### ISSUE TITLE
ActiveRecord creates Record even though validation has failed

### ISSUE THREAD

**Issue by jeffreydvp** [rails/rails#35230] opened 2019-02-12 03:18 UTC
### Steps to reproduce
app/models/user.rb
```ruby
class User < ApplicationRecord
  has_many :subscriptions
  validate :custom_validation

  def custom_validation
    errors.add(:subscriptions, 'No subscriptions') if subscriptions.size > subscription_limit
  end
end
```

app/models/subscription.rb
```ruby
class Subscription < ApplicationRecord
  belongs_to :user, validate: true
end
```

app/controllers/subscriptions_controller.rb
```ruby
class SubscriptionsController < ApplicationController
  def create
    @user.subscriptions.create!
  end
end
```

### Expected behavior
The Subscription record should not be created, however, it seems that this is due to `subscriptions.size` being 0
But if you do the below instead it fails to save as expected

app/controllers/subscriptions_controller.rb
```ruby
class SubscriptionsController < ApplicationController
  def create
    @subscription = @user.subscriptions.build
    @subscripiton.save
  end
end
```

### Actual behavior
The Subscription record gets created

### System configuration
master branch of rails

ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]

**Comment by jvillarejo** [comment] 2019-02-14 20:48
I think this is an extreme case with a circular dependency. And I wouldn't this a bug.

**Comment by jeffreydvp** [comment] 2019-02-14 20:50
Okay... then, how do suggest one approaches this scenario

**Comment by jvillarejo** [comment] 2019-02-14 22:00
How do you create a Subscription in your model if a Subscription requires your User to be valid and your User requires that it's subscriptions size be 0 always?
Is there a possible way to have a Subscription? 
If not the validation should be directly
```ruby
def custom_validation
  errors.add(:subscriptions, 'No subscriptions') if subscriptions.size >= 0
end
```
Doing that would also behave as you expect when you call ```user.subscriptions.create!```

Sorry, maybe there is something I'm not understanding about your example. 

```create``` adds the object to the collection after being saved. And in my opinion that is the expected behavior most of the times. 
Here is the code: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/collection_association.rb#L346

What you propose is to add the object to the collection first and then call save on the object. 
It would work if we change the method to this:

```ruby
def _create_record(attributes, raise = false, &block)
  unless owner.persisted?
    raise ActiveRecord::RecordNotSaved, "You cannot call create unless the parent is saved"
  end

  if attributes.is_a?(Array)
    attributes.collect { |attr| _create_record(attr, raise, &block) }
  else
    record = build_record(attributes, &block)
    transaction do
      add_to_target(record)
      result = insert_record(record, true, raise) {
        @_was_loaded = loaded?
        @association_ids = nil
      }
      raise ActiveRecord::Rollback unless result
    end
    record
  end
end
```
But I don't know the impact of it or if it should be the expected scenario.

**Comment by jeffreydvp** [comment] 2019-02-14 22:51
I apologize, I just used 0 for the sake of the example however in my application this number is dynamic based on a value in the database.

Okay so if the object is added to the collection after it is saved. How can I put a limit on the number of subscriptions a User can have based on a column in the User database?

**Comment by rafaelfranca** [comment] 2019-02-14 23:09
This is a hard problem to solve because it is even susceptive to race conditions. I'd implement a `User.create_subscription` that would check if the subscription limit was reached before even trying to build the subscription, not after.

I'm closing this because it is not a bug, but a limitation of the current implementation that we can't fix without breaking another expectations. Thanks

**Closed by rafaelfranca** 2019-02-14 23:09 UTC
