### ISSUE TITLE
`ActiveSupport::Inflector.transliterate` performance optimization

### ISSUE THREAD

**Issue by SeanLF** [rails/rails#46569] opened 2022-11-24 19:44 UTC
The method seems to return the same string if it is already in ASCII.
We could return early if the string only contains ASCII characters and avoid doing any work:

```ruby
def transliterate(string, replacement = "?", locale: nil)
  return string if string.ascii_only?

  string = string.dup if string.frozen?

  raise ArgumentError, "Can only transliterate strings. Received #{string.class.name}" unless string.is_a?(String) 
  raise ArgumentError, "Cannot transliterate strings with #{string.encoding} encoding" unless ALLOWED_ENCODINGS_FOR_TRANSLITERATE.include?(string.encoding) 
      ...
```

https://github.com/rails/rails/blob/324880c393a82c5212f2402def66af1c14d6b02a/activesupport/lib/active_support/inflector/transliterate.rb#L64-L67

**Comment by ghiculescu** [comment] 2022-11-25 23:34
Would you like to make a PR for this? Tests would go [here](https://github.com/rails/rails/blob/main/activesupport/test/transliterate_test.rb) and you can also find details about benchmarking the changes [here](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#benchmark-your-code) to confirm how much faster it is. Based on that we can evaluate if it's a worthwhile change.

**Comment by ghiculescu** [comment] 2022-11-25 23:35
I'm going to close this, as it's not a bug, which is what we try to reserve the issue tracker for. A PR would be a great place to discuss this 👍

**Closed by ghiculescu** 2022-11-25 23:35 UTC
Labels: activesupport

**Comment by SeanLF** [comment] 2022-11-26 15:42
@ghiculescu I've opened the PR 🚀
