### ISSUE TITLE
Yield in partial view does not call block given by calling view

### ISSUE THREAD

**Issue by carrieje** [rails/rails#27593] opened 2017-01-06 16:19 UTC
### Steps to reproduce

Create following controller and views.

`app/controller/welcome_controller.rb`
```
class WelcomeController < ApplicationController
  def index
    render 'welcome/index'
  end
end
```

`app/views/welcome/index.html.erb`
```
Hello. <br />
<%= render('partial') do %>
  proud
<% end %><br />
Goodbye though.
```

`app/views/welcome/_partial.html.erb`
```
I am partially <%= yield %>.
```

### Expected behavior

Rendered HTML should be ([Rails guide](http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials))

```
Hello. <br />
I am partially  proud.
<br />
Goodbye though.
```

### Actual behavior

Rendered HTML was

```
Hello. <br />
I am partially .
<br />
Goodbye though.
```

My block was not executed.

### System configuration
**Rails version**: `4.2.7.1`

**Ruby version**: `2.3.0`

**Comment by charalamposgy** [comment] 2017-01-09 00:39
Good evening!

After playing around for a while, I came up with the simplest solution; to allow a block argument, since it was obvious that this is what is missing. But hey. It's been already implemented in Rails 5 as I saw next.

The point is that the guide you provide is of Rails 5, while the actual guide you should have been looking at is the following:

http://guides.rubyonrails.org/v4.2/layouts_and_rendering.html#using-partials

where the documentation you provide is of course missing.

Anyway, the commit of interest is the following:

https://github.com/rails/rails/commit/f02a35b86efea24f1e2ab684bc8081ced5eb3b1a

I do not know if a minor feature like this is to be added in previous versions (probably not though) (probably, it won't be hard to cherry-pick it).

To conclude, this issue is definitely not a bug.

Hope I helped! :-)

**Comment by caristomenopoulos** [comment] 2017-01-09 00:40
Good evening!

After playing around for a while, I came up with the simplest solution; to allow a block argument, since it was obvious that this is what is missing. But hey. It's been already implemented in Rails 5 as I saw next.

The point is that the guide you provide is of Rails 5, while the actual guide you should have been looking at is the following:

http://guides.rubyonrails.org/v4.2/layouts_and_rendering.html#using-partials

where the documentation you provide is of course missing.

Anyway, the commit of interest is the following:

https://github.com/rails/rails/commit/f02a35b86efea24f1e2ab684bc8081ced5eb3b1a

I do not know if a minor feature like this is to be added in previous versions (probably not though) ( it won't be hard to cherry-pick it however).

To conclude, this issue is definitely not a bug.

Hope I helped! :-)

**Comment by prathamesh-sonpatki** [comment] 2017-01-09 06:48
Thanks @caristomenopoulos! Closing this as this is not a bug.

**Closed by prathamesh-sonpatki** 2017-01-09 06:48 UTC
Labels: actionview

**Comment by kaspth** [comment] 2017-01-09 07:37
But @prathamesh-sonpatki is working on updating the docs nonetheless. Thanks! :)

**Comment by prathamesh-sonpatki** [comment] 2017-01-09 08:37
Yes, adding it to release notes for Rails 5.0 as it's a good change: https://github.com/rails/rails/pull/27613 

Also it will make it clear that it was added 5.0 onwards.

**Comment by carrieje** [comment] 2017-01-10 15:11
Thank you !
