### ISSUE TITLE
Rails console doesn't start - uninitialized constant Zeitwerk

### ISSUE THREAD

**Issue by msdundar** [rails/rails#35259] opened 2019-02-13 21:04 UTC
### Steps to reproduce

I'm following the master branch and experimenting with `beta1`. After the recent changes in branch, I can not start rails console and getting an error related with Zeitwerk.

### Expected behavior

Rails console should start as usual.

### Actual behavior

`rails console`, and `rails console` fails with an `uninitialized constant Zeitwerk` error.

Full error log: https://gist.github.com/msdundar/8a9f730e8603854748328abadb204370
Gemfile.lock: https://gist.github.com/msdundar/5c3d9bbb8a5fc2492a9f0cee9d056839

### System configuration

**Rails version**:

- 6.0.0.beta1

**Ruby version**:

- ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]

**Bundler version**:

- 2.0.1

**Comment by rafaelfranca** [comment] 2019-02-13 21:05
Can you provide an example application that reproduce the issue?

**Comment by msdundar** [comment] 2019-02-13 21:08
@rafaelfranca Of course, it's already an open-source project:

https://github.com/omu/nokul/tree/refactor-accounts

(I upgraded dependencies in this branch and can not start console or server at the moment)

**Comment by danielcompton** [comment] 2019-02-13 22:33
I can reproduce this error with `gem 'rails', github: 'rails/rails', ref: 'af6ade0cfd09e3d3d9ebd304a2afae4d60a044dc'`, and not with 38f9e41f2c4b64377ffb036c53873dbfb51546cf.

**Comment by danielcompton** [comment] 2019-02-14 00:12
In the meantime, you can disable Zeitwerk by setting `config.autoloader = :classic` in `config/application.rb`.

**Comment by msdundar** [comment] 2019-02-14 00:39
Thanks a lot @danielcompton. This is something definitely missing from CHANGELOG of railties. It's also interesting that `config.autoloader = :classic` didn't work for me when I add that to `application.rb`. However it's working when I add it to `development.rb`, `production.rb` and `test.rb`.

**Comment by y-yagi** [comment] 2019-02-14 00:41
This issue fix with #35261.

**Comment by rafaelfranca** [comment] 2019-02-14 00:42
cc @fxn about `config.autoloader = :classic` not working when set on application.rb

**Comment by fxn** [comment] 2019-02-14 06:43
That could be an application that changed the defaults to 6.0 at some point, but that didn't add `zeitwerk` to the `Gemfile`. Going to merge #35261, could you please try after it?

Thanks for testing this!

**Comment by fxn** [comment] 2019-02-14 06:45
Merged, no need to add the gem to the `Gemfile` now, it has become a dependency of Active Support.

**Comment by danielcompton** [comment] 2019-02-14 09:07
I can confirm that I can run `rails console` against https://github.com/rails/rails/commit/a20b00db3fd2e05a960c1d68cc7bce64733e49e7. I'll let @msdundar also confirm this works for him.

**Comment by fxn** [comment] 2019-02-14 09:19
@msdundar could it be the case that you added `config.autoloader = :classic` in `config/application.rb` before loading the framework defaults?

**Comment by fxn** [comment] 2019-02-14 09:21
I have added a brief CHANGELOG entry in Active Support to at least register the new feature somewhere (https://github.com/rails/rails/commit/e53430fa9af239e21e11548499d814f540d421e5).

**Comment by danielcompton** [comment] 2019-02-14 10:54
For context, I added `config.autoloader = :classic` to this line: https://github.com/omu/nokul/blob/2278ed0b9fad3841ccbf9a2c3c19e960ec2ee695/config/application.rb#L22.

**Comment by fxn** [comment] 2019-02-14 12:47
Since by now the main source of information for this feature is the PR description, I have added a remark about the position of the config override.

<img width="610" alt="screenshot 2019-02-14 at 13 34 28" src="https://user-images.githubusercontent.com/3387/52787647-cdd72980-305e-11e9-8519-229d706477b5.png">

**Comment by msdundar** [comment] 2019-02-14 19:48
I confirm the PR, now our app is working as expected. I tested it:

- Without `config.autoloader = :classic`, so `zeitwerk` was active.
- By adding `config.autoloader = :classic` after `config.load_defaults 6.0`
- By adding `config.autoloader = :classic` before `config.load_defaults 6.0`

All are working now. Thanks @fxn and @danielcompton!

**Comment by fxn** [comment] 2019-02-14 22:01
Thanks a lot for testing edge guys! ❤️

**Closed by fxn** 2019-02-14 22:01 UTC
