### ISSUE TITLE
Jbuilder is broken in a new Rails app

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#39492] opened 2020-05-31 18:06 UTC
I’m filing this here because I think it was broken by a recent change to Rails, not anything in Jbuilder, and it may affect other template engines like Haml.

### Steps to reproduce

1. Create a new Rails app from latest master: `railties/exe/rails new ~/Desktop/sandbox --edge`.

   * Note that [Jbuilder](https://github.com/rails/jbuilder) is included in the default Gemfile.
   * App generation may fail on the Webpacker installation step. Finish by `cd`ing into the app and running `bundle exec bin/rails webpacker:install`.

2. Add `FeedsController` with an empty `show` action:

   ```ruby
   # app/controllers/feeds_controller.rb
   class FeedsController < ApplicationController
     def show
     end
   end
   ```

3. Add singular resource routes to `FeedsController`:

   ```ruby
   # config/routes.rb
   Rails.application.routes.draw do
     resource :feed
   end
   ```

4. Add a Jbuilder view for `feeds#show`:

   ```ruby
   # app/views/feeds/show.json.jbuilder (or app/views/feeds/show.jbuilder)
   json.foo "bar"
   ```

5. Start the development web server: `bundle exec bin/rails s`.

6. Access `/feed.json`: `curl -i http://localhost:3000/feed.json`.

### Expected result

A JSON response is returned:

```
$ curl -i http://localhost:3000/feed.json
HTTP/1.1 200 OK
...
Content-Type: application/json
...

{"foo":"bar"}
```

### Actual result

The Jbuilder template is returned verbatim in the response body:

```
$ curl -i http://localhost:3000/feed.json
HTTP/1.1 200 OK
...
Content-Type: application/json
...

json.foo "bar"
```

### Notes

In attempting to reproduce this, I sometimes get the expected result after starting the development server for the first time. Requests after stopping and restarting the development server get the actual result. Stopping Spring doesn’t help. Clearing the Bootsnap cache doesn’t help.

I’ll share an example app shortly.

**Comment by georgeclaghorn** [comment] 2020-05-31 18:16
Here’s the sample app: [georgeclaghorn/rails-issue-39492](https://github.com/georgeclaghorn/rails-issue-39492).

**Comment by eugeneius** [comment] 2020-05-31 20:17
Using this command line repro:

```bash
$ bin/rails runner 'puts ApplicationController.renderer.render("feeds/show", formats: :json)'
json.foo "bar"
```

I bisected the problem to https://github.com/rails/rails/commit/e53c45b80c61e1a03b0c86efe116adbc4e91d07f.

**Comment by jonathanhefner** [comment] 2020-05-31 20:41
@eugeneius Yes!  What appears to be happening is `OptimizedFileSystemResolver`s are being instantiated on Action Controller load, [memoizing the regex built with `Template::Handlers.extensions`](https://github.com/rails/rails/blob/ab06682534f63257f33ad81e4c87931e36658cb7/actionview/lib/action_view/template/resolver.rb#L39-L60).  Jbuilder [registers its handler on Action View load](https://github.com/rails/jbuilder/blob/5a314bd8732d50a9fdda54d35f5e742d8499e4ba/lib/jbuilder/railtie.rb#L7-L8), which happens after, and thus is excluded from the regex.

**Comment by kaspth** [comment] 2020-05-31 20:55
> What appears to be happening is `OptimizedFileSystemResolver`s are being instantiated on Action Controller load

Hm, sounds like there's an unfortunate interconnected root cause effect here. Jbuilder is doing its thing correctly with the right hook, and Action Controller is separately doing its thing correctly by loading what it needs when it needs it. Feels like solving the root cause would mean a larger restructuring of the Action View / Action Controller loading order, but that's just off the top of my head and a little out of scope for this 😄

**Comment by jhawthorn** [comment] 2020-05-31 21:21
Sorry about this. I was worried something like this might happen, but thought [my added test](https://github.com/rails/rails/commit/a70ad604cfbbf191bc27e784c3fe1913a8c7b238) would catch it. 😞

I would really like to be able to do build this (and even glob and parse all views) on initialize, but it's seeming more and more like I'll have to do what @kaspth suggests and detangle the AV/AC initialization. Until then #39494 looks like a great fix ❤️

**Closed** 2020-06-01 12:29 UTC
Labels: actionview
