### ISSUE TITLE
RemoteIp middleware's proxy handling does not handle an origin that falls within the trusted IP address ranges

### ISSUE THREAD

**Issue by aetherknight** [rails/rails#20239] opened 2015-05-21 00:56 UTC
* Affects: Rails 4.2.1, but also all versions of Rails going back to 3 that I have examined.

### Setup:
* User Agent runs on a computer with a private IP address.
* Nginx reverse proxy runs in front of the Rails app on the same host. (Or even on a remote host that is also on a private IP address
* ActionDispatch::RemoteIp middleware uses its default configuration of trusting internal IP address ranges (See the TRUSTED_PROXIES constant within `actionpack/lib/action_dispatch/middleware/remote_ip.rb`)

### Observed behavior:
* `request.remote_ip` reports that the remote IP address is '127.0.0.1'

### Expected behavior:
* `request.remote_ip` reports the private IP address that the User Agent runs on.

## Analysis

I looked through RemoteIP's existing test cases, as well as its source, and it explicitly makes the assumption that if all IP addresses reported by the proxy headers are on the trusted IP list, then it returns REMOTE_ADDR. However, in a simple reverse proxy setup, REMOTE_ADDR is the IP address of the proxy directly in front of the Rails app:

From `actionpack/lib/action_dispatch/middleware/remote_ip.rb`:
```ruby
        # We assume these things about the IP headers:
        #
        #   - X-Forwarded-For will be a list of IPs, one per proxy, or blank
        #   - Client-Ip is propagated from the outermost proxy, or is blank
        #   - REMOTE_ADDR will be the IP that made the request to Rack
        ips = [forwarded_ips, client_ips, remote_addr].flatten.compact

        # If every single IP option is in the trusted list, just return REMOTE_ADDR
        filter_proxies(ips).first || remote_addr
```

`filter_proxies` removes every IP address from `ips` that matches the trusted IP addresses, leaving all public IP addresses. The first element in the array it returns is the "closest" non-trusted IP address. 

This makes sense when User Agents are always coming from public IP addresses --- if the outer-most reverse proxy were misconfigured to allow a User Agent to also set X-Forwarded-For (such that the outermost reverse proxy would append the IP address that communicated to it to that header), then this would prevent the User Agent from spoofing its IP address. However, if the User Agent is in the trusted IP address ranges, then it gets filtered out, with all the other proxy IP addresses. Since the `ips` list is now empty, the middleware returns REMOTE_ADDR instead, making `request.remote_ip` useless for internal User Agents (eg, users on a VPN).

I guess my question is, is there some reason to distrust all "trusted" IP addresses and default to the nearest proxy, or is this just an oversight? There aren't any test cases in `actionpack/test/dispatch/request_test.rb` to cover my scenario.

## Test case (cobbled from request_test.rb)

```ruby
gem 'actionpack', '4.2.1'
require 'action_dispatch'

require 'minitest/autorun'
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  def setup
    @env = {
      :ip_spoofing_check => true,
      :tld_length => 1,
      "rack.input" => "foo"
    }
  end

  def stub_request(env = {})
    ip_spoofing_check = env.key?(:ip_spoofing_check) ? env.delete(:ip_spoofing_check) : true
    @trusted_proxies ||= nil
    ip_app = ActionDispatch::RemoteIp.new(Proc.new { }, ip_spoofing_check, @trusted_proxies)
    tld_length = env.key?(:tld_length) ? env.delete(:tld_length) : 1
    ip_app.call(env)
    ActionDispatch::Http::URL.tld_length = tld_length

    env = @env.merge(env)
    ActionDispatch::Request.new(env)
  end

  # Suppose the User Agent that originated the request is on a private VPN,
  # with IP address of 172.16.0.1, from the perspective of the first reverse
  # proxy. A load balancer reverse proxy is running at 10.0.0.1, and it
  # forwards to a reverse proxy that is running on the same host as the rails
  # app.
  #
  # UA(172.16.0.1) => LB(10.0.0.1) => Proxy(localhost) => Rails app(localhost)
  def test_proxies
    request = stub_request 'REMOTE_ADDR' => '127.0.0.1',
                           'HTTP_X_FORWARDED_FOR' => '172.16.0.1, 10.0.0.1'

    assert_equal '172.16.0.1', request.remote_ip
  end
end
```

**Comment by matthewd** [comment] 2015-05-21 03:35
Thank you for the far more eloquent report than I managed. This is a duplicate of #14600 -- which I will actually really definitely deal with in the near future.

**Closed by matthewd** 2015-05-21 03:35 UTC
