### ISSUE TITLE
ActiveRecord 5 has_many :through and STI does not work with preload

### ISSUE THREAD

**Issue by n-crossfire-shibata** [rails/rails#28552] opened 2017-03-24 02:55 UTC
### Steps to reproduce

I create models with `has_many :through` association and STI.

```
# have name: :string
class User < ApplicationRecord
  has_many :gifts
  has_many :toys, through: :gifts
  has_many :toy_cars, through: :gifts
end

class Gift < ApplicationRecord
  belongs_to :user
  belongs_to :toy
  belongs_to :toy_car, foreign_key: :toy_id, optional: true
end

# have name: :string
class Toy < ApplicationRecord
  has_many :gifts
  has_many :users, through: :gifts
end

class ToyCar < Toy
end
```

In `rails c` , make test data.

```
user = User.create(name: "test user")
toy_car = ToyCar.create(name: "sample toy car")
user.toy_cars << toy_car
```

When I use `eager_load` it works well.

```
User.eager_load(:toy_cars).take
  SQL (0.3ms)  SELECT  DISTINCT "users"."id" FROM "users" LEFT OUTER JOIN "gifts" ON "gifts"."user_id" = "users"."id" LEFT OUTER JOIN "toys" ON "toys"."id" = "gifts"."toy_id" AND "toys"."type" IN ('ToyCar') LIMIT ?  [["LIMIT", 1]]
  SQL (0.2ms)  SELECT "users"."id" AS t0_r0, "users"."name" AS t0_r1, "users"."created_at" AS t0_r2, "users"."updated_at" AS t0_r3, "toys"."id" AS t1_r0, "toys"."name" AS t1_r1, "toys"."type" AS t1_r2, "toys"."created_at" AS t1_r3, "toys"."updated_at" AS t1_r4 FROM "users" LEFT OUTER JOIN "gifts" ON "gifts"."user_id" = "users"."id" LEFT OUTER JOIN "toys" ON "toys"."id" = "gifts"."toy_id" AND "toys"."type" IN ('ToyCar') WHERE "users"."id" = 1
```

But when I use `preload` it seems broken.

```
User.preload(:toy_cars).take
  User Load (0.2ms)  SELECT  "users".* FROM "users" LIMIT ?  [["LIMIT", 1]]
  Gift Load (0.5ms)  SELECT "gifts".* FROM "gifts" WHERE "toys"."type" IN ('ToyCar') AND "gifts"."user_id" = 1
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: toys.type: SELECT "gifts".* FROM "gifts" WHERE "toys"."type" IN ('ToyCar') AND "gifts"."user_id" = 1
```

I also try to use `source` and `class_name` options, but it did not work as I expected.

### Expected behavior
It should `SELECT` from toys table.

### Actual behavior
`SELECT` from gifts table.

### System configuration
Here's part of my `Gemfile.lock`.

```
    activerecord (5.0.2)
      activemodel (= 5.0.2)
      activesupport (= 5.0.2)
      arel (~> 7.0)
    rails (5.0.2)
      actioncable (= 5.0.2)
      actionmailer (= 5.0.2)
      actionpack (= 5.0.2)
      actionview (= 5.0.2)
      activejob (= 5.0.2)
      activemodel (= 5.0.2)
      activerecord (= 5.0.2)
      activesupport (= 5.0.2)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.2)
```

I tried it with rails 5.1.0.beta1, but did not work.

**Ruby version**:
```
ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin14]
```

**Comment by k0kubun** [comment] 2017-04-02 02:29
I think this is duplicated with https://github.com/rails/rails/issues/11078 and hopefully https://github.com/rails/rails/pull/14312 will fix it.

**Comment by maclover7** [comment] 2017-04-02 17:31
Agree with @k0kubun, closing as a duplicate of #11078.

**Closed by maclover7** 2017-04-02 17:31 UTC
Labels: activerecord
