### ISSUE TITLE
Turbo depends on ActiveJob::Base but no error when I start a project with `rails new . --skip-active-job`

### ISSUE THREAD

**Issue by fguillen** [rails/rails#51917] opened 2024-05-26 20:15 UTC
### Steps to reproduce

```bash
rails new . --skip-active-job 
rails s -C --log-to-stdout -e production
```

### Expected behavior

I expect a warning or a suggestion to also `--skip-hotwire` if I don't active active-jobs.

### Actual behavior

The application is created properly, and the error only shows up when you try to deploy in `production` environment 👍 

```
> rails s -C --log-to-stdout -e production
=> Booting Puma
=> Rails 7.1.3.3 application starting in production 
=> Run `bin/rails server --help` for more startup options
W, [2024-05-26T22:12:16.630369 #10309]  WARN -- : You are running SQLite in production, this is generally not recommended. You can disable this warning by setting "config.active_record.sqlite3_production_warning=false".
Exiting
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/turbo-rails-2.0.5/app/jobs/turbo/streams/action_broadcast_job.rb:2:in `<main>': uninitialized constant ActiveJob (NameError)

class Turbo::Streams::ActionBroadcastJob < ActiveJob::Base
                                           ^^^^^^^^^
Did you mean?  ActiveModel
	from <internal:/Users/me/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/me/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/kernel.rb:26:in `require'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/helpers.rb:148:in `const_get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/helpers.rb:148:in `cget'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/helpers.rb:42:in `block in ls'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/helpers.rb:25:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/helpers.rb:25:in `ls'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader.rb:413:in `block in eager_load_all'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader.rb:411:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.15/lib/zeitwerk/loader.rb:411:in `eager_load_all'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/application/finisher.rb:80:in `block in <module:Finisher>'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/initializable.rb:32:in `run'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/application.rb:426:in `initialize!'
	from /Users/me/Downloads/test_project/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-3.0.11/lib/rack/builder.rb:103:in `eval'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-3.0.11/lib/rack/builder.rb:103:in `new_from_string'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-3.0.11/lib/rack/builder.rb:94:in `load_file'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-3.0.11/lib/rack/builder.rb:64:in `parse_file'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/commands/server/server_command.rb:36:in `start'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/commands/server/server_command.rb:136:in `perform'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/command/base.rb:73:in `perform'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/command.rb:71:in `block in invoke'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/command.rb:149:in `with_argv'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/command.rb:69:in `invoke'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.1.3.3/lib/rails/commands.rb:18:in `<main>'
	from <internal:/Users/me/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/me/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

### System configuration

```
> rails --version
Rails 7.1.3.3
> ruby -v
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin19]
```

**Comment by zzak** [comment] 2024-05-27 07:11
Duplicate of #51768, if you are able to point your app at `turbo-rails` main and verify the issue is fixed? :bow:

**Closed by zzak** 2024-05-27 07:11 UTC
