### ISSUE TITLE
Rails 5: NameError: uninitialized constant User on reload! from console in production environement

### ISSUE THREAD

**Issue by vaibhav8275** [rails/rails#28146] opened 2017-02-24 05:59 UTC
`$ RAILS_ENV=production rails c`
Running via Spring preloader in process 5191
Loading production environment (Rails 5.0.1)

`2.3.3 :001 > User.new`
 => #<User id: nil, email: "", created_at: nil, updated_at: nil>

`2.3.3 :002 > reload!`
Reloading...
NameError: uninitialized constant User
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:268:in `const_get'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:268:in `block in constantize'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:266:in `each'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:266:in `inject'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:266:in `constantize'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:583:in `get'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:614:in `constantize'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/devise-4.2.0/lib/devise.rb:301:in `get'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/devise-4.2.0/lib/devise/mapping.rb:81:in `to'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/devise-4.2.0/lib/devise/mapping.rb:76:in `modules'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/devise-4.2.0/lib/devise/mapping.rb:93:in `routes'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/devise-4.2.0/lib/devise/mapping.rb:160:in `default_used_route'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/devise-4.2.0/lib/devise/mapping.rb:70:in `initialize'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/devise-4.2.0/lib/devise.rb:331:in `new'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/devise-4.2.0/lib/devise.rb:331:in `add_mapping'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/devise-4.2.0/lib/devise/rails/routes.rb:241:in `block in devise_for'
... 45 levels...
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Downloads/temp/carrierwave/bin/rails:9:in `<top (required)>'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/commands/rails.rb:6:in `load'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/commands/rails.rb:6:in `call'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/command_wrapper.rb:38:in `call'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/application.rb:191:in `block in serve'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/application.rb:161:in `fork'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/application.rb:161:in `serve'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /.rvm/gems/ruby-2.3.3@rails5.0.1/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by al2o3cr** [comment] 2017-02-24 12:11
This is going to be very difficult to troubleshoot without some way to reproduce the issue. A first troubleshooting step would be to check for relevant `require` or `require_dependency` lines; this kind of bug is usually caused by something getting marked as "not autoloaded" incorrectly.

**Comment by rafaelfranca** [comment] 2017-02-25 00:23
`reload!` doesn't work in production environment because the classes are cached.

**Closed by rafaelfranca** 2017-02-25 00:23 UTC

**Comment by dreyks** [comment] 2017-06-17 20:44
@al2o3cr, @rafaelfranca 
this actually can happen in test environment too
steps to reproduce

- run standard `rails new wtfapp`
- in `config/environments/test.rb` set `config.eager_load = true`
- add one empty model, say `User`
- in `config/routes.rb` reference the model anywhere, just put `User` on line 2
- run `rails c test`
- in console run `reload!`
- get `NameError: uninitialized constant User`
- alternatively run console with spring disabled `DISABLE_SPRING=true rails c test`
- run `reload!`
- get `ArgumentError: unknown firstpos: NilClass`

**Comment by rafaelfranca** [comment] 2017-06-19 20:15
Test environment also cache the classes

**Comment by dreyks** [comment] 2017-06-19 20:22
So um... how should `spring` deal with it? It does use [reload](https://github.com/rails/spring/blob/85f9aa7cfbaddf135a3588b93be28e37fe02c3c0/lib/spring/application.rb#L164)
or should I open an issue on spring then?

**Comment by rafaelfranca** [comment] 2017-06-19 20:43
spring also disable cache classes https://github.com/rails/spring/blob/85f9aa7cfbaddf135a3588b93be28e37fe02c3c0/lib/spring/application.rb#L105

**Comment by dreyks** [comment] 2017-06-20 03:47
ok... but the issue still stands. i can't use spring in test environment, it fails each time i do changes to code

**Comment by rafaelfranca** [comment] 2017-06-20 06:10
You enabled eager loading that doesn't support reload. That will happen not matter the environment.

**Comment by dreyks** [comment] 2017-06-20 06:19
got it! thanks for the explanation

**Comment by rafaelfranca** [comment] 2017-06-20 06:26
To explain better, when you enable `eager_load` rails will load all files inside the eager load paths using `require` at boot time. Because Ruby does load a file that was already required, reload will not work since the next time rails tries to load Ruby will just ignore saying that the file was already required.

**Comment by dreyks** [comment] 2017-06-20 06:32
this got me confused because the comment in test.rb says that "if you're using tests preloaded you might want to set eager_load to true"
