### ISSUE TITLE
i am using ruby 3.2.2 and rails version 7.0.1 in my code at one file i have to add explicitly the path of model class otherwise it didnt work i think on rails 7 my zeitwerk will handle the autoloading but it didnt working for me 

### ISSUE THREAD

**Issue by AbdulWahab552** [rails/rails#50690] opened 2024-01-10 07:39 UTC
### Steps to reproduce

```ruby
# Your reproduction script goes here
```

### System configuration
**Rails version**:

**Ruby version**:

**Comment by byroot** [comment] 2024-01-10 09:16
Duplicate of https://github.com/rails/rails/issues/50691

**Closed by byroot** 2024-01-10 09:16 UTC
