### ISSUE TITLE
Rails::Generators::GeneratedAttribute - adding new valid types

### ISSUE THREAD

**Issue by boardfish** [rails/rails#43523] opened 2021-10-25 09:41 UTC
[Rails::Generators::GeneratedAttribute](https://github.com/rails/rails/blob/31ad3f152954142c68c030db596c35e31ca93a76/railties/lib/rails/generators/generated_attribute.rb) doesn't appear to support adding new valid types. I'm using it to generate Active Model attribute declarations for a new class. It raises an error if I try to use a type I've added to the registry through an initializer. In essence, if I specify this:

```ruby
ActiveModel::Type.registry.register(:round_thing, ActiveModel::Type::Value)
```

I expect to be able to do this:

```bash
rails generate my_generator Car wheel:round_thing
```

and not receive the error `Could not generate field 'wheel' with unknown type 'round_thing'`.

I think the reason why it is the way it is now is because the only thing Rails generators generate with regards to fields are migrations, and for those it needs to know that the field type that's getting passed maps to a valid column type in the database.

**Comment by ghiculescu** [comment] 2021-11-02 00:21
From reading the [code](https://github.com/rails/rails/blob/31ad3f152954142c68c030db596c35e31ca93a76/railties/lib/rails/generators/generated_attribute.rb#L63) this seems to me like intended behaviour, ie. not a bug.

> and for those it needs to know that the field type that's getting passed maps to a valid column type in the database.

Yes, I think so too, hence checking `native_database_types`.

Do you have a proposal for how this could work? It may be best to move this to the [discussion forum](https://discuss.rubyonrails.org/c/rubyonrails-core/5) or to make a PR showing what you have in mind.

**Comment by rafaelfranca** [comment] 2021-11-02 00:30
Yeah. This is by design. Since we would not know what a `round_thing` would be in the database. Closing since this is more a feature request and feature request should be made in the discussion forum.

**Closed by rafaelfranca** 2021-11-02 00:30 UTC
Labels: railties
