### ISSUE TITLE
Cookies are being set incorrectly

### ISSUE THREAD

**Issue by obie** [rails/rails#48195] opened 2023-05-11 20:23 UTC
Cookies are being sent wrapped in an array string, not in the correct format. Results in keys to cookies including an extraneous `["` prefix that breaks querying later. First practical effect is breaking the establishment of current user identity in `ActionCable::Channel`

### Steps to reproduce
Set any cookie. Inspect response headers and cookie store in browser. Compare to behavior witih literally any other site on the web.

### Expected behavior

![image](https://github.com/rails/rails/assets/3908/65db8ab9-a8a9-4cca-b688-3fdbafb698c0)

### Actual behavior

![image](https://github.com/rails/rails/assets/3908/7e4f1d3d-5f1f-47a1-9d2f-8be1532b174f)

### System configuration
**Rails version**: 7.1.0.alpha

**Ruby version**: 3.2.2

**Comment by obie** [comment] 2023-05-11 20:23
Can workaround by manually renaming the key using your browser inspector to remove the extraneous `["` prefix.

**Comment by obie** [comment] 2023-05-11 20:58
Workaround for cable connection in case anyone else stumbles into this.

```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      # todo: this is a hack to get around https://github.com/rails/rails/issues/48195
      # once that is fixed should switch back to simpler solution with encrypted cookie for user_id
      # turn cookies into a hash and find a key that matches user_id using a regex
      key = cookies.to_h.find { |k, _v| k.match?(/user_id/) }&.first
      user_id = cookies[key]
      return reject_unauthorized_connection if user_id.nil?
      user = User.find_by(id: user_id)
      return reject_unauthorized_connection if user.nil?
      self.current_user = user
    end
  end
end
```

**Comment by jonathanhefner** [comment] 2023-05-12 02:38
I am having trouble reproducing this locally.  Could you share some more information?

For example, which cookie serializer are you using?  Which `config.load_defaults` version?  Are you using any add-ons?  Can you reproduce this with a fresh Rails 7.1 app?  Could you share a minimal reproduction script or app?

Also, would you mind trying the latest `main` ref now that #48197 is merged?

**Comment by JoeDupuis** [comment] 2023-05-23 04:45
I had the same issue. I tracked it to rack 3 with Puma 5. They don't seem compatible. 
If you generated your app a while ago, your gemfile probably has `gem "puma", "~> 5.0"` (mine did) which would give you the broken combination when running `bundle update`. 

If you run a `rails new` today (from main), you'll get `gem "puma", ">= 5.0"` instead. Which explain why it's hard to recreate. 

Not really a rails bug. I checked what's returned in the `Engine#call` and the same `set-cookie` header was returned with or without the bug (toggling puma version).

**Comment by JoeDupuis** [comment] 2023-05-28 04:32
I built a minimal repro [here](https://gist.github.com/JoeDupuis/1d219656f4d9d6dd3421e98b4eb00eea) and I opened a [PR for Puma](https://github.com/puma/puma/pull/3164). I think a lot of people are about to hit this (when Rails 7.1 releases). I am hoping to mitigate it.

Upgrading to Puma 6 should fix the issue.

**Closed** 2023-05-30 21:45 UTC
Labels: more-information-needed

**Comment by mahfuz16** [comment] 2023-10-29 12:31
I faced same issue in Rails 7.1
Now I am using rails 7.0.8
Anyone can confirm, this issue is fixed in latest Rails version?

**Comment by skipkayhil** [comment] 2023-10-29 18:03
> nginx passenger.

The latest release of passenger is not compatible with Rack 3. You can add `gem "rack", "< 3"` to your Gemfile to use Rails 7.1

**Comment by javinto** [comment] 2023-11-13 21:26
Unfortunately adding gem "rack", "<3" or gem "rack-session", '1.0.1' is not possible with Rails 7.1.2 due to dependencies.

Should we wait for a new release of Passenger then?

**Comment by skipkayhil** [comment] 2023-11-13 21:29
> Unfortunately adding gem "rack", "<3" or gem "rack-session", '1.0.1' is not possible with Rails 7.1.2 due to dependencies.

That's unlikely to be an issue with Rails, but you may have to downgrade some other gem to use Rack 2.

**Comment by javinto** [comment] 2023-11-14 08:31
> > Unfortunately adding gem "rack", "<3" or gem "rack-session", '1.0.1' is not possible with Rails 7.1.2 due to dependencies.
> 
> That's unlikely to be an issue with Rails, there's probably some other gem you will have to downgrade to use Rack 2.

I managed to activate Rack 2.0 by adding this to my gemfile:
```
gem 'rack-session', '1.0.1'
gem 'rackup', '1.0.0'

```
But with deployment I now get:
```
      01 LoadError: cannot load such file -- /.../rails/shared/bundle/ruby/3.2.0/gems/rackup-1.0.0/lib/rackup/handler (LoadError)
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/rackup-1.0.0/lib/rackup.rb:6:in `require_relative'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/rackup-1.0.0/lib/rackup.rb:6:in `<main>'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/bundler-2.3.13/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/bundler-2.3.13/lib/bundler/runtime.rb:55:in `each'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/bundler-2.3.13/lib/bundler/runtime.rb:55:in `block in require'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/bundler-2.3.13/lib/bundler/runtime.rb:44:in `each'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/bundler-2.3.13/lib/bundler/runtime.rb:44:in `require'
      01 /.../rails/shared/bundle/ruby/3.2.0/gems/bundler-2.3.13/lib/bundler.rb:176:in `require'
      01 /.../rails/releases/20231114082124/config/application.rb:19:in `<top (required)>'
      01 /.../rails/releases/20231114082124/Rakefile:4:in `require_relative'
      01 /.../rails/releases/20231114082124/Rakefile:4:in `<top (required)>'

```

Is there another dependency breaking this?

**Comment by javinto** [comment] 2023-11-14 08:35
I see I'd better wait for the release of Passenger 6.0.19 which should solve the Rack 3.0 header arrays.

**Comment by gdonald** [comment] 2023-11-24 18:55
I hit this today when I took my new Rails app that I created two weeks ago into production.  Downgrading rack to 2.2.8 was the fix.

**Comment by atha10** [comment] 2023-12-02 18:58
I am using rails 7.1.2 and getting same issue , trying to save cookie for user_id but saving with ["user_id. And i cant be able to donwgrade rack as project is live.

**Comment by voducvu** [comment] 2024-05-08 05:07
It's because of Rack 3 supports multiple header values. So the cookies are now stored in an array instead of multiple lines string. see https://github.com/rack/rack/blob/v3.0.10/lib/rack/response.rb#L218

For unicorn 6.1 we need to patch the HttpResponse module so that it accepts "Set-Cookie" header with array of values
`module Unicorn::HttpResponse

  def http_response_write(socket, status, headers, body,
    req = Unicorn::HttpRequest.new)
    hijack = nil

    if headers
      code = status.to_i
      msg = STATUS_CODES[code]
      start = req.response_start_sent ? ''.freeze : 'HTTP/1.1 '.freeze
      buf = "#{start}#{msg ? %Q(#{code} #{msg}) : status}\r\n" \
            "Date: #{httpdate}\r\n" \
            "Connection: close\r\n"
      headers.each do |key, value|
        case key
        when %r{\A(?:Date|Connection)\z}i
          next
        when "rack.hijack"
          # This should only be hit under Rack >= 1.5, as this was an illegal
          # key in Rack < 1.5
          hijack = value
        else
          # support Rack 3.0 multi-value headers
          if value.is_a?(Array)
            value.each { |v| buf << "#{key}: #{v}\r\n" }
          elsif value =~ /\n/
            # avoiding blank, key-only cookies with /\n+/
            value.split(/\n+/).each { |v| buf << "#{key}: #{v}\r\n" }
          else
            buf << "#{key}: #{value}\r\n"
          end
        end
      end
      socket.write(buf << "\r\n".freeze)
    end

    if hijack
      req.hijacked!
      hijack.call(socket)
    else
      body.each { |chunk| socket.write(chunk) }
    end
  end
end`

**Comment by Earlopain** [comment] 2024-05-08 13:36
For people stuck on Unicorn, I recommend looking into [pitchfork](https://github.com/Shopify/pitchfork) instead which is properly maintained and works with Rack 3 out of the box.

Since Pitchfork is a fork of Unicorn it should be relatively painless to migrate over and not as much work as going for something with a different architecture, like Puma for example. There's a basic migration guide for unicorn users in the repo if anyone is interested.
