### ISSUE TITLE
wrong schema.rb for foreign key

### ISSUE THREAD

**Issue by twiduch** [rails/rails#29023] opened 2017-05-09 23:39 UTC
### Steps to reproduce

For postgresql, working with different schemas.

Having the migration:
```ruby
  class CreateRoleAssignments < ActiveRecord::Migration[5.1]
    def change
      create_table :role_assignments do |t|
        t.references :user, foreign_key: true
        t.references :role
      end
      add_foreign_key :role_assignments, :"public.roles",
                      column: :role_id, name: :public_role
    end
  end
```

after rails:db:migrate

the wrong line in file db/schema.rb is
```
add_foreign_key "role_assignments", "roles", name: "public_roles"
```
it should be:

```
add_foreign_key "role_assignments", "public.roles", column: 'role_id', name: "public_roles"
```

### System configuration
**Rails version**:
5.1
**Ruby version**:
2.4.1

**Comment by DmytroVasin** [comment] 2017-05-10 11:13
BTW If you try to specify another schema ( for example `settings` ) rails will detect it fine.

```ruby
add_foreign_key "role_assignments", "settings.roles", column: "role_id", name: "public_role"
```

My assumption is that `public` schema structure is default for postgresql, thats why we have behaviour that described in the issue

**Comment by alexcameron89** [comment] 2017-05-10 13:32
This looks to be a duplicate of #28654, so I'm going to close it. We can continue the conversation on that issue so that information useful to the issue can be contained in one location.

**Closed by alexcameron89** 2017-05-10 13:32 UTC
Labels: activerecord
