### ISSUE TITLE
Custom `FormBuilder` not being passed to nested `fields_for` in Rails 7.0.

### ISSUE THREAD

**Issue by joshuapinter** [rails/rails#46154] opened 2022-09-29 16:15 UTC
### Steps to reproduce
After upgrading from Rails 6.1 to 7.0, using a nested `fields_for` inside of a custom `FormBuilder` no longer passes/uses the custom `FormBuilder` as the nested `FormBuilder` object.

For example: 

```ruby
<%= form_for @person, builder: MyFormBuilder do |f| %>
  I am a child: <%= f.div_radio_button(:admin, "child") %>
  I am an adult: <%= f.div_radio_button(:admin, "adult") %>
  
  <%= f.fields_for :permission, @person.permission do |permission_fields| %>
    <%# permission_fields.class is ActionView::Helpers::FormBuilder instead of MyFormBuilder, which it was in Rails 6.1. %>
    Admin?  : <%= permission_fields.check_box :admin %>
  <% end %
<% end -%>
```

### Expected behavior
The nested `FormBuilder` object should inherit the custom `FormBuilder` from the parent `FormBuilder`.

### Actual behavior
The nested `FormBuilder` object is of the default class `ActionView::Helpers::FormBuilder` and not inherited from parent `FormBuilder`.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2p20

**Comment by joshuapinter** [comment] 2022-09-29 16:52
FYI, to temporarily get around this, I've had to avoid using the parent `FormBuilder` (i.e. `f`) to create the `fields_for` and pass the `builder` manually, like this: 

```ruby
<%= fields_for :permission, @person.permission, builder: MyFormBuilder do |permission_fields| %>
```

**Comment by joshuapinter** [comment] 2022-09-29 19:32
Quick follow up.

I found it works fine when you either don't mass an object to `fields_for`: 

```ruby
<%= f.fields_for :permission do |permission_fields| %>
  <%# permission_fields.class is MyFormBuilder %>
```

Or if you pass the proper parent object or dependent object: 

```ruby
<%= f.fields_for :permission, @person do |permission_fields| %>
  <%# permission_fields.class is MyFormBuilder %>
```

or

```ruby
<%= f.fields_for :permission, @person.permission do |permission_fields| %>
  <%# permission_fields.class is MyFormBuilder %>
```

In our case, we were passing a `serialized` column (a bunch of search filters) as the object and that seemed to result in the parent builder not being inherited properly: 

```ruby
<%= f.fields_for :serialized_column, @person.serialized_column do |permission_fields| %>
  <%# permission_fields.class is ActionView::Helpers::FormBuilder %>
```

Sorry if this was convoluted and maybe turned out to be an even more obscure bug/issue. However, I still think it may be valid to at least look at since it only occurred in Rails 7 (not in any version from Rails 3 - 6.1).

Thanks, regardless.

**Comment by ubaidmyasintv** [comment] 2022-10-12 06:32
For latest Asian/Korean Movies, drama, K-Series please visit [MyAsianTv] (https://myasiantv.at/)

**Comment by adrianvalenz** [comment] 2022-10-31 06:32
`  <%= form_for(resource, as: resource_name, url: session_path(resource_name), builder: SourdoughFormBuilder, data: { turbo: false }) do |f| %>
...
<% end %>
`
I did something like this in my Devise form and my builder worked. I guess specifying values. I think the wave is leaning toward `form_with` for any form created for Rails 7 and on.

**Comment by MatElGran** [comment] 2022-11-06 15:26
Hi @joshuapinter, I may have missed something, but I can't reproduce this.

I've set up a new [project](https://github.com/MatElGran/nested_form_builder) (rails 7.0.4, ruby 3.1.2p20) with a model defining a serialized attribute, and adapted the generated form to match the description provided here, but fields_for block parameter is an instance of the expected class. Do you still have this problem ?

**Comment by joshuapinter** [comment] 2022-11-06 15:54
Hi Mathieu,

Thanks for looking into this. Are you able to make that sample repo public and share it with me. I’ll then look at reproducing the issue in there.

Thanks!

Joshua

**Comment by MatElGran** [comment] 2022-11-06 17:06
It already is: https://github.com/MatElGran/nested_form_builder

**Comment by joshuapinter** [comment] 2022-11-06 18:56
Wonderful. I’ll take a look as soon as I get a minute. Thanks.

**Comment by joshuapinter** [comment] 2022-11-11 18:40
Hi @MatElGran. Thanks again for looking into this and creating that sample repo to reproduce the issue.

I modified by setting  default class to the `serialize` column and the issue was reproduced. I created a PR to your sample project here: 

https://github.com/MatElGran/nested_form_builder/pull/1. 


With this change, inspecting the `fields_form.class` will yield the standard `ActionView::Helpers::FormBuilder` instead of the custom `CustomBuilder` as provided in the parent `form_for`:

```ruby
fields_form.class
#=> ActionView::Helpers::FormBuilder
```

Let me know what you find out and if you need anything else. 

Thanks!

**Comment by MatElGran** [comment] 2022-11-17 08:56
Hi @joshuapinter, I've dug into this, learned loads of things, and in the end I think this is a shortcoming of `FormBuilder#fields_for` design, and that it only worked accidentally before 7.x.

The short explanation is that the `record_object` parameter you pass to `fields_for` gets misinterpreted as the `fields_options` parameter and it being a `HashWithIndifferentAccess` messes up builder instantiation.

It was already the case in 6.1, the code was already not doing what you thought it was, but #43421 made it visible. If you have had a `:builder` key in your serialized attribute (or any other valid `fields_for` option), you would have probably seen it sooner.

Now for the longer version:

`ActionView::Helper::FormBuilder#fields_for` block parameter takes a form builder as its parameter. This builder is instantiated by calling `new` on the class configured via the `:builder` key in the `fields_options` parameter passed to `fields_for`.

If none is explicitly provided, the `:builder` option passed to the surrounding `form_for` will be added to `fields_options` ([here](https://github.com/rails/rails/blob/2a2a6ab6219b12e9e77931a60fe83c658db44ac7/actionview/lib/action_view/helpers/form_helper.rb#L2269), that's the builder "inheritance" part), and if there was none, the code falls back to the configured default form builder or  `ActionView::Helpers::FormBuilder` ([here](https://github.com/rails/rails/blob/main/actionview/lib/action_view/helpers/form_helper.rb#L1613)).

Because the `record_object` parameter you pass to `fields_for` is a kind of `Hash`, `fields_for` parameters handling misinterprets it as the `fields_options` parameter (see [here](https://github.com/rails/rails/blob/2a2a6ab6219b12e9e77931a60fe83c658db44ac7/actionview/lib/action_view/helpers/form_helper.rb#L2268), this is the root cause of your problem, and it has been there for at least 12 years). 

As our record_object has no `:builder` key, the one configured on the outer form builder gets added to what the code now considers to be `fields_options`. 

Before #43421, `fields_options` were passed untouched (i.e as a `HashWithIndifferentAccess`) to the code in charge of instantiating the builder, and when this code looked for a `:builder` option, the expected value was returned.

#43421 changed that. `fields_options` is now merged into a classic `Hash` [here](https://github.com/rails/rails/blob/3d019868d5e9da57abc9f1113778388f6158690e/actionview/lib/action_view/helpers/form_helper.rb#L1026), with its keys added as strings instead of symbols (`HashWithIndifferentAccess` have string keys under the hood) and lookups for `:builder` key now being on this `Hash`, they return nil, and so the default builder is used.

I would have thought `FormBuilder#fields` would not have this problem, since it defines an explicit :model parameter, unfortunately it is defined using `fields_for` and it seems we lose that bit information because of that (The `FormHelper` versions have opposite dependencies,  `fields_for` is defined in terms of `fields`)

I can't yet think of a fix, and I'm not even sure it is fixable. In your case, since it is not used as intended anyway, you can probably remove the second parameter (the `record_object`) when calling `fields_for`, and the code should use the correct builder. 

More generally, I think this behavior should be documented (I did not find anything about it). I also think `FormBuilder#fields` should be made independent of `fields_for` so that we stop losing the benefit of the explicit model assignment. As a first step, we could redefine `FormBuilder#fields` in terms of `FormHelper#fields`, and then maybe try to make `FormBuilder#fields_for` depend on `FormBuilder#fields` (I'm not yet clear on how beneficial this second step would be). Finally, I'm wondering if we could provide a way for `FormBuilder#fields_for` to handle `Hash`-like record_objects, even if only when `fields_options` parameter is explicitly provided  

If there is interest in this, I'm willing to have a go at it

**Comment by joshuapinter** [comment] 2022-11-18 16:08
Hey @MatElGran. First off, can I say that this is the most comprehensive response I have ever seen to an Issue, let alone an open-source one where you're not part of the core team. So well done and thank you! 🙏 

It certainly would be nice to have this fixed or at the very least documented but I know that's asking a lot more from what you've already done so I'll let one of the core team members determine the viability of this. 

For now, I will just use your suggested workaround and use some notes in the code to inform our team of the shortcomings of this and reference back to your diagnosis.

Thanks so much again for looking into this. Very much appreciated.

**Comment by MatElGran** [comment] 2022-11-23 11:45
Hi @joshuapinter, just a quick follow-up, I submitted #46554 which just got merged (first rails contrib \o/). While it does not fix the problem for `FormBuilder#fields_for`, it documents it, adds a way to ensure `record_object`is correctly used, and fixes `FormBuilder#fields`.

**Comment by joshuapinter** [comment] 2022-11-23 16:39
Great job @MatElGran! And congrats on the first Rails contribution. Very well deserved.

**Comment by ghiculescu** [comment] 2022-12-20 22:08
I think https://github.com/rails/rails/pull/46554 is as close as we will get to a fix here. I will close this issue, but if there's more fixes that could be made let me know and I can reopen.

**Closed by ghiculescu** 2022-12-20 22:08 UTC
Labels: actionview

**Comment by joshuapinter** [comment] 2022-12-20 22:12
:+1: Thanks again @MatElGran
