### ISSUE TITLE
collection_select cannot use instance variable when used in a partial

### ISSUE THREAD

**Issue by iandouglas** [rails/rails#32905] opened 2018-05-16 17:01 UTC
### Steps to reproduce

in controller do
```ruby
def new
  @collection = MyModel.all
  ...
end
```

in `/app/views/controller/new.html.erb` do
```ruby
<%= render partial "_form.html.erb" %>
```

in `/app/views/controller/_form.html.erb` do
```ruby
<%= form_for ... do |f| %>
  <%= f.collection_select( ..., ..., @collection, ...)
<% end %>
```

The `@collection` works just fine if we DON'T call our form in a partial.

We've tried passing `@collection` through locals and that has the same effect.

Ruby docs say that calling `MyModel.all` within the view is acceptable, but we'd like to be able to populate the `@collection` instance variable using other model methods.

### Expected behavior

A `<select>` form field is built as expected using the instance variable or locals variable when `collection_select` is using a a partial.

### Actual behavior

An error is thrown saying that @collection is nil (or that the 'local' value is also nil)

### System configuration

**Rails version**: 5.1.6

**Ruby version**: 2.4.x

**Comment by y-yagi** [comment] 2018-05-17 03:05
Can you please provide a sample application that reproduces the issue?

**Comment by savroff** [comment] 2018-05-19 02:06
Can't reproduce this issue too.

**Comment by udn** [comment] 2018-05-28 23:51
Can't reproduce this issue too. I'm trying to reproduce with this repository, https://github.com/udn/32905-issue, but failed to reproduce.

**Comment by y-yagi** [comment] 2018-05-28 23:56
Because no one can reproduce the issue, I will close this. 
If you can create an application to reproduce the issue, feel free to reopen. Thanks.

**Closed by y-yagi** 2018-05-28 23:56 UTC
Labels: needs work
