### ISSUE TITLE
Running 'rake assets:precompile' in dev mode makes Rails include code twice

### ISSUE THREAD

**Issue by jcoglan** [rails/rails#10091] opened 2013-04-04 18:55 UTC
In Rails 3.2.13, the default `application.js` depends on `jquery` and `jquery_ujs`. When you boot into development mode and load the default layout, you get three `script` tags: `jquery.js`, `jquery_ujs.js` and `application.js`, the last of which has no code in it.

Now run `rake assets:precompile`. The request for `application.js` now gets routed to `public/assets`, and you get a file containing all the minified source of `jquery.js` and `jquery_ujs.js`. However, you still get `script` tags for `jquery.js` and `jquery_ujs.js`.

So, Rails is both loading `application.js` from `public/assets` and reading the copy in `app/assets`, getting its dependencies and rendering `script` tags for those too.

This results in all JS code being loaded twice, causing all manner of weird bugs. Precompiling during development is useful for running tests, which is best done with static files rather than by booting Rails. Please make `javascript_include_tag` do something sane when it finds precompiled files in development mode.

**Comment by bluebird-communication** [comment] 2015-04-02 08:14
I can't use Highcharts because of this bug.
This bug leads to load twice the library of Highcharts and an error message (Uncaught Highcharts error #16).

I beg you to please correct it :(

**Comment by simi** [comment] 2015-04-02 08:17
@bluebird-communication can you provide rails version and steps how to reproduce this?

**Comment by bluebird-communication** [comment] 2015-04-02 08:20
Rails version 3.2.21

I put this into my Gemfile :

    gem 'jquery-rails'
    gem 'highcharts-rails', '~> 3.0.0'

I put this into my app/assets/javascripts/application.js :

    //= require jquery
    //= require jquery_ujs
    //= require_tree .
    //= require highcharts

**Comment by chrisccerami** [comment] 2015-05-04 14:10
This has been fixed as of Rails 4, right? This issue is contained to 3.2?

**Comment by geminiyellow** [comment] 2015-07-28 07:36
@simi sorry sir, i don't know why, but `hightcharts` still `error #16`.

i dont know why. i use `Rails 4.2.1` and webpack.
i use `webpack`, install `highcharts` from `npm`, then pack it into `app/assets/javascripts/client`.
and finally use `#=require highcharts.bundle` in `application.js`
when i start the application, alway `#16`. production mode is ok. just in development mode.

change `development.rb` 
    
    config.assets.prefix = '/dev/assets'

follow @dbaba and @idejuan 
work well, no `error #16`. what should i do?

**Comment by rafaelfranca** [comment] 2016-01-06 04:17
This issue only happen if you precompile the assets in development and have the debug option enabled. If you have debug enabled I don't see why precompile in development.

**Closed by rafaelfranca** 2016-01-06 04:17 UTC
Labels: asset pipeline, pinned

**Comment by andreif** [comment] 2017-03-20 18:10
@rafaelfranca Because I want to stare at my code for a few hours and feel that I am getting crazy because things don't work or act extremely weirdly. Thanks for that 👍

**Comment by andreif** [comment] 2017-03-20 18:33
I have removed `public/assets` but the server still serves the compiled version (curled it). I am now completely lost and don't see what I should configure to stop serving same javascript two times with assets debug. The only thing fixing it is prefix. This shit breaks bootstrap in a so weird way that trying to debug it is JUST INSANE. Well done guys.
