### ISSUE TITLE
Missing association filter query in sql

### ISSUE THREAD

**Issue by MeterSoft** [rails/rails#44828] opened 2022-04-02 08:54 UTC
### Steps to reproduce

```ruby
class Account < ApplicationRecord
  has_many :orders
end

class Order < ApplicationRecord
  belongs_to :account

  def self.search(name: name)
    Order.where(name: name)
  end
end
  
account.orders.search(name: 'hello')
```

### Expected behavior
Rails 5.2 it generate sql with `WHERE "orders"."account_id" = $1`

### Actual behavior
Rails 6.0.3 missing sql filter by account

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.7.0

**Comment by SkipKayhil** [comment] 2022-04-02 17:02
Hey @MeterSoft, I tried to reproduce this on 6.0.3 and was unable to.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "6.0.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :accounts, force: true do |t|
  end

  create_table :orders, force: true do |t|
    t.integer :account_id
    t.string :name
  end
end

class Account < ActiveRecord::Base
  has_many :orders
end

class Order < ActiveRecord::Base
  belongs_to :account

  def self.search(name:)
    Order.where(name: name)
  end
end

class BugTest < Minitest::Test
  def test_class_scope
    a = Account.create!
    o = a.orders.create!(name: 'hello')

    a2 = Account.create!
    o2 = a2.orders.create!(name: 'hello')

    assert_equal 1, a.orders.search(name: 'hello').to_a.length
  end
end
```

Do you have a repository or a reproduction script that could show the error?

**Comment by MeterSoft** [comment] 2022-04-02 17:59
> Hey @MeterSoft, I tried to reproduce this on 6.0.3 and was unable to.
> 
> ```ruby
> # frozen_string_literal: true
> 
> require "bundler/inline"
> 
> gemfile(true) do
>   source "https://rubygems.org"
> 
>   git_source(:github) { |repo| "https://github.com/#{repo}.git" }
> 
>   gem "rails", "6.0.3"
>   gem "sqlite3"
> end
> 
> require "active_record"
> require "minitest/autorun"
> require "logger"
> 
> # This connection will do for database-independent bug reports.
> ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
> ActiveRecord::Base.logger = Logger.new(STDOUT)
> 
> ActiveRecord::Schema.define do
>   create_table :accounts, force: true do |t|
>   end
> 
>   create_table :orders, force: true do |t|
>     t.integer :account_id
>     t.string :name
>   end
> end
> 
> class Account < ActiveRecord::Base
>   has_many :orders
> end
> 
> class Order < ActiveRecord::Base
>   belongs_to :account
> 
>   def self.search(name:)
>     Order.where(name: name)
>   end
> end
> 
> class BugTest < Minitest::Test
>   def test_class_scope
>     a = Account.create!
>     o = a.orders.create!(name: 'hello')
> 
>     a2 = Account.create!
>     o2 = a2.orders.create!(name: 'hello')
> 
>     assert_equal 2, Order.where(name: 'hello').size
>     assert_equal 1, a.orders.search(name: 'hello').to_a.length
>   end
> end
> ```
> 
> Do you have a repository or a reproduction script that could show the error?

hi, i changed your script as it is in my code

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "6.0.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :organizations, force: true do |t|
  end

  create_table :accounts, force: true do |t|
    t.integer :organization_id
  end

  create_table :orders, force: true do |t|
    t.integer :organization_id
    t.integer :account_id
    t.string :name
  end
end

class Organization < ActiveRecord::Base
  has_many :accounts
  has_many :orders
end

class Account < ActiveRecord::Base
  has_many :orders
  belongs_to :organization
end

class Order < ActiveRecord::Base
  belongs_to :account
  belongs_to :organization

  def self.search(org, name:)
    org.orders.where(name: name)
  end
end

class BugTest < Minitest::Test
  def test_class_scope
    org = Organization.create!

    a = org.accounts.create!
    o = a.orders.create!(organization: org, name: 'hello')

    a2 = org.accounts.create!
    o2 = a2.orders.create!(organization: org, name: 'hello')

    assert_equal 2, Order.where(name: 'hello').size
    assert_equal 1, a.orders.search(org, name: 'hello').to_a.length
  end
end
```

**Comment by SkipKayhil** [comment] 2022-04-02 18:35
Okay, I can confirm I'm seeing the difference between 5.2 and 6.0 now. However, this looks like a bug that was fixed in 6.0. By using `org` as the base of the query (as opposed to `Orders` or `self`, I think its expected that it should only be scoping based on the `org` and not on the `account`.

```ruby
# The query effectively ends up looking like this
a.orders.search(org, name: 'hello') # => org.orders.where(name: 'hello')
```

**Comment by MeterSoft** [comment] 2022-04-02 19:11
> Okay, I can confirm I'm seeing the difference between 5.2 and 6.0 now using your script. However, this looks like a bug that was fixed in 6.0. By using `org` as the base of the query (as opposed to `Orders` or `self`, I think its expected that it should only be scoping based on the `org` and not on the `account`.
> 
> ```ruby
> # The query effectively ends up looking like this
> a.orders.search(org, name: 'hello') # => org.orders.where(name: 'hello')
> ```

Sorry, Why behavior is different?
I need scope both organization and account. Can you change script and show me that it forks for 6.0?

My hot solution is change my `search` to
```ruby
def self.search(org, name:)
  where(organization_id: org.id, name: name)
end
```
But i want know why previous solution does not work anymore, thank

**Comment by SkipKayhil** [comment] 2022-04-02 19:53
> Sorry, Why behavior is different?

In the first case, your `search` method is creating a new relation because you are calling methods on `org`. What you want is for the `search` method to call methods on `Order` (like `Order#where` in your solution) so that it extends the existing relation instead of starting a new one.

**Comment by skipkayhil** [comment] 2024-11-11 20:17
I'm going to close this as I don't think there's a bug here.

**Closed by skipkayhil** 2024-11-11 20:17 UTC
Labels: activerecord, With reproduction steps
