### ISSUE TITLE
touching an active record instance should not trigger a stale object error

### ISSUE THREAD

**Issue by arianf** [rails/rails#34768] opened 2018-12-21 02:19 UTC
Sometimes a stale object error is triggered when you perform a touch on an active record instance if you have optimistic locking on.

When would you ever care that the object is out of date when you perform a touch action?

It'd be nice if it was possible to disable optimistic locking on certain columns

**Comment by kamipo** [comment] 2020-05-17 18:38
Duplicate of #16449.

**Closed by kamipo** 2020-05-17 18:38 UTC
Labels: activerecord, attached PR
