### ISSUE TITLE
"rails new" not initializing full app structure

### ISSUE THREAD

**Issue by jblac** [rails/rails#38358] opened 2020-01-31 07:06 UTC
### Steps to reproduce
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```
```
$ rails -v
Rails 6.0.2.1
```

```
$ rails new example_app
```
### Expected behavior
I expect a new application, `example_app`, to be initialized with a full and complete application structure.

### Actual behavior
```
$ rails new example_app
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
```

*
### System configuration
**Rails version**:
*Ruby version**:

**Comment by dominikstraessle** [comment] 2020-01-31 11:34
Same problem here:
# Steps to reproduce

```shell
# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.9.0
PRETTY_NAME="Alpine Linux v3.9"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

```shell
# ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-musl]
```

```shell
# ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-musl]
/usr/src/app/blog # rails -v
Rails 6.0.2.1
```

```shell
# rails new blog
```

## Expected behavior

I expect a new application, blog, to be initialized with a full and complete application structure.
## Actual behavior

```shell
# rails new blog
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
```

**Comment by eileencodes** [comment] 2020-01-31 16:21
I just tested this locally and wasn't able to reproduce, however I'm using macos and not linux and don't have access to a linux machine to test. Do other Rails versions install correctly? Does it install correctly if you use a newer Ruby version? Is your version of Git out of date?

**Comment by rafaelfranca** [comment] 2020-01-31 16:51
Duplicate of #38035

**Closed by rafaelfranca** 2020-01-31 16:51 UTC
