### ISSUE TITLE
Rails 6 : rails guides documentation / setup of rails via CLI

### ISSUE THREAD

**Issue by Lewiscowles1986** [rails/rails#38954] opened 2020-04-15 01:22 UTC
### Steps to reproduce

Follow the https://guides.rubyonrails.org/getting_started.html
At `rails serve` step, missing steps lead to complaint regarding webpacker.yml

### Expected behavior

The guide should instruct the user to `npm install -g yarn` if yarn is not already installed.

Following this `rails webpacker:install` should be run, and if possible a link to `rake -T webpacker` or that might cause confusion `rails -T webpacker` should be indicated as a place to get more information, or use to setup different frontend framework support.

### Actual behavior

Quite confusing error

```
traceback
,rvm/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:92 in `read': No such file or directory @ rb_sysopen - /home/lewis/projects/rails-blog/config/webpacker.yml (Errno:ENOENT)
```

### System configuration
**Rails version**:

6.0.2.2 (`rails --version`)

**Ruby version**:

ruby-2.7.1 (`rvm current`)

I'm running npm through nvm at v12.16.2 (`nvm current`) with yarn 1.22.4 (`yarn --version`)

I would be happy to contribute if someone might signpost me, either to docs, or to a place I can script the calls as part of the `rails new rails-blog` command (I know the name rails-blog seems redundant and differs from the guides. I have tried the verbatim name blog and as suspected it produced the same error within the ~/projects/blog folder)

**Comment by jonathanhefner** [comment] 2020-04-16 04:59
Duplicate of #38322.  Fixed by #38477.

You can find the most up-to-date instructions in the [edge guides](https://edgeguides.rubyonrails.org/getting_started.html#installing-node-js-and-yarn).

**Closed** 2020-04-16 07:12 UTC

**Comment by Lewiscowles1986** [comment] 2020-04-17 05:04
> You can find the most up-to-date instructions in the edge guides.

Except 6 isn't an edge and people should not need to look at the edge guides to deal with stable Rails.

Thank you for fixing, apologies for posting duplicate

**Comment by Lewiscowles1986** [comment] 2020-04-17 05:08
Looking again at those two, I think there is room for part of this still to go into the edgeguides as telling people to run install of webpacker is still missing. Thank you for signposting via PR link.
