### ISSUE TITLE
Activestorage: S3 presigned url get expired before access.

### ISSUE THREAD

**Issue by vsingh-cts** [rails/rails#32236] opened 2018-03-13 12:09 UTC
I am using active storage to store the files on AWS s3. and override the ActiveStorage::Service.url_expires_in = 24.hours default 300sec.

Sometimes while accessing the file is not loaded due to URL already expired. As I can check while accessing full Expired time is less than server time.

![screenshot](https://user-images.githubusercontent.com/35395302/37340720-fff4f598-26e4-11e8-8988-7a9d481f594d.png)

### Expected behavior
Generated URL must be accessible every time while accessing.

### Actual behavior
URL is already expired error message

### System configuration
**Rails version**: 5.2.0alpha

**Ruby version**: 2.5.0

**Comment by pixeltrix** [comment] 2018-03-13 13:22
@vsingh-cts can you double check your system clock - the time of the request is passed via `X-Amz-Date` parameter and the aws-sigv4 gem handles all of that. It's either that or you're somehow passing a `:time` option into the aws-sigv4 gem's method for building a presigned url.

**Comment by vsingh-cts** [comment] 2018-03-14 13:47
Hi @pixeltrix 
As I can check server system clock and S3 are in the same zone.
I think it might be the problem with browser cashing or turbolinks somehow cache the URL generated by 
`<%= image_tag(image.variant(resize: "#{size}x#{size}") %>`
and it fetch older url.
For now, I changed it to
`<%= image_tag(image.variant(resize: "#{size}x#{size}").try(:service_url) %>`
and  try to reporduce the issue.

Thanks

**Comment by pixeltrix** [comment] 2018-03-14 14:09
@vsingh-cts thanks for coming back - I'll have a look to see if the temporary url redirect is setting the the correct cache headers.

**Comment by pixeltrix** [comment] 2018-03-18 07:48
Yep, looks like they're being set - when I call the reference URL I get this:

```
Cache-Control: max-age=300, private
```

Wondering whether we need to also set `must-revalidate` - perhaps the browser was using a stale request? WDYT @georgeclaghorn ?

**Comment by cbisnett** [comment] 2018-04-19 02:48
I've run into a similar issue before and it was really hard to track down because it only happened some times. I was running an ElasticBeanstalk cluster in AWS and the AMI keys they use to sign the URLs apply to the instance and are removed when the instance is replaced. What this meant is that when I would generate a signed URL from an instance I could retrieve the data from S3 as long as that instance was still running. But if I generated a signed URL from an instance and then that instance was torn down due to auto-scaling (or it just died) then I would get an error that the request expired even though comparing the current time and the time returned in the error should mean that the request is still valid.

You can test if this is your issue by generating a URL that should be valid for a few hours and try downloading a file. If this works, then you know your signed URL is valid. Now terminate that instance and once it's completely gone, try hitting the signed URL again. If you get the access denied error that tells you the request is expired even though the expiration timestamp is still in the future, then you've hit this bug.

We worked around this bug by creating a set of IAM keys that we use specifically for signing S3 URLs since the keys aren't tied to any specific EC2 instance they won't be revoked because of auto-scaling. Doing this immediately cleared up any of these intermittent errors we were seeing. Hope this helps.

**Comment by wilg** [comment] 2018-04-21 08:02
It definitely seems to be a problem with browser caching, I'm experiencing this and I eventually figured out that a hard refresh in Chrome (Cmd+Shift+R) unbreaks the images.

**Comment by matthaliski** [comment] 2018-04-21 21:59
@wilg - I just ran into the same thing in Chrome (Version 65.0.3325.181). I saw your post after around 4 hours of smashing my head on the desk trying to figure out why my uploads all of a sudden stopped redirecting properly away from the blob.

Old images were all displaying fine, but after 5 minutes ([mentioned here](http://guides.rubyonrails.org/active_storage_overview.html#linking-to-files)) it borked and cached hard. 

Anywhoo, thanks for posting. Hard refresh brought all the images back for me.

**Comment by pixeltrix** [comment] 2018-04-23 07:01
@matthaliski can you tell me what headers are being returned from both the reference url request which generates the redirect and the S3 url request? I'm wondering whether the browser is trying to refetch the latter rather than the reference url and then redirecting again.

**Comment by matthaliski** [comment] 2018-04-23 17:59
No problem @pixeltrix. Here we go.

## First pass

**Blob request**

<img width="962" alt="1st pass blob request" src="https://user-images.githubusercontent.com/431169/39144164-da4cbeaa-46e4-11e8-8779-d665012860b3.png">

**S3 request**

<img width="962" alt="1st pass s3 request" src="https://user-images.githubusercontent.com/431169/39144187-e6fcf3ae-46e4-11e8-987e-baad63bcaaef.png">

## Second pass (a little over 5 minutes later)

**Blob request**

<img width="963" alt="2nd pass blob request" src="https://user-images.githubusercontent.com/431169/39144227-0070f24a-46e5-11e8-88d7-a5b22042497e.png">

**S3 request**

<img width="964" alt="2nd pass s3 request" src="https://user-images.githubusercontent.com/431169/39144239-0b9b8478-46e5-11e8-9b3f-b45836e744e4.png">

Sorry about the screenshots. I wasn't sure how else to export that data. I'm posting these without looking at them, but I'll respond further if I notice anything obvious.

And, to be ultra clear, if you force refresh after the second pass you get a good S3 request.

**Comment by pixeltrix** [comment] 2018-04-23 18:34
@matthaliski looks like the cache control headers on the redirect are wrong they should be something like this:

```
Cache-Control: max-age=300, private
```

Whereas your screenshot is showing the following:

```
Cache-Control: public, max-age=14400
```

When the temporary url expires on Amazon your browser is still seeing the cached redirect as valid - you can see in the screenshot where it says `(from disk cache)`. Since the S3 url has expired then that returns a 403 error. Apart from the issue with the expiry time it's also set to `public` which means that any intermediate proxy servers will cache the result and return it for other users - which is possibly not ideal if you're using authenticated access to resources.

As for why this is happening, I can see you're using CloudFlare so I suspect that something in your CDN config is changing the default headers returned by Active Storage. The forced reload ignores the disk cache, fetching a fresh redirect and begins working again.

@wilg @vsingh-cts @cbisnett could this be the same problem for you too? Do you have a CDN service sitting in front of your Rails application?

**Comment by wilg** [comment] 2018-04-23 21:02
Thanks @matthaliski! That solution makes sense to me, I'll try that and report back if I encounter any issues with.

**Comment by cbisnett** [comment] 2018-04-24 01:08
@pixeltrix I'm not using CloudFlare but I was using long-lived URLs (expiration set to `1.week.from_now`) and was storing those in PostgreSQL. In my case the links weren't being visited by a browser so there was no cache to worry about, but the symptoms the OP was describing matched the symptoms we saw. Good call on the caching headers though.

**Comment by dladowitz** [comment] 2018-05-07 00:55
I had this exact problem using Cloudflare and ActiveStorage. The page rule fix worked for me. Thanks!

**Comment by JonAbrams** [comment] 2018-05-31 22:52
Thanks for the workaround @matthaliski! 

Cloudflare really ought to pay attention to the origin's Cache-Control header. Has anyone reported this to them?

**Comment by wilg** [comment] 2018-06-04 19:26
I've unfortunately still seen occasional blank images even with the workaround in place, but I haven't figured out why yet.

**Comment by cj** [comment] 2018-06-22 04:50
I've just ran into `The provided token has expired.` using GCP, the issue is I'm streaming using video.js and it expires half way through playing the video.  Being able to change the expires per attachment would be nice.

**Comment by mskog** [comment] 2018-06-27 12:21
> Cloudflare really ought to pay attention to the origin's Cache-Control header. Has anyone reported this to them?

I'm not 100% sure about this but I think that Cloudflare will by default override any Cache-Control headers set to **less** than the Browser Cache Expiration setting in the "Caching" section. The default is 4 hours which explains the 14400 seconds in the example above. Setting it to "Respect Existing Headers" instead should make the problem go away.

**Comment by ManuelFrigerio** [comment] 2018-07-24 16:14
Hey guys,
I've tried both setting the browser expiration (on Cloudflare) to "Respect existing headers" and @matthaliski's page rule hack but the problem is still there. You can actually see the page here: https://littlered.life/

Has anyone solved this issue for good?

Thanks

**Comment by matthaliski** [comment] 2018-07-24 22:19
Hey @ManuelFrigerio,

I recently had to add another page rule: `https://leavingharbor.com/rails/active_storage/representations/*` to bypass caching. Maybe give that a go?

**Comment by ManuelFrigerio** [comment] 2018-07-25 10:30
@matthaliski thanks for that. I will try @JonAbrams's approach, which seems more reasonable. By the way, is it just me who thinks that implementing ActiveStorage is such a pain the ass, compared to gems like Paperclip or CarrierWave?

**Comment by ManuelFrigerio** [comment] 2018-07-25 11:40
It appears that the problem has been fixed now but I'm not entirely sure why 😅

**Closed** 2018-07-25 11:57 UTC
Labels: activestorage

**Comment by matthaliski** [comment] 2018-07-26 15:04
Yes, @JonAbrams I think that URL is probably fine. I was taking a "whitelist" approach and just okaying the URLs I saw Active Storage using. It's likely okay to bypass that entire path because -- and I haven't read through their source code -- it's only storing references to the large media residing somewhere else. Not a huge loss to lose from caching assuming you're not dealing with billions of users.

**Comment by ben-rabid** [comment] 2018-08-15 02:44
Just in case anyone else encounters this and is trying to debug it, make sure you double check the clock time of your workstation or server is accurate.

Our server drifted out enough to cause all URLs to be invalid even when they were newly generated.

**Comment by hainam8x** [comment] 2019-09-04 15:03
I have the same issue. It caused by cloudflare and Active Storage as you mention.

But I found another solution for this. Under "Caching" tab, there are option **Browser Cache Expiration** are default set to 4hours. Change to **Respect existing header** and that work for me.

![image](https://user-images.githubusercontent.com/11920842/64266752-58ca3380-cf5f-11e9-93b4-7e18353d7e8f.png)
