### ISSUE TITLE
Deterministically encrypted attributes add unwanted queries when other attributes are uniquely validated

### ISSUE THREAD

**Issue by zhuravel** [rails/rails#47562] opened 2023-03-02 20:35 UTC
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Encryption.configure(
  support_unencrypted_data: true,
  extend_queries: true,
  primary_key: SecureRandom.alphanumeric(32),
  deterministic_key: SecureRandom.alphanumeric(32),
  key_derivation_salt: SecureRandom.alphanumeric(32),
)

ActiveRecord::Encryption::ExtendedDeterministicUniquenessValidator.install_support

ActiveRecord::Schema.define do
  create_table :people, force: true do |t|
    t.bigint :site_id
    t.string :email
    t.string :username
    t.index [:site_id, :username], unique: true
  end
end

class Person < ActiveRecord::Base
  encrypts :email, deterministic: true, downcase: true

  validates :username, uniqueness: { scope: :site_id, case_sensitive: false }
end

class BugTest < Minitest::Test
  def test_bug
    Person.create!(site_id: 42, email: "alice@example.com", username: "PixiesFan")

    # Look at the # of queries performed in the SQL output.
    #
    # The code above makes 3 SELECT queries before doing INSERT,
    # but I believe only the 1st SELECT should be executed:
    #
    #  SELECT 1 AS one FROM "people" WHERE LOWER("people"."username") = LOWER(?) AND "people"."site_id" = ? LIMIT ?  [["username", "PixiesFan"], ["site_id", 42], ["LIMIT", 1]]
    #  SELECT 1 AS one FROM "people" WHERE LOWER("people"."username") = LOWER(?) AND "people"."site_id" = ? LIMIT ?  [["username", "{\"p\":\"5wDVc4FrlD8O\",\"h\":{\"iv\":\"PKIelpDwQmEDjWnW\",\"at\":\"T39guTPcxT0EadJ9bcG5+w==\"}}"], ["site_id", 42], ["LIMIT", 1]]
    #  SELECT 1 AS one FROM "people" WHERE LOWER("people"."username") = LOWER(?) AND "people"."site_id" = ? LIMIT ?  [["username", "pixiesfan"], ["site_id", 42], ["LIMIT", 1]]
    #  INSERT INTO "people" ("site_id", "email", "username") VALUES (?, ?, ?)  [["site_id", 42], ["email", "{\"p\":\"gOJfTLBzlDnAWcYGx426MtE=\",\"h\":{\"iv\":\"ACu7afkEmnfGU3K0\",\"at\":\"Tc/Pt59+ZF+YY1sGV3Ni2Q==\"}}"], ["username", "PixiesFan"]]
    #
    # Attribute `username` is not encrypted, and should not be validated as such (2nd SELECT).
    # LOWER("PixiesFan") also equals LOWER("pixiesfan") so the 3rd SELECT looks redundant.
  end
end
```

### Expected behavior
When the model has some deterministically encrypted attribute and another uniquely validated non-encrypted attribute, the uniqueness validator makes unwanted queries.

### Actual behavior
Non-encrypted attribute should not be validated as such, and the uniqueness validator in the provided test should make 1 SELECT query instead of 3.

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 3.2.1

**Comment by eileencodes** [comment] 2023-03-02 21:03
Hi @zhuravel this is a duplicate of https://github.com/rails/rails/issues/46195 which I believe is fixed by https://github.com/rails/rails/pull/46256. We had to revert the followup commit, but I don't think that fixes this issue. Can you verify if this is fixed on main?

**Comment by zhuravel** [comment] 2023-03-02 21:12
Hi @eileencodes. I checked and this is fixed on main, thanks.

**Closed** 2023-03-03 04:41 UTC
Labels: activerecord, duplicate
