### ISSUE TITLE
ActiveModel::Type::ImmutableString, ActiveModel::Type::String #cast_value(value) freeze string value in-place

### ISSUE THREAD

**Issue by zlobz** [rails/rails#24185] opened 2016-03-14 12:03 UTC
### Steps to reproduce

not_frozen_string = ''
not_frozen_string.frozen? # false
cast_value(not_frozen_string)
not_frozen_string.frozen? # true
### Expected behavior

ActiveModel::Type::String#cast_value(value) doesn't freeze string value in-place
ActiveModel::Type::ImmutableString#cast_value(value) doesn't freeze string value in-place
### Actual behavior

ActiveModel::Type::String#cast_value(value) freezes string value in-place
ActiveModel::Type::ImmutableString#cast_value(value) freezes string value in-place
### System configuration

Rails master
### My monkey patch

``` ruby
ActiveModel::Type::ImmutableString.class_eval do
  def cast_value(value)
    case value
    when true then 't'.freeze
    when false then 'f'.freeze
    when ::String then ::String.new(value).freeze
    else value.to_s.freeze
    end
  end
end
```

**Comment by sgrif** [comment] 2016-03-16 23:12
The entire point of the `ImmutableString` type is to avoid duplicating the string. If you need mutability, don't use it. We never use this type by default.

**Comment by xzo** [comment] 2016-03-18 15:25
@sgrif 
Rails uses ImmutableString by default.
```ruby
name = 'John'
name.frozen? # false
forum = User.new name: name
forum.save
name.frozen? # true
```

**Comment by sgrif** [comment] 2016-03-19 01:45
Keeping a strong reference to anything passed to Active Record violates the ownership contract. Mutating that value would cause unexpected bugs to occur. You must access that value via `user.name`

**Comment by matthewd** [comment] 2016-03-20 17:14
> Keeping a strong reference to anything passed to Active Record violates the ownership contract

We have an ownership contract? That involves us stealing ownership of a passed argument??

**Comment by aprescott** [comment] 2016-06-10 19:58
I share @matthewd's confusion. If "keeping a strong reference [...] violates the ownership contract", then why is that an argument for _freezing strings AR doesn't own_?

I described a scenario in #25353 (closed as a duplicate of this issue) where a simple unit test breaks because of interplay between shoulda-matchers and Active Record's own Postgres adapter. shoulda-matchers assumes that a string constant passed in to an Active Record model won't be modified in-place, which seems completely reasonable. That a call to `valid?` freezes a library's string (a fairly global state change!) seems like something you'd want to _avoid_ if the aim is to not have strong references.

**Comment by kaspth** [comment] 2016-07-29 14:55
We're seeing this too in our app.

<details>
  <summary>Reproducible with this script</summary>
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '5.0.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :orders, force: true do |t|
    t.string :person_email
    t.belongs_to :person
  end

  create_table :people, force: true do |t|
    t.string :email
  end
end

class Order < ActiveRecord::Base
  belongs_to :person, optional: true

  validates_presence_of :person_email

  before_save { person_email.strip! }

  def build
    create_person!(email: person_email)

    # Other order setup...

    save!
  end
end

class Person < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_order_building
    order = Order.create(person_email: 'one@example.com')

    assert order.build # Raises can't modify frozen String.
  end
end
```
</details>

I'd expect the test to pass, as it did in 4.2.7, but on Rails 5.0.0 a `RuntimeError: can't modify frozen String` is raised.

@sgrif you say Active Record has an ownership contract. I'd like to reraise @matthewd's point:

> We have an ownership contract? That involves us stealing ownership of a passed argument??

**Closed** 2017-04-11 22:03 UTC
Labels: activemodel, attached PR, With reproduction steps
