### ISSUE TITLE
ActionController::Parameters issue with DELETE in Testing only.

### ISSUE THREAD

**Issue by nanark** [rails/rails#31149] opened 2017-11-14 10:16 UTC
With Rails 5.1.4.

I have a different param return using the GET or DELETE http verb **in testing condition only**.

Here is what I send:
```ruby
require 'test_helper'

#
class LikesControllerTest < ActionDispatch::IntegrationTest
  test 'like project' do
    attributes = {
      like: {
        project_ref: 'PROJECT_1_REF'
      }
    }
    # WITH DELETE
    delete api_v3_destroy_like_path, headers: { user: 1 }, as: :json, params: attributes

    # WITH GET
    get api_v3_destroy_like_path, headers: { user: 1 }, as: :json, params: attributes
  end
end
```

And this is what I get in return:
```ruby
# WITH DELETE
<ActionController::Parameters {"{\"like\":{\"project_ref\":\"PROJECT_1_REF\"}}"=>nil, "controller"=>"api/v3/likes", "action"=>"destroy", "like"=>{}} permitted: false>

# WITH GET
<ActionController::Parameters {"like"=>{"project_ref"=>"PROJECT_1_REF"}, "controller"=>"api/v3/likes", "action"=>"destroy"} permitted: false>
```

So with DELETE I get an additional `like => {}` with the previous `{like}` as a key.
I have no issue of that kind using Postman or when the API is called from an application. It is stricly observed using the `test_helper` lib.

**Comment by rafaelfranca** [comment] 2017-11-14 19:51
Can you please provide a sample application that reproduces the error?

**Comment by nanark** [comment] 2017-11-14 20:18
Of course: https://github.com/nanark/testing_param_issue

```
rails server
rails t
```

**Comment by y-yagi** [comment] 2017-11-16 03:56
It seems to be the same issue as #30570(cause a rack test https://github.com/rack-test/rack-test/issues/200).
Does it work properly if removing `as: :json` from DELETE request?

**Comment by nanark** [comment] 2017-11-16 09:17
Yes it looks like the same issue.

```
# without as: json
<ActionController::Parameters {"where_am_i"=>{"id"=>"1"}, "controller"=>"sample", "action"=>"test_delete"} permitted: false>
"{\"where_am_i\":{\"id\":\"1\"},\"controller\":\"sample\",\"action\":\"test_delete\"}"
```

**Comment by rafaelfranca** [comment] 2017-11-16 20:52
Duplicate of #30570

**Closed by rafaelfranca** 2017-11-16 20:52 UTC
Labels: actionpack
