### ISSUE TITLE
Rails console was crash with Rails 5.0.0.1 and Ruby 2.3.1

### ISSUE THREAD

**Issue by amicming** [rails/rails#27010] opened 2016-11-11 05:26 UTC
### Steps to reproduce
bundle exec rails c --sandbox

### Expected behavior
Should Display Rails Console

### Actual behavior
https://gist.github.com/amicming/f7a561a1ffa9cea2c70c10edbdacc7f3

### System configuration
**Rails version**: 5.0.0.1
**Ruby version**: 2.3.1

**Comment by amicming** [comment] 2016-11-11 05:27
looks like ```--sandbox``` not available in Rails 5.0.0.1

**Comment by amicming** [comment] 2016-11-11 05:32
```bundle exec rails c``` working fine, but on rails console if I write ```user = User.first``` generating blow error.

https://gist.github.com/amicming/c9a44c09e864f202f422be8577b1a764

**Comment by esparta** [comment] 2016-11-11 07:10
Are you using MacOS Sierra?
If the answer is yes, then is probably a duplicate of #26609 and can probably be fixed on #26965

**Comment by maclover7** [comment] 2016-11-12 02:20
👍 closing as a duplicate of #26609.

**Closed by maclover7** 2016-11-12 02:20 UTC
Labels: railties

**Comment by amicming** [comment] 2016-11-15 19:55
@esparta Thanks for the link, yes - I am using MacOS Sierra, @maclover7 - sorry for the duplicate of #26609. I have to check before I opened.
