### ISSUE TITLE
Using backticks in erb files will produce standard production error in development mode

### ISSUE THREAD

**Issue by KNejad** [rails/rails#38404] opened 2020-02-07 10:58 UTC
When using the wrong quotation mark (`‘` instead of `'`) in development, I would expect a relevant error page pointing to the line causing the issue. Instead I am receiving a generic "We're sorry, but something went wrong." page.

### Steps to reproduce

```
rails new bad_quote
cd bad_quote
rails generate scaffold bad_quote_example
rails db:migrate
echo "<%= submit_tag ‘Search’ %>" >>  app/views/bad_quote_examples/index.html.erb
rails s
firefox localhost:3000/bad_quote_examples
```

**Note**: This works fine in Rails 5.2.4.1 and I get the error page I would expect. It seems to be a new issue with Rails 6

### Expected behavior

The standard development error page pointing to the line causing the error with an error message, or some relevant output in the console

### Actual behavior

I see the standard "We're sorry, but something went wrong."  error message with the following console output:

```
Started GET "/bad_quote_examples" for ::1 at 2020-02-07 10:51:21 +0000
Processing by BadQuoteExamplesController#index as HTML
  Rendering bad_quote_examples/index.html.erb within layouts/application
  BadQuoteExample Load (0.1ms)  SELECT "bad_quote_examples".* FROM "bad_quote_examples"
  ↳ app/views/bad_quote_examples/index.html.erb:13
  Rendered bad_quote_examples/index.html.erb within layouts/application (Duration: 128.1ms | Allocations: 74658)
Completed 500 Internal Server Error in 130ms (ActiveRecord: 0.1ms | Allocations: 75822)
```

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.0

**Comment by eugeneius** [comment] 2020-02-07 11:39
This is a duplicate of https://github.com/rails/rails/issues/38056, which was fixed by https://github.com/rails/rails/pull/38059. The fix will be released in 6.0.3.

**Closed by eugeneius** 2020-02-07 11:39 UTC
Labels: actionview
