### ISSUE TITLE
Generate Scaffold with a namespace 

### ISSUE THREAD

**Issue by GildedHonour** [rails/rails#21652] opened 2015-09-17 13:23 UTC
Is  this a bug in Rails 4.2.0?

```
rails g scaffold MyNamespace::Address
```

And this what it generates:

```
class MyNamespace::AddressesController < ApplicationController
  # ...........

  def create
    @my_namespace_address = MyNamespace::Address.new(address_params) # doesn't match my_namespace_address_params

    @my_namespace_address.save
    respond_with(@my_namespace_address)
  end

  def update
    @my_namespace_address.update(address_params)  # doesn't match my_namespace_address_params
    respond_with(@my_namespace_address)
  end

  def destroy
    @my_namespace_address.destroy
    respond_with(@my_namespace_address)
  end

  private
    def set_my_namespace_address
      @my_namespace_address = MyNamespace::Address.find(params[:id])
    end

    def my_namespace_address_params # 1
      params[:my_namespace_address]
    end
```

**Comment by pixeltrix** [comment] 2015-09-21 15:14
@GildedHonour yes, that looks like a bug

**Comment by pixeltrix** [comment] 2015-09-21 15:15
@GildedHonour do you know whether it worked correctly in 4.1? If you don't then I'll check it myself so don't worry about it.

**Comment by hansondr** [comment] 2015-09-24 17:52
@pixeltrix, verified it is working in 4.1.13

```ruby
class MyNamespace::AddressesController < ApplicationController
  # ...........

  def create
    @my_namespace_address = MyNamespace::Address.new(my_namespace_address_params)

    respond_to do |format|
      if @my_namespace_address.save
        format.html { redirect_to @my_namespace_address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @my_namespace_address }
      else
        format.html { render :new }
        format.json { render json: @my_namespace_address.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @my_namespace_address.update(my_namespace_address_params)
        format.html { redirect_to @my_namespace_address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_namespace_address }
      else
        format.html { render :edit }
        format.json { render json: @my_namespace_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # ...........

  private
    def set_my_namespace_address
      @my_namespace_address = MyNamespace::Address.find(params[:id])
    end

    def my_namespace_address_params
      params[:my_namespace_address]
    end
end
```

**Comment by pixeltrix** [comment] 2015-09-25 16:00
@hansondr can you replicate it anywhere?

**Comment by hansondr** [comment] 2015-09-25 16:50
@pixeltrix no, I tried 4.1.0, 4.1.13, 4.2.0 and 4.2.4 and I was unable to reproduce @GildedHonour's generated output.  I don't believe I messed up my testing process but I was doing the following:

```
$ gem install 'rails' --version 4.1.0
$ rails _4.1.0_ new scaffold_test
$ cd scaffold_test
$ rails g scaffold MyNamespace::Address
$ sed '26,38!d' app/controllers/my_namespace/addresses_controller.rb
```
expected output:
```ruby
  def create
    @my_namespace_address = MyNamespace::Address.new(my_namespace_address_params)

    respond_to do |format|
      if @my_namespace_address.save
        format.html { redirect_to @my_namespace_address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @my_namespace_address }
      else
        format.html { render :new }
        format.json { render json: @my_namespace_address.errors, status: :unprocessable_entity }
      end
    end
  end
```

**Comment by naliwajek** [comment] 2015-10-21 10:49
I wasn't able to reproduce it either (Ruby 2.1.2 and ruby-head, Rails 4.2 and 4.2.4) unless there's something more to the setup process than what @hansondr wrote.

**Comment by arunagw** [comment] 2015-10-26 09:36
I am not be able to reproduce this Rails 4.2.4. Closing this for now.

@GildedHonour please reopen this if you still this issue. thanks.

**Closed by arunagw** 2015-10-26 09:36 UTC
Labels: needs feedback, railties
