### ISSUE TITLE
activerecord runtime error with database version

### ISSUE THREAD

**Issue by wikimo** [rails/rails#46181] opened 2022-10-03 07:23 UTC
### Steps to reproduce

When use activerecord, it returns like that
RuntimeError (Your version of MySQL (5.1.35) is too old. Active Record supports MySQL >= 5.5.8.)

for example
```ruby
model.first 
model.last
ActiveRecord::Base.connection.current_database
```

When use gem mysql2, it's ok
```ruby
connect = Mysql2::Client.new(host: 'hostname', username: 'username', password: 'password', database: 'name_db')
result = connect.query('SELECT version()')

# {"version()"=>"5.6.16-log"} 
p result.first
```

### System configuration
**Rails version**: 6.0.3.7

**Ruby version**: 2.7.6

**Comment by yahonda** [comment] 2022-10-03 08:42
Rails uses mysql2 gem. However that does not mean Rails support every MySQL versions that mysql2 gem does.
MySQL 5.1 support has been dropped since Rails 6.0 via https://github.com/rails/rails/pull/33853 .

**Comment by fatkodima** [comment] 2022-10-03 08:48
> # {"version()"=>"5.6.16-log"} 

Seems like the problem is that rails incorrectly identifies the mysql version, am I right, @wikimo? If this is the case, can you reproduce on the latest changes from the rails `main` branch?

**Comment by yahonda** [comment] 2022-10-03 09:04
Reopened this issue because I misunderstood it. I do not know which database shows `5.6.16-log` as database version, though.

**Comment by byroot** [comment] 2022-10-03 20:09
And even then, the code handle a suffix like this just fine: 

```ruby
>> v = ActiveRecord::ConnectionAdapters::AbstractAdapter::Version.new("5.6.16-log", "5.6.16-log")
=> #<ActiveRecord::ConnectionAdapters::AbstractAdapter::Version:0x00007f8b8b6f43e8 @full_version_string="5.6.16-log", @version=[5, 6, 16]>
```

**Comment by byroot** [comment] 2022-10-03 20:16
@wikimo could you show us the result of:

```ruby
connect = Mysql2::Client.new(...)
connect.server_info[:version]
```
Since that's what Rails uses to get the MySQL version.

Also a bit of warnings, Rails 6.0 isn't supported since a long time, so there's no way we backport a fix for that, I'd just like to make sure it's fixed on current versions.

**Comment by wikimo** [comment] 2022-10-04 13:37
Yes, you're right. @fatkodima

**Comment by wikimo** [comment] 2022-10-04 13:53
It returns '5.1.35'. Maybe it's the database issue.  SQL 'select version()' returns '5.6.16', but code returns 5.1.35. We use the aliyun analyticdb compatible MySQL. It's an OLAP DB. Thanks for your help.  @byroot 

```ruby
# returns 5.1.35
connect.server_info[:version]
```

**Comment by wikimo** [comment] 2022-10-04 14:04
Is it can set the adapter version with code? @byroot 
```ruby
ActiveRecord::ConnectionAdapters::AbstractAdapter::Version.new
```

**Comment by byroot** [comment] 2022-10-04 14:05
@wikimo sorry I don't understand your question.

**Comment by byroot** [comment] 2022-10-04 14:09
> Maybe it's the database issue. SQL 'select version()' returns '5.6.16', but code returns 5.1.35. We use the aliyun analyticdb compatible MySQL. It's an OLAP DB. 

Definitely an issue with your database. Somehow they patched `version()`, but the `server_info` wasn't updated.

If you can, you should report this to the maintainers of that database, here's how mysql2 get this info: https://github.com/brianmario/mysql2/blob/8193dc412c6a266045b9d13a9da36c16750939a4/ext/mysql2/client.c#L1015

Just tell them that `mysql_get_server_info` return `5.1.35` they should be able to understand where their bug is.

In the meantime, you can probably workaround this issue by creating a custom Mysql adapter that inherits from the default one and just return a fake version. Here's an example of such adapter: https://github.com/Shopify/activerecord-pedantmysql2-adapter

Given that we're now certain this is a third party issue, I'll close.

**Closed by byroot** 2022-10-04 14:09 UTC
Labels: activerecord

**Comment by jicheng1014** [comment] 2025-02-16 03:14
@wikimo 

add a  patch file to config/initializers/

```ruby
module ActiveRecord
  module ConnectionAdapters
    module CheckVersionPatch
      def check_version
        @version = [5, 6, 16]
        true
      end

      def database_version
        [5, 6, 16]
      end

      def get_database_version
        [5, 6, 16]
      end
    end
  end
end

ActiveSupport.on_load(:active_record) do
  ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter.prepend(
    ActiveRecord::ConnectionAdapters::CheckVersionPatch
  ) if defined?(ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter)
end
```
