### ISSUE TITLE
Two definition of find_by in ActiveRecord ( 4.2.0rc3)

### ISSUE THREAD

**Issue by briseis** [rails/rails#18326] opened 2015-01-04 15:46 UTC
Hi evryone,
I'm not a computer guy and not fluent in English ... Sorry.

There are two definition of find_by (and find_by! and find ids)
One is define in activerecord-4.2.0.rc3/lib/active_record/core.rb line 161
One is define in activerecord-4.2.0.rc3/lib/active_record/relation/finder_methods.rb line 84

In my application, the last one (in FinderMethods) works, but not the first one.
Unfortunately, when we call

Post.find_by name: 'Spartacus', rating: 4

the last one (in Core) is call.

Is it normal ? 
How to explicitly call the one in FinderMethods ?
the find_by in Core will be depreciated ? 
and replace by find_in FinderMethods ?

Thanks
Laurent

**Comment by rafaelfranca** [comment] 2015-01-04 15:51
First, make sure you are using the final version of 4.2.0.

Second, the core.rb definition call the finder_methods.rb definition.

Could you explain what is "doesn't work"?

**Comment by rafaelfranca** [comment] 2015-01-04 15:52
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by briseis** [comment] 2015-01-04 16:35
Thanks  rafaelfranca
I have an application on Rails 3 that use "inheritance" with the gem "Citier"
(see https://github.com/petehamilton/citier)
based on a previous gem CITIEsForRails
(see https://github.com/altrabio/CITIEsForRAILS)
Unfortunately, theses gem doen't work with rails 4. So I try to update cities for rails 4, in a
"citier4" gem.
Work is not finish, but you can download citier4 in
https://rubygems.org/gems/citier4

If you run the test as it is, it is ok, because I overwrite "find_by" in "lib/root_class_method.rb"
but if you remove the find_by oveerwrite, then you have a failure in the test, because attributes of and child class (Book) are not present then you perform
Product.find_by name: "UnLivre"

(For run the test, you have to build the db, in dummy : 
cd test/dummy
rake db:migrate
cd ../..
rake test

Sorry, It is the first time a try to explain. Be gentle ...
Thanks
Laurent

**Comment by briseis** [comment] 2015-01-04 16:48
It is not a bug, but a different behaviours (with the citier4 gem)
In Core, the result is (with no author attribute)

Product.find_by name: "UnLivre"
  Product Load (0.3ms)  SELECT  "products".* FROM "products" WHERE "products"."name" = ? LIMIT 1  [["name", "UnLivre"]]
 => #<Book id: 1, name: "UnLivre", type: "Book", created_at: "2015-01-04 11:26:43", updated_at: "2015-01-04 11:26:43"> 

In FinderMethods, the result include author attribute (with two loads)
 
Product.find_by name: "UnLivre"
Product Load (0.4ms)  SELECT  "products".* FROM "products" WHERE "products"."name" = ? LIMIT 1  [["name", "UnLivre"]]
Book Load (0.3ms)  SELECT  "view_books".* FROM "view_books" WHERE "view_books"."type" IN ('Book') AND "view_books"."id" = ? LIMIT 1  [["id", 1]]
 => #<Book id: 1, name: "UnLivre", type: "Book", created_at: "2015-01-04 11:26:43", updated_at: "2015-01-04 11:26:43", author: "Inconnu", title: nil>

**Comment by rafaelfranca** [comment] 2015-01-04 19:58
This seems to be more a problem in the gem that needs to change its implementation to match the 4.2.0 find_by implementation. If core.rb implementation doesn't work it is because it use the new statement cache feature and you would need to avoid it.

Closing since it is not Rails issue.

**Closed by rafaelfranca** 2015-01-04 19:58 UTC
Labels: activerecord
