### ISSUE TITLE
active_support/core_ext/array/conversions raises when required

### ISSUE THREAD

**Issue by zenspider** [rails/rails#49709] opened 2023-10-19 22:59 UTC
### Steps to reproduce

found via cocoapods, running `pod` blows up:

```
5549 % ruby -ractive_support/core_ext/array/conversions -e 0
/private/tmp/xxx/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
	from /private/tmp/xxx/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
	from <internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `require'
	from <internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `rescue in require'
	from <internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
<internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- active_support/core_ext/array/conversions (LoadError)
	from <internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

### Expected behavior

requiring any file in rails shouldn't raise

### Actual behavior

see above

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment] 2023-10-19 23:03
Duplicate of https://github.com/rails/rails/issues/49495?

**Comment by zenspider** [comment] 2023-10-19 23:38
ah... but do they have a fix incoming?

**Closed** 2023-10-19 23:47 UTC

**Comment by rafaelfranca** [comment] 2023-10-20 00:42
https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support

**Comment by rafaelfranca** [comment] 2023-10-20 00:44
BTW, https://github.com/CocoaPods/CocoaPods/pull/12082
