### ISSUE TITLE
t("foo", default: false) doesn't respect the default

### ISSUE THREAD

**Issue by jdelStrother** [rails/rails#31426] opened 2017-12-13 09:51 UTC
### Steps to reproduce

Try to translate a key, supplying a default of `false` ( eg `t("foo", default: false)`).

### Expected behavior

If the translation is missing, it returns `false`

### Actual behavior

If the translation is missing, it returns `<span class="translation_missing" title="translation missing: en.false">False</span>`

This is also demonstrated in this sample project:
[rails51.zip](https://github.com/rails/rails/files/1554939/rails51.zip)

### System configuration
**Rails version**:

5.1.4

**Ruby version**:

2.3.4

This appears to be a change in the i18n gem since 0.8.3 - if you downgrade to 0.8.1, `t("foo", default: false)` return `false`.
However, the problem only occurs if you use Rails `t` helper - if you go via `I18n.t("foo", default: false)`, it returns false regardless of the i18n version.

This was originally filed on the i18n repo at https://github.com/svenfuchs/i18n/issues/379.

**Comment by utilum** [comment] 2017-12-13 11:05
@jdelStrother could you reproduce with an executable script based on https://github.com/rails/rails/blob/master/guides/bug_report_templates/generic_gem.rb ?

**Comment by jdelStrother** [comment] 2017-12-13 11:20
Will see what I can do

**Comment by adityan-webonise** [comment] 2017-12-13 13:08
I think the issue is with Array being passed as an option [here](https://github.com/rails/rails/blob/v5.1.4/actionview/lib/action_view/helpers/translation_helper.rb#L62) in the Rails helper.
`I18n.translate('foo', default: [false])` returns `"translation missing: en.foo"`

And thus, the helper encapsulates it [here](https://github.com/rails/rails/blob/v5.1.4/actionview/lib/action_view/helpers/translation_helper.rb#L108) in the `rescue` block. I wonder if its an update on Rails side or I18n side that has caused this to happen.

**Comment by aditya-vector** [comment] 2017-12-13 13:18
I think the issue is with Array being passed as an option [here](https://github.com/rails/rails/blob/v5.1.4/actionview/lib/action_view/helpers/translation_helper.rb#L62) in the Rails helper.
The code in the helper encapsulates the `default` option to an array no matter what. And, thus on the I18n side when I run,
`I18n.translate('foo', default: [false])` it returns `"translation missing: en.foo"`

And then, the helper transforms it to the message `"<span class=\"translation_missing\" title=\"translation missing: en.false\">False</span>"` [here](https://github.com/rails/rails/blob/v5.1.4/actionview/lib/action_view/helpers/translation_helper.rb#L108) in the `rescue` block. I wonder if its an update on Rails side or I18n side that has caused this to happen.

**Comment by jdelStrother** [comment] 2017-12-17 12:27
FWIW, a simple test case.  For me, flipping between i18n 0.8.1 & 0.8.3 will fix/break the test.

```ruby
# frozen_string_literal: true

gem "bundler", "< 1.16"

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", tag: 'fd1304d'
  
  # gem "i18n", "0.8.1"
  gem "i18n", "0.8.3"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render inline: "<%= t(:foo, default: false) || 'no default' %>"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_default_false_translations_should_return_false
    assert I18n.t(:foo, default: false) == false
    
    get "/"
    assert_equal "no default", last_response.body
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by fatkodima** [comment] 2018-01-10 20:03
It is not a bug, it is a [documented](http://edgeapi.rubyonrails.org/classes/ActionView/Helpers/TranslationHelper.html#method-i-translate) behavior of view's translation helper.

**Comment by rafaelfranca** [comment] 2018-01-10 20:07
If that is the case this is a i18n issue since they changed the behavior in a patch version.

**Comment by fatkodima** [comment] 2018-01-10 21:40
Opened PR on i18n side https://github.com/svenfuchs/i18n/pull/399.

**Comment by y-yagi** [comment] 2018-03-18 01:19
Fixed with https://github.com/svenfuchs/i18n/pull/399

**Closed by y-yagi** 2018-03-18 01:19 UTC
Labels: i18n
