### ISSUE TITLE
Eager load populating wrong number of records for through associations.

### ISSUE THREAD

**Issue by Mihail-K** [rails/rails#30766] opened 2017-10-01 04:38 UTC
### Steps to reproduce
```ruby
class Conversation < ApplicationRecord
  has_many :conversation_users, inverse_of: :conversation
  has_many :users, through: :conversation_users
end

class ConversationUser < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
end

class User < ApplicationRecord
end

Conversation.create(users: [User.new, User.new])
```

### Expected behaviour
```ruby
conversation = Conversation.includes(:users).first
conversation.users.count         # => 2
conversation.users.length        # => 2
conversation.users.reload.length # => 2
```

### Actual behaviour
```ruby
conversation = Conversation.includes(:users).first
conversation.users.count         # => 2
conversation.users.length        # => 1
conversation.users.reload.length # => 2
```

### System configuration
**Rails version**:
5.1.4
**Ruby version**:
2.3.4

**Comment by narrator0** [comment] 2017-10-14 09:05
@Mihail-K I tried to reproduce the bug using the code below but things seem to behave normally. Is there something that I missed?

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :conversations, force: true do |t|
  end

  create_table :users, force: true do |t|
  end

  create_table :conversation_users, force: true do |t|
    t.integer :conversation_id
    t.integer :user_id
  end
end

class Conversation < ActiveRecord::Base
  has_many :conversation_users, inverse_of: :conversation
  has_many :users, through: :conversation_users
end

class ConversationUser < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_count
    Conversation.create(users: [User.new, User.new])
    conversation = Conversation.includes(:users).first

    assert_equal 2, conversation.users.count
    assert_equal 2, conversation.users.length
    assert_equal 2, conversation.users.reload.length
  end
end
```

**Comment by kamipo** [comment] 2017-10-20 06:13
Closing this since I also tried the script to reproduce the issue, but it works as expected on 5.0, 5.1, and master.

**Closed by kamipo** 2017-10-20 06:13 UTC
