### ISSUE TITLE
Respect `X-Forwarded-Port`

### ISSUE THREAD

**Issue by kayhide** [rails/rails#39366] opened 2020-05-20 13:56 UTC
### Steps to reproduce
1. Create a new rails app.
2. Create a controller and action.
3. Start the server
4. Make a request with the html headers of `X-Forwarded-Host:okinawa` and `X-Forwarded-Port:42`.
5. See the `request.port` or `request.base_url`.

Commands are like the followings:

```console
$ rails new forwarded_port --skip-active-record --skip-javascript
...
$ cd forwarded_port
$ rails g controller home index
... Edit app/controllers/home_controller.rb to show the variables,
... it would be something I put below.
... Also edit config/application.rb and add `config.hosts << "okinawa"` to
... allow `X-Forwarded-Host`.
$ rails s
... This should start a server on http://localhost:3000
... Then go to another terminal.
$ curl -H "X-Forwarded-Host:okinawa" -H "X-Forwarded-Port:42" http://localhost:3000/home/index
... Here, you will see the variables.
request.base_url: http://okinawa
request.port: 80

HTTP_X_FORWARDED_PORT: 42
Rack::Request::Helpers#port: 42
```

```rb
class HomeController < ApplicationController
  def index
    render inline: <<EOS
request.base_url: #{request.base_url}
request.port: #{request.port}

HTTP_X_FORWARDED_PORT: #{request.get_header "HTTP_X_FORWARDED_PORT"}
Rack::Request::Helpers#port: #{Rack::Request::Helpers.instance_method(:port).bind(request).call}
EOS
  end
end
```

Note that the last 2 lines of the output are for reference.
Rack seems to take care of the port as expected.

### Expected behavior
`request.port` to return `42`.
`request.base_url` to return `http://okinawa:42`.

### Actual behavior
`request.port` to return `80`.
`request.base_url` to return `http://okinawa`.

### System configuration
**Rails version**:
$ rails --version
Rails 6.0.3.1

**Ruby version**:
$ ruby --version 
ruby 2.6.6p146 (2020-03-31) [x86_64-linux]

**Comment by kayhide** [comment] 2020-05-20 14:02
I encountered this issue when I was setting up a proxy server with nginx.

The issue occurs with this configuration:
```nginx
    proxy_set_header  X-Forwarded-Port $server_port;
    proxy_set_header  X-Forwarded-Host $host;
```

Instead, this works:
```nginx
    proxy_set_header  X-Forwarded-Host "$host:$server_port";
```

**Comment by kayhide** [comment] 2020-05-20 14:11
I dug and found a suspicious piece of code here:

https://github.com/rails/rails/blob/c50170d213b225849ccda3244bd1f7ff1bb88fae/actionpack/lib/action_dispatch/http/url.rb#L221-L224

and `port` is picked from it as:
https://github.com/rails/rails/blob/c50170d213b225849ccda3244bd1f7ff1bb88fae/actionpack/lib/action_dispatch/http/url.rb#L260-L264

Rack version of the corresponding is as:
```ruby
      def port
        if authority = self.authority
          _, _, port = split_authority(self.authority)

          if port
            return port
          end
        end

        if forwarded_port = self.forwarded_port
          return forwarded_port.first
        end
```
https://github.com/rack/rack/blob/a5e80f01947954af76b14c1d1fdd8e79dd8337f3/lib/rack/request.rb#L308-L319

**Comment by jonathanhefner** [comment] 2020-05-20 23:39
This seems to be a duplicate of #26180.

I think the [solution you mentioned](https://github.com/rails/rails/issues/39366#issuecomment-631493330) is the correct approach. :+1:

**Comment by kayhide** [comment] 2020-05-21 02:08
@jonathanhefner Hi, thanks for your reply!
Yeah, you are right, this is a duplicate. I have not realized it.
Sorry for duplication.

But why is the #26180 closed?
We found a workaround but the issue itself is unsolved.

And I have a question.
Why are you implementing `port` or other similar methods by yourself other than relying on the `Rack::Request::Helpers` which is in ancestors of `request.class` (= `ActionDispatch::Request`).

I just tried to remove `ActionDispatch::Http::URL#port` and it worked for me.

**Comment by vipulnsward** [comment] 2020-06-06 20:10
The `X-Forwared-Port` is not a standard header, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers (I can't find from any RFC's or standard documentation) for this sort of forwarding.

Hence the documentation to pass the port via `X-Forwarded-Host` instead and making https://github.com/rails/rails/issues/26180#issuecomment-240154011 as the solution to address your issue.

This is available on `req.forwarded_port` though.

**Closed by vipulnsward** 2020-06-06 20:10 UTC
Labels: actionpack
