### ISSUE TITLE
rails 6 lib folder doesn't work

### ISSUE THREAD

**Issue by silva96** [rails/rails#37835] opened 2019-11-29 16:53 UTC
rails 6 lib folder doesn't work

to reproduce:

`rails new my_app`

add a file to: lib/my_lib.rb

```
# lib/my_lib.rb
class MyLib

  def self.hello
    puts 'Hello'
  end
end
```

`rails console`
```
MyLib.hello

NameError: uninitialized constant MyLib
from (pry):1:in `__pry__'

**Comment by fxn** [comment] 2019-11-29 17:05
The `lib` folder does not belong to the autoload paths by default, you need to

```ruby
require "my_lib"
```

before using `MyLib`.

**Comment by silva96** [comment] 2019-11-29 17:15
Can I add lib folder to autoload paths? is it a best practice with Zeitwerk, or discouraged?

**Comment by pixeltrix** [comment] 2019-12-01 08:25
> Can I add lib folder to autoload paths? is it a best practice with Zeitwerk, or discouraged?

A better option is to add an `app/lib` folder which will be auto-loaded and eager-loaded by default without any extra configuration.

**Comment by fxn** [comment] 2019-12-02 20:18
I think we can close this one.

The `lib` folder does not belong to the autoload paths [since Rails 3](https://github.com/rails/rails/blob/3-0-stable/railties/CHANGELOG). @pixeltrix's is the recommended modern idiom if you want to autoload.

Otherwise, `lib` belongs to `$LOAD_PATH` and you can `require` files in that directory.

**Closed by fxn** 2019-12-02 20:18 UTC

**Comment by chaffeqa** [comment] 2021-01-05 16:43
I'm looking for a DX solution for our team where:

* If `lib/**.rb` is modified, we would trigger `Rails.configuration.autoloaders.main.reload` (ref: https://github.com/fxn/zeitwerk#reloading) but *only* if in a situation that uses reloading (rails server non-eager load).

This makes sense since some of our lib code is middleware / base classes, and this is how we had the project set up prior to zeitwerk.

My problem is there is little documentation on how to hook into the rails 6 file watcher to enable that.  I'll try to dive in at some point, but if anyone else has any insight that would be great!

My idea:

```ruby
Rails.configuration.autoloaders.main.enable_reloading
# ...
if config.autoloaders.main.reloading_enabled?
  config.file_watcher.watch(Rails.root.join("lib/**.rb") do
    config.autoloaders.main.reload
  end
end
```

**Comment by fxn** [comment] 2021-01-05 16:55
Hey, nothing of that seems correct. You should not be reaching into the autoloader that way.

Could you please explain a bit more the situation? Do you realize middleware _cannot_ be reloadable because the middleware stack is not recomputed after reload?

**Comment by chaffeqa** [comment] 2021-01-09 15:06
Dang sorry, i thought GH would email me whenever a reply happens... guess that changed.

So the goal is purely DX: if you change something in the `lib` folder, effectively "restart" the rails server (like `reload!` does in rails console).

my hope was, instead of writing our own script to do so, use the already running autoloader to:
1. watch the `lib` folder for changes
2. when something changes in `lib`, "restart" the rails server (via reloading everything)

Like I said, purely DX, but still if its pretty simple I'd love to keep that feature around while still switching to zeitwerk

**Comment by fxn** [comment] 2021-01-09 21:11
The best practice to accomplish that nowadays is to move that code to `app/lib`. Only the Ruby code you want to autoload, tasks or other auxiliary files are OK in `lib`.

If you do that, there is nothing to configure, it works automatically, and your code base remains simple and standard.

Let clarify, since we are on it, that "reloading" does not "restart" the server, it only reloads application level code, what's below `app` to get the idea. The server stays up, initializers do not run again, the operating system process is the same, etc. Only application code is reloaded in memory.

**Comment by yagudaev** [comment] 2021-01-21 18:39
There are still legitimate cases where someone would want to use the `lib`. Mainly, it is code that is not specific to the application domain. Putting it in `app/lib` seems weird. There are a few concrete cases I use the lib folder for namely: reports, search, analytics, importing, exporting, integration to private apis without a gem.

Anything in the lib folder should be extractable to a separate gem and shared with the world.

In a rails 6+ application all you need to do is

```ruby
# config/application.rb

config.autoload_paths << config.root.join('lib')
```

Further reading:

* [How Zeitwork Autoloading Works](https://www.rubyguides.com/2019/08/autoloading-in-ruby/)
* [How Ruby's Native Autoload Method Works](https://medium.com/rubycademy/the-autoload-method-in-ruby-11fd079562ef)

**Comment by bobf** [comment] 2021-02-21 10:40
@yagudaev I agree that things in `lib/` should be extractable into a separate gem.

However I do not think it is correct that files in `lib/` should be auto-loaded, because a plain Ruby gem must `require` all of its files explicitly, which does not seem to be compatible with Rails auto-loading semantics.

I put "other" code that is app-specific into `app/lib` and assume it will be part of that Rails app permanently (and so I use ActiveSupport extensions etc. in that code). That code is auto-loaded (and reloaded) just fine.

For code that I plan to extract into a separate gem at some point, I put it in `lib/` and I add that to `$LOAD_PATH`:

```ruby
# config/application.rb

$LOAD_PATH.insert(0, File.expand_path(File.join(__dir__, '..', 'lib')))
```

This means I have to restart my Rails server every time I make changes to files in this directory, which is a pain (and your snippet above does not solve that issue - I just tested in a Rails 6 app). It may work if I remove the `require` statements but then the gem will not work standalone.

If there is a way to auto-reload code in `lib/` while being both Rails-compliant and gem-compliant then that would be very useful. Until then I just suck it up and restart my server every time I make a change.

**Comment by fxn** [comment] 2021-02-21 11:37
Just in case, let me add that `lib` is added to `$LOAD_PATH` by Rails automatically.

```ruby
Bundler.require(*Rails.groups)

# lib not in $LOAD_PATH yet here.

module MyApp
  class Application < Rails::Application
    # Now, it is.
    ...
  end
end
```

In my view, conceptually there is no probem in making files within `lib` autoloadable and reloadable. There are dozens of gems that use Zeitwerk to load their code (their own instance).

You only need to be careful, because if you have

```
lib/tasks
```

and you put `lib` in as autoload path, you are saying that `lib/tasks` defines the namespace `Tasks`. So, you can do that, but you need to be careful. And that was the main reason `lib` was removed from the default autoload paths, because it has a mix of things.

You can still have `lib/code`, or tell Zeitwerk to ignore `lib/tasks`, but recently people have switched to lib tasks in `lib/tasks`, and actual Ruby code in `app/lib`.

However, you can pick and choose whatever combination feels better to you, technically a few are possible.

**Comment by JoshCheek** [comment] 2021-04-14 22:49
Hi. Been  reading https://guides.rubyonrails.org/autoloading_and_reloading_constants.html and the zeitwerk readme and some source and tried out maybe 8 different ideas, from `Zeitwerk::Loader.for_gem` to `Rails.autoloaders.main.push_dirs` to manually adding entries to `Rails.autoloaders.main.autoloads`, and I'm still really at a loss.

I have a file `lib/my_app/my_file.rb`, which defines `MyApp::MyFile`. How do I get it to autoload that one file? I honestly tried a lot of things, but it's difficult to explain all the issues (I can try harder if it's really necessary).

The hard part about "use `app/lib`" is that it implies I won't be namespacing my constants, or that if I do, it'll be using the Rails pattern of appending the namespace to the end (`SmthController`, `SmthMailer`, `SmthPresenter`), so do I rename it to `app/lib/my_file_lib.rb` and call the constant `MyFileLib`? 😐 I mean... I guess I can do, but it's a hard pill to swallow. It feels like my PORO should be able to do its own thing and not need to adhere to Rails conventions, even if I do stick it into `app/lib`.

Another alternative that would feel a lot better would be `app/my_app` in the same way I do `lib/my_app`, and then `app/my_app/my_file.rb` would define `MyApp::MyFile`, like normal. That would be fine, preferable, even. But how do I tell Zeitwerk that? It seems to want me to give it a directory that maps to `Object`, or to have a constant already defined which I can pass in place of `Object`

**Comment by yagudaev** [comment] 2021-04-15 03:35
@JoshCheek are you trying to have a few apps inside of a rails project? What you are describing reminds me of Django which has many apps as it came from publishing so they had many domains/brands.

In rails, this is accomplished with Rails Engines: https://guides.rubyonrails.org/engines.html.

> The hard part about "use app/lib" is that it implies I won't be namespacing my constants, or that if I do, it'll be using the Rails pattern of appending the namespace to the end (SmthController, SmthMailer, SmthPresenter),

There are a few component types like Models that don't follow that naming convention. Some gems like graphql, activeadmin also take liberty with it. In this case, omitting it would make sense.

Otherwise the trick I mentioned should work well here it is:

```
# config/application.rb

config.autoload_paths << config.root.join('lib')
```

I'm using it here for a live project: https://github.com/yagudaev/search_on_rails_demo/blob/main/lib/search/in_memory.rb#L2 and https://github.com/yagudaev/search_on_rails_demo/blob/main/config/application.rb#L36. It's a reference implementation of search for a course and new gem I'm working on.

**Comment by JoshCheek** [comment] 2021-04-15 17:48
Thank you, @yagudaev, the autoload paths worked for me. I think that was my initial thought, I'm not sure why I got turned around about it. Maybe b/c most of the comments in this thread are saying to not do that, or maybe b/c I was thinking I want it to be reloaded, not autoloaded. Not sure, but adding `config.autoload_paths << config.root.join('lib')` is working thus far.

**Comment by jeromedalbert** [comment] 2021-11-24 02:33
I have worked on apps that put code closely related to the application in `app/`, and code less closely related to the application (i.e. that could be extracted to a gem in the future) in `lib/`. Having the two folders separated (and not one included in another) makes sense according to this point of view.

So I wanted the app I was working on to work with `lib/`, but I was getting the following error:

```
No such file to load -- le_importer/omega.rb (LoadError)
```

The issue was caused by the last two lines in my `config/application.rb`:

```ruby
    config.autoload_paths   << Rails.root.join('lib')
    config.eager_load_paths << Rails.root.join('lib')
    config.autoload_paths   << Rails.root.join('lib/**/*')
    config.eager_load_paths << Rails.root.join('lib/**/*')
```

Removing those lines to only keep the base paths worked great:

```ruby
    config.autoload_paths   << Rails.root.join('lib')
    config.eager_load_paths << Rails.root.join('lib')
```

Thanks to @yagudaev for pointing to the right resources.

**Comment by fxn** [comment] 2021-11-24 10:35
@jeromedalbert that's right.

Please note that you should also ignore subdirectories that are not meant to be namespaces. For example:

```ruby
Rails.autoloaders.main.ignore('lib/tasks', 'lib/assets')
```

Otherwise, Zeitwerk would define `Tasks` constant, but that is not your intention (and could potentially conflict with a genuine `Tasks` constant).
