### ISSUE TITLE
NoMethodError - undefined method `clear' for nil:NilClass - ConnectionHandler#establish_connection - after upgrading to rails 5.2.0

### ISSUE THREAD

**Issue by cliffcrosland** [rails/rails#33022] opened 2018-05-30 15:59 UTC
### Steps to reproduce
Difficult to reproduce, but it occurs in our production environment about once in every 10,000 Resque child process forks. Possibly caused by a race condition between `#discard!` and `#disconnect!` in `ActiveRecord::ConnectionAdapters::ConnectionPool`.

### Expected behavior
We have a few abstract models that inherit from ApplicationRecord and connect to different Postgres databases. We use the common pattern where where we call `#disconnect!` on each of the connection pools of these abstract models in a `Resque.before_fork` hook, and we run `#establish_connection` on each of these abstract models in a `Resque.after_fork` hook. 

It looks like this pattern is no longer necessary thanks to https://github.com/rails/rails/pull/31173. However, it sounds like we want this pattern to remain safe to use since it is widely adopted.

Expected behavior is that no error should be raised.

### Actual behavior
This error happens rarely. Possibly caused by a race condition between `#discard!` and `#disconnect!` in `ConnectionPool`.

The `@available.clear` method call fails because `@available` is nil at lib/active_record/connection_adapters/abstract/connection_pool.rb:759

Backtrace:

```
NoMethodError - undefined method `clear' for nil:NilClass
.../activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `block in with_new_connections_blocked'
.../activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:755:in `ensure in with_new_connections_blocked'
.../activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:772:in `with_new_connections_blocked'
.../activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:674:in `with_exclusively_acquired_all_connections'
.../activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `disconnect'
.../activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:453:in `disconnect!'
.../activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1025:in `remove_connection'
.../activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:952:in `establish_connection'
.../activerecord-5.2.0/lib/active_record/connection_handling.rb:60:in `establish_connection'
```

### System configuration
**Rails version**: 5.2.0
**Ruby version**: 2.5.1

**Comment by rafaelfranca** [comment] 2018-05-30 19:15
What is calling `disconnect!` is your application right? Looks like you are calling it after the pool was already discarded and as documented the state of the pool after that is undefined.

You don't need to call `disconnect!` anymore before the fork. Rails will take case of it for you.

**Comment by eugeneius** [comment] 2018-05-30 20:16
In the backtrace provided above, `disconnect!` is being called from `remove_connection` via `establish_connection` - the error seems to be happening in the child process, not the parent.

"about once in every 10,000 Resque child process forks" is the right order of magnitude for the problem to be a collision due to PID recycling. I think `discard_unowned_pools` should probably be removing the ancestor pools from the hash when it discards them.

@cliffcrosland how are you running your Reque workers? Do you use anything like [resque-pool](https://github.com/nevans/resque-pool)?

**Comment by cliffcrosland** [comment] 2018-06-02 16:29
Thank you for the pid collision insight, @eugeneius. I was able to reproduce the problem locally. This error occurs when there is a collision between a grandparent pid and a child pid. 

### Test to reliably reproduce

I was able to reliably reproduce the error by adding the following test to rails/activerecord/test/cases/connection_adapters/connection_handler_test.rb at line 266.
```Ruby
def test_handles_collision_with_grandparent_pid
  grandparent_pid = Process.pid
  ActiveRecord::Base.establish_connection(:arunit)

  # parent process
  fork do
    ActiveRecord::Base.establish_connection(:arunit)

    # force child process pid collision with grandparent pid
    Process.stub(:pid, grandparent_pid) do
      fork do
        assert_equal grandparent_pid, Process.pid
        ActiveRecord::Base.establish_connection(:arunit)
        exit
      end
    end
    exit
  end
end
```

### Test output
```
Finished in 0.014596s, 68.5129 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
Traceback (most recent call last):
37: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
36: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:136:in `run'
35: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run'
34: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
33: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
32: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
31: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
30: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
29: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run'
28: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:320:in `each'
27: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run'
26: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method'
25: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:960:in `run_one_method'
24: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:93:in `run'
23: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:211:in `with_info_handler'
22: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
21: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:94:in `block in run'
20: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest.rb:265:in `time_it'
19: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
18: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:195:in `capture_exceptions'
17: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
16: from test/cases/connection_adapters/connection_handler_test.rb:271:in `test_handles_collision_with_grandparent_pid'
15: from test/cases/connection_adapters/connection_handler_test.rb:271:in `fork'
14: from test/cases/connection_adapters/connection_handler_test.rb:275:in `block in test_handles_collision_with_grandparent_pid'
13: from /home/vagrant/.gem/ruby/2.5.1/gems/minitest-5.11.3/lib/minitest/mock.rb:234:in `stub'
12: from test/cases/connection_adapters/connection_handler_test.rb:276:in `block (2 levels) in test_handles_collision_with_grandparent_pid'
11: from test/cases/connection_adapters/connection_handler_test.rb:276:in `fork'
10: from test/cases/connection_adapters/connection_handler_test.rb:278:in `block (3 levels) in test_handles_collision_with_grandparent_pid'
 9: from /home/vagrant/cliff/rails/activerecord/lib/active_record/connection_handling.rb:64:in `establish_connection'
 8: from /home/vagrant/cliff/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:952:in `establish_connection'
 7: from /home/vagrant/cliff/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:1025:in `remove_connection'
 6: from /home/vagrant/cliff/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:453:in `disconnect!'
 5: from /home/vagrant/cliff/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `disconnect'
 4: from /home/vagrant/cliff/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:674:in `with_exclusively_acquired_all_connections'
 3: from /home/vagrant/cliff/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:772:in `with_new_connections_blocked'
 2: from /home/vagrant/cliff/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:755:in `ensure in with_new_connections_blocked'
 1: from /opt/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/vagrant/cliff/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `block in with_new_connections_blocked': undefined method `clear' for nil:NilClass (NoMethodError)
```

### Description of our Resque system

We use [mojombo/god](https://github.com/mojombo/god) to monitor and launch processes to run Resque jobs. I believe that the following chain of events leads to the error:
- A short-lived "grandparent" process and launches the "parent" Resque worker process, which is long-lived. 
- When Resque jobs arrive, the "parent" Resque worker process forks short-lived "child" processes. 
- Since the "grandparent" is short-lived, it is possible for a child's pid to collide with its grandparent's pid. 
- When a collision occurs and `#establish_connection` is called in the "child" process, the code fetches the discarded connection from `@owner_to_pool` in `ConnectionHandler` that once belonged to its "grandparent" because they share the same pid.
- When the discarded connection is used, its instance variables are all nil, including `@available`, leading to the error.

**Comment by cliffcrosland** [comment] 2018-06-05 00:52
Opened a PR https://github.com/rails/rails/pull/33057

Since using connection pools after they have been discarded leads to undefined behavior, it seems safe to delete them from the pid_map once they've been discarded.

**Comment by eileencodes** [comment] 2023-04-04 15:40
Stumbled upon this and I don't think this is a bug anymore. The reproduction test doesn't fail on main and the changes to connection management since 2018 have been extensive. We no longer call `remove_connection` on `establish_connection` if the configuration is the same and the pid handling is different as well. I'm going to close it, if it's still an issue please open a new issue using one of our [bug report templates](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb).

**Closed by eileencodes** 2023-04-04 15:40 UTC
Labels: attached PR
