### ISSUE TITLE
Rails ActiveRecord::RecordInvalid exception not raised in after_create of association

### ISSUE THREAD

**Issue by mountriv99** [rails/rails#24301] opened 2016-03-24 15:22 UTC
### Steps to reproduce

I have 3 simple tables that are built with the following lines:

```
rails g model receipt
rails g model receipt_item receipt:references
rails g model transaction transacted_at:datetime
```

and the models look like this:

```
class Receipt < ActiveRecord::Base
  has_many :receipt_items
end

class ReceiptItem < ActiveRecord::Base
  after_create :create_transaction
  belongs_to :receipt
private
  def create_transaction
    Transaction.new.save!
  end
end

class Transaction < ActiveRecord::Base
  validates :transacted_at, :presence => true
end
```
### Expected behaviour

So every time a new ReceiptItem is created, it triggers the after_create callback to create a new Transaction object using save!. But because Transaction requires that the column transacted_at to be present, Transaction.new.save! should raise an ActiveRecord::RecordInvalid every time, I assumed.
### Actual behaviour

So then I created 3 tests:

```
test "creating an invalid transaction" do
    assert_raises ActiveRecord::RecordInvalid do
        Transaction.new.save!
    end
end

test "creating invalid transaction in after_create" do
    assert_raises ActiveRecord::RecordInvalid do
        ReceiptItem.new.save!
    end
end

test "creating invalid transaction in after_create of associated model" do
    assert_raises ActiveRecord::RecordInvalid do
        r = Receipt.new
        i = r.receipt_items.new
        r.save!
    end
end
```

The first two tests passed as expected. The third test, however, failed because the exception was never raised. As a matter of fact, if I add the following lines after the 'r.save!' line:

```
r.reload
p r
p r.receipt_items
```

I could see that the Receipt and the ReceiptItem have been created successfully.

```
#<Receipt id: 980190963, created_at: "2016-03-24 14:39:43", updated_at: "2016-03-24 14:39:43">
#<ActiveRecord::Associations::CollectionProxy [#<ReceiptItem id: 980190964, receipt_id: 980190963, created_at: "2016-03-24 14:39:43", updated_at: "2016-03-24 14:39:43">]>
```

Furthermore, if I replaced

`assert_raises ActiveRecord::RecordInvalid do`
with
`assert_difference "Transaction.count", +1 do`

The test also failed and I confirmed that the Receipt and the ReceiptItems were created but the Transaction wasn't. That means the creation of the Transaction failed, but was silently ignored, even though I used 'save!' as opposed to just 'save'.

Is this the intended behaviour, or is this a bug?
### System configuration

**Rails version**: Tried this in Rails 4.0.13 and 4.2.0

**Ruby version**: 2.1.2p95 and  2.0.0p353

**Comment by maclover7** [comment] 2016-03-24 23:03
Hmm, seems like errors aren't being passed upstream. Can you see if this is reproducible on Rails master?

**Comment by mountriv99** [comment] 2016-03-25 04:08
yes, same thing happens on master

**Comment by twonegatives** [comment] 2016-03-25 06:17
note that there was a related issue some time ago:
https://github.com/rails/rails/issues/17282

**Comment by vipulnsward** [comment] 2016-03-25 06:29
Script to reproduce - https://gist.github.com/vipulnsward/0b7224ffc66ff7d72980

**Comment by vipulnsward** [comment] 2016-03-25 13:12
So Receipt's `save!` calls ReceiptItems `save` to save the belongs_to associations.
The `Transaction.new.save!` has no effect, due to this behaviour, as we don't raise from ReceiptItem's `save` method.

**Comment by mountriv99** [comment] 2016-03-26 05:39
@vipulnsward Understood. Is this the intended behaviour?

**Comment by vipulnsward** [comment] 2016-03-26 05:57
I think so, I don't see a different documented behaviour cc @rafaelfranca ?

**Comment by mechanicles** [comment] 2016-03-26 07:18
It's the intended behaviour. Because there are two `save` methods which are happening in one request and those `save` methods will have their own transaction (ActiveRecord::Transactions), one for `receipt` object and another for `transaction` object.

If you want, you will get the `ActiveRecord::RecordInvalid ` error on the `transaction` object if that `transaction` belongs to any of these objects `receipt` or `receipt_item`. 

Something like this,

```Ruby
class ReceiptItem < ActiveRecord::Base
  belongs_to :receipt
  has_one :item_transaction, class_name: 'Transaction'

  accepts_nested_attributes_for :item_transaction
end

class Transaction < ActiveRecord::Base
  belongs_to :receipt_item
  validates :transacted_at, :presence => true
end

receipt = Receipt.new
receipt_item = receipt.receipt_items.new
receipt_item.build_item_transaction
receipt.save! # => ERROR ActiveRecord::RecordInvalid
```

**Comment by twonegatives** [comment] 2016-03-26 07:53
could we get a RoR member comment on this, please?
note that even though `receipt_item` is wrapped in a silent `save` call, it gets saved regardless of an exception raised in its `after_save` block.[Halting execution](http://guides.rubyonrails.org/active_record_callbacks.html#halting-execution) section of guide mentiones that exceptions raised inside of `after_save` should rollback (at least) `receipt_item` saving transaction.

**Comment by vipulnsward** [comment] 2016-03-26 08:17
True.

**Comment by skiningham** [comment] 2017-08-31 14:14
Has a conclusion been reached as to whether or not this is intended behavior? The behavior in the reproduction is still present today.

**Comment by abaldwin88** [comment] 2023-06-25 18:05
Recommend closing this issue

* Running the reproduction script against main shows the behavior now matches the expectation of the OP
* This new behavior seems ideal to me... Principle of least surprise
* Performing `git bisect` with the reproduction script shows the change happened in #36210

**Comment by vipulnsward** [comment] 2023-06-25 18:58
Closing, the reproduction script passes against main branch now.

**Closed by vipulnsward** 2023-06-25 18:58 UTC
Labels: activerecord, With reproduction steps
