### ISSUE TITLE
accepts_nested_attributes_for breaks automatic inverse_of for has_many

### ISSUE THREAD

**Issue by dontfidget** [rails/rails#18672] opened 2015-01-24 18:41 UTC
Adding accepts_nested_attributes_for seems to break the automatic setting of inverse_of.  I have a self-contained gist for this at https://gist.github.com/dontfidget/c336923ee94609528095.

```

class Post < ActiveRecord::Base
  has_many :comments
  accepts_nested_attributes_for :comments # removing this line makes the test pass
end
 
class Comment < ActiveRecord::Base
  belongs_to :post
end
 
class BugTest < Minitest::Test
  def test_inverse_of
    post = Post.new
    post.comments << Comment.new
 
    assert_equal post.comments.first.post, post
  end
end
```

Removing `accepts_nested_attributes_for` will make it pass.  Also, adding explicit inverse_of will make it pass.  Using create instead of new will also make it pass.

**Comment by dontfidget** [comment] 2015-01-24 20:15
Apparently this is because `accepts_nested_attributes_for` does an explicit set of `autosave: true`.  I don't really see us making this work, but maybe it could be documented.

**Comment by aalvarado** [comment] 2015-01-26 10:46
Your gist was giving me the following error:

```
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activesupport/lib/active_support/core_ext/class/attribute.rb:89:in `block (2 levels) in class_attribute': undefined method `singleton_class?' for ActiveSupport::Callbacks::CallbackChain:Class (NoMethodError)
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activesupport/lib/active_support/callbacks.rb:523:in `<class:CallbackChain>'
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activesupport/lib/active_support/callbacks.rb:514:in `<module:Callbacks>'
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activesupport/lib/active_support/callbacks.rb:59:in `<module:ActiveSupport>'
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activesupport/lib/active_support/callbacks.rb:10:in `<top (required)>'
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:71:in `<class:AbstractAdapter>'
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:66:in `<module:ConnectionAdapters>'
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:14:in `<module:ActiveRecord>'
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:13:in `<top (required)>'
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activerecord/lib/active_record.rb:129:in `<module:ActiveRecord>'
	from /home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/rails-c414fc60ac66/activerecord/lib/active_record.rb:32:in `<top (required)>'
	from x.rb:15:in `require'
	from x.rb:15:in `<main>'
```

If I change the Gemfile to use latest stable Rails:

```
    gem 'rails', '4.2.0'
```

I get the same results as you.
```
-- create_table(:posts, {:force=>true})
D, [2015-01-26T01:42:13.272635 #6482] DEBUG -- :    (0.2ms)  CREATE TABLE "posts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL) 
   -> 0.0029s
-- create_table(:comments, {:force=>true})
D, [2015-01-26T01:42:13.273161 #6482] DEBUG -- :    (0.1ms)  CREATE TABLE "comments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "post_id" integer) 
   -> 0.0004s
Run options: --seed 1000

# Running:

F

Finished in 0.011038s, 90.5939 runs/s, 90.5939 assertions/s.

  1) Failure:
BugTest#test_inverse_of [x.rb:46]:
Expected: nil
  Actual: #<Post id: nil>
```

**Comment by sgrif** [comment] 2015-01-28 17:11
This appears to have been by design, and has always been true. However, none of the commits which introduced the code responsible give context as to why this is the case. I'll dig further.

**Comment by aalvarado** [comment] 2015-01-28 18:34
Adding, `inverse_of` seems to solve the issue, I ran into the same problem trying to validate presence of an association with nested attributes on new records.

https://gist.github.com/aalvarado/93562e11243c24dbdb4d#file-inverse_of_test-rb-L33

**Comment by sgrif** [comment] 2015-01-28 19:00
@aalvarado The issue is automatic inverse of, not when manually set.

**Comment by sgrif** [comment] 2015-01-28 20:10
I've spent a good bit of time digging into this. The issue is that when `inverse_of` and `autosave` are both set, it is quite possible for models to get saved twice. This is why `accepts_nested_attributes` was intentionally set to turn off automatic inverse of.

The root cause of the double saving issue is how dirty tracking works. Specifically, the fact that we clear the dirty flags after all save related callbacks have run, which means that the record is still dirty. So the flow looks like this:

- parent record is dirty
- parent record saves
- parent record runs callbacks
- parent's autosave associations look for loaded associations which need autosaving
  - whether a record should be autosaved is defined as it being a new record, it being dirty, or it having any loaded associations which need autosaving
- since the parent is still dirty at this point, the child decides that the parent should be autosaved
- parent record saves
- parent record runs callbacks
- parent's autosave associations look for loaded associations which need autosaving
  - a recursive block prevents the child from autosaving its associations a second time
- the parent is marked as non-dirty

So the best fix here would be to not have a record marked as dirty in the callbacks. (Which makes sense, you shouldn't be dirty *after save*). First off, this would be a major breaking change, and we would need to have a discussion about whether its worth it. However, right now the changes required to make that happen seem to be infeasible. I'll continue refactoring towards making it possible, but right now it just isn't.

**Closed by sgrif** 2015-01-28 20:10 UTC
Labels: activerecord
