### ISSUE TITLE
ActiveRecord `dependent: :destroy` requires `id` on the associated object, raises NoMethodError: undefined method `to_sym' for nil:NilClass

### ISSUE THREAD

**Issue by spencerroan** [rails/rails#31022] opened 2017-10-31 22:21 UTC
### Steps to reproduce
```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update
     your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: "sqlite3",
  database: ":memory:"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:doctors) {}

  create_table :appointments, id: false do |t|
    t.integer :doctor_id, null: false
  end
  create_table :tools, id: false do |t|
    t.integer :doctor_id, null: false
  end
end

class Doctor < ActiveRecord::Base
  has_many :appointments, dependent: :destroy
  has_many :tools, dependent: :delete_all
end

class Appointment < ActiveRecord::Base
end

class Tool < ActiveRecord::Base
end

class BugTest < Minitest::Test
  # dependent: destroy requires the association to have :id
  def test_destroy
    d = Doctor.create
    d.appointments << Appointment.new()
    assert d.destroy
  end

  # workaround 1: use delete_all and skip yer callbacks
  def test_delete_all
    d = Doctor.create
    d.tools << Tool.new()
    assert d.destroy
  end
  # workaround 2: give the association an id.
end
```
### Expected behavior
The resource should be destroyed without raising an error.

### Actual behavior
NoMethodError: undefined method `to_sym' for nil:NilClass

### System configuration
**Rails version**:
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
**Ruby version**:
Rails 5.0.6

**Comment by kennyx46** [comment] 2017-11-03 15:58
Seems this is a duplicate of [#25437](https://github.com/rails/rails/issues/25347) issue.
Please view the comments.

Briefly: when you use `dependent: :destroy` each dependent model is going to be instantiated, and rails can't operate them if they do not have the primary key, that is why it fails. In case of `dependent: :delete_all` rails are not going to initialize any dependent models so everything works fine. 
It is expected behavior for associations. You should either add primary key (`id` or another field) or use `dependent: :delete_all`

**Comment by al2o3cr** [comment] 2017-11-03 17:17
+1 to @kennyx46 - `dependent: :destroy` is going to try to remove records by loading them and then calling `destroy` on each one. 

That process - like most ActiveRecord processes - expects models to have a primary key (either `id` or something else, set by doing `self.primary_key = ...` in the model). I suspect you'd get the exact same `to_sym` error with code like this:
```ruby
  tool = Tool.create
  tool.destroy
```

**Comment by kamipo** [comment] 2017-11-04 07:16
It is expected behavior. See https://github.com/rails/rails/issues/25347#issuecomment-300067025

**Closed by kamipo** 2017-11-04 07:16 UTC

**Comment by spencerroan** [comment] 2017-11-07 19:44
Thank you for the update.

**Comment by bonafernando** [comment] 2018-01-25 17:56
I had the same issue. Used to have a table like this:

```
CREATE TABLE user_country (
  id_user INTEGER(12) NOT NULL,
  id_country VARCHAR(15) NOT NULL,
  PRIMARY KEY (id_user,id_country),
  FOREIGN KEY (id_user) REFERENCES user(id),
  FOREIGN KEY (id_country) REFERENCES country(id)
);
```
With it, Active Record was always sending me warnings:

> WARNING: Active Record does not support composite primary key.

And fixed creating a primary key for it:

```
CREATE TABLE user_country (
  id INTEGER(12) NOT NULL AUTO_INCREMENT,
  id_user INTEGER(12) NOT NULL,
  id_country VARCHAR(15) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_user) REFERENCES user(id),
  FOREIGN KEY (id_country) REFERENCES country(id)
);
```

Not my favorite solution, but fixed...
