### ISSUE TITLE
Can't roll back `add_check_constraint` with comment

### ISSUE THREAD

**Issue by jscheid** [rails/rails#52419] opened 2024-07-25 21:24 UTC
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # Also fails with edge rails
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3", "~> 1.4"

  # Note: this seems to be necessary with bundler 2.5.16, not sure why
  gem "timeout", "~> 0.4.1"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :payments, force: true
end

class Payment < ActiveRecord::Base
end

class AddCheckConstraintWithComment < ActiveRecord::Migration::Current
  def change
    add_check_constraint :payments, 'TRUE', comment: 'foo'
  end
end

class BugTest < Minitest::Test
  def test_migration_up
    AddCheckConstraintWithComment.migrate(:up)
    Payment.reset_column_information
  end

  def test_migration_down
    AddCheckConstraintWithComment.migrate(:down)
    Payment.reset_column_information
  end
end

```

### Expected behavior

Should be able to roll back a migration that uses `add_check_constraint` with a comment.

### Actual behavior

Can't roll back a migration that uses `add_check_constraint` with a comment.

### System configuration
**Rails version**: test case fails with latest and edge

**Ruby version**: tested with 3.2.3

**Comment by fatkodima** [comment] 2024-07-25 22:15
`add_check_constraint ` does not accept a `:comment` option when adding a check constraint in sqlite.

**Comment by jscheid** [comment] 2024-07-26 05:55
Sorry, it is a problem with `postgresql` and that's where I observed it originally. I thought I can simplify the test case by using sqlite when I could still repro with it. Would you like me to change the test case to use postgres?

That said, I feel that even for sqlite the `comment` option should either raise an error (along the lines of "unsupported argument") or it should be completely ignored. Ignoring it silently during migration, but then having its presence preventing rollback, seems like a footgun.

**Comment by fatkodima** [comment] 2024-07-26 08:48
`add_check_constraint` does not accept a `:comment` option when adding a check constraint, no matter the database.

I want to hear @rafaelfranca's opinion on this.

**Comment by aidanharan** [comment] 2024-09-13 08:46
The issue is that if you include an invalid option that does not exist for `add_check_constraint` then the migration works in the `up` direction but then fails in the `down` direction. 

```ruby
class AddCheckConstraintWithInvalidOption < ActiveRecord::Migration::Current
  def change
    add_check_constraint :payments, 'true', **invalid_option: 'foo'**
  end
end
```

It should either:

1. Fail in both the `up` and `down` direction. This would be a breaking change for existing `add_check_constraint ` migrations that are using invalid options.
2. Complete successfully in both the `up` and `down` directions. The fix for this option is in https://github.com/rails/rails/pull/52903

**Closed** 2024-12-02 05:29 UTC
Labels: activerecord, attached PR, With reproduction steps
