### ISSUE TITLE
ActiveRecord::Relation#cache_key throws error for some distinct collections.

### ISSUE THREAD

**Issue by martijnbleeker** [rails/rails#29779] opened 2017-07-13 14:24 UTC
When retrieving the `cache_key` of a distinct, ordered `ActiveRecord::Relation`, 
a `PG::InvalidColumnReference` error is thrown

```
ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  
  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...STINCT "posts"."updated_at" FROM "posts" ORDER BY "posts"."n...
                                                             ^
: SELECT COUNT(*) AS "size", MAX(subquery_for_cache_key.updated_at) AS timestamp 
  FROM (SELECT  DISTINCT "posts"."updated_at" FROM "posts" 
  ORDER BY "posts"."name" ASC LIMIT $1) subquery_for_cache_key
    test.rb:41:in `test_association_stuff'
```

Once the relation is loaded, the cache_key is returned as expected.
While it works to avoid the bug, it is less efficient.

This is an example query which produces the issue:

``` ruby
Post.limit(10).order(:name).distinct.cache_key
```

### Steps to reproduce
Run the [test template](https://gist.github.com/martijnbleeker/c4682654ff9adca3e0481ae5b9d87680). 
It tries to use a postgres database named `test` by default.

### Expected behavior
The cache key is returned

### Actual behavior
A `PG::InvalidColumnReference` error is thrown

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 4.2.1

**Comment by duffyjp** [comment] 2017-07-14 18:27
You're not selecting any columns for Postgres to use with [SELECT DISTINCT](http://www.postgresqltutorial.com/postgresql-select-distinct/)

Mysql lets you get away with that, but not postgres.

**Comment by martijnbleeker** [comment] 2017-07-17 06:32
Sounds reasonable, however when executing this line:

``` ruby
Post.select(:name).limit(10).order(:name).distinct.cache_key
```

The same error occurs, because the select value gets ignored by `CollectionCacheKey`.

Also,

``` ruby
Post.limit(10).order(:name).distinct.load.cache_key
```

works just fine.

**Comment by meinac** [comment] 2017-07-17 10:28
Here the problem is implementation of `cache_key`. The query we are sending to database engine to fetch components(size and max of updated_at) for cache key is problematic for PostgreSQL. The query should use 'DISTINCT ON' instead 'DISTINCT'. I'll try to make it working.

**Comment by martijnbleeker** [comment] 2017-07-17 10:39
I tried to think of a fix as well, not yet implemented since I wasn't sure if this was an issue in rails or an issue with the query we were using.

Since the error is caused by the statement in the `order` call, I was wondering if the solution could be to append the `order.expr.name` value to `select_values` in `collection_cache_key` . Or are there other AR calls that could trigger the same error?

**Comment by meinac** [comment] 2017-07-17 10:48
the problem is PostgreSQL expects you to select the order value so if you send a query like this:
```sql
select distinct updated_at from posts order by name
```
the query will fail because you try to order the result set by a value which is not selected. But if you send a query like:
```sql
select distinct updated_at, name from posts order by name
```
it should work but this checks the distinction by two values and this is not the thing you want.

There is another way to select distinct entries from PostgreSQL which is `distinct on` so if you send a query like this:
```sql
select distinct on (updated_at) updated_at, name from posts order by name
```
this should work perfectly.

So if you take a look at the cache_key query: 
```sql
SELECT COUNT(*) AS "size", MAX(subquery_for_cache_key.updated_at) AS timestamp FROM (SELECT  DISTINCT "posts"."updated_at" FROM "posts" ORDER BY "posts"."name" ASC) subquery_for_cache_key
```
this is wrong because it tries to select only updated_at but ordered by name. This is because of the `order` call in your query means this is a bug in rails.

**Comment by martijnbleeker** [comment] 2017-07-19 07:47
@meinac The test passes on your branch. Code is looking good too!

**Comment by meinac** [comment] 2017-07-19 11:03
There are more cases we need to cover for PostgreSQL like if the query has `group by` literal then the query for cache key will be invalid because the updated_at should be in group by or used with an aggregate function.

**Comment by hopsoft** [comment] 2017-08-04 05:19
It should also handle the use case of selecting a virtual column & then ordering on that attribute with pagination. 

For example, 

```ruby
User.select("*")
  .select("first_name || last_name as full_name")
  .order("full_name desc")
  .limit(10)
  .offset(2)
  .cache_key

# ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "full_name" does not exist
```

I monkey patched `ActiveRecord::CollectionCacheKey` for my current project to handle this scenario.

https://gist.github.com/hopsoft/f25b804b6adf46910e99a5167adb1a94

**Closed** 2017-12-30 09:54 UTC
Labels: activerecord
