### ISSUE TITLE
new_framework_defaults_7_1.rb are not working as expected

### ISSUE THREAD

**Issue by fatkodima** [rails/rails#46567] opened 2022-11-24 15:01 UTC
### Steps to reproduce
1. Create a new (< 7.1) rails app
2. Use `config.load_defaults 7.0` in `application.rb`
3. Add https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_7_1.rb.tt to initializers and uncomment commented lines

### Expected behavior
For example, in console
```
ActiveRecord.allow_deprecated_singular_associations_name # => false
```

### Actual behavior
```
ActiveRecord.allow_deprecated_singular_associations_name # => true
```

Even though there is a test case for this - https://github.com/rails/rails/blob/cef42e692e1c9ac52299e8d5443d173d89abeec7/railties/test/application/configuration_test.rb#L2497-L2507

The same situation applies for many of the configs in the `new_framework_defaults_7_1.rb.tt` file. 
Am I doing something wrong?

### System configuration
**Rails version**: `main`

**Comment by rafaelfranca** [comment] 2022-11-24 18:26
This usually happen because something in the application is loading `ActiveRecord::Base` too early. Did you observe this behavior really in a new generated application or did you added any gem after it?

**Comment by fatkodima** [comment] 2022-11-24 20:59
>  Did you observe this behavior really in a new generated application

Rechecked within a completely new app - works as expected.

I originally checked within the existing app. I was able to identify 2 gems that load `ActiveRecord::Base` too early. Without them - also works as expected.

I am wondering if reassigning a local variable `configs` here - https://github.com/rails/rails/blob/324880c393a82c5212f2402def66af1c14d6b02a/activerecord/lib/active_record/railtie.rb#L245, which is used then here - https://github.com/rails/rails/blob/324880c393a82c5212f2402def66af1c14d6b02a/activerecord/lib/active_record/railtie.rb#L234 when `ActiveRecord::Base` is loaded earlier, is intentional? Because without that mutation everything works as expected with that 2 gems.

**Comment by mrhead** [comment] 2022-11-25 12:42
Unfortunately, this is a common issue caused by different gems. Another example: https://github.com/rollbar/rollbar-gem/issues/906

I wish Rails would automatically identify issues like this, but I'm unsure how to implement it.

**Comment by ghiculescu** [comment] 2022-11-25 23:40
> I wish Rails would automatically identify issues like this, but I'm unsure how to implement it.

There's a few ideas floating around. I think my favourite is https://github.com/rails/rails/pull/45297

@fatkodima are you able to share which gems had issues? Ideally they get patched.

**Comment by fatkodima** [comment] 2022-11-25 23:45
One is https://github.com/ledermann/unread, another one is mine - https://github.com/fatkodima/data_checks 😄 

> Actually that reminds me of https://github.com/rails/rails/pull/46278 - another one caused by a third party issue.

Ah, yes, haven't seen that. Had exactly the same idea.

**Comment by ghiculescu** [comment] 2022-11-25 23:52
I think [this](https://github.com/paper-trail-gem/paper_trail/blob/91732d03ea7518444f1dc7414291b2641733e381/lib/paper_trail/frameworks/rails/railtie.rb#L26) is probably what you want the architecture to look like in your gem. But I agree that it would be better if Rails could handle this in more cases.

**Comment by fatkodima** [comment] 2022-11-25 23:56
Yes, thanks for looking into this. I will definitely fix my gem and probably send a PR into `unread` (if no one will outpace me).
I defer loading of Active Record in my other gem with a similar technique you mentioned 👍.

**Comment by fatkodima** [comment] 2022-11-26 21:54
Opened a PR in `unread` and released a new version of `data_checks` with the fix. 
So feel free to close, if no more actions can be taken.

**Comment by ghiculescu** [comment] 2022-11-27 06:46
@byroot @rafaelfranca do you think we will make any big changes for this in Rails 7.1?

In any case I will close this particular issue as resolved.

**Closed by ghiculescu** 2022-11-27 06:46 UTC
Labels: railties

**Comment by pbstriker38** [comment] 2024-03-28 00:05
Here's another gem that loads ActiveRecord too early. It seems like they don't want to accept my PR unless I add a way to test it. Any ideas on a good way to test it?

https://github.com/flippercloud/flipper/pull/832

**Comment by byroot** [comment] 2024-03-28 06:38
That's not really testable unless you have something like our Railties test that generate and boot an application. But it's very slow and doubt flipper will want just 20 seconds test.
