### ISSUE TITLE
accept_nested_attributes not working without simple_token_authentictaion (gem)

### ISSUE THREAD

**Issue by faisalsahil** [rails/rails#25425] opened 2016-06-17 09:10 UTC
### Steps to reproduce
1. Create new project in rails 5 
2. Create models  
     -  rails g model user username:string.
     -  rails g model product name:string user_id:integer

3. Create relationship b/w models
       Class User
         has_many :products
         accepts_nested_attributes_for :products

     Class Product
       belongs_to   :user

4. Gemfile is: 
      gem 'annotate'
      gem 'dotenv-rails'
      gem 'mysql2'
      gem 'pg'
      gem 'puma', '~> 3.0'
      gem 'rails', '>= 5.0.0.rc1', '< 5.1'
      gem 'redis', '~> 3.0'
      gem 'rack-cors', require: 'rack/cors'
      gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
      gem 'annotate'
      gem 'awesome_print'
      gem 'better_errors' 
      gem 'binding_of_caller'
      gem 'byebug', platform: :mri
      gem 'pry'
      gem 'spring'
      gem 'spring-watcher-listen', '~> 2.0.0'
      gem 'web-console'

5.  Go to terminal and run following commands:
     data  = {"user": {"username": "test", "products_attributes": [{"name": "p1"}, {"name": "p2"}]}}
     User.create!(data[:user])
 
### Expected behavior
User and products should be created.

### Actual behavior
--ROLLBACK
Error:     ActiveRecord::RecordInvalid: Validation failed: Products user must exist

### System configuration
**Rails version**:
    'rails', '>= 5.0.0.rc1', '< 5.1'
**Ruby version**:
    2.3.0

**Comment by faisalsahil** [comment] 2016-06-17 09:18
I solved this by adding the gem in gemfile.
     gem 'simple_token_authentication'
but its no a proper solution because the ActiveRecord, Rake etc not depends on this gem.

**Comment by sgrif** [comment] 2016-06-17 10:24
Duplicate of #25198

**Closed by sgrif** 2016-06-17 10:24 UTC
