### ISSUE TITLE
ActiveRecord::SubclassNotFound (Invalid single-table inheritance type) after file change

### ISSUE THREAD

**Issue by alfie-max** [rails/rails#29542] opened 2017-06-23 03:36 UTC
### Steps to reproduce
Here's a repo i put together for reproducing the issue : https://bitbucket.org/alfiemax/traderapp
The readme in it should be self explanatory.

I've got Trader & Retailer Model which is inherited from User model (STI)
Devise has been setup for authentication. and when the `authenticate_trader!` method is called is when the issue gets triggered.

To reproduce, setup the app. make the `connect` action after signing up. It should work fine.
Now make any change to any model/controller (just add a new line to the class). The purpose is to trigger a code change.

### Expected behavior
This is what should happen both the times.

![ok_request](https://user-images.githubusercontent.com/8247590/27465674-afe9d418-57f2-11e7-93b0-c9ef6a3df7ef.png)

### Actual behavior
This is what happens. 
![error_request](https://user-images.githubusercontent.com/8247590/27465686-bc670814-57f2-11e7-9cb2-23457868d0eb.png)

Seems like the object referenced as `self`does not get loaded after file change and so the equality `subclass == self` fails and hence the error :

```
ActiveRecord::SubclassNotFound (Invalid single-table inheritance type: Trader is not a subclass of Trader):
```

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

**Comment by sevenseacat** [comment] 2017-06-23 03:52
Worth noting that when I tested it out with that repo, I couldn't replicate the buggy behaviour.

**Comment by alfie-max** [comment] 2017-06-23 04:06
@sevenseacat did you edit any code and make the request again? I got it replicated in 3 different systems. (1 OSX, 2 Ubuntu)

**Comment by sevenseacat** [comment] 2017-06-23 04:14
I did.

**Comment by alfie-max** [comment] 2017-06-23 04:18
here's a screen recording i did just now : https://www.dropbox.com/s/sds4agjivtglz4c/bug_report.mov?dl=0

**Comment by redtachyons** [comment] 2017-06-23 05:33
Reproduced the issue, Cause is `subclass` is getting reloaded when some files are changed and it gets new object_id. But `self` object is remains the same as before.
 So once [remove_unloadable_constants!](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/dependencies.rb#L549) is triggered
```ruby
self == subclass
``` 
will fail
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/dependencies.rb#L558

**Comment by redtachyons** [comment] 2017-07-08 18:06
Cross posting the comment from related issue @waiting-for-dev/devise-jwt

I tried to find the cause of this issue, In devise jwt we are storing model mappings in ```JWT.config.mappings``` this configuration is not auto loaded and will remain the same for entire lifespan of the app. But the actual model will reload and will have new class with same name but with different object_id.

Eg

model `Trader` is loaded is object id 1
`JWT.config.mappings` will be `{:trader => Trader()}`
Now once the app is reloaded in file change, `Trader` will get reloaded and get new id 2.

But devise jwt will be still using old model which is cached inside mappings hash. So the equality comparison fails

I am not sure about which gem is to be fixed

- If it is devise-jwt gem, then we have to make config hash compatible with autoload
- If it is active record, then we have to change comparison logic, from object_id to model name

**Comment by pixeltrix** [comment] 2017-07-28 13:53
Closing as this is a devise-jwt issue - maintaining long-lived references to classes in development mode has always had this limitation and changing the logic in Active Record won't help solve the problem.

**Closed by pixeltrix** 2017-07-28 13:53 UTC

**Comment by arivero** [comment] 2019-04-25 18:51
Plain Rails 5.2.3 here, I can trigger a very similar if not the same problem, no jwt issue, I am executing "bundle exec rails server" from command line, no more.

`ActiveRecord::SubclassNotFound (Invalid single-table inheritance type: Admin is not a subclass of User)`

But in my case the fail is that `descendants.include?(subclass)` goes to false, when it was being true before the update of the controller.

Before saving the controller, descendants show the daughter class, but when the development mode has reloaded the files it becomes empty.

**Comment by blaszczakphoto** [comment] 2019-05-02 08:48
I am also having this issue in 6.0.0.beta3

**Comment by arivero** [comment] 2019-06-05 12:29
It is actually a headache as one is forced to kill server and reload all the time during development if using subclasses. Is there any workaround?

**Comment by amitsaxena** [comment] 2019-06-14 14:54
+1 to that this issue exists in rails 5.2.2.1 and is a headache when doing development.

**Comment by travisofthenorth** [comment] 2019-06-17 21:58
+1

**Comment by adlerfaulkner** [comment] 2019-08-09 20:11
+1

**Comment by pixeltrix** [comment] 2019-08-27 16:35
The way to solve these errors is to hook into the mechanisms we provide for handle code reloading such as [`to_prepare`][1] and [`before_remove_const`][2]. How you handle letting go of the references and getting references to the newly defined constants is very much application dependent and not something we can do generically in Rails but if you're using STI I would definitely suggest preloading all the subclasses using `require_dependency` in a `to_prepare` block so that Active Record knows about all of them.

Some of you may be seeing ActiveRecord::SubclassNotFound when upgrading because we now validate the parent class to avoid abuse of setting the STI class via user submitted attributes. However the base cause is still references to unloaded constants being kept and re-used.

I'm going to lock this to prevent more +1 comments being added since no-one is looking at this issue now. If you feel like you've found something in Rails that causes `ActiveRecord::SubclassNotFound` and you've double checked you're not holding onto a constant please open a new issue.

[1]: https://guides.rubyonrails.org/configuring.html#initialization-events
[2]: https://blog.subvertallmedia.com/2015/07/03/model-caching-in-rails-or-when-a-student-is-not-a-student/
