### ISSUE TITLE
`build_association` on `belongs_to` does not add the builder to has_many association

### ISSUE THREAD

**Issue by matthee** [rails/rails#32024] opened 2018-02-16 21:10 UTC
### Steps to reproduce

When `build_association` is called on a `belongs_to` relation, then the model does not get added to the inverse `has_many` relation. This behavior can also be observed when assigning a new record directly to the `belong_to` association.

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.5"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :authors, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :authors

  validates :authors, length: { minimum: 1 }
end

class Author < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test

  def test_build_association_adds_to_inverse
    author = Author.new

    post = author.build_post

    assert_equal 1, post.authors.length
    assert_equal author, post.authors.first
    assert_predicate author, :valid?
    assert_predicate post, :valid?
    assert author.save
  end

  def test_assigning_belongs_to_adds_to_inverse
    author = Author.new
    post = Post.new

    author.post = post

    assert_equal 1, post.authors.length
    assert_equal author, post.authors.first
    assert_predicate author, :valid?
    assert_predicate post, :valid?
    assert author.save
  end

end
```
 
### Expected behavior

I expect the `Post` model to know about the author, through which it was built. This would match the behavior observed, when used the other way round. (`post.authors.build` actually assigns the inverse `post` and `post = authors.build_post` results in `authors.post == post` being `true`) 

### Actual behavior

The `authors` relation is blank. Hence, the validations on the `Post` model are failing. Neither am I able to then save `Post` nor the `Author` model, without me explicitly adding the `Author` model to the `post.authors` relation.

### System configuration
**Rails version**:
5.1.5
**Ruby version**:
2.3.6

**Comment by jfragoulis** [comment] 2018-02-26 14:11
This may have to do with https://github.com/rails/rails/pull/31575.

**Comment by matthee** [comment] 2018-02-26 14:43
I'm not exactly sure what you mean. I've run the test case against AR 5.2.0.rc1 and it still persists. 

I've originally encountered the bug in an application using AR 4.2.6, but I'm well aware that there won't be landing a bug fix in the old 4.2 branch. Since this bug seems to be present since at least rails version 4.2, i was wondering if it still persisted in a newer rails version, which it obviously does.

**Comment by victorhazbun** [comment] 2018-03-04 07:30
Can someone confirm is this is a bug or not? Thanks!

**Comment by Stormcore** [comment] 2018-03-28 17:58
Reproduces on 5.1.2 when migrated from 4.2.1  and it has broken all application - that's a disaster!!!

**Comment by rafaelfranca** [comment] 2018-03-28 19:12
> Can someone confirm if this is a bug or not?

Please do investigate.

**Comment by Stormcore** [comment] 2018-03-28 20:59
I can confirm its a bug as it worked as expected on rails 4.2 and now relations are broken, which argument does it need in addition?

**Comment by rafaelfranca** [comment] 2018-03-28 21:11
Someone to investigate and fix the bug. Rails is made by volunteers and people usually to be better motivated when the problem is their problem.

**Comment by victorhazbun** [comment] 2018-03-28 21:46
I tested the script with `gem "activerecord", "4.2.1"` instead of `gem "activerecord", "5.1.5"` and the tests are still broken. https://gist.github.com/victorhazbun/3570daaeaf78450e46d9d5904289aba7 Am I doing something wrong?

**Comment by Stormcore** [comment] 2018-03-28 21:52
@victorhazbun could you test on 4.2.0 please?

**Comment by victorhazbun** [comment] 2018-03-28 21:57
Results for `gem "activerecord", "4.2.0"` still not passing https://gist.github.com/victorhazbun/195f4d8a8043584e10fd60639ec51908

**Comment by jash-kothari** [comment] 2018-07-02 11:34
Is this still an issue would like to pick this up.

**Comment by dmitry** [comment] 2020-01-25 18:27
In the latest rails you can set `ActiveRecord::Base.has_many_inversing = true` to make it work.

**Comment by kaelumania** [comment] 2020-05-05 07:57
should this be fixed in 6.0.2.2?

**Comment by Edouard-chin** [comment] 2024-01-23 13:41
Fixed by https://github.com/rails/rails/pull/50284

**Closed by Edouard-chin** 2024-01-23 13:41 UTC
Labels: activerecord, With reproduction steps

**Comment by zzak** [comment] 2024-05-24 12:34
I could be wrong but since #50284 was reverted, this should be re-opened.
