### ISSUE TITLE
create_of_find_by not returning object

### ISSUE THREAD

**Issue by atstockland** [rails/rails#35450] opened 2019-03-02 05:18 UTC
### Steps to reproduce
Use create_or_find_by on a model.  Such as Automobile.create_or_find_by(name: 'Ford')

### Expected behavior
Assuming a Ford record (with only a name attribute) exists...  
Automobile.create_or_find_by(name: 'Ford') should return that object.  
And, Automobile.create_or_find_by(name: 'Ford').id should return the record id.

### Actual behavior
The Ford record does exist in the database.  Yet, Automobile.create_or_find_by(name: 'Ford') returns an empty object with only the name attribute.  For example, I could do Automobile.create_or_find_by(name: 'Ford').name.  But, I could not do Automobile.create_or_find_by(name: 'Ford').id

If the record does not exist, the record is created and object returned as expected.  This is only an issue when the record already exists.

+--+------+-----------+-----------+
| id | name | created_at | updated_at |
+--+------+-----------+-----------+
|     |  Ford |                    |                     |
+--+------+-----------+-----------+

### System configuration
Rails 6 beta 2

**Ruby version**:
2.6.1p33

**Comment by y-yagi** [comment] 2019-03-08 02:56
Thanks for your report, but I cannot reproduce your issue.
Can you create a reproduce script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)?

**Comment by atstockland** [comment] 2019-03-08 18:03
I was not able to reproduce in tests using that template.  I added all the gems in my gemfile to the template, and customized the Post model to include name attribute.  I was not able to reproduce.  Yet, the issue remains in my app.  Strange.  I will continue trying to create a test that will reproduce the issue.

**Comment by atstockland** [comment] 2019-03-11 23:31
I have continued playing with this...attempting to create a test within the script that will illustrate this bug.  I can find anything in my app configs, etc that seem to, or even could, alter rails create_or_find_by method.  It's quite strange.

**Comment by y-yagi** [comment] 2019-03-11 23:36
Can you reproduce the issue with a newly application?

**Comment by atstockland** [comment] 2019-03-12 00:08
I was not able to reproduce in a new app.  But, what possibly in my existing app could be altering the behavior of a rails method (I have not defined a create_or_find_by method)?

I guess this proves it is not a Rails bug.  It's my bug.  I'll post back if I find something interesting.

**Comment by y-yagi** [comment] 2019-03-12 00:18
Thanks for your investigation. I close this because it doesn't seem like a bug of Rails.  
But if there is a possibility of a bug in Rails in further investigation, please feel free to reopen this. Thanks.

**Closed by y-yagi** 2019-03-12 00:18 UTC

**Comment by thib44** [comment] 2019-05-15 10:08
I have the same Issue.
I have a Company model, with an existing company of title 'Cubyn'.
If I do a find, i've got the company :
```
Company.find_by(title: 'Cubyn')
  Company Load (0.3ms)  SELECT "companies".* FROM "companies" WHERE "companies"."title" = $1 LIMIT $2  [["title", "Cubyn"], ["LIMIT", 1]]
=> #<Company:0x00007fa457c287f8
 id: "f4038208-e2a9-49a0-8547-923fb5c144cf",
 title: "Cubyn",
 created_at: Tue, 14 May 2019 08:59:43 UTC +00:00,
 updated_at: Tue, 14 May 2019 08:59:43 UTC +00:00>
```

But if I do a create_or_find_by, it return a record without id :
```
Company.create_or_find_by(title: 'Cubyn')
   (0.2ms)  BEGIN
  Company Exists? (0.4ms)  SELECT 1 AS one FROM "companies" WHERE "companies"."title" = $1 LIMIT $2  [["title", "Cubyn"], ["LIMIT", 1]]
   (0.2ms)  COMMIT
=> #<Company:0x00007fa45a74ea68 id: nil, title: "Cubyn", created_at: nil, updated_at: nil>
```

**System Configuration :**
Rails 6.0.0.rc1 <br>
ruby-2.6.3

**Comment by vibragiel** [comment] 2019-10-21 12:25
@atstockland @thib44 `create_or_find_by` relies on the model raising an `ActiveRecord::RecordNotUnique` exception when trying to create a duplicate object with the provided `name`. This is only going to happen if both:

1) The model's table has a `UNIQUE INDEX` defined by the `name` column.
2) The model doesn't have a `uniqueness` ActiveRecord validation by `name` (otherwise, `create` will return the incomplete object without raising)
