### ISSUE TITLE
[actioncable] Add engines to package.json

### ISSUE THREAD

**Issue by MichaelDeBoey** [rails/rails#39847] opened 2020-07-14 20:39 UTC

**Comment by composerinteralia** [comment] 2020-08-16 02:51
Could you provide a bit more detail here? What were you trying to do and what error did you see? How might I be able to reproduce that error?

**Comment by MichaelDeBoey** [comment] 2020-08-16 08:56
@composerinteralia I didn't get any error, but adding an `engines` key to `package.json` makes it more clear which minimum Node version should be used to use this package.

**Comment by composerinteralia** [comment] 2020-08-20 03:26
Got it, thanks for clarifying. Are there specific versions of Node that definitely don't work with Action Cable that you know of?

**Comment by KapilSachdev** [comment] 2020-08-25 05:58
Haven't looked closely but I think `>=8.0.0` would be a safe bet as `http-proxy` used by `karma` requires `>=8.0.0` in `action_cable`.

This can be extended to `action_view`, `active_storage` and `action_text` as well.

`>=8.0.0` for `action_cable`
`>=4.0` for `active_storage` 
`>=4.0` for `action_text` as well because of `active_storage` dependency as `trix` will work fine with `>=0.10.0`.
`>=6.9.1` is required by `coffeelint` so same for `action_view`
So `>=8.0.0` can be added under rails.

**Comment by composerinteralia** [comment] 2020-09-03 01:45
Needing to manually search through our dependencies doesn't sound right to me. If our dependencies have engine constraints, then I would expect `yarn` to do whatever it needs to do with those constraints without us having to add anything on our end.

Since it sounds like there isn't any specific bug here, I am going to close this issue for now. If we find a specific problem that the `engines` key will help solve, then we can reopen this issue.

Thanks!

**Closed by composerinteralia** 2020-09-03 01:45 UTC
