### ISSUE TITLE
Two foreign key violations test get failure with PostgreSQL

### ISSUE THREAD

**Issue by yahonda** [rails/rails#19265] opened 2015-03-09 19:42 UTC
Sometimes `rake test_postgresql` causes two failures. 
Here are minimum case to reproduce these failures.

```ruby
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
$ psql --version
psql (PostgreSQL) 9.4.1
```

```ruby
$ ARCONN=postgresql ruby -w -I"lib:test"  "/home/yahonda/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/cases/multiple_db_test.rb" "test/cases/adapter_test.rb"

Using postgresql
Run options: --seed 6225

# Running:

................F.....F....

Finished in 0.736658s, 36.6520 runs/s, 84.1639 assertions/s.

  1) Failure:
ActiveRecord::AdapterTest#test_foreign_key_violations_are_translated_to_specific_exception_with_validate_false [/home/yahonda/git/rails/activerecord/test/cases/adapter_test.rb:162]:
ActiveRecord::InvalidForeignKey expected but nothing was raised.


  2) Failure:
ActiveRecord::AdapterTest#test_foreign_key_violations_are_translated_to_specific_exception [/home/yahonda/git/rails/activerecord/test/cases/adapter_test.rb:146]:
ActiveRecord::InvalidForeignKey expected but nothing was raised.

27 runs, 62 assertions, 2 failures, 0 errors, 0 skips
```

I still do not know how to fix them yet, there are some findings.

- They do not reproduce by switching the order of "test/cases/multiple_db_test.rb" "test/cases/adapter_test.rb

```ruby
$ ARCONN=postgresql ruby -w -I"lib:test"  "/home/yahonda/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/cases/adapter_test.rb" "test/cases/multiple_db_test.rb" 
```

- Also they do not reproduce by removing `rake_test_loader.rb` as follows

```ruby
$ ARCONN=postgresql ruby -w -Itest "test/cases/multiple_db_test.rb" "test/cases/adapter_test.rb"
```

- There may be `self.use_transactional_fixtures = false` at https://github.com/rails/rails/blob/master/activerecord/test/cases/multiple_db_test.rb#L7

is related with these failures. Since these tests requires parents table data at `pk_has_pk` data
needs loaded to cause foreign key integrity errors.

Will update when I find some good fix.

**Comment by senny** [comment] 2015-03-11 13:37
:flushed: @yahonda thank you for catching this. :yellow_heart: 

Caused by a typo I committed some time ago.

**Closed** 2015-03-11 13:37 UTC

**Comment by yahonda** [comment] 2015-03-11 13:47
Great!
