### ISSUE TITLE
undefined method `alias_method_chain' for Sprockets::Manifest:Class (NoMethodError)

### ISSUE THREAD

**Issue by sandeep181819** [rails/rails#46660] opened 2022-12-07 08:05 UTC
I am getting below issue when trying to run the rails server. It is coming when I have migrated the rails application from 4.2 to 5.2.
After commenting `Bundler.require(*Rails.groups)` in application.rb will fix the issue.

/Users/rahul/.rvm/gems/ruby-2.6.10/gems/non-stupid-digest-assets-1.0.5/lib/non-stupid-digest-assets.rb:50:in `<class:Manifest>': undefined method `alias_method_chain' for Sprockets::Manifest:Class (NoMethodError)
Did you mean?  alias_method
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/non-stupid-digest-assets-1.0.5/lib/non-stupid-digest-assets.rb:24:in `<module:Sprockets>'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/non-stupid-digest-assets-1.0.5/lib/non-stupid-digest-assets.rb:23:in `<main>'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rahul/.rvm/rubies/ruby-2.6.10/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/rahul/.rvm/rubies/ruby-2.6.10/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `each'
	from /Users/rahul/.rvm/rubies/ruby-2.6.10/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
	from /Users/rahul/.rvm/rubies/ruby-2.6.10/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `each'
	from /Users/rahul/.rvm/rubies/ruby-2.6.10/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `require'
	from /Users/rahul/.rvm/rubies/ruby-2.6.10/lib/ruby/site_ruby/2.6.0/bundler.rb:114:in `require'
	from config/application.rb:10:in `<main>'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<main>'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from/bin/rails:9:in `<top (required)>'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	from /Users/rahul/.rvm/gems/ruby-2.6.10/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from bin/spring:15:in `require'
	from bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by asif9qureshi** [comment] 2022-12-07 08:11
I would very much want to help but please share steps on how to reproduce this issue.

**Comment by eileencodes** [comment] 2022-12-07 13:56
Hi @sandeep181819 - `alias_method_chain` was removed in Ruby 2.0 in favor of `prepend`. Rails 5+ required Ruby 2.0 and above so it looks like that's what's happening in your `non-stupid-assets` gem. It might have been fixed so you may want to try upgrading but ultimately you should probably swap that gem out as it appears to no longer be maintained since 2016.

Rails 5.2 is no longer supported and will not receive security patches as of June 2022, so we recommend at a minimum being on 6.0 (6.0 support ends in June 2023).

This is not a Rails bug so I'm going to close this.

**Closed by eileencodes** 2022-12-07 13:56 UTC
