### ISSUE TITLE
Rails 7.0.7.1 migrations issue

### ISSUE THREAD

**Issue by jason-hobbs** [rails/rails#49002] opened 2023-08-22 19:52 UTC
When running migrations on Kubernetes with 7.0.7.1 I am getting:
```
<internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- /usr/local/bundle/gems/activesupport-7.0.7.1/lib/active_support/dependencies/autoload.rb (LoadError)
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /usr/local/bundle/gems/activesupport-7.0.7.1/lib/active_support.rb:27:in `<main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /usr/local/bundle/gems/railties-7.0.7.1/lib/rails/command.rb:3:in `<main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /usr/local/bundle/gems/railties-7.0.7.1/lib/rails/commands.rb:3:in `<main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

With 7.0.7 I have no issues.  I have reverted for now.

**Comment by smortex** [comment] 2023-08-22 19:56
Hey!

Faced a similar issue today with CD failing to deploy new version:

```
LoadError: cannot load such file -- /srv/www/xxx/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.7.1/lib/active_support/dependencies/autoload.rb
```

The file has wrong permission:

```sh-session
$ ls -l /srv/www/xxx/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.7.1/lib/active_support/dependencies
-rw------- 1 deploy deploy 1728 22 août  07:56 /srv/www/xxx/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.7.1/lib/active_support/dependencies/autoload.rb
```

Only this file seems affected:

```sh-session
$ ls -l /srv/www/xxx/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.7.1/lib/active_support/dependencies
total 12
-rw------- 1 deploy deploy 1728 22 août  07:56 autoload.rb
-rw-r--r-- 1 deploy deploy 1159 22 août  07:56 interlock.rb
-rw-r--r-- 1 deploy deploy 1029 22 août  07:56 require_dependency.rb
```

The group and other are missing the read permission.

**Comment by rafaelfranca** [comment] 2023-08-22 19:59
Duplicate of #49002

**Closed by rafaelfranca** 2023-08-22 19:59 UTC

**Comment by smortex** [comment] 2023-08-22 20:03
> Duplicate of #49002

_This_ is #49002 :upside_down_face: 

Duplicate of #49000

**Comment by rafaelfranca** [comment] 2023-08-22 20:03
RIght. Fixed it
