### ISSUE TITLE
5.0.0.beta1 generated Gemfile uses wrong version of turbolinks

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#22834] opened 2015-12-29 18:51 UTC
I think it ought to be using the version in master rather than the released 2.5.3 version.  The released version uses before_filter and after_filter which raise deprecation warnings with Rails 5.0.0.beta1.  Alternatively, turbolinks should have a 3.0.0.beta1 release.

**Comment by rafaelfranca** [comment] 2015-12-29 19:07
It is by design. Turbolinks master is not ready to be released yet because turbolinks 3 will never see the sun light https://github.com/rails/turbolinks/issues/628. When turbolinks 5 is released we will use it in the generated Gemfile, but we can't point users to a version that is not going to be released as it is.

**Closed by rafaelfranca** 2015-12-29 19:07 UTC

**Comment by jcoyne** [comment] 2015-12-29 19:59
@rafaelfranca The issue is that users will see deprecation warnings with the default gemset.  That seems undesirable. 

Possibly we backport https://github.com/rails/turbolinks/commit/d759161cf46243d2e9316864ee8a045be0d7b25b
https://github.com/rails/turbolinks/commit/a6175e9ca426c3c6d7f74c6b2346488513897825
https://github.com/rails/turbolinks/commit/ed5b866d9972e4f47dddc736347d199f2c9d654a

to the turbolinks 2.5-stable branch and create a new release of Turbolinks 2? Or is Turbolinks 5 going to be released before Rails 5 final?

**Comment by eileencodes** [comment] 2015-12-29 20:01
@jcoyne Yup, the plan is to release Turbolinks 5 with Rails 5.

**Comment by rafaelfranca** [comment] 2015-12-29 20:01
> Or is Turbolinks 5 going to be released before Rails 5 final?

Yes, it will, or at least it should. If not we will backport, but that is not priority right now.

**Comment by jcoyne** [comment] 2015-12-29 20:03
I was unaware that Turbolinks 5 existed.  For anyone else who's looking, you can find it here: https://github.com/basecamp/turbolinks/tree/v5
