### ISSUE TITLE
Accessing `response.body` inside any controller action messes up the response

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [rails/rails#23964] opened 2016-02-29 16:51 UTC
I was trying to set strong ETags header by using the response.body inside the controller 

``` ruby
def set_etag # after_action callback
  response.headers["ETag"] = Digest::MD5.hexdigest(response.body)
end
```

But it gives following error - 

```
ActionDispatch::IllegalStateError (header already sent):
  
app/controllers/posts_controller.rb:8:in `index'
  Rendering /Users/prathamesh/Projects/sources/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/prathamesh/Projects/sources/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /Users/prathamesh/Projects/sources/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (4.0ms)
  Rendering /Users/prathamesh/Projects/sources/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/prathamesh/Projects/sources/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.7ms)
  Rendering /Users/prathamesh/Projects/sources/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/prathamesh/Projects/sources/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /Users/prathamesh/Projects/sources/rails/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (59.1ms)
```

**Comment by vipulnsward** [comment] 2016-02-29 19:59
This is probably something we should document?
You have used `response.body`, which similar to creating response out of the action, after which you are setting some header on already created response, which is causing an error.
I don't see someone calling `response.body` and using response header though.

**Comment by vsorlov** [comment] 2016-02-29 21:23
this is caused by https://github.com/rails/rails/commit/69009f4473637a44ade26d954ef5ddea6ff903f2#diff-0b53645cdb23933ef05759b2426f069aR42

both @response.sending? and @response.sent? are true

**Comment by rthbound** [comment] 2016-03-02 02:36
This would recreate: https://gist.github.com/rthbound/0f15b2295a2995ae1ab5

The commented out bits, would make use of this for a workaround: [compare origin:master...rthbound:adds-workaround-for-23964-via-rewind](https://github.com/rails/rails/compare/master...rthbound:adds-workaround-for-23964-via-rewind?expand=1)

**Comment by rthbound** [comment] 2016-03-02 03:10
[This branch](https://github.com/rails/rails/compare/master...rthbound:fixes-23964?expand=1) tries to fix it by allowing a user to call `response.body(should_send = false)`. This change has `should_send` defaulted to `true`, but it'd be better to default the other way... So, call `response.body(true)` internally when sending so that a user could just call `response.body` as usual.

**Comment by tenderlove** [comment] 2016-04-04 17:46
I'm not sure I understand the usecase.  This code:

```ruby
def index
  response.headers["ETag"] = Digest::MD5.hexdigest(response.body)
end
```

accesses the response body before anything has been rendered.  `response.body` will always be an empty string in this case, so you'll always generate the same ETag.  You could just write:

```ruby
def index
  response.headers["ETag"] = Digest::MD5.hexdigest('')
end
```

Is there some use case that has been omitted?  Thanks.

**Comment by rthbound** [comment] 2016-04-04 18:24
@tenderlove consider a case where the etag header is set in an `after_action` callback.

E.g. https://gist.github.com/rthbound/859508ebc9b07964dcb9f51473dc0ad6

**Comment by tenderlove** [comment] 2016-04-04 20:56
@rthbound thank you!  That makes much more sense.

**Comment by prathamesh-sonpatki** [comment] 2016-04-05 10:48
Thanks @rthbound I updated the issue description.

**Comment by sgrif** [comment] 2016-04-13 19:11
Is this new in 5.0 or is this issue present on 4.2?

**Comment by vipulnsward** [comment] 2016-04-13 19:33
No this was introduced with https://github.com/vipulnsward/rails/commit/fcf5e178dd6384cb5f9e99c0026ba958e426a03f

**Comment by maclover7** [comment] 2016-04-14 17:37
Marking as a regression, since this is a bug that was introduced starting in the 5.0 betas, and is an unintentional breaking change.

**Comment by jeremy** [comment] 2016-04-26 02:30
#24029

**Comment by sgrif** [comment] 2016-05-06 17:02
Leaving this open since we haven't actually merged a fix yet.

**Closed** 2016-05-06 19:22 UTC
Labels: actionpack, attached PR, regression
