### ISSUE TITLE
Signed cookie bug

### ISSUE THREAD

**Issue by freiden** [rails/rails#39704] opened 2020-06-23 10:26 UTC
Since the last update of Rack (2.2.3) the signed cookie keys are not url decoded by Rails which prevent to retrieve them from the cookie when using special characters.

### Steps to reproduce

Set a signed cookie from the test and try to retrieve the value from the controller using the same key

I created a sample project to details the issue https://github.com/freiden/test-signed-cookie
the main files  are https://github.com/freiden/test-signed-cookie/blob/master/test/integration/cookies_controller_test.rb and https://github.com/freiden/test-signed-cookie/blob/master/app/controllers/cookies_controller.rb

### Expected behavior

The cookie should contain the key used to insert the signed value

### Actual behavior

The cookie contain a url encoded version of the key used to insert the signed value

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.6.6

**Comment by pixeltrix** [comment] 2020-06-23 11:13
@freiden I think this is a duplicate of #39670, yes? I know your report is about signed cookies but effectively it's the same underlying issue.

**Comment by freiden** [comment] 2020-06-23 12:09
@pixeltrix thanks it seems like it's the same. I'll close mine.

**Closed** 2020-06-23 12:09 UTC
