### ISSUE TITLE
Don't know how to build task 'active_storage:install'

### ISSUE THREAD

**Issue by marwenB** [rails/rails#33792] opened 2018-09-04 15:29 UTC
### Steps to reproduce
rails active_storage:install

### Expected behavior

`Copied migration 20171127215057_create_active_storage_tables.active_storage.rb from active_storage`

### Actual behavior

> rails aborted!
> Don't know how to build task 'activestorage:install' (see --tasks)
> //~app/bin/rails:9:in `require'
> //~app/bin/rails:9:in `<top (required)>'
> //~app/bin/spring:15:in `<top (required)>'
> bin/rails:3:in `load'
> bin/rails:3:in `<main>'
> (See full trace by running task with --trace)

### System configuration
**Rails version**:
`Rails 5.2.0`
**Ruby version**:
`ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]`

**BUNDLED WITH**:
 `  1.16.1`

**Comment by y-yagi** [comment] 2018-09-04 22:54
Can you please provide a sample application that reproduces the issue?

**Comment by ben-toogood** [comment] 2018-09-14 10:41
Duplicate of https://github.com/rails/rails/issues/31245

**Comment by MarkMekhaiel** [comment] 2018-09-14 10:46
Going through this at the minute myself..

rails active_storage:install
rails aborted!
Don't know how to build task 'active_storage:install' (see --tasks)

rails -v
Rails 5.2.1

ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

**Comment by MarkMekhaiel** [comment] 2018-09-14 10:47
Solution for me was to change

require "active_storage"

to

require "active_storage/engine"

in config/application.rb

**Comment by y-yagi** [comment] 2018-09-16 22:38
I think there is a possibility of mistake of requirement of `active_storage/engine`. Please check the `config/application.rb` 
If you require a correct file, but still encountered an error, please reopen it freely. Thanks.

**Closed by y-yagi** 2018-09-16 22:38 UTC

**Comment by aleccool213** [comment] 2018-09-27 18:18
Got the same issue. My fix was what @MarkMekhaiel suggested.
https://github.com/rails/rails/issues/33792#issuecomment-421318659

**Comment by bholanath-gloify** [comment] 2022-10-20 07:19
rails -v
5.0.7.2
ruby -v
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]


same error!
include require "active_storage/engine"  in application.rb page but again same error!
