### ISSUE TITLE
api.rubyonrails.org/v6.1: broken navigation

### ISSUE THREAD

**Issue by dmke** [rails/rails#43955] opened 2021-12-21 14:31 UTC
This might be related to #43943 ("api.rubyonrails.org/v6.1 redirects to edgeapi.rubyonrails.org").
/cc @rafaelfranca 

### Steps to reproduce

1. Visit https://api.rubyonrails.org/v6.1/
2. In the main content area, click on the "Active Record" link in the second section:
   
   ![image](https://user-images.githubusercontent.com/327411/146944859-b85365e8-2b45-4a12-8e6b-10a5271f890e.png)

3. I'm redirected to `https://edgeapi.rubyonrails.org/activerecord/README_rdoc.html`, which answers with a 404 error.

Alternatively:

1. Search for a method in the sidebar and hit enter:
 
   ![image](https://user-images.githubusercontent.com/327411/146945486-f1b09eda-758e-490e-9950-16e85b28b7a9.png)

2. The redirect location now is `https://edgeapi.rubyonrails.org/undefinedclasses/AbstractController/Rendering.html`, which, again, renders a 404 error page.

### Expected behavior

The page should render the documentation.

### Actual behavior

I'm getting a 404 error.

On https://api.rubyonrails.org/v6.0/, the documentation links seem to work.

When accessing https://api.rubyonrails.org/v6.1/, I'm seeing the following error in the devtools:

```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
   <anonymous> https://api.rubyonrails.org/js/main.js:43
   dispatch https://api.rubyonrails.org/js/turbolinks.js:5
  ...
```

```js
document.addEventListener("turbolinks:load", function() {
  // ...
  // https://api.rubyonrails.org/js/main.js:43
  panel.toggle(JSON.parse($('meta[name="data-tree-keys"]').attr("content")));
```

where there is no `<meta name="data-tree-keys" />` element on the page.

### System configuration

Not relevant.

**Comment by rafaelfranca** [comment] 2022-01-05 20:12
Duplicate of #44042

**Closed by rafaelfranca** 2022-01-05 20:12 UTC
