### ISSUE TITLE
ActiveSupport::Concern#class_methods affects parent classes

### ISSUE THREAD

**Issue by ewoutkleinsmann** [rails/rails#20489] opened 2015-06-09 11:42 UTC
ActiveSupport::Concern's class_methods uses const_defined? without a second argument and therefore also searches its ancestors for a ClassMethods module. This results in concerns included in a child class that add class methods to a parent class.

Code example:
```ruby
require 'active_support/concern'

module Foo
  extend ActiveSupport::Concern

  class_methods do
    def foo

    end
  end
end

module Bar
  extend ActiveSupport::Concern

  class_methods do
    def bar

    end
  end
end

class Parent
  include Bar
end

class Child < Parent
  include Foo
end

Parent.respond_to? :foo # returns true
```

Am I right that this isn't the desired behaviour?

**Comment by kddeisz** [comment] 2015-06-09 13:53
Slightly more concerning:

```
require 'active_support/concern'

module Foo
  extend ActiveSupport::Concern

  class_methods do
    def foo
    end
  end
end

class Bar
  include Foo
end

BasicObject.respond_to? :foo # true
```

**Comment by kddeisz** [comment] 2015-06-09 14:08
For that matter I also don't understand:

```
require 'active_support/concern'

module Foo
  extend ActiveSupport::Concern

  class_methods do
    def foo
    end
  end
end

class Bar
  include Foo
end

BasicObject.respond_to? :foo #true
```

**Comment by sgrif** [comment] 2015-06-09 14:14
Wow I had just started looking at what was going on with the original issue but that second bit made me crack up.

**Comment by sgrif** [comment] 2015-06-09 14:15
I find this bug very... Concerning...

OK I'll stop now and actually fix it.

**Comment by knovoselic** [comment] 2015-06-09 14:31
I was just debugging the same bug. For me, changing 
`mod = const_defined?(:ClassMethods) ?`
 to 
`mod = const_defined?(:ClassMethods, false) ?` 
fixes the problem - but I do not know enough to say that it's not breaking something else.

@sgrif Any idea when this fix (and v4.2.2) will be released? Are we talking days, weeks or months?

**Comment by sgrif** [comment] 2015-06-09 14:33
Yes, that change is what I was thinking as well. If the tests pass, it's fine, we just need a failing test for this case. Feel free to open a PR. We do not have a specific date for 4.2.2, but usually we release ~once per month.

**Comment by knovoselic** [comment] 2015-06-09 16:58
So I've been trying to reproduce this, but wasn't able to. I've been using @ewoutkleinsmann's code. 
`ruby test.rb` always returns false (test.rb has @ewoutkleinsmann's code inside, last line is printed to console).
Finally, I tried this:
`rails r test.rb`

and this returns true. After some more debugging, it seems that `Mongoid::Extensions::Object::ClassMethods` has something to do with all this.
After I've added 'require mongoid' in test.rb, running it outside of rails also returns true.

Seems that this line is problem in mongoid's `object.rb`:
`::Object.__send__(:include, Mongoid::Extensions::Object)`

After the include  inner module gets define on `::Object` and module's name is `ClassMethods`. Should I open bug report with Mongoid about this? I think it's a bug, but I'm not sure. I'll create PR for this bug shortly.

**Comment by kddeisz** [comment] 2015-06-09 18:25
It has to do with whether or not there's a ClassMethods in the inheritance chain of the singleton class. In my project it happens to be `Delayed::MessageSending`. You can find out with something like:

```
Object.ancestors.select { |klass| klass.const_defined?(:ClassMethods, false) }
```

**Comment by knovoselic** [comment] 2015-06-10 10:53
Yes, that's it, but I do not see a reason why `Mongoid` would like to include `ClassMethods` module into `Object`, do you? I mean, if their module was rewritten like this:

    module Mongoid::Extensions::Object
        module InstanceMethods
            ...
        end
        module ClassMethods
            ...
        end
    end

and then if `InstanceMethods` was included and `ClassMethods` was extended, this bug wouldn't happen. Or am I missing something?

**Comment by kddeisz** [comment] 2015-06-10 14:50
The module is defined here: https://github.com/mongoid/mongoid/blob/master/lib/mongoid/extensions/object.rb#L222

Someone correct me if I'm wrong here, but it's my understanding that when you extend a module (and Class is just a subclass of Module with new and superclass defined, among other things) with another module, it pushes a constant into the ancestor chain of the singleton class of the thing that's being extended. That way the method lookup will hit those methods.

So in this case the Mongoid::Extensions::Object::ClassMethods constant is being pushed into the Object ancestor chain, and because const_defined? is looking for a ClassMethods constant, it's finding it in the ancestor chain of Object. Doesn't really matter if they had added a module called InstanceMethods, either way this would have happened.

Sorry if that was oddly worded.

**Comment by knovoselic** [comment] 2015-06-10 16:13
Here's an example of what I mean. First how it's defined in `Mongoid::Extensions::Object`:

    module Foo
      def foo; end
      module ClassMethods
        def x; end
      end
    end

    ::Object.__send__(:include, Foo)
    ::Object.extend(Foo::ClassMethods)

    p Object.const_defined? :ClassMethods

The code prints `true`.

Now with additional module:

    module Foo
      module InstanceMethods
        def foo; end
      end
      module ClassMethods
        def x; end
      end
    end

    ::Object.__send__(:include, Foo::InstanceMethods)
    ::Object.extend(Foo::ClassMethods)

    p Object.const_defined? :ClassMethods

The code prints `false`.

So right now `Object` has `Foo::InstanceMethods` as its ancestor (instead of just `Foo`) and because `Foo::InstanceMethods` doesn't define inner module `ClassMethods`, the bug will not doesn't get triggered.

**Comment by kddeisz** [comment] 2015-06-10 16:47
Sure, but it's not a bug in Mongoid to implement it like that. This is a bug in rails for not restricting the constant lookup. It's perfectly valid for them to put a ClassMethods module there.

**Closed** 2015-06-12 16:49 UTC
Labels: activesupport
