### ISSUE TITLE
Many to Many relationships creation Error: stack level too deep

### ISSUE THREAD

**Issue by sescobb27** [rails/rails#22153] opened 2015-11-02 05:27 UTC
Hi, I'm just migrating a rails project from 4.2.0 to 4.2.3 but all my Many to Many relationships creation start failing with `stack level too deep`
```ruby
Failure/Error: customer.discounts << discount
SystemStackError:
  stack level too deep
```
 what's the new way to do it? as a workaround I'm just building the relations manually
```ruby
CustomersDiscount.create customer_id: customer.id, discount_id: discount.id
```

**Comment by pixeltrix** [comment] 2015-11-02 06:03
@sescobb27 there isn't a new way to do it and it certainly shouldn't break going from 4.2.0 to 4.2.3. Since this is a commonly used feature of Rails there's probably something unique to your setup that's contributing to the error so it'd be really helpful if you can reproduce the bug using the [Active Record bug report template][1] - this will allow us to track down the problem much quicker.

If you can't do that then we really need to see a backtrace to give us something to go on.

[1]: https://raw.githubusercontent.com/rails/rails/master/guides/bug_report_templates/active_record_gem.rb

**Comment by sescobb27** [comment] 2015-11-03 01:25
I wasn't able to reproduce it, the bug report template worked as expected but here is the stack trace I'm getting in my tests.
```bash
Failures:

  1) API::V1::CustomersController GET #likes customers should get all liked clients
     Failure/Error: customer.discounts << client.discount
     SystemStackError:
       stack level too deep
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/bullet-4.14.9/lib/bullet/active_record42.rb:194:in `has_cached_counter?'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/bullet-4.14.9/lib/bullet/active_record42.rb:194:in `has_cached_counter?'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/bullet-4.14.9/lib/bullet/active_record42.rb:194:in `has_cached_counter?'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/bullet-4.14.9/lib/bullet/active_record42.rb:205:in `has_cached_counter?'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:67:in `insert_record'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:569:in `block (2 levels) in concat_records'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:408:in `replace_on_target'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:403:in `add_to_target'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:568:in `block in concat_records'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:566:in `each'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:566:in `concat_records'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/has_many_association.rb:173:in `concat_records'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:44:in `concat_records'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:168:in `block in concat'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:182:in `transaction'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:168:in `concat'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:38:in `concat'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_proxy.rb:970:in `<<'
     # ./spec/controllers/api/v1/customers_controller_spec.rb:132:in `block (3 levels) in <module:V1>'
     # ./spec/rails_helper.rb:44:in `block (3 levels) in <top (required)>'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:92:in `cleaning'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `call'
     # /home/kiro/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:43:in `block (2 levels) in <top (required)>'

```

**Comment by sescobb27** [comment] 2015-11-03 01:33
I think is bullet related
https://stackoverflow.com/questions/33297134/stack-level-too-deep-on-creation
https://stackoverflow.com/questions/33134224/how-can-i-correct-a-systemstackerror-stack-level-too-deep-on-habtm-relations

**Comment by pixeltrix** [comment] 2015-11-03 08:43
Yep, there's a comment on the second link that it's been fixed by a recent commit to Bullet - if it's not been released yet I suggest trying the master branch to see if that fixes your problem.

**Closed by pixeltrix** 2015-11-03 08:43 UTC
