### ISSUE TITLE
PG::SyntaxError on query serialize in Rails 7.2

### ISSUE THREAD

**Issue by vitalinfo** [rails/rails#52643] opened 2024-08-18 16:14 UTC
### Description
Problem with serialization sql query with string condition and `nil` bind value with PostgreSQL adapter (it does work with sqlite3) 

### Steps to reproduce
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

db_config = { adapter: 'postgresql', database: 'test', host: 'localhost' }
ActiveRecord::Tasks::DatabaseTasks.create(db_config)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'test')
ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    user1 = User.create!(name: 'John Doe')
    user2 = User.create!

    assert_equal user1, User.find_by('LOWER(name) = ?', 'john doe')
    assert_equal nil, User.find_by('LOWER(name) = ?', 'jane doe')
    assert_equal user2, User.find_by('LOWER(name) IS ?', nil)
  end
end
```

### Expected behavior
Serialize query with `LOWER(name) IS NULL` condition

### Actual behavior
```
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "$1"
LINE 1: ...LECT "users".* FROM "users" WHERE (LOWER(name) IS $1) LIMIT ...
```

### System configuration
**Rails version**:
Rails 7.2.0
**Ruby version**:
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]

**Comment by maniSHarma7575** [comment] 2024-08-19 03:38
Using `git bisect`

https://github.com/rails/rails/commit/8e6a5deca626c944933211d7977f4e7e76869e74 is the first bad commit

Rails version: ">=v7.2.0" introduced the bug.

**Comment by maniSHarma7575** [comment] 2024-08-19 03:49
With MySQL and Sqlite3 functionality is working as expected.

**Comment by maniSHarma7575** [comment] 2024-08-19 05:03
The following line is giving different SQL

https://github.com/rails/rails/blob/16882b886e245f363cd61f5ea553fe2bc525d070/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L34

**Before**
```ruby
"SELECT \"users\".* FROM \"users\" WHERE (LOWER(name) IS NULL) LIMIT $1"
```

**>=7.2.0**

```ruby
"SELECT \"users\".* FROM \"users\" WHERE (LOWER(name) IS $1) LIMIT $2"
```

`arel_or_sql_string` value is

**Before**

```ruby
#<Arel::Nodes::SelectStatement:0x0000000137892370 @cores=[#<Arel::Nodes::SelectCore:0x00000001374bed98 @source=#<Arel::Nodes::JoinSource:0x00000001528350b0 @left=#<Arel::Table:0x00000001209f01e8 @name="users", @klass=User(id: integer, name: string), @type_caster=#<ActiveRecord::TypeCaster::Map:0x0000000150752528 @klass=User(id: integer, name: string)>, @table_alias=nil>, @right=[]>, @set_quantifier=nil, @optimizer_hints=nil, @projections=[#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x00000001209f01e8 @name="users", @klass=User(id: integer, name: string), @type_caster=#<ActiveRecord::TypeCaster::Map:0x0000000150752528 @klass=User(id: integer, name: string)>, @table_alias=nil>, name="*">], @wheres=[#<Arel::Nodes::Grouping:0x0000000152834a48 @expr="LOWER(name) IS NULL">], @groups=[], @havings=[], @windows=[], @comment=nil>], @orders=[], @limit=#<Arel::Nodes::Limit:0x00000001528349a8 @expr=#<ActiveModel::Attribute::WithCastValue:0x00000001378922d0 @name="LIMIT", @value_before_type_cast=1, @type=#<ActiveModel::Type::Value:0x00000001506bdea0 @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil>>, @lock=nil, @offset=nil, @with=nil>
```

**>=7.2.0**
```ruby
#<Arel::Nodes::SelectStatement:0x00000001347b89e8 @cores=[#<Arel::Nodes::SelectCore:0x0000000123d54a70 @source=#<Arel::Nodes::JoinSource:0x00000001342dd090 @left=#<Arel::Table:0x00000001350fdf30 @name="users", @klass=User(id: integer, name: string), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00000001340fb330 @klass=User(id: integer, name: string)>, @table_alias=nil>, @right=[]>, @set_quantifier=nil, @optimizer_hints=nil, @projections=[#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x00000001350fdf30 @name="users", @klass=User(id: integer, name: string), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00000001340fb330 @klass=User(id: integer, name: string)>, @table_alias=nil>, name="*">], @wheres=[#<Arel::Nodes::BoundSqlLiteral "(LOWER(name) IS ?)" [nil]>], @groups=[], @havings=[], @windows=[], @comment=nil>], @orders=[], @limit=#<Arel::Nodes::Limit:0x00000001342dca00 @expr=#<ActiveModel::Attribute::WithCastValue:0x00000001347b88f8 @name="LIMIT", @value_before_type_cast=1, @type=#<ActiveModel::Type::Value:0x0000000134331960 @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil>>, @lock=nil, @offset=nil, @with=nil>
```

**Comment by byroot** [comment] 2024-08-19 06:47
After a quick search it appears that Postgresql don't support `"IS $1", [nil]`. It worked previously because these fragments where eagerly interpolated rather than properly prepared.

I think I can restore that behavior when the bound value is NULL, but, even if I know the example is contrivied for reproduction purposes, given that the only valid value to pass to `"name is ?"` is `nil`, I'd require that code to just not take a parameter.

**Comment by byroot** [comment] 2024-08-19 07:14
> I think I can restore that behavior when the bound value is NULL

Actually, I'm afraid I can't. The problem isn't the bound value, it's the query itself, and parsing the query would be too unreliable. 

I get how this is a bit of a regression in your specific case, but the advantages far out-weight that one case. So I'll be closing as wontfix, but if someone has an idea how to handle this case, feel free to open a PR.

Sorry.

**Closed by byroot** 2024-08-19 07:14 UTC

**Comment by noctivityinc** [comment] 2024-09-07 14:37
Im having the same issue with things like:

```
scope :completed, -> { where("completed_at IS NOT ?", nil) }
scope :uncompleted, -> { where("completed_at IS ?", nil) }
```

Both worked fine in 7.1

**Comment by byroot** [comment] 2024-09-07 17:10
Any reason not do use ? :

```ruby
scope :completed, -> { where.not(completed_at: nil) }
scope :uncompleted, -> { where(completed_at: nil) }
```

**Comment by noctivityinc** [comment] 2024-09-07 18:11
@byroot its an excellent question. Short answer - no.  the rest of my scopes are like that.  Something tells me it was some legacy code.  Regardless, it still should support it.

**Comment by joshmrallen** [comment] 2024-09-08 13:51
I should probably have clarified in my comment above that we had a complex query that if refactored to use the `where.and`, `where.not`, `where.or` methods with a `joins`. The result would been a `where.or` that threw an error because the relations passed were not [structurally compatible](https://github.com/rails/rails/blob/e1d58cfd05ae1cc0bfc1006b7ce973a7730831df/activerecord/lib/active_record/relation/query_methods.rb#L1155).

**Comment by byroot** [comment] 2024-09-08 13:55
I understand this breaking change is annoying, but it is a Postgresql limitation, and there is no realistic way to work around it without lossing everything we've gained with this change.

What I don't quite understand though, is that unless I'm mistaken, the only valid valid for a `IS` is `NULL`. So I don't understand the need to parametise it at all.

Like how is:

```ruby
User.where('LOWER(name) IS ?', Arel.sql("NULL"))
```

Any better than just:

```ruby
User.where('LOWER(name) IS NULL')
```

Are you ever passing anything else than `NULL`?

**Comment by joshmrallen** [comment] 2024-09-08 14:15
True, but since we use parameters with other calls to keep with convention and avoid injection attacks, we kept the same form here as well.

But that leads me to the next question: Could using a full string without parameters for NULL:
```ruby
User.where('LOWER(name) IS NULL')
```
open up an app to injection attacks?

**Comment by byroot** [comment] 2024-09-08 14:16
> open up an app to injection attacks?

No.

**Comment by patleb** [comment] 2024-12-29 14:31
@byroot

> What I don't quite understand though, is that unless I'm mistaken, the only valid valid for a IS is NULL.

`FALSE, TRUE and UNKNOWN` are also valid values. This could be used for a boolean as a three-state value.

**Comment by byroot** [comment] 2024-12-29 14:41
TIL
