### ISSUE TITLE
ActionCable not working in recent versions of Safari when connecting via WSS

### ISSUE THREAD

**Issue by sergelerator** [rails/rails#43835] opened 2021-12-10 20:04 UTC
This issue was previously reported here: https://github.com/rails/rails/issues/39104 but was dismissed by the author because they found a workaround.

**Disclaimer:** This seems to be a bug with Safari's default WebSocket client (NSURLSession WebSocket) in recent versions (15.1+ at least), but there could be something ActionCable can do to mitigate this issue.

Some references:
- Report in Apple Forums about the bug in NSURLSession WebSocket: https://developer.apple.com/forums/thread/685403
- Another report on Safari changing the default WebSocket client: https://github.com/wandenberg/nginx-push-stream-module/issues/295
- Discussion about supporting the permessage-deflate extension: https://discuss.rubyonrails.org/t/permessage-deflate-support-in-actioncable/73102

Relevant highlights:

- > This error is caused by NSURLSession’s inability to process split messages normally. As long as the received WebSocket Message Frame is Fin=0, an error will occur. Our team adjusted the WebSocket Server configuration in the production environment to solve this problem.
- > We faced error WebSocket connection to 'wss:****' failed: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 100 - Protocol error) with big websocket messages on iOS15 (production, not beta) if server responds with "Sec-WebSocket-Extensions: permessage-deflate; server_no_context_takeover; client_no_context_takeover", if there are no such headers or if message very small then all works fine. Maybe there is a bug with websockets compression in WKWebView
- > Disabling "NSURLSession WebSocket" resolves the issue.

### Steps to reproduce

Using Safari, make sure your Websocket client is set to "NSURLSession WebSocket":
![image](https://user-images.githubusercontent.com/1591869/145631326-8630b1a1-6066-416e-9956-49f6fb38c488.png)

This "NSURLSession WebSocket" experimental feature is turned on by default in Safari 15.1

I followed the same steps mentioned in [this comment](https://github.com/rails/rails/issues/39104#issuecomment-622979107) in the previously linked issue, but used an ngrok tunnel with an HTTPS endpoint instead of a normal HTTP endpoint. Please note that, if you connect to the WebSocket server via HTTP (WS) instead of HTTPS (WSS), the issue is not present.

Based on the referenced articles above, I also tried manually adding the `PermessageDeflate` extension to `ClientSocket` instances:

```rb
# config/initializers/websockets.rb
module ClientSockerExtensions
  def initialize(*args)
    super(*args)
    @driver.add_extension(PermessageDeflate)
  end
end

module ActionCable
  module Connection
    class ClientSocket
      prepend ClientSockerExtensions
    end
  end
end
```

Including the initializer above did not change the outcome.

### Expected behavior

The "Connected" alert should be displayed when visiting the test site, and a successful WSS connection should be visible

### Actual behavior

The "Connected" alert is not displayed, an infinite loop of failed attempts to establish a WebSocket connection.

### System configuration
**Rails version**: 6.1.4.1
**Ruby version**: 2.6.4

### Additional information

To be clear, this seems to be a bug with Safari's now default WebSocket client, but ActionCable alternatives such as Socket.io don't have this issue, which leads me to believe that the WebSocket's server might be able to mitigate this shortcoming in NSURLSession WebSocket.

With Safari 15 being the default in MacOS Monterey, an increasing number of users will be facing this issue.

**Comment by ghiculescu** [comment] 2021-12-13 20:50
Thanks for the report. Do you have any idea at all how Socket.io would be working around this?

It looks like it could be a concerning problem (particularly if this becomes the default on iOS too) so any ideas around how to fix it are welcome.

**Comment by sergelerator** [comment] 2021-12-14 19:31
Thanks for following up.

> Do you have any idea at all how Socket.io would be working around this?

I haven't been able to put more time into this, I have a couple vague ideas:

- The WS server might be handling the permesage-deflate request in a way that is compatible with the current shortcomings in NSURLSession WebSocket, based on what I can recollect from the linked discussions, the lead I would follow is to prevent splitting messages server side.
- Socket.io's WebSocket client doesn't seem to use the vanilla implementation of the browser's `WebSocket` constructor, and they also have fallbacks to use different transports (e.g. the `XMLHttpRequest` constructor or a polling strategy): https://github.com/socketio/engine.io-client/tree/master/lib/transports

Unfortunately, I'm not very knowledgeable to go deeper into this issue and attempt a fix, but I'd be glad to contribute in any way I can.

**Comment by jorgemanrubia** [comment] 2021-12-14 23:33
I can confirm we've experienced this problem. It was reported to Webkit [here](https://bugs.webkit.org/show_bug.cgi?id=228296#c22). That same person suggested a workaround in that thread:

```javascript
document.addEventListener('visibilitychange', () => {
  if (document.visibilityState === 'hidden') {
    cable.disconnect()
  } else {
    cable.connect()
  }
})
```

We've been testing that workaround and, while we observed an improvement, it didn't fix the problem for good for us. We are still looking for a good solution here.

**Comment by kriszabala** [comment] 2021-12-15 05:37
We're experiencing the same issues with WSS in a webview in iOS 15. Did some tests with other websocket servers and if  permessage-deflate is enabled on the server, the socket will disconnect upon the client sending a message > ~1024 bytes. Disabling permessage-deflate on the server allows the message to be sent without disconnecting. @sergelerator mentioned manually adding the permessage-deflate extension to ClientSocket, which is supposed to enable the extension, but it seems it is already enabled by default. I think we need to do the opposite and disable it until Apple fixes it on their end. As a workaround, is there a way to disable this extension in ActionCable? On other servers (WebSocketSharp) the way to disable it is specifying an `ignore extensions` option. Maybe there's something similar for ActionCable?

**Comment by kriszabala** [comment] 2021-12-17 15:27
Any leads on how to disable permessage-deflate extension in ActionCable? Seems to be the easiest workaround until Apple fixes on their end.

**Comment by afcapel** [comment] 2021-12-17 18:24
@kriszabala I've [reported this same error to Apple](https://bugs.webkit.org/show_bug.cgi?id=228296#c34). It seems there's a bug in their websocket implementation.

AFAIK ActionCable doesn't enables `permessage-deflate` by default. Maybe is your load balancer the one adding the extension?

**Comment by seven1m** [comment] 2021-12-17 20:06
FYI we're getting early reports this may have been fixed in Safari. https://github.com/wandenberg/nginx-push-stream-module/issues/295#issuecomment-996940057

**Comment by jorgemanrubia** [comment] 2021-12-28 21:28
We found another problem in recent Safari versions. I [reported it to Safari here, along with a snippet to reproduce](https://bugs.webkit.org/show_bug.cgi?id=228296#c38). Essentially, when closing a websocket in a `connecting` state, it can happen that the websocket system gets completely borked, requiring a browser/app restart to fix (not just a reload). Another action cable user [reported suffering apparently the same problem earlier in that thread](https://bugs.webkit.org/show_bug.cgi?id=228296#c22). 

Action Cable's monitoring system can try to close sockets while in a "connecting" state and can trigger this bug.

We are using using this patch for now, which essentially monkey-patch Websocket to avoid closing sockets in that `connecting` state. 

```js
const originalWebSocketClose = WebSocket.prototype.close
WebSocket.prototype.close = function () {
  if (this.readyState != WebSocket.CONNECTING) {
    originalWebSocketClose.apply(this, arguments)
  }
}
``` 

We hope Apple gets this fixed asap but who knows. We can look into upstreaming a better patch into Action Cable (e.g: not closing connections in a "connecting" state there, without monkey-patching anything). I'm curious if more people are hitting this problem.

This is another bug in the new NSURLSession Websockets implementation. It's different to the one about using compression mentioned above (permessage-deflate extension), which doesn't impact Action Cable that much since it doesn't enable compression by default.

**Comment by grncdr** [comment] 2022-01-17 16:23
> I'm curious if more people are hitting this problem.

Fairly certain I encountered this today, and it was extremely confusing. It wasn't until I read your comment that I tried restarting Safari, which cleared it up immediately.

**Comment by jorgemanrubia** [comment] 2022-02-02 16:03
We upstreamed [the patch into ActionCable](https://github.com/rails/rails/pull/44304). We still have no clue if/when Apple is going to fix this.

**Closed** 2022-02-03 14:52 UTC
Labels: actioncable

**Comment by krisdigital** [comment] 2022-02-10 23:54
@jorgemanrubia Thank you for the patch, I had also noticed the errors for some time! Maybe dumb question, do you know if this patch will also arrive in Rails 6 or 6.1, or will it only come to Rails 7?
The Monkey Patch from above does not work for me sadly - the console errors are gone, but the connection does not succeed. Firefox works. Interestingly in the local dev environment it even works in Safari 🤔 The only difference I can spot is the nginx in between, but that has always been there 🤔🤔

**Comment by krisdigital** [comment] 2022-02-11 01:38
I am probably late to the party, but I had this bug and just installed macOS 12.2.1 and it is working again 🎉

**Comment by acetinick** [comment] 2022-02-21 10:42
We are experiencing this issue with more and more of our customers.  @dhh is this fix something we can hotfix in the 6.x branch?

**Comment by dhh** [comment] 2022-02-21 12:21
Yes, you can just grab the JS out of the branch of Rails you're using, make [the one-line change](https://github.com/basecamp/rails/blob/974329585fff58373c85df9ca3bf221dde63ce43/actioncable/app/assets/javascripts/action_cable.js) and put the result in vendor, and then include that instead of the framework version.

**Comment by acetinick** [comment] 2022-02-21 12:35
Cool will give a go, thx
