### ISSUE TITLE
Attributes API: Accessing attribute not backed by database column on persisted records raises `ActiveModel::MissingAttributeError`

### ISSUE THREAD

**Issue by doits** [rails/rails#25809] opened 2016-07-13 10:48 UTC
### Steps to reproduce

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '5.0.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  attribute :completed, :boolean
end

class BugTest < Minitest::Test
  def test_attribute_api_works_with_new_record
    post = Post.new
    assert_equal nil, post.completed
  end

  def test_attribute_api_works_with_find
    Post.create!
    post = Post.find(1)

    assert_equal nil, post.completed
  end

  def test_new_record_attributes_include_completed
    post = Post.new
    assert_includes post.attributes.keys, 'completed'
  end

  def test_found_record_attributes_include_completed
    Post.create!
    post = Post.find(1)

    assert_includes post.attributes.keys, 'completed'
  end
end
```

### Expected behavior
In [the doc](http://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html) it says:

> Attributes do not need to be backed by a database column.

So: `post.completed` should always work, even if the record is fetched from database.

### Actual behavior
`ActiveModel::MissingAttributeError` for objects which are fetched with `#find` from database.

### System configuration
**Rails version**:
5.0.0

**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by maclover7** [comment] 2016-07-15 17:18
Thank you for opening this issue! Closing as a duplicate of #25787. #25841 should hopefully fix this.

**Closed by maclover7** 2016-07-15 17:18 UTC
Labels: activerecord
