### ISSUE TITLE
Rails 7.x after_destroy not triggered when a before_create on associated model is defined

### ISSUE THREAD

**Issue by devsheva** [rails/rails#50782] opened 2024-01-17 16:26 UTC
### Steps to reproduce

Prerequisites
- [stateful_enum](https://github.com/amatsuda/stateful_enum)
- rspec

```ruby

ORDER_MAX_ITEMS = 100

# == Schema Information
#
# Table name: orders
#
#  id                   :integer          not null, primary key
#  code                 :string
#  cart_user_id         :string
#  status               :integer
#  customer_id          :integer
#  invoice_profile_id   :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  expiration_timestamp :datetime
#  payment_datetime     :datetime
#  payment_method_id    :string
#  payment_method_type  :string
#  error_info           :json
#
class Order < ApplicationRecord
  ### Associations ###
  has_many :order_items, dependent: :destroy, autosave: true

  ### Enums ###
  enum status: {expired: 5 } do
 
    event :expire do
      before { self.order_items = [] }
      transition all - [:paid, :cancelled] => :expired
    end

  end


  def check_max_order_items_reached
    if order_items.size == ORDER_MAX_ITEMS
      raise Error::CustomError.new(
        "order.check_max_order_items_reached.reached",
        422,
        "Maximum Order items reached"
      )
    end
  end

 
end



# == Schema Information
#
# Table name: order_items
#
#  id                 :integer          not null, primary key
#  order_id           :integer          not null
#  status             :integer
#  product_code       :integer
#  itemable_type      :string
#  itemable_id        :integer
#  price              :float
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  is_executed        :boolean
#  execution_datetime :datetime
#  dns_setup          :integer
#  apply_to_all       :boolean
#  template_dns       :integer
#  amount_tax         :float
#  vat                :integer
#
class OrderItem < ApplicationRecord
  delegate(:check_max_order_items_reached, to: :order)

  ### Associations ###
  belongs_to :order
  belongs_to :itemable, polymorphic: true, optional: true

  # 
  before_create :check_max_order_items_reached
  after_destroy :destroy_associated_records

end

```

### Expected behavior
It should trigger after_destroy as expected

### Actual behavior
It doesn't trigger the after_destroy in OrderItem model after I've added the before_create callback.

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.1.3

**Comment by devsheva** [comment] 2024-01-17 16:57
EDIT: using `count` instead of `size` works, but can't explain why

**Comment by Edouard-chin** [comment] 2024-01-17 21:22
I can't reproduce. Can you tweak this bug template to reproduce the problem?

<details>
<summary> Bug template </summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :orders, force: true do |t|
  end

  create_table :order_items, force: true do |t|
    t.integer :order_id
  end
end

class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
end

class OrderItem < ActiveRecord::Base
  attr_accessor :after_destroy_called

  belongs_to :order

  before_create :before_create_callback
  after_destroy :after_destroy_callback

  private

  def before_create_callback
  end

  def after_destroy_callback
    @after_destroy_called = true
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    order = Order.new
    order_item = OrderItem.new
    order.order_items << order_item
    order.save!

    assert_nil(order_item.after_destroy_called)

    order.destroy!
    assert(order_item.after_destroy_called)
  end
end
```
</details>

**Comment by devsheva** [comment] 2024-01-17 23:25
@Edouard-chin now you can reproduce the problem

<details>
  <summary>Bug Template </summary>

  ```ruby
   # frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
	source "https://rubygems.org"

	git_source(:github) { |repo| "https://github.com/#{repo}.git" }

	gem "rails"
	# If you want to test against edge Rails replace the previous line with this:
	# gem "rails", github: "rails/rails", branch: "main"

	gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
	create_table :orders, force: true do |t|
		t.integer :status
	end

	create_table :order_items, force: true do |t|
		t.integer :order_id
	end
end

class Order < ActiveRecord::Base
	attr_accessor :before_create_called

	has_many :order_items, dependent: :destroy, autosave: true

	enum status: {pending: 0, expired: 1}

	
	def expire!
		self.order_items = []
		self.status = :expired
		self.save!	
	end

	def before_create_callback
		@before_create_called = true
		if order_items.size == 100
			raise "max order items reached"
		end
	end
end

class OrderItem < ActiveRecord::Base
	attr_accessor :after_destroy_called

	delegate(:before_create_callback, to: :order)

	belongs_to :order

	before_create :before_create_callback
	after_destroy :after_destroy_callback

	private

	def after_destroy_callback
		@after_destroy_called = true
	end
end

class BugTest < Minitest::Test
	def test_association_stuff
		order = Order.create!(status: :pending)
		order_item = OrderItem.create!(order:)

		order.expire!

		assert(order.before_create_called)
		assert_empty(order.order_items)

		assert_nil(order_item.after_destroy_called)	
		assert(order_item.after_destroy_called)

		assert_equal(0, OrderItem.count)
	end
end
   ```
</details>

**Comment by Edouard-chin** [comment] 2024-01-17 23:34
You aren't destroying any records in your bug report 🤔 , so it's normal the after_destroy callback doesn't get called.

**Comment by devsheva** [comment] 2024-01-17 23:40
@Edouard-chin try to replace size with count, and you'll see that a destroy on associated records will be applied. 

Reference to [Associations Guide](https://guides.rubyonrails.org/association_basics.html#methods-added-by-has-many-collection-objects)
The `collection=` method makes the collection contain only the supplied objects, by adding and deleting as appropriate. The changes are persisted to the database.

**Comment by iamradioactive** [comment] 2024-01-18 18:34
Issue is valid but it has little to do with callbacks. The records are not being deleted even if `dependent: :destroy` is set.

It can be reproduced using this script

<details>
<summary>Reproduction Script</summary>

```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"

  gem "sqlite3"
  gem "pry"
end

require "active_record"
require "minitest/autorun"
require "logger"
 
# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
 
ActiveRecord::Schema.define do
  create_table :orders, force: true do |t|
    t.integer :status
  end
 
  create_table :order_items, force: true do |t|
    t.integer :order_id
  end
end
 
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  
  enum status: {pending: 0, expired: 1}

  def expire!
    self.order_items = []
    self.status = :expired
    self.save!	
  end
end
 
class OrderItem < ActiveRecord::Base
  belongs_to :order
end
 
class BugTest < Minitest::Test
  def test_association_stuff
    order = Order.create!(status: :pending)
    # OrderItem.create!(order: order)
    order.order_items.size
    OrderItem.create!(order: order)
    order.expire!

    assert_equal(0, OrderItem.count)
   end
 end
```
</details>

The reason why it happens is because the size method internally uses [count_records](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/associations/has_many_association.rb#L90) method which sets the `loaded` flag to true when there are no associated records. 

Reference: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/associations/has_many_association.rb#L90

I'm not sure why the loaded flag is set to true only in cases when the count is 0, maybe for Optimization purposes. Will dig further into the issue.

**Comment by devsheva** [comment] 2024-01-18 20:26
@iamradioactive Thank you for the explanation, I wouldn't have got the answer this fast.

**Comment by Edouard-chin** [comment] 2024-01-18 23:50
Thanks @iamradioactive , I see now. 

The problem is because the association on the `belongs_to` side can't find the inverse of the other relation. It's a known bug reported in https://github.com/rails/rails/issues/49574

You can workaround the problem by explicitly setting the inverse of. Here is the patch to make the bug report work

```diff
diff --git a/bug_report.rb b/bug_report.rb
index 93ab214..8393963 100644
--- a/bug_report.rb
+++ b/bug_report.rb
@@ -19,6 +19,7 @@ require "logger"
 # This connection will do for database-independent bug reports.
 ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
 ActiveRecord::Base.logger = Logger.new(STDOUT)
+ActiveRecord::Base.has_many_inversing = true # No need for this in a Rails 6+ application. It is set by default.

 ActiveRecord::Schema.define do
   create_table :orders, force: true do |t|
@@ -43,7 +44,7 @@ class Order < ActiveRecord::Base
 end

 class OrderItem < ActiveRecord::Base
-  belongs_to :order
+  belongs_to :order, inverse_of: :order_items
 end

 class BugTest < Minitest::Test

```

**Comment by devsheva** [comment] 2024-01-20 17:52
Had to put also this code `ActiveRecord::Base.has_many_inversing = true`, cause is not set default true as the comment explains for Rails 6+

**Comment by Edouard-chin** [comment] 2024-01-21 22:09
> Had to put also this code `ActiveRecord::Base.has_many_inversing = true`, cause is not set default true as the comment explains for Rails 6+

Maybe your application hasn't called `config.load_defaults(6.0)` (where `6.0` can be any valid rails version `>= 6.0`)

**Comment by Edouard-chin** [comment] 2024-01-21 22:10
Closing since #50284 resolved the issue. Thank you for reporting it ❤️ !

**Closed by Edouard-chin** 2024-01-21 22:10 UTC
