### ISSUE TITLE
Bug with namespaced ActiveRecord models on 4.1.x (PostgreSQL)

### ISSUE THREAD

**Issue by thelucid** [rails/rails#15811] opened 2014-06-19 14:37 UTC
I've come up against a bug with ActiveRecord when using namespaces models and polymorphic associations, it's a common use-case so should probably be fixed before a 4.2 release.

Error:

```
NoMethodError: undefined method `relation_delegate_class' for Comment:Module
```

Example:

``` ruby
class Post::Base < ActiveRecord::Base
  self.table_name = 'posts'
end

class Post::Special < Post::Base
  has_many :comments, as: :commentable
end

class Comment::Base < ActiveRecord::Base
  self.table_name = 'comments'
  belongs_to :commentable, polymorphic: true
end

class Comment::Special < Comment::Base
end

Post::Special.first.comments

# => NoMethodError: undefined method `relation_delegate_class' for Comment:Module
```

**Comment by adiakritos** [comment] 2017-07-10 23:12
To be more precise for others who try @frenkel 's method... I found that the class name has to specifically match the model that contains `polymorphic: true`. I was thrown off for about an hour with the '::classname' format. 

So in this case you'd write it like this:

```
class Post::Special < Post::Base
  has_many :comments, as: :commentable, class_name: "Comment::Base"
end
```

Not sure if he's trying to accomplish something different from me, but this makes namespaced models work with polymorphism work for me.

**Comment by shrirambalakrishnan** [comment] 2017-08-05 11:56
@matthewd I will work on this.

**Comment by tiagonbotelho** [comment] 2017-09-25 23:14
@shrirambalakrishnan are you working on this? If not can I start working on it? Thanks 😄

**Comment by shrirambalakrishnan** [comment] 2017-09-26 00:40
@tiagonbotelho I am not working on this. You can start with this.

**Comment by tiagonbotelho** [comment] 2017-09-26 20:50
@rafaelfranca could you point me to the code snippet where:

> When trying to find possible candidates for the class of your association called comments Rails tries to find inside the current class, inside the parent module and inside the global scope. So the candidates for this case would be: ["Post::Special::Comment", "Post::Comment", "Comment"]

happens?

I also assume that checking if the candidate is an Active Record model is just `candidate.is_a?(ActiveRecord::Base)` or do we already have a method in place for that?

It is my first time contributing so sorry in advance if they are bad questions 😄 

Thanks!

**Comment by tiagonbotelho** [comment] 2017-10-02 18:55
Ok so I was able to track down where we pick the candidates (https://github.com/rails/rails/blob/master/activerecord/lib/active_record/inheritance.rb#L143) however I am not being able to find where we actually check if a candidate is a Active Record model

**Comment by al2o3cr** [comment] 2017-10-09 15:54
@tiagonbotelho I don't believe there's currently a check - that's the cause of the original error report; the search finds `Comment` (a module) but assumes it is a model.

**Comment by tiagonbotelho** [comment] 2017-10-09 16:10
Thanks @al2o3cr I created a comment https://github.com/rails/rails/pull/30778/files#r143513045 where I propose a possible solution to the "Checking if the object is a active record model"

Also could you provide me the example you mentioned from `ActiveHash` if possible?

**Comment by saveriomiroddi** [comment] 2018-01-30 20:24
@rafaelfranca I've provided my proposed fix in #31829.

**Comment by vedant1811** [comment] 2018-05-05 22:00
Is this still open? Can I pick it up?

**Comment by saveriomiroddi** [comment] 2018-05-08 18:57
> Is this still open? Can I pick it up?

@vedant1811 hello! there are two PRs for this issue, one incomplete and another possibly/likely complete ([mine](https://github.com/rails/rails/pull/31829)). since the feedback cycle died on mine, I've closed it, but feel free to rip it off and improve it as you please; it's for the community's sake, anyway.

**Comment by schneems** [comment] 2018-07-17 20:57
Is this still an issue with master? We wouldn’t accept a backport for Rails 4.1 at this time.

**Comment by ngetahun** [comment] 2018-09-26 11:04
Is this issue up for grabs? I would like to make my first PR to the project

**Comment by Dean-Coakley** [comment] 2018-10-04 11:43
@ngetahun Looks like https://github.com/rails/rails/pull/30778 should fix it but is awaiting review. It's quite old/inactive though, not sure if new PR should be opened. 😕

**Comment by Schwad** [comment] 2020-11-02 15:56
So it looks like this is the only issue on the Rails repository with the __good first issue__ label. 

If anyone comes here and wants to take a crack at it, @eileencodes has indicated that the best candidate to fix this and get merged is this PR by @tiagonbotelho:  https://github.com/rails/rails/pull/30778

This PR was closed a few months ago due to being stale (unfortunately ☹️ ). It does appear that the Rails-Core team would *like* a test with the implementation.

Anyone looking to pick this up ( @ngetahun ? ) that might be your best bet.

If you're new to Rails and unsure how to approach the testing side of things, Eileen's talk [here](https://www.youtube.com/watch?v=7zoD6NZy6vY) should be more than enough to get you rolling.

**Comment by intrip** [comment] 2020-12-09 10:44
@rafaelfranca I'd like to pickup #30778 and work on it.

**Comment by rafaelfranca** [comment] 2020-12-09 17:19
Yes!

**Comment by intrip** [comment] 2020-12-14 14:04
@rafaelfranca I've created https://github.com/rails/rails/pull/40836 which should introduce a better error for this scenario.

**Closed** 2020-12-16 22:44 UTC
Labels: activerecord, good first issue, pinned
