### ISSUE TITLE
Dead Link On ActiveRecord Readme

### ISSUE THREAD

**Issue by PAMulligan** [rails/rails#33233] opened 2018-06-27 03:50 UTC
### Steps to reproduce

Visit https://github.com/rails/rails/blob/master/activerecord/README.rdoc and click on the "Learn More" link (https://github.com/rails/rails/blob/master/activerecord/classes/ActiveRecord/Base.html).

### Expected behavior
Render a page with more information about ActiveRecord

### Actual behavior
Render 404 page

### System configuration
**Rails version**: N/A

**Ruby version**: N/A

**Comment by y-yagi** [comment] 2018-06-27 04:18
Duplicate of #28256. 
Please see https://github.com/rails/rails/issues/28256#issuecomment-283758826 for a detailed explanation.

**Closed by y-yagi** 2018-06-27 04:18 UTC
