### ISSUE TITLE
DateTime range `include?` returns wrong output (or so I think)

### ISSUE THREAD

**Issue by apneadiving** [rails/rails#30799] opened 2017-10-04 13:06 UTC
### Steps to reproduce
```ruby
ref = DateTime.now
ts1 = (ref - 1.hour)..(ref + 1.hour)
ts2 = (ref)..(ref + 1.hour)
ts1.include? ts2.first
> false
```
### Expected behavior
`ts1.include? ts2.first` should return `true`

### Actual behavior
`ts1.include? ts2.first` returns `false`

### Side notes
Interestingly enough, if you use `Time` instead of `DateTime`, it works as expected.

With Ruby only, it does not work...
```ruby
require 'date'
ref = DateTime.now
ts1 = (ref - Rational(3600, 86400))..(ref + Rational(3600, 86400))
ts2 = (ref)..(ref + Rational(3600, 86400))
ts1.include? ts2.first
> false
```

### System configuration
**Rails version**: 5.1.3
**Ruby version**: 2.4.2

**Comment by nicolasblanco** [comment] 2017-10-04 14:17
On your use case `Range#include?` does not return what you expect simply because a range of two DateTimes is *not* converted to an array containing all the dates with a granularity of a second.

You need to use `Range#cover?` to check if a value is between your range of two DateTimes.

**Comment by apneadiving** [comment] 2017-10-04 14:27
`cover?` works but... the whole point is to do something like: `ts1.include?(ts2)`.

ActiveSupport extends `include?` properly to check range to range. Internally it checks: `ts1.include?(ts2.first) && ts1.last >= ts2.last`.

So it fails because of the `include?`...

What is also confusing is that it works with Time but not DateTime.

**Comment by nicolasblanco** [comment] 2017-10-04 14:37
@apneadiving : have a look at:
https://github.com/rails/rails/blob/v5.1.4/activesupport/lib/active_support/core_ext/range/include_range.rb

`Range#include?` is only extended in `ActiveSupport` to support a `Range` as a parameter. If something different than a `Range` is passed, the original behaviour is applied.

**Comment by apneadiving** [comment] 2017-10-04 14:42
@nicolasblanco indeed this is what I describe :) it works fine with Time but not with DateTime.

**Comment by nicolasblanco** [comment] 2017-10-04 14:56
@apneadiving 

About your question on why you have a different behaviour between a range of DateTimes and a range of Times:

Ruby has a customized way of dealing with a range of Times. For this reason, you cannot convert a range of Times to an array:

    (Time.now..3.hours.from_now).to_a
    #=> TypeError: can't iterate from Time

But you can convert a range of DateTimes to an array:

    (DateTime.now..(DateTime.now + 3.days)).to_a
    #=> [Wed, 04 Oct 2017 16:49:43 +0200, Thu, 05 Oct 2017 16:49:43 +0200, Fri, 06 Oct 2017 
    16:49:43 +0200, Sat, 07 Oct 2017 16:49:43 +0200]

As you see, when converting a range of DateTimes to an array, Ruby has a granularity of 1 day between each DateTime.

That's why you don't have the expected behaviour when using `Range#include?` with DateTime values...

**Comment by apneadiving** [comment] 2017-10-04 15:03
The whole point of my issue is questionning the inconsistency of what `include?` returns between Time and DateTime. 
Hopefuly it would be considered as a legitimate request.

**Comment by al2o3cr** [comment] 2017-10-04 15:18
Looks like `DateTime` should be considered a "linear object" like `Time` and `Numeric` are in this patch:

https://bugs.ruby-lang.org/issues/11113

Since it isn't, the default `include?` implementation from `Enumerable` gets used. The default behavior of `Range` performs `each` using `succ`, which increments a `DateTime` by a full day. :(

**Comment by pixeltrix** [comment] 2017-11-07 10:25
The issue with `DateTime` ranges should be fixed in Ruby itself by removing the `succ` method and making `include?` use `cover?` like core Ruby does for floats. However `ActiveSupport::TimeWithZone` does not have a `succ` method but `include?` doesn't work because the linear object check is coded to a fixed set of core types - this we can fix in Active Support.

**Closed** 2017-11-09 13:52 UTC
