### ISSUE TITLE
select adding limit on query but not in database on sqlite and mysql

### ISSUE THREAD

**Issue by ganesh111023** [rails/rails#30497] opened 2017-09-01 12:57 UTC
## Steps to reproduce
Run query
Company.select(:id, :name)   see logs and data

### Expected behavior
Select query add LIMIT 11 to each query in sqlite and mysql database but it is not applying on database lavel. I got all record of table but logs show me limit 11.
Company.select(:id, :name)
SELECT  `test_development`.`companies`.`id`, `test_development`.`companies`.`name` FROM `test_development`.`companies`

### Actual behavior
current behaviour
Company.select(:id, :name)
SELECT  `test_development`.`companies`.`id`, `test_development`.`companies`.`name` FROM `test_development`.`companies` LIMIT 11

### System configuration
**Rails 5.1.1**:

*ruby 2.4.1p111**:

**Comment by tcopeland** [comment] 2017-09-12 19:01
@ganesh111023 what you're seeing here is the behavior of `ActiveRecord::Relation#inspect`; you can see that it only displays the first 11 records here https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L631-L638.

**Comment by sumandroid** [comment] 2017-09-27 06:12
@ganesh111023
I am on Rails 5.0.0
and I ran the following active_record query:
User.select(:id, :name)
and the sql query generated is:
SELECT `users`.`id`, `users`.`name` FROM `users`
as you can see there is no limit either in activerecord query nor in sql query.
and I am using mysql.
Can you specify which rails version you are using?

**Comment by kamipo** [comment] 2017-10-20 15:49
Closing this since `LIMIT 11` is the expected behavior of `Relation#inspect`:

https://github.com/rails/rails/blob/feb0fd0ca91052bbdce8ed67ffa937ecfcf249ec/activerecord/lib/active_record/relation.rb#L537-L544

**Closed by kamipo** 2017-10-20 15:49 UTC

**Comment by drews256** [comment] 2017-12-01 19:25
I am seeing this same thing in some instances and I do not expect inspect to be called. 

Maybe that is my issue, but 

doing 
`Model.where("(some_jsonb ->> 'key') = ?", value ).to_sql`

results in the following

`"SELECT \"models\".* FROM \"models\" WHERE (((some_jsonb ->> 'key') = 'value')` 

as expected

But when executed as `Model.where("(some_jsonb ->> 'key') = ?", value )` I receive the following SQL 

`SELECT  "models".* FROM "models" WHERE ((some_jsonb ->> 'key') = 'value') LIMIT $1  [["LIMIT", 11]]`

Which in my mind feels faulty and inconsistent. Is this expected behavior? 

Ruby 2.4.1 and Rails 5.1.4

**Comment by kamipo** [comment] 2017-12-02 06:56
Yes, as mentioned above, this is the expected behavior of `Relation#inspect`.

**Comment by kwerle** [comment] 2018-02-02 16:55
OK, this left me really confused.  If I specify a limit, I do kind of expect that limit to be used.  I'm guessing there is no way to check the SQL when the .inspect is called and see there is a limit already in place, however?  If there is, I'd like a warning about what's going on.

**Comment by petermumford** [comment] 2018-02-20 10:49
This is confusing. I'm using 5.2.0.rc1 with PostgreSQL and started to see this where it was adding a limit (LIMIT 11) to the end of my queries in the logs. This is still unclear to me why you're doing this?

**Comment by ShadowRadiance** [comment] 2018-04-14 09:07
I think the clarity comes from a number of things working together:

1. When you call `Model.where(...)` you aren't executing a query. You are just defining a scope/relation.
1.1 Usually the query gets executed when you try to iterate over the relation.
2. When you call `Model.where(...)` in the rails console, it returns the Relation and the console will call `Relation#inspect` on the relation for you to have something nice to display.
3. `Relation#inspect` limits the results to 11 so it doesn't send your entire database to your terminal console.
4. You see the query execute with LIMIT 11, and then return value of your call... the "inspected" Relation, which is what caused the query execution, not the call to Model.where(...)

Hope that helps?
