### ISSUE TITLE
create_association method added by has_one throws ArgumentError in some cases

### ISSUE THREAD

**Issue by kevinsapp** [rails/rails#27770] opened 2017-01-22 22:40 UTC
### Steps to reproduce

1. Create two models: Service and SamlServiceProviderMetadatum 
1. ("metadatum" was contrived by the Rails inflector when I used the generator to create the model)
1. SamlServiceProviderMetadatum belongs_to :service
1. Service has_one :saml_service_provider_metadatum
1. Instantiate a Service - i.e. `service = Service.first`
1. Call `service.create_saml_service_provider_metadatum`

### Expected behavior
`service.create_saml_service_provider_metadatum` should create a SamlServiceProviderMetadatum where `service.saml_service_provider_metadatum.service_id == service.id`

### Actual behavior
Rails throws `ArgumentError: wrong number of arguments (given 1, expected 0)`
Note: doing...
`sp = service.build_saml_service_provider_metadatum`
`sp.save`
...works fine

I'm suspicious that there's something going on with the way inflection works, but I'm out of my depth on tracking that down.

### System configuration
**Rails version**: `5.0.0.1`

**Ruby version**: `2.3.3p222`

**Comment by mazharul-monstarlab** [comment] 2017-01-23 06:28
couldn't recreate this issue,

os: Ubuntu 16.04
ruby: 2.3.3p222
rails version: 5.0.0.1

can you provide the stack trace?

**Comment by mithucste30** [comment] 2017-01-23 06:32
couldn't recreate this issue,

os: Ubuntu 16.04
ruby: 2.3.3p222
rails version: 5.0.0.1

can you provide the stack trace?

**Comment by maclover7** [comment] 2017-01-23 22:28
Same deal as @mithucste30, can't reproduce. Tried to make a reproduction script [here](https://gist.github.com/maclover7/010636cdaf7a36b62dc63764b2833abe) but passes for me.

Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by abraham** [comment] 2017-02-01 20:33
Do you have bullet enabled? I ran into a similar error until I disabled bullet.

**Comment by doits** [comment] 2017-02-23 21:12
> Do you have bullet enabled? I ran into a similar error until I disabled bullet.

I second this - bullet with Rails 5.1.0.beta1 causes the same problem for me. Disabling it and it works.

**Comment by abraham** [comment] 2017-03-01 15:46
Bullet just landed a PR that fixed the issue for me. https://github.com/flyerhzm/bullet/pull/326

**Comment by maclover7** [comment] 2017-03-11 19:48
Looks like this was an issue caused bullet, closing since a PR was merged / version released.

**Closed by maclover7** 2017-03-11 19:48 UTC
Labels: activerecord, needs work
