### ISSUE TITLE
Not autoloading custom subdirectories of app

### ISSUE THREAD

**Issue by fubarius** [rails/rails#24969] opened 2016-05-11 08:27 UTC
### Steps to reproduce

Add app/foo/bar.rb to application, defining Bar class. Elsewhere in application, reference Bar

### Expected behavior
According to http://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html, "All subdirectories of app in the application and engines. For example, app/controllers. They do not need to be the default ones, **any custom directories like app/workers belong automatically to autoload_paths.**"
app/foo should be in autoload paths and bar.rb should be autoloaded by referencing Bar

### Actual behavior
NameError uninitialized constant Bar

### System configuration
**Rails version**:
5.0.0.rc1
**Ruby version**:
2.3.1

**Comment by fubarius** [comment] 2016-05-11 08:39
Issue seems to have been because I added app/foo after spring was running the app. bin/spring stop & trying again seems to do the trick. Perhaps the guide should have a note about autoload_paths being generated at app start and it not being a live * wildcard?

**Comment by vipulnsward** [comment] 2016-05-11 08:54
Hmm, I think there was an issue being worked on related to this? cc @fxn

**Comment by prathamesh-sonpatki** [comment] 2016-05-15 10:31
@fubarius According to https://github.com/rails/spring#watching-files-and-directories - Spring will detect file changes to any file loaded when the server boots. Changes will cause the affected environments to be restarted.

So if you have referenced `Bar` in any of the existing files **after** adding `app/foo/bar.rb` it should restart the server. Can you try to upload a sample application on Github with steps for reproducing the issue?

Thanks for the report.

**Comment by rafaelfranca** [comment] 2016-05-15 15:23
Spring only detects changes in the autoload paths that are defined when the server was booted. In this case `app/foo` was not in the autoload paths yet because it didn't exist. When the file is added spring server don't know about that path yet.

**Comment by prathamesh-sonpatki** [comment] 2016-05-15 15:45
@rafaelfranca True. But when some already existing file refers to `Bar` it should restart the server right?

**Comment by rafaelfranca** [comment] 2016-05-15 15:50
yes. If  `app/foo` existed when spring was started and you add a `bar.rb` file it will work fine.

**Comment by prathamesh-sonpatki** [comment] 2016-05-15 16:29
@rafaelfranca I meant to say, at boot time `app/models/post.rb` existed. Then we create `app/foo/bar.rb`. Spring it not affected by this. Now we edit `post.rb` and refer to `Bar` which is defined in `app/foo/bar.rb` then the server should get restarted. I wanted to ensure the OP followed this sequence or not.

**Comment by rafaelfranca** [comment] 2016-05-15 16:33
No. That is not going to work. `app/foo` is not in the autoload paths so spring will not restart because that file was added.

**Comment by rafaelfranca** [comment] 2016-05-15 16:35
The OP will get exactly what was described in the issue, but that is expected behavior. The autoload paths are loaded only in the boot time and new directories added to it will not be recognized until the server is restarted.

**Comment by prathamesh-sonpatki** [comment] 2016-05-15 16:39
ok. I think I may be misunderstanding but editing `post.rb` and referencing `Bar` constant then I thought it should restart the server because `post.rb` was present at boot time. But I will do some research about my understanding. 

We can close this issue if this expected behavior.

**Comment by rafaelfranca** [comment] 2016-05-15 16:46
Changing files doesn't restart the spring server, only creates a new client.

**Closed by rafaelfranca** 2016-05-15 16:46 UTC
Labels: activesupport

**Comment by fubarius** [comment] 2016-05-24 18:18
If this is expected behavior can we add a note to the documentation?

**Comment by rafaelfranca** [comment] 2016-05-24 18:41
We can. But that documentation doesn't mention spring so we would have to write a note about it.

**Comment by fxn** [comment] 2016-05-26 05:50
When the application launches autoload paths are computed and they remain fixed. The application is going to monitor their contents recursively, but won't monitor ascendants to update the collection itself.

This is not really related to Spring, if you opt-out and add the _app/foo_ directory while the server is running, it won't be picked up. You need to restart the server.

I have added this fact to the guide in https://github.com/rails/rails/commit/28a7c98fe665e40f40d4c69c0729ad0c0436bef2, also cherry-picked to 5-0-* branches.

**Comment by fxn** [comment] 2016-05-27 06:45
Ah, I just noticed there is an INFO card at the bottom of the section of the guide that documents the autoload dirs (http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoload-paths), the blue box.

The new edit is minimal though and goes in the right spot, no problem in being a bit redundant.

**Comment by fubarius** [comment] 2016-05-27 13:05
Thanks!
