### ISSUE TITLE
ETag middleware possibly preventing SSE

### ISSUE THREAD

**Issue by jefflasslett** [rails/rails#38842] opened 2020-03-29 23:37 UTC
### Steps to reproduce
I have a controller like so ..
```
class CreditDecisionsController < ApplicationController
  include ActionController::Live

  def subscribe
    connect_to_redis
    app_number = find_application_number
    @redis_channel = "#{current_user.login}:#{app_number}"

    headers['Content-Type'] = 'text/event-stream'

    # Putting these here prevent the ETag middleware modifying
    # the response
    # headers['Last-Modified'] = '0'
    # headers['ETag'] = '0'

    @sse = SSE.new(response.stream, event: 'credit_decision')

    begin
        @redis.subscribe(@redis_channel) do |on|
          on.message do |_, message|
            @sse.write("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
            @sse.write(message)
          end
        end
        Rails.logger.debug "   DBG: SSE::CreditDecisionsController#subscribe: LOOP END"
    rescue IOError => io_error
      Rails.logger.debug "DBG: SSE::CreditDecisionsController#subscribe: IOError: #{io_error.message}"
    rescue ClientDisconnected => client_disconnected
      Rails.logger.debug "DBG: SSE::CreditDecisionsController#subscribe: ClientDisconnected: #{client_disconnected.message}"
    rescue StandardError => e
      Rails.logger.debug "DBG: SSE::CreditDecisionsController#subscribe: StandardError: #{e.message}"
    ensure
      Rails.logger.debug "DBG: SSE::CreditDecisionsController#subscribe: ENSURE"
      @sse.close
      @redis.close
    end
  end
end
```

### Expected behavior
A request to this controller should persist and server-sent event should be sent to the browser whenever Redis publishes them to the subscribed channel.

### Actual behavior
Nothing is sent.  No data ends up "on the wire".  I've checked with wireshark.
Digging into this a bit, it seems that the `ETag` rack middleware is causing the response to "disappear".

```
# from rack-2.2.2/lib/rack/etag.rb

    def call(env)
      status, headers, body = @app.call(env)

      if etag_status?(status) && etag_body?(body) && !skip_caching?(headers)

        # Without 'Last-Modified' or 'ETag' headers, we end up in here.

        original_body = body
        digest, new_body = digest_body(body)
        body = Rack::BodyProxy.new(new_body) do
          original_body.close if original_body.respond_to?(:close)
        end
        headers[ETAG_STRING] = %(W/"#{digest}") if digest
      end

      unless headers[CACHE_CONTROL]
        if digest
          headers[CACHE_CONTROL] = @cache_control if @cache_control
        else
          headers[CACHE_CONTROL] = @no_cache_control if @no_cache_control
        end
      end

      [status, headers, body]
    end
```

I suspect the problem lies with the body replacement taking place here.  The original body is a `Thread::SizedQueue`, on which threads are waiting, presumably.  But then this middleware replaces that body with a plain array.  I think that is the problem.

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.5.7

**Comment by jeremy** [comment] 2020-03-30 19:06
Broken by https://github.com/rack/rack/pull/1416. Downgrading to Rack 2.1.x is an immediate workaround.

**Comment by jeremyevans** [comment] 2021-01-18 08:05
@jeremy You may want to consider reopening this.  The Rack core team has determined this is not a bug in Rack, so it's something Rails should fix if you want streaming to work. See https://github.com/rack/rack/issues/1619#issuecomment-648477608.  I apologize for not realizing earlier that Rails wasn't working on a fix for this, especially considering it's now been almost a year since Rack 2.2.0 was released.

**Comment by cristian-rivera** [comment] 2021-02-24 22:02
I can confirm that instead of downgrading Rack, the following workaround yields success: https://github.com/rack/rack/issues/1619#issuecomment-741649037

**Comment by zzak** [comment] 2021-05-25 23:04
@ioquatix or @jeremyevans Do you know if this is still a bug? It seems there was a workaround in https://github.com/rack/rack/issues/1619#issuecomment-741649037 but should that apply to Rails itself?

**Comment by ioquatix** [comment] 2021-05-26 03:20
Yes for Rack 2.x a workaround is required, the one you linked to seems okay to me. For Rack 3.x (unreleased), the problem is fixed by a spec which prevents `Rack::ETag` from trying to buffer the response.

**Comment by zzak** [comment] 2021-05-26 03:31
@ioquatix Do you think there's anything Rails can do to make this easier? I'd like to avoid having users monkey-patching Rack internals, or setting headers themselves. At least, it seems this behavior is apart of Rack 2 and therefore we could support a patch in Rails to workaround this until we can depend on Rack 3. (I'm assuming that is some time away).

**Comment by ioquatix** [comment] 2021-05-26 04:14
Yes, I think you can implement the hack internally for Rack 2.x.

For Rack 3.x you can remove it.

Regarding a more general approach, I discussed it here: https://github.com/rails/rails/issues/42031

**Comment by byroot** [comment] 2021-07-27 21:27
Since I don't see what Rails could do, I'm afraid we can only mark as 3rd party issue.

**Closed by byroot** 2021-07-27 21:27 UTC
Labels: third party issue
