### ISSUE TITLE
[regression?] ROR 4.2.0: Marking virtual attribute dirty causes invalid SQL at save time

### ISSUE THREAD

**Issue by minaguib** [rails/rails#18522] opened 2015-01-14 20:51 UTC
This issue popped up after upgrading a rails application from 4.1.7 to 4.2.0

Given an instance (p) of an AR model (Purchase) that would otherwise save successfully, marking a virtual attribute as dirty (such as done in a custom setter):
`irb(main):009:0> p.send(:attribute_will_change!, :virtfoo)`

Then causes errors saving:
```
irb(main):010:0> p.save
   (0.2ms)  BEGIN
PG::UndefinedColumn: ERROR:  column "virtfoo" of relation "purchases" does not exist
LINE 1: ...ses" ("user_id", "item_id", "item_type", "price", "virtfoo",...
                                                             ^
: INSERT INTO "purchases" ("user_id", "item_id", "item_type", "price", "virtfoo", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
   (0.2ms)  ROLLBACK
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "virtfoo" of relation "purchases" does not exist
LINE 1: ...ses" ("user_id", "item_id", "item_type", "price", "virtfoo",...
                                                             ^
```

It's attempting to set "virtfoo" in the DB which doesn't exist there (it's only a virtual @attribute in the ruby object).

**Comment by sgrif** [comment] 2015-01-14 20:52
Duplicate of https://github.com/rails/rails/issues/18407

**Closed by sgrif** 2015-01-14 20:52 UTC

**Comment by minaguib** [comment] 2015-01-14 20:56
I searched. I really did! Not sure how I missed #18407.  My apologies.

**Comment by sgrif** [comment] 2015-01-14 20:57
Not a problem! :grin:
