### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by harrylove** [rails/rails#34245] opened 2018-10-17 18:31 UTC
Rails 1.0 made me so productive and happy and it made app development feel effortless. I'm just writing this to say thank you: to 37signals, to DHH, to all of the contributors, and all of the ecosystem developers over the years. You didn't have to make this an open source project. You didn't have to contribute time and materials and your lives, but you did.

Learning Ruby on Rails was one of the best career decisions I ever made. Not only was it a fantastic piece of tech, even at version 1.0, but it forced me to learn and consider a slew of subjects and practices with which I might have never engaged otherwise. It also freed up my time to concentrate on things that mattered.

I have moved on in my career and don't do any Rails development these days, although there are times I wish I still did. To those of you who still keep the lights on, Thank You!

Feel free to close this issue.

### Steps to reproduce

1. Start using Ruby on Rails in 2005.
2. Fall in love with the simplicity and start building your dream app.
3. Open the door to users earlier than expected.

### Expected behavior
1. Productivity.
2. Praise for getting so much done in such a short time.
3. Learn about the aesthetics of good software design from a lot of really smart people.
4. Overnight success.

### Actual behavior
3 out of 4 ain't bad.

**Comment by tachyons** [comment] 2018-10-17 19:03
Duplicate of #16731 :run:

**Comment by dhh** [comment] 2018-10-18 02:30
😍🙏

**Comment by lucasprag** [comment] 2018-10-20 21:54
Thank you Rails team =)

**Closed** 2021-07-28 13:23 UTC
Labels: With reproduction steps, ready
