### ISSUE TITLE
UnpermittedParameters not raised

### ISSUE THREAD

**Issue by KjellMorgenstern** [rails/rails#30025] opened 2017-08-01 08:14 UTC
### Steps to reproduce

In config/environments/test.rb (and development.rb) set
config.action_controller.action_on_unpermitted_parameters = :raise

Run a test that tries to pass a non whitelisted parameter to an action.

Rails 5.1.2 behaves fine, the moment we upgrade to 5.1.3RC3, the unpermitted parameter is logged instead of raised.

### Expected behavior
ActionController::UnpermittedParameters should be raised.

### Actual behavior
Nothing is raised, instead the unpermitted parameter ist logged and the transaction is executed.

### System configuration
**Rails version**:
5.1.3RC3

**Ruby version**:
2.4.1

**Comment by sgrif** [comment] 2017-08-01 12:07
Please provide a sample application that demonstrates your issue.

**Comment by pixeltrix** [comment] 2017-08-01 12:08
Looks like it's related to this change: 6b0606a984ef259c283f1c763b12017711ed35bc

**Comment by JakariaBlaine** [comment] 2017-08-01 13:52
I also tried to pass unpermitted parameters in the request. No exception was thrown.
The rails version was 5.1.3RC3

This is the sample application with tests - https://github.com/JakariaBlaine/rails-test

**Comment by albertoalmagro** [comment] 2017-08-01 20:45
I could reproduce it with Rails 5.1.3RC3

@sgrif @pixeltrix May I try to fix it?

**Comment by rafaelfranca** [comment] 2017-08-01 20:55
@albertoalmagro yes

**Comment by albertoalmagro** [comment] 2017-08-02 16:53
Created PR https://github.com/rails/rails/pull/30045

**Comment by kaspth** [comment] 2017-08-03 18:05
Thanks for helping out with the RCs! Much appreciated ❤️

We're on the third RC for 5.1.3 and didn't want to delay that release further. Instead we've reverted the change causing this for now.

Hopefully #30045 is ready for 5.1.4.rc1 💪

**Comment by albertoalmagro** [comment] 2017-08-04 06:58
@kaspth yesterday I updated #30045 please feel free to review it 😊

**Comment by albertoalmagro** [comment] 2017-08-15 21:44
PR is now merged ❤️

**Comment by rafaelfranca** [comment] 2017-08-15 21:51
Thanks!

**Closed by rafaelfranca** 2017-08-15 21:51 UTC
Labels: actionpack, regression
