### ISSUE TITLE
Default disable_with on submit_tag breaks the app if the user goes back

### ISSUE THREAD

**Issue by robinwhittleton** [rails/rails#26366] opened 2016-09-02 10:13 UTC
### Steps to reproduce
1. Add an `f.submit` to your app
2. Observe the default `data-disable-with` attribute
3. Submit the form
4. Hit the back button
### Expected behavior

The submit button should be enabled.
### Actual behavior

The submit button retains its `disabled` state due to the browser caching the state of the form.

This is a good thing in general – we want state to be retained as we want users to be able to edit their previous submission and resubmit. However with a disabled submit button the app is effectively broken from that point on until they know how to force a refresh (standard refresh doesn’t refresh form state) or can pop open web inspector and manually remove the disabled state.

While I can see the utility of this behaviour it’s absolutely user hostile to make it a default. I note that in the PR that added this (https://github.com/rails/rails/pull/21135) there wasn’t any discussion of the back button issue.
### System configuration

Rails 5.0.0.1
Ruby 2.3.0

**Comment by maclover7** [comment] 2016-09-02 16:03
Hi @robinwhittleton, thanks for reporting this! I think this is more of a jquery-ujs bug, than a Rails/Action View bug. Looks like there was a ticket opened at rails/jquery-ujs a few months ago (https://github.com/rails/jquery-ujs/issues/357), and there was a PR that was merged in (rails/jquery-ujs/pull/385) to try and fix this bug. Would you be willing to test out this patch locally, and see if it fixes the error for you? Thanks again for opening up this issue! :)

**Comment by robinwhittleton** [comment] 2016-09-03 10:51
The PR you referenced was merged on the 8th Sep 2014 rather than a few months ago 🙂 This was included in [jquery-ujs 1.0.2](https://github.com/rails/jquery-ujs/releases/tag/v1.0.2), which was then included in [jquery-rails 4.0.0](https://github.com/rails/jquery-rails/blob/master/CHANGELOG.md#400). My app is on jquery-rails 4.1.1, so [on jquery-ujs 1.2.1](https://github.com/rails/jquery-rails/blob/master/CHANGELOG.md#411). So either jquery-ujs has since broken or the patch wasn’t effective in the first place.

I’ll investigate what’s going on with jquery-ujs when I get some more time.

**Comment by ain** [comment] 2017-03-27 13:13
I can second @robinwhittleton's report here. Experienced the same. The patch seems to have no effect whatsoever.

**Comment by neilvilela** [comment] 2020-10-07 19:08
@maclover7 I tried reproducing this issue on Rails 6, with and without Turbolinks, and even though the form state was cached by the browser, showing the previous form data, the button was re-enabled. Since jquery-ujs is not used anymore by currently maintained versions of Rails, I believe this issue should be closed, right?

**Comment by robinwhittleton** [comment] 2020-10-07 19:11
Unfortunately I haven’t worked on a Rails project in three years and currently have no way of confirming this. But I’m happy for you to close if you believe it’s now a non-issue.

**Comment by p8** [comment] 2024-01-05 10:27
Closing this as UJS has been removed from Rails: https://github.com/rails/rails/pull/50535

**Closed by p8** 2024-01-05 10:27 UTC
Labels: actionview, With reproduction steps
