### ISSUE TITLE
Rails 5 Logging adds extra lines that should not be there

### ISSUE THREAD

**Issue by jules2689** [rails/rails#23215] opened 2016-01-24 01:55 UTC
This is a default application that was created to reproduce the issue.
```
rails new TestApp
bin/rails g scaffold TestModel thing:string
bin/rails s
```

The attached image demonstrates the issue I am seeing. It happens on Rails Master and 5.0.0-beta1, with a new application and existing application.

![image](https://cloud.githubusercontent.com/assets/3074765/12533968/1baa48d0-c213-11e5-8baa-fd16fa529004.png)

**Comment by maclover7** [comment] 2016-01-24 02:02
I believe @schneems has been doing some work on logging, all though not sure if it's related to this. Can you try and create a new app based off of Rails master, and see if this error can still be reproduced?

**Comment by schneems** [comment] 2016-01-24 02:20
You mean the extra white space? I didn't touch anything there. An example app that reprise the problem would be helpful.

**Comment by jules2689** [comment] 2016-01-24 02:25
Reproduced off of master. Same extra lines.
Here is an app that reproduces it for me: https://github.com/jules2689/Rails5Issue

Literally the only thing I did to make the "app" is:
```
rails new MyApp
bin/rails g scaffold TestModel thing:string
bin/rake db:migrate
bin/rails s
```

Hope this helps!

**Comment by vipulnsward** [comment] 2016-01-24 07:07
Seems to be caused by https://github.com/vipulnsward/rails/blob/a8aa8b7fc37784b36a41834af0272907bb07eeb8/railties/lib/rails/rack/logger.rb#L35-L36
without it, there's no space in the requests.

**Comment by vipulnsward** [comment] 2016-01-24 08:46
Ahh, I see why this is being caused. Above lines put in 2 newlines per request, so that we can grep them(ref: https://github.com/vipulnsward/rails/commit/1a7049906ee6735bae058e9985a3806d08d9746b)

But since Rails 5, we default to puma server, which is serving multiple assets at a time, due to threads.
Hence, the request are being interleaved and logged like so- https://gist.github.com/vipulnsward/ecf0923015faba0c9e03

The extra spaces are from different requests and not just a single one.

Any suggestions to handle these? cc @jeremy @schneems

**Comment by schneems** [comment] 2016-01-24 15:05
Either we remove those lines or we leave them in. I'm fine with either. When sprockets 4 gets released we no longer serve individual files in development so the problem will be slightly better.

**Comment by maclover7** [comment] 2016-01-24 15:12
Opened PR #23220 to remove the blank lines. Justification is in commit message. :heart:

**Comment by vipulnsward** [comment] 2016-01-24 15:14
@maclover7 you are fast. Was just about to open one. :grin:

**Comment by jules2689** [comment] 2016-01-24 15:15
Thank you @maclover7 !
Much easier to read the logs without it :)

**Comment by maclover7** [comment] 2016-01-24 15:17
:+1:

**Comment by vipulnsward** [comment] 2016-01-29 07:45
Fixed by https://github.com/rails/rails/pull/23220

**Closed by vipulnsward** 2016-01-29 07:45 UTC
Labels: attached PR, railties
