### ISSUE TITLE
I18n: Error message interpolation should be done inside the messages themselves

### ISSUE THREAD

**Issue by johnnyshields** [rails/rails#19569] opened 2015-03-28 12:37 UTC
**I previously submitted this issue to Rails-I18n repo (https://github.com/svenfuchs/rails-i18n/issues/532) and they directed me here**

Currently the attribute name in error messages is setup as follows:

```yaml
  errors:
    format: "%{attribute} %{message}"
    messages:
      accepted: must be accepted
      blank: can't be blank
      present: must be blank
```

Any reason why we don't get rid of the "format" node and instead do:

```yaml
  errors:
    messages:
      accepted: "%{attribute} must be accepted"
      blank: "%{attribute} can't be blank"
      present: "%{attribute} must be blank"
```

This would be much more flexible as it's not necessarily natural in all locales to force ALL error messages to have the same sentence structure. (In addition, there are some error messages where you may not want to use the attribute name at all.)

**Comment by carlosantoniodasilva** [comment] 2015-03-31 10:54
The problem is that we don't always want the complete/full error with the attribute name on it, for example Simple Form by default displays the error below the input and it does not use the full message, and I've seen this in many other places as well. The format is only used when you request the full messages, otherwise it's just a list of errors tied to a specific field.

If we didn't have this difference, I'd probably be +1 for this "simplified" way of handling errors, however right now I think it is more flexible this way (although I agree in some locales it's not super natural, I've had a few issues myself with that).

Lets get some more thoughts on this one.

**Comment by rafaelfranca** [comment] 2015-03-31 16:23
I agree with @carlosantoniodasilva. Also, changing this right now will give us a lot of hard time to handle backward compatibility. I'd say that the current way is fine and I'd like to keep it.

**Comment by senny** [comment] 2015-06-23 12:58
Closing for the reasons presented by @carlosantoniodasilva. Depending on the context you want to use the full message including the attribute name (eg. a flash message) and other times you just want the explanation part (eg. inline errors in forms).

Since that context can change for the same type of error we need some mechanism to have a message with attribute or without.

**Closed by senny** 2015-06-23 12:58 UTC
Labels: activemodel, i18n
