### ISSUE TITLE
Wrong number of arguments (3 for 0..1) with link_to

### ISSUE THREAD

**Issue by swaathi** [rails/rails#25007] opened 2016-05-13 10:55 UTC
### Expected behavior
`link_to` should allow me to pass more than one parameter. 

### Actual behavior
`link_to` now allows me to pass only one parameter. So I can do things `link_to board_path(@board)` but not `link_to groups_board_path(@group, @board)`. Or even, `board_url(@board, format: :json, subdomain: current_domain.name)`. This is the error I'm getting,

`ActionView::Template::Error: wrong number of arguments (3 for 0..1)`

I've had to manually remove all paths and fill it in with hard coded links – something I know I will regret when I find a permanent fix for this bug.

### Steps to reproduce
I'm not sure how this error popped up, I only pushed code to production and this happened. Even when CI passed. But this error has been reported before [here] (https://github.com/CultivateLabs/storytime/issues/49).

### System configuration
**Rails version**: 4.2.3

**Ruby version**: ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

**Comment by maclover7** [comment] 2016-05-13 13:30
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by sblackstone** [comment] 2016-05-13 16:12
> link_to board_url(@board, format: :json, subdomain: current_domain.name)

Perhaps you mean, 

`link_to board_url(@board), format: :json, subdomain: current_domain.name
`

**Comment by rafaelfranca** [comment] 2016-05-13 19:30
Can you please provide a sample application that reproduces the error?

**Comment by swaathi** [comment] 2016-05-14 02:35
I am actually not sure of what caused this to occur. I only pushed my latest code to production and this happened out of the blue. I had to change all the paths in my entire code base to something that was hardcoded because I couldn't figure it out at all. After 30 hours, I updated Rails from `4.2.3` to `4.2.5` and everything started working! All the `link_to`s I used earlier started to magically work. Is there any changes related to this bug from `4.2.3` to `4.2.5`?

**Comment by rafaelfranca** [comment] 2016-05-14 04:07
No. There is not. I never saw this bug before and we have tests to assert this behavior. I'm guessing it was some kind of gem in your project.

I'm closing since it is not a bug in Rails. Thanks.

**Closed by rafaelfranca** 2016-05-14 04:07 UTC
Labels: actionview, needs feedback

**Comment by thewatts** [comment] 2016-05-17 07:14
@swaathi, I'm in the process of upgrading an old app to Rails 4.2 (from 4.1).

I was having this same issue - found out an old gem was being included that was causing the issues, [`bartt-ssl_requirement`](https://github.com/bartt/ssl_requirement).

**Comment by dineshPallapa** [comment] 2016-11-02 11:24
How you resolved that issue with bartt-ssl_requirement gem @thewatts.

**Comment by thewatts** [comment] 2016-11-02 12:52
@dineshPallapa I stopped using the gem 😅

**Comment by dineshPallapa** [comment] 2016-11-02 13:00
Great..! Did you replaced  bartt-ssl_requirement gem with any other gem @thewatts .If you did any good replacement for that gem suggest to us.

**Comment by thewatts** [comment] 2016-11-02 13:14
@dineshPallapa - Instead of using a gem, we're just forcing SSL in production.

```ruby
# config/environments/production.rb

MyApp::Application.configure do
  # ... more stuff ...

  # Force all access to the app over SSL, 
  # use Strict-Transport-Security, and use secure cookies.
  config.force_ssl = true

  # ... more stuff ...
end
```

**Comment by dineshPallapa** [comment] 2016-11-02 13:18
Thanks a lot.

**Comment by thewatts** [comment] 2016-11-02 13:19
@dineshPallapa welcome!
