### ISSUE TITLE
Action Cable: Request origin not allowed issue

### ISSUE THREAD

**Issue by aamir-pk** [rails/rails#31524] opened 2017-12-20 11:11 UTC
### Steps to reproduce
Create an API only application using Rails 5.1.4. Create simple channel and return a string from subscribed method of the channel. Add following line in config/development.rb:

`config.action_cable.allowed_request_origins = ['http://localhost:4200']`

and add an appropriate entry in routes file to let Websocket client connect to the server.

### Expected behavior
I should be able to connect from my Ember application and then subscribed to the channel.

### Actual behavior
I am trying to connect to server from my Ember application using ember_cable addon but it doesn't connect. On rails console it gives following messages:

```
Started GET "/cable" for 172.17.0.1 at 2017-12-20 10:17:26 +0000
Started GET "/cable/" [WebSocket] for 172.17.0.1 at 2017-12-20 10:17:26 Request origin not allowed: http://localhost:4200
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for 172.17.0.1 at 2
```

### System configuration
**Rails 5.1.4**:

**Ruby 2.4.1**:

**Comment by eileencodes** [comment] 2017-12-20 20:39
Hey @aamir-pk thanks for the issue!

Can you create a brand new Rails application from 5.1.4 that reproduces the issue for us so we can take a closer look? If you can reproduce without the `ember_cable` add-on then it sounds like the sisue is in Rails, but if you can't I suspect the issue is with the gem you're using. Thanks!

**Comment by hgsongra** [comment] 2017-12-26 05:55
@aamir-pk 

Add below line to `config/environments/development.rb` file   

`config.action_cable.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/]`   

Hope this will help you.   
   
Check out it on StackOverflow [Here](https://stackoverflow.com/questions/38719359/action-cable-not-working-after-binding-with-ip/38721895#38721895)

**Comment by hgsongra** [comment] 2017-12-26 06:14
@aamir-pk Once you confirmed the solution works for you then close the issue, So other can use these solutions and avoid duplicate.

Thanks,
hgsongra

**Comment by aamir-pk** [comment] 2017-12-26 06:19
@hgsongra I think I tried this or something similar to this as I've spent hours and hours on it. Still let me try it again and I'll update you with my response here.

Thanks

**Comment by aamir-pk** [comment] 2018-01-01 06:24
@hgsongra  I tried your what you suggested but still getting the same error.

**Comment by aamir-pk** [comment] 2018-01-01 09:58
@eileencodes I just created a fresh application using rails 5.1.4. Following are the changes/additions I made in the application:

1) I added following line in development.rb file:

`config.action_cable.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/, /file:\/\/*/, 'file://']`

2) Added following line in appliation.rb
`config.action_cable.mount_path = '/cable'`

3) cable.yml file looks likes following:

```
development:
  adapter: async

test:
  adapter: async

production:
  adapter: async

```
No other changes. After that I downloaded this project https://github.com/mwalsher/actioncable-js and open html file (in Chrome) from example folder that uses JavaScript to connect to action cable. I can see following error on the console:

```
Started GET "/cable" for 172.17.0.1 at 2018-01-01 09:48:50 +0000
Started GET "/cable/" [WebSocket] for 172.17.0.1 at 2018-01-01 09:48:50 +0000
Request origin not allowed: file://
Finished "/cable/" [WebSocket] for 172.17.0.1 at 2018-01-01 09:48:50 +0000
```

Please note that this is not the only way I have tried. I have again spent hours and hours trying lot of different options whatever I came across in official guide and various forums.

Thaks

**Comment by eileencodes** [comment] 2018-01-03 14:27
I suspect the problem is that you're using actioncable-js. The README says the project is no longer maintained and you should use the official Rails npm package here https://www.npmjs.com/package/actioncable#npm-usage

If you remove the actioncable-js gem does the application work as suspected?

**Comment by aamir-pk** [comment] 2018-01-04 04:24
@eileencodes Let me clarify this. The application is API only and there is no actioncable-js gem in Gemfile. I am using Ember client to connect to ActionCable using this add-on https://emberobserver.com/addons/ember-cable. 

In order to make sure that problem was not due to Ember. I created a new project from the scratch and then used earlier mentioned Javascript library just to see if it connects to ActionCable or not. What I found was I got exactly the same problem I faced using Ember add-on. That's why I am pretty sure that the problem is with my Rails application. Searching through different forums I noticed many people faced this problem and solution has been tweaking this parameter: config.action_cable.allowed_request_origins. However in my case changing this parameter doesn't seem to have any effect.

Hope the scenarios is clear now.

Thanks

**Comment by eileencodes** [comment] 2018-01-04 12:53
We have our own gem in Rails so if this is a bug in Rails, you should be able to reproduce this without Ember or actioncable-js if this is a Rails issue. Can you provide a newly generated application without ember or actioncable-js that reproduces the issue you're seeing?

I'm sorry I can't help more, but right now I don't have enough information to debug or help you debug.

**Comment by apauly** [comment] 2018-09-13 12:19
Stumbled across a similar issue - Just in case it's helpful for somebody:
If you use an external client, make sure it sends an `HTTP_ORIGIN` header that matches your `allowed_request_origins`. You could also include `nil` into the list as a warkaround.

**Comment by ShisiJu** [comment] 2020-03-26 10:34
I also meet the issue. 

I use the npm package `actioncable` 
Using the package in Chrome, I try to take a test for my application.


```js
  var cable = ActionCable.createConsumer(`ws://127.0.0.1:3000/cable`);
  cable.subscriptions.create(
    { channel: "ChatChannel" },
    {
      received: data => {
        switch (data.type) {
          case "message":
            this.setState({
              messages: this.state.messages.concat(data.message)
            });
            break;
          case "messages":
            this.setState({ messages: data.messages });
            break;
        }
      },
      speak: function(data) {
        return this.perform("speak", data);
      },
      load: function() {
        return this.perform("load");
      }
    }
  );
```

In console it has error as below :

```
action_cable.js:241 WebSocket connection to 'ws://127.0.0.1:3000/cable' failed: Error during WebSocket handshake: Unexpected response code: 404
```


rails debug console as below

```bash
Started GET "/cable" for 127.0.0.1 at 2020-03-26 18:09:47 +0800
Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2020-03-26 18:09:47 +0800
Request origin not allowed: file://
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for 127.0.0.1 at 2020-03-26 18:09:47 +0800
```

I aslo take the advice of @hgsongra ; But it still has  error;

I think it maybe beacuse of  ` not sending the HTTP_ORIGIN   ` @apauly 

How to use actioncable to send websocket with `HTTP_ORIGIN` ?
Or have other solutions ?

Thanks in advance !

**Comment by apauly** [comment] 2020-03-26 10:47
> ```shell
> Request origin not allowed: file://
> ```

It does look like you're using the file protocol for showing the client webpage. 

I don't think (also not sure) that Chrome or any browser will allow you to change the HTTP_ORIGIN header. is it possible for you to switch to an actual webserver rendering the page from an actual domain?

As a workaround it might be possible to set this:
```
config.action_cable.allowed_request_origins = ['file://']

**Comment by ShisiJu** [comment] 2020-04-02 03:46
Thanks a lot!
It works.  
I use webpack and devServer. Let the application run in a server.

**Comment by mahfuz10** [comment] 2021-01-23 09:51
For my flutter app, request origin was nil. So, needed to add `nil` in the list.

I have added this code in `config/environments/development.rb`, and it works!

``` ruby
config.action_cable.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/, /file:\/\/*/, 'file://', nil]
```

**Comment by joeyvanlierop** [comment] 2021-06-01 03:45
For anyone trying to connect using [Postman](https://blog.postman.com/postman-supports-websocket-apis/), you need to add `nil` to the list of allowed request origins like @mahfuz10 did.

**Comment by zzak** [comment] 2021-06-18 07:09
@aamir-pk @hgsongra @apauly @ShisiJu @mahfuz10 @joeyvanlierop Could you also try setting `config.action_cable.disable_request_forgery_protection = true`, this should give the same effect as setting the allowed origins to `nil`. 🙏

**Comment by zzak** [comment] 2021-06-25 10:37
Closing this, please feel free to open if you can confirm this doesn't solve the problem:

```
config.action_cable.disable_request_forgery_protection = true
```

**Closed by zzak** 2021-06-25 10:37 UTC
Labels: actioncable, attached PR, docs, more-information-needed

**Comment by vimalahari** [comment] 2021-07-28 06:26
Request origin not allowed: 'ionic'
please give a suggestion to solve the issue

**Comment by mahfuz10** [comment] 2021-10-02 20:36
@vimalahari If you add 'ionic' in the `allowed_request_origins` array, it should work.
```
config.action_cable.allowed_request_origins = ['ionic']
```
or, try disabling `forgery_protection`
```
config.action_cable.disable_request_forgery_protection = true
```
