### ISSUE TITLE
Controller tests lose some parameters

### ISSUE THREAD

**Issue by rthbound** [rails/rails#23624] opened 2016-02-11 23:24 UTC
I'm not sure what circumstances cause this, but when issuing a POST request with a [large parameters object](https://raw.githubusercontent.com/rthbound/controller-test-defect-rails-5/master/payload.json) in a controller test, **not all of the parameters make it through to the controller.** Of all that JSON, this is what makes it through:
```
{"data"=>{"attributes"=>{"enabled"=>"true", "position"=>"1", "display_label"=>"My very first dashboard"}, "measures"=>[{"data"=>{"id"=>"1", "attributes"=>{"position"=>"2", "enabled"=>"true", "unit_of_measure"=>"mmHg", "name_of_measure"=>"Blood Pressure Systolic", "source_of_measure"=>"BIOMETRIC_WATNO", "result_display_title"=>"Blood Pressure Systolic", "result_suffix_label"=>"mmHg", "link_display_label"=>"Learn More", "link_target"=>"https://google.com/", "promotion_config_id"=>"8675309"}, "relationships"=>{"dashboard"=>{"data"=>{"type"=>"dashboard", "id"=>"2"}}}, "measure_ranges"=>[{"data"=>{"id"=>"1", "attributes"=>{"gender"=>"MF"}, "measure_range_sections"=>[{"data"=>{"id"=>"5", "attributes"=>{"start"=>"180", "end"=>"210", "start_condition"=>"=", "end_condition"=>"=", "display_value"=>"", "display_title"=>"Hypertensive Crisis", "severity"=>"5"}, "relationships"=>{"measure_range"=>{"data"=>{"type"=>"measure_range", "id"=>"1"}}}, "type"=>"measure_range_section"}}], "relationships"=>{"measure"=>{"data"=>{"type"=>"measure", "id"=>"1"}}}, "type"=>"measure_range"}}], "type"=>"measure"}}], "type"=>"dashboard"}, "controller"=>"foobars", "action"=>"create"}
```

Note that all but the last object in the `measure_range_sections` collection are lost.

Reproduction: [an app to demo the bug](https://github.com/rthbound/controller-test-defect-rails-5). app was generated using the  `--api` option
Failing test showing the bug's effect: [bugs_controller_test](https://github.com/rthbound/controller-test-defect-rails-5/blob/master/test/controllers/bugs_controller_test.rb#L8-L9)

With `curl -H 'Content-Type: application/json' -H 'Accept: application/json' --data @payload.json -XPOST http://localhost:3000/bugs` everything works as expected (all params present).

**Comment by maclover7** [comment] 2016-02-11 23:37
Working on a reproduction script for this.

**Comment by maclover7** [comment] 2016-02-11 23:44
Confirmed bug via [this reproduction script](https://gist.github.com/maclover7/5611d5fb76a6abbf2564). Do you know if this worked in previous versions of Rails?

**Comment by rthbound** [comment] 2016-02-12 00:03
@maclover7 the bug is also present in rails 4.2.5

**Comment by maclover7** [comment] 2016-02-12 00:41
Will bisect this.

**Comment by maclover7** [comment] 2016-02-12 00:46
Just tried to run my reproduction script on `4-1-stable` and `4-2-stable`, and looks like this fails on both of those branches...

**Comment by rthbound** [comment] 2016-02-12 01:07
I looked at the params object with rails 4.2.5. I found some differences (e.g. `1` versus `"1"`), but all the information was there.

**Comment by diego-silva** [comment] 2016-02-12 01:17
Hey @maclover7 I was not able to reproduce this on master after a few changes on ur script:

L26: render json: params[:data]
L373: post '/hi', data: DATA

**Comment by rthbound** [comment] 2016-02-12 01:19
@diego-silva good catch.  @maclover7 and all, I updated the first issue comment to include the bad output.  A strict test for equality might not be the best (`1` / `"1"`). It'd be better to check to see if the number of objects in each collection is the same.

**Comment by rthbound** [comment] 2016-02-12 01:31
This assertion would better target the behavior: https://gist.github.com/rthbound/af1679506abedb14bfba#file-23624-rb-L375-L376

**Comment by rthbound** [comment] 2016-02-12 17:17
Params are still in tact here:
https://github.com/rails/rails/blob/892658a3d266828bd30d20101cab67de1e889278/actionpack/lib/action_dispatch/testing/integration.rb#L293 & 324
And here in rack-test https://github.com/brynary/rack-test/blob/master/lib/rack/test.rb#L224 & 231, the params are still good: [here they are](https://gist.github.com/rthbound/e5442a3e546f488b6e4a)
Still good: https://github.com/rack/rack/blob/master/lib/rack/mock.rb#L119
Still good: https://github.com/rails/rails/blob/master/railties/lib/rails/engine.rb#L692 :sweat: 
**Finally**, they're bad here https://github.com/rack/rack/blob/master/lib/rack/sendfile.rb#L112 ... body[-1] [looks like this](https://gist.github.com/rthbound/9acc9584c4d507a0067b)

**Comment by rthbound** [comment] 2016-02-13 01:10
Okay, I spent some more time stepping through the stack. I hope I'm narrowing in... It looks like the last time params are in tact is here:
From: /home/rth/Software/[rails/railties/lib/rails/rack/logger.rb @ line 24 Rails::Rack::Logger#call](https://github.com/rails/rails/blob/master/railties/lib/rails/rack/logger.rb#L24)

There, the 'rack.input' property of env has all the data we expect, but the return value of `call_app(request, env)` has the missing collection objects.

**Comment by rthbound** [comment] 2016-02-13 02:50
@maclover7 sorry for all the noise. It looks like [Rack::QueryParser#parse_nested_query](https://github.com/rack/rack/blob/2ac599551d6147184321c42f40a0ab3241499b08/lib/rack/query_parser.rb#L60-L73) @ line 458 Rack::Request::Helpers#parse_query may be at fault...

**Comment by rthbound** [comment] 2016-02-13 03:09
I think https://github.com/rack/rack/issues/951 and https://github.com/rack/rack/issues/1015 have this issue covered.

**Comment by rthbound** [comment] 2016-02-13 03:13
I guess the odd thing about this is how parsing fails in test env but has no problem in development env.

**Comment by rthbound** [comment] 2016-03-05 17:58
I noticed the code written to address https://github.com/rack/rack/issues/951 did not cover this issue. If we're holding #23997 open until a 3rd party fixed is introduced, we should probably be keeping an eye on this one as well.

https://github.com/rack/rack/pull/1029 would fix this issue and #23997.

**Comment by sgrif** [comment] 2016-03-11 17:26
Going to close this to keep the discussion focused in one place. We can discuss this issue on #23997, as this appears to be the same issue.

**Closed by sgrif** 2016-03-11 17:26 UTC
Labels: actionpack, third party issue, With reproduction steps

**Comment by rthbound** [comment] 2016-03-11 17:29
@sgrif well it's fixed with the same PR... two separate changes for two separate problems. Fair enough to close, though.
