### ISSUE TITLE
Add 'rails active_storage:update' to upgrade documentations from 6.0 to 6.1

### ISSUE THREAD

**Issue by iraszl** [rails/rails#41101] opened 2021-01-13 05:48 UTC
### Steps to reproduce
1. Read [documentation](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1) to upgrade from 6.0 to 6.1
2. Run into problems displaying ActiveStorage files when trying to run site after upgrade to 6.1

### Expected behavior
1. Documentation should mention that if you use ActiveStorage, you should run:
```rails active_storage:update```
```rails db:migrate```

### Actual behavior
1. Nothing mentioned about the need to add new columns to the ActiveStorage tables for the upgrade to work.

### System configuration
**Rails version**: 6.0 -> 6.1.1.

**Comment by jonathanhefner** [comment] 2021-01-13 16:12
Thank you for opening an issue!  This is a duplicate of #40895, which was addressed by #40791.

**Closed by jonathanhefner** 2021-01-13 16:12 UTC
