### ISSUE TITLE
Time marshalling with jruby is broken

### ISSUE THREAD

**Issue by nchainani** [rails/rails#10900] opened 2013-06-10 04:07 UTC
Envrionment
jruby 1.7.2
Macbook pro with snow leapord
Activesupport 3.2.12

Problem
Marshaling and un-marshaling a time object adds 1 hour

```
~/project/ » bundle exec irb
irb(main):001:0> Marshal.load(Marshal.dump(Time.now))
=> 2013-06-09 23:00:28 -0500
irb(main):004:0>
irb(main):005:0* require 'active_support/core_ext/time/marshal'
=> true
irb(main):006:0> Marshal.load(Marshal.dump(Time.now))
=> 2013-06-10 00:00:34 -0500
```

**Comment by robin850** [comment] 2015-07-22 16:38
It looks like this is not reproducible anymore on JRuby 1.7.21 and 9.0.0.0 so we can certainly close this, thanks for reporting!

**Closed by robin850** 2015-07-22 16:38 UTC
Labels: activesupport, attached PR, JRuby
