### ISSUE TITLE
Just started (3 days ago) getting ActionDispatch::IllegalStateError for controllers rspec test with edge rails

### ISSUE THREAD

**Issue by jasnow** [rails/rails#25269] opened 2016-06-03 21:56 UTC
Just started (3 days ago) getting ActionDispatch::IllegalStateError for controllers rspec test with edge rails.

### Steps to reproduce

 * Given you have a repo: https://github.com/jasnow/testing-app5edge
    And you run the following: **rspec ./spec/controllers/posts_controller_spec.rb:17**
    Then it will run without errors.

 * Now run "bundle upgrade" and you see the following gems were upgraded:
```
    ...Rails
    -  revision: c4cb6862babd2665a65056e205c2a5fd17a5d99d
    +  revision: 66ebbc4952f6cfb37d719f63036441ef98149418
    ...
    -    rails-dom-testing (2.0.0)
    +    rails-dom-testing (2.0.1)
    ...
    -    webmock (2.0.3)
    +    webmock (2.1.0)
```
 * Now rerun the above rspec test and you get this:
```
     Failure/Error: get :index

     ActionDispatch::IllegalStateError:
       header already sent
```
  * The total stacktrace is here: https://gist.github.com/jasnow/358925716d2068145790b11e4615cd3e

### Expected behavior

Expect the above test to run without the ActionDispatch::IllegalStateError error

### Actual behavior
Get error:
```
     Failure/Error: get :index

     ActionDispatch::IllegalStateError:
       header already sent
```
The total stacktrace is here: https://gist.github.com/jasnow/358925716d2068145790b11e4615cd3e

### System configuration
**Rails version**: Rails 5.1.0.alpha
  * Before: edge Rails: c4cb6862babd2665a65056e205c2a5fd17a5d99d
  * After:: edge Rails: 66ebbc4952f6cfb37d719f63036441ef98149418

**Ruby version**: ruby-2.3.1

**Comment by matthewd** [comment] 2016-06-03 22:47
6d4ac2726f56c33677867178e2e01e5237df780a

**Comment by jasnow** [comment] 2016-06-08 15:46
Unclear what the next step is. Do we fix actionpack code or fix my repo?

**Comment by amingRo** [comment] 2016-06-11 13:38
ignore this

**Comment by jasnow** [comment] 2016-06-11 13:57
@amingRo - Please explain. Currently have a failed test because of the https://github.com/rails/rails/commit/6d4ac2726f56c33677867178e2e01e5237df780a change. Thanks.

**Comment by amingRo** [comment] 2016-06-11 15:36
oh i am sorry brother,i am a JavaScript coder,learn github now,so i say that.delete the issue what i say is right.i am so sorry about that.

**Comment by dalpo** [comment] 2016-06-23 08:45
I encountered the same issue after the upgrade to rails5-rc2.

**Comment by jasnow** [comment] 2016-06-23 11:42
@dalpo - Yes, I have 2 more repos impacted since upgrading all my Rails 5.0.0.rc1 repos to 5.0.0.rc2.

**Comment by matthewd** [comment] 2016-06-23 13:31
I doubt the problem is in your code... I would expect it's either a bug I introduced in the above commit, or a problem in something rspec-rails is doing (maybe it's accidentally depending on the previous misbehaviour).

Can you reproduce the problem without rspec?

**Comment by jasnow** [comment] 2016-06-23 13:53
The only common gem in all 4 repos is devise.
One repo does not use rspec: https://github.com/jasnow/adopt-a-hydrant5edge

**Comment by guialbuk** [comment] 2016-06-23 17:56
I'm getting the same error, using rails 5.0.0.rc2 and rspec-rails  3.5.0.beta4.
Everything works fine when going back to RC1.

**Comment by jasnow** [comment] 2016-06-23 18:00
@guialbuk - Are you using devise too?

**Comment by guialbuk** [comment] 2016-06-23 18:14
Yes. I'm using devise too.

**Comment by guialbuk** [comment] 2016-06-23 18:41
In my project, this error occurs only in tests when a regular or guest user tries to access an admin-only page and gets a 302 response. When the user receives a 200 response the error doesn't happen.
So it definitely has something to do with Devise.

**Comment by sblackstone** [comment] 2016-06-23 18:57
Same issue, Devise and Minitest... Tried using both the older Devise helpers and the newer ones, and that did not upgrade.  Changing solely the rails version back to rc1 fixes the issue..

**Comment by jasnow** [comment] 2016-06-23 18:59
When I run this for this repo:  https://github.com/jasnow/adopt-a-hydrant5edge
```
post :create, params: { user: { email: @user.email, 
password: 'incorrect' }, format: :json }
```
and note that the password value is wrong, I get the above exception.

**Comment by sblackstone** [comment] 2016-06-23 19:46
Devise's controller helpers seem to be triggering process which in action_controller/test_case, it sets sent! which is what request.rb is checking to see if the header can be set..


```
/Users/sblackstone/code/rails/actionpack/lib/action_dispatch/http/response.rb:211:in `sent!'
/Users/sblackstone/code/rails/actionpack/lib/action_controller/test_case.rb:559:in `ensure in process'
/Users/sblackstone/code/rails/actionpack/lib/action_controller/test_case.rb:559:in `process'
/Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/rails-controller-testing-0.1.1/lib/rails/controller/testing/template_assertions.rb:61:in `process'
/Users/sblackstone/.rvm/gems/ruby-2.3.1/bundler/gems/devise-ac702843ddaa/lib/devise/test/controller_helpers.rb:33:in `block in process'
/Users/sblackstone/.rvm/gems/ruby-2.3.1/bundler/gems/devise-ac702843ddaa/lib/devise/test/controller_helpers.rb:100:in `catch'
/Users/sblackstone/.rvm/gems/ruby-2.3.1/bundler/gems/devise-ac702843ddaa/lib/devise/test/controller_helpers.rb:100:in `_catch_warden'
/Users/sblackstone/.rvm/gems/ruby-2.3.1/bundler/gems/devise-ac702843ddaa/lib/devise/test/controller_helpers.rb:33:in `process'
/Users/sblackstone/code/rails/actionpack/lib/action_controller/test_case.rb:629:in `process_with_kwargs'
/Users/sblackstone/code/rails/actionpack/lib/action_controller/test_case.rb:381:in `get'
```

**Comment by lkdjiin** [comment] 2016-06-24 17:08
Same error here with:
* rails 5.0.0.rc2
* rspec-rails 3.1.0
* devise 4.1.1

**Comment by codeodor** [comment] 2016-06-24 20:25
I've got the same error since upgrading from RC1 to RC2. Using minitest though, not rspec. App also uses devise, and all tests that are failing are along the lines of "should redirect to login when not logged in"

**Comment by shakycode** [comment] 2016-06-24 21:07
Should this be cross posted to devise since it looks like maybe an issue between the two?

**Comment by hamadata** [comment] 2016-06-25 20:43
I found a workaround for this issue.
The tests in devise gem pass with this change.
```
diff --git a/lib/devise/test/controller_helpers.rb b/lib/devise/test/controller_helpers.rb
index 462f313..060630e 100644
--- a/lib/devise/test/controller_helpers.rb
+++ b/lib/devise/test/controller_helpers.rb
@@ -137,9 +137,8 @@ module Devise

           status, headers, response = Devise.warden_config[:failure_app].call(env).to_a
           @controller.response.headers.merge!(headers)
-          r_opts = { status: status, content_type: headers["Content-Type"], location: headers["Location"] }
-          r_opts[Rails.version.start_with?('5') ? :body : :text] = response.body
-          @controller.send :render, r_opts
+          @controller.status = status
+          @controller.response.body = response.body
           nil # causes process return @response
         end
```

**Comment by lucasmazza** [comment] 2016-06-25 21:57
@hamadata can you please open a Pull Request on plataformatec/devise with this patch? We will probably cut a new release next week and we can ship it with this fix.

**Comment by lucasmazza** [comment] 2016-06-27 17:37
We merged @hamadata fix on plataformatec/devise#4169 and a release will be cut soon. Anyone else having this issue is welcomed to try it out and report anything on the Devise PR, and I guess we can close this one.

**Comment by jasnow** [comment] 2016-06-27 18:36
I will close this issue after I verified the above fix.

**Comment by rosenfeld** [comment] 2016-06-27 18:38
I can confirm it fixed my app as well.

**Comment by jasnow** [comment] 2016-06-27 18:46
https://github.com/plataformatec/devise/pull/4169 appears to fix my original problem. The whole community thanks you. - @hamadata and @lucasmazza

**Closed** 2016-06-28 20:37 UTC
Labels: actionpack
