### ISSUE TITLE
RAILS_RELATIVE_URL_ROOT is ignored by url_helpers outside controllers/views

### ISSUE THREAD

**Issue by wnewbery** [rails/rails#29053] opened 2017-05-11 23:11 UTC
### Steps to reproduce
When using URL helpers outside a controller/view (e.g. in a `.js.erb` to give a link to a page) the RAILS_RELATIVE_URL_ROOT environment variable is being ignored. This looks the same as #9058 to me so not sure what changed. I got the same results with SCRIPT_NAME (allthough not sure  the difference, the guide uses [RAILS_RELATIVE_URL_ROOT](http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root)).

Paths from a controller/view are correct for me using Puma or Passenger.

It does seem possible for the app to fix this by doing `Rails.application.routes.default_url_options[:script_name] = ENV["RAILS_RELATIVE_URL_ROOT"]` (e.g. an initializer) but I did not think that was meant to be required, and am not sure if the result of `default_url_options` is even intended to be edited (All I found on Google / API docs was its a [attr_accessor in route_set.rb](https://github.com/rails/rails/blob/93034ad7fea7e00562103a7cd0acfab19bbfadf9/actionpack/lib/action_dispatch/routing/route_set.rb#L335))?

The [template/test](https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb) did not work for assets either (I guess some start-up stuff is missing?) but does in actual apps.

```
$ rails -v
Rails 5.0.2

$ rails new testing
...

$ cd testing

Add "get '/patients/:id', to: 'patients#show', as: 'patient'" to config/routes.rb

$ RAILS_RELATIVE_URL_ROOT="/testing" rails console
2.4.1 :001 > ENV["RAILS_RELATIVE_URL_ROOT"]
 => "/testing"
2.4.1 :002 > helper.image_path "testing.png"
 => "/testing/images/testing.png"
2.4.1 :003 > app.patient_path(1)
 => "/patients/1"
2.4.1 :004 > Rails.application.routes.url_helpers.patient_path(1)
 => "/patients/1"
2.4.1 :005 > Rails.application.routes.default_url_options[:script_name] = ENV["RAILS_RELATIVE_URL_ROOT"]
 => "/testing"
2.4.1 :006 > app.patient_path(1)
 => "/testing/patients/1"
2.4.1 :007 > Rails.application.routes.url_helpers.patient_path(1)
 => "/testing/patients/1"
```

```ruby
ENV["RAILS_RELATIVE_URL_ROOT"] = "/testing"


begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "rails", "5.1.0"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token    = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/patients/:id', to: 'patients#show', as: 'patient'
  end
end

require "minitest/autorun"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_path
    asset_helpers = ActionController::Base.helpers
    url_helpers = Rails.application.routes.url_helpers
    assert_equal "/testing/assets/image.png", asset_helpers.image_path("image.png") # Fails
    assert_equal "/testing/patients/1", url_helpers.patient_path(1) # Fails
    Rails.application.routes.default_url_options[:script_name] = ENV["RAILS_RELATIVE_URL_ROOT"]
    assert_equal "/testing/patients/1", url_helpers.patient_path(1) # Success
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
All the URL paths to have `/testing/` root.

### Actual behavior
The URL helper routes ignored RAILS_RELATIVE_URL_ROOT.

### System configuration
**Rails version** (tested with same steps as above):
4.2.8, 5.0.0, 5.0.2, 5.1.0

**Ruby version**:
2.4.1

**Comment by britnia** [comment] 2017-05-12 19:57
@locrawfish and I are trying but are unable to reproduce this issue with the given instructions. We found [This Gist](https://gist.github.com/ebeigarts/5450422) which explains how to properly use RAILS_RELATIVE_URL_ROOT. If you are sure you have used it properly please expand a bit on how to reproduce the issue. When we run the script we are getting one failing test however there are 3 total tests in the script. We should be seeing them pass or fail as well.

**Comment by wnewbery** [comment] 2017-05-13 03:06
Not tried playing with config.ru (its not even mentioned by http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root ) so will look at that. But even then, why should a url helper and an asset helper handle it differently outside a controller/view?

Not sure what you mean on the test? Its only one test case with 3 asserts? Maybe this, although still the global state so order might matter:
```ruby
  def test_image_path
    assert_equal "/testing/assets/image.png", ActionController::Base.helpers.image_path("image.png") # Fails
  end
  def test_url_path
    assert_equal "/testing/patients/1", Rails.application.routes.url_helpers.patient_path(1) # Fails
  end
  def test_url_path_with_explicit_config
    Rails.application.routes.default_url_options[:script_name] = ENV["RAILS_RELATIVE_URL_ROOT"]
    assert_equal "/testing/patients/1", Rails.application.routes.url_helpers.patient_path(1) # Success
  end
```
```
$ ruby url_test.rb
...
Finished in 0.156218s, 19.2039 runs/s, 19.2039 assertions/s.

  1) Failure:
BugTest#test_url_path [url_test.rb:46]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"/testing/patients/1"
+# encoding: US-ASCII
+"/patients/1"


  2) Failure:
BugTest#test_image_path [url_test.rb:43]:
Expected: "/testing/assets/image.png"
  Actual: "/images/image.png"

3 runs, 3 assertions, 2 failures, 0 errors, 0 skips
```

**Comment by maclover7** [comment] 2017-05-30 20:48
Closing in favor of #24393, very similar tickets.

**Closed by maclover7** 2017-05-30 20:48 UTC

**Comment by wnewbery** [comment] 2017-05-31 09:37
@maclover7 Is it actually the same part of Rails source? Does `url_helpers` etc. use that method? I did look through the source, but am not that familiar with the internal structure, so maybe I missed something.

That seems to be referring to `ActionDispatch::Request#url` during a request, rather than urls/routes outside a request (and within ActionController or views I never encountered a problem)?
