### ISSUE TITLE
Side Nav Covers Much of the Content Rails Routing from the Outside In

### ISSUE THREAD

**Issue by CorySpitzer** [rails/rails#52568] opened 2024-08-11 14:40 UTC
### Steps to reproduce

I browsed https://guides.rubyonrails.org/routing.html#resource-routing-the-rails-default

### Expected behavior

I expected the side menu (<nav id="subcol"> as far as I can tell) To be on the left with no space in between and not covering up part of the content.

### Actual behavior

It covered much of the content and wasn't flush with the left side.

### System configuration
Chrome Browser Version 127.0.6533.99 (Official Build) (64-bit)
on Windows 10 

Problem pics
![Rails-guides-nav-position](https://github.com/user-attachments/assets/380441e2-6937-4f25-86fd-ad64f925b49d)
![Rails-guides-nav-position-1](https://github.com/user-attachments/assets/91615bea-797f-4e05-a8aa-778bf3f796a6)

### What did you do to try and fix the problem?

In dev tools, highlighting 
`<nav id="subcol">` 
I commented out
`position: absolute;`
and added
`float: left;`

That partially fixed it, but it still isn't flush with the left side
![Rails-guides-nav-position-partial-fix](https://github.com/user-attachments/assets/1d0bc9c2-807d-4725-b2df-f9c53c6a148a)

Any thoughts about getting the nav flush with the left side, if that is the desired behavior?

**Comment by Earlopain** [comment] 2024-08-11 14:59
I've seen that myself (once of course), I believe it is a cache issue. Try force refreshing

**Comment by CorySpitzer** [comment] 2024-08-11 16:46
Force refresh seemed to fix it.

**Comment by Uaitt** [comment] 2024-08-12 12:08
I can confirm that this was happening to me too on all the guides (even on the guides homepage). 

I solved it by deleting all cookies and session storage data from the developer tools Application panel.

**Comment by rafaelfranca** [comment] 2024-08-12 15:51
Yeah, this is the second css cache issue that we have. We need to fix this by adding a cache key to the assets file.

**Comment by rafaelfranca** [comment] 2024-08-12 15:55
Duplicate of #52575

**Comment by jathayde** [comment] 2024-08-12 18:16
@rafaelfranca looking at this. The CSS files are generated by dartsass in generator.rb:123:

```
    def process_scss
        system "bundle exec dartsass \
          #{@guides_dir}/assets/stylesrc/style.scss:#{@output_dir}/stylesheets/style.css \
          #{@guides_dir}/assets/stylesrc/highlight.scss:#{@output_dir}/stylesheets/highlight.css \
          #{@guides_dir}/assets/stylesrc/print.scss:#{@output_dir}/stylesheets/print.css"
      end
```

Is this as straightforward as borrowing the `cache_digest` method from https://github.com/rails/rails/blob/fb6c4305939da06efdf2893d99130e7829c53e8b/actiontext/lib/action_text/attachments/caching.rb#L8 and appending it to the CSS file and then adding it into the HTML generation to append to those CSS file calls?

**Comment by rafaelfranca** [comment] 2024-08-12 18:23
Yes. I don't think we need that method though. We can just append the result of the `hexdigest` of the content of those files.

**Closed** 2024-08-13 14:04 UTC
Labels: docs, pinned
