### ISSUE TITLE
Regression around `errors#added?` in 5.2.2 ?

### ISSUE THREAD

**Issue by mjankowski** [rails/rails#34629] opened 2018-12-05 17:37 UTC
### Steps to reproduce

Call `model.errors.added?(:name, :taken)` on a record which has a uniqueness validation that has been hit.

<details>
<summary>Example case</summary>

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end
end

class Post < ActiveRecord::Base
  validates :name, uniqueness: true
end

class BugTest < Minitest::Test
  def test_errors_added
    post = Post.create!(name: "Test")

    same = Post.create(name: "Test")
    assert same.errors.added?(:name, :taken)
  end
end
```
</details>

### Expected behavior

In Rails 5.2.1.1 (and presumably earlier) this works as expected and returns true when given the relevant `:taken` symbol.

### Actual behavior

In Rails 5.2.2 this returns false.

Maybe worth nothing that changing the code to `record.errors.added?(:name, "has already been taken")` (ie, lose the symbol and use string instead) does get the expected result ... so it looks like the regression is around the symbol case specifically. I haven't tested things other than uniqueness/`:taken`.

**Comment by rafaelfranca** [comment] 2018-12-05 18:18
It was working before because of a bug that is now fixed.

You need to pass the correct options see the "If the error message requires an option, then it returns true with the correct option, or false with an incorrect or missing option." section in http://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-added-3F

**Closed by rafaelfranca** 2018-12-05 18:18 UTC

**Comment by fabrik42** [comment] 2018-12-07 16:36
Hi! Sorry for re-opening this issue, but I think it is really a regression. I'll try to explain:

You are right with your explanation. There is no problem with other/simpler validations, like `presence`, where just the `error` key (aka no options) are present. For example:

```
class User < ApplicationRecord
  validates :phone_number, presence: true
end

user = User.new.tap(&:valid?)

user.errors.details[:name]
# => [{:error=>:blank}]
user.errors.added?(:name, :blank)
# => true
```

Let's say I have the following model:

```ruby
class GameSession < ApplicationRecord
  validates :user_id, uniqueness: true
end
```

If there is already an active game session, it would rightfully add an error that would look like this:

```ruby
#<ActiveModel::Errors:0x00007fbe5deddfb0
 @base=
  #<GameSession:0x00007fbe5dedec80
   id: nil,
   user_id: "7476bf48-be7b-4b42-8204-948686b54c0b",
   activated_at: Fri, 07 Dec 2018 15:46:09 UTC +00:00>,
 @details=
  {:user_id=>[{:error=>:taken, :value=>"7476bf48-be7b-4b42-8204-948686b54c0b"}], :base=>[]},
 @messages={:user_id=>["has already been taken"]}>
```

You can see that the `:taken` error is something special in this case, because it adds a `value` key to the error details:

```
game = GameSession.new(user_id: '<user_id>').tap(&:valid?)

game.errors.details[:user_id]
# => [{:error=>:taken, :value=>"<user_id>"}]
game.errors.added?(:user_id, :taken)
# => false
```

The problem here is that the `#added?` method [compares the given details](https://github.com/rails/rails/blob/v5.2.2/activemodel/lib/active_model/errors.rb#L328) with `#include?` on the details array.

With the current implementation, you would need to call it in the following way:

```
game.errors.added?(:user_id, :taken, :value=>"<user_id>")
```

The value is the user id that gets validated, but it was not really defined as an option by the programmer, rather automagically by Rails. If you wrap your head around it, it makes sense, but it is not very intuitive. I am not sure if this is really desired behaviour.

If you consider this a regression, I would be happy to help to fix it! 😃

**Comment by rafaelfranca** [comment] 2018-12-07 16:58
I still don't think it is a regression. `added?` is doing the right thing. `game.errors.added?(:user_id, :taken, :value=>"1")` is different from `game.errors.added?(:user_id, :taken)` so `game.errors.added?(:user_id, :taken")` should not return `true`.

You could make a case that the uniqueness validation should not pass the message to the details, but in that case you can't say which value is duplicated.

I'm more included to say we should document better which options are passed to the message generation on each validator, given those options are also used in the i18n of the message.

**Comment by fabrik42** [comment] 2018-12-07 17:19
I think my case is that `added?` now needs way too much internal knowledge to be used outside of the model. This was not the case before.

For example, we are using `added?` in some of our service classes to check for AR errors. Now these classes would need to know the options for minimum length to perform these checks.

**Comment by mjankowski** [comment] 2018-12-07 17:45
My use case which led to the original report was similar.

We have a background job which is processing records when their state changes, and part of what it does is create new records populated partially with the name of the initial records. In the case where creating a new record with the same name fails due to already being taken, we try again with something like "#{name} #{timestamp}" instead.

So our code of `...project.errors.added?(:name, :taken)` was using this method just to check "did the record fail to save because of a specific type of validation error on a specific attribute?". The check doesn't really care about what other options rails passed internally to create that.

Is there another public method which provides what we were using this method for?

I agree with the point that the docs could use more examples from each built-in validation type.

**Comment by rafaelfranca** [comment] 2018-12-07 21:36
Just to be clear the behavior you were expecting was always a bug. Before `details` was added in Rails 5.1 this method call you are expecting now to return `true` could return false depending on the locale you were using.

It changed in 5.2.0 to return true with missing information due to this bug fix https://github.com/rails/rails/commit/15cb4efadb61a8813967d3c25f4adfc9a918a0c0.

We don't have a public method that does what you want but you can do:

```ruby
errors.details[:name].map { |e| e[:error] }.include? :taken
```

We could probably add a method to check this, something like:

```ruby
person.errors.of_kind? :name, :too_long                                # => true
person.errors.of_kind? :name, "is too long"                            # => false
```

which would be implemented as above when symbol and by checking if the message includes the string when string.
