### ISSUE TITLE
destroy command

### ISSUE THREAD

**Issue by chashmeetsingh** [rails/rails#24186] opened 2016-03-14 13:52 UTC
### Steps to reproduce

- rails g controller abc
- rails d controller abc
- rails d controller abc

### Expected behaviour
Second time destroy is run it should say controller does not exist

### Actual behaviour
Shows log deleting controller and other related files created

### System configuration
**Rails version**:
4.2.6
**Ruby version**:
2.2.3

**Comment by aaronang** [comment] 2016-03-15 20:25
I just confirmed the same behavior.

**Comment by chrisarcand** [comment] 2016-03-15 21:47
Indeed, I'm looking in to this issue.

Note that this is true of anything that isn't a migration, and it needn't be created ahead of time. You can `rails d * *` and the output is the same. It also affects all versions; it's not _quite_ so much a bug as it is a slight inconvenience that it doesn't verify existence like migrations do.

**Comment by ojss** [comment] 2016-03-23 08:47
This is also happening on 4.2.5.1 for me. So its probably been happening for some time now?

**Comment by chrisarcand** [comment] 2016-03-23 12:01
Yes, I _believe_ this is how thor handles deletions normally, and if that's true it's probably been this way forever. This isn't so much of a bug as it is an enhancement.

**Comment by rafaelfranca** [comment] 2016-03-23 16:22
Yes this is more an enhancement and it needs to be done at thor level. So I'm closing since it is not a Rails issue.

**Closed by rafaelfranca** 2016-03-23 16:22 UTC
Labels: railties
