### ISSUE TITLE
ActiveStorage contaminating model instances resulting in ActiveRecord::AssociationTypeMismatch

### ISSUE THREAD

**Issue by adambutler** [rails/rails#37591] opened 2019-10-29 21:39 UTC
Using ActiveStorage can result in the class instance becoming contaminated in a strange way that results in a `ActiveRecord::AssociationTypeMismatch` exception when trying to associate the instance with another ActiveRecord model.

This example may seem a little unconventional as I discovered this issue whilst building seeds for my application.

### Steps to reproduce

```rb
require 'open-uri'

class User
  has_one_attached :avatar
  has_many :talks
end

class Talk
  belongs_to :user
end

user_a = User.create!({ email: 'user.a@example.com' })
user_b = User.create!({ email: 'user.b@example.com' })

user_a.avatar.attach(io: open('https://example.com/any/valid/image/uri'))

user_a.class.to_s
# => "User"

user_b.class.to_s
# => "User"

Talk.new({ user: user_a })
# => ActiveRecord::AssociationTypeMismatch

Talk.new({ user: user_b })
# => true
```

### Expected behavior

Associating `user_a` to a new instance of `Talk` should return `true`.

### Actual behavior

The following exception is unexpectedly raised:

```
ActiveRecord::AssociationTypeMismatch (User(#70172285884400) expected, got #<User id: "5c01db01-fd4d-464c-bb36-33d29469fe77", email: "example@example.com", created_at: "2019-10-29 21:20:16", updated_at: "2019-10-29 21:20:45"> which is an instance of User(#70172283718280))
```

### Further information

I added a `binding.pry` into the method `raise_on_type_mismatch!` in `activerecord-6.0.0/lib/active_record/associations/association.rb`. I've included the output below:

```
From: /Users/adambutler/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/associations/association.rb @ line 275 ActiveRecord::Associations::Association#raise_on_type_mismatch!:

    273: def raise_on_type_mismatch!(record)
    274:   unless record.is_a?(reflection.klass)
 => 275:     binding.pry
    276:     fresh_class = reflection.class_name.safe_constantize
    277:     unless fresh_class && record.is_a?(fresh_class)
    278:       message = "#{reflection.class_name}(##{reflection.klass.object_id}) expected, "\
    279:         "got #{record.inspect} which is an instance of #{record.class}(##{record.class.object_id})"
    280:       raise ActiveRecord::AssociationTypeMismatch, message
    281:     end
    282:   end
    283: end

[1] pry(#<ActiveRecord::Associations::BelongsToAssociation>)> record.is_a?(reflection.klass)
=> false

[2] pry(#<ActiveRecord::Associations::BelongsToAssociation>)> record
=> #<User id: "a19c59f1-fd39-40da-abd8-42bc94f2bfc7", email: "user@example.com", created_at: "2019-10-29 21:32:33", updated_at: "2019-10-29 21:32:34">

[3] pry(#<ActiveRecord::Associations::BelongsToAssociation>)> record.class
=> User(id: uuid, email: string)

[4] pry(#<ActiveRecord::Associations::BelongsToAssociation>)> reflection.klass
=> User(id: uuid, email: string)
```

### System configuration

**Rails version**: 6.0.0

**Ruby version**: 2.6.5

**Comment by victor-am** [comment] 2019-11-08 19:04
Hey, I was looking into this issue and although I could reproduce it on rails 6.0.0 and 6.0.1, I couldn't at the current master (which is in 6.0.2 alpha right now).

So I'm guessing this should be fixed once 6.0.2 is released :D

I didn't delve into it that much but maybe the fix is related to this PR:
https://github.com/rails/rails/pull/34827

btw thanks to @felippe-cardozo for the help debugging it :)

**Comment by adambutler** [comment] 2019-11-08 19:55
@victor-am My main concern is that this could have broader consequence. I think it is important that the underlying issue is understood and not just addressed by proxy of another issue.

I wish I were the right person to do this but the issue is strange enough to go beyond my understanding. Essentially as far as I can tell in "ruby land" (for lack of a better phrase) the two class instances should be comparable with the native `is_a?` method since:

a. They both resolve to the same string when `.class.name` is called
b. They both resolve to the file when given to pry's `show-source` method
c. When simply printed they are clearly instances that share the same class

My concern is that there is _something_ being modified that is yet to be identified on the class instance that causes the two objects to not respond as equal classes on the native Ruby `is_a?` method. I can't explain what at this time but it wouldn't surprise me if the root cause could have broader consequences if not understood correctly.

**Comment by victor-am** [comment] 2019-11-08 20:02
Yes, I also believe it should be understood correctly before closing it off.

But unfortunately, I'm also not the most adequate person for that since my rails internals knowledge isn't that great.

I was just going over some issues and seeing if there is anything I could solve in the few days I have some extra time and hoped to share what I learned while debugging this before heading to the next issue.

**Comment by adambutler** [comment] 2020-04-22 14:20
I would like to ask that this issue is reopened and the problem can be reproduced on Rails 6.0.2.2

**Comment by rafaelfranca** [comment] 2020-04-22 16:23
It has passed more than 3 months and nobody fixed the issue. Keeping it open alone will not fix it. If you need it to be fixed please do investigate and open a PR.

**Comment by composerinteralia** [comment] 2020-06-23 23:26
I was not able to reproduce the issue exactly as stated, but I was able to reproduce and investigate something quite similar, involving the interaction between Active Storage, Spring, and the `EventedFileUpdateChecker`.

To reproduce the issue:

* Run:
```rb
rails new test_app
cd test_app
bin/rails active_storage:install
bin/rails g model account
bin/rails db:migrate
```
* Add `has_one_attached :profile_photo` to `Account`
* Add `config.active_job.queue_adapter = :inline` to config/environments/development.rb
* Run:

```rb
bin/rails runner '
  require "open-uri"
  account = Account.create!
  account.profile_photo.attach(io: open("https://example.com/"), filename:
"test")
  puts Account == account.class
'
```

(If it is easier I could put this together into a repo and share a link to that.)

### Expected behavior

I expected this to print `true`

### Actual behavior

`Account` is getting reloaded in the middle of the example, causing this to return `false`

### What is going on?

* [As the application initializes, it builds a file watcher](https://github.com/rails/rails/blob/v6.0.3.2/railties/lib/rails/application/finisher.rb#L220), configured by default in development as an `EventedFileUpdateChecker`
* [When the `EventedFileUpdateChecker` initializes, it sets `@pid` to the current process id](https://github.com/rails/rails/blob/v6.0.3.2/activesupport/lib/active_support/evented_file_update_checker.rb#L36-L52)
* [Spring reloads if necessary before forking](https://github.com/rails/spring/blob/master/lib/spring/application.rb#L165-L175). Note that after spring forks the `EventedFileUpdateChecker` 's `@pid` will no longer match `Process.pid` in the forked process
* Our code references `Account`, loading it for the first time.
* Setting the account `profile_photo` triggers an `ActiveStorageAnalysis` job.
* [Active Job runs its execution callback](https://github.com/rails/rails/blob/v6.0.3.2/activejob/lib/active_job/execution.rb#L23-L26)
* [The execution callback wraps execution](https://github.com/rails/rails/blob/v6.0.3.2/activejob/lib/active_job/railtie.rb#L42-L44)
* [As part of execution wrapping we call the `run!` method](https://github.com/rails/rails/blob/v6.0.3.2/activesupport/lib/active_support/execution_wrapper.rb#L83-L92)
* [This in turn calls `check!` before running any callbacks](https://github.com/rails/rails/blob/v6.0.3.2/activesupport/lib/active_support/reloader.rb#L61-L67)
* [`check!` is configured by default to check whether the file watchers have been updated](https://github.com/rails/rails/blob/v6.0.3.2/railties/lib/rails/application/finisher.rb#L212-L214)
* [Because we are in a forked process, `EventedFileUpdateChecker#updated?` will always return true the first time](https://github.com/rails/rails/blob/v6.0.3.2/activesupport/lib/active_support/evented_file_update_checker.rb#L73-L77)
* [So we go ahead and perform the `run` callback](https://github.com/rails/rails/blob/v6.0.3.2/activesupport/lib/active_support/execution_wrapper.rb#L111)
* [Which causes the file watcher to execute](https://github.com/rails/rails/blob/v6.0.3.2/railties/lib/rails/application/finisher.rb#L226-L233)
* [Which in clears out the `Account` constant with `ActiveSupport::Dependencies.clear`](https://github.com/rails/rails/blob/v6.0.3.2/railties/lib/rails/application/finisher.rb#L204-L220)
* When we refer to `Account` again, it gets loaded for the second time.

This came up in https://github.com/thoughtbot/factory_bot/issues/1330 as an `ActiveRecord::AssociationTypeMismatch` error. I closed the issue when I could reproduce it without using factory_bot at all.

### Workarounds

This bug involves the interaction between spring, active_job, and the evented file
update checker. Removing any one of these makes this problem go away:

* Disable spring - this puts the initialization of the `EventedFileUpdateChecker` in
  the same process as the `updated?` check.
* Use the `FileUpdateChecker` instead, which doesn't have this problem
* Disable Active Storage to avoid its execute callbacks (this seems like the worst option!)


### Versions

Rails 6.0.3.2
Ruby 2.6.6

**Comment by composerinteralia** [comment] 2020-06-24 05:46
This issue is also present on master, but instead of erroring it hangs forever, seemingly related to [a change to run inline jobs in a separate Thread](https://github.com/rails/rails/commit/8319f9eceae0584bc4d360cd497b3b5e8e31c3110).

[Active Record calls #clear_reloadable_connections! in its before_class_unload callback](https://github.com/rails/rails/blob/ed06b52192ba24e324a1b5d30fec635fc289afa1/activerecord/lib/active_record/railtie.rb#L224-L228), and that ends up hanging forever because the new thread is unable to [enter the lock to check in the connection](https://github.com/rails/rails/blob/ed06b52192ba24e324a1b5d30fec635fc289afa1/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L602) it has [stolen](https://github.com/rails/rails/blob/ed06b52192ba24e324a1b5d30fec635fc289afa1/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L555-L556) back into the pool.

**Comment by jonathanhefner** [comment] 2020-06-25 05:53
@composerinteralia That issue [sounds familiar](https://github.com/rails/rails/issues/39431#issuecomment-634931451)... :laughing:

I am attempting a *partial* solution in #39718.

**Comment by composerinteralia** [comment] 2020-06-25 06:13
Yup, that's it! This was a fun one to debug.

**Comment by r4mbo7** [comment] 2020-07-25 12:36
That's a serious bug :roll_eyes: 
I'm surprise that issue doesn't have many :+1:

**Comment by floydback** [comment] 2020-10-24 18:49
Rails 6.0.3.2 still has this issue. What this message means?

> ActiveRecord::AssociationTypeMismatch (User(#70361853713520) expected, got #<User id: 1

**Comment by nicolasrouanne** [comment] 2020-10-31 12:33
@floydback since #39718 has [recently been merged](https://github.com/rails/rails/commit/60546a0c23f7fc078d6427e202744ae17225ee76) (2 days ago), you should probably try to reproduce it on the `master` branch. It's not yet in a official release.

**Comment by composerinteralia** [comment] 2020-11-02 22:45
I just ran through the [reproduction steps](https://github.com/rails/rails/issues/37591#issuecomment-648479317) for this issue on the [latest commit](https://github.com/rails/rails/commit/8389f9902c3f0e984df17a77386493f856d7a1bb) and I can no longer reproduce it, so I am going to close this issue.

**Closed by composerinteralia** 2020-11-02 22:45 UTC
