### ISSUE TITLE
Monkey Patch 'at_with_coercion' (activesupport) / Handle milliseconds from epoch

### ISSUE THREAD

**Issue by StefanMueller1993** [rails/rails#46710] opened 2022-12-13 09:01 UTC
### Description
We have a Ruby and Rails application with a web frontend and an API to support web calls from outside the frontend. We use the API in one use case to create and update work orders (resource) from calling an web url and sending the parameters as raw JSON data to our API controller (separate controller with separate route).
One attribute of an work order is 'due_date' which is defined in the model as a field of type DateTime (through Mongoid).
While Rails tries to instantiate the new object of a work order in the controller with the given parameters the transformation into the defined database fieldtypes gets done. For DateTime fields this is done internally by calling “at_with_coercion” in rails/activesupport/lib/active_support/core_ext/time/calculations.rb in line  44 (https://github.com/rails/rails/blob/v5.2.6/activesupport/lib/active_support/core_ext/time/calculations.rb#L44).
Because the API is called from outside there is an use case to set the 'due_date' field with an integer number which contains the amount of milliseconds from epoch time (1970-01-01 01:00:00).
Rails can only handle an integer which contains the amount of seconds from epoch time.
So we tried to monkey patch the internal “at_with_coercion” method but ran into some issues.

### Steps to reproduce
Model:  
```ruby
include Mongoid::Document
include Mongoid::Timestamps
field :due_date, type: DateTime
```

Controller:
```ruby
def create
  @work_order = WorkOrder.new(params.require(:work_order).permit(:name, … , :due_date, … ))
  @work_order.save
end
```

**Monkey Patches**
lib/core_extensions/time.rb:
```ruby
class Time
  class << self
    remove_method :at_without_coercion
    remove_method :at_with_coercion
    remove_method :at

    # Layers additional behavior on Time.at so that ActiveSupport::TimeWithZone and DateTime
    # instances can be used when called with a single argument
    def at_with_coercion(*args)
      return at_without_coercion(*args) if args.size != 1

      # Time.at can be called with a time or numerical value
      time_or_number = args.first

      if time_or_number.is_a?(ActiveSupport::TimeWithZone) || time_or_number.is_a?(DateTime)
        at_without_coercion(time_or_number.to_f).getlocal
      elsif time_or_number.is_a?(Integer) && time_or_number.to_s.length == 13
        time_or_number /= 1000.0
        at_without_coercion(time_or_number)
      else
        at_without_coercion(time_or_number)
      end
    end
    alias at_without_coercion at
    alias at at_with_coercion
  end
end
```
config/initializers/monkey_patches.rb:
```ruby
Dir[Rails.root.join('lib', 'core_extensions', '*.rb')].sort.each do |f|
  require f
end
```

API call:
URL: {{protocol}}://{{subdomain}}.{{url}}/api/v2/work_orders.json
Parameters (raw JSON): {
```json
"work_order":{
    "name":"Test workorder",
    ... ,
    "due_date":1669105754783,
    ...
    }
}
```

### Expected behavior
Rails should use our monkey patched method and return the correct formatted Time value.

### Actual behavior
If we don’t remove the existing aliases the calls to “at_without_coercion” leads to the internal Rails method alias and we get a StackLevel too deep exception.
If we override the aliases we end up in an infinity loop following a StackLevel to deep exception because the overriden method calls itself multiple times.

### System configuration
**Rails version**: 5.2.6

**Ruby version**: 2.5.9p229

**Mongoid gem version**: 7.3.1

### Alternatives
If there is no possibility to monkey patch the internal method is there a possibility so Rails can handle an amount of milliseconds from epoch time?

**Comment by eileencodes** [comment] 2022-12-13 18:05
Hi @StefanMueller1993 - thanks for opening an issue. 

We don't generally want applications to monkey patch Rails so we are unlikely to make a change simply to make monkey patching easier. However, if there is a bug or a missing feature we can fix that. But from the report it's not clear to me if there's a bug. If there is a bug we need a reproduction. Here's an [example script](https://github.com/rails/rails/blob/main/guides/bug_report_templates/generic_gem.rb) we use for these. Or you can provide an demo application.

If we determine there's a bug and fix it, it won't be backported to Rails 5.2. The 5.2 version no longer receives any updates and has been EOL since June. A new method would only be available in the next release (7.1), a bug fix would only be available in 7.1 or 7.0. So even if we did make a change it's not going to work for your current situation.

It's not really your question, but I really do recommend upgrading. We aren't going to do any more security releases for 5.2 and we also won't debug issues in a version that old. So we need a reproduction against main to consider fixing a potential bug. 😄

**Comment by StefanMueller1993** [comment] 2022-12-14 17:01
Hey @eileencodes ,
thank you for the fast reply!

Firstly you are absolutely right, we need to update and upgrade Rails to a supported version or in the best case to the latest version. We are going to do this in the next weeks.
So I understand that there are no bugfixes or updates regarding our issue for the older Rails version and that is fine.

Let me add some more explaination what the problem is and what we want to achieve:
Rails internal uses the mentioned method `at_with_coercion` from the ActiveSupport to translate integer numbers into time values for example when creating a new resource object in the controller for its DateTime fields (columns).
Our requirement is that in this case on the one hand an integer number with the amount of seconds from epoch time and on the other hand an integer number with the amount of milliseconds from erpoch time should be converted to a valid time value.
But Rails currently handles all integer number overgiven to this method as a amount of seconds.
So if you call `Time.at_with_coercion(1234567890)` gets converted to `2009-02-14 00:31:30 +0100` but if you call `Time.at_with_coercion(1234567890000)` it gets converted to `41091-11-25 06:00:00 +0100` because the bigger number gets interpreted also as a amount of seconds.

We have the use cases in multiple resources in our application to convert amount of milliseconds into time values so we would need to update all controllers to check for the specific parameter and convert it before we create the object which is not the best I think.
Additionally if we add a DateTime field to one of our resources we need to update the controller checks also which is also not the best solution in my opinion.

So therefore we wanted to monkey patch the `at_with_coercion` method from the Time class to also check for that long integers and handle them as a amount of milliseconds instead of seconds but can't get it working (as described in the post itself).
We also checked this method in the current Rails version (https://github.com/rails/rails/blob/v7.0.4/activesupport/lib/active_support/core_ext/time/calculations.rb#L45) but it hasn't changed and won't work for our use case and we need a other solution still after updating.
May you can provide us a suggestion how we can solve this issue with or without monkey patching the Rails ActiveSupport method no matter in which Rails version.

And after we upgraded to the latest Rails version I will open a PR to optimize the internal method to also handle milliseconds or maybe you also see a possibility to update the method to handle them.

**Comment by ghiculescu** [comment] 2022-12-18 18:57
`Time.at` is a [Ruby method](https://ruby-doc.org/core-2.6.3/Time.html#method-c-at) that accepts a number of seconds since the epoch. So given that, I think Active Support is not likely to stray too far from that behaviour by also supporting milliseconds. 

Assuming mongoid calls `Time.at` internally, could you monkey patch that to instead call something else? Then you could implement your own `Time.milliseconds_at`, which implements the `/= 1000` logic you need.

**Comment by eileencodes** [comment] 2023-01-03 15:21
Thanks for the link @ghiculescu - given that the underlying behavior is in Ruby and we don't want Rails to stray from Ruby and implement custom behavior I'm going to close this.

**Closed by eileencodes** 2023-01-03 15:21 UTC
