### ISSUE TITLE
Rails new with both bootstrap and propshaft does not work

### ISSUE THREAD

**Issue by kivanio** [rails/rails#44597] opened 2022-03-02 14:38 UTC
### Steps to reproduce

Create a new app with options for both bootstrap and propshaft

With only one of them It works.
With bulma, tailwind It also works as expected.

```ruby
rails new r7propshaft --database=postgresql --css=bootstrap --asset-pipeline=propshaft
```

### Actual behavior
```
├─ source-map-js@1.0.2
└─ to-regex-range@5.0.1
✨  Done in 4.16s.
rails aborted!
Thor::Error: The file /Users/kivanio/Sites/blockchain/r7propshaft/config/initializers/assets.rb does not appear to exist

Tasks: TOP => app:template
(See full trace by running task with --trace)
```

### System configuration
**Rails version**:
Rails 7.0.2.2
**Ruby version**:
ruby 3.0.3p157

**Comment by strobilomyces** [comment] 2022-03-03 09:18
Confirmed against rails/main. The problem was introduced in rails/cssbundling-rails@33af011. Running bin/rails css:install:bootstrap works when rolling back to the previous commit.

**Comment by kivanio** [comment] 2022-03-03 13:50
I have made a fix here https://github.com/rails/cssbundling-rails/pull/82

**Comment by Edouard-chin** [comment] 2022-03-03 14:50
I added a comment in https://github.com/rails/cssbundling-rails/pull/82#issuecomment-1058115188 because I think the fix should be made here

**Comment by ghiculescu** [comment] 2022-03-04 17:32
https://github.com/rails/rails/pull/44615 should fix this

**Comment by Edouard-chin** [comment] 2022-03-06 17:41
Fixed by https://github.com/rails/rails/pull/44615

**Closed by Edouard-chin** 2022-03-06 17:41 UTC
Labels: railties, attached PR

**Comment by Kroid** [comment] 2024-03-26 05:57
Error still exists:

```
> ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]

>  rails -v
Rails 7.1.3.2
```

```
> rails new app -T -d postgresql --css bootstrap -j esbuild -a propshatf

bin/rails aborted!
Rails::Generators::Error: The template [/home/kroid/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cssbundling-rails-1.4.0/lib/install/bootstrap/install.rb] could not be loaded. Error: The file /home/kroid/code/app/config/initializers/assets.rb does not appear to exist (Rails::Generators::Error)


Caused by:
Thor::Error: The file /home/kroid/code/app/config/initializers/assets.rb does not appear to exist (Thor::Error)

Tasks: TOP => app:template
(See full trace by running task with --trace)

```
