### ISSUE TITLE
DB:Prepare failing

### ISSUE THREAD

**Issue by rctneil** [rails/rails#53543] opened 2024-11-06 10:31 UTC
This is an issue when running `db:prepare`. It's identified from this Issue: https://github.com/rails/solid_queue/issues/402

I have also tried updating to Rails 8.0.0.RC2 and the same issue occurs.

Basically @rosa states: "the problem is that db:prepare tries to run db:migrate, and that tries to run a migration that has already been run according to db:migrate:status, and the same error doesn't happen when running db:migrate alone."

When running `bin/rails db:migrate:status`:

database: family_media_development

```
 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20240229130131  Create photos
   up     20240301091711  Update fields on photo
   up     20240301101628  Add google drive id to photos
   up     20240301104651  Create folders
   up     20240313104912  Create tokens
   up     20240314122134  Add slug to folders
   up     20240318105044  ********** NO FILE **********
   up     20240318105045  ********** NO FILE **********
   up     20240507115321  Add secret to tokens
   up     20240507125352  Add type and refreshable to token
   up     20240509091942  Acts as taggable on migrationacts as taggable on engine
   up     20240509091943  Add missing unique indicesacts as taggable on engine
   up     20240509091944  Add taggings counter cache to tagsacts as taggable on engine
   up     20240509091945  Add missing taggable indexacts as taggable on engine
   up     20240509091946  Change collation for tag namesacts as taggable on engine
   up     20240509091947  Add missing indexes on taggingsacts as taggable on engine
   up     20240509091948  Add tenant to taggingsacts as taggable on engine
   up     20240510090903  Add last update to photos
   up     20240522094103  Create settings
   up     20240522094846  Add fields to settings
   up     20240522114749  Create active storage tablesactive storage
   up     20240523085216  Create action text tablesaction text
   up     20240523102046  Create pages
   up     20240523102345  Add slug to pages
   up     20240617105037  Rename fields
   up     20240617112347  Add extra fields to photo
   up     20240617113641  Store photo ur ls on photo
   up     20240617115925  Rename google drive id to remote id on folders
   up     20240618092246  Create users
   up     20240618092302  Add devise to users
   up     20240710091842  Add role to users
   up     20240716103526  Create videos
   up     20240716111221  Add service name to active storage blobsactive storage
   up     20240716111222  Create active storage variant recordsactive storage
   up     20240716111223  Remove not null on active storage blobs checksumactive storage
   up     20240717085638  Create sizes
   up     20240718092127  Add position to photo
   up     20240718095033  Add position to video
   up     20240726093041  Create people
   up     20240726113531  Add parents to people
   up     20240726114511  Create partnerships
   up     20240730142529  Add root to people
   up     20240801121018  Add tag id to people
   up     20240809115203  Change folder id to be nullable in videos
   up     20240813110631  Create documents
   up     20240814104717  ********** NO FILE **********
   up     20240814105241  ********** NO FILE **********
   up     20240814110121  ********** NO FILE **********
   up     20240913092750  ********** NO FILE **********
   up     20240913103856  Add type to page
   up     20240913104247  Change type to string on pages
   up     20240913105519  Add media types to pages
   up     20240913114047  Change type to integer in pages
   up     20240913121904  Add page to setting
   up     20240913131847  Move media types
   up     20240913132026  Rename media types to value media types on settings
   up     20240913140617  Add media flags to folders
   up     20240913150903  Add position to pages
   up     20240917102518  Add document to pages
   up     20240917114603  Add source to videos
   up     20240917115419  Add video to pages
   up     20240919144339  Create people tags
   up     20240923084940  Rename parent1 id to parent id in people
   up     20240923091605  Remove roots from people
   up     20240923114417  Change biography to text in people
   up     20240924084019  Add marriage date and marriage date parts and divorce date and divorce date parts and marriage place to partnerships
   up     20241007125043  Create recurring executionssolid queue
   up     20241007125044  Create recurring taskssolid queue
   up     20241007125045  Add name to processessolid queue
   up     20241007125046  Make name not nullsolid queue
   up     20241007125047  Change solid queue recurring tasks static to not nullsolid queue
   up     20241105105659  Drop solid queue tables


database: family_media_development_queue

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     001             ********** NO FILE **********
```

When running `bin/rails db:migrate`:

No output.

When running `bin/rails db:prepare`:

```
== 20240726093041 CreatePeople: migrating =====================================
-- create_table(:people)
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::DuplicateTable: ERROR:  relation "people" already exists
/workspaces/family-media/db/migrate/20240726093041_create_people.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "people" already exists (ActiveRecord::StatementInvalid)
/workspaces/family-media/db/migrate/20240726093041_create_people.rb:3:in `change'

Caused by:
PG::DuplicateTable: ERROR:  relation "people" already exists (PG::DuplicateTable)
/workspaces/family-media/db/migrate/20240726093041_create_people.rb:3:in `change'
Tasks: TOP => db:prepare
(See full trace by running task with --trace)
```

I'm unsure what else to say here but have posted all the info asked of me by @rosa .

I hope it's enough to identify / track down what's going on.

**Comment by nedzadk** [comment] 2024-11-06 13:56
adding this
```
config.active_job.queue_adapter = :solid_queue
config.solid_queue.connects_to = { database: { writing: :queue } }
```
 to `config/environments/development.rs` fixed many issue with solid_queue setup.
 
 Let me know if it helps you

**Comment by rctneil** [comment] 2024-11-06 14:05
@nedzadk 

Yes, My `development.rb` and `production.rb` both have those lines already.

**Comment by rctneil** [comment] 2024-11-21 12:31
Any updates on this?  What's the status?

**Comment by flavorjones** [comment] 2024-11-21 15:10
@rctneil Are you able to provide a repository that reproduce this error? A way to quickly reproduce this would lower the barrier-to-entry for working on diagnosing and fixing it.

**Comment by rctneil** [comment] 2024-11-21 15:12
@flavorjones I do have the repo but it's private and annoyingly I can't share it.

**Comment by flavorjones** [comment] 2024-11-21 15:27
@rctneil OK. I realize it's frustrating for someone to ask more of you after reading through some of https://github.com/rails/solid_queue/issues/402, but it's likely that nobody is going to work on this without a clean reproduction. I'm worried that I could spend hours trying to reproduce what you're seeing and not getting anywhere.

All of which is to say, if you find yourself with the time to do it, it would be very valuable to work backwards from your app removing things that are unshareable, until you have something you could share that still reproduces the behavior.

**Comment by rctneil** [comment] 2024-11-22 11:38
@flavorjones I understand.   I "think" i've managed to create a reproduction of it.

There is a devcontainer in there.  If you run it, as part of creation it runs `db:prepare` (and fails), if you manually run `db:migrate`, it runs fine.

Repo is here: https://github.com/cbjdigital/db-prepare-repro

I really do hope this helps!

**Comment by rosa** [comment] 2024-11-22 14:43
Huh, I see there are some migrations there that shouldn't exist. In particular, the Solid Queue migrations being run in the main DB. It seems as if [the instructions to upgrade Solid Queue](https://github.com/rails/solid_queue/blob/main/UPGRADING.md#upgrading-to-version-08x) haven't been followed, and instead gone directly to version 1.0 and try to use the separate DB directly, together with the Solid Queue tables in the main DB. Not sure if this is related to the other error, but it's the errors you're seeing @flavorjones

**Comment by flavorjones** [comment] 2024-11-22 14:44
OK, I understand why you're having this problem. I'll explain how I uncovered it.

First, the only difference between `db:prepare` and `db:create db:migrate` is that `db:prepare` will load the schema from the schema dump file if it exists. So I have a hunch that the behavior differences we're seeing between the two commands may be because the migration files and the schema files are out-of-sync.

So, focusing only on the development databases (I commented out the test and prod entries in `config/database.yml`) ... I deleted the schema files and ran `db:prepare` and I get the same error I got from `db:migrate`. This confirms my hunch.

The error during migration is:

```
PG::UndefinedTable: ERROR:  relation "solid_queue_jobs" does not exist
```

I restored the schema file, then grepped for this table in the `db/` directory. I noticed that it's present in `db/queue_schema.rb`, but there is no migration for it. My conclusion is that you may have accidentally deleted the migration for `solid_queue_jobs`.

One final note: looking at your `config/database.yml`, it looks like the `queue` database sets its `migrations_path` to `db/queue_migrate` which is empty in the repro repository. Remember to move your queue-related migration files into that directory if you really want to keep your solid queue tables in a separate database.

Does all that make sense? I'm going to close this since it's not a Rails bug, but I'm happy to continue the conversation with you until you get things up and running.

**Closed** 2024-11-22 14:44 UTC

**Comment by rosa** [comment] 2024-11-22 14:46
> I noticed that it's present in db/queue_schema.rb, but there is no migration for it. My conclusion is that you may have accidentally deleted the migration for solid_queue_jobs.

This is expected if you install Solid Queue from version 0.8 onwards, as we just include a schema file to prepare the DB. However, in this case we have a mix: a previous installation of Solid Queue where only some of the migrations are present for the main DB, and then a new install where we have the new schema file. Basically, a sort of mix between an old version and the new version, without following the intermediate steps to go from < 0.8 to 1.0.

**Comment by rctneil** [comment] 2024-11-22 15:22
Hey @flavorjones and @rosa .  Thanks for your comments.  Ok.  So it seems like things are just a bit muddled up.

How would you recommend me to proceed to resolve this?

I want a separate queue DB in dev and prod ideally.  Hopefully nothing complicated!
