### ISSUE TITLE
ActionText Trix does not open links in new tab

### ISSUE THREAD

**Issue by yshmarov** [rails/rails#40672] opened 2020-11-23 23:21 UTC
### Steps to reproduce

Add any link in `actiontext`

### Expected behavior

* Open all links in a new tab **by default**

### Actual behavior

* any link in actiontext opens **in the same tab**, redirecting the user **out of your app.** This in most cases is not desired. How can we make all links open in a new tab like:

```
<a href="/" target="_blank">The home page will open in another tab.</a>
```

### System configuration
**Rails version**: 6.1+

**Ruby version**: 2.7+

Edit: I've found this issue https://github.com/basecamp/trix/issues/55 **SINCE 2015** that was never resolved

**Comment by composerinteralia** [comment] 2020-11-23 23:53
Good find on that trix issue. Since this is intentional behavior in trix, rather than a bug in  Rails, I am going to close this issue. You could try making a case for reopening that trix issue, but based on the [initial response](https://github.com/basecamp/trix/issues/55#issuecomment-165861753) in 2015 I am doubtful it will get much traction.

FWIW, my own opinion is that opening links in a new tab would not be a good default. I personally find that behavior fairly annoying for reasons like those in this [article](https://css-tricks.com/use-target_blank/).

**Closed by composerinteralia** 2020-11-23 23:53 UTC

**Comment by yshmarov** [comment] 2020-11-24 13:21
Interesting article, but IMHO the opinion is quite biased. 
Well, pity that a simple option like optional `open_link_in_new_tab: boolean` that adds `"target","_blank"` to a `href` couldn't be added in four years. 🙁

**Comment by ianrandmckenzie** [comment] 2021-03-03 21:33
> Interesting article, but IMHO the opinion is quite biased.
> Well, pity that a simple option like optional `open_link_in_new_tab: boolean` that adds `"target","_blank"` to a `href` couldn't be added in four years. 🙁

I agree, I'd love to have a boolean like this. I recently deployed my app to the iOS and Android app stores (basically a webview of my rails app), and contrary to the CSS tricks article, it *is* expected behavior for a new window (their actual browser) to be opened.

One might argue that my app being a webview is not good practice, but at the end of the day, I'm just one guy and it's hard enough managing a Rails codebase, let alone Swift and Java on top of that. Some of us gotta live our lives, man! 😛
