### ISSUE TITLE
StrongParameters#permit has inconsistent behavior with numeric-looking keys

### ISSUE THREAD

**Issue by nightpool** [rails/rails#41625] opened 2021-03-05 17:52 UTC
### Steps to reproduce

```ruby
params = ActionController::Parameters.new(items: {'1': {x: 2, y: 3}, '2': {x: 3, y: 4}})

params.require(:items).permit('1': [:x, :y], '2': [:x])
#  {"1"=>{"x"=>2, "y"=>3}, "2"=>{"x"=>3}}

params.permit(items: {'1': [:x, :y], '2': [:x]})
#  {"items"=>{"1"=>{}, "2"=>{}}}
```

### Expected behavior

Permit should behave the same when called on a parent hash as it does when called on a child hash.

### Actual behavior

Permit's behavior is inconsistent, and it's very difficult and confusing to permit a nested hash with integer-like keys. More generally, when dealing with JSON parameters, the implicit "array-like" handling behavior should be limited to real, actual arrays—not just objects with keys that look like numbers.

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.3

**Comment by markvanlan** [comment] 2021-03-09 16:16
you can see how the current test for numberic keys here: https://github.com/rails/rails/blob/dc7817cb42768ad01d69d5f9b0023f556760cb06/actionpack/test/controller/parameters/nested_parameters_permit_test.rb#L128-L151

You can just do `params.permit(items: [:x, :y])` for the case you gave.

@fxn I see you wrote this test. I can reproduce what @nightpool says here; if those keys are non-numeric the permit would work. I can work on a fix for this if it is a bug worth fixing; not sure because the answer is use the structure I suggested above.

**Comment by nightpool** [comment] 2021-03-09 16:21
Mark, in this case I need to permit different parameters for different
IDs—your workaround would allow the parameter "y" in for the second object,
which in some cases may be undesired.

**Comment by markvanlan** [comment] 2021-03-09 18:32
You're basically wanting to rely on an index to determine what params are permitted... Seems like a bad pattern honestly.

**Comment by nightpool** [comment] 2021-03-09 23:54
@markvanlan nope, nothing to do with an index. The structure in question was a map from models IDs to new instances of those models with specific attributes. So in this case, what might be an acceptable attribute for one model class might be dangerous for another.

**Comment by nightpool** [comment] 2021-08-17 22:45
This is still an issue, reproduction steps are the same as above!

**Closed** 2021-09-21 05:14 UTC
Labels: actionpack

**Comment by HParker** [comment] 2021-09-27 16:26
@nightpool if you want to try out the main branch permitting parameters this way is possible now.
