### ISSUE TITLE
Upgrading to rails v6-beta3 causes Upgrading Rails to v6-beta3 causes uninitialized constant ActionText::Engine::ApplicationController (NameError)

### ISSUE THREAD

**Issue by prokopsimek** [rails/rails#35749] opened 2019-03-25 16:15 UTC
### Steps to reproduce
1) create app rails v6-beta1
2) upgrade to rails v6-beta3
3) run `rails s`
4) open localhost:3000

### Expected behavior
Open homepage

### Actual behavior
```
Puma caught this error: uninitialized constant ActionText::Engine::ApplicationController (NameError)
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0.beta3/lib/action_text/engine.rb:39:in `block (2 levels) in <class:Engine>'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:429:in `instance_exec'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:429:in `block in make_lambda'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:606:in `catch'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:606:in `block in default_terminator'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:202:in `block in halting'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:514:in `block in invoke_before'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:514:in `each'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:514:in `invoke_before'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/callbacks.rb:134:in `run_callbacks'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/execution_wrapper.rb:119:in `complete!'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/execution_wrapper.rb:76:in `ensure in block in run!'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/execution_wrapper.rb:76:in `block in run!'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/execution_wrapper.rb:70:in `tap'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/execution_wrapper.rb:70:in `run!'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.beta3/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.beta3/lib/action_dispatch/middleware/static.rb:126:in `call'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.beta3/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/sentry-raven-2.9.0/lib/raven/integrations/rack.rb:51:in `call'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/webpacker-4.0.0.rc.7/lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-6.0.0.beta3/lib/rails/engine.rb:523:in `call'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/Users/prokop/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

### System configuration
**Rails version**: 6.0.0-beta3

**Ruby version**: 2.6.0

**Using puma**: 3.12.0

It seems like an error of puma, but because of `uninitialized constant ActionText::Engine::ApplicationController (NameError)` I guess it could be bug of rails.

**Comment by fxn** [comment] 2019-03-25 16:42
Sorry the reproduction steps are a bit ambiguous because you need to "upgrade".

Can you reproduce generating a minimal brand new beta 3 application?

**Comment by corneverbruggen** [comment] 2019-04-02 14:10
Facing exactly the same error after upgrading from beta2 to beta3, but only after I edit a file and reload a page. So it seems to have something to with reloading/autoloading. Haven't found the root cause yet.

I did find a difference in two files in the `bin` directory after upgrading to beta3, compared to a new beta3 app: both `bin/rake` and `bin/rails` lost those lines after running `rails app:upgrade`:

```
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError => e
  raise unless e.message.include?('spring')
end
```
But re-adding those (so these files are identical to those in a new beta3 app) does not solve the issue yet.

**Comment by corneverbruggen** [comment] 2019-04-02 14:28
Since it seems to be related to autoloading: could this be related to #35609?

**Comment by fxn** [comment] 2019-04-02 14:35
@corneverbruggen it could be that the engine is using a constant from the application (I have not checked).

In `master` engines are reloaded (they are managed by the `main` autoloader) to avoid that problem. Could you point the `Gemfile` to `master` and see if it disappears? That will upgrade Bootsnap and Zeitwerk too, but the fix is in Rails itself.

**Comment by corneverbruggen** [comment] 2019-04-02 15:13
Thanks, @fxn. I gave it a try, but using `master` did not solve the issue. What *did* solve it though, was upgrading `bootsnap`. Only using `master` did not upgrade it to the lastest version. A new rails app gets bootsnap `1.4.2` while an app upgrade from `beta2` to `beta3` still has bootsnap `1.4.1`. Upgrading bootsnap to `1.4.2` solves the issue.

**Comment by fxn** [comment] 2019-04-02 15:27
Ah, yes, you're right. The dependency is generated for new apps, but since Bootsnap is not a dependency of the gems, the upgrade is not automatic.

The last version of Zeitwerk has a more performant reloading, but if client code is also using Bootsnap, it needs 1.4.2 ([see why](https://github.com/fxn/zeitwerk/blob/b1c41dc7e3cb22873fc1896d722be10bb38af74e/lib/zeitwerk/loader.rb#L254-L265)). In Rails that is [documented in a CHANGELOG](https://github.com/rails/rails/blob/master/railties/CHANGELOG.md) for RC.

So, all squares. I think we can close it as fixed in `master`.

Thanks!

**Closed** 2019-04-02 15:27 UTC

**Comment by corneverbruggen** [comment] 2019-04-02 19:04
Ok, great. Thanks.

**Comment by bonekost** [comment] 2019-04-12 09:03
Hey @fxn I am facing the same issue but I don't use `bootsnap`. So can't upgrade.
I tried to use `master`, but no luck.

**Comment by fxn** [comment] 2019-04-14 22:16
@bonekost can you tell me more? Which version of Rails and Ruby?

**Comment by bonekost** [comment] 2019-04-15 09:53
ruby 2.5.1
rails 6.0.0.beta3

**Comment by fxn** [comment] 2019-04-15 10:00
Are you able to test against `master`? Engines are now handled differently. RC should be soon out too.

**Comment by bonekost** [comment] 2019-04-16 07:24
@fxn I updated ruby to 2.6.1 and added rails to `master` but still getting this error:
```
Puma caught this error: uninitialized constant ActionText::Engine::ApplicationController (NameError)
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actiontext/lib/action_text/engine.rb:39:in `block (2 levels) in <class:Engine>'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:429:in `instance_exec'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:429:in `block in make_lambda'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:606:in `catch'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:606:in `block in default_terminator'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:202:in `block in halting'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:514:in `block in invoke_before'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:514:in `each'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:514:in `invoke_before'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/callbacks.rb:134:in `run_callbacks'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/execution_wrapper.rb:119:in `complete!'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/execution_wrapper.rb:76:in `ensure in block in run!'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/execution_wrapper.rb:76:in `block in run!'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/execution_wrapper.rb:70:in `tap'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/execution_wrapper.rb:70:in `run!'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/notifications.rb:182:in `instrument'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:56:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/static.rb:126:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/notifications.rb:182:in `instrument'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:56:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/notifications.rb:182:in `instrument'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:56:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/notifications.rb:182:in `instrument'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:56:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/gems/webpacker-4.0.2/lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/notifications.rb:182:in `instrument'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/actionpack/lib/action_dispatch/middleware/stack.rb:56:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/engine.rb:526:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by fxn** [comment] 2019-04-16 08:19
On my phone.

Two things that would help diagnosing this one would be.

1. In `config/application.rb` add

```ruby
Rails.autoloaders.logger = method(:puts)
```

after the line loading the framework defaults, hit the error, and share the traces.

2. If possible, a minimal app or instructions to reproduce.

**Comment by bonekost** [comment] 2019-04-16 09:21
this is error what i got from what you suggest ^
```
Traceback (most recent call last):
	19: from bin/rails:4:in `<main>'
	18: from bin/rails:4:in `require'
	17: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/commands.rb:18:in `<top (required)>'
	16: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/command.rb:46:in `invoke'
	15: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/command/base.rb:65:in `perform'
	14: from /Users/user/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	13: from /Users/user/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /Users/user/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	11: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/commands/server/server_command.rb:138:in `perform'
	10: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/commands/server/server_command.rb:138:in `tap'
	 9: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	 8: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/dependencies.rb:302:in `require'
	 7: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	 6: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	 5: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/activesupport/lib/active_support/dependencies.rb:302:in `require'
	 4: from /Users/user/JsProjects/magpie/config/application.rb:18:in `<top (required)>'
	 3: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/autoloaders.rb:36:in `logger='
	 2: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/autoloaders.rb:29:in `each'
	 1: from /Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails/autoloaders.rb:40:in `zeitwerk_enabled?'
/Users/user/.rvm/gems/ruby-2.6.1@mgp/bundler/gems/rails-20b94af9eb93/railties/lib/rails.rb:48:in `configuration': undefined method `config' for nil:NilClass (NoMethodError)
```

**Comment by fxn** [comment] 2019-04-16 10:10
Zeitwerk does not even get a chance to log something?

**Comment by bonekost** [comment] 2019-04-16 11:45
```
      def zeitwerk_enabled?
        Rails.configuration.autoloader == :zeitwerk
      end
```

**Comment by fxn** [comment] 2019-04-16 22:17
Does your application define `ApplicationController`? Don’t see an autoload for it in the traces.

**Comment by bonekost** [comment] 2019-04-17 15:04
@fxn adding `ApplicationController` helped. Thanks

**Comment by isc** [comment] 2019-05-04 11:34
By following Chapter 2 of the book Component-Based Rails Applications, I stumbled upon the same exception. Adding an ApplicationController indeed helps but prevents from having an application built with components / engines an no app folder in the parent application as suggested by Stephan Hagemann in his book.

> Why Would You Delete the app Folder? It is optional to delete the app folder at this point. I am suggesting it for a couple of reasons. For one, it sends a clear message to everyone working on the codebase that something special is going on here. Also, the app folder is not currently needed and is likely not going to be needed in the future. Thus, it would be cruft to keep it around right now. And it can always be added back later if needed.

Hagemann, Stephan. Component-Based Rails Applications (Addison-Wesley Professional Ruby Series) (p. 19). Pearson Education. Kindle Edition.

**Comment by ro31337** [comment] 2019-05-09 23:54
This issue is blocking me. I need to restart the app every time I make change :( :( :(

**Comment by maurcarvalho** [comment] 2019-10-07 10:00
> Ran into the same issue with a minimal Rails test application and fixed it, as suggested above, by adding:
> 
> ```
> class ApplicationController < ActionController::Base
> end
> ```
> 
> and then inheriting from ApplicationController instead of ActionController::Base.
> This is a regression in Rails 6.0.0, it wasn't required to have ApplicationController defined in Rails 5. So I am also wondering if we need this new requirement.

indeed. I'm creating a component-based Rails app where /app directory is unnecessary. While using rails-5 I've been able to run it smoothly, after update to rails-6 I started to run into this regression..
