### ISSUE TITLE
AR causes stack level too deep when joining tables

### ISSUE THREAD

**Issue by krzysiek1507** [rails/rails#25653] opened 2016-07-02 16:24 UTC
### Steps to reproduce
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '5.0.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments

  def self.test_it
    current_scope.to_sql
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_through_joins
    Post.joins(comments: :post).test_it
  end
end
```
### Expected behavior
Should work same as in AR4.2.6 (I hope).
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.6'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments

  def self.test_it
    current_scope.to_sql
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_through_joins
    Post.joins(comments: :post).test_it
  end
end
```

### Actual behavior
Raises 
```BugTest#test_through_joins:
SystemStackError: stack level too deep
```

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.2.4

**Comment by krzysiek1507** [comment] 2016-07-02 16:30
Related to #18109

**Comment by alextaylor000** [comment] 2016-07-05 05:04
It looks like the regression was introduced by 12e9e38.

**Comment by maclover7** [comment] 2016-07-05 13:43
cc @sgrif

**Comment by kamipo** [comment] 2016-07-05 13:49
@k0kubun Can you take a look at this?

**Comment by k0kubun** [comment] 2016-07-05 14:25
I guess this can be resolved in the same way as https://github.com/rails/rails/pull/25187 and only that direction can solve both problems. As you can see from the discussion in the PR, `scoping`(`current_scope`) itself is going to be removed and I guess the fix won't be done.

By the way, just curious, why do you do circular joins and refer to `current_scope`? I couldn't imagine the use case from the code. (I understand stack level too deep is definitely a bug and it should be handled properly.)

**Comment by krzysiek1507** [comment] 2016-07-05 14:30
@k0kubun don't ask why. :D I found this use case in some gem.

**Comment by k0kubun** [comment] 2016-07-05 14:33
>  don't ask why. :D I found this use case in some gem.

Ah, I see. It may be difficult to fix since it's caused in a gem. Sorry for the trouble and thank you for reporting it.

**Comment by k0kubun** [comment] 2016-07-05 15:38
Sent a patch to fix this issue. https://github.com/rails/rails/pull/25702
Please tell me if the branch does not solve your problem.

**Comment by krzysiek1507** [comment] 2016-07-05 17:54
@k0kubun branch solves the problem.

**Closed** 2016-07-28 00:33 UTC
Labels: activerecord, attached PR, With reproduction steps
