### ISSUE TITLE
`railties-5.1.3` gem has .DS_Store files littered in it

### ISSUE THREAD

**Issue by chdiza** [rails/rails#30200] opened 2017-08-11 15:04 UTC
If I do `gem install rails`, then the gem `railties`, version 5.1.3, gets installed.  New to this version of the `railties` gem, there are a bunch of macOS's `.DS_Store` files laying around:
```
gems/railties-5.1.3/lib/rails/.DS_Store
gems/railties-5.1.3/lib/rails/command/.DS_Store
gems/railties-5.1.3/lib/rails/commands/.DS_Store
gems/railties-5.1.3/lib/rails/commands/generate/.DS_Store
gems/railties-5.1.3/lib/rails/engine/.DS_Store
```

Probably someone forgot to do some cleanup before shipping.  Easy to overlook, since those files are invisible.

I think this is new to 5.1.3, because I have a script to scour and remove .DS_Store  from various places on my macOS machines, and this is the first time that I can recall the script finding anything among my gems.

**Comment by rafaelfranca** [comment] 2017-08-11 15:22
@kaspth FYI.

I'm not sure we can do anything other than making sure `rake build` will remove those files before building the gem, because our gemspec allow hidden files.

**Comment by matthewd** [comment] 2017-08-11 15:54
We could filter to only expectedly-named hidden files, or we could use a `git ls-files` approach to only include files git knows about

**Comment by vfonic** [comment] 2017-08-13 04:46
I like the idea of using `git ls-files`. Is there any reason that we might need to include files, that are not committed to the git repo, in the gem? If not, `git ls-files` sounds like a good solution and will avoid having someone to add more code to `rake build` or anywhere else.

**Comment by matthewd** [comment] 2017-08-13 04:51
There are definitely files in the gem that aren't in the repo, but they're rare and known. (The ones that come to mind -- and quite possibly the only instances -- are the blade-generated JS files in actioncable and actionview.)

**Comment by kirs** [comment] 2017-08-13 18:54
I've been trying to reproduce it:

```diff
diff --git a/railties/railties.gemspec b/railties/railties.gemspec
index e5587b531a..6d417b68b5 100644
--- a/railties/railties.gemspec
+++ b/railties/railties.gemspec
@@ -16,6 +16,8 @@
   s.homepage = "http://rubyonrails.org"

   s.files        = Dir["CHANGELOG.md", "README.rdoc", "MIT-LICENSE", "RDOC_MAIN.rdoc", "exe/**/*", "lib/**/{*,.[a-z]*}"]
+  puts s.files.select { |file| File.basename(file) =~ /^\./ || File.basename(file) =~ /DS/ }
+
   s.require_path = "lib"

   s.bindir      = "exe"
```

```
$ touch lib/rails/engine/.DS_Store
$ touch lib/rails/commands/generate/.DS_Store
$ gem build railties.gemspec
lib/rails/generators/rails/generator/templates/templates/.empty_directory
<stripped warnings>
  Successfully built RubyGem
  Name: railties
  Version: 5.2.0.alpha
  File: railties-5.2.0.alpha.gem

$ gem unpack railties-5.2.0.alpha.gem
Unpacked gem: '/Users/kir/Projects/opensource/rails/railties/railties-5.2.0.alpha'
$ cat railties-5.2.0.alpha/lib/rails/engine/.DS_Store
No such file or directory
```

It looks like .DS_Store is not included into the built gem?

**Comment by kaspth** [comment] 2017-08-14 18:45
Dang, thanks!

👍 on `git ls-files`

I've got the `.DS_STORE` files in my user level `.gitignore` — @rafaelfranca what do you do for prerelease cleanup of these?

**Comment by rafaelfranca** [comment] 2017-08-14 19:58
No. I don't have `.DS_STORE` files inside the Rails repository.

**Comment by chdiza** [comment] 2017-11-13 14:02
No .DS_Store files are present in the 5.1.4 version of `railties`.

**Closed** 2017-11-13 14:05 UTC

**Comment by chdiza** [comment] 2018-04-01 15:21
FYI, this problem has now returned in 5.1.6.  There are `.DS_Store` files here:
```
railties-5.1.6/lib/.DS_Store
railties-5.1.6/lib/rails/.DS_Store
railties-5.1.6/lib/rails/generators/.DS_Store
railties-5.1.6/lib/rails/generators/rails/.DS_Store
railties-5.1.6/lib/rails/generators/rails/app/.DS_Store
```

**Comment by pixeltrix** [comment] 2018-04-02 09:43
Sorry, this was my fault - I was unaware that I needed to strip my tree of them before building the gem.
