### ISSUE TITLE
actioncable npm package seems broken

### ISSUE THREAD

**Issue by alexhanh** [rails/rails#25649] opened 2016-07-02 11:43 UTC
### Steps to reproduce

Goto https://tonicdev.com/npm/actioncable and hit run. 

I've also tried locally by running `npm install actioncable --save` and then `require('actioncable')` which gives `action_cable.js:4 Uncaught TypeError: Cannot set property 'ActionCable' of undefined`.

### Expected behavior
Should run without errors.

### Actual behavior
`ReferenceError: Cable is not defined` and `action_cable.js:4 Uncaught TypeError: Cannot set property 'ActionCable' of undefined`.

### System configuration
**Node version**: 4.4.6

**Comment by sevenseacat** [comment] 2016-07-02 12:13
I think this is missing a lot of info before it can be useful

**Comment by alexhanh** [comment] 2016-07-02 12:26
Further info: seems like `require('actioncable')` gives errors, but `<script src="node_modules/actioncable/lib/assets/compiled/action_cable.js"></script>` is working.

**Comment by alexhanh** [comment] 2016-07-02 12:39
Here's a repo that demonstrates this issue https://github.com/alexhanh/actioncable-npm-require-error

```
git clone git@github.com:alexhanh/actioncable-npm-require-error.git
cd actioncable-npm-require-error
npm install
npm start
open index.html
```

**Comment by maclover7** [comment] 2016-07-02 13:59
Investigating -- thank you for reporting!

**Comment by maclover7** [comment] 2016-07-02 14:11
Hmm, can you try and reproduce this with v5.0.0 of the `actioncable` npm package? The tonicdev.com page you are linking above is testing with 0.1.1.

<img width="982" alt="screen shot 2016-07-02 at 10 10 14 am" src="https://cloud.githubusercontent.com/assets/3020626/16540759/544f813e-403d-11e6-83ac-c8b2428d444e.png">

**Comment by alexhanh** [comment] 2016-07-02 14:17
@maclover7 Ooops, good catch. See https://github.com/alexhanh/actioncable-npm-require-error

**Comment by javan** [comment] 2016-07-02 19:41
It looks like `actioncable-5.0.0.gem` was not released with the latest compiled version of `action_cable.js` so it's missing proper module support added in https://github.com/rails/rails/pull/25119 and perhaps other changes too. [Here's the full diff against a freshly compiled `action_cable.js`](https://gist.github.com/javan/6d17410377f9802f5e86b46fbd20bf47). Much of it is a change indentation change. [Here are the missing likes that add module support](https://gist.github.com/javan/6d17410377f9802f5e86b46fbd20bf47#file-action-cable-diff-L1156-L1160).

/cc @matthewd

**Comment by schneidmaster** [comment] 2016-07-09 04:37
Actioncable is still broken from npm. Did you release a new version after merging #25119?

**Comment by rafaelfranca** [comment] 2016-07-09 04:38
No. It will be released with Rails 5.0.1

**Comment by schneidmaster** [comment] 2016-07-09 04:42
Ah okay. Is there an ETA for 5.0.1? If it's going to be a while, you might consider publishing a `5.0.0.1` to npm, seems undesirable to have a completely broken package out there.

**Comment by rafaelfranca** [comment] 2016-07-09 04:45
No ETA, and in my opinion no need to release a npm package outside our release process. If it is important to fix the npm package we should do a full release cycle, but I don't know if it is important or not.

**Comment by schneidmaster** [comment] 2016-07-09 04:51
I mean, the npm package is completely broken (just requiring it throws an error). I guess I don't know how serious it is to you to actually have npm support but that's about as broken as it gets. I maintain [action-cable-react](https://github.com/schneidmaster/action-cable-react) and I'd like to update it for rails 5 stable but this is blocking, unless I just copy the latest source code into my project as I did before. (npm supports installs directly from GitHub but this is untenable for this case because actioncable is contained inside rails and rails is a huge repo to clone just for a tiny portion of the code.)

**Comment by alexhanh** [comment] 2016-07-09 08:51
Given that Rails 5 natively supports API-only mode and it has been promoted as an important feature, maintaining a working npm package seems quite important, since we can't rely on the server serving AC via `require action_cable`. So I tend to agree with @schneidmaster about releasing `5.0.0.1`.

However, the npm package's download numbers seem pretty low (316 downloads last month), so maybe it indeed is a long-tail support case, in which case it should perhaps wait for `5.0.1`.

PS. Action Cable seems promising and is wonderfully easy to integrate. However, according to our experience, it had unreliable behaviour (weird deadlocks and timeouts) and we decided to implemented our pubsub via a simple Node+Socketio proxy. Really hoping to revisit AC in the future.

**Comment by javan** [comment] 2016-07-09 13:21
@alexhanh, I just took a look at your example repo (https://github.com/alexhanh/actioncable-npm-require-error). It seems to work fine if you don't use `babel-loader`. I changed `webpack.config.js` to:
```js
module.exports = {
  entry: './index',
  output: {
    filename: 'browser-bundle.js'
  },
  devtool: 'source-map'
};
```

**Comment by javan** [comment] 2016-07-09 14:50
The 5.0.0 npm package works as expected. It includes module support added in https://github.com/rails/rails/pull/24903, which was later improved but not fundamentally altered in https://github.com/rails/rails/pull/25119.

This issue stems from processing it through babel, which won't work since `action_cable.js` is not ES2105+ (I think CoffeeScript compiles to ES3 or 4). If you're using the webpack babel loader, just exclude actioncable. For example, change [this `webpack.config.js`](https://github.com/alexhanh/actioncable-npm-require-error/blob/master/webpack.config.js) to:
```diff
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -9,10 +9,11 @@ module.exports = {
       {
         test: /\.js$/,
         loader: 'babel-loader',
+        exclude: /actioncable/,
         query: {
           presets: ['es2015', 'react']
         }
       },
     ]
   }
```

**Closed by javan** 2016-07-09 14:50 UTC
Labels: actioncable

**Comment by schneidmaster** [comment] 2016-07-09 14:58
@javan The 5.0.0 npm package does not work as expected. It is completely broken, out of the box, independent of using Babel.

Run this:

```
$ npm install actioncable
$ node
> require('actioncable')
ReferenceError: ActionCable is not defined
    at Object.<anonymous> 
    ....
```

It's also obvious why this happens if you read the compiled code. You're compiling each of the source files as a separate `(function() { ... });` scope. The first one declares `this.ActionCable = { ... }` and later ones try to directly access the `ActionCable` object but it's not scoped correctly so it errors.

I really don't know why this is a controversial thread. There's literally no point in supporting an npm package if you can't be arsed to make it basically functional on the first stable release. I understand if you don't want to push a 5.0.1 release across the entire rails ecosystem, but why is it better to leave the package indefinitely broken than to have it a fraction of a version (5.0.0.1) different from rails for a few weeks?

**Comment by javan** [comment] 2016-07-09 15:28
> It is completely broken, out of the box, independent of using Babel.

That's only true if you're trying to use it in node where it wouldn't work anyways because it's designed for the browser. ActionCable uses native DOM APIs like `WebSocket` and `document.querySelector` only present in browser environments.

> It's also obvious why this happens if you read the compiled code. You're compiling each of the source files as a separate (function() { ... }); scope. The first one declares this.ActionCable = { ... } and later ones try to directly access the ActionCable object but it's not scoped correctly so it errors.

That was corrected in https://github.com/rails/rails/pull/25119, but again it's only a problem if you're trying to use it outside of a browser.

> the whole point of an npm package is for me to be able to use it in node requires

I disagree. There are plenty of npm packages intended for browser-only use.

The 5.0.0 release works in the browser, and `var ActionCable = require('actioncable')` works for getting a *reference* to `window.ActionCable`. The next release will work the same, but without setting `window.ActionCable`.

**Comment by javan** [comment] 2016-07-09 15:32
Related: https://github.com/basecamp/trix/issues/119#issuecomment-218318478

**Comment by schneidmaster** [comment] 2016-07-09 16:02
> That's only true if you're trying to use it in node where it wouldn't work anyways because it's designed for the browser. ActionCable uses native DOM APIs like WebSocket and document.querySelector only present in browser environments.

Right, but I should still be able to load the code in a node environment, because

> There are plenty of npm packages intended for browser-only use.

while this is true, the overwhelming majority of those packages assume or rely on a webpack-based flow. If people just want a `<script>` to set a window global they're probably using bower. @alexhanh's use case is an exceptionally common one. (And polluting the global namespace is an antipattern in webpack-based setups anyway.)

> Related: basecamp/trix#119 (comment)

I understand there's some tension between Rails folks and Javascript folks surrounding modules/JS dependency management. But I assume most of the point of releasing an npm package is for people who want to build a standalone frontend that can interact with a Rails API including ActionCable. Seems to defeat the purpose to then not make the package actually work in that context.

But I guess you've made your decision, your project your rules. I'll just go back to maintaining my fork to support the module use case.

**Comment by javan** [comment] 2016-07-09 16:10
The current npm package works with webpack and other module loaders to create a bundle for the browser. Yes, it *also* sets `window.ActionCable`, but there's no need for a separate `<script>` tag. The next release will have improved support, and will allow you to load it in a node environment for "because".

Sorry for the trouble! We have every intention of supporting the npm package. I'm just trying to explain the current situation and why I don't think there's a need to rush out a new npm release ahead of the next Rails release.

**Comment by javan** [comment] 2016-07-09 16:21
To be sure, I just tested with the next release's `action_cable.js` by manually replacing the one in `node_modules/actioncable/lib/assets/compiled/`:
```js
$ node
> require('actioncable')
{ INTERNAL: 
   { message_types: 
      { welcome: 'welcome',
        ping: 'ping',
        confirmation: 'confirm_subscription',
        rejection: 'reject_subscription' },
     default_mount_path: '/cable',
     protocols: [ 'actioncable-v1-json', 'actioncable-unsupported' ] },
  createConsumer: [Function],
  getConfig: [Function],
  createWebSocketURL: [Function],
  startDebugging: [Function],
  stopDebugging: [Function],
  log: [Function],
  ConnectionMonitor: { [Function: ConnectionMonitor] pollInterval: { min: 3, max: 30 }, staleThreshold: 6 },
  Connection: { [Function: Connection] reopenDelay: 500 },
  Subscriptions: [Function: Subscriptions],
  Subscription: [Function: Subscription],
  Consumer: [Function: Consumer] }
```

**Comment by schneidmaster** [comment] 2016-07-09 16:33
Yeah I appreciate the responses! I'm not trying to give you a hard time, I'm just trying to explain why the existing release is a problem for me. It's not great that people have to exclude `actioncable` from babel or other transpilers to avoid throwing an error (just frankly speaking, from the error message it gives, people will assume the `actioncable` package is broken unless they find this thread). But beyond that it's also completely blocking (as you noted) in cases that need to interact with the ActionCable code outside the browser. For example, my package (`action-cable-react`) implements React bindings for ActionCable in part by extending the core CS classes to add functionality; I can't do this if I can't e.g. `{Subscription} = require('actioncable')` in my codebase. Before there was an official npm package back in beta 2 or 3 I just maintained a forked npm package myself; I don't want to wait indefinitely for the new package to be released in order to update my package for Rails 5 stable, so I'll do the same again.

**Comment by danielbastos11** [comment] 2017-09-25 15:01
Any updates on this? It looks to me like the package is still broken.

While my team was able to come up with a workaround, I'd really rather use the ActionCable like I use every other NPM package out there - just install it and use it with Webpack, Babel or whatever I'd like to use.

**Comment by javan** [comment] 2017-09-26 20:20
@danielbastos11, what version of [the npm package](https://www.npmjs.com/package/actioncable) are you using? 5.1.4 (the latest) works fine here as a `require`able module.

**Comment by danielbastos11** [comment] 2017-09-28 17:50
We're using the latest version (5.1.4), running through Webpack.

**Comment by javan** [comment] 2017-09-29 17:28
What's broken for you?  I just tried with a vanilla Webpack setup and it's working fine.
```js
import * as ActionCable from "actioncable"

console.log("ActionCable 5.1.4 running through Webpack ↓")
console.log(ActionCable)
```

<img width="644" alt="screen shot 2017-09-29 at 1 27 06 pm" src="https://user-images.githubusercontent.com/5355/31027890-e83793cc-a519-11e7-9a70-6002614debc9.png">

**Comment by romariolopezc** [comment] 2018-01-02 22:21
I'm also having problems with the usage of the package in node.

```bash
~/Repos/lambda(feature/websocket ✗) node
> require('actioncable')
ReferenceError: window is not defined
<<stacktrace>>
>```

**Comment by guilleiguaran** [comment] 2018-01-02 22:29
@romariolopezc maybe you can use this: https://www.npmjs.com/package/window

**Comment by javan** [comment] 2018-01-02 22:40
> I'm also having problems with the usage of the package in node

The package is designed for the browser, not node. You may be able to get actioncable working with node using a simulated DOM, but we don't plan to support it officially.

**Comment by romariolopezc** [comment] 2018-01-02 22:59
Is as easy to do.
```js
// mock window before usage
window.console = console;
window.WebSocket = ??; // Need an actual websocket library

const ActionCable = require('actioncable');
```

But I don't know what JS websocket package to use? Is it [websocket](https://www.npmjs.com/package/websocket)? or [ws](https://www.npmjs.com/package/ws)?

**Comment by tranvantuanb** [comment] 2018-05-10 08:42
Hi @javan 
I'm working with ReactJS, but I have had problems with ActionCable package.
I ran: npm install actioncable --save => version  5.2.0 in package.json file
But when I import ActionCable from 'actioncable', that rendered to me this problem.
How can I deal with it?
My webpack.config.js:
`module: {
    loaders: [{
      test: /\.jsx?$/,
      loaders: [
        "babel?cacheDirectory",
      ],
    }]
  },`
My .jsx file:
`import ActionCable from "actioncable";`
