### ISSUE TITLE
When running `zeitwerk:check`: undefined method 'eager_load_paths' for I18n::Config

### ISSUE THREAD

**Issue by br3nt** [rails/rails#38931] opened 2020-04-13 01:40 UTC
### Steps to reproduce

1. Start with a Rails 5.2 application
2. Upgrade to Rails 6.0.2
3. Follow instructions from the [Upgrading Ruby on Rails](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) guide:
  1. Run `bin/rails app:update`
  2. Run `bin/rails webpacker:install`. (side note: there is no mention in guide that yarn should be installed)
  3. Run `bin/rails zeitwerk:check`

### Expected behavior

I expect to see the output as displayed in the [Upgrading Ruby on Rails](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) guide.

> Hold on, I am eager loading the application.
> All is good!

### Actual behavior

An incomplete run due to `NoMethodError: undefined method 'eager_load_paths' for #<I18n::Config:0x0000564eea8f1a08>`.

In addition, there are several warnings of `Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call` due to my use of ruby 2.7.

> root@0943e6c6f955:/app# bin/rails zeitwerk:check
> /bundle_cache/ruby/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
> /bundle_cache/ruby/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
> Hold on, I am eager loading the application.
> /bundle_cache/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
> /bundle_cache/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
> /bundle_cache/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/store.rb:106: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
> /bundle_cache/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/store.rb:109: warning: The called method `store_accessor' is defined here
> rails aborted!
> NoMethodError: undefined method `eager_load_paths' for #<I18n::Config:0x0000564eea8f1a08>
> /bundle_cache/ruby/2.7.0/gems/railties-6.0.2.2/lib/rails/tasks/zeitwerk.rake:57:in `block (3 levels) in <main>'
> /bundle_cache/ruby/2.7.0/gems/railties-6.0.2.2/lib/rails/tasks/zeitwerk.rake:56:in `map'
> /bundle_cache/ruby/2.7.0/gems/railties-6.0.2.2/lib/rails/tasks/zeitwerk.rake:56:in `block (2 levels) in <main>'
> /bundle_cache/ruby/2.7.0/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
> /bundle_cache/ruby/2.7.0/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
> /bundle_cache/ruby/2.7.0/gems/railties-6.0.2.2/lib/rails/command.rb:48:in `invoke'
> /bundle_cache/ruby/2.7.0/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
> /bundle_cache/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
> /bundle_cache/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
> /bundle_cache/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
> /bundle_cache/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
> /bundle_cache/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
> /bundle_cache/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
> /bundle_cache/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
> /bundle_cache/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
> bin/rails:4:in `<main>'
> Tasks: TOP => zeitwerk:check
> (See full trace by running task with --trace)

### System configuration
**Rails version**: Rails 6.0.2.2
**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Comment by eugeneius** [comment] 2020-04-13 07:50
This is a duplicate of https://github.com/rails/rails/issues/37966, which was addressed by https://github.com/rails/rails/commit/da28edf9baf0bd83b5308564bdcd8f4673b492bd. It will be fixed in the next release.

**Closed by eugeneius** 2020-04-13 07:50 UTC
Labels: activesupport, railties
