### ISSUE TITLE
Changing reference_id doesn't change reference

### ISSUE THREAD

**Issue by PeizGuo** [rails/rails#18633] opened 2015-01-21 21:54 UTC
Here are the basic information:
```ruby
class User < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :user
end

user1 = User.create!(:name => "User1")
user2 = User.create!(:name => "User2")
Post.create(:content => "Post", :user_id => user1.id) # assume new post id is "1"
```

The first way to change the associated user for post
```ruby
post = Post.find(1)
post.user_id == user1.id # true
post.user.id == user1.id #true

post.user_id = user2.id
post.user_id == user2.id # true
post.user.id == user2.id # true
```

The second way to change the associated user for the post
```ruby
post = user1.posts.find(1)
post.user_id == user1.id # true
post.user.id == user1.id #true

post.user_id = user2.id
post.user_id == user2.id # true
post.user.id == user2.id # false , why? Is this a intention?
```

**Comment by GCorbel** [comment] 2015-01-24 16:51
What is your version of Rails? I tried to reproduce the bug with, on the master branch, this code : 

    def test_reference_id_change_reference
      liquid1 = Liquid.create(:name => 'salty')
      liquid2 = Liquid.create(:name => 'salty')
      molecule = liquid1.molecules.create(:name => 'molecule_1')

      molecule = liquid1.molecules.find(molecule.id)
      assert_equal molecule.liquid_id, liquid1.id
      assert_equal molecule.liquid.id, liquid1.id

      molecule.liquid_id = liquid2.id
      assert_equal molecule.liquid_id, liquid2.id
      assert_equal molecule.liquid.id, liquid2.id
    end

It works. Can you try with the master branch?

**Comment by sgrif** [comment] 2015-01-25 04:19
I also could not duplicate. If I have made an error, please provide a script that can be used to reproduce the issue, using https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb as a template, and I will re-open.

**Comment by PeizGuo** [comment] 2015-01-28 21:01
Here is the code snippet.

```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
  end

  create_table :comments, force: true  do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post1 = Post.create!
    post2 = Post.create!
    comment = Comment.create!(:post => post1)

    # way1
    founded_comment = Comment.find comment.id
    assert_equal post1.id,  founded_comment.post_id
    assert_equal post1.id,  founded_comment.post.id
    founded_comment.post_id = post2.id
    assert_equal post2.id,  founded_comment.post_id
    assert_equal post2.id,  founded_comment.post.id

    # way2
    founded_comment2 = post1.comments.find comment.id # this is the difference
    assert_equal post1.id,  founded_comment2.post_id
    assert_equal post1.id,  founded_comment2.post.id
    founded_comment2.post_id = post2.id
    assert_equal post2.id,  founded_comment2.post_id
    assert_equal post2.id,  founded_comment2.post.id
  end
end
```

**Comment by GCorbel** [comment] 2015-01-28 22:31
I succesfully replicate the issue in a new Ruby file but I cannot duplicate in Rails tests. I will investigate.

**Comment by GCorbel** [comment] 2015-01-28 23:56
The difference if here : 

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/association.rb#L107

In the first case `ActiveRecord::Associations::BelongsToAssociation#invertible_for?` is called. In the other case it's `ActiveRecord::Associations::Association#invertible_for?`. 

If you add `founded_comment2.association(:post).inversed = false` just after the second find, it works as expected.

**Comment by GCorbel** [comment] 2015-01-29 01:16
I need some advice. @sgrif , what you think?
The association is set as inversed and I think it's normal because it's the case. The data is not reloaded because of this line : https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/singular_association.rb#L8.

The association is setted as loaded and not "stale". `stale_target` is true if the association is not inversed and loaded.

Should we reload even if it's inversed? Do you have an idea of a better solution?

**Comment by yasyf** [comment] 2015-01-31 22:43
I tried the following, which fixes the bug in question (by setting `inversed` to `false` on the association), but causes a bunch of test failures, presumably due to extra queries that are generated.

```diff
diff --git a/activerecord/lib/active_record/attribute_methods/dirty.rb b/activerecord/lib/active_record/attribute_methods/dirty.rb
index 06d87ee..701b1c6 100644
--- a/activerecord/lib/active_record/attribute_methods/dirty.rb
+++ b/activerecord/lib/active_record/attribute_methods/dirty.rb
@@ -96,9 +96,16 @@ module ActiveRecord
         result = super
         store_original_raw_attribute(attr)
         save_changed_attribute(attr, old_value)
+        set_inversed_false(attr)
         result
       end
 
+      def set_inversed_false(attr)
+        self.class.reflections
+        .select { |k,v| v.belongs_to? && v.foreign_key == attr }
+        .each_key { |key| association(key.to_sym).inversed = false }
+      end
+
       def raw_write_attribute(attr, value)
         attr = attr.to_s
 ```

**Comment by sgrif** [comment] 2015-02-02 19:41
I'm really not sure whether we should reload when inversed. My immediate reaction is leaning towards no, since normal usage is to assign the association not the id. I think there's additional concerns that we might need to address, as to whether all of the relevant code (particularly in `AutosaveAssociation` still gets run when the id is changed instead of the association itself.

I also have some farther off implementation ideas regarding belongs_to associations which involves moving them to the attributes API, which would fix this as a side effect, but that's not really relevant for the time being as it's months out.

**Comment by sgrif** [comment] 2015-02-02 19:45
I think it could be reasonable to perform the stale state comparison in `stale_target?`, even if `inversed` is true.

**Comment by GCorbel** [comment] 2015-02-02 20:00
So we have to change those lines 
https://github.com/rails/rails/blob/1d6bb77636aeec734079f63e1c14429b34e79ed9/activerecord/lib/active_record/associations/association.rb#L75-L77 by

      def stale_target?
        loaded? && @stale_state != stale_state
      end

I think it's reasonble. Please, let me do the pull request. I will be happy to do a commit for Rails!

**Comment by sgrif** [comment] 2015-02-02 20:12
Well the inversed check is still there for a reason. I'd expect it to be something more along the lines of: `(inversed? || loaded?) && @stale_state != stale_state`. I'd play around with it, and see if the tests pass. You should also make sure you look at the commit which originally added the `!inversed` check there to make sure we aren't missing something from the original intention, and that we have sufficient test coverage for all types of associations here.

**Comment by GCorbel** [comment] 2015-02-02 20:26
You're right. I also have to reproduce the bug in a test. I will check that tonight.

**Comment by GCorbel** [comment] 2015-02-02 20:39
This is the comment which change the code : https://github.com/rails/rails/commit/05b178085a2ad3bf3f2c0dcd1ea40fb5e8c8dc0d. It was changed by @dmitry and approved by @rafaelfranca and @arthurnn. As I said, I will do a pull request tonight. Please, is it possible to revalidate after?

Thanks!

**Comment by sgrif** [comment] 2015-02-02 21:21
Yeah, so as long as `@stale_state == stale_state` returns the right thing when inversed, or is replaced with some code that does the right thing (like looking at the ID of the loaded record), it should be fine to make. Ping me when you've got a PR

**Comment by GCorbel** [comment] 2015-02-03 02:14
I finally reproduce the bug by using the right models. It pass but I think it break another test. I don't have the time to finish it to day. It will go tomorrow.

**Comment by GCorbel** [comment] 2015-02-03 10:30
I think I was wrong. The problem is the following : 

    def test_inversed_instance_should_be_reloaded_if_assigned_by_association_id
      face1 = Face.create
      face2 = Face.create
      new_man = Man.create(face: face1)

      p new_man.association(:face).loaded? # true

      new_man.face_id = face2.id

      p new_man.association(:face).loaded? # true again

      assert_equal new_man.face, face2
    end

The association is loaded even if we reassign the id. I think it should be false. @sgrif what you think?

Now, I try to find a way to find the assocation corresponding to `face_id` in the `new_mane` variable. I'm not sure how to do. I will we explore (and learn) but a little tip can be very useful.

**Comment by GCorbel** [comment] 2015-02-03 12:41
On an assigment of a variable, it's possible to do : 

    # self if new_man
    self.class.reflect_on_all_associations.each do |association|
      association.reset if association.association_foreign_key == field_name # field_name is face_id
    end

It will work but it can create a performance issue. I need your opinion again @sgrif .

**Comment by GCorbel** [comment] 2015-02-04 02:00
To reset the association does not work because it do a SQL request and the record is not saved yet. I'm no longer able to reproduce the original bug. It was failing two days ago but now, when I copy the @PeizGuo 's code, it works. It's strange. I did reverted my modification and it works.

Does someone else can try it?

**Comment by hundredwatt** [comment] 2015-02-12 04:18
I played around with this and it looks like Rails is forcing a choice between:

1. Not reloading inverse associations after a stale state change, as @GCorbel  found in 05b178085a2ad3bf3f2c0dcd1ea40fb5e8c8dc0d
2. Automatically reloading loaded associations after a foreign key change

If we keep the current `stale_target?` implementation, we get 1, but not 2. If we change to `(!inversed? || loaded?) && @stale_state != stale_state` as in #18793, we get 2, but not 1.

Personally, I think the status quo is the right way to go here. If the developer choses to use the underlying plumbing, by changing the foreign key, then the higher level functionality (associations) shouldn't be invoked. Also, I don't see a use case for changing a foreign key and then re-reading the object. Normally, the two would happen in a separate HTTP request, for example, so there would be an inherit reload after writing and before reading.

**Comment by sgrif** [comment] 2015-02-12 14:19
Yeah, this roughly sums up my feelings on the matter as well. I don't think there's a solution at the moment that will solve all sides of this issue.

**Closed by sgrif** 2015-02-12 14:19 UTC
Labels: activerecord, With reproduction steps
