### ISSUE TITLE
Segfault when ",." is typed into bin/rails console

### ISSUE THREAD

**Issue by TheNetyx** [rails/rails#44201] opened 2022-01-19 01:02 UTC
### Steps to reproduce
1. create or open a rails application made with rails 7.0.1  (I've tested this on applications made with rails 7.0.0, doesn't seem to affect them)
2. run `bin/rails console`
3. type anything into the console with ",." in it

### Expected behavior
syntax error

### Actual behavior
segfault

### System configuration
**Rails version**: Rails 7.0.1

**Ruby version**: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by yahonda** [comment] 2022-01-19 04:11
I have reproduced it using Ruby 2.7.0 and also confirmed it does not reproduce with Ruby 2.7.5.
What I can suggest is upgrading the Ruby version to its latest patch releases.

### Steps to reproduce

```ruby
git clone https://github.com/yahonda/sample44201
cd sample44201
bundle install
bin/rails c
```

### Result with Ruby 2.7.5
```
irb(main):001:0> ,.
Traceback (most recent call last):
/home/yahonda/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/irb-1.4.1/lib/irb/workspace.rb:119:in `eval': (irb):1: syntax error, unexpected ',' (SyntaxError)
irb(main):002:0>
```

### Result with Ruby 2.7.0

```
$ bin/rails c
Loading development environment (Rails 7.0.1)
irb(main):001:0> ,.
<internal:trace_point>:346: [BUG] Segmentation fault at 0x0000000000000008
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
... snip ...
```
I do not add stack trace information here because it is too long and not worth adding stack trace which is already fixed by the newer versions of Ruby. I just wanted to say it reproduced with Ruby 2.7.0.

**Closed** 2022-01-20 01:52 UTC
