### ISSUE TITLE
If you set after_destroy_commit && after_create_commit calling the same method. Only one fires.

### ISSUE THREAD

**Issue by ConfusedVorlon** [rails/rails#51171] opened 2024-02-22 19:45 UTC
### Steps to reproduce

have `after_destroy_commit` and `after_create_commit` callbacks calling the same method

```
    after_destroy_commit :increment_count
    after_create_commit :increment_count
```

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :foos, force: true do |t|
  end

  create_table :bars, force: true do |t|
  end
  
  create_table :counters, force: true do |t|
      t.integer :count, default: 0
  end
end

class Foo < ActiveRecord::Base
    
    after_destroy_commit :increment_count
    after_create_commit :increment_count
        
    def increment_count
      counter = Counter.first
      counter.count = counter.count + 1
      counter.save
    end
end

class Bar < ActiveRecord::Base
    
    after_destroy_commit :increment_count_a
    after_create_commit :increment_count_b
        

    def increment_count_a
      counter = Counter.first
      counter.count = counter.count + 1
      counter.save
    end
        
    def increment_count_b
      counter = Counter.first
      counter.count = counter.count + 1
      counter.save
    end
end

class Counter < ActiveRecord::Base

end


class BugTest < Minitest::Test
    
  def test_callbacks_on_shared_method
      
    counter = Counter.create!
      
    assert_equal 0, counter.reload.count
    
    foo = Foo.create!

    assert_equal 1, counter.reload.count
    
    foo.destroy
    
    assert_equal 2, counter.reload.count
  end

  #Just for good measure - passing test where the only difference is that callbacks call different methods
  def test_callbacks_on_different_method
      
    counter = Counter.create!
      
    assert_equal 0, counter.reload.count
    
    bar = Bar.create!

    assert_equal 1, counter.reload.count
    
    bar.destroy
    
    assert_equal 2, counter.reload.count
  end

end

```

### Expected behavior

Both callbacks fire

### Actual behavior

Only the second callback fires `after_create_commit` in this example

The root of this seems to be that both callbacks are aliases for after_commit - which then presumably uses the called method as a key in some way.
However, this conflict is both surprising - and (as far as I can tell) not warned about in the docs. 

### System configuration
**Rails version**:

Installing rails 7.1.3.2

**Ruby version**:
3.3.0

**Comment by rafaelfranca** [comment] 2024-02-22 20:17
Duplicate of #40648

**Closed by rafaelfranca** 2024-02-22 20:17 UTC

**Comment by ConfusedVorlon** [comment] 2024-02-23 11:40
Thanks for the quick response.

> A pull request to document this would more than welcome

Happy to do that. Would appreciate some pointers if you have the time.

> Just note that this can happen with any callback.

I'm seeing this specifically for after_commit because it is a shortcut with a 'hidden' :on option
Are there other callbacks where there is a non-obvious sharing? (I can't see any)

I was thinking to add a note in the caveats section here:
https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html

Would it be excessive to note on each shortcut that it is deduplicated at the after_commit level?


https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/activerecord/lib/active_record/transactions.rb#L244

```
# Shortcut for <tt>after_commit :hook, on: :create</tt>. 
# nb: this callback is deduplicated at the after_commit level
```

**Comment by rafaelfranca** [comment] 2024-02-23 19:58
I think that would be fine. I'd just give example as well to explain what `deduplicated` means
