### ISSUE TITLE
Creating a new Rails application using `rails new` results in error

### ISSUE THREAD

**Issue by keesbriggs** [rails/rails#38925] opened 2020-04-11 21:22 UTC
### Steps to reproduce
```
KeesB-MBP:coding-exercise keesbriggs$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]
KeesB-MBP:coding-exercise keesbriggs$ rails -v
Rails 6.0.2.2
KeesB-MBP:coding-exercise keesbriggs$ rails new acme-hs-course-grades
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/keesbriggs/Sites/coding-exercise/acme-hs-course-grades/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
Traceback (most recent call last):
	49: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
	48: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
	47: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/bin/rails:23:in `<main>'
	46: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/bin/rails:23:in `load'
	45: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/exe/rails:10:in `<top (required)>'
	44: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	43: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	42: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/cli.rb:18:in `<top (required)>'
	41: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/command.rb:46:in `invoke'
	40: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/command/base.rb:69:in `perform'
	39: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	38: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	37: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	36: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/commands/application/application_command.rb:26:in `perform'
	35: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	34: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	33: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	32: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	31: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	30: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	29: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	28: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	27: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/generators/rails/app/app_generator.rb:319:in `create_config_files'
	26: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/generators/app_base.rb:156:in `build'
	25: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/generators/rails/app/app_generator.rb:106:in `config'
	24: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/generators/rails/app/app_generator.rb:19:in `inside'
	23: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions.rb:187:in `inside'
	22: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:122:in `cd'
	21: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/fileutils.rb:122:in `chdir'
	20: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions.rb:187:in `block in inside'
	19: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/generators/rails/app/app_generator.rb:115:in `block in config'
	18: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/generators/rails/app/app_generator.rb:19:in `directory'
	17: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/directory.rb:52:in `directory'
	16: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions.rb:93:in `action'
	15: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/directory.rb:66:in `invoke!'
	14: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/directory.rb:80:in `execute!'
	13: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/directory.rb:80:in `each'
	12: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/directory.rb:92:in `block in execute!'
	11: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:122:in `template'
	10: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:25:in `create_file'
	 9: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions.rb:93:in `action'
	 8: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	 7: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:117:in `invoke_with_conflict_check'
	 6: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `block in invoke!'
	 5: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `open'
	 4: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `block (2 levels) in invoke!'
	 3: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:53:in `render'
	 2: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:131:in `block in template'
	 1: from /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/erb.rb:885:in `result'
/Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/erb.rb:885:in `eval': /Users/keesbriggs/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.2/lib/rails/generators/rails/app/templates/config/environments/test.rb.tt:10: syntax error, unexpected ')', expecting end-of-input (SyntaxError)
);  if spring_install? 
^
KeesB-MBP:coding-exercise keesbriggs$
 ```

### Expected behavior
The `rails new` call should not error

### Actual behavior
see above

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.5.0

**Comment by eugeneius** [comment] 2020-04-11 22:08
This is a duplicate of https://github.com/rails/rails/issues/38639, which has been fixed by https://github.com/rails/rails/pull/38642 but not released yet. That said, the easiest way to avoid the error is to use a newer patch version of Ruby 2.5, or Ruby 2.6.

**Closed by eugeneius** 2020-04-11 22:08 UTC
