### ISSUE TITLE
ActiveRecord .last and ActiveRecord .last(1) return different results

### ISSUE THREAD

**Issue by konung** [rails/rails#19118] opened 2015-02-28 01:54 UTC
I posted this a question on http://stackoverflow.com/questions/28678611/activerecord-last-and-activerecord-last1-return-different-results , but I'm thinking this might be a bug

Using ActiveRecord 4.2 with MySQL 5.5 using pry console. I don't overwrite last anywhere in my code. I try to stay clear from rails & ruby reserved words unless I want to modify behavior. 

I have a model called Product.

Running `Product.last` in console - I get the FIRST record in  the table ( with id 1 and updated_at in 2013) 

Running `Product.last(1)` - I get the LAST record in the table with id (122039) and updated_at  in Feb 2015.

I was under impression that they should return the same. Why would `Product.last` return  the result of `Product.first` ?

P.S.:
This is a dev database. So I destroyed it and re-migrated it and re-seeded all the data. Don't know if it matters, but to speed up seeding processes (since I seed some tables with 100,000s of rows of production-grade data) - I seed from .sql files using bulk insert & `ActiveRecord::Base.connection.execute(sql_from_file)`

**UPDATE**

Having done a comparison ( see 2 edits below) it seems that Product.last doesn't do `order by id desc`, while the Product.last(1) does it actually.  Any ideas why?

From logs:
````ruby
 Product.last (1)
````
````sql
        SELECT DISTINCT 
      `products`.`id` 
    FROM
      `products` 
      LEFT OUTER JOIN `restrictions` 
        ON `restrictions`.`id` = `products`.`distribution_restriction_id` 
        AND `restrictions`.`type` IN ('DistributionRestriction') 
      LEFT OUTER JOIN `vendors` 
        ON `vendors`.`id` = `products`.`vendor_id` 
      LEFT OUTER JOIN `manufacturers` 
        ON `manufacturers`.`id` = `products`.`manufacturer_id` 
      LEFT OUTER JOIN `categories` 
        ON `categories`.`id` = `products`.`category_id` 
        AND `categories`.`type` IN ('ProductCategory') 
      LEFT OUTER JOIN `products_restrictions` 
        ON `products_restrictions`.`product_id` = `products`.`id` 
      LEFT OUTER JOIN `restrictions` `restrictions_products` 
        ON `restrictions_products`.`id` = `products_restrictions`.`restriction_id` 
        AND `restrictions_products`.`type` IN ('ProductRestriction') 
      LEFT OUTER JOIN `categories` `departments_products` 
        ON `departments_products`.`id` = `products`.`department_id` 
        AND `departments_products`.`type` IN ('Department') 
      LEFT OUTER JOIN `comments` 
        ON `comments`.`commentable_id` = `products`.`id` 
        AND `comments`.`commentable_type` = 'Product' 
      LEFT OUTER JOIN `pictures` 
        ON `pictures`.`picturable_id` = `products`.`id` 
        AND `pictures`.`picturable_type` = 'Product' 
    ORDER BY `products`.`id` DESC 
    LIMIT 1 ;

    SELECT 
      `products`.`id` AS t0_r0,
      `products`.`name` AS t0_r1,
      `products`.`client_number` AS t0_r2,
      `products`.`client_reference_string` AS t0_r3,
      `products`.`client_id` AS t0_r4,
      `products`.`vendor_number` AS t0_r5,
      `products`.`vendor_reference_string` AS t0_r6,
      `products`.`vendor_id` AS t0_r7,
      `products`.`manufacturer_number` AS t0_r8,
      `products`.`manufacturer_reference_string` AS t0_r9,
      `products`.`manufacturer_id` AS t0_r10,
      `products`.`reman_number` AS t0_r11,
      `products`.`superseded_by_id` AS t0_r12,
      `products`.`description` AS t0_r13,
      `products`.`category_id` AS t0_r14,
      `products`.`first_year_used` AS t0_r15,
      `products`.`last_year_used` AS t0_r16,
      `products`.`reorder_level` AS t0_r17,
      `products`.`minimum_order_quantity` AS t0_r18,
      `products`.`total_stock` AS t0_r19,
      `products`.`stock_details` AS t0_r20,
      `products`.`status` AS t0_r21,
      `products`.`discontinued_at` AS t0_r22,
      `products`.`currency` AS t0_r23,
      `products`.`dealer_exchange_amount_cents` AS t0_r24,
      `products`.`dealer_sale_amount_cents` AS t0_r25,
      `products`.`retail_exchange_amount_cents` AS t0_r26,
      `products`.`retail_sale_amount_cents` AS t0_r27,
      `products`.`cost_amount_cents` AS t0_r28,
      `products`.`core_charge_amount_cents` AS t0_r29,
      `products`.`reman_amount_cents` AS t0_r30,
      `products`.`out_of_warranty` AS t0_r31,
      `products`.`backordered_till` AS t0_r32,
      `products`.`repair_only` AS t0_r33,
      `products`.`publicly_visible` AS t0_r34,
      `products`.`period_usage` AS t0_r35,
      `products`.`distribution_restriction_id` AS t0_r36,
      `products`.`department_id` AS t0_r37,
      `products`.`stats` AS t0_r38,
      `products`.`announcement_date` AS t0_r39,
      `products`.`status_with_vendor` AS t0_r40,
      `products`.`masterfile_details` AS t0_r41,
      `products`.`created_at` AS t0_r42,
      `products`.`updated_at` AS t0_r43,
      `restrictions`.`id` AS t1_r0,
      `restrictions`.`name` AS t1_r1,
      `restrictions`.`code` AS t1_r2,
      `restrictions`.`description` AS t1_r3,
      `restrictions`.`severity` AS t1_r4,
      `restrictions`.`begins_at` AS t1_r5,
      `restrictions`.`expires_at` AS t1_r6,
      `restrictions`.`type` AS t1_r7,
      `restrictions`.`created_at` AS t1_r8,
      `restrictions`.`updated_at` AS t1_r9,
      `vendors`.`id` AS t2_r0,
      `vendors`.`name` AS t2_r1,
      `vendors`.`code` AS t2_r2,
      `vendors`.`created_at` AS t2_r3,
      `vendors`.`updated_at` AS t2_r4,
      `manufacturers`.`id` AS t3_r0,
      `manufacturers`.`name` AS t3_r1,
      `manufacturers`.`code` AS t3_r2,
      `manufacturers`.`created_at` AS t3_r3,
      `manufacturers`.`updated_at` AS t3_r4,
      `categories`.`id` AS t4_r0,
      `categories`.`name` AS t4_r1,
      `categories`.`code` AS t4_r2,
      `categories`.`description` AS t4_r3,
      `categories`.`type` AS t4_r4,
      `categories`.`category_id` AS t4_r5,
      `categories`.`created_at` AS t4_r6,
      `categories`.`updated_at` AS t4_r7,
      `restrictions_products`.`id` AS t5_r0,
      `restrictions_products`.`name` AS t5_r1,
      `restrictions_products`.`code` AS t5_r2,
      `restrictions_products`.`description` AS t5_r3,
      `restrictions_products`.`severity` AS t5_r4,
      `restrictions_products`.`begins_at` AS t5_r5,
      `restrictions_products`.`expires_at` AS t5_r6,
      `restrictions_products`.`type` AS t5_r7,
      `restrictions_products`.`created_at` AS t5_r8,
      `restrictions_products`.`updated_at` AS t5_r9,
      `departments_products`.`id` AS t6_r0,
      `departments_products`.`name` AS t6_r1,
      `departments_products`.`code` AS t6_r2,
      `departments_products`.`description` AS t6_r3,
      `departments_products`.`type` AS t6_r4,
      `departments_products`.`category_id` AS t6_r5,
      `departments_products`.`created_at` AS t6_r6,
      `departments_products`.`updated_at` AS t6_r7,
      `comments`.`id` AS t7_r0,
      `comments`.`title` AS t7_r1,
      `comments`.`body` AS t7_r2,
      `comments`.`author_id` AS t7_r3,
      `comments`.`category` AS t7_r4,
      `comments`.`commentable_id` AS t7_r5,
      `comments`.`commentable_type` AS t7_r6,
      `comments`.`created_at` AS t7_r7,
      `comments`.`updated_at` AS t7_r8,
      `pictures`.`id` AS t8_r0,
      `pictures`.`name` AS t8_r1,
      `pictures`.`title` AS t8_r2,
      `pictures`.`path` AS t8_r3,
      `pictures`.`picturable_id` AS t8_r4,
      `pictures`.`picturable_type` AS t8_r5,
      `pictures`.`category` AS t8_r6,
      `pictures`.`created_at` AS t8_r7,
      `pictures`.`updated_at` AS t8_r8 
    FROM
      `products` 
      LEFT OUTER JOIN `restrictions` 
        ON `restrictions`.`id` = `products`.`distribution_restriction_id` 
        AND `restrictions`.`type` IN ('DistributionRestriction') 
      LEFT OUTER JOIN `vendors` 
        ON `vendors`.`id` = `products`.`vendor_id` 
      LEFT OUTER JOIN `manufacturers` 
        ON `manufacturers`.`id` = `products`.`manufacturer_id` 
      LEFT OUTER JOIN `categories` 
        ON `categories`.`id` = `products`.`category_id` 
        AND `categories`.`type` IN ('ProductCategory') 
      LEFT OUTER JOIN `products_restrictions` 
        ON `products_restrictions`.`product_id` = `products`.`id` 
      LEFT OUTER JOIN `restrictions` `restrictions_products` 
        ON `restrictions_products`.`id` = `products_restrictions`.`restriction_id` 
        AND `restrictions_products`.`type` IN ('ProductRestriction') 
      LEFT OUTER JOIN `categories` `departments_products` 
        ON `departments_products`.`id` = `products`.`department_id` 
        AND `departments_products`.`type` IN ('Department') 
      LEFT OUTER JOIN `comments` 
        ON `comments`.`commentable_id` = `products`.`id` 
        AND `comments`.`commentable_type` = 'Product' 
      LEFT OUTER JOIN `pictures` 
        ON `pictures`.`picturable_id` = `products`.`id` 
        AND `pictures`.`picturable_type` = 'Product' 
    WHERE `products`.`id` IN (122039) 
    ORDER BY `products`.`id` DESC 
````  

vs second 

````ruby
 Product.last
````

````sql
    SQL (2.1 ms) 
    SELECT DISTINCT 
      `products`.`id` 
    FROM
      `products` 
      LEFT OUTER JOIN `restrictions` 
        ON `restrictions`.`id` = `products`.`distribution_restriction_id` 
        AND `restrictions`.`type` IN ('DistributionRestriction') 
      LEFT OUTER JOIN `vendors` 
        ON `vendors`.`id` = `products`.`vendor_id` 
      LEFT OUTER JOIN `manufacturers` 
        ON `manufacturers`.`id` = `products`.`manufacturer_id` 
      LEFT OUTER JOIN `categories` 
        ON `categories`.`id` = `products`.`category_id` 
        AND `categories`.`type` IN ('ProductCategory') 
      LEFT OUTER JOIN `products_restrictions` 
        ON `products_restrictions`.`product_id` = `products`.`id` 
      LEFT OUTER JOIN `restrictions` `restrictions_products` 
        ON `restrictions_products`.`id` = `products_restrictions`.`restriction_id` 
        AND `restrictions_products`.`type` IN ('ProductRestriction') 
      LEFT OUTER JOIN `categories` `departments_products` 
        ON `departments_products`.`id` = `products`.`department_id` 
        AND `departments_products`.`type` IN ('Department') 
      LEFT OUTER JOIN `comments` 
        ON `comments`.`commentable_id` = `products`.`id` 
        AND `comments`.`commentable_type` = 'Product' 
      LEFT OUTER JOIN `pictures` 
        ON `pictures`.`picturable_id` = `products`.`id` 
        AND `pictures`.`picturable_type` = 'Product' 
    LIMIT 1 ;
    
    SELECT 
      `products`.`id` AS t0_r0,
      `products`.`name` AS t0_r1,
      `products`.`client_number` AS t0_r2,
      `products`.`client_reference_string` AS t0_r3,
      `products`.`client_id` AS t0_r4,
      `products`.`vendor_number` AS t0_r5,
      `products`.`vendor_reference_string` AS t0_r6,
      `products`.`vendor_id` AS t0_r7,
      `products`.`manufacturer_number` AS t0_r8,
      `products`.`manufacturer_reference_string` AS t0_r9,
      `products`.`manufacturer_id` AS t0_r10,
      `products`.`reman_number` AS t0_r11,
      `products`.`superseded_by_id` AS t0_r12,
      `products`.`description` AS t0_r13,
      `products`.`category_id` AS t0_r14,
      `products`.`first_year_used` AS t0_r15,
      `products`.`last_year_used` AS t0_r16,
      `products`.`reorder_level` AS t0_r17,
      `products`.`minimum_order_quantity` AS t0_r18,
      `products`.`total_stock` AS t0_r19,
      `products`.`stock_details` AS t0_r20,
      `products`.`status` AS t0_r21,
      `products`.`discontinued_at` AS t0_r22,
      `products`.`currency` AS t0_r23,
      `products`.`dealer_exchange_amount_cents` AS t0_r24,
      `products`.`dealer_sale_amount_cents` AS t0_r25,
      `products`.`retail_exchange_amount_cents` AS t0_r26,
      `products`.`retail_sale_amount_cents` AS t0_r27,
      `products`.`cost_amount_cents` AS t0_r28,
      `products`.`core_charge_amount_cents` AS t0_r29,
      `products`.`reman_amount_cents` AS t0_r30,
      `products`.`out_of_warranty` AS t0_r31,
      `products`.`backordered_till` AS t0_r32,
      `products`.`repair_only` AS t0_r33,
      `products`.`publicly_visible` AS t0_r34,
      `products`.`period_usage` AS t0_r35,
      `products`.`distribution_restriction_id` AS t0_r36,
      `products`.`department_id` AS t0_r37,
      `products`.`stats` AS t0_r38,
      `products`.`announcement_date` AS t0_r39,
      `products`.`status_with_vendor` AS t0_r40,
      `products`.`masterfile_details` AS t0_r41,
      `products`.`created_at` AS t0_r42,
      `products`.`updated_at` AS t0_r43,
      `restrictions`.`id` AS t1_r0,
      `restrictions`.`name` AS t1_r1,
      `restrictions`.`code` AS t1_r2,
      `restrictions`.`description` AS t1_r3,
      `restrictions`.`severity` AS t1_r4,
      `restrictions`.`begins_at` AS t1_r5,
      `restrictions`.`expires_at` AS t1_r6,
      `restrictions`.`type` AS t1_r7,
      `restrictions`.`created_at` AS t1_r8,
      `restrictions`.`updated_at` AS t1_r9,
      `vendors`.`id` AS t2_r0,
      `vendors`.`name` AS t2_r1,
      `vendors`.`code` AS t2_r2,
      `vendors`.`created_at` AS t2_r3,
      `vendors`.`updated_at` AS t2_r4,
      `manufacturers`.`id` AS t3_r0,
      `manufacturers`.`name` AS t3_r1,
      `manufacturers`.`code` AS t3_r2,
      `manufacturers`.`created_at` AS t3_r3,
      `manufacturers`.`updated_at` AS t3_r4,
      `categories`.`id` AS t4_r0,
      `categories`.`name` AS t4_r1,
      `categories`.`code` AS t4_r2,
      `categories`.`description` AS t4_r3,
      `categories`.`type` AS t4_r4,
      `categories`.`category_id` AS t4_r5,
      `categories`.`created_at` AS t4_r6,
      `categories`.`updated_at` AS t4_r7,
      `restrictions_products`.`id` AS t5_r0,
      `restrictions_products`.`name` AS t5_r1,
      `restrictions_products`.`code` AS t5_r2,
      `restrictions_products`.`description` AS t5_r3,
      `restrictions_products`.`severity` AS t5_r4,
      `restrictions_products`.`begins_at` AS t5_r5,
      `restrictions_products`.`expires_at` AS t5_r6,
      `restrictions_products`.`type` AS t5_r7,
      `restrictions_products`.`created_at` AS t5_r8,
      `restrictions_products`.`updated_at` AS t5_r9,
      `departments_products`.`id` AS t6_r0,
      `departments_products`.`name` AS t6_r1,
      `departments_products`.`code` AS t6_r2,
      `departments_products`.`description` AS t6_r3,
      `departments_products`.`type` AS t6_r4,
      `departments_products`.`category_id` AS t6_r5,
      `departments_products`.`created_at` AS t6_r6,
      `departments_products`.`updated_at` AS t6_r7,
      `comments`.`id` AS t7_r0,
      `comments`.`title` AS t7_r1,
      `comments`.`body` AS t7_r2,
      `comments`.`author_id` AS t7_r3,
      `comments`.`category` AS t7_r4,
      `comments`.`commentable_id` AS t7_r5,
      `comments`.`commentable_type` AS t7_r6,
      `comments`.`created_at` AS t7_r7,
      `comments`.`updated_at` AS t7_r8,
      `pictures`.`id` AS t8_r0,
      `pictures`.`name` AS t8_r1,
      `pictures`.`title` AS t8_r2,
      `pictures`.`path` AS t8_r3,
      `pictures`.`picturable_id` AS t8_r4,
      `pictures`.`picturable_type` AS t8_r5,
      `pictures`.`category` AS t8_r6,
      `pictures`.`created_at` AS t8_r7,
      `pictures`.`updated_at` AS t8_r8 
    FROM
      `products` 
      LEFT OUTER JOIN `restrictions` 
        ON `restrictions`.`id` = `products`.`distribution_restriction_id` 
        AND `restrictions`.`type` IN ('DistributionRestriction') 
      LEFT OUTER JOIN `vendors` 
        ON `vendors`.`id` = `products`.`vendor_id` 
      LEFT OUTER JOIN `manufacturers` 
        ON `manufacturers`.`id` = `products`.`manufacturer_id` 
      LEFT OUTER JOIN `categories` 
        ON `categories`.`id` = `products`.`category_id` 
        AND `categories`.`type` IN ('ProductCategory') 
      LEFT OUTER JOIN `products_restrictions` 
        ON `products_restrictions`.`product_id` = `products`.`id` 
      LEFT OUTER JOIN `restrictions` `restrictions_products` 
        ON `restrictions_products`.`id` = `products_restrictions`.`restriction_id` 
        AND `restrictions_products`.`type` IN ('ProductRestriction') 
      LEFT OUTER JOIN `categories` `departments_products` 
        ON `departments_products`.`id` = `products`.`department_id` 
        AND `departments_products`.`type` IN ('Department') 
      LEFT OUTER JOIN `comments` 
        ON `comments`.`commentable_id` = `products`.`id` 
        AND `comments`.`commentable_type` = 'Product' 
      LEFT OUTER JOIN `pictures` 
        ON `pictures`.`picturable_id` = `products`.`id` 
        AND `pictures`.`picturable_type` = 'Product' 
    WHERE `products`.`id` IN (1)

````
````ruby
      default_scope {eager_load([:distribution_restriction, :vendor, :manufacturer, :category, :restrictions, :department, :comments, :pictures])}
````

**Comment by laurocaetano** [comment] 2015-02-28 15:56
Have you tried it in a brand new app using Rails 4.2?

I have tried here and the behaviour is correct:

```
test_last $ rails g model Post name:string title:string count:integer
      invoke  active_record
      create    db/migrate/20150228154940_create_posts.rb
      create    app/models/post.rb
      invoke    test_unit
      create      test/models/post_test.rb
      create      test/fixtures/posts.yml
test_last $ rake db:create
test_last $ rake db:migrate
== 20150228154940 CreatePosts: migrating ======================================
-- create_table(:posts)
   -> 0.0300s
== 20150228154940 CreatePosts: migrated (0.0301s) =============================

test_last $ bin/rails c
Loading development environment (Rails 4.2.0)
irb(main):001:0> Post.last
  Post Load (0.3ms)  SELECT  `posts`.* FROM `posts`  ORDER BY `posts`.`id` DESC LIMIT 1
=> nil
irb(main):002:0> Post.last(1)
  Post Load (0.4ms)  SELECT  `posts`.* FROM `posts`  ORDER BY `posts`.`id` DESC LIMIT 1
=> []
irb(main):003:0>
```

As you can see, the query is the same. It could be something changing the default behaviour (gem or other thing).

**Comment by maveonair** [comment] 2015-02-28 16:36
@konung Can you please post the queries without having a defined default_scope?

**Comment by konung** [comment] 2015-03-01 21:36
Indeed it seems that eager_load in default_scope is messing with the order. 

With `default_scope` commented out

````sql
Product.last(1); Product.last; nil
D, [2015-03-01T20:02:34.298289 #8998] DEBUG -- :   Product Load (0.6ms)  SELECT
 `products`.* FROM `products`  ORDER BY `products`.`id` DESC LIMIT 1
D, [2015-03-01T20:02:34.299236 #8998] DEBUG -- :   Product Load (0.4ms)  SELECT
 `products`.* FROM `products`  ORDER BY `products`.`id` DESC LIMIT 1
````

I experimented a little bit and it seems that I can't use eager_load within default_scope, without messing up how last works.
It still seems like a bug. I mean I can work around it by either explicitly calling .last(1) or redefine  default_scope as a method, and add some checking to add proper order_by if the caller is `last`, but it's not obvious and error prone. 

The reason I want to use eager_load withing default_scope, is that by default I actually want to load all those other belongs_to relationships, but I have several scopes where I don't want to eager_load anything, as I'm dealing directly with the Product table only.  Now since eager_load is class wide, every time I need to do anything, eager_load will get called. With some of the more intensive tasks that's extra unnecessary load.

Am I missing something?

**Comment by konung** [comment] 2015-03-01 22:00
Ok so it seems that's something needs to be kept in mind and maybe mentioned in the docs, that eager_loading messes up ordering in .last()

I tried  this
`  scope :include_all, -> {eager_load([:distribution_restriction, :vendor, :manufacturer, :category, :restrictions, :department, :comments, :pictures])}
`

And then 
` Product.include_all.last` & `Product.include_all.last(1)`

As with my original problem  eager_loading - messed up ordering in the first case.

**Comment by maveonair** [comment] 2015-03-02 08:25
@konung I guess it should return of course the same result. Have you already checked the Rails code and which Rails version do you use?

**Comment by sgrif** [comment] 2015-03-02 16:41
Can you please provide a test script that we can use to reproduce the error, and that shows the expected behavior, using https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb as a template?

**Comment by konung** [comment] 2015-03-03 17:48
@maveonair  as I said "Using ActiveRecord 4.2 with MySQL 5.5 using pry console. I don't overwrite last anywhere in my code. I try to stay clear from rails & ruby reserved words unless I want to modify behavior."   I'm not using Rails full stack, just activesupport & activerecord, inside https://github.com/rightscale/praxis  but it shouldn't matter, I think? I'm not using any "rails" special sauce,  just the ORM within POROs

**Comment by konung** [comment] 2015-03-03 17:49
@sgrif  - I'll try to do this later this week, as I get a bit of breathing room. We only noticed this in production system, and I was trying to come up with a fix asap. I'll come up with a sample and submit it later.

**Comment by konung** [comment] 2015-03-06 00:47
I've tried to recreate the same setup I have using active_record_master mentioned above - I can't reproduce the bug. It's doesn't happen on any other Models either. 

Don't know what else to try.

**Comment by sgrif** [comment] 2015-03-06 00:48
Its probably a bug in your code then. Closing as unable to reproduce.

**Closed by sgrif** 2015-03-06 00:48 UTC
Labels: activerecord
