### ISSUE TITLE
ActionText: renders raw html when using slim-rails. Rails 6.0.0rc2 & ruby 2.5.5

### ISSUE THREAD

**Issue by pinzonjulian** [rails/rails#36955] opened 2019-08-16 20:09 UTC
### Steps to reproduce

1. Download or fork this fresh rails app: https://github.com/pinzonjulian/rails_6_active_text_slim. This app uses rails 6.0.0rc2 and ruby 2.5.5.
2. run `rails db:migrate`
3. run `rails s`
4. go to `localhost:3000/posts/new`
5. create a new post with title and a body. Use at least one of the action text modifiers (eg. bold) to make the example more obvious.
6. Go to `localhost:3000/posts/1` and see that `@post.body` is rendered correctly
7. go to `localhost:3000/posts/1/show_slim` and see that `@post.body` is rendered incorrectly

When you visit `localhost:3000/post/:id` the templating engine is ERB while visiting `localhost:3000/post/:id/show_slim` uses SLIM. In the first example, calling `@post.body` renders the "html_safe" version of the ActionText object whereas the second shows the raw html.

### Expected behavior
ActionText should behave the same using SLIM as when using ERB

### Actual behavior
It renders the raw html.

### System configuration
**Rails version**:
`6.0.0rc2 & 6.0.0-stable`
**Ruby version**:
`2.5.5`
**Gems installed**
`slim-rails`

**Comment by bugtender** [comment] 2019-08-21 00:05
I think the problem is when slim render ActionText it will be escaping characters included.

<img width="706" alt="Screen Shot 2019-08-21 at 12 57 15 AM" src="https://user-images.githubusercontent.com/5573816/63392442-a5820c00-c3ae-11e9-834f-10ddf0bcc2ea.png">

You can change 
```ruby
# show_slim.slim
div
  = @post.body
```
to 
```ruby
div
  == @post.body
```

Or you can use render partial like [this post](https://tech.mof-mof.co.jp/blog/rails6-actiontext.html).

Hope this helps!

**Comment by zzak** [comment] 2021-06-02 11:10
I _think_ this is no longer a problem, and we could close it (that is unless there is some way to re-generate this bug..) 🤔

**Closed** 2021-06-02 12:53 UTC
Labels: With reproduction steps, actiontext
