### ISSUE TITLE
Images saved via using ActiveStorage different in production and development environments

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#45506] opened 2022-07-01 14:03 UTC
### Expected behavior
In both environments same behavior

### Actual behavior
In development environment saved (attach) image in content-page within `gem ckeditor` using `ActiveStorage` with `mini_magick` - then in production environment image are not showed, and vice versa - saved in production, then are not showed in development. I use **same database** (mysql) in development and production environments.

### System configuration
- **Ruby version**: 3.1.2
- **Rails version**: 7.0.3
- gem [ckeditor](https://github.com/galetahub/ckeditor) 5.1.1

In production mode I use config: 
```ruby
config.assets.compile = true
config.active_storage.service = :local
config.active_storage.variant_processor = :mini_magick
```
in development:
```ruby
config.active_storage.service = :local
config.active_storage.variant_processor = :mini_magick
```

saved image in source code of page show like this:
```
<img alt="" src="/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68a08d9de8f843ecd8b5c5be61d33859a3333bb7/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1Rnd01ENEdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--2ccbd7d12a252e03eb26bb2401505e4efaeff669/7d85fe9c160bb2f3b559a45303cc8ce4.jpg" style="width: 700px; height: 475px;" />
```

### The problem, most likely, is in the ActiveStorage, because the `gem ckeditor` works correctly with other configurations

**Comment by rafaelfranca** [comment] 2022-07-04 16:59
Closing since the issue is on sprockets-rails

**Closed by rafaelfranca** 2022-07-04 16:59 UTC
