### ISSUE TITLE
An error pointing to action_controller/test_case.rb when use rspec

### ISSUE THREAD

**Issue by jiajiawang** [rails/rails#20916] opened 2015-07-17 15:27 UTC
Met an error when use rspec
https://github.com/rspec/rspec-core/issues/2034

`@_layouts` becomes nil
https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/test_case.rb#L30

**Comment by rafaelfranca** [comment] 2015-07-17 15:35
Thank you for the report. This looks like a RSpec issue even that the exception point to rails code so I'm closing since you already reported there. If they found that the problem is in Rails or you can reproduce it without RSpec please let us know.

**Closed by rafaelfranca** 2015-07-17 15:35 UTC
