### ISSUE TITLE
number_to_currency shouldn't use a simple space, use nbsp instead.

### ISSUE THREAD

**Issue by estani** [rails/rails#37912] opened 2019-12-08 12:09 UTC
### Summary 
The problem was already mentioned in  [the docs in 2008](https://apidock.com/rails/ActionView/Helpers/NumberHelper/number_to_currency#259-number-to-euro).
There is no valid scenario where a symbol should be separated from the amount it describes, it's as bad as breaking the number itself, so this behavior should be finally addressed, imho.

### Steps to reproduce
Use some locale where the currency symbol has a space in it, like `de`
```ruby
HTMLEntities.new.encode(Class.new.extend(ActionView::Helpers::NumberHelper).number_to_currency(12, locale: 'de'), :named)
=> "12,00 &euro;"
```
Because of the simple space the semantic is:
> if needed is ok to separate "12,00" from "&euro;"

which is not true.

### Expected behavior
The space need to be considered part of the symbol so it should be a non-breaking space.
The expected result should be: `12,00&nbsp;&euro;`

### Work around
Replacing the space by `nbsp` would sort it out (a proven work around for over 11 years):
```ruby
HTMLEntities.new.encode(Class.new.extend(ActionView::Helpers::NumberHelper).number_to_currency(12, locale: 'de').gsub(' ',"\u00A0"), :named)
=> "12,00&nbsp;&euro;"
```

### System configuration
Rails 5.2.2 - but from the sources, it seems this is still there.

**Comment by eileencodes** [comment] 2019-12-10 16:40
> The problem was already mentioned in the docs in 2008

BTW apidock.com are not Rails official docs and never have been. Our official docs live here: https://api.rubyonrails.org/. 

I tried reproducing this but since we don't have any tests that use this kind of currency at the end of a number and I don't know how to set up the locale for currency, it's difficult for me to reproduce quickly. Can you create a test app that reproduces this? Or open a PR adding a test/fix if you're up for it? Thanks!

**Comment by estani** [comment] 2019-12-10 17:27
I followed this further, and I think the format should be changed, no the method, so I've written the issue in [rails-i18n](https://github.com/svenfuchs/rails-i18n/issues/881).
To test it would be enough to use any locale from there, but since I think this issue is better there, I'd suggest this one to be closed (does it make sense?)

**Comment by simi** [comment] 2020-03-09 18:27
@estani, yes I think this case can be closed in favour of that one in rails-i18n.

**Comment by kaspth** [comment] 2020-03-28 20:02
Closing in favor of https://github.com/svenfuchs/rails-i18n/issues/881

**Closed by kaspth** 2020-03-28 20:02 UTC
Labels: activesupport
