### ISSUE TITLE
6.1.0 Change in the way tables are aliased in joins/includes/references?

### ISSUE THREAD

**Issue by codeodor** [rails/rails#40743] opened 2020-12-03 19:20 UTC
Is there a way to do 999bf3d without changing the default aliases? 

It seems to have applied a change to the way tables in joins are aliased (or rather aliases them even when not necessary), so that everywhere anyone would have referenced the table in their `where` condition or a subsequent string `joins` or embedding in another query via `to_sql` would.

So now that I got my tests running, many are errors due to this change.

**Comment by codeodor** [comment] 2020-12-03 19:21
Tagging @kamipo as the author of that change.

**Comment by codeodor** [comment] 2020-12-03 19:25
As an example of what I mean, before I might have had:

```ruby
class ContestEntry < ApplicationRecord
  belongs_to :contest 
end

ContestEntry.includes(:contest).references(:contest).where('contests.active = ?', true) 

and it would work, because `contests` is the table name and it was not aliased.

But now, it will produce SQL that aliases the `contests` table to `contest` or to `contest_entries_contest` depending on how I'm using it.

**Comment by codeodor** [comment] 2020-12-03 20:27
I am working on a test case. It seems my simple example above does not trigger it.

**Comment by rafaelfranca** [comment] 2020-12-04 00:04
Duplicate of #40737

**Comment by simi** [comment] 2020-12-04 00:18
I tried to raise this issue in the original case, but my comments were slightly ignored :(.

**Comment by codeodor** [comment] 2020-12-04 02:43
For what it's worth, @rafaelfranca I did see that other issue, but it mentioned Rails 6.0.3.4, where I did not have this same issue. Happy to keep this closed as a duplicate, but just wanted to mention that it may not be.

**Closed** 2020-12-04 08:24 UTC
Labels: activerecord

**Comment by wbotelhos** [comment] 2022-10-15 18:14
Hey, @townegr , I think it was merged: https://github.com/rails/rails/pull/40749

**Comment by adamzapasnik** [comment] 2024-08-22 08:24
still an issue for Rails 7.0 :( did you guys figure out any workaround?
