### ISSUE TITLE
In The Upgrade of Rails 3.2 to 5

### ISSUE THREAD

**Issue by bapu-hyland** [rails/rails#38270] opened 2020-01-21 12:01 UTC
### Steps to reproduce
I have a model by name Video which inherits from the ApplicationRecord and the videos_controller being inheriting from ApplicationController and now the issue is that when i go to my rails console i see this weired behaviour with the active record.

### Actual behavior
```
 Video.first
  Video Load (1.2ms)  SELECT  "videos".* FROM "videos" ORDER BY "videos"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => #<Video id: 1, title: "small", status: "error", description: nil, user_id: nil, created_at: "2019-08-01 10:41:17", upload_finished: true, publisher_name: "admin@twistage.com", company_id: 1, guid: "998ecb20c3478", main_asset_id: nil, container_type: nil, codec: nil, library_id: 1, deleted_at: nil, purged_at: nil, hits_count: 0, hidden: false, plays_count: 0, updated_at: "2019-08-01 11:07:09", upload_protocol: nil, main_screenshot_id: nil, parent_id: nil, upload_method: nil, youtube_id: nil, `tubemogul_id:` nil, album_id: nil, audio_insight: nil, visual_insight: nil, audio_insight_duration: nil> 
```

```
Video.first.guid
  Video Load (1.2ms)  SELECT  "videos".* FROM "videos" ORDER BY "videos"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => nil 
```

### Expected behavior
```
Video.first.guid
  Video Load (1.2ms)  SELECT  "videos".* FROM "videos" ORDER BY "videos"."id" ASC LIMIT $1  [["LIMIT", 1]]
=>"998ecb20c3478"
```

### System configuration
Current: 5.0
Old: 3.2.2

**Ruby version**:
Current: 2.6.3
old: 2.3.7

**Comment by shaicoleman** [comment] 2020-01-21 14:19
Instead of jumping from Rails 3.2 to 5.0, you should do it more incrementally:
 3.2 => 4.0 => 4.1 => 4.2 => 5.0
It's very likely that you're missing some deprecation warning.

Also check if you have some default scope, it might have something to do with that.

Your bug report doesn't have enough information for the developers to reproduce the issue. 
See https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report

**Comment by eileencodes** [comment] 2020-01-21 20:31
Hey @bapu-hyland - @shaicoleman is correct, we don't have enough information here to determine the cause of the issue.

Please try to reproduce this in a new, sample application and share that with us here. In addition, please keep in mind that Rails 5.0 and below are all EOL (end of life) which means they no longer receive bug fixes or feature improvements. If you can reproduce this bug in Rails 5.2, 6.0, or master then we can fix it on master and backport to 5.2.

**Comment by eileencodes** [comment] 2020-01-31 17:27
I'm going to close this, there's not enough information to debug further. If you send a reproduction app or script @bapu-hyland I'll reopen.

**Comment by bapu-hyland** [comment] 2020-02-02 13:04
ok elieencodes actually the problem which i had was the attributes are being overridden. So that's the cause thanks for closing sorry for the delay .

**Closed** 2020-02-02 13:04 UTC
