### ISSUE TITLE
Does not work with Jruby 9.2.x on Win

### ISSUE THREAD

**Issue by x-itec** [rails/rails#33487] opened 2018-07-31 10:09 UTC
I have no time to do your QA, just a notice that current version does not work with Jruby, not with sqlite, not with postgresql, nothing works on my machine. I have trouble since 5.0 until today, everytime with a new release I think "maybe not it works" but it won't.

If you do not want the java market, I recommend to write that into your README that you are not interested in jruby compatibility.

**Comment by ahorek** [comment] 2018-07-31 12:48
I think the rails team is interested in jruby compatibility. Why do you think the opposite? Because it doesn't work for you?

actually jruby should work just fine until 5.2.0. For rails >= 5 you have to use compatible database adapters https://github.com/jruby/activerecord-jdbc-adapter Yes, there's been a delay because there're not many mainainers. Instead of complaining you should help them.

```
platforms :jruby do
  gem "activerecord-jdbc-adapter", "~> 51.0"
  gem "activerecord-jdbcpostgresql-adapter", "~> 51.0"
  gem "activerecord-jdbcmysql-adapter", "~> 51.0"
end
```
rails 5.2.x should work on master activerecord-jdbc-adapter, but it isn't released yet.

the second known issue is that the bootsnap doesn't work properly with jruby (yet), just remove it from your Gemfile.

unfortunatelly you didn't provide any useful information about your problem. No one will be able to help you if you just say "it doesn't work!"

**Comment by sikachu** [comment] 2018-07-31 13:02
I'm not in a Rails core team, but I can say that everyone do care about JRuby compatibility. However, I don't think many people that contributes to Rails are using JRuby in development or production in a daily basis, so there will always be an issue or something that may get overlooked by the core team.

Rails is an open-source project. It's a collaborative project where everyone can help to make this framework better. And since we're short on the number of active contributors, especially people are using JRuby in a daily basis, this is where _you_ comes in.

Please help us making sure that Rails is working with JRuby.

If you upgrade your app and run into any issue, would you mind open a GitHub issue (hopefully with a PR too if you already found out what is broken) so we can take a look at them? We might not be as responsive as you'd like, since most of the people aren't doing open-source full-time, but I can guaranteed you that a fix that will make us more compatible with JRuby (or even Windows) will definitely get merged.

Thank _you_ for bringing up this issue. We definitely can do better, but we also need _your help_ to archive the goal.

---

> the second known issue is that the bootsnap doesn't work properly with jruby (yet), just remove it from your Gemfile.

I think Bootsnap will only work with MRI since the optimization is very MRI-focused. In 5.2.0, we forgot and include that into default Gemfile. [That will stop happening after 5.2.1.](https://github.com/rails/rails/blob/v5.2.0/railties/lib/rails/generators/app_base.rb#L443-L445)

**Comment by sikachu** [comment] 2018-07-31 13:03
I'm going to close this issue since it does not include a particular bug in general. Please don't take this action as if I'm trying to silence the conversation or anything — we just want to keep our issue tracker compact.

If you find any issue regarding running Rails on JRuby, _please_ open new issues with reproducible steps so we can help you out.

Thanks again.

**Closed by sikachu** 2018-07-31 13:03 UTC

**Comment by x-itec** [comment] 2018-07-31 23:03
Could you keep this item open? I would try to show the current problems, maybe I can help for jruby if you like.

**Comment by sikachu** [comment] 2018-08-01 09:55
I can reopen this. However, before I do that, one thing I'm not really sure is that ... will this issue act as an Epic for all JRuby issues right now?

Generally, we're more a fan of issues that are specific to an issue/problem so we can make the conversation focused on just one issue and make the issue easily triaged. It's okay to open multiple issues if you find multiple issues in various part.

Would that be okay if I may ask you to open new issues fo the each one you find? Or, would you still rather insist on me reopen this issue?

**Comment by x-itec** [comment] 2018-08-01 14:13
Ok, you are right, of course - one ticket per issue. Thank you.
