### ISSUE TITLE
`number_to_currency` printing negative zero when precision > 0

### ISSUE THREAD

**Issue by pjpires** [rails/rails#42577] opened 2021-06-23 14:24 UTC
In https://github.com/rails/rails/pull/37865 `number_to_currency` was fixed to properly print values that would result in a negative zero when passing `precision: 0`. However, it doesn't work when precision is > 0 as seen below.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "action_view"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  include ActionView::Helpers::NumberHelper

  def test_stuff
    assert_equal "$0", number_to_currency(-0.456789, precision: 0) # This works fine
    assert_equal "$0.0", number_to_currency(-0.0456789, precision: 1) # This does not (prints "-$0.0")
  end
end
```

**Note**: calling `number_to_currency` without specifying `precision` also causes issues, since the default value for precision is > 0.

### Expected behavior

Given the above test "$0.0" should be printed.

### Actual behavior

"-$0.0" is printed instead.

### System configuration
**Rails version**:
main

**Ruby version**:
2.7.2

**Comment by flavorjones** [comment] 2021-06-23 15:03
@pjpires Thanks for asking this question. I believe this is functioning as designed. The tests for this method are:

```ruby
      def test_number_to_currency
        [@instance_with_helpers, TestClassWithClassNumberHelpers, ActiveSupport::NumberHelper].each do |number_helper|
          assert_equal("$1,234,567,890.50", number_helper.number_to_currency(1234567890.50))
          assert_equal("$1,234,567,890.51", number_helper.number_to_currency(1234567890.506))
          assert_equal("-$1,234,567,890.50", number_helper.number_to_currency(-1234567890.50))
          assert_equal("-$ 1,234,567,890.50", number_helper.number_to_currency(-1234567890.50, format: "%u %n"))
          assert_equal("($1,234,567,890.50)", number_helper.number_to_currency(-1234567890.50, negative_format: "(%u%n)"))
          assert_equal("$1,234,567,892", number_helper.number_to_currency(1234567891.50, precision: 0))
          assert_equal("$1,234,567,891", number_helper.number_to_currency(1234567891.50, precision: 0, round_mode: :down))
          assert_equal("$1,234,567,890.5", number_helper.number_to_currency(1234567890.50, precision: 1))
          assert_equal("&pound;1234567890,50", number_helper.number_to_currency(1234567890.50, unit: "&pound;", separator: ",", delimiter: ""))
          assert_equal("$1,234,567,890.50", number_helper.number_to_currency("1234567890.50"))
          assert_equal("1,234,567,890.50 K&#269;", number_helper.number_to_currency("1234567890.50", unit: "K&#269;", format: "%n %u"))
          assert_equal("1,234,567,890.50 - K&#269;", number_helper.number_to_currency("-1234567890.50", unit: "K&#269;", format: "%n %u", negative_format: "%n - %u"))
          assert_equal("0.00", number_helper.number_to_currency(+0.0, unit: "", negative_format: "(%n)"))
          assert_equal("$0", number_helper.number_to_currency(-0.456789, precision: 0))
          assert_equal("$1,11", number_helper.number_to_currency("1,11"))
          assert_equal("$0,11", number_helper.number_to_currency("0,11"))
          assert_equal("$,11", number_helper.number_to_currency(",11"))
          assert_equal("-$1,11", number_helper.number_to_currency("-1,11"))
          assert_equal("-$0,11", number_helper.number_to_currency("-0,11"))
          assert_equal("-$,11", number_helper.number_to_currency("-,11"))
        end
      end
```

The [key piece of logic from the method](https://github.com/rails/rails/blob/75ac626c4e21129d8296d4206a1960563cc3d4aa/activesupport/lib/active_support/number_helper/number_to_currency_converter.rb) is that if a number is in the range `[-0.5, 0]`, and `precision` is set to 0, then the "positive format" is used. If `precision` is larger, or if the number is less than -0.5, then the "negative format" is used.

**Comment by flavorjones** [comment] 2021-06-23 15:10
I'm going to close this out -- but if you have follow-up questions, please do post them and I'll do my best to help!

**Comment by flavorjones** [comment] 2021-06-23 15:13
:thinking: Actually, I'm reopening this because the original bug report you reference seemed to establish that "-$0" is an unexpected format, and this feels like a minor variation.

**Comment by pjpires** [comment] 2021-06-23 15:41
> 🤔 Actually, I'm reopening this because the original bug report you reference seemed to establish that "-$0" is an unexpected format, and this feels like a minor variation.

Yes, this got me intrigued. Right now, something like `number_helper.number_to_currency(-0.456789, precision: 0)` returns "$0" (rather than "-$0"). This led me to think that the same would be valid for `precision` > 0, as long as the rounded number (to the specified precision) would end up as a "negative zero".

For presentation purposes, I think it would make sense to print "$0.00" rather than "-$0.00" in the same way that right now "$0" is printed instead of "-$0".

**Comment by ghiculescu** [comment] 2021-06-23 16:07
FWIW i'd also expect `"$0.0"`, `"$0.00"`, etc.

**Comment by flavorjones** [comment] 2021-06-23 16:43
I've opened a PR to try to address this formatting inconsistency: https://github.com/rails/rails/pull/42581

**Closed** 2021-06-23 18:00 UTC
Labels: activesupport
