### ISSUE TITLE
ActiveRecord::UnknownAttributeReference have too much false positive

### ISSUE THREAD

**Issue by nleo** [rails/rails#51486] opened 2024-04-04 06:08 UTC
First two assertions is simple every day SQL usage and should just works without magic string `Arel.sql`

Third one maybe not so usual but still constant string written by coder without user input and so secure, and idealy should just works to.

Also if some feature in ORM not ready and don't feets my needs I shoul have a way to disable it complitele.

Also ORM can be used separatly from rails and web tasks scope in some cli tools for example.

```ruby
require 'bundler/inline'

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

puts "Active Record #{ActiveRecord::VERSION::STRING}"

ActiveRecord::Base.establish_connection(
  :adapter  => 'postgresql',
  :database => 'test'
)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  drop_table :images rescue nil

  create_table :images, :force => true do |t|

    t.string  :filename
    t.integer :width
    t.integer :height

  end
end

class Image < ActiveRecord::Base
end

class OrderUnknownAttributeReferenceBugTest < Minitest::Test
  def test_ordering
    data = [
      ['folder1/1712009477000000.jpg', 100, 200],
      ['folder2/1712109477000300.jpg', 200, 200],
      ['folder3/1712209477000000.jpg', 300, 100],
      ['folder4/1712309477000000.jpg', 100, 150],
    ]

    data.each do |el|
      Image.create! filename: el[0], width: el[1], height: el[2]
    end

    assert_equal data[3][0], Image.order('width*height').first.filename
    assert_equal data[0][0], Image.order('width::decimal/height').first.filename
    assert_equal data[0][0], Image.order("regexp_replace(filename, '[^0-9]+', '', 'g')::bigint/1_000_000").first.filename
  end
end
```

**Comment by fatkodima** [comment] 2024-04-04 08:46
Duplicate of https://github.com/rails/rails/issues/51471

**Closed by fatkodima** 2024-04-04 08:46 UTC

**Comment by fatkodima** [comment] 2024-04-04 08:48
Github issues is reserved for issues in the framework. This is not a rails issue.
If you want to start a discussion, use https://discuss.rubyonrails.org, discord or stackoverflow for this. Thanks.

**Comment by nleo** [comment] 2024-04-04 09:01
@fatkodima Hi, yestaday I regestered on discuss.rubyonrails.org and make a post, but it's not appears on forum

![image](https://github.com/rails/rails/assets/800970/29ded732-87c4-495d-a237-566e55453bc7)

What should I do to discuss this with comunity?

**Comment by fatkodima** [comment] 2024-04-04 09:04
It should work, maybe try again? Had you confirmed email, I don't know? You can see my post (second from the bottom)

**Comment by nleo** [comment] 2024-04-04 09:20
![image](https://github.com/rails/rails/assets/800970/7471ddf2-0c54-45b1-96d9-d67e335c02c9)
I have this mesage

**Comment by nleo** [comment] 2024-04-04 09:21
@fatkodima  Also Discord not alloing me goin in 
![image](https://github.com/rails/rails/assets/800970/7d407ac0-a7cd-4088-b11b-d433c410b91b)

**Comment by nleo** [comment] 2024-04-04 09:34
disble ipv6 can add email to discord but still have immidiate ban
![image](https://github.com/rails/rails/assets/800970/865d2cd0-8874-4af0-a339-7f73b1c71e72)

**Comment by fatkodima** [comment] 2024-04-04 09:54
Have no idea, I asked on discord, maybe other people know.

**Comment by nleo** [comment] 2024-04-04 10:03
Tried login thour github still get error
![image](https://github.com/rails/rails/assets/800970/406bdb2e-d9c7-419b-a00d-bfac7c3645c9)

**Comment by nleo** [comment] 2024-04-04 10:04
and hold notification again
![image](https://github.com/rails/rails/assets/800970/8344e5fd-9039-4840-b9c2-424a08e800c7)

**Comment by nleo** [comment] 2024-04-04 11:04
I found way to disable this thing completely:

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  class << self
    def disallow_raw_sql!(*args)
      # noop
    end
  end

end
```

I'm happy for now, untill rails team will come up with new strange thing, which they think all should forcibly use.

**Comment by fatkodima** [comment] 2024-04-04 11:55
Nice!

People suggesting what may be the issue:
> I suspect they probably use tor or some vpn that must be blacklisted by many providers. There is 0 link between discuss and discord, so for both of them to block the same user, they either use a similar list of IPs or something like that

**Comment by nleo** [comment] 2024-04-05 04:11
@fatkodima I'm think its becouse I tried to post big post just after registration.

If I act like a spammer: register account, waits 2 days, start posting some completely useless, but social welcomed comments like "Yeh, man!", "Great idea!", "I want to see it in rails!" after weeks I probably can provide a feedback on feature.

So, there is no easy way to provide any feedback rails team.
