### ISSUE TITLE
Unable to use methods created in child class when parent class is inside of gem | Rails 7.1.3.3 / Ruby 3.2.4

### ISSUE THREAD

**Issue by RailsCod3rFuture** [rails/rails#52556] opened 2024-08-09 21:44 UTC
### Steps to reproduce
1. create a gem with folder **models/good_friend.rb**
2. In base application -- create a model named....**new_friend.rb** 
Example below

```
class NewFriend < GoodFriend
   def fun_friend
  "fun friends!"
   end
end
```

### Expected behavior
I should be able to use fun_friend method even though its not defined in good friend

### Actual behavior
I get method undefined for GoodFriend when I add methods to NewFriend class.

### System configuration
**Rails version**: 7.1.3.3

**Ruby version**:
ruby 3.2.4

**Comment by RailsCod3rFuture** [comment] 2024-08-09 21:45
This functionality works in earlier rails versions < 7

**Comment by rafaelfranca** [comment] 2024-08-09 21:52
Can you provide an example application that reproduce the issue?

Also can you clarify how you are calling this method? Because `fun_friend` is indded not defined in `GoodFriend`, so you should get `undefined for GoodFriend` when you add method to `NewFriend` but don't add to `GoodFriend` and try to use it in a `GoodFriend` instance.

**Comment by RailsCod3rFuture** [comment] 2024-08-09 21:58
We have a user object that inherits from a super user class object in a gemspec that holds some resources for our application.

Essentially we are are inheriting from the base class like below

```
class User < Mohegan::User
  # newly defined method below
  def users_full_name
    "users full name"
  end
end
```

this method users_full_name isn't present in the parent class and doesn't work...Can we no longer inherit from gems and define methods through the child class? It seems like a gem only issue at this capacity. Not sure if its loaded into the env and immutable at that point.

**Comment by rafaelfranca** [comment] 2024-08-09 22:43
Thank you for explaning.

> this method users_full_name isn't present in the parent class and doesn't work...Can we no longer inherit from gems and define methods through the child class?

You could never do that. This never worked in Ruby or Rails. Method defined in the child class are only available in the child class, never in the parent. Maybe something else was making it work?

Regardless, closing this issue since this isn't supposed to work. That isn't how inheritance works.

**Closed by rafaelfranca** 2024-08-09 22:43 UTC
