### ISSUE TITLE
ActiveModel::Dirty behaves incorrectly with type casting

### ISSUE THREAD

**Issue by AntonZh** [rails/rails#25152] opened 2016-05-26 15:29 UTC
### Steps to reproduce

[Executable Test Case](https://gist.github.com/AntonZh/4da55e005d401a5a6c1bec23a2b64b25)

1. Create a model with an integer attribute
2. Create an object with some value
3. Assign some value to that object, so that this value will be type casted to equal value

```ruby
foo = Foo.create!(bar: 5)
foo.bar = ' 5 '
p foo.bar # => 5
```

### Expected behavior
```ruby
p foo.changes # => {}
```

### Actual behavior
```ruby
p foo.changes # => {"bar"=>[5, 5]}
```

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.1

**Comment by maclover7** [comment] 2016-05-26 19:48
Investigating.

**Comment by maclover7** [comment] 2016-05-26 20:05
Hmm, spent some time investigating but wasn't able to come to the root of the bug. This likely has something to do with `changed_attributes` not taking into account a type's value before type casting (`'5'` instead of `5`), but this might be the expected behavior. cc @sgrif

**Comment by sgrif** [comment] 2016-05-26 21:49
Can you check if this is still the case on master? I vaguely recall fixing this exact bug

**Comment by sgrif** [comment] 2016-05-26 21:52
This is actually the intended behavior, as the field has to get marked as changed in order for numericality validations to run, etc. We always treat numeric fields as changed if you assign a string containing any characters that are non numeric, as it did in fact change (even if it's the same after type casting)

**Closed by sgrif** 2016-05-26 21:52 UTC
Labels: activerecord
