### ISSUE TITLE
Unable to create spec folder using rails generate rspec:install

### ISSUE THREAD

**Issue by suresh02** [rails/rails#27129] opened 2016-11-21 11:08 UTC
### Steps to reproduce
1. Install rails
2. Install rspec gems
3.Enter rails g rspec:install command in cmd
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Spec folder should be generated

### Actual behavior
```
D:\Demo\sample>rails generate rspec:install
   identical  .rspec
       exist  spec
      create  spec/C:/Users/suresh.achanta/AppData/Local/Temp/d20161117-6256-19l
lfm8/spec/spec_helper.rb
C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': Invalid argument @ dir
_s_mkdir - D:/Demo/sample/spec/C: (Errno::EINVAL)
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels)
in mkdir_p'
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'

        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:211:in `each'
        from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/create_file.rb:61:in `block in invoke!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/empty_directory.rb:116:in `invoke_with_conflict_check'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/create_file.rb:60:in `invoke!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
.rb:94:in `action'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/create_file.rb:25:in `create_file'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/file_manipulation.rb:27:in `copy_file'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/directory.rb:94:in `block in execute!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/directory.rb:80:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/directory.rb:80:in `execute!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/directory.rb:66:in `invoke!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
.rb:94:in `action'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions
/directory.rb:52:in `directory'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.2/lib/genera
tors/rspec/install/install_generator.rb:23:in `block in copy_spec_files'
        from C:/Ruby23-x64/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.2/lib/genera
tors/rspec/install/install_generator.rb:20:in `copy_spec_files'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command
.rb:27:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocat
ion.rb:126:in `invoke_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocat
ion.rb:133:in `block in invoke_all'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocat
ion.rb:133:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocat
ion.rb:133:in `map'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocat
ion.rb:133:in `invoke_all'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.r
b:232:in `dispatch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb
:440:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/g
enerators.rb:180:in `invoke'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/c
ommands/generate.rb:13:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/ac
tive_support/dependencies.rb:293:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/ac
tive_support/dependencies.rb:293:in `block in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/ac
tive_support/dependencies.rb:259:in `load_dependency'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/ac
tive_support/dependencies.rb:293:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:138:in `require_command!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:145:in `generate_or_destroy'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:60:in `generate'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:49:in `run_command!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/c
ommands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**:5.0.0.1

**Ruby version**:2.3.1

**Comment by utilum** [comment] 2016-11-21 12:08
This looks like an issue with an Rspec generator, not Rails.

**Comment by suresh02** [comment] 2016-11-21 12:47
Rspec team declared that it is issue with rails.. it worked well in my home desktop but im unable to install in office machine

**Comment by prathamesh-sonpatki** [comment] 2016-11-21 12:57
@suresh02 Can you add link to the RSpec issue? Thanks.

**Comment by suresh02** [comment] 2016-11-21 13:23
https://github.com/rspec/rspec-rails/issues/1747

**Comment by rafaelfranca** [comment] 2016-11-24 00:47
This seems like a thor issue, but we can leave it here. I don't have a windows machine and I fear nobody in the core does have and I don't care enough about the windows development history but maybe @sgrif can help here.

**Comment by sgrif** [comment] 2016-11-24 01:18
Yeah I can take a look after the holidays

**Comment by sgrif** [comment] 2016-11-24 01:18
s/holidays/thanksgiving

**Comment by suresh02** [comment] 2016-12-06 07:09
#27129sgrif Can you please look into this issue

**Comment by jjeffries** [comment] 2016-12-18 16:22
I'm having the same issue. What I did for now is create and copy the contents of 'rails-helper.rb' and 'spec_helper.rb' from an app I had prior to upgrading. When I ran rails generate rspec:install, the contents that should have been placed in the (missing) rails_helper.rb file was actually in spec_helper.rb file.

**Comment by utilum** [comment] 2016-12-18 18:10
Can't reproduce with 5.0.1.rc2.
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux].
Is this only reproduced on Windows ?

**Comment by jjeffries** [comment] 2016-12-18 20:56
Yes

**Comment by rafaelfranca** [comment] 2017-02-13 02:24
Closing since this is a thor issue.

**Closed by rafaelfranca** 2017-02-13 02:24 UTC
Labels: railties
