### ISSUE TITLE
Undefined method `cache`. Regression in 4.2.5.1

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#23245] opened 2016-01-25 20:50 UTC
This line:
```
render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
```
raises:

```
     NoMethodError:
       undefined method `cache' for nil:NilClass
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/template/resolver.rb:151:in `cached'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/template/resolver.rb:121:in `find_all_anywhere'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:68:in `block (2 levels) in _find_all'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:66:in `each'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:66:in `block in _find_all'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:65:in `each'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:65:in `_find_all'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:50:in `find_file'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/lookup_context.rb:126:in `find_file'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:18:in `find_file'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:32:in `block in determine_template'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/lookup_context.rb:147:in `with_fallbacks'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:18:in `with_fallbacks'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:32:in `determine_template'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:8:in `render'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:23:in `render'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:100:in `_render_template'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:83:in `render_to_body'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/abstract_controller/rendering.rb:25:in `render'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:16:in `render'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/hydra-core-9.6.0/app/controllers/concerns/hydra/controller/download_behavior.rb:25:in `block (2 levels) in render_404'
```

**Comment by maclover7** [comment] 2016-01-25 20:53
Duplicate of #23244.

**Closed by maclover7** 2016-01-25 20:53 UTC
