### ISSUE TITLE
Migrations for reference removal generate statements in problematic order

### ISSUE THREAD

**Issue by vemv** [rails/rails#19396] opened 2015-03-19 01:05 UTC
The following:

`rails g migration remove_contest_from_prizes contest:references`

Generates these 2 statements:

```ruby
    remove_reference :prizes, :contest, index: true
    remove_foreign_key :prizes, :contests
```

However the migration won't run successfully on MySQL:

```
Mysql2::Error: Cannot drop index 'index_prizes_on_contest_id': needed in a foreign key constraint: ALTER TABLE `prizes` DROP `contest_id`/Users/vemv/khana/db/migrate/20150319005657_remove_contest_from_prizes.rb:3:in `change'
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot drop index 'index_prizes_on_contest_id': needed in a foreign key constraint: ALTER TABLE `prizes` DROP `contest_id`
```

This can be fixed by editing the migration so the `remove_foreign_key` statement runs before the `remove_reference` statement.

Would it be good to ensure that particular order?

**Comment by vemv** [comment] 2015-03-19 01:16
(using Rails 4.2.0)

**Comment by kuldeepaggarwal** [comment] 2015-03-19 08:24
Thanks for reporting the issue. Can you please provide the full error stack?

**Comment by senny** [comment] 2015-03-19 09:15
This looks very much like a duplicate of #18664 and #19009. This issue has been fixed on `4-2-stable`. You can use the latest RC `4.2.1.rc4` and see if that works out for you.

Please use the search before reporting new issue. This prevents us from spread out discussions and saves time investigating already discussed issues. Thank you for your understanding.

**Closed by senny** 2015-03-19 09:15 UTC
