### ISSUE TITLE
FATAL Rails : ActiveRecord::ConnectionNotEstablished (could not translate host name "xxxx.us-east-1.rds.amazonaws.com" to address: System error)

### ISSUE THREAD

**Issue by vs37559** [rails/rails#42555] opened 2021-06-22 05:19 UTC
I have recently migrated from Rails 4.2.1 to Rails 6.1.3.2
And getting this error frequently. It occurs multiple times in a day and reloading the ngnix configuration fixes it temporarily.

Earlier I had tried increasing pool size in my database.yml to 15.
This change fixed this issue for some days but it started appearing again.

### Expected behavior
Should connect to Database and fetch the relevant information.

### Actual behavior
Thorws error
```
FATAL Rails :   
ActiveRecord::ConnectionNotEstablished (could not translate host name "xxxx.us-east-1.rds.amazonaws.com" to address: System error)

```
### System configuration
**Rails version**: 6.1.3.2

**Ruby version**:3.0.1

**Comment by ghiculescu** [comment] 2021-06-22 15:39
Do you have any more detail, eg. a backtrace of where the error is being raised from?

Did the error start happening on 6.1 only, or on another version as you were upgrading?

**Comment by vs37559** [comment] 2021-06-22 18:16
@ghiculescu Unfortunately, this is all that comes up no backtrace or I would've given it earlier. And as I said Re-loading the nginx service seems to fix it.

I have other services that are running on v6.0 and they work fine so I think it would be safe to say that this issue is with v6.1.

**Comment by p8** [comment] 2021-06-23 08:13
Are you using Kubernetes?
This seems like an DNS issue, unrelated to Rails.
https://github.com/kubernetes/kops/issues/4251

**Comment by byroot** [comment] 2021-06-24 21:38
@vs37559 unless you are able to reproduce this in isolation, we can only assume it's an issue with your production setup and not with Rails. Feel free to keep this issue updated for anyone who would run into the same issue, but since it's not actionable for the Rails team I'll be closing it.

**Closed by byroot** 2021-06-24 21:38 UTC
Labels: third party issue
