### ISSUE TITLE
Misleading deprecation warning when referencing ActionController::Base

### ISSUE THREAD

**Issue by pvande** [rails/rails#36546] opened 2019-06-24 05:48 UTC
### Steps to reproduce
- Create a new app with Rails 6.0.0.rc1.
- Add a reference to `ActionController::Base` to `config/application.rb`.
- Run `bundle install`.
- Run `rails environment`.
- Run `cat log/development.log`.

### Expected behavior
The `development.log` file should be empty.

### Actual behavior
The log file contains the following deprecation warning:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <main> at /Users/
USER/Projects/rails-app-test/config/environment.rb:5)
```

A few thoughts:
- Referencing `ActionController::Base` from an initializer may be poor form, but that is neither documented nor indicated by the warning.
- I cannot tell whether ActionText's helper modules are *intentionally* passing through the autoloader.  Most Rails code *doesn't seem to*, but maybe Engine code is exceptional?
- Tracking down what was causing these autoloads was tricky, involving monkeypatches to `ActiveSupport::Dependencies` and direct edits to the Rails source files loaded by Bundler.

(I have filed a related bug with another project, including a detailed outline of the observed causal chain.  rollbar/rollbar-gem/issues/880)

### System configuration
**Rails version**: 6.0.0.rc1
**Ruby version**: 2.6.3

**Comment by pvande** [comment] 2019-08-04 23:36
Can confirm this is still an issue in `6.0.0.rc2`.

**Comment by archonic** [comment] 2019-08-19 21:42
Still happening in 6.0.0. In my app I had references to `ActiveSupport::Logger` and `ActiveSupport::TaggedLogging` in my config/application.rb which was causing the zeitwerk deprecation notices about `ActionText::ContentHelper` and `ActionText::TagHelper`. This was also causing zeitwerk deprecation notices about all my sidekiq workers for that machine. Inserting `require "active_support/logger"` and `require "active_support/tagged_logging"` didn't remove those warnings.

I wrapped the Logger and TaggedLogging references in a `ActiveSupport.on_load(:action_controller) do` block and that got rid of the issue on startup. Still working on getting rid of those warnings for rspec though.

**Comment by kevin-j-m** [comment] 2019-08-26 13:50
> Tracking down what was causing these autoloads was tricky, involving monkeypatches to ActiveSupport::Dependencies and direct edits to the Rails source files loaded by Bundler.

@pvande have you, or could you, document the process you followed to identify the root cause? I'm looking to do the same in my app and am not sure where to start. Thanks!

**Comment by fernandoluizao** [comment] 2019-09-03 18:08
+1 for describe the root cause(s) in the warning. Just point to config/environment.rb gives no idea where to look

**Comment by Vasfed** [comment] 2019-11-26 19:05
Got this in my app on 6.0.1, the warning was caused by several old gems trying to `include` their helpers into `ActionController::Base` in engine initializer/railtie, which caused loading of helpers.
Gems were `wicked_pdf`(opened a PR with a fix there), `split`(new version is already fixed) and old version of `twitter-bootstrap-rails`.

To track this I used an initializer with:
```ruby
ActiveSupport.on_load(:action_controller_base) do
  bc = ActiveSupport::BacktraceCleaner.new
  bc.remove_silencers!
  bc.add_silencer { |line| line.start_with?(RbConfig::CONFIG["rubylibdir"]) }
  bc.add_silencer { |line| line =~ Regexp.union(
    *(
      %w{ bootsnap railties spring activesupport actionpack zeitwerk thor rack }.
      map{|g| /\A#{g} \([\w.]+\) /}
    ),
    /\Abin\/rails/
  )}
  trace = bc.clean(caller)
  puts "Cleaned backtrace:\n\t#{trace.join("\n\t")}"
  puts "\nMost probably the cause is: #{trace.first}"
  puts "If not - uncomment `raise` at #{__FILE__}:#{__LINE__+1}"
  # raise "i can haz full backtrace"
  exit(1)
end
```
and spotted gems and my own initializers in the backtrace, like:
> Most probably the cause is: split (3.3.2) lib/split/engine.rb:6:in \`block in <class:Engine>'
> If not - uncomment `raise` at \<initializer filename here\>

**Comment by vdegove** [comment] 2019-12-01 11:13
Hello! @Vasfed thanks a lot for the initilializer. Would you have a link to the proposed fixes in `wicked_pdf`, `split` and `twitter-bootstrap-rails` to get an idea of the PR to propose for `remotipart`?

**Comment by choznerol** [comment] 2019-12-01 13:18
@vdegove looks like `remotipart` got a fix PR opened already: https://github.com/JangoSteve/remotipart/pull/206

**Comment by choznerol** [comment] 2019-12-01 13:22
@vdegove Looks like `remotipart` already has an open PR here: https://github.com/JangoSteve/remotipart/pull/206

**Comment by ziaulrehman40** [comment] 2019-12-11 12:26
I am seeing it just after adding rails-admin v 2.0.0, so it is it or some of its dependency.

And found it is already filed: https://github.com/sferik/rails_admin/issues/3190 

For anyone who lands here.

**Comment by jankeesvw** [comment] 2019-12-13 12:24
Wicked_pdf has an open PR here: https://github.com/mileszs/wicked_pdf/pull/869

**Comment by EnziinSystem** [comment] 2020-02-13 06:29
> ```ruby
> ActiveSupport.on_load(:action_controller_base) do
>   bc = ActiveSupport::BacktraceCleaner.new
>   bc.remove_silencers!
>   bc.add_silencer { |line| line.start_with?(RbConfig::CONFIG["rubylibdir"]) }
>   bc.add_silencer { |line| line =~ Regexp.union(
>     *(
>       %w{ bootsnap railties spring activesupport actionpack zeitwerk thor rack }.
>       map{|g| /\A#{g} \([\w.]+\) /}
>     ),
>     /\Abin\/rails/
>   )}
>   trace = bc.clean(caller)
>   puts "Cleaned backtrace:\n\t#{trace.join("\n\t")}\n"
>   puts "Most probably the cause is: #{trace.first}"
>   puts "If not - uncomment `raise` at #{__FILE__}:#{__LINE__+1}"
>   # raise "i can haz full backtrace"
>   exit(1)
> end
> ```

I create an initializer with your source code ("/config/initializers/tracker_log.rb").
But I get the message:
```
/config/initializers/tracker_log.rb:1:in `<main>'
/config/environment.rb:5:in `<main>'
rake (13.0.1) lib/rake/task.rb:281:in `block in execute'
rake (13.0.1) lib/rake/task.rb:281:in `each'
rake (13.0.1) lib/rake/task.rb:281:in `execute'
rake (13.0.1) lib/rake/task.rb:219:in `block in invoke_with_call_chain'
rake (13.0.1) lib/rake/task.rb:199:in `synchronize'
rake (13.0.1) lib/rake/task.rb:199:in `invoke_with_call_chain'
rake (13.0.1) lib/rake/task.rb:243:in `block in invoke_prerequisites'
rake (13.0.1) lib/rake/task.rb:241:in `each'
rake (13.0.1) lib/rake/task.rb:241:in `invoke_prerequisites'
rake (13.0.1) lib/rake/task.rb:218:in `block in invoke_with_call_chain'
rake (13.0.1) lib/rake/task.rb:199:in `synchronize'
rake (13.0.1) lib/rake/task.rb:199:in `invoke_with_call_chain'
rake (13.0.1) lib/rake/task.rb:243:in `block in invoke_prerequisites'
rake (13.0.1) lib/rake/task.rb:241:in `each'
rake (13.0.1) lib/rake/task.rb:241:in `invoke_prerequisites'
rake (13.0.1) lib/rake/task.rb:218:in `block in invoke_with_call_chain'
rake (13.0.1) lib/rake/task.rb:199:in `synchronize'
rake (13.0.1) lib/rake/task.rb:199:in `invoke_with_call_chain'
rake (13.0.1) lib/rake/task.rb:188:in `invoke'
rake (13.0.1) lib/rake/application.rb:160:in `invoke_task'
rake (13.0.1) lib/rake/application.rb:116:in `block (2 levels) in top_level'
rake (13.0.1) lib/rake/application.rb:116:in `each'
rake (13.0.1) lib/rake/application.rb:116:in `block in top_level'
rake (13.0.1) lib/rake/application.rb:125:in `run_with_threads'
rake (13.0.1) lib/rake/application.rb:110:in `top_level'
rake (13.0.1) lib/rake/application.rb:186:in `standard_exception_handling'
/bin/rails:9:in `<top (required)>'
/bin/spring:15:in `require'
/bin/spring:15:in `<top (required)>'
Most probably the cause is: /config/initializers/tracker_log.rb:1:in `<main>'
If not - uncomment `raise` at /config/initializers/tracker_log.rb:16
```
It not detect gems, instead it stop on this initializer!

**Comment by athix** [comment] 2020-07-26 02:48
Getting incredibly confused by this while working on the Sorcery rework. When using @Vasfed's example above, it points at the `ActiveSupport.on_load(:action_controller_base) do` call itself as what's causing Zeitwerk deprecation warnings. Not sure how that's possible, nor how to address it... If anyone has an idea please let me know. If I figure it out, I'll follow up here for anyone else similarly confused in the future.

**Comment by athix** [comment] 2020-07-26 03:19
Issue appeared to be calling `require 'rspec/rails'` in the wrong order.

This causes deprecation warnings:
```ruby
require 'rails/all'
require 'rspec/rails'
require 'dummy_app/config/environment'
```
To fix, move the require below your application call:

```ruby
require 'rails/all'
require 'dummy_app/config/environment'
require 'rspec/rails'
```

**Comment by dbackeus** [comment] 2020-09-01 19:42
We had these deprecation warnings but only if `RAILS_ENV=test`. I didn't manage to figure out why but changing from `require "rails/all"` to requiring individual parts of rails and skipping to require `rails/action_text` got rid of the warnings. Simple fix for anyone who doesn't actually make use of ActionText.

**Comment by p8** [comment] 2020-10-31 08:53
@rafaelfranca I still get the deprecation warning on 82ab90365330e22614c73a5900f12dbc6e9c352b :
"DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper."
So #40222 doesn't fix this.

**Comment by itsmonktastic** [comment] 2020-11-15 23:05
From what I've seen there is always some code using ActionController "too early" whenever this warning is emitted. On the rails app I saw this on:

* there was a gem being loaded that was patching/referencing ActionController without using `ActiveSupport.on_load(:action_controller)`, causing ActionController to be loaded early
* when the ActionText initializer runs ActiveSupport.on_load(:action_controller), ActionController is already loaded so the block to load helpers runs immediately, autoloading ActionText::ContentHelper

How I diagnosed it - I put a debugger in the action_controller/base.rb to figure out the first thing to load it. Going up in the stack trace, it lead me to the code referencing ActionController without ActiveSupport.on_load

How I fixed it - I updated the code in the gem to use ActiveSupport.on_load:

```
-module ActionController
-  module MultipassRequestForgeryProtection
-    def self.included(klass)
-      klass.extend(ClassMethods)
-    end
+ActiveSupport.on_load(:action_controller) do
+  module ActionController
+    module MultipassRequestForgeryProtection
+      def self.included(klass)
+        klass.extend(ClassMethods)
+      end
```

Hope this helps someone - it's like there's a gem or initializer being loaded that is the cause

**Comment by hirowatari** [comment] 2021-01-08 20:43
For me, there were two gems causing this issue `parallel_tests` and `rails_semantic_logger`.  Hope that helps others track down these deprecations.  There aren't any fixed versions of these gems yet.

**Comment by jacobwalkr** [comment] 2021-01-13 16:56
Maybe a stupid question but how did you all figure out where the issue was in your apps? I'm about to start digging through my app and the Gemfile but would be nice to have some direction before I start 😁

**Comment by rubendinho** [comment] 2021-01-13 17:44
> Maybe a stupid question but how did you all figure out where the issue was in your apps? I'm about to start digging through my app and the Gemfile but would be nice to have some direction before I start 😁

@jacobwalkr Once I figured out that another gem is the culprit, I started commented out various non-essential/less-popular gems (and any associated initializers) and ran `rails c`.  Once I got the console to run without the deprecation message, I started un-commenting out the gems one-by-one, until I found the one causing problems.

**Comment by kevinhq** [comment] 2021-01-20 04:49
We see this warning after upgrading to Rails 6.1.1. 

The one that works for us is this solution

> We had these deprecation warnings but only if `RAILS_ENV=test`. I didn't manage to figure out why but changing from `require "rails/all"` in `application.rb` to requiring individual parts of rails and skipping to require `rails/action_text` got rid of the warnings. Simple fix for anyone who doesn't actually make use of ActionText.

We don't use ActionText because we already used froala editor.

Here's what we come up in config/application.rb 

```
require "rails"

%w(
  active_record/railtie
  active_storage/engine
  action_controller/railtie
  action_view/railtie
  action_mailer/railtie
  active_job/railtie
  action_cable/engine
  action_mailbox/engine
  rails/test_unit/railtie
  sprockets/railtie
).each do |railtie|
  begin
    require railtie
  rescue LoadError
  end
end
```

**Comment by lubosch** [comment] 2021-01-20 17:06
after few hours I've discovered that mailgun-ruby is causing this and particularly these things:

ActionMailer::Base.add_delivery_method :mailgun, Railgun::Mailer
ActionMailer::Base.register_interceptor(OverrideAttachmentsContentId)

I've substituted `ActionMailer::Base.register_interceptor(OverrideAttachmentsContentId)` -> `Mail.register_interceptor(OverrideAttachmentsContentId)`
but nothing to do with mailgun .. dunno if it's a ActionMailer::Base bug but I guess so as I couldn't find a replacement

**Comment by jeffblake** [comment] 2021-01-21 18:58
For me it was this in an initializer:

`ActionMailer::Base.add_delivery_method :sendgrid, SendgridDelivery`

Changing it to 

```
ActiveSupport.on_load(:action_mailer) do
  add_delivery_method :sendgrid, SendgridDelivery
end
```

Fixed it.

**Comment by jacobwalkr** [comment] 2021-01-28 10:34
Thanks for the advice, all. In our case, it's in `rubycas-client`, required by `devise_cas_authenticatable`: https://github.com/nbudin/devise_cas_authenticatable/issues/151.

It happens when calling `rake test` but not `rails test`, which I think has something to do with the Spring preloader.

**Comment by petitJAM** [comment] 2021-03-05 21:57
This chunk of code needs to be inserted in `config/application.rb` _before_ the call to `Bundler.require` so that it runs before gems run.  Obvious in hindsight, but hopefully I save someone else a few minutes of confusion.

> To track this I used an initializer with:
> 
> ```ruby
> ActiveSupport.on_load(:action_controller_base) do
>   bc = ActiveSupport::BacktraceCleaner.new
>   bc.remove_silencers!
>   bc.add_silencer { |line| line.start_with?(RbConfig::CONFIG["rubylibdir"]) }
>   bc.add_silencer { |line| line =~ Regexp.union(
>     *(
>       %w{ bootsnap railties spring activesupport actionpack zeitwerk thor rack }.
>       map{|g| /\A#{g} \([\w.]+\) /}
>     ),
>     /\Abin\/rails/
>   )}
>   trace = bc.clean(caller)
>   puts "Cleaned backtrace:\n\t#{trace.join("\n\t")}\n"
>   puts "Most probably the cause is: #{trace.first}"
>   puts "If not - uncomment `raise` at #{__FILE__}:#{__LINE__+1}"
>   # raise "i can haz full backtrace"
>   exit(1)
> end
> ```
> 
> and spotted gems and my own initializers in the backtrace, like:
> 
> > Most probably the cause is: split (3.3.2) lib/split/engine.rb:6:in `block in class:Engine'
> > If not - uncomment `raise` at <initializer filename here>

@athix That may have been your problem with it (though I'm sure you're well past this issue by now :smile:)

**Comment by jacobjlevine** [comment] 2021-04-23 18:40
In case other folks are still running into this, a bit of sleuthing revealed two sources of this deprecation warning in my Rails 6.1 app.

1) I referenced ActionMailer::Base in a couple of initializers. Based on the suggestion in the Rails Guides (https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration), I decided to move all those references to environment.rb.

2) The same deprecation error was also apparently being generated by the mailgun-ruby gem v 1.2.3. It appears the deprecation warning has been fixed in v 1.2.4.

**Comment by archonic** [comment] 2021-05-13 01:40
@petitJAM Thanks very much for your addition. That helped me find the culprit which was the `health_check` gem.

**Comment by ilude** [comment] 2021-05-29 19:37
If you are seeing this message because of using ActionMailer::Base in an initializer:

From @csutter "Instead of adding configuration to ActionMailer::Base, set it on Rails.configuration.action_mailer instead."

**Comment by zzak** [comment] 2021-05-30 01:12
Making a note for myself to check if this isn't already updated in the documentation 👀

**Closed** 2021-05-31 14:54 UTC
Labels: activesupport, docs, railties
