### ISSUE TITLE
Released Web Console doesn't work with Rack 3.x and main branch doesn't work with Rack 2.x

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#48990] opened 2023-08-21 16:56 UTC
https://github.com/rails/web-console/issues/331

We need to fix this before the 7.1 release

**Comment by akhilgkrishnan** [comment] 2023-08-24 12:23
@rafaelfranca Seems like the issue is already fixed in web-console https://github.com/rails/web-console/pull/332

**Closed** 2023-08-24 15:14 UTC
