### ISSUE TITLE
asset_path and asset_url should respect *_path vs *_url convention

### ISSUE THREAD

**Issue by blarralde** [rails/rails#22721] opened 2015-12-21 11:53 UTC
Having set `config.action_controller.asset_host = "example.com"` in my app I got into an unexpected behavior when I tried fine-tuning which assets should use a relative path and which should use a full URL.

In my views, I'm using `asset_path("icon.svg")` and expecting it to output `/assets/icon.svg`, but instead get `http://example.com/assets/icon.svg`. I would expect that `asset_path` would always return a relative path, and `asset_url` would try to always return a full URL.

Is this behavior due to legacy support for when `asset_url` didn't exist?

**Comment by maclover7** [comment] 2015-12-22 01:08
Hi @blarralde, which version of Rails are you running? Also, could you create an executable bug report script, using one of the [templates](https://github.com/rails/rails/tree/master/guides/bug_report_templates)? Thanks!

**Comment by rafaelfranca** [comment] 2015-12-22 01:15
It is not an unexpected behavior. It may be not documented but it is expect. Both `assert_path` and `assert_url` generates the full path if `asset_host` is set. The only difference is when it is not set. `assert_path` will use a relative path if `:host` is not set and `assert_url` will use the host from the current request.

Feel free to open a PR to update the documentation but I'm closing this since it is not an issue.

**Closed by rafaelfranca** 2015-12-22 01:15 UTC
