### ISSUE TITLE
Can't copy paste from action mailer documentation

### ISSUE THREAD

**Issue by sb8244** [rails/rails#25655] opened 2016-07-02 16:37 UTC
### Steps to reproduce

* Go to http://edgeguides.rubyonrails.org/action_mailer_basics.html#previewing-emails
* Copy the first code snippet

![image](https://cloud.githubusercontent.com/assets/1231659/16541462/8c04db92-4051-11e6-8ec0-59368f302ea1.png)

* Paste it into rails console (see error)
* Remove all leading spaces from the copy and paste it again (passes)

### Expected behavior
A class is created and the symbol :welcome_email is returned

```
[13] pry(main)> class UserMailerPreview < ActionMailer::Preview
[13] pry(main)*   def welcome_email
[13] pry(main)*     UserMailer.welcome_email(User.first)
[13] pry(main)*   end
[13] pry(main)* end
=> :welcome_email
```

### Actual behavior

An error occurs where welcome_email method is not defined.

```
[12] pry(main)> class UserMailerPreview < ActionMailer::Preview
[12] pry(main)*     def welcome_email
[12] pry(main)*       UserMailer.welcome_email(User.first)
[12] pry(main)*     end
[12] pry(main)* end
NameError: undefined local variable or method `welcome_email' for UserMailerPreview:Class
```

### System configuration
**Rails version**: 4.2.5

**Ruby version**: 2.2.2

**Comment by sevenseacat** [comment] 2016-07-02 17:18
The edge guides are not for Rails 4.2.5 - they're for edge Rails.

If you want the guides for Rails 4.2.5, go here - http://guides.rubyonrails.org/v4.2/

**Comment by sb8244** [comment] 2016-07-02 17:29
I do understand that, but the spacing issues are invalid ruby independent of rails version. It's not a code issue, it's formatting.

**Comment by sb8244** [comment] 2016-07-02 17:33
This actually originated from copy pasting into a file and changing to what I needed. The previews unexplainably wouldn't show up and would give that error the first refresh. It seems that the spaces might not be valid on all machines

**Comment by vipulnsward** [comment] 2016-07-02 22:34
@sb8244 I believe we can give this a close, since its not a Rails issue.

**Comment by sb8244** [comment] 2016-07-02 23:05
@vipulnsward is the documentation a part of rails/rails or is there another place I can report there?

As a user of rails, I would expect documentation code snippets to be copy pastable and runnable in Ruby. I'm not sure if the problem is systemic to the styling of edge doc code snippets, but there is definitely something amiss here. Even if I copy in the "plain text" styling [1], it is not compatible with rails console.

[1]
![image](https://cloud.githubusercontent.com/assets/1231659/16542838/dfe3e6aa-4087-11e6-8d5d-88f6e0daf9b0.png)

**Comment by sb8244** [comment] 2016-07-02 23:14
I took the documentation and put it through https://r12a.github.io/apps/conversion/ to see what is going on. I see that the spaces are actually \u00A0. Is this a ruby compatible character for spaces?

```
class UserMailerPreview < ActionMailer::Preview
\u00A0\u00A0def welcome_email
\u00A0\u00A0\u00A0\u00A0UserMailer.welcome_email(User.first)
\u00A0\u00A0end
end
```

When I remove the spaces in sublime, re-tab it, and then put it through the converter, I get the following:

```
class UserMailerPreview < ActionMailer::Preview
	def welcome_email
		UserMailer.welcome_email(User.first)
	end
end
```

I tested this out a bit more and noticed that I *can* get a correct copy paste when the whitespace backed copier in the above screenshot isn't triggered. I tried it on 4.2 docs and copying from the whitespace backed copier doesn't copy as expected, either.

I confirmed that the documentation is in rails/rails and so I believe that this issue is valid for this repo.

**Comment by prakashmurthy** [comment] 2016-07-02 23:23
I tried to reproduce the issue locally and wasn't successful at that. I am on a macbook and tried with Chrome, Safari, and Firefox browsers; worked fine in each case.

I agree with Vipul this issue should be closed as it is not caused by rails repository, but most likely a browser quirk.

**Comment by sb8244** [comment] 2016-07-02 23:31
I have been able to recreate this issue on safari and chrome on OSX. Here is a gif of Safari:

![failure](https://cloud.githubusercontent.com/assets/1231659/16542953/6b718cd8-408b-11e6-82bd-d6955742c3d0.gif)

Here is a gif on Chrome + I show how it can work properly at the end

![failurechrome](https://cloud.githubusercontent.com/assets/1231659/16542961/9b05d9a4-408b-11e6-8a39-d25f669262d9.gif)

**Comment by vipulnsward** [comment] 2016-07-02 23:32
I see the issue now, let me see what we do about it.

**Closed** 2016-07-04 06:05 UTC
Labels: attached PR, docs

**Comment by fxn** [comment] 2016-07-04 06:09
The fix is in master and 5-0-stable. Should appear in edge docs soon, and in stable docs with 5.0.1.

**Comment by sb8244** [comment] 2016-07-24 15:39
Thanks Y'all. Nice job @vipulnsward
