### ISSUE TITLE
`RenderStreaming::StreamingTest` fail with since https://github.com/rack/rack/pull/2195

### ISSUE THREAD

**Issue by yahonda** [rails/rails#52066] opened 2024-06-09 00:29 UTC
### Steps to reproduce

Managed to reproduce CI failure at https://buildkite.com/rails/rails-nightly/builds/635#018ff9a7-967b-49b3-b352-0d4b87d6b2fa/1230-1239

```ruby
git clone https://github.com/rails/rails
cd rails/actionpack
export RACK="head"
bundle update rack
bin/test test/controller/new_base/render_streaming_test.rb -n /test_rendering_with/
```

### Expected behavior
It should pass.

### Actual behavior
These tests fail.

```ruby
$ bin/test test/controller/new_base/render_streaming_test.rb -n /test_rendering_with/
Running 9 tests in a single process (parallelization threshold is 50)
Run options: -n /test_rendering_with/ --seed 43709

# Running:

F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_template_exception [test/controller/new_base/render_streaming_test.rb:89]:
Expected # encoding: US-ASCII
#    valid: true
"66" to be nil.


bin/test test/controller/new_base/render_streaming_test.rb:86

F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_streaming_given_to_render [test/controller/new_base/render_streaming_test.rb:60]:
Expected # encoding: US-ASCII
#    valid: true
"37" to be nil.


bin/test test/controller/new_base/render_streaming_test.rb:57

F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_streaming_no_layout [test/controller/new_base/render_streaming_test.rb:72]:
Expected # encoding: US-ASCII
#    valid: true
"21" to be nil.


bin/test test/controller/new_base/render_streaming_test.rb:69

F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_layout_exception [test/controller/new_base/render_streaming_test.rb:83]:
Expected # encoding: US-ASCII
#    valid: true
"84" to be nil.


bin/test test/controller/new_base/render_streaming_test.rb:80

F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_streaming_enabled_at_the_class_level [test/controller/new_base/render_streaming_test.rb:54]:
Expected # encoding: US-ASCII
#    valid: true
"37" to be nil.


bin/test test/controller/new_base/render_streaming_test.rb:51

F

Failure:
RenderStreaming::StreamingTest#test_rendering_with_streaming_do_not_override_explicit_cache_control_given_to_render [test/controller/new_base/render_streaming_test.rb:66]:
Expected # encoding: US-ASCII
#    valid: true
"37" to be nil.


bin/test test/controller/new_base/render_streaming_test.rb:63

.

Finished in 0.263055s, 26.6104 runs/s, 76.0298 assertions/s.
7 runs, 20 assertions, 6 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.3.2 (2024-05-30 revision e5a195edf6) [x86_64-linux]

**Comment by yahonda** [comment] 2024-06-09 00:29
According to git bisect, this behavior change has been introduced since https://github.com/rack/rack/pull/2195/commits/cfeccf6c7ced92cf4592a7c56a6639d6c5eda3d7

**Comment by yahonda** [comment] 2024-06-09 08:41
All of failures happen at 

https://github.com/rails/rails/blob/fdbe3634dff812a38fb0527cc492317dc0f8e00d/actionpack/test/controller/new_base/render_streaming_test.rb#L115

headers did not return "content-length", not it does.

- Before https://github.com/rack/rack/pull/2195/commits/cfeccf6c7ced92cf4592a7c56a6639d6c5eda3d7
```ruby
(rdbg) headers
{"cache-control"=>"no-cache", "transfer-encoding"=>"chunked", "content-type"=>"text/html; charset=utf-8"}
```

- After https://github.com/rack/rack/pull/2195/commits/cfeccf6c7ced92cf4592a7c56a6639d6c5eda3d7
```ruby
(rdbg) headers
{"cache-control"=>"no-cache", "transfer-encoding"=>"chunked", "content-type"=>"text/html; charset=utf-8", "content-length"=>"37"}
```

**Comment by byroot** [comment] 2024-06-09 10:13
We should probably open an issue upstream to discuss this, because this Rack change likely will break way more than just Rails. cc @tenderlove

**Comment by yahonda** [comment] 2024-06-10 04:49
Sure. Let me open an issue to rack/rack.

**Comment by Earlopain** [comment] 2024-06-11 07:35
FYI: https://github.com/rack/rack/pull/2198#issuecomment-2159965622

**Comment by ioquatix** [comment] 2024-06-11 07:51
Apologies, I did not see this issue until now.

I'll try to create a PR to address this issue. I suspect we just need to avoid defining `#to_ary` in whatever class is being used as the response body, but I won't know until I take a closer look at the issue.

Starting from Rack v3, `#to_ary` is used to indicate whether a response can be buffered. Previously `transfer-encoding: chunked` could be used but was not well specified and is explicitly disallowed by HTTP/2. Because it was poorly specified, there have been other related issues like `Rack::ETag` trying to compute ETag's for streaming responses.

**Comment by yahonda** [comment] 2024-06-11 12:48
Thanks for the follow up. I should have opened an issue to rack before the rack 3.1.0 was out. I'm looking forward to a new pull request at rack/rack to address this issue.

**Comment by ioquatix** [comment] 2024-06-11 16:45
I would suggest we hold off on a final 7.2 release until we've resolved this issue.

**Comment by rafaelfranca** [comment] 2024-06-11 18:52
Wait, what? Now we need to block Rails release because Rack decided to release a breaking change in a minor release? Let's revert the change on rack, that should not be merged, sorry.

**Comment by rafaelfranca** [comment] 2024-06-11 19:59
@yahonda when you see the rack main CI failing, let's default to open issues in the rack repo. Maybe it is by design and we need to change Rails, but most often than not it is a regression in rack, so let's try to avoid rack being released breaking Rails by having an issue open there.

**Comment by tenderlove** [comment] 2024-06-11 20:04
> @yahonda when you see the rack main CI failing, let's default to open issues in the rack repo. Maybe it is by design and we need to change Rails, but most often than not it is a regression in rack, so let's try to avoid rack being released breaking Rails by having an issue open there.

+1

I've reverted the change in Rack and shipped a new version.

**Closed by tenderlove** 2024-06-11 20:04 UTC
Labels: actionpack, ci issues
