### ISSUE TITLE
Type of keys returned by grouped count on joined enum column inconsistent after 7.0.5

### ISSUE THREAD

**Issue by adamzapasnik** [rails/rails#48590] opened 2023-06-27 08:26 UTC
### Steps to reproduce
```ruby
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"

  gem 'activerecord', "7.0.4.3"
  # gem 'activerecord', "7.0.5.0"
  gem 'sqlite3'
end

require 'active_record'
require 'sqlite3'

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Base.establish_connection(
  adapter: 'sqlite3',
  database: ':memory:'
)


ActiveRecord::Base.connection.create_table :ufos do |t|
  t.integer :color
end

ActiveRecord::Base.connection.create_table :cows do |t|
  t.belongs_to :ufo
end

class Ufo < ActiveRecord::Base
  has_many :cows

  enum color: [:green, :blue]
end

class Cow < ActiveRecord::Base
  belongs_to :ufo
end

green_ufo = Ufo.create!(color: :green)
blue_ufo = Ufo.create!(color: :blue)

Cow.create!(ufo: green_ufo)
Cow.create!(ufo: green_ufo)
Cow.create!(ufo: green_ufo)
Cow.create!(ufo: blue_ufo)


puts Ufo.group(:color).count
puts Ufo.group("color").count
puts Ufo.group("ufos.color").count


puts Cow.joins(:ufo).group(:color).count
puts Cow.joins(:ufo).group("color").count
puts Cow.joins(:ufo).group("ufos.color").count

```

### Expected behavior
AR 7.0.4.3
```ruby
7.0.4.3
D, [2023-06-27T11:23:15.523050 #37544] DEBUG -- :   Ufo Count (0.4ms)  SELECT COUNT(*) AS "count_all", "ufos"."color" AS "ufos_color" FROM "ufos" GROUP BY "ufos"."color"
{"green"=>1, "blue"=>1}
D, [2023-06-27T11:23:15.523285 #37544] DEBUG -- :   Ufo Count (0.0ms)  SELECT COUNT(*) AS "count_all", "ufos"."color" AS "ufos_color" FROM "ufos" GROUP BY "ufos"."color"
{"green"=>1, "blue"=>1}
D, [2023-06-27T11:23:15.523499 #37544] DEBUG -- :   Ufo Count (0.0ms)  SELECT COUNT(*) AS "count_all", "ufos"."color" AS "ufos_color" FROM "ufos" GROUP BY "ufos"."color"
{"green"=>1, "blue"=>1}
D, [2023-06-27T11:23:15.536016 #37544] DEBUG -- :   Cow Count (0.1ms)  SELECT COUNT(*) AS "count_all", "color" AS "color" FROM "cows" INNER JOIN "ufos" ON "ufos"."id" = "cows"."ufo_id" GROUP BY "color"
{0=>3, 1=>1}
D, [2023-06-27T11:23:15.536388 #37544] DEBUG -- :   Cow Count (0.0ms)  SELECT COUNT(*) AS "count_all", color AS "color" FROM "cows" INNER JOIN "ufos" ON "ufos"."id" = "cows"."ufo_id" GROUP BY color
{0=>3, 1=>1}
D, [2023-06-27T11:23:15.536662 #37544] DEBUG -- :   Cow Count (0.0ms)  SELECT COUNT(*) AS "count_all", "ufos"."color" AS "ufos_color" FROM "cows" INNER JOIN "ufos" ON "ufos"."id" = "cows"."ufo_id" GROUP BY "ufos"."color"
{0=>3, 1=>1}
```

### Actual behavior
AR 7.0.5
```ruby
7.0.5
D, [2023-06-27T11:23:31.090960 #37564] DEBUG -- :   Ufo Count (0.1ms)  SELECT COUNT(*) AS "count_all", "ufos"."color" AS "ufos_color" FROM "ufos" GROUP BY "ufos"."color"
{"green"=>1, "blue"=>1}
D, [2023-06-27T11:23:31.091140 #37564] DEBUG -- :   Ufo Count (0.0ms)  SELECT COUNT(*) AS "count_all", "ufos"."color" AS "ufos_color" FROM "ufos" GROUP BY "ufos"."color"
{"green"=>1, "blue"=>1}
D, [2023-06-27T11:23:31.091316 #37564] DEBUG -- :   Ufo Count (0.0ms)  SELECT COUNT(*) AS "count_all", "ufos"."color" AS "ufos_color" FROM "ufos" GROUP BY "ufos"."color"
{"green"=>1, "blue"=>1}
D, [2023-06-27T11:23:31.094997 #37564] DEBUG -- :   Cow Count (0.1ms)  SELECT COUNT(*) AS "count_all", "color" AS "color" FROM "cows" INNER JOIN "ufos" ON "ufos"."id" = "cows"."ufo_id" GROUP BY "color"
{0=>3, 1=>1}
D, [2023-06-27T11:23:31.095297 #37564] DEBUG -- :   Cow Count (0.0ms)  SELECT COUNT(*) AS "count_all", color AS "color" FROM "cows" INNER JOIN "ufos" ON "ufos"."id" = "cows"."ufo_id" GROUP BY color
{0=>3, 1=>1}
D, [2023-06-27T11:23:31.095528 #37564] DEBUG -- :   Cow Count (0.0ms)  SELECT COUNT(*) AS "count_all", "ufos"."color" AS "ufos_color" FROM "cows" INNER JOIN "ufos" ON "ufos"."id" = "cows"."ufo_id" GROUP BY "ufos"."color"
{"green"=>3, "blue"=>1}
```

I think the inconsistency is easy to spot ☝️ Not sure if a bug? but obviously the behavior has changed to an unpredictable one.

### System configuration
**Rails version**: 7.0.4.3 and 7.0.5.0

**Ruby version**: 3.1.4

**Comment by fatkodima** [comment] 2023-06-27 14:29
Similar to https://github.com/rails/rails/issues/48420. Fixing that issue will also fix this.

**Comment by rafaelfranca** [comment] 2023-06-27 18:05
Duplicate of #48420

**Closed by rafaelfranca** 2023-06-27 18:05 UTC
Labels: activerecord
