### ISSUE TITLE
ActionCable: NoMethodError in websocket/driver/hybi.rb in generate_accept

### ISSUE THREAD

**Issue by Flipez** [rails/rails#30999] opened 2017-10-27 08:38 UTC
NoMethodErrorwebsocket/driver/hybi.rb in generate_accept at line 11

### Steps to reproduce

This bug popped up in our sentry and unfortunately I do not know why exactly occurred. But I think maybe you guys want to dig into this.

### Actual behavior
```
NoMethodError: undefined method `+' for nil:NilClass
  from websocket/driver/hybi.rb:11:in `generate_accept'
  from websocket/driver/hybi.rb:76:in `initialize'
  from websocket/driver.rb:158:in `new'
  from websocket/driver.rb:158:in `rack'
  from action_cable/connection/client_socket.rb:45:in `initialize'
  from action_cable/connection/web_socket.rb:8:in `new'
  from action_cable/connection/web_socket.rb:8:in `initialize'
  from action_cable/connection/base.rb:57:in `new'
  from action_cable/connection/base.rb:57:in `initialize'
  from action_cable/server/base.rb:28:in `new'
  from action_cable/server/base.rb:28:in `call'
  from action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
  from action_dispatch/routing/mapper.rb:46:in `serve'
  from action_dispatch/journey/router.rb:50:in `block in serve'
  from action_dispatch/journey/router.rb:33:in `each'
  from action_dispatch/journey/router.rb:33:in `serve'
  from action_dispatch/routing/route_set.rb:834:in `call'
  from rack/etag.rb:25:in `call'
  from rack/conditional_get.rb:25:in `call'
  from rack/head.rb:12:in `call'
  from rack/session/abstract/id.rb:232:in `context'
  from rack/session/abstract/id.rb:226:in `call'
  from action_dispatch/middleware/cookies.rb:613:in `call'
  from action_dispatch/middleware/callbacks.rb:26:in `block in call'
  from active_support/callbacks.rb:97:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:24:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  from action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from logster/middleware/reporter.rb:31:in `call'
  from rails/rack/logger.rb:36:in `call_app'
  from rails/rack/logger.rb:26:in `call'
  from action_dispatch/middleware/remote_ip.rb:79:in `call'
  from action_dispatch/middleware/request_id.rb:25:in `call'
  from rack/method_override.rb:22:in `call'
  from rack/runtime.rb:22:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  from action_dispatch/middleware/executor.rb:12:in `call'
  from action_dispatch/middleware/static.rb:125:in `call'
  from rack/sendfile.rb:111:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from rails/engine.rb:522:in `call'
  from puma/configuration.rb:225:in `call'
  from puma/server.rb:605:in `handle_request'
  from puma/server.rb:437:in `process_client'
  from puma/server.rb:301:in `block in run'
  from puma/thread_pool.rb:120:in `block in spawn_thread'
```

### System configuration
**Rails version**: 5.1.4

```
actioncable | 5.1.4
actionmailer | 5.1.4
actionpack | 5.1.4
actionview | 5.1.4
activejob | 5.1.4
activemodel | 5.1.4
activerecord | 5.1.4
activesupport | 5.1.4
```

**Ruby version**: ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux]

**Comment by DmytroVasin** [comment] 2017-10-30 04:48
Looks like that issue is a duplication of the https://github.com/rails/rails/issues/30908

**Comment by rafaelfranca** [comment] 2017-10-30 23:39
Duplicate of #30908

**Closed by rafaelfranca** 2017-10-30 23:39 UTC
