### ISSUE TITLE
Controller Test: params with array of hashes merged into 1 hash

### ISSUE THREAD

**Issue by javierjulio** [rails/rails#26069] opened 2016-08-05 22:09 UTC
A little background first. I've been upgrading my Rails 4.2.6 app to Rails 5.0.0. I noticed a few controller test cases failing and they all stem from the same issue here. It seems that when you have a request with params containing a permitted array of hashes, those hashes get merged into one and thus the array always has 1 item in it (unexpected).

Since these tests are for JSON API endpoints I've been wanting to transition our controller tests to integration tests. When I did that for those that failed I noticed these same errors stopped happening. So this seems to only happen for controller tests. I'm not sure if it is strong parameters related since its possible strong parameters is receiving a modified set of params whereas in an integration test its not.

Somewhat related in that this started from researching what happened in #26033.

### Steps to reproduce

This executable script has a controller test (fails) and integration test (passes) to demonstrate the issue. This will help to see the difference. I've added comments as I've tried various things. I thought perhaps we were using strong parameters wrong (its not the easiest to understand sometimes 😞) so I've commented out different approaches but that doesn't seem to be the issue.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
end

require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index'
    resources :posts
  end
end

class PostsController < ActionController::Base
  include Rails.application.routes.url_helpers

  def create
    render json: { post: post_params }
  end

  private

    def post_params
      # NOTE: I've tried different ways of setting strong parameters
      # but the same issue keeps occurring, a controller test merges
      # an array of hashes into one value. I've left different attempts
      # here since I wondered if perhaps I'm using strong parameters
      # incorrectly as I've had trouble understanding it with a complex
      # deeply nested set.
      params.require(:post)
        .permit(
          :title,
          # games_attributes: [ { numbers: permitted_set_names } ]
          # games_attributes: [ { numbers: [ { standard: [] } ] } ]
          games_attributes: [ numbers: [ standard: [] ] ]
        )
    end

    def permitted_set_names
      set_names = {}
      params[:post][:games_attributes][0][:numbers].keys.each do |set_name|
        set_names[set_name] = []
      end
      set_names
    end

end

require 'minitest/autorun'
require 'rack/test'
require 'rails/test_help'

class PostsControllerTest < ActionController::TestCase

  def test_parsed_game_numbers_do_not_come_back_merged
    post :create,
      params: {
        post: {
          title: 'test',
          games_attributes: [
            { numbers: { standard: [1, 2] } },
            { numbers: { standard: [3, 4] } }
          ]
        }
      },
      as: :json

    assert_response :success

    # SIDENOTE: for some reason `response.parsed_body` doesn't work here.
    # It is set and outputs but same hash lookup returns nil. Not sure why.
    # Is `response.parsed_body` not supported with ActionController TestCase?

    json = JSON.parse(response.body)
    # FAILS: returns 1, hashes get merged
    assert_equal 2, json['post']['games_attributes'].size
  end

  private
    def app
      Rails.application
    end
end

class PostsIntegrationTest < ActionDispatch::IntegrationTest

  test "should have a count of 2 in games_attributes" do
    post posts_url,
      params: {
        post: {
          title: 'test',
          games_attributes: [
            { numbers: { standard: [1, 2] } },
            { numbers: { standard: [3, 4] } }
          ]
        }
      },
      as: :json

    assert_response :success
    # PASSES: this is expected behavior.
    assert_equal 2, response.parsed_body['post']['games_attributes'].size
  end

  private
    def app
      Rails.application
    end

end
```

### Expected behavior

I expected the array containing 2 hashes (correct) in params to remain like that and not have the hashes be merged into one and thus be an array of 1 hash (wrong).

### Actual behavior

In a controller test if params has a permitted array of hashes, those hashes get merged into one when they shouldn't be modified at all.

In an integration test that does not happen and the permitted params remain in the structure as given in the request.

### System configuration
**Rails version**: 5.0.0
**Ruby version**: 2.2.3

**Comment by maclover7** [comment] 2016-08-05 23:01
Thank you for opening up another issue @javierjulio! Could be a bit of a longshot, but do you think this is related to #23640?

**Comment by javierjulio** [comment] 2016-08-05 23:08
@maclover7 it could be but I'm not really sure. The issue here is I have an array of hashes and I know all values are passed since they are there but for some reason the hashes are merged into one. If I try to work with the params in a controller action the array always has just one hash rather than what was actually sent. I'm not really sure if its strong parameters related since an integration test works fine which is weird since that uses more of the full Rails stack. When it comes to controller tests I don't know how much stubbed under the hood. My guess is strong parameters is the same in both which makes this weirder. Either way this replicates what I noticed after upgrading to Rails 5 *without any changes* but again this only happened to me when the params contained an array of hashes. It doesn't seem to happen in other cases.

**Comment by tak1n** [comment] 2016-08-16 10:40
I could reproduce it on one of our apps I tried to upgrade, first I thought it's part of this issue: https://github.com/rails/rails/issues/23997#issuecomment-237516461

But the more I dig into it the more I think it is related to this bug report.
I could observe that it happens in controller specs (app I tried to upgrade) and integration tests (in the reproduction app).

When doing the request manually e.g: through Postman it works:

Following json in `PUT /books/1.json`:
```
{
    "book": {
        "title": "Cool",
        "pages_params": [
            {
                "id": 1, "content": "Another Content for page1"
            },
            {
                "id": 2, "_destroy": 1
            },
            {
                "content": "Another new page"
            }
        ]
    }
}
```

Results in this params:

```
[3] pry(#<BooksController>)> params
=> <ActionController::Parameters {"book"=>{"title"=>"Cool", "pages_params"=>[{"id"=>1, "content"=>"Another Content for page1"}, {"id"=>2, "_destroy"=>1}, {"content"=>"Another new page"}]}, "controller"=>"books", "action"=>"update", "id"=>"1", "format"=>"json"} permitted: false>
```

When running it through the integration test I get following params:

```
[1] pry(#<BooksController>)> params
=> <ActionController::Parameters {"book"=>{"title"=>"Cool", "pages_params"=>[{"id"=>"1", "content"=>"another content"}, {"id"=>"2", "_destroy"=>"1", "content"=>"another new page"}]}, "format"=>"json", "controller"=>"books", "action"=>"update", "id"=>"1"} permitted: false>
```

Notice the difference:

```
# Postman json request
"pages_params"=>[{"id"=>1, "content"=>"Another Content for page1"}, {"id"=>2, "_destroy"=>1}, {"content"=>"Another new page"}]}
# Integration test request
"pages_params"=>[{"id"=>"1", "content"=>"another content"}, {"id"=>"2", "_destroy"=>"1", "content"=>"another new page"}]
```

**Comment by maclover7** [comment] 2016-08-16 13:59
cc @tenderlove

**Comment by tak1n** [comment] 2016-08-16 15:07
I digged a little bit deeper, in general the request params from `ActionDispatch::Request` are wrong.

The difference between the test and the real request occurs in here: https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/http/parameters.rb#L63

For the real request I get following:

```
benny@benny-Lenovo-Y50-70:~/dev/onlim/nested_attributes_reproduction$ rails s
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
Started PUT "/books/1.json" for 127.0.0.1 at 2016-08-16 16:55:31 +0200
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"

From: /home/benny/dev/onlim/nested_attributes_reproduction/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb @ line 63 ActionDispatch::Http::Parameters#parse_formatted_parameters:

    60: def parse_formatted_parameters(parsers)
    61:   return yield if content_length.zero?
    62: 
 => 63:   binding.pry
    64:   strategy = parsers.fetch(content_mime_type.symbol) { return yield }
    65: 
    66:   begin
    67:     strategy.call(raw_post)
    68:   rescue # JSON or Ruby code block errors
    69:     my_logger = logger || ActiveSupport::Logger.new($stderr)
    70:     my_logger.debug "Error occurred while parsing request parameters.\nContents:\n\n#{raw_post}"
    71: 
    72:     raise ParamsParser::ParseError
    73:   end
    74: end

[1] pry(#<ActionDispatch::Request>)> parsers
=> {:json=>#<Proc:0x0055cf41633bc8@/home/benny/dev/onlim/nested_attributes_reproduction/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb:9 (lambda)>}
[2] pry(#<ActionDispatch::Request>)> content_mime_type.symbol
=> :json
```

For the integration test request I get following:

```
./bin/rake test TEST="test/integration/book_test.rb" TESTOPTS="--name='/BookTest#test_something$/'"
Run options: "--name=/BookTest#test_something$/" --seed 11688

# Running:


From: /home/benny/dev/onlim/nested_attributes_reproduction/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb @ line 63 ActionDispatch::Http::Parameters#parse_formatted_parameters:

    60: def parse_formatted_parameters(parsers)
    61:   return yield if content_length.zero?
    62: 
 => 63:   binding.pry
    64:   strategy = parsers.fetch(content_mime_type.symbol) { return yield }
    65: 
    66:   begin
    67:     strategy.call(raw_post)
    68:   rescue # JSON or Ruby code block errors
    69:     my_logger = logger || ActiveSupport::Logger.new($stderr)
    70:     my_logger.debug "Error occurred while parsing request parameters.\nContents:\n\n#{raw_post}"
    71: 
    72:     raise ParamsParser::ParseError
    73:   end
    74: end

[1] pry(#<ActionDispatch::Request>)> parsers
=> {:json=>#<Proc:0x0055e20ee514b0@/home/benny/dev/onlim/nested_attributes_reproduction/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb:9 (lambda)>}
[2] pry(#<ActionDispatch::Request>)> content_mime_type.symbol
=> :url_encoded_form
```

Therefore it executes the block which yields the code in the block of https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/http/request.rb#L367 which calls `super`.

The super method is defined in rack and I get following params from it:

```
[1] pry(#<ActionDispatch::Request>)> exit

From: /home/benny/dev/onlim/nested_attributes_reproduction/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/request.rb @ line 353 Rack::Request::Helpers#POST:

    329: def POST
    330:   params = if get_header(RACK_INPUT).nil?
    331:     raise "Missing rack.input"
    332:   elsif get_header(RACK_REQUEST_FORM_INPUT) == get_header(RACK_INPUT)
    333:     get_header(RACK_REQUEST_FORM_HASH)
    334:   elsif form_data? || parseable_data?
    335:     unless set_header(RACK_REQUEST_FORM_HASH, parse_multipart)
    336:       form_vars = get_header(RACK_INPUT).read
    337: 
    338:       # Fix for Safari Ajax postings that always append \0
    339:       # form_vars.sub!(/\0\z/, '') # performance replacement:
    340:       form_vars.slice!(-1) if form_vars[-1] == ?\0
    341: 
    342:       set_header RACK_REQUEST_FORM_VARS, form_vars
    343:       set_header RACK_REQUEST_FORM_HASH, parse_query(form_vars, '&')
    344: 
    345:       get_header(RACK_INPUT).rewind
    346:     end
    347:     set_header RACK_REQUEST_FORM_INPUT, get_header(RACK_INPUT)
    348:     get_header RACK_REQUEST_FORM_HASH
    349:   else
    350:     {}
    351:   end
    352: 
 => 353:   binding.pry
    354: 
    355:   params
    356: end

[1] pry(#<ActionDispatch::Request>)> params
=> {"book"=>{"title"=>"Cool", "pages_params"=>[{"id"=>"1", "content"=>"another content"}, {"id"=>"2", "_destroy"=>"1", "content"=>"another new page"}]}, "format"=>"json"}
```

So following problems I see for now:

* In the integration test request the content_mime_type is not set properly (altough specified through `format: :json`)
* The Rack params parser which is used as fallback when no parser strategy matches returns something different then the rails params parser.

Will try to dig deeper into those 2 problems when I got more time.

**Comment by javierjulio** [comment] 2016-08-16 15:45
@tak1n interesting. Your case with nested attributes for creating/updating/deleting all in one was the first issue I ran into when upgrading to Rails 5 but seems to be the opposite result. The controller test failed on upgrading and then when I moved the same test case to an integration test everything passed. The params were parsed as they were given but in the controller test for some reason the params were not. So weird.

I could share another example demonstrating this issue but the underlying issue is the same. In controller tests, the params are not in the same structure as they were given in the JSON request.

**Comment by javierjulio** [comment] 2016-08-16 16:06
@tak1n I commented elsewhere about your sample code but note that `format: :json` does not work on integration tests, only on controller tests (based on documentation in respective rails code files). If you update your test case I'm sure the integration test will now pass which is the behavior I was seeing, but the controller test will continue to fail.

For integration tests use `as: :json` as listed here:
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L311

For controller tests use `format: :json` as listed here:
https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L433

**Comment by tak1n** [comment] 2016-08-17 04:55
@javierjulio yep ur right I forgot this `as: :json` thing in the integration test, will move it to a controller spec/test and dig further into it.

With `as: :json` on the integration test request I get following content mime type and params:

```
./bin/rake test TEST="test/integration/book_test.rb" TESTOPTS="--name='/BookTest#test_something$/'"
Run options: "--name=/BookTest#test_something$/" --seed 62769

# Running:


From: /home/benny/dev/onlim/nested_attributes_reproduction/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb @ line 63 ActionDispatch::Http::Parameters#parse_formatted_parameters:

    60: def parse_formatted_parameters(parsers)
    61:   return yield if content_length.zero?
    62: 
 => 63:   binding.pry
    64:   strategy = parsers.fetch(content_mime_type.symbol) { return yield }
    65: 
    66:   begin
    67:     strategy.call(raw_post)
    68:   rescue # JSON or Ruby code block errors
    69:     my_logger = logger || ActiveSupport::Logger.new($stderr)
    70:     my_logger.debug "Error occurred while parsing request parameters.\nContents:\n\n#{raw_post}"
    71: 
    72:     raise ParamsParser::ParseError
    73:   end
    74: end

[1] pry(#<ActionDispatch::Request>)> content_mime_type.symbol
=> :json
[2] pry(#<ActionDispatch::Request>)> exit

From: /home/benny/dev/onlim/nested_attributes_reproduction/app/controllers/books_controller.rb @ line 3 BooksController#update:

    2: def update
 => 3:   binding.pry
    4: end

[1] pry(#<BooksController>)> params
=> <ActionController::Parameters {"book"=>{"title"=>"Cool", "pages_params"=>[{"id"=>1, "content"=>"another content"}, {"id"=>2, "_destroy"=>1}, {"content"=>"another new page"}]}, "controller"=>"books", "action"=>"update", "id"=>"1", "format"=>"json"} permitted: false>
```

**Comment by tak1n** [comment] 2016-08-17 05:02
@javierjulio as far as I know there are "no" controller tests anymore in rails 5, basically they inherit from the same test class `ActionDispatch::IntegrationTest` therefore I think also for controller tests u have to set `as: :json`.

With that set the `content_mime_type.symbol` is `:json` and uses the rails parser as strategy.
If this is not set it is `:url_encoded_form` and falls back to the rack parser which obviously has some problems.

`as: :json` not set:

```
From: /home/benny/dev/onlim/nested_attributes_reproduction/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb @ line 63 ActionDispatch::Http::Parameters#parse_formatted_parameters:

    60: def parse_formatted_parameters(parsers)
    61:   return yield if content_length.zero?
    62: 
 => 63:   binding.pry
    64:   strategy = parsers.fetch(content_mime_type.symbol) { return yield }
    65: 
    66:   begin
    67:     strategy.call(raw_post)
    68:   rescue # JSON or Ruby code block errors
    69:     my_logger = logger || ActiveSupport::Logger.new($stderr)
    70:     my_logger.debug "Error occurred while parsing request parameters.\nContents:\n\n#{raw_post}"
    71: 
    72:     raise ParamsParser::ParseError
    73:   end
    74: end

[1] pry(#<ActionDispatch::Request>)> content_mime_type.symbol
=> :url_encoded_form
```

`as: :json` set:

```
From: /home/benny/dev/onlim/nested_attributes_reproduction/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb @ line 63 ActionDispatch::Http::Parameters#parse_formatted_parameters:

    60: def parse_formatted_parameters(parsers)
    61:   return yield if content_length.zero?
    62: 
 => 63:   binding.pry
    64:   strategy = parsers.fetch(content_mime_type.symbol) { return yield }
    65: 
    66:   begin
    67:     strategy.call(raw_post)
    68:   rescue # JSON or Ruby code block errors
    69:     my_logger = logger || ActiveSupport::Logger.new($stderr)
    70:     my_logger.debug "Error occurred while parsing request parameters.\nContents:\n\n#{raw_post}"
    71: 
    72:     raise ParamsParser::ParseError
    73:   end
    74: end

[1] pry(#<ActionDispatch::Request>)> content_mime_type.symbol
=> :json
```

**Comment by tak1n** [comment] 2016-08-17 05:34
Still `rspec-rails` controller specs include `ActionController::TestCase::Behavior` this means u have to specify the format with `format: :json` in the params.

I updated the reproduction app and included `rspec-rails` and a controller spec: https://github.com/tak1n/nested_attributes_reproduction/commit/85360ea53911f0ca238a38f973e5bdb03e635726

For the given controller spec I get following `content_mime_type.symbol`:

```
bundle exec rspec spec/controllers/books_controller_spec.rb:24
Run options: include {:locations=>{"./spec/controllers/books_controller_spec.rb"=>[24]}}

From: /home/benny/dev/onlim/nested_attributes_reproduction/.gem/ruby/2.3.1/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb @ line 63 ActionDispatch::Http::Parameters#parse_formatted_parameters:

    60: def parse_formatted_parameters(parsers)
    61:   return yield if content_length.zero?
    62: 
 => 63:   binding.pry
    64:   strategy = parsers.fetch(content_mime_type.symbol) { return yield }
    65: 
    66:   begin
    67:     strategy.call(raw_post)
    68:   rescue # JSON or Ruby code block errors
    69:     my_logger = logger || ActiveSupport::Logger.new($stderr)
    70:     my_logger.debug "Error occurred while parsing request parameters.\nContents:\n\n#{raw_post}"
    71: 
    72:     raise ParamsParser::ParseError
    73:   end
    74: end

[1] pry(#<ActionController::TestRequest>)> content_mime_type.symbol
=> :url_encoded_form
```

So the integration test misbehavior was my fault, but `rspec-rails` controller specs still use `ActionController::TestCase::Behavior` which means specifying the format with the param `format: :json`.

Also if I would upgrade a rails 4 app (which uses `ActionController::TestCase` for controller tests) the same happens.

**Comment by rafaelfranca** [comment] 2016-08-17 05:49
> So the integration test misbehavior was my fault, but rspec-rails controller specs still use ActionController::TestCase::Behavior which means specifying the format with the param format: :json.

This is the expected behavior. If you want controller specs to parse paraters as json you need to explicitly specify it. The default is `url_encoded_form`, `format: :json` doesn't set the content type so you need to set the `request.header['CONTENT_TYPE']` to `application/json`, like any request object that exists.

**Comment by tak1n** [comment] 2016-08-17 06:05
I always assumed `format: :json` sets the mime type to json for the test request (which is wrong).

The `ActionController::TestCase#process` method (which deprecates get, put, post etc) calls `ActionController::TestRequest#assign_parameters` in https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L523 which lives in https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L96 where rack's `fetch_header` is called.

Rack's `fetch_header` is defined here: https://github.com/rack/rack/blob/master/lib/rack/request.rb#L56

This means the mime type of a `ActionController::TestRequest` is set to `:url_encoded_form` because the `CONTENT_TYPE` header is set to `application/x-www-form-urlencoded` when no header is specified.

Therefore as shortterm fix for my failing controller specs I can do following:

```ruby
@request.env['CONTENT_TYPE'] = 'application/json'
```

This sets the `CONTENT_TYPE` header properly and therefore the rails json params parser is used instead of the rack fallback params parser.

**Comment by tak1n** [comment] 2016-08-17 09:17
@javierjulio another fix would be to specify nested attributes not as array but as hash:

```ruby
params = {
      id: @book.id,
      book: {
        title: 'Cool',
        pages_params: {
          "0" => { id: @page.id, content: 'another content' },
          "1" => { id: @delete_page.id, _destroy: 1 },
          "2" => { content: 'another new page' }
        }
      },
      format: :json
    }
```

Unfortunately this was removed from the documentation of nested attributes so I don't know if this is going to stay valid. http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html

**Comment by rafaelfranca** [comment] 2016-08-19 03:06
This will be fixed by #26212. I'll write on that PR the description why this happened.

**Comment by rafaelfranca** [comment] 2016-08-19 04:47
Fixed by that PR.

**Closed by rafaelfranca** 2016-08-19 04:47 UTC
Labels: actionpack

**Comment by jiggneshhgohel** [comment] 2016-10-07 07:51
@tak1n your suggestion in comment https://github.com/rails/rails/issues/26069#issuecomment-240358290 about using Hashes instead of Array helped me in resolving this params mingling issue. 

Thanks.

**Comment by jiggneshhgohel** [comment] 2021-12-15 12:15
w.r.t the discussion in this issue, and the recommended and suggested solutions, I have posted a detailed answer in https://stackoverflow.com/a/70363366/936494 based on the problems I encountered in my context wherein I am using following versions of ruby and gems:

* ruby 2.3.2
* rails (5.0.0.1)
* rspec-rails (3.5.2)

**Comment by Paddlesleepy2** [comment] 2025-10-20 20:26
I unlocked it https://administrator71.github.io/wqi0SMqjBCK6ul2e2ReH2GeAjgq7vOKOY9zrk8QIMTTLnhUSO7RuA/

**Comment by zzak** [comment] 2025-10-22 01:56
There have been a few cases recently of bots posting suspicious links in old PRs or issues, please don't click them.

You can report the message to GitHub and they will deal with it.
