### ISSUE TITLE
`truncate' on html-safe input will escape only when truncating

### ISSUE THREAD

**Issue by afn** [rails/rails#13721] opened 2014-01-15 20:35 UTC
If the text passed to truncate is an html-safe string, the result gets an extra level of encoding if (and only if) truncation is performed.  This seems unintuitive, although it's not clear from the documentation whether the expected behavior is to encode in both cases or neither.

```
Loading development environment (Rails 4.1.0.beta1)
2.1.0p0 :001 > include ActionView::Helpers
 => Object
2.1.0p0 :002 > truncate('foo&amp;bar blahblahblah'.html_safe, length: 20, separator: ' ')
 => "foo&amp;amp;bar..."
2.1.0p0 :003 > truncate('foo&amp;bar blahblahblah'.html_safe, length: 30, separator: ' ')
 => "foo&amp;bar blahblahblah"
```

If I pass `escape: true` the behavior is unchanged.

**Comment by listx** [comment] 2015-01-08 22:49
I just want to make clear/summarize the discussion so far, but with slightly
adjusted input methods to help ease readability for others looking at this
issue. My goal is to help others understand the issue better (maybe we need more
help on this thing?). I hope it helps!

I am using the input string `>>>>>` because they are just as HTML-unsafe as
@afn's original example, and I can still reproduce the same kind of behavior,
when `html_safe` is involved. Also, I'll be using `omission: 'X'` because I
think it makes the output easier to read.

The following is the block of code to paste into your Rails console to
cross-check against my machine.

.irbrc:
```
include ActionView::Helpers::TextHelper
truncate('>>>>>',           omission: 'X', length: 5)
truncate('>>>>>',           omission: 'X', length: 4)
truncate('>>>>>',           omission: 'X', length: 5, escape: true)
truncate('>>>>>',           omission: 'X', length: 5, escape: false)
truncate('>>>>>',           omission: 'X', length: 4, escape: true)
truncate('>>>>>',           omission: 'X', length: 4, escape: false)
truncate('>>>>>'.html_safe, omission: 'X', length: 5)
truncate('>>>>>'.html_safe, omission: 'X', length: 4)
truncate('>>>>>'.html_safe, omission: 'X', length: 5, escape: true)
truncate('>>>>>'.html_safe, omission: 'X', length: 5, escape: false)
truncate('>>>>>'.html_safe, omission: 'X', length: 4, escape: true)
truncate('>>>>>'.html_safe, omission: 'X', length: 4, escape: false)
```

```
Loading development environment (Rails 4.2.0)
irb(main):001:0> include ActionView::Helpers::TextHelper
=> Object
irb(main):002:0> truncate('>>>>>',           omission: 'X', length: 5)
=> "&gt;&gt;&gt;&gt;&gt;"

	(A) OK; we escape the string to make it HTML-safe.

irb(main):003:0> truncate('>>>>>',           omission: 'X', length: 4)
=> "&gt;&gt;&gt;X"

	(B) OK; we escape the string to make it HTML-safe, then remove the last
    character with an 'X', our omission character. We get a total length of 4
    characters rendered on-screen, which is great!

irb(main):004:0> truncate('>>>>>',           omission: 'X', length: 5, escape: true)
=> "&gt;&gt;&gt;&gt;&gt;"

	(C) OK; no change from (A); the only difference is that we escape
    explicitly.

irb(main):005:0> truncate('>>>>>',           omission: 'X', length: 5, escape: false)
=> ">>>>>"

	(D) OK; escaping is disabled so we get the plain string back.

irb(main):006:0> truncate('>>>>>',           omission: 'X', length: 4, escape: true)
=> "&gt;&gt;&gt;X"

	(E) OK; this is just like (B), but with explicity escaping with `escape`.

irb(main):007:0> truncate('>>>>>',           omission: 'X', length: 4, escape: false)
=> ">>>X"

	(F) OK; we disable escaping, and we also truncate.


irb(main):008:0> truncate('>>>>>'.html_safe, omission: 'X', length: 5)
=> ">>>>>"

	(G) OK; this is expected. It is the functional equivalent of (D). The only
    difference is that the string is marked HTML-safe, instead of passing in
    `escape: false`.

irb(main):009:0> truncate('>>>>>'.html_safe, omission: 'X', length: 4)
=> "&gt;&gt;&gt;X"

	(H) ERROR 1; this is the bug as originally described by @afn.

irb(main):010:0> truncate('>>>>>'.html_safe, omission: 'X', length: 5, escape: true)
=> ">>>>>"

	(I) ERROR 2?; this is a special case. Although we marked the string as
    HTML-safe, we still asked Rails to escape it, but it did not. This is what
    @pallan's first comment was addressing. Whether this is a bug itself or not
    depends on how you want to define the precedence of `escape` vs the
    `html_safe` method.

irb(main):011:0> truncate('>>>>>'.html_safe, omission: 'X', length: 5, escape: false)
=> ">>>>>"

	(J) OK; however, the coder cannot tell whether the string was left as-is,
    because of the call to `.html_safe` or because we told it explicitly not to
    escape with `escape: false`, or both!

irb(main):012:0> truncate('>>>>>'.html_safe, omission: 'X', length: 4, escape: true)
=> "&gt;&gt;&gt;X"

	(K) OK? This is just like (I) in that it is a special case. We already
    marked the string as HTML-safe, but we explicitly asked Rails to escape it.
    Personally, I think this is not an error and is expected behavior.

irb(main):013:0> truncate('>>>>>'.html_safe, omission: 'X', length: 4, escape: false)
=> ">>>X"

	(L) OK; however, just like (J), we cannot tell whether it was `.html_safe`
    or `escape: false` that made the resulting string not HTML-escaped.

```

I think the discussion so far boils down to (H) and (I). @afn's second comment
is about cases (J) and (K), where the precedence of `.html_safe` vs. `escape:
true/false` is ambiguous.

I disagree with @afn's 2nd comment; I think that the `escape` option should take
precedence over `.html_safe`, because it is explicit. That is, even if a string
is marked HTML-safe, passing along `escape: true` should still make it
HTML-escaped one level. After all, whether the string is marked HTML-safe with
`.html_safe` is something that might happen elsewhere in the application; if
we're calling `truncate` with `escape` *now*, it makes sense to uphold that
request.

I believe resolving the ambiguity between passing in
already-HTML-safe-marked-strings vs. the `escape` option is just as important
here as the original bug report.

**Comment by SuckRok** [comment] 2016-01-14 04:17
1

**Comment by ghiculescu** [comment] 2021-09-03 20:06
Closing this issue per https://github.com/rails/rails/pull/13730#issuecomment-382767619

**Closed by ghiculescu** 2021-09-03 20:06 UTC
Labels: actionview, attached PR
