### ISSUE TITLE
Association nil with accepts_nested_attributes

### ISSUE THREAD

**Issue by jordanthomas** [rails/rails#20690] opened 2015-06-24 18:25 UTC
Encountered some strange behavior with associations when a model `accepts_nested_attributes`.

Test file showing behavior:
https://gist.github.com/jordanthomas/e6cc3f7c2db773adeb7d

When a parent model with a `has_many` association `accepts_nested_attributes` the association from child to parent is nil. It came to our attention when removing the protected_attributes gem from a project. With it, this behavior did not exist.

``` ruby
c = Car.new
w = c.wheel.build
w.car # nil
```

I'd be happy to invest some time tracking this down further if someone can point me in the right direction.

**Comment by pascalbetz** [comment] 2015-06-24 19:58
Looks like the association is only set when you _save_ the parent. Or if you add _inverse_of_ option to the _has_many_. Not sure if the difference with _nested_attributes_ is intended.

**Comment by jordanthomas** [comment] 2015-06-25 14:42
Added a test to the gist above demonstrating how adding `inverse_of` to an association with `accepts_nested_attributes` effects the outcome.

https://gist.github.com/jordanthomas/e6cc3f7c2db773adeb7d

**Comment by mberning** [comment] 2015-06-29 20:26
Ran tests provided in gist and received the failure

**Comment by tjshipe** [comment] 2015-06-29 22:25
Same +1

**Comment by Rafe** [comment] 2015-06-30 03:03
Looks related to #20451, accepts_nested_attributes make the association not able to inverse.

**Comment by ojab** [comment] 2016-02-12 15:13
Reproducible also with `has_one` on current master.

**Comment by ojab** [comment] 2016-02-12 15:16
[Up-to-date testcase with has_one added](https://gist.github.com/ojab/f4fe4448bcbaf5694184)

**Comment by ojab** [comment] 2016-02-12 16:09
(I've tried to bisect this, it's reproducible on 3.0.3 and older versions are not so easy to install because of `bundler '~> 1.0'` dependency and alike)

**Comment by xhoy** [comment] 2017-08-01 12:02
This bug is fixed with this commit: https://github.com/rails/rails/commit/c7adc610f0233b9afd51a6d68aa9061cdb250fad seems to be fixed in 5.1.rc3+?

**Comment by sgrif** [comment] 2017-08-01 15:21
Confirmed that the provided reproduction script passes on master.

**Comment by sgrif** [comment] 2017-08-01 15:21
Confirmed that the provided reproduction script passes on 5-1-stable.

**Closed by sgrif** 2017-08-01 15:21 UTC
Labels: activerecord, With reproduction steps
