### ISSUE TITLE
6.0.0 – Bundler could not find compatible versions for gem "railties" for a NEW app

### ISSUE THREAD

**Issue by HoracioChavez** [rails/rails#36953] opened 2019-08-16 19:19 UTC
### Steps to reproduce

`rails new six`

### Expected behavior
Business as usual – A new App. 

### Actual behavior
```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      railties (= 6.0.0)

    sass-rails (~> 5) was resolved to 5.0.4, which depends on
      railties (>= 4.0.0, < 5.0)

    web-console (>= 3.3.0) was resolved to 4.0.0, which depends on
      railties (>= 6.0.0.a)

    webpacker (~> 4.0) was resolved to 4.0.7, which depends on
      railties (>= 4.2)
         run  bundle binstubs bundler
Could not find gem 'puma (~> 3.11)' in any of the gem sources listed in your Gemfile.
         run  bundle exec spring binstub --all
Could not find gem 'puma (~> 3.11)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
       rails  webpacker:install
Could not find gem 'puma (~> 3.11)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```

#### Complete output
```
          ➜  rails new six
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/horacio/Projects/six/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_0.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_6_0.rb
         run  bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      railties (= 6.0.0)

    sass-rails (~> 5) was resolved to 5.0.4, which depends on
      railties (>= 4.0.0, < 5.0)

    web-console (>= 3.3.0) was resolved to 4.0.0, which depends on
      railties (>= 6.0.0.a)

    webpacker (~> 4.0) was resolved to 4.0.7, which depends on
      railties (>= 4.2)
         run  bundle binstubs bundler
Could not find gem 'puma (~> 3.11)' in any of the gem sources listed in your Gemfile.
         run  bundle exec spring binstub --all
Could not find gem 'puma (~> 3.11)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
       rails  webpacker:install
Could not find gem 'puma (~> 3.11)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3

**Comment by arun057** [comment] 2019-08-16 19:51
Confirming issue on a completely fresh install as well

**Comment by neidiom** [comment] 2019-08-16 20:20
Having the same issue.

**Comment by zocoi** [comment] 2019-08-16 20:22
A duplicate of https://github.com/rails/rails/issues/36954

**Comment by rafaelfranca** [comment] 2019-08-16 20:26
Duplicate of #36954

**Closed** 2019-08-16 20:26 UTC

**Comment by 9mm** [comment] 2019-08-16 21:58
Ok... I am glad I'm not crazy.
