### ISSUE TITLE
localhost/%C0 generates BadRequest (Maybe because of non UTF-8 characters in the url?)

### ISSUE THREAD

**Issue by nadavb** [rails/rails#33672] opened 2018-08-21 15:06 UTC
localhost/%C0 generates BadRequest (Maybe because of non UTF-8 characters in the url?)

Rails version:
5.0.0
Ruby version:
2.2.7

ActionController::BadRequest in ApplicationController#raise_not_found!

actionpack (5.0.0) lib/action_dispatch/http/request.rb:75:in `block in check_path_parameters!'
actionpack (5.0.0) lib/action_dispatch/http/request.rb:72:in `each'
actionpack (5.0.0) lib/action_dispatch/http/request.rb:72:in `check_path_parameters!'
actionpack (5.0.0) lib/action_dispatch/http/request.rb:86:in `controller_class'
actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:44:in `controller'
actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:30:in `serve'
actionpack (5.0.0) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:725:in `call'
exception_notification (4.2.2) lib/exception_notification/rack.rb:41:in `call'

It should be very simple, yet I can see the solution no where.

**Comment by rafaelfranca** [comment] 2018-08-21 18:09
Can you reproduce this in Rails 5.2? Rails 5.0 is not supported anymore.

**Comment by nadavb** [comment] 2018-08-21 18:21
Oh come on. I did it on 4.0.2, and somebody said that I will do it on 5, and closed the issue without giving me the option to reply. I did it on 5.0.0 and now you are asking to do it on 5.2.0. 
Can you please simply try to paste the link:

localhost/%C0

and see if it happens to you? If it doesn't then I will do another migration to 5.2.0 to try and reproduce.

Thanks.

**Comment by rafaelfranca** [comment] 2018-08-21 18:26
I can't, sorry. I don't have any application in hand. When in doubt about which versions are supported check https://guides.rubyonrails.org/maintenance_policy.html.

**Comment by tgturner** [comment] 2018-08-21 18:36
<img width="1439" alt="screen shot 2018-08-21 at 2 30 31 pm" src="https://user-images.githubusercontent.com/16597153/44421783-84929b00-a54f-11e8-880f-124e57031c03.png">

Looks like it isn't generating a BadRequest

**Comment by rafaelfranca** [comment] 2018-08-21 19:00
Cool, so it is fixed already in Rails 5.2. Given that is the first version that is supported to bug fixes and it is working I'm closing this issue. Thank you for verifying.

**Closed by rafaelfranca** 2018-08-21 19:00 UTC
