### ISSUE TITLE
Uninitialized constant when create reusable module

### ISSUE THREAD

**Issue by fauzieuy** [rails/rails#40118] opened 2020-08-27 07:30 UTC
We try to implement [Reducing boilerplate](https://github.com/fotinakis/swagger-blocks#reducing-boilerplate) on swagger block to DRY declaring parameter headers on swagger

We create a module `app/controllers/concerns/swagger/v1/authentication_header.rb`

```
module Swagger
    module V1
        module AuthenticationHeader
            def self.extended(base)
                base.parameter do
                    key :name, :uid
                    key :in, :header
                    key :description, 'UID'
                    key :required, true
                end
                base.parameter do
                    key :name, :authorization
                    key :in, :header
                    key :description, 'Bearer [Token Here]'
                    key :required, true
                end
            end
        end
    end
end
```

And extend it on controller `app/controllers/api/v1/shop/categories_controller.rb`

```
module Api
    module V1
        module Shop
            class CategoriesController < ApplicationController

                swagger_path '/api/v1/shop/categories/list' do
                    operation :get do
                        extend Swagger::V1::AuthenticationHeader
                        extend Swagger::V1::ErrorResponse
                        # other stuff here ...
                    end
               end
           end
       end
   end
end
```

### Expected behavior
It's work return parameter headers block

### Actual behavior
When load swagger doc we got : 
```
Started GET "/apidocs/v1" for 127.0.0.1 at 2020-08-27 09:03:44 +0000
  
NameError (uninitialized constant V1::AuthenticationHeader):
```

Also try use rails console
```
Running via Spring preloader in process 8950
Loading development environment (Rails 6.0.3.2)
2.7.1 :001 > Swagger::V1::AuthenticationHeader
Traceback (most recent call last):
        1: from (irb):1
NameError (uninitialized constant V1::AuthenticationHeader)
```

When I change the module name of V1 to another name (eg : Version1) It's work.
We have a lot of V1 module, it's looks like collasion name,  Does it matter if we have a structure module looks like this?
```
- app
    - controllers
       - api
           - v1
              - shop
      - concerns
          - swagger
             - v1
     - serializers
         - v1
            - shop
     - services
         - v1
            - shop
```

### System configuration
Rails version : 6.0.3.2
Ruby version : 2.7.1

We use classic autoloader

```
config.load_defaults 6.0
config.autoloader = :classic
```

**Comment by KapilSachdev** [comment] 2020-08-27 07:59
If you require the file `authentication_header.rb` and use `Swagger::V1::AuthenticationHeader` it would work, but thats not how rails defines constants.
Rails autoload constants based on _path_ rather than requiring a file.

You should either create a folder named `swagger` with `v1` inside it to use `Swagger::V1::AuthenticationHeader`

```ruby
# app/controllers/concers/swagger/v1/authentication_header.rb
module Swagger
  module V1
    module AuthenticationHeader
      ...
    end
  end
end
```
or remove `Swagger` module namespace to use `V1::AuthenticationHeader`.
```ruby
# app/controllers/concers/v1/authentication_header.rb
module V1
  module AuthenticationHeader
  end
end
```

**Comment by fauzieuy** [comment] 2020-08-27 08:22
> You should either create a folder named `swagger` with `v1` inside it to use `Swagger::V1::AuthenticationHeader`

We've directory structure like that, sorry I've mistake on post, OP just has updated.

**Comment by KapilSachdev** [comment] 2020-08-27 08:33
In that case I'm unable to reproduce the issue. This might be something to do with the fact that you have many modules with `V1` namespace in it.

Can you try if `::Swagger::V1::AuthenticationHeader` instead of `Swagger::V1::AuthenticationHeader` and see if that is defined.

Also see if  `config.autoloader = :zeitwerk` changes anything (i doubt that, but just to verify).

**Comment by fauzieuy** [comment] 2020-08-27 08:35
@KapilSachdev it's works now, I don't know why, I just move swagger directory to controller and move again to concerns directory without change any code inside.

**Comment by KapilSachdev** [comment] 2020-08-27 08:43
That's interesting. Please close the issue if you think its resolved.

_Please note that this issue tracker is for tracking bug in rails source code and the issue mentioned was related to application structure. Please use stackoverflow or similar platforms for issues like these, but feel free to create issues here in case you think `rails` is the culprit_

**Closed** 2020-08-27 09:13 UTC
