### ISSUE TITLE
ActiveStorage: uploaded video doesn't seek in Chrome

### ISSUE THREAD

**Issue by StanlyShauro** [rails/rails#33368] opened 2018-07-15 13:25 UTC
**rails 5.2.0, ActiveStorage::DiskController**
I upload a video file (MP4) to activestorage, than insert it on a page via

```
<%=video_tag rails_blob_url(@video.video) ... or
<%=video_tag url_for(@video.video)
```
I can't rewind or seek video in Chrome and Chrome-based browsers.

I suppose there is a problem with ` http headers` in server response. DiskController doesn't provide enough information in `response`
1 - missing `Content-Length`.
2 - response code could be 206 instead 200 with http header `Content-Range`

**Comment by georgeclaghorn** [comment] 2018-07-15 15:11
This is a duplicate of #32193.

**Closed by georgeclaghorn** 2018-07-15 15:11 UTC
