### ISSUE TITLE
`reverting?` method does not work with PostgreSQLAdapter

### ISSUE THREAD

**Issue by nbrustein** [rails/rails#41175] opened 2021-01-19 18:16 UTC
### Steps to reproduce

1. Using a rails app that connects to a postgresql database
2. Put a debugger inside of `def down` in a migration
3. Rollback the migration to hit the debugger
4. `self.reverting? => false`
5. `self.connection.class => ActiveRecord::ConnectionAdapters::PostgreSQLAdapter`
6. `self.connection.respond_to?(:reverting) => false`

### Expected behavior
The `reverting?` method should return `true` when reverting a migration.

### Actual behavior
The `reverting?` method returns `false` when reverting a migration.

### Note
It seems like this must have worked in the past, because I have code in my app in old migrations that relied on `reverting?`

### System configuration
**Rails version**:
6.0.3.4

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]

**Comment by intrip** [comment] 2021-02-09 11:42
Could you please provide an execution script? This would ease the process.

**Comment by nbrustein** [comment] 2021-02-09 12:07
Add this at `db/migrate/20210209120309_test_reverting.rb`

```
class TestReverting < ActiveRecord::Migration[6.0]
    def up
        puts " ******************** reverting: #{reverting?.inspect}"
    end

    def down
        puts " ******************** reverting: #{reverting?.inspect}"
    end
end

```

Then run:

```
rake db:migrate
rake db:rollback
```

I would expect to see ` ******************** reverting: false` when I migrate and ` ******************** reverting: true` when I rollback, but I'm seeing `false` both times.

**Comment by intrip** [comment] 2021-02-10 11:47
@nbrustein 
I don't think your expectations are correct: `reverting?` is used to figure out which operation to do and is set automatically in the `change` methods. For example:

```ruby
def change
  p reverting?
end

rake db:migrate
rake db:rollback
```

will print correctly: 
```ruby
true
false
```

The same applies for

```ruby
def up
   p reverting?
end
def down
  revert {   p reverting? }
end
```

In short this is not a bug.

**Comment by nbrustein** [comment] 2021-02-10 13:18
I see.  My issue is that I have a helper method that is sometimes called when migrating and sometimes called when rolling back, and I need to be able to tell the difference.  

Is there some way to do that?  It's like this:

```
module MigrationHelper

    def my_helper
        if reverting?
            # do something
        else
            # do something else
        end      
    end

end

class TestReverting < ActiveRecord::Migration[6.0]
    include MigrationHelper

    # ...
end

```

**Comment by fatkodima** [comment] 2021-02-10 19:22
Have you considered [`reversible`](https://api.rubyonrails.org/classes/ActiveRecord/Migration.html#method-i-reversible)?

**Comment by nbrustein** [comment] 2021-02-10 22:40
I don't think that would let my helper know which direction I was going in.  I guess I can make it an argument to the helper, and then it could be implemented either with `reversible` or with separate `down` and `up` methods, like in the following code.

But I'd prefer it if I didn't have to do that, and the helper could somehow figure it out on its own.

```
module MigrationHelper

    def my_helper(reverting)
        if reverting
            # do something
        else
            # do something else
        end      
    end

end

class TestReverting < ActiveRecord::Migration[6.0]
    include MigrationHelper

    def up
        my_helper(true)
    end

    def up
        my_helper(false)
    end

end
```

**Comment by intrip** [comment] 2021-02-15 11:44
Technically `reverting` is used not to expose the direction of the migration but to figure out if a statement such as `add_column` needs to be interpreted in the opposite way `remove_column`.

Could you please elaborate further the use case of your helper method so that hopefully I could give you some hints ? 🙂

**Comment by nbrustein** [comment] 2021-02-15 15:40
It's probably more effort that in it's worth for me to try to explain or for you to try to understand the details of what we're doing here.  It's not a big deal.  If there's no way to detect whether we're migrating or reverting, we can just keep passing it into the method.  It's only a small inconvenience.  Thanks for your help.

**Comment by intrip** [comment] 2021-02-15 15:58
You're welcome. 
I think we can close this issue then 😃

**Closed** 2021-06-21 19:19 UTC
Labels: activerecord
