### ISSUE TITLE
Rails Guides

### ISSUE THREAD

**Issue by lws68825** [rails/rails#28252] opened 2017-03-02 13:25 UTC
Hi, when I clicked the "Rails 4.2" link on the home page of Ruby on Rails Guides, it was linked to the Edge Guides. please fix it.

**Comment by st0012** [comment] 2017-03-02 13:55
Confirmed. But the link's url is correct, I was redirected to the Edge Guides.

**Comment by robin850** [comment] 2017-03-02 21:03
Hi there !

Thanks for reporting this ! It looks like the documentation for Rails 4.2.8 hasn't been properly generated on the server (both the guides and the API documentation).

Actually the `/v4.2` endpoints should point to `/v4.2.8` at the moment but it looks like the URL doesn't exist, 4.2.7 is the latest valid version.

*  http://guides.rubyonrails.org/v4.2.7/ works
* http://guides.rubyonrails.org/v4.2.8/ doesn't work

(and same for the API site)

@fxn : Sorry to ping you on that, but it's certainly a problem of missing files on the documentation server, there's no problem to generate the guides or the API on a fresh checkout of the `4-2-8` branch.

**Comment by fxn** [comment] 2017-03-02 21:16
Yes, I saw it precisely yesterday. The problem is the Gemfile uses `:mri_23`, and the version of Bundler used to build those docs does not know that one. Need to program docs generation for those releases to use a newer version.

On my plate!

**Comment by fxn** [comment] 2017-03-03 09:43
Fixed now, thanks for opening the ticket!

**Comment by fxn** [comment] 2017-03-03 09:53
Reopening, because API generation was restored, but guides generation has other issues in that release. Something related to encodings.

I have symlinked to v4.2.7 meanwhile.

**Comment by fxn** [comment] 2017-03-07 08:26
Fixed.

For some reason I don't understand the locales in the server were screwed up and `Encoding.default_external` yielded `Encoding:US-ASCII`. Something has to be happened, because of course this was routinely correctly configured. The only thing that comes to mind is that the server installs security updates automatically.

Anyway, fixed. If this happens again we'll have two data points :).

**Closed by fxn** 2017-03-07 08:26 UTC
Labels: docs
