### ISSUE TITLE
Configuring action_controller on initializers doesn't work

### ISSUE THREAD

**Issue by deeeki** [rails/rails#30064] opened 2017-08-03 16:02 UTC
This was discussed at #29527 and made a commit, but still doesn't work.

`rake initializers` shows `ActionController::Railtie.action_controller.parameters_config` before `Myapp::Application.load_config_initializers`.

### Steps to reproduce

In a directory just ran `rails new`
```
echo 'Rails.application.config.action_controller.permit_all_parameters = true' > config/initializers/ac.rb
bin/rails c
```

### Expected behavior
```
> ActionController::Parameters.permit_all_parameters
=> true
```

### Actual behavior
```
> ActionController::Parameters.permit_all_parameters
=> false
```

### System configuration
**Rails version**:
5.1.2, 5.0.5

**Comment by deeeki** [comment] 2017-08-03 16:06
@rafaelfranca It'd be helpful if you check.

**Comment by kirs** [comment] 2017-08-06 15:44
I can reproduce this with the config value set in `config/application.rb`:

```diff
diff --git a/config/application.rb b/config/application.rb
index a08179a..a25c536 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -24,5 +24,7 @@ module Edgeblog
     # Settings in config/environments/* take precedence over those specified here.
     # Application configuration should go into files in config/initializers
     # -- all .rb files in that directory are automatically loaded.
+
+    config.action_controller.permit_all_parameters = true
   end
```

```
Loading development environment (Rails 5.2.0.alpha)
irb(main):001:0> ActionController::Parameters.permit_all_parameters
=> false
```

**Comment by kirs** [comment] 2017-08-06 18:07
Actually this might not be a bug because I see why we don't fully load ActionController in the console environment. When you run `rails server` and hit the controller it would set the config value to what's expected.

**Comment by y-yagi** [comment] 2017-08-08 22:07
6b0606a984ef259c283f1c763b12017711ed35bc has been committed,  but it has been reverted because there was a different problem eba78cbe05cf9ea70aeb14e66df826ec831f4f1d.  
As a result, the original problem has not been solved with the released gem.

**Comment by rafaelfranca** [comment] 2017-08-15 21:50
Fixed now

**Closed by rafaelfranca** 2017-08-15 21:50 UTC
Labels: actionpack
