### ISSUE TITLE
Error loading cached data after upgrade to 7.1 `dump format error`

### ISSUE THREAD

**Issue by matthutchinson** [rails/rails#48611] opened 2023-06-29 09:40 UTC
We have a Rails `7.0.5.1` app set with `config.load_defaults 6.0`

When attempting to upgrade to 7.1.0-alpha, with cached data already present in the app (Redis cache) I'm getting an error when Rails attempts to read the data with `Marshal.load` in `Marshal61WithFallback` ([here](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/serializer_with_fallback.rb#L147)). 

```
Argument Error 
dump format error (user class)
```

The cached data is correctly identified as 6.1 with `Marshal61WithFallback::MARSHAL_SIGNATURE` but fails to load.  

I've created an [example app](https://github.com/matthutchinson/rails-caching-example) where you can easily replicate this, (see reproduction instructions below).

From reading recent commits and the [CHANGELOG](https://github.com/rails/rails/blob/main/activesupport/CHANGELOG.md), I can see that @jonathanhefner did make some --recent changes in here, but from what I can see, this should just work, without any necessary cache migration.  

### Steps to reproduce

```
git clone https://github.com/matthutchinson/rails-caching-example
cd rails-caching-example
bin/setup
rails db:seed
rails dev:cache
rails server
open https://localhost:3000

# visit page, causing partials to be cached
# stop server
# edit Gemfile, set to use edge rails from gh master

bundle update rails
rails server
open https://localhost:3000
# page errors when loading cached data with dump format error (user class)

```

Here's a what the [dumped var](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/serializer_with_fallback.rb#L26) looks like in my [example app](https://github.com/matthutchinson/rails-caching-example) and I'm caching partials in `high_scores#index` with;

`<%= render partial: "high_score", collection: @high_scores, cached: true %>`

```
"\u0004\bo: ActiveSupport::Cache::Entry\t:\v@valueIC:\u001DActionView::OutputBuffer\"\u0001\xAB<div id=\"high_score_1\">\n  <p>\n    <strong>Game:</strong>\n    <a href=\"/high_scores/1\">Tetris</a>\n  </p>\n\n  <p>\n    <strong>Score:</strong>\n    100000\n  </p>\n\n</div>\n<hr/>\n\a:\u0006ET:\u000F@html_safeT:\r@versionI\"\u001920230628145327125454\u0006;\bT:\u0010@created_atf\u00060:\u0010@expires_in0"
```

### Expected behavior

Cached partial data should be loaded and displayed without error

### Actual behavior

Error raised when loading cached data from `Marshal.load`

```
Argument Error 
dump format error (user class)
```

<img width="1010" alt="Screenshot 2023-06-28 at 16 35 43" src="https://github.com/rails/rails/assets/2095/a06d95ed-7f35-42a0-97d4-0e2170bd21d3">

### System configuration

**Rails version**: `7.1.0-alpha` (migrating from `7.0.5.1`)
**Ruby version**: `3.1.2` and `3.2.0` 

#### Other Notes:

* I thought [this commit](https://github.com/jonathanhefner/rails/commit/e2524e574b2f8f157190c00e7c2d1377995d2fdd) might have been the cause, but reverting to the commit before that, I get the same issue.
* Clearing the cache will fix the issue, but in production, we'd really prefer not to have to do that.  
* If clearing the cache _is a requirement_, we should update the docs and upgrade guide to explain that.

cc @jonathanhefner

**Comment by skipkayhil** [comment] 2023-07-03 15:16
I bisected and got https://github.com/rails/rails/commit/4e8e8282 cc @byroot 

```ruby
require "active_support"
require "active_support/core_ext/object/blank"
require "action_view"

require "minitest/autorun"

FAILING_ON_MAIN = "\u0004\bo: ActiveSupport::Cache::Entry\t:\v@valueIC:\u001DActionView::OutputBuffer\"\u0001\xAB<div id=\"high_score_1\">\n  <p>\n    <strong>Game:</strong>\n    <a href=\"/high_scores/1\">Tetris</a>\n  </p>\n\n  <p>\n    <strong>Score:</strong>\n    100000\n  </p>\n\n</div>\n<hr/>\n\a:\u0006ET:\u000F@html_safeT:\r@versionI\"\u001920230628145327125454\u0006;\bT:\u0010@created_atf\u00060:\u0010@expires_in0"

class BugTest < Minitest::Test
  def test_stuff
    Marshal.load(FAILING_ON_MAIN)
  end
end
```

**Comment by byroot** [comment] 2023-07-03 16:41
Urk, not Marshal again 😢 .

Ok, so classes that inherit from core types such as `String` are not serialized in the same way than "regular" classes.

I don't really see a solution to make 7.0 and 7.1 cache compatible here, except perhaps keeping the old code defined as `ActionView::OutputBuffer` and just stop using it and use another class named differently, but that's quite dirty.

In the meantime, if you are blocked in your upgrade, one solution is to use a different cache prefix when rolling out 7.1, so each version uses a different cache.

@rafaelfranca do you know what exactly is our backward compatibility policy around AS::Cache content?

In this specific instance the cache call is by `render cached: true` and `ActionView::OutputBuffer` isn't public API, so we might be able to get away with this by simply prefixing or versioning these Action View cache calls?

**Comment by matthutchinson** [comment] 2023-07-04 09:50
Thanks for looking into this @byroot - let me know if I can help in anyway

**Comment by byroot** [comment] 2023-07-04 10:36
@matthutchinson thanks. I'll try to find a solution today. 

Right now I'm thinking we could do two birds one stone, by caching these fragments as bare strings:

  - We'd no longer couple the cache format to the internal representation of `ActionView::OutputBuffer`
  - That would allow to fasten serialization/deserialization thanks to https://github.com/rails/rails/pull/48122 (cc @jonathanhefner)

But either way, that requires to bust these caches, which we can probably do by changing the prefix in https://github.com/rails/rails/blob/c388a4dcf580281aef4e341f87c52956b0b0057a/actionpack/lib/abstract_controller/caching/fragments.rb

**Comment by matthewd** [comment] 2023-07-04 12:00
Changing the cache key will break invalidations across the upgrade boundary (while both versions are running, one version uses `expire_fragment` to invalidate a cache entry; the other version's entry remains).

I was initially also concerned that storing bare strings would lose HTML safety, but that's apparently not an issue? https://github.com/rails/rails/blob/c388a4dcf580281aef4e341f87c52956b0b0057a/actionpack/lib/abstract_controller/caching/fragments.rb#L101

If we're looking specifically for top-level (within the Entry) AV::OB instances, and we can hand-wave the possibility of user-set ivars or anything... it might only be moderately ridiculous for us to unmarshal by hand? 🤔  (I know the future-focused answer is to avoid Marshal, but still I wish Marshal.load could be given a serialized-class-name => actual-class-to-use hash, or something.)

Given the particularly strict bounds of switching from a String subclass to Object, surrendering the class name might be the best option. I don't think we need to keep it as an implementation -- just having Cache::Entry convert between NewOutputBuffer and a hollow methodless OutputBuffer in its `marshal{_dump,_load}` seems like it's probably sufficient?

**Comment by byroot** [comment] 2023-07-04 12:10
> while both versions are running, one version uses `expire_fragment`

Oh -_-. I wasn't aware of `expire_fragment`, I thought fragment caching only used key busting. That's unfortunate.

> storing bare strings would lose HTML safety, but that's apparently not an issue? 

Yeah, not an issue.

That snippet you link is interesting though, I need to dig more, but if we call `html_safe` on the result, it means storing bare string would be backward compatible at least, so we'd only have to handle deserialization failures in 7.1, which can just treat the Marshal error as a cache miss.

>  it might only be moderately ridiculous for us to unmarshal by hand?

The performance would be quite terrible no? We'd need a Ruby implementation of Marshal etc.

We'd only go into that path when an error happen, but still, at this stage it might be simpler to just treat it as a cache miss.

> just having Cache::Entry convert between NewOutputBuffer and a hollow methodless OutputBuffer in its marshal{_dump,_load} seems like it's probably sufficient?

I'd rather not add such logic into `AS::Cache::Entry`, it would be `AC::Caching::Fragments` job.

I'd prefer not to have to keep around the old implementation for that, so I'll try the bare string route + treating deserialization errors as cache misses. If it doesn't work we can consider keeping the old implementation.

**Comment by byroot** [comment] 2023-07-04 12:23
Ok, so it appears that fragments are already supposed to be strings: https://github.com/rails/rails/blob/c388a4dcf580281aef4e341f87c52956b0b0057a/actionpack/test/controller/caching_test.rb#L148-L150

This test is 14 years old, so there's the question of how you end up with an `ActionView::OutputBuffer` in cache. I'll have to dig into that reproduction app.

**Comment by byroot** [comment] 2023-07-04 12:36
Ok, so the issue is here: https://github.com/rails/rails/blob/c388a4dcf580281aef4e341f87c52956b0b0057a/actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb#L97

When we use `render collection:, cache: true`, buffers aren't casted to `String`.

However once the fragments are joined, they are assumed to be `html_safe`: https://github.com/rails/rails/blob/c388a4dcf580281aef4e341f87c52956b0b0057a/actionview/lib/action_view/renderer/abstract_renderer.rb#L122-L124

So I think the plan is:

  - Get collection_caching to save bare strings, both for performance and correctness.
  - Treat HTML fragment deserialization issues as cache misses.

**Comment by byroot** [comment] 2023-07-04 13:17
I just opened part 1 of the fix: https://github.com/rails/rails/pull/48645

The next step is to rescue cache deserialization issues, and treat them as cache misses.

**Comment by byroot** [comment] 2023-07-06 09:03
Part two merged, let me know if the issue persists when you try upgrading again.

**Closed** 2023-07-06 09:03 UTC
Labels: activesupport

**Comment by matthutchinson** [comment] 2023-07-06 11:23
👍 Confirmed fixed on my example app, but still having an issue on my other production app. This may be due to our use of a custom cache store.  I'll investigate further and re-open this issue if necessary.

Thanks for addressing this so quickly 🤝 🙇

**Comment by benubois** [comment] 2023-10-19 03:12
Hi @byroot,

I'm seeing the same exception thrown at a different callsite when upgrading from 7.0 -> 7.1. I'm having trouble making a reproducible test case because the exception is only getting raised in production. 

I will continue to try to reproduce it, but just in case the exception is enough to identify what is happening, here it is:

`ArgumentError: dump format error (user class)`
```
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache/entry.rb:124 :in `uncompress`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache/entry.rb:34 :in `value`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache/redis_cache_store.rb:335 :in `block in read_multi_entries`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache/redis_cache_store.rb:331 :in `each`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache/redis_cache_store.rb:331 :in `each_with_object`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache/redis_cache_store.rb:331 :in `read_multi_entries`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache/strategy/local_cache.rb:144 :in `read_multi_entries`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache/redis_cache_store.rb:173 :in `block in read_multi`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache.rb:1015 :in `block in _instrument`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:208 :in `instrument`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache.rb:1014 :in `_instrument`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache.rb:995 :in `instrument_multi`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/cache/redis_cache_store.rb:172 :in `read_multi`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/partial_renderer/collection_caching.rb:34 :in `cache_collection_render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:169 :in `block in render_collection`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:208 :in `instrument`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:155 :in `render_collection`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:127 :in `render_collection_with_partial`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:74 :in `render_partial_to_object`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:29 :in `render_to_object`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:24 :in `render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/rendering_helper.rb:37 :in `block in render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/base.rb:291 :in `in_rendering_context`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/rendering_helper.rb:33 :in `render`
[PROJECT_ROOT]/app/views/tags/_tag.html.erb:34 :in `block in _app_views_tags__tag_html_erb`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/buffers.rb:75 :in `capture`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/cache_helper.rb:285 :in `write_fragment_for`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/cache_helper.rb:276 :in `fragment_for`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/cache_helper.rb:172 :in `block in cache`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/cache_helper.rb:300 :in `track_caching`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/cache_helper.rb:170 :in `cache`
[PROJECT_ROOT]/app/views/tags/_tag.html.erb:1 :in `_app_views_tags__tag_html_erb`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/base.rb:264 :in `public_send`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/base.rb:264 :in `_run`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/template.rb:254 :in `block in render`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:208 :in `instrument`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/template.rb:535 :in `instrument_render_template`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/template.rb:248 :in `render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:197 :in `block in collection_with_template`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:74 :in `block in each_with_info`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:74 :in `each`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:74 :in `each_with_info`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:188 :in `each`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:188 :in `map`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:188 :in `collection_with_template`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:170 :in `block (2 levels) in render_collection`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/partial_renderer/collection_caching.rb:21 :in `cache_collection_render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:169 :in `block in render_collection`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:208 :in `instrument`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:155 :in `render_collection`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/collection_renderer.rb:127 :in `render_collection_with_partial`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:74 :in `render_partial_to_object`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:29 :in `render_to_object`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:24 :in `render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/rendering_helper.rb:37 :in `block in render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/base.rb:291 :in `in_rendering_context`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/rendering_helper.rb:33 :in `render`
[PROJECT_ROOT]/app/views/feeds/_feeds.html.erb:32 :in `_app_views_feeds__feeds_html_erb`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/base.rb:264 :in `public_send`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/base.rb:264 :in `_run`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/template.rb:254 :in `block in render`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:208 :in `instrument`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/template.rb:535 :in `instrument_render_template`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/template.rb:248 :in `render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/partial_renderer.rb:252 :in `block in render_partial_template`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206 :in `block in instrument`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications/instrumenter.rb:58 :in `instrument`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206 :in `instrument`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/partial_renderer.rb:246 :in `render_partial_template`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/partial_renderer.rb:237 :in `render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:83 :in `render_partial_to_object`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:29 :in `render_to_object`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:24 :in `render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/rendering_helper.rb:37 :in `block in render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/base.rb:291 :in `in_rendering_context`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/helpers/rendering_helper.rb:33 :in `render`
[PROJECT_ROOT]/app/views/site/logged_in.html.erb:35 :in `block in _app_views_site_logged_in_html_erb`
[PROJECT_ROOT]/app/helpers/application_helper.rb:5 :in `present`
[PROJECT_ROOT]/app/views/site/logged_in.html.erb:1 :in `_app_views_site_logged_in_html_erb`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/base.rb:264 :in `public_send`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/base.rb:264 :in `_run`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/template.rb:254 :in `block in render`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:208 :in `instrument`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/template.rb:535 :in `instrument_render_template`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/template.rb:248 :in `render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/template_renderer.rb:66 :in `block (2 levels) in render_template`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206 :in `block in instrument`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications/instrumenter.rb:58 :in `instrument`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206 :in `instrument`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/template_renderer.rb:60 :in `block in render_template`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/template_renderer.rb:76 :in `block in render_with_layout`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206 :in `block in instrument`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications/instrumenter.rb:58 :in `instrument`
[GEM_ROOT]/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206 :in `instrument`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/template_renderer.rb:75 :in `render_with_layout`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/template_renderer.rb:59 :in `render_template`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/template_renderer.rb:11 :in `render`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:63 :in `render_template_to_object`
[GEM_ROOT]/gems/actionview-7.1.1/lib/action_view/renderer/renderer.rb:31 :in `render_to_object`
```

**Comment by byroot** [comment] 2023-10-19 06:35
Hi @sedubois.

Can you tell me from which version exactly you are upgrading, and what is `config.load_defaults` set to? in `config/application.rb`?

**Comment by benubois** [comment] 2023-10-19 06:50
Hi @byroot,

The previous version was 7.0.8. 

[load_defaults](https://github.com/feedbin/feedbin/blob/ad7bb3af3f6a2bbf675e188d5e3eadc9c4c4a7d4/config/application.rb#L20) is set to 6.1. 

I’ve since tried setting `cache_format_version` to 7.1 (with a different cache prefix) and still got this exception. 

Thanks for looking into this!

**Comment by benubois** [comment] 2023-10-19 16:26
@byroot that fixed it! 

Appreciate your help and sorry I wasn't able to give you something reproducible.

**Comment by byroot** [comment] 2023-10-20 14:02
@sedubois the fix is in `7-1-stable` now.
