### ISSUE TITLE
ActionDispatch response ignores MIME parameters

### ISSUE THREAD

**Issue by mcr** [rails/rails#36095] opened 2019-04-25 16:47 UTC
https://github.com/rails/rails/blob/fb4268401575b5af3d5d2566fd37fc75f34bb93b/actionpack/lib/action_dispatch/http/response.rb#L412

I am trying to return a multipart/mixed content-type in a response. I use a multipart library to build the body, and then call:

    send_data object, :type => "multipart/mixed; boundary=#{stuff}"

but the content_type= processing in response.rb seems to ignore all parameters except for the charset parameter.  Is it the intention that an end-user would override, CONTENT_TYPE_PARSER or is there some other interface I should be using to pass parameters into the content-type.

**Comment by mcr** [comment] 2019-04-25 16:52
This is the hack that I've come up with, and I hate it:

    send_data object, :type => "multipart/mixed; boundary=#{stuff}" 
    @_response.set_header "Content-Type", content

**Comment by prathamesh-sonpatki** [comment] 2019-04-26 14:30
This is duplicate of https://github.com/rails/rails/issues/35709

**Comment by prathamesh-sonpatki** [comment] 2019-04-26 14:32
I am closing this issue as #35709 has on-going discussion and there is also a related PR #36034

**Closed by prathamesh-sonpatki** 2019-04-26 14:32 UTC
