### ISSUE TITLE
ActionController::Live regression - broken with Rack 2.2

### ISSUE THREAD

**Issue by jeffblake** [rails/rails#38466] opened 2020-02-15 18:09 UTC
### Steps to reproduce

1. Comment out `gem 'rack'` to see the test fail on Rack 2.2

```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.0.0"
  gem 'rack', '~> 2.1.0'
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  include ActionController::Live

  def index
    response.headers['Content-Type'] = 'text/event-stream'

    3.times do
      puts 1
      response.stream.write "This is a test Message\n"
      sleep 1
    end

    response.stream.close
  end

end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
    response_time = last_response.headers['X-Runtime'].to_f
    assert response_time < 1, "expected #{response_time} to be less than 1 second"
  end

  private
    def app
      Rails.application
    end
end
```

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6

**Comment by alor** [comment] 2020-03-11 21:35
I can confirm this.  Rack 2.2.x is breaking the ability to stream responses. I've opened an issue on https://github.com/rack/rack/issues/1619

**Comment by rafaelfranca** [comment] 2020-03-12 19:26
Thank you for reporting. Closing since it is a bug in rack.

**Closed by rafaelfranca** 2020-03-12 19:26 UTC

**Comment by jeremyevans** [comment] 2020-06-23 14:13
Currently, the rack-core team considers the change in Rack 2.2 a bugfix, and does not plan to revert.  So you may want to consider reopening this issue and changing Rails to work with Rack 2.2.  Otherwise, you are forcing all Rails users that want to use streaming to implement workarounds in their apps.  Alternatively, you could have one of the Rack committers that are also Rails committers reconsider Rack's behavior.

**Comment by themilkman** [comment] 2020-12-09 09:37
I also think it is bad and not easy to nail down.. At very least the rails docs/guides should mention it...

https://api.rubyonrails.org/classes/ActionController/Live.html
