### ISSUE TITLE
Rails hidden fields now fail W3C HTML Validation due to "autocomplete=off"

### ISSUE THREAD

**Issue by mattscilipoti** [rails/rails#46470] opened 2022-11-10 21:57 UTC
The W3C HTML Validator was updated on 2022/10/26, in https://github.com/validator/validator/pull/1458, to conform to https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute. The validator now identifies an issue with hidden fields, due to https://github.com/rails/rails/issues/42610.

### Steps to reproduce
Add a hidden field to a form, via various methods (including authenticity_token) and test the rendered form via W3C Html Validator.

I looked at the various test cases, but I don't see how to render a control on a form.

```ruby
# Your reproduction script goes here
```

### Expected behavior
I'm not clear about this. For this use case, I think the html spec is saying the autocomplete attribute should simply not be there. They discuss using an ordered set of space-separated tokens, but I haven't found how that would be applicable.

### Actual behavior
All hidden fields have `autocomplete="false"`.

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.1.2

**Comment by mattscilipoti** [comment] 2022-11-10 21:58
You can read more about the issue and HTML validator change here: https://stackoverflow.com/questions/74256523/rails-button-to-fails-with-w3c-validator

**Comment by fatkodima** [comment] 2022-11-10 22:00
Duplicate of https://github.com/rails/rails/issues/46405 ?

**Comment by skipkayhil** [comment] 2022-11-10 22:08
> Duplicate of #46405 ?

Yep, see the discussion over there for why this can't really be changed

**Closed by skipkayhil** 2022-11-10 22:08 UTC

**Comment by mattscilipoti** [comment] 2022-11-10 22:12
Sorry. You are correct. This is a duplicate. I searched for "hidden" or "autocomplete" and didn't find #46405
