### ISSUE TITLE
Surprising sequence of order clauses in nested :through associations

### ISSUE THREAD

**Issue by DavidMikeSimon** [rails/rails#24887] opened 2016-05-06 15:08 UTC
When a :through association involves order clauses on more than one point in the chain (from default_scope, or from lambda arguments to the association class method), the order clauses are applied in the opposite order from what would be naturally expected.

### Steps to reproduce

```
class Page < ActiveRecord::Base
  has_many :paragraphs, -> { order(:x) }
  has_many :words, through: :paragraphs
end

class Paragraph < ActiveRecord::Base
  has_many :words, -> { order(:y) }
end

class Word < ActiveRecord::Base
end
```

### Expected behavior

Rails retrieves `page.words` using a query similar to `SELECT * FROM words ... ORDER BY paragraphs.x ASC, words.y ASC`

### Actual behavior

The query instead has an order clause like `ORDER BY words.y ASC, paragraphs.x ASC`.

I've written a unit test to demonstrate this more behavior more thoroughly: https://github.com/DavidMikeSimon/rails/tree/multi-through-scope-order
https://github.com/DavidMikeSimon/rails/commit/23efb61df3986949d6f150a59923b5d577924c7d

### System configuration

**Rails version**: master as of 2016-05-04

**Ruby version**: 2.3.0p0

**Comment by maclover7** [comment] 2016-05-06 21:36
Can you extract your bug report tests, and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by DavidMikeSimon** [comment] 2016-05-09 15:02
@maclover7 Sure, here's a running example of my pseudocode from above:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :pages, force: true do |t|
  end

  create_table :paragraphs, force: true do |t|
    t.integer :page_id
    t.integer :paragraph_position
  end

  create_table :words, force: true do |t|
    t.integer :paragraph_id
    t.integer :word_position
    t.string  :word
  end
end


class Page < ActiveRecord::Base
  has_many :paragraphs, -> { order(:paragraph_position) }
  has_many :words, through: :paragraphs
end

class Paragraph < ActiveRecord::Base
  belongs_to :page
  has_many :words, -> { order(:word_position) }
end

class Word < ActiveRecord::Base
  belongs_to :paragraph
end

class BugTest < Minitest::Test
  def test_nested_sequence_order
    page = Page.create!
    para1 = page.paragraphs.create!(paragraph_position: 1)
    para1.words.create!(word: "Roses", word_position: 1)
    para1.words.create!(word: "are", word_position: 2)
    para1.words.create!(word: "red.", word_position: 3)
    para2 = page.paragraphs.create!(paragraph_position: 2)
    para2.words.create!(word: "Violets", word_position: 1)
    para2.words.create!(word: "are", word_position: 2)
    para2.words.create!(word: "blue.", word_position: 3)

    assert_equal ["Roses", "are", "red.", "Violets", "are", "blue."], page.words.map(&:word)
  end
end
```

Output:

```
  1) Failure:
BugTest#test_nested_sequence_order [ar-bug-report.rb:65]:
--- expected
+++ actual
@@ -1 +1 @@
-["Roses", "are", "red.", "Violets", "are", "blue."]
+["Roses", "Violets", "are", "are", "red.", "blue."]
```

**Comment by maclover7** [comment] 2016-05-09 19:37
👍 thanks for posting, this definitely looks like a bug to me. Steps forward:

1) Has this worked for you in past versions of Rails? --> if so, can you do a `git bisect` and see where the error was introduced
2) If not, can you try and find the source of the bug 😬

**Comment by DavidMikeSimon** [comment] 2016-05-09 20:13
I'm not sure if the behavior was different in prior versions of Rails; I ran into this problem when implementing something new.

However, I have figured out the source of the bug, at least somewhat. It seems that queries on nested :through relationships are generally built from the bottom up, rather than the top down. In most cases wouldn't matter, but `ORDER BY` is affected a lot by argument order, unlike most of the other SQL operations that Rails typically does.

I have a partial fix, which is to simply prepend new order clauses rather than appending them as is currently done. For example, in `AssociationScope#add_constraints`, you can replace:

`scope.order_values |= item.order_values`

With:

`scope.order_values = item.order_values | scope.order_values`

Unfortunately, this doesn't entirely solve the problem. It seems that default_scopes on :through associations are completely resolved by Rails before it begins applying the lambdas given to association declarations. So while my fix does correct the failing test pasted above, the same issue will still occur if the `order(:word_position)` is part of a default_scope on Word instead of being specified with the has_many :words association on Paragraph. :-(

**Comment by maclover7** [comment] 2016-05-09 21:14
cc @sgrif 
r? @sgrif (so you don't forget about this while you are moving ;))

**Comment by sgrif** [comment] 2016-05-09 21:46
Just got to Canada. Should have time to clear the backlog 🔜🔜🔜🔜

**Comment by sevaorlov** [comment] 2016-05-15 18:56
default scopes are merged here https://github.com/rails/rails/blob/dc925119a3912ecfe0df400007163f33b99d6385/activerecord/lib/active_record/associations/through_association.rb#L18 with `ActiveRecord::Relation::Merger`. We can merge them in reverse order there without `Merger`. @sgrif, does that sound good for you? I can create a PR.

**Comment by sgrif** [comment] 2016-05-16 13:48
Hm. I agree that the proposed order is better than what we're doing now, but this would be a pretty big breaking change. We'd need to at least have a deprecation cycle and I'm not sure if we can easily do that. @rafaelfranca WDYT? I like the proposed behavior but I'm not sure it's worth the breaking change

**Comment by DavidMikeSimon** [comment] 2016-05-16 15:05
@sevaorlov 

I have the beginnings of a possible fix here:

https://github.com/DavidMikeSimon/rails/commit/9874260a29ed93b5c74b543301c26da84a9ec5f0

Instead of not using Merger, it adds `:order` to the list of excluded scope properties, then handles it manually elsewhere. This makes my tests pass for `default_socpe` and for association lambdas, and for both of those in combination in either order.

However, it only passes on SQLite. :-( On MySQL and PG, the ordering in the combined case goes back to the original failure mode, and I'm not sure why.

**Comment by sgrif** [comment] 2016-05-16 17:29
@DavidMikeSimon The problem isn't coming up with a fix. The change would be easy to make, but it would be a breaking change in behavior that I'm not sure we can make at this point

**Comment by rafaelfranca** [comment] 2016-05-16 17:34
We did this change in Rails 4.0 and we had to revert. It was a really huge breaking change and I don't think we should do it again. See https://github.com/rails/rails/pull/16051.

**Closed by rafaelfranca** 2016-05-16 17:34 UTC
Labels: activerecord, With reproduction steps

**Comment by DavidMikeSimon** [comment] 2016-05-16 18:17
@rafaelfranca I don't think this is the same thing as issue #16051.

The problem is not with the general behavior of the `order` relation method, but specifically with the way that order is composed on :through associations. It's not surprising that `rel.order(:x).order(:y)` orders first by :x and then by :y.

But I definitely think it *is* surprising that when you look up an ordered child relation through an ordered parent relation, it orders first by the child and then by the parent. See my test code in a comment above; is the `["Roses", "Violets", "are", "are", ...]` output to be expected?

**Comment by rafaelfranca** [comment] 2016-05-16 18:21
Not actually the same cause but definitely the problem. Changing this
behavior will be a huge break change with no feasible backward
compatibility path neither a deprecation path. It is a behavior that exists
for a long time and changing this behavior is not worth, although it is
less surprising.
