### ISSUE TITLE
System test with Selenium Fails with EOFError

### ISSUE THREAD

**Issue by bparanj** [rails/rails#28940] opened 2017-04-30 22:22 UTC
### Steps to reproduce

Create a scaffold resource and run rails test:system.

Here is the repo: https://github.com/bparanj/r51st

### Expected behavior

The system test generated by the scaffold should run in the browser.

### Actual behavior

```
$ rails test:system
Run options: --seed 8150

# Running:

E

Error:
ThoughtsTest#test_visiting_the_index:
EOFError: end of file reached
    
Error:
ThoughtsTest#test_visiting_the_index:
EOFError: end of file reached

bin/rails test test/system/thoughts_test.rb:4

Finished in 2.928448s, 0.3415 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration

**Rails version**: 5.1

**Ruby version**: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin14]

ChromeDriver : 2.9
Capybara : 2.13.0
Mac OS : 10.10.5
Chrome : 58.0.3029.81 (64-bit)

**Comment by daqing** [comment] 2017-05-01 13:45
I got the same error today.

**Comment by maclover7** [comment] 2017-05-01 20:26
cc @eileencodes

**Comment by eileencodes** [comment] 2017-05-01 20:36
@samphippen saw this same error before. Seems to be from not having chromedriver installed. I'm not sure why it's throwing an unhelpful EOFError. Does installing chromedriver (if you're on mac use `brew install chromedriver` and then run again) work for you?

**Comment by eileencodes** [comment] 2017-05-01 20:37
If you have chromedriver installed on your system elsewhere you may need to remove it first

**Comment by samphippen** [comment] 2017-05-01 20:51
My understanding is that the eof error occurs exactly when the chrome driver version on the system is lower than the one required by capybaras

**Comment by alexcameron89** [comment] 2017-05-01 20:56
I just reproduced the issue on my work Mac, which had `chromedriver 2.21`.

I upgraded with `brew upgrade chromedriver`, which upgraded to 2.29. After that, the test passed.

**Comment by bparanj** [comment] 2017-05-05 05:00
I had to:

```
brew install chromedriver
```

It works with:

```
/usr/local/bin/chromedriver -v
ChromeDriver 2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b)
```

**Comment by eileencodes** [comment] 2017-10-18 17:23
Fixed by https://github.com/rails/rails/pull/30923

**Closed by eileencodes** 2017-10-18 17:23 UTC
Labels: actionpack
