### ISSUE TITLE
Rails 5.1.0.alpha can not start server with options

### ISSUE THREAD

**Issue by FlowerWrong** [rails/rails#27260] opened 2016-12-03 15:15 UTC
### Steps to reproduce

I can not use `5.1.0.alpha` to start a rails server with options.

### Expected behavior
work well.

### Actual behavior

<img width="1204" alt="2016-12-03 11 11 00" src="https://cloud.githubusercontent.com/assets/5362640/20860244/51e89972-b9ae-11e6-887e-ac57f22c26e8.png">

### System configuration
**Rails version**: 5.1.0.alpha

**Ruby version**: 2.3.3

**Comment by georgeclaghorn** [comment] 2016-12-03 15:39
This is being fixed in https://github.com/rails/rails/pull/26977.

**Comment by maclover7** [comment] 2016-12-03 15:41
Closing as a duplicate of #27155; as noted by @georgeclaghorn, there's a PR in progress at #26977 to fix this error. Thank you for opening this issue!!

**Closed by maclover7** 2016-12-03 15:41 UTC
