### ISSUE TITLE
structure.sql not working with multiple schema_search_paths defined

### ISSUE THREAD

**Issue by johnhamelink** [rails/rails#23141] opened 2016-01-20 18:06 UTC
Hi there,

After upgrading postgres from 9.4 to 9.5, and then upgrading rails from 9.4.2 to 9.4.5 (to fix #21931), I'm finding that running `db:migrate` is resulting in an error when multiple `schema_search_path`s are set in `database.yml`. Interestingly, the pg_dump command it provides seems to work - it does create a `structure.sql` file and it returns `0`.

### Example with multiple search paths set:

```yml
default: &default                                                                                                                                                                              
  adapter: postgis                                                                                                                                                                             
  schema_search_path: public,postgis,topology                                                                                                                                                  
  #schema_search_path: public                                                                                                                                                                  
  encoding: unicode                                                                                                                                                                            
  pool: 5                                                                                                                                                                                      
  username:                                                                                                                                                                                    
  password:
```

```
$ be rake db:drop db:create db:migrate

< snip >

-- add_index(:sms_verifications, :phone_number_id, {:name=>"sms_phone_number_id_idx"})
   -> 0.0250s
== 20160120133702 SmsVerifications: migrated (0.0836s) ========================

pg_dump: No matching schemas were found
rake aborted!
failed to execute:
pg_dump -s -x -O -f /home/john/Public/fap/api_2.0/src/db/structure.sql --schema=public --schema=postgis --schema=topology fap_development

Please check the output above for any errors and make sure that `pg_dump` is installed in your PATH and has proper permissions.


Tasks: TOP => db:structure:dump
(See full trace by running task with --trace)
```

### Example with more standard behaviour:

```yml
default: &default                                                                                                                                                                              
  adapter: postgis                                                                                                                                                                             
  #schema_search_path: public,postgis,topology                                                                                                                                                 
  schema_search_path: public                                                                                                                                                                   
  encoding: unicode                                                                                                                                                                            
  pool: 5                                                                                                                                                                                      
  username:                                                                                                                                                                                    
  password: 
```

```
$ be rake db:drop db:create db:migrate

< snip >

== 20160120133702 SmsVerifications: migrating =================================
-- create_table(:sms_verifications)
   -> 0.0579s
-- add_index(:sms_verifications, :phone_number_id, {:name=>"sms_phone_number_id_idx"})
   -> 0.0251s
== 20160120133702 SmsVerifications: migrated (0.0831s) ========================

Loading application environment...
Loading code in search of Active Record models...
ActiveJob::QueueAdapters::InlineAdapter does not support delayed retries, so does not work with ActiveJob::Retry. You may experience strange behaviour.
Generating Entity-Relationship Diagram for 42 models...
Done! Saved diagram to erd.pdf.
```

**Comment by walski** [comment] 2016-01-21 23:26
For me this is fixed with d1dcdf21286cb459a422b6b88967d712c75f002a

**Comment by walski** [comment] 2016-01-21 23:36
A workaround is to create this file:

```ruby
# lib/tasks/fix_multiple_schema_dump_problem.rake

namespace :db do
  task fix_structure_dump: :environment do
    # DIRTY MONKEY PATCH FIX
    ActiveRecord::Tasks::PostgreSQLDatabaseTasks
    class ActiveRecord::Tasks::PostgreSQLDatabaseTasks
      def structure_dump(filename)
        set_psql_env
        args = ['-s', '-x', '-O', '-f', filename]
        search_path = configuration['schema_search_path']
        unless search_path.blank?
          # THIS IS THE ACTUAL FIX FROM:
          # https://github.com/rails/rails/commit/d1dcdf21286cb459a422b6b88967d712c75f002a
          # args << search_path.split(',').map do |part|
          args += search_path.split(',').map do |part|
            "--schema=#{part.strip}"
          end
          # end.join(' ')
        end
        args << configuration['database']
        run_cmd('pg_dump', args, 'dumping')
        File.open(filename, "a") { |f| f << "SET search_path TO #{connection.schema_search_path};\n\n" }
      end
    end
  end
end

Rake::Task["db:structure:dump"].enhance ["db:fix_structure_dump"]
```

**Comment by prathamesh-sonpatki** [comment] 2016-01-22 13:12
@johnhamelink Can you try `4-2-stable` branch to see if it works or not? The issue is backported to `4-2-stable` branch as per https://github.com/rails/rails/pull/22345#issuecomment-160680455.

It will also be part of next release in `4-2` series.

**Comment by GUI** [comment] 2016-01-28 20:08
I added a note in https://github.com/rails/rails/pull/22345#issuecomment-176379703, but if you need this fixed in Rails 4.2.5.1, I created a gem to patch this specific issue: https://github.com/GUI/rails_425_structure_dump_patch

**Comment by maclover7** [comment] 2016-01-28 22:10
Closing this since #22345 has been merged.

**Closed by maclover7** 2016-01-28 22:10 UTC
Labels: activerecord, PostgreSQL

**Comment by johnhamelink** [comment] 2016-02-03 15:10
Hey guys,

Sorry I took so long to get back to you on this!

Upgrading to `4-2-stable` branch did indeed fix this for me.

Best,
JH
