### ISSUE TITLE
Config in config/puma.rb not working properly

### ISSUE THREAD

**Issue by Alamoz** [rails/rails#23681] opened 2016-02-15 04:58 UTC
The environment param in config/puma.rb is not setting to the value in RAILS_ENV, it is always set to the default value:

environment ENV.fetch("RAILS_ENV") { "development" }

This is getting set to "development" even when I have RAILS_ENV set to "production". This is happening on a production server.

**Comment by prathamesh-sonpatki** [comment] 2016-02-15 07:02
@Alamoz Can you please upload a sample app on Github using which we can reproduce the issue?

Thanks!

**Comment by xw19** [comment] 2016-02-15 11:09
@Alamoz Which rails version are you using ?

**Comment by mdoza** [comment] 2016-02-18 21:55
@Alamoz the environment variable should be set to RAILS_ENV, or is that a typo in your comment?

**Comment by Alamoz** [comment] 2016-02-19 23:47
@xw19 - Rails version 5.0.0.beta2

**Comment by schneems** [comment] 2016-02-20 17:45
I'll take a look on monday

**Comment by Alamoz** [comment] 2016-02-22 08:27
@schneems - When I go into irb on the production server the correct result is returned, using Ruby 2.3.0p7:

irb(main):001:0> ENV.fetch("RAILS_ENV") { "development" }
=> "production"
irb(main):002:0> 

Must be a puma issue, but I reported it here now that Rails 5 uses Puma.

**Comment by mdoza** [comment] 2016-02-22 18:25
@Alamoz did you ever upload a sample app? I can't recreate this error. Setting the RAILS_ENV environment variable works as expected. But then again, I don't know your setup.

**Comment by schneems** [comment] 2016-02-22 18:32
Are you using Puma version `3.0.0rc1`?

**Comment by mdoza** [comment] 2016-02-22 18:53
@schneems yes, I tried it on Puma 3.0.0rc1.

Inline env var:

```
$ RAILS_ENV=production rails s
=> Booting Puma
=> Rails 5.0.0.beta2 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.0.0.rc1 (ruby 2.3.0-p0), codename: Schneems Sleak Shoes
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

Predefined var:

```
$ export RAILS_ENV=production
$ rails s
=> Booting Puma
=> Rails 5.0.0.beta2 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.0.0.rc1 (ruby 2.3.0-p0), codename: Schneems Sleak Shoes
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

**Comment by Alamoz** [comment] 2016-02-22 19:20
@mdoza The app is started in production using the /etc/init.d/puma start script. Uploading a "sample app" won't do any good and I'm not going to place one of my client's apps on github anyway. The issue isn't the app, it is a configuration problem. I just tried again with Rails 5.0.0.beta2 and now when I try to run the app it crashes with:

ActiveRecord::RecordNotFound (Couldn't find Somemodel with 'id'=):
  app/controllers/somemodels_controller.rb:68:in `set_somemodel'

Wish I could spend more time digging into this, but have to switch the app back to rails 4.2.5.1. Good luck!

**Comment by mdoza** [comment] 2016-02-22 20:53
@Alamoz I'm thinking the issue is the start up method/script, not Puma or Rails. I haven't used the puma start script, is the script taking care of setting the environment var there?

**Comment by schneems** [comment] 2016-02-22 21:17
`$ rails server` is supposed to pick up `config/puma.rb` but only on Puma 3.0.0.rc1 and above. Can you verify your version of puma?

**Comment by schneems** [comment] 2016-02-22 21:17
NM, just saw your post

**Comment by schneems** [comment] 2016-02-22 21:19
In this comment it looks like it is working correctly? https://github.com/rails/rails/issues/23681#issuecomment-187317234

In both you're booting with `RAILS_ENV=production` and i'm seeing this in your logs

```
* Environment: production
```

**Comment by mdoza** [comment] 2016-02-22 22:09
@schneems I'm not having the issue, @Alamoz was. I was trying to help him out, everything appears to work as desired.

**Comment by schneems** [comment] 2016-02-22 22:15
Thanks, sorry for the confusion. I've had a bit of a hectic monday. 😂 Thanks for the sanity check :heart:

**Comment by mdoza** [comment] 2016-02-22 22:29
@schneems Don't worry, you're definently not alone!

**Comment by schneems** [comment] 2016-02-22 22:58
There's no bug with Puma 3.0.0.rc1. We can't close this just yet, once a non-rc is released by @evanphx then we can generate that info into the gemfile when we `rails new` then we can close this.

@evanphx I can confirm things are working on codetriage with 3.0.0.rc1

```
$ rails s
=> Booting Puma
=> Rails 5.0.0.beta1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:2: warning: already initialized constant GitHubBub::Request::USER_AGENT
/Users/richardschneeman/.gem/ruby/2.3.0/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:7: warning: previous definition of USER_AGENT was here
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:3: warning: already initialized constant GitHubBub::Request::RETRIES
/Users/richardschneeman/.gem/ruby/2.3.0/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:12: warning: previous definition of RETRIES was here
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:4: warning: already initialized constant GitHubBub::Request::GITHUB_VERSION
/Users/richardschneeman/.gem/ruby/2.3.0/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:8: warning: previous definition of GITHUB_VERSION was here
[73307] Puma starting in cluster mode...
[73307] * Version 3.0.0.rc1 (ruby 2.3.0-p0), codename: Schneems Sleak Shoes
[73307] * Min threads: 5, max threads: 5
[73307] * Environment: development
[73307] * Process workers: 2
[73307] * Preloading application
[73307] * Listening on tcp://localhost:3000
[73307] Use Ctrl-C to stop
[73307] - Worker 0 (pid: 73308) booted, phase: 0
[73307] - Worker 1 (pid: 73309) booted, phase: 0
```

**Comment by Alamoz** [comment] 2016-02-25 00:26
@schneems I will try to find time later today to create a bare-bones rails app and a server and see if the problem occurs on it.

**Comment by prathamesh-sonpatki** [comment] 2016-02-26 02:35
@schneems Tried generating new app from Rails master now that Puma 3.0 is released - 

```
$ rails s
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.0.0 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
^CExiting

prathamesh ~/Projects/reproductions/go_puma_go 2.3.0 
$ RAILS_ENV=production rails s
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.0.0 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

Do we have to update anything on our side?

**Comment by Alamoz** [comment] 2016-02-26 08:17
@prathamesh-sonpatki - The issue occurs when running Puma as a service in Debian (Debian 8.3 in this case) using the start script in /etc/init.d/puma.

@schneems - OK, I just verified this problem is happening, this time trying to run a Rails 5.0.0.beta3 app with Puma 3.0.1 on a Debian 8.3 server with Ruby 2.3.0p7. The problem I originally reported is happening when I run older versions of /etc/init.d/puma and /usr/local/bin/run-puma and it happened again tonight on a shiny new server set up just to test this issue. Tonight I also used the latest versions of those scripts, which results in Puma not starting at all but no log or stdout/stderr output (failing silently.) When I simply start the app with 'Rails s' or 'Puma' from the app directory, it starts and correctly connects to the production database. Then strangely, when I just tried switching back to the old scripts now Puma doesn't start with the older scripts (did 'update-rc.d puma remove' then 'update-rc.d puma defaults' just to make sure.) I've tried attaching a screen shot of the Rails error display showing the first/original problem, but for some reason Github can't handle it either as a .png or .jpg.

I don't have these problems when running a Rails 4.2.5.1 app using Puma as a service under Debian 8.3.

**Comment by schneems** [comment] 2016-02-26 14:26
@prathamesh-sonpatki we need #23906 then we can close this issue

@Alamoz if `$ rails server` works with Puma 3.0 and the `puma` command also works then it sounds like the issue is with whatever scripts you're using. I would suggest trying to reproduce in a simple app locally. From there you could either debug or possibly get enough information to open a bug report with Puma. All that rails really cares about is that the config gets picked up correctly when `rails server` is being run, though that functionality comes from Rack::Server and Puma.

**Closed** 2016-02-26 14:55 UTC
Labels: needs feedback, railties

**Comment by Alamoz** [comment] 2016-02-26 20:09
Not a problem for me, in Rails 5 I can simply change config/puma.rb so it will work. Kind of embarrassing for Puma to have such a bad impedance mismatch between 'rails s' and '/etc/init.d/puma'.

**Comment by schneems** [comment] 2016-03-01 16:30
What is the mismatch? Previously `rails s` didn't read in config/puma.rb` now it should have much greater parity with the `puma` command in Puma 3.0+

**Comment by schneems** [comment] 2016-03-03 20:00
Ping. Any more info here?

**Comment by zacharyw** [comment] 2016-05-11 12:07
I just did a fresh install of Rails 5.0.0.rc1 and attempted to start a server using "rails server". It appeared to work, but going to localhost:3000 in my browser could not connect to anything.

Running "puma -C config/puma.rb" did work, and I was able to hit my rails app in the browser.

Output from the commands was similar:

rails server

> => Booting Puma
> => Rails 5.0.0.rc1 application starting in development on http://localhost:3000
> => Run `rails server -h` for more startup options
> Puma starting in single mode...
> * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
> * Min threads: 5, max threads: 5
> * Environment: development
> * Listening on tcp://localhost:3000

puma -C Config/puma.rb

> Puma starting in single mode...
> * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
> * Min threads: 5, max threads: 5
> * Environment: development
> * Listening on tcp://0.0.0.0:3000

So it appears that `rails server` is still not picking up the config.

**Comment by schneems** [comment] 2016-06-08 18:21
The problem is this is more of a "can't fix" type of a problem. We would need to modify the Rack interface to differentiate between user specified configuration and "default" configuration. `rails server -p 3001` would work to modify the port because that gets passed straight through the rack handler.
