### ISSUE TITLE
"Invalid default value" in migrations on Rails 4.2.0 with mysql2 gem

### ISSUE THREAD

**Issue by roberts1000** [rails/rails#18868] opened 2015-02-10 05:48 UTC
I just upgraded from 4.1.9 to 4.2.0.  I happened to rerun all of my migrations on a new development machine and received the following error:

`Mysql2::Error: Invalid default value for 'preview': ALTER TABLE 'blog_posts'  CHANGE 'preview' 'preview' tinyint(1) DEFAULT 'f' NOT NULL/Users/dev/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299: in query`

The breaking migration is:

```
class ChangePreviewInBlogPosts < ActiveRecord::Migration
  def change
     change_column :blog_posts, :preview, :boolean, :null => false, :default => false
  end
end
```

If I checkout a version of my code that is based on 4.1.9, I'm able to run all migrations.  I'm using mysql2 0.3.17.

**Comment by sgrif** [comment] 2015-02-11 20:55
I was unable to replicate the problem with the information given. Can you provide a script that we can use to reproduce the issue, using this template? https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

**Comment by paulociecomp** [comment] 2015-02-12 13:03
i tried  to reproduce with the test https://github.com/paulociecomp/issue_18868. It's run fine.

**Comment by roberts1000** [comment] 2015-02-13 05:45
Sounds good.  I'll try and get you guys something that's reproduceable next week.

**Comment by roberts1000** [comment] 2015-03-08 05:41
I couldn't get the template to work, so I ended up creating a demo Rails app here https://github.com/roberts1000/migration_break.  This is a Rails 4.2.1rc3 app with an empty model called BlogPost and three simple migrations to create the table, add a column and then change the column.  `rake db:migrate` breaks for me on Windows and Mac.

If I generate the same application with Rails 4.1.9, the everything works fine.  I tried upgrading to mysql2 0.3.18, but that didn't help.

Here is the full error output:

    DL is deprecated, please use Fiddle
    == 20150308034354 CreateBlogPosts: migrating ==================================
    -- create_table(:blog_posts)
    -> 0.0130s
    == 20150308034354 CreateBlogPosts: migrated (0.0130s) =========================

    == 20150308034654 AddPreviewToBlogPosts: migrating ============================
    -- add_column(:blog_posts, :preview, :text, {:null=>false})
    -> 0.0290s
    == 20150308034654 AddPreviewToBlogPosts: migrated (0.0290s) ===================

    == 20150308034921 ChangePreviewInBlogPosts: migrating =========================
    -- change_column(:blog_posts, :preview, :boolean, {:null=>false, :default=>false})
    rake aborted!
    StandardError: An error has occurred, all later migrations canceled:

    Mysql2::Error: Invalid default value for 'preview': ALTER TABLE `blog_posts` CHANGE `preview` `preview` tinyint(1) DEFAULT 'f' NOT NULLc:/Users/dev/Documents/
    dev/migration_break/db/migrate/20150308034921_change_preview_in_blog_posts.rb:3:in `change'
    c:in `migrate'
    ActiveRecord::StatementInvalid: Mysql2::Error: Invalid default value for 'preview': ALTER TABLE `blog_posts` CHANGE `preview` `preview` tinyint(1) DEFAULT 'f' N
    OT NULL
    c:/Users/dev/Documents/dev/migration_break/db/migrate /20150308034921_change_preview_in_blog_posts.rb:3:in `change'
    c:in `migrate'
    Mysql2::Error: Invalid default value for 'preview'
    c:/Users/dev/Documents/dev/migration_break/db/migrate/20150308034921_change_preview_in_blog_posts.rb:3:in `change'
    c:in `migrate'
    Tasks: TOP => db:migrate
    (See full trace by running task with --trace)

**Comment by paulociecomp** [comment] 2015-03-09 12:58
@roberts1000 @sgrif  i got reproduce the error with some changes in my test case: 

first: add_column :blog_posts, :preview, :text, :null => false

and then change_column :blog_posts, :preview, :boolean, :null => false, :default => false

https://github.com/paulociecomp/issue_18868

**Comment by mcfiredrill** [comment] 2015-03-23 13:17
I believe I'm running into this problem, although I'm using strings instead of booleans.
```
    change_column :posts, :status, :string, null: false, default: ''
```

I don't see the error occur in rails master, but I do see it in the 4-2 stable git branch. I've created a sample app demonstrating the problem. 

Against rails master:
https://github.com/mcfiredrill/rails_mysql2_bug/tree/master

Against 4-2-stable branch:
https://github.com/mcfiredrill/rails_mysql2_bug/tree/4-2-stable

**Comment by mcfiredrill** [comment] 2015-03-24 14:40
Seems like it was fixed here, 
3c10043bc272e13d2e01219b43beece060e5aa19

which is not in 4-2-stable for some reason.

**Comment by mcfiredrill** [comment] 2015-03-31 07:59
I made a script with the active_record_master.rb template, if that helps:
https://gist.github.com/mcfiredrill/066a17fd3450ef30f30a

I'm not sure exactly why this commit seems to fix the problem, as the commit message just says its a refactoring and not changing any behaviour. 
https://github.com/rails/rails/commit/3c10043bc272e13d2e01219b43beece060e5aa19

I will try to figure out why and create a test that proves that its behaviour is necessary.

**Comment by mackermedia** [comment] 2016-02-01 22:07
bump

**Comment by smikkelsen** [comment] 2016-02-08 23:38
I get same problem. I have an accounts table with product column that currently has null values. I try the following migration:
`        change_column :accounts, :product, :integer, default: 0, null: false`

and get the following error:
`    Mysql2::Error: Invalid use of NULL value: ALTER TABLE `accounts` CHANGE `product` `product` int(11) DEFAULT 0 NOT NULL/Users/.rvm/gems/ruby-2.2.0@global/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'

`


rails 4.2
ruby 2.2
mysql2 gem (0.3.17)

**Comment by kamipo** [comment] 2017-03-04 14:21
Fixed in #17822.

This issue was due to using previous column type for quoting a default value.
The refactoring changed to use correct column type for that.

https://github.com/rails/rails/blob/3c10043bc272e13d2e01219b43beece060e5aa19/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb#L101

Closing.

**Closed by kamipo** 2017-03-04 14:21 UTC
Labels: activerecord, With reproduction steps

**Comment by roberts1000** [comment] 2017-03-04 17:56
Thank You!

**Comment by wellington1993** [comment] 2018-02-27 13:30
I have similar problem:

I has a migration for creating table with the field:
```
  def self.up
    create_table :licencas do |t|
       ...
      t.timestamp :datateste
       ...
    end
  end
```

And another changing the column name:
```
  def self.up
    ...
    rename_column :licencas, :datateste, :data_teste
    ...
  end
```
But when try to run I received this error:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Invalid default value for 'data_teste': ALTER TABLE `licencas` CHANGE `datateste` `data_teste` timestamp DEFAULT NULL
```
and 

```
Caused by:
Mysql2::Error: Invalid default value for 'data_teste'
```

Any idea how to solve this example?

**Comment by wellington1993** [comment] 2018-02-27 13:38
I solve :+1:  the "Mysql2::Error: Invalid default value for 'data_teste'" problem,
adding "before rename_column":

`change_column_default :licencas, :datateste, Time.now`
