### ISSUE TITLE
Selenium WebDriver version 4.8 does not allow passing the URL to the driver anymore (actionpack)

### ISSUE THREAD

**Issue by Martouta** [rails/rails#47706] opened 2023-03-17 20:25 UTC
### Summary
In my `ApplicationSystemTestCase`, An `ArgumentError` is thrown when initializing `Selenium::WebDriver::Chrome::Driver` (in the `driven_by`) with the `:url` option in `selenium-webdriver` version 4.8.1. This issue was introduced intentionally in a recent commit.

### Steps to reproduce

Given an `ApplicationSystemTestCase` such as the following:

```ruby
require 'test_helper'
require 'selenium-webdriver'

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :headless_chrome, options: { url: 'http://localhost:4444/wd/hub' } do |option|
    option.add_argument('no-sandbox')
  end
end
```

Using `selenium-webdriver` version `4.8.1` (I guess it is the same with `4.8.0` as I will explain briefly).
The tests fail (in CircleCI) with this error log:

```
Error:
MainSystemTest#test_#root_&_#home:
ArgumentError: Can't initialize Selenium::WebDriver::Chrome::Driver with :url
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/chrome/driver.rb:32:in `initialize'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/driver.rb:47:in `new'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver/common/driver.rb:47:in `for'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.1/lib/selenium/webdriver.rb:88:in `for'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:83:in `browser'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/driver.rb:64:in `block in register_selenium'
    <internal:kernel>:90:in `tap'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/driver.rb:63:in `register_selenium'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/driver.rb:49:in `block in register'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/session.rb:105:in `driver'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/session.rb:91:in `initialize'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara.rb:421:in `new'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara.rb:421:in `block in session_pool'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara.rb:317:in `current_session'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/dsl.rb:46:in `page'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:99:in `save_image'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:36:in `take_screenshot'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:45:in `take_failed_screenshot'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:8:in `before_teardown'

rails test test/system/main_system_test.rb:22
```

I would expect it to work as it was working with `selenium-webdriver` version `4.7.1` for this line:

https://github.com/rails/rails/blob/18e53fbb2c1b76e4e0b906e602edb4ad7291b621/actionpack/lib/action_dispatch/system_testing/driver.rb#L16

But the reason it fails is that they introduced this exception intentionally in this commit:
https://github.com/SeleniumHQ/selenium/commit/08ee2d9fcf952aff3dc9752d2399e9474c356843

Looking at the date of that commit, I am guessing that the exception is also introduced in version 4.8.0 although I haven't tried this one, based on the release dates:
![image](https://user-images.githubusercontent.com/11318903/226026078-c6a50a68-cdda-4ccc-bad1-dfeea0e55840.png)

I see that your tests right now assume that the URL can be passed:
https://github.com/rails/rails/blob/29441c0e2f3ae57de9cb03ed4a06b218773990eb/actionpack/test/dispatch/system_testing/driver_test.rb#L13-L29

### System configuration
You can see all the versions I am using for the log backtrace, but anyway:
**Rails version**: 7.0.4.3
**Ruby version**: 3.2.0

**Comment by dorianmariefr** [comment] 2023-03-22 06:08
I'm able to reproduce with:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "capybara"
  gem "selenium-webdriver"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by(
    :selenium,
    using: :headless_chrome,
    options: { url: 'http://localhost:4444/wd/hub' }
  ) do |option|
    option.add_argument('no-sandbox')
  end

  def test_shows_the_homepage
    visit "/"
  end
end
```

**Comment by dorianmariefr** [comment] 2023-03-22 10:14
Failing test on rails/rails

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 4690b0f3d4..747663b407 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -429,7 +429,7 @@ GEM
       fugit (~> 1.1, >= 1.1.6)
     sdoc (2.6.1)
       rdoc (>= 5.0)
-    selenium-webdriver (4.7.1)
+    selenium-webdriver (4.8.1)
       rexml (~> 3.2, >= 3.2.5)
       rubyzip (>= 1.2.2, < 3.0)
       websocket (~> 1.0)
diff --git a/actionpack/test/dispatch/system_testing/system_test_case_test.rb b/actionpack/test/dispatch/system_testing/system_test_case_test.rb
index 855fb89e67..4dc529bdb5 100644
--- a/actionpack/test/dispatch/system_testing/system_test_case_test.rb
+++ b/actionpack/test/dispatch/system_testing/system_test_case_test.rb
@@ -42,3 +42,15 @@ class SetDriverToSeleniumHeadlessFirefoxTest < DrivenBySeleniumWithHeadlessFiref
     assert_equal :selenium, Capybara.current_driver
   end
 end
+
+class DrivenByHeadlessChromeWithUrl < ActionDispatch::SystemTestCase
+  driven_by(
+    :selenium,
+    using: :chrome,
+    options: { url: 'http://localhost:4444/wd/hub' }
+  )
+
+  test "uses selenium headless chrome with url" do
+    visit "/"
+  end
+end
```

**Comment by dorianmariefr** [comment] 2023-03-22 22:38
Only the remote driver accepts an url

So the correct way to do it is:

```
  driven_by(
    :selenium,
    using: :remote,
    options: { url: 'http://localhost:4444/wd/hub', capabilities: :chrome }
  ) do |options|
    options.add_argument('no-sandbox')
    options.add_argument('--headless')
  end
```

**Comment by Martouta** [comment] 2023-03-26 23:59
Thanks 👍 Unfortunately, this is what I get after running it exactly with what you sent (copy & paste):

```
Error:
MainSystemTest#test_#root_&_#home:
ArgumentError: Selenium::WebDriver::Remote::Driver needs :options to be set
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.2/lib/selenium/webdriver/remote/driver.rb:57:in `process_options'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.2/lib/selenium/webdriver/remote/driver.rb:36:in `initialize'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.2/lib/selenium/webdriver/common/driver.rb:57:in `new'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.2/lib/selenium/webdriver/common/driver.rb:57:in `for'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.2/lib/selenium/webdriver.rb:88:in `for'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:83:in `browser'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/driver.rb:64:in `block in register_selenium'
    <internal:kernel>:90:in `tap'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/driver.rb:63:in `register_selenium'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/driver.rb:49:in `block in register'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/session.rb:105:in `driver'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/session.rb:91:in `initialize'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara.rb:421:in `new'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara.rb:421:in `block in session_pool'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara.rb:317:in `current_session'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/capybara-3.38.0/lib/capybara/dsl.rb:46:in `page'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:99:in `save_image'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:36:in `take_screenshot'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:45:in `take_failed_screenshot'
    /root/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:8:in `before_teardown'


rails test test/system/main_system_test.rb:22
```

**Comment by hahmed** [comment] 2023-05-16 21:46
https://github.com/rails/rails/pull/44981 is merged, we should be able to close this because the docs will reflect the settings expected

**Comment by zzak** [comment] 2023-10-07 01:54
Ok, I could reproduce this, but got the actiontext tests running locally with this:

```diff
diff --git a/actiontext/test/application_system_test_case.rb b/actiontext/test/application_system_test_case.rb
index a24f473..dd1d2cb 100644
--- a/actiontext/test/application_system_test_case.rb
+++ b/actiontext/test/application_system_test_case.rb
@@ -3,7 +3,13 @@
 require "test_helper"

 class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
-  driven_by :selenium, using: :headless_chrome
+  options = {
+    browser: ENV["SELENIUM_DRIVER_URL"].blank? ? :chrome : :remote,
+    url: ENV["SELENIUM_DRIVER_URL"].blank? ? nil : ENV["SELENIUM_DRIVER_URL"]
+  }
+  driven_by :selenium, using: :headless_chrome, options: options
 end

 Capybara.server = :puma, { Silent: true }
+Capybara.server_host = "0.0.0.0" # bind to all interfaces
+Capybara.app_host = "http://#{IPSocket.getaddress(Socket.gethostname)}" if ENV["SELENIUM_DRIVER_URL"].present?
```

**Comment by hahmed** [comment] 2023-10-08 20:39
Hey @zzak just looking at the code you pasted and I can see in this line: `browser: ENV["SELENIUM_DRIVER_URL"].blank? ? :chrome : :remote,` 

The browser is set to `:chrome` and the URL is `nil` if there is no `SELENIUM_DRIVER_URL` ENV variable passed in, I think that's the expected behaviour. 

If you have browser: `:chrome` and url: `ENV["SELENIUM_DRIVER_URL"]` it should throw an error, which was what the OP was trying to do, but that's changed now and you can only pass in the URL if browser is `:remote`.

Sorry if I misunderstood

**Comment by zzak** [comment] 2023-10-09 00:08
You are right, I think I was able to reproduce both of those errors by doing the wrong thing, and the documented method works. So we can actually close this. Thanks for the sanity check!

**Closed by zzak** 2023-10-09 00:08 UTC
Labels: docs, With reproduction steps
