### ISSUE TITLE
NoMethodError: undefined method _deprecated_scope_block for ActiveRecord::AssociationRelation

### ISSUE THREAD

**Issue by foxlance** [rails/rails#41209] opened 2021-01-22 06:12 UTC
### Steps to reproduce
Our app is currently at **Rails v6.0.3.4** and **Ruby 2.7.2**. We would like to upgrade to Rails **v6.1.1**

Bundle update went well, but some of our specs started failing, particularly around our usage of `first_or_create`.

```ruby
[1] Facility.first.amenities.where(name: 'pool').first
=> nil

[2] Facility.first.amenities.where(name: 'pool').first_or_create
/Users/foxlance/.rvm/gems/ruby-2.7.2/gems/pry-0.12.2/lib/pry/exceptions.rb:28: warning: $SAFE will become a normal global variable in Ruby 3.0
NoMethodError: undefined method `_deprecated_scope_block' for #<ActiveRecord::AssociationRelation []>
from /Users/foxlance/.rvm/gems/ruby-2.7.2/gems/activerecord-6.1.1/lib/active_record/relation/delegation.rb:110:in `method_missing'
```

Tried this with **Rails v6.1.0** with the same result.

### Expected behavior
- The `Amenity` model should be created.

### Actual behavior
- We're getting the following error: **NoMethodError: undefined method `_deprecated_scope_block' for #<ActiveRecord::AssociationRelation []>**

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 2.7.2

**Comment by composerinteralia** [comment] 2021-01-23 18:46
As far as I can tell all references to `_deprecated_scope_block` within Rails were removed in Rails 6.1 via https://github.com/rails/rails/commit/255a7ef7b09ba96f92c7c8a8d59666314551f454. Your code or another library you are using might still reference `_deprecated_scope_block`. Seeing more of the stack trace might help narrow it down, but I'm going to close this issue since it doesn't seem like this error is coming from Rails itself. The method is not part of the public API, so breaking changes are acceptable.

If you are able to reproduce this issue with an [executable test case](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) then I can reopen.

Thank you!

**Closed by composerinteralia** 2021-01-23 18:46 UTC
