### ISSUE TITLE
Rails Upgraded to version 7

### ISSUE THREAD

**Issue by raoehtesham03** [rails/rails#50725] opened 2024-01-12 13:31 UTC
I have upgraded my application from Rails 6.1 to 7.0.8. 

```ruby
doctype html
html
  head
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"
    = stylesheet_link_tag "mailer"
  body
    table.logo width="100%" align="center" cellpadding="0" cellspacing="0"
      tr
        td align="left"
          img src="test.png"
    = yield

    div.footer
      p
        ' Thank You,
        br Powered by <a href="www.test.com">Test</a>
        br
        | Know Your Building Inside Out<sup>TM<sup/>
```

### Expected behavior
    It should render this.

### Actual behavior
Failure/Error: = stylesheet_link_tag "mailer"
     
     ActionView::Template::Error:
       Error: StringMap expected string key

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.0.2

Please help me to figure out this issue.

**Comment by raoehtesham03** [comment] 2024-01-12 14:17
So, while executing the test case I am getting this error. @akhilgkrishnan

**Comment by bparanj** [comment] 2024-01-12 14:37
Use this bug report template to reproduce the problem: https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_view.rb (post your script here)

This could be due to the way Rails 7 handles asset pipeline or view helpers. Check asset pipeline configuration: https://guides.rubyonrails.org/7_0_release_notes.html and verify that the mailer stylesheet is configured properly.

Make sure haml version that you are using is compatible with Rails 7. Check the haml documentation for any version incompatibilities.

Review Rails 7.0.8 changelog and see if any changes might have affected your application.

Search haml gem issues on github and see if there are any haml compatibility issues with Rails 7.

**Comment by raoehtesham03** [comment] 2024-01-12 15:20
I don't see any specific changes regarding stylesheet_link_tag in Rails 7. @bparanj

**Comment by fatkodima** [comment] 2024-01-12 18:39
I am closing this for now. If you will provide us a reproduction test script or a sample app, I will happily reopen.

**Closed by fatkodima** 2024-01-12 18:39 UTC

**Comment by raoehtesham03** [comment] 2024-01-15 04:44
@fatkodima I think After upgrading the my application to Rails 7.0, assets are not able to compile in test environment. 
How can I solve this ?
