### ISSUE TITLE
ActionView::HelperInclusionTest#test_helper_class_that_is_being_tested_is_always_included_in_view_instance gets error

### ISSUE THREAD

**Issue by yahonda** [rails/rails#36154] opened 2019-05-01 12:38 UTC
Reproduced Action View CI failure at 
https://buildkite.com/rails/rails/builds/60869#71c1ca6c-7165-4517-a08f-cd7452b93cc1 by #36153

### Steps to reproduce

```ruby
$ cd actionview
$ bin/test test/template/render_test.rb test/template/url_helper_test.rb test/template/test_case_test.rb -n "/^(?:CachedCollectionViewRenderTest#(?:test_render_partial_with_layout_using_collection_and_template)|UrlHelperControllerTest#(?:test_recall_params_should_normalize_id)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 49076
```

### Expected behavior
It should pass.

### Actual behavior

```ruby
$ bin/test test/template/render_test.rb test/template/url_helper_test.rb test/template/test_case_test.rb -n "/^(?:CachedCollectionViewRenderTest#(?:test_render_partial_with_layout_using_collection_and_template)|UrlHelperControllerTest#(?:test_recall_params_should_normalize_id)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 49076
Run options: -n "/^(?:CachedCollectionViewRenderTest#(?:test_render_partial_with_layout_using_collection_and_template)|UrlHelperControllerTest#(?:test_recall_params_should_normalize_id)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 49076

# Running:

.E

Error:
ActionView::HelperInclusionTest#test_helper_class_that_is_being_tested_is_always_included_in_view_instance:
ActionView::Template::Error: undefined method `_test_fixtures_test__customer_erb__1331366542035279901_47359544243960' for #<#<Class:0x0000562581a31770>:0x0000562581a313d8>
Did you mean?  _test_fixtures_test__from_helper_erb__825249575139590611_47359544383420
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:274:in `_run'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:185:in `block in render'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:182:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:386:in `instrument_render_template'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:183:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:455:in `block in collection_with_template'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:451:in `map'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:451:in `collection_with_template'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:340:in `block (2 levels) in render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb:15:in `cache_collection_render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:339:in `block in render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:328:in `render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:318:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:22:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:206:in `render'
    /home/yahonda/git/rails/actionview/test/template/test_case_test.rb:126:in `render_from_helper'
    /home/yahonda/git/rails/actionview/test/fixtures/test/_from_helper.erb:1:in `_test_fixtures_test__from_helper_erb__825249575139590611_47359544383420'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:274:in `_run'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:185:in `block in render'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:182:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:386:in `instrument_render_template'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:183:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:361:in `block in render_partial'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:350:in `render_partial'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:320:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:22:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:206:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:122:in `render'
    /home/yahonda/git/rails/actionview/test/template/test_case_test.rb:136:in `block in <class:HelperInclusionTest>'


bin/test test/template/test_case_test.rb:132

.

Finished in 0.122995s, 24.3911 runs/s, 48.7823 assertions/s.
3 runs, 6 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: master branch

**Ruby version**:ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by yahonda** [comment] 2019-05-01 12:47
I had reported a similar one #35389 which does not reproduce anymore.

**Comment by st0012** [comment] 2019-05-02 14:00
This one is very weird. At first I thought it's because ActionView generated different method name between it compiled a template and ran the template. But it's not, the template method name generation was correct.

So I put a break point here

https://github.com/rails/rails/blob/b343beba03722672b9bb827f8ce29c7c1c216406/actionview/lib/action_view/base.rb#L270-L274

And this is what I got

```
(byebug) method
"_test_fixtures_test__from_helper_erb___4322868309272960919_70268160416340"

(byebug) send(method, locals, buffer)
*** ActionView::Template::Error Exception: undefined method `_test_fixtures_test__customer_erb__3054194846241878373_70268160515440' for #<#<Class:0x00007fd12a09d488>:0x00007fd12a09cb78>
Did you mean?  _test_fixtures_test__from_helper_erb___4322868309272960919_70268160416340

(byebug) send("_test_fixtures_test__from_helper_erb___4322868309272960919_70268160416340", locals, buffer)
*** ActionView::Template::Error Exception: undefined method `_test_fixtures_test__customer_erb__3054194846241878373_70268160515440' for #<#<Class:0x00007fd12a09d488>:0x00007fd12a09cb78>
Did you mean?  _test_fixtures_test__from_helper_erb___4322868309272960919_70268160416340

(byebug) send("_test_fixtures_test__customer_erb__3054194846241878373_70268160515440", locals, buffer)
*** NoMethodError Exception: undefined method `_test_fixtures_test__customer_erb__3054194846241878373_70268160515440' for #<#<Class:0x00007fd12a09d488>:0x00007fd12a09cb78>
Did you mean?  _test_fixtures_test__from_helper_erb___4322868309272960919_70268160416340

```

So it looks like Rails was calling the right method but Ruby executed a different one.

**Comment by yahonda** [comment] 2019-05-03 13:31
Thanks for the invesitagation. I was trying to see if this reproduces with the latest version of Ruby, I mean 2.7.0dev and reproduced.

* Minimum step to reproduce

```
bin/test test/template/render_test.rb test/template/test_case_test.rb -n "/^(?:CachedCollectionViewRenderTest#(?:test_template_body_written_to_cache)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 4383
```


* Also reproduced with the latest trunk ruby

```ruby
$ ruby -v
ruby 2.7.0dev (2019-05-03 trunk 58cd4b7bde) [x86_64-linux]
```

* Actual result

```ruby
$ bin/test test/template/render_test.rb test/template/test_case_test.rb -n "/^(?:CachedCollectionViewRenderTest#(?:test_template_body_written_to_cache)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 4383
Run options: -n "/^(?:CachedCollectionViewRenderTest#(?:test_template_body_written_to_cache)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 4383

# Running:

.E

Error:
ActionView::HelperInclusionTest#test_helper_class_that_is_being_tested_is_always_included_in_view_instance:
ActionView::Template::Error: undefined method `_test_fixtures_test__customer_erb___409116034885411214_47433341611180' for #<#<Class:0x00005647deee8730>:0x00005647deee8280>
Did you mean?  _test_fixtures_test__from_helper_erb__2645341888037610986_47433341385940
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:274:in `_run'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:185:in `block in render'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:182:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:386:in `instrument_render_template'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:183:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:455:in `block in collection_with_template'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:451:in `map'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:451:in `collection_with_template'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:340:in `block (2 levels) in render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb:15:in `cache_collection_render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:339:in `block in render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:328:in `render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:318:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:22:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:206:in `render'
    /home/yahonda/git/rails/actionview/test/template/test_case_test.rb:126:in `render_from_helper'
    /home/yahonda/git/rails/actionview/test/fixtures/test/_from_helper.erb:1:in `_test_fixtures_test__from_helper_erb__2645341888037610986_47433341385940'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:274:in `_run'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:185:in `block in render'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:182:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:386:in `instrument_render_template'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:183:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:361:in `block in render_partial'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:350:in `render_partial'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:320:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:22:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:206:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:122:in `render'
    /home/yahonda/git/rails/actionview/test/template/test_case_test.rb:136:in `block in <class:HelperInclusionTest>'


bin/test test/template/test_case_test.rb:132



Finished in 0.115722s, 17.2829 runs/s, 34.5657 assertions/s.
2 runs, 4 assertions, 0 failures, 1 errors, 0 skips
$
```

**Comment by st0012** [comment] 2019-05-05 08:47
I did a further investigation:

## Causes
1) The resolver caches the template between 2 test cases, so the `customer` partial template object in `test_helper_class_that_is_being_tested_is_always_included_in_view_instance` is the same as `test_template_body_written_to_cache`
2)  Because `ActionView` gets the same template object from the previous test case. When we run the second test case, the template object is already marked as compiled. So during the `test_helper_class_that_is_being_tested_is_always_included_in_view_instance` test case, the template compilation will be skipped.
3) But because `ActionView` thinks it compiled the template, it’ll still try to call the compiled method, which causes the error.

We can observe this behavior with these diffs

```
diff --git a/actionview/lib/action_view/template.rb b/actionview/lib/action_view/template.rb
index b80bf56c1b..e21de76b42 100644
--- a/actionview/lib/action_view/template.rb
+++ b/actionview/lib/action_view/template.rb
@@ -181,7 +181,13 @@ def supports_streaming?
     # consume this in production. This is only slow if it's being listened to.
     def render(view, locals, buffer = ActionView::OutputBuffer.new, &block)
       instrument_render_template do
+        puts("Template #{object_id} is compiled? #{@compiled}")
+        puts("view's template methods before calling #compile! on template #{object_id}")
+        puts(view.compiled_method_container.instance_methods(false).grep(/_test/).to_s)
         compile!(view)
+        puts("view's template methods after calling #compile! on template #{object_id}")
+        puts(view.compiled_method_container.instance_methods(false).grep(/_test/).to_s)
+        puts("===============================")
         view._run(method_name, self, locals, buffer, &block)
       end
     rescue => e
```


This is the output for running the problematic test case alone

```
$ bin/test test/template/test_case_test.rb -n "/test_helper_class_that_is_being_tested_is_always_included_in_view_instance/" --seed 34567 -v
```

```
Template 70194631353460 is compiled? false
view's template methods before calling #compile! on template 70194631353460
[]
view's template methods after calling #compile! on template 70194631353460
[:_test_fixtures_test__from_helper_erb___2170271326713613823_70194631353460]
===============================
Template 70194631078620 is compiled? false
view's template methods before calling #compile! on template 70194631078620
[:_test_fixtures_test__from_helper_erb___2170271326713613823_70194631353460]
view's template methods after calling #compile! on template 70194631078620
[:_test_fixtures_test__customer_erb__2778493798454769509_70194631078620, :_test_fixtures_test__from_helper_erb___2170271326713613823_70194631353460]
===============================
Template 70194631078620 is compiled? true
view's template methods before calling #compile! on template 70194631078620
[:_test_fixtures_test__customer_erb__2778493798454769509_70194631078620, :_test_fixtures_test__from_helper_erb___2170271326713613823_70194631353460]
view's template methods after calling #compile! on template 70194631078620
[:_test_fixtures_test__customer_erb__2778493798454769509_70194631078620, :_test_fixtures_test__from_helper_erb___2170271326713613823_70194631353460]
===============================
# PASS
```

And this is the output when running both cases

```
$ bin/test test/template/render_test.rb test/template/test_case_test.rb -n "/test_template_body_written_to_cache|test_helper_class_that_is_being_tested_is_always_included_in_view_instance/"  --seed 34576 -v
```

```
Template 70278092615420 is compiled? false
view's template methods before calling #compile! on template 70278092615420
[]
view's template methods after calling #compile! on template 70278092615420
[:_test_fixtures_test__customer_erb__1876956427239259077_70278092615420]
===============================
# FIRST CASE PASS
view's template methods before calling #compile! on template 70278092521340
[]
view's template methods after calling #compile! on template 70278092521340
[:_test_fixtures_test__from_helper_erb__1669611016399818662_70278092521340]
===============================
Template 70278092615420 is compiled? true
view's template methods before calling #compile! on template 70278092615420
[:_test_fixtures_test__from_helper_erb__1669611016399818662_70278092521340]
view's template methods after calling #compile! on template 70278092615420
[:_test_fixtures_test__from_helper_erb__1669611016399818662_70278092521340]
===============================
# ERROR
```

From the second output, you can see that we got `70278092615420` for both cases. And we lost one method because of this.

And clearing the cache of resolvers makes the tests pass:

```
diff --git a/actionview/test/template/render_test.rb b/actionview/test/template/render_test.rb
index f0b5d7d95e..38f373fb38 100644
--- a/actionview/test/template/render_test.rb
+++ b/actionview/test/template/render_test.rb
@@ -760,6 +760,7 @@ class CachedCustomer < Customer; end

   teardown do
     I18n.reload!
+    ActionController::Base.view_paths.map(&:clear_cache)
   end

   test "template body written to cache" do
```

I guess the root cause may be that we don't teardown the test setup clean enough? Need some confirmations from maintainers. cc @tenderlove @jhawthorn

**Comment by yahonda** [comment] 2019-05-06 04:10
Great investigation. I have confirmed that clearing the cache addresses the issue here.

How about opening a pull request to add `ActionController::Base.view_paths.map(&:clear_cache)` in the teardown?

**Comment by st0012** [comment] 2019-05-06 12:15
@yahonda PR created, thanks for reporting!

**Closed** 2019-05-06 14:23 UTC
