### ISSUE TITLE
can't start new rails 7.0.0.alpha2 app: Command "build" not found

### ISSUE THREAD

**Issue by masterkain** [rails/rails#43338] opened 2021-09-30 09:41 UTC
```
% gem install rails --no-document --pre
% rails -v
Rails 7.0.0.alpha2
% rails new myapp --database=postgresql -j esbuild --css tailwind
```

at the end of the generator there is this line:

```
✨  Done in 6.49s.
Add build:css script
Add "scripts": { "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css" to your package.json
```

it is unclear if the user should add this line manually in their `package.json`, first because in dhh's video https://www.youtube.com/watch?v=JsNtLiph87Y it does not, and second it is missing a closing `}`.
I assume I have to inject it, so I did, the task runs.

second, I tried to start up the application:

`bin/dev`

that results in:

```
11:34:19 web.1  | started with pid 9127
11:34:19 js.1   | started with pid 9128
11:34:19 css.1  | started with pid 9129
11:34:19 css.1  | yarn run v1.22.11
11:34:19 js.1   | yarn run v1.22.11
11:34:19 css.1  | $ tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --watch
11:34:19 js.1   | error Command "build" not found.
11:34:19 js.1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
11:34:20 js.1   | exited with code 1
11:34:20 system | sending SIGTERM to all processes
11:34:20 css.1  | exited with code 1
11:34:20 web.1  | terminated by SIGTERM
```

the generated package.json, plus the `"scripts"` addition mentioned above:

```
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.0.0",
    "@hotwired/turbo-rails": "^7.0.1",
    "autoprefixer": "^10.3.6",
    "esbuild": "^0.13.3",
    "postcss": "^8.3.8",
    "tailwindcss": "^2.2.16"
  },
  "scripts": {
    "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css"
  }
}
```

no task `build`.

generated `Procfile.dev`

```
web: bin/rails server -p 3000
js: yarn build --watch
css: yarn build:css --watch
```

**Comment by SkipKayhil** [comment] 2021-09-30 16:31
Duplicate of #43309

You must have npm 7.1+, see [js-bundling README](https://github.com/rails/jsbundling-rails#installation) and better error message added in https://github.com/rails/jsbundling-rails/commit/afb168af5c091b1162b09c81579f3eb303683eaf

**Closed** 2021-10-01 04:41 UTC

**Comment by buncis** [comment] 2021-11-29 13:58
I've install node `16.13.0` and npm `8.1.0` yarn `1.22.15`
the problem is persist what to do?

**Comment by pdpl89** [comment] 2022-01-23 03:49
if you probably created a new Rails app using Docker(as I did), you may get the info lost, during the project creation,  where the command line asks you to add the scripts in **package.json**  file , that executes both build actions described in the Procfile.dev file.
As been told by @buncis , just run the installers again and check the command line: it will show you the scripts to be added in to package.json
