### ISSUE TITLE
[Rails 6.0rc1] window.Rails not defined

### ISSUE THREAD

**Issue by zzeligg** [rails/rails#36686] opened 2019-07-15 18:24 UTC
### Steps to reproduce
Create new 6.0rc1 app with defaults `rails new test-ujs` and create a simple view on `application_controller#index`

```
# app/views/application/index.html.erb

<p><%= link_to "Confirm this", root_url, data: { confirm: "Really confirm this?" } %></p>
```
visit the resulting url:  http://locahost:3000/

### Expected behavior
In browser console: `Rails` and `window.Rails` should return the Rails object defined in rails-ujs and be globally accessible.

### Actual behavior
In browser console: `Rails` and `window.Rails` are `undefined`

But rails-ujs has been properly initialized, since the link in the page will display the confirmation dialog, as it should.

Also, this means that the event `rails:attachBindings` is never fired from within the start() method.That is my main concern, since i rely on it for some UI functionality.

### Most likely cause

rails-ujs, when bundled using Webpacker, is not exported/compiled the same way as with sprokets.

### System configuration
**Rails version**: 6.0rc1

**Ruby version**: ruby 2.6.1p33

**Comment by robzolkos** [comment] 2019-07-17 19:16
I have confirmed the above behavior.

However `rails:attachBindings` seems to only be in place for tests as per https://github.com/rails/rails/issues/28992#issuecomment-301203867

Could you outline a use case @zzeligg as there may be other ways to do what you need?

**Comment by zzeligg** [comment] 2019-07-17 20:35
Thanks @robzolkos,

The reason i need to hook into `rails:attachBindings` is that I have added my own `window.confirm` functionality to display an HTML-based dialog. This requires to bind my click handler **before** `Rails.start()` is called so that it binds my custom handler before Rails' own `handleConfirm`, and in turn, have my handler called first when clicks occur.

If there is anoway way to prepend an event listener, I am all ears ;-)

**Comment by robzolkos** [comment] 2019-07-17 20:49
I think a workaround is mentioned in the issue I linked https://github.com/rails/rails/issues/28992

It seems like it wasn't _broken_ functionality as such.

Webpacker by default has @rails/ujs imported in like this

```
require("@rails/ujs").start()
```

You could change that to 

```
import Rails from "@rails/ujs";
if (Rails.fire(document, "rails:attachBindings")) {
  Rails.start();
}
```

Would that work for your case?

**Comment by zzeligg** [comment] 2019-07-18 16:13
@robzolkos thanks for the reply.

What you suggest still doesn't define the Rails object globally, though. 

In my case (which I realize is very specific), I end up needing to do the following:

```js
import Rails from "@rails/ujs";
window.Rails = Rails;

// now that Rails is globally defined, I can use it in my code. This allows
// to use Rails.delegate and other utility methods it defines
require("modal-confirm");

// And now, fire rails:attachBindings and then start Rails, so that its own 
// handlers are hooked AFTER mine, since mine must override handleConfirm 
if(Rails.fire(document, "rails:attachBindings")) {
  Rails.start();
}
```
It does work, but it feels hacky that the import/start sequence has to be so specific. And using it this way is prone to break in future version, I think...

I will probably rewrite my custom confirmation dialog code, so that it doesn't rely on the Rails object at all, but I thought it was nice to use its utility methods instead of duplicating them. I'm a big fan of `Rails.delegate` as it is efficient at dispatching events to multiple elements from a single binding.

In any case, I originally intended to report this issue as a general case where `Rails` / `window.Rails` is not available globally anymore. If we compare with Turbolinks for example, its object is available as `window.Turbolinks` whatever the packaging method used (webpack or sprockets). I just thought rails-ujs should behave in the same way.

**Comment by jakeNiemiec** [comment] 2019-07-18 18:29
@zzeligg I think the way you do this above is good. Assigning objects to the `window` object can break other flows like server-side rendering & JS testing on CI servers where `window` does not exist.

This way, it's opt-in.

> It does work, but it feels hacky that the import/start sequence has to be so specific.

There is room for improvement here. You could eliminate side effects from your `modal-confirm` script by exporting a setup function that takes Rails and a callback function:

```js
import Rails from "@rails/ujs";
import { setUpModalConfirm } from "modal-confirm";

// Instead, use the param given instead of global
setUpModalConfirm(Rails, Rails.start); // <- note there is no (), you pass a reference to the function as a callback


// -----------------------
// INSIDE modal-confirm.js
// -----------------------
export const setUpModalConfirm = function (Rails, callback) {
  
  //modal-confirm stuff goes HERE
  
  if(Rails.fire(document, "rails:attachBindings")) {
    callback()
  }
};
```

**Comment by zzeligg** [comment] 2019-07-18 20:24
@jakeNiemiec Thanks for the suggestion. It would indeed work and also have the merit to clarify the dependency on the Rails object (i.e. the Rails object must exist to even call the initializer for the modal confirmation module/object).

However, I can see it would pose a problem if a second script/module used the same strategy: The first script would call the callback `Rails.start()` and that would break the initialization sequence for the second one which would expect to be able to call `Rails.start()` only after its own initialization too.

Of course, this is hypothetical, as I have no other script that works this way, but maybe rails-ujs could continue to provide a mechanism by which we can refer to it before `Rails.start()` is called. This is essentially what was possible when `window.Rails` was simply `require`'d and we could rely on `rails:attachBindings` being fired by rails-ujs itself just before it would `start()`.

**Comment by rafaelfranca** [comment] 2019-07-23 13:37
Closing since this is not an issue. When using rails-ujs with webpack `windown.Rails` is indeed not defined.

**Closed by rafaelfranca** 2019-07-23 13:37 UTC
