### ISSUE TITLE
action_on_unpermitted_parameters = :raise not working

### ISSUE THREAD

**Issue by shaicoleman** [rails/rails#38253] opened 2020-01-17 17:57 UTC
### Steps to reproduce
* Create an initializer with the following line
`ActionController::Parameters.action_on_unpermitted_parameters = :raise`
* Create a form passing an unpermitted parameter to a controller which doesn't permit that field

Example app to reproduce the issue: https://github.com/shaicoleman/action_on_unpermitted_parameters_bug

Relevant documentation page:
https://api.rubyonrails.org/classes/ActionController/Parameters.html

### Expected behavior
It should raise an exception

### Actual behavior
It logs the unpermitted parameter

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5

**Comment by joshmn** [comment] 2020-01-17 21:20
Your example app has `ActionController::Parameters.action_on_unpermitted_parameters` set to `:log` — even though you did set it to `:raise` in your initializer, it's getting overwritten somewhere.

Adding `config.action_controller.action_on_unpermitted_parameters = :raise` to `application.rb` will give you the expected behavior.

**Comment by shaicoleman** [comment] 2020-01-18 01:59
@joshmn , thanks.
If the overwriting is intentional, then the [documentation page](https://api.rubyonrails.org/classes/ActionController/Parameters.html) should be updated to clarify not to update it directly, but through the Rails configuration setting.

**Comment by joshmn** [comment] 2020-01-18 02:01
@shaicoleman you're welcome. I'm not sure where it's getting loaded again (didn't look that hard), but it's on my todo list to find out. If someone knows something I don't they're welcome to inform :)

**Comment by Edouard-chin** [comment] 2020-02-04 16:16
It get overridden here https://github.com/rails/rails/blob/a7104fa44c59d6464572a6402e295d6a1301447d/actionpack/lib/action_controller/railtie.rb#L33-L34  (Basically when the request hit your app)

**Comment by rafaelfranca** [comment] 2020-02-04 19:45
You probably have something that loads `ActionController::Base` before your config is set, this is why you have `:log` instead of `:raise`. Make sure your app don't have any library or code that loads `ActionController::Base` before `config.action_controller.action_on_unpermitted_parameters = :raise` is set by your application.

Closing since this is not a bug in Rails

**Closed by rafaelfranca** 2020-02-04 19:45 UTC
