### ISSUE TITLE
ActiveStorage with Firefox: form doesn't get submitted

### ISSUE THREAD

**Issue by mdesantis** [rails/rails#31860] opened 2018-02-01 14:57 UTC
This issue is different from this other one: https://github.com/rails/rails/issues/31393 Now the upload works, but the form doesn't get submitted.

### Steps to reproduce

It can be reproduced on this demo app: https://github.com/mdesantis/activestorage_demo

### Expected behavior

This is what happens on Chrome: 
![chrome](https://user-images.githubusercontent.com/283320/35684852-6c0d030c-0768-11e8-95c1-bdd410efbc44.gif)

### Actual behavior

This is what happens on Firefox: 
![firefox](https://user-images.githubusercontent.com/283320/35684871-7865c51c-0768-11e8-873b-0711e186588a.gif)

### System configuration
**Rails version**: 5.2.0.rc1

**Firefox version**: 58.0.1(Linux x64)

**Comment by javan** [comment] 2018-02-01 15:58
Thanks for the demo app! I'll take a look soon.

If you remove the file inputs, do Chrome and Firefox handle the validation errors the same way?

**Comment by mdesantis** [comment] 2018-02-01 16:03
> If you remove the file inputs, do Chrome and Firefox handle the validation errors the same way?

Yes, and the form get submitted even if I leave the file input but the user doesn't use it. Otherwise, the form doesn't get submitted (I mean that no create/update request arrives to the server).

**Comment by mdesantis** [comment] 2018-02-01 17:18
I have a question: I'd like to work on this issue, but I have no idea how to setup a development environment for working on activestorage javascripts. Do you have suggestions? Thanks :)

**Comment by javan** [comment] 2018-02-01 18:04
Great! Easiest way is pointing your demo app at a local clone/fork of Rails:
```rb
# Gemfile
gem 'rails', path: '~/Code/rails'
```
Then get set up with the js build tooling:
```sh
$ cd ~/Code/rails/activestorage
$ yarn install
```
Make edits to the source `activestorage/app/javascript/activestorage/*.js` files, and then rebuild the compiled `activestorage.js` file by running: `$ yarn build`.

Reload your app and it'll use your newly compiled `activestorage.js`.

**Comment by Assaya** [comment] 2018-02-01 18:05
Hi

Sent from Mail for Windows 10

**Comment by mdesantis** [comment] 2018-02-02 14:13
Thanks @javan, it helped me a lot. The problem seems to be here: https://github.com/rails/rails/blob/master/activestorage/app/javascript/activestorage/ujs.js#L51-L67

I could verify that `button.click()` there doesn't submit the form, while `form.submit()` does, I have no idea why. I tried commenting the `button.disabled` restoring, but it didn't help. Maybe we could just `form.submit()` there, since we have the form?

**Comment by mdesantis** [comment] 2018-02-02 14:29
Also if we `form.submit()` we can stop caring about submit button disabling, since it's then managed by rails ujs itself, as I've just verified

**Comment by javan** [comment] 2018-02-02 14:58
Hmm, I believe `form.submit()` has its own set of issues. I borrowed the `button.click()` idea from rails ujs itself: https://github.com/rails/rails/blob/74aa62cb691f1abd12e244c3498dc696e0b7ef77/actionview/app/assets/javascripts/rails-ujs/features/method.coffee#L21-L32

**Comment by javan** [comment] 2018-02-02 15:10
Ha, as I was typing this someone opened an unrelated issue that illustrates the problem with using `form.submit()`: https://github.com/stimulusjs/stimulus/issues/92

**Comment by mdesantis** [comment] 2018-02-02 15:12
Ahhh, browsers! Even worse, I couldn't find any useful information around the web about these different behaviours, just issue reports. What about triggering both events hoping one of them to work? :D

**Comment by javan** [comment] 2018-02-03 19:20
FWIW, I'm unable to reproduce this issue in my own sample app. Chrome and Firefox both redirect to /new as expected when there's a validation error.

**Comment by javan** [comment] 2018-02-04 17:32
@mdesantis, can you update your demo app so it doesn't require secret credentials (or provide me with them)? I can't run it locally as-is.

**Comment by mdesantis** [comment] 2018-02-04 17:54
Yeah sorry, the credentials on development environment are:

- username: `admin`
- password: `password`

> FWIW, I'm unable to reproduce this issue in my own sample app. Chrome and Firefox both redirect to /new as expected when there's a validation error

O.O maybe I did something wrong??

**Comment by mdesantis** [comment] 2018-02-04 17:57
If you prefer to disable authentication comment this line: https://github.com/mdesantis/activestorage_demo/blob/master/app/controllers/posts_controller.rb#L2

**Comment by javan** [comment] 2018-02-04 20:24
Thanks, got it running. I commented out your [`event.target.submit()` workaround](https://github.com/mdesantis/activestorage_demo/blob/a50f2a3c056b84c5129e4853ec9c14321451f593/app/assets/javascripts/direct_uploads.js#L49-L50) and am still unable to reproduce the issue. Also using Firefox 58.0.1.

![as-demo-ff](https://user-images.githubusercontent.com/5355/35781986-5ea05ac6-09bf-11e8-97ef-49913eebebac.gif)

Closing for now.

**Closed by javan** 2018-02-04 20:24 UTC
Labels: activestorage

**Comment by andrewkress** [comment] 2018-04-09 20:42
> Also if we form.submit() we can stop caring about submit button disabling, since it's then managed by rails ujs itself, as I've just verified.

> Edit: at the moment, a good workaround without touching ActiveStorage javascript is to put this in your app:


> `addEventListener("direct-uploads:end", event => {
> event.target.submit()
>})`

@mdesantis did you ever figure out what was going on?  I am having the same issue with Firefox (both windows and linux).  I used the event.target.submit workaround and it seems to work now, but would like to know if I have something else incorrect somewhere.  I am using 5.2.0rc2

**Comment by mdesantis** [comment] 2018-04-10 12:55
@andrewkress no, unfortunately I haven't got much luck yet

**Comment by lancecarlson** [comment] 2018-04-17 04:10
Have the changes that fix these Firefox issues made it into 5.2.0? For me, Firefox still has issues. My app is running devise, so I wasn't able to easily upgrade to edge to see if edge was working. If it's working on edge and not 5.2.0, I think there should be a version bump asap?

**Comment by andrewkress** [comment] 2018-04-18 16:54
No, there was not a fix included in 5.2.0 as @javan was unable to reproduce the issue.  The workaround used would require you to change the direct_uploads.js (not directly part of rails) to include this at the end of the file:

```
addEventListener("direct-uploads:end", event => {
  event.target.submit()
})
```

**Comment by mdesantis** [comment] 2018-04-18 17:27
I'd like to point out that you don't have to modify the Rails file, just
add that snippet within your Rails app javascript assets and you are fine

---

Maurizio De Santis

Il mer 18 apr 2018, 18:55 Andrew Kress <notifications@github.com> ha
scritto:

**Comment by memoht** [comment] 2018-05-11 17:36
I feel like this thread describes my issue implanting Active Storage on Rails 5.2.0, but in my case Firefox for MacOS works fine, and Firefox WinOS is the troublemaker. I recorded a brief video of my app demonstrating this issue. https://youtu.be/_KDlsFH1QCc

**Comment by courtsimas** [comment] 2018-07-19 19:47
I still have this issue, but only in mobile safari... but not any current desktop browsers that I test with. So odd.
