### ISSUE TITLE
When a parent model has `before/after_commit/rollback` hooks, changing child attributes with `accepts_nested_attributes_for` causes parent to not be touched

### ISSUE THREAD

**Issue by cannikin** [rails/rails#26726] opened 2016-10-06 19:50 UTC
### Steps to reproduce

Comment out line 39 `after_commit { true }` to get all tests to pass:

``` ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.timestamps
  end

  create_table :posts do |t|
    t.references :user
    t.string :title
    t.timestamps
  end
end

class User < ActiveRecord::Base
  has_many :posts
  accepts_nested_attributes_for :posts

  # Comment out to get tests to pass:
  after_commit { true }
  # Any of the following cause the same issue:
  # after_rollback { true }
  # before_commit { true }
  # before_rollback { true }
end

class Post < ActiveRecord::Base
  belongs_to :user, :touch => true
end

class BugTest < Minitest::Test

  def setup
    User.destroy_all
    Post.destroy_all

    # create a user that was updated an hour ago
    user = User.create
    user.update_columns :created_at => 1.hour.ago, :updated_at => 1.hour.ago
  end

  def test_creating_post_via_has_many_helper_touches_user
    original_updated_at = User.first.updated_at
    User.first.posts.create! :title => 'Post title'

    refute_equal original_updated_at.to_i, User.first.updated_at.to_i
  end

  def test_creating_post_with_nested_attributes_touches_user
    original_updated_at = User.first.updated_at
    User.first.update! :posts_attributes => { '0' => { :title => 'Post title' } }

    refute_equal original_updated_at.to_i, User.first.updated_at.to_i
  end

end
```
### Expected behavior

Creating/updating/destroying a child that is set to touch the parent should do so via nested attributes whether or not the parent has a `before_commit`, `after_commit`, `before_rollback` or `after_rollback` hook set.
### Actual behavior

Creating a `before_commit`, `after_commit`, `before_rollback` or `after_rollback` hook causes nested attributes to NOT touch the parent, even though `:touch => true` is set.
### System configuration

**Rails version**:
5.0.0.1

**Ruby version**:
2.3.1

**Comment by maclover7** [comment] 2016-10-06 22:52
Git bisected and is saying that 89713897830cabe49658755ddd673bbdb0a64f11 by @arthurnn is causing this issue.

**Comment by cannikin** [comment] 2016-10-06 23:01
Sweet, I'm not crazy!

In the meantime I've littered `after_save :touch_user` and `after_destroy :touch_user` callbacks in all the child classes. So much duplication, it hurts my soul! Also when saving 6 different nested models I end up with User being touched 6 times. :( :(

**Comment by johnmaxwell** [comment] 2016-10-19 02:31
Really nice troubleshooting @cannikin . I just ran into this too and you saved me some time.

**Comment by matt297** [comment] 2017-04-17 16:32
Just another quick thanks to @cannikin - this issue was immensely helpful in diagnosing why `touch: true` wasn't working. Also confirming that this is still an issue with a fresh install of rails 5.0.2.

**Comment by wnm** [comment] 2017-05-09 16:07
The test from above now passes on master. But when I change `has_many :posts` to `has_many :posts, -> { order("title DESC") }`, it makes the test fail on master again (it's passing on 4.2.0):

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "4.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.timestamps
  end

  create_table :posts do |t|
    t.references :user
    t.string :title
    t.timestamps
  end
end

class User < ActiveRecord::Base
  has_many :posts, -> { order("title DESC") }
  accepts_nested_attributes_for :posts

  # Comment out to get tests to pass:
  after_commit { true }
  # Any of the following cause the same issue:
  # after_rollback { true }
  # before_commit { true }
  # before_rollback { true }
end

class Post < ActiveRecord::Base
  belongs_to :user, :touch => true
end

class BugTest < Minitest::Test

  def setup
    User.destroy_all
    Post.destroy_all

    # create a user that was updated an hour ago
    user = User.create
    user.update_columns :created_at => 1.hour.ago, :updated_at => 1.hour.ago
  end

  def test_creating_post_via_has_many_helper_touches_user
    original_updated_at = User.first.updated_at
    User.first.posts.create! :title => 'Post title'

    refute_equal original_updated_at.to_i, User.first.updated_at.to_i
  end

  def test_creating_post_with_nested_attributes_touches_user
    original_updated_at = User.first.updated_at
    User.first.update! :posts_attributes => { '0' => { :title => 'Post title' } }

    refute_equal original_updated_at.to_i, User.first.updated_at.to_i
  end

end
```

**Comment by wnm** [comment] 2017-05-11 16:53
I tried to debug this, but I'm stuck. Maybe someone with a better understanding of transactions can help me out. This is how far I got:

When I have the model setup like this

```ruby
class User < ActiveRecord::Base
  has_many :posts
  accepts_nested_attributes_for :posts
end

class Post < ActiveRecord::Base
  belongs_to :user, :touch => true
end
```

And update its attributes via

`User.first.update! :posts_attributes => { '0' => { :title => 'Post title' } }`

the User gets touched, and updated_at is set.

When I add a order scope to the has_many relation, it stops working 

```ruby
class User < ActiveRecord::Base
  has_many :posts, -> { order("title DESC") }
  accepts_nested_attributes_for :posts
end

class Post < ActiveRecord::Base
  belongs_to :user, :touch => true
end
```

I've set a few break points, and one odd thing I found was in [before_commit_records](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L78) call, in the list of records for the transaction.

Without a order scope in User.has_many, the records where all the same object:

```ruby
records[0].equal? records[1] #=> true
records[0].equal? records[2] #=> true
records[1].equal? records[2] #=> true
```

Thus, all records have the instance variable `@_defer_touch_attrs` (which is set by [touch_later](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/touch_later.rb#L18)):

```ruby
records.map{|r| r.instance_variable_get "@_defer_touch_attrs" }
#=> [["updated_at"], ["updated_at"], ["updated_at"]]
```

So, when duplicate records are removed, by [records.uniq](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L79), the remaining record has still an instance variable `@_defer_touch_attrs` set, and when [touch_deferred_attributes](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/touch_later.rb#L47) is called in an before_commit callback, the [has_defer_touch_attrs?](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/touch_later.rb#L54) check returns true.

Compared to the User with an order scope (**which is the case thats not working**), the records are **not** all the same object:

```ruby
records[0].equal? records[1] # true
records[0].equal? records[2] # false
records[1].equal? records[2] # false
```

So, **not** all records have `@_defer_touch_attrs set`:

```ruby
records.map{|r| r.instance_variable_get "@_defer_touch_attrs" }
#=> [nil, nil, ["updated_at"]]
```

And after [removing the dublicates](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L79), the remaining object has no `@_defer_touch_attrs` set:

```ruby
records.uniq.map{|r| r.instance_variable_get "@_defer_touch_attrs" }
#=> [nil]
```

So when [touch_deferred_attributes](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/touch_later.rb#L47) is called in an before_commit callback, the [has_defer_touch_attrs?](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/touch_later.rb#L54) check returns false, and [touch](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/touch_later.rb#L49) is never called.

My problem: I have no idea **why** in the working case all records are the same object, and why they are not the same when I add a scope.

**Comment by wnm** [comment] 2017-05-18 12:56
I did some further digging, and I think I found the problem and a working solution. I created a pull request [here](https://github.com/rails/rails/pull/29132)

**Comment by ulferts** [comment] 2017-09-28 08:07
When working on circumventing the bug by adding `after_save` callbacks as proposed by @cannikin, the test I was writing turned green when I added the `inverse_of` option on the `has_many` association. Manual tests confirmed that adding the option leads to the desired behaviour. 

In the example provided, this would translate to

```
has_many :posts, inverse_of: 'user'
```

The option seems to ensure the correct instance for the touch.

**Comment by wnm** [comment] 2017-10-01 09:11
@ulferts nice find! thanks! It's a much better work around, because `after_save` callbacks are called multiple times, e.g. in the example above when you update multiple posts through `accepts_nested_attributes_for` on the same user, the belonging user gets touched multiple times. With `inverse_of` all posts updates are run, then the belonging user gets touched _once_.

**Comment by afn** [comment] 2020-05-19 02:01
This bug still exists in master. I've added a test case here: https://github.com/rails/rails/compare/master...afn:test-case-for-26726

**Comment by mrbrdo** [comment] 2022-11-09 13:10
Hitting this bug with AR 6.1.7, **even when using** `inverse_of`. TouchLater is being used.

**Comment by cannikin** [comment] 2022-11-09 22:02
I still think about this issue from time to time...it's six years old now!

**Comment by mrbrdo** [comment] 2022-11-10 15:57
@eileencodes could someone take a look?

**Comment by eileencodes** [comment] 2022-11-10 16:14
Please use the Discord to ask for help. We're all really busy and can't pick up random issues that don't have a modern reproduction.

**Comment by mrbrdo** [comment] 2022-11-10 16:31
@eileencodes what do you mean they don't have a modern reproduction? I assume Minitest still exists?
Well, this issue was tagged and **assigned** 6 years ago but was not fixed. The author of the offending code was tagged but not responded.
I'm quite busy too, believe it or not.

**Comment by mrbrdo** [comment] 2022-11-10 22:19
@rafaelfranca sorry if I'm violating a protocol here but does the above unassignment mean this will be considered or was that just housekeeping? So I know if there is a point waiting for some progress or we need to implement a hack, as I don't think I can solve this one. Can wait weeks, maybe months, but not years.

**Comment by rafaelfranca** [comment] 2022-11-18 19:20
Just housekeeping. If this is an issue for you, please go ahead and submit a PR. This isn't an issue for our applications, so of course we are not going to prioritize it.

**Comment by mrbrdo** [comment] 2022-11-18 21:05
After talking on Discord it seems like no one is willing to maintain the TouchLater functionality anymore. Since after 6 years no one has tackled this, it seems it's dead code.
As it provides no feature other than a performance boost, but instead breaks core Rails functionality, I suggest TouchLater is removed. Probably 99% of people are not using this or care about it anyway.
If you need it in your project it should be extracted into a gem.

If you agree @rafaelfranca, I can prepare a PR with the appropriate reverts.

**Comment by mrbrdo** [comment] 2022-11-19 01:01
@rafaelfranca regarding your questions from Discord:

> reading my 5 years old comment, I see a very easy way for you to help, can you verify if the issue is fixed if we change [this line](https://github.com/rails/rails/blob/994bce4e32306b957eb61b8d6edd1cbb3f3120b8/activerecord/lib/active_record/touch_later.rb#L66) to :touch?

Yes, it does fix it. (I added the method override in the base AR model of Spree, where _we_ are observing this issue)

> The second part is to understand what are the cases that touch_later can't be used. Is it because the association can't be inverted? It is because the foreign key is wrong?

In this case `:inverse_of` is provided to all the associations in question, but it did not fix the issue. Let me give an example where it does not work (from Spree):
```ruby
# Price
belongs_to :variant, -> { with_deleted }, class_name: 'Spree::Variant', inverse_of: :prices, touch: true
# Variant
has_many :prices,
             class_name: 'Spree::Price',
             dependent: :destroy,
             inverse_of: :variant
```
After updating the Price, it will not touch the Variant. After applying above change to `belongs_to_touch_method`, it will (that being the only change).

**Comment by rafaelfranca** [comment] 2022-11-19 01:06
Thanks for confirming. How about with this fix:

```diff
diff --git a/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb
index a87e34b08f..f82a2b937a 100644
--- a/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb
+++ b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb
@@ -165,7 +165,20 @@ def rollback_records
       end
 
       def before_commit_records
-        records.uniq.each(&:before_committed!) if records && @run_commit_callbacks
+        return unless records
+
+        ite = records.uniq(&:__id__)
+
+        if @run_commit_callbacks
+          instances_to_run_callbacks_on = records.each_with_object({}) do |record, candidates|
+            candidates[record] = record
+          end
+
+          while record = ite.shift
+            should_run_callbacks = record.__id__ == instances_to_run_callbacks_on[record].__id__
+            record.before_committed! if should_run_callbacks
+          end
+        end
       end
 
       def commit_records
```

**Comment by mrbrdo** [comment] 2022-11-19 01:34
The above fix seems to work for Spree and as far as I understood it will be in Rails master next week. Great to hear 👍

**Closed** 2022-11-22 23:00 UTC
Labels: activerecord, needs feedback, With reproduction steps
