### ISSUE TITLE
ActiveStorage direct upload bug in safari

### ISSUE THREAD

**Issue by silva96** [rails/rails#45193] opened 2022-05-27 21:39 UTC
I found a bug where ActiveStorage direct uploads are not working in safari, in chrome works perfectly. This happens in ipad safari and mac safari (haven't tried in iphone).

Please see this gif of how it works in chrome:

![direct_upload_chrome](https://user-images.githubusercontent.com/4019924/170791938-01dd2047-beeb-45fe-8ca2-f167608291fc.gif)

But in safari it gets stuck and never calls the form action after the direct upload. I'm looking at Aws S3 and the files are there, but the rails form that attaches the direct uploads to the actual records is never posted so the files are not  associated with the records.

![direct_upload_safari](https://user-images.githubusercontent.com/4019924/170792058-c61ebe16-4114-4f18-96de-c747b14c01be.gif)

the relevant code:

```erb
<%= form_with(model: @product, url: update_cover_media_product_path(@product)) do |f| %>
  <%= f.file_field :cover_media, class: 'file-input is-hidden', direct_upload: true, multiple: true %>

  ...
<% end %>
```

**Comment by ghiculescu** [comment] 2022-06-02 22:47
Could you share a sample app that reproduces the issue? With just a few lines it's not easy to reproduce.

**Comment by silva96** [comment] 2022-06-03 22:37
Alright, so first of all, I managed to fix my problem
Second, it's not abug of activestorage persé, only happens when using Turbo and trying to programmatically submit the form on file change

Here is the reproduction app

https://github.com/silva96/direct_upload_bug

Note that in the Stimulus controller called `direct-upload-controller.js` there is a function like this:

```js
submit (event) {
    // it works if we programatically click the submit
    // event.currentTarget.closest('form').querySelector('input[type=submit]').click()
    // doesn't work if we requestSubmit
    event.currentTarget.closest('form').requestSubmit()
  }
  ```
  
  Which is called whenever a file input changes it's content.
  
  The code will work in Chrome when you run the app as is. It wont work in Safari.
  
  If you switch from `event.currentTarget.closest('form').requestSubmit()` to `event.currentTarget.closest('form').querySelector('input[type=submit]').click()` it will work in both.

**Comment by skipkayhil** [comment] 2022-06-14 02:36
Nice find, looks like `requestSubmit` won't be supported until Safari 16: https://caniuse.com/mdn-api_htmlformelement_requestsubmit

Since this doesn't sound like a bug in Active Storage, I'm going to close this issue

**Closed by skipkayhil** 2022-06-14 02:36 UTC
Labels: activestorage
