### ISSUE TITLE
Asset path should ignore relative URL root for application when using asset host

### ISSUE THREAD

**Issue by dssjoblom** [rails/rails#42588] opened 2021-06-24 12:50 UTC
### Steps to reproduce

1. Configure Rails to use a relative URL root with env variable: RAILS_RELATIVE_URL_ROOT=/subdir
2. Use an asset_host: config.action_controller.asset_host = 'host'

### Expected behavior

asset_path should not include /subdir

For example:

http://host/assets/my_asset

### Actual behavior

asset_path includes /subdir

For example:

http://host/subdir/assets/my_asset

### System configuration

**5.1.7**:
**2.5.5**:

But also reproducible on newer versions. 

### Hacky fix

A work-around is to change the asset_path method so that it checks whether an asset host is used:

```        
        if !defined?(config.asset_host) || config.asset_host.blank? # Added if
          relative_url_root = defined?(config.relative_url_root) && config.relative_url_root
          if relative_url_root
            source = File.join(relative_url_root, source) unless source.start_with?("#{relative_url_root}/")
          end
        end
```

Note that the behavior is fine if asset_host is not defined. In this case, /subdir should/could be added to the asset path. Or maybe it could be an option in both cases? Intuitively, it seems like /subdir is only relevant for reverse proxying the app itself, not for serving assets from a CDN.

### Notes

This was also asked on Stackoverflow many years ago: https://stackoverflow.com/questions/2931528/how-to-make-actioncontrollerbase-asset-host-and-base-relative-url-root-indepen

**Comment by alexcameron89** [comment] 2021-06-24 14:52
Hey @dssjoblom, does this script seem to represent the issue you're seeing?

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

ActionController::Base.asset_host = "host"
ActionController::Base.relative_url_root = "/subdir"

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  include ActionView::Helpers::AssetUrlHelper

  def index
    render plain: asset_path("image.png")
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"

    refute last_response.body.include?("/subdir")
  end

  private
    def app
      Rails.application
    end
end
```

Looking at the documentation, I couldn't tell if this is expected behavior, but [this group of tests in Action View](https://github.com/rails/rails/blob/d4d560bc4b8ba03ef576c766d1561c06f93a2cb2/actionview/test/template/asset_tag_helper_test.rb#L807-L939) seem to imply that it's expected.

Still, we could probably find a solution that allows opting into the behavior you're describing without breaking backwards compatibility.

I'm less familiar with this area of the code so I'll leave room for opinions from other members of the team that have more familiarity here.

**Comment by zzak** [comment] 2021-06-25 10:33
As @alexcameron89 pointed out, this is the intended behavior and we cannot change it.

We could possibly provide an option to skip prepending the relative URL root, but that would require feedback from the core team.

In this case, this behavior is not a bug so I'm closing this issue. Please feel free to [open a feature request](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark) if you have ideas on how to improve things.

**Closed by zzak** 2021-06-25 10:33 UTC
Labels: actionview

**Comment by dssjoblom** [comment] 2021-06-28 06:42
@alexcameron89 @zzak The script does indeed represent the issue, thank you. It is possible that this was intended behavior, but IMHO it's contrary to what you would expect. I might open a feature request at some point if I have more time, but for now, the hack will have to do.
