### ISSUE TITLE
ActiveStorage .attach ignores ActiveRecord record_timestamps

### ISSUE THREAD

**Issue by Baxxx** [rails/rails#38934] opened 2020-04-13 08:20 UTC
### Steps to reproduce

- Create a model with `record_timestamps = false`.
- Add `has_one_attached` relation to the model.
- Call `model_instance.attach(file)`. This will update model's `updated_at`.

Reproduction repository can be found [here](https://github.com/Baxxx/attach_updated_at), please check [relevant commit](https://github.com/Baxxx/attach_updated_at/commit/085c01f7ccf578012a267fc8f1c682cb81ac4a2c).

### Expected behavior
It shouldn't have changed model's `updated_at`.

### Actual behavior
It does change model's `updated_at`.

### System configuration
**Rails version**: Reproduced on both Rails 5 and Rails 6
**Ruby version**: 2.6.5

**Comment by jonathanhefner** [comment] 2020-04-14 04:31
This occurs because `ActiveStorage::Attachment` has [`touch: true`](https://github.com/rails/rails/blob/a4deb637984e4aff7c679f4c5d1eebc789774105/activestorage/app/models/active_storage/attachment.rb#L13).  In essence, this issue is a duplicate of #18811.  I don't believe a consensus was ever reached on that issue, but I can work up a PR if it's desirable.

**Closed** 2020-06-15 18:29 UTC
