### ISSUE TITLE
ActionDispatch Regression between RC1 and RC2...

### ISSUE THREAD

**Issue by sblackstone** [rails/rails#25491] opened 2016-06-23 18:14 UTC
I have a test case that ensures a controller is being properly protected by devise..

```
  test "should require access" do
    c = create(:company)
    request.host = c.entity_domains.first.host_name
    get :listing, params: { :company_id => c.id }
    assert_response :redirect
  end

```

Under Rails 5.0.0RC1 and the 'rails-controller-testing' gem, this test passes.

Under RC2:

```
Error:
CasinosControllerTest#test_should_require_access:
ActionDispatch::IllegalStateError: header already sent
    /Users/sblackstone/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/delegate.rb:85:in `call'
    /Users/sblackstone/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/delegate.rb:85:in `method_missing'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/http/response.rb:44:in `[]='
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/http/response.rb:180:in `set_header'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/http/response.rb:420:in `set_content_type'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/http/response.rb:228:in `content_type='
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal.rb:149:in `content_type='
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal/rendering.rb:126:in `_process_options'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal/streaming.rb:200:in `_process_options'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionview-5.0.0.rc2/lib/action_view/rendering.rb:82:in `render_to_body'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal/renderers.rb:144:in `render_to_body'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/abstract_controller/rendering.rb:26:in `render'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal/rendering.rb:36:in `render'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc2/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
    /Users/sblackstone/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc2/lib/active_support/core_ext/benchmark.rb:12:in `ms'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc2/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/metal/instrumentation.rb:43:in `render'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/bundler/gems/devise-ac702843ddaa/lib/devise/test/controller_helpers.rb:142:in `_process_unauthenticated'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/bundler/gems/devise-ac702843ddaa/lib/devise/test/controller_helpers.rb:116:in `_catch_warden'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/bundler/gems/devise-ac702843ddaa/lib/devise/test/controller_helpers.rb:33:in `process'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/test_case.rb:629:in `process_with_kwargs'
    /Users/sblackstone/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_controller/test_case.rb:381:in `get'
    /Users/sblackstone/code/agency/test/controllers/casinos_controller_test.rb:28:in `block in <class:CasinosControllerTest>'


```
edit:  full backtrace

### System configuration
Ruby 2.3.1

**Comment by maclover7** [comment] 2016-06-23 18:51
Thank you for reporting! Closing as a duplicate of #25269.

**Closed by maclover7** 2016-06-23 18:51 UTC
Labels: actionpack
