### ISSUE TITLE
Assets pipeline URL helpers generate `/javascript/....` instead of `/assets/....`

### ISSUE THREAD

**Issue by snird** [rails/rails#32464] opened 2018-04-05 10:30 UTC
First, I'm sorry I can't attach an example application, as I couldn't reproduce it outside of my production app.
And even with it, locally, in development everything worked fine, it was just when deploying to production the weird behaviour occurred.

I'm in the process of upgrading a rails 4.2 app to rails 5.0. In development, everything works as expected, but the issue occurs only on deployment:
The assets pipeline compilation works as expected, and all the files are under `/public/assets`, as it always has been.
In the local development machine, loading every page works as expected, and the URLs for all the assets looks like:
`/assets/application.js`
`/assets/application.css`
But when deploying the app, the pipeline compilation still compiles as expected, but the URLs in all pages for the assets now looks like:
`/javascripts/application.js`
`/stylesheets/application.css`

After trying long to find solution in google, it seems like it has happen to some people but there was no solution.
I dived into the rails code, which made me wonder how did it ever work.
Every URL and Tag helper available, from here: https://github.com/rails/rails/tree/5-0-stable/actionview/lib/action_view/helpers
are using the `compute_asset_path` method in the end. https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/helpers/asset_url_helper.rb#L192
And this method, determines the path by the `type` of the asset, generating `/javascripts/..` for script etc'.
But all comments of the function say that is should generate `/assets/...` for everything.
(And I did check, it is the same code for rails 4.2.. it didn't change.)

So taking a look at the code did not help.
I feel like I'm missing something obvious. Can someone help me with a pointer?

**Comment by snird** [comment] 2018-04-05 11:02
So I have found that `compute_asset_path` is override by Sprockets own method. But it fallbacks to the original  (or completely skips Sprockets implementation..) in my deployed app. So it is some environmental thing that causes this fallback.
Maybe just a warning I missed somewhere.

**Comment by pixeltrix** [comment] 2018-04-05 12:29
@snird I would suggest running your app locally in production mode and then trying to debug that way - sounds like the asset pipeline could be disabled in production so check your asset config using [RailsDiff][1] to compare versions since you're upgrading.

I'm going to close this since it's almost certainly not a bug in Rails, if you find anything to suggest otherwise I'm happy to re-open.

[1]: http://railsdiff.org

**Closed by pixeltrix** 2018-04-05 12:29 UTC
