### ISSUE TITLE
 Intergration test HTTP verb method as: :json argument error.

### ISSUE THREAD

**Issue by zw963** [rails/rails#26407] opened 2016-09-06 15:43 UTC
### Steps to reproduce
Following code is work well as expect.
```ruby
get api_v1_search_url(as: :json), params: {q: '手机'}

# get params object from controller
# <ActionController::Parameters {"q"=>"手机", "as"=>"json", "controller"=>"api/v1/search", "action"=>"index"} permitted: false>

```

But if change to following form, it not worked.
```ruby
get api_v1_search_url, params: {q: '手机'}, as: :json

# error params object
# <ActionController::Parameters {"{\"q\":\"手机\"}"=>nil, "controller"=>"api/v1/search", "action"=>"index", "format"=>"json", "search"=>{}} permitted: false>
```

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.2.4

**Comment by prathamesh-sonpatki** [comment] 2016-09-06 17:21
Can you create an executable test script using https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb which reproduces the issue?

Thanks!

**Comment by zw963** [comment] 2016-09-07 05:17
Hi, I can reproduce exactly in my project, But I could not reproduce  in
with ``action_controller_gem.rb``.

Following is basically all the relative code written in my code. two form params output
is same as expect.

https://gist.github.com/23418b7f702b1b4c18f37b5ea568ca76

But the `params`  is different with all the above result from my project.

```
<ActionController::Parameters {"params"=>{"q"=>"手机"}, "controller"=>"api/v1/search", "action"=>"index", "format"=>"json"} permitted: >
```

So, I think it could not equal to my case in my project.
 
Thanks.

**Comment by zw963** [comment] 2016-09-15 12:18
I occur this bug again in my code which use as: :json.

I want to know how to help find out this bug is where when I
occur those code again.

**Comment by prathamesh-sonpatki** [comment] 2016-09-15 12:40
@zw963 You can try removing extra code and also removing extra gems in the gemfile to see if the issue is reproducible or not. You can basically try to go close to the `action_controller_gem.rb` template as much as possible. So that we will come to know what is causing this issue.

I suspect it might be related to a 3rd party gem as it is not reproducible by using `action_controller_gem.rb` :)

**Comment by zw963** [comment] 2016-09-15 13:17
Thanks, I will try it as soon as possible, 
I suspect it caused by following gem.

https://github.com/thoughtbot/shoulda-matchers

**Comment by rafaelfranca** [comment] 2016-09-15 13:39
Closing since it is not a rails bug.

**Closed by rafaelfranca** 2016-09-15 13:39 UTC
Labels: actionpack
